### ISSUE TITLE
No file extension when downloading files from artifacts web-interface

### ISSUE THREAD

**Issue by maria-korosteleva** [wandb/wandb#1167]
`wandb --version && python --version && uname`

* Weights and Biases version: 0.9.3
* Python version: 3.6.10
* Operating System: Win10 
* Browser: Chrome

### Description

When I try to download a file from artifacts web-interface to my computer, it gets loaded with some hash instead of a name with no file extension, e.g. "dc9067a141a0788057af18ba7033cb39". 
This means that I need to do an extra step to rename the file in order to open it (kind of annoying).

Screenshot with the download button clicked:
![image](https://user-images.githubusercontent.com/6837635/88136551-7611fa00-cc24-11ea-95e9-a2f53a7688fa.png)

I suspect the issue is related purely with the downloading from web:
* I can see that all files are uploaded with correct names and that files extensions are correctly recognized, e.g. Netron launches when I try to view .pth file in web-interface.
* I don't have any problem with filenames when downloading with Python API

**Comment by vanpelt** [comment]
Hey @maria-korosteleva we're working on improvements to the storage layer of artifacts that will address this issue.  We're currently storing the data as content addressable which is the file name you're seeing.  As mentioned in python we're able to rename the file after downloading we'll look into doing this in the UI as well.

**Comment by ariG23498** [comment]
Hey @maria-korosteleva 
In the past few months we've majorly reworked the CLI and UI for Weights & Biases. We're closing inactivate threads for the time being. Please comment to reopen. :smile:

**Comment by maria-korosteleva** [comment]
The issue is still there, unfortunately

![image](https://user-images.githubusercontent.com/6837635/101238804-bb2a5a80-36f3-11eb-86e7-958aad754343.png)

**Comment by ariG23498** [comment]
I am reopening the issue
Thanks for the reply
CC: @cvphelps

**Comment by maria-korosteleva** [comment]
The problem is still there

**Comment by vanpelt** [comment]
Hey @maria-korosteleva we had to revert our fix for this due to server performance issues.  We're looking into a new fix for this.

**Comment by thanos-wandb** [comment]
Hi @maria-korosteleva thanks for reporting, and we really appreciate your patience and understanding during this long-running issue. This has been now addressed by our engineers, so I will go ahead and close this ticket again. If the issue still persists for you, please let us know and we will be happy to keep investigating.
