### ISSUE TITLE
Allow setting executable via environment variable

### ISSUE THREAD

**Issue by honnibal** [wandb/wandb#1229]
Hey :)

In `_init_headless` there are some comments about using `sys.executable` to execute the subprocess: https://github.com/wandb/client/blob/master/wandb/__init__.py#L305 . It's extremely difficult to cover all the edge-cases with virtualenvs etc, and in fact `sys.executable` isn't always entirely correct.

The particular edge-case I'm hitting is that I containerise my experiments as executable zip files, built using [Pex](https://pex.readthedocs.io/en/stable/). This manipulates the `sys.path` to set up the imports, so just running the `sys.executable` value doesn't recover the "environment". There are other types of edge-cases people can hit with debuggers or IDEs that might be executing Python in strange ways.

I think the best solution is to allow the user to set an environment variable that will control what W&B executes, defaulting to `sys.executable` if unset. 

(Incidentally, it's easy enough to work around in the meantime: I've just made sure `wandb` is importable outside of the PEX, so that I don't need to change the `sys.executable`.)

Thanks, I'm having fun exploring the tool so far :)

**Comment by cvphelps** [comment]
Hi there, this is a good feature request for the client. We've added it to the backlog.
