### ISSUE TITLE
Legend does not work for user's attributes 

### ISSUE THREAD

**Issue by berlino** [wandb/wandb#1351]
Hi, there

  I found that the legend for plotting does not work for user's attributes, and only works for pre-defined attributes like name, id, datecreated. Here is the screenshot of the issue, where I try to use the attribute 'args.dropout' as the legend, but it didn't show up.

  I'm wondering if it's a bug or it's not supported yet. Thanks! 

![Screenshot 2020-10-12 at 20 16 54](https://user-images.githubusercontent.com/2403596/95782781-5db3f780-0cc8-11eb-90bc-e642eff66e53.png)

**Comment by tyomhak** [comment]
Hey @berlino , I think it should work for configs that are not multileveled, meaning that if your config was not 'args.dropout', but just 'dropout' it should work.

I'm filing an internal ticket to support your case too.

**Comment by ClaraBing** [comment]
Hi, may I ask if this is fixed? Thanks!
