### ISSUE TITLE
overrride files with wandb.save

### ISSUE THREAD

**Issue by gismo07** [wandb/wandb#1372]
During training, we are saving a snapshot of the best model and upload the snapshot to wandb.

```python

if best:
   saveSnapshot("./snapshot.onnx")
   wandb.save("./snapshot.onnx")
```

However, only the first generated snapshot is available on wandb. I assume that wandb checks if this file already exists and does not overwrite it.

Is there any option to enable overriding?

**Comment by gismo07** [comment]
I've tested it with a simple txt file.
It seems, that the content of the file is updated on wandb like expected, only the timestamp is not updated

**Comment by ariG23498** [comment]
Hey @gismo07 
Would you let us know whether you face the same issue? We have had some upgrades recently to take care of some issues.

**Comment by savvaki** [comment]
@vanpelt I will investigate using the "now" policy. It is quite a common use case to resume runs and update the logged files on wandb accordingly. Thank you

**Comment by sydholl** [comment]
Hi @savvaki, we wanted to follow up and confirm if you were still experiencing this issue?

**Comment by savvaki** [comment]
Hi @sydholl, as far as I am aware, it seemed like no one was intending to update the timestamps issue. So I assume that the message I sent earlier still applies: using `wandb.save("filename", policy="now")` the file gets overwritten as expected but the timestamp is not updated.

**Comment by sydholl** [comment]
Thank you. We'll continue tracking this issue and update you when we have a fix.
