### ISSUE TITLE
Overwriting old history

### ISSUE THREAD

**Issue by fgvbrt** [wandb/wandb#1395]
Is it possible to overwrite old history with wandb. I have use-case, when my experiment diverged and I lowered learning rate and used older checkpoint to restart experiment, but wandb doesn’t overwrite history and shows me this warning:
```WARNING Adding to old History rows isn't currently supported.```

I was wondering maybe there is flag to overwrite old history (didn't find in documentation)? If there is no such flag, is it possible to add this as feature request?
Thank you in advance!

**Comment by vanpelt** [comment]
Hey @fgvbrt unfortunately the fundamental design of our current history store is immutable.  We're currently working on a new history implementation that should support this use case but it's not likely to be completed until early next year.  In the meantime, you can update the final value of any metrics logs with:

```
api = wandb.Api()
run = api.run("username/project/run_id")
run.summary.update({"key": value})
```

**Comment by vanpelt** [comment]
@cinjon unfortunately we do not support adding new history metrics to historic runs.  The best thing to do would be to use our public api to pull down the old metrics and create a new run with all of the metrics and checkpoints logged.

**Comment by rubencart** [comment]
I have a similar use case: I'd like to add new metrics or rename old ones in the histories of my runs, so I can make plots and charts of these metrics. Still not possible?

**Comment by vanpelt** [comment]
You can add metrics to history by resuming a run, but modifying historic metrics in history still isn't officially supported.

**Comment by Fed03** [comment]
👍

**Comment by aidanjdonohue** [comment]
Hi @collinmccarthy, if the runs are part of the same project, it should be as simple as adding the new key to the x axis field of your chart.

**Comment by KennethEnevoldsen** [comment]
Is there any update on whether it is possible to updating the run history?

**Comment by tcotte** [comment]
On documentation, it's written : 
"Logging nested metrics is encouraged and is supported in the W&B UI. If you log with a nested dictionary like wandb.log({"train": {"acc": 0.9}, "val": {"acc": 0.8}}), the metrics will be organized into train and val sections in the W&B UI.
wandb keeps track of a global step, which by default increments with each call to wandb.log, so logging related metrics together is encouraged. If it's inconvenient to log related metrics together calling wandb.log({"train-loss": 0.5}, commit=False) and then wandb.log({"accuracy": 0.9}) is equivalent to calling wandb.log({"train-loss": 0.5, "accuracy": 0.9})."

https://docs.wandb.ai/ref/python/run

**Comment by Natithan** [comment]
Just to add that I could also use this feature!

My specific case is that I want to show some metric y for x-axis=0 (so e.g. wandb.log({'y': .359, 'x': 0}), but have a logarithmic x-axis.
In past runs, I logged this as x-axis-value=.1 ({'y': .359, 'x': 0.1}), in present runs I use x-axis-value=.5 (as this happens to be more legible for my case).
For easy comparison to past runs, I would want to overwrite the past runs value to use .5 instead of .1.
It seems like a shame to need to rerun the past experiments for this, when all it should take is a simple edit in wherever this value is stored.

**Comment by collinmccarthy** [comment]
Maybe I'm missing some context here, but if we're just talking about resuming _and_ you have full control over how the Wandb API is used, you can just never log the `step` explicitly and Wandb will auto-increment. Then if you also log another x-axis value like `iter` you can use this as your x-axis and you'll see both the old values and the new values overlaid on top of each other, if that makes sense. Granted this isn't the same as overwriting old history, but it is a workaround for some use cases. 

I still think this feature is necessary to give the user full control over the history for all use cases.

**Comment by dannygoldstein** [comment]
Hi folks, W&B eng here, wanted to give an update on the roadmap for addressing this issue. 

We just added support for a feature we call "run forking" to certain projects (reach out to us at support@wandb.com if you want us to enable this for you). Run forking allows you to call `wandb.init(fork_from=f'[old_run_id]?_step=[fork_step]')` to produce a new run with a new ID, different than `old_run_id`. All of the history logged to `old_run_id` will be visible in `new_run_id` until `fork_step`. History logged to the new run will start from `fork_step + 1`.

While this isn't the exact request from this thread, it is the key missing piece required to provide the feature folks here are asking for, which we are calling "truncated resume." We have a design for truncated resume on our roadmap that uses fork under the hood, and we are expecting to implement this design in Q2 2024. 

Here is a list of upcoming features relevant to the discussion in this thread: 

1. We are going to add a convenience function, `last_run_if_any(step=[fork_step]) -> str` that will allow auto resuming from the previous run. You will be able to use it like this:

```python
wandb.init(fork_from=last_run_if_any(step=500))
```

to fork a new run. If there is no run to resume from the function will return `None`.

2. We are going to add support for resuming an existing run from a previous step, and we are calling this feature "truncated resume". The API will be similar to fork but it will be a different `init()` kwarg, 

```python
resumed_run = wandb.init(resume_from='[old_run_id]?_step=[desired_step]')
```

This will do some metadata shifting (and use forking under the hood) to get the behavior requested in #1395. We have a design for this, and plan to implement in Q2 of this year.

3. We are also planning to allow forking/resuming from other metrics than `_step`, although `_step` is the only allowed one for now. This will be specifiable in the fork/resume string, like:

```python
wandb.init(fork_from='abcdefgh?loss=1`)
```

4. We are planning to deprecate the current `resume=` argument in `wandb.init()` once all of this is done.

**Comment by kopylovvasily** [comment]
But what about adding new metrics to the existing run with their own history? Is this going to be supported at some point? This doesn't require modification of history of the existing metrics, so I guess it should be easier to implement?     

This was on your roadmap 3 years ago (#2723). What is the outcome?

**Comment by thanos-wandb** [comment]
Hi everyone, thank you for your interest in this feature. For future reference, could you please provide us with your wandb usernames if you would like to be added to the [runs rewind](https://docs.wandb.ai/guides/runs/rewind) and/or [runs forking](https://docs.wandb.ai/guides/runs/forking) features? We will proceed with enabling this for you accordingly.

If you prefer not to disclose this information publicly, you can always email us at [support@wandb.com](mailto:support@wandb.com).

**Comment by JohannesTheo** [comment]
I'd like to test this, here is my username https://wandb.ai/theodoridis :)

**Comment by thanos-wandb** [comment]
Thank you, @JohannesTheo, I have added you to the list. I will let you know once our engineers in Infra team have activated it in your entity (it might be early next week).

**Comment by JohannesTheo** [comment]
Awesome :) Let me know if I should report feedback and if so, where.

**Comment by thanos-wandb** [comment]
hi @JohannesTheo I wanted to follow up with you and let you know that we have now enabled this for your account. You should be able to use both [runs rewind](https://docs.wandb.ai/guides/runs/rewind) and [runs forking](https://docs.wandb.ai/guides/runs/forking) features. Feel free to share here any feedback or questions/issues you may have encountered.

**Comment by cinjon** [comment]
Hi @thanos-wandb, I was on this thread a while back and *think* it may be what I'm looking for again. My issue is that I have runs for which I want to write new evals at different checkpoints along the way, corresponding to different steps. For example, I might have a run that was 100 steps and want to add eval metrics to the wandb chart at steps 25, 50, 75, and 100. At the moment, I am struggling because I can't write to a prior step. 

Does run rewind help with this? It *looks* like I might be able to a) retrieve all the metrics for a run, b) loop through it again and rewrite those old metrics, c) when I get to a step with the new eval, then write that in as well and and continue. Is this how you would do it today as well? Thanks!
