### ISSUE TITLE
Model description is not fully displayed on the Model tab in run pages

### ISSUE THREAD

**Issue by maria-korosteleva** [wandb/wandb#1456]
wandb version: 10.0.7
OS: Win 10
Python: 3.8
DL Library: PyTorch 

In the table representation of a model on the Model tab in Run web-interface, values in Type and #Parameters columns are cut and not fully visible (at least when a simple table view of the model is used).

Sometimes I need to refer to some specific settings in the model definition used in a run, and this Tab could be very useful.. when the visibility is fixed =)

### Example run
https://wandb.ai/maria_korosteleva/Test-Garments-Reconstruction/runs/2ssfl3qs/model?workspace=user-maria_korosteleva

**Comment by cvphelps** [comment]
Hi Maria, good point and thanks for the example link! We can make this more obvious but for the moment, if you hover the mouse over the `...` you can see a tooltip with the full list.

<img width="1378" alt="Screen Shot 2020-11-03 at 10 39 27 PM" src="https://user-images.githubusercontent.com/6355078/98077682-8cd00b80-1e25-11eb-921b-c48f7f0fe4ab.png">

**Comment by maria-korosteleva** [comment]
Hi @cvphelps!

Yes, I know the trick too! But some text does not fit into hover-over either (try with feature_extactot + Type cell). I once had to look into the page source to get to the value I wanted to check xD
