### ISSUE TITLE
New Artifact display page: versions of the current artifact are hard to access

### ISSUE THREAD

**Issue by maria-korosteleva** [wandb/wandb#1469]
This change seemed to happen during the last few days. 
On the artifact page, in the column that used to contain the list of versions of the current artifact, there is a list of ALL artifacts of the same type. The currently opened artifact is not highlighted and could as well be on the bottom of the page (the new ones are at the end of the list). 

![image](https://user-images.githubusercontent.com/6837635/98326973-e018a880-2035-11eb-8c87-e96aabe5f28b.png)

Could you make the list of versions of the current artifact easily accessible? At the very least, I want to see my current artifact at the top of the column.

**Comment by cvphelps** [comment]
Hi Maria, great point thank you! We'll flip the order these are sorted by

**Comment by maria-korosteleva** [comment]
@cvphelps Thank you!
This will help in many cases, but it's not a perfect solution either. Imagine I choose to open the artifact from the middle of the list -- then it will still be hard to figure out where to look for versions. 
Why was the previous solution given up on?
