### ISSUE TITLE
CLI: Feature to import metrics from a previous training run directly instead of creating a training run to upload the data

### ISSUE THREAD

**Issue by sff1019** [wandb/wandb#1628]
**Problem or Use Case**
There are times where I would like to visualize and save my training results on wandb that were created without using wandb. However, the only possible way currently is to create a "fake" run and load the table in a for-loop. 

**Suggested Solution**
Add a feature where we can load an external file or dataframe (e.g. csv, JSON, pandas.DataFrame) to wandb directly. Below is a pseudo-code: 

```
import wandb

file_name = '/path/to/csv_file.csv'
wandb.init()
wandb.load_training_results(file_name, type='csv')
```

**Alternatives**
Currently, the only way to do this is by creating a "fake" run and logging the data in a for-loop. This maybe what the new feature might do, but it would be great if there is a function that will do it for us.

**Comment by cvphelps** [comment]
Hi Hanna, thanks for this great suggestion! You're right, the current recommendation is to load your data in via a dummy run. In the future we can build support for a better import tool.

**Comment by kptkin** [comment]
I think this is now supported with the `wandb.Table` functionality so i'm closing this ticket.

**Comment by kptkin** [comment]
The solution we would do is to iterate over the results and log them, which the user is already doing. So it seems like this feature has a reasonable workaround. Closing for now if there is more demand we can re-evaluate.
