### ISSUE TITLE
sklearn plot_summary_metrics doesn't work on text

### ISSUE THREAD

**Issue by barnybug** [wandb/wandb#1632]
I'm trying to use the sklearn plots on a text classification model (`HashingVectorizer` -> `LinearSVC`).

Unfortunately most are disallowed because of this assertion in `test_missing`:
https://github.com/wandb/client/blob/11ee41a3a95a9e3ab6cc69d1137377273c6bdbf6/wandb/sklearn/utils.py#L139

I'm sure some could still be used fine - `plot_summary_metrics` for example, only passes X_train/X_test through to the model, so it'd work fine with text problems:
https://github.com/wandb/client/blob/11ee41a3a95a9e3ab6cc69d1137377273c6bdbf6/wandb/sklearn/__init__.py#L224-L225
(Also the call to `model.predict_proba` is unused)

So a request to relax this condition on plots where relevant.

Thanks! :-)

**Comment by cvphelps** [comment]
Hi Barnaby thanks for your message, agreed this is something we should address in the client. For context, we are transitioning our focus to the Custom Charts feature which is a little more configurable and less restrictive than the legacy sklearn features. Would you like to give Custom Charts a try? 

https://docs.wandb.com/app/features/custom-charts

https://docs.wandb.com/library/log#custom-charts

![image](https://user-images.githubusercontent.com/6355078/103113101-5c7f3f00-4616-11eb-901b-bdc2ccf71d12.png)

**Comment by barnybug** [comment]
Hi, thanks for the pointer towards custom charts.

I've ended up simply using log statements with a few manually calculated metrics, since it's tracking the 'headline' numbers that are most valuable to us between experiments. I think it'd still be really valuable to have the 'out of the box' sklearn features - even just as a demonstration of what can be done. It's a great way to through an existing workflow into wandb and just see it work without having to read into docs to far!

thanks.
