### ISSUE TITLE
New table panel for constructing experiment comparisons

### ISSUE THREAD

**Issue by ashleve** [wandb/wandb#1657]
**Problem or Use Case**
I'd like to be able to compose flexible table comparisons of different runs for different model types and datasets, which could be exported to latex table.

I think this would make it much easier to analise benchamark results, conduct research and write papers.

Ideally, it would be great if I could easily create something like this with graphic interface:
![image](https://user-images.githubusercontent.com/43458894/103482118-2e041f80-4ddf-11eb-9caa-4fbfcf4d3982.png)
(rows are models, columns are datasets)

**Suggested Solution**
I think this could be implemented as a new panel/chart.
So this means user should be able to:
- choose main metric diplayed in table 
- choose from which config field rows should be created (e.g. create new row for each model type, average results if some models had multiple runs)
- choose from which config field columns should be created (e.g. create new column for each dataset, leave cell empty if model wasn't benchamarked on certain dataset)
- export table to latex or csv

**Comment by vanpelt** [comment]
Thanks @hobogalaxy this is a great suggestions and it's already on the roadmap.  We hope to implement this soon!

**Comment by cvphelps** [comment]
Hi there, you can log a text table to wandb in different runs and then visualize it with the "Text Table" option in the UI.

![image](https://user-images.githubusercontent.com/6355078/104075432-0abae500-51d0-11eb-9e9e-e8aa968d4a1a.png)
