### ISSUE TITLE
Allow for optional boolean flags in sweeps

### ISSUE THREAD

**Issue by radkoff** [wandb/wandb#1700]
**Problem or Use Case**
I'm using a yaml-based sweep config to run a script that uses ArgumentParser. Since ArgumentParser doesn't accept bool values, one of the [workarounds](https://stackoverflow.com/a/15008806/11954720) is to do the following:

```
parser.add_argument('--foo', dest='foo', action='store_true')
parser.set_defaults(foo=False)
```

In this scenario the `foo` will be False, unless `--foo` is provided. One could also add a `--no-foo` flag to make both options explicit.

I don't see a way for wandb to sweep optional flags like this. My workaround is to make the arg a string like `parser.add_argument('--foo', type=str, default='false')`, give the sweep `[true, false]` categorical options, and later convert the value like so: `args.foo = args.foo in {'True', 'true'}`. But this is hacky; I don't want to change my arg structure for external tools like wandb, and it's easy to forget the conversion when adding new args.

**Suggested Solution**
A way to configure optional flag configurations for sweeps, where the flag is either present or not

**Comment by radkoff** [comment]
Oh and a related problem: being able to sweep with None arg values. For an arg like `parser.add_argument('--foo', type=str, choices=['bar', 'buzz', None], default=None)`, omitting it results in a None in the parsed Namespace, but that's not possible to include in a wandb search AFAIK.

**Comment by cvphelps** [comment]
Hi Evan, thanks for the good suggestion. We will be returning to Sweeps to start a new batch of improvements next quarter, and I'll include your feedback in that process.

**Comment by RyleeThompson** [comment]
+1, this would be nice

**Comment by trigal** [comment]
i'd say, more than nice :-P

**Comment by talesa** [comment]
Also, heads up, if you try to fix it manually like this
```
args = parser.parse_args()
wandb.init(config=args, ...)
args = wandb.config
args['swept_parameter'] = bool(distutils.util.strtobool(str(args['swept_parameter'])))
```
you get 
`wandb: WARNING Config item 'swept_parameter' was locked by 'sweep' (ignored update).`

**Comment by ameet-1997** [comment]
Hi, are there any updates on this?

**Comment by ameet-1997** [comment]
I just created a new flag called `all_boolean_args` and I pass all the boolean arguments as a comma separated list. For example,
``` bash
--all_boolean_Args do_train,do_eval,do_predict,overwrite_output_dir
```

In the code, I added the following block to handle all the boolean arguments.

``` python
def get_modified_boolean_args(args):
    list_of_bool_args = args.all_boolean_arguments.strip().split(',')

    # Iterate over `list_of_bool_args` and assign arguments accordingly
    for arg_passed in list_of_bool_args:
        setattr(args, arg_passed,  True)
    return args
```

It's also easy to automatically check if an argument is `store_true` or `store_false`.

**Comment by ntudy** [comment]
We can add boolean flags under `command`
https://docs.wandb.ai/guides/sweeps/configuration#command

![20210711212249](https://user-images.githubusercontent.com/20146770/125196919-35285080-e28e-11eb-9e00-775e3acbca5c.jpg)

**Comment by bradgrimm** [comment]
+1 For this feature request.

**Comment by bluch** [comment]
+1 for the feature request

**Comment by armanhar** [comment]
Hey everyone, i've bumped up the priority for this feature request.

**Comment by ngocminhbui** [comment]
+1

**Comment by dangne** [comment]
+1

**Comment by melifluos** [comment]
+1

**Comment by ianbenlolo** [comment]
+1

**Comment by rafi-cohen** [comment]
You can tell `wandb` to call your script without arguments when running the sweep, and then fetch them from `wandb` within the code. This way, if your script is running as part of a sweep, it will use the parameters defined by the sweep. Otherwise, the parameters defined by your `ArgumentParser` will be used. This means you can use boolean values in your sweep configuration, for example:
```yaml
parameters:
  flag:
    values:
      - True
      - False
```

To call the script without arguments, edit your `sweep.yaml` to include:
```yaml
command:
  - ${env}
  - ${interpreter}
  - ${program}
```

To fetch the arguments from `wandb`, do something like this in your code:
```python
args = parser.parse_args()
wandb.init(config=args)
args = argparse.Namespace(**wandb.config)
```

You can also just use `wandb.config` to access your arguments directly. Keep in mind that it's a dictionary, so it behaves differently from `argparse.Namespace` (which is returned by `prase_args`). Namely, to access parameters, you have to use `wandb.config['param']` instead of `args.param`.

**Comment by andreimargeloiu** [comment]
Thumbs up.

**Comment by noamgot** [comment]
+1

**Comment by masonhargrave** [comment]
+1

**Comment by ejmejm** [comment]
+1

**Comment by kleinay** [comment]
+1

**Comment by demdecuong** [comment]
+1

**Comment by Jarvis-K** [comment]
+1

**Comment by neilfendley** [comment]
+1

**Comment by HilaManor** [comment]
+1

**Comment by armanhar** [comment]
Thanks everyone, I'll bump up the priority for the request.

**Comment by youngjae-avikus** [comment]
+1

**Comment by ejmejm** [comment]
+1

**Comment by giuliano-97** [comment]
+1

**Comment by giuliano-97** [comment]
I believe that this has already been fixed according to [the sweep config docs](https://docs.wandb.ai/guides/sweeps/configuration#command). You can force this behavior by passing the `${args_no_boolean_flags}` macro in the `command` section of the yaml config:
```yaml
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args_no_boolean_flags}
```

**Comment by HilaManor** [comment]
> I believe that this has already been fixed according to [the sweep config docs](https://docs.wandb.ai/guides/sweeps/configuration#command). You can force this behavior by passing the `${args_no_boolean_flags}` macro in the `command` section of the yaml config:
> 
> ```yaml
> command:
>   - ${env}
>   - ${interpreter}
>   - ${program}
>   - ${args_no_boolean_flags}
> ```

That's not a fix. If I want to sweep over both "true" and "false" configurations, I need to create 2 separate sweeps...
If I have multiple such flags this becomes quite a hassle

**Comment by HilaManor** [comment]
> I believe that this has already been fixed according to [the sweep config docs](https://docs.wandb.ai/guides/sweeps/configuration#command). You can force this behavior by passing the `${args_no_boolean_flags}` macro in the `command` section of the yaml config:
> 
> ```yaml
> command:
>   - ${env}
>   - ${interpreter}
>   - ${program}
>   - ${args_no_boolean_flags}
> ```

From what I understand, that's not a fix, it's a bypass. You need to create 2 different sweeps to run over "true" or "false" configs.
If you have 4 boolean flags you need to create 8 different sweeps, each with the relevant hyperparameter on or off, which is quite a hassle.

**Comment by giuliano-97** [comment]
@HilaManor I think is a misunderstanding over the meaning of that macro. The docs which I linked clearly state:

> Hyperparameters and their values in the form --param1=value1 except boolean parameters are in the form --boolean_flag_param when True and omitted when False.

To test this, I initialized a sweep with the following config:
```yaml
program: train.py
command:
  - ${interpreter}
  - ${program}
  - ${args_no_boolean_flags}
method: random
metric:
  goal: minimize
  name: Loss/val
parameters:
  use_weighted_random_sampler:
    distribution: categorical
    values:
      - false
      - true
```
and started two agents. The first agent ran the following command:
```bash
2022-08-13 13:55:37,340 - wandb.wandb_agent - INFO - About to run command: python train.py
```
i.e. the boolean flag was not passed, which corresponds to the first hyperparam configuration.
The second agent ran the following command:
```bash
2022-08-13 14:02:23,062 - wandb.wandb_agent - INFO - About to run command: python train.py --use_weighted_random_sampler
```
i.e. the boolean flag was passed, which corresponds to the second hyperparam configuration.

**Comment by HilaManor** [comment]
Nice!
I can see in web archive now that that wasn't there in February 22, so they must have fixed it :D

**Comment by krishpop** [comment]
> To test this, I initialized a sweep with the following config:
> 
> ```yaml
> program: train.py
> command:
>   - ${interpreter}
>   - ${program}
>   - ${args_no_boolean_flags}
> method: random
> metric:
>   goal: minimize
>   name: Loss/val
> parameters:
>   use_weighted_random_sampler:
>     distribution: categorical
>     values:
>       - false
>       - true
> ```
> 
> and started two agents. The first agent ran the following command:
> 
> ```shell
> 2022-08-13 13:55:37,340 - wandb.wandb_agent - INFO - About to run command: python train.py
> ```
> 
> i.e. the boolean flag was not passed, which corresponds to the first hyperparam configuration. The second agent ran the following command:
> 
> ```shell
> 2022-08-13 14:02:23,062 - wandb.wandb_agent - INFO - About to run command: python train.py --use_weighted_random_sampler
> ```
> 
> i.e. the boolean flag was passed, which corresponds to the second hyperparam configuration.

Which version of wandb are you running?  I am finding that this functionality is broken in version 0.13.3, when I try using `{args_no_boolean_flags}` it still produces the boolean-flag=True in the generated command.

**Comment by timmytonga** [comment]
> 

I am having the same issue as @krishpop.

**Comment by luckyhug** [comment]
> > To test this, I initialized a sweep with the following config:
> > ```yaml
> > program: train.py
> > command:
> >   - ${interpreter}
> >   - ${program}
> >   - ${args_no_boolean_flags}
> > method: random
> > metric:
> >   goal: minimize
> >   name: Loss/val
> > parameters:
> >   use_weighted_random_sampler:
> >     distribution: categorical
> >     values:
> >       - false
> >       - true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and started two agents. The first agent ran the following command:
> > ```shell
> > 2022-08-13 13:55:37,340 - wandb.wandb_agent - INFO - About to run command: python train.py
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > i.e. the boolean flag was not passed, which corresponds to the first hyperparam configuration. The second agent ran the following command:
> > ```shell
> > 2022-08-13 14:02:23,062 - wandb.wandb_agent - INFO - About to run command: python train.py --use_weighted_random_sampler
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > i.e. the boolean flag was passed, which corresponds to the second hyperparam configuration.
> 
> Which version of wandb are you running? I am finding that this functionality is broken in version 0.13.3, when I try using `{args_no_boolean_flags}` it still produces the boolean-flag=True in the generated command.

same with me (0.14.0 and 0.15.4): 

train.py: error: argument --resplit: ignored explicit argument 'true'

**Comment by luckyhug** [comment]
> @HilaManor I think there is a misunderstanding over the meaning of that macro (or maybe I misunderstood the problem 😄 ). The docs which I linked clearly state:
> 
> > Hyperparameters and their values in the form --param1=value1 except boolean parameters are in the form --boolean_flag_param when True and omitted when False.
> 
> To test this, I initialized a sweep with the following config:
> 
> ```yaml
> program: train.py
> command:
>   - ${interpreter}
>   - ${program}
>   - ${args_no_boolean_flags}
> method: random
> metric:
>   goal: minimize
>   name: Loss/val
> parameters:
>   use_weighted_random_sampler:
>     distribution: categorical
>     values:
>       - false
>       - true
> ```
> 
> and started two agents. The first agent ran the following command:
> 
> ```shell
> 2022-08-13 13:55:37,340 - wandb.wandb_agent - INFO - About to run command: python train.py
> ```
> 
> i.e. the boolean flag was not passed, which corresponds to the first hyperparam configuration. The second agent ran the following command:
> 
> ```shell
> 2022-08-13 14:02:23,062 - wandb.wandb_agent - INFO - About to run command: python train.py --use_weighted_random_sampler
> ```
> 
> i.e. the boolean flag was passed, which corresponds to the second hyperparam configuration.

Thank you! I tried your config and boolean flag was passed. However, when I tried to use:

command:
  - ${env}
  - python3
  - ${program}
  - ${args}
  - ${args_no_boolean_flags}

The sweep agent generates cmds like:

2023-07-04 15:11:39,570 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python /home/wl/pycharmProjs/timm26Jun/train.py --aa=rand-m8-inc1-mstd101 --cooldown_epochs=5 --cutmix=0.25822087541256544 --decay_epochs=111 --decay_rate=0.7260674682731386 --drop=0.12353318819337074 --drop_path=0.08730710109343917 --epochs=88 --hflip=0.3617019759496862 --lr=0.000589380235758411 --lr_cycle_decay=0.36793792008305903 --lr_cycle_limit=2 --lr_k_decay=1.3756057746005976 --min_lr=2.3103324720177968e-06 --mixup=0.3140822317790255 --mixup_prob=0.4575996877720277 --mixup_switch_prob=0.2850905929098838 --model_ema=False --model_ema_decay=0.6202644377670434 --momentum=0.8929789794238745 --no_aug=True --opt=adamw --patience_epochs=9 --recount=1 --reprob=0.2478798660197045 --resplit=False 


train.py: error: argument --resplit: ignored explicit argument 'False'

**Comment by sydholl** [comment]
This feature was implemented as of April 2024
