### ISSUE TITLE
Execution Queue to run experiments (ablation study) on local servers

### ISSUE THREAD

**Issue by Yura32000** [wandb/wandb#1746]
Execution Queue to run experiments (ablation study) on local and remote servers

Currently, we use W&B paltform as the solution for the epxeriments and  history management along with visualization for our current workflow.
However, under our worklow each resercher develops an experiment on his own computer abd then launches it on local server. 
Since, we have more developers than servers we need a way to mange and synchronize the experiments under W&B echo system.

This feture request is very importatn for us, since without it we lose a lot of development time to synchronize manually experiments on servers.

**Comment by tyomhak** [comment]
Thank you for the request, @Yura32000 . We're looking into it.

@vanpelt do you know if there's a fast workaround for this?
