### ISSUE TITLE
Resuming grid sweep does not launch missing runs

### ISSUE THREAD

**Issue by ExpectationMax** [wandb/wandb#1787]
**Describe the bug**
After removing some runs from a completed grid sweep and resuming the sweep, no new runs are passed to the agents and the sweep goes back into the complete state.

This is in contrast to the documentation which describes that the missing configurations will be launched when the sweep is resumed: https://docs.wandb.ai/sweeps/faq#rerun-grid-search

**To Reproduce**
1. Create a sweep for example:
```yaml
method: grid
parameters:
  batch_size:
    values:
    - 20
program: train.py
```
2. Launch an agents for the sweep
3. Remove the entry of the run when completed
4. Resume the sweep
5. Launch a new agent to run the missing sweep
6. Wandb agent will give the following output
```
wandb: Starting wandb agent :sleuth_or_spy:
2021-02-01 21:32:51,562 - wandb.wandb_agent - INFO - Running runs: []
2021-02-01 21:32:51,915 - wandb.wandb_agent - INFO - Agent received command: exit
2021-02-01 21:32:51,915 - wandb.wandb_agent - INFO - Received exit command. Killing runs and quitting.
wandb: Terminating and syncing runs. Press ctrl-c to kill.
```
7. The state of the sweep will go back to `completed`

**Expected behavior**
The missing sweep should be run by the agent after it has been deleted from the sweep.

**Comment by ariG23498** [comment]
Hey @ExpectationMax 
I tried reproducing the issue and these are my observations :point_down: 

## Code
I have tried out with a very basic example to showcase the features of resuming the grid sweep.
`train.py`
```python
import wandb

# Set up your default hyperparameters before wandb.init
# so they get properly set in the sweep
hyperparameter_defaults = {
    'epoch':2
}

# Pass your defaults to wandb.init
wandb.init(config=hyperparameter_defaults)
config = wandb.config

# Log metrics inside your training loop
metrics = {'custom_metric': config["epoch"]/2}
wandb.log(metrics)
```

`sweeps.yaml`
```yaml
program: train.py
method: grid
metric:
  name: custom_metric
  goal: minimize
parameters:
  epoch:
    values:
      - 2
      - 4
```

## Steps
1. With both the `train.py` and `sweeps.yaml` at hand, I ran the sweep with the command `$ wandb sweep sweeps.yaml`
2. This gives me a command to run the sweep agent.
3. After I run the agent for the sweep my dashboard looks like this
![before_deletion](https://user-images.githubusercontent.com/36856589/106860332-415e1f80-66ea-11eb-8067-8563c79bc62d.png)
Here we can see that both the runs have been logged with `epoch` values 2 and 4.
4. After the agent terminates, I do a `ctrl-c ` in the terminal to close the sweep.
5. I go into the dashboard and delete the run that I want my agent to resume.
![after_deletion](https://user-images.githubusercontent.com/36856589/106860586-9bf77b80-66ea-11eb-9304-e68d83eecde0.png)
Here one can see that the first run has been deleted.
6. After the run has been deleted, I go into the `control-page` of the sweep and click on the `resume` button.
7. With the `resume` button clicked, I run the same sweep agent again from the terminal.
8. After the process terminates this is how my dashboard looks
![run_the_sweep_again](https://user-images.githubusercontent.com/36856589/106860773-dbbe6300-66ea-11eb-980d-0e4f2db4946d.png)

I think the detailed walkthrough would make it feasible for you to combat your issues. Feel free to write in if this does not help you.

**Comment by MBakirWB** [comment]
@jvlmdr, can you please provide a link to your workspace for review. Thanks.

**Comment by MBakirWB** [comment]
@jvlmdr, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by jpcbertoldo** [comment]
Question: if some runs fail or are deleted, is the (grid) sweep supposed to go through them again and relaunch?

**Comment by MBakirWB** [comment]
@jpcbertoldo , depends on the search strategy - if you were using a grid search, yes the agent will create a run for the exact same run configuration (since a grid search is an exhaustive search of your config). bayes and random search sample from a distribution, so there is a probability to run the same config, but for most configs to control a neural network, the chance of you reaching the same config is low - specially if you have a continuous distribution like normal or uniform defined in your config.

**Comment by jpcbertoldo** [comment]
So, for the record, I think there is a bug on that as well.
I launched a grid sweep and, as it was running, I deleted some runs that broke.
As it finished the last combinations it did **not** go back to the ones missing.

**Comment by botcs** [comment]
I bumped into the same issue.

**Comment by puzzler10** [comment]
yeah, this is busted. same experience

**Comment by al-stev** [comment]
Have tested based on original feedback (https://github.com/wandb/wandb/issues/1787#issuecomment-773104274) and this is working as intended.
