### ISSUE TITLE
[Feature] Can I calculate an expression in a more complex way?

### ISSUE THREAD

**Issue by wizard1203** [wandb/wandb#1796]
Can I calculate an expression in a more complex way? 
For example, I want to give different metric expressions to different legends.

**Comment by ariG23498** [comment]
Hey @wizard1203 
If I am getting you correctly you want to plot complex expression from the metrics that you have logged. For that you can look into the `Expression` section of [Line Plot docs](https://docs.wandb.ai/app/features/panels/compare-metrics#settings). You could also look into the `Legends` section of the same page for more info on the
> different metric expressions to different legends

Please feel free to write in if this does not help.

**Comment by cvphelps** [comment]
Hi there, could you describe a little more what you're trying to do, having different expressions in different legends? Could you share a screenshot or example link?

**Comment by wizard1203** [comment]
> Hi there, could you describe a little more what you're trying to do, having different expressions in different legends? Could you share a screenshot or example link?

@cvphelps @ariG23498 

Hi, thanks for replying. 
For one example, I have two lines, A and B. And I want to scale axis x of A with ratio 2, and scale axis x of B with ratio 5. This scaling ratio is not recorded in experiment config or results. It seems that I must download data and write other codes to do this.

**Comment by StellaAthena** [comment]
@cvphelps @ariG23498 I am also trying to do this and have found the expression documentation incomprehensible. Some of the stated examples also don’t seem to work?

I have two curves on the same plot and want to scale the x-axis for only one of them.

Alternatively, I am training a transformer model and would like “tokens” to be the x-axis rather than “steps.” Despite the fact that I log the number of tokens and can see this number in the overview, it does not appear to be an option for the x-axis of my plot.

**Comment by aidanjdonohue** [comment]
Hi @StellaAthena , can you share a link to your workspace so I can take a look at things for you?

**Comment by StellaAthena** [comment]
> Hi @StellaAthena , can you share a link to your workspace so I can take a look at things for you?

https://wandb.ai/eleutherai/gpt-thicc?workspace=user-stellaathena

**Comment by aidanjdonohue** [comment]
Hi @StellaAthena , I don't see "tokens" as a logged metric. One thing you can do to simply things going forward is to define a metric ahead of time on your run object like this:

```
run = wandb.init()
run.define_metric("tokens", hidden=True) # don't create a plot for "token"
run.define_metric("training/loss", step_metric="tokens")
```

As for your other queries, it would be helpful if you could point me to two specific metrics on a specific run that you'd like me to take a look at.

**Comment by StellaAthena** [comment]
Thank you, I'll look into logging tokens explicitly.
