### ISSUE TITLE
UI Runs Table: Show the max/min of summary metrics in the table

### ISSUE THREAD

**Issue by awsaf49** [wandb/wandb#1846]
When we group some runs we can only see their `mean` or `average` of any particular column, It would be really if we can also see `min`, `max` or `std` of the grouped runs

**Comment by ariG23498** [comment]
If I am getting you correctly, you would want to see the `min`, `max` and `std` with the grouping of runs.
![image](https://user-images.githubusercontent.com/36856589/108027543-5d4db380-7050-11eb-91cf-8514f1b93fff.png)
With the plotted graphs we can indeed do this as shown.

Let us know if this helps you.

**Comment by awsaf49** [comment]
![image](https://user-images.githubusercontent.com/36858976/108035612-58453000-7061-11eb-87d4-c0018be30550.png)
As you can see all the grouped runs are aggregated by `mean` I want to aggregate them by `min` or `max` or `std`

**Comment by tyomhak** [comment]
Hey @awsaf49 , to make sure we're on the same page: you wish to have more control over the resulting value for metrics in the run table after the runs are grouped — to be able to set it to be one of the mean/min/max/std of the grouped runs values. Does that sound right?

**Comment by awsaf49** [comment]
yes

**Comment by Anjum48** [comment]
Hi @tyomhak, it would also be good to have the aggregations independent of the group agg. For example, if you were tracking AUC of 5 folds, you would want to get the max AUC per fold and then take the mean:  
![image](https://user-images.githubusercontent.com/13783303/109973804-bd9b5100-7cf0-11eb-83dc-b10a7d207b31.png)

**Comment by cvphelps** [comment]
@Anjum48 thanks for the feedback. As a workaround, you can set the final values that show up in the table from our Public API, so after your run has finished you can set the summary to the max or min, instead of the final value:

This example sets the accuracy of a previous run to 0.9. It also modifies the accuracy histogram of a previous run to be the histogram of numpy_array.
import wandb
api = wandb.Api()

run = api.run("<entity>/<project>/<run_id>")
run.summary["accuracy"] = 0.9
run.summary["accuracy_histogram"] = wandb.Histogram(numpy_array)
run.summary.update()

**Comment by jakobwowy** [comment]
Hello @cvphelps, I have the same request. And the workaround is not working for me because I dont want to overwrite the summery of the previous run for documentation purpose. Any other workaround to show the max value of a summery field of a group?

**Comment by ramit-wandb** [comment]
Hey @jakobwowy,

I wrote a small script to create the `max`, `min` & `std` values for your groups. It is a little bit of a hack, but it gets the job done:

```python3

import wandb
import numpy as np

from collections import defaultdict

ENTITY = '<entity>'
PROJECT = '<project>'
METRIC_NAME = '<metric>'

api = wandb.Api()

runs = api.runs(f"{ENTITY}/{PROJECT}")

groups = set()
metrics = defaultdict(list)

for run in runs:    # Get all individual group names
    groups.add(run.group)

for run in runs:
    metrics[run.group].append(run.summary[METRIC_NAME])

maximums = {}
minimums = {}
std_devs = {}

for group in metrics.keys():    # Aggregate each group individually
    maximums[group] = np.max(metrics[group])
    minimums[group] = np.min(metrics[group])
    std_devs[group] = np.std(metrics[group])

for run in runs:    # Update runs
    run.summary[f"{METRIC_NAME}_max"] = maximums[run.group]
    run.summary[f"{METRIC_NAME}_min"] = minimums[run.group]
    run.summary[f"{METRIC_NAME}_std"] = std_devs[run.group]

    run.summary.update()
```

You are going to have to edit the `ENTITY`, `PROJECT` and `METRIC_NAME` variables, and it should create the desired aggregations on your run table like so: (here `METRIC_NAME = "value"`)

<img width="360" alt="Screen Shot 2022-02-18 at 1 50 59 AM" src="https://user-images.githubusercontent.com/93002515/154564527-d877a5f3-0b51-4e10-a9a7-6f05bf43a2dd.png">

A proper solution of this through our backend is planned for the future, but this script should hopefully get the desired result for now. Please let me know if I can assist you with anything else here.

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
Hey @jakobwowy,

I wanted to follow up here and ask if the above solution worked for you. Please let us know if we can be of further assistance.

Thanks,
Ramit

**Comment by jakobwowy** [comment]
@ramit-wandb 
Your workaround works fine. Thanks
