### ISSUE TITLE
Avoid returning None on init

### ISSUE THREAD

**Issue by agrinh** [wandb/wandb#1899]
It's a bit inconvenient that that init may return `None`, especially since I have to manually check before using `with` when using mypy. Looks like the following TODO is an intended fix for that, considering how easy of a fix it'd be I'd love to see it happen.

https://github.com/wandb/client/blob/7cc4dd311f3cdba8a740be0dc8903075250a914e/wandb/sdk/wandb_init.py#L742

**Comment by tyomhak** [comment]
Hey @agrinh , thanks for the request. I'm bringing this up with the team, to see if we could include a fix for this in the upcoming release.

**Comment by d-miketa** [comment]
Seconding this feature request.

**Comment by kptkin** [comment]
@d-miketa and @tyomhak we return None in case of a failure. Would a DummyRun or a DisabledRun would more of an api you are looking to see?

**Comment by kptkin** [comment]
issue seems to be fixed. If it is still an issue please provide a repro
