### ISSUE TITLE
[CLI] wandb.init() hanging in the multiprocessing.Process()

### ISSUE THREAD

**Issue by AntivistRock** [wandb/wandb#2092]
**Description**
wandb.init() hanging in the `multiprocessing.Process()` while the sweep

**Wandb features**
* [wandb Cross-Validation example](https://github.com/wandb/examples/tree/master/examples/wandb-sweeps/sweeps-cross-validation)
* [simpletransformers](https://simpletransformers.ai/) integration
* wandb.init()

**How to reproduce**
1. There is the [notebook](https://colab.research.google.com/drive/1RkNeXFuiXS_h5HFmy3Eeek2-MJf2HgVM?usp=sharing).
2. Run all cells, but don't forget to restart the env after simpletransformers installation
3. You will see that nothing happens after sweep initialization

**Environment**
- OS: Linux-4.19.112+-x86_64-with-Ubuntu-18.04-bionic
- Environment: Google Colab
- Python Version: 3.7.10

I am trying to make Cross-Validation based on wandb Cross-Validation example for simpletransformers hyperparameter tuning using Colab.

But there is a hanging problem at the moment of calling 
```
run = wandb.init(
        group=worker_data.sweep_id,
        job_type=worker_data.sweep_run_name,
        name=run_name,
        config=config,
    )
``` 
in the `train()` function, which is in the `multiprocessing.Process()`  according to the official example.

Docs says something about it

> Hanging at the beginning of training
If launching the wandb process hangs, it could be because the wandb multiprocessing is interfering with the multiprocessing from distributed training. Try setting the WANDB_START_METHOD environment variable to "thread" to use multithreading instead.

but either it doesn't help or I doing something wrong by adding `settings=wandb.Settings(start_method="thread")` to the code above and to the `wandb.init()` in `main()`.

I tried to run wandb CV example and it finished without any problems.
Also I tried to run my script similar to official example (using _.yaml_ file with my parameters and _.py_ with scrip) and it looked like script passing everything from `wandb.init()` to end in `train()` function.

I also found #1771 seems similar to this problem.

**Comment by ariG23498** [comment]
Hey @AntivistRock 
Thanks for the ticket!
We will track it internally. The colab notebook will help a lot in the process 😄

**Comment by AntivistRock** [comment]
@JohnnyC08, I found the solution for KFold problem. It is not 100% great, but it is good according to the documentation. In fact CV example requres to start sweeps by these commands:

> wandb sweep sweep-cross-validation.yaml
> wandb agent SWEEP_ID

So, you need to make your oun `.yaml` file with your hyperparameters and name of your `.py` script with sweep code (it is easy enough, there is the [example](https://github.com/wandb/examples/blob/master/examples/wandb-sweeps/sweeps-cross-validation/sweep-cross-validation.yaml)), then add script and `.yaml` file to Colab, run the first command in command prompt. The output will be the sweep_id. Copy and paste it into the second command, run it too and enjoy.

That's worked for me!

**Comment by AntivistRock** [comment]
> I'm having this issue too when trying to a parallelize my folds across two processes. Also, the KFold + sweep script also hangs for me in colab.
> 
> So +1 from me! Hope it can be addressed soon!

Hi again, I published a [repo](https://github.com/AntivistRock/Roberta-Hyperparameter-Optimization-with-Wandb-CV) with my solution, so you can check and easily reproduce it!

**Comment by anmolmann** [comment]
Hey @AntivistRock , we've been working on improving our lib w.r.t handling runs where multiprocessing is involved. [This documentation](https://docs.wandb.ai/guides/track/advanced/distributed-training#wandb-service) includes how to enable the new distributed training service for experiment tracking. You can find how to enable this service and use it in your script from the documnetation link shared before. 
Please let us know if this helps resolving your issue or in case of further queries.

**Comment by anmolmann** [comment]
Hi @AntivistRock, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.
