### ISSUE TITLE
[CLI] sklearn plot_feature_importances does not accept np.array list as attribute type

### ISSUE THREAD

**Issue by dunnkers** [wandb/wandb#2118]
**Description**
The sklearn integration function `plot_feature_importances` fails when using a `feature_importances` attribute of `np.array` type. e.g.

```python
# works
two_features = ['f1', 'f2']
plot_feature_importances(model, feature_names=two_features)

# fails
two_features = np.array(["a", "b"])
plot_feature_importances(model, feature_names=two_features)
```

**Wandb features**
Using `plot_feature_importances` from the sklearn integration.

**How to reproduce**
1. Link to a reproducible script:
[https://colab.research.google.com/drive/1trdc-WHvhuA5UbPvG7S7jQhO0awOLQd2?usp=sharing](https://colab.research.google.com/drive/1trdc-WHvhuA5UbPvG7S7jQhO0awOLQd2?usp=sharing)
2. Run the script: the last cell will fail.

**Environment**
- OS: Mac OS 10.15.7 Catalina / Linux
- Environment: Google Colab
- Python Version: 3.7.10
→ bug should be existant in any environment, however.

**Comment by ariG23498** [comment]
Hey @dunnkers 
Thanks for the issue and the PR.
I am tagging @raubitsj here who could guide you in the process. 😄

**Comment by kptkin** [comment]
Tried the colab the issue seems to be resolved (couldn't reproduce).
