### ISSUE TITLE
[Feature] Read files with .yml extension same way wandb handle .yaml files

### ISSUE THREAD

**Issue by stasbel** [wandb/wandb#2184]
**Is your feature request related to a problem? Please describe.**
WanDB doesn't allow to read (and highlight syntax) any file with .yml extension in "Files" section of your run. You can only download it.  

**Describe the solution you'd like**
I want to read .yml files same way I see every .yaml file.

**Describe alternatives you've considered**
...

**Additional context**
I want to be able to read structurally yml files I attach to each of my run.

**Comment by ariG23498** [comment]
Hey @stasbel 
Thanks for the feature request. We will track this internally.

**Comment by kptkin** [comment]
@stasbel i just tried it and it see that a file  with .yml extension is highlighted correctly. I'm closing this issue, if you still experiencing this issue please feel free to open this issue or a new one.
