### ISSUE TITLE
[CLI] Can't save model, h5py returned error: 

### ISSUE THREAD

**Issue by ayulockin** [wandb/wandb#2192]
**Description**
W&B shows this warning when a Keras model uses a layer that's not part of Keras sequential or Functional APIs. 

My model definition is:
```
def CommonLitModel():
    # Input layers
    input_ids = Input(shape=(CONFIG['max_token_length'],), dtype=tf.int32, name="input_ids")
    attention_mask = Input(shape=(CONFIG['max_token_length'],), dtype=tf.int32, name="attention_mask")
    
    # Transformer backbone to extract features [CAUSE OF ERROR]
    sequence_output = transformer_model(input_ids=input_ids, attention_mask=attention_mask)[0]
    clf_output = sequence_output[:, 0, :]
    
    # Dropout to regularize 
    clf_output = Dropout(0.1)(clf_output)
    
    # Output layer with linear activation as we are doing regression. 
    out = Dense(1, activation='linear')(clf_output)
    
    # Build model 
    model = Model(inputs=[input_ids, attention_mask], outputs=out)
    
    return model
```
Since I have used a transformer model which is not part of sequential or functional API, serializing the model using the `h5` format is potentially throwing this warning. 

**Wandb features**
I am using Keras `WandbCallback()`.

**How to reproduce**
[Kaggle kernel](https://www.kaggle.com/ayuraj/transformer-baseline-with-tf-keras-and-w-b?scriptVersionId=62683116) to reproduce. 

**Environment**
Kaggle environment.

**Potential Fix**
Upon investigating the `client/wandb/integration/keras/keras.py` file there's a [line](https://github.com/wandb/client/blob/94c226afc4925535e6301c9bc9b9ee36061d99d4/wandb/integration/keras/keras.py#L354):
`self.filepath = os.path.join(wandb.run.dir, "model-best.h5")`

Since custom layers can't be serialized using `h5` format if the line is modified such that,
`self.filepath = os.path.join(wandb.run.dir, "model-best")`

Keras will save the model in the default [SavedModel format](https://www.tensorflow.org/guide/keras/save_and_serialize#savedmodel_format). However, it will create a directory with the name `model-best` with multiple files within.

**Comment by ariG23498** [comment]
Hey @ayulockin 
Thanks for the clean code and the issue. We will try to track it internally.
