### ISSUE TITLE
[App] Team admin can set himself to Member and lock out team Admin settings (even when he is the only person in team)

### ISSUE THREAD

**Issue by jaideepheer** [wandb/wandb#2285]
**Describe the bug**
Create a new team.
Goto team settings page.
In the invite text box, write your own username and select 'Member' in the dropdown.
Click Invite.
Weep and cry.

**Expected behavior**
Don't let team Admins be this stupid.

**Additional context**
I did this to my team and now I want to fix it, pls help.

**Comment by tyomhak** [comment]
Hey @jaideepheer , thank you for reporting this. We'll get this fixed. 
Can you please write in through the web app chat-box with the your team details, so we could fix your case directly?

**Comment by vanpelt** [comment]
Hey @jaideepheer if you give us the team name and your username our support staff can fix your issue.  We'll also be tracking this bug to make the UI more clear here.

**Comment by jaideepheer** [comment]
Hi, I have provided my details via the chat app. I'll provide them here too,

My username is: jaideep (https://wandb.ai/jaideep)
The team with the problem is: https://wandb.ai/teams/rcai

I created another team to reproduce this and have ended up in the same
situation there, https://wandb.ai/temp_team

I have created an issue on GH for the same:
https://github.com/wandb/client/issues/2285

**Comment by vanpelt** [comment]
Just fixed the `rcai` team!

**Comment by jaideepheer** [comment]
Yes `rcai` is fixed, thanks. 
Could you also fix [`temp_team`](https://wandb.ai/temp_team), same issue.

**Comment by vanpelt** [comment]
Done

**Comment by jaideepheer** [comment]
Thank you.
Should I close this issue?

**Comment by vanpelt** [comment]
Let's keep it open so we can prevent users from getting into this state in the future.

**Comment by metemadi** [comment]
whoops.. did this to the "hit" team.. does someone mind fixing? thank you!

**Comment by vanpelt** [comment]
@metemadi you're all good now.
