### ISSUE TITLE
[Feature] OR logic for Filters

### ISSUE THREAD

**Issue by richardrl** [wandb/wandb#2315]
**Is your feature request related to a problem? Please describe.**
I find myself needing an OR operation between filters all the time. It's very hard to select runs otherwise.

**Describe the solution you'd like**
In the filter screen, if I click checkmarks next to two filters, it does an AND operation between the filters. But for example, I want to find all runs that are "status=running" or "name=dog". This is excruciating to do right now in the current interface.

**Describe alternatives you've considered**
A simple line of logic to allow OR logic between filters.

**Additional context**
![image](https://user-images.githubusercontent.com/5181990/123056940-67ecd080-d3d5-11eb-8e18-d783141098b3.png)

Add a UI element that enables OR operations here.

**Comment by tyomhak** [comment]
Hey @richardrl , thank you for the feature request! We'll bump up the priority for this feature.

**Comment by richardrl** [comment]
@tyomhak Hi, just wondering if there's any update here, or if there's some other way to accomplish what I want?

**Comment by cvphelps** [comment]
@richardrl if you create a report with multiple run sets in a section, those run sets will operate as "OR". Here's an example from our docs. As you can see, each run set is filtering to a group of runs, which are then displayed above together on the charts.

![image](https://user-images.githubusercontent.com/6355078/126705762-e2a338ac-545e-46f1-8973-5950b179618c.png)

**Comment by cvphelps** [comment]
I'd like to note that we do have this ticket in the backlog, and would like to improve the filter UI to directly support that.

**Comment by richardrl** [comment]
> @richardrl if you create a report with multiple run sets in a section, those run sets will operate as "OR". Here's an example from our docs. As you can see, each run set is filtering to a group of runs, which are then displayed above together on the charts.
> 
> ![image](https://user-images.githubusercontent.com/6355078/126705762-e2a338ac-545e-46f1-8973-5950b179618c.png)

Hi, the problem is I (and I imagine many others) need to do this dozens of time per day, manipulating the report to do it is too time consuming.

**Comment by richardrl** [comment]
> I'd like to note that we do have this ticket in the backlog, and would like to improve the filter UI to directly support that.

Is there any update here? Still hurting for this feature. Very hard to compare new runs with key old runs unless I do a bunch of unnecessary tagging. I should be able to see how the "currently running" runs compare with a few select old runs, without generating a bunch of unnecesssary tags.

**Comment by richardrl** [comment]
@anmolmann Any update? Myself and many other researchers I know are hurting for this future.

**Comment by paulhager** [comment]
Would like to echo how useful this would be!

**Comment by alinafdima** [comment]
Would also really love such a feature, eg. for setting baselines that have entirely different hyperparameters. 
One idea would be to have multiple filter profiles, and only filter out the runs that do not match any of the filter profiles.

**Comment by anmolmann** [comment]
Thanks for the context @alinafdima! I've made an internal note for this!

**Comment by najwalb** [comment]
Not sure if this is a new feature, but using the 'in' and 'not in' operators seems to achieve this purpose now.
