### ISSUE TITLE
[CLI] Wandb patched root_dir does not sync all tensorboard logs

### ISSUE THREAD

**Issue by jzazo** [wandb/wandb#2426]
**Description**
Wandb's patched tensorboard root directory does not sync all events, such as embeddings.
Logged events such as losses are being synced (`tfevents` files). Patch command is run before wandb.init().
The tensorboard tab in the web does not appear either, even if the `.pbtxt` and `.tsv` files are copied manually.

This occurs using both TensorBoardLogger and WandbLogger within pytorch lightning.

**Wandb features**
Tensorboard integration.

**How to reproduce**
```
import os
import pytorch_lightning as pl
import torch
import torch.nn as nn
import torch.nn.functional as F
import wandb
from pytorch_lightning.loggers import TensorBoardLogger, WandbLogger
from torch.utils.data import DataLoader
from torchvision import transforms
from torchvision.datasets import MNIST


class AutoEncoder(pl.LightningModule):

    def __init__(self):
        super().__init__()
        self.encoder = nn.Sequential(
            nn.Linear(28 * 28, 64),
            nn.ReLU(),
            nn.Linear(64, 3)
        )
        self.decoder = nn.Sequential(
            nn.Linear(3, 64),
            nn.ReLU(),
            nn.Linear(64, 28 * 28)
        )

    def forward(self, x):
        return self.encoder(x)

    def training_step(self, batch, batch_idx):
        x, y = batch
        x = x.view(x.size(0), -1)
        z = self.encoder(x)
        x_hat = self.decoder(z)
        loss = F.mse_loss(x_hat, x)
        self.log('train_loss', loss)
        return {"loss": loss, "z": z}

    def training_epoch_end(self, outputs):
        z = torch.cat([output["z"] for output in outputs])
        tb_logger = self.trainer.logger[1]
        tb_logger.experiment.add_embedding(z, global_step=self.trainer.current_epoch)

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=1e-3)


root_logdir = "lightning_logs"
wandb.tensorboard.patch(root_logdir=root_logdir)
wandb_logger = WandbLogger(project="mwe")
tb_logger = TensorBoardLogger(save_dir=root_logdir, name="")
logger = [wandb_logger, tb_logger]

dataset = MNIST(os.getcwd(), train=False, download=True, transform=transforms.ToTensor())
loader = DataLoader(dataset, batch_size=2000)
gpus = 1 if torch.cuda.is_available() else 0
autoencoder = AutoEncoder()
trainer = pl.Trainer(max_epochs=5, logger=logger, gpus=gpus, log_every_n_steps=1, checkpoint_callback=False)
trainer.fit(autoencoder, loader)
trainer.logger[0].experiment.finish()
```

**Environment**
- OS: Linux 20.04
- Environment: wandb local
- Python Version: 3.8.5

**Comment by vanpelt** [comment]
Hey @jzazo currently our hosted tensorboard does not support the embedding plugin.  Is that the only tensorboard information that's missing for you?  Specifying `root_logdir` is only required if you write multiple tfevent files in different sub directories of the `root_logdir`

**Comment by vanpelt** [comment]
@jzazo I was able to get a projector plugin to load, but I had to manually save the files.  The following code should work:

```
for root, dirs, files in os.walk(writer.log_dir):
  for name in files:
    wandb.save(os.path.join(root, name), base_path=writer.log_dir)
```

I still had to choose "PROJECTOR" from the dropdown menu in the upper right corner of the tensorboard interface.  I'll investigate upgrading tensorboard as well as doing this automatically when we know the root_logdir.

**Comment by jzazo** [comment]
Thanks for the proposal! The files uploaded, but the tensorboard interface does not activate. Any way I can trigger the interface?

**Comment by vanpelt** [comment]
@jzazo yeah, you can click the dropdown in the upper right and then select "PROJECTOR".

**Comment by vanpelt** [comment]
If it's still not working for you, send me a link to the run and I can take a look.

**Comment by jzazo** [comment]
This is the run: https://wandb.ai/jzazo/mwe/runs/1gtw23ol
This is the generating code: https://colab.research.google.com/drive/1b4Zzsz7nAnvlp6-x_ZOyPUjXmnv8zoBP

On your wandb.ai the tensorboard tab appears, but projector shows an empty frame.

When running wandb local, the tensorboard tab does not show. 
![image](https://user-images.githubusercontent.com/25750092/126626089-7bf056a8-fc07-441e-8992-ed12450abd59.png)
![image](https://user-images.githubusercontent.com/25750092/126626126-2093e137-d030-4f12-8b8f-7605117e5367.png)

Thanks for your help.

**Comment by vanpelt** [comment]
Tensorboard is not supported when running the wandb/local container.  I was able to load the projector in the wandb.ai run by selecting the "PROJECTOR" value from the dropdown in the upper right:

![image](https://user-images.githubusercontent.com/17/126675874-c4065b4e-989b-4b75-9402-3e896df4ecf9.png)

**Comment by jzazo** [comment]
It didn't work in Firefox, but it did work in Edge! Thanks for checking...
Any way to integrate TB in wandb local?

Should I close this issue as there are similar issues like this one open?

**Comment by vanpelt** [comment]
We can keep this ticket open as it would be great to eventually support this natively.  Regarding tensorboard in wandb/local, it's possible we'll support it in a future release, but only when wandb/local is running in a kubernetes cluster.  The tensorboard service needs to run a seperate docker container which isn't possible from within a normal docker container unless you're running in kubernetes.

**Comment by jzazo** [comment]
Ok, thanks for the clarification.

**Comment by kptkin** [comment]
This issue seems to be resolved. If you still see the issue please feel free to re-open
