### ISSUE TITLE
[Q]wandb.run.define_metric("metrics/mAP_0.5", summary="max") error

### ISSUE THREAD

**Issue by besbesmany** [wandb/wandb#2449]
Sir , I added this line
`wandb.run.define_metric("metrics/mAP_0.5", summary="max") `

after 
`names = ['item'] if single_cls and len(data_dict['names']) != 1 else data_dict['names']  # class names`
in train.py

I got this error

Traceback (most recent call last):
  File "train.py", line 47, in <module>
    from utils.wandb_logging.wandb_utils import WandbLogger, check_wandb_resume
ModuleNotFoundError: No module named 'utils.wandb_logging'

**Comment by vanpelt** [comment]
We would need the full traceback to debug this.  The specific error is saying when `train.py` tried to import `utils.wandb_logging` it couldn't find that module.  This could mean theres a filed named `utils.py` or a directory which doesn't actually have that module.  This specific error has nothing to do with the line you added.  I would verify that after restoring the file to what it was before you added the line it still functions.

**Comment by besbesmany** [comment]
do you mean you will fix `utils.py` sir or should I add something to avoid error that appears??

**Comment by vanpelt** [comment]
No, @besbesmany this is an error in your code.  Unless we have the full traceback we can't know the root cause.  My guess for the root cause was an issue with your python environment or path loading a `utils.py` file that isn't the one the yolov5 library expects.  Please share the full traceback of the error, or a colab that can reproduce it if you want help debugging.

**Comment by besbesmany** [comment]
In fact I don't know how to fix the error I only add this line in train.py
`wandb.run.define_metric("metrics/mAP_0.5", summary="max")`

**Comment by vanpelt** [comment]
Send the full stacktrace and the exact commands you ran.

**Comment by rubencart** [comment]
This might be related. I did not get any errors, but if I run `wandb_logger.experiment.define_metric(metric, summary='max')` (using pytorch-lightning, but `wandb_logger.experiment` returns the current run, so should be the same as `wandb.run.define_metric`), where `metric` is for instance `'Avg_Precision_IoU=0.50:0.95_area=all_maxDets=100'`, the statement seems to have no effect at all (the last value is still being kept in the summary, no max). With `metric` set to `'coco_ap_iou_05-095'`, the statement works and the max value is kept, as expected. I thought it might have to do with the non alphabetical/numerical tokens in the metric name like /, :, =.

**Comment by vanpelt** [comment]
Yeah, that seems likely.  @rubencart can you try `wandb_logger.experiment.define_metric("Avg_Precision_IoU*", summary="max")` and see if that works?

**Comment by besbesmany** [comment]
where I can run this line in yolov5 is it before train.py or put it inside code train.py

`wandb_logger.experiment.define_metric("Avg_Precision_IoU*", summary="max")`

**Comment by vanpelt** [comment]
@besbesmany it would have to be in train.py after the WandbLogger was initialized.

**Comment by besbesmany** [comment]
which parameters we also have like
Avg_Precision_IoU
metrics/mAP_0.5
metrics/recall
metrics/precision
