### ISSUE TITLE
[Feature] Network usage graphs

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/wandb#2492]
Could you add a way to monitor network usage to system metrics? (assuming this hasn't yet been done)

(our old project had to hack around it by [grepping](https://github.com/cybertronai/imagenet18/blob/dev/training/meter.py#L66) /proc/net/dev)

**Comment by tyomhak** [comment]
Hi @yaroslavvb , I believe we do provide network usage by default. You should be able to find it in the _Settings_ panel section, though you might have to scroll through the pages in the section.
<img width="817" alt="Screen Shot 2021-08-04 at 12 16 10 AM" src="https://user-images.githubusercontent.com/16812535/128080360-e1ddb774-b75f-48d7-8f81-ec7f5bef1539.png">

**Comment by elgalu** [comment]
@tyomhak I think the issue with the current Network Traffic usage is that it's cumulative. What would be more useful is to have MBytes/s over time.

**Comment by elgalu** [comment]
Thanks a lot for sharing meter.py under a permissive license @yaroslavvb ! You may want to not only filter the loopback network interface `line.startswith('lo')` but also bond or you'll see double the real bandwidth in some systems, e.g. `INTERFACE_FILTER = re.compile('^(lo|face|bond.+|.+\.\d+)$')`

**Comment by yaroslavvb** [comment]
Indeed, the cumulative usage in current wandb is not directly useful -- instead it should show MB/sec rather than total MB, MB/sec graph can tell if you you are being bottlenecked by network performance.

**Comment by elgalu** [comment]
I took Yaroslav's code and created the [iometrics](https://github.com/elgalu/iometrics#iometrics) pip package.

The easiest way to have MB/sec network/disk metrics end up in WandB is to use PyTorch-Lightning callbacks integration:

```py
from pytorch_lightning import Trainer
# pip install iometrics
from iometrics.pytorch_lightning.callbacks import NetworkAndDiskStatsMonitor

net_disk_stats = NetworkAndDiskStatsMonitor()

trainer = Trainer(..., callbacks=[net_disk_stats], ...)
```

<img id="png_recv_MB_per_sec" width="450" src="https://github.com/elgalu/iometrics/raw/main/docs/img/metrics/network_recv_MB_per_sec.png" />

WandB folks: feel free to go through the Pure-Python implementation and integrate the pieces into the WandB agent. If you find any bugs please let me know:)

**Comment by vanpelt** [comment]
Thanks @elgalu this is really cool!  We'll look into integrating it directly.

**Comment by sydholl** [comment]
This feature has been implemented as of Feb 2023
