### ISSUE TITLE
[App] Hidden legend when viewing the graphs

### ISSUE THREAD

**Issue by loicsacre** [wandb/wandb#2551]
**Describe the bug**
Sometimes, the legend is hidden when visualising the graphs (see the screenshot)

**Expected behavior**
Being able to always see the complete legend without having to display the graph in full screen

**Screenshots**

![Screen Shot 2021-08-17 at 12 09 05](https://user-images.githubusercontent.com/32166486/129727007-8bd081d2-1d4b-4de2-8d0e-7fe7a7566bd6.png)

**Operating System**
 - OS: MacOS
 - Browser: chrome
 - Version: 92.0.4515.131

**Comment by tyomhak** [comment]
Hey @loicsacre , thanks for reporting this.

**Comment by bablf** [comment]
Would love this as well!

**Comment by sydholl** [comment]
This bug was fixed in Sept 2024
