### ISSUE TITLE
[Feature] Any way to only synchronize successful runs?

### ISSUE THREAD

**Issue by lijiaqi** [wandb/wandb#2575]
**Is your feature request related to a problem? Please describe.**
Is it possible to only synchronize **successful runs** when using ```wandb sync --sync-all``` in ```offline``` mode. Generally, we have many directories like ```./wandb/offline-run-xxx```, some are successful runs who return a ```successful``` flag by wandb. However, others are failed runs due to various reasons with returning a ```failed``` flag, or even without a ```failed``` flag (e.g., the program crushed). If we use ```wandb sync --sync-all```, all runs in ```./wandb``` will be uploaded to the online interface, and it is not convenient to delete the failed runs. However, synchronize one by one is time-consuming.

So is it add a function that only automatically synchronizes successful runs?

**Describe the solution you'd like**
A possible solution is we can add a flag like ```--only-success``` to filter  out the directories with ```successful``` results.

**Describe alternatives you've considered**
None

**Additional context**
If any solution already existed, could you please provide more information for it?

**Comment by vanpelt** [comment]
Hey @lijiaqi this is a great feature request.  We'll continue tracking it here, but I don't think we'll be able to implement it in the near future.  A workaround would be a little script that iterated through the run directories and removed any of them that weren't in the state you want by looking at the "wandb-metadata.json" file in the `files` directory.  Here's some sudo code that I haven't tested but should illustrate the idea:

```
import os
import json
import glob

dirs = glob.glob("./wandb/*run-*")
for dir in dir:
  meta = os.path.join(dir, "files", "wandb-metadata.json")
  if os.path.exists(meta): 
    with open(meta) as f:
      state = json.loads(f.read())["state"]
      if state != "finished":
        os.removedirs(dir)
  else:
    print("No metadata in dir: {}".format(dir))
```

**Comment by lijiaqi** [comment]
Thank you for providing an alternative solution. Hope this feature will be implemented in the future.

**Comment by lijiaqi** [comment]
@vanpelt BTW, I found that the auto-detection of "synced" and "non-synced" is not accurate and will fail sometimes. If I don't delete the already synced runs and try to sync the results of the new runs after some new experiments, ```wandb sync --sync-all``` will still try to sync the already synced directories, which will waste time.

**Comment by vanpelt** [comment]
Hey @lijiaqi how specifically does it fail?  By default when we've synced a directory we write a file named `.synced` in the directory.  We'll not attempt to re-sync these directories unless you tell us to with the `--include-synced` flag.  Maybe there's a specific run that is failing to sync and therefore isn't getting the `.synced` file written.  We would need the specific error to debug the issue.

**Comment by lijiaqi** [comment]
Hi @vanpelt 
It seems it never success since I installed ```wandb```... And it seems no ```.synced``` files were written after ```wandb sync --sync-all```.

Here is a testing case:
Environment:  wandb=0.12.0   python=3.7.0

In Picture 1, if I run ```wandb sync```, it shows I have 302 files unsynced. Then I run ```wandb sync --sync-all``` to sync these files, then we get the displays in Picture 2.

After running ```wandb sync --sync-all```, I rerun ```wandb sync``` and it still shows there are 302 unsynced runs. For example, if we check the directory of ```wandb/offline-run-20210823_185436-5kgf1tp8```, we cannot find any file ending with ```.synced```

Picture 1:
![P1](https://user-images.githubusercontent.com/15867915/130660772-bd728489-7d02-4288-9d76-abee5c3a7f7c.png)

Picture 2:
![P2](https://user-images.githubusercontent.com/15867915/130661070-a2fa9c7a-eee6-432e-b766-687328eff6ab.png)

**Comment by vanpelt** [comment]
Hmm, it could be that those runs never "finished" according to our logic.  We check to see that the process exited cleanly to allow someone to sync runs that are currently in progress.  [Here's the logic](https://github.com/wandb/client/blob/master/wandb/sync/sync.py#L290), `finished` will be true if the run itself called `wandb.finish()` or the process that called `wandb.init()` exited.  What is the state of the run in question according to `wandb-metadata.json`?

**Comment by lijiaqi** [comment]
yeah, ```wandb/offline-run-20210823_185436-5kgf1tp8/files/wandb-metadata.json``` exactly showa ```  "state": "running"```. 

It is so weird, since I did call ```wandb.finish()``` after all the logging processes, but it still showed ```running```.

**Comment by nate-wandb** [comment]
@lijiaqi this should be resolved now. Let us know if you are still seeing this behavior when syncing runs in the latest version of `wandb` (0.16.3)
