### ISSUE TITLE
Binary sklearn LogisticRegression and feature importance

### ISSUE THREAD

**Issue by dalgaard** [wandb/wandb#2671]
Hi wandb team,

I am trying to plot the feature importance of a LogisticRegression model for binary classification problem. Then 
`model.coef_.shape == (1, n_features)`
and this check fails :
https://github.com/wandb/client/blob/63a5dd08e72fc20d3fe0eb5d441843870b0ed7f5/wandb/sklearn/__init__.py#L646
(unless we have n_features == 1)

I believe we should (at least) squeeze `importance` before the check and not have the else branch?

/Jens

**Comment by aidanjdonohue** [comment]
Hi @dalgaard this seems reasonable. Let me look into this and get back to you.
