### ISSUE TITLE
[Feature] Is it possible to log additional values once a run is finished?

### ISSUE THREAD

**Issue by gabriel-vanzandycke** [wandb/wandb#2723]
I would like to log a new evaluation metric for all steps of a finished run (based on the checkpoints that I can reload and use to compute the new metric). Is it possible?
I've been through the doc and didn't find a way to do it. I can either modify the summary of a finished run with the `wandb.apis.public.Run` API, or log data on new runs with the `wandb.wandb_run.Run` API.

**Edit:**
Using the `wandb.wandb_run.Run` API, I was able to resume a previous run by specifying `entity`, `project` and `id`. However, the API `log` function doesn't allow non strictly incremental `step` argument.

The workaround mentioned [here](https://github.com/wandb/client/issues/1626#issuecomment-878722263) require to 
- have anticipated this by logging a dedicated `step` value like `epoch` (which fortunately I did)
- update all visualization that use the `step` value to use the `epoch` value instead (which will take me some times :-/)

Would it be possible to enable non-incremental step logging ? I know it can be dangerous (loosing data), but it would be pretty convenient.

**Comment by aidanjdonohue** [comment]
Hi Gabriel, we probably won't allow for non-incremental step logging for the reasons you identified. Those "workarounds" are actually the intended use so we might need to do a better job of documenting this.

**Comment by vanpelt** [comment]
Hey @gabriel-vanzandycke we're actively working on the ability to overwrite existing data especially for usecases like resuming from checkpoints.  We plan to have these interfaces available within the next month or so.

**Comment by gabriel-vanzandycke** [comment]
@collinmccarthy Yes it's similar. We would like to complement the history with additional metrics computed later but doesn't affect previously logged metrics.
I guess it will be possible in the new history being implemented (cfr https://github.com/wandb/client/issues/1395#issuecomment-713172823). Can't wait to have that feature !

**Comment by KennethEnevoldsen** [comment]
Just noting here that updating run history is very much a feature of interest, but it sounds like it is already in the pipeline?
