### ISSUE TITLE
[CLI] VSCode Notebook can't login WandB

### ISSUE THREAD

**Issue by dennisushi** [wandb/wandb#2735]
**Description**
Can't login from within VSCode notebooks. Tried both `!wandb login` and python version.

**Wandb features**

`wandb.login()`, returns False

**How to reproduce**

`wandb.login()` from a local VSCode jupyter notebook (not on Jupyter Server)

**Environment**
- OS: [Linux 18.04]
- Environment: [VSCode Jupyter]
- Python Version: [3.8.7]

**Comment by vanpelt** [comment]
Hey @dennisushi you can always login by specifying your api key in the environment, i.e.

```
%env WANDB_API_KEY=$YOUR_KEY
```

You should be able to run `wandb login` from a regular terminal on that same machine and your vscode kernel will pickup the credentials.  I tried to reproduce and I was able to login fine.  Can you share what messages or output you're seeing?  Also, can you run `!wandb --version` to verify what version of wandb you're using?
