### ISSUE TITLE
[App] Project page table not showing any columns and width not adjustable

### ISSUE THREAD

**Issue by prash-p** [wandb/wandb#2763]
**Describe the bug**
The table on my [project's overview page](https://wandb.ai/prashant-pand3y/uncertainty-bone-seg?workspace=user-prashant-pand3y) is not showing any columns, despite having selected all columns to show. The width of the table is also not adjustable as it used to be, which is causing all my plots to be squished in the right pane. 

Does not seem to be an issue for my other projects.

**Screenshots**

Columns settings:
![image](https://user-images.githubusercontent.com/5707552/137151312-0eed1575-445c-42b8-959e-3954ad5c2e58.png)

Project page overview:
![image](https://user-images.githubusercontent.com/5707552/137151402-351fae75-c7dd-4f81-bcb2-fe31479aa57d.png)

**Operating System**
 - OS: Windows 11
 - Browser Chrome

**Comment by aidanjdonohue** [comment]
Hi @prash-p could you share a link the your project page where this is happening so I can take a look?

**Comment by prash-p** [comment]
@aidanjdonohue I recorded a video to show how I am not able to adjust the name column or table width whether the table is expanded or not. I then show that I can do it in another project. 

https://drive.google.com/file/d/1hUGa0e8lnkuxd9ghi8Em9VQzbPCQesxA/view?usp=sharing
