### ISSUE TITLE
wandb login permission denied[Q]

### ISSUE THREAD

**Issue by xli4217** [wandb/wandb#2770]
Hi, I'm trying to run `wandb login` on the server where I don't have write access to `/tmp`. I get the error `Permission denied: '/tmp/debug-cli.log'`. I tried setting WANDB_DIR but didn't work. Help would be appreciated.

**Comment by xli4217** [comment]
That worked. Thanks a lot!

**Comment by yuvalkirstain** [comment]
I also encountered this issue and solved it by setting a different `TMPDIR`, do you know what can cause this behavior?
