### ISSUE TITLE
[Feature] Automatically delete empty artifact folders

### ISSUE THREAD

**Issue by Wilann** [wandb/wandb#2787]
**Is your feature request related to a problem? Please describe.**
It's tidious to manually delete folders of empty artifacts in the "Artifacts" tab. 

**Describe the solution you'd like**
It would be nice if these folders were deleted automatically.

**Describe alternatives you've considered**
N/A

**Additional context**
Please see this screenshot where all subsequent runs, after the first run, are empty folderes 
![Screenshot from 2021-10-18 13-34-39](https://user-images.githubusercontent.com/40744757/137780137-41e5c890-4781-4ae7-8616-a0ca348c1ab1.png)

**Comment by ranshadmi** [comment]
Is a fix to this issue really implemented?
I'm seeing the same behavior today. Do I need to wait for some time before the empty "folders" are automatically deleted?

**Comment by lesliewandb** [comment]
It's currently not implemented, but I have brought this up with our engineering team again

**Comment by ranshadmi** [comment]
Looks like your bot is a bit confused. Is it open or is it closed...?

**Comment by MitShah-eaton** [comment]
Hi, Is this issue resolved?
