### ISSUE TITLE
[Feature] Delete Hidden Columns 

### ISSUE THREAD

**Issue by Wilann** [wandb/wandb#2788]
**Is your feature request related to a problem? Please describe.**
After changing which parameters are being tracked many times, eventually the "Hidden Columns" section of "Runs" gets quite cluttered. 

**Describe the solution you'd like**
If would be nice if we could remove unused columns.

**Describe alternatives you've considered**
N/A

**Additional context**
See this screenshot how there are 92 hidden columns:
![Screenshot from 2021-10-18 14-53-03](https://user-images.githubusercontent.com/40744757/137789917-64a5e1ba-ba6d-4522-9de5-bbe64bdbe25d.png)

**Comment by armanhar** [comment]
Hey there, thanks for the suggestion. I'll create an internal ticket so that the team can consider adding this option in a future release.

**Comment by Wilann** [comment]
Hey @armanhar, thank you for taking this into consideration. Really appreciate it.
