### ISSUE TITLE
[Q] How to associate run with already uploaded dataset? 

### ISSUE THREAD

**Issue by Wilann** [wandb/wandb#2800]
Hi, 

I'd like to associate a new run with a dataset that's already been uploaded. 

When initializing a run and adding my dataset artifact, it takes quite a long time since its ~50 GB. Also, my dataset hasn't changed from the one on your servers. Is there a way to point a run to that dataset (and its version), so that this association is displayed on the graph view?

**Comment by armanhar** [comment]
Hey Wilson, when you call [use_artifact](https://docs.wandb.ai/guides/artifacts/api#3-use-an-artifact) W&B will find that artifact and mark it as input to the run.
