### ISSUE TITLE
[CLI] Import wandb SDK does not work in Jupyter Notebook on Linux

### ISSUE THREAD

**Issue by kaylolittlejohn** [wandb/wandb#2889]
**Description**
Wandb fails to load sdk.lib

**Wandb features**
Version: 0.7 - 0.12.6 all yield same problem
Code: import wandb

Error:
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-cd35ee5d166e> in <module>
----> 1 import wandb

/userdata/kaylo/anaconda3/envs/voca/lib/python3.6/site-packages/wandb/__init__.py in <module>
     32 from wandb.errors.term import termsetup, termlog, termerror, termwarn
     33 
---> 34 from wandb import sdk as wandb_sdk
     35 
     36 import wandb

/userdata/kaylo/anaconda3/envs/voca/lib/python3.6/site-packages/wandb/sdk/__init__.py in <module>
      5 """
      6 
----> 7 from . import wandb_helper as helper  # noqa: F401
      8 from .wandb_alerts import AlertLevel  # noqa: F401
      9 from .wandb_artifacts import Artifact  # noqa: F401

/userdata/kaylo/anaconda3/envs/voca/lib/python3.6/site-packages/wandb/sdk/wandb_helper.py in <module>
      6 from wandb.errors import UsageError
      7 
----> 8 from .lib import config_util
      9 
     10 

ModuleNotFoundError: No module named 'wandb.sdk.lib'

**How to reproduce**
I am not sure how to reproduce this to be honest. It just happens on a fresh import

After deleting the package in the environment and reinstalling the latest version, I did confirm wandb/sdk/lib is a directory in the installed source code. All other code and packages run as desired.

That being said, I have a separate program using wandb in a separate directory in a large server system, but using the same config and account, and that program runs fine. After running that program, this is when the issue started.

Edit: I've verified that "import wandb" works using Python 3.6 from the command line and it is only via running on jupyter notebook (v6.2.0) that this problem occurs

**Environment**
- OS: Ubuntu 20.04.3 LTS
- Environment: Conda
- Python Version:  3.6

Is this a common bug? This happens when reloading everything from scratch on a fresh build.

**Comment by kaylolittlejohn** [comment]
After deleting the package in the environment and reinstalling the latest version, I did confirm wandb/sdk/lib is a directory in the installed source code.

**Comment by ematao** [comment]
I had the same problem importing wandb from Google Colab.

**Comment by vanpelt** [comment]
We're working on a long term fix, the problem is being caused by the shortuuid library.  If you run the following, importing wandb should work:

```
pip install --force shortuuid==1.0.1
```
