### ISSUE TITLE
[Q] Run ongoing for 1 day 11h and counting - Progress bar for logging artifacts? 

### ISSUE THREAD

**Issue by Wilann** [wandb/wandb#2899]
I'm currently updating my dataset artifact, which is a total of 260 GB - 150 GB of which is new. My run has been in progress for 1 day and 11 hours and is still running. Is there a way to see how much has been uploaded as a percentage, GBs, or anything like that? 

This is quite urgent, as my PC's RAM and Swp are all used (can't even use Chrome, and therefore obviously can't do any development) and I need to restart the PC to free them (have tried various CLI commands but they haven't worked). I'm debating on just stopping this run and setting up another PC to do it, as idle development time is very costly. 

Not sure if this is a question or feature request - apologies if I've used the wrong title. Hoping to get a response soon. Thank you for reading.

**Comment by Wilann** [comment]
I got this error after 1 day and 21 hours:
```
wandb: Waiting for W&B process to finish, PID 28401... (success).
^R
wandb: Network error (TransientError), entering retry loop.
wandb: Network error (TransientError), entering retry loop.
wandb: Network error (TransientError), entering retry loop.
wandb: Network error (TransientError), entering retry loop.
wandb: Network error (TransientError), entering retry loop.
wandb: Network error (TransientError), entering retry loop.
wandb: Network error (TransientError), entering retry loop.
wandb: ERROR Error uploading "/home/wilsonchan/.cache/wandb/artifacts/obj/md5/98/6f90c
2e7560fbd59a5d7912dcc5021": CommError, <Response [400]>
wandb: ERROR Uploading artifact file failed. Artifact won't be committed.
wandb: ERROR Error uploading "/home/wilsonchan/.cache/wandb/artifacts/obj/md5/a2/3f51e
0f482b415407ee848139a626c": CommError, <Response [400]>
wandb: ERROR Uploading artifact file failed. Artifact won't be committed.
```

Here's the associated `debug-internal.log` file: 
[debug-internal.log](https://github.com/wandb/client/files/7504165/debug-internal.log)

I would really appreciate a progress far in the future, and would like to know what happened to this run.

**Comment by vanpelt** [comment]
Thanks @Wilann looking the debug log we're seeing "Temporary failure in name resolution" when trying to upload the files from the artifact.  Is it possible there was some kind of network outage or fault on the machine you were running on?  If you control+C and try again we should only upload the files in the artifact that didn't make it previously.

**Comment by Wilann** [comment]
Hi @vanpelt, for some reason my PC is disconnecting occasionally from the network, but this only occurs with Ubuntu and not my other devices, so I'll have to look into this. 
I see. Does this mean that if I say, have 100 GB to upload, and I manage to upload 40 GB in my first run but it crashes, and upload 60 GB in my second run which succeeds, will it only show in the UI (aka committed) when the second run succeeds?
Regardless, is there any way to show a progress bar for the upload?

**Comment by vanpelt** [comment]
@Wilann yep, that's correct.  We've created a ticket to show a better upload progress bar in the future.

**Comment by Wilann** [comment]
Thank you for confirming @vanpelt - I thought once the run crashes all upload progress is discarded (since the storage used shown in the UI doesn't change). Looking forward to the improved progress bar in the future releases!
