### ISSUE TITLE
Syncing/deleting runs from a sweep

### ISSUE THREAD

**Issue by ianbenlolo** [wandb/wandb#2921]
I'd like to be able to sync or delete all the runs from a sweep (from my local machine) without having to figure out each of their separate id's and deleting one by one. 

Maybe a command `wandb delete sweep [sweepid]` would be nice. 

Thank you.

**Comment by armanhar** [comment]
Hey there, you can use this code snippet to delete the runs programmatically:
`import wandb

api = wandb.Api()

sweep = api.sweep("<entity>/<project>/<sweep_id>")

for run in sweep.runs:
  run.delete()`
