### ISSUE TITLE
[CLI] Wrong exception being thrown when empty config-defaults.yaml file is present in the working dir.

### ISSUE THREAD

**Issue by Dan8991** [wandb/wandb#2935]
**Description**
When wunning wandb.init() with an empty config-defaults.yaml file in the working directory a non informative error is thrown.
By looking at the code in the anaconda environment folder what looks to be happening is that the file is considered as a valid config file but then when loading the yaml info None is returned by the loading function which results in an exception being thrown later.

**Wandb features**
wandb.init()

**How to reproduce**
```
conda create --name test
conda activate test
conda install -c conda-forge wandb
python
import wandb
wandb.init()
```
**Environment**
- OS: Ubuntu 18.04.6
- Environment: Anaconda
- Python Version: 3.9.7

[test.zip](https://github.com/wandb/client/files/7562809/test.zip)

**Comment by aidanjdonohue** [comment]
Hey @Dan8991, I agree that we could have a better error message. I'll file a ticket for this.
