### ISSUE TITLE
[CLI] Permission denied in middle of run

### ISSUE THREAD

**Issue by zplizzi** [wandb/wandb#2936]
I got the error:

```
|2021-11-16 09:47:25.064 | INFO     | opt     :generally:computronium.utils:run_local_command:109: # << #     if not check_retry_fn(e):
|2021-11-16 09:47:25.065 | INFO     | opt     :generally:computronium.utils:run_local_command:109: # << #   File "/home/user/.conda/lib/python3.9/site-packages/wandb/util.py", line 821, in no_retry_auth
|2021-11-16 09:47:25.065 | INFO     | opt     :generally:computronium.utils:run_local_command:109: # << #     raise CommError("Permission denied, ask the project owner to grant you access")
|2021-11-16 09:47:25.065 | INFO     | opt     :generally:computronium.utils:run_local_command:109: # << # wandb.errors.CommError: Permission denied, ask the project owner to grant you access
Epoch 6723:  84% 37/44 [00:21<00:04,  1.70it/s, loss=-0.895, v_num=exac, val/loss=-.897]wandb: ERROR Internal wandb error: file data was not synced
```

in the middle of a run (after running for a couple of days), and the run shut down. I'm not logging to a networked drive or anything, as I saw was mentioned in a different issue.

I'm running with wandb version: '0.10.31'
and pytorch-lighting: git+https://github.com/wandb/pytorch-lightning.git@wandb-service-attach

I was logging a lot of data, is it possible I hit some sort of per-run data cap?

**Comment by aidanjdonohue** [comment]
Hi @zplizzi, there are a few things that could be going on. There isn't a per run storage limit but your account may be over it's storage limit. You can check your storage at wandb.ai/usage/<your-username>. Additionally, there your version of wandb is fairly old (current version is 0.12.6) so it's possible that could be related to the issue.

**Comment by vanpelt** [comment]
Hey @zplizzi this was likely related to a google cloud outage yesterday.  Normally we just keep retrying errors, but the outage actually caused the load balancer to return 404 error codes which we don't retry 🙃 .  You should be able to run `wandb sync wandb/run-XXX-XXXX` to get all the data synced up to the server.

**Comment by zplizzi** [comment]
Gotcha. You might also want to make these kinds of errors not kill the whole run - I would rather wandb shut itself off but let my run continue so that I can then manually sync the data later than have my whole run die :)
