### ISSUE TITLE
[CLI] Can't sync wandb run

### ISSUE THREAD

**Issue by yanghoonkim** [wandb/wandb#2965]
**Description**
I'm currently using AWS ec2.

Since I want to resume the log of training a deep learning model (which means that I train a single deep learning model, stop in the middle and then resume training), I specified a `id` to `wandb.init()` and set `resume='auto' or `resume=allow`. I found that the wandb logs are resumed well.

However, when I delete the run from the wandb web console, I didn't find that the deleted run is automatically synced with the AWS server. Also, I can hardly sync manually. Everytime I run `python code_of_mine.py`, the terminal outputs `wandb: ERROR Error while calling W&B API: Error 1062: Duplicate entry '569728-hp' for key 'PRIMARY' (<Response [409]>)`.

Then I tried `wandb sync`, the terminal outputs: `No runs to be synced. NOTE: use wandb sync --clean to delete 1 synced runs from local directory.`

Then I tried `wandb sync --clean`, the terminal outputs: `No runs older than 24 hours found`

After 24hours I tried again `wandb sync --clean`, the terminal outputs several message that runs are synced, but I still get the error message above when I run the code.

What should I do?

p.s. The only way I found to use the same id with the same project is: remove the project from the console, re-init wandb in the terminal and create a new project with the same project name, and run the code with the same id.

**Wandb features**
What lines of wandb code are you using? This could be wandb.init(), wandb.log(), or features like the Keras callback, the Hugging Face integration, or PyTorch Lightning integration, for example.

**How to reproduce**
1. Link to a reproducible script we can run to see the bug
2. Describe what we have to do in order to trigger the issue
3. Add a zip file with the run folder 

**Environment**
- OS: Ubuntu 18.04.5 LTS
- Environment: AWS
- Python Version: 3.8.10

**Comment by yanghoonkim** [comment]
Yes, I am actually reusing the same `run id` my init. What I want is that when I resume experiment after stopping(pausing) for a while, I want wandb to plot log continuously on the last experiment's plot (I don't want another 'run' to be created on the wandb dashboard) : `wandb.init(project='PROJECT_NAME', id='EXP_NAME', resume='allow')` (I also try to use `resume='auto'`)

Actually, the way I did works well unless I don't delete those runs from the web.

After I delete the run on the web(for example, a run with `id='hello'`), and then if I run the code with the same id, several error message occurs: 
1. `wandb: ERROR Error while calling W&B API: Error 1062: Duplicate entry '569728-hello' for key 'PRIMARY' (<Response [409]>)`
~~ During handling of the above exception, another exception occurred
2. `wandb: ERROR Internal wandb error: file data was not synced`
3. `wandb: ERROR Abnormal program exit`

at this moment, if I run `wandb sync`:
`wandb: No runs to be synced.`
`wandb: NOTE: use wandb sync --clean to delete 35 synced runs from local directory`

and then I run `wandb sync --clean`:
`No runs older than 24 hours found`

after 24hours, if I `wandb sync --clean`, some of the runs seems to be synced, but the error still occurs.
(And I don't understand why it only allows to sync after 24 hours)

**Comment by StellaAthena** [comment]
See here: https://github.com/wandb/client/issues/1526

**Comment by vanpelt** [comment]
@yanghoonkim unfortunately today you can not re-use deleted run ids in a project.  We provide a helper method `wandb.util.generate_id()` which can be used to generate a random set of characters to append to your experiment name.  If you have an existing run that isn't deleted which you want to append data to you should see the resuming documentation provided by Leslie.
