### ISSUE TITLE
[Q] 2 questions regarding wandb tables

### ISSUE THREAD

**Issue by miraodasilva** [wandb/wandb#2990]
Hi, I was logging a table to wandb and had a couple of questions:
1. I select rows = ["a","b","c"] when initializing wandb.Table, but on the client the columns are still labelled as 1,2, etc. Is there a way to actually change these labels? I did not see any examples of this in the docs, so I assume this is not yet possible?

2. Is there a way to export the table from the client? Like to .csv or .png?

Thanks a lot!

**Comment by miraodasilva** [comment]
I am trying to export a table that I logged using wandb.Table

**Comment by lesliewandb** [comment]
Hi @miraodasilva! Great news, we now have the ability to export tables as a CSV!

**Comment by miraodasilva** [comment]
> Hi @miraodasilva! Great news, we now have the ability to export tables as a CSV!

Perfect, thanks so much for your hard work!
