### ISSUE TITLE
[Q] In Hyperparameter List/Diff is there a way to hide image files? 

### ISSUE THREAD

**Issue by Wilann** [wandb/wandb#3020]
Hi wandb team, 

I really find the hyperparameter list/diff to be really useful in the UI, but it would be great if we could hide certain types of diffs. For example, image diffs, as they can clutter the UI. 

Here's an image of the images cluttering the diff list: 
![Screenshot from 2021-12-10 09-17-45](https://user-images.githubusercontent.com/40744757/145588315-f942d86b-c293-40a8-9d84-4eef924e430e.png)

Alternatively, if this feature is already present, how can I use it? Thank you for reading!

**Comment by aidanjdonohue** [comment]
Hi @Wilann could you please link me to this project?

**Comment by Wilann** [comment]
Hi @aidanjdonohue, this is a private project. How can I link this to you?

**Comment by aidanjdonohue** [comment]
@Wilann I will be able to see it as an admin

**Comment by Wilann** [comment]
@aidanjdonohue Here it is: https://wandb.ai/wilan/Automatic-Highlight-Generation/table?workspace=user-wilan

**Comment by Wilann** [comment]
Thanks so much Leslie! Yes, please do let me know when there's been an update for this.
