### ISSUE TITLE
Bug on Windows: path is on mount 'C:', start on mount 'H'

### ISSUE THREAD

**Issue by janluke** [wandb/wandb#3065]
On line 1032:

https://github.com/wandb/client/blob/5e019ad35ff9b41da73332340705e0fdcfdacabc/wandb/sdk/wandb_settings.py#L1025-L1038

```python
..\src\unboxai\core\trainer.py:126: in _prepare
    self.logger = wandb.init(
..\.venv\lib\site-packages\wandb\sdk\wandb_init.py:969: in init
    six.raise_from(Exception("problem"), error_seen)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

value = None
from_value = ValueError("path is on mount 'C:', start on mount 'H:'")

>   ???
E   Exception: problem

<string>:3: Exception

```

**Comment by janluke** [comment]
In the stacktrace you can see I'm calling wandb.init(). The problem is inside _get_program_relpath_from_gitrepo and can summarized as this: you should never call os.path.relpath with paths located in different Windows partition. In this case, the "program" and the repo are in different partitions.

Not sure this helps but I can't run the code now.

**Comment by janluke** [comment]
Of course I'm still having the issue. Honestly, I'm quite surprised you even think to close an issue because the opener doesn't reply for a few days in this period of the year ^^"

**Comment by janluke** [comment]
I figured out this is a duplicate of
- https://github.com/wandb/client/issues/1991

It happens to me only when I run tests from PyCharm. The issue above was closed by a bot because stale but it has never been fixed.

**Comment by janluke** [comment]
Yes, I'm using that. I've not checked too much if the workaround is acceptable as a stable change that can be merged to the repo I'm working on though.

**Comment by mattip** [comment]
xref ray-project/ray#28542 which seems to be similar.
