### ISSUE TITLE
[Q] Organize simulations in sub-folders

### ISSUE THREAD

**Issue by EmanueleFrancazi** [wandb/wandb#3077]
Is it possible to organize project/group of simulations in subfolder structure during the logging?
The command
```Python
run = wandb.init(project="project_name",
           group = '/Father_folder/Child_folder1',
           entity="Owner_Name",
           reinit=True,
           name = 'run_name')
```
Doesn't work. With it I'd like to reproduce 
```
project_name
├── Father_folder
│       └── Child_folder1
│          └── run_name

```
the above structure on the dashboard.
What I get instead is:
```
project_name
├── Father_folder/Child_folder1
│   └── run_name

```
**What's the right way to do it?**

**Comment by ramit-wandb** [comment]
Hi @EmanueleFrancazi, you can change the directory where your data is logged in your project using the `dir` argument as:

```python3
run = wandb.init(project="project_name",
           dir = '/Father_folder/Child_folder1',
           entity="Owner_Name",
           reinit=True,
           name = 'run_name')
```

This should create the following file structure for you:
```
Father_folder
└── Child_folder1
    └── wandb
```

**Comment by EmanueleFrancazi** [comment]
Hi @ramit-wandb,  I tried your suggestion and substitued `group` argument with `dir` ; it didn't work in my case.
None of the 2 folders was created ( neither `Father_folder` nor `Child_folder1` ) and run has been saved directly inside the project main directory. To be more clear the structure I got is:
```
Father_folder
└── run_name
```
Plus I got this warning message multiple times:
```
wandb: WARNING Path /Father_folder/Child_folder1/wandb/ wasn't writable, using system temp directory
```

**Comment by ramit-wandb** [comment]
Hey @EmanueleFrancazi, Yes you are right, the directory specified should already exist for `wandb` to log in there. You should be able to create the directory automatically like so:

```python3
if not os.path.isdir(folder_path):
    os.makedirs(folder_path)
```

Callint `init()` after this should result in the desired behavior.

**Comment by EmanueleFrancazi** [comment]
@ramit-wandb thank's for the clarification;
 what should I substitute to `folder_path` in my example?
I tryed with './Father_folder/Child_folder1' but it doesn't work; what am I missing?

**Comment by ramit-wandb** [comment]
`./Father/Child` seemed to work on my computer. This could be dependent on your operating system. Maybe using something like `os.path.join` would work?

**Comment by cvphelps** [comment]
Hi @EmanueleFrancazi could I clarify, are you looking for a way to have a nested folder hierarchy show up in the W&B UI? We don't offer that feature right now, but it's a good request.

**Comment by EmanueleFrancazi** [comment]
Thank you bath for your replies; I'll open a request for this feature as suggested by @cvphelps

**Comment by kptkin** [comment]
close in favor of the feature request
