### ISSUE TITLE
[Feature] Upload progress indicator for artifact upload

### ISSUE THREAD

**Issue by segments-tobias** [wandb/wandb#3084]
**Is your feature request related to a problem? Please describe.**
When adding a directory to an artifact, it finishes very quickly, e.g.:
`wandb: Adding directory to artifact (./../data/COCO/annotations)... Done. 2.5s`
However, then the files still need to be uploaded. This is not clear, and it is impossible to see how long it will take to finish.
`wandb: Waiting for W&B process to finish, PID 249... (success).`

**Describe the solution you'd like**
Add a progress indicator when uploading/syncing files.

**Comment by EyalCohenResearch** [comment]
any news about the feature?

**Comment by ottozastrow** [comment]
this is still a thing?
would be nice to have an upload bar.
using it to upload datasets before training on cluster.
this is the first indicator I'm getting that tells me the artifacts tooling is not a wandb prio and not ideal for our team going forward.

**Comment by lesliewandb** [comment]
I have raised this feature request once again with our team. This thread will be notified if there are any updates

**Comment by jlzhao27** [comment]
Hey folks, sorry for the delay, the feature turned out to be surprisingly tricky but we just shipped it in 0.16.2! Here is the PR for reference: https://github.com/wandb/wandb/pull/6497
