### ISSUE TITLE
[App]  Segmentation mask not appearing

### ISSUE THREAD

**Issue by samsam3232** [wandb/wandb#3090]
Hi,
I'm training models on computers with no internet connection therefore I run wandb in offline mode.
I log images and their segmentation mask among with other values.
Since training is long, I want mid training to be able to see the images and their segmentation mask.
I download the log so far and use `wandb sync tmp/wandb_runs/neon_ensemble_begining_step2000_reg_max0.1_beta4.2_lr1e-05_gamma2.0/wandb/offline-run-20211229_094455-me-samuela-ensembleSelecNewFramework-1229-093531-algo-1/` to sync them.
The image itself appears on the wandb report but the segmentation masks don't.

Here is the code I use to log:
```
 wandb.log({"media/train_images_pred": wandb.Image(np.array(frame[0][:, :, None].cpu()), 
                                         masks={"predictions": {"mask_data":np.array(torch.argmax(segmentation, dim = 1)[0].cpu() * max_pred),
                                            "class_labels": pred_enum}, "ground_truth": {"mask_data": np.array(gt[0].cpu() + 2), 
                                               "class_labels": gt_enum}})})
```

Thanks

**Comment by ramit-wandb** [comment]
Hi @samsam3232,

Could you share a link to the project where you see this behaviour?

Thanks,
Ramit

**Comment by samsam3232** [comment]
Hi @ramit-wandb 

Here is the link to the project.
https://wandb.ai/sam_me/neon_ensemble?workspace=user-sam_me

**Comment by ramit-wandb** [comment]
Hi @samsam3232 ,

Looking at your project, it seems like segmentation masks are appearing on your images:

<img width="200" alt="Screen Shot 2022-01-05 at 10 59 07 PM" src="https://user-images.githubusercontent.com/93002515/148262354-ed0c998f-545b-435d-b869-26baa8f2f480.png">

Are you still facing this issue?

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
Hi @samsam3232,

We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by samsam3232** [comment]
Hi @ramit-wandb ,
Sorry I missed your previous answer. 
I found a workaround of saving the segmentation image as a png using matplotlib.
I can that way view the segmentation mask but I don't have the advantages of logging with a mask flag in wandb.log (i.e, the ability so select which categories to view)

**Comment by ramit-wandb** [comment]
Ah I see, sorry for missing that. I'm not completely sure what's happening in the code snippet you provided above, I'm going to need a little more context into your code (as in how `segmentation` got to where it was, what its shape is, etc). Could you share a colab where this error is reproduced? It would really help me dig into exactly why the segmentation masks are not popping up for you.

Thanks,
Ramit
