### ISSUE TITLE
[Q] How to delete team in wandb

### ISSUE THREAD

**Issue by jayleicn** [wandb/wandb#3091]
Is there a way that I can delete a `Team` or rename a `Team` in wandb? I searched in the doc and Google but did not find a way. Any help is appreciated!!  -- Jie

**Comment by ssmall41** [comment]
Are there any updates on this?

**Comment by nmichlo** [comment]
Also wondering about the progress of this. And possibly renaming teams?

**Comment by lesliewandb** [comment]
Thank you for your patience! We now have the ability to delete teams :) You can do this at the [wandb.ai/teams/<team_name>](http://wandb.ai/teams/%3Cteam_name%3E) page.
