### ISSUE TITLE
[App] Bug: Issue when using subheadings with the same name

### ISSUE THREAD

**Issue by andreimargeloiu** [wandb/wandb#3121]
**Describe the bug**
The heading is represented using the anchor "#$headingName" in the reports. This creates issues when there are multiple headers with the same name. Consider the use case:
```
# Model 1
## Train
## Validation

# Model 2
## Train
## Validation
```
Model1/Train and Model2/Train sections are represented using the anchor #train, which is wrong because it's not unique. Hence, sharing or scrolling to the section Model2/Train points to the section Model1/Train.

**Expected behavior**
In the table of content, clicking on a subheading should scroll the page to it. Each subheading should have a unique anchor.

**To Reproduce**
See [this](https://wandb.ai/andreimargeloiu/low-data/reports/Bug-section--VmlldzoxNDE0NjE0?accessToken=a2trl5l58qidjznqfmifgwv7fd1wvxai9yq2mvz0k2y2sjdud2lb28cqxy5yuopj#subsection-a) example report.

Notice that clicking on any "Subsection A" updates the URL with the anchor "#subsection-a," which is wrong because it scrolls down only to the first "Subsection A".

![CleanShot 2022-01-07 at 14 42 20](https://user-images.githubusercontent.com/18227298/148560425-f3af57c0-6d8e-41e3-a3f2-959fb4e53530.png)

**Comment by ramit-wandb** [comment]
Hi @andreimargeloiu,

Thank you for pointing this out! I'll create a ticket for this and we should have a fix out for this soon. I'll keep you updated.

Thanks,
Ramit

**Comment by andreimargeloiu** [comment]
The issue is still live. Any updates?
