### ISSUE TITLE
[CLI] artifact dataset versioning breaks on windows

### ISSUE THREAD

**Issue by fgraffitti-cyberhawk** [wandb/wandb#3133]
**Description**
This issue is linked to https://github.com/wandb/client/issues/2859
Dataset versioning doesn't work when run on windows.

**Wandb features**
To version dataset:
```python
import wandb
run = wandb.init(name='check_error',project='version_dataset')
artifact = wandb.Artifact('check_error', type='dataset')
artifact.add_reference('s3://ai-wandb-error/a/b')
run.log_artifact(artifact)
```
To download dataset:
```python
artifact = run.use_artifact('check_error/version_dataset/check_error:v0', type='dataset')
artifact_dir = artifact.download()
```

**How to reproduce**
1. Upload a file in a s3 bucket's subfolder
2. Run the first script above from windows
3. Run the second script (either on windows or linux): a boto3 error is raised as described in the linked issue
```
ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
```

Running the first script on linux works, and the dataset is correctly downloaded.
By checking the wandb browser interface, the issue seems to be linked with the last backslash in the URI.
When versioning from windows, this is what the URI looks like on wandb:

![image](https://user-images.githubusercontent.com/86408113/148973725-d42f49cd-2ea7-4af8-b4b1-c0c61749691e.png)

while when versioning from linux, this is the output:

![image](https://user-images.githubusercontent.com/86408113/148973839-0145dae7-511e-4b79-a305-c3693967b788.png)

I believe this is a bug, but it would be great to have some insight on this (and also to know if there is a workaround to rename the URI in the wandb artifact so that they match the ones in s3).

**Environment**
- OS: [Windows 10]
- Environment: local python session
- Python Version: 3.9.6

**Comment by ramit-wandb** [comment]
Hi @fgraffitti-cyberhawk,

Thank you for pointing this out! This is a known issue, and it is planned to be fixed in an upcoming release.

I don't think there is a good way to edit the URI to the Artifact in S3. The best method currently would be to use a library like `boto3` to make an API call to S3 and retrieve the object.
