### ISSUE TITLE
[Q] How to use wandb Table withour artifacts?

### ISSUE THREAD

**Issue by WinKawaks** [wandb/wandb#3178]
I am using wandb Table and put a lot of image (wandb Image) in the table. I didn't use any APIs of artifacts. But I found some artifacts files in my local cache folder and the Usage Dashboard of the official website. And all artifacts are ImageTable. Can I turn off the artifacts when I use wandb Image and Table?

**Comment by quzhiyuhuanqian** [comment]
> I am using wandb Table and put a lot of image (wandb Image) in the table. I didn't use any APIs of artifacts. But I found some artifacts files in my local cache folder and the Usage Dashboard of the official website. And all artifacts are ImageTable. Can I turn off the artifacts when I use wandb Image and Table?

曲智宇你怎么还不还钱呢？

**Comment by quzhiyuhuanqian** [comment]
曲智宇你怎么还不还钱呢？

**Comment by quzhiyuhuanqian** [comment]
曲智宇 你再不还钱 上海小女友心里承受不住了她要帮你还啦

**Comment by quzhiyuhuanqian** [comment]
> I am using wandb Table and put a lot of image (wandb Image) in the table. I didn't use any APIs of artifacts. But I found some artifacts files in my local cache folder and the Usage Dashboard of the official website. And all artifacts are ImageTable. Can I turn off the artifacts when I use wandb Image and Table?

曲智宇你这个大骗子 就你还讨好型人格 你这么自恋你讨好谁了？

**Comment by quzhiyuhuanqian** [comment]
曲智宇你怎么还不还钱？
