### ISSUE TITLE
[Q] How to make custom charts be automatically created for future&existing runs?

### ISSUE THREAD

**Issue by andreimargeloiu** [wandb/wandb#3224]
I created some custom charts in the chart view of one run. These charts aggregate some logged metrics. I have multiple runs with the same logged metrics, and I would like to analyze the same chart across numerous future&existing runs.

**How to make custom charts be automatically created for future&existing runs? Is there a function to have a "template" chart view?**

![CleanShot 2022-02-07 at 08 53 56](https://user-images.githubusercontent.com/18227298/152755908-7bdf5d2c-7f21-4d0d-a541-feb7bb950350.png)

**Comment by aidanjdonohue** [comment]
Hi @andreimargeloiu , if you are creating a "custom chart" you can reuse that template across multiple projects; however, we currently don't offer a way to manage charts that you edited through the UI as templates. I'm adding this feature request to our internal ticket on improving the modularity of workspaces in general and will update this thread as things develop on our end.
