### ISSUE TITLE
[Q] Is there a clean way to suppress unwatch warnings?

### ISSUE THREAD

**Issue by JakeColor** [wandb/wandb#3233]
`wandb` logs a warning every time we `.unwatch()` a model, spamming up our logs.

Is there a clean way to suppress this warning? 

```
**wandb**: WARNING [...] model has not been watched
```

## Our code
``` python
self.logger.experiment[0].unwatch(self.model)
```

## What we've tried:

``` python
with warnings.catch_warnings():
    warnings.filterwarnings("ignore", message="model has not been watched")
    self.logger.experiment[0].unwatch(self.model)
```

Thanks!

**Comment by ramit-wandb** [comment]
Hey @JakeColor,

Looking at the warning message, It seems like you are calling `unwatch(self.model)` before actually calling `watch(self.model)`. I think the best way to go about this would be to create a flag to make sure you call `watch` before.

If you still want a method to get rid of the warnings, I have somewhat of a hack that will work:
```python3
stderr = sys.stderr
sys.stderr = open(os.devnull, 'w')

self.logger.experiment[0].unwatch(self.model)

sys.stderr = stderr
```

I'm going to put a feature request to allow for better management of our warning/error messages.

Thanks,
Ramit

**Comment by JakeColor** [comment]
Thanks. I'll give this a try in the near future and re-open this issue if i still have issues.

Please reference this issue in future releases so I can replace our hack w/ a better solution!
