### ISSUE TITLE
[Q] Is it possible to know whether file has synced with server

### ISSUE THREAD

**Issue by JJBT** [wandb/wandb#3238]
`wandb.save(glob_str='snapshots/shapshot_*', policy='now')` is non-blocking call and i want to know whether snapshot has synced with server.
It is necessary to send message to another process that would download last snapshot from W&B server, create videos with this snapshot and upload videos to the corresponding run.

**Comment by armanhar** [comment]
Hey there, checking on this for you.

**Comment by vanpelt** [comment]
You can achieve this by using [wandb Artifacts](https://docs.wandb.ai/guides/artifacts).  Any call to log_artifact or use_artifact will return an artifact object.  Calling `.wait()` on that object will block your main thread until all files have been uploaded.
