### ISSUE TITLE
[Feature]: Try to scrub annoying "No path found after" messages from tensorboard?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [wandb/wandb#3274]
### Description

When running with `wandb.init(..., sync_tensorboard=True)`, the following wandb component:
https://github.com/wandb/client/blob/v0.12.10/wandb/sdk/internal/tb_watcher.py#L186-L189
tends to "spam" from the following line:
https://github.com/tensorflow/tensorboard/blob/2.8.0/tensorboard/backend/event_processing/directory_watcher.py#L122-L125

Is there someway to configure that component, via wandb by default, to avoid injecting noise in the console?

It cropped up when we upgraded tensorboard from 2.2.2 to 2.8.0 (quite a big jump, yeah).
Unfortunately, I do not have a compact, shareable reproduction script.

FWIW: I like `sync_tensorboard` so we're not strictly dependent on `wandb` for viewing our metrics (e.g. locally viewing them when on travel and w/o internet), so I strongly prefer to keep that as-is.

### Suggested Solution

In our codebase, we wrap `wanb.init()`. We've made a PR to our codebase (8442) to do the following (which seems to work):

```py
import logging

from tensorboard.util import tb_logging
import wandb


class _IgnoreTensorboardPathNotFound(logging.Filter):
    def filter(self, record):
        assert record.name == "tensorboard"
        if "No path found after" in record.msg:
            return False
        return True

def our_wandb_init_wrapper(...):
    ...
    wandb.init(...)
    tb_logger = tb_logging.get_logger()
    tb_logger.addFilter(_IgnoreTensorboardPathNotFound())
    ...
```

### Alternatives

Make a PR to tensorboard to demote that to debug (not info)?
https://github.com/tensorflow/tensorboard/issues/5577
https://github.com/tensorflow/tensorboard/pull/5578

### Additional Context

We are on Ubuntu 20.04, CPython 3.8.10

What I believe to be relevant packages:
```sh
torch == 1.10.2
wandb == 0.12.10
tensorboard == 2.8.0
```

**Comment by aidanjdonohue** [comment]
Hi @EricCousineau-TRI , thanks for the detailed feature request. I'll file something internally and update this thread when we implement this. All the best, Aidan.

**Comment by EricCousineau-TRI** [comment]
Thanks! See upstream PR w/ discussion: https://github.com/tensorflow/tensorboard/pull/5578#issuecomment-1051009818
I think they'd like to see if things can be configured via `wandb` to avoid demoting log info.
