### ISSUE TITLE
[Q][F] Revert config viewer?

### ISSUE THREAD

**Issue by OverLordGoldDragon** [wandb/wandb#3287]
I have nested dictionaries and tuples, which are a pain to view with the new `Config` layout. Every value in a tuple gets its own entire row. `Summary` also now includes weights for some reason. Can these changes be reverted? If not, I'd appreciate the option.

E.g. `'stem_kernel_size': (5, 7, 7)` renders as

<img src="https://user-images.githubusercontent.com/16495490/155466737-bddcc3f4-97be-4b3e-bf4e-3f8962b1b2fd.png" width="250">

**Comment by armanhar** [comment]
Hey there, could you share a link to a run with this issue?

**Comment by OverLordGoldDragon** [comment]
It's a private project. MRE:

```python
import wandb

kw = {'seresnet_3d_0_kw': 
      {'stem_kernel_size': (5, 7, 7)}}
run = wandb.init(config=kw)
```
