### ISSUE TITLE
[Q] How are logs captured by WandB?

### ISSUE THREAD

**Issue by JoshKImperial** [wandb/wandb#3299]
Lately I've been using an [unofficial WandB Julia wrapper](https://github.com/avik-pal/Wandb.jl) which works great, except it doesn't capture log messages.  I've spent some time looking through the WandB Python package and cannot see where it captures log messages, how are log messages captured?

This issue at Wandb.jl: https://github.com/avik-pal/Wandb.jl/issues/11

**Comment by vanpelt** [comment]
Hey @JoshKImperial unfortunately it's rather none-trivial.  The majority of the logic [is here](https://github.com/wandb/client/blob/master/wandb/sdk/lib/redirect.py#L686).  To support progress bars and various ascii control characters we had to implement a [terminal emulator](https://github.com/wandb/client/blob/master/wandb/sdk/lib/redirect.py#L195).  The actual stdout and stderr redirecting happens after `wandb.init` is called in [this function](https://github.com/wandb/client/blob/master/wandb/sdk/wandb_run.py#L1598).  Additional complexities include special logic for Windows and multiple modes of wrapping the stdout and stderr depending on various environments like jupyter etc.

In the end after all the emulation and de-duping the data is periodically streamed to a wandb server from the [FileStream thread](https://github.com/wandb/client/blob/master/wandb/sdk/internal/file_stream.py) which streams the data under the "output.log" key using the[ CRDedupeFilePolicy](https://github.com/wandb/client/blob/master/wandb/sdk/internal/file_stream.py#L98).

**Comment by vadimkantorov** [comment]
@vanpelt Is it possible to disable any wandb log capture / meelding with sys.stdout/stderr completely?

**Comment by vanpelt** [comment]
@vadimkantorov yep, with the `WANDB_CONSOLE=off` env variable.
