### ISSUE TITLE
[CLI]: Failed sweep runs stay alive, cannot delete them from the web application

### ISSUE THREAD

**Issue by zimmer-m** [wandb/wandb#3312]
### Describe the bug

Sometimes I start sweeps only to notice that there is still a bug in my implementation, causing some runs to fail. Previously I would simply delete them from the wandb sweep interface, fix the bug, and then restart the client on my computing infrastructure. These runs typically stay active for a very long time, even after having crashed (right now, >10 minutes and still alive). Recently however, some new web-app feature was introduced, disallowing me to delete these runs:

![image](https://user-images.githubusercontent.com/66726489/156167572-45282590-6946-4dc2-8cf3-6f8306c6126f.png)

This is really annoying since I cannot redo these runs and have to start a completely new sweep. Could we revert to the state where active runs are deletable? Or is there some workaround?

Thanks!

### Environment

WandB version: 0.12.9

OS: Linux

Python version: 3.8.5

**Comment by zimmer-m** [comment]
Hey @ramit-wandb, thanks for the fast answer.

Not sure if `pkill -9 wandb` is what I actually want, since afaik this will kill all wandb processes on the machine? I am using clusters with multiple GPUs, so its very likely that I have working and active runs on a machine which I do not want to kill.

I will get back to you as soon as I acquire a `debug.log`, this however mostly happens when using SLURM to start runs and a simple python bug terminates the programm (I reckon that a failed assert statement would suffice to kill my run, while keeping the wandb connection alive).

In any case, it would be really nice to either being able to delete multiple active runs, like it was before, or stop multiple active runs from the web interface, such that deletion is not a problem anymore. As of now, one can stop a single run, and I am not sure how this behaves when the run is actually "dead" like in my case.

**Comment by ramit-wandb** [comment]
Hi @zimmer-m,

If you do not want to use `pkill`, one way to navigate around this could be to use `top`/`pgrep` to find the process ids associated with the zombie runs and then use `kill` to end those processes manually.

We are working on a solution to let you delete active runs from the Web UI with something like a confirmation modal to confirm if you want to delete an active run. I'll keep you updated on the progress of this feature.

Thanks,
Ramit

**Comment by Hzzone** [comment]
Same issue here.

**Comment by ramit-wandb** [comment]
Hi @zimmer-m, @Hzzone!

The confirmation modal I described in the above message is ready. We are just getting ready to perform some testing, I'll let you know when this is deployed and ready to use!

Thanks!
Ramit

**Comment by ramit-wandb** [comment]
Hi @zimmer-m, @Hzzone!

The confirmation modal is ready to use and is now live at wandb.ai, which will confirm that you want to delete an active run before going ahead and doing so. I'm going to close this issue out for now, but if you face any issues while using this, please respond to this thread and I will be glad to assist.
