### ISSUE TITLE
[CLI]: Can't plot decision boundaries

### ISSUE THREAD

**Issue by s-wheels-behold** [wandb/wandb#3317]
### Describe the bug

Trying to use the function wandb.sklearn.plot_decision_boundaries and it doesn't appear to correctly import the DBPlot class

![image](https://user-images.githubusercontent.com/94847626/156372714-1b8c299b-25c7-46e1-b666-ea0080b8f28f.png)

### Environment

WandB version: 0.12.11

OS: Linux

Python version: 3.8.12

**Comment by nate-wandb** [comment]
Hi @s-wheels-behold, thank you for catching this and reporting it. I see that DBplot isn't imported anywhere in the source code and isn't defined before it is called. I apologize for the inconvenience. I'll report this bug so we can get this fixed. 
Thank you,
Nate

**Comment by nate-wandb** [comment]
Hi @s-wheels-behold, it looks like the `plot_decision_boundaries` function has been deprecated so we will no longer be supporting this feature and it is removed from upcoming versions of `wandb`. There is still the option to make these plots in sklearn or matplotlib and upload them to wandb though.

Thank you,
Nate
