### ISSUE TITLE
[CLI]: `wandb.api.public.Sweep.state` is documented, but doesn't actually exist?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [wandb/wandb#3343]
### Describe the bug

Tried using `.state` on a sweep via public API, but I got an error that it didn't exist.

Docs don't agree with code.

Not in code:
https://github.com/wandb/client/blob/v0.12.11/wandb/apis/public.py#L2061-L2235
but docs say it's there:
https://docs.wandb.ai/ref/python/public-api/sweep
> ![image](https://user-images.githubusercontent.com/26719449/157343197-f96b7840-0158-4b62-ab56-46b1d1eb38d2.png)

### Additional Files

N/A

### Environment

WandB version: v0.12.11

OS: Ubuntu 20.04

Python version: CPython 3.8

Versions of relevant libraries: N/A

### Additional Context

For being able to clean and resume a sweep. Worked around by using the following hacky setup:

```py
import argparse
from subprocess import run, PIPE, STDOUT
from textwrap import dedent, indent

import wandb


def yesno(prompt):
    print(f"{prompt} [y/N]")
    answer = input()
    if answer:
        c = answer[0].lower()
        if c == 'y':
            return True
    return False

def maybe_resume_sweep(sweep):
    # TODO(eric.cousineau): Make this use API instead of CLI.
    sweep_path = f"{sweep.entity}/{sweep.project}/{sweep.id}"
    result = run(
        ["wandb", "sweep", "--resume", sweep_path], stdout=PIPE, stderr=STDOUT, text=True
    )
    print(result.stdout)
    if result.stdout != 0:
        print(dedent(f"""
        WARNING! At time of writing (2022-03-08), `wandb sweep --resume` via CLI may fail.
        
        As workaround, go to sweep controls page:
            {sweep.url}/controls
        And manually click "Resume"
        """))  # noqa


def clean_and_resume_sweep(project_name, sweep_id):
    api = wandb.Api()
    entity = "..."
    sweep_path = f"{entity}/{project_name}/{sweep_id}"
    sweep = api.sweep(path=sweep_path)
    to_delete = []
    for run in sweep.runs:
        if run.state != "finished":
            to_delete.append(run)
    if len(to_delete) > 0:
        print("Will delete following runs:")
        to_delete_txt = "\n".join(
            f"id={run.id}, name={repr(run.name)}, state={run.state}"
            for run in to_delete
        )
        print(indent(to_delete_txt, "  "))
        if not yesno("Continue?"):
            print("Aborting")
            return
        for run in to_delete:
            run.delete()
    maybe_resume_sweep(sweep)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--project", "-p", type=str, required=True)
    parser.add_argument("sweep_id", type=str)
    args = parser.parse_args()
    clean_and_resume_sweep(args.project, args.sweep_id)


if __name__ == "__main__":
    main()

```

**Comment by realCrush** [comment]
Same issue.

**Comment by lesliewandb** [comment]
Hi @realCrush, I have further increased the priority on this ticket. I'll let you know if I have any updates

**Comment by realCrush** [comment]
> Hi @realCrush, I have further increased the priority on this ticket. I'll let you know if I have any updates

Thank you Leslie😊

**Comment by lesliewandb** [comment]
Hi @EricCousineau-TRI , we have fixed the code to include the Sweep state property! Please upgrade to the most recent version to use it

**Comment by dendritic** [comment]
This issue is still present as of version 0.13.5

**Comment by dendritic** [comment]
> This issue is still present as of version 0.13.5

Actually, correction: the state _is_ available from a sweep obtained via `api.sweep('chrisburgess/sweeps_test/955lkhx7')` but _not_ from a sweep obtained via `api.project('my_project_name').sweeps[sweep_idx]`
