### ISSUE TITLE
[CLI]: `wandb sweep --resume` doesn't actually resume stopped sweeps?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [wandb/wandb#3344]
### Describe the bug

Wanted to use API, but there is no `wanb.apis.public.sweep.resume()`.
(Requested feature via private Slack channel)

Tried to use command line to resume sweep, but that failed.

Confirmed it was stopped on web APP, and could Resume using the button.

Error:
```
$ wandb sweep --resume {path}
wandb: Resuming sweep {path}
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "{venv}/wandb/__main__.py", line 3, in <module>
    cli.cli(prog_name="python -m wandb")
  File "{venv}/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "{venv}/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "{venv}/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "{venv}/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "{venv}/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "{venv}/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "{venv}/wandb/cli/cli.py", line 86, in wrapper
    return func(*args, **kwargs)
  File "{venv}/wandb/cli/cli.py", line 735, in sweep
    getattr(api, "%s_sweep" % state)(sweep_id, entity=entity, project=project)
  File "{venv}/wandb/apis/internal.py", line 117, in resume_sweep
    return self.api.resume_sweep(*args, **kwargs)
  File "{venv}/wandb/sdk/internal/internal_api.py", line 2651, in resume_sweep
    self.set_sweep_state(
  File "{venv}/wandb/sdk/internal/internal_api.py", line 2586, in set_sweep_state
    raise Exception("Cannot resume %s sweep." % curr_state.lower())
Exception: Cannot resume finished sweep.
```

### Additional Files

See script in https://github.com/wandb/client/issues/3343#issue-1163307416

### Environment

WandB version: v1.12.10

OS: Ubuntu 20.04

Python version: CPython 3.8

Versions of relevant libraries: N/A

**Comment by nate-wandb** [comment]
Hi @EricCousineau-TRI, I wanted to respond here and let you know the bug is being looked at. There's a few issues with resuming sweeps currently but I think the feature request we talked about will help alleviate these issues. We'll still see if we can resolve this bug for anyone who wants to programmatically resume a sweep.

Thank your reporting,
Nate

**Comment by EricCousineau-TRI** [comment]
Apologies for delay! May take a week or more to get back - thank you for following up!

**Comment by nate-wandb** [comment]
Hi @EricCousineau-TRI,
I wanted to check back in and see if you've gotten a chance to look into this? I've tested a few different things and haven't been able to reproduce so I figured I was probably missing a step here. 

Thank you,
Nate

**Comment by EricCousineau-TRI** [comment]
Howdy Nate! I have just confirmed that the issue still exists on my side. Please see:
https://github.com/EricCousineau-TRI/repro/tree/34e2c79bbe2989dfa3e1fe6c1a0410e9bf4ec169/python/wandb_sweep_example

Please see example output in `example_failure.txt`; note that I cannot automatically resume. I must manually navigate to the sweep controls and resume.

**Comment by nate-wandb** [comment]
@EricCousineau-TRI sorry for the delayed response on this. I can confirm that this is a bug and has been reported to our engineering team. Hopefully we can get a fix on this soon.

Thank you,
Nate

**Comment by geyao1995** [comment]
> Howdy Nate! I have just confirmed that the issue still exists on my side, for both `wandb==0.12.10` and `wandb=0.12.14`. Please see: https://github.com/EricCousineau-TRI/repro/tree/34e2c79bbe2989dfa3e1fe6c1a0410e9bf4ec169/python/wandb_sweep_example
> 
> Please see example output in `example_failure.txt`; note that I cannot automatically resume. I must manually navigate to the sweep controls and resume.

Same, command fails but UI sweep controls button works.

**Comment by MBakirWB** [comment]
Hi @geyao1995 , this is still actively being worked on by our engineering team. We will provide an update when available. Apologies for the inconvenience this is causing.
