### ISSUE TITLE
[CLI]: Disabling code saving not working as intended

### ISSUE THREAD

**Issue by psinger** [wandb/wandb#3386]
### Describe the bug

According to documentation, one can set `WANDB_DISABLE_CODE` environment variable to True or use `wandb.init(save_code=False)` to disable code saving. However, this seems to be overwritten by the user setting in the UI to enable code saving. 

Even if I set both the environment variable, and the init flag, but enable it in the UI under settings, the code is saved.
This should not be possible to be overwritten by a user.

### Environment

WandB version: latest

OS: Ubuntu

Python version: 3.7

### Additional Context

Related: https://github.com/wandb/client/issues/3372

**Comment by ramit-wandb** [comment]
Hi @psinger,

I'm sorry you are facing this. Our engineering team is currently working on resolving this, and as a temporary workaround you should be able to use the following line of code:

```
run._settings.update(save_code=False)
```

I'll let you know once this issue has been fixed.

Thanks,
Ramit

**Comment by pascal-pfeiffer** [comment]
Thank you for addressing this important issue @ramit-wandb 
I am afraid that the proposed workaround does not yield the desired results. The current client (v0.12.11) would still log the entry point and even commit diffs changes with WANDB_DISABLE_GIT=true. 

minimal code example:
```python
import os

os.environ["WANDB_DISABLE_CODE"] = "true"
os.environ["WANDB_DISABLE_GIT"] = "true"
os.environ["WANDB_ERROR_REPORTING"] = "false"
os.environ["WANDB_CONSOLE"] = "off"
os.environ["WANDB_IGNORE_GLOBS"] = "*.*"
os.environ["WANDB_HOST"] = "Runner"
os.environ["WANDB_API_KEY"] = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

import wandb

logger = wandb.init(
    project="XXXX",
    entity="XXXXX",
    name="XXXXXX",
    save_code=False,
)

wandb.run._settings.update(save_code=False)

logger.log({"test_name": 14, "test_name2": 1})

```

**Comment by ramit-wandb** [comment]
Hi @pascal-pfeiffer,

I apologize for the delay here. I'm sorry to hear that the above suggested solution did not work for you. Our engineers have come up with a solution for this, and it should be released in the next launch of the `wandb` SDK, i.e., v0.12.12. I'll keep you updated on the status of this - It should be released in the coming few days.

Thanks,
Ramit
