### ISSUE TITLE
[App]: UI summary differs from json summary

### ISSUE THREAD

**Issue by ignasi00** [wandb/wandb#3387]
### Current Behavior

When analysing my runs, there are some experiments without a summary element.
(at first, I through it was my code problem, like not waiting enough to sync before the program finish, SPOILER: it is not)

- When studying the **summary (raw) of a run from the web user interface** (on the overview section), some "updated" elements are missing: ctrl+F of "mIoU" find 8 coincidences (after some seconds).
- When studing the **wandb-summary.json of the same run from the web user interface** (on the files section), all elements are there: ctrl+F of "mIoU" find 12 coincidences.

 I should like to post the summaries but, although the wandb-summary.json only weights 10,2 MB, the summary (raw) is not downloadable, copiable  or printable (because the webpage memory requirement). Then, I will share my links:
For the wandb-summary.json: [https://wandb.ai/ignasi00/platgesBCN/runs/wlq59dbl/files](url)
For the overview: [https://wandb.ai/ignasi00/platgesBCN/runs/wlq59dbl/overview](url)

---

By the way, how can each tab related to a project on wandb.ai require 2 GB of RAM?
By instance, this run is 50 epochs and the plain text json summary weights 10,2 MB which makes approx 0,5 GB for all the run, given that most of the data is not required at the same time, it is scary how it requires that much memory.

### Expected Behavior

The web app should coincide with the summary JSON.

---

The web app should requiere less RAM

### Steps To Reproduce

1. Get my script (wandb obtains the github from my project by itself)
2. Get some semantic segmentation dataset (prepared to work with my dataset objects, by instance ArgusNL)
3. Make the lists for the step 2 dataset.
4. Run my kfolds code with the step 3 lists
5. Check that the run ends succesfully with the full summary
6. Check that wandb web app do not found valid_mIoU on the run summary
7. Check that wandb do not have it on the summary raw of the overview section.
8. Check that wandb do have it on the wandb-summary.json of the files section.

### Environment

OS: Code run on Ubuntu (see the overview for details), web view on Windows 10 pro 64bits (although Google Chrome is a embedded OS)

Browsers: Google Chrome 

Version: Google Chrome 99.0.4844.74 (Build oficial) (64 bits); wandb-0.12.11

**Comment by bruzwen** [comment]
I've been having the same issue. I can see some metrics are logged in `wandb-summary.json` but they don't show up in the summary panel on the web page (or the "raw" summary). This is troubling especially when using Sweep, as it can't track the summary metric to choose the hyper params for the next run.

Is there any update on this issue?

**Comment by ignasi00** [comment]
> I've been having the same issue. I can see some metrics are logged in `wandb-summary.json` but they don't show up in the summary panel on the web page (or the "raw" summary). This is troubling especially when using Sweep, as it can't track the summary metric to choose the hyper params for the next run.
> 
> Is there any update on this issue?

After some time without receiving any idea of how I could try to solve it, and knowing why the web page requiered that much memory, **I decided to remove my project and start another (with the same name) from scratch with my code updated**. I restarted the project because there was column names from previous runs that I do not use anymore. Hopefully it won't happen to me anymore :) (<- I wanted to post this here because it may affect the work of the ones that could solve it)

If you need faster help, maybe you should provide some examples of runs where this happens (if it was lunched on a git folder with origin on GitHub they will be able to read the exact code used on the run).


Answering your question: No, at least not that I know.

I hope your problem will be solved as soon as possible :)

**Comment by nate-wandb** [comment]
Hi @bruzwen and @ignasi00, sorry for the delay on this. Could you both upgrade to W&B version 0.12.16 and then run `wandb sync -project <name-of-project> <path/to/run/folder>` and see if you still experience the issue after trying to sync the run again? Here are the [docs](https://docs.wandb.ai/ref/cli/wandb-sync) for this.

@bruzwen could you share a link to the workspace as well?

Thank you,
Nate

**Comment by nate-wandb** [comment]
@bruzwen were you able to try the above solution or do you have a link to the workspace where I can investigate this further?

**Comment by nate-wandb** [comment]
Hi All, since we haven't heard back I'll go ahead and close this ticket on our side but feel to comment and tag me if you would like reopen this issue and we'll be happy to look into it more.

Thank you,
Nate

**Comment by sydholl** [comment]
We are closing this ticket due to inactivity, please comment to reopen.
