### ISSUE TITLE
[Q] Setting git version information manually

### ISSUE THREAD

**Issue by nbren12** [wandb/wandb#3421]
It would be nice to see the git version cleanly in the web UI when running from containers jobs. The catch: we usually don't copy `.git` into our images. Similarly, wandb does capture the image digest, but not the actual container name.

We have a workaround, but it is a bit unwieldy. We inject the git sha manually into our containers using docker build args and save it as an environment variable `COMMIT_SHA`. Then, we log this environment variable as `wandb.config`. The downsides is that it is a bit clunky and requires python code changes for any script.

Is there a better workaround? It would be ideal to be able to control some of these run-metadata fields using env vars. For example, wandb could listen to env variable called `WANDB_GIT_COMMIT`.

**Comment by nbren12** [comment]
or looking into it there are some standards about annotations for images that could be leveraged: https://github.com/opencontainers/image-spec/blob/main/annotations.md

**Comment by nbren12** [comment]
> Is there a reason why you don't copy .git in your images?

Just philosophical ones and wanting to keep the image lean. We use argo/k8s to run our workflows, not sure how common that is amongst your users. Better integration with this kind of setup seems like a potentially rich area for future feature development---or is out of scope depending on your perspective. Would be great to have a wandb sidecar container that can monitor the stdout and container information of another container

**Comment by lesliewandb** [comment]
Hi @nbren12, Congrats, this feature is going to be included in our next update on August 2nd!

**Comment by nbren12** [comment]
@lesliewandb Great! Thanks.

**Comment by ethanluoyc** [comment]
I would like to mention that this would be a very useful feature. I have a use case where I deploy my code without .git/ folder but would still like to track some VCS info, being able to set this manually would make my life much easier.
