### ISSUE TITLE
[Q] How to use `wandb sync --exclude-globs` properly?

### ISSUE THREAD

**Issue by JinchaoLove** [wandb/wandb#3454]
Hi, I want to exclude some large files, such as `*.pt`, when uploading an offline training directory to W&B. I've tried the command lines `wandb sync --exclude-globs \*.pt offline-run-xxx` and `wandb sync --exclude-globs "*.pt" offline-run-xxx`,  but they doesn't seem to work. May I ask how to use the `--exclude-globs` option properly?

**Comment by ramit-wandb** [comment]
Hi @JinchaoLove,

May I ask what your goal is with this command? `--exclude-globs` is used to exclude whole runs by defining a glob string, not individual files, which seems to be happening here with the `*.pt` argument.

Thanks,
Ramit

**Comment by JinchaoLove** [comment]
Hi @ramit-wandb, thanks for the reply. Since I want to store the models locally, while uploading the results, logs and configs online, I wonder if there's a command to exclude certain file types while doing `wandb sync`. The goal of the command is intended to exclude the individual `.pt` files when uploading an offline-run. I also tried the command without `*`, i.e., `wandb sync --exclude-globs ".pt"`, but it still uploaded the `*.pt` files online.

**Comment by ramit-wandb** [comment]
Hi @JinchaoLove,

You might want to save your model files in a folder separate from the `wandb` folder if you do not want to upload them online. `wandb` uploads any files that are in the `wandb/run-xxx` folder.

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
Hi @JinchaoLove,

We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

Best,
Ramit

**Comment by JinchaoLove** [comment]
Hi @ramit-wandb, the issue has been resolved with separated folders. It would be more helpful if `wandb` could support excluding individual files when uploading the folder.

Best,
Jinchao

**Comment by ramit-wandb** [comment]
Hi @JinchaoLove,

Glad to hear this issue has been resolved! Thanks for the suggestion, I'll pass it on to our team for review.

Thanks,
Ramit
