### ISSUE TITLE
Alpha dimension for videos does not work

### ISSUE THREAD

**Issue by xmax1** [wandb/wandb#3481]
### Describe the bug

It seems that the alpha parameter has no effect on representation of videos. The grey/black/white comparison might not seem good enough, but this was noticed on another problem. Same effect. 

```python 

import wandb
import numpy as np

run = wandb.init(project='', entity='')

with run:
    white = np.ones((10, 4, 10, 10)) * 255
    wandb.log({'white': wandb.Video(white.astype(int), fps=4)})
    black = np.ones((10, 4, 10, 10)) * 0
    wandb.log({'black': wandb.Video(black.astype(int), fps=4)})
    grey = np.ones((10, 4, 10, 10)) * 120
    wandb.log({'grey': wandb.Video(grey.astype(int), fps=4)})
    grey[:, -1, ...] = 50 
    wandb.log({'should_be_faded_grey': wandb.Video(grey.astype(int), fps=4)})
    black[:, -1, ...] = 0 
    wandb.log({'should_be_white': wandb.Video(black.astype(int), fps=4)})
```

### Environment

WandB version: 0.12.12

OS: Linux

Python version: 3.10

**Comment by armanhar** [comment]
Hey there, thanks for reporting the issue. I'll try to reproduce this on me end and get back to you.

**Comment by armanhar** [comment]
Hey @xmax1, could you upgrade your client version and check if the issue still persists?

**Comment by armanhar** [comment]
Hi @xmax1, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.
