### ISSUE TITLE
[CLI]: W&B crashes Sentry integration

### ISSUE THREAD

**Issue by iamhatesz** [wandb/wandb#3497]
### Describe the bug

Importing `wandb` module disables [Sentry](https://sentry.io/) integration.

```python 
import sentry_sdk
import os

sentry_sdk.init(
    os.environ.get("SENTRY_DSN", ""),
    environment="development",
)
import wandb  # <=== Comment this line or replace with any other import and everything works fine again
raise Exception()  # <=== This exception is no longer handled by Sentry
```

### Environment

WandB version: tested on 0.12.10 - 0.12.13

OS: Ubuntu 20.04

Python version: Python 3.9.6

Versions of relevant libraries: sentry_sdk==1.5.8

### Additional Context

In real scenario the import comes from unpickling a class, which imports `wandb`.

**Comment by iamhatesz** [comment]
@nate-wandb that's the workaround I've used as well. However, a good practice is that package import should have no side-effects, especially on other packages.

**Comment by nate-wandb** [comment]
Hi @iamhatesz, our engineering team has merged a fix for this and it will be available in the next release of W&B. Thank you for bringing this to our attention!
