### ISSUE TITLE
[Q] Possibility to archive projects or dumb data

### ISSUE THREAD

**Issue by phrasenmaeher** [wandb/wandb#3507]
For a project, I have used the Weights & Biases logging library. Over time, I have logged a couple thousand experiments. Because this clogs my W&B disk space, I wanted to know if there's a way to either a) archive the data, or b) download a dump that can (somehow) be viewed offline.

Of the second solution, I am not sure how to achieve this, maybe some kind of lean W&B only for viewing dumps? With that in mind, I am generally looking for a solution that lets me access and also nicely view the data at a later point (around two years).

Downloading the project via wget or curl does not seem to be the right solution; the dynamic dashboards are what makes `wandb` so unique and outstanding.

**Comment by phrasenmaeher** [comment]
@armanhar Thanks for our answer. I'll close the issue then.

**Comment by ashok-arora** [comment]
Hey @armanhar, is there any update on this? I wish to download and share the dump so that others can use it too.

**Comment by ashok-arora** [comment]
@MBakirWB Okay, thank you for the update. Currently, my workflow is to use the local wandb docker container for visualization and testing with a lot of experiments, and then I sync some of them to my wandb account. Lastly, I would like to have a dump of my saved logs from the wandb account so I can share it with others so they can open it in their local wandb docker container.
