### ISSUE TITLE
[Q] Sort of timeout between wandb.init and wandb.log call

### ISSUE THREAD

**Issue by philippart-s** [wandb/wandb#3512]
Hi,

Sorry if my question is obvious but with the following code in my notebook:
```python
wandb.init(project = 'notebook_tf_MNIST',
                     config = {  
                         "learning_rate": 0.001,
                         "epochs": 10,
                         "batch_size": 64,
                         "dropout": 0.2,
                         "loss_function": "sparse_categorical_crossentropy",
                         "architecture": "CNN",
                         "dataset": "MNIST",
                         "resume" : "auto"
                     }
)

# some code

wandb.log({'Test error rate': round((1 - accuracy) * 100, 2)})
```

If I wait a couple of times (several minutes) between the call of `init` and `log` I've the following error: `Error: You must call wandb.init() before wandb.log()`

Is there a timeout between the call of `init` and the call of `log` function ?

**Comment by philippart-s** [comment]
the problem occurs between the init and the first call of log, so if I don't think you want I call finish before the first call of log ?

**Comment by vanpelt** [comment]
It could be that your kernel actually stops between your call to log and init.  Within a running python process you must call init before log.  Once you're done with an experiment you can call finish and then call init again before the next log...

**Comment by philippart-s** [comment]
ok thanks, I'll investigate on my side to know if the kernel is stopped or restarted (it seams not but I'm waiting for a confirmation).
Last information I used the free version of W&B.

**Comment by armanhar** [comment]
Hey @philippart-s, I wanted to follow up with you on this. Do you need further assistance?

**Comment by philippart-s** [comment]
Hi,

I don't know 😅, in one side my ops said the kernel and python process is up and in the other side W&B said to me that there is no timeout.

But if I wait a couple of minutes between the `init` and the `log` method I have an error that indicate to me that I have to init before log 😅.

The only way to avoid this is to execute the two cells of my notebook quickly.

By the way it's one point that I haven't mentioned : I launch the `init` in one cell and the `log` in another cell of my notebook.

**Comment by ash0ts** [comment]
Hello @philippart-s,

Can you try changing your `init` and `log` usage to match below? You can assign the run object generated by `wandb.init` to a variable (like `run`) and then log via that variable.

```
run = wandb.init(project = 'notebook_tf_MNIST',
                     config = {  
                         "learning_rate": 0.001,
                         "epochs": 10,
                         "batch_size": 64,
                         "dropout": 0.2,
                         "loss_function": "sparse_categorical_crossentropy",
                         "architecture": "CNN",
                         "dataset": "MNIST",
                         "resume" : "auto"
                     }
)

# some code

run.log({'Test error rate': round((1 - accuracy) * 100, 2)})
```

If this snippet does not work can you send over a minimal reproducible example of this behavior and the `debug-internal.log` found in the `./wandb` directory relative to the code? Thank you!

**Comment by ash0ts** [comment]
​Hi @philippart-s ,

We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.
​
Best,
Anish
​

**Comment by philippart-s** [comment]
Hi,
Sorry I'm travelling this week but I will try your proposition next week and give you the result.

**Comment by ash0ts** [comment]
I'm glad to hear that @philippart-s. Happy experimenting 🧑‍💻!
