### ISSUE TITLE
[CLI]: wandb does not record git diff when mode="offline"

### ISSUE THREAD

**Issue by samuela** [wandb/wandb#3519]
### Describe the bug

The [offline docs](https://docs.wandb.ai/guides/technical-faq#can-i-run-wandb-offline) suggest that offline mode works the same as online, but with the ability to push the results to API at a later time. However, when running with `mode="offline"`, wandb does not store the git diff as it does in online mode.

```
$ python -c "import wandb; wandb.init('foo')"
$ python -c "import wandb; wandb.init('foo', mode='offline')"
```
Then check the contents of the respective `./wandb/offline-run-*` and `./wandb/run-*` directories. Note that `./wandb/run-*/files/diff.patch` exists where as no such patch file exists in `./wandb/offline-run-*/files`.

### Environment

WandB version: 0.12.7 - 0.12.14

OS: 
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.13.0-1021-aws, Ubuntu, 20.04.4 LTS (Focal Fossa)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.6.1`
 - channels(ubuntu): `"home-manager, nixgl"`
 - channels(root): `"nixpkgs"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

Python version: 3.9.11

Versions of relevant libraries: n/a

### Additional Context

Discovered in the context of packaging wandb for [nixpkgs](https://github.com/NixOS/nixpkgs).

**Comment by nate-wandb** [comment]
Hi @samuela, thank you for reporting! I'll ask our engineering team if this is intended behavior or if this is a bug and have them look at it. I'll follow up shortly.

Thank you,
Nate

**Comment by samuela** [comment]
If this is intended behavior I would find it to be highly counterintuitive based on the docs and implied usage of the option.

**Comment by kptkin** [comment]
@samuela sorry it took so long, but we are working on a new backend for the client. It should be officially released by EOQ (we already have beta releases and RC coming very soon, cleaning all the quirks). But I tried your use case and it works with our new backend. I'll link the doc with more info here: https://github.com/wandb/wandb/blob/main/core/README.md
(we also introduced a new sync cli command `wandb beta sync` that only works with the new backend). 
I will update this ticket when it is officially released, you can give it a try sooner but note it is still in beta
