### ISSUE TITLE
[App]: Mask does not show up in full screen

### ISSUE THREAD

**Issue by sachit-menon** [wandb/wandb#3523]
### Current Behavior

When images are logged with a mask, the mask shows up in the image preview, but if you click it to make it full screen the mask is not shown. 

### Expected Behavior

For the mask to show up in full screen unless the user turns it off, same as in the preview. 

### Steps To Reproduce

Log with
```
wandb.log(
        {"output" : wandb.Image(x, masks={
            "predictions" : {
                "mask_data" : mask,
            }
        })})
```
then open the run in the web app

### Environment

OS: Mac OS

Browsers: Edge, Chrome

Version:

**Comment by armanhar** [comment]
Hey there, thanks for flagging this. I'll try to reproduce this and get back to you.

**Comment by armanhar** [comment]
Hey there, apologies about the delay on this. Can you share a link to an image with this issue?

**Comment by armanhar** [comment]
Hey @sachit-menon, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by armanhar** [comment]
Hi @sachit-menon , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
