### ISSUE TITLE
[App]: Abnormal Behavior when writing a report using Chinese input methods

### ISSUE THREAD

**Issue by lwaekfjlk** [wandb/wandb#3525]
### Current Behavior

When writing one experiment report using Chinese input methods, the behavior of the whole text input UI will behave abnormally.
To be precise, the abnormal behavior of the report editor page using Chinese input methods is:
1. When using English input methods, everything is good.
2. When using Chinese input methods (provided by macOS), after selecting the correct character with Chinese input methods, the location of the cursor will change automatically to difference places and two replicate characters or words will appear on this report editer even though I only input one character or word.
3. Problem also exists when using Japanese input methods.
4. Problem do not exist when editing the headline or the abstract for the report, only exists for the editing of the main part of the report.

### Expected Behavior

Have the save behavior as English input methods

### Steps To Reproduce

1. Go to create a new report
2. Type in the main part of the report using English input methods

### Environment

OS: macOS

Browsers: Chrome

Version:

**Comment by ash0ts** [comment]
Hello @lwaekfjlk,
I apologize for the problems you're facing in writing your reports in Chinese and Japanese. Would you be able to provide a link to the report or a gif showing this behavior? I will be inputting a ticket for our engineers to fix as we value the literature provided by all of our users. 
Thank you!

**Comment by lwaekfjlk** [comment]
![case](https://user-images.githubusercontent.com/49915633/163600094-e04ff38b-e8a8-442e-98f1-c5e86f28b73c.gif)
Thanks a lot for your reply. Here is one simple example for this possible web error.

**Comment by ash0ts** [comment]
Hello @lwaekfjlk,

If possible can you check the settings for your input sources on your keyboard? What browser are you using? 
I have tested this behavior on Safari and found I could not recreate the issue shown in your video. Linked is my video of an identical recreation. 

https://user-images.githubusercontent.com/93145909/163839600-62c7101a-0023-4e67-ab78-fa37eaf39f01.mov

**Comment by lwaekfjlk** [comment]
Hi, you can see that after each time you confirm the Chinese word, the location of the cursor is moved to the beginning of the line. It should not be the normal behaviour.
In Safari, I do found the same behaviour like yours. And the GIF is related to Chrome 100.0.4896.88.

**Comment by ash0ts** [comment]
@lwaekfjlk,

I escalated this to our engineers to look at. Thank you for bringing this to our attention. We really appreciate this

**Comment by sephmard** [comment]
Hello @lwaekfjlk! We appreciate your patience. My awesome colleague @altay has been investigating this and we believe the issue to be resolved. Can you please test this and confirm on your side when you have a chance?

**Comment by lwaekfjlk** [comment]
Awesome! Yes, this bug has been fixed. Thank you for that!
