### ISSUE TITLE
How to plot two different runs/charts of different axis on a single chart

### ISSUE THREAD

**Issue by zahidmb** [wandb/wandb#3531]
Hi, 
I want to plot different runs having different x-axis values. Say, first run have x-axis from 0-100 whilst second run has x-axis from 100-200. How can i plot these two runs on a single chart. I can do this using simple python and matplotlib. Curious how to do this with wandb. Thanks.

I have attached a sample chart explaining what i want. 

![CIFAR10 Niid _Clients-RN_G-ResNet_accuracy -Code_json_0604-aug](https://user-images.githubusercontent.com/46418998/163942973-02b7ea8a-af38-4bfc-aa0c-9258bf9da4f9.jpg)

**Comment by ramit-wandb** [comment]
Hi @zahidmb,

This is definitely possible! You can add another metric to the chart by adding the new metric in the "Y Axis" option.

Thanks,
Ramit

**Comment by zahidmb** [comment]
Hi @ramit-wandb,
Thanks for your reply. I am sorry but i couldn't get it properly. I know that i can plot multiple runs on same chart. My question is how to change their **x-axis scale**. For example,

i train model A for 1 epochs. then train model B for 2 epochs. By default they both have same x-axis scale i.e. 0-2.

I want to plot model A on x-axis scale 0-1 (its already okay) and B from x-axis scale 1-3 (2 epochs). More precisely, model B should start where model A ends (x-axis scale).  

![W B Chart 4_20_2022, 7 51 57 AM](https://user-images.githubusercontent.com/46418998/164119691-3dd04115-6cce-436a-a3b4-9e1ef8f9c684.png)

This is the sample what i am trying to do. Here some models are plotted on **x-axis scale 0-50** and some models are plotted on **x-axis scale 50-100**.

![image](https://user-images.githubusercontent.com/46418998/164120172-15126b63-901f-4a4e-9560-deb8fa41790c.png)

**Comment by ramit-wandb** [comment]
Hi @zahidmb,

Correct me if I am wrong, but I believe you are looking for something like this:

<img width="700" alt="Screen Shot 2022-05-04 at 11 14 39 AM" src="https://user-images.githubusercontent.com/93002515/166799606-6c5b5390-7741-4f2a-b21b-585b3e5d7bbe.png">

This is completely possible in wandb. We employ a "step" variable that keeps track of the time at which a call to `wandb.log` is made, on the basis of which we synchronize our charts. You would want to log `Model B` after you are done logging `Model A`. Here is the code I used to create the above chart:

```python3

import wandb

run = wandb.init()

# Step 0
run.log({
    'Model A' : 0.2
})

# Step 1
run.log({
    'Model A' : 0.3,
    'Model B' : 0.5
})

# Step 2
run.log({
    'Model B' : 0.7
})

# Step 3
run.log({
    'Model B' : 0.8
})

run.finish()
```

Please let me know if you have any other questions regarding this.

Thanks,
Ramit

**Comment by zahidmb** [comment]
Hi, 
I am sorry for the late reply. 

Yes, it is exactly what I want to do however in my scenario, **model A and model B have a different wandb.inti(...)**. 

More specifically, these models are usually **trained separately** using different scripts. So, in my scenario, i am still unable to plot different models having different 'run' means wanb.init(....).

**Comment by zahidmb** [comment]
> Ah, you should be able to resume the run and the second wandb process will pick up where the first one left off. [Here](https://docs.wandb.ai/guides/track/advanced/resuming) are some docs about how to resume runs.
> 
> Thanks, Ramit

Thanks for your reply. I am not sure whether I perfectly got your point or not. What I understood is that I can resume a previous run so the next run will resume its `__step_` value from the end of the last run.

However, in my scenario, 

1. I have already **completed models training** means all models have **finished their runs**. So, how can I change the values of a completed/finished run (means **how to change the value of a `__step_` variable of a saved run**)? 

2. I have to plot many models on the same chart with different starting points (x-axis/ _step) like model A might start from` _step = 0`, model B might start from `_step = 5`, model C might start from the `_step = 50` and so on. 

I also tried to set the `Wall Time` as X-axis to solve my problem however, that doesn't properly address my problem as well. So, it seems like i need to **modify** the `_step` values of the **saved run(s)** to solve my problem. 

Looking for your suggestion please.

**Comment by ramit-wandb** [comment]
Hey @zahidmb,

Ah, I apologize if I was not specific enough. For a run that has already been completed, I'm afraid there is no way to alter the `step` variable associated to a run. But, for all future runs, the following pattern can be followed:

```python3
run = wandb.init()

run.log({'A' : 0})
run.log({'A' : 1})
run.log({'A' : 1})

run.finish()

step = run.step

run = wandb.init() # New run

run.log({'B' : 0}, step=step)
run.log({'B' : 0.5})
run.log({'B' : 0.75})

run.finish()
```

This should allow you to offset your step by the previous run's steps so that they are arranged in the desired manner.

Thanks,
Ramit

**Comment by zahidmb** [comment]
Hi,
Thanks for your reply. For new runs, I would follow it. I got it that there is no straightforward way to change the `step` variable. However, I was just wondering if there is any workaround to do so. 

Like is it possible to download/export the run in .csv then modify the history data and then import it back to wandb.... or something like this???

Another question/suggestion: 
Why wandb doesn't allow to set any variable as X-axis like config.loss or any other parameter?

thanks.

**Comment by ramit-wandb** [comment]
Hi Zahid,

Unfortunately not, the run history for any given run is immutable - you can not go back into a run and change its history. We also do allow you to change your X Axis to any logged metric - but in order to do so, the X-axis metric and the Y-axis metric has to be logged at the same step. This is done to ensure that your metrics are synchronized correctly. If you are not seeing the option to set a certain metric as your X-Axis metric, chances are that you are logging them at different steps.

[Here](https://docs.wandb.ai/guides/track/log/logging-faqs#why-am-i-seeing-fewer-data-points-than-i-logged) is some information on how you can improve this.

Thanks,
Ramit

**Comment by zahidmb** [comment]
I got it that there is no way to modify the saved runs history. Thanks.
