### ISSUE TITLE
[App]: Plots disappearing during run

### ISSUE THREAD

**Issue by timothybrooks** [wandb/wandb#3545]
### Current Behavior

My plots keep disappearing! All plots under "metrics/[name]" are gone for all my active runs. How frustrating to not know what any of my metrics are. I saw a similar bug about them disappearing once finished but for me it is the _active_ runs. Please make the reappear -- thanks!

### Environment

OS:

Browsers:

Version:

**Comment by sydholl** [comment]
Hi @timothybrooks. Thank you for reporting and sorry for the inconvenience. Our backend team is addressing the issue and we should have this resolved shortly. I'll follow up once I have an update on this.

**Comment by magehrig** [comment]
I am currently experiencing the same issue

**Comment by magehrig** [comment]
It's fixed for my new runs but my ongoing run is still not showing newly logged data:
https://wandb.ai/magehrig/eRAFT/runs/392rm745/overview?workspace=user-magehrig

**Comment by ash0ts** [comment]
@magehrig 

Are you facing this issue still? If so, can you provide me details about how you are logging to `wandb`?

**Comment by timothybrooks** [comment]
The issue is occurring again for me. Metric plots are randomly disappearing. Could someone please look into it?

**Comment by ash0ts** [comment]
@timothybrooks We just rolled back a recent change to our application. Are you still facing this issue?

**Comment by timothybrooks** [comment]
I see most of them now. But metric plots are still missing for this run in particular: https://wandb.ai/timbrooks/vgan-lres/runs/2syu2tm3

**Comment by ash0ts** [comment]
@timothybrooks It went out around the same time as my comment. It may take a little longer for older runs to show their metrics. New runs should run as expected however

**Comment by ash0ts** [comment]
We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.
