### ISSUE TITLE
[Feature]: Exporting weave panels

### ISSUE THREAD

**Issue by danielegrattarola** [wandb/wandb#3548]
### Description

Currently, the kebab menu for weave panels only allows the following actions
![Screenshot 2022-04-21 at 13 08 05](https://user-images.githubusercontent.com/11634240/164445795-9d299a50-c4a5-4844-844d-e27121221e8b.png)

It would be nice to have the possibility to export a weave panel like all other types of panel. 

### Suggested Solution

Add the option to export weave panels like all other types panel. 
The interface would look like this:
![Screenshot 2022-04-21 at 13 08 22](https://user-images.githubusercontent.com/11634240/164446019-1f3f5ab4-06ef-4345-bc22-4e7cedf009ef.png)

**Comment by ramit-wandb** [comment]
Hi @danielegrattarola,

Thank you for a feature request. This is actually a feature we are working on at the moment. I'll let you know once there is some we have this available.

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
Hi @danielegrattarola !

This feature has been implemented and now you can export weave panels as CSV files! I'm closing this github issue for now, but in case you run up against any issues here, please feel free to reopen!

Thanks,
Ramit
