### ISSUE TITLE
Is there a way to delete local runs's folder automatically?

### ISSUE THREAD

**Issue by realCrush** [wandb/wandb#3564]
wandb is a perfact tool for us ML researchers, however I found runs's local folder takes a huge disk space, so I was wonder is there  a way to delete local folder right after this runs finished/crashed/failed? I implement a code based on multiprocessing and python `tempfile` module, however it always crashes and create so many empty runs like https://github.com/wandb/client/issues/1869 mentioned

My code for `main.py`:
```python
for i in range(10):
    process = Process(target=wandb.agent, args=(sweep_id, lambda: runner(wandb_config, params_default), 'realcrush', 'ON-GNN', ))
    list_process.append(process)
    process.start()
for p in list_process:
    p.join()
```

My code for `runner`:
```python
def runner(wandb_config, params_default):
    with tempfile.TemporaryDirectory() as tmpdirname:
        temp_dir = tempfile.TemporaryDirectory()
        wandb_config['dir'] = tmpdirname
        wandb.init(**wandb_config, config=params_default)
        ...
        wandb.finish()
```

An empty run created by agent: https://wandb.ai/realcrush/ON-GNN/runs/gtwbebop/overview?workspace=user-realcrush

I believe there are some error with python `tempfile` module as https://github.com/wandb/client/issues/1869#issuecomment-847464464 said, by the way, is there an official way to achive my goal?

**Comment by realCrush** [comment]
This problem is really wired, as I use python `tempfile` module and create a temp folder in `\tmp` which pass to `wandb.init(dir='xxx')` , wandb should not take too large space in `\tmp` , however when I create 20~30 parallel agents, `\tmp` quickly consume ~100G in about 18 hours, what's wrong with my code? does wandb consume local storage outside of my `tempfile` 's context? 
Another wired thing is when I stop all the runs, `\tmp` quickly become empty even **without cleaning**, so I guess wandb would consume some storage out of `tempfile`

**Comment by anmolmann** [comment]
Hi @realCrush, thanks for writing in. We're working on something that will do this automatically going forward. In the meantime, [you can use `wandb sync --clean` to sync all synced runs](https://docs.wandb.ai/ref/cli/wandb-sync) and then remove all synched run dirs locally. 
I'll also bump up the priority for this request and will follow up with you once I've an update.

**Comment by realCrush** [comment]
> Hi @realCrush, thanks for writing in. We're working on something that will do this automatically going forward. In the meantime, [you can use `wandb sync --clean` to sync all synced runs](https://docs.wandb.ai/ref/cli/wandb-sync) and then remove all synched run dirs locally.
> I'll also bump up the priority for this request and will follow up with you once I've an update.

thank u

**Comment by zimmer-m** [comment]
> Hi @realCrush, thanks for writing in. We're working on something that will do this automatically going forward. In the meantime, [you can use `wandb sync --clean` to sync all synced runs](https://docs.wandb.ai/ref/cli/wandb-sync) and then remove all synched run dirs locally. I'll also bump up the priority for this request and will follow up with you once I've an update.

Is there any news on this? It would be really nice if wandb had an option to always cleanup (locally) after itself, even in the case of an Exception Error or Crash.

**Comment by realCrush** [comment]
> > Hi @realCrush, thanks for writing in. We're working on something that will do this automatically going forward. In the meantime, [you can use `wandb sync --clean` to sync all synced runs](https://docs.wandb.ai/ref/cli/wandb-sync) and then remove all synched run dirs locally. I'll also bump up the priority for this request and will follow up with you once I've an update.
> 
> Is there any news on this? It would be really nice if wandb had an option to always cleanup (locally) after itself, even in the case of an Exception Error or Crash.

Now I just force the temp files created by wandb stored into /tmp folder

**Comment by zimmer-m** [comment]
@realCrush I do it in a similar way, however its not optimal. If for some reason the runs crash, the temporary folder will persist until reboot, which happens rarely on my cluster.

Eventually, I will have filled up several dozens of machines and my runs collapse due to no space left in /tmp, forcing me to cleanup the machines.
(wanted to tag @anmolmann in my original reply)

**Comment by anmolmann** [comment]
Thanks, @zimmer-m for writing in. I'm checking in with our team internally and will follow up with you once I've an update here. In the meantime, periodically running:
`wandb sync --clean-old-hours 24` might provide you with the desired results, we plan to eventually have a setting to auto-delete files.

**Comment by andreimargeloiu** [comment]
+1

**Comment by andreimargeloiu** [comment]
any updates on this?

**Comment by andreimargeloiu** [comment]
Thanks! My current solution is:

1. Open the terminal.
2. Type `crontab -e` to edit the cron table.
3. In the editor, add a new line with the following format:
4. `0 */4 * * * wandb sync --clean-old-hours 4`. This will run a cron job every 4 hours to clean the runs.

**Comment by mrseeker** [comment]
Bumping this since this is over a year old and I have a project that generates a lot of artifacts on a machine where harddrive space is scarse.

**Comment by punglee** [comment]
Any update about this feature?

**Comment by anmolmann** [comment]
Hey, @punglee -- this is on our TODO list, however, we are working on some improvements internally in both our infra and SDK side to make sure that the data is saved by the backend before we implement this feature. We've made some major changes to the way our data is stored (in terms of datastore we use), therefore, this is in our backlog as of now.

**Comment by punglee** [comment]
> Hey, @punglee -- this is on our TODO list, however, we are working on some improvements internally in both our infra and SDK side to make sure that the data is saved by the backend before we implement this feature. We've made some major changes to the way our data is stored (in terms of datastore we use), therefore, this is in our backlog as of now.

If there is a way that allow wandb to stop monitoring system metrics?

**Comment by anmolmann** [comment]
Hi @punglee, system metric logging can be disabled when initializing a run via `_disable_stats`. Fro example, `wandb.init(..., settings=wandb.Settings(_disable_stats=True))`. We do list the most commonly used optional environment variables that can alter your wandb setting [here](https://docs.wandb.ai/guides/track/environment-variables#optional-environment-variables). For a more details list of available options, please see [here](https://github.com/wandb/wandb/blob/bc3a09bf626f2aa74df0b526aa7eede52f30c63f/wandb/sdk/wandb_settings.py#L292) in our wandb sdk codebase. Let me know if you have any additional questions

**Comment by brianhenn** [comment]
Hi @anmolmann I am trying your workaround of running `wandb sync --clean-old-hours <n_hours>` in the `wandb` folder for a run. However, I am finding that this only tries to sync an existing run and does not actually delete any of the `run-*-*` directories inside the `wandb` folder. I also find that nothing is deleted if I try `wandb sync --clean-force`.

Are these commands supposed to remove these directories (which can be large with lots of logged images that have already been synced to the server), and if so do you have any idea what I'm doing wrong? Or should we just manually delete these folders on our own?

**Comment by anmolmann** [comment]
> Hi @realCrush, thanks for writing in. We're working on something that will do this automatically going forward. In the meantime, [you can use `wandb sync --clean` to sync all synced runs](https://docs.wandb.ai/ref/cli/wandb-sync) and then remove all synched run dirs locally. I'll also bump up the priority for this request and will follow up with you once I've an update.

Hey @brianhenn , could you please try and delete the run folders via `wandb sync --clean` and let me know if this cleans up all of the synced runs for you?

**Comment by anmolmann** [comment]
Hey everyone, closing the thread here since the cleanup of runs can be achieved by executing: `wandb sync --clean` as suggested [above](https://github.com/wandb/wandb/issues/3564#issuecomment-1111561420). In case anyone wants to automate this further, as @andreimargeloiu suggested [above](https://github.com/wandb/wandb/issues/3564#issuecomment-1535331719), one can also write a cron job and execute this cmd periodically. Please let me know if this isn't the desired solution and I'll pass that to our eng team.

**Comment by brianhenn** [comment]
Hi @anmolmann , 

No, running `wandb sync --clean` does not seem to remove wandb folders for me. It will say "no runs older than 24 hours" it there are no older runs. If I run `wandb sync --clean-force` it will say "wandb: No runs to be synced". Either way, the wandb folders are not removed from the job directories. It seems like this command is only looking to sync folders that have not been synced, not actually delete them.

**Comment by jaded0** [comment]
Yeah, I'll second that. No commands will remove the past runs. Currently, running wandb sync --sync-all continues to sync upwards of 30 jobs despite anything I do. Only rm -rf wandb/offline-run* will do it.

**Comment by mrseeker** [comment]
I second this: Sync does NOT delete the directory after its synced. I suggest changing this behaviour to:
1. Delete all files after successful sync
2. and adding a --keep-offline command for backwards compatibility.

**Comment by brianhenn** [comment]
Hi @anmolmann. Is there any response to the users here posting that `wandb sync --clean` does not actually clean up any of these directories? Thanks.

**Comment by anmolmann** [comment]
Hey @brianhenn , this is what I see in my console upon running `wandb sync --clean` with wandb SDK version: 0.18.6

<img width="721" alt="Image" src="https://github.com/user-attachments/assets/f77e9f47-f64d-487b-b5c5-ffc716d09e56" />

This command is cleaning the synced runs within the `wandb` dir. Below are the runs left in the `wandb` dir for me and the other runs prompted in the output of `wandb sync --clean` (in the above screenshot) are cleaned from the dir.

<img width="725" alt="Image" src="https://github.com/user-attachments/assets/6d1bb0eb-2d6c-4b50-9b7a-a472617cce0f" />


Could you share the output of the `wandb sync --clean` command on your end so that we can investigate the issue further?

**Comment by mrseeker** [comment]
@anmolmann Since this has been ping-ponging for over 2 years now, let me ask the question again:

Does it also clean runs synced less than 24 hours ago, or only runs older than 24 hours? When it "cleans", I expect that it cleans all runs that have been synced, not runs that have been synced and are older than 24 hours. If you have 20Gb artefacts being created every hour, that eats a lot of disk space. I expect --clean to remove all unsynced files, not only those older than 24 hours (for that, I can also run a cron script)

**Comment by anmolmann** [comment]
Hi @mrseeker , yes one can clean runs which are < 24 hours old using `wandb sync --clean --clean-old-hours 0`.

For example, I just executed a run a few minutes ago and cleaned it via the above cmd:
<img width="725" alt="Image" src="https://github.com/user-attachments/assets/2bae2fe7-0a82-4166-8989-bea1fff4cae1" />

Please let me know if this works for you.

**Comment by alberthli** [comment]
Is there any way to prevent the local caching of runs/models entirely? We've been running into the issue of our temp files filling up extremely quickly due to the training of a large model and killing our runs due to running out of disk space. It would be great to have an automatic and clean solution to this instead of us having to run cron jobs to clean the temp files. The ideal solution for us would be to only upload results to the wandb server but not save anything locally, since this is redundant.

**Comment by anmolmann** [comment]
Hey @alberthli , 
> Is there any way to prevent the local caching of runs/models entirely? We've been running into the issue of our temp files filling up extremely quickly due to the training of a large model and killing our runs due to running out of disk space. 

Regarding the above, 
Yes - you can, I'm assuming when you say local caching of runs/models - you are logging models as artifacts? If yes, then [with](https://docs.wandb.ai/ref/python/artifact/#add_file) `skip_cache=True` and `policy=immutable` in artifact's `add_dir`, `add_file` methods, this way neither staging nor cache files are created. 

For automated cleaning up, we currently do not have a way to automatically clean up wandb run dir(s). Therefore, for now you would have to rely on running a cron job or a script similar to the one below to clean up wandb run dir after a run is finished.
```
#!/bin/bash

# Run your training script
python train.py

# Sync and clean up W&B files immediately after training
wandb sync --clean --clean-old-hours 0
```

**Comment by brianhenn** [comment]
Hi @anmolmann , I was able to get wandb to clean up its files finally by running `wandb sync --clean --clean-old-hours 0` as you suggested. So thanks for pointing out this method. 

However, it's still potentially a problem that wandb will not clean up after itself automatically and requires a custom command like `wandb sync --clean --clean-old-hours 0` to do so. As other users have mentioned this fills up space and increases overhead of using wandb. Is there a plan to have this behavior available by default in the case of a successful sync? (Obviously we also want to retain the ability to run offline, but this doesn't seem incompatible with wandb automatically removing its folders after a successful sync.)

**Comment by brianhenn** [comment]
To be very clear, what I am requesting is that once the (Python) process that invoked `wandb.init` finishes and wandb has finished syncing any remaining items that need to be logged, this should result in the wandb run directories being deleted automatically. At the least this should be a configurable option or available via the Python SDK, if not the default -- what reason is there to force retention of local copies of data that have been successfully uploaded?
