### ISSUE TITLE
[Q] Is there i/o overhead concern when loging images/videos ?

### ISSUE THREAD

**Issue by wztdream** [wandb/wandb#3567]
Hi,
As wandb client is using an remote server, so it seems there will be i/o concern if we logging large mounts of data like images or videos, because you need to pass images or videos through the internet. Or may be wandb only sending some kind of meta information to the remote server thus there is no such concern?

If it does have this i/o concern, does it mean that we have to use wandb/local if we need logging large mount of data like images or videos?

**Comment by vanpelt** [comment]
By default data is streamed to our servers over the internet.  This happens async from your script so you should see any overhead impact unless your internet connection is slow and then you would only see the impact when the script is finishing as we wait for all uploading to complete.

You can use artifact references to just store the metadata in wandb: https://docs.wandb.ai/guides/artifacts/references

Using this approach means you won't be able to visualize that data in wandb as we don't have access to it.

In the coming months we'll be rolling out a feature that will let you choose what cloud provider / region to store the data in so you can always maximize speed and data locality.

Where are you running your training jobs today?

**Comment by wztdream** [comment]
@vanpelt thank you.
