### ISSUE TITLE
[Q] WandB TensorBoard pushing data to server. (No tensorboard tab on the server)

### ISSUE THREAD

**Issue by Msameim181** [wandb/wandb#3572]
I tried using tensorboardX, but it has a lot to change with the name of the chart.

So I'm using torch.utils.tensorboard instead.

But in the server of W&B, there is no tab for tensorboard. What am I doing wrong? 
For the record, I can see charts on the local tensorboard.

TensorBoard part:
```
from torch.utils.tensorboard import SummaryWriter
...
    # Create a run
    tb_logger = SummaryWriter(log_dir=Path(log_dir, name))
...
     # Logging
    tb_logger.add_scalar('Loss/Step Loss', loss.item(), global_step)
    tb_logger.add_scalar('Loss/Train Loss (Step)', epoch_loss_step, global_step)
    tb_logger.add_scalar('Process/Step', global_step, global_step)
    tb_logger.add_scalar('Process/Epoch', epoch, global_step)
    tb_logger.flush()
```

WandB part:
```
wandb_logger = wandb.init(
        project = "...", 
        entity = "....", 
        sync_tensorboard = True,
        name = run_name, 
        tags = [
            f'{model}', 
            f'{run_name}', 
            f'{device}'
        ],)
wandb_logger.config.update(config)
...
    # Logging
    wandb_logger.log({
        'Loss/Step_Loss':            loss.item(),
        'Process/Step':                 global_step,
        'Loss/Train_Loss_(Step)':    epoch_loss_step,
        'Process/Epoch':                epoch
    })
```

**Comment by vanpelt** [comment]
The tensorboard tab only works when using our cloud server.  Are you running wandb/local?

**Comment by Msameim181** [comment]
The setting is set for online and every run will sync to W&B servers if is that what you need, But I run it on my local computer.

**Comment by vanpelt** [comment]
You're not running `wandb local` anywhere right?

If your syncing to the cloud please share a link to a run that doesn't have tensorboard tab.

**Comment by Msameim181** [comment]
No for sure, I think it requires Docker which I don't have.

Of course, This is a [Link ](https://wandb.ai/rsna-bone-age/Bone-Age-RSNA/runs/ux7puz44) to a recent run, but I'm not sure you be able to see it or not.

I used Pytorch. And WandB and tensorboard together as I explain in the first place.

**Comment by Msameim181** [comment]
@vanpelt Any update?

**Comment by ash0ts** [comment]
Hello @Msameim181,

[Looking at this section in our docs](https://docs.wandb.ai/guides/integrations/tensorboard#pytorch-and-tensorboard), can you try seeing if you can upload the Pytorch Profiler JSON as such and see if that alleviates the issue?
`wandb.save(glob.glob(f"runs/*.pt.trace.json")[0], base_path=f"runs")`

**Comment by Msameim181** [comment]
And When I used this:
``` wandb.save(glob.glob(f"tensorboard/*.pt.trace.json")[0], base_path=f"tensorboard") ```

I got this: 
``` 
    wandb.save(glob.glob(f"tensorboard/*.pt.trace.json")[0], base_path=f"tensorboard")
IndexError: list index out of range 
```

Just in case you want to know the result.

**Comment by ash0ts** [comment]
​Hi @Msameim181 ,

We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.
​
Best,
Anish
​

**Comment by Msameim181** [comment]
No, nothing changed.
I tried these:
``` 
log_dir = "./tensorboard"
run_name = "test123"
tb_logger = SummaryWriter(log_dir=Path(log_dir, run_name))
```

```wandb.tensorboard.patch(root_logdir="./tensorboard")```
and
```wandb.tensorboard.patch(root_logdir=f"./tensorboard/{run_name}")```

**Comment by ash0ts** [comment]
Hello @Msameim181,

Are you able to provide a reproducible minimal example for us to look at? I am unable to run into the issues you mentioned with our various Tensorboard syncing methods.

Thank you!

**Comment by Msameim181** [comment]
Sure,
These are the codes that I'm using in my projects:
WandB logger: [link](https://github.com/Msameim181/RSNA-Bone-Age/blob/main/utils/wandb_logger.py)
TensorBoard logger: [link](https://github.com/Msameim181/RSNA-Bone-Age/blob/main/utils/tensorboard_logger.py)

**Comment by anmolmann** [comment]
@Msameim181 , Could you try syncing to new run id: `wandb sync [PATH] --id new_run_id`? 
- Generate the new run id via `wandb.util.generate_id()` first.

**Comment by Msameim181** [comment]
Yes, I stored all of the runs log files, Also ```tfevents```.

So, I chose one of the previous runs, I looked for ```run_id``` from the runs page.
The run link: https://wandb.ai/rsna-bone-age/Bone-Age-RSNA/runs/1uy2gz0y
The command:
```
>> wandb sync tensorboardLocal/20220523_110557_MobileNetV3_Pre/events.out.tfevents.1653287760.DESKTOP-ISIIVT7.11940.0 --id 1uy2gz0y
Found 1 tfevent files in C:\Users\mahdi\Desktop\Github_Work\1\RSNA-Bone-Age\tensorboardLocal\20220523_110557_MobileNetV3_Pre
Syncing: https://wandb.ai/rsna-bone-age/RSNA-Bone-Age/runs/1uy2gz0y ...
```

And still nothing on the run page:
![image](https://user-images.githubusercontent.com/25700939/171607028-ba5756c2-6e5c-4d92-8e5a-ebc4e961b6e2.png)

Any idea?

**Comment by Msameim181** [comment]
Yes, I stored all of the runs log files, Also ```tfevents```.

So, I chose one of the previous runs, I looked for ```run_id``` from the runs page.
The run link: https://wandb.ai/rsna-bone-age/Bone-Age-RSNA/runs/1uy2gz0y
The command:
```
>> wandb sync tensorboardLocal/20220523_110557_MobileNetV3_Pre/events.out.tfevents.1653287760.DESKTOP-ISIIVT7.11940.0 --id 1uy2gz0y
Found 1 tfevent files in C:\Users\mahdi\Desktop\Github_Work\1\RSNA-Bone-Age\tensorboardLocal\20220523_110557_MobileNetV3_Pre
Syncing: https://wandb.ai/rsna-bone-age/RSNA-Bone-Age/runs/1uy2gz0y ...
```

And still nothing on the run page:
![image](https://user-images.githubusercontent.com/25700939/171607028-ba5756c2-6e5c-4d92-8e5a-ebc4e961b6e2.png)

Any idea?

**Comment by anmolmann** [comment]
Thanks for the additional context @Msameim181.
[1] is the code you're tracking in this particular run already instrumented with Tensorboard calls? I'm suspecting it might not be the case. Reason i'm asking: The intended use of the `sync_tensorboard` flag is to easily align code instrumented with Tensorboard specific calls directly to the W&B workspace - [here](https://github.com/wandb/examples/blob/master/examples/tensorboard/tensorboard-tf2-kerasfit/train.py) is a good example from our examples repo that shows what that could look like in practice. It's mainly meant to allow those who have spent a lot of time working with Tensorboard to not have to reinstrument their scripts with all W&B API calls, and just flip the `sync_tensorboard` flag to True in their call to `wandb.init()`.
[2] Could you also try adding `writer = SummaryWriter(f"runs/{experiment_name}")` (or `./tensorboard/{run_name}` in your case a custom output dir) after your `wandb.init` call? Let me know if this helps.

**Comment by loganlebanoff** [comment]
Could it be that `sync_tensorboard` doesn't work on Windows? I got this [example](https://github.com/wandb/examples/blob/master/examples/tensorboard/tensorboard-tf2-gradienttape/train.py) to work on Linux (the TF tab shows up in the wandb UI) , but it doesn't work on Windows for me (the TF tab doesn't show up). I used a fresh python environment with wandb==0.12.17 and tensorflow/tensorboard==2.9.1

**Comment by anmolmann** [comment]
@loganlebanoff , it seems like you might be right. @Msameim181 , could you please confirm once if this is the case? I couldn't replicate the issue on my end. 
Also, If you could your environment? Then, I'll try again to replicate it on my end and also, file a bug report & ask help from our eng team.

**Comment by Msameim181** [comment]
@anmolmann, Well, I'm using Windows 10 in my case. I didn't try on Linux, so the Theory is half true on my side.
Environment:
Python==3.9.0
wandb==0.12.14
tensorboard==2.8.0
torch==1.11.0+cu113

**Comment by anmolmann** [comment]
> @anmolmann, Well, I'm using Windows 10 in my case. I didn't try on Linux, so the Theory is half true on my side.
> Environment:
> Python==3.9.0
> wandb==0.12.14
> tensorboard==2.8.0
> torch==1.11.0+cu113

Did you get a chance to try this out on Linux platform with WSL on your Windows instead?

**Comment by Msameim181** [comment]
I think I could try. Why don't you give me a couple of days, to see what I can do? I'll give you the update shortly. Thanks.

**Comment by Msameim181** [comment]
Yes, It seems about right. On WSL works perfectly. the TF tab appears on the new run page

![image](https://user-images.githubusercontent.com/25700939/173182740-98b017a6-4004-42b3-a1c2-e8c15199ea4c.png)

Also, the TB logs seem to find a way to be in main page charts (It's a little odd but okay).

![image](https://user-images.githubusercontent.com/25700939/173182714-ec31236d-5036-4f1c-ab8e-e10bd156978a.png)

**Comment by Msameim181** [comment]
> wandb sync tensorboardLocal/20220523_110557_MobileNetV3_Pre/events.out.tfevents.1653287760.DESKTOP-ISIIVT7.11940.0 --id 1uy2gz0y

I was trying to use this on WSL to sync tensorboard to wandb, But nothing. The status goes to sync and uploading data, but No results.

![image](https://user-images.githubusercontent.com/25700939/174546059-48932e38-8f6c-4e63-a82b-0b53e72c4547.png)

![image](https://user-images.githubusercontent.com/25700939/174546109-fccc9f5d-82ab-4cab-a7a0-5ba1e9bdd810.png)
