### ISSUE TITLE
[CLI]: Agent ends without killing script on Slurm.

### ISSUE THREAD

**Issue by lemmersj** [wandb/wandb#3600]
### Describe the bug

When running sweeps on Slurm, the agent occasionally ends without ending the underlying python script. This results in a cascade of crashes as Slurm launches jobs on nodes where resources are not available. The script itself continues logging successfully.

The associated Slurm files contain a series of 429 and Network Errors, but no traceback.

### Environment

WandB version: 0.12.14

OS: Ubuntu 20.04

Python version: 3.7.12

Versions of relevant libraries:
Slurm: 0.4.3
Munge: 0.5.13

### Additional Context

We typically run our agents with --count 1. The problem does not appear on shorter (i.e., < 1 hour) jobs.

**Comment by nate-wandb** [comment]
Hi @lemmersj, I'm sorry you're having this issue and this does indeed look like a bug.

Could you provide any steps necessary to reproduce the issue?

I know you are getting this only occasionally but if we can test and reproduce it once it may help with the debugging.

Thank you,
Nate

**Comment by lemmersj** [comment]
Hi Nate,

Thanks for the response. I've attached an [MWE](https://github.com/wandb/client/files/8616887/MWE.zip) of my current project (I think I included all of the necessary files, but if anything is missing let me know), as well as the conda environment, slurm script, and sweep parameters. I was able to intentionally produce the issue today by:

1. Launching the first 21 jobs in the sweep with --count 1
2. Waiting about four hours---a handful of the jobs finished in this time.
3. Running scancel -u to end the remaining jobs.

Let me know if there's anything else I can provide.

-Stephan

**Comment by nate-wandb** [comment]
Hi @lemmersj, sorry for the delay on this. The 429 Network errors are being caused by rate limiting coming from our servers. [Here ](https://docs.wandb.ai/guides/track/limits)is some information on what our limits are and how to stay under them.

If it is necessary for you to log this often, another option would be to use `wandb.init(mode='offline')` and then sync your run folders with `wandb sync` after your run is completed to avoid making any network calls during your training.

**Comment by lemmersj** [comment]
Hi Nate,

Thanks for the response. I will certainly take the number of sweeps and rate at which I'm sending data into account in future development.

Would you mind clarifying for me how the 429 errors lead to the issue where jobs continue to run after the agent (and therefore Slurm) has ended? Since it concerns shared resources, I'd like to have a bit more detail as to what's happening in case I encounter similar issues in the future.

-Stephan

**Comment by nate-wandb** [comment]
Hi @lemmersj, 
Are you still seeing this after using `mode="offline"`? A few W&B processes will still continue to attempt to upload the results until they are successful, even if the main process has been killed. If you would like to kill these processes you can use `pkill -9 wandb` but this will prevent your data from showing up in the UI until you run `wandb sync` later. 

Thank you,
Nate

**Comment by lemmersj** [comment]
Hi @nate-wandb,

Since (in this case) I'm instantiating the logger through pytorch_lightning.logger.WandbLogger, I didn't use wandb.init(mode="offline") as suggested, but used "wandb off" as part of my slurm launch script.

The 429 errors are resolved, but the more critical issue of jobs continuing to run is not. The wandb-service and the python script remain active despite the slurm job being killed. If there are any other expected wandb processes, it appears that they successfully shut down.

-Stephan

**Comment by nate-wandb** [comment]
Hi @lemmersj, 
Could you possibly share the `debug.log`  and `debug-internal.log` files from the local run directory on your training machine? 

The `pytorch_lightning.logger.WandbLogger` has the argument `offline=` which can be set to `True` if you wanted to try the run with `wandb` in offline mode. 

Are you logging any large data such as histograms or images that may be taking a while to upload upon completion of the training script? 

What I think may be happening is that these W&B processes are staying active while they make network calls to upload your data to the UI. The `debug.log` files will be able to show if this is what is happening. 

Thank you,
Nate

**Comment by nate-wandb** [comment]
Hi @lemmersj,
This looks like a bug. It looks like when we try to save your Conda environment it is causing an error. Once that error occurs something goes wrong and W&B gets stuck. I'll report this to our engineering team. 

It looks like the error is caused but W&B not being able to find your conda folder. Is there any reason to believe this has been renamed from "conda" or if there is any other reason that this is not being found?

Thank you,
Nate

**Comment by lemmersj** [comment]
Hi @nate-wandb,

I have conda loaded through the modules package (e.g., _module load miniconda3_ prior to calling my script). The exact details of how this package works are beyond my expertise, but it might be relevant.

Additionally, I load the environment itself through the absolute filepath (/network_drive/username/conda_envs/env_name) instead of allowing conda to resolve it automatically, meaning that some expected environment variables/paths might not be set.

-Stephan

**Comment by nate-wandb** [comment]
Hi @lemmersj,
I've reported this as a bug so that we can handle the exception where we can't find the Conda env. This is strange that though that this only shows up occasionally. Are all of your runs using this same flow of importing the Conda environment in this way? 

My guess is that this is raising the error on every run but it isn't causing the run to hang every time. Could you possibly send the debug logs from a run that was successful? 

Thank you,
Nate

**Comment by lemmersj** [comment]
Hi @nate-wandb,

Sorry for the slow response. We haven't been able to find anything that we're sure was successful, since I never kept track of what completed successfully (not sure I could have if I wanted to). If you give me further guidance on what I'm looking for in the log files, I could try to find something with grep.

-Stephan

**Comment by nate-wandb** [comment]
Hi @lemmersj, after looking into this it looks like the issue is likely caused by a temporary inability to connect to the network drive that the Conda env is stored on. We typically recommend having any files that `wandb` needs to read/write to located on the local hard drive. 

That said, I've reported the bug that wandb will hang if it is not able to local the condo env so we can make the SDK more robust to this type of issue. 

Thank you,
Nate

**Comment by lemmersj** [comment]
Hi @nate-wandb, 

Thanks for looking into it! We will take this into account in the future.

-Stephan

**Comment by nate-wandb** [comment]
Happy to help! I'll follow up if we can get a fix on the client getting stuck issue

**Comment by nate-wandb** [comment]
Hi @lemmersj, would it be possible to test this with the latest version of `wandb` (0.13.9)? We think this may have been resolved since you first reported this.

Thank you,
Nate

**Comment by lemmersj** [comment]
Hi @nate-wandb ,

Sure. I'll upgrade and check with my next experiments.

-Stephan

**Comment by lesliewandb** [comment]
Hi @lemmersj , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by Kartik-Neralwar** [comment]
> Hi @lemmersj, would it be possible to test this with the latest version of `wandb` (0.13.9)? We think this may have been resolved since you first reported this.
> 
> Thank you, Nate

Hi, I encountered the same problem on wand 0.13.3 .

Using higher version (> 0.13.3) gives an error when importing wandb and wandb.keras: 
`AttributeError: 'NoneType' object has no attribute 'message_types_by_name'`

Importing protobuf/3.20.1 solves the error with wandb. 
However, it gives a different error with wandb.keras : 
```
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

The packages (modules) that I use currently:
 1) anaconda/3/2021.11                                   5) keras/2.6.0                
 2) cuda/11.4                                                      6) keras-preprocessing/1.1.2  
 3) cudnn/8.2.4                                                  7) protobuf/3.20.1            
 4) tensorflow/gpu-cuda-11.4/2.8.0               8) wandb/0.14.2

**Comment by lemmersj** [comment]
@nate-wandb @lesliewandb 

Sorry for the slow response. It does appear that the upgrade to 0.13.9 resolves this issue---I've checked with the previously posted MWE on my system, and no one else in the lab has reported the issue since upgrading. Thanks!
