### ISSUE TITLE
Exception: The wandb backend process has shutdown

### ISSUE THREAD

**Issue by GiorgioBarnabo** [wandb/wandb#3625]
Hi everyone,

I have been using the WandB logger on Pytorch Lightning for a while now, and it keeps on randomly crashing with the following error: "Exception: The wandb backend process has shutdown".

I launch the same script several times on the same machine (same docker container and same gpu). Inside the script, I create a pytorch lightning model and I use the weight and biases logger to monitor the results. Here is the code:

**wandb_logger = pl.loggers.WandbLogger(
reinit=True,
settings=wandb.Settings(start_method="fork"),
project = "Misinformation_Detection",
entity = "misinfo_detection",
save_dir = os.path.join(project_folder,"out","training_logs","wandb"),)**

In addition, inside the same script, I need to instantiate and delete the same model several times. For this reason, at the end of every run I do the following:

**wandb_logger.experiment.finish()**

Am I doing something wrong?

Thanks. Best,

Giorgio

```python 

```

```shell

```

### Environment

WandB version: 0.12.16

Python version: 3.6.9

**Comment by GiorgioBarnabo** [comment]
Hi Ramit,

thank you very much for your quick answer. First of all, I made a mistake. Here is the updated information on my system:

"os": "Linux-4.15.0-135-generic-x86_64-with-glibc2.10"
"python": "3.8.8"

As for the behaviour. Basically, I connect to the VPN, that to the cluster through ssh. When inside the machine,
I create a docker and I run the same script several times on the same gpu. Inside each process, I open and close
several wandb runs as explained in my previous posts. To keeps the code running I use screen.

Now, for some time wandb runs are correctly created and they appear on the web interface. They what they are expected
and then they finish. After a while though and quite randomly apparently, some runs simpy crash or they appear as running but they seem kind of stuck. In addition, when I go back to the screens that I have previously created to keep the scripts running seem kind of freezed. 

I attached the two files that you requested.

[debug-internal.txt](https://github.com/wandb/client/files/8636792/debug-internal.txt)
[debug.txt](https://github.com/wandb/client/files/8636793/debug.txt)

Thank you in advance.

Best,

Giorgio

**Comment by ramit-wandb** [comment]
Hey Giorgio,

Apologies for the delay here. I looked through your debug files, and unfortunately there does not seem to be anything that stands out. One quick question: Is it possible that your code is making calls to `wandb` after your call to `wandb.finish()`? That would be one way through which this error could occur.

Additionally, just to understand the behavior of this error, is this error happening randomly or deterministically?

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
​Hi Giorgio, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
