### ISSUE TITLE
[CLI]: Logging media with leading / as key leads to permission denied

### ISSUE THREAD

**Issue by sebimarkgraf** [wandb/wandb#3656]
### Describe the bug

```python 
import wandb
wandb.init(...)

wandb.log({"/test_image": wandb.Image(...)})
```

```shell
Permission Error: [Errno 13] Permission Denied: '/test_image_0_1823490.png'
```

The issue here is the joining of the key together with the path in `wandb/sdk/data_types/base_types/media.py`.
Joining with a leading slash leads to the file having a root directory as destination, which will be blocked on most devices.

A decent solution could be cleaning the key to not have leading slashes or throwing an error that makes this easier to debug.

### Environment

WandB version: 0.12.13 and 0.12.16

OS: Linux

Python version: 3.8

Versions of relevant libraries:

**Comment by ash0ts** [comment]
Hello @sebimarkgraf,

The error you are facing does not have to do with the leading slash in the key you are logging to `wandb`. If you take a look at [this colab](https://colab.research.google.com/drive/1PjWHz3vvoMZlA25ffA56AUw_3vSwaSGx?usp=sharing) you can see that the image I simulated logs properly to `wandb`, albeit with a specific nesting.

`Permission Error: [Errno 13] Permission Denied:`
occurs when a file you are trying to open is opened by a user who does not have the proper permissions, or if you are trying to open a file that is actually a folder. [Here is a SO post that explains some workaround to ensure you don't face this.](https://stackoverflow.com/questions/36434764/permissionerror-errno-13-permission-denied).

Are you passing in a filepath to your call to `wandb.Image`? If so, I would recommend assigning the `wandb.Image` to an intermediate variable before passing it to `run.log` to determine if the creation of the `wandb.Image` is the actual problem

**Comment by sebimarkgraf** [comment]
Hi @ash0ts,

Thanks for your swift reply and the reproduction of the issue.

Your Colab suffers from the same problem. Just add a cell at the end with `!ls /`.
It just does not produce any errors because Colabs have a writable root folder by default.

**Comment by ash0ts** [comment]
Hello @sebimarkgraf,

I misunderstood your issue earlier. I see the problem that you have mentioned. Thank you for bringing this to our attention! We really appreciate it. I will raise this to our engineers to fix.

For more context, can you let us know why you have keys that have a leading slash to it?

**Comment by sebimarkgraf** [comment]
No problem!

Thanks for raising the issue!

I did not have them deliberately, but evaluated a prefix dynamically that evaluated to the empty string.

Just raised it due to the security issues of writing to the root directory.
