### ISSUE TITLE
Can not run in Ubuntu - getting "cannot import name '_psutil_linux' from partially initialized module 'psutil'"

### ISSUE THREAD

**Issue by rohan-paul** [wandb/wandb#3661]
### Describe the bug

As soon as I run `import wandb` get below error

```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.6) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?943da16a-89e7-439b-aac8-a89d1b29988c)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_41487/3602696945.py in <module>
----> 1 import wandb

~/.local/lib/python3.9/site-packages/wandb/__init__.py in <module>
     30 from wandb.errors.term import termsetup, termlog, termerror, termwarn
     31 
---> 32 from wandb import sdk as wandb_sdk
     33 
     34 import wandb

~/.local/lib/python3.9/site-packages/wandb/sdk/__init__.py in <module>
     10 from .wandb_config import Config  # noqa: F401
     11 from .wandb_history import History  # noqa: F401
---> 12 from .wandb_init import _attach, init  # noqa: F401
     13 from .wandb_login import login  # noqa: F401
     14 from .wandb_require import require  # noqa: F401

~/.local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py in <module>
     33 
     34 from . import wandb_login, wandb_setup
---> 35 from .backend.backend import Backend
     36 from .lib import filesystem, ipython, module, reporting, telemetry
     37 from .lib import RunDisabled, SummaryDisabled
...
---> 26 from . import _psutil_linux as cext
     27 from . import _psutil_posix as cext_posix
     28 from ._common import ENCODING

ImportError: cannot import name '_psutil_linux' from partially initialized module 'psutil' (most likely due to a circular import) (/usr/lib/python3/dist-packages/psutil/__init__.py)
```

### Environment

WandB version:

OS: Ubuntu 20.04

Python version: 3.9.12.64

**Comment by ramit-wandb** [comment]
Hi Rohan,

Could you run the following 2 commands and retry this?

```
sudo apt-get install python-dev
pip install -U psutil
```

This should likely resolve this error.

Thanks,
Ramit

**Comment by rohan-paul** [comment]
> Hi Rohan,
> 
> Could you run the following 2 commands and retry this?
> 
> ```
> sudo apt-get install python-dev
> pip install -U psutil
> ```
> 
> This should likely resolve this error.
> 
> Thanks, Ramit

Thanks v.much. That solved it...

**Comment by ahmedazzam991** [comment]
azzam@azzam-VirtualBox:~$ aws configure
Traceback (most recent call last):
  File "/usr/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/usr/lib/python3/dist-packages/awscli/clidriver.py", line 17, in <module>
    import botocore.session
  File "/home/azzam/.local/lib/python3.8/site-packages/botocore/session.py", line 29, in <module>
    import botocore.credentials
  File "/home/azzam/.local/lib/python3.8/site-packages/botocore/credentials.py", line 35, in <module>
    from botocore.config import Config
  File "/home/azzam/.local/lib/python3.8/site-packages/botocore/config.py", line 16, in <module>
    from botocore.endpoint import DEFAULT_TIMEOUT, MAX_POOL_CONNECTIONS
  File "/home/azzam/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 24, in <module>
    from botocore.awsrequest import create_request_object
  File "/home/azzam/.local/lib/python3.8/site-packages/botocore/awsrequest.py", line 19, in <module>
    from urllib3.connection import VerifiedHTTPSConnection
ImportError: cannot import name 'VerifiedHTTPSConnection' from 'urllib3.connection' (/home/azzam/.local/lib/python3.8/site-packages/urllib3/connection.py)

Hi everyone, How I can fix "ImportError: cannot import name 'VerifiedHTTPSConnection' from 'urllib3.connection" ?
