### ISSUE TITLE
[CLI]: `Artifact.download()` fails silently when `wandb.init(..., mode="disabled")`

### ISSUE THREAD

**Issue by samuela** [wandb/wandb#3672]
### Describe the bug

`Artifact.download()` fails silently when wandb is `init`'d with `mode="disabled"`. I would expect that `mode="disabled"` would disable logging, but not silently prohibit the use of `Artifact`s.

How does one use an Artifact without logging or creating a new `wandb.Run`?

```python 
import wandb

if __name__ == "__main__":
  with wandb.init(
      project="playing-the-lottery",
      entity="skainswo",
      mode="disabled",
  ) as wandb_run:
    artifact_a = wandb_run.use_artifact("mnist-mlp-weights:v0").download()
    print(f"artifact_a: {artifact_a}")
    print(f"artifact_a == '': {artifact_a == ''}")

  with wandb.init(
      project="playing-the-lottery",
      entity="skainswo",
      mode="online",
  ) as wandb_run:
    artifact_a = wandb_run.use_artifact("mnist-mlp-weights:v0").download()
    print(f"artifact_a: {artifact_a}")
    print(f"artifact_a == '': {artifact_a == ''}")
```

```shell
[nix-shell:~/dev/research/lottery]$ nixGLNvidia-510.60.02 python wandb_bug.py 
artifact_a: 
artifact_a == '': True
wandb: wandb version 0.12.16 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.12.11
wandb: Run data is saved locally in /home/ubuntu/dev/research/lottery/wandb/run-20220516_230535-1jkxyqe8
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run wild-jazz-245
wandb: ⭐️ View project at https://wandb.ai/skainswo/playing-the-lottery
wandb: 🚀 View run at https://wandb.ai/skainswo/playing-the-lottery/runs/1jkxyqe8
wandb: Downloading large artifact mnist-mlp-weights:v0, 533.54MB. 50 files... Done. 0:0:0
artifact_a: ./artifacts/mnist-mlp-weights:v0
artifact_a == '': False

wandb: Waiting for W&B process to finish... (success).
wandb:                                                                                
wandb: Synced wild-jazz-245: https://wandb.ai/skainswo/playing-the-lottery/runs/1jkxyqe8
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 1 other file(s)
wandb: Find logs at: ./wandb/run-20220516_230535-1jkxyqe8/logs
```

### Environment

WandB version: 0.12.11

OS: Ubuntu 20.04.4 LTS

Python version: Python 3.9.10

Versions of relevant libraries: The following `shell.nix` file pins all of the relevant package versions:
```nix
# Run with nixGL, eg `nixGLNvidia-510.47.03 python cifar10_convnet_run.py --test`

let
  # pkgs = import (/home/skainswo/dev/nixpkgs) { };

  # Last updated: 2022-03-07. Check for new commits at status.nixos.org.
  pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/4d60081494259c0785f7e228518fee74e0792c1b.tar.gz") {
    config.allowUnfree = true;
    # These actually cause problems for some reason. bug report?
    # config.cudaSupport = true;
    # config.cudnnSupport = true;

    # Note that this overlay currently doesn't really accomplish much since we override jaxlib-bin CUDA dependencies.
    overlays = [
      (final: prev: {
        cudatoolkit = prev.cudatoolkit_11_5;
        cudnn = prev.cudnn_8_3_cudatoolkit_11_5;
        # blas = prev.blas.override { blasProvider = final.mkl; };
        # lapack = prev.lapack.override { lapackProvider = final.mkl; };
      })
    ];
  };
in
pkgs.mkShell {
  buildInputs = with pkgs; [
    ffmpeg
    python3
    python3Packages.augmax
    python3Packages.einops
    python3Packages.flax
    python3Packages.ipython
    python3Packages.jax
    # See https://discourse.nixos.org/t/petition-to-build-and-cache-unfree-packages-on-cache-nixos-org/17440/14
    # as to why we don't use the source builds of jaxlib/tensorflow.
    (python3Packages.jaxlib-bin.override {
      cudaSupport = true;
      cudatoolkit_11 = cudatoolkit_11_5;
      cudnn = cudnn_8_3_cudatoolkit_11_5;
    })
    python3Packages.matplotlib
    # python3Packages.pandas
    python3Packages.plotly
    # python3Packages.scikit-learn
    (python3Packages.tensorflow-bin.override {
      cudaSupport = false;
    })
    python3Packages.tensorflow-datasets
    python3Packages.tqdm
    python3Packages.wandb
    yapf
  ];
}
```

**Comment by samuela** [comment]
Confirmed on 0.12.16 (latest version at time of writing) as well

**Comment by armanhar** [comment]
Hey @samuela, by using wandb.init(mode="disabled") you will make wandb act like a NOOP which is used for testing your code. So this is expected behavior.

**Comment by samuela** [comment]
This is very confusing though since my tests expect to be able to receive files from `Artifact.download`. How should one test code that uses Artifacts? 

I was under the impression that `mode="disabled"` acts as a sort of read-only mode. How does one accomplish a read-only mode `wandb.init`?

**Comment by vanpelt** [comment]
@samuela `mode="disabled"` returns mocked objects and prevents all network communication.  Since there's no way for us to know what you were actually downloading in this case you'll need add code to check if wandb is disabled (`if run.disabled:`) and then write some fixture data or custom file you can use for your assertions.

Can you share more about exactly what you're trying to accomplish?  If you want to read an existing artifact you can use our public API.  This will not create a new run:

```python
import wandb
api = wandb.Api()
art = api.artifact("skainswo/playing-the-lottery/mnist-mlp-weights:v0")
print(art.metdata)
```

More examples can be found here in our docs: https://docs.wandb.ai/guides/track/public-api-guide

**Comment by samuela** [comment]
Thanks for your response @vanpelt! I'm trying to accomplish something like the following: `step1.py` trains a model and saves the weights to an `Artifact`. `step2.py` loads said `Artifact` and does some downstream processing -- say fine-tuning on a held-out dataset or some evaluation of the model. 

I'd like both scripts to have a `--dry-mode/--test` flag that tests the scripts (using the same code paths) but does not result in any side-effects. This is easy enough for `step1.py`: I just load a tiny subset of the dataset and let it run with `wandb.init(mode="disabled")`. But it's not clear what to do for `step2.py`. In my situation I need to use real model weights in order for it to be a meaningful test, however it's not clear how to get those. I just want wandb to not have any side-effects but retrieving an Artifact is necessary.

I suppose I could branch on whether it's running in dry-run mode to determine whether to call `wandb_run.use_artifact` or `api.artifact`, but then there's two separate code paths, and it just unnecessarily complicates things.

**Comment by samuela** [comment]
Only tangentially related: The [wandb.init docs](https://docs.wandb.ai/ref/python/init) do not explain the differences between `mode="online"`, `mode="offline"`, and `mode="disabled"`.

**Comment by armanhar** [comment]
@samuela sorry about the late response. I'll update the docs to include the descriptions for the different modes. As for the use-case you mentioned, that is currently not possible so I'd suggest using the workaround you mentioned.
