### ISSUE TITLE
[Q] Is it possible to load a run config without resuming a run?

### ISSUE THREAD

**Issue by GeoffNN** [wandb/wandb#3678]
I'm trying to load model weights using `wandb.restore` for a run from a while back, but for this I need to load the `wandb.config` to initialize a model with the right architecture before loading the weights. Is there a way to do that similar to `wandb.restore`, without using `wandb.init(resume=True, run_id=...)` ?

**Comment by ramit-wandb** [comment]
Hi @GeoffNN,

You should be able to get the relevant files and config through our [Public API](https://docs.wandb.ai/guides/track/public-api-guide) as well. [This example](https://docs.wandb.ai/guides/track/public-api-guide#download-all-files-from-a-run) allows you to download your files from a given run, and similarly, you should be able to get your config through the API as:

```
run = api.run("<entity>/<project>/<run_id>")
config = run.config
```

Thanks,
Ramit

**Comment by GeoffNN** [comment]
This worked, thank you!
