### ISSUE TITLE
[CLI]: Cannot log pytorch model with artifacts

### ISSUE THREAD

**Issue by nicofirst1** [wandb/wandb#3681]
### Describe the bug

I'm trying to log my PyTorch model with an artifact, but i keep getting this error
`wandb: ERROR Error while calling W&B API: json: cannot unmarshal string into Go value of type map[string]interface {} (<Response [500]>)`

While it is labeled as error it does not raise any Exception, so the program continues but nothing is logged after that.

This is my python script
```python 
  file_name =  "saved_models/model.pth"
  save_dict = {
        "accuracy": accuracy,
        "args": args,  # NameSpace from argparse
        "epoch": epoch,
        "model_state_dict": model.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
    }

    torch.save(save_dict,file_name)

    artifact = wandb.Artifact("myModel", type="model", description="", metadata=args)
    artifact.add_file(file_name)
    self.run.log_artifact(artifact)
```

`self.run` is the ouptut of 
```
 self.run=wandb.init(
            group=group,
            entity="adaptive-speaker",
            id=run_id,
            dir=out_dir,
            config=opts,
            mode="disabled" if opts["debug"] else "online",
            #settings=wandb.Settings(start_method='fork'),
            **kwargs,
        )
```

I tried commenting out everything in the `save_dict`, but even with `save_dict={}` i still get the error.

I also tryed using `artifact.wait()`, but it just gets stuck while printing the error: 

```shell
wandb: ERROR Error while calling W&B API: json: cannot unmarshal string into Go value of type map[string]interface {} (<Response [500]>)

```

### Environment

WandB version:  0.12.16

OS: MacOS BigSur, version 11.6 (20G165)

Python version: 3.9.0

Versions of relevant libraries:
Torch: 1.11.0

**Comment by nicofirst1** [comment]
I found the error. 
The metadata filed does not accept anything that is not a string. 
I don't know if I missed some doc where this was specified or not, but it would be useful to have either a warning or an implicit cast of the kind 
`metadata={k:str(v) for k,v in metadata.items()}`

**Comment by vanpelt** [comment]
Thanks for reporting the bug!  We'll ensure we sanitize this on the client side.

**Comment by MBakirWB** [comment]
Hi @nicofirst1 ,

We have documented this bug and will update you when it is addressed. Thank-you!

**Comment by MBakirWB** [comment]
HI @nicofirst1, this bug has been fixed and will released with our next release.
