### ISSUE TITLE
[App]: Range selector doesn't work on grouped runs on web app

### ISSUE THREAD

**Issue by AntonioLopardo** [wandb/wandb#3692]
### Current Behavior

The range selector to switch between Min/Max, Std Dev, Std Err and  Sampels in grouped bar plots doesn't work on my project. We are using pykeen, a library to train models on knowledge graphs, and it logs a lot of metrics, so we end up with 450 charts on the  web interface. The bar plots initially worked without issues, but soon after we started using grouped runs to run models with different random seeds, the range selector would get stuck on Min/Max. The UI of the selector would change, but the change wouldn't be reflected in the plot. The first change in a new plot takes effect, but after that the selector has no effect and the plot always displays the Min/Max.

### Expected Behavior

Range selector working on grouped runs on bar plot, showing std dev and std err. 

### Steps To Reproduce

1.  Launch multiple grouped runs using pykeen (the issue might be more general)
2. Select the chart for one or more metrics, like hits@10
3. Toggle multiple changes with the Range selector in the grouping menu of the bar plot 
4. Close and reopen the chart, toggle more changes with the Range selector in the grouping menu of the bar plot

### Screenshots

![image](https://user-images.githubusercontent.com/8061862/169643909-1e3a7aa8-e45a-4203-afbe-706981ec2419.png)
![image](https://user-images.githubusercontent.com/8061862/169643923-f1f9e264-ca7e-4e98-ba2b-13ce9091370f.png)
![image](https://user-images.githubusercontent.com/8061862/169643935-6f09e6ce-33b4-42bd-8419-f617b4e2ace1.png)
![image](https://user-images.githubusercontent.com/8061862/169643951-45c61444-f78f-4dd2-bc25-38f4c0dce586.png)
![image](https://user-images.githubusercontent.com/8061862/169643962-8af22a39-3e53-4901-8c1c-a354ebe34ad5.png)

### Environment

OS: macOS monterey 12.3.1, ubuntu 22.04

Browsers: Chrome, Firefox

Version: Chrome 101.0.4951.64

**Comment by ramit-wandb** [comment]
Hi @AntonioLopardo,

I'm sorry you are facing this issue. Could you share a link to the workspace where you see this so that I can investigate further and report this to our engineering team?

**Comment by AntonioLopardo** [comment]
Sorry for not answering earlier, I made new plot and now they work the chart auto-generated by wandb when logging metrics still have this issue. How can I share the workspace?

**Comment by ramit-wandb** [comment]
Hey @AntonioLopardo,

You can share the workspace by simply sharing the link you use to access the workspace. We should be able to look into it then.

Thanks,
Ramit

**Comment by AntonioLopardo** [comment]
Sorry for not getting back to you earlier but the problem is still there. Here my workspace https://wandb.ai/eth_ai_center_kg_project/W2V_for_KGs?workspace=user-antoniolopardo
The problem is on the auto-generated charts for metrics like both.realistic.hits_at_5, when we try to change the range selectors in these plots it doesn't work. Generating new plots works, and that's what we ended up doing but it's still something you might want to fix

**Comment by ramit-wandb** [comment]
Hi @AntonioLopardo!

This seems to be working now, could you confirm this on your end as well?

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
​Hi @AntonioLopardo, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
​

**Comment by dlavado** [comment]
Hello, I am facing the same issue, is there any update on this?
Basically the range on histogram plots is fixed on min/max and does not change when I change to another one.

Thanks!
