### ISSUE TITLE
[Feature]: Zoom in/out charts

### ISSUE THREAD

**Issue by xy9485** [wandb/wandb#3693]
### Description

I wonder if charts can be zoomed in and out like in Tensorboard by holding alt and then scrolling?
Sometimes I don't want the whole chart is fullfilled by those curves and zooming out a bit makes it more good looking.

### Suggested Solution

If this function is missing, I'm looking forward to seeing it in the feature.

**Comment by MBakirWB** [comment]
@xy9485 ,

Thank you for writing in. Scrolling and zooming into charts is currently supported, see this example [workspace](https://wandb.ai/wandb/plots) for functionality. In the   `Charts` panel you can highlight a region on of the line plots to zoom into. In the `Custom Charts` (see [here](https://docs.wandb.ai/ref/app/features/custom-charts) for our guide on custom charts) panel you can use your mouse scroll wheel to zoom in/out of the various line/scatter plots. 

Please let me know if you have any questions.

**Comment by MBakirWB** [comment]
Hi @xy9485 ,

I hope you were successful in being able to zoom in/out of charts. I will be closing this out, but please do reach out again if you have require any assistance with our platform.
