### ISSUE TITLE
[CLI] Breaking: `wandb.init()` crashes main Process w/ PyTorch TPU VMs on Google Cloud

### ISSUE THREAD

**Issue by siddk** [wandb/wandb#3694]
### Describe the bug

When using the new TPU VM paradigm on Google Cloud with the default PyTorch VMs (in this case, the `tpu-vm-pt.11` image), W&B completely fails. Running `wandb.init()` results in a `Aborted (core dumped)`.

I was able to trace this back to the core TPU code in the library here and specifically this function [`is_tpu_available()`](https://github.com/wandb/client/blob/master/wandb/sdk/internal/tpu.py#L86) which gets called by SystemStats.

The issue is that due to the build process for this image, the Tensorflow install is a bit weird, and rather than throwing an import error, the following occurs:

```
Python 3.8.10 (default, Mar 15 2022, 12:22:08)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import wandb
>>> import tensorflow
2022-05-22 04:26:37.222843: I tensorflow/core/tpu/tpu_api_dlsym_initializer.cc:116] Libtpu path is: libtpu.so
2022-05-22 04:26:37.385183: F ./tensorflow/core/tpu/tpu_executor_init_fns.inc:148] TpuCompiler_DefaultDeviceShapeRepresentation not available in this library.
Aborted (core dumped)
```

I was able to confirm that by turning off `SystemStats`, W&B works as normal:

```
wandb.init(project=<PROJECT>, entity=<ENTITY>, settings=wandb.Settings(_disable_stats=True)
```

As an initial patch, catching this error, or just straight up disabling SystemStats on PyTorch TPU VMs would be good; as a longer-term fix, figuring out how to add the TPU Profiler functionality for these environments would be ideal! 

### Environment

WandB version: 0.12.16

OS: Linux TPU VM w/ image `tpu-vm-pt-1.11`

Python version: 3.8

**Comment by ramit-wandb** [comment]
Hi @siddk!

I'm sorry you are facing this issue. Could you run the following 2 lines of code in the same environment as a first test:

```python3
from tensorflow.python.distribute.cluster_resolver import tpu_cluster_resolver  # type: ignore # noqa
from tensorflow.python.profiler import profiler_client
```

I would like to see where exactly this error is coming from.

Thanks,
Ramit

**Comment by siddk** [comment]
Hey @ramit-wandb 

```
sidd@t1v-n-a40e9bbd-w-0:~$ ipython
Python 3.8.10 (default, Mar 15 2022, 12:22:08)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from tensorflow.python.distribute.cluster_resolver import tpu_cluster_resolver
2022-05-23 20:27:45.814247: I tensorflow/core/tpu/tpu_api_dlsym_initializer.cc:116] Libtpu path is: libtpu.so
2022-05-23 20:27:45.887661: F ./tensorflow/core/tpu/tpu_executor_init_fns.inc:148] TpuCompiler_DefaultDeviceShapeRepresentation not available in this library.
Aborted (core dumped)
sidd@t1v-n-a40e9bbd-w-0:~$ ipython
Python 3.8.10 (default, Mar 15 2022, 12:22:08)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tensorflow
2022-05-23 20:27:55.773585: I tensorflow/core/tpu/tpu_api_dlsym_initializer.cc:116] Libtpu path is: libtpu.so
2022-05-23 20:27:55.828311: F ./tensorflow/core/tpu/tpu_executor_init_fns.inc:148] TpuCompiler_DefaultDeviceShapeRepresentation not available in this library.
Aborted (core dumped)
sidd@t1v-n-a40e9bbd-w-0:~$
```

It's definitely just the `tensorflow` dependency.

**Comment by ramit-wandb** [comment]
Hey @siddk,

This looks like a tensorflow internal issue to me, which we can not fix on our end. I would suggest raising this to the tensorflow team [here](https://github.com/tensorflow/tensorflow/issues).

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
​Hi @siddk, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by siddk** [comment]
Closing - as @ramit-wandb suggested, this seems to be a Tensorflow/core TPU VM issue.

It'd be nice to enable/document this fix for others though:

```python
wandb.init(project=<PROJECT>, entity=<ENTITY>, settings=wandb.Settings(_disable_stats=True)
```
