### ISSUE TITLE
[Q]Hyper-parameter optimization for YOLOR

### ISSUE THREAD

**Issue by GunjanPatel1108** [wandb/wandb#3697]
How can i integrate wandb sweeps for hyper parameter optimization in yolor? Where can i add agent and should i need to create different .yaml file for defining hyper parameter? https://github.com/wandb

**Comment by nate-wandb** [comment]
Hi @GunjanPatel1108, you would have to define the hyperparameters in a .yaml file in the format used for sweeps. Here are some [examples](https://github.com/wandb/examples/tree/master/examples/keras/keras-cnn-fashion). Your model would have to be set to take any arguments that are going to be passed in from your sweep.yaml. 

Next `wandb sweep sweep.yaml` from the command line.

Followed by `wandb agent <sweep_id>`

If you define the program as your train.py in your sweep.yaml, then W&B will automatically start running the sweep using train.py as the training script. 

The only trick here would be to make sure that your train.py is setup to take the command line arguments that are going to be passed in by the sweep agent and not the default values you are assigning in your hyperparams.yaml.

**Comment by nate-wandb** [comment]
Hi @GunjanPatel1108 I wanted to see if you had a chance to try the above solution or if there was anything I could help clarify?
