### ISSUE TITLE
[Q]Why wandb.watch(model, log="all")  is not effective?

### ISSUE THREAD

**Issue by firstelfin** [wandb/wandb#3701]
`wandb.watch (model, log="all")` does not display weights and parameters, but only a blank box, and the following errors will be caused during training:
* wandb: ERROR Summary data exceeds maximum size of 10.4MB. Dropping it.
* wandb: ERROR Dropped streaming file chunk (see wandb/debug-internal.log)
ERROR:root:dropped chunk 413 Client Error: Request Entity Too Large for url: 
* Exception: The wandb backend process has shutdown

During the training process, it seems that the program has been sending the parameters and gradient information of the model to **wandb**, which also leads to the increasing training time of each iteration
*   7%|▋               | 1017/14686 [23:19<8:17:32,       2.18s/it, loss=0.273955]
* 28%|██▊          | 4090/14686 [3:02:14<13:02:32,  4.43s/it, loss=0.101270]
* 40%|████       | 5909/14686 [5:38:20<13:56:41,  5.72s/it, loss=0.089744]
* 42%|████▏     | 6234/14686 [6:13:43<8:26:41,    3.60s/it, loss=0.100164]

**Comment by nate-wandb** [comment]
Hi @firstelfin, sorry that you are encountering this issue. Histograms can get quite large and there is a cap of 10.4MB per each logging call. If you need to `log='all'` then I would recommend specifying `wandb.init(mode="offline")` and then using `wandb sync` (documentation found [here](https://docs.wandb.ai/ref/cli/wandb-sync)) to upload the run folder after the run has completed. 

As far as the training speed is concerned, we won't hang up your code since wandb operates in a separate process, but it still uses some computer resources (usually negligible) so this may be caused by wandb constantly attempting the network calls because of the issue you described. I believe the offline mode solution should resolve this as well. 

Let me know if this solves the issue for you!
Thank you,
Nate

**Comment by firstelfin** [comment]
Hi @nate-wandb,  thank you for your reminder. According to your and @Angelica's tips, I have made the following attempts:
|Operation|Out iteration|Offline|Log_freq|Criterion|Visible|Error|
|---|---|---|---|---|---|---|
|epx1|1|1|1|1|True| |
|exp2|1|0|1|1|True| |
|exp3|0|0|1|1|True|Error1|
|exp4|0|0|1|0|True| |
|exp5|0|0|0|1|True|Error1|

**Experiment description**
* **Error1**: wandb: ERROR Summary data exceeds maximum size of 10.4MB. Dropping it
* **Out iteration**:  Using `wandb.watch` outside a loop iteration;
* **Criterion**: Whether to specify the criterion we use;
* **log_freq**:  Whether to use sampling every 10 batches.


The possible reasons for these phenomena are as follows.

**Causes of `wandb.watch (model, log="all")` failure**

* **log_freq=1000 default**. The model needs to run for some time before sampling the gradient and parameters;
* After the last experiment, the last `run` under the wandb official website project is still running, so the current run will not release the gradient information to wandb!
* Due to continuous accumulation, the data volume is too large, resulting in overload.

**Finally, thank you for your advice(`mode = offline`), which is very useful.**

**Comment by AustinApple** [comment]
Hello,
I have tried to run this notebook(https://github.com/ayulockin/debugNNwithWandB/blob/master/MNIST_pytorch_wandb_Vanishing_Gradient.ipynb) on a remote server. But, I found `wandb.watch (model, log="all")` does not display weights and parameters, without any error message @firstelfin mentioned above.

**Comment by XuKarenYan** [comment]
> Hello,
> I have tried to run this notebook(https://github.com/ayulockin/debugNNwithWandB/blob/master/MNIST_pytorch_wandb_Vanishing_Gradient.ipynb) on a remote server. But, I found `wandb.watch (model, log="all")` does not display weights and parameters, without any error message @firstelfin mentioned above.

I got the same problem. Things I used are `wandb.watch(model, log="gradients", log_graph=True)`. Does anyone know how to solve this? Many thanks!

**Comment by AustinApple** [comment]
Probably it would take some time to process and display. Last time I wait a period of time before seeing the graphs.

**Comment by XuKarenYan** [comment]
Gotcha. Thanks I'll try!
