### ISSUE TITLE
[CLI]: Save media images with leading zeros in local wandb dir to preserve logging order

### ISSUE THREAD

**Issue by tom-andersson** [wandb/wandb#3704]
### Describe the bug

Currently, media logged to `wandb` appear to be saved locally in something like the following format: `<wandb_dir>/<run_id>/files/media/images/<media_name>_<step>_<media_id>.png`.

The issue is that the `<step>` part of the file name is just a plain integer. This means that when ordered alphabetically (as is the default in most systems), the files are not in the order they are logged. For example, here is a snippet of one of my media folders:

```
all_100_cc5ef7a50d65b4c5dacf.png
all_107_4d6f8dd22f9daf443f04.png
all_114_5937fbc5a3ac33865580.png
all_1_1ab59e95bf4affa60ed0.png  
all_121_71cf4ab3144011fc22dc.png
all_128_7f916240b5c21cd4f8af.png
all_135_2111ab39ee5313f8319c.png
all_142_bcccef22d7e36256c885.png
all_149_f91dcd61865cc041cecc.png
all_156_686af7bb9ff8dd8cd5c0.png
all_16_2e774e98215831f4c991.png 
all_163_508c194af1c359498240.png
...
```

It would be useful if the files were ordered in the same order that they are logged (ie with increasing `step`). This would mean that you could easily create a gif showing the evolution of a figure during training (this is also possible with the incorrect order as above, but is more irritating and would probably need regex to extract the step counter part and then order based on that). Creating an animation over `step` is not supported by the W&B web app, so this one-line change to the library would be a quick way to make it possible for users to do this manually.

I suggest adding leading zeros to the `step` part of the filename to ensure they are stored in the correct order.

### Environment

wandb version: `0.12.11`

**Comment by armanhar** [comment]
Hi @tom-andersson, thanks for the suggestion. I will file a ticket for your engineering team, so that they can consider this.

**Comment by armanhar** [comment]
Hey @tom-andersson, I wanted to circle back to this. You can also achieve the desired result with `ls | sort -V`.
