### ISSUE TITLE
[Q] How to continue recording data after the status of wandb changes to crash?

### ISSUE THREAD

**Issue by chinoll** [wandb/wandb#3723]
The network on my GPU server crashed for a period of time, and then my wandb status became crash, but the process did not crash. How can I make wandb continue to record data?

**Comment by ramit-wandb** [comment]
Hi @chinoll,

Thanks for writing in! If your process was still active, your metrics should be stored locally in your `wandb` folder. You should be able to use `wandb sync` in order to sync your run to the cloud. As a first step, could you try that?

Thanks,
Ramit

**Comment by chinoll** [comment]
> Hi @chinoll,
> 
> Thanks for writing in! If your process was still active, your metrics should be stored locally in your `wandb` folder. You should be able to use `wandb sync` in order to sync your run to the cloud. As a first step, could you try that?
> 
> Thanks, Ramit

thanks,
