### ISSUE TITLE
[Q] Could wandb give some discount for mmdetection user to Subscriptions, and support the Alipay to pay?

### ISSUE THREAD

**Issue by vansin** [wandb/wandb#3737]
Could wandb give some discount for mmdetection user to Subscriptions, and support the Alipay to pay?

**Comment by ramit-wandb** [comment]
Hi @vansin,

I saw the team mmdetection consists of users with Academic Emails. Is this for an Academic or Commercial purpose?

**Comment by vansin** [comment]
most of users are Academic purpose

**Comment by ramit-wandb** [comment]
Hi @vansin,

If the users on your team are academic users, W&B is free of charge to use already. If you are using W&B for a commercial purpose though, we do not have any discounts.

Thanks,
Ramit
