### ISSUE TITLE
[Q]What does the bracket mark of abscissa mean?

### ISSUE THREAD

**Issue by firstelfin** [wandb/wandb#3752]
# Desc
In **charts**, bracket marks appear on the abscissa of the icon, as shown in the following figure. What does this mean?
![image](https://user-images.githubusercontent.com/36871890/172327344-aa871500-966e-4812-82be-385621af6b08.png)

Is this marking caused by the presence of Nan in the data?

**Comment by MBakirWB** [comment]
Hi @firstelfin ,

Thank you for writing in. Based on the approximate location of the mark reflecting (2601 Nan) label it might be. Can you please provide a link to your workspace and I can take a look.

**Comment by firstelfin** [comment]
@MBakirWB Hello, after confirming that the data is Nan, the workspace has been deleted. I'm very sorry that we can't provide a link for you to view.

**Comment by MBakirWB** [comment]
@firstelfin , 

Not a problem. If you ever run across this issues again, please do reach out. 

Regards,

Mohammad
