### ISSUE TITLE
[CLI]: ROC Curve clips remaining points

### ISSUE THREAD

**Issue by tylerganter** [wandb/wandb#3756]
### Describe the bug

`wandb.plot.roc_curve()` will clip the remaining points in an illogical way when the data exceeds `chart_limit = wandb.Table.MAX_ROWS`. This is problematic particularly because it forces the user to use less data for evaluation, as opposed to subsampling the true/false positive rates after computing them with all data.

### Environment

N/A

### Additional Context

I already have the fix, making a PR now

**Comment by ramit-wandb** [comment]
Hi @tylerganter,

Thanks for reaching out to us. There is already a planned feature to make allow for different methods of sampling from our web UI. This should let you resample data as desired from the UI. I'll let you know once this feature is implemented.

Thanks,
Ramit

**Comment by tylerganter** [comment]
@ramit-wandb could you just use my PR (#3757)? It's already implemented and I solved a more pertinent issue with PR curves...

**Comment by kptkin** [comment]
This change went out in the latest release (0.12.21) thanks @tylerganter for the contribution!
