### ISSUE TITLE
[App]: Abnormal Behavior when writing a report using Korean input methods

### ISSUE THREAD

**Issue by Taehee-K** [wandb/wandb#3773]
### Current Behavior

I think this is an extension of #3525, the abnormal behavior happening to Korean characters along with Chinese and Japanese.
When trying to type in Korean (using MacOS Monterey) on the report page, the following abnormal behaviors happen:
1. Location of the cursor will suddenly change to different places on the line
2. The characters will be duplicated erratically

### Expected Behavior

I had no problem writing Korean in the description section and expected it to behave the same for the main part of the report.

### Steps To Reproduce

1. Go to create a new report
2. Type in the main part of report in Korean 

### Screenshots

https://user-images.githubusercontent.com/63901494/172969636-d97aa4bb-013c-4b08-ba14-4356b98fb212.mov

### Environment

OS: MacOS Monterey

Browsers: Google Chrome

Version: Chrome version 102.0.5005.61 (Official Build) (arm64)

**Comment by armanhar** [comment]
Hey @Taehee-K, thanks for flagging this. I'll file a ticket for this bug.

**Comment by Taehee-K** [comment]
Yes I can create a report in Korean now 
thank you!
