### ISSUE TITLE
[App]: Images not appearing as a possible media key. 

### ISSUE THREAD

**Issue by joseph-bae** [wandb/wandb#3787]
### Current Behavior

When trying to add a panel with images across epochs, the following appears: 
![image](https://user-images.githubusercontent.com/62440391/173205641-5395933a-6e47-4ed3-8d22-a7a08e4d03ec.png)

I'm not sure why this would be since the image files are appearing in the media folder on the web app:
![image](https://user-images.githubusercontent.com/62440391/173205662-98f75d1b-70ab-46bd-9af5-713babfbbe86.png)

### Expected Behavior

Ability to add the media key (here it would be a list of images titled "prediction_visualizations"

### Environment

OS: Windows 10

Browsers: Chrome

**Comment by MBakirWB** [comment]
@joseph-bae ,

We will take a look at this for you. Can you please provide a link to the workspace you are experiencing this issue.

**Comment by MBakirWB** [comment]
Hi @joseph-bae ,

Since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

Regards,

Mohammad
