### ISSUE TITLE
[Feature]: Mass delete runs

### ISSUE THREAD

**Issue by richardrl** [wandb/wandb#3804]
### Description

It is very common while debugging code to perform many runs, which may be a few seconds long, but which ultimately fail due to code bugs.

### Suggested Solution

There are two options for 'getting rid' of these erroneous runs.

One, we can disable WANDB with environment option. This is horrible because it messes up the workflow significantly and adds a very annoying switching cost while developing with wandb.

Two, we can delete runs posthoc in the user interface. For example, I can sort by ascending order of "runtime" and delete 20 runs at a time. The problem is, this is really inefficient. Please allow us to blanket delete runs that meet a certain criteria instead of 20 at a time. E.g. we should be able to delete all 10,000 runs with <20 runtime with one click.

**Comment by armanhar** [comment]
Hey @richardrl, have you tried [tagging the runs](https://docs.wandb.ai/ref/app/features/tags#how-to-add-tags) you do for testing? Once you do that you can then filter out all the runs that don't have the test tag and delete those
<img width="482" alt="Screen Shot 2022-06-15 at 13 29 10" src="https://user-images.githubusercontent.com/89597668/173794420-182b61f3-3ae8-4440-9b4a-ecb6a61d7dab.png">
.

**Comment by armanhar** [comment]
​Hi @richardrl, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.
​

**Comment by richardrl** [comment]
@armanhar This is also not a great solution.... I guess I could use an argparse argument to set the test tag, then mass delete using the tag. But is there no way to do what I want retroactively by filtering on the run time?

**Comment by armanhar** [comment]
​Hi @richardrl , I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.
​

**Comment by richardrl** [comment]
@armanhar Once you filter that way, you can still only delete 20 runs at a time, no?

**Comment by armanhar** [comment]
Hey @richardrl, apologies about the delay on this. No, you can select all the runs and then deleted those runs in bulk in the UI.
<img width="478" alt="Screen Shot 2022-06-30 at 13 47 30" src
<img width="437" alt="Screen Shot 2022-06-30 at 13 47 42" src="https://user-images.githubusercontent.com/89597668/176647693-c8c21a6d-bbea-47ca-8536-6ef06e5dcb66.png">
="https://user-images.githubusercontent.com/89597668/176647603-7b11b363-1577-42ea-938a-7f4596c3bec6.png">
<img width="281" alt="Screen Shot 2022-06-30 at 13 47 36" src="https://user-images.githubusercontent.com/89597668/176647649-a30b09f1-b14d-4861-a37b-967f4f6d7028.png">

**Comment by richardrl** [comment]
@armanhar If you click "select all runs", that deletes all the runs in the project. I want to delete all the runs that have runtime < 1 minute, which is very different from deleting all runs overall

**Comment by armanhar** [comment]
Hey @richardrl, apologies about the delay. "Select all runs" only selects that runs that are not filtered out. By default if you select all the runs, it will select the runs in the current page. "Select all runs" is used to select the runs on all the pages. In the screenshots below you can see that:

<img width="488" alt="Screen Shot 2022-07-12 at 11 45 55" src="https://user-images.githubusercontent.com/89597668/178438137-3e816f56-cc9e-4661-adf3-0907b6a1c3a2.png">
<img width="1002" alt="Screen Shot 2022-07-12 at 11 47 20" src="https://user-images.githubusercontent.com/89597668/178438145-7382d2c4-57c4-42ec-9416-
<img width="394" alt="Screen Shot 2022-07-12 at 11 47 43" src="https://user-images.githubusercontent.com/89597668/178438172-ba7377a2-4671-4672-a95c-b9a21890428e.png">
8ba79e6d7baf.png">
<img width="435" alt="Screen Shot 2022-07-12 at 11 47 49" src="https://user-images.githubusercontent.com/89597668/178438179-d196cba5-f601-4c93-b88c-8b7427290a0d.png">

**Comment by nprime496** [comment]
Hi, I wanted to delete a lot of runs at once too, I followed your instructions but noticed that I don't have checkboxes in my UI.

Is it normal ? Am I missing something ?

![Screenshot from 2022-07-29 10-12-48](https://user-images.githubusercontent.com/54849528/181715195-f2cac5c4-3ed2-4e04-b46a-fe40c61c3cb2.png)

**Comment by lesliewandb** [comment]
Hi @nprime496, you are currently trying to delete runs from the workspace tab. In order to delete multiple runs at a time, you'll need to navigate to the Table tab. From there, you'll be able to see the checkboxes. Let me know if you have any other questions on how to do this!
![Screen Shot 2022-08-02 at 12 01 25 PM](https://user-images.githubusercontent.com/91079402/182452985-ed822876-94aa-49ef-98b3-e86ecb35e6d6.png)

**Comment by brando90** [comment]
would be nice for a python option see issue: https://github.com/wandb/wandb/issues/1745

**Comment by udaylunawat** [comment]
Would also like a similar feature to mass delete saved models/artifacts by having an option like select all.

**Comment by BitCalSaul** [comment]
> Would also like a similar feature to mass delete saved models/artifacts by having an option like select all.

Agreed, now i have to delete the models/artifacts one by one, which is time-consuming.
