### ISSUE TITLE
[App]: Unable to save model artifacts via subclassing the model class (Tensorflow 2.9)

### ISSUE THREAD

**Issue by TanyaChutani** [wandb/wandb#3833]
### Current Behavior

 Unable to save model artifacts via subclassing the model class (Tensorflow 2.9).
 
 
WandB version - 0.12.18

### Steps To Reproduce

Google colab notebook link - https://colab.research.google.com/drive/1NYPvOElO6qnI8_H3W53ab4peJFQ5YMeU?usp=sharing

### Screenshots

<img width="1717" alt="Screenshot 2022-06-23 at 12 18 05 AM" src="https://user-images.githubusercontent.com/25456344/175113798-084d5faf-b8bd-4dea-be5b-a2dc871de2cb.png">

### Environment

OS: Google colab

Browsers: Mozilla Firefox

Version: 101.0

**Comment by MBakirWB** [comment]
HI @TanyaChutani , thank-you for writing in. We will review the provided details and get back to you soon.

**Comment by MBakirWB** [comment]
Hi @TanyaChutani ,

Apologies for the delay on this. After review, this error is not directly attribute to Wandb but rather Tensorflow or Keras where tensors aren't being serialized to JSON, potentially your optimizer. This is similar to the known issue reported [here](https://github.com/tensorflow/addons/issues/2446) in the Tensorflow Addons Github. I was able to find a few stackoverflow hits on this as well, see[ Unable to Serialize](https://stackoverflow.com/questions/71965660/unable-to-serialize-0-1-2-63-to-json-in-keras-for-dl-issues) and [ModelCheckpoint Type Error](https://stackoverflow.com/questions/69882263/tf-keras-callbacks-modelcheckpoint-type-error-unable-to-serialize-1-0000000656). There a few helpful suggestion in each of these posts to address this, hope you find them helpful. 

Regards

**Comment by TanyaChutani** [comment]
Understood, thanks for a quick response to my query. Appreciated.
