### ISSUE TITLE
[Q]How to export a table with image content?

### ISSUE THREAD

**Issue by Minxiangliu** [wandb/wandb#3837]
I am training a segmentation model and display the validation results in a table, I can see the results from wandb, but I want to download all the images, I can't find any exporting place here, can someone please help me?

![image](https://user-images.githubusercontent.com/30144428/175452682-e440788b-79c2-4b70-9ce2-a3c04fab12f4.png)

**Comment by ramit-wandb** [comment]
Hi @Minxiangliu,

You can use the `get()` call to a table to download the `wandb.Table` object, which can then be used to extract the images from it. Here is an example on how you can do this: https://docs.wandb.ai/guides/data-vis/log-tables#access-tables-programmatically

Thanks,
Ramit
