### ISSUE TITLE
[Q] Is it possible to disable ssl check on wandb.init()?

### ISSUE THREAD

**Issue by ssemeniuta** [wandb/wandb#3838]
When trying to do `wandb.init(...)` inside our corp ML platform, I get this error - `ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)` 

The error is expected because of how the platform is set up and I have no control over it. I'm wondering if it is possible to disable this check?  In my usecase I'm ok with reduced security for the sake of simpler usage.

Thanks.

**Comment by vanpelt** [comment]
If you're still stuck with SSL errors, you can disable TLS verification but it's not secure.  You do this by setting the environment variable `WANDB_INSECURE_DISABLE_SSL=true`

**Comment by ssemeniuta** [comment]
>Hi, can you give me more information as to why you aren't able to upgrade your SSL libraries in your docker container? Usually, this can be fixed by updating certifi via pip install --upgrade certifi

Thank you for the suggestion, but in my case the problem is not in libs - there is some kind of an issue with certificates in our system. 

>If you're still stuck with SSL errors, you can disable TLS verification but it's not secure. You do this by setting the environment variable WANDB_INSECURE_DISABLE_SSL=true

This helped, thank you!
