### ISSUE TITLE
[Q] How can I add config from an already existing project?

### ISSUE THREAD

**Issue by youngjae-avikus** [wandb/wandb#3844]
Hello
For example, I want to include the value of the inference result in the training wandb project in the table
If I just write the code of inference, wandb shows a new project-name, how do I make it possible?

**Comment by MBakirWB** [comment]
HI @youngjae-avikus , thank you for writing in. Can you please clarify what you are attempting to do as it isn't clear from the message posted. When you wrote you want to add a "config" from an existing project to a new one, are you attempting to use our API to fetch a specific run configuration and manually add/use it for another run?

Thanks

**Comment by youngjae-avikus** [comment]
@MBakirWB 

For example, I want to measure the model inference time after model training and add(logging) the config (or like table) to the existing project, 
so do I have to specify the `run_id` when I run `wandb.init`?

**Comment by MBakirWB** [comment]
@youngjae-avikus ,

To log to an existing run that has finished you need to [reinitialize the old run](https://docs.wandb.ai/guides/track/advanced/resuming) and proviode the actual run id, `wandb.init(id=run_id) `.

Please let us know if you have additional questions.
