### ISSUE TITLE
[Q] Does resume='auto' always rerun a crashed run even if I pass a new 'id' in init?

### ISSUE THREAD

**Issue by archilk** [wandb/wandb#3846]
Let's say, in my train script, I call my init function as follows:

`wandb.init(entity='me', config=run_config, id=wandb.util.generate_id(), resume='auto')`

Now let's say run with id "run-id-1" crashes, and this script is run again. Will it now do a new run with "run-id-2" or resume "run-id-1"?

PS: Thanks for this amazing tool. It's everything I've ever needed.

**Comment by MBakirWB** [comment]
Hi @archilk, please [see this document](https://docs.wandb.ai/guides/track/advanced/resuming) on specifics of resuming runs for your particular use case. Please let me know if you have any questions after reviewing. Thanks.

**Comment by MBakirWB** [comment]
Hi @archilk l, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
