### ISSUE TITLE
[Q] Difference between `wandb.require('service')` and `wandb.require(experiment='service')`

### ISSUE THREAD

**Issue by Co1lin** [wandb/wandb#3848]
In [document about wandb service](https://github.com/wandb/client/blob/master/docs/dev/wandb-service-user.md), it says for `spawn` multiprocessing, we should use `wandb.require('service')` in the main process. But in "General usage" section, it is `wandb.require(experiment='service')`. I also found that `wandb.require` has two arguments, 'requirement' and 'experiment' . What's the difference between them?

**Comment by kptkin** [comment]
Currently, there shouldn't be any difference, and any way you specify this would do the same thing, though `requirement` will take precedence over `experiment` as you can see from this line: https://github.com/wandb/client/blob/master/wandb/sdk/wandb_require.py#L77

Hope this helps!
