### ISSUE TITLE
[Feature]: Enable GitHub Discussions in this repository

### ISSUE THREAD

**Issue by alvarobartt** [wandb/wandb#3851]
### Description

So this issue is basically to request the creation of a Discussions page in GitHub for this repository, this is a feature that GitHub moved out of beta last August 2021 as described at https://github.blog/changelog/2021-08-17-github-discussions-is-now-out-of-beta/, and it's something really useful so that the community members can have a place to ask questions, share ideas, etc.

The wand community seems to be growing each day so this is a feature that could be really helpful IMHO!

### Suggested Solution

Here's GitHub's explanation on how to set-up the Discussions in your repository https://docs.github.com/en/discussions/quickstartset up

**Comment by armanhar** [comment]
Hey @alvarobartt, we created a discourse for our community. Here is the link: https://community.wandb.ai
