### ISSUE TITLE
[CLI]: Wandb login within Airflow task throws multiprocessing error. 

### ISSUE THREAD

**Issue by mancunian1792** [wandb/wandb#3861]
### Describe the bug

I have an airflow script that tries to log the metrics of an evaluation model to wandb. I had to make use of login programmatically because the airflow environment (MWAA - AWS) is a managed server instance that changes every time a dependency is changed.

Below is a sample airflow task where I test out if wandb works correctly. 

```python 
@task
def test_wandb(**kwargs):
    import wandb
    curr_date = datetime.now().strftime("%Y-%M")
    wandb.login(key=Variable.get('WANDB_API_KEY'))
    wandb.init(project=f'TEST-PROJECT',
                   entity='avenuetech', name=f'test-run-{curr_date}', reinit=True)
    wandb.log({"message": "SUCCESS"})
    wandb.finish()


```

I just use the above task in a DAG. It fails in the login key with the following error message

![wandb_error](https://user-images.githubusercontent.com/9761766/176206903-d9d224fc-3e44-4f35-8f09-7201c98601c8.png)

### Environment

WandB version: 0.12.19

OS: Linux

Python version: 3.8

Versions of relevant libraries: Airflow 2.2.2

### Additional Context

I can see that this issue has been raised in some form before along with joblib and the recommendation was to use an earlier version of wandb which doesn't have many plotting features that I absolutely need.

**Comment by lesliewandb** [comment]
Hi @mancunian1792, thank you for bringing this to our attention. Can you try setting `os.environ["WANDB_START_METHOD"] = "thread"` and seeing if this is able to help?
