### ISSUE TITLE
My runs has large upstream_diff.patch, how can I avoid this? [Q]

### ISSUE THREAD

**Issue by Jarvis-K** [wandb/wandb#3862]
I am using the wandb to track my running. However, it automatically tracks the code and has a large upstream_diff.patch. This happens even if I committed and pushed my code to my git. I am wondering how can I avoid this ?

**Comment by lesliewandb** [comment]
Hi @Jarvis-K, you can turn code saving off by going into [settings](https://wandb.ai/settings) and making sure that 'Enable code saving in your personal account' under 'Project Defaults' is turned off.

**Comment by Jarvis-K** [comment]
Thanks! This solves my problem and I will close the issue.
