### ISSUE TITLE
[App]: Long captions are clipped in UI.

### ISSUE THREAD

**Issue by PiotrDabkowski** [wandb/wandb#3875]
### Current Behavior

Long audio captions are clipped and there is no way to see them in full (likely also applies to other media, but did not test).
They are also not centered and look weirdly offset to the right, and are clipped in both, beginning and end:
<img width="1626" alt="image" src="https://user-images.githubusercontent.com/4052440/176728311-631948ba-653c-4654-8866-390fe0abd830.png">

The only way to see the caption is to open the page source...

### Expected Behavior

The caption is wrapped or otherwise, there is some way to see the caption in full. Long captions are common, for example for ASR or TTS tasks, being able to see just ~100 letters is not enough.

### Environment

OS: Mac

Browsers: Chrome

Version: Chrome 103.

**Comment by armanhar** [comment]
Hey @PiotrDabkowski, can you share a code snippet you used for logging the audio file? Also which wandb version are you using?

**Comment by armanhar** [comment]
Hey @PiotrDabkowski, ​I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.
​

**Comment by PiotrDabkowski** [comment]
Thank you, here is the code to log the 4 second, silent audio, with a very long caption. You will see that the caption is cut in the UI.

`wandb.log(dict(audio=wandb.Audio(np.zeros(4*22050), 22050, caption=100*"Very long caption."))`

Wandb version: 0.12.21 (latest). The issue is on the web client UI side, as the text is logged fine, and is present in the HTML of the site, but it is simply not being displayed right.

**Comment by PiotrDabkowski** [comment]
This issue still happens: 
<img width="1632" alt="image" src="https://user-images.githubusercontent.com/4052440/186519462-9303404f-d6bb-42b3-8f71-31376427eaf8.png">

**Comment by paudom** [comment]
Any updates on this?

**Comment by thanos-wandb** [comment]
Hi @PiotrDabkowski thank you very much for reporting this issue and surfacing it recently. 

A fix has been deployed yesterday which should address the issue by adding a scrollbar when the audio captions overflow cc: @paudom. I will now close this support request but please let me know if you are still encountering any issues, and we will be happy to keep investigating.
