### ISSUE TITLE
[App]: DDP processes not able to access artifacts when wandb initialized only in main process

### ISSUE THREAD

**Issue by thiyagu-lily** [wandb/wandb#3877]
### Current Behavior

When wandb.init is called only in the main process, the child processes initialized by ddp dont have access to the wandb run

### Environment

OS:

Browsers:

Version:

**Comment by MBakirWB** [comment]
Hi @thiyagu-lily, can you please expand on your post and what you are attempting to access.It would be great if you can provide us with sample code of how you are using DDP and logging to runs. 

Please see this [document](https://docs.wandb.ai/guides/track/advanced/distributed-training#logging-distributed-training-experiments-with-w-and-b) on our recommended methods of using DDP, including advanced features using [wandb service](https://docs.wandb.ai/guides/track/advanced/distributed-training#wandb-service)

**Method 1**:  using `wandb.init() `in just the `rank0` process and only calling `wandb.log()` there, not in any sub-processes. This method is simple and robust, but it means that model metrics from other processes (e.g. loss values or inputs from their batches) are not logged.

**Method 2**:  using `wandb.init()` and `wandb.log()`from each process and to use the [grouping](https://docs.wandb.ai/guides/track/advanced/grouping) feature to keep track of which runs correspond to which experiments. 

Please let me know if you have any questions.

**Comment by MBakirWB** [comment]
Hi @thiyagu-lily,

Since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by thiyagu-lily** [comment]
hi @MBakirWB 
sorry missed the update! 

Im trying to call wandb init from rank0, but my code needs to access artifacts from wandb. So the non rank0 processes are not able to access the artifacts. I want to do this, to prevent duplicate runs for the same configuration!

**Comment by MBakirWB** [comment]
Hi @thiyagu-lily,

Thank-you for getting back to me. You are correct that you can't access multiple artificats during multiprocessing. When access an artifcat a new run is initiallized while you use that specific run. We don't allow or multiple runs to be initialized/in progress for the same artifact. You would see this error `Duplicate entry {} for key 'unique_artifact_collection_membership_version `if you are attempting to do so. 

For large datasets or distributed training, multiple parallel runs might need to contribute to a single artifact, [see this document ](https://docs.wandb.ai/guides/artifacts/api#adding-files-from-parallel-runs)for a code pattern in how to construct such parallel artifacts.

**Comment by MBakirWB** [comment]
HI @thiyagu-lily, I will be marking this matter closed. Please let us know if you'd like to re-open the conversation.
