### ISSUE TITLE
[Q] How to sweep with multiple GPU

### ISSUE THREAD

**Issue by Waterkin** [wandb/wandb#3882]
Hi,
I have 8 GPUs that are able to load wandb agent, how can I utilize them?
In https://wandb.ai/site/articles/multi-gpu-sweeps, I have learned command `CUDA_VISIBLE_DEVICES=0 wandb agent SWEEP_ID`
So can I use the following command to sweep 8 runs at the same time?
`CUDA_VISIBLE_DEVICES=0 wandb agent SWEEP_ID`
`CUDA_VISIBLE_DEVICES=1 wandb agent SWEEP_ID`
`CUDA_VISIBLE_DEVICES=2 wandb agent SWEEP_ID`
...
`CUDA_VISIBLE_DEVICES=7 wandb agent SWEEP_ID`

**Comment by MBakirWB** [comment]
HI @Waterkin,

Thank-you for writing in with your question. Wandb supports distributed training through several methods listed [here](https://docs.wandb.ai/guides/track/advanced/distributed-training) in our documents, additionally our wandb service feature, see [here](https://docs.wandb.ai/guides/track/advanced/distributed-training#wandb-service), enhanced distributed training and addresses common issues that could occur when training across multiple device. Please do let me know if you have additional questions post review of these docs.

**Comment by MBakirWB** [comment]
Hi @Waterkin , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
