### ISSUE TITLE
[Q] Sweep with each sweep run on multi-gpu DDP 

### ISSUE THREAD

**Issue by levan92** [wandb/wandb#3883]
Hi, I am using sweep, but each sweep training run is on 4 GPUs in a DDP training mode. 

I need to have access to `wandb.config` in all 4 processes, in order to update the hyperparameters given by the sweep server to all 4 processes of each training run. 

I do understand that according to ur [documentation on DDP](https://docs.wandb.ai/guides/track/advanced/distributed-training), you recommend 2 ways to do DDP with wandb. I am currently doing the first method, which is only logging on first process. But this does not work in sweep as I need my other 3 processes to be able to access the wandb config (as explained above). How will second method work with sweep then? If I do `wandb.init` on the other 3 processes, will it still get the same set of hyperparams as the main process, as part of the sweep? 

Thanks!

Don't think it is important, but in case it helps, I am using PyTorch, mmdetection framework.

**Comment by levan92** [comment]
Update: I tried second DDP method (aka, init for other 3 processes as well), and as expected, it didn't work, error log below: 

```None
FileExistsError: [Errno 17] File exists: '/home/x/y/z/wandb/run-20220702_181653-5z0vi35p/run-5z0vi35p.wandb'
Thread WriterThread:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 52, in run
    self._run()
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 102, in _run
    self._process(record)
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 331, in _process
    self._wm.write(record)
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/internal/writer.py", line 30, in write
    self.open()
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/internal/writer.py", line 26, in open
    self._ds.open_for_write(self._settings.sync_file)
  File "/opt/anaconda3/lib/python3.8/site-packages/wandb/sdk/internal/datastore.py", line 79, in open_for_write
    self._fp = open(fname, open_flags)
FileExistsError: [Errno 17] File exists: '/home/x/y/z/wandb/run-20220702_181653-5z0vi35p/run-5z0vi35p.wandb'
wandb: ERROR Internal wandb error: file data was not synced
wandb: ERROR Internal wandb error: file data was not synced
wandb: ERROR Internal wandb error: file data was not synced
```

Any idea how I can do this otherwise?

**Comment by levan92** [comment]
Hi, any updates on this?

**Comment by ramit-wandb** [comment]
Hi @levan92,

Thanks for writing in! Looking at the traceback you sent for Method 2, It seems like multiple W&B processes are writing to one file, which is why you are facing this error.

I would recommend actually using just a single Rank 0 process and establish a form of synchronized interprocess communication channel in order to get this working in the best way possible. This way, you can share the `wandb.config` to all your other processes and the data to be logged back to the Rank 0 process.

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
Yup, they should work. You want to make sure you broadcast config and you communicate the logs to rank 0.

**Comment by ramit-wandb** [comment]
Hi @levan92,

I'm closing this issue out. In case you need further assistance here, feel free to reply and we can continue the conversation.

**Comment by iyuner** [comment]
I also encouter the problem and I am using torch.distributed.launch. I modify my code as below, then it works. For the ones who found here,

```
learning_rate_tensor = torch.zeros(1).to(self.device)

if self.is_main_process:
    # initalize wandb board
    run = wandb.init()
    # If wandb is setting a learning rate, use it. Otherwise, use the default from your config file
    learning_rate = run.config.get('learning_rate', config.learning_rate) 
    learning_rate_tensor[0] = self.config.learning_rate

# Broadcast the tensor to all processes
dist.broadcast(learning_rate_tensor, src=0)

# Now all processes have the same learning rate
learning_rate = learning_rate_tensor.item()
```

**Comment by Junqing-Gong** [comment]
Hello, I would like to know how you guys start the main function, if only the main process is used as agent and the main process starts the main function via `wandb.agent(sweep_id, function=main, count=30)`, then how should the other processes start the main function?

**Comment by phrasenmaeher** [comment]
Another solution would be the following route, for those of you looking for a solution without broadcasting:


```python

def update_params_with_sweep_values():
    cfg = wandb.config
    logging.info("Rank %d updating params with sweep values" % world_rank)

    ...

    param_dictionary = {...}

    for i in range(params['world_size']):
        np.save(os.path.join(params["experiment_dir"], f"sweep_values_{i}.npy"), param_dictionary)
    #params is a global variable/argparse object

    logging.info("Rank %d updated params with sweep values" % world_rank)


def load_sweep_values():
    logging.info("Loading param values for rank %d" % world_rank)
    param_dictionary = np.load(os.path.join(params["experiment_dir"], f"sweep_values_{world_rank}.npy"),
                               allow_pickle=True).item()
    params... = ...
    logging.info("Loaded param values for rank %d" % world_rank)


def runner():
    try:
        main()
    except Exception as e:
        print(traceback.format_exc(), file=sys.stderr)


def runner_sweep():
    wandb.init(config=params, name=params.name, group=params.group, project=params.project,
               entity=params.entity)
    update_params_with_sweep_values()

    try:
        main()
    except Exception as e:
        print(traceback.format_exc(), file=sys.stderr)


def main():
    load_sweep_values()

    logging.info(
        "Hparam set to evaluate: ...")

    if params.log_to_wandb:
        wandb.config.update(params)

    trainer = Trainer(params, world_rank)

    optim_target = trainer.train()
    # optim target is only a valid metric if it comes from from the main rank!

    if params.log_to_wandb:
        wandb.log({"optim_target": optim_target})
```

and then running it with

```python
    if params.log_to_wandb:
        wandb.agent(args.sweep_id, runner_sweep, count=1, project=params.project, entity=params.entity)
    else:
        time.sleep(20)
        runner()

```

For me, the broadcasting took way to long, so I switched to the hacky solution of saving the parameters in an intermediate file.

**Comment by RylanSchaeffer** [comment]
Could someone please explain what this problem is and how to solve it (in general)? I'm hitting this same error when trying to train on 4 GPUs

**Comment by RylanSchaeffer** [comment]
I'm new to distributed computing and I'm somewhat lost by what the fix is or should be. Perhaps @ramit-wandb could clarify?
