### ISSUE TITLE
[Q] How to transfer runs between two wandb instance?

### ISSUE THREAD

**Issue by HaoLiuHust** [wandb/wandb#3884]
for example my first wandb instance server(physical server) has reinstalled OS, so I have to reinstall wandb.  After reinstall wandb, I want to recover the runs logs. Is there a way?  my wandb has setup with s3 and mysql, is it will automaticly recover with the same s3 and mysql?

**Comment by MBakirWB** [comment]
Hi @HaoLiuHust, 

Thank-you for writing in. I have a few questions, 

- Are you using wandb local or cloud?
- When you reinstalled OS, did you do full reformat prior to reinstalling wandb?
- When you configured your initial S3 and MySQL, was your data ported to AWS or did your maintain data storage locally?

**Comment by HaoLiuHust** [comment]
> Hi @HaoLiuHust,
> 
> Thank-you for writing in. I have a few questions,
> 
> * Are you using wandb local or public cloud?
> * When you reinstalled OS, did you do full reformat ?
> * When you configured your initial S3 and MySQL, was your data ported to AWS or did your maintain data storage locally?
Thanks for your reply.
* I am using wandb local with docker
* no, it's not full reformat
* the S3 is a local ceph cluster

**Comment by vanpelt** [comment]
If you point the new server to the same s3 bucket all you'll need to restore is the MySQL data which would be on the original docker volume (unless you also pointed the original to an external MySQL).

**Comment by HaoLiuHust** [comment]
thanks, I got it
