### ISSUE TITLE
[Q] Logging metrics for previous steps / Resetting a run's step

### ISSUE THREAD

**Issue by ManiadisG** [wandb/wandb#3890]
As far as I can tell, the default behaviour of wandb is that you can only log metrics forwards, not backwards. That is, if a metric is logged for step _t_, logs made for step _t-1_ are ignored.

Is it possible to overcome this? Specifically, I want to have two distinct training runs (with non-overlapping metrics other than what wandb logs by default such as device-related measurements) and log them in the same wandb run, so I would need to log metrics for steps 0-100, and then reset the run so that I could log new metrics, again for steps 0-100.

**Comment by ManiadisG** [comment]
Hi @armanhar. So is there no way to revisit previous steps? Not even if the goal is to overwrite them?

**Comment by armanhar** [comment]
Hey @ManiadisG, no, at the moment this is not possible.

**Comment by ManiadisG** [comment]
Ok, thank you very much for the clarification!
