### ISSUE TITLE
How to automatically choose which parameters and metric to create parallel coordinate chart?

### ISSUE THREAD

**Issue by stephano41** [wandb/wandb#3891]
Wondering how to automatically choose which parameters and metric to create parallel coordinate chart from within python code, so that I don't need to create one for every single group run I do.

So far have tried logging parameters as config, doesn't automatically make a parallel coordinate chart

**Comment by lesliewandb** [comment]
Hi @stephano41, the parameters come from your .yaml file when you create your [Sweep](https://docs.wandb.ai/guides/sweeps). Can you show me how you are currently creating your Sweep?

**Comment by stephano41** [comment]
Ah I see, I've been using wandb as the wandb mixin to log ray tune trials as detailed in the ray tune documentation. Is there anyway to manually define it without creatimg an actual sweep?

**Comment by lesliewandb** [comment]
Just to confirm, are you trying to create a parallel coordinates plot without sweeps? If so you can click on the top right of your workspace under '+Add Panel' and add a Parallel coordinate chart through there. However, your runs have to have equivalent metrics logged.
![Screen Shot 2022-07-28 at 12 21 58 PM](https://user-images.githubusercontent.com/91079402/181620378-06550490-7925-43ee-a180-d2aa6579057d.png)
