### ISSUE TITLE
[Q] Changing X-axis results in empty figure

### ISSUE THREAD

**Issue by Ji4chenLi** [wandb/wandb#3905]
Hi,

Thank you so much for constructing such an amazing repo! 

Currently, I encountered an issue that the line plots do not show correctly after I change the value for the X-axis. As is shown below, both `Metrics/EnvironmentSteps` and `Metrics/AverageReturn` are plotted correctly with the `x-axis = global_steps` 
![image](https://user-images.githubusercontent.com/44934137/177716530-37b549ba-d9b5-442e-b3d1-65f7d69fb3bc.png)

However, when I tried to create the plot with `x-axis = Metrics/EnvironmentSteps ` and `y-axis =  Metrics/AverageReturn`, the resulting plot is shown below
![image](https://user-images.githubusercontent.com/44934137/177717009-f03c501f-6a01-48a4-8fd5-719ff6923be2.png)

Can you help me with the issue?

Many thanks,
Jiachen

**Comment by Ji4chenLi** [comment]
Fixed the issues. This issue is encountered when I am trying to use `wandb.tensorboard.patch` to sync the `tensorboard` results to `wandb`.

The key is that Wandb seems to rely on its internal `_steps` to judge if two vectors can be combined (e.g., `Metrics/EnvironmentSteps` and `Metrics/AverageReturn`) to create a plot.

As is mentioned in [Metrics/EnvironmentSteps and Metrics/AverageReturn](https://github.com/wandb/client/issues/2369#issuecomment-880285519), whenever you `SummaryWriter` records an value, it seems to + 1 for the `wandb _steps`. Thus we should be very careful in terms of these operations.

**Comment by armanhar** [comment]
Hey @Ji4chenLi, glad you figured it out. Let me know if you have any further issues.

**Comment by Ji4chenLi** [comment]
Thank you so much!
