### ISSUE TITLE
[FR]: Allow skipping new FLOP calculation

### ISSUE THREAD

**Issue by jokleinn** [wandb/wandb#3916]
### Description

Since the recent W&B update that added FLOPs calculation, #3817, I now get: 

> WARNING Unable to compute FLOPs for this model.

Filling my output. I know that my model is designed in a nonstandard way, and this is likely to be the cause of the underlying exception that is being caught and thrown away.

### Suggested Solution

I ask that a boolean constructor argument `calc_flops` -- default True, to preserve existing behavior -- for WandbCallback() be added mainline s.t. `_check_can_compute_flops()` can be gently disabled rather than erroneously returning True initially and catching/logging tons of exceptions later.

**Comment by ramit-wandb** [comment]
HI @jokleinn,

Thank you for your suggestion. I'll pass this on to our engineering team to be implemented and will keep you posted on the status of this.

Thanks,
Ramit
