### ISSUE TITLE
[App]: sweep UI - axis range hides all runs and can't be found or removed

### ISSUE THREAD

**Issue by brianhenn** [wandb/wandb#3917]
### Current Behavior

On the app's Sweep workspace page, I got into a state where all runs are hidden and there's no way I can tell to get out of it.  The error message states that a range on a parallel coordinates or scatter plot is hiding the run, for every run. However, I could not find any such ranges on my plots to remove. I tried deleting all of the panels, but the filter remains. No way to see any data now.  

### Expected Behavior

The UI should indicate to me exactly how to lift whatever filter is hiding all runs (the current message is so vague as to be unhelpful).

Additionally, if the panels causing the hiding are deleted, the filtering should be lifted and the sweep runs should reappear.

### Steps To Reproduce

Unfortunately I don't have exact reproducing steps but it involved inadvertently selecting a small range on a scatterplot that filtered out all runs, and then being unable to remove this filter in any way. 

### Screenshots

See Sweep workspace. All runs hidden, no panels left (all deleted). No way to remove the offending filter. Is this sweep dead now for visualization purposes?

<img width="1792" alt="Screen Shot 2022-07-11 at 10 54 47 AM" src="https://user-images.githubusercontent.com/40010792/178328543-98101115-7d28-4aa1-9c1a-8023f7b6189f.png">

### Environment

OS: MacOS

Browsers: Chrome

Version:

**Comment by brianhenn** [comment]
OK, after a lot of time clicking around, I realized that it is possible to remove the range restriction (whatever it was) by clicking on the eye at next to 'Name' at left and then clicking 'visualize all'. This restored the runs.

However, it is certainly still unexpected (a bug IMO) that when a panel with a restricted range is deleted it does not remove the overall range restriction.

And it also still seems like a bug that it was very difficult/not possible to see what panel and axis is causing the range restriction in the first place.

**Comment by MBakirWB** [comment]
Hi @brianhenn ,

Thank-you for writing in about your experience. You are correct in that when you select a region of any chart you effectively filter to the runs that were selected. This results in the "closed eye" icon next to run names in the UI. Selecting the eye next to "Name" does provide you with several options, which does include "Visualize All" as you indicated. 

After selecting the region of the scatter plot, did you delete the scatter plot chart?

**Comment by MBakirWB** [comment]
Hi @brianhenn , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by tbuckworth** [comment]
I have the same issue, the scatter plot chart is hidden once the filter is applied, so it can't be accessed to undo the filter

**Comment by tbuckworth** [comment]
ah, name -> visualize all fixed the problem, thanks
