### ISSUE TITLE
wandb.plot.histogram only contains part of the data points

### ISSUE THREAD

**Issue by LiuCMU** [wandb/wandb#3921]
Hi, thanks for this excellent product! 

 I tried to log a histogram, but find that the plot only contains part of the data points. Here are my steps: Firstly I created a wandb `Table` object with the data that I want to plot. Then I use `wandb.plot.histogram` to plot the data. But I find the histogram only contains part of the data in the Table object.

The code is as follows,
```{Python}
prob1_data = [[ID_train[i], losses[i]] for i in range(len(ID_train))]
print(len(prob1_data))  #37,115
table1 = wandb.Table(data=prob1_data, columns=['IDs', 'losses'])
wandb.log({
'losses_distribution_for_model1': wandb.plot.histogram(table1, 'losses', title="losses for model1"),
})
```

Here is the screenshot of the histogram (you can see that there are only a few thousand data points):
<img width="537" alt="image" src="https://user-images.githubusercontent.com/60156077/178605043-2694e428-8b37-4251-b811-97119e4da027.png">
Here is the screenshot of the table (there are 37,115 data points):
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/60156077/178605125-683d2430-1c8f-4758-9f2c-8393e076aa55.png">

Could you please take a look? Thank you very much!

**Comment by MBakirWB** [comment]
Hi @lukas,

We allow up to 10K data points to be displayed in our charts. There is discussion of increasing this value for specific use cases. We do set an initial limit to how many points are displayed on a graph (`500 points`). To increase this value, you can do so directly from the Data Source column in the edit charts panel, setting `Limit` value, see image below. 
![ChartLimit](https://user-images.githubusercontent.com/104453360/179097716-be66a208-5ef7-44fc-9dd1-1737501d634a.png)

**Comment by LiuCMU** [comment]
Thank you very much for the explanation!

One thing that would be interesting to know: When the number of data points exceeds the limit, does wandb randomly sample 10k data points, or just take the last/first 10k data points?

Thanks!

**Comment by MBakirWB** [comment]
Hi @LiuCMU ,

If you have more than the allowed points on a chart, [we non deterministically sample downsample](https://docs.wandb.ai/guides/track/log/logging-faqs#what-happens-when-i-log-millions-of-steps-to-w-and-b-how-is-that-rendered-in-the-browser) before we send your browser the data.

**Comment by LiuCMU** [comment]
Makes sense! Thank you very much!

**Comment by KamilDeja** [comment]
Hi I have an issue related to this one. I have a table with 3456 values, I can see that the query works properly ![image](https://github.com/wandb/wandb/assets/10699888/05c7ed6a-f8bb-4e15-95c5-6401e9c78e17), I'm using the default Histogram preset, but for some reason the histogram only contains 41 samples 
![image](https://github.com/wandb/wandb/assets/10699888/cdd40b67-e49b-44a9-9b5a-352df52ea610)

Do you have any idea what might be wrong?

**Comment by LiuCMU** [comment]
It should visualize 50 points, maybe @MBakirWB could help to answer your question?
