### ISSUE TITLE
[Feature Request]: Allow multiple workspaces per user with stored layouts

### ISSUE THREAD

**Issue by ercanburak** [wandb/wandb#3926]
### Description

Currently, there is one workspace per user for each project. Sometimes I require two (or more) different layouts with different plots, to examine different aspects of my runs. As far as I know, this can only be achieved by modifying the layout manually each time. A similar problem also exists on the Table page of a project, where one can require two (or more) different sets of columns, filters, etc. Again, as far as I know, this can only be achieved by modifying the columns, filters, etc manually each time. 

### Suggested Solution

A solution to this problem can be to allow multiple workspaces per user with stored layouts. For example, one can modify their workspace and save it with a name such as `My Workspace 1`, and restore this workspace whenever required. Each user can have multiple saved workspaces in a project. Similarly, one should also be able to save and restore the columns, filters etc. in Tables page.

**Comment by nate-wandb** [comment]
Hi @ercanburak, thank you for the feature request! This is a project we are currently working on. The goal would to be allow workspace "templates" that could be switched between and also shared across different projects. I'm not entirely sure the design of saving the "state" of filters, grouping, and columns in the table tab but I will add your feedback around this to the feature request.

I'll follow up here with you once this has been implemented. 

Thank you,
Nate

**Comment by MBakirWB** [comment]
Hi @ercanburak we just wanted to update you that we are going to be releasing name workspaces this quarter and to keep an eye out for ability to created multiple views within your workspace.

**Comment by MBakirWB** [comment]
Hi @ercanburak , I wanted to update you that named workspaces feature is now active, see our updated [docs](https://docs.wandb.ai/guides/app/pages/workspaces) on how to use this feature. If you have encounter any issues or require assistance please email support@wandb.com.
