### ISSUE TITLE
[App]: Legend is bugged

### ISSUE THREAD

**Issue by miraodasilva** [wandb/wandb#3930]
### Current Behavior

![image](https://user-images.githubusercontent.com/17463598/178975439-7f564d36-e4d5-48ea-850c-8d2e9f219ef0.png)

(Some parts are censored since this is a private project)
The legend is bugged: these little hollow squares appear rather than the little lines that should appear normally. Has been happening on all my plots for a while now, no idea why.

### Expected Behavior

Lines to appear normally in the legend

### Steps To Reproduce

Plot any lines in the web app and check the legend (this has been happening for my project, not sure if this is easily reproducible for others)

### Environment

OS: Ubuntu

Browsers: Brave (based on Chromium)

Version:

**Comment by miraodasilva** [comment]
Sure, here is the link to the project https://wandb.ai/eldorado/avse?workspace=user-miraodasilva .

**Comment by hanglearning** [comment]
I am also experiencing the same bug. I have both solid and dashed lines in the same color for a comparison so I really need to show the legend correctly

**Comment by nate-wandb** [comment]
Hi @miraodasilva and @hanglearning, I wanted to follow up and see if you were still experiencing this? We no longer can reproduce this. 

Thank you,
Nate

**Comment by hanglearning** [comment]
Hi Nate, sorry I haven't been using it recently, and the project was done. If I meet the same problem again, I will update here. Thanks for your support! @nate-wandb
