### ISSUE TITLE
`wandb.save` doesn't upload empty files to `wandb` server

### ISSUE THREAD

**Issue by alvarobartt** [wandb/wandb#3931]
As`wandb.save` doesn't uplopad the empty files to the `wandb` remote, I'd suggest you to add a warning message in case the file is empty so as to let the user know that the file won't be uploaded.

https://github.com/wandb/client/blob/a339333b3ee93864daf416f04c1501186dffac5c/wandb/sdk/wandb_run.py#L1353-L1443

To calculate the file size if it exists you can just `os.path.getsize(path)` as described in https://docs.python.org/3/library/os.path.html#os.path.getsize, which raises an `OSError` in case the file doesn't exist or is unaccesible, and the size in bytes if it succeeds, so something like:

```python
...
if os.path.getsize(glob_str) == 0:
    warnings.warn(f"File {glob_str} is empty and won't be uploaded")
    return
...
```

**Comment by ramit-wandb** [comment]
Hi @alvarobartt,

Thanks for the suggestion! I'll pass it on to the engineering team to be added in a future version.

Thanks,
Ramit

**Comment by alvarobartt** [comment]
Cool @ramit-wandb, I can fill a PR to add that if applicable!

**Comment by ramit-wandb** [comment]
Sure! We happily accept PRs, it would be awesome if you could submit a PR. One of our enigneers could review it.
