### ISSUE TITLE
[App]: Video logged in media folder but not displayed in Media

### ISSUE THREAD

**Issue by nicolas-dufour** [wandb/wandb#3936]
### Current Behavior

Hi,
I have an error where some videos are logged in at each step and do get recorded in the media folder.
However, when trying to display them in the media object they do not appear. Only the first two (or first depending of the log) do get displayed.

On another run they do get displayed with a slider to select between steps

### Expected Behavior

Been able to display all videos

### Steps To Reproduce

1. go on https://wandb.ai/nicolas-dufour/torchrl/runs/2r54ati0?workspace=user-nicolas-dufour
2. Look at media
3. Look at media folder

### Environment

OS: Linux

Browsers: Chrome and Safari
Version: 0.12.21

**Comment by nicolas-dufour** [comment]
@nate-wandb Hiu, yeah sorry, i ahd deleted it by error, i reproduced it here: https://wandb.ai/nicolas-dufour/torchrl/runs/btslaz6v?workspace=user-nicolas-dufour

**Comment by nate-wandb** [comment]
Hi @nicolas-dufour, thank you for the reproduction. I see the issue as well. I'll report this to our engineering team as a bug and follow up with you once we are able to get this resolved. 

Thank you,
Nate

**Comment by dyunis** [comment]
Was there ever a resolution reached? I'm seeing a similar issue with image logging at https://wandb.ai/dyunis/deq_diffusion/runs/c85nrhug?workspace=user-dyunis including the missing images in `wandb-summary.json`.

**Comment by nate-wandb** [comment]
Hi @dyunis, it looks like this hasn't been resolved. I will raise this again to our engineering team so we can get a fix on this. Thank you for providing your workspace so we have another example of this behavior.

Thank you,
Nate

**Comment by dyunis** [comment]
Thanks @nate-wandb, I really enjoy working with wandb and appreciate you looking into it.

**Comment by sepsamavi** [comment]
This seems related to #4830

**Comment by frotaur** [comment]
As of today, I stil have the problem that the logged videos are in the media folder, but don't appear (whereas images do)

**Comment by Nate711** [comment]
I also have this problem. The videos are in the media folder but do not show up in the workspace.

**Comment by ArtsiomWB** [comment]
Hi @Nate711, looks like this ticket got buried, and the examples provided above by the user aren't available anymore. 

Could you please send me a code snippet of you reproing this as well as the workspace where you are experiencing this behavior?

**Comment by ArtsiomWB** [comment]
Hi Wanted to follow up with you regarding this thread!

**Comment by Nate711** [comment]
@ArtsiomWB This is probably due to my code specifying the step like with https://github.com/wandb/wandb/issues/4830#issuecomment-1431935492
```
wandb.log(
        {
            "eval/video/command/vx": vx,
            "eval/video/command/vy": vy,
            "eval/video/command/wz": wz,
            "eval/video": wandb.Video(filename, format="mp4", fps=fps),
        },
        step=current_step,
    )
 ```
 In another place I have
 `wandb.log(metrics, step=num_steps)`
 
 Is there a way to log both data to the same step that does work?

**Comment by ArtsiomWB** [comment]
> Is there a way to log both data to the same step that does work

The step has to either be the same for the epoch of metrics you are logging such as:
```py
wandb.log(
        {
            "eval/video/command/vx": vx,
            "eval/video/command/vy": vy,
            "eval/video/command/wz": wz,
            "eval/video": wandb.Video(filename, format="mp4", fps=fps),
        },
        step=current_step,
    )
```
```py
wandb.log(metrics, step=current_step)
```

Or has to be monotonically increasing. Unfortunately, there is no way of writing it as a previous step, or a step located in the future to go straight back to the previous step.  

If you are interested in using a separate x-axis that is not just `step`, you can customize it using [define metric](https://docs.wandb.ai/ref/python/run/#define_metric)

**Comment by Nate711** [comment]
@ArtsiomWB I was providing the same step number to both calls to .log. Once I deleted the Video panel and recreated it, all the media showed up.

**Comment by anmolmann** [comment]
Thanks for the update @Nate711 !
