### ISSUE TITLE
[CLI]: Unable to log images of type torch.uint8

### ISSUE THREAD

**Issue by luxiya01** [wandb/wandb#3937]
### Describe the bug

When trying to log images of type `torch.uint8`, e.g. images loaded by `torchvision.io.read_image`, wandb gives the following runtime error: 
`RuntimeError: result type Float can't be cast to the desired output type Byte`

It seems like that the `Image` class attempts to convert all torch tensors using the `make_grid` function from torchvision with `normalization=True`, but a uint8 tensor cannot be normalized.

Minimal example:
```python 
from torchvision.io import read_image
from wandb import Image
image = read_image(path)
wandb_image = wandb.Image(image)
```

```shell
File ~/anaconda3/envs/superglue/lib/python3.9/site-packages/wandb/sdk/data_types/image.py:143, in Image.__init__(self, data_or_path, mode, caption, grouping, classes, boxes, masks)
    141     self._initialize_from_path(data_or_path)
    142 else:
--> 143     self._initialize_from_data(data_or_path, mode)
    145 self._set_initialization_meta(grouping, caption, classes, boxes, masks)

File ~/anaconda3/envs/superglue/lib/python3.9/site-packages/wandb/sdk/data_types/image.py:262, in Image._initialize_from_data(self, data, mode)
    260     if hasattr(data, "requires_grad") and data.requires_grad:
    261         data = data.detach()
--> 262     data = vis_util.make_grid(data, normalize=True)
    263     self._image = pil_image.fromarray(
    264         data.mul(255).clamp(0, 255).byte().permute(1, 2, 0).cpu().numpy()
    265     )
    266 else:

File ~/anaconda3/envs/superglue/lib/python3.9/site-packages/torch/autograd/grad_mode.py:27, in _DecoratorContextManager.__call__.<locals>.decorate_context(*args, **kwargs)
     24 @functools.wraps(func)
     25 def decorate_context(*args, **kwargs):
     26     with self.clone():
---> 27         return func(*args, **kwargs)

File ~/anaconda3/envs/superglue/lib/python3.9/site-packages/torchvision/utils.py:104, in make_grid(tensor, nrow, padding, normalize, value_range, scale_each, pad_value, **kwargs)
    102             norm_range(t, value_range)
    103     else:
--> 104         norm_range(tensor, value_range)
    106 assert isinstance(tensor, torch.Tensor)
    107 if tensor.size(0) == 1:

File ~/anaconda3/envs/superglue/lib/python3.9/site-packages/torchvision/utils.py:98, in make_grid.<locals>.norm_range(t, value_range)
     96     norm_ip(t, value_range[0], value_range[1])
     97 else:
---> 98     norm_ip(t, float(t.min()), float(t.max()))

File ~/anaconda3/envs/superglue/lib/python3.9/site-packages/torchvision/utils.py:92, in make_grid.<locals>.norm_ip(img, low, high)
     90 def norm_ip(img, low, high):
     91     img.clamp_(min=low, max=high)
---> 92     img.sub_(low).div_(max(high - low, 1e-5))

RuntimeError: result type Float can't be cast to the desired output type Byte

```

### Environment

- WandB version: 0.12.17
- OS: Ubuntu 22.04 kernel 5.15.0-41
- Python version: 3.9.7

Versions of relevant libraries:
- torch: 1.11.0
- torchvision: 0.12.0

**Comment by MBakirWB** [comment]
Hi @luxiya01 ,

Thank you for writing in. Upon review, this error is not attributed to wandb but rather to the torchvision `make_grid` function in utils, see [here](https://github.com/pytorch/vision/blob/3db30442a52e250c569ba131485fc432c8300f16/torchvision/utils.py#L24). When wandb reads in your image in via [`_initlize_from_data()`](https://github.com/wandb/private-client/blob/225c28f6f62519b6acc2a93aa4fcc20d0ffec748/wandb/sdk/data_types/image.py#L243) as a pytorch tensor, we call 
[data = vis_util.make_grid(data, normalize=True)](https://github.com/wandb/private-client/blob/225c28f6f62519b6acc2a93aa4fcc20d0ffec748/wandb/sdk/data_types/image.py#L264)

`make_grid()` attempts to clamp the tensor using float [point values](https://github.com/pytorch/vision/blob/3db30442a52e250c569ba131485fc432c8300f16/torchvision/utils.py#L103) using the inplace [clamp_](https://github.com/pytorch/vision/blob/3db30442a52e250c569ba131485fc432c8300f16/torchvision/utils.py#L96) method. This produces the error you are seeing. 

To reproduce the error associated with `clamp_()`

```
from torchvision.io import read_image
img = read_image(<img_path>)
min = float(img.min())
max = float(img.max())
img.clamp_(min=min, max=max);
```
Producing : `RuntimeError: result type Float can't be cast to the desired output type Byte`

To fix this and set img to float
`img = img.to(torch.float)`

Now when you log the image to wandb you will not encounter the error

```
from torchvision.io import read_image
from wandb import Image

img = read_image(<img_path>)
img = img.to(torch.float)
wandb_image = wandb.Image(img)
```

**Comment by MBakirWB** [comment]
Hi @luxiya01, this issue is now resolved per this [PR](https://github.com/wandb/wandb/pull/6043) and will be reflected in our next sdk release.
