### ISSUE TITLE
[Q] How to download multiple files of a run?

### ISSUE THREAD

**Issue by Guptajakala** [wandb/wandb#3942]
![image](https://user-images.githubusercontent.com/40518028/179366606-6ab3bc8c-b5c2-4889-ac35-c49970727a29.png)
If I go to the UI of a run, I can only click the download button for one file. What if I want to download the whole `/root/media/images` folder? Is there a way to do that either in UI, or with command line?

**Comment by armanhar** [comment]
Hey @Guptajakala, you can use our [Public API](https://docs.wandb.ai/guides/track/public-api-guide?q=public+) for that. Let me know if you have further questions.

**Comment by Guptajakala** [comment]
Hi @armanhar, is the python api the only way to do that? I'm wondering if there is a more simple way instead of writing a dedicated python script for it.

**Comment by armanhar** [comment]
At the moment this is the only way to do it, @Guptajakala.
