### ISSUE TITLE
[Q] How wandb implement automatically call run.finish when the script exits?

### ISSUE THREAD

**Issue by LuoXin-s** [wandb/wandb#3943]
How wandb implement automatically call `run.finish()` when the script exits? I have not found relevant logic in the source code.

And if I call `wandb.finish()` manually, how wandb set `record_writer_thread.stopped` so it will not stuck in infinite loop? I can see `backend.cleanup()` called `wandb_process.join()`, but how wandb_process to finish itself?

**Comment by LuoXin-s** [comment]
@ramit-wandb Oh, thank you for your response.
Could you please explain to me the second question I asked?

> And if I call wandb.finish() manually, how wandb set record_writer_thread.stopped so it will not be stuck in an infinite loop? I can see backend.cleanup() called wandb_process.join(), but how wandb_process to finish itself?

**Comment by ramit-wandb** [comment]
Hi @LuoXin-s,

I can see that the `WriterThread` class, of which `record_writer_thread` is an instance, does not call `stopped.set()`. However, when one thread sends a stopped signal, every other thread joins itself. You can check this logic out here:

https://github.com/wandb/wandb/blob/d431deaa0c53efe103f5c160b0358c8d0c992fb8/wandb/sdk/internal/internal.py#L145-L160

Thanks,
Ramit

**Comment by LuoXin-s** [comment]
Hi, @ramit-wandb 
The code snippet that you provided set `stopped` only when `KeyboardInterrupt` has happened, but what confused me was other situations. For example, where wandb set `stopped` when the program exit normally.

**Comment by ramit-wandb** [comment]
Hi @LuoXin-s,

The `stopped` flag is what drives all of this, you are right that the `KeyboardInterrupt` stops all the threads, but so does the `process_check.is_dead()` check. That essentially checks if the user process is still active, i.e., if W&B still needs to record data.

Once this process has stopped, all the threads including `record_writer_thread` also stop running.

**Comment by LuoXin-s** [comment]
@ramit-wandb Hi, thank you for your patience.
But as I see it from https://github.com/wandb/wandb/blob/master/wandb/sdk/backend/backend.py#L246.
The user process has to wait for `wandb_process` to finish. I wonder if this causes a deadlock between the user process and wandb_process since wandb_process use `process_check.is_dead()` to check the user process is dead or not.

**Comment by ramit-wandb** [comment]
Hi @LuoXin-s,

I wanted to check in with you to find if you needed additional assistance here.

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
​Hi @LuoXin-s, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
​
