### ISSUE TITLE
`wandb.apis.public.Run.upload_file` overwrites the file if already exists in `wandb` remote

### ISSUE THREAD

**Issue by alvarobartt** [wandb/wandb#3944]
So the default behavior of https://docs.wandb.ai/ref/python/public-api/run#upload_file is to upload the file without taking into consideration whether that file was already there or not, so it's not actually checking whether the file exists in the `wandb` remote or not, it's just uploading it.

Shouldn't this be handled through a parameter `replace: bool = False` just like for https://docs.wandb.ai/ref/python/public-api/file#download?

I've been playing around with these functions these days and I've filled one PR for each function:
* https://github.com/wandb/client/pull/3929
* https://github.com/wandb/client/pull/3924

But is this something we should consider? Or the default behavior is supposed to work like this?

Thanks! 🤗

**Comment by alvarobartt** [comment]
As I've already modified the logic/behavior of `wandb.apis.public.Run.upload_file` in https://github.com/wandb/client/pull/3929, in case this is something to consider adding, we should do it over the following code:

**Comment by nate-wandb** [comment]
Hi @alvarobartt, thank you for the request and the PR's! It looks like the engineering team is working on getting both of them merged.

Let me know if you have any other questions around this that I can help with.

We appreciate your contributions!
-Nate
