### ISSUE TITLE
[Q] C:\Users\MyName\anaconda3\envs\ML\python.exe: can't find '__main__' module in '' when running wandb agent on terminal

### ISSUE THREAD

**Issue by TheodoreWolf** [wandb/wandb#3946]
Hi, I started a hyperparam sweep on a notebook to get a feel for how it works but I had to pause it. I would like to continue running this run through my terminal by running the command given in the info tab of my sweep. But every time I try to run this command, I see that I get the correct sweep configuration that comes through but then when it tries to run I get the following 
error C:\Users\MyName\anaconda3\envs\ML\python.exe: can't find '__main__' module in '' which cancels the run. 

I'm not adamant about running it through the command line but I can't find in the documentation how to continue a hyperparameter sweep run through jupyter. 
Andy help is appreciated.

Thanks.

**Comment by ramit-wandb** [comment]
Hi @TheodoreWolf,

Could you share the steps you took to reach this error? I'll help look into this for you

**Comment by ramit-wandb** [comment]
Hi @TheodoreWolf,

We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by TheodoreWolf** [comment]
Hi sorry, for not replying sooner, but I fixed my issue, so I'm all good now, thanks though!

**Comment by ramit-wandb** [comment]
Glad to hear! Closing this issue out.

**Comment by uchennailodigwe** [comment]
> Hi sorry, for not replying sooner, but I fixed my issue, so I'm all good now, thanks though!

Hey @TheodoreWolf  please can you help share how you resolved it as i am having the same error .Thanks

**Comment by V0XNIHILI** [comment]
I had the same issue but found out that it was due to the fact that I forgot to add the key (+value) `program: program_name.py` to my sweep config!
