### ISSUE TITLE
[Q]I try to insert 'plotly' to 'table', but only shown text.

### ISSUE THREAD

**Issue by ma-chengcheng** [wandb/wandb#3954]

**Comment by ma-chengcheng** [comment]
`wandb.init('test')
N = 5
menMeans = (20, 35, 30, 35, 27)
womenMeans = (25, 32, 34, 20, 25)
menStd = (2, 3, 4, 1, 2)
womenStd = (3, 5, 2, 3, 3)
ind = np.arange(N)  # the x locations for the groups
width = 0.35  # the width of the bars: can also be len(x) sequence

p1 = plt.bar(ind, menMeans, width, yerr=menStd)
p2 = plt.bar(ind, womenMeans, width,
             bottom=menMeans, yerr=womenStd)

plt.ylabel('Scores')
plt.title('Scores by group and gender')
plt.xticks(ind, ('G1', 'G2', 'G3', 'G4', 'G5'))
plt.yticks(np.arange(0, 81, 10))
plt.legend((p1[0], p2[0]), ('Men', 'Women'))
# plt.show()
tb = w.wandb.Table(columns=['user', 'figure'], allow_mixed_types=True)
tb.add_data('user', wandb.Plotly(plt.gcf()))
wandb.log({'test': tb})`

**Comment by ramit-wandb** [comment]
Hi! Currently, Tables do not support Plotly figures. You should be able to convert them to a `wandb.Image` and see the plots displayed in the table.

**Comment by ma-chengcheng** [comment]
> Hi! Currently, Tables do not support Plotly figures. You should be able to convert them to a `wandb.Image` and see the plots displayed in the table.

Thank you!
