### ISSUE TITLE
[App]: Point clouds no longer offer 3D view

### ISSUE THREAD

**Issue by drscotthawley** [wandb/wandb#3955]
### Current Behavior

Reposting from https://community.wandb.ai/t/point-clouds-no-longer-3d-viewable/2770

Point cloud view no longer offers the "X" in the upper right on mouseover to offer transition from full 3D view (e..g. rotations supported).
This used to work. But now the X is gone. 

Here's [my example](https://wandb.ai/drscotthawley/dubstep-diffgan).   Arg. LINK FAILURE: In the WandB run page, I went to the point cloud panel I wanted to share and selected “Share panel” and then “Anyone with the link can view” but it’s still not giving you a direct link to the pane. So because it’s not linking directly to the panel you’ll have to scroll through “Media” until you find “embeddings_3dpca”.

### Expected Behavior

That when mousing over an image of the point cloud, an "X" would appear in the top right of the image, which you could then click on to get a full 3D view.  This used to be the case, but is no longer appearing. 

### Steps To Reproduce

To reproduce: go to any WandB page for point cloud that used to be viewable in 3D, whether in documentation or in your own runs. You will see that there is no longer a way to make it 3D.

Try [my example](https://wandb.ai/drscotthawley/dubstep-diffgan) run, or [“3D Objects Live Example”](https://wandb.ai/nbaryd/SparseConvNet-examples_3d_segmentation/reports/Point-Clouds--Vmlldzo4ODcyMA) or [“3D Molecules”](https://wandb.ai/stacey/alphafold?workspace=user-stacey).

### Screenshots

Screenshot may not be informative because X is not appearing.  Used to be an "X" would appear in the upper right of the image when you ran the mouse over it. 
![2022-07-19_17-37](https://user-images.githubusercontent.com/13925685/179803578-56d677e5-22f2-4629-b5ee-f9e6616133c7.png)
Or you could expand to "full screen" and similarly an X would appear when you mouse over. 

### Environment
Anything I've tried so far. 

OS: Ubuntu Linux and/or iOS

Browsers: iOS: Safari.  Ubuntu: Brave, Chrome, and/or Firefox

Chrome Version 102.0.5005.115 (Official Build) (64-bit)
Brave [Version 1.37.116 Chromium: 100.0.4896.127 (Official Build) (64-bit)](https://brave.com/latest/)

### Additional Context

See my forum post here: https://community.wandb.ai/t/point-clouds-no-longer-3d-viewable/2770

**Comment by armanhar** [comment]
Hey Scott, thanks for the detailed report. I'll reproduce the issue and file a ticket.

**Comment by drscotthawley** [comment]
@armanhar thanks. I'll add: seems to be an intermittent / machine-dependent bug.  Sometimes the point clouds are 3D-ify-able, other times not.  
Again, used to be everything worked great.
On my current run (https://wandb.ai/drscotthawley/audio-algebra?workspace=user-drscotthawley), I'm not able to rotate the point clouds on any machine or browser I try.

**Comment by drscotthawley** [comment]
One more update: Ok that run I just linked to, I can actually view the "X" and 3D view using Firefox on Ubuntu.  Not Chrome or any Chromium-based browser though.

**Comment by drscotthawley** [comment]
...wait, spoke to soon... that was while I was not logged in via Firefox.  Once I logged in on Firefox, the X's went away!    So it seems to be that you have to be NOT logged in  for it to work. 

...or maybe have Dark Theme off? -- But I don't seem to disable Dark Theme anymore.  I removed "night" from my profile text but thing's didn't go back to light theme.

**Comment by drscotthawley** [comment]
SOLVED!   @armanhar whatever you guys did when you upgraded Night Mode broke 3D viz for point clouds.  turning off night mode restores 3D view on all browers & systems.  :-)
