### ISSUE TITLE
[CLI]: Can't change save_dir in wandb + PyTorchLightning

### ISSUE THREAD

**Issue by azinonos** [wandb/wandb#3965]
Hi,

I'm trying to change the local save directory for my experiments so they don't get stored under the default "wandb" folder. I'm instantiating a WandbLogger instance from PyTorch Lightning as shown below, passing "save_dir" as one of the parameters. However, when running the code it seems like this does nothing. The new experiment is created (I can see it on the web app), but it doesn't seem to be saved anywhere locally.

Example:
```python 
# Imports
...
from pytorch_lightning.loggers import WandbLogger

# Instantiate logger
wandb_logger = WandbLogger(
        config=cfg,
        save_dir="results/EXP_NAME"
)
```

I've tried different combinations of this, for example adding only "save_dir='wandb'" in the configuration, and this creates a nested "wandb" folder inside the original "wandb" folder. Anything else though, such as "save_dir='results/EXP_NAME'" just lead to the above, where the local files are saved nowhere. So the only way is to remove the save_dir parameter and then have all my experiments save in the default wandb.

Can someone help debug this? Thanks in advance.

### Environment

WandB version: 0.12.10

OS: Linux 5.13.0-1025-aws

Python version:3.8.12

Versions of relevant libraries:
pytorch-lightning         1.5.9

### Additional Context

I'm also using hydra to instantiate the wandb object and pass the parameters, but I have tried doing it without it (like the code given above) for more simplicity, with the same problem.

**Comment by MBakirWB** [comment]
Hi @azinonos ,

WandbLogger() `save_dir` expects the directory to already exist. It's  an absolute path to where metadata will be stored. You are correct that by default this is `./wandb` if a user doesnt defines their own directory. If for example the directory `results/EXP_NAME` doesn't already exist when instantiating your logger , 

```
# Instantiate logger
wandb_logger = WandbLogger(
        config=cfg,
        save_dir="results/EXP_NAME"
)
```

wandb will log the warning

`wandb: WARNING Path results/EXP_NAME/wandb/ wasn't writable, using system temp directory.`

If the directory exists however, you will see wandb log

`Run data is saved locally in results/EXP_NAME/wandb/run-20220722_055024-156puage`

Please let me know if you have any questions. Additionally, please note we recommend our users to update to the latest CLI version, which is currently at **wandb 0.12.21**

**Comment by MBakirWB** [comment]
Hi @azinonos, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by azinonos** [comment]
Thanks for the responses, and apologies for the slow response. Ok, sounds good. I'm wondering whether it would be better to throw an error instead of a warning, as the warning got lost among other output I had and I didn't see it, which led to a couple of hours of frustratingly trying to see where these files disappeared.

**Comment by bfs18** [comment]
> [CLI]: Wandb tries to write to /wandb/ even when dir argument is specified #4600

I think the save_dir should be created before wandb.init() in lightning.
