### ISSUE TITLE
[Feature]: Automatically group metrics into windows in the GUI

### ISSUE THREAD

**Issue by andrewwarrington** [wandb/wandb#3967]
### Description

I would like a way of designating a metric when I log it to appear in the Hidden Windows section*.  

It is annoying that if I push to a new project I have to go through and sift out all of the metrics that I want to store but not show. 

(or maybe even a separate window section.)

### Suggested Solution

something like `Wandb.log(METRIC, hidden=True)` (where the default is `hidden=False`).  Then the GUI sorts metrics based on the `hidden` flag.

### Alternatives

Ideally, there would be a `metric_group` field, that allowed metrics to be displayed in separate GUI windows automatically. 

Alternatively, maybe if one could copy the GUI config from one project to another?  If there is a setting for a particular metric in the GUI config then it is applied to the new project.  

### Additional Context

We use projects for sorting experiments to keep individual projects smaller and easier to use.  I realise this is maybe not the most common modus operandi, however...

**Comment by andrewwarrington** [comment]
I see something related to this was discussed in #3926.  I also like the feature request made in that issue, but would still request that metrics can have a usable grouping field when first logged.  Maybe this field can even be used as part of generating / administering the layouts suggested in #3926.

**Comment by nollied** [comment]
yes, this would be an AMAZING feature to have! it would save me at least 20% of setup time.

**Comment by nollied** [comment]
something like:

```python
wandb.log({"validation_loss": val_loss, "training_loss": train_loss}, same_graph=True)
```

this would automatically hide the `validation_loss` and `training_loss` metrics individually, and on the UI it would show them on a single graph.

**Comment by nate-wandb** [comment]
Hi @andrewwarrington and @nollied! While we don't have the exact thing you are looking for, I believe you could use our prefix grouping as a solution here. If you give a metric a prefix in the form or "prefix_name/metric_name" it will automatically add all of the metrics with the same "prefix_name" to the same panel. 

@andrewwarrington in your use case you could call 
`wandb.log({"hidden_panel/metric_I_want_to_hide_1": metric_1, "hidden_panel/metric_I_want_to_hide_2": metric_2, "metric_I_want_to_see": metric_3})`
And then hide "hidden_panel" once in the UI to collapse all of these metrics.

@nollied there isn't something to specify the same plot via the UI but I can certainly put in a feature request around this if you would like?

Also, as note we are currently working on templates of workspaces which I believe will help out both use cases and allow for a quicker setup of new projects. 

Thank you,
Nate

**Comment by nollied** [comment]
yeah that would be cool if you could put it in a feature request thanks for the response @nate-wandb

**Comment by nate-wandb** [comment]
@nollied great! I'll go ahead and put that in for you and follow up once the engineering team has had a chance to look at this.

Thank you,
Nate

**Comment by andrewwarrington** [comment]
Hi WandB,

Yep, using the "hidden_pannel/METRIC" does what I need it to do.  Thanks!  I am happy to close this issue.
