### ISSUE TITLE
[Feature]: time per step

### ISSUE THREAD

**Issue by alexandre-dang** [wandb/wandb#3971]
### Description

I would like to log the time per step (or the number or steps over time).

I'm working with images of different sizes and knowing how much it affect the training speed would be very useful in that case.

Maybe I didn't use the charts properly and you can do it, but I didn't find anyone asking or explaining how to do it so I'm making a feature request

### Suggested Solution

It seems that both the step and the time are automatically logged by wandb, but for some reason I cannot make a graph that shows both (either time per step or steps over time)

**Comment by armanhar** [comment]
Hey @alexandre-dang, thanks for writing in. Not sure why we don't allow plotting step and time against each other. I'll file a ticket for your feature request.

**Comment by anmolmann** [comment]
Hi @alexandre-dang, apologies for the delay this one. I was going through your request, are you looking for something like the follwoing chart: 
![image](https://user-images.githubusercontent.com/20401632/184051296-392e8fd6-bdb3-43a8-b87c-3f42db0b5dc5.png)

**Comment by alexandre-dang** [comment]
Yes !
I mean, ultimately what I really want is the derivative (how long each step takes) but this is enough, thank you vrey much

**Comment by anmolmann** [comment]
Thanks for the update, @alexandre-dang! Glad we could help.

**Comment by sjkoelle** [comment]
Do we have to log _timestamp explicitly to make this happen?
