### ISSUE TITLE
[Q] Sweep line plot not colored by metric after sweep iteration is completed

### ISSUE THREAD

**Issue by EricKeenan** [wandb/wandb#3976]
I'm using sweeps to optimize hyperparmaeters on a YOLOv5 model. I've noticed that the sweep line plots are only colored according to my defined metric (`metrics/mAP_0.5:0.95`) during training for each iteration. I.e. once each iteration is complete, the line goes gray. e.g
<img width="1080" alt="Screen Shot 2022-07-22 at 1 32 41 PM" src="https://user-images.githubusercontent.com/44210245/180560490-4ac72248-5b85-428d-8c24-d3cf4b33278d.png">
Any idea how I can ensure that each iteration's line is colored according to the metrics? Both during and after each iteration's training? 

For reference I'm running `wandb v0.12.20` and using a custom call, e.g.
```python
# Define training function
def train(config=None):
    
    # Initialize a new wandb run
    with wandb.init(config=config):
        # If called by wandb.agent, as below,
        # this config will be set by Sweep Controller
        config = wandb.config
        
        # Modify hyps
        epochs = config.epochs
        src_path = "/home/ubuntu/repos/Steely_modeling/data/yolo_input/hyp.yaml"
        tgt_path = "/home/ubuntu/repos/Steely_modeling/data/yolo_input/hyp_sweep.yaml"
        hyp_dict = {"scale": config.scale,
                    "shear": config.shear,
                    "obj_pw": config.obj_pw,
                    "obj": config.obj,
                    "cls": config.cls,
                    "warmup_momentum": config.warmup_momentum,
                    "warmup_epochs": config.warmup_epochs,
                    "momentum": config.momentum,
                    "lr0": config.lr0,
                    "lrf": config.lrf,
                   }
        update_hyp_yaml(src_path, tgt_path, hyp_dict)
        
        # Train YOLOv5
        !(cd ../../yolov5/; \
        conda activate yolo; \
        python -m torch.distributed.launch \
            --nproc_per_node 4 train.py \
            --batch 40 \
            --data /home/ubuntu/repos/Steely_modeling/data/yolo_input/dataset.yaml \
            --cfg models/yolov5x.yaml \
            --hyp /home/ubuntu/repos/Steely_modeling/data/yolo_input/hyp_sweep.yaml \
            --project steely_yolo \
            --name steely_v1p5_yolov5x_c512_s512_i1024_neg_cl10_ \
            --epochs {epochs} \
            --img-size 1024 1024 \
            --device 0,1,2,3 \
            --weights yolov5x.pt)   
```

Which I then call using an agent
```python
# Run sweep
wandb.agent(sweep_id, train, count=100)
``` 

If it is any troubleshooting use to `wandb` devs, my sweep is located at https://wandb.ai/maxar-technologies/steely_yolo/sweeps/p8otld2h?workspace=user-ekeenan

**Comment by nate-wandb** [comment]
Hi @EricKeenan, it looks like that metric is reporting as `null` in the UI which is causing the run to turn gray. Could you show me how you define and log your custom metric and in your Yolo script? 

Thank you,
Nate

**Comment by EricKeenan** [comment]
Managed to get a sweep working properly. https://wandb.ai/maxar-technologies/steely_yolo/sweeps/5bt90aob?workspace=user-ekeenan

The trick was to upgrade my YOLOv5 source from tag v5 to tag v6.

I suspect this solution will work. But I'm still working through some down stream consequences. Going to leave this open just in case I need to revert back to tag v5.

**Comment by EricKeenan** [comment]
I'll close the issue once I confirm my solution is suitable.
