### ISSUE TITLE
[Q] Running W&B locally in jupyter 

### ISSUE THREAD

**Issue by WasifurRahman** [wandb/wandb#3985]
Hi,
I train my models in a system wthout internet access and then sync the wandb outputs with the wand-local server running in my laptop.

If I run the code below (with a valid API key) in a regular python file, it works correctly. However, if I run the same code in jupyter, the run stalls for a long time. I have attached a part of the error message I got after stopping the kernel. 

```
import wandb
import os

#copy your API key here
os.environ["WANDB_API_KEY"] = 'local-***'
os.environ["WANDB_MODE"] = 'dryrun'
wandb.init(project="my-test-project_1",entity ="_")
wandb.config = {
  "learning_rate": 0.001,
  "epochs": 100,
  "batch_size": 128
}
loss=0.01
wandb.log({"loss": loss})
wandb.log({"another_loss":0.05})
```

<img width="1030" alt="Screen Shot 2022-07-25 at 8 35 26 PM" src="https://user-images.githubusercontent.com/8361099/180897846-13f59580-116c-438d-9471-2b97623f65ec.png">

**Comment by ramit-wandb** [comment]
Hi @WasifurRahman!

Could you share the full error message you see along with the version of `wandb` you currently have installed? I'll help look into this for you.

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
​Hi @WasifurRahman ,

We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.
​

**Comment by WasifurRahman** [comment]
Thanks a lot for reaching out.

It's working now. I believe I made a mistake before.

**Comment by ramit-wandb** [comment]
Glad to hear you were able to resolve it! I'll go ahead and close this issue out in that case.
