### ISSUE TITLE
[Q] Config item 'name_of_experiment' was locked by 'sweep' 

### ISSUE THREAD

**Issue by antonagafonov** [wandb/wandb#3993]
Hi,
I am performing a sweep and creating the random names of experiments inside the training loop, the problem is, that I cannot update the name inside wandb.config
![image](https://user-images.githubusercontent.com/63194980/181207222-b781e437-a70f-48a1-b311-52d4b222915a.png)

**Comment by lesliewandb** [comment]
Hi @antonagafonov, can you show me how you are updating the config to change the sweep name? A code snippet will suffice

**Comment by antonagafonov** [comment]
Hi,
Yes. Tried in two ways, but none of them succeeded.

![image](https://user-images.githubusercontent.com/63194980/182536424-a9621a32-2fe6-470e-9cd0-3b3d66497492.png)

![image](https://user-images.githubusercontent.com/63194980/182536496-1d1bd89e-f8c8-47fb-93ae-212f90b065f8.png)

Thanks.

Anton

**Comment by lesliewandb** [comment]
Hi Anton, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
