### ISSUE TITLE
[Q] Using wandb on SLURM

### ISSUE THREAD

**Issue by EmanueleFrancazi** [wandb/wandb#4034]
Usually to use wandb on a machine/server the first step to do is to login ([wandb login](https://docs.wandb.ai/quickstart)). 
In cluster, as SLURM, we login in a node but the code will run on a different one; how should one proceed to login in wandb?

I read that the login in wandb can be performed by environment variable [WANDB_API_KEY](https://docs.wandb.ai/guides/track/advanced/environment-variables).
In fact the description in the above link says: "Sets the authentication key associated with your account. This must be set if wandb login hasn't been run on the remote machine." which seems exatly my case.

I didn't understand exatly how to use (and where to put the environment variable (python code, slurm script..)). I tried to define the WANDB_API_KEY variable in the slurm script but this didn't work.
Can you explain how to proceed?

**Comment by MBakirWB** [comment]
Hi @EmanueleFrancazi , can you provide example of how you define the Env variable. Additionally, you can set the environment variables in the node running your code before the script runs or within the script.

**Comment by EmanueleFrancazi** [comment]
the structure that I'm using for my run is the following:
the command `sbatch slurm_script.sh` execute the slurm script; this one, in turn call a bash script (bash_script.sh) that finally call the python code which perform the simulation

I set the environment variable in the slurm script, before the command that launch the python code.
Here there is the complete slurm_script.sh :+1: 
```
#!/bin/bash

#SBATCH --job-name=Test                    #This is the name of your job
#SBATCH --cpus-per-task=4                  #This is the number of cores reserved
#SBATCH --mem-per-cpu=1G              #This is the memory reserved per core.
#Total memory reserved: 4GB

#SBATCH --time=23:50:00        #This is the time that your task will run
#SBATCH --qos=1day           #You will run in this queue

# Paths to STDOUT or STDERR files should be absolute or relative to current working directory
#SBATCH --output=myrun.o%j     #These are the STDOUT and STDERR files
#SBATCH --error=myrun.e%j

#SBATCH --partition=Gpu_partition_name
#SBATCH --gres=gpu:1

#This job runs from the current working directory


#Remember:
#The variable $TMPDIR points to the local hard disks in the computing nodes.
#The variable $HOME points to your home directory.
#The variable $SLURM_JOBID stores the ID number of your job.


#load your required modules below
#################################

source $HOME/Environments/env/bin/activate


#export your required environment variables below
#################################################

WANDB_API_KEY=42

#add your command lines below
#############################

nohup ./bash_script.sh 

deactivate
~                                                                                                                                                                                                          
~                              
```
where instead of 42 in the field WANDB_API_KEY there is my real key

**Comment by EmanueleFrancazi** [comment]
I substituted the line `WANDB_API_KEY=42` with `export WANDB_API_KEY=42` and now the code seems to run correctly; since [here](https://docs.wandb.ai/guides/track/advanced/environment-variables) the use of the env variable is not descibed in detail and as is the first time that I use it, could you explain me how to handle them in general (or send a ref that explain this) ?

Even if the simulation now is running I got the following exception:
```
Traceback (most recent call last):
  File "/scicore/soft/apps/Python/3.7.3-foss-2018b/lib/python3.7/urllib/request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/scicore/soft/apps/Python/3.7.3-foss-2018b/lib/python3.7/http/client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/scicore/soft/apps/Python/3.7.3-foss-2018b/lib/python3.7/http/client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/scicore/soft/apps/Python/3.7.3-foss-2018b/lib/python3.7/http/client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/scicore/soft/apps/Python/3.7.3-foss-2018b/lib/python3.7/http/client.py", line 1016, in _send_output
    self.send(msg)
  File "/scicore/soft/apps/Python/3.7.3-foss-2018b/lib/python3.7/http/client.py", line 956, in send
    self.connect()
  File "/scicore/soft/apps/Python/3.7.3-foss-2018b/lib/python3.7/http/client.py", line 1384, in connect
    super().connect()
  File "/scicore/soft/apps/Python/3.7.3-foss-2018b/lib/python3.7/http/client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/scicore/soft/apps/Python/3.7.3-foss-2018b/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/scicore/soft/apps/Python/3.7.3-foss-2018b/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host
```
what does it imply and what should I do to fix it?

Sorry for the dummy questions :)

**Comment by MBakirWB** [comment]
Hi @EmanueleFrancazi ,

`[Errno 113] No route to host `denotes a network problem with your computer being unable to reach the target server.  Are you running a local version of wandb? If so please see this [github response](https://github.com/wandb/wandb/issues/3382#issuecomment-1068578844) for some feedback. 

Additionally when running a SLURM job  you should submit the job using `export` flag for the `WANDB_API_KEY`  env variable. Besides our documents on environmental variables you referenced above, this [thread](https://github.com/wandb/wandb/issues/3382) on running a SLURM job parallels your questions on setting up a SLURM script.

**Comment by MBakirWB** [comment]
Hi @EmanueleFrancazi , do you still need assistance/feedback with the issue you were experiencing running a SLURM job. Did the links above help?

**Comment by MBakirWB** [comment]
Hi @EmanueleFrancazi, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by EmanueleFrancazi** [comment]
Hi @MBakirWB,
sorry for the delay in my replay but I was out in the last weeks. The export flag solved the problem; I've also set wandb offline since the computing server has not access to internet. Thank you for all the support ;)

**Comment by MBakirWB** [comment]
HI @EmanueleFrancazi , no worries, and thank-you for the update and I'm glad you were able to resolve issues on your end.
