### ISSUE TITLE
[Q] Adding custom folder/files to wandb server when running RLib

### ISSUE THREAD

**Issue by dejangrubisic** [wandb/wandb#4037]
When running wandb inside RLlib, the documentation says we need to use WandbLoggerCallback (or whatever new API) to get metrics, but since we don't define wandb.init and wandb.finish, wandb.save() is not working, and copying the folder/files we want to save to wandb_run_dir doesn't send it to the server.

Do you have any suggestions on how to do this?

Thanks!

**Comment by nate-wandb** [comment]
Hi @dejangrubisic, it doesn't look like this is possible with the standard `wandb.save()` when using the `WandbLoggerCallback`. You can still access the `run_id` with `wandb.run.id` so you could using the [public api](https://docs.wandb.ai/guides/track/public-api-guide#upload-files-to-a-finished-run) to access the run and upload the files. 

I'll check with our engineering team and if you would like I can put in a feature request around this?

Thank you,
Nate

**Comment by dejangrubisic** [comment]
I confirm that I can send the files to the wandb repository with run_id, but I cannot find a way to set run_id myself.
The instructions from [class WandbLogger(Logger)](https://docs.ray.io/en/latest/_modules/ray/tune/integration/wandb.html)  say:
`Wandb's ``group``, ``run_id`` and ``run_name`` are automatically selected by Tune, but can be overwritten by filling out the respective configuration values.`

But suggested approaches doesn't really work for 'run_id'. 

wandb.run.run_id doesn't work since wandb.run == None.

The only solution I see is to find the newest file in logging wandb folder and to extract run_id from there

**Comment by MBakirWB** [comment]
Hi @dejangrubisic , can you try to call wandb.init before initializing wandblogger. Within wandb init, set the run_id, and use wandb.save() after initializing the run.

**Comment by MBakirWB** [comment]
Hi @dejangrubisic, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
