### ISSUE TITLE
WandB naming issue

### ISSUE THREAD

**Issue by qh2150** [wandb/wandb#4048]
Hello, around 1am EST I started encountering an issue in all of my runs (using google colab).  All of the run names are being assigned the project name (see below).  The crashed jobs were just jobs I aborted after I noticed this happening.  This is happening across all code pieces and across all projects.  The exact same code was fine just before this happened and now all W&B jobs have this issue, do you have any advice?  Thank you!
![wandbissue](https://user-images.githubusercontent.com/54342838/182694941-d955eaaa-f3fe-4dd8-9c16-69c6704023c5.png)
!

**Comment by johndoeaki** [comment]
- [ ] Approved

**Comment by johndoeaki** [comment]
- [ ]

**Comment by qh2150** [comment]
This is the link to the workspace where the issue occurs.
https://wandb.ai/qhershey/ML-test/table?workspace=user-qhershey

I'm not setting the name or id parameter in wandb.init, as a note I am using it through PyTorch Lightning's WandbLogger() which declares those by default as None.  Prior to this, there was no issue using the same code.

**Comment by samgelman** [comment]
Check out this thread: https://github.com/Lightning-AI/lightning/issues/14054
Hopefully there will be a fix soon.

**Comment by qh2150** [comment]
Thank you samgelman, the workaround posted there is very helpful, thank you!

**Comment by ramit-wandb** [comment]
Hey @qh2150 @samgelman!

This issue should now be fixed with the release of PyTorch Lightning 1.7.2 🎉. I'm going to close this issue out, but in case you see any other issues surrounding this, please feel free to reply to this thread and I will be more than happy to assist you further.

Cheers!
Ramit
