### ISSUE TITLE
[Q] TensorBoard data does not upload to WandB properly after upgrading from 0.12.20 to 0.13.0

### ISSUE THREAD

**Issue by Ji4chenLi** [wandb/wandb#4055]
Hi,

Thank you again for developing the amazing tools!

I am using WandB along with tensorboard. Moreover, I am doing training and evaluation in a multiprocessing manner. Thus, I call `wandb.init` in all my processes and use the group keyword argument to define a shared group as suggested in the documentation.

Recently, I upgraded my WandB from 0.12.20 to 0.13.0. However, only the main-process results are logged in my wandb workspace. For the evaluation results that are done by a remote worker (in a different process), they do not show in the workspace. However, I can still access its `Tensorboard` information on the wandb webpage. This issue does not happen to version 0.12.20.

Could help me have a look on this? Happy to provide more details if needed!

Thanks,
Jiachen

**Comment by thanos-wandb** [comment]
Hi @Ji4chenLi , thank you for reporting this issue! 

Could you please upgrade to the latest version 0.13.1 and see if that issue still persists? what arguments do you use with `wandb.init`? are you using `sync_tensorboard=True`? Would it be also possible to share a workspace so that we see what is being logged to the UI?

**Comment by thanos-wandb** [comment]
Hi @Ji4chenLi I wanted to follow up with you regarding this issue. Please let me know if your issue has been resolved or if we can be of any further assistance.

**Comment by thanos-wandb** [comment]
Hi @Ji4chenLi, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
