### ISSUE TITLE
[CLI]: wand.Image fails with some seaborn plots

### ISSUE THREAD

**Issue by jzazo** [wandb/wandb#4057]
### Describe the bug

When trying to log a seaborn plot with `wandb.Image`, e.g., Facetgrid, it raises an `AttributeError`.

```python
import os

import seaborn as sns
import wandb

tips = sns.load_dataset("tips")

g = sns.FacetGrid(tips, col="time", row="sex")
g.map(sns.scatterplot, "total_bill", "tip")

wandb.init()
wandb.Image(g)
```

Error output:
```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/javier/repos/immunocam/immunocam-app/src/python/immunocam/app/jupytext/mwe_facegrid.py in <cell line: 3>()
      17 # %%
      18 wandb.init()
----> 19 wandb.Image(g)

File ~/.cache/pypoetry/virtualenvs/immunocam-app-5TDetCSo-py3.8/lib/python3.8/site-packages/wandb/sdk/data_types.py:2086, in Image.__init__(self, data_or_path, mode, caption, grouping, classes, boxes, masks)
   2084     self._initialize_from_path(data_or_path)
   2085 else:
-> 2086     self._initialize_from_data(data_or_path, mode)
   2088 self._set_initialization_meta(grouping, caption, classes, boxes, masks)

File ~/.cache/pypoetry/virtualenvs/immunocam-app-5TDetCSo-py3.8/lib/python3.8/site-packages/wandb/sdk/data_types.py:2208, in Image._initialize_from_data(self, data, mode)
   2206 if hasattr(data, "numpy"):  # TF data eager tensors
   2207     data = data.numpy()
-> 2208 if data.ndim > 2:
   2209     data = data.squeeze()  # get rid of trivial dimensions as a convenience
   2210 self._image = pil_image.fromarray(
   2211     self.to_uint8(data), mode=mode or self.guess_mode(data)
   2212 )

AttributeError: 'FacetGrid' object has no attribute 'ndim'
```

I solved the issue by writing first the image to `png` and then logging the image, but that is something that actually `wandb.Image` could handle, if there is no better solution:
```python
# %%
g.savefig("facetgrid.png")
wandb.Image("facetgrid.png")
```
Thanks!

### Environment

WandB version: 0.12.9
OS: Ubuntu 20.04
Python version: 3.8.10
Versions of relevant libraries: seaborn (0.11.2).

**Comment by nate-wandb** [comment]
Hi @jzazo, I don't think you would be able to log your Seaborn plot as an in Image in this way. You should be able to log your Seaborn plot simply with `wandb.log({"plot_name": g})` and pass the plot directly into `wandb.log`. Was there a reason you were trying to convert this to an image first?

Thank you,
Nate

**Comment by jzazo** [comment]
That's how it's described in the [documentation](https://docs.wandb.ai/guides/track/log/media#images), "Logging images from Files" tab, i.e.,
```python
im = PIL.fromarray(...)
rgb_im = im.convert('RGB')
rgb_im.save('myimage.jpg')

wandb.log({"example": wandb.Image("myimage.jpg")})
```
Do I not need to save a `.png` image first then? Thanks.

**Comment by nate-wandb** [comment]
@jzazo if you would like to save it as an image that is certainly an option. I realized a mistake I made earlier though. You can't pass a `FacetGrid` into `wandb.log` but the `FacetGrid.figure` is what you need to pass in here. 

So the two options would be to save as an image as you were before and then loading the image into a `wandb.Image` or save the figure with `wandb.log({'plot': g.figure})`.

The second method will maintain interactivity when you view the plot in the UI rather than simply display the plot as an image.

https://user-images.githubusercontent.com/97066933/184392485-ce396e67-1017-4e4e-8341-24dafe1679cd.mov

**Comment by MBakirWB** [comment]
Hi @jzazo , following up on this thread. Did @nate-wandb feedback assist in resolving this for you?

**Comment by MBakirWB** [comment]
Hi @jzazo , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by jzazo** [comment]
Thank you, I haven't had time to try it yet, but I will soon. If I encounter any issue I will reopen.
