### ISSUE TITLE
[Q] Account Migration

### ISSUE THREAD

**Issue by Limingxing00** [wandb/wandb#4067]
hi,

I registered wandb on my google account by default, and after 250 hours of operation, it shows that I need to charge. I am an individual (academic) and I have re-registered an account with my school email. How to migrate my previous records.

I tried using wandb sync locally and it showed wandb: ERROR Nothing to sync.

what should I do?

**Comment by MBakirWB** [comment]
Hi @Limingxing00 , you cannot sync work between two accounts. If you want I can transfer your projects from your personal to your academic account. Please provide me the email addresses or wandb user ids for both accounts and let me know what projects you would like moved and from which id.

**Comment by Limingxing00** [comment]
Hi,

The old repo is `zhongbao-gaode/new-baseline` for account `limingxing.qq@gmail.com`.

The new account  is `mxli@mail.ustc.edu.cn`. And I need to transfer old repo to `mingxing-zhongbao/new-baseline` for new account.

Thank you!

**Comment by MBakirWB** [comment]
Hi @Limingxing00 , the projects have been moved.

**Comment by Limingxing00** [comment]
Thank you!
