### ISSUE TITLE
[App]: Credentials rejected when signing into localhost:8080 for wandb local

### ISSUE THREAD

**Issue by aclifton314** [wandb/wandb#4080]
### Current Behavior

I have posted this [issue](https://community.wandb.ai/t/unable-to-login-using-wandb-local/2868) on the forum, but will detail it here as well.

I was able to log into localhost:8080 via `wandb local` last week with the same credentials I used to post to the wandb forum. However, this week those credentials are being rejected and I get an “Error while trying to reset password” message when I try to reset the password.

### Expected Behavior

To successfully login to localhost:8080 using `wandb local` and view the runs that have been synced.

### Steps To Reproduce

1. conda activate my_env
2. wandb local
3. In a browser navigate to http://localhost:8080
4. Click login
5. Use credentials to login
6. Credentials are rejected

### Environment

OS: Ubuntu 20.04.4 LTS

Browsers: Firefox 103.0

Version: wandb 0.12.17

### Additional Context

Thanks in advance for your help!

**Comment by fdsig** [comment]
Hey @aclifton314 , Let us know if you need any further help and if you have been able to log in to wandb server (wandb local).

**Comment by aclifton314** [comment]
@fdsig Thanks for your suggestions. I went ahead and updated wandb and wandb server. I started wandb server with `wandb server start` and navigated to `http://localhost:8080` and got an error that says "Application Error. An application error occured."

I then ran:
```
docker exec -it wandb-local bash 
/usr/local/bin/local password user@email.com
```
and changed the password. I ran `wandb server stop`, then `wandb server start`, and got the same "Application Error. An application error occured."

**Comment by fdsig** [comment]
Hi @aclifton314 , sorry to hear you are still running into some issues. 

The best option here might be to stop the wandb docker container remove the docker image altogether and start with a new container. (This can be done both in the docker app and using docker CLI). Then clear your browser history and then go to `http://localhost:8080` in your web browser and also try a  private browser session. 

Could I also ask here where you are running WandB server?

**Comment by aclifton314** [comment]
@fdsig Sure thing. Do you mind telling me what those commands are? I'm not super familiar with docker at this point. 

I'm not sure I understand what is meant by "where are you running the WanDB server". I have been running it through the CLI on my desktop that is running Ubuntu 20.04.4.

**Comment by fdsig** [comment]
Hi @aclifton314 , Thanks for the update. you can first stop your container with `docker stop wandb-local` and then  use:

```docker rmi wandb/local:latest```

to remove the image.  If you want to see what docker images you have you can also list images using ```docker images -a```

If your needing to run sudo with docker command and this is blocking `wandb server start` then running:

```sudo setfacl -m user:$USER:rw /var/run/docker.sock```

gives permission to docker to start containers on local host (sharing as Ubuntu distros don't always have this by default ).

 I hope this helps and let us know if you need any further help.

**Comment by aclifton314** [comment]
@fdsig thanks for your reply. I ran the following:
```
docker stop wandb-local
docker rmi wandb/local:latest
```
I then made sure to update `wandb` and start the server:
```
pip install wandb --upgrade wandb 
wandb server start --upgrade
```

which produced the following:
```
Command '['docker', 'inspect', 'wandb/local', '--format', '{{json .RepoDigests}}']' returned non-zero exit status 1.
Unable to find image 'wandb/local:latest' locally
latest: Pulling from wandb/local
7c3b88808835: Pulling fs layer
6ea0e81b1046: Pulling fs layer
2cdac9582559: Pulling fs layer
16363a734ec5: Pulling fs layer
f9533d5ac9e0: Pulling fs layer
4f4fb700ef54: Pulling fs layer
85d5002882ef: Pulling fs layer
73ae86c4c4ee: Pulling fs layer
c51a928e927c: Pulling fs layer
dc17bcfdb3d9: Pulling fs layer
72e24bc94d4e: Pulling fs layer
da382b696476: Pulling fs layer
ed78d5de3670: Pulling fs layer
6f6718ea686a: Pulling fs layer
6a624e7f742d: Pulling fs layer
5efa42035f29: Pulling fs layer
5686fae921aa: Pulling fs layer
7bbbf104adaf: Pulling fs layer
f9533d5ac9e0: Waiting
ef18e667b3b0: Pulling fs layer
11bdf6d18146: Pulling fs layer
4f4fb700ef54: Waiting
533b2f6e5771: Pulling fs layer
85d5002882ef: Waiting
73ae86c4c4ee: Waiting
72e24bc94d4e: Waiting
c51a928e927c: Waiting
da382b696476: Waiting
ed78d5de3670: Waiting
dc17bcfdb3d9: Waiting
6f6718ea686a: Waiting
ef18e667b3b0: Waiting
6a624e7f742d: Waiting
11bdf6d18146: Waiting
5efa42035f29: Waiting
533b2f6e5771: Waiting
5686fae921aa: Waiting
7bbbf104adaf: Waiting
16363a734ec5: Waiting
6ea0e81b1046: Download complete
16363a734ec5: Download complete
f9533d5ac9e0: Verifying Checksum
f9533d5ac9e0: Download complete
4f4fb700ef54: Verifying Checksum
4f4fb700ef54: Download complete
7c3b88808835: Verifying Checksum
7c3b88808835: Download complete
7c3b88808835: Pull complete
6ea0e81b1046: Pull complete
73ae86c4c4ee: Verifying Checksum
73ae86c4c4ee: Download complete
85d5002882ef: Verifying Checksum
85d5002882ef: Download complete
dc17bcfdb3d9: Verifying Checksum
dc17bcfdb3d9: Download complete
c51a928e927c: Verifying Checksum
c51a928e927c: Download complete
2cdac9582559: Verifying Checksum
2cdac9582559: Download complete
ed78d5de3670: Verifying Checksum
ed78d5de3670: Download complete
6f6718ea686a: Verifying Checksum
6f6718ea686a: Download complete
2cdac9582559: Pull complete
16363a734ec5: Pull complete
f9533d5ac9e0: Pull complete
4f4fb700ef54: Pull complete
85d5002882ef: Pull complete
73ae86c4c4ee: Pull complete
c51a928e927c: Pull complete
dc17bcfdb3d9: Pull complete
72e24bc94d4e: Verifying Checksum
72e24bc94d4e: Download complete
72e24bc94d4e: Pull complete
5efa42035f29: Verifying Checksum
5efa42035f29: Download complete
da382b696476: Verifying Checksum
da382b696476: Download complete
5686fae921aa: Verifying Checksum
5686fae921aa: Download complete
7bbbf104adaf: Download complete
da382b696476: Pull complete
ed78d5de3670: Pull complete
6f6718ea686a: Pull complete
11bdf6d18146: Verifying Checksum
11bdf6d18146: Download complete
533b2f6e5771: Verifying Checksum
533b2f6e5771: Download complete
6a624e7f742d: Verifying Checksum
6a624e7f742d: Download complete
6a624e7f742d: Pull complete
5efa42035f29: Pull complete
5686fae921aa: Pull complete
7bbbf104adaf: Pull complete
ef18e667b3b0: Verifying Checksum
ef18e667b3b0: Download complete
ef18e667b3b0: Pull complete
11bdf6d18146: Pull complete
533b2f6e5771: Pull complete
Digest: sha256:b00dca5a45f59fe26046ea38cff820b4d70730ba48139f5e5af737bc8d2981e3
Status: Downloaded newer image for wandb/local:latest
wandb: W&B server started at http://localhost:8080 🚀
wandb: You can stop the server by running `wandb server stop`
```

I cleared my browser history, went to `http://localhost:8080`, and get "Application Error. An application error occurred." I'm now using `wandb 0.13.2`.

**Comment by fdsig** [comment]
Hi @aclifton314 , 

Could you also try running:

```docker run --rm -d -e LOCAL_RESTORE=true  -p 8080:8080 --name wandb-local wandb/local```
to reset your instance of local 

If you don't have any data logged from running wandb server previously then you can try:

```docker rmi wandb/local:latest
docker volume rm wandb```

As you mentioned that you are newer to docker, I know that setting up wandb locally can be tricky and I wonder whether you have considered using our cloud offering which would also give you the latest features ahead of time. Look forward to hearing back and hope that the above helps resolve the issues that you are experiencing.

**Comment by aclifton314** [comment]
@fdsig I think that worked! I was able to sync a test run of my training session. Thank you for your patience and help!

I have one additional favor to ask, if you don't mind. Through my debugging of this and past issues I feel like there are several accounts on wandb and wandb local that I have created to try and resolve these issues. Would it be possible to completely wipe and delete any and all information associated with these accounts? I'm happy to provide them to you through your wandb email if you'd like. I'd like to start over fresh with wandb so as to avoid any future issues with accounts. If there are commands that I can run on my end, please let me know as well.

**Comment by fdsig** [comment]
Hi @aclifton314 , I am really glad to hear that this is fixed for you. In relation to accounts/data removal, you are correct you would need to email support@wandb.com for this. In case it is helpful/relevant you can switch between the two by specifying this in the W&B using:

CLI:
```
wandb login --cloud
```
or :
```
wandb login --host https://api.wandb.ai/
```

SDK:
```python
wandb.login(host='https://api.wandb.ai',force=True)
```

**Comment by aclifton314** [comment]
@fdsig Your help and cooperation is most appreciated. Thank you. I will close this issue out.
