### ISSUE TITLE
[Q] How to log custom config parameters?

### ISSUE THREAD

**Issue by JoseBarreiros-TRI** [wandb/wandb#4093]
I am working with the Wandb integration with SB3 and I would like to log additional config parameters that I use for my environment. 
When I open the table in my log, I can see the custom config parameters; however, they are hidden and cannot be shown. 

This is a minimal example:

 `
     config = {
        "policy_type": "MlpPolicy",
        "total_timesteps": 10e6,
        "env_name": "env-v0",
        "num_workers": 21,
        "env_time_limit": 7,
        "local_log_dir": "/home/path/path/",
        "observations_set": "state",
        "model_save_freq": 10000,
    }

    run = wandb.init(
        project="sb3_test",
        config=config,
        sync_tensorboard=True,  # auto-upload sb3's tensorboard metrics
        monitor_gym=True,  # auto-upload the videos of agents playing the game
        save_code=True,  # optional
    )
   
    env = ****
    model = PPO(policy_type, env, verbose=1, tensorboard_log=log_dir+f"runs/{run.id}")

    model.learn(
        total_timesteps=total_timesteps,
        callback=WandbCallback(
            gradient_save_freq=1000,
            model_save_path=log_dir+f"models/{run.id}",
            verbose=2,
            model_save_freq=config["model_save_freq"],
        ),
    )
    run.finish()
`
![wandb_bug](https://user-images.githubusercontent.com/103549637/184409375-5886aa0f-8434-4df8-ab15-545afc11072d.gif)

**Comment by MBakirWB** [comment]
Hi @JoseBarreiros-TRI, we will take a look at this for you. We will attempt to duplicate and get back to you. In the meantime, can you please provide a link to your workspace (We can access private projects)

**Comment by JoseBarreiros-TRI** [comment]
It is fixed, not sure if this is the result of a recent PR since the last time I tested. I can [see](https://wandb.ai/josebarreiros-tri/sb3_test/table?workspace=user-josebarreiros-tri) all the columns now. Thank you.

**Comment by MBakirWB** [comment]
Hi @JoseBarreiros-TRI , thank-you for letting us know it's been resolved on your end.
