### ISSUE TITLE
[Q] How to clear cache?

### ISSUE THREAD

**Issue by geyao1995** [wandb/wandb#4099]
I have run several experiments and logged the metric `A`, and then I delete the local cache files (./wandb) and the cloud runs. However, when I start the new experiments and log the new metric `B` instead of `A`, it seems that the history still exists. Two points evidence this:
1. The run name string is continued (not from xxx-xxx-**1** after I clear the local and online cache).
2. The `A` metric still exists in online view.

So I want to know how to clear cache and re-initialize the wandb correctly.

**Comment by geyao1995** [comment]
Do I have to delete the project online to achieve this cache clearing?

**Comment by MBakirWB** [comment]
Hi @geyao1995, once the local cache files and the runs from cloud are removed, then only data associated with those runs are removed. If several runs logged metric `A`, then unless you delete all runs that logged metric `A`, it will continue appearing in the online view.  Please verify that all runs that logged metric A were deleted from the project UI. 

Additionally, the incremental counter for randomly generated run names cannot be reset once a project is initialized. However, you can override it by assigning your own run names in [wandb init()](https://docs.wandb.ai/ref/python/init?q=wandb.init)

**Comment by geyao1995** [comment]
Thanks for your reply. That helps me!
