### ISSUE TITLE
[Q] MMDetWandbHook for Mask RCNN does not log image samples

### ISSUE THREAD

**Issue by sarmientoj24** [wandb/wandb#4121]
Using this code but it does not log images sample.

```
log_config = dict(
    interval=1,
    hooks=[
        # dict(type='TensorboardLoggerHook'),
        dict(type='TextLoggerHook'),
        dict(type='MMDetWandbHook',
            init_kwargs={
                'project': PROJECT,
                'entity': ENTITY,
                'name': EXP_NAME,
                'config': {
                    'lr': 0.02 / GPUS, 'batch_size': BATCH_SIZE
                },
                'tags': WANDB_TAGS
            },
            interval=1,
            log_checkpoint=False,
            log_checkpoint_metadata=True,
            num_eval_images=3,
            bbox_score_thr=0.1
        )
    ])
```

**Comment by MBakirWB** [comment]
Hi @sarmientoj24 , can you please expand on your meaning behind images are not logging? Have you verified if the .json file is being saved as an artifact similar to what is shown in this [gif](https://docs.wandb.ai/guides/integrations/mmdetection#visualize-dataset-and-model-prediction) from our docs.

**Comment by sarmientoj24** [comment]
@MBakirWB It does not produce that json file. just this
![image](https://user-images.githubusercontent.com/8830319/185293414-5b99c3a2-6531-4120-907f-a2531afd8ea8.png)

I meant it does not log something like this
![image](https://user-images.githubusercontent.com/8830319/185293711-03b4776c-517f-4199-bc7b-c2c23bceddf5.png)

**Comment by MBakirWB** [comment]
Hi @sarmientoj24 , reviewing your project [mmdtection-instance-segmentation](https://wandb.ai/james_adra/mmdetection-instance-segmentation), I verified the [val_data.json](https://wandb.ai/james_adra/mmdetection-instance-segmentation/artifacts/dataset/val/v0/files/val_data.table.json) file has been logged as an artifact. To bring this in to your workspace, from the workspace select `+ Add Panel -> Weave` and type in the following `project.artifact("val").versions.file("val_data.table.json")`. Please let me know if this is what is intended.

**Comment by MBakirWB** [comment]
Hi @sarmientoj24, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
