### ISSUE TITLE
[CLI]: Calling wandb.init() on slow storage triggers OSErrors

### ISSUE THREAD

**Issue by l-salewski** [wandb/wandb#4124]
### Describe the bug

Initializing Weights and Biases produces an `OSError` if the storage is too slow to create the file.

On a SSD the code below works just fine. But on a very slow network storage ([Quobyte](https://www.quobyte.com/)) it seems a thread initialized in `wandb.init()` that is looking for a file called `wandb-metadata.json` which is not available yet. I think it might be related to the fact that it takes some time for metadata to propagate to all nodes in Quobyte, but a) I am not sure about that and b) the `init()` call and the error happen on the same machine.

```python
import wandb
wandb.init()
```

This produces the following traceback:
```shell
Exception in thread Thread-16 (_thread_body):
Traceback (most recent call last):
  File "/mnt/miniconda3/envs/envname/lib/python3.10/site-packages/wandb/filesync/step_checksum.py", line 83, in _thread_body
    shutil.copy2(req.path, path)
  File "/mnt/miniconda3/envs/envname/lib/python3.10/shutil.py", line 435, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/mnt/miniconda3/envs/envname/lib/python3.10/shutil.py", line 378, in copystat
    _copyxattr(src, dst, follow_symlinks=follow)
  File "/mnt/miniconda3/envs/envname/lib/python3.10/shutil.py", line 320, in _copyxattr
OSError: [Errno 5] Input/output error: 'wandb/run-20220817_182503-1bv74ap5/files/wandb-metadata.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/miniconda3/envs/envname/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/mnt/miniconda3/envs/envname/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/miniconda3/envs/envname/lib/python3.10/site-packages/wandb/filesync/step_checksum.py", line 86, in _thread_body
    shutil.copy2(req.path, path)
  File "/mnt/miniconda3/envs/envname/lib/python3.10/shutil.py", line 435, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/mnt/miniconda3/envs/envname/lib/python3.10/shutil.py", line 378, in copystat
    _copyxattr(src, dst, follow_symlinks=follow)
  File "/mnt/miniconda3/envs/envname/lib/python3.10/shutil.py", line 320, in _copyxattr
    names = os.listxattr(src, follow_symlinks=follow_symlinks)
OSError: [Errno 5] Input/output error: '/wandb/run-20220817_182503-1bv74ap5/files/wandb-metadata.json'
```

As this is only an error in a thread the program continues normally (I suppose) and the file `wandb-metadata.json` eventually appears on the disk.
I also tried the `fork` setting but that did not make a difference.

### Environment

WandB version: 0.13.1

OS: Ubuntu 18.04.6 LTS

Python version: 3.10.5

**Comment by MBakirWB** [comment]
Hi @l-salewski , can you please provide the debug logs associated with this failed run. `debug.log` and `debug-interal.log` are located in the working directory of your project. We will review to take a closer look.

**Comment by l-salewski** [comment]
Hi @MBakirWB, sorry for not providing those in the first place. Hopefully they are helpful: [debug.log](https://github.com/wandb/wandb/files/9372035/debug.log) and [debug-internal.log](https://github.com/wandb/wandb/files/9372037/debug-internal.log).
.

**Comment by MBakirWB** [comment]
Hi @l-salewski , the debug logs did not capture the error. Can you please trigger the error and send the corresponding logs, thanks. Additionally [the code](https://github.com/wandb/wandb/blob/44270677725ee24fc0d8ef4151b4c9c99f1e69c5/wandb/filesync/step_checksum.py#L85) that threw an exception, `shutil.copy2(req.path, path)`, is attributed to [certain linux distributions](https://bugs.python.org/issue43743)  when copying large file, this could be the contributing factor here. The debug logs should shed further light on this.

**Comment by l-salewski** [comment]
Hi @MBakirWB, I ran the code again and after it sucessfully finished, I collected the logs ([debug.log](https://github.com/wandb/wandb/files/9431944/debug.log) and [debug-internal.log](https://github.com/wandb/wandb/files/9431945/debug-internal.log)). I am not sure whether they include the error, let me know if not.

Thanks for the pointer to the code and the bug report, I will get in touch with the admins of my local storage system.

In the meantime I have found another issue, which possibly might be related to this. The following code triggers W & B to hang forever after the finishing step if I point the storage path to said quobyte system (on my local SSD it works fine):
```python
wandb.init()
table = wandb.Table(columns=["foo", "bar"])
wandb.log({"examples": table})
wandb.finish()
```
The console shows this output:
```
wandb: Currently logged in as: lsalewski. Use `wandb login --relogin` to force relogin
wandb: wandb version 0.13.2 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.1
wandb: Run data is saved locally in /wandb/run-20220826_113209-18ba3044
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run splendid-morning-4
wandb: ⭐️ View project at https://wandb.ai/lsalewski/uncategorized
wandb: 🚀 View run at https://wandb.ai/lsalewski/uncategorized/runs/18ba3044
Exception in thread Thread-16 (_thread_body):
Traceback (most recent call last):
  File "/mnt/miniconda3/envs/envname/lib/python3.10/site-packages/wandb/filesync/step_checksum.py", line 83, in _thread_body
    shutil.copy2(req.path, path)
  File "/mnt/miniconda3/envs/envname/lib/python3.10/shutil.py", line 435, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/mnt/miniconda3/envs/envname/lib/python3.10/shutil.py", line 378, in copystat
    _copyxattr(src, dst, follow_symlinks=follow)
  File "/mnt/miniconda3/envs/envname/lib/python3.10/shutil.py", line 320, in _copyxattr
    names = os.listxattr(src, follow_symlinks=follow_symlinks)
OSError: [Errno 5] Input/output error: '/wandb/run-20220826_113209-18ba3044/files/wandb-metadata.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/miniconda3/envs/envname/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/mnt/miniconda3/envs/envname/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/miniconda3/envs/envname/lib/python3.10/site-packages/wandb/filesync/step_checksum.py", line 86, in _thread_body
    shutil.copy2(req.path, path)
  File "/mnt/miniconda3/envs/envname/lib/python3.10/shutil.py", line 435, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "/mnt/miniconda3/envs/envname/lib/python3.10/shutil.py", line 378, in copystat
    _copyxattr(src, dst, follow_symlinks=follow)
  File "/mnt/miniconda3/envs/envname/lib/python3.10/shutil.py", line 320, in _copyxattr
    names = os.listxattr(src, follow_symlinks=follow_symlinks)
OSError: [Errno 5] Input/output error: '/wandb/run-20220826_113209-18ba3044/files/wandb-metadata.json'
wandb: Waiting for W&B process to finish... (success).
```

For this run, here are the [debug.log](https://github.com/wandb/wandb/files/9432039/debug.log) and [debug-internal.log](https://github.com/wandb/wandb/files/9432040/debug-internal.log) files.

**Comment by MBakirWB** [comment]
Hi @l-salewski , thank-you for providing the debug logs. I was also able to successfully log the following without issue on my local disk. 

```
wandb.init()
table = wandb.Table(columns=["foo", "bar"])
wandb.log({"examples": table})
wandb.finish()
```
The debug logs didn't log anything specific to wandb. Additionally the `OSError: [Errno 5] Input/output error` indicates a problem at filesystem level, more specifically, the operating system cannot access a certain part of  a disk drive (or virtual disk drive). This points to a potential issue with write access to the quobyte system. I recommend starting with carefully inspecting the permissions of the folder/directory you’re working in.

**Comment by MBakirWB** [comment]
Hi @l-salewski , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by l-salewski** [comment]
Sorry, for not getting back to you (I was on vacation). I am trying to solve this problem with my local admins as it seems to be related to the specific file system we are using. If anything interesting comes from it, I would re-open/report here.

**Comment by MBakirWB** [comment]
Thank-you for the update @l-salewski. Yes please do re-open if you would like to continue the conversation.
