### ISSUE TITLE
[App]: Wandb local login problem

### ISSUE THREAD

**Issue by Leonezz** [wandb/wandb#4132]
### Current Behavior

I can't get the login page of wandb local after setting up, actually, no matter what page I want to go, it always redirects me to sign up page, question is it tells me I can't sign up...

### Expected Behavior

I should be able to login in with the default account.

### Steps To Reproduce

1. set up wandb local with docker
2. load the wandb page and wait till ready
3. the sign in page come in for about one second, and it refreash me to sign up page
4. change the url to /login or any other page, it always ends up /signup
5. that is all...

### Screenshots

trying here
![image](https://user-images.githubusercontent.com/33564074/185300878-53e722ad-44e7-4a9a-bdd8-dd9b3135deb3.png)
ends up here
![image](https://user-images.githubusercontent.com/33564074/185300451-355172a3-2c08-4777-85d8-594dbf272153.png)
and I can't do anything here
![image](https://user-images.githubusercontent.com/33564074/185300543-b2f16277-b08e-457e-b3f5-e29b08eeb33d.png)

### Environment

OS: Unubtu 20.04.4 LTS (GNU/Linux 5.0.4-88-generic x86_64)

Browsers: Microsoft Edge

Version: docker.io/wandb/local:latest(by 2022-08-18)

**Comment by MBakirWB** [comment]
Hi @Leonezz , perform the following:

docker exec -ti wandb-local bash
/usr/local/bin/local password <admin_email@domain.com>

Restart wandb server and now you should be prompted to login with the new password

**Comment by Leonezz** [comment]
Hi @MBakirWB , thanks for advice, I did exactly what you said but nothing changed.

**Comment by purplesword** [comment]
I faced exactly same issue.

**Comment by MBakirWB** [comment]
@Leonezz, can you ask you admin to send you another invite link for that local instance. It may be that in the instance you were accidentally removed .

@purplesword , are you part of an org, or is this a personal local instance?

**Comment by Leonezz** [comment]
@MBakirWB Sorry but I don't have a admin, I set the local instance just for personal use. It's that mean I have to be in some orgs to use wandb local?

**Comment by Leonezz** [comment]
@MBakirWB Sorry but I don't have an admin, I set the local instance just for personal use. It's that mean I have to be in some orgs to use wandb local?

**Comment by purplesword** [comment]
@MBakirWB I am running a personal local instance. 

https://github.com/wandb/local/issues/64#issuecomment-1106030481  I got mine running at end, following this hacky solution. @Leonezz

**Comment by Leonezz** [comment]
Thanks, will try! @purplesword

**Comment by MBakirWB** [comment]
Hi @Leonezz , we've identified an issue with local instances where Local will stop accepting the correct password for a given account. We are actively investigating and working on a fix. Have you been able to log back into your account?

**Comment by Leonezz** [comment]
> Hi @Leonezz , we've identified an issue with local instances where Local will stop accepting the correct password for a given account. We are actively investigating and working on a fix. Have you been able to log back into your account?

Sorry, I am recently working on other projects, I will let you know as soon as I get back to it.

**Comment by MBakirWB** [comment]
Hi @Leonezz , no worries at all. I will close the ticket out for now. When you are ready to continue the conversation, please respond here and we will reopen the ticket.

**Comment by AliJavanJ1** [comment]
I had an account for my wandb-local server and after changing server's network service I cant login to my account anymore and I get Invalid password error each time I try to login

**Comment by MBakirWB** [comment]
Hi @AliJavanJ1 , can you please expand on what you meant by changing server's network service? Additionally please note there is a fix in development to prevent this from happening that we hope to ship soon.

**Comment by AliJavanJ1** [comment]
After changing network service my servers IP has changed and I found out that in some cases my previous IP was hard coded and didn't change after my IP has changed for example in system admin, Frontend Host field was my previous IP and I couldn't change it before login
I solved my problem by redirection my previous IP to my new IP all around my server so when wandb sends request to previous IP it will end up to the recent one and I could login again

**Comment by MBakirWB** [comment]
@Leonezz @AliJavanJ1 @purplesword, following up on the login/password issues you were facing with Wandb Local. For our next release we are implementing a new method of saving passwords on the instance to prevent the behavior you are experiencing from occurring. The release will go out within next 1-2 weeks.

**Comment by MBakirWB** [comment]
Hi @Leonezz , @AliJavanJ1 , @purplesword , following up on this. Our latests wandb local version ([0.23.0](https://github.com/wandb/local/releases/tag/0.23.0)) now includes a new method of how usernames and passwords are stored. Please update your local version and keep me updated if you still run into issues with password resets.

**Comment by 1957787636** [comment]
https://github.com/wandb/local/issues/64#issue-1211152465，I solved this problem according to this method
