### ISSUE TITLE
[Q] Use Accelerate Launch with wandb sweeps

### ISSUE THREAD

**Issue by JeremyAlain** [wandb/wandb#4135]
Hi there, 
I am using Huggingface's accelerate library to train on multiple-gpu's etc. The way the library is setup is that one needs to call 
`accelerate launch train.py` where `train.py` is my training script. This works well in itself and I am also able to log everything to Wandb. 

The problem I have is when I try to use sweeps with accelerate. Concretely, my sweep.yaml has the following lines: 

```
 command:
  - python3
  - ${program}
  - ${args}
 ``` 
  
 On SLURM I then call `wandb agent --count 1 $sweep_id` which starts the agents with the command specified in the sweep.yaml file. Now when I want to use accelerate, what I tried to do is change the lines in the sweep.yaml to 

``` 
command:
  - accelerate launch
  - python3
  - ${program}
  - ${args} 
 ```
  
  I also tried 

```
 command:
  - "accelerate launch"
  - python3
  - ${program}
  - ${args} 
```
  
  However, this doesn't seem to be working. Every time I dot this I get the following error: 
  `FileNotFoundError: [Errno 2] No such file or directory: 'accelerate launch'`. 
  
  I was wondering whether anybody has an idea what is happening and how I can use accelerate launch with sweeps?
  
  Thanks so much

**Comment by ramit-wandb** [comment]
Hey Jeremy!

Could you try setting up your command as follows:

```
 command:
  - accelerate
  - launch
  - python3
  - ${program}
  - ${args} 
```

Please let me know if this works for you and if there is anything else I can do to assist.

Thanks,
Ramit

**Comment by JeremyAlain** [comment]
Thank you so much !! this resolved the issue :)
