### ISSUE TITLE
[CLI]: Wandb client forgets access key

### ISSUE THREAD

**Issue by franzigeiger** [wandb/wandb#4139]
### Describe the bug

The wandb client library asks for credentials ever time a new process is started. It seems to not remember the access key any more. The credentials are stored correctly under .netrc file. This effect appeared only recently, I am not sure what exactly triggered it, before this worked fine. 

Downgrading the wandb version has no effect, I tried version 0.12.2, 0.12.1, 0.13.0

### Environment

Operating system: 
MacOS Montgomery 12.4
Wandb version 0.13.0
Python version: 3.8.12

**Comment by MBakirWB** [comment]
HI @franzigeiger, there hasn't been other users reporting similar behavior. Can you clear/delete the ~/.netrc , then reset the credentials with `wandb login --relogin`. If that doesn't work, please expand with an example of how you are starting a new process. Thanks

**Comment by MBakirWB** [comment]
Hi @franzigeiger , thank-you for verifying this worked. I will mark this request resolved.
