### ISSUE TITLE
[CLI]: wandb hangs on wandb.init() when trying to start a run

### ISSUE THREAD

**Issue by scploeger** [wandb/wandb#4142]
### Describe the bug

When attempting to initialize a run, wandb hangs on wandb.init(). Leaving it for upwards of ten minutes, nothing happens. 
I have attempted to relogin, as well as creating a new api key and relogging in with that but nothing seems to fix it.
Note: I am the owner of the aicv-lab team and I own the wgan-gp project.

```python
CONFIG = dict(
    dataset = DATASET,
    subset = SUBSET,

    layers_crit = NUM_LAYERS_CRIT,
    kernels_crit = KERNEL_CRIT,
    stride_crit = STRIDE_CRIT,
    padding_crit = PAD_CRIT,
    features_crit = FEATURES_CRIT,

    layers_gen = NUM_LAYERS_GEN,
    kernels_gen = KERNEL_GEN,
    stride_gen = STRIDE_GEN,
    padding_gen = PAD_GEN,
    features_gen = FEATURES_GEN,

    batch_size = BATCH_SIZE,
    learning_rate_crit = LR_CRIT,
    learning_rate_gen = LR_GEN,
    crit_iterations = CRIT_ITERATIONS,
    gp_coefficient = LAMBDA
)

if RECORD_METRICS: # if false will not save checkpoint or log on W+B # gets stuck here
    run = wandb.init(project='wgan-gp', entity='aicv-lab', config=CONFIG)
```

When I check if I am logged in, I get this, so I am not sure why I can't initialize a run.
```
$ ~/Git/LSTM-Autoencoder$ wandb login
wandb: Currently logged in as: sploeger. Use `wandb login --relogin` to force relogin
```

### Environment

WandB version: 0.13.1

OS: Ubuntu 18.04

Python version: 3.7.11

**Comment by lesliewandb** [comment]
Hi @scploeger, thank you for writing in about this. Can you give me the debug logs found in your wandb run directory when you created this run? This will help me get more information as to why this is happening.

**Comment by lesliewandb** [comment]
Do you still need help here? If so, can you give me your debug logs please?

**Comment by lesliewandb** [comment]
Hi @scploeger , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by mahasch** [comment]
I have the same issue and there's nothing in the debug file, its empty. It was working before, I didn't change the code, but it just fails now.
