### ISSUE TITLE
[CLI]: wandb agent cannot be stopped by KeyboardInterrupt using subprocess.Popen

### ISSUE THREAD

**Issue by Hzzone** [wandb/wandb#4162]
### Describe the bug

 
wandb agent cannot be stopped by KeyboardInterrupt using subprocess.Popen

#### Code to reproduce this problem:

main_test.py
```python
import sys
import json
import subprocess
import os
import yaml

if __name__ == '__main__':
    configs = sys.argv[1]
    configs = json.loads(configs)
    cmd = f"python test.py {configs['batch_size']}"
    current_env = os.environ.copy()
    process = subprocess.Popen(cmd, env=current_env, shell=True)
    try:
        process.wait()
    except KeyboardInterrupt:
        process.kill()
    if process.returncode != 0:
        raise subprocess.CalledProcessError(returncode=process.returncode,
                                            cmd=cmd)
```
test.py
```python
if __name__ == '__main__':
    import time, sys
    batch_size = sys.argv[1]
    for i in range(100):
        print(i, batch_size)
        time.sleep(1)
```

#### Running without sweep:
```shell
> python main_test.py "{\"batch_size\": 64}"
0 64
1 64
^CTraceback (most recent call last):
  File "test.py", line 16, in <module>
    time.sleep(1)
KeyboardInterrupt
Traceback (most recent call last):
  File "main_test.py", line 18, in <module>
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command 'python test.py 64' died with <Signals.SIGINT: 2>.
```
The program can be stopped by KeyboardInterrupt.

#### Running with sweep

Config file:
```yml
command:
- ${env}
- ${interpreter}
- ${program}
- ${args_json}
method: grid
parameters:
  batch_size: 
    distribution: categorical
    values:
      - 64
      - 128
      - 256
      - 512
program: main_test.py
```

wandb agent logs:
```shell
wandb agent xxxx
wandb: Starting wandb agent 🕵️
2022-08-23 19:28:57,573 - wandb.wandb_agent - INFO - Running runs: []
2022-08-23 19:28:57,607 - wandb.wandb_agent - INFO - Agent received command: run
2022-08-23 19:28:57,608 - wandb.wandb_agent - INFO - Agent starting run with config:
	batch_size: 64
2022-08-23 19:28:57,608 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python main_test.py "{"batch_size": 64}"
0 64
1 64
2 64
3 64
^Cwandb: Ctrl-c pressed. Waiting for runs to end. Press ctrl-c again to terminate them.
4 64
^Cwandb: Terminating and syncing runs. Press ctrl-c to kill.
➜  5 64
6 64
7 64

➜  8 64
9 64
```
The code will be still running, which may be a little strange.

### Environment

WandB version: 0.12.6

OS: Ubuntu

Python version: 3.8.8

Versions of relevant libraries: No

**Comment by ramit-wandb** [comment]
Hi @Hzzone,

I'm not sure what you are exactly trying to do here. Would it not directly be possible to pass `test.py` into the config.yaml to run your sweep?

I might be missing something here, so please let me know so that I can help you out better here.

Thanks,
Ramit

**Comment by Hzzone** [comment]
@ramit-wandb 
Thanks for your quick reply. You are right for that directly passing `test.py` into config.yaml can enable `KeyboardInterrupt` to work again. However, I have to do this because I am using pytorch ddp for distributed training. In detail, we must pass the `master_port` and `nproc_per_node` into `torchrun` or `torch.distributed.launch`. If there are several wandb agents in a single machine, we need different `master_ports for each wandb agent. Therefore, there is no more convenient  way as now for sweep to launch a distributed training. Anyway, I appreciate your helpful comments, and I will try better solutions later.
