### ISSUE TITLE
Problems with wandb frontend when I report a line plot[App]: 

### ISSUE THREAD

**Issue by AlbertoPresta** [wandb/wandb#4176]
### Current Behavior

Until yesterday my plots were right, now the number of points for each experiment has changed for no reason, resulting in a meaningless plot. 

I put a screenshot so you can understand the problem. I am sure that there is no bug in my code because until yesterday everything was fine

### Screenshots

<img width="843" alt="Schermata 2022-08-25 alle 08 55 52" src="https://user-images.githubusercontent.com/43781044/186597855-8a15b612-5d7f-4b4c-8b44-ab245f5879bc.png">

### Environment

OS:

Browsers:

Version:

**Comment by fdsig** [comment]
Hey @AlbertoPresta,

Thanks so much for reporting this & sincere apologies for the inconvenience. We have looked at this as a matter of urgency and should have now fixed the underlying issue.

Please let us know if issues showing plots in the UI persist.

Best wishes W&B team,

**Comment by fdsig** [comment]
Hey @AlbertoPresta,

I wanted to follow up with you regarding plots loading in the UI to check that this has now been resolved on your end.  Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by AlbertoPresta** [comment]
Hey, 
Sorry if I answer after some days. 
Yes everything is working perfectly now, thanks!
