### ISSUE TITLE
[Feature]: Display number of runs in a sweep grid search

### ISSUE THREAD

**Issue by zimmer-m** [wandb/wandb#4179]
### Description

I perform quite large grid searches and have to 'manually' compute the total number of runs that such a sweep would result in.

### Suggested Solution

It would be nice to display somewhere the total number of runs that a sweep will contain.

**Comment by nate-wandb** [comment]
Hi @zimmer-m,
Thank you for the feature request. I imagine something on the sweeps tab where it says completed 10/120 runs or something similar would work for you correct? 
Thank you,
Nate

**Comment by zimmer-m** [comment]
@nate-wandb Yes that is exactly what I am looking for! That would be great to have. I just need to know before starting the sweep how many runs it will produce, e.g. a 0/120 before even starting it would be great.

**Comment by nate-wandb** [comment]
@zimmer-m perfect! I can put that in for you. Since the sweep shows up in the UI once you run `wandb sweep sweep.yaml` you should be able to see the number of runs it will produce before assigning any agents to the sweep.

**Comment by zimmer-m** [comment]
@nate-wandb Just saw that it is already online! Thanks a lot, that was quick!

**Comment by zimmer-m** [comment]
This seems to not work in certain projects, in some this column does simply not exist in the sweep overview. 
<img width="477" alt="grafik" src="https://github.com/wandb/wandb/assets/66726489/6a3f0230-34b7-4b92-a2b0-f6ca0ee6f058">
