### ISSUE TITLE
[Q] Is there a way to automatically do a multi-line plot without using wandb.plot.line_series()?

### ISSUE THREAD

**Issue by cwfparsonson** [wandb/wandb#4182]
Hi,

I have a `gym` environment made up of multiple 'teams' where I record `wandb.log(results)` each time I call `env.step()`. Amongst other step metrics, I am logging data of the form:

```python
results = {
                'team_1':
                    'metric_1': 10,
                'team_2':
                    'metric_1': 15
            }
wandb.log(results)
```

This plots `metric_1` for each team on a separate graph. To plot `metric_1` on the same graph for each team, I have to manually edit the graph. Ideally `metric_1` for each team would be automatically plotted on the same graph.

I know that `wandb.plot.line_series()` achieves this functionality, however each time I call `wandb.log()` I only have `int` or `float` values rather than a `list` because I make the `wandb.log()` call after each `env.step()` call rather than at the end of the environment episode. Unfortunately `wandb.plot.line_series()` seems to require that only one call be made to it, and each time it is called it overwrites previously logged `wandb.plot.line_series()` data (unlike `wandb.log()`, which appends to previously logged data).

Is there a way to do the equivalent of `wandb.plot.line_series()` but for `int` or `float` value logging so that I can automatically plot multi-line plots?

**Comment by MBakirWB** [comment]
Hi @cwfparsonson , you are correct that `plot.line_series()` would be the best approach here. The alternative that could work for your use case is to assign a `group` tag to the individual runs and then clear the group tag from the UI. See attached video. Please let me know if this helps. 

https://user-images.githubusercontent.com/104453360/186986127-4a78d55c-7cb7-4dd6-a7dc-9f3ac47337d8.mp4

**Comment by cwfparsonson** [comment]
> Hi @cwfparsonson , you are correct that `plot.line_series()` would be the best approach here. The alternative that could work for your use case is to assign a `group` tag to the individual runs and then clear the group tag from the UI. See attached video. Please let me know if this helps.
> 
>  GroupedRuns.mp4

Thanks for the reply @MBakirWB. I am not sure if that group solution will work in my case, since the multiple lines are for different agents running inside the same experiment (i.e. it's a multi-agent experiment), so the data is not generated with separate `wandb` runs but rather from one single simulation.

I think I have thought of a slightly hacky solution, which I'll share in case it's useful for anyone else (or if someone has a better solution). Before I run any experiments, I instantiate a `wandb.Table()` object:

```python
log['results_by_team'] = wandb.Table(columns=['team_id', 'episode', 'metric_1', 'metric_2'])
```

At the end of each step, I add a single row to the `wandb.Table` for each team:

```python
for team_id in ['team_1', 'team_2']:
    metric_1, metric_2 = get_team_metrics(team_id)
    row = [team_id, episode, metric_1, metric_2]
    log['results_by_team'].add_row(*row)
```

Then, at the end of the episode, I use `wand.plot.line_series()` to overwrite the metric plots with the most up-to-date `wandb.Table`:

```python
import pandas as pd

# convert table to pandas dataframe
table_df = {}
for col in log['results_by_team'].columns:
    table_df[col] = log['results_by_team'].get_columns(col)
table_df = pd.DataFrame(table_df)

# plot line series
xs = list(table_df.groupby('team_id')['episode'].apply(list).to_dict().values())
for metric in ['metric_1', 'metric_2']:
    team_id_to_metric = table_df.groupby('team_id')[metric].apply(list).to_dict()
    log[f'results_by_team_{metric}'] = wandb.plot.line_series(xs=xs, ys=list(team_id_to_metric.values()), keys=list(team_id_to_metric.keys()), title=metric, xname='Episode')
```

This solution effectively does what I want to do, which is to update a `wandb` multi-line plot on a per-step basis.

One thing I would like to do is learn how to use the `wandb.Table.plot_table()` method with the `vega` commands so I can e.g. add a y-axis to the `line_series` plot, but I couldn't find any resources showing how to use `vega` with weights and biases to do this for multi-line plots. If anyone has any pointers to help me learn how to use `vega` with multi-line plots and `wandb.Table.plot_table()`, that would be very helpful!

**Comment by MBakirWB** [comment]
Hi @cwfparsonson , thank-you for the update and letting me know you produced an approach. 

In general a vega spec can be used with wandb plot_table by first saving a [custom chart preset](https://docs.wandb.ai/ref/app/features/custom-charts#saving-chart-presets) in your project and pass that spec to plot_table. If I can track down a good example for your specific use case I will respond here, I found this [overview report](https://wandb.ai/wandb/plots/reports/Custom-Multi-Line-Plots--VmlldzozOTMwMjU) on vega custom line charts with use with wandb. There are links at the bottom for additional resource.

**Comment by MBakirWB** [comment]
Hi @cwfparsonson, I'll be moving forward with closing this ticket. If you would like to re-open the conversation, please let us know!
