### ISSUE TITLE
[Docs] Minor issue in the documentation on Sweeps in Jupyter

### ISSUE THREAD

**Issue by avm19** [wandb/wandb#4187]
[Running Sweeps in Jupyter](https://docs.wandb.ai/guides/sweeps/python-api) refers to [configuration#structure-of-the-sweep-configuration](https://docs.wandb.ai/guides/sweeps/configuration#structure-of-the-sweep-configuration):
> We store all of this information in a dictionary (or dictionary-like) Python data structure, the `sweep_config`. For details, see this guide.

The latter specifies `program` as a required parameter, which is not the case.

**Comment by MBakirWB** [comment]
Hi @avm19 , thank-you for writing in. I do recognize how that could lead to some confusion for some users, but there are several methods of initiating/running sweeps and defining the key `program` is required in the `.YAML` file if running a sweep from the command line agent.
