### ISSUE TITLE
[Q] Projects with 0 runs to upload artifacts

### ISSUE THREAD

**Issue by miguelvalente** [wandb/wandb#4190]
Is it possible to have a project with no runs solely to be used as place to visualise/upload/manipulate(through filters) artifacts.

**Comment by ramit-wandb** [comment]
Hi @miguelvalente,

Yes! Artifacts reside at the project level, so you can absolutely push them without having to create a run to do so. We provide a CLI command to upload artifacts directly, you can find documentation about that here: https://docs.wandb.ai/ref/cli/wandb-artifact/wandb-artifact-put.

Let me know if I can assist with anything else.

**Comment by ramit-wandb** [comment]
Hi @miguelvalente, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
​
