### ISSUE TITLE
[Q] Visualising Bayes sweep search params

### ISSUE THREAD

**Issue by cwfparsonson** [wandb/wandb#4197]
Hi,

Is it possible to plot graphs of the various stats (`expected_improvement`, `predicted_value`, `success_probability`, etc.) under the hood when using the `bayes` method to do an hparam sweep with W&B? I can see these values being printed in the Logs tab of the UI, but I am not sure how to visualise them. It would be nice to be able to visualise the latest Bayes graphs for each hparam being tuned and their possible values (for example, a plot similar to the pred var vs. pred mean vs. truth vs. evaluations sketch in the tutorial: https://wandb.ai/site/articles/bayesian-hyperparameter-optimization-a-primer)

**Comment by MBakirWB** [comment]
Hi @cwfparsonson , we currently don't expose gaussian process metrics for bayes search. There was a feature request out for this but the engineering team decided not to move forward with implementing it. If there is anything else I could help you with, please let me know.
