### ISSUE TITLE
[Q] How can I get the best F1 score via run.summary?

### ISSUE THREAD

**Issue by venti07** [wandb/wandb#4203]
How do I modify this code to get the run with the best F1 score?

```
api = wandb.Api()
runs = api.runs("xxxxx/xxxxxx")

summary_list, config_list, name_list = [], [], []
for run in runs:
  summary_list.append(run.summary._json_dict)
  config_list.append(
      {k: v for k,v in run.config.items()
        if not k.startswith('_')})
  name_list.append(run.name)

runs_df = pd.DataFrame({
    "name": name_list,
    "summary": summary_list})
```

**Comment by lesliewandb** [comment]
Hi @venti07, do you have a wandb question? I can help you if you are running into an error regarding our product.

**Comment by venti07** [comment]
Hi @lesliewandb,

Yes I have a question. In the documentation it says the following about attribute "summary": 

"(Summary) Single values set for each wandb.log() key. By default, summary is set to the last value logged. You can manually set summary to the best value, like max accuracy, instead of the final value."

https://docs.wandb.ai/guides/track/public-api-guide 

And my question is how can I make run.summary give me the run with the highest accuracy or for example highest f1?

Thank you for your feedback!

**Comment by lesliewandb** [comment]
Yes there is a way :) You can use [`define_metric`](https://docs.wandb.ai/ref/python/run#define_metric) and set the goal to maximize. Let me know if you need any further help here :)

**Comment by lesliewandb** [comment]
HI @venti07, do you still need help here?

**Comment by lesliewandb** [comment]
Since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
