### ISSUE TITLE
[App]: Invalid tag. must be between 1 and 64 characters (<Response [400]>)

### ISSUE THREAD

**Issue by Msameim181** [wandb/wandb#4208]
### Current Behavior

Hi, I'm using WandB as usual to log my program, I had to Run it on a Server which is not suitable for online logging. So I am Using `Offline` mode to handle the situation.
I'm using tags and I made a mistake. I passed the name of the run to tags and this time, the name was too long.
I have an Error, How to handle it, I really need this data.

```
wandb: ERROR Error while calling W&B API: invalid tag '20220826_011322_MobileNetV3_Attention_Pre_male_MSE_G32_M_Age_G0_Atten'. must be between 1 and 64 characters (<Response [400]>)
```

### Expected Behavior

Solution: Sync and if anything was wrong warn it but save the others.

### Steps To Reproduce

Use a Big Tag

### Screenshots

![image](https://user-images.githubusercontent.com/25700939/187825379-e2008fbe-0f55-4674-8387-942e6ee85298.png)

### Environment

OS: Windows 10

Browsers: Brave

Version:

**Comment by Msameim181** [comment]
Or Can I edit the Tag before syncing? How Can I read and Edit after the run is finished?

**Comment by thanos-wandb** [comment]
Hey @Msameim181 I wanted to follow up on this issue, does it still remain for you? can you please provide more information to help us replicate this issue and debug it. Thanks!

**Comment by thanos-wandb** [comment]
Hi @Msameim181 since we haven't heard back from you, I will go ahead and close this ticket for now. If you still experience this issue or have further questions please feel free to re-open it by posting here and we will be happy to keep investigating!
