### ISSUE TITLE
[Q] Docker args are not passed to a local container

### ISSUE THREAD

**Issue by SonyPony** [wandb/wandb#4211]
Where are not the docker arguments defined in _launch_ passed to a local container?

Specifically in `wandb/sdk/launch/agent/agent.py`:
```
def run_job(self, job: Dict[str, Any]) -> None:
    ...
    backend_config: Dict[str, Any] = {
            PROJECT_DOCKER_ARGS: {},
            PROJECT_SYNCHRONOUS: False,  # agent always runs async
        }
    ...
```

If I change the code according to the following snippet, it works.
```
def run_job(self, job: Dict[str, Any]) -> None:
    ...
    backend_config: Dict[str, Any] = {
            PROJECT_DOCKER_ARGS: launch_spec["docker"].get("args"),
            PROJECT_SYNCHRONOUS: False,  # agent always runs async
        }
    ...
```

**Comment by MBakirWB** [comment]
Hi @SonyPony , thank-you for reporting this. The Launch team confirmed this is a bug. I will report back once it's been fixed.

**Comment by MBakirWB** [comment]
Hi @SonyPony , the Launch team implemented a fix for how docker arguments are passed to launch containers. This will be reflected in our next release. Thanks again for reporting.

**Comment by MBakirWB** [comment]
Hi @SonyPony , a [fix ](https://github.com/wandb/wandb/pull/4215) for this has been merged into production. Thanks again for bringing the bug to our attention.
