### ISSUE TITLE
shape description in Object3D's documentation is not correct

### ISSUE THREAD

**Issue by hzaskywalker** [wandb/wandb#4220]
https://github.com/wandb/wandb/blob/0a3b035d0fb206570660275503c8b72f8d7b4399/wandb/sdk/data_types/object_3d.py#L22-L208

The description of the shape of input numpy arrays is quite confusing and not correct.

**Comment by MBakirWB** [comment]
Hi @hzaskywalker , thank-you for writing in. Can you please expand on the specific description you are referring to and what you expect it to read instead? I will mark your comments down as part of the review.
