### ISSUE TITLE
[Q] Two level logs in a single metric?

### ISSUE THREAD

**Issue by JiarunLiu** [wandb/wandb#4222]
Hi, can I logging a single metric with two levels? For instance, logging batch-level accuracy `acc1` and epoch-level accuracy `acc1_inepoch` (an weighted averge version of batch-level accuracy in each epoch, weighted by actrual batch_size) in a unified metric `acc1`, so I can switch it in dashboard. 

I'm trying to do this by the following code:
```python
tmp_log_dict = {}
# logging epoch level metric
def log_epoch(**kwargs):
    tmp_log_dict.update(**kwargs)

# commit epoch level metric to wandb
# call it in the end of each epoch
def commit_epoch_log():
    wandb.log(tmp_log_dict)
    tmp_log_dict.clear()

def log_step(self, **kwargs):
    wandb.log(dict(**kwargs), step=global_step)

global_step = 0
acc_avg = AvergeMeter()  
for epoch in range(total_epochs):
    for batch in dataloader:
        # forward pass
        ...

        acc = accuracy(outputs, targets)  # num_correct / len(targets)
        acc_avg.update(acc, len(targets)  # record moving average accuracy
        global_step += 1
        log_step(epoch=epoch, acc=acc)


    # logging epoch level metric
    log_epoch(acc_inepoch=acc_avg.avg, val_acc=val_acc)
    commit_epoch_log()

```

But the result seems mismatched when I switch axis to epoch in dashboard:
<img width="932" alt="image" src="https://user-images.githubusercontent.com/42335666/188272003-912cfbe9-5cab-471e-b703-0f71040cd2c2.png">

**Comment by JiarunLiu** [comment]
邮件已收到！

**Comment by MBakirWB** [comment]
Hi @JiarunLiu, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by JiarunLiu** [comment]
Thanks for your help.  I will close this issue.
