### ISSUE TITLE
[Q] How to turn off debug-internal.log?

### ISSUE THREAD

**Issue by YouJiacheng** [wandb/wandb#4223]
It seems to cause performance issues since I use NFS which may be backed by blob storage and append will trigger full rewrite.

**Comment by YouJiacheng** [comment]
I figure out a workaround as the following:
```bash
# CWD is the parent of the file that executes wandb.init
mkdir wandb # can be skipped if there is one
ln -s /dev/null wandb/null
```
```python
from pathlib import Path
wandb.init(
    settings=wandb.Settings(
        log_internal=str(Path(__file__).parent / 'wandb' / 'null'),
    )
)
```
We cannot use `/dev/null` directly, otherwise `wandb` will make dir `/dev` and fail.

**Comment by thanos-wandb** [comment]
Hi @YouJiacheng thank you for this question and the provided workaround. May I ask what performance issues is the `debug-internal.log` file is causing and if the above would solve your issue? You could also do something similar for `debug.log` file by setting the `log_user` argument.

**Comment by thanos-wandb** [comment]
Hi @YouJiacheng just following up on this issue, has this been resolved for you and would there be anything else we could help with? thanks!
