### ISSUE TITLE
[App]: Parallel coordinates average metrics in the Group

### ISSUE THREAD

**Issue by dejangrubisic** [wandb/wandb#4227]
### Current Behavior

I couldn't find a way to visualize runs in the group separatelly. I am running ray.tune.run with WandbLoggerCallback, setting the group number and for each run, I send extra parameters with wandb.Api() and this works fine. The problem comes when I am trying to visualize all runs in parallel coordinates, that averages all metrics across runs, rather than showing each of them individually.

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/40608743/188479740-309ae89f-38c4-4fdb-a9c8-2a771d8eb16e.png">

I was able to show the metric final_performance of each run separately only if I specify some parameters in the configuration that two runs differ. The default behavior was to average these (options are mean, median, min, max).

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/40608743/188477993-1e2549b3-4174-42c3-883a-7bc1107cc5c5.png">

### Expected Behavior

I would expect that there is a way to show each run from the same group separately in parallel coordinates, or in the plot as default.

### Steps To Reproduce

Unfortunately, I cannot provide a reproducer.Unfortunately

### Environment

OS: MacOS

Browsers: Firefox, Chrome

Version: 0.13.1

**Comment by ramit-wandb** [comment]
Hi @dejangrubisic !

Could you try filtering by the `Group` parameter instead of Grouping over them? I think that should result in what you are looking for.

Thanks,
Ramit

**Comment by dejangrubisic** [comment]
If I group over Group, it creates Group:PPO, which are all runs together. I was able though to send additional parameter group_id through wandb_run.summary, and group over it, and it works ok that way.
I would say that this is just a workaround, and it would be more convenient for users to have default independent grouping.

**Comment by lukas** [comment]
Another way is to turn off the grouping in panels completely: 
<img width="323" alt="image" src="https://user-images.githubusercontent.com/29/188954758-bbe0d4d4-88a7-47bf-9b02-9e8a91c80dbb.png">

Does that work for you?

**Comment by dejangrubisic** [comment]
Unfortunately that only shows mean +- std and not all runs from the group separatelly

**Comment by ramit-wandb** [comment]
Hey @dejangrubisic,

Could you tell me a little bit more about why the filter by "Group" does not work for you? Seems to do the job for me. I would love to understand some more to help you better.

<img width="1220" alt="Screen Shot 2022-09-22 at 11 41 18 AM" src="https://user-images.githubusercontent.com/93002515/191829707-f3fba458-8100-4f0a-83b5-44d940f23848.png">
<img width="1227" alt="Screen Shot 2022-09-22 at 11 45 18 AM" src="https://user-images.githubusercontent.com/93002515/191829730-d5522ef6-fc52-438e-ac5b-ae8748401336.png">

Thanks,
Ramit

**Comment by dejangrubisic** [comment]
Your example is exactly what I would like to see, but what I can see are averaged values of all runs for parallel coordinates. This surely can be useful sometimes, but it would be nice to see separate lines like in your example, so we can identify the best run.
