### ISSUE TITLE
[Q] How to avoid data averaging when logging to metric across multiple runs?

### ISSUE THREAD

**Issue by a-rich** [wandb/wandb#4230]
Hello, I'm trying to log data points for the same metric across multiple runs (`wandb.init` is called repeatedly in between each data point) and I'm unsure how to avoid the behavior seen in the attached screenshot...

Instead of getting a line chart with multiple points, I'm getting a single data point with associated statistics. In the attached e.g., the 1st data point was generated at step 1,470 and the 2nd at step 2,940...rather than seeing two points, I'm instead getting a single point that's the average and appears at step 2,205. 

![image](https://user-images.githubusercontent.com/4131505/188540676-d5a79044-a695-4a51-a3c1-94ab71f07543.png)

My hunch is that using the [resume run](https://docs.wandb.ai/guides/track/advanced/resuming) feature may address my problem, but even testing out this hunch is proving to be cumbersome given the constraints of the system I'm working with...

Before I invest more time in my hypothesized solution, could someone confirm that the behavior I'm seeing is, indeed, the result of logging data to the same metric across separate runs without using the resume feature?

If this is the case, can you confirm or deny my conception of how to use resume?

Initial run:
1. `run = wandb.init()`
2. `wandb_id = run.id`
3. cache `wandb_id` for successive runs

Successive run:
1. retrieve `wandb_id` from cache
2. `wandb.init(id=wandb_id, resume="must")`

Is it also acceptable / preferable to replace `1.` and `2.` of the initial run with:
1. `wandb_id = wandb.util.generate_id()`
2. `wandb.init(id=wandb_id)`

**Comment by thanos-wandb** [comment]
hey @a-rich thank you for reporting this! Do you have a code snippet on how you log these data? and is it possible to share a workspace of this chart? there might be a way to change how data are plotted using Weave. Do you want to plot something like the mean loss (y-axis) vs epochs (x-axis) for each experiment, so that would be n experiments line plots?

**Comment by a-rich** [comment]
Hi @thanos-wandb!

I'm not able to share the workspace where this is actually happening, but I made a personal account and can share a [workspace from there](https://wandb.ai/a-rich/alrichards?workspace=user-a-rich) that demonstrates the issue.

![demo-workspace](https://user-images.githubusercontent.com/4131505/188932362-3c698bae-9698-4d59-b08f-78766ad7b55f.png)

Here's a snippet to reproduce the group in the linked demo workspace seen in the attached screenshot:
```
import wandb

# wandb run associated with evaluation after first N epochs of training.
wandb.init(project="alrichards", name="test-run-1/job-1", group="test-run-1")
wandb.log({"mean_evaluate_loss_epoch": 20}, step=1)
wandb.finish()

# wandb run associated with evaluation after second N epochs of training.
wandb.init(project="alrichards", name="test-run-1/job-2", group="test-run-1")
wandb.log({"mean_evaluate_loss_epoch": 10}, step=5)
wandb.finish()
```

**Comment by a-rich** [comment]
Ok, I think my original question is now answered. Using the `id` and `resume` fields yield the desired effect. Now I can invest time making changes to support this as a feature.

```
import wandb

# wandb run associated with evaluation after first N epochs of training.
wandb_id = wandb.util.generate_id()
wandb.init(id=wandb_id, project="alrichards", name="test-run-3/job-1", group="test-run-3")
wandb.log({"mean_evaluate_loss_epoch": 20}, step=1)
wandb.finish()

# wandb run associated with evaluation after second N epochs of training.
wandb.init(id=wandb_id, resume="must", project="alrichards", name="test-run-3/job-2", group="test-run-3")
wandb.log({"mean_evaluate_loss_epoch": 10}, step=5)
wandb.finish()

```

**Comment by lukas** [comment]
Hi! Using id and resume definitely works for your use case.

The reason you are seeing a single datapoint is the line chart averages points over runs by default when they are grouped. If you want to turn this off you can do so in the UI in the upper right.

<img width="320" alt="image" src="https://user-images.githubusercontent.com/29/188953337-37628fcc-b403-401a-8584-e453b7f40738.png">

**Comment by thanos-wandb** [comment]
Hi @a-rich thank you for confirming this. I will close the ticket for now, but feel free to re-open it by posting here if you have any further questions and we will be happy to keep investigating!
