### ISSUE TITLE
Wandb fails when run on a server

### ISSUE THREAD

**Issue by CatarauCorina** [wandb/wandb#4235]
Hi, I've been using Wandb locally for awhile now using pytorch-lighthing, and it has all worked well. I have just moved my code to a cluster, and now I'm having an issue with the url that wandb is trying to access:
Instead of calling : https://api.wandb.ai/graphql  it's trying to call {proxy_url}/graphql

  File "versions/slot_att_local/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File ".pyenv/versions/slot_att_local/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/.pyenv/versions/slot_att_local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://hpc-proxy00.city.ac.uk:3128/graphql

Do you have any ideas what I'm doing wrong or what I should change ?

**Comment by nate-wandb** [comment]
Hi @CatarauCorina, do you access your local instance at http://hpc-proxy00.city.ac.uk:3128 ? If this is the URL where you are hosting your instance then this should be the endpoint where graphQL queries should be pointed. Also, I noticed this URL is http and not https. Is it possible that you have a load balancer or anything in front of the instance that won't accept http traffic?

Thank you,
Nate

**Comment by nate-wandb** [comment]
@CatarauCorina, if you are trying to log runs to wandb.ai, you may need to re-login. I would try `wandb login --cloud --relogin` which should allow you to log to wandb.ai rather than the proxy address. If that doesn't work can you check what your env variables are set to and make sure your `WANDB_BASE_URL` is not set?

**Comment by kptkin** [comment]
@CatarauCorina Since we didn't hear from you, we will be closing this issue. Feel free to re-open if you still experiencing this issue
