### ISSUE TITLE
[Q] Download Table logged as Summary

### ISSUE THREAD

**Issue by subho406** [wandb/wandb#4236]
I'm logging Table as a summary using wandb which I am able to visualise in the web interface. However, I'm trying to download the summary table for a specific run using `run.summary` but I'm not sure how to do that. 

Printing `run.summary` in Python returns:
```
{
	'_wandb': {
		'runtime': 934
	},
	'_runtime': 934,
	'_timestamp': 1662160511,
	'result_table': {
		'sha256': '766bb7f11158aee402a6bc89e0b9edbb11ce3a700eda181fdba03d083bd98711',
		'artifact_path': 'wandb-client-artifact://zoxq5uqiochj19e7u0jdewa8odnj7lxdopox96a1cndru02pknz0e4lym8gotgkbfteijggcf0ygu924ov50lr3yx9mzgmi44pem8230730o0s2546m8yx2q953amz0q:latest/result_table.table.json',
		'_latest_artifact_path': 'wandb-client-artifact://zoxq5uqiochj19e7u0jdewa8odnj7lxdopox96a1cndru02pknz0e4lym8gotgkbfteijggcf0ygu924ov50lr3yx9mzgmi44pem8230730o0s2546m8yx2q953amz0q:latest/result_table.table.json',
		'path': 'media/table/result_table_1000000_766bb7f11158aee402a6.table.json',
		'size': 3486,
		'_type': 'table-file',
		'ncols': 3,
		'nrows': 100
	},
	'loss': 0.25604966997206213,
	'_step': 1000000
}
```

Is there a way I can load the summary table as a DataFrame in Python?

**Comment by thanos-wandb** [comment]
Hi @subho406 thank you for writing in! Could you please post a link to a Workspace or a screenshot of the summary table? are you interested in doing so only by using the Python API? or would it work for you if you could export a .csv file from the UI?

**Comment by thanos-wandb** [comment]
Hey @subho406 I wanted to follow up with you regarding this issue, could you provide some more information asked above to help debug this? Please let me know if I can be of further assistance or if your issue has been resolved.

**Comment by thanos-wandb** [comment]
Hi @subho406 great to hear you resolved this issue and thanks so much for posting here the solution! I am closing the ticket for now, but please feel free to re-open it if you have any further questions or issues related to this.
