### ISSUE TITLE
[Q] Is there any `direct_url` to existing artifact files?

### ISSUE THREAD

**Issue by alvarobartt** [wandb/wandb#4238]
As of the File System, we can easily retrieve the `direct_url` of a file uploaded to a `wandb` run, pointing to the Google Storage URL as follows:

```python
import wandb
api = wandb.Api()
file = api.run(f"{entity}/{project}/{run_id}").file(name=file_path)
file.direct_url
```

Is there any way to actually retrieve the URL to the Google Storage for the Artifact Store files? If not, can it be implemented?

```python
import wandb
api = wandb.Api()
artifact = api.artifact(name=f"{entity}/{project}/{artifact_name}:{artifact_version}", type=artifact_type)
file = artifact.get_path(name=file_path)
file.direct_url
```

Thanks in advance! :D

**Comment by thanos-wandb** [comment]
Hi @alvarobartt thank you for writing in! May I ask what's the use case for retrieving the URL? Also do you mean a URL to W&B Google Cloud Storage bucket? or are these stored externally on your GCP bucket? in the latter case you could track the artifacts by reference and download them, using the `add_reference` method as is demonstrated in [this Report](https://wandb.ai/stacey/artifacts/reports/Tracking-Artifacts-by-Reference--Vmlldzo1NDMwOTE) and the guides included in it. Would this work for you?

**Comment by alvarobartt** [comment]
Hi @thanos-wandb, thank you for answering! So it's actually to share the artifact file URL from a private W&B Run, in order to easily share the artifacts with others without making it public, as for the files we can easily generate a temporary URL pointing to W&B's Google Cloud Storage bucket.

**Comment by alvarobartt** [comment]
I'll drop an example here so as to follow this issue up!

e.g. you want to retrieve the download URL of the following artifact https://wandb.ai/wandb/yolo-chess/artifacts/model/run_1dnrszzr_model/v6/files/last.pt. So if you copy the link in the download button at https://wandb.ai/wandb/yolo-chess/artifacts/model/run_1dnrszzr_model/v6/files, you'll end up having a GCP URL.

![image](https://user-images.githubusercontent.com/36760800/189885459-40e5c58e-2ae6-4e68-8cf2-17784314cf87.png)

So that the URL is https://api.wandb.ai/artifactsV2/gcp-us/wandb/QXJ0aWZhY3Q6MTQwMzQ3ODM2/e1f9056a7a95a55f5b285535d9bfe2f0?_gl=1*12jg7m3*_ga*NTQzNTA2MzMxLjE2NTUxMDg0MTE.*_ga_JH1SJHJQXJ*MTY2MzA2Njk0MC4zNC4xLjE2NjMwNjY5NTYuNDQuMC4w

Is there any way to actually retrieve that URL through the W&B Public API in Python?

**Comment by alvarobartt** [comment]
So I've found a way via reverse-engineering `wandb`'s code, but not sure whether this is the actual best way to do it, but it works so I'm closing this issue!

```python
import wandb

api = wandb.Api()
artifact = api.artifact(
  name=f"{entity}/{project}/{artifact_name}:{artifact_version}",
  type=artifact_type,
)
entity = artifact.entity
path = artifact.get_path(name=file_path)
manifest = path._parent_artifact._load_manifest()
policy = manifest.storage_policy
response = policy._session.get(
  policy._file_url(policy._api, entity, manifest.entries[path.name]),
  auth=("api", os.getenv("WANDB_API_KEY")),
  stream=True,
)
response.raise_for_status()
return response.url
```

**Comment by thanos-wandb** [comment]
Excellent! Thanks for posting this solution @alvarobartt. I also post an alternative option, let me know if that wouldn't work for you.

```
import wandb
import base64

api = wandb.Api()
artifact = api.artifact(
  name="wandb/yolo-chess/run_1dnrszzr_model:v8",
  type="model",
)
id = artifact.id
hid = wandb.util.b64_to_hex_id(artifact._load_manifest().entries["last.pt"].digest)
print(f"https://api.wandb.ai/artifactsV2/gcp-us/{artifact.entity}/{id}/{hid}")
```

**Comment by thanos-wandb** [comment]
Hi @alvarobartt thanks for the commit! The above snippet was an example, if you wanted to handle multiple files and not having to add the file name you could adapt as follows:

```
id = artifact.id
for _, name in artifact.manifest.entries.items():
    hid = wandb.util.b64_to_hex_id(name.digest)
    print(f"https://api.wandb.ai/artifactsV2/gcp-us/{artifact.entity}/{id}/{hid}")
```

**Comment by thanos-wandb** [comment]
Hi @alvarobartt it appears there is another more direct and neat way to do just that, so I am also posting that solution below and you can choose what fits best in your case. Please let me know if you have any questions regarding this. 

```
import wandb

api = wandb.Api()
artifact = api.artifact(
  name="wandb/yolo-chess/run_1dnrszzr_model:v8",
  type="model",
)
for f in artifact.files(per_page=1000):
  print(f.url)
```

**Comment by alvarobartt** [comment]
> 

So I tested that approach. but it doesn't seem to work if you want to retrieve the URL from a private artifact and then share it with others, as that URL is not authenticated... But thanks for also proposing that!

**Comment by alvarobartt** [comment]
> Hi @alvarobartt it appears there is another more direct and neat way to do just that, so I am also posting that solution below and you can choose what fits best in your case. Please let me know if you have any questions regarding this.
> 
> ```
> import wandb
> 
> api = wandb.Api()
> artifact = api.artifact(
>   name="wandb/yolo-chess/run_1dnrszzr_model:v8",
>   type="model",
> )
> for f in artifact.files(per_page=1000):
>   print(f.url)
> ```

Thanks for proposing @thanos-wandb! So the only thing is that it's `artifact._files` as `artifact.files` doesn't seem to be accessible, anyway I'll let you know, as ideally, I don't want to loop over all the files until I find the one that I want and then print its URL, so if `artifact.get_path` response object had the URL attribute, that would be perfect!

**Comment by thanos-wandb** [comment]
Hi @alvarobartt thanks for the additional context. Since you're interested only to specific filename you could then replace your last two lines with something like the following:

```
f = list(artifact.files(names=['last.pt'], per_page=1000))
print(f[0].url)
```

You can have multiple filenames in there and access their attributes from the created list. The artifact.files is an iterator of File objects (which are the ones with the url method).

Regarding the issue with artifact._files this should be fixed if you upgrade to the most recent version according to this [commit](https://github.com/wandb/wandb/pull/3969). Hope this helps!
