### ISSUE TITLE
[Q] Which is the port I should expose in my docker container to use keras Wandbcallback() to log models in wandb?

### ISSUE THREAD

**Issue by mathbr10** [wandb/wandb#4239]
I am currently logging my `Keras` weights in my Weights and Biases environment using `Wandbcalback()`. It works fine when I do it from my local machine.
When I do from a `container`, that is being used in the `GCP` cloud provider, the models are never being logged. I belevie I should expose some `port` in the container and in the machine to allow communication with Weights and Biases platform, but I can not find it in the documentation.

**Comment by lesliewandb** [comment]
Hi @mathbr10, are you using [wandb server](https://docs.wandb.ai/guides/self-hosted/setup/configuration) when you use GCP? If you are can you make sure that the [permissions](https://docs.wandb.ai/guides/self-hosted/setup/configuration#google-cloud-platform) are properly set up?

**Comment by vanpelt** [comment]
Hey @mathbr10, by default our library logs data to our hosted service at https://wandb.ai, this is the simplest way to use wandb and doesn't require any port forwarding.

If you want to run your own private wandb server you'll want to configure a load balancer and DNS then you can configure the SDK to use that server by setting the WANDB_BASE_URL environment variable.

**Comment by mathbr10** [comment]
Hello @lesliewandb, no I am only using Wandbcallback() and normal wandb run. I did not set those permission but they are related to wadb server wright?

**Comment by mathbr10** [comment]
Hi @vanpelt, yes maybe the port is not the poblem. I want to use your hosted serve in wandb.ai, but when I use keras WandbCallback  (https://docs.wandb.ai/ref/python/integrations/keras/wandbcallback) it does not logs the model in my gcp machine. It logs if I train in my local machine though.

**Comment by vanpelt** [comment]
Are you seeing any error messages in the logs?  You still need to call wandb.init before calling model.fit with the callback.  It could be that your containers have firewall rules that prevent access to the internet, but you would see errors in the logs.

**Comment by mathbr10** [comment]
Hello @vanpelt yes I am calling it. I am sending attached the output log
[output.log](https://github.com/wandb/wandb/files/9526432/output.log). Below I am sending also the callback structure we are using.

`
earlystopping = EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True)
        # TODO: add schedulers here
        self.callbacks = [
            earlystopping,
            tf.keras.callbacks.ModelCheckpoint(
                "ckpts/weights.{epoch:02d}-{val_accuracy:.5f}.hdf5",
                monitor="val_accuracy",
                verbose=1,
                save_best_only=False,  # save all the checkpoints
                # was showing error because the model's ist parent is tfimm not tf.keras.Model
                save_weights_only=True,
                mode="max",
                save_freq="epoch",
            ),
            WandbCallback(
                save_model=True,
                monitor="val_accuracy",
                mode="max",
                save_graph=True,
                save_weights_only=True,
                log_weights=True,
                log_gradients=False,
            ),
        ]
`

**Comment by mathbr10** [comment]
Data is being download from wandb in my pipeline. Where is located the `./wandb/debug-internal.log` I cant find it in the logs. Ok I will try this approach and get back to you soon.

**Comment by kptkin** [comment]
@mathbr10 since we haven't heard from you, we are going to close this issue. Feel free to re-open if you still have follow up questions.
