### ISSUE TITLE
[Q] events and code files not uploaded

### ISSUE THREAD

**Issue by CarlossShi** [wandb/wandb#4246]
Hi, I'm new to wandb and is running code in [ppo-implementation-details](https://github.com/vwxyzjn/ppo-implementation-details) following the video tutorial [Part 1 of 3 — Proximal Policy Optimization Implementation: 11 Core Implementation Details](https://www.youtube.com/watch?v=MEt6rrxH8W4).

The related code in the `ppo.py` are shown as follows
```python
    if args.track:
        import wandb
        wandb.init(
            project=args.wandb_project_name,
            entity=args.wandb_entity,
            sync_tensorboard=True,
            config=vars(args),
            name=run_name,
            monitor_gym=True,
            save_code=True,
        )
```

I ran `python ppo.py --track --capture-video` and saw the media uploaded, but found no events and code files on the wandb website console so that there is not any loss plot online.

Specifically, I got the logs
```
wandb: Waiting for W&B process to finish... (success).
wandb:
wandb: Synced CartPole-v1__ppo__1__1662611168: https://wandb.ai/carlos-shi/ppo-implementation-details/runs/y7wbggib
wandb: Synced 6 W&B file(s), 4 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: .\wandb\run-20220908_122611-y7wbggib\logs
```

But in the tutorial video, the expected log after running the same code is  like `wandb: Synced 6 W&B file(s), 4 media file(s), 0 artifact file(s) and 2 other file(s)`, which seems to me that the event and code files are not uploaded.

I also ran `tensorboard --logdir .\runs\CartPole-v1__ppo__1__1662608133\` and checked the logs were written correctly.

I'm on PyCharm Windows 10, with Python 3.8.13 and wandb 0.13.2. Any help would be greatly appreciated.

**Comment by thanos-wandb** [comment]
Hi @CarlossShi thank you for reporting this and providing all these details. Can you please try running the code again by disabling cuda and also specifying the project name and entity details as follows:
`python ppo.py --track --wandb-project-name ppo-implementation-details --wandb-entity carlos-shi --cuda False --total-timesteps 100000`
Please let me know if that would work? if so, you can also try with cuda enabled next.

**Comment by CarlossShi** [comment]
Hi, thanks for your quick response! I ran both `python ppo.py --track --cuda false` and `python ppo.py --track --wandb-project-name ppo-implementation-details --wandb-entity carlos-shi --cuda False --total-timesteps 10000` on Windows 10 and WSL2 Ubuntu 20.04.4 LTS. I made the project public on [https://wandb.ai/carlos-shi/ppo-implementation-details](https://wandb.ai/carlos-shi/ppo-implementation-details). The problems on Windows still exist and are summarised below.

On Windows 10

- I need to repeatedly input the key in each run. It seems that the directory `C:\Users\USERNAME/.netrc` is not detected by wanb, which I think is a path problem on Windows that would also cause the uploading problem. I found the key problem can be manually fixed by adding a line `os.environ["WANDB_API_KEY"]`
- There is no `Run history` and `Run summary` output on the terminal. The content of `wandb-summary.json` is `{"_wandb": {"runtime": 8}}`
- I can find the local `ppo.py` file located in `wandb\run-20220909_101714-144qbg8p\files\code\ppo.py`, but have no idea why it is not uploaded. This is the only difference between local files and online files.
- Events file exists in `runs\CartPole-v1__ppo__1__1662608133`, but is missing both locally (in `wandb\run-20220909_101714-144qbg8p\files`) and also online,

On WSL2 Ubuntu 20.04.4 LTS, everything goes fine except the upload of code. Specifically, I can find `ppo.py` locally but not online, which is the same as the situation I face on Windows.

Using WSL2 kind of resolves my problem, but I hope there are some ways I can try it on Windows.

**Comment by thanos-wandb** [comment]
Hi @CarlossShi thanks for the additional detailed information! For Win 10 are you running the code in `cmd`? have you tried with Jupyter notebook? would that work for you? 
Regarding the code uploading, have you enabled from https://wandb.ai/settings the option for code saving in your personal account?

**Comment by CarlossShi** [comment]
Hi @thanos-wandb, thanks for your suggestions! I have solved all my problems.
- I ran the code in PyCharm terminal when I met the problem. But when I run the code in cmd with admistrators, the events file is finally uploaded as expected.
- The code file is also uploaded correctly after I turn on the code saving option. Forgive my carelessness.

**Comment by thanos-wandb** [comment]
Hey @CarlossShi thank you for writing how this was solved, and great to hear everything now works for you! I am closing the ticket for now, but please feel free to re-open it if you have any additional questions or issues with this.
