### ISSUE TITLE
[Q]the "entity" of wandb.init is not work

### ISSUE THREAD

**Issue by Yangsenqiao** [wandb/wandb#4263]
Hi, I'm new to wandb and is running code. However, I have two teams so I need each code runs under the corresponding group. However, when I use the wandb.init() the “entity” is not work, no matter what I fill in, it will automatically log in to the default entity. This confuses me, thank you.

**Comment by ramit-wandb** [comment]
Hi @Yangsenqiao!

Could you share a link to a run logged to the wrong user along with the code snippet you used to call `wandb.init` for that run? Also, what version of the `wandb` SDK are you using?

As a side note, we have an option in wandb.ai/settings to change the default entity to which runs are logged in case you want to change the default completely.

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
Hi @Yangsenqiao, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
​
