### ISSUE TITLE
[App]: Table sorting mechanism has a bug

### ISSUE THREAD

**Issue by yanghoonkim** [wandb/wandb#4266]
### Current Behavior

when sort Desc

![image](https://user-images.githubusercontent.com/9985986/190067433-eb7488f7-7d31-42a4-9983-271487382386.png)

some numbers formmatted as n e-0k has wrong order

for example, in the image,  9.360033276174322e-05 < 0.004638235609728778

### Environment

OS: Windows

Browsers: chrome

**Comment by ramit-wandb** [comment]
Hi @yanghoonkim !

Thanks for reaching out! I'll pass this information off to our engineers to have this resolved. Is there a project link you can share so that we can look into this?

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
Hi @yanghoonkim,

Just checking in here - would it be possible to share the link for this project?

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
​Hi @yanghoonkim, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
​
