### ISSUE TITLE
[Q] Can i upload files to old finished runs?

### ISSUE THREAD

**Issue by umbertov** [wandb/wandb#4285]
Hi, I have a problem with checkpoints sometimes not being uploaded when i manually stop training with Ctrl+C multiple times (since it also interrupts file uploads).

The problem is that i cannot figure out a way to upload those checkpoint after the run is completed.
I have tried the following, all with no results:
```python
import wandb
api = wandb.Api()
run = api.run("my_entity/my_project/my_run_id")
###### ***move relevant files to run.dir***
run.save()
run.finish()
```

```sh
wandb sync --id my_run_id wandb/my_run_path/ --include-synced
```

And also this:
```python
wandb.init(id="my_run_id")
wandb.save("path/to/checkpoints/last.ckpt.zip", base_path="/path/to/checkpoints", policy="now")
wandb.finish()
```
Which i have just found to create new run directories.

None of the methods i tried worked, and i can't find information by googling.

Anyone knows if uploading files to finished runs is at all possible, and if so, how?

**Comment by thanos-wandb** [comment]
Hi @umbertov have you tried restoring the model (for instance model.h5 from my_run_id) as follows:

wandb.restore('model.h5', run_path="my_entity/my_project/my_run_id")

Would this work for you? There is some more information about restoring models in [this](https://wandb.ai/lavanyashukla/save_and_restore/reports/Saving-and-Restoring-Models-with-W-B--Vmlldzo3MDQ3Mw) Report and our reference docs [here](https://docs.wandb.ai/guides/track/advanced/save-restore).

Regarding the issue with the creation of new run directories in the second method you described above, can you please try the following and see if that helps? 

`wandb.init(id="my_run_id", resume="must")`

**Comment by umbertov** [comment]
Hi @thanos-wandb my problem is just that: there is no model checkpoint to be loaded, since it didn't get uploaded to W&B during the run in the first place (due to e.g. power outage, program crashing or being killed). 

My checkpoint files were however saved on disk (to another location outside the wandb run dir), so i have access to them. 
Still, I would like these checkpoint files to be uploaded to the W&B run, because that's where they belong and can be easily accessed even if i switch machine.

Is there a way to upload files or artifacts to a run post-mortem?

I usually add checkpoints as files in the `./run_files/checkpoints/` path of the W&B run, but certainly adding them as artifacts would work just the same for me.

**Comment by thanos-wandb** [comment]
Hi @umbertov apologies for the late response here, and thanks for the additional information. In this case you can use our Public API to upload files to a finished run. Please find [here](https://docs.wandb.ai/ref/python/public-api/run#upload_file) the `upload_file` method documentation and below a code snippet:

```
import wandb
api = wandb.Api()

run = api.run("entity/project/run_id")
run.upload_file("file_name.extension")
```

Would this work for you to upload the checkpoint files?

**Comment by thanos-wandb** [comment]
Hi @umbertov just following up on this issue, has it been now resolved for you? were you able to upload the files using the API?

**Comment by umbertov** [comment]
Hi @thanos-wandb , and pardon the late reply. 
Yes the `upload_file` method is exactly what i was looking for, somehow i didn't catch it when i was reading the docs! Thanks for your help.

**Comment by thanos-wandb** [comment]
Thanks for the confirmation @umbertov, I am glad this works for you! I will close the ticket for now, but let us know if you have any further questions or issues.
