### ISSUE TITLE
[Feature]: Quartiles in chart grouping.

### ISSUE THREAD

**Issue by andrewwarrington** [wandb/wandb#4288]
### Description

Hi WandB,

It would be really useful if you could add quartiles to the grouping of samples in the web GUI.  You have the median as an option for the aggregate, and the most natural range metric for that is quartiles.  It is also asymmetric which is useful (unlike i.e. stddev). 

Thank you very much!
Andy

### Suggested Solution

Add a grouping option for quartiles.  

### Alternatives

N-th percentiles is also an option (i.e. user-specified upper and lower percentiles) but that seems more involved.

**Comment by lesliewandb** [comment]
Hi @andrewwarrington! Thank you for the feature request :) We actually have a ticket out for this. I've further increased the priority on it and I'll let you know if there are any updates on it

**Comment by andrewwarrington** [comment]
Thank you!  👍
