### ISSUE TITLE
[CLI]:  error in callback 

### ISSUE THREAD

**Issue by GeorgePearse** [wandb/wandb#4294]
### Describe the bug

Drives me insane. Literally no code can be executed after this point. The Notebook is gone, kaput, useless. Hit this bug in two completely differently companies and completely different environments (GCP and on-prem).

![image](https://user-images.githubusercontent.com/47161914/191374942-518c558f-13dd-4a61-b6db-29da36cbeba7.png)

### Environment

WandB version:

OS:

Python version:

Versions of relevant libraries:

**Comment by MBakirWB** [comment]
Hi @GeorgePearse , can you please provide an example notebook for us description of your steps to reproduce this behavior, thanks.

**Comment by GeorgePearse** [comment]
Think it normally occurs when I've interrupted training.

**Comment by MBakirWB** [comment]
Hi @GeorgePearse , thank-you for the update. What type of environment are you running wandb in, additionally which version of wandb are you using?

**Comment by MBakirWB** [comment]
Hi @GeorgePearse , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by kptkin** [comment]
@GeorgePearse could you try running `wandb.teardown()` and see if this resolves your issue?
I think there is residual state that is not cleared completely that causes this issue
