### ISSUE TITLE
[CLI]: Logging code in separate runs using multiprocessing creates deadlock

### ISSUE THREAD

**Issue by kiddyboots216** [wandb/wandb#4297]
### Describe the bug

When wandb logs artifacts, specifically code, it is for some reason requesting some file permissions that can create deadlock. This error manifests when a race condition is met, so is transient, but can be easily reproduced if you simply initiate a large number of runs that all do the same thing. It's worth mentioning that if I replace the line 'wandb run log code' with my own implementation of a function with the same functionality (iterates over fds, checks whether they are valid, then uploads only the diffs to a remote server over ssh) this error does not occur.

```python
import wandb
wandb.init()
wandb.run.log_code("/your/library/here/")
```

```shell
wandb: ERROR Error while calling W&B API: conflict detected for file digest 0Jk9O1SycvE+N699TA6aZg==, rebase required (<Response [409]>)
wandb: ERROR Error while calling W&B API: conflict detected for file digest 0Jk9O1SycvE+N699TA6aZg==, rebase required (<Response [409]>)
wandb: ERROR Error while calling W&B API: conflict detected for file digest 0Jk9O1SycvE+N699TA6aZg==, rebase required (<Response [409]>)
```

This error is mentioned by multiple users recently in #1407 but it is closed so I am making a new issue here.

### Environment

WandB version: 0.13.3

OS: Linux

Python version: 3.8.13

Versions of relevant libraries: N/A

**Comment by thanos-wandb** [comment]
Hi @kiddyboots216 thank you for reporting this and for bringing to our attention the closed issue thread. 

This is a known issue indeed and the engineering team is working on a fix. Have you noticed this happening only when logging code? would it work for you to use `run.log_code(".", name=run.name)` as a temporary workaround? it creates a new Artifact every run so this may not be an ideal solution. Alternatively you could use `wandb.save('./*.py*')` to attach the files to each run (but this option lacks the Artifacts functionality). Please let me know if these work for you, or if you have any further questions/issues with these!

**Comment by kiddyboots216** [comment]
Hi @thanos-wandb thank you, I have already worked around it in the manner that you suggested.

**Comment by kevinashaw** [comment]
I'm seeing the error too:
`wandb: ERROR Error while calling W&B API: conflict detected for file digest 5JTLlpZ+AyHsSsztei4mpA==, rebase required`

**Comment by thanos-wandb** [comment]
Thanks for the update @kiddyboots216 and glad this now works for you! 

Hi @kevinashaw thank you for reporting this as well. Can you please provide a bit more information on the conditions when you're running into this issue? Do you have calls to `log_code` and did you try any of the above workarounds? is the `user` from the logs you provided intentionally changed? Can you try to force login as: `wandb login --relogin` and run your code again?

**Comment by kevinashaw** [comment]
No idea why, but the error has gone away.  I'll report again if I can repeat it.

**Comment by thanos-wandb** [comment]
Hi @kiddyboots216 @kevinashaw  just an update on this issue, our engineering team has released a fix and it should be now resolved. However, please let us know if the issue still occurs for you, and we will be happy to keep investigating.

**Comment by VitamintK** [comment]
@thanos-wandb Was this fix on the server or client side? I updated to 0.13.7 but am still getting `wandb: ERROR Error while calling W&B API: conflict detected for file digest 0Jk9O1SycvE+N699TA6aZg==, rebase required (<Response [409]>)` errors.

**Comment by VitamintK** [comment]
@thanos-wandb bump
