### ISSUE TITLE
[Q] wandb.watch() have large gradients while using gradient_clip

### ISSUE THREAD

**Issue by icedpanda** [wandb/wandb#4301]
Hi, 

I'm using `PyTorch lightning` and  set `gradient_clip_val` to `1.0`. However, the gradient from `wandb.watch()` are really big.

Is it reasonable to have such large gradients? 

![W B Chart 9](https://user-images.githubusercontent.com/45261170/191788516-d4dde9c2-ca42-4c1b-9130-f07081c4b080.png)

The max/min gradients are over 10000 in the last few epochs.

**Comment by thanos-wandb** [comment]
Hi @icedpanda thank you for writing in. Would it be possible to share a reproducible code example with us? and a link to your Workspace?

**Comment by thanos-wandb** [comment]
Hi @icedpanda We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by thanos-wandb** [comment]
Hi @icedpanda, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by jamarju** [comment]
Could it be that Wandb's `watch` is logging the scaled gradients? This callback will get you the actual un-scaled gradients, they are orders of magnitude smaller in my case:

```py
from lightning.pytorch.utilities import grad_norm

    def on_before_optimizer_step(self, optimizer):
        # If using mixed precision, the gradients are already unscaled here
        norms = grad_norm(self, norm_type=2)
        self.log_dict(norms)
```
