### ISSUE TITLE
[CLI]: Integration with OpenAI gym is broken due to missing ImageEncoder in the most recent gym version

### ISSUE THREAD

**Issue by pauldb89** [wandb/wandb#4305]
### Describe the bug

The following snippet to initialize wandb with gym monitoring:

```
wandb.init(project="atari",  monitor_gym=True)
```

throws the following exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1073, in init
    wi.setup(kwargs)
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 247, in setup
    wandb.gym.monitor()
  File "/usr/local/lib/python3.9/site-packages/wandb/integration/gym/__init__.py", line 11, in monitor
    vcr.ImageEncoder.orig_close = vcr.ImageEncoder.close
AttributeError: module 'gym.wrappers.monitoring.video_recorder' has no attribute 'ImageEncoder'
```

which checks out because the `ImageEncoder` class was removed in the gym repo [here](https://github.com/openai/gym/commit/de9eed541b9a2fda2bb33e72c235e2169a2f72a7).

### Environment

WandB version:
wandb==0.13.3

OS: Ubuntu 20.04.4 LTS

Python version: 3.9.7

Versions of relevant libraries:
gym==0.26.1

**Comment by MBakirWB** [comment]
Hi @pauldb89 , thank-you for letting us know. I put in a request for review by eng. Once I hear back with updates, I will let you know. In the meantime please continue using the last compatible gym version, 0.25.2.
