### ISSUE TITLE
[CLI]: Display name attribute in publicApi.runs documentation is wrong

### ISSUE THREAD

**Issue by mjvanderboon** [wandb/wandb#4308]
### Describe the bug

The documentation in publicApi.runs() uses the attribute "display_name" to filter for runs where run name matches a regex. This attribute should probably be "displayName".

### Environment

WandB version:

OS:

Python version:

Versions of relevant libraries:

**Comment by thanos-wandb** [comment]
Hi @mjvanderboon thank you for writing in! The documentation is correct, you can confirm this by running something like the following:
 
```
api = wandb.Api()
entity= 'entity-name'
project= 'project-name'
runs = api.runs(
    path=f"{username}/{project}",
    filters={"display_name": {"$regex": ""[1-9]*""}}
for r in runs:
  print(r.display_name)
)
```

Would this work for you? if not, which wandb version are you using?

**Comment by mjvanderboon** [comment]
Hi @thanos-wandb . Not sure what went wrong when I tested "display_name", because that does work as expected. In fact, both displayName and display_name work for the query, and the returned runs have both run.displayName and run.display_name. @dmitryduev thanks for merging, but perhaps it's better to rollback this PR to stick to variable_name convention. Sorry for the hassle.

**Comment by thanos-wandb** [comment]
Hi @mjvanderboon no worries at all, on the contrary, we thank you for the PR! Indeed both variables are available and work here for the query. I am closing this ticket for now but please let me know if you have any further questions or issues with this. Have a great day!
