### ISSUE TITLE
[CLI]: run.summary does not contain the underlying stored tensor

### ISSUE THREAD

**Issue by kiddyboots216** [wandb/wandb#4311]
### Describe the bug

Updating the wandb summary dictionary with a tensor or NumPy array should persist that data as a binary file according to the documentation. However, it does not seem possible to access the underlying tensors. 

```python
meta = wandb.api.download_url("project", "wandb.h5", "entity", "run-id")
path, res = api.download_write_file(meta, out_dir="/your/directory/here")
```

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Api' object has no attribute 'download_write_file'
```

### Environment

WandB version: 0.13.3

OS:

Python version:

Versions of relevant libraries:

**Comment by thanos-wandb** [comment]
Hi @kiddyboots216 thank you for reporting this! May I ask what's the use case here, is it to update the run.summary or to download the wandb.h5 model and access the tensors? Also, can you please post what's the output you get from the first command? and how did you define `api` before as it's inconsistent between the two lines?

**Comment by kiddyboots216** [comment]
The usecase is to download the .h5 tensor (in this case it is something maintained by the optimizer) and access it. The first command does not produce any output. api = wandb.Api() is how I defined the api.

**Comment by thanos-wandb** [comment]
Hi @kiddyboots216 thank you for the additional information. The methods you use are defined in the InternalApi, but for your case it would be best and simpler to use the Public API. Can you try the following and let me know if it works?

```
import wandb
api = wandb.Api()

run = api.run("<entity>/<project>/<run_id>")
run.file("wandb.h5").download()
```

**Comment by kiddyboots216** [comment]
Hi @thanos-wandb this raises an HTTP 404 error. HTTPError: 404 Client Error: Not Found for url: https://api.wandb.ai/files/kiddyboots216/dp/18mn4f7g/wandb.h5

**Comment by thanos-wandb** [comment]
Hi @kiddyboots216 this is because there is no `wandb.h5` under the files in this specific Run. There is a tensor stored in `output.log` file. Can you try replace the file names: `run.file("output.log").download()` and see if that works for you? thanks!

**Comment by thanos-wandb** [comment]
Hi @kiddyboots216 just following up on this issue, did the above resolve it for you or are you still getting any HTTPError or other error messages? thanks!

**Comment by thanos-wandb** [comment]
Hey @kiddyboots216 since we haven't heard back from you, I will go ahead and close this ticket. Please let us know if you still experience any issue or have further questions, and we will be happy to re-open this and keep investigating.
