### ISSUE TITLE
[CLI]: Receiving `-bash: wandb: command not found` error.

### ISSUE THREAD

**Issue by seanswyi** [wandb/wandb#4315]
### Describe the bug

Hi! I've been using W&B without any problem for a while now but recently I noticed the command isn't being recognized. I've taken a look at [Issue #1969](https://github.com/wandb/wandb/issues/1969) and have also tried the workaround `python -m wandb.cli` which doesn't work. I installed W&B using PIP.

Does anybody have any suggestions on what I could do? I've tried uninstalling and re-installing but it doesn't seem to work.

### Environment

WandB version: 0.13.3

OS: Linux

Python version: 3.7.9

Versions of relevant libraries: requests (2.28.1)

**Comment by ramit-wandb** [comment]
Hey @seanswyi,

Could you confirm for me that your python executable is present on your PATH env var? Let's also run a few other steps to be sure we have not executed `wandb` on a different python executable:

1. Uninstall `wandb` : This should be done however you did it last time.
2. Run `which python3` : This should give you an output like `/usr/bin/python3` (Just an example, could be different for you)
3. Use this path to reinstall `wandb` as : `/usr/bin/python3 -m pip install wandb`

Once this is done, let's try running 3 commands to check where the issue may be lying:
1. `wandb login`
2. `python3 -m wandb login`
3. `/usr/bin/python3 -m wandb login`

Please let me know what you find from these tests, and then we can look into this further!

Thanks,
Ramit

**Comment by seanswyi** [comment]
Hi @ramit-wandb thanks for the comment!

Unfortunately I've tried that and it didn't work. I've added the Python executable to my path and did as you suggested. However, when I run `wandb login` I still get the `-bash: wandb: command not found` error.

**Comment by seanswyi** [comment]
@ramit-wandb I'm not sure if this is even relevant, but the only thing that I can think of that I did differently was run `direnv` for another project. Could that be causing potential problems?

**Comment by ramit-wandb** [comment]
Hi @seanswyi!

Apologies for the delay here. That's definitely very weird - I think your `PATH` environment variable might not have been configured correctly. Do you have your python distribution's `/bin` file present in your `PATH`?

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
​Hi @seanswyi ,

We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by ramit-wandb** [comment]
​Hi @seanswyi, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
​

**Comment by JosephSBoyle** [comment]
FWIW I solved this by running `python -m wandb login` if that doesn't work I would try `python3 -m wandb login`.
