### ISSUE TITLE
[CLI]: Faulty parse_path logic in wandb.apis.public.Api.run(path="")

### ISSUE THREAD

**Issue by calvinleungyk** [wandb/wandb#4320]
### Describe the bug

From https://docs.wandb.ai/ref/python/public-api/api#run, I see `If api.entity is set, this can be in the form project/run_id and if api.project is set this can just be the run_id.`

The logic that parses path in [wandb/apis/public.py#L642](https://github.com/wandb/wandb/blob/master/wandb/apis/public.py#L642) suggests otherwise and after I set both `entity` and `project`, just passing in `"run_id"` results in `entity/run_id/run_id` as `_parse_path()` treats `run_id` as the `project` as well.

```python
api = wandb.Api(
  overrides={
    "base_url": "https://base_url",
    "entity": "user",
    "project": "uncategorized",
  })
run = api.run(path="run_id")
```

```shell
ValueError: Could not find run <Run entity/run_id/run_id (not found)>
```

### Environment

WandB version: 0.12.21

OS: CentOS 7 / MacOSX 12.5.1

Python version: 3.7

Versions of relevant libraries:

**Comment by devforfu** [comment]
It seems like this issue persists in `wandb.__version__ == '0.15.12'`. 

I am trying to use a `wandb.Api` object and encounter the same problem.
```python
import wandb

api = wandb.Api(overrides={"entity": "my_entity", "project": "my_project"})

print(api.settings)
# {'section': 'default',
#  'git_remote': 'origin',
#  'ignore_globs': [],
#  'base_url': '...',
#  'root_dir': None,
#  'api_key': None,
#  'entity': 'my_entity',
#  'project': 'my_project',
#  '_extra_http_headers': None}

run_id = ...
api.run(run_id)

# CommError: Could not find run <Run my_entity/<run_id>/<run_id> (not found)>
```
So, it uses `run_id` twice in the URI instead of building it as `my_entity/my_project/<run_id>`.

Do you have any estimate when it might be solved?

**Comment by luisbergua** [comment]
Hi @devforfu, thanks for flagging this one. I'll bump up the priority of this bug internally so that it can be prioritized

**Comment by luisbergua** [comment]
Hey @calvinleungyk @devforfu, thanks for your patience! This issue has been fixed and will be included in the next release
