### ISSUE TITLE
[Feature]: Speed up filtering files in a directory with excluded sub-directories

### ISSUE THREAD

**Issue by amitabe** [wandb/wandb#4322]
### Description

Currently, when calling `wandb.sdk.lib.filenames.filtered_dir`, the function iterates over every file and folder in the root directory.
The problem starts if there is a directory containing a lot of files that needs to be excluded - in such case, the function will iterate all the files in this directory for no reason.

### Suggested Solution

The function current implementation:
```
def filtered_dir(
    root: str, include_fn: Callable[[str], bool], exclude_fn: Callable[[str], bool]
) -> Generator[str, None, None]:
    """Simple generator to walk a directory"""
    for dirpath, _, files in os.walk(root):
        for fname in files:
            file_path = os.path.join(dirpath, fname)
            if include_fn(file_path) and not exclude_fn(file_path):
                yield file_path
```

Instead of ignoring the directories, one can iterate over the directories as well and exclude them if needed. The change is implemented in the following code snippet:

```
def filtered_dir(
    root: str, include_fn: Callable[[str], bool], exclude_fn: Callable[[str], bool]
) -> Generator[str, None, None]:
    """Simple generator to walk a directory"""
    for dirpath, dirs, files in os.walk(root):
        for dir in dirs:
            if exclude_fn(dir):
                dirs.remove(dir)
        for fname in files:
            file_path = os.path.join(dirpath, fname)
            if include_fn(file_path) and not exclude_fn(file_path):
                yield file_path
```

**Comment by ramit-wandb** [comment]
Hi @amitabe!

Thank you for your suggestion, I can create an internal feature request for this, or if you would like - you can submit a PR to this repository as well.

Thanks,
Ramit
