### ISSUE TITLE
The same parameter happens in multiple runs in a Sweep

### ISSUE THREAD

**Issue by talenz** [wandb/wandb#4323]
### Current Behavior

The config.yaml is as follows:
_program: hpo.py
project: random_name
name: hqo
method: grid
parameters:
  seed:
    values: [0,1,2,3,4,5,6,7]_

I ran 8 agents on 8 gpu manually, it gives me 8 runs. **WHILE only 4 seeds are chosen (should be 8) as follows, it wastes half of my gpu!!!**

![image](https://user-images.githubusercontent.com/6121158/192720324-cf5f0902-6c72-4b5c-bc49-662926e433d3.png)

### Expected Behavior

It should gives 8 runs, each run has a unique seed in [0, 7]

### Environment

OS:

Browsers:

Version:

**Comment by thanos-wandb** [comment]
Hi @talenz thank you for reporting this! Can you please share a screenshot of your Sweep Overview page? also would it be possible to provide a code snippet of your `agent` and `wandb.init` calls and the part where you specify your GPU according to the seed number?

**Comment by talenz** [comment]
Usage of wandb.config in my hpo.py:
_wandb.init()

random.seed(wandb.config.seed)
torch.manual_seed(wandb.config.seed)_

I didn't specify the GPU according to the seed, while the GPU is specified in ENV CUDA_VISIBLE_DEVICES. I ran 8 times in 8 terminal use the same following command:

_wandb agent user/project_name/59atlow4_

**Comment by thanos-wandb** [comment]
Thanks @talenz for the additional information, can you also try running the agents by specifying the GPU as follows:
  ```
  CUDA_VISIBLE_DEVICES=0 wandb agent 59atlow4
    CUDA_VISIBLE_DEVICES=1 wandb agent 59atlow4
    ...
    CUDA_VISIBLE_DEVICES=7 wandb agent 59atlow4
```
Would this work for you?

**Comment by talenz** [comment]
> Thanks @talenz for the additional information, can you also try running the agents by specifying the GPU as follows:
> 
> ```
> CUDA_VISIBLE_DEVICES=0 wandb agent 59atlow4
>   CUDA_VISIBLE_DEVICES=1 wandb agent 59atlow4
>   ...
>   CUDA_VISIBLE_DEVICES=7 wandb agent 59atlow4
> ```
> 
> Would this work for you?

That's exactly what I did !

**Comment by thanos-wandb** [comment]
Hi @talenz can you please send a screenshot of your Sweep overview page (as the one below) to check if seed gets all the values there? may I also ask where are you using the random.seed() and torch.manual_seed() values? thanks

<img width="443" alt="Screenshot 2022-10-12 at 00 40 39" src="https://user-images.githubusercontent.com/108423944/195218227-58286b69-8e8b-4339-ac65-d1b64a79938a.png">

**Comment by talenz** [comment]
> Hi @talenz can you please send a screenshot of your Sweep overview page (as the one below) to check if seed gets all the values there? may I also ask where are you using the random.seed() and torch.manual_seed() values? thanks
> 
> <img alt="Screenshot 2022-10-12 at 00 40 39" width="443" src="https://user-images.githubusercontent.com/108423944/195218227-58286b69-8e8b-4339-ac65-d1b64a79938a.png">

I set seeds in yaml as follows:
```
seed:
    values: [0,1,2,3,4,5,6,7]
```
And the seeds is used in .py file:

> random.seed(wandb.config.seed)
> torch.manual_seed(wandb.config.seed)
> cudnn.deterministic = True
> cudnn.benchmark = False

**Comment by thanos-wandb** [comment]
Hi @talenz thank you for the additional information. The amount of estimated runs (8 GPUs * 8 parameters) points out that the issue is that each GPU tries out all the possible permutations. Have you deleted some experiments and then run the agents using the same sweep_id? that would explain why the run count is more than estimated runs. 

Would it be possible to run the same code in single GPU and see if that would use all seeds? Also, could you please provide a bit more context on how you're doing the distributed training (frameworks, [logging in one or multiple processes](https://docs.wandb.ai/guides/track/advanced/distributed-training))?

**Comment by thanos-wandb** [comment]
Hi @talenz just checking in with you to see if there are any updates about this issue, and if you could provide any additional information regarding the above? thanks

**Comment by thanos-wandb** [comment]
Hi @talenz since we haven't heard back from you, I will go ahead and close the ticket for now. Please let us know if you still experience this issue, and we can re-open this and keep investigating.

**Comment by bigbenbird** [comment]
same thing happened to me!!!
