### ISSUE TITLE
[CLI]: Can't download more than 500 files with `wandb pull`

### ISSUE THREAD

**Issue by MasterScrat** [wandb/wandb#4324]
### Describe the bug

I am trying to download some images from a long (28d+) training run. However I can't find a way to either:
- Specify the folder or file mask of what I want to download
- Download more than 500 files

This prevents me from downloading the files I need, as they are not in the first 500 files

```python
wandb pull -p <project> -e <entity> <run_with_over_500_files>
```

### Environment

WandB version: `wandb, version 0.13.3`

OS: MacOS 12.4

Python version: `Python 3.8.13`

**Comment by thanos-wandb** [comment]
Hey @MasterScrat just following up on this issue, did you try the above workaround to download the files you need? Thanks!

**Comment by thanos-wandb** [comment]
Hi @MasterScrat since we haven't heard back from you, I will go ahead and close this ticket for now. Please let us know if this hasn't been resolved for you, we will be happy to open this again and keep investigating.
