### ISSUE TITLE
The server is uploaded with partial information

### ISSUE THREAD

**Issue by ioanacretu97** [wandb/wandb#4331]
The data that is send to the server is incomplete (or logged from time to time and not at every epoch).
I am saying this because the number of epochs on the server is 72 whereas in reality is over 200 (when I print in jupyter notebook). The wandb sends data for just 190 epochs, although in the notebook the training is running to 1000 epochs. At the end of the training (1000 epochs) I receive this error:
`ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host`
Can anyone please tell me what the cause of this error is and how can it be fixed?

**Comment by MBakirWB** [comment]
Hi @ioanacretu97, we've seen this issue in the past and it could be directly attributed to users proxy and SSL certificates. Please provide the `debug.log` and `debug-internal.log` files for the crashed run, the files may provide additional clues. Thanks

**Comment by MBakirWB** [comment]
Hi @ioanacretu97 since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by ioanacretu97** [comment]
Hi @MBakirWB, thank you for your response and apologies for not answering earlier. The problem was actually not from the wandb. I was running this code on an external GPU server and (I think) the internet connection was lost, and it wasn't transmitting the data online on the cloud. I solved this error by running everything offline and then using sync at the end of the training.

**Comment by MBakirWB** [comment]
Hi @ioanacretu97 thank you for updating us on your use case and how it contributed to the error you ran into. I'm glad you were able to run your experiments offline successfully and sync them to your workspace. Please do reach out again when any additional questions come up.
