### ISSUE TITLE
Import Error on M1 Chip

### ISSUE THREAD

**Issue by yannickeich** [wandb/wandb#4349]
Hey, I have trouble importing the wandb module on my M1 Chip.

I did the installation with the command:
pip install wandb.

But I get the following error, when trying to import wandb in PyCharm:

ImportError: dlopen(/Users/test/PycharmProjects/test_project/venv/lib/python3.9/site-packages/psutil/_psutil_osx.cpython-39-darwin.so, 0x0002): tried: '/Users/test/PycharmProjects/test_project/venv/lib/python3.9/site-packages/psutil/_psutil_osx.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_psutil_osx.cpython-39-darwin.so' (no such file), '/usr/lib/_psutil_osx.cpython-39-darwin.so' (no such file)

Any ideas how to handle this?

**Comment by ramit-wandb** [comment]
Hi @yannickeich,

Looks like there is an issue with `psutil` installing the incorrect binary, could you try the following

```
pip uninstall psutil
pip install --no-cache psutil
```

Thanks,
Ramit

**Comment by yannickeich** [comment]
Thank you for your fast reply!

Unfortunately I get the same error,  when I try what you proposed.

Best,
Yannick

**Comment by ramit-wandb** [comment]
Hey @yannickeich,

Perhaps using Rosetta 2 would help resolve this:

```
arch -arm64 python3 -m pip install wandb
```

Are you having problems installing other libraries / running other code on your computer? This definitely sounds like a configuration issue between Python and your Mac and not an issue at W&B's end, since I'm able to run `wandb` SDK fine on my M1 Mac. One other option which might work is actually downloading a fresh install of Python which you know would work with the M1 chip.

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
​Hi @yannickeich,

We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by ramit-wandb** [comment]
​Hi @yannickeich, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by Ben-jamin888** [comment]
Hey, I have trouble in configuring Django-mysql environment.

thread '<unnamed>' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/pyo3-0.20.3/src/err/mod.rs:788:5:
Python API call failed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
