### ISSUE TITLE
I'm trying to execute my code via SSH using 2 GPUs but I get this error

### ISSUE THREAD

**Issue by lorenzlorg** [wandb/wandb#4365]
I'm executing the training of YOLOv7 using Multi-GPU DistributedDataParallel Mode (https://docs.ultralytics.com/tutorials/multi-gpu-training/).

The error is: 
**FileNotFoundError: [Errno 2] No such file or directory: 'runs/train/exp52/weights'**

Using only one GPU everything is ok.

Why?

**Comment by ramit-wandb** [comment]
Hi @lorenzlorg,

This error does not seem to be related to W&B - looks like the weights are missing. I would look further look into the documentation of the YOLOv7 library or reach out to their developers.

Thanks,
Ramit

**Comment by lorenzlorg** [comment]
@ramit-wandb thanks for your reply! I've tried to change weights but I get the same error.
 
Anyway, it's strange because other similar errors arise, such as: 
**PermissionError: [Errno 13] Permission denied: 'runs/train/exp...**
It seems that the code has some problems accessing to these folders.

**Comment by ramit-wandb** [comment]
Can you share the whole stack trace?

**Comment by ramit-wandb** [comment]
​Hi @lorenzlorg, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
