### ISSUE TITLE
[App]: Custom chart shows "no data available", 

### ISSUE THREAD

**Issue by andrewgark** [wandb/wandb#4368]
### Current Behavior

Custom Plot writes "No data available", see screenshot below

### Expected Behavior

I expected for custom plot to draw the plot.

### Steps To Reproduce

1. Set up local wandb
2. 
```
import wandb
wandb.init(project="ProjectExample")
table = wandb.Table(data=[(x, x ** 2) for x in range(1, 10)], columns = ["x", "y"])
wandb.log({"NativePlotExample" : wandb.plot.line(table, "x", "y", title="Custom Y vs X Line Plot")})
wandb.finish()
```

I'm not sure this behaviour is reproducible, I had troubles with installing wandb-local and at my first iteration this plot worked but server stopped working and when I restarted the server and created this plot again, everything was fine except this plot that stopped drawing. 

### Screenshots

![image](https://user-images.githubusercontent.com/9502906/195502903-6f747e06-7bbe-43e0-893e-717326f0f27f.png)

You can clearly see where the bug is in a response:
```
message: "objconv/json: expected token but found '<'"
path: ["runSets", 0, "summaryTable"]
```

But http query does not contain '<':
```
operationName: null
query: "{\n  runSets(runSets: [{entityName: \"demo_iser\", projectName: \"ProjectExample\", filters: \"{\\\"$and\\\":[{\\\"$or\\\":[{\\\"$and\\\":[{\\\"name\\\":\\\"2j5abltc\\\"}]}]},{\\\"$and\\\":[{\\\"name\\\":{\\\"$ne\\\":null}}]}]}\", order: \"+createdAt\", grouping: []}], limit: 500) {\n    id\n    name\n    _defaultColorIndex\n    summaryTable(tableKey: \"NativePlotExample_table\", tableColumns: [\"y\", \"x\"])\n    _defaultColorIndex1: _defaultColorIndex\n    __typename\n  }\n}\n"
variables: {}
```

### Environment

OS:
Fedora 33 (Container Image)
Browsers:
Google Chrome
Version:
wandb==0.13.4

### Additional Context

The same mistake can be found in earlier issue: https://github.com/wandb/wandb/issues/2051.
But sumple change from summaryTable to historyTable does not help. The bug is seemingly is in something else, probably in objconv/json generation.

**Comment by thanos-wandb** [comment]
Hi @andrewgark thank you for reporting this! This code seems to work fine in the W&B public cloud instance. May I ask which local version you're using so as to try to reproduce this issue (you can easily check from the UI from top right icon and then settings)? also can you please post the output of `wandb verify` command from your CLI?

**Comment by andrewgark** [comment]
Version: W&B Local 0.20.0

And yeah, `wandv verify` did find some bad things:
```
Default host selected: http://10.80.0.206:8080
Find detailed logs for this test at: /tmp/tmpxbr95cr2/wandb
Checking if logged in...................................................✅
Checking signed URL upload..............................................✅
Checking ability to send large payloads through proxy...................✅
Checking requests to base url...........................................❌
Connections are not made over https. SSL required for secure communications.
Checking requests made over signed URLs.................................❌
Signed URL requests not made over https. SSL is required for secure communications.
Checking CORs configuration of the bucket...............................❌
Your object store does not have a valid CORs configuration, you must allow GET and PUT to Origin: http://10.80.0.206:8080
Checking wandb package version is up to date............................✅
Checking logged metrics, saving and downloading a file..................✅
Checking artifact save and download workflows...........................✅
```

**Comment by thanos-wandb** [comment]
Hi @andrewgark thanks for the update. I tried your code above for the same local version and it worked, which suggests that's something not properly configured with your wandb-local instance. Have you tried running new experiments, would the new Charts not display? It may be related to CORs configuration, and won't render any image (also the avatar icon in first screenshot seems broken). 

Can you please also describe the steps you followed to install wandb-local? do you have any data that you would like to keep or are you fine with starting from a fresh installation?

**Comment by andrewgark** [comment]
Charts consistently do not display in any experiments. Also it appeared that Run Comparer is also disabled with the same error. Maybe the problem is specifically with graphql2? Requests to graphql work just fine.

I think I can start fresh if needed, I have already restarted server a few times with these commands:
```
docker stop wandb-local
docker rmi wandb/local:latest
docker volume rm wandb
pip install wandb --upgrade wandb 
docker run --rm -d -e LOCAL_RESTORE=true -p 8080:8080 --name wandb-local wandb/local
```
Error with custom charts is consistent.

I took these commands from [https://github.com/wandb/wandb/issues/4080](this issue) because I had problem with credentials, by this I mean that default user could not authorize and the first sign-up after server startup was not starting.

**Comment by thanos-wandb** [comment]
Hi @andrewgark sorry for the late reply here. Can you please share your frontend host from the System Settings, does it match the one you're accessing the instance (is it `http` or `https`)? also since you're defining a host can you please replace the last command with the following two?
```
export WANDB_HOST=http://10.80.0.206/
docker run --rm -d -v wandb:/vol -p 8080:8080 -e HOST=$WANDB_HOST --name wandb-local wandb/local
```

**Comment by thanos-wandb** [comment]
Hi @andrewgark I wanted to follow up on this issue, did the above command work for you? thanks

**Comment by thanos-wandb** [comment]
Hi @andrewgark since we haven't heard back from you, I will close this ticket for now. If you still experience any issue, feel free to reopen this and we will be happy to keep investigating.

**Comment by indrasweb** [comment]
I had the same issue. Failed because I had a pretty restrictive firewall setup to block incoming traffic. Some shenanigans with docker means you need to explicitly allow incoming traffic from the actual server you're running the wandb-local deploy from. I.e. add a firewall rule to allow all TCP from the ip of your actual server.

Keywords: dial tcp i/o timeout 500 graphql error loopback

**Comment by guyfreund** [comment]
@thanos-wandb this is happening to me as well, bar plot where the table exists in logs.

**Comment by eladn** [comment]
Happens to me as well. Custom plots won't show. Regular plots are displayed. Similar errors in the console.

**Comment by eladn** [comment]
I also see the following message in the console:
`index.1fa4cb98.js:21851 Experiments were not loaded in time to manage updateHistoryKeyInfo call`
Maybe there's a timeout set somewhere and if there's too-much data the threshold is exceeded?

**Comment by thanos-wandb** [comment]
Hi @guyfreund sorry for late response here, this thread was closed and slipped through the cracks. Do you still have the same issue? Could you please send us a link to your Workspace to investigate further? @eladn was the table uploaded successfully?

**Comment by lucamarini22** [comment]
I found this solution (https://community.wandb.ai/t/no-history-data-in-custom-charts/2087/2) to work for me, but only if the name of the key in the y axis has no spaces in it.

For example, if I choose a key called "steps x" it does not show anything, but if I choose a key called "steps_x" then it works
