### ISSUE TITLE
Process hangs due to race condition in file pusher?

### ISSUE THREAD

**Issue by OrEisenberg** [wandb/wandb#4375]
### Describe the bug

Our team has been using the `wandb` logger in `pytorch-lightning` to monitor trial progress and log artifacts for over a year now and fairly recently (perhaps due to recent upgrades of our `wandb` version?) we've been encountering a bug where upon the completion of a trial, the process hangs, seemingly due to a race condition in file uploading. Our `debug-internal.log` file ends with the following 3 lines: 
```
2022-10-16 08:04:19,712 INFO    SenderThread:615 [sender.py:finish():1315] shutting down sender
2022-10-16 08:04:19,712 INFO    SenderThread:615 [file_pusher.py:finish():168] shutting down file pusher
2022-10-16 08:04:19,713 INFO    SenderThread:615 [file_pusher.py:join():173] waiting for file pusher
```
At face value, this would appear to be a race condition of some kind. Worth noting perhaps is the fact that we are using a `tempfile.TemporaryDirectory` as our `save_dir`. Also worth mentioning is the potential relatedness of #269.

Please let me know if I can provide any more details regarding the nature of the issue. We're currently in the process of decrementing our `wandb` version in the hopes that this will help but currently, this issue is blocking our ability to use `wandb`!

### Environment

WandB version: 0.13.3

OS: ubuntu 18.04

Python version: 3.8.10

**Comment by MBakirWB** [comment]
Hi @OrEisenberg , happy to help here. Can you please provide the following:
- Complete `debug.log` and `debug-internal.log` files for the runs that are hanging
- wandb version you were using prior to upgrading
- Brief description of your experiment and count/size of files you are uploading to your project. 
- For the files logged, are you logging them as artifacts?
Thank you

**Comment by weiyaw** [comment]
I'm facing similar issue as well with similar setup as @OrEisenberg: using the logger in `python_lightning` and running in a Bitnami pytorch container (Debian 11, Python 3.8.14, wandb 0.13.4). I suspect I was being rate-limited, as I was running the container as one of the 12 agents of my sweep. 

I have notice something strange however. The wandb dashboard showed the run `crashed` initially (although the run was actually running fine on my local machine), but after coming back from my dinner break it shows the run was `finished` and everything was uploaded to the dashboard. And this happens not just once, but on almost all the runs in my sweep.

- Brief description of your experiment and count/size of files you are uploading to your project.
An variational inference algorithm with 5000 iterations, logging 4 scalers in every 10 iterations. The 'run' file with a `.wandb` extension was 4.4MB.

- For the files logged, are you logging them as artifacts?
No

- Complete debug.log and debug-internal.log files for the runs that are hanging
[debug-internal.log](https://github.com/wandb/wandb/files/9809574/debug-internal.log)
[debug.log](https://github.com/wandb/wandb/files/9809575/debug.log)

**Comment by OrEisenberg** [comment]
@weiyaw Would you happen to be calling `wandb.finish()` before starting your training by chance (this is recommended by `pytorch_lightning` if I recall correctly)?

**Comment by weiyaw** [comment]
I didn't call `wandb.finish()` in my script, as I'm not using a notebook. Are you referring to this article, under the section 'Let's Train our Model'? https://wandb.ai/manan-goel/MNIST/reports/How-to-Integrate-PyTorch-Lightning-with-Weights-Biases--VmlldzoxNjg1ODQ1

I wasn't using `ray` either. I was running my containers on Kubernetes.

**Comment by weiyaw** [comment]
Here's another run that was stuck in an infinite loop without uploading anything to wandb server after around the 2000th iteration.

I was running 28 sweep agents across 4 VMs (7 each) simultaneously. Each agent was wrapped in a container, and I was using `docker run` repeatedly to run the containers.
 
[debug.log](https://github.com/wandb/wandb/files/9837685/debug.log)
[debug-internal.log](https://github.com/wandb/wandb/files/9837684/debug-internal.log)

**Comment by OrEisenberg** [comment]
We've resolved this issue on our end. It turn out it was just an interaction between `ray` and `pytorch-lightning`. See [this iss](https://github.com/Lightning-AI/lightning/issues/14292).

**Comment by MBakirWB** [comment]
Hi @OrEisenberg , we appreciate you writing in with an update and informing us it's been addressed.
