### ISSUE TITLE
[Feature]: Allow for histograms to be displayed in project view

### ISSUE THREAD

**Issue by ArneTroch99** [wandb/wandb#4380]
### Description

Currently histograms that are logged to WandB are only shown in the run view itself, and not when viewing this run on a project page. Since this makes it difficult to compare runs - one has to click on each run to see it's histograms - it would be nice if the histograms were also showing on the project page.

### Suggested Solution

I understand that it is difficult/impossible to display histograms from multiple runs in one graph. Maybe we can have the histograms only displaying the most recently selected run, or allow for a dropdown menu on the histogram to choose which of the runs that are currently being displayed we want to see on the histogram (this could even be a global setting to allow for a more qualitative user experience).

**Comment by thanos-wandb** [comment]
Hi @ArneTroch99 thank you for this feature, I have now made this request to our engineering team. In the meantime, you may want to check the option of using [Weave](https://docs.wandb.ai/ref/app/features/panels/weave) in the Projects page. If you are logging the data as `wand.log({'data': data})` besides the histograms of this data, you can add a Weave panel in your project page and query these with an expression like: `runs.summary["data"]["values"]`

This will display your data from your runs as table but you can change the render option from the top right gear to Histograms and have these for your selected runs. Please let me know if this helps, and if have any further questions.

**Comment by thanos-wandb** [comment]
Hi @ArneTroch99 I am closing this ticket for now, as the engineering team will follow up with you once this feature is implemented. Please let me know though if you have any further questions regarding the Weave workaround.
