### ISSUE TITLE
How to pass a dictionary as a hyperparameter when doing sweep and assign a name to it [Q]

### ISSUE THREAD

**Issue by cijerezg** [wandb/wandb#4383]
This code can be used to pass hyperparameters for a sweep:
```
parameters_dict = {
    'optimizer': {
        'values': ['adam', 'sgd']
        },
    'fc_layer_size': {
        'values': [128, 256, 512]
        },
    'dropout': {
          'values': [0.3, 0.4, 0.5]
        },
    }
```

Is there a way I can pass a dictionary and assign a name to it that will be displayed in the hyperparameter chart? I know I can pass a dictionary as argument, for example: `arc: {'values': [{'a': 1, 'b': 2}, {'a': 2, 'b': 3}]}`, but it is not displayed in the chart because it isn't one value, e.g., the hyperparameter is the dictionary itself. 

Specifically, what I'd like is  `arc: {'values': [{'first': {'a': 1, 'b': 2}}, {'second': {'a': 2, 'b': 3}}]}`, and then the chart will have `first` and `second`. Is there a way to do something like this?

**Comment by thanos-wandb** [comment]
Hi @cijerezg thank you for writing in! You can have a nested dictionary to configure sweeps as follows: 
```
parameters_dict = {
    'optimizer': {
        'values': ['adam', 'sgd']
        },
    'fc_layer_size': {
        'values': [128, 256, 512]
        },
    'dropout': {
          'values': [0.3, 0.4, 0.5]
        },
    'arc': {
        'values': {
            'first': {'a': 1, 'b': 2}, 
            'second': {'a': 2, 'b': 3}
        }
    }
}
```
This will give you access in the parallel coordinates plots of your parameters such as `arc.values.first.a`, and you can rename them to a simpler name from the chart settings. Would this work for you?

**Comment by cijerezg** [comment]
I get the error: `wandb.errors.CommError: Invalid sweep config; invalid hyperparameter configuration: arc`. I experimented with this before, but I noticed I always need to pass a list to the `values` dictionary.

**Comment by cijerezg** [comment]
A simple workaround solution is to pass a value, e.g., 1 and then inside the code you use 1 as a key for whatever dictionary you want.

**Comment by thanos-wandb** [comment]
Hi @cijerezg thank you for posting what solved it for you! Indeed the previous config with throw the error you reported, and a way to fix this would be to have `values` followed by an array in the innermost layer, and a `parameters` keyword each time you need to nest your hyperparameter layer, as below:
```
parameters_dict = {
  'method': 'grid',
  'name': 'my-sweep',
  'optimizer': {
    'values': ['adam', 'sgd']
  },
  'fc_layer_size': {
    'values': [128, 256, 512]
  },
  'dropout': {
    'values': [0.3, 0.4, 0.5]
  },
  'parameters': {
    'arc': {
      'parameters': {
        'first': {
          'parameters': {
            'a': {'values': [1]},
            'b': {'values': [2]}
          }
        }, 
        'second': {
          'parameters': {
            'a': {'values': [1]},
            'b': {'values': [2]}
          }
        }  
      }            
    }
  }
}
```
I hope this helps! Please let me know if you have any further issues or questions about it.
