### ISSUE TITLE
Sweep stopped when running "openai wandb sync" inside sweep function

### ISSUE THREAD

**Issue by pkkvk** [wandb/wandb#4384]
### Describe the bug

I am trying to find the best hyperparameters for openai fimetuned models using wandb sweep. But when I try to run the "openai wandb sync" inside the function of sweep it is running successfully for the first run. But throwed error and stopped the rest of the runs.

```python
sweep_id = wandb.sweep(sweep=sweep_configuration, project=project)
wandb.agent(sweep_id=sweep_id, function=finetune,count=run_count)

def finetune():
    run = wandb.init()
    with run:
        response = openai.FineTune.create(**args)
        #some code here to wait for the finetune to finish and get the finetune_id
        os.system("openai wandb sync --project {} --id {}".format(str(run.project_name()),finetune_id))
```

```shell
🎉 wandb sync completed successfully
wandb: Waiting for W&B process to finish... (success).
Exception in thread SockSrvRdThr:
Traceback (most recent call last):
  File "C:\Users\KarthikeyanV\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\KarthikeyanV\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\service\server_sock.py", line 112, in run
    shandler(sreq)
  File "C:\Users\KarthikeyanV\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\service\server_sock.py", line 173, in server_record_publish
    iface = self._mux.get_stream(stream_id).interface
  File "C:\Users\KarthikeyanV\AppData\Local\Programs\Python\Python310\lib\site-packages\wandb\sdk\service\streams.py", line 199, in get_stream
    stream = self._streams[stream_id]
KeyError: 'pxjbs8ta'
```

### Environment

WandB version: 0.13.4

OS: Windows 10 Pro 

Python version: 3.10.6

Versions of relevant libraries:
openai==0.23.1

**Comment by MBakirWB** [comment]
Hi @pkkvk , happy to help with you question. Please provide us with

- Expanded description of the experiment you are running that could assist us in reproducing 
- `debug.log` and `debug-internal.log` file of the runs that are crashing

It may be that **openai sync** and the **wandb agent** threads are conflicting when new runs are initiated. As a quick test, could you only call `openai sync` after your sweeps completes as apposed to calling sync within `finetune()`.

**Comment by MBakirWB** [comment]
Hi @pkkvk , following up on this thread. Are you still experiencing issue with **openai sync**?

**Comment by MBakirWB** [comment]
Hi @pkkvk since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by CCRcmcpe** [comment]
Encountering this issue as well. In my case I'm training a model, and wandb.log loss stats, nothing special. It just happens randomly through the training process. Probably a network issue (like http connection unexpectly closed) if you look the stack trace.

**Comment by CCRcmcpe** [comment]
If so, wandb need to improve resiliency to not-perfect network condictions. Random exceptions through a long training process is disasterous.

**Comment by bigheiniu** [comment]
I had the same issue. 
I run two modeling training scripts on a single machine. 
Each script utilizes the same wandb project name. 
Every time, it throws an error at the end of the training.

**Comment by MBakirWB** [comment]
Hi @Joaquin-Gajardo , when using the `WandbLogger` are you also calling `wandb.init()` within your script(s)?

**Comment by linlu-qiu** [comment]
Hi @MBakirWB I ran into the similar issue when logging images (worked fine without it). Also using diffusers like @CCRcmcpe. Any idea what the issue is? 
[debug-internal.log](https://github.com/wandb/wandb/files/10081114/debug-internal.log)
[debug.log](https://github.com/wandb/wandb/files/10081116/debug.log)

**Comment by Joaquin-Gajardo** [comment]
Hi @MBakirWB, thanks for your reply. No I don't call wand.init()

**Comment by MBakirWB** [comment]
Hi @pkkvk @bigheiniu @linlu-qiu @Joaquin-Gajardo @CCRcmcpe . Could you please try executing your experiments with wandb service turned off, `WANDB_DISABLE_SERVICE=True` and report back with an update on new behaviors with your experiments. Thank you.

**Comment by linlu-qiu** [comment]
Hi @MBakirWB, setting `WANDB_DISABLE_SERVICE=True` works for me, and I can still see the log in the wandb UI. Thanks!

**Comment by Joaquin-Gajardo** [comment]
Hi @MBakirWB, I tried setting it as an environmental variable and doesn't change anything, but there is this line in the debug.log of the run:
`2022-12-05 10:47:17,237 WARNING MainThread:463226 [wandb_setup.py:_flush():68] Unknown environment variable: WANDB_DISABLE_SERVICE`

**Comment by MBakirWB** [comment]
Hi @Joaquin-Gajardo , thank you for the update. I will review why  [WANDB_DISABLE_SERVICE](https://github.com/wandb/wandb/blob/928b1a37afb6ab4b447d25efe47ade54409ef977/wandb/env.py#L75) isn't recognized in the logger as an env variable. 

In regards to the new error, this possibly points to a network related error. Could you share the `debug-internal.log` file associated with this run? It should contain more relevant information on what might be happening here. One test you could perform to verify correctness is to run wandb in offline mode , `export WANDB_MODE=offline`

**Comment by DuttaSamarpan** [comment]
Please can this be fixed. I am also facing the same issue on run_finish, when I am using wandb service for Sagemaker based distributed data parallelism. 

```
[1,mpirank:0,algo-1]<stderr>:Exception in thread SockSrvRdThr:
[1,mpirank:0,algo-1]<stderr>:Traceback (most recent call last):
[1,mpirank:0,algo-1]<stderr>:  File "/opt/conda/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[1,mpirank:0,algo-1]<stderr>:    self.run()
[1,mpirank:0,algo-1]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/service/server_sock.py", line 112, in run
[1,mpirank:0,algo-1]<stderr>:    shandler(sreq)
[1,mpirank:0,algo-1]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/service/server_sock.py", line 173, in server_record_publish
[1,mpirank:0,algo-1]<stderr>:    iface = self._mux.get_stream(stream_id).interface
[1,mpirank:0,algo-1]<stderr>:  File "/opt/conda/lib/python3.8/site-packages/wandb/sdk/service/streams.py", line 199, in get_stream
[1,mpirank:0,algo-1]<stderr>:    stream = self._streams[stream_id]
[1,mpirank:0,algo-1]<stderr>:KeyError[1,mpirank:0,algo-1]<stderr>:: '38vn5k4l'
```

**Comment by MBakirWB** [comment]
Hi @DuttaSamarpan , thank you for writing in and providing info. I will continue the conversation in our email exchange and then provide an update here once we've reached a resolution.

**Comment by jeremyjordan** [comment]
I've saw this KeyError recently and it took me a while to figure out what was going on so I figured I'd share that here.

I saw two errors in my tracebacks:

```
Exception in thread SockSrvRdThr:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/site-packages/wandb/sdk/service/server_sock.py", line 112, in run
    shandler(sreq)
  File "/usr/local/lib/python3.10/site-packages/wandb/sdk/service/server_sock.py", line 151, in server_inform_attach
    dict(self._mux._streams[stream_id]._settings),
KeyError: 'vvhc0rkk'
```

```
Traceback (most recent call last):
  ...
  File "/usr/local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 810, in _attach
    response = manager._inform_attach(attach_id=attach_id)
  File "/usr/local/lib/python3.10/site-packages/wandb/sdk/wandb_manager.py", line 181, in _inform_attach
    response = svc_iface._svc_inform_attach(attach_id=attach_id)
  File "/usr/local/lib/python3.10/site-packages/wandb/sdk/service/service_sock.py", line 61, in _svc_inform_attach
    response = self._sock_client.send_and_recv(inform_attach=inform_attach)
  File "/usr/local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 186, in send_and_recv
    raise Exception("No response")
Exception: No response
```

After spending a lot of time understanding the `wandb` codebase and [adding back in this debug thread](https://github.com/wandb/wandb/blob/928b1a37afb6ab4b447d25efe47ade54409ef977/wandb/sdk/service/server_sock.py#L260) I was able to piece together what was going on.

I had a script locally which had been doing some setup before sending code off to be executed on a remote worker. The issue was that I was creating the wandb run object locally (and requiring the wandb service) before sending the run object to a remote machine for execution.

This meant the remote machine only had a couple of the required threads
```
DEBUG: MainThread
DEBUG: SockAcceptThr
DEBUG: DebugThr
```

Whereas most of the threads had already spawned on my local machine.
```
DEBUG: MainThread
DEBUG: SockAcceptThr
DEBUG: DebugThr
DEBUG: SockSrvRdThr
DEBUG: MsgRouterThr
DEBUG: StreamThr
DEBUG: QueueFeederThread
DEBUG: SenderThread
DEBUG: WriterThread
DEBUG: HandlerThread
DEBUG: QueueFeederThread
DEBUG: SockSrvIntRdThr
DEBUG: QueueFeederThread
...
``` 

Changing my code to instantiate the run object on the remote machine resolved my issue, so sharing that here in case it's helpful for anyone else trying to diagnose a `KeyError` on `SockSrvRdThr`.

**Comment by gabriel-vanzandycke** [comment]
Downgrading to `0.12.0` solved the problem for me 😒 (I know it's not a solution but I don't have time to investigate further)
