### ISSUE TITLE
wandb: ERROR Run uokaakm1 errored: ValueError('Expected parameter loc (Tensor of shape (1, 1)) of distribution Normal(loc: tensor([[nan]]), scale: tensor([[nan]])) to satisfy the constraint Real(), but found invalid values:\ntensor([[nan]])').

### ISSUE THREAD

**Issue by tannu945** [wandb/wandb#4390]
How to get over this error ? And how to log multiple tables in same sweep ?

**Comment by ramit-wandb** [comment]
Hi @tannu945,

This does not look like any of the errors that `wandb` throws - Are you sure this error is stemming from `wandb` and is simply not reported by `wandb`?

Thanks,
Ramit
