### ISSUE TITLE
[CLI]: Offline mode not logging config information

### ISSUE THREAD

**Issue by jbuckman** [wandb/wandb#4417]
### Describe the bug

Running wandb in regular, online mode, there is no problem. But on a cluster with no internet on compute nodes, when I run it in offline mode, there is no file generated corresponding to the configuration information of the experiment. This is not a sync issue; even manually inspecting the *local* files on my cluster, it seems that the file that would normally contain the config JSON is not created.

### Environment

WandB version:  0.13.4

OS: CentOS 7

Python version: 3.9.6

**Comment by kptkin** [comment]
@jbuckman note that if you try to sync the run, the file will be added. 
All the data is saved in the wandb file and will populate the config file once you try to sync the run.
