### ISSUE TITLE
[Q] How to use API to upload output.log (stdout / stderr)

### ISSUE THREAD

**Issue by garymm** [wandb/wandb#4418]
Is there a way to use the API to upload output.log (so it shows up as the contents of the `<run>/logs` page)?

**Comment by ramit-wandb** [comment]
Hi @garymm, `wandb` should automatically upload the `output.log` to the `run/logs` page during a run. Is this not your experience? If so, could you share the link to the run?

**Comment by garymm** [comment]
Hi @ramit-wandb,
Sorry for not being clear, but I'm using [the "public API"](https://docs.wandb.ai/ref/python/public-api/api) to programatically create a run like so:

```py
import wandb
api = wandb.Api()
run = api.create_run(...)
```

Once I create that run, how can I upload output.log?

**Comment by ramit-wandb** [comment]
Hi @garymm,

You can use `run.upload_file` in this case to upload your file to the files tab of the run. I'm curious though - why would you want to use `api.create_run` over `wandb.init`? The `Run` object returned from `create_run` is not the same as the one from `init` and is limited in its capabilities, so I'm having a little bit of a hard time understanding your use case here.

**Comment by garymm** [comment]
@ramit-wandb I'm not asking to upload to the files tab, I'm asking to upload to the logs page.
I have some data generated by outside code that I can't modify to use `wandb.init()`. I want to run it and then upload the results to wandb.

**Comment by ramit-wandb** [comment]
@garymm, that is not possible from the `create_run` API. best option here would be to upload to the files tab. This is why I was asking what made you choose the `create_run` API over `init`
