### ISSUE TITLE
[CLI]: Cannot resume run if I specify the name

### ISSUE THREAD

**Issue by samuelstevens** [wandb/wandb#4423]
### Describe the bug

```python
model_checkpoint_exists = True

wandb.init(
    project="project-name",
    resume=model_checkpoint_exists,
    name="groovy-grape-192",
)
```

When I stop experiments, then start them again using the snippet above, the web UI shows two different runs with the same name.
I want to resume the previous run (`resume=True`), but it creates a new run with the same name. If I don't specify the name, I can resume a run.

I would like to resume runs, with a custom name.

### Environment

WandB version:
0.13.4

OS:
Ubuntu

Python version:
3.10.7

**Comment by lesliewandb** [comment]
Hi @samuelstevens, you can do this by putting in the ID variable within your wandb.init() function instead and setting `resume = must`. The run ID can be found on the run's overview page in the Run Path after the project name. This will keep the custom name of your run while still allowing resuming to occur. You can find more information on it[ here](https://weightsandbiases.slack.com/archives/C02MQ49ATEE/p1667412339175239)

**Comment by samuelstevens** [comment]
I don't have a wandb email so I can't access that slack documentation. 

Is there no way to resume a run without specifying the ID? I can write a simple script to generate wandb IDs, but it would be nice to be able to only refer to human-readable names in my experiment config files!

**Comment by lesliewandb** [comment]
Sorry about that, [here's the link to the documentation](https://docs.wandb.ai/guides/sweeps/pause-resume-and-cancel-sweeps#resume-sweeps) I had mentioned previously. We have also stated in our documentation that a sweep ID is 'The pseudo random, unique ID generated by W&B', so there isn't a way to generate your own sweep ID. However, if you would like, I can put in a feature request for this?

**Comment by lesliewandb** [comment]
Just checking back in, would you like me to make a feature request for you?

**Comment by samuelstevens** [comment]
Well I don't want to manually generate sweep IDs, I would like to manually generate run IDs. But from reading other threads, it doesn't seem like that's possible with wandb's architecture (since we still cannot delete IDs and then use them again).

**Comment by ramit-wandb** [comment]
Hey @samuelstevens,

You do not manually need to generate sweep IDs. Internally, we use our run IDs to identify runs, not the run names. If you want to resume a run, you can do so by

```python3
wandb.init(
    project="project-name",
    resume=model_checkpoint_exists,
    id = <ID_OF_groovy-grape-192>
)
```
If you would like - you can specify your own run ID during the first (non-resumed) run of your training (which can be any string you would like, even if you would like it to be human readable) and use that same ID across all your resumed runs. You would need to make sure that each individual ID is unique however, since your data will not be stored otherwise and your run will error out.

**Comment by samuelstevens** [comment]
Right, I'm not interested in sweep ids at all--not sure where that came from. 

I was looking to resume a run with the same name, rather than manually generate a wandb run ID and include that in a config. So I could use whatever string I want for a run ID, that would be easiest for me.

**Comment by ramit-wandb** [comment]
Yup, you can use human readable strings in your run ID as `wandb.init(project="project_name", id = ...)` on any run that is starting up for the first time. The only caveat is that you must make sure the ID for each run is unique over the project - any conflicting run IDs will lead to runs crashing when `init` is called (or if you are running your code offline - when `sync` is called).

I'm going to close this issue for now, but if you need further assistance here feel free to reopen!
