### ISSUE TITLE
[CLI]: canno't sync my runs

### ISSUE THREAD

**Issue by de-gozaru** [wandb/wandb#4424]
### Describe the bug

Hi, 
I was syncing my experiment normally with the command `wandb sync name`. This worked for tens of experiments.
Suddenly, an hour ago, this command stopped working, and I'm getting the following error:
```bash
wandb sync experiment_xxx
wandb: Network error (ReadTimeout), entering retry loop.
wandb: ERROR Error while calling W&B API: internal database error (<Response [500]>)
```
I do not have a network connection problem. In fact, I tried to sync from a different computer and it's not working.

I checked my account, everything seems ok. Mentioning the project or the experiment id in the command `--id` does not help either.

How can I address this issue?

Thank you in advance!

### Environment

WandB version: 0.12.10

OS: Ubuntu 

Python version: 3.9

Versions of relevant libraries:

**Comment by jasonkyuyim** [comment]
I am also running into this same issue. Everything was working fine until about na hour ago.

**Comment by alexeyfsk** [comment]
I am experiencing this as well. There seems to be some downtime on W&B's end though the status page doesn't reflect this https://status.wandb.com/history

**Comment by isaacmg** [comment]
Yes I'm having this same issue with all my Wandb code. Doesn't matter my environment.

**Comment by ramit-wandb** [comment]
Hi everyone,

Yes we were experiencing an elevated error rate earlier today. This should be resolved now, however. Could you try syncing your runs again and let us know if you run into any issues?

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
Hi, since we have not heard back we are closing this issue. In case you still see errors related to this, please let us know.

**Comment by ramit-wandb** [comment]
Hi @jameschapman19,

Could you help explain the behavior you notice and share any error messages you see? We'll be able to continue investigating from there.

Thanks,
Ramit
