### ISSUE TITLE
[Feature]: Scatter plot with parity line

### ISSUE THREAD

**Issue by janosh** [wandb/wandb#4437]
### Description

Is there a way to add a parity line (`x = y`) to a scatter plot? For regression models, this is a great way to visualize prediction quality.

**Current `wandb.plot.scatter()` output**

![Screenshot 2022-11-03 at 14 57 59](https://user-images.githubusercontent.com/30958850/199842395-1f8b0610-c475-4975-8927-4aef36addcca.png)

**Desired**

![density-scatter](https://user-images.githubusercontent.com/30958850/199842412-522138e8-e0b3-44e3-bd5f-2f046b81748b.svg)

### Suggested Solution

Either add a kwarg to `wandb.plot.scatter(parity_line=True)` or implement a more flexible API that allows adding arbitrary lines across a plot like matplotlib's [`ax.axline`](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.axline.html) which draws a line though any point `(x, y)` with given `slope`.

**Comment by thanos-wandb** [comment]
Hi @janosh thank you for writing in about this feature request. I just wanted to gather some information on the use case before filing this request and refer to couple of workarounds. 

One option to do so would be from the UI, if in you add a `Scatter plot` panel in your Workspace. Then if you edit (✏️ icon) this Chart and go to `Annotations` tab, you can add a `Linear Regression` line, as in the attached screenshot. 
<img width="1375" alt="Screenshot 2022-11-07 at 11 08 27" src="https://user-images.githubusercontent.com/108423944/200298628-daabdd8d-b282-4d75-b0d2-e08204464702.png">

Alternatively, you could log a [Custom chart](https://docs.wandb.ai/ref/app/features/custom-charts) using a customised [Vega spec](https://vega.github.io/editor/#/examples/vega-lite/layer_point_line_regression) or a [matplotlib/plotly](https://docs.wandb.ai/guides/track/log/plots#matplotlib-and-plotly-plots) figure.

Would any of these options work for you?

**Comment by janosh** [comment]
@thanos-wandb yes, I could resort to log a `matplotlib` figure with an `axline`. That has other drawbacks though, e.g. no hover tooltip to see which points correspond to which samples. Plotly plots provide that but they scale poorly to ~100k points and slow down the UI a lot.

Regression line isn't quite what I'm after and I couldn't where to enable it either. When I click the edit button on a plot, this is what I get:

![Screenshot 2022-11-07 at 13 19 40](https://user-images.githubusercontent.com/30958850/200418331-f19892b7-5281-4e7b-9f9f-c1fbe267d188.png)

Where do I find that Annotations tab in your screenshot?

**Comment by thanos-wandb** [comment]
Hi @janosh sorry for the late reply here, the screenshot I shared above can be found when you add a `Scatter plot` in the UI. However, when you log it using wandb.plot.scatter as you do, this will create a Custom chart with can be modified using the Vega specs. 

Therefore, in order to be consistent with your workflow, it would be best that you adapt the Vega spec in order to bring the `parity` and/or `regression` line. The regression line can be done if you click Edit next to Scatter plot (from the menu in your screenshot above) and paste the following Vega spec:

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A simple scatter plot",
  "data": {"name": "wandb"},
    "transform": [
    {
      "calculate": "if('${field:groupKeys}' === ''  || datum['${field:groupKeys}'] === '', false, true)",
      "as": "grouped"
    },
    {
      "calculate": "if('${field:groupKeys}' === ''  || datum['${field:groupKeys}'] === '', datum.name, datum['${field:groupKeys}'])",
      "as": "newGroupKeys"
    },
    {
      "calculate": "if('${field:groupKeys}' === ''  || datum['${field:groupKeys}'] === '', datum.color, datum['${field:groupKeys}'])",
      "as": "color"
    },
  {
    "joinaggregate": [
      {
      "op" : "average",
      "field": "${field:y}",
      "as": "groupedY"
      }
    ],
    "groupby": ["${field:x}", "newGroupKeys", "color", "grouped"]
  }
],
  "title": "${string:title}",
  "layer": [
      {
      "transform": [
        {"filter": "datum.grouped == false"}
      ],
      "mark": {"type": "circle", "tooltip": {"content": "data"}},
      "selection": {
            "grid1": {
              "type": "interval",
              "bind": "scales"
            }
          },
      "encoding": {
        "x": {"field": "${field:x}", "type": "quantitative"},
        "y": {"field": "${field:y}", "type": "quantitative", "axis": {"title": false}},
        "color": {
          "type": "nominal",
          "field": "name",
          "scale": {"range": {"field": "color"}},
          "legend": {"title": null}
        }
      }
    },
    {
      "transform": [
        {"filter": "datum.grouped == true"}
      ],
      "mark": {"type": "circle", "tooltip": {"content": "data"}},
      "selection": {
            "grid0": {
              "type": "interval",
              "bind": "scales"
            }
          },
      "encoding": {
        "x": {"field": "${field:x}", "type": "quantitative"},
        "y": {"field": "groupedY", "type": "quantitative", "axis": {"title": "${field:y}"}},
        "color": {
          "field": "newGroupKeys",
          "type": "nominal",
          "scale": {"range": "category"},
          "legend": {"title": null}
        }
      }
    },
    {
      "mark":{
        "type":"line",
        "color":"purple"
      },
      "transform":[{
        "regression": "${field:y}",
        "on": "${field:x}"
      }],
      "encoding": {
        "y":{
          "field":"${field:y}",
          "type":"quantitative"
        },
        "x":{
          "field":"${field:x}",
          "type":"quantitative"
        }
      }
    }
  ],
  "resolve": {"scale": {"color": "independent"}}
}
```
Then you will need to do `Detach` > `Save as preset` > `scatter-regression`.

Once this Vega spec has been created, you can then use it when you're logging new data such as:
```

# Create a table with the columns to plot
table = wandb.Table(data=data, columns=["step", "value"])

# Map from the table's columns to the chart's fields
fields = {"x": "step",
          "y": "value"}

# Use the table to populate the new custom chart preset
# To use your own saved chart preset, change the vega_spec_name
my_custom_chart = wandb.plot_table(vega_spec_name="ENTITY/scatter-regression",
              data_table=table,
              fields=fields,
              )

# Log the plot to have it show up in the UI
wandb.log({"custom_chart": my_custom_chart})
```

If you wanted to have just the parity line `y=x` you could replace the prefinal field from above spec with the following one:
```
      "encoding": {
        "y":{
          "field":"${field:x}",
          "type":"quantitative"
        },
```

I hope this helps! Please let me know if you tried this and if it worked for you or you run into any issue. I have also created an internal ticket for the engineering team according to your initial request as it would be indeed more convenient to have only one argument to generate this line.

**Comment by janosh** [comment]
Thanks for the detailed guidance! 👍  Works great! This is what I got pasting your snippet into the chart definition of my plot:

![Screenshot 2022-11-15 at 21 22 39](https://user-images.githubusercontent.com/30958850/202090989-ba784eac-b59f-4408-b7b7-76ca30ba59e7.png)

Haven't tried logging this plot yet from a new run but will tomorrow.

Just a nitpick at this point but is there a way to have the line extend to the edge of the plot, be dashed and in the background (behind the scatter points)?

<details>
<summary>JSON snippet</summary>

```json5
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A simple scatter plot",
  "data": {
    "name": "wandb"
  },
  "transform": [
    {
      "calculate": "if('${field:groupKeys}' === ''  || datum['${field:groupKeys}'] === '', false, true)",
      "as": "grouped"
    },
    {
      "calculate": "if('${field:groupKeys}' === ''  || datum['${field:groupKeys}'] === '', datum.name, datum['${field:groupKeys}'])",
      "as": "newGroupKeys"
    },
    {
      "calculate": "if('${field:groupKeys}' === ''  || datum['${field:groupKeys}'] === '', datum.color, datum['${field:groupKeys}'])",
      "as": "color"
    },
    {
      "joinaggregate": [
        {
          "op": "average",
          "field": "${field:y}",
          "as": "groupedY"
        }
      ],
      "groupby": [
        "${field:x}",
        "newGroupKeys",
        "color",
        "grouped"
      ]
    }
  ],
  "title": "${string:title}",
  "layer": [
    {
      "transform": [
        {
          "filter": "datum.grouped == false"
        }
      ],
      "mark": {
        "type": "circle",
        "tooltip": {
          "content": "data"
        }
      },
      "selection": {
        "grid1": {
          "type": "interval",
          "bind": "scales"
        }
      },
      "encoding": {
        "x": {
          "field": "${field:x}",
          "type": "quantitative"
        },
        "y": {
          "field": "${field:y}",
          "type": "quantitative",
          "axis": {
            "title": false
          }
        },
        "color": {
          "type": "nominal",
          "field": "name",
          "scale": {
            "range": {
              "field": "color"
            }
          },
          "legend": {
            "title": null
          }
        }
      }
    },
    {
      "transform": [
        {
          "filter": "datum.grouped == true"
        }
      ],
      "mark": {
        "type": "circle",
        "tooltip": {
          "content": "data"
        }
      },
      "selection": {
        "grid0": {
          "type": "interval",
          "bind": "scales"
        }
      },
      "encoding": {
        "x": {
          "field": "${field:x}",
          "type": "quantitative"
        },
        "y": {
          "field": "groupedY",
          "type": "quantitative",
          "axis": {
            "title": "${field:y}"
          }
        },
        "color": {
          "field": "newGroupKeys",
          "type": "nominal",
          "scale": {
            "range": "category"
          },
          "legend": {
            "title": null
          }
        }
      }
    },
    {
      "mark": {
        "type": "line",
        "color": "purple"
      },
      "transform": [
        {
          "regression": "${field:y}",
          "on": "${field:x}"
        }
      ],
      "encoding": {
        "y": {
          "field": "${field:x}",
          "type": "quantitative"
        },
        "x": {
          "field": "${field:x}",
          "type": "quantitative"
        }
      }
    }
  ],
  "resolve": {
    "scale": {
      "color": "independent"
    }
  }
}
```
</details>

**Comment by janosh** [comment]
Update: Logging from new runs works as expected. 🎉 

Any advice on how to extend the line all the way to bottom left and top right corners of the plot area?

**Comment by thanos-wandb** [comment]
Hi @janosh thanks for the update, happy to hear that! And sorry for the late response to the previous question, the concept of the previous spec was to use the bounds of `x` variable, therefore if you wanted to extent this line you will need to create a different spec that adds a line. 

You could either hard code the line bounds as below or these values can be exposed as two new fields `minP`, `maxP` which you can provide from your Python script or the UI. To expose the fields you could do something like:
```
          {"x": '${field:minP}', "y": '${field:maxP}'},
          {"x": '${field:minP}', "y": '${field:maxP}'}
```

<details>
<summary>Please see here the new Vega spec</summary>

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A simple scatter plot",
  "data": {"name": "wandb"},
    "transform": [
    {
      "calculate": "if('${field:groupKeys}' === ''  || datum['${field:groupKeys}'] === '', false, true)",
      "as": "grouped"
    },
    {
      "calculate": "if('${field:groupKeys}' === ''  || datum['${field:groupKeys}'] === '', datum.name, datum['${field:groupKeys}'])",
      "as": "newGroupKeys"
    },
    {
      "calculate": "if('${field:groupKeys}' === ''  || datum['${field:groupKeys}'] === '', datum.color, datum['${field:groupKeys}'])",
      "as": "color"
    },
  {
    "joinaggregate": [
      {
      "op" : "average",
      "field": "${field:y}",
      "as": "groupedY"
      }
    ],
    "groupby": ["${field:x}", "newGroupKeys", "color", "grouped"]
  }
],
  "title": "${string:title}",
  "layer": [
      {
      "transform": [
        {"filter": "datum.grouped == false"}
      ],
      "mark": {"type": "circle", "tooltip": {"content": "data"}},
      "selection": {
            "grid1": {
              "type": "interval",
              "bind": "scales"
            }
          },
      "encoding": {
        "x": {"field": "${field:x}", "type": "quantitative"},
        "y": {"field": "${field:y}", "type": "quantitative", "axis": {"title": false}},
        "color": {
          "type": "nominal",
          "field": "name",
          "scale": {"range": {"field": "color"}},
          "legend": {"title": null}
        }
      }
    },
    {
      "transform": [
        {"filter": "datum.grouped == true"}
      ],
      "mark": {"type": "circle", "tooltip": {"content": "data"}},
      "selection": {
            "grid0": {
              "type": "interval",
              "bind": "scales"
            }
          },
      "encoding": {
        "x": {"field": "${field:x}", "type": "quantitative"},
        "y": {"field": "groupedY", "type": "quantitative", "axis": {"title": "${field:y}"}},
        "color": {
          "field": "newGroupKeys",
          "type": "nominal",
          "scale": {"range": "category"},
          "legend": {"title": null}
        }
      }
    },
    {
      "data": {
        "values": [
          {"x": 0, "y": 0},
          {"x": 100, "y": 100}
        ]
      },
      "mark": {
        "type": "line",
        "opacity": 0.5,
        "color":"purple",
        "size": 1,
        "strokeDash": [10,2]
      },
      "encoding": {
        "x": {"type": "quantitative", "field": "x"},
        "y": {"type": "quantitative", "field": "y"}
      }
    }
  ],
  "resolve": {"scale": {"color": "independent"}}
}
```

</details>

I have also added some new configurations to control the size, opacity and stroke's style as you requested previously. I hope this helps, please let me know if that worked for you!

**Comment by janosh** [comment]
Perfect, thanks a lot! Hard-coding the line bounds doesn't work in my case due to changing data. How would I pass those values from a Python script to the plot? Like this?

```py
scatter_plot = wandb.plot_table(
    vega_spec_name="<entity>/scatter-parity",
    data_table=table,
    fields=dict(minP=table.data.min(), maxP=table.data.max(),
)
```

**Comment by thanos-wandb** [comment]
Hi @janosh thanks for the update, indeed that would be the way to fill in the min and max values from your Python script, provided in your Vega spec you have created these fields as above. Did you try passing data from your script, and is it working for you?

**Comment by janosh** [comment]
Yes, passing data from script to UI is working. Thanks for all your help here! 👍

**Comment by thanos-wandb** [comment]
Perfect! Thanks @janosh for confirming, glad to be of help. I will close the ticket for now, but please feel free to reopen it if you have any further related questions or issues.
