### ISSUE TITLE
[App]: wandb hover: Waiting for W&B process to finish... (success).

### ISSUE THREAD

**Issue by PussInCode** [wandb/wandb#4441]
### Current Behavior

wandb is stuck, it's always been like this
wandb: Waiting for W&B process to finish... (success).
![image](https://user-images.githubusercontent.com/38970840/199930156-b50976ed-08f9-4c0a-ae67-a6b13cdb8c43.png)
![image](https://user-images.githubusercontent.com/38970840/199930263-ba42a0c4-68a9-4377-84c5-967cf6da8bec.png)

### Environment

OS:

Browsers:

Version:

**Comment by ramit-wandb** [comment]
Hi @PussInCode ,

Could you share the `debug.log` and `debug-internal.log` files associated to an affected run? They should be present on your machine in the `wandb` folder relative to your working directory and should contain some more information about these runs so that we can dig in deeper.

**Comment by ramit-wandb** [comment]
​Hi @PussInCode, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
​

**Comment by Hal9999** [comment]
Hi, I'm experiencing the same issue.


I'm running an hyperparameters sweep and after each run (made of 10 epochs) the process stucks on "wandb: Waiting for W&B process to finish... (success)."

I noticed that it is just very very slow at uploading data to the cloud dashboard, like 15-20 minute per run, much than it takes for the train.

This happens on my local computer using pure python and Jupiter notebook but also using wandb command line and config.yaml.

The same thing doesn't happen when I use Google Colab.

**Comment by Luca1920342** [comment]
I also have the same issue, I init the run with
`run = wandb.init(project=PROJECT, sync_tensorboard=True, job_type='training')`

and end with 
`run.finish()`

but it doesn't end and outputs
`Waiting for W&B process to finish... (success).`
while still running.

I'll upload my debug.log and debug-internal.log (the latter is updating while finish() is running)

[debug.log](https://github.com/wandb/wandb/files/10335836/debug.log)
[debug-internal.log](https://github.com/wandb/wandb/files/10335840/debug-internal.log)

**Comment by 2catycm** [comment]
same issue occurs

**Comment by shicheng0829** [comment]
same issue

**Comment by ChristopherMarais** [comment]
Same issue

**Comment by lkbarth** [comment]
Same issue

**Comment by justchenhao** [comment]
Same issue

**Comment by alvinshao0313** [comment]
same issue

**Comment by etasnadi** [comment]
The same issue here.

**Comment by etasnadi** [comment]
The same issue here.

It seems that the tfevents file can not be sent to the server and the client retries 2 more times but waits 15 minutes before between them.

**Comment by hxb727628998** [comment]
same issue

**Comment by Akramz** [comment]
Same issue.

**Comment by tangbao** [comment]
same issue

**Comment by RoHei** [comment]
same issue

**Comment by adaruna3** [comment]
same issue...

**Comment by mkotyushev** [comment]
I have encountered the same issue on one of my agent machines I use to run sweeps. 

It happens not after every sweep end so workaround could be to kill all the hung processes manually. I have executed `ps aux | grep python` and found following two processes:
- `python -c from joblib.externals.loky.backend.resource_tracker import main; main(63, False)`
- `python -c from multiprocessing.resource_tracker import main;main(70)`

I have killed them using `pkill -9 python` (although it is better to use `kill -9 <PID>` for each of them) and the next sweep started without any issues.

**Comment by nicofirst1** [comment]
Same issue here too. It would be nice to have a verbose output to see the progress of wandb syncing.

**Comment by liqing-ustc** [comment]
Same issue here too.

**Comment by TYTTYTTYT** [comment]
Same issue here too.

**Comment by yahah100** [comment]
Same issue here too.

**Comment by crj1998** [comment]
Same issue here too.

**Comment by bhatiaabhinav** [comment]
Same issue. Why is this closed?

**Comment by MichaelGaliciaZ** [comment]
I have the same issue. In fact wandb upload tracked information but no avoid to finish my script

**Comment by liuqi8827** [comment]
Same issue.

**Comment by WangX0111** [comment]
same issue

**Comment by HelloWorldLTY** [comment]
Same issue. Even the offline mode cannot work.

**Comment by chengengliu** [comment]
I have a sequence of running trainings and this just hangs the program there, though the correct stats were uploaded to wandb. After checking the debug-internal.log, I have found this: `
2023-12-08 17:18:17,913 INFO    HandlerThread:2521165 [system_monitor.py:probe():211] Finished collecting system info
2023-12-08 17:18:17,913 INFO    HandlerThread:2521165 [system_monitor.py:probe():214] Publishing system info
2023-12-08 17:18:17,913 DEBUG   HandlerThread:2521165 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-12-08 17:18:17,916 DEBUG   HandlerThread:2521165 [system_info.py:_save_pip():67] Saving pip packages done
2023-12-08 17:18:17,916 DEBUG   HandlerThread:2521165 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-12-08 17:18:17,924 ERROR   HandlerThread:2521165 [system_info.py:_save_conda():85] Error saving conda packages: [Errno 2] No such file or directory: 'conda'
` And I also checked other logs previously, they don't have such error; maybe this is what blocks the wandb.finish()?

**Comment by xingzhongyu** [comment]
same issue

**Comment by HelloWorldLTY** [comment]
I somehow addressed this problem by changing the order of wandb close and run close:

```
run.finish()
wandb.finish()
```
