### ISSUE TITLE
Incorrect parameter name in docstring for `artifact.add_dir()`

### ISSUE THREAD

**Issue by noobmldude** [wandb/wandb#4443]
The docstring shows an example with parameter name `path`, 
https://github.com/wandb/wandb/blob/097ef2ea6d033d2f45f667e006e9b4df3793c130/wandb/sdk/interface/artifacts.py#L449

however the function expects parameter `name`
https://github.com/wandb/wandb/blob/097ef2ea6d033d2f45f667e006e9b4df3793c130/wandb/sdk/interface/artifacts.py#L432

**Comment by thanos-wandb** [comment]
Hi @noobmldude thanks so much for spotting and reporting this. The correct usage is indeed `name` and not `path`, I created a ticket for the team and we will update the `docstring` accordingly. Thanks!

**Comment by ngrayluna** [comment]
PR was created. Waiting for review.
