### ISSUE TITLE
[Feature]: Add wandb/.gitignore

### ISSUE THREAD

**Issue by Freed-Wu** [wandb/wandb#4444]
### Description

Add wandb/.gitignore which content is `*` to ignore all files in wandb to be tracked by git.

### Suggested Solution

As above.

### Additional Context

Should be a simple feature.

**Comment by MBakirWB** [comment]
Hi @Freed-Wu, thank you for writing in and we are happy to help. Could you please expand on this specific request in terms of why you are asking for it and the impact it would have on your workflow. Thank you

**Comment by Freed-Wu** [comment]
A gitignore can let git ignore `wandb/*`. If we don't add it, sometimes user will `git add -A` to add `wandb/*`. It is incorrect.

**Comment by MBakirWB** [comment]
Hi @Freed-Wu , thank you for the clarification. I will submit the feature request and keep you update once I've received feedback from the team.
