### ISSUE TITLE
[Feature]: Fasten cli

### ISSUE THREAD

**Issue by Freed-Wu** [wandb/wandb#4446]
### Description

`wandb --help` is too slow. Like <https://github.com/jazzband/pip-tools/issues/1703#issuecomment-1302524416>, `wandb --help` import the full wandb.  if user just want to take a look at the usage of cli, that is `wandb --help`, it shouldn't import full it. Why not divide the argument parse part to a separate file `__maim__.py` to fasten `wandb --help`?

```sh
❯ time wandb \--help
Usage: wandb [OPTIONS] COMMAND [ARGS]...

Options:
  --version  Show the version and exit.
  --help     Show this message and exit.

Commands:
  agent         Run the W&B agent
  artifact      Commands for interacting with artifacts
  controller    Run the W&B local sweep controller
  disabled      Disable W&B.
  docker        W&B docker lets you run your code in a docker image...
  docker-run    Simple wrapper for `docker run` which adds WANDB_API_KEY...
  enabled       Enable W&B.
  init          Configure a directory with Weights & Biases
  launch        Launch or queue a job from a uri (Experimental).
  launch-agent  Run a W&B launch agent (Experimental)
  login         Login to Weights & Biases
  offline       Disable W&B sync
  online        Enable W&B sync
  pull          Pull files from Weights & Biases
  restore       Restore code, config and docker state for a run
  scheduler     Run a W&B launch sweep scheduler (Experimental)
  server        Commands for operating a local W&B server
  status        Show configuration settings
  sweep         Create a sweep
  sync          Upload an offline training directory to W&B
  verify        Verify your local instance
wandb \--help  0.75s user 0.10s system 99% cpu 0.859 total
```

### Suggested Solution

Divide argparse part to `__main__.py`.

**Comment by thanos-wandb** [comment]
Hi @Freed-Wu thank you for this enhancement suggestion. From your `time` output above, it seems to take about `0.75s` to load, have you also noticed even slower loading times? would there be any additional use case to have the `argparse` part in `__main__.py`?

**Comment by thanos-wandb** [comment]
Hi @Freed-Wu just an update, I have created an internal ticket for this feature request, and we will reach out to you when there are any updated. I am closing this ticket for now, thanks for the suggestion!
