### ISSUE TITLE
[App]: Stuck at showing only 4 groups and new groups all have same colour

### ISSUE THREAD

**Issue by LindaSt** [wandb/wandb#4457]
### Current Behavior

One of my projects only shows 4 groups in the plots and not more. It works ok in all my other projects. I've tried to reset the workspace, visualize and un-visualize. Nothing helped. Additionally, the newer runs all have the same colour. I only have 9 groups in the project.

### Expected Behavior

The max number of displayed groups is as selected in drop down and not stuck at 4. Additional runs get new colours.

### Environment

OS: Mac

Browsers: Firefox

**Comment by nate-wandb** [comment]
Hi @LindaSt, could you possibly share a link to the workspace where you are seeing this and I can take a look? 

Thank you,
Nate

**Comment by LindaSt** [comment]
Sure it's here: https://wandb.ai/lindast/BTS-cv10?workspace=user-lindast

**Comment by LindaSt** [comment]
Hi! I think I know what the problem is (but not how to fix it). The reason is that the displayed runs are capped at 100, and it just only shows the last 100 ones, regardless of the group. I'm using the groups for cross-validation and multi-running, so I have quite a high number of runs. 

Is there also a way to change the setting on all panels at the same time (increasing the number of runs and groups displayed, etc.)?

**Comment by nate-wandb** [comment]
I see. Yes, I agree about the cause. If you hide runs with the eye they will not be counted in the 150 that are capped so if there is a way to hide runs that you don't want to visualize so that the UI will pick 150 runs from the groups you are trying to look at that may work as a workaround.

Let me know if that helps.

**Comment by nate-wandb** [comment]
Hi @LindaSt, I wanted to follow up and see if this helped solved the issue?

Thank you,
Nate
