### ISSUE TITLE
[CLI]: `RunDisabled` object is not pickle loadable

### ISSUE THREAD

**Issue by dakinggg** [wandb/wandb#4458]
### Describe the bug

The `RunDisabled` object cannot be dumped and then loaded via pickle. This is because it overrides `__getstate__` (https://github.com/wandb/wandb/blob/63941eaf98c6b34538a508cef108da5114ae10ce/wandb/sdk/lib/disabled.py#L174), but not `__setstate__`. The result of this is that if you disable wandb, but store something like `wandb.run.project` in a pickle file, the pickle file will save just fine, but then is not loadable. Unless there is some reason that `__setstate__` is not overridden, I'm guessing it is just an oversight?

```python
In [1]: from wandb.sdk.lib.disabled import RunDisabled

In [2]: rd = RunDisabled()

In [3]: import pickle

In [4]: pickle.loads(pickle.dumps(rd))
```

```shell
---------------------------------------------------------------------------
UnpicklingError                           Traceback (most recent call last)
<ipython-input-4-d360a29e4f94> in <cell line: 1>()
----> 1 pickle.loads(pickle.dumps(rd))

UnpicklingError: state is not a dictionary
```

### Environment

WandB version: 0.13.5

OS: macOS Monterey, 12.6

Python version: 3.9.13

Versions of relevant libraries:

**Comment by dakinggg** [comment]
So, we write wandb info (e.g. project, run name) to our checkpoints (at https://github.com/mosaicml/composer), so that we can potentially autoresume a training run. Writing wandb project results in a corrupted checkpoint because the `RunDisabled` object can't be loaded via pickle. The workaround is to just check if wandb is disabled before writing it in the checkpoint, not terrible, and logically correct anyway, since there is no wandb info to resume to if wandb was disabled when the run was run.

**Comment by nate-wandb** [comment]
@dakinggg, thank you for the context! This has been submitted to our engineering team and we can follow up once this has been reviewed.

**Comment by kptkin** [comment]
This should be resolved as we removed the `RunDisabled` object here #8037
