### ISSUE TITLE
‘wandb_api_key’ not found[Q]

### ISSUE THREAD

**Issue by Logicino** [wandb/wandb#4476]
Hello, I'm running this project:
https://github.com/ws-choi/Conditioned-Source-Separation-LaSAFT
which need to use HYDRA training and wandb key. I followed the instructions, registered a wandb account and got an API key. I copied the API key to the terminal as required. However when I take training, it report this error:
```
Global seed set to 2020
wandb: Currently logged in as: kinologic. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.13.5
wandb: Run data is saved locally in ./wandb/run-20221110_150236-293r0nox
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run grateful-bee-6
wandb: ⭐️ View project at https://wandb.ai/kinologic/lasaft
wandb: 🚀 View run at https://wandb.ai/kinologic/lasaft/runs/293r0nox
Error executing job with overrides: ['dataset.musdb_root=dev/musdb/musdb18hq/']
Traceback (most recent call last):
  File "train.py", line 24, in hydra_entry
    main(cfg)
  File "train.py", line 19, in main
    trainer.train(cfg)
  File "/home/usrname/Conditioned-Source-Separation-LaSAFT/lasaft/source_separation/conditioned/scripts/trainer.py", line 45, in train
    wandb_login(key=cfg['wandb_api_key'])
omegaconf.errors.InterpolationResolutionError: KeyError raised while resolving interpolation: "Environment variable 'wandb_api_key' not found"
    full_key: wandb_api_key
    object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: Synced grateful-bee-6: https://wandb.ai/kinologic/lasaft/runs/293r0nox
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20221110_150236-293r0nox/logs
```
What should I do? Thank you.

**Comment by thanos-wandb** [comment]
Hi @Logicino thank you for reporting this. I checked the repo you're using and there is a `wandb_api_key` environment variable set in a `.env` file defined [here](https://github.com/ws-choi/Conditioned-Source-Separation-LaSAFT/blob/546f02f8880fcfbd6aab6508c8162dccc1aa79e4/.env.sample). You will need to copy your API from [https://wandb.ai/authorize](https://wandb.ai/authorize) and paste it to this file. Would this work for you?

**Comment by thanos-wandb** [comment]
Hi @Logicino just checking in here to see if the above resolved this issue? thanks!

**Comment by Logicino** [comment]
> Hi @Logicino just checking in here to see if the above resolved this issue? thanks!

Thank you! Sorry for my server's broken these days and I finally tried it success today :) Thank you for your reply!

**Comment by thanos-wandb** [comment]
Thanks @Logicino for the confirmation, glad it now works! I am closing the ticket for now, feel free to reach out again if you run into any other issues.
