### ISSUE TITLE
[Q] How to resume a run from specific step?

### ISSUE THREAD

**Issue by wztdream** [wandb/wandb#4482]
Hi,
As mentioned in these #2236 #2234 issues, we need wandb to resume a run from specific step. 

We usually did not save checkpoint each step, so when we resume a run, the checkpoint is usually with old step compared with more frequent logs like "loss". We need to tell wandb to resume from a specific step in order to make the logging consistent.

The workaround by setting the step value in #2234 seems did not work:

```
wandb.log(dict, step=iteration)
```

I found the old value are not updated.

So, any update on this problem?

**Comment by ramit-wandb** [comment]
Hi @wztdream,

The step needs to monotonically increase with each call to `log` in a run, so currently it is not possible to add a previous step. This is a feature which we plan to implement in the future. Our team will reply to this thread once this has been implemented.

**Comment by fac2003** [comment]
This is critical for those who need to resume training from saved checkpoints.

**Comment by Ubadub** [comment]
@ramit-wandb Has there been any update on implementing this functionality?

**Comment by YudiXie** [comment]
@ramit-wandb Thanks for the response; this is a much-needed feature in my use case. I really look forward to any updates on this.

**Comment by hywang66** [comment]
Any updates? This is indeed a very important feature

**Comment by kptkin** [comment]
closing this in favor of  #1395 as it a duplicate
