### ISSUE TITLE
[Feature]:  please add data type for 3D voxel visualization like https://github.com/K3D-tools/K3D-jupyter

### ISSUE THREAD

**Issue by dirtycomputer** [wandb/wandb#4483]
### Description

please add data type for 3D voxel visualization like https://github.com/K3D-tools/K3D-jupyter
3D voxel data type (not 3D point data type) are not included in current supported data types
[example1](https://github.com/K3D-tools/K3D-jupyter/blob/main/imgs/vr.gif)
[example2](https://github.com/K3D-tools/K3D-jupyter/blob/main/imgs/vr.gif)

### Suggested Solution

add features that support visualize 3D voxel data (move, change view, change intensity, 
compare predictions and ground truth in one 3d voxel object ➡️https://k3d-jupyter.org/gallery/showcase/segmentation.html)

**Comment by dirtycomputer** [comment]
more example please refer to https://k3d-jupyter.org/gallery/index.html

**Comment by thanos-wandb** [comment]
Hi @dirtycomputer I wanted to follow up with you regarding this request, would this work for you and do you have any further questions regarding this that I could help with?

**Comment by thanos-wandb** [comment]
Hi @dirtycomputer since we haven't heard back from you, I will close this ticket for now. If the above won't work for you, please let us know here and we will keep investigating.
