### ISSUE TITLE
[Feature]: Grouped Scatter Plot

### ISSUE THREAD

**Issue by abwilf** [wandb/wandb#4485]
### Description

Hi there! I have the following use case: for some groups, I'd like to visualize a scatter plot of their performance.  e.g. below (sorry for the poor quality).  

![IMG_1319 Large](https://user-images.githubusercontent.com/17789925/201725128-4d56f1f8-bdd4-451b-89ad-eb3165f5f531.jpeg)

In w&b right now, I can "group by", but when I go to scatter plot where it looks like this ungrouped,
![image](https://user-images.githubusercontent.com/17789925/201725388-e37e6c92-fa5a-4751-afbb-3ab4cd66c2bc.png)

It then looks like this when grouped.
![image](https://user-images.githubusercontent.com/17789925/201725561-2a3f7e50-3722-4f87-8067-ac7389a0809d.png)

Not sure if this is a bug or a feature. Please feel free to allocate accordingly!

Thank you for an amazing tool – I'm a big fan and proponent.

### Suggested Solution

Grouping by should have the same functionality as elsewhere (e.g. in line plots): it should preserve the different runs across the axes and show all the points. Perhaps this could be done with line plots? I couldn't figure out how b/c line plots only take as the x axis things like step, where I want to do this over a hyperparameter in a sweep.

**Comment by MBakirWB** [comment]
Hi @abwilf , happy to help here. From my understanding of your post, you are attempting to group runs by **both** their `alpha value` and their respective `model` type, similar to what I [show here](https://wandb.ai/socialiq/meta_synthetic?workspace=user-mohammadbakir) of my copy of your workspace? I noticed in the image above you only grouped by model type which would only show 2 points as there are only 2 model types. Could you please let me know if the example I provide is what you intended to do?

**Comment by abwilf** [comment]
HI @MBakirWB, thank you for the fast response! yes that's kind of like what I'd like to do, but in that plot it's not clear which datapoints correspond to which model. It'd be nice to have something like what I drew out in the image above, where there are clear labels for which datapoints are related to which model for each of the alpha values.  That way I can test as alpha changes how the different models perform.  Do you know how I can do that?

**Comment by MBakirWB** [comment]
Hi @abwilf , you're welcome. At this time this functionality isn't supported in our prebuilt scatter plot as the **legends equivalent** appears when you hover over the individual data points. I recognize how important it is to have a legend displayed and submitted a feature request for the app team to consider. The feature is to surface charts **"Legend Fields"** and display customizable legends directly on the graph. 

As wandb support [custom charts](https://docs.wandb.ai/ref/app/features/custom-charts) built via [vega](https://vega.github.io/), it would be possible to build your own custom scatter plot.

**Comment by abwilf** [comment]
Ah got it, thank you! I should learn how to use vega. I'll check it out. Thanks!
