### ISSUE TITLE
[Q] Overwriting runs within loops using wandb server

### ISSUE THREAD

**Issue by aclifton314** [wandb/wandb#4490]
wandb 0.13.4
python 3.9.7
ubuntu 20.04.5 LTS
docker 20.10.21

I noticed that how I am I using `wandb` within loops is overwriting (or seems to overwrite) the runs that I am recording. Here is some example code:
```python
import wandb

def wandb_run(my_int: int):
    wandb.init(project='my_project')
    wandb.run.name = 'my_run_' + str(my_int)

    if my_int == 0:
        for ii in range(0, 11):
            wandb.log({'ii': ii})
    
    elif my_int == 1:
        for jj in range(10, 31):
            wandb.log({'jj': jj})
    
    else:
        for kk in range(50, 120):
            wandb.log({'kk': kk})


for ll in range (0,5):
    wandb_run(ll)

print('DONE!')
```
What this produces is 5 offline runs recording different variables under the same project. An analogy to ML would be training the same model on different transformations of a data set or training different models (transformer, convnet, etc.) on a single data set, all of which is done in a loop.

When I run `wandb server start` and then `wandb sync offline-run-*`, I get the following output:
```bash
Find logs at: /tmp/debug-cli.aclifton.log
Syncing: http://localhost:8080/gary-clifton/my_project/runs/1rqa7gol ... done.
Skipping directory: /home/aclifton/rf_fp/tmp_wandb/wandb/offline-run-20221115_124609-2fu7do2r
Skipping directory: /home/aclifton/rf_fp/tmp_wandb/wandb/offline-run-20221115_124609-3v9wyo51
Skipping directory: /home/aclifton/rf_fp/tmp_wandb/wandb/offline-run-20221115_124609-jy49wo4l
Skipping directory: /home/aclifton/rf_fp/tmp_wandb/wandb/offline-run-20221115_124609-nhc45vke
```

Navigating a browser to `http://localhost:8080`, I'm able to sign in and see `my_project`, however there is only a single run, namely `my_run_4`. While all the variables are logged (kk, jj, and ii), I would've expected all the runs to be logged and show up in the Runs panel.

I also noticed that some of the `offline-run-*` directories have other directories in them but not any files:
```
$ ls offline-run-20221115_12460*
offline-run-20221115_124608-1rqa7gol:
files  logs  run-1rqa7gol.wandb  run-1rqa7gol.wandb.synced  tmp  wandb

offline-run-20221115_124609-2fu7do2r:
files  logs  tmp

offline-run-20221115_124609-3v9wyo51:
files  logs  tmp

offline-run-20221115_124609-jy49wo4l:
files  logs  tmp

offline-run-20221115_124609-nhc45vke:
files  logs  tmp
```

Ideally, what I am interested in doing is to log various runs with a unique name under the same project so I can keep tabs on the changes and performances. If anyone has a suggestion on how to do this better, please let me know. I appreciate the help in advance!

**Comment by luisbergua** [comment]
Hi @aclifton314, thanks for writing in! I've explored this and it seems that you're getting all the data appended in the same run. The solution for this is using `wandb.finish()` at the end of your function and so a new run will start in each iteration. Please let me know if this solves your issue.

**Comment by aclifton314** [comment]
@luisbergua That worked! Thank you! I'll close the issue out.

**Comment by luisbergua** [comment]
Great to hear it @aclifton314! Thanks!
