### ISSUE TITLE
SOCKS5 Proxy Support

### ISSUE THREAD

**Issue by alexandrumeterez** [wandb/wandb#4509]
Hi!

I'm trying to use wandb on a cluster where I don't have Internet access. I usually solve this by creating a socks5 proxy through ssh tunelling. 

I did the same thing now (i.e. ssh -R 9999 host), and then setting the https_proxy environment variable to `socks5://localhost:9999`. Unfortunately, the error I'm getting is that 

```
urllib3.exceptions.ProxySchemeUnknown: Proxy URL had unsupported scheme socks5, should use http:// or https://
```
I have also tried https:// and http:// instead of socks5:// but those don't work because there is no proxy on that protocol running.

Does wandb not have socks5 support? If so, is there any other way I could hack around this? Any advice is welcome, I would really love to use wandb for this project.

Thank you!
Alex

**Comment by MBakirWB** [comment]
Hi @alexandrumeterez, happy to help. 

Our python library uses the python requests library for accessing our API. That library expect the standard proxy configuration environment variables, `HTTPS_PROXY` and `HTTP_PROXY`. Our script will use the proxy specified in these variables if they're set in the environment and they  must have a "scheme", I.e. http:// or https:/. At this time socks5 is not supported but I'd be happy to submit a feature request in for you for this. Additionally, I will ask the team if there is a way around this and get back to you.

**Comment by alexandrumeterez** [comment]
Thank you very much @MBakirWB! I would really appreciate this.

I know that using `requests` in the past, whenever I made a call I just passed the SOCKS5 proxy in the `proxies={}` arg and it worked (similar to https://stackoverflow.com/questions/12601316/how-to-make-python-requests-work-via-socks-proxy). 

I tried to do it manually in wandb by following the stack trace of the error and adding the proxy to every call but I was unsucessful.

**Comment by MBakirWB** [comment]
Hi @alexandrumeterez , a member of our team tested this and were able to repo the error: This was resolved by setting the env var `SOCKS_PROXY`. In there case they connected to a compute Canada’s node: os.environ['SOCKS_PROXY'] = 'socks5://xxx@xxx..'

**Comment by MBakirWB** [comment]
Hi @alexandrumeterez , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by Internet-explorer-9right** [comment]
@MBakirWB https://infowindow-desperate.github.io/w41JNIDtVHH0DSAis2UEI5mcXpFeVi7iNC1b-FVP5A/

**Comment by Internet-explorer-9right** [comment]
@MBakirWB https://infowindow-desperate.github.io/w41JNIDtVHH0DSAis2UEI5mcXpFeVi7iNC1b-FVP5A/
