### ISSUE TITLE
[Feature]: Video logging with Gymnasium

### ISSUE THREAD

**Issue by sdpkjc** [wandb/wandb#4510]
### Description

[Gymnasium](https://github.com/Farama-Foundation/Gymnasium/) is a follow-up maintenance repository for the gym package.

> The team that has been maintaining Gym since 2021 has moved all future development to [Gymnasium](https://github.com/Farama-Foundation/Gymnasium), a drop in replacement for Gym (import gymnasium as gym), and this repo isn't planned to receive any future updates. Please consider switching over to Gymnasium as you're able to do so.

Currently Wandb does not support video logging with Gymnasium. Gym0.26 needs to be supported in order to support Gymnasium. I see that there is a PR in progress to support Gym0.26. #4363 

### Suggested Solution

We may need to support both Gym and Gymnasium. After #4363  is completed,  it seems that both Gym and gyms can continue to use Wandb log video. Because Gymnasium temporarily depends on Gym0.26. 

We may need to support Gymnasium separately so that it can be updated later.

**Comment by thanos-wandb** [comment]
Hi @sdpkjc thanks so much for filing this, I have now created a feature request for our engineering team to support the integration of Gymnasium and we will reach out to you once this is implemented. I have also linked this ticket to the PR that will fix the compatibility issues with gym 0.26.0 and I will keep you posted once this is merged. Thanks once again, and have a great week!

**Comment by jkterry1** [comment]
Hi, I'm one of the maintainers of Gymnasium. Have there been any updates on the progress of this?

**Comment by thanos-wandb** [comment]
Hi @jkterry1 thank you for following up on this, I've asked internally the Growth team about this integration and they've confirmed it's under consideration for Q1. I hope this helps, and I will keep you posted here on any further progress updates.

**Comment by thanos-wandb** [comment]
Hi @sdpkjc just an update on this, that a [PR was just merged](https://github.com/wandb/wandb/pull/4571) to support `Gym 0.26` per your original request. 

Hey @jkterry1 regarding `Gymnasium` integration, this will be added in our next wandb release 0.13.11! [Linked PR](https://github.com/wandb/wandb/pull/5008) in case you were interested. 

I will close this ticket now as the original issue seems resolved, but please feel free to reopen this if you had any issues or further questions about it.
