### ISSUE TITLE
[Q] wandb login in a automated environment

### ISSUE THREAD

**Issue by AtomicNess123** [wandb/wandb#4517]
If I want to send a job remotely, how do I login?

**Comment by MBakirWB** [comment]
Hi @AtomicNess123, happy to help. Could you please expand on your questions and what you meant by **"sending a job remotely**". Thanks

**Comment by AtomicNess123** [comment]
Thanks. I am sending my script to a supercomputer via ssh to be queued and run.

**Comment by AbhiKhoyani** [comment]
@AtomicNess123 you can set wandb username and API key in environment variable like below:
`os.environ['WANDB_API_KEY']='your-API-key'
os.environ['WANDB_ENTITY']='your-wandb-username'
`

**Comment by MBakirWB** [comment]
@AbhiKhoyani , thank you for the assistance and feedback to @AtomicNess123. @AtomicNess123 , did the comment address your question or do you need additional support. More on environment variable [here](https://docs.wandb.ai/guides/track/advanced/environment-variables).

**Comment by AtomicNess123** [comment]
Thank you! I have modified my script accordingly, and will test tomorrow.
Just one more question:
What does checkin mean here?

```python
# Only needed if you don't checkin the wandb/settings file
WANDB_ENTITY=$username
WANDB_PROJECT=$project
```

**Comment by MBakirWB** [comment]
Thank you for the update @AtomicNess123. Checkin is referring to version controlling of your project. The `wandb/settings` folder contains identifying user information( i.e username). If you set entity/project there, you don't have to set the environment variable from your command line/script.

**Comment by AtomicNess123** [comment]
Thanks! So it doesn't hurt to have it, right? I don't have any wandb/settings folder that I know of. Should I create it?

**Comment by MBakirWB** [comment]
Hi @AtomicNess123 , you don't have to create a settings file `.config/wandb/settings`, but you are welcome to if you want more control over your environment settings.
