### ISSUE TITLE
GPU usage is not getting tracked after launching my ipynb notebook from vscode in a conda rendered python env. 

### ISSUE THREAD

**Issue by gothchico** [wandb/wandb#4518]
I'm using pytorch to run a deep learning model and honestly a little worried if the model is even using gpu while training although all my tensors seem to show device as cuda:0 but my CPU utilization is hitting 100% alot while gpu also does drop down to 0% while also staying within a 10% range. The GeForce NVIDIA GPU activity panel also shows no active files using GPU as follows : 
![image](https://user-images.githubusercontent.com/57798433/203287068-f469e610-f529-4d79-a27d-252dd5c8d900.png)

What is the issue?

**Comment by MBakirWB** [comment]
Hi @gothchico, happy to help. Could you expand on how you are using wandb to track your experiments, if you are using any integrations (i.e, Pytorch), and which wandb version you are using? Additionally, please see this [example](https://www.kaggle.com/code/ayuraj/use-pytorch-lightning-with-weights-and-biases/notebook) notebook on using PTL with GPU to track experiments with wandb. If you could run through it as a test case and recheck if your GPU is being utilized. Thank You

**Comment by MBakirWB** [comment]
Hi @gothchico, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
