### ISSUE TITLE
Cannot retrieve model versions in the Model Registry

### ISSUE THREAD

**Issue by kayvane1** [wandb/wandb#4519]
I'm unable to retrieve the versions of an artifact on the Model Registry. The same code works in a regular wandb projects but doesn't work for the `model-registry`. It doesn't understand the `model_type` to be valid.

Within the original project where this model has been linked from, the command does work (with the same model type).

![image](https://user-images.githubusercontent.com/42403093/203313041-9c39e756-baeb-45c4-bd2b-7dfc9c360b5f.png)

![Screenshot 2022-11-22 at 12 25 07](https://user-images.githubusercontent.com/42403093/203313286-a9e8d23b-952e-4cc1-b8ca-cccc111dbf30.png)

Trace: 

```
ValueError                                Traceback (most recent call last)
/databricks/python/lib/python3.8/site-packages/wandb/apis/normalize.py in wrapper(*args, **kwargs)
     24         try:
---> 25             return func(*args, **kwargs)
     26         except requests.HTTPError as err:

/databricks/python/lib/python3.8/site-packages/wandb/apis/public.py in artifact_versions(self, type_name, name, per_page)
    892         artifact_type = ArtifactType(self.client, entity, project, type_name)
--> 893         return artifact_type.collection(collection_name).versions(per_page=per_page)
    894 

/databricks/python/lib/python3.8/site-packages/wandb/apis/public.py in collection(self, name)
   3718     def collection(self, name):
-> 3719         return ArtifactCollection(
   3720             self.client, self.entity, self.project, name, self.type

/databricks/python/lib/python3.8/site-packages/wandb/apis/public.py in __init__(self, client, entity, project, name, type, attrs)
   3735         if self._attrs is None:
-> 3736             self.load()
   3737 

/databricks/python/lib/python3.8/site-packages/wandb/apis/public.py in load(self)
   3790         ):
-> 3791             raise ValueError("Could not find artifact type %s" % self.type)
   3792         self._attrs = response["project"]["artifactType"]["artifactSequence"]

ValueError: Could not find artifact type model

During handling of the above exception, another exception occurred:

CommError                                 Traceback (most recent call last)
<ipython-input-115-d4f262d7ee43> in <module>
      4 artifact_type = "model"
      5 
----> 6 artifact_vers = api.artifact_versions(artifact_type, 'util-co/model-registry/relationship-classification')
      7 
      8 for version in artifact_vers:

/databricks/python/lib/python3.8/site-packages/wandb/apis/normalize.py in wrapper(*args, **kwargs)
     59                 raise
     60             else:
---> 61                 raise CommError(message, err).with_traceback(sys.exc_info()[2])
     62 
     63     return wrapper

/databricks/python/lib/python3.8/site-packages/wandb/apis/normalize.py in wrapper(*args, **kwargs)
     23         message = "Whoa, you found a bug."
     24         try:
---> 25             return func(*args, **kwargs)
     26         except requests.HTTPError as err:
     27             raise CommError(err.response, err)

/databricks/python/lib/python3.8/site-packages/wandb/apis/public.py in artifact_versions(self, type_name, name, per_page)
    891         entity, project, collection_name = self._parse_artifact_path(name)
    892         artifact_type = ArtifactType(self.client, entity, project, type_name)
--> 893         return artifact_type.collection(collection_name).versions(per_page=per_page)
    894 
    895     @normalize_exceptions

/databricks/python/lib/python3.8/site-packages/wandb/apis/public.py in collection(self, name)
   3717 
   3718     def collection(self, name):
-> 3719         return ArtifactCollection(
   3720             self.client, self.entity, self.project, name, self.type
   3721         )

/databricks/python/lib/python3.8/site-packages/wandb/apis/public.py in __init__(self, client, entity, project, name, type, attrs)
   3734         self._attrs = attrs
   3735         if self._attrs is None:
-> 3736             self.load()
   3737 
   3738     @property

/databricks/python/lib/python3.8/site-packages/wandb/apis/public.py in load(self)
   3789             or response["project"]["artifactType"].get("artifactSequence") is None
   3790         ):
-> 3791             raise ValueError("Could not find artifact type %s" % self.type)
   3792         self._attrs = response["project"]["artifactType"]["artifactSequence"]
   3793         return self._attrs

CommError: Could not find artifact type model

```

_Originally posted by @kayvane1 in https://github.com/wandb/wandb/issues/4359#issuecomment-1323596975_

**Comment by MBakirWB** [comment]
Hi @kayvane1, happy to help.  This doesn’t exist currently in the same way that it would for a standard Artifact. You can use `wandb.use_artifact()` which will return an [Artifact object](https://docs.wandb.ai/guides/models/walkthrough#4.-use-a-model-version) you can then check the version of. Please let me know if you have any questions.

**Comment by kayvane1** [comment]
Hi @MBakirWB , what I'm trying to do here is:
- Check all the models are currently in production, or have ever been in production (i.e. the versions prior to `:latest` )
- Within each one of the artifacts, I can look at the `logged_by` and `used_by` runs to get all the runs and artifacts that are linked to my production lineage over time
- I can then use this list, to prune the runs and artifacts that I no longer want to keep in my W&B account / in the remote S3 storage to free up space.

To my knowledge, the [Artifact](https://docs.wandb.ai/ref/python/artifact) class that the `wandb.use_artifact()` method would give me, doesn't have a method to check previous versions of the artifact.

**Comment by vwrj** [comment]
Hi @kayvane1, thanks for flagging! We'll get a fix out for this.

**Comment by kayvane1** [comment]
Thanks @vwrj @MBakirWB !

**Comment by Snagnar** [comment]
Same issue here :wave: 

Currently working on a project that uses the wandb model registry as a model zoo for different pretraining versions of the same model in the context of a research project. We went with the model registry as we currently do not plan to make our wandb project with the runs, that created the models, public. I need to access the different model versions, filter by some metadata and download the corresponding model.

All this currently fails on is the model type bug described above.

**Comment by MBakirWB** [comment]
Hi All, This has now been fixed. Please do let us know if you run into other issues.

**Comment by kayvane1** [comment]
Thanks for implementing the fix! It works on 2 of the 3 models I've currently got on the model registry. The third model raises the same error as previously. They're all set-up in the same way so unsure why this hasn't worked across the board.

![Screenshot 2022-12-01 at 10 41 36](https://user-images.githubusercontent.com/42403093/205032347-eb987b16-639b-4c5b-8935-0a2d6e049336.png)

**Comment by MBakirWB** [comment]
@kayvane1, thank you for the update and informing us the fix worked. Wandb release cycles are typically every 2-3 weeks.
