### ISSUE TITLE
[CLI]: A torch.Tensor now triggers error if it is passed as metadata in Artifact

### ISSUE THREAD

**Issue by w238liu** [wandb/wandb#4520]
### Describe the bug

In the current version (0.13.5) of wandb python library, passing a `torch.Tensor` as metadata of a `wandb.Artifact` triggers a `TypeError: Object of type Tensor is not JSON serializable`. I find that it is possible to pass a `torch.Tensor` as metadata in 0.13.4. I am not sure why this feature is removed from 0.13.5. This causes incompatibility between pytorch-lightning and wandb when saving a checkpoint.

```python
import wandb
import torch


metadata = {
    "score": torch.tensor(1.0, device="cpu", dtype=torch.float)
}
wandb.Artifact(name="model-test", type="model", metadata=metadata)
print("Passed")
```

```shell
Traceback (most recent call last):
  File "tmp/test_artifact_metadata/test.py", line 8, in <module>
    wandb.Artifact(name="model-test", type="model", metadata=metadata)
  File "/home/ubuntu/.conda/envs/torchqa2/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py", line 164, in __init__
    metadata = _normalize_metadata(metadata)
  File "/home/ubuntu/.conda/envs/torchqa2/lib/python3.8/site-packages/wandb/sdk/wandb_artifacts.py", line 98, in _normalize_metadata
    Dict[str, Any], json.loads(json.dumps(util.make_safe_for_json(metadata)))
  File "/home/ubuntu/.conda/envs/torchqa2/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/home/ubuntu/.conda/envs/torchqa2/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/ubuntu/.conda/envs/torchqa2/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ubuntu/.conda/envs/torchqa2/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Tensor is not JSON serializable
```

### Environment

WandB version: 0.13.5

OS: Ubuntu 20.04.4 LTS

Python version: 3.8.15

Versions of relevant libraries:
torch: 1.12.1

**Comment by w238liu** [comment]
Hmm, it seems like Pytorch-Lightning has already fixed the compatibility issue. If the described change was made intentionally, feel free to close this issue.

**Comment by fdsig** [comment]
Hey @w238liu , Thanks so much for messaging with this and highlighting, we really value the input and highlighted issues.

I have reproduced this for you and will flag it as a bug for our eng team. 

In terms of getting you back on track using `.numpy().tolist()` methods would work for you taking your code example this would look like: 

```python
import wandb
import torch
metadata = {
    "score": torch.tensor(1.0, device="cpu", dtype=torch.float).numpy().tolist()
}
wandb.Artifact(name="model-test", type="model", metadata=metadata)
print("Passed")
```

Thanks again for your input and hope the above works for you.

**Comment by kptkin** [comment]
Hi @w238liu, just wanted to follow up here, as of version 0.13.7 we reverted the PR that caused the regression. 
I would recommend updating to the latest release to get the most of new features.

I will close this issue if you still seeing and issue please feel free to reopen this issue.
