### ISSUE TITLE
[Q]Questions about how Wandb uses multithreading？

### ISSUE THREAD

**Issue by PussInCode** [wandb/wandb#4522]
Whether running a parameter search program all the time can achieve the effect of multi-threaded parameter search？

likie this:
I run the search parameter file in multiple clients, can I achieve the effect of multithreading?

`python wandb_train.py`

**Comment by nate-wandb** [comment]
Hi @PussInCode, are you starting the agent on multiple machines and they are all running parameters from a single sweep? 

What I would recommend is creating 1 `sweep_id` and then running `wandb agent <sweep_id>` on any machine you want to run parameters from that sweep. The agents receive their parameters from the wandb.ai which knows not to give an agent any parameters that have already been run. 

Let me know if that answers your question or if I might be misunderstanding.

Thank you,
Nate

**Comment by nate-wandb** [comment]
Hi @PussInCode, I wanted to follow up and see if you had a chance to try this out or if you had any additional questions around this?

Thank you,
Nate

**Comment by PussInCode** [comment]
that's all ,thanks you!
