### ISSUE TITLE
[CLI]: Error while calling W&B API: internal database error (<Response [500]>)

### ISSUE THREAD

**Issue by avi-jit** [wandb/wandb#4537]
### Describe the bug

Wandb logs stop getting synced after training starts.

```python
wandb_logger = pl.loggers.WandbLogger(project="etok", save_dir='...')
wandb.run.name = f"{DATASET} {'-'.join(langs)} {model_type}{model.config.num_prefix} {decoder} {batch_size}bs {block_size}bl {'-'.join(wandb.run.name.split('-')[:2])}"
trainer = Trainer(.... logger=wandb_logger, ....)
trainer.fit(model, train_loader, val_loader)
```
Error:

```shell
Epoch 0:   1%|▋                                                                                | 44/4943 [00:11<21:31,  3.79it/s, loss=7.11, v_num=z34s]
wandb: ERROR Error while calling W&B API: internal database error (<Response [500]>)
Epoch 0:   1%|▉                                                                                | 60/4943 [00:14<20:16,  4.01it/s, loss=6.37, v_num=z34s]
wandb: ERROR Error while calling W&B API: internal database error (<Response [500]>)
Epoch 0:   2%|█▎                                                                               | 83/4943 [00:19<18:58,  4.27it/s, loss=6.26, v_num=z34s]
wandb: ERROR Error while calling W&B API: internal database error (<Response [500]>)
```

### Environment

WandB version: 0.13.3

OS: Linux

Python version: 3.9.13

Versions of relevant libraries: torch 1.12.1+cu102

**Comment by ramit-wandb** [comment]
Hi @avi-jit!

Could you share the `debug.log` and `debug-internal.log` files associated to this affected run? They should be present in the `wandb` folder in your working directory - they will help me get better visibility into the issue here.

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
​Hi @avi-jit,

We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.
​

**Comment by ramit-wandb** [comment]
​Hi @avi-jit, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
​

**Comment by avi-jit** [comment]
@ramit-wandb sorry for the late response. The `log` subfolder inside `wandb/run-20221015_150557-2k1zr02k` is empty. There is a wandb_summary.json inside the `files` subfolder which contains summary metrics after the run finished (but none of this was synced online). I also couldn't find any `debug-internal.log` instead found a `debug-cli.thawani.log` inside wandb local folder but that is empty.

**Comment by ramit-wandb** [comment]
Hey @avi-jit, understood. Could you share your username and a link to the run that was running into this issue in that case? I'll check our logs on our end to see if I can find anything that was working incorrectly.

**Comment by avi-jit** [comment]
Hey @ramit-wandb, any update on this issue?

**Comment by avi-jit** [comment]
It seems I cannot run `wandb verify` either

```Shell
>>> wandb verify
Default host selected: https://api.wandb.ai
Find detailed logs for this test at: /tmp/tmp3p2c1tcl/wandb ❌
Cannot run wandb verify against api.wandb.ai
```

**Comment by avi-jit** [comment]
Strike that, reinstalled and it magically works now.
