### ISSUE TITLE
[CLI]: Make class `Runs` sliceable

### ISSUE THREAD

**Issue by janosh** [wandb/wandb#4574]
### Describe the bug

`class Runs(Paginator)` inherits from `Paginator` which defines `__getitem__` in a way that doesn't support slicing, causing the following snippet to throw a `TypeError`:

```python
runs = wandb.Api().runs("<entity>/<project>)

runs[:3]
>>> TypeError: '>' not supported between instances of 'slice' and 'int'

wandb/apis/public.py:1047, in Paginator.__getitem__(self, index)
   1045 def __getitem__(self, index):
   1046     loaded = True
-> 1047     while loaded and index > len(self.objects) - 1:
   1048         loaded = self._load_page()
   1049     return self.objects[index]
```

### Environment

WandB version: 0.13.5

OS: macOS

Python version: 3.11.0

Versions of relevant libraries:

**Comment by ArtsiomWB** [comment]
Hi @janosh, could you talk a bit about your use case?

**Comment by janosh** [comment]
In my case `runs` is an ensemble. Sometimes I'd like to make predictions with all models. Then passing around the whole `runs` object to different test/predict functions is all I need. Other times I need predictions from individual models or subgroups. Taking subgroups of `runs` requires slicing:

```py
make_predictions(runs[0]) # select 1st model, already possible
make_predictions(runs[:10]) # select first 10 models, currently throws TypeError
```
