### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '../../model_cpt'[Q]

### ISSUE THREAD

**Issue by TangJiakai** [wandb/wandb#4579]
I want makdirs in my program, but when I use wandb agent to run, program reports error:
PermissionError: [Errno 13] Permission denied: '../../model_cpt'
model_cpt/aaa.pth is the path I want to make.
How could I fix this bug? ( I had chomd model_cpt to 777)

**Comment by MBakirWB** [comment]
Hi @TangJiakai, happy to help. Could you expand on how you are using wandb agent? Do you have a sample code snippet we can test out to reproduce the behavior your are seeing?

**Comment by TangJiakai** [comment]
Thanks! I'm sorry that my issue is unrelated to wandb and luckily, I have solved it!😂
