### ISSUE TITLE
[CLI]: Wandb shows a run as finished even though it failed when launched with hydra.

### ISSUE THREAD

**Issue by pablo2909** [wandb/wandb#4591]
### Describe the bug

Hello,

I am launching a multi run with hydra. One of those run contains an error. I expect to see on the dashboard that the run failed but it displays that the run finished. Additionally, the logs on each run seems incoherent. Below is a minimal code snippet:

There are two configurations. If we run the configuration `model1` we compute `k -> k**2` for `k in [0,99]`. If we run the configuration `model2` we compute `k -> k**factor` with factor an integer specified in the config file. The error introduced here is that `factor` is never specified in the file, so the line `factor=cfg.model.factor` fails.
```python
import hydra
from omegaconf import  OmegaConf

import wandb


@hydra.main(version_base=None, config_path="minimal_conf", config_name="minimal_config")
def main(cfg):
    print(OmegaConf.to_yaml(cfg))
    my_cfg = OmegaConf.to_container(cfg, resolve=True, throw_on_missing=True)
    run = wandb.init(
        project="Test-multirun",
        entity="pablo2909",
        settings=wandb.Settings(start_method="thread"),
        config=my_cfg,
        reinit=True,
    )
    if cfg.model.model_type == "model1":
        for k in range(100):
            wandb.log({"squared": k**2})

    if cfg.model.model_type == "model2":
        factor = cfg.model.factor
        for k in range(100):
            wandb.log({"special": k**factor})

    wandb.finish()


if __name__ == "__main__":

    main()

```

The configuration directory is organised as follows:

```shell
minimal_conf
├── minimal_config.yaml
└── model
    ├── model1.yaml
    └── model2.yaml
```

with `model1.yaml`:
```yaml
model_type: "model1"
```

and `model2.yaml`:
```yaml
model_type: "model2"
# factor: 5
```
and `minimal_config.yaml`:

```yaml
defaults:
  - model: model1
```

The command line:

```shell
python neuralodev2/train/neuralode_2018/minimal_main.py -m model=model1,model2
```

works, since the failing configuration is specified last. In the dashboard we see indeed that the `model2` failed, as expected.

But the command line:

```shell
python neuralodev2/train/neuralode_2018/minimal_main.py -m model=model2,model1
```

fails. In the dashboard we see that the configuration `model2` finished, which is not what I expect.

What could the issue be ?

Thank you for any help :)

### Environment

WandB version:
wandb = 0.13.15

OS:
OSX 12.3

Python version:
3.8.13

Versions of relevant libraries:
hydra-core = 1.2.0

**Comment by pablo2909** [comment]
Hi @MBakirWB , thank you for looking into this. I sent the email with the object name being "GitHub issue #4591 - MBakir".

**Comment by MBakirWB** [comment]
Hi @pablo2909 

Thank you for sending over the logs. I reviewed the logs and there isn't anything that is called out affecting the run metadata state, the state is set by the client based on the runs exist code. I checked other runs that were called with the same command line arguments and they appear in a [Failed State](https://wandb.ai/pablo2909/Test-multirun/runs/16al7mbe/overview). Additionally, I was unable to reproduce the behavior you are running into. With the use of wandb reinit, it may be that the last process doesn't tear down completely and wandb.init resumes from it, the reason why the failed state is never captured. Are you running multiples tests in rapid succession?

**Comment by pablo2909** [comment]
I'm only running the step up I showed here. My way of solving it for now is to catch if there is an error and call `wandb.finish(exit_code=-1)`

**Comment by ArtsiomWB** [comment]
Hi @pablo2909!

Happy new year and sorry for the late response, could you provide the debug bundle associated with your instance? It can be found at <YOUR_INSTANCE_ADDRESS>/system-admin page. For the debug bundle, it would be at the top right corner menu of this page, downloadable as a ZIP.

**Comment by pablo2909** [comment]
Hi @ArtsiomWB , happy new year to you too as well ! Thank you for getting back to me. Could you provide some more informations on where to find that debug bundle please ?

**Comment by pablo2909** [comment]
Yes :)

**Comment by pablo2909** [comment]
Sorry for my delayed response. 

I am a "regular user" of wandb as part of my PhD. Since I am the only one using my account I assumed I am the admin. This might be not the case as I don't have a system-admin page with a debug bundle.

**Comment by ArtsiomWB** [comment]
Interestiiing. What's your username?

**Comment by pablo2909** [comment]
pablo2909 :)

**Comment by pablo2909** [comment]
I did not know that ! I suppose I have to register my academic email address right ?
I have not tried to see if I encounter the issue anymore. I'm using a work around where I run `wandb.finish(exit_code=-1)` every time I "expect" an error and try to cover as many cases as possible. Not the best option I know :/
