### ISSUE TITLE
[App]: Deleting entire groups of runs causes "internal database error"

### ISSUE THREAD

**Issue by konstantinjdobler** [wandb/wandb#4601]
### Current Behavior

When deleting runs in the UI by selecting entire groups, the deletion fails and "internal database error" is displayed. Selecting all the runs *individually* works as expected and without issues.

### Steps To Reproduce

1. Group runs by group or any other attribute
2. Select one or more groups by the checkmarks for the *entire* group
3. Try to delete the runs

### Screenshots

![Screenshot 2022-12-09 at 18 38 36](https://user-images.githubusercontent.com/28780372/206760517-ee4552d7-8dea-4c57-8bc1-f2330e53c579.png)

### Environment

OS: MacOS

Browsers: Safari

**Comment by lesliewandb** [comment]
Hi @konstantinjdobler, I tried to reproduce this on my side and didn't run into this error. Can you send me a link of the page of where you're trying to delete the runs and which group this is erroring out on? Also, if you click on `x` on the top right of the error message, does that do anything?

**Comment by konstantinjdobler** [comment]
Hello @lesliewandb, now I cannot reproduce it either anymore. Not sure what changed, closing this for now. Thanks!

**Comment by lesliewandb** [comment]
It's great that you're not running into this error anymore :) I hope you have a beautiful rest of the week
