### ISSUE TITLE
[App]:  Unable to log in GPU metric for colab notebooks

### ISSUE THREAD

**Issue by noobkid2411** [wandb/wandb#4606]
### Current Behavior

So far I've been using the following code snippet to log in the GPU metric for my colab notebooks and it worked. But recently, wandb only logs CPU metrics and does not show GPU metric for the colab notebook on running the same code. Please respond,it's a bit urgent. Thanks!

`!pip install wandb`
`import wandb`
`wandb.init(project="")`

### Environment

OS:

Browsers:

Version:

**Comment by nate-wandb** [comment]
Hi @noobkid2411, this is a bug we recently came across that affects versions `0.13.6` and `0.13.5`. Using `!pip install wandb==0.13.4` should resolve this. 

Thank you,
Nate

**Comment by nate-wandb** [comment]
Hi @noobkid2411, I just wanted to follow up on this and see if this resolved the issue for you?

**Comment by nate-wandb** [comment]
Happy to help! We're aware of the bug and a fix will be in the next release. Sorry for the inconvenience.

**Comment by nate-wandb** [comment]
Hi @noobkid2411, I just tested and this has been resolved I `0.13.9`. Let me know if you still see any issues!

Thank you,
Nate
