### ISSUE TITLE
[CLI]: sync unavailable and/or missleading receipts in warnings

### ISSUE THREAD

**Issue by GrigoriiTarasov** [wandb/wandb#4607]
### Describe the bug

Firstly I ran
```python
run = wandb.init(project='proj_name', 
                         config={k:v for k, v in dict(vars(CFG)).items() if '__' not in k},
                         anonymous=anonymous,
                         name="fold_f_str",
                         group=CFG.comment,
                        )
```
and getting 
```shell
...
You can sync this run to the cloud by running:
wandb sync {rund_folder_absolute_path}
...
```

And when I tring to do it 

```shell
raise CommError("Invalid or missing api_key. Run `wandb login`")
wandb.errors.CommError: Invalid or missing api_key. Run `wandb login`
```

Ok lets login:
```python
wandb.login(my_wandb_api_key)
```
```shell
wandb: WARNING Calling wandb.login() after wandb.init() has no effect.
True
```

But afterwards the result of sync is still the same.

Is there a way to sync using py API? Is there a way to use CLI api from jupyter properly?
Why "You can sync this run to the cloud by running:
wandb sync {rund_folder_absolute_path}" is not describing all of this steps?

https://docs.wandb.ai/ref/cli/wandb-sync?q=sync
seem to not have answer for this usage case,

### Environment

WandB version:
0.13.2
OS:
Ubuntu 20
Python version:
3.8.13
Versions of relevant libraries:

**Comment by ArtsiomWB** [comment]
Hi @GrigoriiTarasov! Are you running this on the public cloud? (wandb.ai)

**Comment by GrigoriiTarasov** [comment]
Hi, yes

> Hi @GrigoriiTarasov! Are you running this on the public cloud? (wandb.ai)

**Comment by ArtsiomWB** [comment]
Could you try logging in using CLI with the `wandb login` command
After that try logging in wandb.relogin() in the code.

**Comment by GrigoriiTarasov** [comment]
> Could you try logging in using CLI with the `wandb login` command After that try logging in wandb.relogin() in the code.

AttributeError: module 'wandb' has no attribute 'relogin'

wandb.__version__
'0.13.2'

**Comment by GrigoriiTarasov** [comment]
> Artsiom Skarakhod commented: Hi! What happens wandb login in the cli?

Yes "wandb login in the cli". It happens. Can't sync afterwards.

**Comment by GrigoriiTarasov** [comment]
> Artsiom Skarakhod commented: What's the error message that pops up when it won't let you sync in cli?

Can't answer cause now I can't even 'init' due 
`3.8/site-packages/wandb/sdk/lib/sock_client.py", line 61, in _sendall_with_error_handle
    sent = self._sock.send(data[total_sent:])
BrokenPipeError: [Errno 32] Broken pipe
wandb: ERROR Abnormal program exit`
the wandb calls wasn't changed by me.

**Comment by ArtsiomWB** [comment]
Hi Grigorii! Haven't gotten a response for a bit so I'll close this ticket, as always, you can always write in to reopen it.
