### ISSUE TITLE
[Q] Check sweep controller by name.

### ISSUE THREAD

**Issue by ShuAiii** [wandb/wandb#4615]
I'm trying to resume sweeps by name instead of `sweep_id`. 

Is there a way to check for the status of a sweep controller by name + project name

OR

Get the entire set of sweeps under an entity (kind of like how you can with runs within a project)
```
api = wandb.Api()

api.runs(f"{ENTITY}/{project_name}")
```

**Comment by thanos-wandb** [comment]
Hi @ShuAiii thank you for writing in! Would the following API snippet work for you? 
```
api = wandb.Api()
sweeps = api.project('project-name').sweeps()
for s in sweeps:
  print(s.name)
```
Please let me know if this is what you were looking for, and if you have any further questions.

**Comment by thanos-wandb** [comment]
Hi @ShuAiii just an update regarding the second question, you could loop all projects of certain entity as follows:
```
for p in api.projects('entity-name'):
  print(p.name)
```
That could be the outer loop of the code snippet above. I hope this helps.

**Comment by ShuAiii** [comment]
@thanos-wandb This works, thank you!

> Hi @ShuAiii thank you for writing in! Would the following API snippet work for you?
> 
> ```
> api = wandb.Api()
> sweeps = api.project('project-name').sweeps()
> for s in sweeps:
>   print(s.name)
> ```
> 
> Please let me know if this is what you were looking for, and if you have any further questions.
