### ISSUE TITLE
[App]: [Cli]: Report crashes when offline runs are synced in real time

### ISSUE THREAD

**Issue by Vishu26** [wandb/wandb#4620]
### Current Behavior

I was editing a report on the web app that contained graphs from an offline run that was still running. To update the graphs, I called `wandb sync --sync-all`. This caused the webpage to crash and also the sync failed. *Note - the report was open in edit mode while the runs were synced.

### Steps To Reproduce

1. Create a report of an offline run that is still running.
2. While in edit mode for the report, sync the offline run.

### Environment

OS: Ventura 13.1 Beta (22C5050e)

Browsers: Safari Version 16.2 (18614.3.6.11.2)

Version: Wandb 0.13.6

The code is running in a remote host : Ubuntu 20.04.5 LTS (Focal Fossa)

**Comment by nate-wandb** [comment]
Hi @Vishu26, are you able to access the report after refreshing or is the report still not accessible? I can work on reproducing on my end as well. 

Thank you,
Nate

**Comment by Vishu26** [comment]
Hi @nate-wandb. Refreshing does not work. You have to close the window and reopen it.

**Comment by nate-wandb** [comment]
Hi @Vishu26 could you send me the URL of your report? I wasn't able to replicate on my side.

I tried creating a report and syncing an offline run while I was editing the report but the additional run just showed up in the runset and it updated the charts so it may be related to a particular chart you are using. 

Thank you,
Nate

**Comment by Vishu26** [comment]
I think the issue was very random. It does not happen right now for me. The link to the report is - https://wandb.ai/vishu26/my-test-project/reports/FFCV-Evaluations--VmlldzozMTM2NDUz?accessToken=xwvk38rkupqe7yq1p5ey2vud58ghspzr7lx6l09zwb3brmlzt57hqnv88ovh9vyo

**Comment by nate-wandb** [comment]
Hi @Vishu26, I just wanted to follow up on this. If you get the option to report the issue via Sentry next time this comes up could you try doing that? If not, I will probably need to see the console tab when inspecting the page to see which query is causing the page to crash

**Comment by Vishu26** [comment]
Hi @nate-wandb. Yes I did get an option to report through sentry. I will try doing that next time!

**Comment by nate-wandb** [comment]
Thank you! This will give the engineering team more insight into what happened that caused it. You can post the console errors here as well and I can take a look but I'll close the issue for now and we can see if it comes up again. 

Thank you,
Nate
