### ISSUE TITLE
[Q]  How to check if a secret key corresponds to an entity?

### ISSUE THREAD

**Issue by mathbr10** [wandb/wandb#4621]
I am trying to create a wandb run.

```

wandb.login(key=wandb_secret_key, relogin=True)
try:
    run = wandb.init(
        entity=wandb_entity_name,
        project=wandb_project,
        name=wandb_run_name,
        notes=wandb_experiment_description,
        config=wandb_configs,
    )
except Exception:
    raise InvalidWanbInfoConfigurationsExeption(f"wandb_secret_key({wandb_secret_key}) is not associated with wandb_entity_name ({wandb_entity_name})")

return run
```

I can exception handle like I did, but the subsequent runs are crashing even if wandb_secret_key and wandb_entity_name correspond.

```
---------------------------------------------------------------------------
BrokenPipeError                           Traceback (most recent call last)
~/.virtualenvs/tfpipeline/lib/python3.8/site-packages/wandb/sdk/wandb_init.py in init(job_type, dir, config, project, entity, reinit, tags, group, name, notes, magic, config_exclude_keys, config_include_keys, anonymous, mode, allow_val_change, resume, force, tensorboard, sync_tensorboard, monitor_gym, save_code, id, settings)
   1077         try:
-> 1078             run = wi.init()
   1079             except_exit = wi.settings._except_exit

~/.virtualenvs/tfpipeline/lib/python3.8/site-packages/wandb/sdk/wandb_init.py in init(self)
    573             logger.info("setting up manager")
--> 574             manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
    575 

~/.virtualenvs/tfpipeline/lib/python3.8/site-packages/wandb/sdk/wandb_manager.py in _inform_init(self, settings, run_id)
    169         svc_iface = self._get_service_interface()
--> 170         svc_iface._svc_inform_init(settings=settings, run_id=run_id)
    171 

~/.virtualenvs/tfpipeline/lib/python3.8/site-packages/wandb/sdk/service/service_sock.py in _svc_inform_init(self, settings, run_id)
     37         assert self._sock_client
---> 38         self._sock_client.send(inform_init=inform_init)
     39 

~/.virtualenvs/tfpipeline/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py in send(self, inform_init, inform_start, inform_attach, inform_finish, inform_teardown)
    210             raise Exception("unmatched")
--> 211         self.send_server_request(server_req)
...
   1115                 os._exit(-1)
-> 1116             raise Exception("problem") from error_seen
   1117     return run
```

Is there a wat to check if they correspond without creating the run?

**Comment by luisbergua** [comment]
Hi @mathbr10, thanks for writing in! The thing here is that the api_key is associated to a user and then the user belongs to entities (teams). This is easy to check from the UI by looking at the teams a user is part of. From the code you created, the exception is raising every time that the run creation fails, but this isn't necessary because the api_key is wrong. It may be for example because any of the arguments is wrong written.

Could you give me some more details about the issue you're facing when starting the run and so I can help you with this?

**Comment by mathbr10** [comment]
Hi @luisbergua. We are using wandb in a internal system of my company and we need to garanty that the user does not crash the system. If the key is not corresponing to the user, it crashes forever, even thought the next calls key correspond to the user. 
My exception is raised, but the problem is that in thi way wandb crashes forever. I want to check if it is ok before calling `wandb.init`

**Comment by mathbr10** [comment]
@luisbergua  If it is not possible to verify it with wandb. Could you please verify that wandb crashes after you send invalid key/entity pair and the next requests fail?

**Comment by luisbergua** [comment]
Hi @mathbr10! There's a way to check this by using our Public API. If you try to run a code like this
```
import wandbwandb-login(key=your_key)
api = wandb.Api()
run = api.run(entity_name/project_name/run_id)
```
with a run under the entity that you'd like to check, it will raise `CommError: Could not find run` if this users has no access to the entity and so you can check it. 

Please let me know if this would work for you or if you'd like me to create a new feature request for this. If this is the case, could you explain me what would be the ideal way to check this programmatically?

**Comment by mathbr10** [comment]
@luisbergua it

> Hi @mathbr10! There's a way to check this by using our Public API. If you try to run a code like this
> 
> ```
> import wandbwandb-login(key=your_key)
> api = wandb.Api()
> run = api.run(entity_name/project_name/run_id)
> ```
> 
> with a run under the entity that you'd like to check, it will raise `CommError: Could not find run` if this users has no access to the entity and so you can check it.
> 
> Please let me know if this would work for you or if you'd like me to create a new feature request for this. If this is the case, could you explain me what would be the ideal way to check this programmatically?

@luisbergua we want to check it before training a model, so the `run_id` does not exist in this moment.

**Comment by luisbergua** [comment]
Hi @mathbr10! After some investigation, I've been able to fin a way to check this. First, the user need to log in and add their api_key:
`wandb login --relogin`
Once logged, if you run the following code you can see the usernames under an entity:
```
import wandb
api = wandb.Api()
team = api.team(team_name)
print([m.username for m in team.members])
```
If the user belongs to this entity, the the list of members is visible. However, if the user doesn't belong to this team, the list will be empty `[]` and you can check that they're not right logged in. Please let me know if this would help. Thanks!

**Comment by mathbr10** [comment]
@luisbergua this solves my problem. Thanks a lot!!!

**Comment by luisbergua** [comment]
Hi @mathbr10, great to hear it! I'll then close this ticket but please feel free to ping me here if you have any other question regarding this!
