### ISSUE TITLE
[App]: Sweep agent mysteriously fails

### ISSUE THREAD

**Issue by ShuAiii** [wandb/wandb#4628]
### Current Behavior

I'm trying to run hyperparameter sweeps with the following parameters:

```yaml
sweep:
  method: random
  project: project_name
  name: sweep_name
  metric:
    goal: minimize
    name: Validation loss
  run_cap: 100
```
Caps is not set on each agent, but a total `run_cap` is set on the sweep controller.

I noticed I'm constantly getting errors like this:

```bash
...
wandb: Find logs at: ./wandb/run-20221214_011259-0jbbwa4t/logs
Run 0jbbwa4t errored: IndexError('list index out of range')
wandb: ERROR Run 0jbbwa4t errored: IndexError('list index out of range')
wandb: Agent Starting Run: mu8l3q87 with config:
...
wandb: Find logs at: ./wandb/run-20221214_011314-mu8l3q87/logs
Run mu8l3q87 errored: IndexError('list index out of range')
wandb: ERROR Run mu8l3q87 errored: IndexError('list index out of range')
wandb: Agent Starting Run: s1016hjc with config:
...
wandb: Find logs at: ./wandb/run-20221214_011329-s1016hjc/logs
Run s1016hjc errored: IndexError('list index out of range')
wandb: ERROR Run s1016hjc errored: IndexError('list index out of range')
Detected 3 failed runs in the first 60 seconds, killing sweep.
wandb: ERROR Detected 3 failed runs in the first 60 seconds, killing sweep.
```

And the more agents I launch, the more of them tend to have this error...

I also checked the wandb logs, and found nothing useful in there.
Does anyone know what this error is referring to?

### Screenshots

Here you see 1 of the agents failed 3 times in row then crashed, another agent failed once then recovered, while the remaining agents are fine.

![image](https://user-images.githubusercontent.com/36847796/207485634-62d8b59e-8012-4271-b4e6-e0a0e2824585.png)

### Environment

OS: Ubuntu 20.04

Browsers: Chrome?

Version: Latest wandb version

**Comment by luisbergua** [comment]
Hi @ShuAiii, thanks for reporting this! Is this error raising if you don't specify `run_cap`? Also, could you send me a link to the project where these sweeps are? And when calling the agent, are you specifying the `count` argument?

**Comment by ShuAiii** [comment]
@luisbergua I encountered the same error when the `count` argument is set.

**Comment by luisbergua** [comment]
Hi @ShuAiii, sorry for the delay here! It seems that you deleted the sweep from which you shared the link, I cannot access it (although I can see the project), is this the case? Are you still experiencing this issue? If so, did you try to run without `run_cap`?
