### ISSUE TITLE
[Q] Manually extract metrics from .wandb files

### ISSUE THREAD

**Issue by catalys1** [wandb/wandb#4635]
After using wandb to track metrics for my runs, I’d like to go back and extract those metrics for creating my own plots and visualizations, etc. I know the python API can be used to download them from the server, but what if I just want to access them locally instead of downloading them, which can be slow? I know they’re all stored on disk in a wandb binary log file. Is there a way to read that file locally? That would be really great.

**Comment by ArtsiomWB** [comment]
Hi @catalys1! And what kind of metrics are you talking about in particular? Are you talking about system metrics and stats about your computer during the run or the data you are logging into wandb?

**Comment by catalys1** [comment]
I'm talking about values logged through wandb with `wandb.log`.

The local directory for a run has a file `run-{run_id}.wandb`, which is a binary file, but I can open it up and see all the logged metrics in there (along with a lot of other stuff). I assume this is what is sent to the server, and the server obviously has a way of parsing it and extracting the logged metrics. Basically I was wondering if there was something that exposes that functionality that I could use locally.

**Comment by catalys1** [comment]
That would be a nice feature. I can retrieve the information with a regex, but it's not super robust and occasionally fails.

**Comment by catalys1** [comment]
Yep, just looking forward to seeing the new feature implemented.

**Comment by catalys1** [comment]
Hi, I just wanted to see if there has been any progress on this?
