### ISSUE TITLE
[App]: error in copy/paste code on Download the best model file from a sweep

### ISSUE THREAD

**Issue by blazespinnaker** [wandb/wandb#4657]
### Current Behavior

From the https://wandb.ai/../../overview web page

![image](https://user-images.githubusercontent.com/2188809/208396233-7dd6ca68-9474-4a56-b69e-456670021637.png)

`val_acc = runs[0].summary.get("val_acc". 0)`

Should that be a comma maybe?

### Environment

OS:

Browsers:

Version:

**Comment by ArtsiomWB** [comment]
Hi @blazespinnaker! That should be a comma :)

**Comment by blazespinnaker** [comment]
I dunno, did it?

**Comment by ArtsiomWB** [comment]
Ohhh I am so sorry, I see what you are talking about now... Had to reread this multiple times. I'll let our documentation team know... Wow.
