### ISSUE TITLE
Wandb local server start error

### ISSUE THREAD

**Issue by liswp** [wandb/wandb#4663]
### Current Behavior

Hi Wandb team,

I am a wandb user and currently encountering the following error when we run: wandb server start

*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/01_enable-services.sh...
*** Copying services to runit
*** Copying jobber template
*** Enabling production mode
*** Running /etc/my_init.d/02_load-settings.sh...
*** Loading settings...
2022/12/19 23:47:02 Created default user
2022/12/19 23:47:02 Generating new session key for auth...
2022/12/19 23:47:02 Generating new certificate and key for auth...
*** Booting runit daemon...
*** Runit started as PID 48
*** Setting up mysql database...
*** Starting wandb servers...
*** Configuring minio...
Bucket created successfully `local/local-files`.
mc: <ERROR> Unable to set 'notify_redis address=127.0.0.1:6379 format=access queue_limit=10000 queue_dir=/etc/minio/events key=filemetadata' to server: one or more targets are offline. Please use `mc admin info --json` to check the offline targets.
mc: <ERROR> Unable to enable notification on the specified bucket. A specified destination ARN does not exist or is not well-formed. Verify the destination ARN.

Above is the output from `docker logs wandb-local`

Please help. Many thanks.

### Environment

OS: ubuntu linux 16.04

Browsers: Chrome and Firefox

Version: 16.04, pip 22.2.2, Docker version 18.09.7, build 2d0083d

**Comment by lesliewandb** [comment]
Hi @liswp, can you double check that minio is set up properly by referring to [these docs](https://min.io/docs/minio/linux/administration/monitoring.html?ref=docs-redirect) please?

**Comment by liswp** [comment]
Checking now!

**Comment by liswp** [comment]
@lesliewandb I am checking the docs now, is there a particular cli command you'd like me to run to confirm minio is correctly set up?

**Comment by liswp** [comment]
@lesliewandb And just to be clear, does wandb require minio server, client, or both?

**Comment by liswp** [comment]
@lesliewandb I can confirm that minio server has always been restored, according to the screenshot below:

![image](https://user-images.githubusercontent.com/43964774/208794919-e10e2995-96e5-40ae-8825-9ea80e95ea13.png)

**Comment by nate-wandb** [comment]
@liswp do you have any runs yet or is this an entirely new server you are trying to start? If this is a new server, I'd recommend deleting the docker volume and image, then trying `wandb server start` again.

Let me know if that helps or if you get stuck on the same error. Also, if there is anything unique about your environment that may be helpful information for our side.

**Comment by nate-wandb** [comment]
Hi @liswp, I just wanted to follow up on this and see if this was still and issue?

Thank you,
Nate

**Comment by nate-wandb** [comment]
@liswp I'm closing for now since we haven't heard back but feel free to ping me here if this is still an issue. Thank you!

**Comment by VytasMule** [comment]
I am having the same issue as @liswp.

Removing volume and image and running `wandb server start` once again does not help.
