### ISSUE TITLE
[App]: Bug when displayed aggregated plots

### ISSUE THREAD

**Issue by wjaskowski** [wandb/wandb#4666]
### Current Behavior

Wrong plotting when adding a new run. Hard to describe. Just look at the video:  https://www.loom.com/share/6fa694b9de124c62afe378f560cd2853

### Environment

OS: Linux, Ubuntu

Browsers: Version 107.0.5304.110 (Official Build) (64-bit)

Version:

**Comment by lesliewandb** [comment]
Hi @wjaskowski, thank you for writing in about this! This does look a little weird, can you send me a link to your workspace so I can dig into this a bit more please? Also, does this issue happen when the runs aren't grouped too?

**Comment by wjaskowski** [comment]
Take a look here: https://wandb.ai/gat/alan-exploration/reports/Bug-report--VmlldzozMTk3Mjg4?accessToken=4lorlaqiu6fpwp279fw7nmghb4mee7r82k5d3u8zwx1i012xpyrjyb8cuamnzdvv. 

It seems that the problem is with displaying when X Axis is time.

**Comment by wjaskowski** [comment]
And here is a simpler, artificial example: https://wandb.ai/gat/alan-plot-bug?workspace=user-wjgat 
![image](https://user-images.githubusercontent.com/4952605/209001587-0544b269-3d18-4402-ae37-00568261b3b0.png)

**Comment by luisbergua** [comment]
Hi @wjaskowski, thanks a lot for sharing these Workspaces and reporting this! I've already escalated this bug to our Engineering Team and they'll fix it.

**Comment by sfc-gh-wjaskowski** [comment]
Any updates on this issue?

**Comment by luisbergua** [comment]
Hey @sfc-gh-wjaskowski, let me please check internally what's the status of this

**Comment by luisbergua** [comment]
Hi @sfc-gh-wjaskowski, apologies about the delay here. This haven't been fixed yet by our Eng Team so I'll raise the priority of the bug and keep you posted

**Comment by luisbergua** [comment]
Hey @wjaskowski @sfc-gh-wjaskowski, thanks for your patience! There were some improvements on our UI and we aren't able to reproduce this issue anymore, would you mind sharing if you also see this fixed as well?
