### ISSUE TITLE
[App]: apparent limit on number of viewable images in workspace viewer, but not in single run viewers

### ISSUE THREAD

**Issue by nblauch** [wandb/wandb#4679]
### Current Behavior

I log a lot of images for each training run. When I try to visualize them in the workspace web interface viewer, the ones that make it on the first few pages (the first 36 image metrics per group) show up just fine. However, when I filter to find metrics that are not on the first page, they show up as an empty scatter plot with each datapoint listed as "images/separated".

If I click a single run, and try to view the same metrics, they show up just fine.

This seems to be something about bandwidth. Is it possible there is a maximum number of image metrics to be stored per group in the workspace viewer? If so could this maximum be increased? 

### Expected Behavior

All plotted image should be viewable in the multi-run editor

### Steps To Reproduce

1. Track > 50 (or 100) image metrics for a single grouping in wandb
2. Go to the workspace
3. Try to view all the images, probably only 36 will show up in the workspace editor
4. Click the run
5. Try to view all the images, probably all will show up

### Screenshots

Viewed correctly (metrics 1-36)
<img width="393" alt="image" src="https://user-images.githubusercontent.com/14841433/209013000-9366d6a7-f117-48f7-a30e-16df2c804305.png">
Viewed incorrectly (metrics 37->)
<img width="466" alt="image" src="https://user-images.githubusercontent.com/14841433/209013037-713f9744-b977-4e07-b162-5e4265b492f9.png">

### Environment

OS: Windows (to view), Linux (to run)

Browsers: Chrome

Version: 108.0.5359.125

**Comment by luisbergua** [comment]
Hi @nblauch, thank you for reporting this! Could you send me a link to the Workspace where this is happening? Also, in the bottom left corner, could you try to load the default workspace and see if the same issue appears?

**Comment by nblauch** [comment]
Oh, very interesting. Changing to the default workspace solved the issue, thanks! Not sure why though. We can close this if you prefer, I can't yet make the workspace public (but could share privately with you). Though I'm not sure you would see the problem since it seems to depend on whatever is custom about my own workspace.

**Comment by nblauch** [comment]
Update: saving the default workspace to my own, and making edits to it, haven't yet had the problem reemerge. Let's close this and if at some point I find out what causes it to emerge again, I can reopen if needed. Thanks for the help!
