### ISSUE TITLE
[CLI]: offline mode and upload wrong

### ISSUE THREAD

**Issue by jameschapman19** [wandb/wandb#4688]
### Describe the bug

Running in offline mode (and possibly relating to tensorboard). When I upload it seems to overwrite some runs with other runs meaning I have duplicate runs when I shouldn't. When I look at the log files they are correct but the logged metrics are not.

```python
wandb.init(config=defaults, sync_tensorboard=True, mode='offline')
```

```shell
wandb sync wandb results --sync-all --sync-tensorboard
```

### Environment

WandB version: 0.13.7

OS: Linux

Python version:

Versions of relevant libraries:

**Comment by ramit-wandb** [comment]
Do you have links to a few affected runs? A few links and some more information would go a long way in helping to figure out the issue here.

**Comment by ramit-wandb** [comment]
Hi @jameschapman19,

We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by jameschapman19** [comment]
I ended up just re running the experiments until things worked - I can't isolate whether the problem is happening before upload or during upload. Does seem to be connected to other users issues when using computer clusters. I'm certain it will happen again and will reopen when it does.
