### ISSUE TITLE
[CLI]: Is the wandb server down?(Can't use wandb logger, can't use sweep)

### ISSUE THREAD

**Issue by BingliangLI** [wandb/wandb#4694]
### Describe the bug

`sweep` doesn't work properly, so does `wandb.log`. Is there something wrong with my machien or it's wandb? My other machine also has the same issue(`wandb: ERROR Error while calling W&B API: internal database error (<Response [500]>)`).

And how should I use wandb if the server is down? Any help is appreciated!

```python
>>> import wandb
>>> wandb.init('hello')
```

```shell
500 response executing GraphQL.
{"error":"internal database error"}
500 response executing GraphQL.
{"error":"internal database error"}
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
wandb: Network error (HTTPError), entering retry loop.
wandb: - Waiting for wandb.init()...
```

### Environment

WandB version: 0.13.7

OS: Linux 64

Python version: 3.8

Versions of relevant libraries: torch 1.9.1

**Comment by konstantinjdobler** [comment]
Experiencing the same issue but on `wandb=0.13.4`, so likely not related to the latest release.
Other environment: linux x86_64, python 3.10 and `torch=1.13.1`

**Comment by BingliangLI** [comment]
Visit https://api.wandb.ai/graphql and it showes `{"error":"internal database error"}`

Boys, I think wandb is down😭

I'm trying to host it on my own computer: https://docs.wandb.ai/guides/self-hosted

**Comment by Boltzmachine** [comment]
Same problem here. It looks like a issue on wandb's server?

**Comment by ramit-wandb** [comment]
Hi everyone,

We are aware that the website is experiencing some downtime at the moment and our engineering team is currently investigating this and working on resolving this.

I'll update this thread when the site is back up.

**Comment by lpc-eol** [comment]
Thank you for pointing that out.

**Comment by ramit-wandb** [comment]
Hi everyone,

The website should be back up. Please let us know if you run into any issues.

**Comment by BingliangLI** [comment]
> Hi everyone,
> 
> The website should be back up. Please let us know if you run into any issues.

Thanks! Everything is now synced  to wandb! You guys are amazing!
