### ISSUE TITLE
[CLI]: Recorded videos are broken

### ISSUE THREAD

**Issue by Kami-code** [wandb/wandb#4695]
### Describe the bug

Hi. Wandb Team! 
Thanks for providing such a useful tool.
Recently, I use wandb to record my reinforcement learning experiments, which requires to record a video in simulation every fixed step. At the very begining, the videos seems good as follows.
![Screenshot from 2022-12-27 01-11-04](https://user-images.githubusercontent.com/58084462/209571104-772372a6-9e03-4165-8ac0-8c1efdcc2861.png)
But with the training going, the latest recorded videos started to be broken.
![Screenshot from 2022-12-27 01-11-46](https://user-images.githubusercontent.com/58084462/209571153-4aacddd4-e064-4800-ab51-10004157e6c2.png)
And finally, I cannot see anything but some stripes on almost all new videos.
![Screenshot from 2022-12-27 01-11-57](https://user-images.githubusercontent.com/58084462/209571184-db6fe49d-25f0-4596-a8f4-db54002b4b57.png)
The broken video looks like:
![Screenshot from 2022-12-27 01-13-21](https://user-images.githubusercontent.com/58084462/209571266-a6f97eea-5bf9-449b-88c4-6eac9ac81b8d.png)

I am not a expert in video encoding, so I can only provide some basic facts that may help you.
1. The problem does not exist 2 month ago.
2. The basic frames which form the wandb.Video() instance are intact.

It would be great if you could help me to figure out the problem.

### Environment

WandB version: 0.12.21

OS: Linux

Python version: 3.8

Versions of relevant libraries:

**Comment by MBakirWB** [comment]
Hi @Kami-code , happy to look into this for you. Could you direct me to the project where you are experiencing this issue. I reviewed one of your latest project and don't see any rendering issues with any of your training steps from my end.

**Comment by Kami-code** [comment]
Hi @MBakirWB , this is my project which experienced the problem. **_baochen_state_trail_**

**Comment by MBakirWB** [comment]
Hi @Kami-code , thank you for providing the name of the project.  I asked the app team to review your workspace and should have an update for you by EOW on the cause of the problem.
