### ISSUE TITLE
[CLI]: Waiting for wandb.init() every second call

### ISSUE THREAD

**Issue by willsonNakano** [wandb/wandb#4704]
### Describe the bug

I'm using wandb (0.13.5) to log recurrent data through a FastAPI application. Everytime that I start the application to log some data, it works perfectly. Although, if I run a second time it get stuck in wandb.init() until it breaks. 

I saw some previous issues related to the same error during the wandb.log() method and the relationship of such of some wandb instabilities. I'm not sure what might be causing it, as I was using the exactly same process before with any issue.

For every call, I'm running:
```python
wandb.login(key=<secret_key>, relogin=True)
run = wandb.init(
    entity=<entity_name>,
    project=<project>,
    name=<run_name>,
    settings=wandb.Settings(start_method="thread"),
    reinit=True,
)
artifact = wandb.Artifact(<artifact_name>, type=<artifact_type>, metadata=<metadata>)
artifact.add_dir(<data_path>)
run.log_artifact(artifact)
artifact.wait()
run.finish()
```
The exception that raises everytime when the wandb.init() reaches its timeout:
```shell
Waiting for wandb.init()
wandb: ERROR Error communicating with wandb process
wandb: ERROR For more info see: https://docs.wandb.ai/library/init#init-start-error
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_init.py", line 1078, in init
    run = wi.init()
  File "/usr/local/lib/python3.8/dist-packages/wandb/sdk/wandb_init.py", line 719, in init
    raise UsageError(error_message)
wandb.errors.UsageError: Error communicating with wandb process
For more info see: https://docs.wandb.ai/library/init#init-start-error
```

### Environment

WandB version: 0.13.5

OS: ubuntu 20.04

Python version: 3.8.3

**Comment by nate-wandb** [comment]
Hi @willsonNakano, can you try this without using `reinit=True`? 

If that doesn't work, can you tell me a little more about this is getting called? Is this being called as a subprocess or is this part of a loop?

Thank you,
Nate

**Comment by willsonNakano** [comment]
Hi @nate-wandb, I'll provide a end-to-end process detailed in a new issue. I noticed that the issue only happened when I'm using wandb together with fastapi, celery and redis. Also, the issue wasn't happening with the wandb versions >= 0.12.XX, it started to happen with 0.13.XX versions.

**Comment by nate-wandb** [comment]
Hi @willsonNakano, ok I'm happy to debug here as well if you'd like. One thing you could try is setting the env variable `WANDB_DISABLE_SERVICE=True` when using versions 0.13.XX. Service is a updated backend process that we enabled by default in versions >= 0.13.0 and could possibly be causing the issue.

**Comment by nate-wandb** [comment]
Hi @willsonNakano, I just wanted to follow up and see if this was still an issue after setting `WANDB_DISABLE_SERVICE=True`?

Thank you,
Nate

**Comment by nate-wandb** [comment]
Since we haven't heard back I'll go ahead and close this issue but feel free to tag me here to re-open if you are still experiencing this.
