### ISSUE TITLE
[App]: wandb.errors.CommError: Invalid or missing api_key. Run `wandb login

### ISSUE THREAD

**Issue by DachunKai** [wandb/wandb#4705]
### Current Behavior

I use `wandb sync log_dir --id`, but always got wandb.errors.CommError: Invalid or missing api_key. Run `wandb login

### Environment

OS:

Browsers:

Version:

**Comment by nate-wandb** [comment]
Hi @DachunKai, what is the output of running `wandb login`? Or do you login using the env variable `WANDB_API_KEY`?
