### ISSUE TITLE
[Q] I have train a wandb log directory offline. How to sync it but I want to change the project name.

### ISSUE THREAD

**Issue by DachunKai** [wandb/wandb#4711]
For example, I have trained a wandb log directory named `run-A` with project name`A` in wandb.init function. Usually, I will sync it with `wandb sync run-A`, but it will sync to `A` project. Now I want to sync it to `B` project. How to solve it?

**Comment by luisbergua** [comment]
Hi @DachunKai, thanks for your question! As you can see in [this](https://docs.wandb.ai/ref/cli/wandb-sync) page from our docs, when you run `wandb sync`, you have the option to select the project, is this helpful?

**Comment by DachunKai** [comment]
Thank you @luisbergua ! I found it.
