### ISSUE TITLE
[Q] Will deleted runs get executed again by the agent?

### ISSUE THREAD

**Issue by royvelich** [wandb/wandb#4713]
If I stop a run in the middle, and then delete its record from W&B while the agent is still executing other runs, will the sweep agent reinitiate that run configuration later?

**Comment by MBakirWB** [comment]
Hi @royvelich , thank you for writing in with your question. The sweep will not reinitiate that run configuration later as you cleared the sweep queue of that config. My recommendation is to either run the sweep to competition, then delete the run and resume the sweep, more on this [here](https://docs.wandb.ai/guides/sweeps/faq#can-i-rerun-a-grid-search). You could alternatively launch a new sweep with just those configurations. Please let me know if you have any questions.

**Comment by MBakirWB** [comment]
Hi @royvelich , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
