### ISSUE TITLE
[Q] Offline Mode

### ISSUE THREAD

**Issue by sicroci** [wandb/wandb#4744]
I would like to run wandb offline and then upload the local data. I tried the following commands in Ubuntu:
```
export WANDB_MODE=offline
wandb init -p TEST_PROJECT
... run my training ...
wandb sync /tmp/run_***
```
The last command returns the message "Skipping directory: /tmp/run_***"

What am I doing wrongly? How can I define the local folder where to save the wandb files?

**Comment by MBakirWB** [comment]
Hi @sicroci , if I used is interested in changing the default wandb directory where their runs are stored, they can set the env var `WANDB_DIR`, more on option env vars [here](https://docs.wandb.ai/guides/track/advanced/environment-variables). Once your offline run is complete, run `wandb sync [PATH TO RUN FOLDER]` to sync your offline runs. Please let me know if this helps and if you are successfully. Thanks!

**Comment by sicroci** [comment]
Hi @MBakirWB, thank you for your answer.

I have tried the following code:
```
export WANDB_MODE=offline
export WANDB_DIR=/home/simone/repo/wandb_log/
... run my training ...
```
Unfortunately, the wandb data is still stored in /tmp/. The folder WANDB_DIR=/home/simone/repo/wandb_log/ is empty.

I have also tried to upload the run data with wandb `sync /tmp/run_2023-01....`, but I get the message `Skipping directory: /tmp/run_2023-01....`

**Comment by MBakirWB** [comment]
Hi @sicroci, thanks for the additional info. Two things come to mind:
- Do you have read/write access the directory?
- Are you using a network mapped drive?

**Comment by MBakirWB** [comment]
Hi @sicroci , following up on this thread. Are you still experiencing issues with your storage directory?

**Comment by ramit-wandb** [comment]
Hi @sicroci, since we have not heard back from you, we are going to go ahead and close out this request. In case you have any other questions, please re-open this thread and we can continue the conversation.
