### ISSUE TITLE
[App]: Web UI freezes when trying to load thousands of gradients in deep models

### ISSUE THREAD

**Issue by kenmbkr** [wandb/wandb#4759]
### Current Behavior

I notice that the browser loading time of gradients increases as a model goes deeper.
In particular, when the number of gradients is in the 1000s range, the browser starts to slow down before the gradients appear.
When in the 2000s range, the browser may freeze for minutes until the gradients display properly.
I assume that the web UI tries to load all the gradients to the browser before displaying them.

### Expected Behavior

I expect the gradient loading time to be consistent regardless of the size of the models.
Since the screen can display only 10-20 gradients at once, I expect the web UI to load them on demand to improve the loading speed.

### Environment

OS: core-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch

Browsers: Firefox

Version: 108.0.1

**Comment by billmdevs-wandb** [comment]
Hi @kenmbkr , When you say number of gradients in the 1000s or 2000s do you mean the number of steps?

How do you log the gradients in your code? It will be helpful if you could share your wandb workspace.

When logging do you use the `log_freq` argument? If yes I would recommend to increase the number to increase performance as it defaults to 100.

**Comment by kenmbkr** [comment]
No, I mean the number of charts in the gradient panel. For example, the web UI is logging 621 gradients in the attached screenshot. When the number of charts are more than 1000, especially when larger than 2000, those charts will be spinning for minutes until they are visible.

![Screenshot_20230112_114406](https://user-images.githubusercontent.com/64956291/211963913-464b5ef0-e46c-43ac-a5b9-24b49a2abccc.png)


> Hi @kenmbkr , When you say number of gradients in the 1000s or 2000s do you mean the number of steps?
> 
> How do you log the gradients in your code? It will be helpful if you could share your wandb workspace.
> 
> When logging do you use the `log_freq` argument? If yes I would recommend to increase the number to increase performance as it defaults to 100.

**Comment by kenmbkr** [comment]
> Bill Morrisson commented: I understand but I will need to know how you log your gradients in your code(specific function or example maybe) and what value you used for your `log_freq` argument.

This is how I log the gradients in my code:
```python
wandb.init(config, project='name', resume='allow')
wandb.watch(mode, log='all', log_freq=100)
```

**Comment by kenmbkr** [comment]
> Bill Morrisson commented: Thank you @kenmbkr for your patience! Please try to change the log_freq argument to a higher value( 350 and above) to enable a better performance when loading your gradients.

May I know if there are any scaling rules for the recommended `log_freq`?
For example, should it be directly proportional to the number of layers being logged or the number of steps per epoch? Or is it 350 and above all the time?

**Comment by billmdevs-wandb** [comment]
Not exactly! The rule is that `log_freq` logs gradients and parameters every N batches so the more you increase the number from the default(100) you will be logging a greater number of batches for each log step.
So to summarize `log_freq` is related to the number of batches not the number of layers.

**Comment by kenmbkr** [comment]
> Bill Morrisson commented: Hello @kenmbkr,
> 
> I am circling back to ask if you tested out the suggestion mentioned and if there is any other issue you want me to help with.

I set the `log_freq` argument to 350 and the charts are still spinning for a couple of minutes until they can be fully loaded like before. Please kindly advise what I can try next.

**Comment by kenmbkr** [comment]
I think it solved my problem. Thanks a lot for your help.
