### ISSUE TITLE
[Q] transfer run to another account

### ISSUE THREAD

**Issue by Guptajakala** [wandb/wandb#4777]
Hi, I have two accounts `A` and `B`. `A` has some runs. `B` is a new account using a local server.

Is it possible to transfer runs from `A` to `B`? Either using GUI button (if any), or writing some code?

I've been trying to download all files from a run. But the downloaded files don't seem to include the loss curve data. It's also unclear how to upload these files (and whether these files suffice) to become a new run in account `B`.
```
import wandb
api = wandb.Api()

run = api.run("<entity>/<project>/<run_id>")
for file in run.files():
    file.download()
```

**Comment by luisbergua** [comment]
Hi @Guptajakala, thanks for your question! Our Public Cloud and local server are completely independent, so there is not a straight way to transfer runs from one account to another. However, you can do this in the way you were trying. With `run.history()` you can access all the logged metrics (docs [here](https://docs.wandb.ai/ref/python/public-api/run#history)) and if you download these metrics, you can log them to the new run. Once metrics and files are downloaded, the process would be the standard one, initialize a run and log metrics and files. Please let me know if you face any issue while doing this.

**Comment by Guptajakala** [comment]
Thanks, issue resolved!
