### ISSUE TITLE
Multiple issues when project name includes special symbolds s.a. ":".

### ISSUE THREAD

**Issue by Confusezius** [wandb/wandb#478]
* Weights and Biases version: 0.8.7
* Python version: 3.6.9
* Operating System: Ubuntu 18.04

### Problem
During my `wandb.init(project=<project_name>,...)`-call with a **project name that includes special characters s.a. ":"**, I get a `wandb.apis.CommError: <Response [400]>` error or `requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql` without any information on the problem source. In addition, this results in me not being able to delete these projects from my online wandb page. If I try to do that, I get an `invalid project id`-error, and the project remains.

### Temporary Fix
From my side, the fix was very simple: I simply did not use any special characters. 

However, I now have multiple dead projects that spam my Project page which I assume can't be removed due to the special character issue.

**Comment by vanpelt** [comment]
Hey @Confusezius this is definitely a bug, thanks for reporting.  We'll get a fix out on the server and client in the next week or so.  In the meantime, would you like me to remove the dead projects manually?

**Comment by Confusezius** [comment]
Hey @vanpelt thanks for the quick response! Good to hear that it's going to get fixed :). I don't mind the dead projects too much as long as I'll be able to remove them in the near future.

Anyway, keep up the great work! I really enjoy using wandb!

**Comment by ariG23498** [comment]
Hey @vanpelt 
I think this issue is not yet resolved
![image](https://user-images.githubusercontent.com/36856589/100831944-ce87bc80-348c-11eb-8bb6-3bf95a911668.png)

CC: @cvphelps

**Comment by kptkin** [comment]
This issue is resolved. We inform the user that there are invalid characters in the names of the project. So i'm closing as done!
