### ISSUE TITLE
[Q] Initiatied a run with specific run_id on one process, but was not able to resume the run in a separate process.

### ISSUE THREAD

**Issue by Aldo-Aditiya** [wandb/wandb#4789]
Hi! I've been trying to get two different scripts to log into the same run-id, to no avail. One script initiaties the run with the specific run_id, the other continues.

In one script I've put this:
```
wandb.init(
      id=wandb_id,
      project=args.wandb_project, 
      name=args.wandb_runname, 
      config=vars(args),
      tags=[args.wandb_tag])
```

In another (where I resume the logging) I put this:
```
wandb.init(
          id=wandb_id,
          resume="must")
```

Where wandb_id is the same for both runs. 

When running the second script, it outputs this error:
```
Traceback (most recent call last):
  File "run.py", line 104, in <module>
    wandb.init(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1108, in init
    run = wi.init()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 742, in init
    raise error
wandb.errors.UsageError: resume='must' but run (8squmyay) doesn't exist
```

**Comment by thanos-wandb** [comment]
Hi @Aldo-Aditiya thanks for reporting this issue. Could you please try to provide also the `project` argument in the resumed run and see if that helps?

**Comment by thanos-wandb** [comment]
Hi @Aldo-Aditiya just checking in here to see if you've tried again but specifying the `project` and `entity` arguments, would you still get the `UsageError` that you've originally reported? thanks

**Comment by Aldo-Aditiya** [comment]
Sorry for the late reply. But it worked! Thanks 👍
