### ISSUE TITLE
[Feature]: Give the possibility to add a seed to reproduce random and bayesian searches with sweeps

### ISSUE THREAD

**Issue by tommasocarraro** [wandb/wandb#4804]
### Description

Hello everyone,
I am working on a big research project with my University and we need that everything is reproducible from the beginning to the end. We decided to rely on Weights and Biases for the hyper-parameter tuning part of the project since we love it.

However, the only hyper-parameter search that I am able to reproduce in wandb is the grid search since it simply iterates over the hyper-parameter values in the sweep config. So, by just putting a classic `set_seed()` function before the call to `wandb.agent()`, I am able to reproduce exactly the entire search. By exactly, I mean that the entire training for every single "sampled" configuration is reproducible.

Now, we have a much more complex model that we need to tune. For this model, it is unthinkable to use a grid search for scalability issues. For this reason, I tried to work with random and bayesian searches. However, even if I set a seed before the call to `wandb.agent()`, I am not able to reproduce the sampling of the hyper-parameters from the sweep config. Random search simply randomly samples a configuration for each run, instead, bayesian search samples only the first configuration and then tries to change it in order to maximize performance. 

### Suggested Solution

So, after this big preamble, my request is to simply add a `seed` or `random_state` parameter to the `wandb.agent()`, like `wandb.agent(sweep_id=..., function=..., count=..., random_state=...)`.

I tried to go through your code, and it seems you work with some `Queue` objects. Maybe you just need to add a seed on that part of the code. I am not able to find the logic of random and bayesian searches in the library.

Thank you in advance.

**Comment by thanos-wandb** [comment]
Hi @tommasocarraro thanks a lot for this great suggestion! Actually this feature has been asked again before, I have now increased the number of requests and will keep you posted here on any progress updates from the engineering team. 

At the moment only the `grid` search will give you a reproducible experiment, as the `seed` of the `random`/`bayes` methods isn't currently exposed. If your training isn't computationally expensive, you could also run the configuration multiple times and aggregate the metrics if you `Group` the runs by Sweep, in order to somehow eliminate the discrepancies amongst them. I hope this helps!

**Comment by tommasocarraro** [comment]
Nice!

I will wait for this nice feature.

Unfortunately, I do not think that your idea is applicable in my case.

What I would like to do is to perform the Bayesian search for many methods.

Then, if one wants to reproduce my code, he/she just have to run the main and the main will perform the search with the selected seed, and all the other operations. 

So, my request is useful for reproducing the entire experiment from the beginning to the end: dataset creation, hyper-parameter tuning, training of the model with the best parameters, test of the model. I mean, the entire ML pipeline. 

Without the possibility to set a seed, the hyper-parameter tuning will always be different and hence also the best hyper-parameters found by the procedure.

**Comment by thanos-wandb** [comment]
Hi @tommasocarraro thank you for additional details, indeed for your use case you would want to be able to control the seed of the random generator. I will try to bump up the priority of this feature, but for the moment I can only tell that this is something on the roadmap. I will temporarily close this thread now, but will get back to you once there are any updates! Thanks again for suggesting this.
