### ISSUE TITLE
[Q] "Table" Panel only Shows up When Certain Run is Selected, Despite Every Run Having a Table Data

### ISSUE THREAD

**Issue by Aldo-Aditiya** [wandb/wandb#4825]
In the below image, when both runs 5 and 6 are shown, the table is shown correctly for both of the runs.
![image](https://user-images.githubusercontent.com/22410385/214277881-a8383cd2-353c-4972-8b21-a9932a3794a0.png)

Yet in the below image, when only run 6 is shown, the table does not show up for it.
![image](https://user-images.githubusercontent.com/22410385/214277840-fd75f7b7-cd6f-422f-9d81-e46b34e23f28.png)

Furthermore, when only run 5 is shown, the table does show.
![image](https://user-images.githubusercontent.com/22410385/214278249-067ff86b-2b54-49bc-b0a0-1839b219a315.png)

Why the discpreancy with run 6?

**Comment by luisbergua** [comment]
Hi @Aldo-Aditiya, thanks for reporting this! Could you please send me a link to this project and so I can have a look at it and see what's happening here?

**Comment by Aldo-Aditiya** [comment]
Unfortunately I have deleted the project as it's just a test - I'll remake it and let you know.

**Comment by luisbergua** [comment]
Great, thanks @Aldo-Aditiya!

**Comment by Aldo-Aditiya** [comment]
I've recreated the problem here: https://wandb.ai/aldoan/testbed. But it has gotten even weirder.

This is what happens when I display everyone - everyone shows up.
![image](https://user-images.githubusercontent.com/22410385/214316252-eff3a745-086d-40d6-a798-73280b943359.png)

This is what happens if I display 3 only, othing shows up
![image](https://user-images.githubusercontent.com/22410385/214316347-0bf1a283-666f-4a36-a8ea-b3192674acc3.png)

And this is what happens when I display only 3 and one other. 3 does not show up
![image](https://user-images.githubusercontent.com/22410385/214316548-56d40c19-11fd-4e8e-bc48-e5bea6e3deb4.png)

**Comment by Aldo-Aditiya** [comment]
I attach the simple codes that I used to generate the above test.

Note that the code I give is for the last run. For each run i vary it slightly as such:
1. At test_1 I log the dictionary, and at test_2 i log the table
2. Reverse of run 1
3. Like run 2, but I also write config on test_1

test_1.py
```
import wandb

config = {"loss": "test", "lr": "test"}
wandb_id = wandb.util.generate_id()

wandb.init(
    id=wandb_id,
    project="testbed",
    config=config)

logs = {"loss": "test", "lr": "test"}
wandb.log(logs)

wandb.finish()

print(wandb_id)
```

test_2.py
```
import wandb

wandb_id = "149c3orc" # is from the previous run

wandb.init(
      id=wandb_id,
      project="testbed",
      resume="must")

wandb_col = ["Prompt", "Run"]
wandb_table_data = [[1,2], [1,2]]
wandb_table = wandb.Table(data=wandb_table_data, columns=wandb_col)
wandb.log({"test_table": wandb_table})

wandb.finish()
```

**Comment by luisbergua** [comment]
Hi @Aldo-Aditiya, thank you very much for sharing all these information! I've been trying to reproduce the issue but it seems it's working properly for me when accessing your workspace https://wandb.ai/aldoan/testbed?workspace=user-aldoan. I checked both cases and they are properly showed:

![image](https://user-images.githubusercontent.com/113048227/216129252-a83fb5e8-2038-4373-a34f-a303aee921c7.png)
![image](https://user-images.githubusercontent.com/113048227/216129443-0854553a-1a8c-4b28-8d1f-a0500ec5f604.png)

I also tested this in Chrome, Firefox and Safari and seems to be working properly the three of them, are you using any other browser?

If you're still able to get this issue, it would be nice if you could share with me the browser logs (in Chrome, right click -> inspect -> network) and so I can have a look and see if I can figure out what's happening here. Thanks!

**Comment by luisbergua** [comment]
Hi @Aldo-Aditiya, just wanted to follow up here! Could you please share with me the browser logs (in Chrome, right click -> inspect -> network) and so I can have a look and see what's happening here. Thanks!

**Comment by Aldo-Aditiya** [comment]
Apologies for the late reply! I re-checked my workspace just now, but I couldnt reproduce the bug. Now it works as it should.

Perhaps the bug only shows up a few moments after the logs are generated. It might be that if you run the above code that I gave you, you will be able to reproduce the bug on your workspace.

**Comment by Aldo-Aditiya** [comment]
On another note, I am using brave browser

**Comment by luisbergua** [comment]
Hi @Aldo-Aditiya, thanks for your answer! I just checked your code and it seems to be working properly even just after I run it so this may have been a transient issue. I'll go ahead and close this ticket for now but please feel free to re-open it if you face the issue again and I'll keep investigating this!

**Comment by Aldo-Aditiya** [comment]
Okay! it might be a one time thing 😅
