### ISSUE TITLE
Not GPU usage on Ubuntu 18.04 

### ISSUE THREAD

**Issue by MichaelGaliciaZ** [wandb/wandb#4834]
### Current Behavior

I am trying to measure GPU usage when training a Keras model (in addition to calculating GFLOPS), the first error is that it cannot calculate GFLOPS and the second error is that it only reports irrelevant system information, and not GPU information.
![imagen_2023-01-24_155637555](https://user-images.githubusercontent.com/54015101/214429992-fa958db7-a25a-452f-9064-bd7ac2fdcbd8.png)

### Expected Behavior

I need to measure GPU utilization in addition to GFLOPS to compare some models.

### Environment

OS:
Ubuntu 18.04 LTS
Browsers:

Version:
 Last conda version

**Comment by ramit-wandb** [comment]
Hi @MichaelGaliciaZ,

Do you have the CUDA Developer Toolkit installed on your system? Our platform uses [PyNMVL](https://pypi.org/project/pynvml/) which needs [NVML](https://developer.nvidia.com/nvidia-management-library-nvml) to operate correctly.

Could you try to run `nvidia-smi` on your device to confirm that you are able to gather GPU stats from there?

**Comment by MichaelGaliciaZ** [comment]
Yes, when i run `nvidia-smi` in shell, GPU and process information (monitor, python envs, etc.) is displayed correctly. I should mention that I use an anaconda environment with python 3.6. 

I will try to install PyNMVL separately in the hope that the problem will be fixed.

**Comment by MichaelGaliciaZ** [comment]
After installing PyNMVL the GPU information is displayed correctly.

Thanks!

**Comment by giusmatera** [comment]
Hi,

I'm reaching out again because I'm having trouble getting wandb to recognize my GPU. I'm running Windows 11 with an NVIDIA GeForce RTX 4060. Interestingly, wandb works fine with GPUs on some of the clusters I use. However, on my laptop, despite having installed PyNVML and the CUDA toolkit, it's not detecting the GPU. Any suggestions on how to resolve this?

Thanks,
Giuseppe
