### ISSUE TITLE
[App]: There's no data for the selected runs.

### ISSUE THREAD

**Issue by Seraphli** [wandb/wandb#4844]
### Current Behavior

<img width="509" alt="image" src="https://user-images.githubusercontent.com/1586755/214651957-f34ed10c-c5fa-4cfe-bb97-6140ede80f3d.png">
I checked the log and console output. No error. Sometimes if I run for the second time, the data will show up in the new run. And the strange thing is the value in the summary is correct.
<img width="778" alt="image" src="https://user-images.githubusercontent.com/1586755/214652562-f9ee47a6-4a8d-4989-8e0e-d06973a4ee21.png">
I don't know why it happens from time to time.

### Expected Behavior

The data is displayed on the website.

### Steps To Reproduce

Randomly. I have no idea how to trigger this issue.

### Environment

OS: MaOS

Browsers: Chrome

Version: 0.13.9

**Comment by Seraphli** [comment]
Okay, I will try it when it happens again. I deleted the `wandb` folder before and everything seems fine for now. I don't know whether this operation is related.

**Comment by ramit-wandb** [comment]
Sure thing - I'm closing this thread out for now, but in case you run into this again, please feel free to reopen this thread and  I will be happy to assist you.
