### ISSUE TITLE
[Q] How can change the group of a experiment

### ISSUE THREAD

**Issue by dishank-b** [wandb/wandb#4850]
I have a experiment for which I put some group name, now I later want to assign that experiment to different group or change it's group name to a new group. How can I do that?

**Comment by luisbergua** [comment]
Hi @dishank-b, thanks for your question! You can do that by using our Public API like:
```
import wandb
api = wandb.Api()
run = api.run("<entity>/<project>/<run-id>")
run.group = "<group>"
run.update()
```
Please let me know if it works as expected.

**Comment by kptkin** [comment]
Closing this issue. Feel free to re-open if the you need further assistance
