### ISSUE TITLE
[App]: stopping the run is hanged

### ISSUE THREAD

**Issue by jsikyoon** [wandb/wandb#4856]
### Current Behavior

I sent the request to stop the run, but it is stopping meanwhile about several months!

### Expected Behavior

it is important logs used in my paper, hopefully it will be stopped and I can move it to shared project.

### Steps To Reproduce

1. go to https://wandb.ai/jaesikyoon/ocrl/runs/19ve6sfu/overview
2. check the status

### Screenshots

![image](https://user-images.githubusercontent.com/22428579/215029149-323669fb-e2e6-4436-a5d0-a1a7a4de09be.png)

### Environment

OS: mac

Browsers: chrome 

Version:

**Comment by jsikyoon** [comment]
Oh, yes, sorry. The project requires over my limitation, so I deleted the project and currently try to share the trained model through other cloud service.

Anyway, the run was hanged in stopping, maybe the reason could be I deleted the log files right after stopping the run in web (I cannot remember exactly haha).

If I can see same phenomenon later, I will share.

Thank you for your feedback.
Bests, Jaesik.

From: luisbergua ***@***.***>
Date: Monday, January 30, 2023 9:15 PM
To: wandb/wandb ***@***.***>
Cc: Jaesik Yoon ***@***.***>, Mention ***@***.***>
Subject: Re: [wandb/wandb] [App]: stopping the run is hanged (Issue #4856)

Hi @jsikyoon<https://github.com/jsikyoon>, thanks for reporting this! When I try to access the link you shared, it seems there is no project named ocrl, did you delete this project?

**Comment by luisbergua** [comment]
Hi @jsikyoon, thanks for your reply! I'll then close this ticket but please feel free to re-open it if you experience this again.
