### ISSUE TITLE
[CLI]: Artifact.download gives OSError: [Errno 22] Invalid argument: './artifacts/Files_txt:v2'

### ISSUE THREAD

**Issue by deividbotina-alv** [wandb/wandb#4865]
### Describe the bug

I am learning how to use Artifacts and wanted to make a simple example.
1) In a first run I load an artifact with a wandb.Table. 
2) In a second run I want to access that table by downloading the whole artifact but when I use "artifact.download()" the file shows me : <*** OSError: [Errno 22] Invalid argument: './artifacts/Files_txt:v2'> ("Files_txt:v2" is the name of my artifact).
Therefore I decide to specify a root and it works, it downloads the artifact in root, however, I don't know how to access to my table. I have tried the following options:

```python
my_table = artifact.get('Table')
```
Output
```
*** OSError: [Errno 22] Invalid argument: './artifacts/Files_txt:v2'.
```
Using the full file name
```python
my_table = artifact.get('Table.table.json')
```
Output
```
*** OSError: [Errno 22] Invalid argument: './artifacts/Files_txt:v2'.
```
Finally I tried the two previous steps but now using the full path where the artifact was downloaded
```python
my_table = artifact.get('root/Table') # root is my path
my_table = artifact.get('root/Table.table.json') # root is my path
```
Output: It gives me a NoneType object

I think it may be a bug related to the path used by W&B, any suggestions?

```python
    if FIRST_STEP:

        with wandb.init(project='tests', entity='deividbotina', job_type = 'artifact_test') as run:
            
            artifact = wandb.Artifact(
                name='Files_txt',
                type="test",
                description='Just some files txt',
                metadata={"meta1":'Testing metadata', "meta2":'Testing metadata 2'}
            )   
            
            my_table = wandb.Table(columns=["a", "b"], data=[["1a", "1b"], ["2a", "2b"]])
            artifact.add(my_table,"Table")
            
            run.log_artifact(artifact)

    elif SECOND_STEP:

        with wandb.init(project='tests', entity='deividbotina', job_type = 'artifact_test') as run:
            
            artifact = run.use_artifact('deividbotina/tests/Files_txt:latest', type='test')
        
            # artifact_dir = artifact.download() # Gives "OSError: [Errno 22] Invalid argument: './artifacts/Files_txt:v2'"
            artifact_dir = artifact.download(root='/media/deivid/files/repos/WNB/Artifacts_1/download')
            
            # Access to the table
            my_table = artifact.get('Table') # Gives "OSError: [Errno 22] Invalid argument: './artifacts/Files_txt:v2'"
            my_table = artifact.get('Table.table.json') # Gives "OSError: [Errno 22] Invalid argument: './artifacts/Files_txt:v2'"
            my_table = artifact.get(r'/media/deivid/files/repos/WNB/Artifacts_1/download/again/Table') # Gives an NoneType Object
            my_table = artifact.get(r'/media/deivid/files/repos/WNB/Artifacts_1/download/again/Table.table.json') # Gives an NoneType Object

```

```shell
wandb: Tracking run with wandb version 0.13.9
wandb: Run data is saved locally in /media/deivid/files/repos/WNB/Artifacts_1/wandb/run-20230128_182941-ya777m8z
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run glistening-kumquat-8
wandb: ⭐️ View project at https://wandb.ai/deividbotina/tests
wandb: 🚀 View run at https://wandb.ai/deividbotina/tests/runs/ya777m8z
*** OSError: [Errno 22] Invalid argument: './artifacts/Files_txt:v2'
```

### Environment

WandB version: 0.13.9

OS: Linux Mint 21 Cinnamon

Python version: 3.10.8

Versions of relevant libraries:

**Comment by ramit-wandb** [comment]
Hi @deividbotina-alv,

Looks like `artifact.get` is being used incorrectly over here - I would suggest you have a look at our documentation and specifically [this example](https://docs.wandb.ai/ref/python/artifact#get) to understand usage.

Thanks,
Ramit

**Comment by deividbotina-alv** [comment]
> Hi @deividbotina-alv,
> 
> Looks like `artifact.get` is being used incorrectly over here - I would suggest you have a look at our documentation and specifically [this example](https://docs.wandb.ai/ref/python/artifact#get) to understand usage.
> 
> Thanks, Ramit

Hi @ramit-wandb 

Thank you for quick answer, I read the documentation before, maybe I am misunderstanding something?, following your advice I ran the following code (just copy pasting the example but with my project and entity information):

```python
    with wandb.init(project='tests', entity='deividbotina', job_type = 'artifact_test') as r:
        artifact = wandb.Artifact('my_dataset', type='dataset')
        table = wandb.Table(columns=["a", "b", "c"], data=[[i, i*2, 2**i]])
        artifact.add(table, "my_table")
        wandb.log_artifact(artifact)
    
    # Run using the artifact
    with wandb.init(project='tests', entity='deividbotina', job_type = 'artifact_test') as r:
        artifact = r.use_artifact('my_dataset:latest')
        table = r.get('my_table')
```
And I got the following error
```bash
AttributeError: 'Run' object has no attribute 'get'
```
I believe there is an error in the example, to be specific, in the last line, so I changed it to ```table = artifact.get('my_table')``` and I am getting the same error as before: 
```bash
OSError: [Errno 22] Invalid argument: './artifacts/my_dataset:v0'
```
Do you know what I could be doing wrong?

Bests,
Deivid

**Comment by ramit-wandb** [comment]
Hi @deividbotina-alv,

I just tested this on my end, and while the example does have a minor error - it should be `artifact.get('my_table')`, that seems to work for me on MacOS and Ubuntu.

Let's do the following to try to debug this:

1. Could you share the `debug-internal.log` file of one of the runs which crashed with `OSError 22`?
2. If possible, could you uninstall and reinstall the `wandb` SDK?

Based on the error message, this is an error when calling `open()` internally to download this artifact.

There is a good chance this issue might also be coming from the Operating System level in which case this could be an error with the permissions you have on the filesystem, something worth checking and it might be worth trying on another machine if you run into the same issue.

Ramit

**Comment by ramit-wandb** [comment]
​Hi @deividbotina-alv, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
​

**Comment by deividbotina-alv** [comment]
> artifact.get('my_table')

Hello @ramit-wandb, sorry I couldn't reply faster. Here the debug-internal.log file.

[debug-internal.log](https://github.com/wandb/wandb/files/10694862/debug-internal.log)

I am thinking to do the same experiment in google colab also, just to check if it is related with my operative system.

Thanks.

**Comment by ramit-wandb** [comment]
Hey @deividbotina-alv,

Are you sure this is the correct debug log? From what I see, this seems to be the logs for the process that creates and uploads an artifact, not the one that ingests it. The log would be of in your working directory in the format `wandb/run-<DATETIME>-<RUNID>/logs/debug-internal.log` where `<RUNID>` should correspond to the Run ID of the run ingesting the artifacts.

Thanks,
Ramit

**Comment by deividbotina-alv** [comment]
Hi @ramit-wandb 

Thanks again for quick response. Sorry I had a lot of folders and I took the wrong one. Just in case, I deleted all my runs and ran again the code. Here the two files:
[debug-internal_1.log](https://github.com/wandb/wandb/files/10705071/debug-internal_1.log)
[debug-internal_2.log](https://github.com/wandb/wandb/files/10705072/debug-internal_2.log)

Bests,
Deivid.

**Comment by ramit-wandb** [comment]
Hi @deividbotina-alv,

I just looked into the 2 files, and they both seem healthy. You should definitely run the test above in a colab environment, I don't think this error is occuring from the `wandb` SDK's end.

**Comment by deividbotina-alv** [comment]
> Hi @deividbotina-alv,
> 
> I just looked into the 2 files, and they both seem healthy. You should definitely run the test above in a colab environment, I don't think this error is occuring from the `wandb` SDK's end.
> 
> If you could send the whole stack trace, that would be helpful as well.

Hi @ramit-wandb 
Thanks for you answer. I did run the same experiment in a colab environment and it worked just fine, the artifact was saved in /content/artifacts/my_dataset:v0. The problem is only happening in my computer with linux mint, I am going to try in a new conda environment and I'll let you know.
Thanks,
Deivid.

**Comment by ramit-wandb** [comment]
Hey Deivid,

Thanks for confirming this. It might be worthwhile to do containerize your program with Docker and run this on another machine. Maybe this will let you run the program on your current machine too but I'm not sure about that.

**Comment by deividbotina-alv** [comment]
> Hey Deivid,
> 
> Thanks for confirming this. It might be worthwhile to do containerize your program with Docker and run this on another machine. Maybe this will let you run the program on your current machine too but I'm not sure about that.

Hi @ramit-wandb, thank you for the suggestion, I am not really sure how to do that but I will do some research.

Thank you,
Deivid.

**Comment by ramit-wandb** [comment]
Thanks Deivid! Just to help you a little with your research into dockerizing your application, you might want to get started with [Dockers Getting started Guide on building containerized applications](https://docs.docker.com/get-started/02_our_app/)

I'm assuming you are using NVIDIA GPUs to train your Machine Learning models, so you would probably want to use NVIDIA's [CUDA Base Image](https://hub.docker.com/r/nvidia/cuda) to build your image. Additionally, to let your container access the GPU resources within the container, you would want to look into [NVIDIA's Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html) to install the correct runtime.

All the best and happy training!
Ramit
