### ISSUE TITLE
[Feature]: It is better to have a lock mode in the app.

### ISSUE THREAD

**Issue by Jeffrey28** [wandb/wandb#4867]
### Description

After I test some parameters, there are some runs. I want to delete some no better, crashed or abandoned runs. But I have to choose them one by one. It is too troublesome.

### Suggested Solution

If there is a lock button that I can keep one locked and it is easy to delete all what I want to delete.

**Comment by lesliewandb** [comment]
Hi @Jeffrey28, this can be done by filtering the run by what you want. For example, you can filter by crashed runs and be able to mass select those runs by clicking on the checkbox above the run names. From there, you'll be able to delete a lot of runs at the same time. Let me know if you need any further help here!
<img width="648" alt="Screenshot 2023-01-30 at 1 55 23 PM" src="https://user-images.githubusercontent.com/91079402/215604108-b41469d4-914e-4ed6-9d1c-08070be2c075.png">

**Comment by lesliewandb** [comment]
Hi @Jeffrey28, I'm happy you were able to find a workaround for this! Let me know if you need any further help
