### ISSUE TITLE
[CLI]: `wandb.Artifact()` doesn’t work in “disabled” WANDB_MODE since `0.13.8` with `FileNotFoundError`

### ISSUE THREAD

**Issue by YiranJing** [wandb/wandb#4869]
### Describe the bug
`wandb.Artifact()` doesn’t work in “disabled” WANDB_MODE since `0.13.8` with `FileNotFoundError: [Errno 2] No such file or directory`
### Reason
[`cache_dir_base`](https://github.com/wandb/wandb/blob/0c9c915652926f800049a4537bde9bf45c7d40ac/wandb/sdk/interface/artifacts.py#L992) is added in 0.13.8, but it doesn’t return a valid path, instead a class `wandb.sdk.lib.disabled.RunDisabled` if wandb is in the disabled mode. 
### A minimal code snippet to reproduce the bug

```python
import wandb
import os


def main():
    os.environ["WANDB_MODE"] = "disabled"

    run = wandb.init(project="test-mnist")

    singleton = wandb.sdk.wandb_setup._WandbSetup._instance
    cache_dir_base = (
        wandb.run.settings.cache_dir
        if wandb.run and wandb.run.settings.cache_dir # this condition is True if wandb_mode = "disabled"
        else singleton._settings.cache_dir
        if singleton and singleton._settings.cache_dir
        else wandb.env.get_cache_dir()
    )
    print(f"cache_dir_base is '{cache_dir_base}'")  # empty
    print(f"type cache_dir_base is {type(cache_dir_base)}")

    # This line doesn't work since v.0.13.8
    artifact = wandb.Artifact("data", type="data")

    run.finish()

if __name__ == "__main__":
    main()
```

#### Output 

```shell
cache_dir_base is ''
type cache_dir_base is <class 'wandb.sdk.lib.disabled.RunDisabled'>
Traceback (most recent call last):
  File "/Users/yiranjing/Desktop/folder/example.py", line 40, in <module>
    main()
  File "/Users/yiranjing/Desktop/folder/example.py", line 35, in main
    artifact = wandb.Artifact("data", type="data")
  File "...python3.9/site-packages/wandb/sdk/wandb_artifacts.py", line 180, in __init__
    self._storage_policy = WandbStoragePolicy(
  File "...python3.9/site-packages/wandb/sdk/wandb_artifacts.py", line 864, in __init__
    self._cache = get_artifacts_cache()
  File "...python3.9/site-packages/wandb/sdk/interface/artifacts.py", line 1000, in get_artifacts_cache
    _artifacts_cache = ArtifactsCache(cache_dir)
  File "...python3.9/site-packages/wandb/sdk/interface/artifacts.py", line 858, in __init__
    filesystem.mkdir_exists_ok(self._cache_dir)
  File ".../python3.9/site-packages/wandb/sdk/lib/filesystem.py", line 16, in mkdir_exists_ok
    os.makedirs(dir_name, exist_ok=True)
  File "...python3-3.9.12/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: 


```

### Environment

WandB version: 0.13.8

OS: macOS 13.2

Python version: 3.9.12

**Comment by billmdevs** [comment]
Hey @YiranJing 

Thank you very much for your patience. I was able to reproduce the error and will be filing it to the team as a bug.

**Comment by billmdevs** [comment]
Hey @YiranJing 

We just re-tried running this script on our latest release of wandb and it no longer shows any error. Could you please confirm and let me know if you still run into this error?

**Comment by YiranJing** [comment]
> Hey @YiranJing
> 
> We just re-tried running this script on our latest release of wandb and it no longer shows any error. Could you please confirm and let me know if you still run into this error?

Hey @billmdevs, 

thanks! it works for me under `0.12.3`. I close this issue

**Comment by billmdevs** [comment]
Hey @YiranJing 

Just circling back on this issue to check out if the same error doesn't happen on our latest release?([v0.13.10](https://github.com/wandb/wandb/releases/))

**Comment by YiranJing** [comment]
> Hey @YiranJing
> 
> Just circling back on this issue to check out if the same error doesn't happen on our latest release?([v0.13.10](https://github.com/wandb/wandb/releases/))

Hey @billmdevs, the error has been fixed in the latest release, as I commented above. Thanks!
