### ISSUE TITLE
[App]: Grouping of experiments changing the value in the plots compared to true value in the individual experiments

### ISSUE THREAD

**Issue by dishank-b** [wandb/wandb#4879]
### Current Behavior

Let's say I run two experiments, individually I am getting correct plots of some metric. But when I am grouping the runs, the way metrics  combines are not correct. Refer to screenshots below. 

IT'S A REALLY BIG BUG! 

it's related to already existing issue https://github.com/wandb/wandb/issues/1566. 

### Screenshots

<img width="3193" alt="image" src="https://user-images.githubusercontent.com/17731877/215892286-f1ac128b-73e2-4d12-82c9-0ca4c99e3642.png">

The first image is simple a linear plot with x axis having value from [0, 500k] at the interval of 1000. So x-axis is [0,1000,2000,..]. And y-axis is literally y=x. Hence y also have y=[0,1000,2000....]. 

Now I take another experiment which have exactly same plot of the metric as above. 
<img width="3184" alt="image" src="https://user-images.githubusercontent.com/17731877/215892939-dbf9bbae-fcf2-489c-8d42-8a120c0d0097.png">

Now when i group the two experiments, the resulting plot should exactly look like them, since both of these are same plots hence averaging or whatever interpolation being used for grouping should result in same plot. But what I am getting is as below:

<img width="3186" alt="image" src="https://user-images.githubusercontent.com/17731877/215893311-d6a4150a-4f1f-4502-a032-ae840afc8781.png">

Problems in above grouped plot:

- The x-axis doesn't start from 0 like the individual plots. With both the individual plots have same x-axis, the resulting x-axis shouldn't be different. 
- The averaging of grouped run isn't correct. for the first point as shown in the plot above it's (999, 500) with min/max:500/500. This is completely wrong data point. Even ignoring that the x point should be 1000 and not 999, the corresponding y should be 1000 with min/max:1000/1000. Please note that min/max are supposed to be actual samples from the individual runs and none of the two runs have point with y coordinate 500. 

### Environment

OS: Ubuntu

Browsers: Google Chrome

Version:

**Comment by dishank-b** [comment]
@nate-wandb can you please have a look at it or please assign someone to this.

**Comment by dishank-b** [comment]
Yeah, I am sorry. it was some mistake on my end. My x-axis were not same of same range. So it was also getting some weird interpolation/extrapolation on x-axis. 

So something like this. 
`
for i in range(2):
  run = wandb.init(project='group_metrics')
     for j in range(500*(i+1)):
        run.log({'train_env_step':j})
  run.finish()
`
In this case, for 1st run, the steps are [0,500] but for 2nd run, it's [0,1000]. For this kind, when doing grouping, x-axis goes weird.

**Comment by luisbergua** [comment]
Thanks for sharing this @dishank-b! I'll then go ahead and close this ticket. Thanks!
