### ISSUE TITLE
[CLI]: 

### ISSUE THREAD

**Issue by saasglue** [wandb/wandb#4888]
### Describe the bug

I'm calling wandb.init in a python file in a nested directory structure. It's failing with the following error:

```ERROR   SenderThread:15661 [sender.py:send_artifact():1417] send_artifact: failed for artifact "job/job-git_github.com_BambooHR_bhr-ai-labs-ml-ops.git_src_com_bamboohr_ai_labs_ml_ops_annotation_projects_enps_sentiment_enps_auto_tag_to_wandb_loader.py": 400 Client Error: Bad Request for url: https://api.wandb.ai/graphql```

```python
run = wandb.init(
            project=project,
            config={
                "tag": classification_tag,
                "origin": "spreadsheet",
                "labeler": "HR",
            },
        )
```

```shell

```

### Additional Files

[run.zip](https://github.com/wandb/wandb/files/10562780/run.zip)

### Environment

WandB version: 0.13.9

OS: macos Monterey 12.6.2

Python version: 3.9.7

Versions of relevant libraries:

**Comment by saasglue** [comment]
There were a few errors in the log - this one is somewhat more descriptive:

`2023-02-01 15:46:57,582 ERROR   SenderThread:15661 [internal_api.py:execute():245] {"errors":[{"message":"invalid artifact name job-git_github.com_BambooHR_bhr-ai-labs-ml-ops.git_src_com_bamboohr_ai_labs_ml_ops_annotation_projects_enps_sentiment_enps_auto_tag_to_wandb_loader.py, must be 128 characters or less","path":["createArtifact"]}],"data":{"createArtifact":null}}`

**Comment by ArtsiomWB** [comment]
Hi @saasglue! Hope everything is well! could you send me your debug.log and internal log files?

**Comment by ArtsiomWB** [comment]
Hi @saasglue, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.
