### ISSUE TITLE
[CLI]: Not able to delete run temp files

### ISSUE THREAD

**Issue by dishank-b** [wandb/wandb#4895]
### Describe the bug

Trying to delete some wandb temporary files of the runs. But when do so with `rm- rf ./path-to-directory/wandb`, I am getting the following error:

`rm: cannot remove 'logs/walker-run/state/default/1/wandb/run-20221215_144315-3uv1m1js/logs/.nfs009a0000224d270500000022': Device or resource busy`

### Environment

WandB version: 0.13.05

OS: Ubuntu

Python version: 3.8

Versions of relevant libraries:

**Comment by dishank-b** [comment]
Solved, there were some wandb processes going the background. Had to kill them to delete these files.

**Comment by lesliewandb** [comment]
Oh that's great! I'll close this ticket out then :)
