### ISSUE TITLE
[CLI]: Endless retry loop when calling init() with id of previously deleted run

### ISSUE THREAD

**Issue by sehoffmann** [wandb/wandb#4897]
### Describe the bug

When calling `wand.init()` with an `id=123` of a run that has previously been deleted via the web interface, the wandb daemon enters an endless retry loop:

>wandb: Currently logged in as: REDACTED. Use `wandb login --relogin` to force relogin
wandb: ERROR Error while calling W&B API: run REDACTED/test/2281463 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run REDACTED/test/2281463 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run REDACTED/test/2281463 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run REDACTED/test/2281463 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run REDACTED/test/2281463 was previously created and deleted; try a new run name (<Response [409]>)
wandb: ERROR Error while calling W&B API: run REDACTED/test/2281463 was previously created and deleted; try a new run name (<Response [409]>)

### Environment

WandB version: 0.13.9

OS: CentOS

Python version: 3.10.8

Versions of relevant libraries:

### Additional Context

This happened because I use the  `SLURM_JOB_ID` as wandb job id and am currently testing continuation of preempted jobs inside an interactive slurm job (i.e. the slurm job id always stays the same). The likeliness of this happening in a real scenario is small in my opinion.

**Comment by ArtsiomWB** [comment]
Hi @sehoffmann! That's a great catch! This is actually an intended behavior. We do have the option to undelete a run, in case someone made a mistake, and because of that in our database, we do still keep that run's ID just in case someone wants to get it back in the future. 

A possible workaround for this would be using mutable features where possible such as:
`run = wandb.init(name = SLURM_JOB_ID)`

Or in the case you need access to an ID before we call `wandb.init()`, you can use `wandb.util.generate_id`.

**Comment by ArtsiomWB** [comment]
Hi @sehoffmann, since we have not heard back from you, we will close this request. If you would like to re-open the conversation, please let us know!

**Comment by sehoffmann** [comment]
@ArtsiomWB Ive just reported a bug in your software, nothing more, nothing less. Whether you intend to fix that or not is up to you. As for my side, I'm completely fine, since the bug only appeared for me in a very specific testing scenario as described in the issue.

**Comment by kptkin** [comment]
Hello @sehoffmann, thanks for reporting the issue. 
I was able to reproduce it. Will be investing the best solution and will update this issue once we have a proper fix. 
Apologies for the inconvenience in the meantime.
