### ISSUE TITLE
[CLI]: wand.save() does not accept pathlib.Path

### ISSUE THREAD

**Issue by sehoffmann** [wandb/wandb#4898]
### Describe the bug

This is contrary to how most python libraries work. For instance, it is perfectly fine to pass a `pathlib.Path` to
* `open()`
* `torch.save()`
* `numpy.save()`
* `xarray.to_netcdf()`
To give just a few examples. Explicitly requiring a string is unexpected and counter-intuitive.

### Environment

WandB version:

OS:

Python version:

Versions of relevant libraries:

**Comment by luisbergua** [comment]
Hi @sehoffmann, thanks for reporting this! I'll create a new feature request to allow passing a `pathlib.Path` to `wandb.save()`, thanks for the feedback!

**Comment by techytushar** [comment]
Hey @luisbergua,
I would like to work on this, can I pick this up ?

**Comment by luisbergua** [comment]
Hey @techytushar, great to hear it! [Here](https://github.com/wandb/wandb/blob/main/CONTRIBUTING.md) you have all the steps to contribute, thanks a lot!
