### ISSUE TITLE
[App]: Incorrect aggregated value in grouped runs 

### ISSUE THREAD

**Issue by Alek96** [wandb/wandb#4907]
### Current Behavior

When we add filter, aggregated values in grouped runs are not being updated.

Before adding filter:
![Screenshot from 2023-02-04 14-27-24](https://user-images.githubusercontent.com/19309791/216770563-9c4442aa-6143-44ea-b7a0-eaa98dba57f4.png)

After adding filter `test/acc > 0.95`
![Screenshot from 2023-02-04 14-28-12](https://user-images.githubusercontent.com/19309791/216770613-33fedae3-971f-49cc-8404-6d20358891f2.png)

Aggregated values in grouped runs are being be updated only after refreshing page.
![Screenshot from 2023-02-04 14-36-47](https://user-images.githubusercontent.com/19309791/216770696-295ecd92-3f5f-4764-a41b-1db576880c8a.png)

### Expected Behavior

Aggregated values in grouped runs should be updated when filters are updated.

### Steps To Reproduce

1. Add a grouping
2. Add a filter

### Environment

OS:
Ubuntu Desktop 22.04 LTS

Browsers:
Brave

Version:

**Comment by luisbergua** [comment]
Hi @Alek96, thanks for reporting this! I just tested this on my end using Brave and it seems runs are updated without needing to refresh the page. Would it be possible for you to share a link to the project where you're seeing this behaviour and so I can have a look at it? Thanks!
