### ISSUE TITLE
[CLI]: Tensorboard is not syncing when experiment started from a container

### ISSUE THREAD

**Issue by terbed** [wandb/wandb#4908]
Tensorboard syncing works correctly when I run it from a local machine:

<img width="366" alt="Képernyőfotó 2023-02-04 - 17 44 04" src="https://user-images.githubusercontent.com/13771341/216779267-ec148199-685f-4310-8de0-432724d968d5.png">

But if I run the exact same code from a remote server (eg.: vast.ai or paperspace instance) then tf sync is not working:
<img width="294" alt="Képernyőfotó 2023-02-04 - 17 46 42" src="https://user-images.githubusercontent.com/13771341/216779320-24800550-3528-4ae1-94be-fa22cd11e7a5.png">

Here is how I init the run

```python
    # init wandb logger
    save_dir = f"./experiments/{hparams.run_name}"
    # create save dir
    os.makedirs(save_dir, exist_ok=True)

    tb_logger = TensorBoardLogger(save_dir=save_dir)
    wandb_logger = WandbLogger(project=hparams.wandb_project, name=hparams.run_name, save_dir=save_dir,
                               tensorboard=tb_logger, sync_tensorboard=True, config=config, log_model=hparams.log_model)
    wandb_logger.experiment.log_code(hparams.config_path)
```

Then tb_logger is used by pytorch_lightning.
It should be correct as it works except for running from remote instances.

### Environment

WandB version: 0.13.8

OS: 

Python version: 3.10

Versions of relevant libraries: 
Tensorboard: 1.15.0

**Comment by lcc815** [comment]
wandb is such a bull s**t !!!!
so hard to use!

**Comment by lcc815** [comment]
wandb is shit.

**Comment by ramit-wandb** [comment]
Hi @terbed,

Could you share the project link, the `debug.log` and `debug-internal.log` files associated to the run? I'll look into this for you.

Thanks,
Ramit

**Comment by terbed** [comment]
Hi @ramit-wandb,

I appreciate your help. 
I am not sure what you mean about the project link. The WandB link of the project? But it is a private link I think:
https://wandb.ai/t3rb3d/orbiting/runs/18wdxzcr?workspace=user-t3rb3d

I attached the debug.log and debug-internal.log files that are associated with the runs. 
[debug-internal.log](https://github.com/wandb/wandb/files/10673770/debug-internal.log)
[debug.log](https://github.com/wandb/wandb/files/10673771/debug.log)

**Comment by ramit-wandb** [comment]
Hi @terbed,

Thanks for sharing the files! They seem to be pretty healthy. Did your experiments generate `.tfevent` files when logging? If those are not generated, we can not sync tensorboard data over.

If they were generated, I would suggest using the `--sync-tensorboard` option with `wandb sync` to try to reupload your data. Please let me know if this helps get your files up, otherwise we can look into this further.

**Comment by terbed** [comment]
Hi @ramit-wandb ,
Sorry for the late response. The `.tfevents` file is generated but not synced during training when started in remote hosts.

Do you suggest running `wandb sync --sync-tensorboard` bash command after training? Ideally, it should sync during the training so I can look into how it progresses.

**Comment by terbed** [comment]
@ramit-wandb 
If I explicitly upload the `tfevent` file before finishing the experiment, it works properly after the run. It is still not working during training. What I experience is across multiple runs and instances (tried it in paperspace and vast.ai with the same results).
Okey, I will try to arrange some time to create a minimal reproduction code for this issue.

**Comment by ramit-wandb** [comment]
@terbed thanks! I'll try on my end as well with Paperspace, but a repro which we know runs into this would be extremely helpful.

**Comment by ramit-wandb** [comment]
Hey @terbed! 

Wanted to check in here with you if you would be able to share a reproduction for us. I tried on my end, but I see the tfevent files syncing correctly.

Thanks,
Ramit

**Comment by ramit-wandb** [comment]
Hi @terbed,

Since we have not heard back from you I will be closing out this issue for now. In case you need further assistance here please feel free to reply to this thread and we can continue the conversation!

Thanks,
Ramit
