### ISSUE TITLE
[Q] Running wandb on ssh server but getting permission denied 

### ISSUE THREAD

**Issue by davnords** [wandb/wandb#4911]
I am training my models on a school cluster to which I use ssh to access. I have a conda environment where I have downloaded and logged into wandb with my API key. In my home directory on the server a .netrc file has been created with the correct API key. Furthermore, when I have activated the conda environment (called pythonenv) it is clearly indicated that I am logged into wandb with the correct account.

However, when I try to run my script using:
bash /opt/local/bin/run_job.sh --env pythonenv --script "/home/2023/davnords/test.py" 

Where inside test.py is the wandb.init with an entity that I should have access to, I get the following error:

Permission denied: '/home/2023'

I believe this is because I don't have full permissions to '/home/2023', I would be very happy if you could help me resolve this issue :)

Many thanks,

David

**Comment by MBakirWB** [comment]
Hi @davnords , happy to help. Is the permissions denied being logged by wandb or your conda environment? Wandb will need a writable folder to store run data. You could try set the `WANDB_DIR` environment variable to a directory that exists and is **writable by you**. For instance a user could add the following to their `~/.profile` or `~/.bashrc` :

`mkdir -p /tmp/$USER`
`export WANDB_DIR=/tmp/$USER`

The default value of `WANDB_DIR` is `./wandb` which means as long as the user is running commands from a directory that has a "wandb" folder in it it would write the log in that folder. `WANDB_DIR` is used to store all intermediate state for any logged runs. Please let me know if this helps or if you still encountering the same issue.

**Comment by davnords** [comment]
Thank you very much for the help. I really appreciate it, pardon me, I am not very experienced in using a remote linux server. 

I am so very grateful for your input.

I will print the error message I receive in my slurm.error file in the screenshot below.

Furthermore, I want to provide some context I received when asking the professor that manages the server: 
"Short answer: We don't allow logins on markov and shannon for students, so you don't have a home there. The error is as intended. You need to tell your software (or wandb) not to write to home." 

Note that I am using the following command to run my script, indicating that it is on the GPU called markov.
`bash /opt/local/bin/run_job.sh --partition gpu-markov --env pythonenv --script test.py`

Lastly, I want to provide the context that I run the standard initialization of wandb in my script
`wandb.init(project="test-project", entity="davnords")` 
but have also tried adding the argument `dir = "/bayes_datainbackup/home/2023/davnords"`

![Screenshot 2023-02-07 at 12 54 36](https://user-images.githubusercontent.com/118268649/217238118-470a91ac-036a-4ee6-a2a4-012f168a0864.png)

**Comment by davnords** [comment]
Just to add on my latest reply: 

I have tried setting the WANDB_DIR="/bayes_datainbackup/home/2023/davnords" which is a directory that, once I run the script using `bash /opt/local/bin/run_job.sh --partition gpu-markov --env pythonenv --script test.py`, is accessible from the node on which the script is running. However, this path is not accessible from where I stand before running the script, as illustrated in the output below:

```
(pythonenv) davnords@bayes:~$ wandb status
wandb: WARNING Path /bayes_datainbackup/home/2023/davnords/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /bayes_datainbackup/home/2023/davnords/wandb/ wasn't writable, using system temp directory
```

Moreover, I have tried to specify my environmental variables in the script like this:
```

import wandb
WANDB_API_KEY="$SECRET$"
WANDB_DIR = "/bayes_datainbackup/home/2023/davnords"
WANDB_CONFIG_DIR = "/bayes_datainbackup/home/2023/davnords/.config/wandb"
WANDB_CACHE_DIR = "/bayes_datainbackup/home/2023/davnords/.cache/wandb"

wandb.login()
```

And I get a similar error just trying to login, where I receive the same error message (PermissionError).

Once again, thank you very much for your patience :)

**Comment by davnords** [comment]
@MBakirWB Hello again! 

Just wanted to let you know that I solved the issue.

I created a .sh file that do the following:

```
#!/bin/bash

export WANDB_API_KEY=(INSERT SECRET KEY)
export WANDB_DIR=/bayes_datainbackup/home/2023/davnords
export WANDB_CONFIG_DIR=/bayes_datainbackup/home/2023/davnords/.config/wandb

echo "This script iniates a run with wandb."
/bin/bash /opt/local/bin/run_job.sh --partition gpu-markov --env pythonenv --script e3-equivariant-VAMPnets/Alani>
echo "Script succesfully deployed to wandb."
```
And now I don't have the issue anymore since wandb writes to a directory that the remote node has write access to.

Thank you much for the help,

Kindest regards,

David
