### ISSUE TITLE
After wandb is deployed locally, how can a user who has not registered with wandb access public projects?

### ISSUE THREAD

**Issue by suiyan538** [wandb/wandb#4919]
![image](https://user-images.githubusercontent.com/120363294/217254801-1c8e51aa-8c6d-4c87-8c6d-571c304d313f.png)

**Comment by lesliewandb** [comment]
Hi @suiyan538, thank you for writing in about this! Can you send me the link to this page so I can look more into why you're running into it? Did this page used to exist before for you and you're running into this 404 afterwards?

**Comment by suiyan538** [comment]
> Hi @suiyan538, thank you for writing in about this! Can you send me the link to this page so I can look more into why you're running into it? Did this page used to exist before for you and you're running into this 404 afterwards?

Thank you very much for your reply, but sorry, I can't post the link of this page.

**Comment by lesliewandb** [comment]
I see. If you're uncomfortable posting it in a public forum, can you please send it to support@wandb.com and put 'For Leslie' in the subject line please? If you still can't then I don't know how to help you out further here
