### ISSUE TITLE
[Q] Cannot create academic team

### ISSUE THREAD

**Issue by tileb1** [wandb/wandb#4940]
Hello,
What is the process for creating a free academic team ? I cannot select academic because "I need a verified academic email address", however, I do have one. Is this restricted to a certain list of institutions ? My institution is @kuleuven.be

![image](https://user-images.githubusercontent.com/43468258/217856616-c603dc0c-e3a2-483e-85ca-49b6f48c1e9f.png)

Thanks in advance!

**Comment by ArtsiomWB** [comment]
Hi @tileb1! Could you talk a bit about your school (a couple of sentences should be enough)? So I make a direct pr to add your domain to our system?

**Comment by tileb1** [comment]
Hi @ArtsiomWB ! Thanks for the quick reply. 

The university is called KU Leuven (https://en.wikipedia.org/wiki/KU_Leuven). It's the biggest university in Belgium with more than 50k students. Here is the linkedin: https://www.linkedin.com/school/ku_leuven/ (domain: @kuleuven.be)

I would like to add people from @epfl.ch in the team. In case that domain is also not present, can you also make a pr for it? The Swiss Federal Institute of Technology Lausanne is a public research university in Lausanne, Switzerland. Specializing in natural sciences and engineering, it is one of the two Swiss Federal Institutes of Technology. Here is the linkedin: https://www.linkedin.com/school/epfl/ (domain: @epfl.ch)

Thanks in advance!

**Comment by ArtsiomWB** [comment]
Thank you so much for sending all of the info! I have added both of the domains to our system and got the pr approved. The changes should take place by eod or tomorrow in the morning. If you are having more issues please let me know and there might be another thing I'll have to do on my side. 

Cheers! :)

**Comment by tileb1** [comment]
Ok, great, it's working now, thank you!

**Comment by MantasLukauskas** [comment]
@ArtsiomWB Hi Artsiom I have quite the same problem I think, because some time ago I was able to create a team, but now I cannot do that. Information about the university: Kaunas University of Technology (ktu.edu), one of the biggest universities of Lithuania, emails domains @ktu.edu (students) and @ktu.lt (researchers)

**Comment by ArtsiomWB** [comment]
@MantasLukauskas Hey Mantas! Could you also give me a few sentences about your school and I'll add it to our system? :)

**Comment by MantasLukauskas** [comment]
@ArtsiomWB Kaunas University of Technology (KTU) is a leading technological university in Lithuania, located in the city of Kaunas. Founded in 1922, KTU has a long history of providing quality education and conducting cutting-edge research in various fields. The university offers a wide range of undergraduate and graduate programs, including engineering, natural sciences, humanities, and social sciences. Webpage: ktu.edu, email domains @ktu.lt and @ktu.edu

**Comment by ArtsiomWB** [comment]
Hi @MantasLukauskas! Let me know if it worked for you :)

**Comment by GiscardBiamby** [comment]
Hi, I have the same issue. My school email domain is berkeley.edu (UC Berkeley).

**Comment by ArtsiomWB** [comment]
Berkley should definitely be part of our system. What is the email and username you are trying to use?

**Comment by GiscardBiamby** [comment]
Hi username and email are both the same: ***@***.***

Here is what I see when I try to create a new team:
[image: image.png]

**Comment by ArtsiomWB** [comment]
Sadly, it wont let me view the picture, could you reshare it?

**Comment by GiscardBiamby** [comment]
Yes, it is working. Thank you!

**Comment by engmubarak48** [comment]
Interesting, so a person should come here on GitHub, and explain their institution in a few sentences to be added? meanwhile, [here](https://wandb.ai/site/research#:~:text=Whether%20you're%20at%20the,%2C%20educators%2C%20and%20university%20researchers.) you mention that it is free for academics. Why not support it automatically via the domain?
