### ISSUE TITLE
[CLI]: Getting ConnectTimeout in offline mode when trying to log an image

### ISSUE THREAD

**Issue by ArneNx** [wandb/wandb#4946]
### Describe the bug

I am running wandb in offline mode since I don’t have an internet connection on the compute nodes that I use for my experiments.
This works fine when I’m logging training loss and other things.
When I try to log images, however, I get the following warning wandb: `Network error (ConnectTimeout), entering retry loop.` and the run waits forever.

The logging happens through:
```python
images = []
for i in range(10):
    images.append(wandb.Image(image[i], caption=f"{caption}.{i}"))
wandb.log({category: images})
```
I can even see that the offline mode is active since I get the following output when I stop the run:
```shell
wandb: You can sync this run to the cloud by running:
wandb: wandb sync /scratch_emmy/outputs/wandb/offline-run-20230208_142336-9685bcf5ea8d5d35ccc9d93b2d035832
```

Maybe this is related to https://github.com/wandb/wandb/issues/2701 ?

### Environment

WandB version: 0.13.9

OS: 22.04.1 LTS

Python version: 3.9

Versions of relevant libraries:

**Comment by kptkin** [comment]
Hi @ArneNx, 

Thanks for reporting this issue. It seems to be same type of errors as the one you linked, but i think it might be due to some other reason. 

I was able to reproduce it on my end and we'll take a look further to find the source of this issue. I will update this issue, with further finding!

Thanks and sorry for the inconvenience!

**Comment by kptkin** [comment]
Hi @ArneNx,

I was able to reproduce the issue you are seeing and it is somewhat related to the other issue you linked. We are working on a PR and it will be available in one of the upcoming releases. Sorry for the inconvenience.

**Comment by ArneNx** [comment]
Hi @kptkin,

that is good to hear, thank you! 
Sorry for not responding here earlier. 
Please let me know if you need anything else from me or if I can test the PR somehow. 
I also opened a thread in the forum earlier. I'll leave a link to this issue there.

**Comment by kptkin** [comment]
@ArneNx Thanks for the suggestions! 

Your reproduction example was very helpful as I was able to reproduce it right away. I will update this issue in case we need further help :) At the current moment we diagnosed the issue, and we are thinking of the best way to fix it.
