### ISSUE TITLE
[Q] how sync deleted run

### ISSUE THREAD

**Issue by Adam-lxd** [wandb/wandb#4948]
Hi, I use wandb to log my training logs. I made it run in offline mode by calling `wandb offline`, and then I synced the log by calling `wandb sync`. Unfortunately, I deleted the run in my dashboard. However, the training continues, and when I try to sync this run again, I get the following:
```bash
wandb: ERROR Error while calling W&B API: run XXX/XXX/run_id was previously created and deleted; try a new run name (<Response [409]>)
```
How can I sync my log again? Because it's still running, can I recover the deleted one and sync it again? Thanks! :)

**Comment by ArtsiomWB** [comment]
Hi @Adam-lxd ! Depending on how long ago you deleted the run, you can try undeleting it inside of the overview page here
<img width="1587" alt="image" src="https://user-images.githubusercontent.com/115654725/218156860-289ac0e9-c681-406f-b4e4-9dc3a3a1b1d4.png">

**Comment by Adam-lxd** [comment]
Hi @ArtsiomWB! Yes, I can sync it now. Thanks for your kind help! :)
