### ISSUE TITLE
[Q] Migrating project assets from one account to another

### ISSUE THREAD

**Issue by pathikg** [wandb/wandb#4949]
How to transfer runs from a project in one account to the project in another account using wandb python API (including all the logged artifacts)?

**Comment by rsanandres-wandb** [comment]
Hello @pathikg!

There is not a way to move projects from one account to another via the API. However, I can help you move projects between accounts. If you would like that, could you provide the following:
- The user who currently has the project
- The project you wish to move
- The user that you wish to have the project moved to

**Comment by pathikg** [comment]
> Hello @pathikg!
> 
> There is not a way to move projects from one account to another via the API. However, I can help you move projects between accounts. If you would like that, could you provide the following:
> 
> * The user who currently has the project
> * The project you wish to move
> * The user that you wish to have the project moved to

Thanks @rsanandres-wandb but I don't need to immediately move the projects but might need it in coming weeks
Though I got this approach using ChatGPT so can you just verify if it is possible to do it in the following way? (I doubt `run.transfer` won't work)
```
get old_wandb project list from wandb.API
For each project in old_wandb :
    set WANDB API KEY for old account
    wandb init(old account/project_name)
    runs = get all runs
    
    set WANDB API KEY for new account
    wandb init(project) on new account 
    for run in runs
       run.transfer("new account/project_name")
```

**Comment by rsanandres-wandb** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.
