### ISSUE TITLE
[Q] Logged table only shows up in artifacts not on run page

### ISSUE THREAD

**Issue by botcs** [wandb/wandb#4955]
Hi, 

Maybe I have missed something, but after I log the predictions and the true labels of my model they only show up in the artifacts and not on the run page.

Furthermore, I tried adding manually a data table on the run page, but it seems to be disabled.

Most probably I am missing something, here's the code I am using (obviously after `wandb.init` has been called

```
batch_id = torch.arange(batch_size)[:, None].tolist()
                # TRAIN: make a table with the true labels, predicted labels and confidence
                train_pred_confidence, train_pred_label = torch.max(train_pred, dim=1)
                table = self.wandb.Table(data=batch_id, columns=["batch_id"])
                table.add_column("true_label", train_y.tolist())
                table.add_column("predicted_label", train_pred_label.tolist())
                table.add_column("confidence", train_pred_confidence.tolist())
                self.wandb.log({"train_predictions": table}, step=strategy.training_counter)
```

**Comment by botcs** [comment]
hmmm, using the `step` seems to be the culprit.
I am planning to log these samples at fixed iterations, what would you suggest for logging the exact iteration time?
(I can just multiply the batch_id with the `strategy.training_counter`)

**Comment by nate-wandb** [comment]
Hi @botcs, is it possible that you are logging to a previous step? Our history store only allows increasing or logging to the same step as the most recent call to `wandb.log()` which may be why removing the step argument fixed this. 

Thank you,
Nate

**Comment by botcs** [comment]
Hmmm, that's a good point - I think it wasn't clear to me that calling `wandb.log(..., step=i)` will be ignored if it's called after `wandb.log(..., step=j)` if `i<j`.

But thanks @nate-wandb for pointing it out! :)
