### ISSUE TITLE
[Q] Is there a way to get GPU info from the API

### ISSUE THREAD

**Issue by diliadis** [wandb/wandb#4958]
Is there a way to retrieve system details like the GPU type through the wandb.Api for a Run object? I tried to find a solution in the documentation but had no luck.

**Comment by billmdevs** [comment]
Hey @diliadis GPU specific meta data is available in a runs wandb-metadata.json file.
To fetch system utilization metrics, this can be done with [run.history()](https://docs.wandb.ai/guides/track/public-api-guide#download-system-metrics-data).

**Comment by diliadis** [comment]
Great, the metadata file has everything I need! I will close the issue.
