### ISSUE TITLE
[Q] Can't find solution to a run error regarding artifact name being too long

### ISSUE THREAD

**Issue by amstrudy** [wandb/wandb#4959]
Hi, 

I'm new to wandb, but really liking the features. I started a new project recently and keep getting this error whenever I run it:

```wandb: ERROR Error while calling W&B API: invalid artifact name <long name here>, must be 128 characters or less (<Response [400]>)```

However, I'm not setting this artifact anywhere--it seems to be autogenerating. So I'm not sure what to change in order to avoid this issue. Thanks!

**Comment by KyleGoyette** [comment]
Hi @amstrudy, I'm sorry about this issue? Can you confirm which version of wandb you are using? If you can update to the latest version and this problem persists, please let us know.

**Comment by amstrudy** [comment]
Hi @KyleGoyette, thanks for the quick response. I was using version 0.13.9, and upgrading to 0.13.10 solved the issue. Thanks!
