### ISSUE TITLE
Detecting Jupyter notebook name no longer works in Google Colab

### ISSUE THREAD

**Issue by ender-wieczorek** [wandb/wandb#4962]
We special case Google Colab when getting the name of Jupyter notebook [here](https://github.com/wandb/wandb/blob/a76ddcef6d6c096ab26a50e2c93573833a638df1/wandb/jupyter.py#L196). This no longer works: `ipynb["metadata"]["colab"]["name"]` no longer exists in the metadata, which results in a `KeyError` exception and we fail to get the notebook name.

Note that the default method of fetching the notebook name works in Google Colab, so we can just remove the special case handling. For now, monkey-patching works:
```
wandb.jupyter.attempt_colab_load_ipynb = lambda: None
```

**Comment by ender-wieczorek** [comment]
Sorry, I should've provided more context. This bug is hit when you do `wandb.init()` and means code saving doesn't work in Google Colab:
<img width="1644" alt="Untitled" src="https://user-images.githubusercontent.com/18293692/219098877-0d18ee41-ff84-4de8-93bc-97f75ae5b153.png">

**Comment by dmitryduev** [comment]
@ender-wieczorek many thanks for the report! should be fixed with #4987 + make it into the next release.
