### ISSUE TITLE
[App]: Logged value epoch cannot be used for x-axis

### ISSUE THREAD

**Issue by ponderbb** [wandb/wandb#4966]
### Current Behavior

Plots that have previously worked with per-epoch logging, suddenly do not work anymore. It has been working for the last few months. Could it be a new update on either `wandb` or `pytorch lightning`?

### Expected Behavior

I would like to log the validation metric per epoch.

### Steps To Reproduce

I am using Lightning AI and their Wandb Logger implementation:

![image](https://user-images.githubusercontent.com/31917221/218883510-877b28e9-d42a-4142-8292-357297149c92.png)

and my logging calls look like the following:

![image](https://user-images.githubusercontent.com/31917221/218883307-9983b99f-2eb7-4d7b-bdf9-330ddf4995c2.png)

### Screenshots

![image](https://user-images.githubusercontent.com/31917221/218884099-7446bf86-4d56-4eeb-8d20-5649329e5a33.png)

### Environment

OS: Linux Server

Browsers: Firefox, Edge

Version: 0.13.5

**Comment by MBakirWB** [comment]
Hi @ponderbb, happy to help. Our apologies for this. We've identified an issue that is causing the behavior above. A fix is released, please let me know if you still run into any issues.

**Comment by ponderbb** [comment]
Thank you for the quick fix!
