### ISSUE TITLE
[Feature]: Add Gymnasium support

### ISSUE THREAD

**Issue by valentin-cnt** [wandb/wandb#4985]
### Description

[Gymnasium](https://github.com/Farama-Foundation/Gymnasium) is the official drop in replacement for Gym. 

When using `monitor_gym=True` in `wandb.init`, wandb is only looking for the non maintaned [Gym](https://github.com/openai/gym). It would be cool to add support of Gymnasium, removing the necessity to have both packages installed in a project.

### Suggested Solution

In the file [wandb/integration/gym/__init__.py](https://github.com/wandb/wandb/blob/main/wandb/integration/gym/__init__.py`) : 
```
vcr = wandb.util.get_module(
        "gym.wrappers.monitoring.video_recorder",
        required="Couldn't import the gym python package, install with `pip install gym`",
    )
```
could also look for `gymnasium.wrappers.monitoring.video_recorder`

**Comment by ArtsiomWB** [comment]
That sounds like a great feature request. I can submit it for you :)
