### ISSUE TITLE
[Feature]: Play button for logged images, plots, etc.

### ISSUE THREAD

**Issue by csparker247** [wandb/wandb#4986]
### Description

I frequently log generated images or plotly plots during runs. While it's fine to drag the slider back and forth to watch these results evolve, it would be really convenient to have a Play button that automatically cycles through the logged data.

### Suggested Solution

Add a Play button (⏵) next to the Step slider for logged series of images and plots. Other media types might be appropriate as well. These are just the ones I use.

### Alternatives

Letting the keyboard arrow keys control the Step slider is a useful alternative. Anything to get the mouse out of the way of the view.

**Comment by ArtsiomWB** [comment]
Hi @csparker247! Sounds like a great feature request. I submitted it for you to our eng team :)
