### ISSUE TITLE
[Q]why this error occurs (wandb.errors.MailboxError: transport failed) 

### ISSUE THREAD

**Issue by EdewagaPoe** [wandb/wandb#5001]
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1133, in init
    run = wi.init()
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 787, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/site-packages/wandb/sdk/lib/mailbox.py", line 271, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
wandb: ERROR Abnormal program exit
[debug.log](https://github.com/wandb/wandb/files/10782494/debug.log)
[debug-internal.log](https://github.com/wandb/wandb/files/10782493/debug-internal.log)

**Comment by kptkin** [comment]
Hi @EdewagaPoe, there could be many reasons, but without additional context, i would suggest you try the following:

- could you try to downgrade the protobuf package to 3.20.x or lower? just going of an error i see in your internal logs `debug-internal.log`:
```
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

Please do let us know if this solved your issue!

**Comment by EdewagaPoe** [comment]
Hi @kptkin 

> Hi @EdewagaPoe, there could be many reasons, but without additional context, i would suggest you try the following:
> 
> * could you try to downgrade the protobuf package to 3.20.x or lower? just going of an error i see in your internal logs `debug-internal.log`:
> 
> ```
> TypeError: Descriptors cannot not be created directly.
> If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
> If you cannot immediately regenerate your protos, some other possible workarounds are:
>  1. Downgrade the protobuf package to 3.20.x or lower.
>  2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
> ```
> 
> Please do let us know if this solved your issue!

it seems that the protobuf has already be 3.20.x
$ pip install protobuf
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: protobuf in /root/.pyenv/versions/3.7.3/lib/python3.7/site-packages (3.20.3)

**Comment by EdewagaPoe** [comment]
i try to run the code again,the problem doesn't occur now.Thank for your help.

**Comment by StevenZhang904** [comment]
I have the same issue here, while I am running on WSL2 ubuntu. 
the bug info is exactly the same, and the log files are:
[debug.log](https://github.com/wandb/wandb/files/12482445/debug.log)
[debug-internal.log](https://github.com/wandb/wandb/files/12482446/debug-internal.log)

**Comment by StevenZhang904** [comment]
wandb.init(project=self.config['project_name'] + '-' + self.model_prefix,
  File "/home/stevenzhang/miniconda3/envs/pretrain/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1183, in init
    raise e
  File "/home/stevenzhang/miniconda3/envs/pretrain/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    run = wi.init()
  File "/home/stevenzhang/miniconda3/envs/pretrain/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 809, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/home/stevenzhang/miniconda3/envs/pretrain/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
wandb: While tearing down the service manager. The following error has occurred: [Errno 32] Broken pipe

**Comment by thisishale** [comment]
I also faced this error. When running on multiple gpus, logging and initializing wandb only on one of the ranks solved my problem.
