### ISSUE TITLE
[CLI]: run.scan_history() has no data

### ISSUE THREAD

**Issue by chs20** [wandb/wandb#5014]
### Describe the bug

Hi, when I run run.history(), I get a sampled version of the history as expected, in particular it contains data. But when I run run.scan_history(), the resulting object contains no actual data.

Consider the following snippet

```python
api = wandb.Api()
runs = api.runs('chs20/scratch-public')
for run in runs:
    history = run.history()
    scan_history = run.scan_history()
    print(f'run: {run.name}')
    print(f'history rows: {len(history)}')
    print(f'scan_history rows: {len(scan_history.rows)}')
```

The resulting output is

```python
run: 2023-02-07_10:48:43
history rows: 524
scan_history rows: 0
```

Related: https://community.wandb.ai/t/scan-history-is-empty/3811/2

### Environment

WandB version: 0.13.10

OS: Ubuntu 20.04.5 LTS

Python version: 3.10.8

Versions of relevant libraries:

**Comment by nate-wandb** [comment]
Hi @chs20, I'm seeing the same behavior but I believe it is simply that there is nothing in the first page of rows. For example:
```
import wandb

api = wandb.Api()
runs = api.runs('chs20/scratch-public')
run = runs[0]

hist = run.scan_history()
hist._load_next() # There is nothing on the first page of rows so we load the next one here

print(len(hist.rows))
```

This will print `1000`. Also, if you iterate through the `scan_history()` object you can see that it does contain data, just not on the first page. 

Let me know if this helps clear this up a bit or if you have any other questions around this. 

Thank you,
Nate

**Comment by chs20** [comment]
I see, thanks for pointing this out :)
