### ISSUE TITLE
documentation error

### ISSUE THREAD

**Issue by bkmi** [wandb/wandb#5030]
On the page introducing the [sweep config](https://docs.wandb.ai/guides/sweeps/define-sweep-configuration), there is an error in the guide.

the yaml looks like
```
metric:
  goal: maximize
  name: validation_loss
```

and says that you must then log the variable `validation_loss`. The code example looks like this

```
wandb.log({
        'val_loss': validation_loss
      })
```

In the yaml, `metric.name` should equal `val_loss`.

**Comment by thanos-wandb** [comment]
Thanks so much @bkmi for reporting this! I created a PR in our Docs repository to actually rename the metric name to `val_loss` instead so as to be more consistent with other examples in same page. This will be merged soon, thanks again for bringing this up.
