### ISSUE TITLE
[CLI]: Cannot sync results to the webseit when set wandb.init(dir='xx') a deep path 

### ISSUE THREAD

**Issue by zhuzhuxia770** [wandb/wandb#5032]
### Describe the bug

When i try to specify 'dir' with a very deep path,  such as '...\Results\CartPolev0\DQN\Hyperparameter_Seeking\2023_02_23_17_07_24\Logs', then it creates a 'wandb' folder in '\Logs' and records everything in local, but no results or tensorboard logs are sync to the website. Then i comment out the 'dir = 'xxxxx'', it creates the 'wandb' folder by default, and everything are able to sync to the website. Why was this happening? Is a deep path not acceptable?

```python

```
    self.wandb_run = wandb.init(
            # dir cannot be to deep, otherwise there is no log on wandb website
            #dir=os.path.join(self.results_root_path, 'Logs'),
            project=self.config.wandb.project,
            entity=self.config.wandb.entity,
            sync_tensorboard=True,
            name=f'{self.config.general.algorithm}_{self.config.general.environment}_{mode[self.mode]}_{self.timestamp}',
            save_code=True
        )
```

<!--- A full traceback of the exception in the quotes below -->
```shell

```

### Additional Files

![image](https://user-images.githubusercontent.com/55032668/220971797-fab56147-e821-4917-beaa-963240aa9d0f.png)
![image](https://user-images.githubusercontent.com/55032668/220972046-5d68028c-216d-4aff-aafe-4db15295fc13.png)

### Environment

WandB version: 0.13.10

OS: Windos10

Python version: 3.9.13

Versions of relevant libraries:

**Comment by nate-wandb** [comment]
Hi @zhuzhuxia770, could you try using `wandb.tensorboard.patch(root_logdir="<logging_directory>")` as shown [here](https://docs.wandb.ai/guides/integrations/tensorboard#how-do-i-configure-tensorboard-when-im-using-it-with-wandb). This should work if wandb is not able to find the Tensorboard folder when using `sync_tensorboard=True`. You will need to remove `sync_tensorboard=True` when using `wandb.tensorboard.patch(root_logdir="<logging_directory>")`

Let me know if that helps!
Thank you,
Nate

**Comment by zhuzhuxia770** [comment]
Hi, thanks for your reply first. Unfortunately, it doesnt work.
![image](https://user-images.githubusercontent.com/55032668/221138685-eb89a714-cd7f-4d2c-903e-002f8a78ee3d.png)
![image](https://user-images.githubusercontent.com/55032668/221139554-8ab9fe65-f176-4e0e-8aa1-3209b548c869.png)
Here is the debug logs of wandb, seems it can find where the tensorboard logs are located, but just cannot sync somehow.
![image](https://user-images.githubusercontent.com/55032668/221139209-d6bbf8e4-c3be-4a6d-8209-fbe2a22a5e76.png)

**Comment by zhuzhuxia770** [comment]
Hi, i found its all because of Windows. Windows has always limited the path length to 260 characters, if the path too long, it will raise a error like this '[WinError 206] then you can not load or save files.  I changed the registry, make it accept strings up to 32,000 long. Then everything works as usual.....
