### ISSUE TITLE
Couldn't find the option in the UI: undelete all the runs that have been deleted for the past 7 days

### ISSUE THREAD

**Issue by leeinscky** [wandb/wandb#5051]
Hey Richard, at the moment you can undelete all the runs that have been deleted for the past 7 days. The option is in the overview section of a project
<img width="303" alt="Screen Shot 2021-09-16 at 16 48 47" src="https://user-images.githubusercontent.com/89597668/133614842-c1cbfd94-8cfb-4878-82bd-2ce273fee139.png">

_Originally posted by @armanhar in https://github.com/wandb/wandb/issues/2659#issuecomment-920873118_

**Comment by leeinscky** [comment]
Hi, I could not find the "Undelete recently deleted runs" in the overview section of a project. Could you provide a more detailed explanation on how to undelete deleted runs?

**Comment by thanos-wandb** [comment]
Hi @leeinscky thanks for reporting this issue. Is it on our SaaS `wandb.ai`, or on a Local W&B instance? if latter, could you please provide your local/server version? if you're on our public cloud, could you then go to this page:
`https://wandb.ai/ENTITY/PROJECT/overview` and then check at the top right corner (below profile icon) for the three vertical dots (similar to your attached screenshot)? if you can't find this option, could you please share a screenshot to help us understand more the issue?

**Comment by thanos-wandb** [comment]
Hi @leeinscky since we haven't heard back from you, I will go ahead and close this ticket for now. If you're still experiencing any issues please let us know and we can keep investigating.
