### ISSUE TITLE
[CLI]: Couldn't save the model when I used the sweep

### ISSUE THREAD

**Issue by Fly-Pluche** [wandb/wandb#5062]
### Describe the bug

when I used the wandb.sweep ,I couldn't save the model.
"Can't pickle local object 'Settings._validator_factory.<locals>.helper'")

```python
def save_model(name,save_path='./checkpoint/',**kargs):

    if os.path.isdir(save_path)==False:
        os.mkdir(save_path)
    torch.save(kargs, f'{save_path}{name}.pth')

save_dict = {
                    'model': model.state_dict(),
                    'config':config
                }
save_model(f'score_{best_eval_score}_' + name,save_path=f'./checkpoint/classify/{WANDB_RUN_NAME}/', **save_dict)
            
```

```shell

```

### Environment

WandB version:
0.13.10
torch version:
1.13.1

**Comment by billmdevs** [comment]
Hi @Fly-Pluche sorry that this is happening to you!
Do you have a stack trace for the failing of this execution?

**Comment by Fly-Pluche** [comment]
Sorry. How can I stack trace for the failing of the execution?
Do you mean this?
![image](https://user-images.githubusercontent.com/73021377/222618890-db0564ef-c244-4b3f-a5e4-442d187d6e73.png)

**Comment by Fly-Pluche** [comment]
The error was caused by config:
type(config)
<class 'wandb.sdk.wandb_config.Config'>
![image](https://user-images.githubusercontent.com/73021377/223360137-8c16e705-ff9d-45cc-87d0-29ff424b8cc4.png)

I tried this and it worded.

```
    dt = {
        'model':model.state_dict(),
        'config':dict(config)
    }
    torch.save(dt,'2.pth')
```
