### ISSUE TITLE
[CLI]: wandb.errors.UsageError: Timeout attaching to run when in offline mode

### ISSUE THREAD

**Issue by RamyE** [wandb/wandb#5071]
### Describe the bug

When I try to access the config of the run object, I get the exception below. However, this only happens when in offline mode; it works fine when in online mode. (note that I am using multiprocessing as shown below and cannot seem to reproduce in the simple two-line code of a single process run=wandb.init; config=run.config). It only works when in online mode, and I can repro 100% when in offline mode.

```python
import multiprocessing
import wandb

def simple_bug_f(wandb_run):
    print("Trying to get config")
    config = wandb_run.config
    print("Got config")

if __name__ == '__main__':
    wandb_run = wandb.init(mode="offline")
    
    ctx = multiprocessing.get_context('spawn')
    pool = ctx.Pool(processes=2)

    futures = []
    for i in range(2):
        future = pool.apply_async(simple_bug_f, args=(wandb_run,))
        futures.append(future)
    
    [future.get() for future in futures]

```

```shell
    config = wandb_run.config
  File "python3.8/site-packages/wandb/sdk/wandb_run.py", line 332, in wrapper
    raise e
  File "python3.8/site-packages/wandb/sdk/wandb_run.py", line 327, in wrapper
    wandb._attach(run=self)
  File "python3.8/site-packages/wandb/sdk/wandb_init.py", line 897, in _attach
    raise UsageError("Timeout attaching to run")
wandb.errors.UsageError: Timeout attaching to run
```

### Environment

WandB version: 0.13.10

OS: Linux

Python version: 3.8

Versions of relevant libraries:

**Also tried in another totally different environment which has python 3.9.10** I see the problem exactly the same

**Comment by RamyE** [comment]
Did some digging and I can see that _attach in wandb_init.py does not have any offline handling code and always assumes online. As per a TODO comment, this code needs to be consolidated with the wandb.init() path which has handling for offline mode.

**Comment by kptkin** [comment]
@RamyE Thanks for reporting this issue! I will take a look at this, but your observation seems to be correct.

**Comment by techytushar** [comment]
Hey @kptkin,
Can I pick this up ?

**Comment by billmdevs** [comment]
Hey @techytushar sure you can! Thank you very much for proposing your help!

**Comment by techytushar** [comment]
@billmdevs I didn't get a chance to look into this, will be working on this over the weekend

**Comment by billmdevs** [comment]
Alright @techytushar  thank you very much!!! I see you pushed a PR. A member of our team is going to review and/or merge or get back to you with some queries.
