### ISSUE TITLE
[CLI]: Wandb [occasionally] fails to shut down sender and handler 

### ISSUE THREAD

**Issue by rdiehlmartinez** [wandb/wandb#5076]
### Describe the bug

I am running a multi-day wandb job on a slurm cluster that requires me every couple of hours to create a new job and resume training from wherever the previous job left off. Currently, I restart a new job by sending a SIGINT signal (every several hours) to my main program which handles this signal by saving a checkpoint to wandb, and launching a new job with the info required to resume training from where it left off. Most of the time this works great, but occasionally wandb will hang when it receives the exit code. The times when it fails, wandb will push up all the files in the current wandb run before exiting, but then will continue to handle keepalive requests, instead of shutting down the sender and handlers. 

I am attaching two sets of debug-internal and debug logs - both were generated by the same run but one comes from an earlier point in training (when wandb correctly handles shutting down and launching a new job) while the other comes from a later point in training (run on a different slurm node) when wandb fails to exit correctly. 

### Additional Files

[debug-internal_failed.log](https://github.com/wandb/wandb/files/10880966/debug-internal_failed.log)
[debug_failed.log](https://github.com/wandb/wandb/files/10880967/debug_failed.log)

[debug_succeeded.log](https://github.com/wandb/wandb/files/10880970/debug_succeeded.log)
[debug-internal_succeeded.log](https://github.com/wandb/wandb/files/10880971/debug-internal_succeeded.log)

### Environment

WandB version: 0.13.11

OS: SL7.9

Python version: 3.8.2

**Comment by kptkin** [comment]
@rdiehlmartinez Thanks for reporting this issue. This seems like a real bug (I assume you meant 0.13.10 as this is the latest release version). This is a really useful information based on your description, it seems that in the exit path we don't shut everything correctly, we will debug this a report our findings and fixes here.

**Comment by rdiehlmartinez** [comment]
@kptkin Thanks for picking this up quickly. Responding, in order, to your questions: 

That's right. On the failed runs, wandb continues to incorrectly upload additional checkpoints. This is strange because there shouldn't be any additional checkpoints, as the training has stopped. During training, I create checkpoints by calling `torch.save(checkpoint, os.path.join(wandb.run.dir, 'latest-checkpoint.pt')` followed by `wandb.save(checkpoint_file, policy="now")`. Wandb's FilePusher class then creates a TemporaryDirectory for me (e.g.  /home/rd654/rds/hpc-work/tmp/tmpbt56956ewandb/ in the log I shared) and saves a temporary copy of a given checkpoint to this directory prior to uploading. If I had to guess, it seems that wandb continues to incorrectly determine that the latest-checkpoint.pt file is changing and keeps adding this file to the queue of files to upload. 

I can add run.finish(), but I recall already having tested this a couple weeks ago and not having observed any difference.

**Comment by kptkin** [comment]
@rdiehlmartinez Thanks for reporting this. We added it to our backlog and we will work on root-causing this and we will update this thread with further information and/or fix when available.

**Comment by billmdevs** [comment]
@kptkin Please could you share with me internally the link to the Jira ticket?

**Comment by dmitryduev** [comment]
hey @rdiehlmartinez, is this still happening with the latest version of the sdk? if so, could you please try what is described in this PR's https://github.com/wandb/wandb/pull/5894 description (and report back here if you find anything interesting)? 🙏🏻

**Comment by sydholl** [comment]
WandB Internal User commented: 
rdiehlmartinez commented: 
@kptkin Thanks for picking this up quickly. Responding, in order, to your questions: 

That's right. On the failed runs, wandb continues to incorrectly upload additional checkpoints. This is strange because there shouldn't be any additional checkpoints, as the training has stopped. During training, I create checkpoints by calling `torch.save(checkpoint, os.path.join(wandb.run.dir, 'latest-checkpoint.pt')` followed by `wandb.save(checkpoint_file, policy="now")`. Wandb's FilePusher class then creates a TemporaryDirectory for me (e.g.  /home/rd654/rds/hpc-work/tmp/tmpbt56956ewandb/ in the log I shared) and saves a temporary copy of a given checkpoint to this directory prior to uploading. If I had to guess, it seems that wandb continues to incorrectly determine that the latest-checkpoint.pt file is changing and keeps adding this file to the queue of files to upload. 

I can add run.finish(), but I recall already having tested this a couple weeks ago and not having observed any difference.

**Comment by sydholl** [comment]
WandB Internal User commented: 
kptkin commented: 
@rdiehlmartinez Thanks for reporting this. We added it to our backlog and we will work on root-causing this and we will update this thread with further information and/or fix when available.

**Comment by rdiehlmartinez** [comment]
> hey @rdiehlmartinez, is this still happening with the latest version of the sdk? if so, could you please try what is described in this PR's #5894 description (and report back here if you find anything interesting)? 🙏🏻


@dmitryduev will check on this in the coming weeks. Thanks for following up on this thread.
