### ISSUE TITLE
[Q] GPU Metric duplication in distributed runs

### ISSUE THREAD

**Issue by micimize** [wandb/wandb#5078]
Hi – I'm running distributed training with https://github.com/mosaicml/composer, which starts a process-per-gpu, resulting in a wandb log/metric stream per-gpu.

This mostly works alright due to grouping, but because each process logs full system metrics, the grouped metric log view has duplicate logs a multiple of the gpus per worker.

Currently it seems to me the most sensible thing to do is maybe to disable system logs for non rank zero workers with `wandb.init(settings=wandb.Settings(_disable_stats=True))`, but I thought I'd see if there's a better way. 

![Screenshot_2023-03-03_08:43:31](https://user-images.githubusercontent.com/8343799/222781308-19b2ca03-8388-40e9-859a-38fd81d04ff4.png)

**Comment by nate-wandb** [comment]
Hi @micimize, this looks like the best solution from my understanding of the problem. You still want to log model metrics from the non-rank 0 processes correct? You would just like to not duplicate system metrics?

Thank you,
Nate

**Comment by micimize** [comment]
Correct. I haven't been able to get the deduplication I was looking for entirely (unexpected ranks still logged, i.e. rank 1, 4, and 5 GPU logs on a 4x4 run) yet but it might be an issue with my approach. I might just ignore this problem and filter out the processes manually as it's just not that big a deal. Code:
```python
is_local_leader = dist.get_local_rank() == 0
if not is_local_leader:
    init_kwargs = kwargs.get("init_kwargs", {})
    init_kwargs["settings"] = init_kwargs.get("settings", {})
    init_kwargs["settings"]["_disable_stats"] = True
    kwargs["init_kwargs"] = init_kwargs

return WandBLogger(**kwargs)
```

Anyhow, as long as wandb doesn't have some particular knob to account for this, like deduplicating system graphs in aggregations based on the specific resource they represent, I think that answers my question sufficiently

**Comment by N33MO** [comment]
Hi @micimize. I have the same issue here when running my experiment. Can you tell me where you implement the code block you mentioned? Thank you.
I also noticed that in this case, GPU# is misleading and GPU0 in different run numbers could be the metrics from different GPUs.

**Comment by micimize** [comment]
@N33MO it was Mosaic ML specific and applied to `from composer.loggers import WandBLogger` before passing into their `Trainer` class. However, I ended up disabling this in favor of basically just ignoring the problem. Most of the time the graphs are a total jumble anyways, and in the event that you do have a single specific GPU issue, you can filter out the other distributed workers from the graph until you've got one of it's lines.

And yes I think the GPU id is just the gpu that winds up with that particular worker
