### ISSUE TITLE
[CLI]: Couldn't use wandb resume in MMDetsection or mmengine, even pass allow_val_change=True to wandb_init

### ISSUE THREAD

**Issue by zgzhengSEU** [wandb/wandb#5085]
### Describe the bug

Couldn't use wandb resume in MMDetsection or mmengine, even pass allow_val_change=True to wandb_init

![image](https://user-images.githubusercontent.com/62554593/223163407-f9badc18-d891-4807-bfb7-cac40a415366.png)

```python

```

```shell

```

### Environment

WandB version: 0.13.10

OS: centos 7

Python version: 3.8.16

Versions of relevant libraries: MMDetecion dev-3.x

**Comment by billmdevs** [comment]
Hi @zgzhengSEU thank you for contacting us and sorry this is happening to you.
I am not understanding your initial statement. Do you mean you could not set the environment varialble WANDB_RESUME or could not run the command argument --resume in sweeps? 
Could you please share with me the script you are trying to run if there is one?

**Comment by zgzhengSEU** [comment]
![image](https://user-images.githubusercontent.com/62554593/223490438-f20bab17-f23a-4051-899b-fefe7f72dc07.png)
I set the wandb init_kwargs  in MMDetection, then i get an error  about  'allow_val_change', but I already set the  allow_val_change=True

**Comment by zgzhengSEU** [comment]
> Bill Morrisson commented: Thank you for providing the script @zgzhengSEU, just to clarify that this is the entire script you are running before getting the errors?

yes, this is the entire script except the id, in my resume runing, i have set the id

**Comment by billmdevs** [comment]
Thank you @zgzhengSEU I will test it out and get back to you.

**Comment by anmolmann** [comment]
Hi @zgzhengSEU, apologies for the delay here. I've notified our internal team which is responsible for this integration with `mmengine`. I'll provide a follow-up as soon as I've an update.

**Comment by willcray** [comment]
I was able to resume using MMDetection (3.2) by passing these three additional lines to the init_kwargs:

```
'resume': 'must',
'id': 'u3aft4jg',
'allow_val_change': True
```

**Comment by fdsig** [comment]
Thanks for updating us here @willcray -- to update you that @ayulockin has also submitted a PR that was merged to fix this issue [here](https://github.com/open-mmlab/mmengine/pull/977). Please do let us know if you experience any further issues and not would you object to me closing off/ resolving this thread?
