### ISSUE TITLE
Using wandb.log() with Multiprocessing (SubprocVecEnv)

### ISSUE THREAD

**Issue by norikazu99** [wandb/wandb#5087]
I am using wandb with stablebaselines3 and wandb.log seems to work fine with a DummyVecEnv. When I attempt to use SubprocVecEnv, wandb.log() returns the following error: 

[
![subproc](https://user-images.githubusercontent.com/115127897/223291799-528f03c9-21e5-45a2-a4f9-09ec7b374e01.png)
](url)

Note: My custom gym environment implements a wandb.log at the end of each step. 

Code to reproduce: 
`project_name = "VectorizedSpeeds"
sweep_id = wandb.sweep(sweep_config, project=project_name)

if __name__ == "__main__":

    def train():
        config_defaults = {
            "env_name": "FuturesEnv",
            "algorithm": "PPO",
            "policy_type": "MlpPolicy",
            "timeframe": "5T",
            "total_timesteps": 50000,
            "vecEnv":"DummyVecEnv",
            "n_envs": 1
        }

        wandb.init(config=config_defaults, project=project_name, sync_tensorboard=True, save_code=True)

        config = wandb.config 

        env = make_vec_env(lambda:FuturesEnv(*get_inds()), n_envs=config.n_envs, vec_env_cls=SubprocVecEnv)
        env.reset()

        experiment_name = f"{config.vecEnv}_{config.n_envs}"
        model = PPO("MlpPolicy", env=env, verbose=0, tensorboard_log=f"runs/{experiment_name}")
        model.learn(total_timesteps=config.total_timesteps, callback=WandbCallback(model_save_path=f"models/{experiment_name}",))

    wandb.agent(sweep_id, train, count=6)`

**Comment by MBakirWB** [comment]
Hi @norikazu99 , thank you for writing in and providing the code to reproduce. Which version of wandb and gym are you using?

**Comment by MBakirWB** [comment]
Hi @norikazu99  since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by Krishnendu1984** [comment]
env_id = "Humanoid-v2"

num_cpu = 8

env = make_vec_env(env_id, n_envs=num_cpu)

#model = SAC("MlpPolicy", env, verbose=1)

models_dir = "sac/SAC_train"
logdir = 'saclogs'



model = SAC('MlpPolicy', env, verbose=1,tensorboard_log=logdir)

TIMESTEPS = 10000
for i in range(1,500):
     model.learn(total_timesteps=TIMESTEPS, reset_num_timesteps=False, tb_log_name="SAC_train")
     model.save(f"{models_dir}/{TIMESTEPS*i}")


Can anyone tell me when I am using multiprocessing to make training faster ,the training data is saving and is much faster training but while testing it is showing error that :Action spaces do not match: Box(-inf, inf, (201,), float64) != Box(-0.5, 0.5, (6,), float32)

**Comment by pasztorb** [comment]
Hi @MBakirWB,
I came across the same issue. Has there been any updates on solving it?
Thanks!

**Comment by norikazu99** [comment]
You can log somewhere else and then upload to wandb at the end of the parallel runs. That's how I do it. You even train faster because you don't have the overhead of logging so I thinks it's the best way of doing it if you're tuning hyperparameters and running many runs.
