### ISSUE TITLE
[CLI]: from wandb.cli.cli import cli ModuleNotFoundError: No module named 'wandb' on wandb login after installing wandb in new venv

### ISSUE THREAD

**Issue by lkp411** [wandb/wandb#5104]
### Describe the bug

After installing wandb inside a new python 3.10.9 conda environment wandb login fails with the following error:

from wandb.cli.cli import cli
ModuleNotFoundError: No module named 'wandb'

### Environment

WandB version: 0.13.10

OS: Ubuntu 20.04.5 LTS

Python version: 3.10.9

Versions of relevant libraries: conda 4.10.1

**Comment by luisbergua** [comment]
Hi @lkp411, thanks for reporting this! Is this issue affecting both python files and notebooks? Also, could you share with me the output of `pip show wandb`?

**Comment by luisbergua** [comment]
Hi @lkp411 , I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by luisbergua** [comment]
Hi @lkp411 , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by luisbergua** [comment]
Hi @OnlinePage, thanks for sharing this! Could you please share with me the pyinstaller script you're running so I can repro this on my end? Also, are you facing this if not using pyinstaller and does it work properly if you uninstall and reinstall wandb?

**Comment by NewbieTM** [comment]
> 

Can you write more about where all this is located:

Got it fixed by manually adding the everything under site-packages/wandb/vendor to `Pysintaller' with add folders command.


I can't find those folders, or am I looking in the wrong place. If you don't mind writing a short guide. Faced the same error

**Comment by stewy33** [comment]
I solved this by running `python -m wandb login` instead of just `wandb login`—this way you give access to the required packages.

**Comment by jasmeetkaur9** [comment]
Hi, 
I am facing a similar issue. Thinsg were working fine but now I can not do wandb.sweep.
I tried `wandb login` and output is 
`from wandb.cli.cli import cli
ModuleNotFoundError: No module named 'wandb.cli'` 

```

Name: wandb
Version: 0.18.7
```
When I tried, `python -m wandb login`, I get ` No module named wandb.__main__; 'wandb' is a package and cannot be directly executed`

**Comment by jasmeetkaur9** [comment]
Hi,
So I figured out what was going on in my case. In my case, there was an empty __init__.py file in the wandb folder. Once I removed it, uninstalled and installed wandb, everything worked as before.  This `python -m wandb login` should work.
