### ISSUE TITLE
[CLI]: `Api.runs` doesn't find runs by ID

### ISSUE THREAD

**Issue by janosh** [wandb/wandb#5122]
### Describe the bug

I'm unable to query runs through the `Api.runs` method by their ID (which you'd expect to be the most robust way to query for runs).

```py
import wandb

runs = wandb.Api().runs(WANDB_PATH, filters={'id': {'$in': ['1ss5gbww']}})  # this ID exists
print(f"matching runs: {len(runs)}")
>>> matching runs: 0
```

### Environment

WandB version: 0.13.10

OS: macOS

Python version: 3.11

Versions of relevant libraries:

### Additional Context

Related https://github.com/wandb/wandb/issues/3830

**Comment by billmdevs** [comment]
Hi @janosh Thank you for bringing this up! I will need to clarify what is happening with some questions if you don't mind.
Do you have a couple of runs in your workspace?
If yes could you please share it? I am suspecting it might have to do with how it is fetched but I am not sure. I will have to test it.

**Comment by janosh** [comment]
Here's the run in question: https://wandb.ai/janosh/matbench-discovery/runs/1ss5gbww

**Comment by thanos-wandb** [comment]
Hi @janosh I wanted to follow up with you on this issue, could you please try if the following code would work for you? This seems to be confusing as the MongoDB that's used for `filters` uses `name` instead of `id`, and I will raise this behavior with the team.

```
runs = wandb.Api().runs(WANDB_PATH, filters={'name': {'$in': ['1ss5gbww']}})  # name instead of ID
print(f"matching runs: {len(runs)}")
```

**Comment by janosh** [comment]
@thanos-wandb That worked! Thanks for the help. I think going forward making my original query using `id` instead of `name` work would be much more consistent.

**Comment by thanos-wandb** [comment]
Hi @janosh glad to hear this works for you, thanks for the confirmation and the feedback. I agree the variable naming to be confusing on this part, therefore I proceeded with a feature request to handle this case. I will now close the ticket, but feel free to reopen it if you have any other questions and we will be happy to investigate further.

**Comment by rubencart** [comment]
None of the below two works for me: `runs` ends up empty. I'm very sure both exist. `wandb` version '0.15.10'.
```
runs = api.runs(project, filters={"name": {"$in": ["2aq6ritz (main, E=2)"]}}, per_page=2500)
runs = api.runs(project, filters={"id": {"$in": ["dh8edmam"]}}, per_page=2500)
```
