### ISSUE TITLE
[Q] PermissionError: [Errno 13] Permission denied: '/var/run/secrets/kubernetes.io/serviceaccount/token'

### ISSUE THREAD

**Issue by weberxie** [wandb/wandb#5134]
`import wandb
wandb.init()
`

 throws this error from     settings["docker"] = wandb.env.get_docker(wandb.util.image_id_from_k8s()).

Could anyone please explain why wandb must get an image id?

Thanks.

**Comment by rsanandres-wandb** [comment]
Hello @weberxie!

We ping the k8s metadata service in order to check if the pod has appropriate permissions. [Here](https://github.com/wandb/wandb/blob/e5e6fac5a449911ab4795f9e4367a6871ddcdb9c/wandb/util.py#L1226) is the line in the code where `image_id_from_k8s()` is defined.

**Comment by kptkin** [comment]
closing as duplicate
