### ISSUE TITLE
[Q]How can I checked GPU usage in wandb??

### ISSUE THREAD

**Issue by feedhj123** [wandb/wandb#5164]
Hi 
I am a student who just started studying computer vision in Korea.
I have a question because I have a question while using yolov5 and wandb.

here is my question 
After creating my project and training the model, I checked the project on wandb and found that there was nothing related to GPU. I didn't seem to need any additional code to refer to other people's codes or docs, so how can I add things related to GPU usage?
[](url)
<img width="919" alt="캡처" src="https://user-images.githubusercontent.com/119566560/225256553-64c3f222-feba-455f-9a29-d3dced7db4cb.PNG">
<img width="544" alt="캡처2" src="https://user-images.githubusercontent.com/119566560/225256578-d9ebef9e-152c-48ca-94dc-96f1866fc870.PNG">
<img width="1665" alt="캡처3" src="https://user-images.githubusercontent.com/119566560/225256600-0488c1d6-4607-4fc3-bf00-b578e258eec9.PNG">
<img width="1676" alt="캡처4" src="https://user-images.githubusercontent.com/119566560/225256616-e1cbd40b-fd88-4094-acca-9fdc9de6b06e.PNG">

**Comment by nate-wandb** [comment]
Hi @feedhj123, do you see this same issue if you run a basic run using the `wandb` repo? For example:
```
import wandb
import time

run = wandb.init(project="testing-gpu-metrics")

for i in range(10):
    run.log({"metric" : i})
    time.sleep(10)
run.finish()
```
I wanted to see if this is isolated to runs coming from Yolo V5

Thank you,
Nate

**Comment by feedhj123** [comment]
Thank you for your answer.

but , The same issue occurs
<img width="1856" alt="캡처" src="https://user-images.githubusercontent.com/119566560/225563696-b157553e-4b71-40c1-87e3-7787edf6b0c8.PNG">
<img width="1862" alt="캡처2" src="https://user-images.githubusercontent.com/119566560/225563705-7deadcdc-156d-4c64-9292-bce5c5d7af81.PNG">
<img width="388" alt="캡처3" src="https://user-images.githubusercontent.com/119566560/225563707-ac588c66-a22e-47f0-9885-c8cf2fff26d9.PNG">

**Comment by nate-wandb** [comment]
Hi @feedhj123, I apologize for the delay on this. Can you check that your GPU drivers are up to date? The GPU logging should appear without having to add any additional code. We use the library `pynvml` to grab GPU metrics so it appears that the library is not recognizing that you are running a GPU.

Thank you,
Nate

**Comment by nate-wandb** [comment]
Hi @feedhj123, I wanted to follow up and see if this was still an issue or if you were able to resolve this?
