### ISSUE TITLE
[CLI]: wandb.init(..., save_code=True) does not behave as expected when running a script outside of the current working directory

### ISSUE THREAD

**Issue by ThomasKierski** [wandb/wandb#5169]
### Describe the bug

If I run a training script located outside of the current working directory (*e.g.*, `python /path/to/my/code/training.py`), the code is not being logged by wandb. If the python script is copied to the current working directory and run (*e.g.*, `python ./training.py`), then the code saving feature works as expected. For both cases, `save_code` is set to `True` and code saving is enabled in the user settings page. I have reproduced this using wandb v0.13.11 and 0.14.0.

I'm not sure if this is a bug, but the [documentation for `wandb.init()`](https://docs.wandb.ai/ref/python/init) does not state that `save_code=True` only works for python scripts located in the working directory.

This snippet can be used to reproduce this behavior:

```python
import wandb
import argparse

def train():
    wandb.init(config=args,project=args.project,save_code=True)
    wandb.log({'dummy_variable': 1})
    wandb.finish()

if __name__ == "__main__":
    
    parser = argparse.ArgumentParser()
    parser.add_argument('-x','--images',help='Path to training images.',default='/workspace/images/',type=str)
    parser.add_argument('-y','--labels',help='Path to training labels.',default='/workspace/labels/',type=str)
    parser.add_argument('-p','--project',help='WandB project name',default='tmp',type=str)
    args = parser.parse_args()

    train()
```

### Environment

WandB version: tested on 0.13.11 and 0.14.0

OS: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.10

Python version: 3.8.13

Versions of relevant libraries: N/A

**Comment by ArtsiomWB** [comment]
Hi @ThomasKierski 

After calling init, could you see if calling `wandb.run.log_code(".")` will change anything for you?
instead of the `.` you can put the directory of the `training.py` file you are running that is not in your working directory. That will upload the whole directory though and not just a single file.

**Comment by ArtsiomWB** [comment]
Hi @ThomasKierski, We wanted to follow up with you regarding your support request and to see if your question was answered :) 

Should I close this ticket for you?

**Comment by yiphei** [comment]
> Hey @ThomasKierski Thanks for bringing this up! I just tested it now on 0.14.0 and I will be filing it in with the engineering team.

@billmdevs @ArtsiomWB  did you actually implement the change? Because this edge case is still not being handled.

> I'm not sure if this is a bug, but the [documentation for wandb.init()](https://docs.wandb.ai/ref/python/init) does not state that save_code=True only works for python scripts located in the working directory.

If you dont intend to handle the edge case, your docs still havent been updated to note this edge case.
