### ISSUE TITLE
[Q] Logging Model Graph and Model Weights Update in Wandb

### ISSUE THREAD

**Issue by varskann** [wandb/wandb#5174]
Hello,

I am looking to log my model weights and graph in wandb, not as an artifact but more as a complete network and relevant model weights upgrade during the training. I am unable to find any relevant documents for this. I am using Pytorch Lightning. 

Is this supported? If yes, any relevant docs?

**Comment by luisbergua** [comment]
Hi @varskann, thanks for your question! Are you setting argument `log_model="all"` when calling the [logger](https://docs.wandb.ai/guides/integrations/lightning#logger-arguments)? Also, you may find useful to [save your model file](https://docs.wandb.ai/guides/track/save-restore) so it'll be accessible under the files tab of the run. Please let me know if any of these helps!

**Comment by luisbergua** [comment]
Hi @varskann, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by luisbergua** [comment]
Hi @varskann, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by varskann** [comment]
> Hi @varskann, thanks for your question! Are you setting argument `log_model="all"` when calling the [logger](https://docs.wandb.ai/guides/integrations/lightning#logger-arguments)? Also, you may find useful to [save your model file](https://docs.wandb.ai/guides/track/save-restore) so it'll be accessible under the files tab of the run. Please let me know if any of these helps!

Hey @luisbergua this stores the model as artifact, I can't see model graph / architecture. Like we see in Tensorboard and/or corresponding weights upgrade for the epoch

**Comment by luisbergua** [comment]
Hi @varskann, thanks for confirming this! I have had a deeper look into this. Setting `log_model='all'` in `WandbLogger` and adding `wandb_logger.watch(model, log="all")` before calling `trainer.fit(model)` will produce:

1. Model tab with the architecture of your model
2. If you go to the artifacts tab -> Files of your model and click on `model_name.ckpt` the model graph is shown with [netron](https://netron.app/)

You can also use [tensorboard&pytorch](https://netron.app/). Please let me know if this is useful or if you'd like to view the graph in a different way!

**Comment by varskann** [comment]
I am currently using tensorboard for the same but wanted to see something similar in a single unified view.

I had tried wandb_logger.watch (https://lightning.ai/docs/pytorch/latest/api/lightning.pytorch.loggers.wandb.html) as well but this doesn't seem to work for me. I don't see any new tab or topology anywhere in the Run Attaching the screenshots for your reference:


<img width="744" alt="Screenshot 2023-03-24 at 6 03 03 PM" src="https://user-images.githubusercontent.com/4751805/227524815-367b48ed-4ef5-4f7c-85fc-e2578a917a56.png">
<img width="1328" alt="Screenshot 2023-03-24 at 6 14 31 PM" src="https://user-images.githubusercontent.com/4751805/227524828-3b8a9a39-c15c-459e-bfa9-ca955f1d71be.png">
<img width="1087" alt="Screenshot 2023-03-24 at 6 14 48 PM" src="https://user-images.githubusercontent.com/4751805/227524839-89e94f8e-0aed-44ae-bfef-0042418ffe21.png">

Am I missing something? I am unable to debug or find any more reference on this

**Comment by luisbergua** [comment]
Hi @varskann, thank you very much for the context! I'm sharing with you an example code which produces:
1. Model tab:
<img width="1510" alt="image" src="https://user-images.githubusercontent.com/113048227/228972765-052f637e-da63-46e6-a1ba-48ee4976b482.png">
2. Model file in the articfacts files tab:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/113048227/228972852-028aa5cf-7c05-4f33-9c8f-de74802bce12.png">

Could you please check it and see if you get the same behavior? Thanks! This is the code:
```
class MyDataset(Dataset):
    def __init__(self, size=100):
        self.size = size
        self.x = torch.randn(size, 10)
        self.y = torch.randn(size, 1)

    def __len__(self):
        return self.size

    def __getitem__(self, index):
        return self.x[index], self.y[index]


class MyModel(LightningModule):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(10, 32)
        self.fc2 = nn.Linear(32, 16)
        self.fc3 = nn.Linear(16, 1)

    def forward(self, x):
        x = nn.functional.relu(self.fc1(x))
        x = nn.functional.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def training_step(self, batch, batch_idx):
        x, y = batch
        y_hat = self(x)
        loss = nn.functional.mse_loss(y_hat, y)
        self.log('train_loss', loss, prog_bar=False, on_step=True, on_epoch=True)
        return loss

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=1e-3)
        return optimizer
    
    def train_dataloader(self):
        train_dataset = MyDataset()
        train_dataloader = DataLoader(train_dataset, batch_size=32, shuffle=True)
        return train_dataloader


if __name__ == '__main__':

    # Instantiate the model
    model = MyModel()

    # Instantiate the wandb logger
    wandb_logger = WandbLogger(project='project_name', entity='entity_name', log_model='all')

    # Initialize PyTorch Lightning trainer with WandbLogger and ModelCheckpoint callback
    trainer = pl.Trainer(logger=wandb_logger, max_epochs=5, callbacks=[ModelCheckpoint(monitor='train_loss', 
                                                                           save_last=True,
                                                                           every_n_epochs=1)])
    
    wandb_logger.watch(model, log="all")
    
    # Fit the model
    trainer.fit(model)
    
    wandb.finish()
```
