### ISSUE TITLE
[App]: Cloning a Tab clones the panel grid

### ISSUE THREAD

**Issue by VanillaWhey** [wandb/wandb#5191]
### Current Behavior

When moving a tab, the entire panel grid is duplicated as well.

### Expected Behavior

Moving the tab only moves the tab.

### Steps To Reproduce

1. Create report
2. Create panel grid
3. Click everything together
4. Move the tab
5. Observe a new copy of that panel grid below the one you're working on

### Environment

OS: Windows 11 and Ubuntu 

Browsers: Chrome, Chromium and Firefox

Version:

**Comment by ArtsiomWB** [comment]
Hi @VanillaWhey! Thank you so much for reporting this! Could you perhaps record a video or send a few screenshots showing this behavior? Our team has tried reproducing it on our side and hasn't been able to do it yet.

**Comment by VanillaWhey** [comment]
Sorry, I was actually wrong, it wasn't the cloning but the moving which I did after every cloning. 
Here is a video of the behavior. Sorry for my sloppy reporting.

https://user-images.githubusercontent.com/35600676/226565939-93b67b38-6351-4aa5-b2e5-cc7f45588f1c.mp4

**Comment by ArtsiomWB** [comment]
Oh, no worries at all! Thank you so much for reporting this, it can definitely become annoying for the users. Thank you, thank you!

**Comment by ArtsiomWB** [comment]
Hi @VanillaWhey! I have been notified that this issue should have been fixed. let met know if you are still seeing it on your side.
