### ISSUE TITLE
Issue in restore a model from wandb in Pytorch as per document (https://docs.wandb.ai/guides/runs/resuming): 

### ISSUE THREAD

**Issue by bikcrum** [wandb/wandb#5194]
### Describe the bug

I am trying to save and load the model after a resume operation using wandb. I am following a code given in the link https://docs.wandb.ai/guides/runs/resuming (Pytorch version). There are two issues:-

Issues in the doc.
1.  `CHECKPOINT_PATH` should be `checkpoint.pt` instead of  `./checkpoint.pt` because the `restore` function looks for `./checkpoint.pt` while resuming the run but it is actually `checkpoint.pt` that is saved in wandb, not the `./checkpoint.pt`

2. `id` must be present in the argument of `wandb.init` as a type string. I guess it is automatically generated but it is of type `int` so the code crashes

After fixing about two issues in the docs, there is another issue which is reported below:-

```python
import wandb
import torch
import torch.nn as nn
import torch.optim as optim

PROJECT_NAME = 'pytorch-resume-run'
CHECKPOINT_PATH = './checkpoint.tar'
N_EPOCHS = 100

# Dummy data
X = torch.randn(64, 8, requires_grad=True)
Y = torch.empty(64, 1).random_(2)
model = nn.Sequential(
    nn.Linear(8, 16),
    nn.ReLU(),
    nn.Linear(16, 1),
    nn.Sigmoid()
)
metric = nn.BCELoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)
epoch = 0
run = wandb.init(project=PROJECT_NAME, resume=True)
if wandb.run.resumed:
    checkpoint = torch.load(wandb.restore(CHECKPOINT_PATH))
    model.load_state_dict(checkpoint['model_state_dict'])
    optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
    epoch = checkpoint['epoch']
    loss = checkpoint['loss']

model.train()
while epoch < N_EPOCHS:
    optimizer.zero_grad()
    output = model(X)
    loss = metric(output, Y)
    wandb.log({'loss': loss.item()}, step=epoch)
    loss.backward()
    optimizer.step()

     torch.save({ # Save our checkpoint loc
        'epoch': epoch,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'loss': loss,
        }, CHECKPOINT_PATH)
    wandb.save(CHECKPOINT_PATH) # saves checkpoint to wandb
    epoch += 1
```

```shell
(ml) ➜  dummy python main.py
wandb: Currently logged in as: bikramp (team-osu). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.14.0 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.13.7
wandb: Run data is saved locally in /Users/bikram/workspace/PycharmProjects/dummy/wandb/run-20230318_000408-15
wandb: Run `wandb offline` to turn off syncing.
wandb: Resuming run 15
wandb: ⭐️ View project at https://wandb.ai/team-osu/pytorch-resume-run
wandb: 🚀 View run at https://wandb.ai/team-osu/pytorch-resume-run/runs/15
Resuming!
Traceback (most recent call last):
  File "/Users/bikram/workspace/PycharmProjects/dummy/main.py", line 28, in <module>
    checkpoint = torch.load(wandb.restore(CHECKPOINT_PATH))
  File "/Users/bikram/miniforge3/envs/ml/lib/python3.9/site-packages/torch/serialization.py", line 772, in load
    if _is_zipfile(opened_file):
  File "/Users/bikram/miniforge3/envs/ml/lib/python3.9/site-packages/torch/serialization.py", line 78, in _is_zipfile
    byte = f.read(1)
  File "/Users/bikram/miniforge3/envs/ml/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 64: invalid start byte
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: / 0.004 MB of 0.004 MB uploaded (0.000 MB deduped)
wandb: Run summary:
wandb: loss 0.71549
wandb: 
wandb: Synced 15: https://wandb.ai/team-osu/pytorch-resume-run/runs/15
wandb: Synced 3 W&B file(s), 0 media file(s), 0 artifact file(s) and 1 other file(s)
wandb: Find logs at: ./wandb/run-20230318_000408-15/logs
```

### Environment

WandB version: 0.13.7

OS: Darwin Bikrams-MacBook-Pro.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000 arm64

Python version: 3.9.10

Versions of relevant libraries:
pytorch:  1.13.0

**Comment by bikcrum** [comment]
I observed while resuming, the `restore()` function downloads the specified model from wandb server and then saves it to a `wandb` local directory. After that, it reads using `open(path)` which does not read in binary mode if the OS is non-Windows. It is necessary to read it in binary mode because `torch.load(...)` expects the model buffer to be in binary mode.

A quick fix is to edit `open(path)` to `open(path, 'rb')` in the following line. I am not sure if this breaks any other operation because `download()` is called from multiple places. 
https://github.com/wandb/wandb/blob/365891d9b803c6b00baad9e77ded03c5a472fddd/wandb/apis/public.py#L2823

I request a PR to update this as soon as possible.

**Comment by kptkin** [comment]
@bikcrum Thanks a lot for the detailed issue. This is a really helpful information. We will take a look and address all the problems you raised. Appreciate this great detailed feedback!

**Comment by rsanandres-wandb** [comment]
Hello @bikcrum!

Thanks for letting us know about the error! I will be updating our internal team about it.

**Comment by bikcrum** [comment]
I also realized that while restoring the file if root path is given, the function will look for a file locally and if it exist it will open it in non-binary mode which also crashes. The `rb` mode has to be added in this line as well

https://github.com/wandb/wandb/blob/365891d9b803c6b00baad9e77ded03c5a472fddd/wandb/apis/public.py#L2816

**Comment by rsanandres-wandb** [comment]
Thank you for bringing this up! I will bring this up with the team.

**Comment by ivanstepanovftw** [comment]
1 year passed

**Comment by ivanstepanovftw** [comment]
It should return path-like string, not io.

**Comment by ivanstepanovftw** [comment]
@rsanandres-wandb  @kptkin

**Comment by ivanstepanovftw** [comment]
Workaround:
```python
with wandb.restore(CHECKPOINT_PATH) as io:
    checkpoint = torch.load(io.name)
```
