### ISSUE TITLE
[Q] How to log the real GPU memory allocation?

### ISSUE THREAD

**Issue by amitabe** [wandb/wandb#5202]
Hi,
First, this product is really amazing! I love it!

I know that wandb logs the GPU memory allocation out-of-the-box, but it does it in percentage (%).

Is there any way to log the memory allocation in gigabytes?

Since my runs get allocated to different GPUs with different memories, I frequently find myself looking at the percentage graph produced by wandb, looking for the used GPU, searching online for its total memory capacity and computing the allocated GPU memory in Gb.

It would be nice to present such a graph out of the box.

Is it doable, or I should submit a feature-request?

**Comment by wamitw** [comment]
Cool, thanks!
Is there any way I can track the feature request/development?

**Comment by amitabe** [comment]
After two months now, is there any update on this issue?

**Comment by rsanandres-wandb** [comment]
Hello! Currently, the feature request not yet on any roadmap but I can bump our team to review the feature request again.

**Comment by amitabe** [comment]
After four months now, is there any update on this issue?
It shouldn't be that complicated...

**Comment by amitabe** [comment]
I see that you added it to the UI, this is great!

![image](https://github.com/wandb/wandb/assets/97161908/c5ce6c35-d6e2-4019-ae2a-7f6a72552b6c)


But can I ask you to make the sizes human-readable? To have it in Mbs or Gbs, and not in bytes? Seeing the following memory allocation is really hard to understand:

![image](https://github.com/wandb/wandb/assets/97161908/8a7e331e-af4b-48d9-91b5-f22ff4541e61)

Thank you! You are doing an awesome job!

**Comment by amitabe** [comment]
Why this issue got closed?
