### ISSUE TITLE
[CLI]: W&B process does not finish in VScode notebooks on a server

### ISSUE THREAD

**Issue by pauliusrauba** [wandb/wandb#5203]
### Describe the bug

When I run wandb on VSCode on an ubuntu server through notebooks, I can never run a second instance by calling wandb.init() again. The last run never finishes to process and I have to restart the whole notebook. Re-importing the library does not help.

Importantly, it does say that "Successfully finished last run (ID:vdr8a51x). Initializing new run". All the data in each run is also logged. The only problem is re-initializing new runs. This is consistent on two separate servers I am working on.

### Environment

WandB version: '0.13.11'

OS: Linux vds-nc12sv3-02vm 5.15.0-1029-azure #36~20.04.1-Ubuntu SMP Tue Dec 6 17:00:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Python version: Python 3.10.9

**Comment by ArtsiomWB** [comment]
Hi @pauliusrauba! Could you send a reproducible code snippet here?

**Comment by ArtsiomWB** [comment]
Hi @pauliusrauba, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
