### ISSUE TITLE
[CLI]: AttributeError: module 'sweeps' has no attribute 'RunState' in wandb.controller

### ISSUE THREAD

**Issue by vrodriguezf** [wandb/wandb#5216]
### Describe the bug

I cannot make wandb.controller work neither in the Python SDK nor in the terminal

```python
sweep_configuration = {
    "name": "my-awesome-sweep",
    "metric": {"name": "accuracy", "goal": "maximize"},
    "method": "grid",
    "parameters": {"a": {"values": [1, 2, 3, 4]}},
}
sweep = wandb.controller(sweep_configuration)
```

```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[11], line 1
----> 1 sweep = wandb.controller(sweep_configuration)

File /usr/local/pip-global/wandb/sdk/wandb_sweep.py:138, in controller(sweep_id_or_config, entity, project)
    119 def controller(
    120     sweep_id_or_config: Optional[Union[str, Dict]] = None,
    121     entity: Optional[str] = None,
    122     project: Optional[str] = None,
    123 ):
    124     """Public sweep controller constructor.
    125 
    126     Usage:
   (...)
    136 
    137     """
--> 138     from ..wandb_controller import _WandbController
    140     c = _WandbController(
    141         sweep_id_or_config=sweep_id_or_config, entity=entity, project=project
    142     )
    143     return c

File /usr/local/pip-global/wandb/wandb_controller.py:82
     74 sweeps = get_module(
     75     "sweeps",
     76     required="wandb[sweeps] is required to use the local controller. "
     77     "Please run `pip install wandb[sweeps]`.",
     78 )
     81 # This should be something like 'pending' (but we need to make sure everyone else is ok with that)
---> 82 SWEEP_INITIAL_RUN_STATE = sweeps.RunState.pending
     85 def _id_generator(size=10, chars=string.ascii_lowercase + string.digits):
     86     return "".join(random.choice(chars) for _ in range(size))

AttributeError: module 'sweeps' has no attribute 'RunState'
```

### Environment

WandB version: 0.14

OS: Linux-5.14.0-1058-oem-x86_64-with-glibc2.31

Python version: 3.9.2

Versions of relevant libraries:

**Comment by luisbergua** [comment]
Hi @vrodriguezf, thanks for reporting this! I just tested it on my end and this works properly for me on version `0.14.0`. Could you try uninstalling wandb and installing it again and see if the issue still raises?

**Comment by vrodriguezf** [comment]
Thanks @luisbergua . I tried reinstalling it but the issue is still there.

**Comment by luisbergua** [comment]
Hi @vrodriguezf, sorry about the delay here! Could you give us some more details about your environment? Was it always the same in every machine? Also, was this issue raised inside a python file or a notebook?

**Comment by vrodriguezf** [comment]
Thanks for chasing this up! This error raises in a terminal running `wandb controller`. I'm working within a VSCode devcontainer, more specifically, the official one for Python 3 applications:
https://github.com/microsoft/vscode-dev-containers/tree/v0.245.0/containers/python-3

**Comment by rsanandres-wandb** [comment]
Hello @vrodriguezf! Just to make sure I am understanding the situation, would running 

```
sweep_id = wandb.sweep(sweep_configuration)

# run the sweep
wandb.agent(sweep_id, function=my_train_func)
```

instead of `wandb.controller()` work in your situation (just like [in this example](https://docs.wandb.ai/ref/python/sweep#examples))? We recommend starting sweeps using `wandb.sweep()` and `wandb.agent()` over `wandb.controller()` but I am curious to understand your use case.

**Comment by vrodriguezf** [comment]
Yes I can run sweeps with wandb.agent, but I want to use controller to allow for running the sweep completely locally, in a machine with no connection to the internet

**Comment by rsanandres-wandb** [comment]
Ah, I understand. It is currently not possible to run a sweep without internet connection since the [sweep](https://github.com/wandb/wandb/blob/c4726707ed83ebb270a2cf84c4fd17b8684ff699/wandb/sdk/wandb_sweep.py#L109) will need to connect to a `wandb` server in order to generate hyperparameter suggestions. A workaround for doing this is hosting your own [local version](https://docs.wandb.ai/guides/hosting/how-to-guides/basic-setup) of `wandb` and logging the sweep there.

**Comment by vrodriguezf** [comment]
I see, thanks!
