### ISSUE TITLE
[Q]wandb: Network error (SSLError), entering retry loop.

### ISSUE THREAD

**Issue by hancan0** [wandb/wandb#5220]

**Comment by kptkin** [comment]
This issue doesn't have any actionable information. i will be closing it. If you want help please provide more information.

**Comment by hancan0** [comment]
When I run proxy software on Windows, like clash, wandb.init () function raises an error（SSLError）

**Comment by hancan0** [comment]
This issue only recently occurred. Previously, I ran the proxy software and wandb simultaneously without causing errors

**Comment by KAWAKO-in-GAYHUB** [comment]
same error! When I run clash on Ubuntu, it raises the same error!
