### ISSUE TITLE
[App]: Downloading CSV from web returns wrong aggregation

### ISSUE THREAD

**Issue by jaromiru** [wandb/wandb#5222]
### Current Behavior

In the web interface, when I click on an grouped graph [More actions]->[Download]->CSV, the provided data have several fields -- especially `__MIN` & `__MAX`. These are irrespective of the selected grouping in the graph (min/max; std dev; std err). 

I.e., irrespective of the graph grouping method, the downloaded file is always the same.

### Expected Behavior

I'd expect the returned file to contain the visualized data, which includes the selected aggregation method.

### Environment

-

**Comment by ArtsiomWB** [comment]
Hi Jaromiru, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by ArtsiomWB** [comment]
Hi @jaromiru, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by jaromiru** [comment]
Hi, this issue has not been solved and it breaks the ease of use when exporting the data directly from GUI. I would expect the CSV to contain the data I see in the graph. However, it is not the case.

Specifically, I can change the aggregation in the GUI, as in here (stddev/stderr/min-max):
![Screenshot from 2023-12-11 14-34-58](https://github.com/wandb/wandb/assets/12935249/e38001e0-4c4e-4940-83ba-bc1e3c4fb2de)

The aggregation changes the data displayed:
![Screenshot from 2023-12-11 14-35-08](https://github.com/wandb/wandb/assets/12935249/8a2faa09-019d-4835-b8ce-8900ddc7d48f)
vs.
![Screenshot from 2023-12-11 14-34-39](https://github.com/wandb/wandb/assets/12935249/46b3f8af-aae9-498d-b958-e06b0213da45)

Well, I'd expect the downloaded CSV to contain this aggregation.
![Screenshot from 2023-12-11 14-40-06](https://github.com/wandb/wandb/assets/12935249/1121632f-b89d-4d16-aec2-6a7dc105c1a7)

This is not the case. Instead, it contains the MIN and MAX data for the datapoints. Two CSV files downloaded with different aggregation in GUI are identical:
![Screenshot from 2023-12-11 14-35-36](https://github.com/wandb/wandb/assets/12935249/a10965d2-232a-4f1c-b574-46f128fbcf1f)

I hope the issue is clear and will be resolved. Thanks.

**Comment by jaromiru** [comment]
@ArtsiomWB please reopen ^
