### ISSUE TITLE
[App]: Modal dialog to adjust visualisation panel filters very often does not work

### ISSUE THREAD

**Issue by pallgeuer** [wandb/wandb#5225]
### Current Behavior

When I'm in the workspace view of a project and I am trying to edit a custom chart, it is possible to configure run filters in the "Query" part of the window. Very very frequently when I click on the drop-down button that has text like "3 filters", the modal dialog where I can adjust those filters fails to open, and the drop-down button just disappears. This is extremely frustrating because it literally stops me from being able to view my run results in a meaningful way until magically a few days later it might work again.

### Expected Behavior

The modal drop down dialog should always work and never crash/disappear.

### Steps To Reproduce

It is unclear what factors/deterministic steps make this happen, but it happens to me so often that just trying a few times on a few days should be enough to see it happen. Once it happens, it is totally consistent in happening every time and completely blocking me from being able to work. I think it tends to happen more on charts that you have to use the arrows to see (more than 12 charts or so).

### Screenshots

Before clicking on 4 filters:
![before](https://user-images.githubusercontent.com/5592992/227268207-c3ab3296-ffea-4717-8afb-c08f6378bfca.png)
After clicking on 4 filters:
![after](https://user-images.githubusercontent.com/5592992/227268202-167939e6-8280-4c66-9087-9ed005209bd1.png)

### Environment

OS: Linux, Android
Browsers: Chrome, Firefox

**Comment by ArtsiomWB** [comment]
Hi @pallgeuer! thank you so much for sending this over. Could you also send a quick video of this happening to you?

**Comment by pallgeuer** [comment]
It seems to be more likely to happen on the second page of charts, hence why in this video I go to charts 7-12 first, and then try to edit one of them.
https://user-images.githubusercontent.com/5592992/227544625-d340d972-4695-4043-b721-7e018dfb3108.mp4

**Comment by ArtsiomWB** [comment]
Your video was awesome! Thank you for sending it over, could you send me a query you are using or the link to your workspace where I could try reproducing this on my end? After that, I could send it straight to our engineering team.

**Comment by pallgeuer** [comment]
Hi, the query is unimportant. I just then reproduced it simply by going Add panel -> Custom chart while on the second page of charts, and then trying to configure a filter.

**Comment by pallgeuer** [comment]
[https://wandb.ai/pallgeuer/cls_cifar10](Project)
It happens for me on the 5th custom chart in the Results section, which is the first chart that's "over the page".

**Comment by ArtsiomWB** [comment]
Big thank you for sending it over! I was able to reproduce this and shared it with our eng team. I'll keep you posted on any updates on this bug ticket? :)

**Comment by pallgeuer** [comment]
Yes please keep this issue updated about bug ticket progress. I continue to encounter the issue all the time.

**Comment by pallgeuer** [comment]
I have noticed another issue with the filter box.
If I keep adding filters until the dialog box gets big enough that it touches the edge of the browser, then the dialog box also disappears and the same issue occurs. I have been working around this by zooming out before opening the dialog box...
Incidentally, that might be the problem in the first place, that the dialog box fails to open like I originally reported if it tries to lay out the dialog, but the dialog would be too big for the current browser state, and then it just crashes and doesn't open.

**Comment by ArtsiomWB** [comment]
Could you send another video for it?

**Comment by ArtsiomWB** [comment]
Thank you for sharing the video. I reproduced this as well and reported it to our eng team.

**Comment by ArtsiomWB** [comment]
Hi @pallgeuer ! I've been notified that this issue has been fixed. Cheers!
