### ISSUE TITLE
[Q] After logging wandb.plot.line() objects to the same key at each step, how can I visualize them?

### ISSUE THREAD

**Issue by hrbigelow** [wandb/wandb#5234]
Hi,

I have the code:

```python
...
for step in range(1000):
    run.log({ 'myplot': wandb.plot.line(tabdata, 'x', 'y') })
```

Is it possible to have some line plot with a 'step slider' underneath, so that I can see how the line plot evolves as I scan through the training steps?

At the moment, I can't figure out how to do this.  It seems that at each training step, a new "version" of the data is produced in some artifact table (see below).

![image](https://user-images.githubusercontent.com/5355286/227426346-2f495458-0449-4fa1-980e-b8eed5fd1da9.png)

**Comment by anmolmann** [comment]
Hi @hrbigelow , I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by anmolmann** [comment]
Hi @hrbigelow, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
