### ISSUE TITLE
[CLI]: wandb.init is altering my flags (Tensorflow)

### ISSUE THREAD

**Issue by wobbba** [wandb/wandb#5238]
### Describe the bug

I have some tensorflow (no keras) code I have to use and it has a function (A) that is called before training starts, altering some of the flags. This works fine without wandb but when I try to pass the FLAGS object as the wandb init config the FLAGS are altered. It resets them to the state they were in before being altered by the function A. No idea why this might happen...

```python
FLAGS = tf.app.flags.FLAGS
config_and_print_log(FLAGS) # A: alters flags
wandb.init(project='TF-DNet', config=FLAGS)
```

### Environment

WandB version: 0.10.33

OS: Linux-5.4.0-125-generic-x86_64-with-debian-bullseye-sid

Python version: 2.7.15

Versions of relevant libraries:
tensorflow-gpu            1.3.0

**Comment by wobbba** [comment]
Ok, this let's me train at least:
```python
import copy
wandb.init(project='TF-DNet', config=copy.deepcopy(FLAGS))
```
Still, when I view the config in the webinterface, it is just the initial config, the changes are not there, although they are applied before init runs.

**Comment by wobbba** [comment]
A better solution seems to be using 
```python
 wandb.init(project='TF-DNet', config=FLAGS.__dict__)
```
This results in the altered values showing up in the webinterface.
Still, this should not require debugging imo, so I'm leaving the issue open for now.

**Comment by kptkin** [comment]
@wobbba 
In the latest version of wandb we dropped support for python2 and we won't be back-porting changes. 
Is there a specific reason you are using  `wandb==0.10.33`, python 2.7 and tensorflow 1? Is it possible for you to upgrade to the latest versions?

**Comment by wobbba** [comment]
The reason I'm using the old versions is that I needed to reproduce the results of a paper using their code which uses these versions, before porting it to PyTorch, so I can show result equality afterwards.

It is odd that you can't reproduce it. The only difference I can think of is that the function altering the flags is imported from another file but I don't see what difference that could make.

In the end, the workaround did the job, I just don't understand what happened to cause this, so I figured maybe it pointed to a bug you'd want to address. But since you already said you'd stopped development for python2 versions, I will close the issue.

Thanks anyway!

**Comment by kptkin** [comment]
@wobbba Thanks a lot for the additional context. 
Very much appreciated the bug report! 
On another note, if you still see the issue in a later version of wandb (with Python3) please feel free to re-open this issue 😊.

Good luck with your reproduction and porting 😄
