### ISSUE TITLE
[CLI]: Unable to sync crashed run 

### ISSUE THREAD

**Issue by alexandrasouly** [wandb/wandb#5239]
### Describe the bug

During my run, the API key I logged in with accidentally got deleted through the website. My run finished, but expectedly could not sync after that. After the run has finished, I have tried running 
```python
wandb sync wandb\path\to\run
```
to sync again with another API jey, but I get the following error:
```shell
Syncing: https://wandb.ai/myteam/myproject/runs/uod93v6h ...Exception in thread Thread-1:
Traceback (most recent call last):
  File "/share/apps/python-3.9.5-shared/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/share/apps/python-3.9.5-shared/lib/python3.9/site-packages/wandb/sync/sync.py", line 215, in run
    sm.send(pb)
  File "/share/apps/python-3.9.5-shared/lib/python3.9/site-packages/wandb/sdk/internal/sender.py", line 171, in send
    assert record_type
AssertionError
```

Is there a way to sync my run?

### Environment

WandB version:
0.10.30.
OS:
Ubuntu
Python version:
3.9.5

**Comment by ArtsiomWB** [comment]
Hi @alexandrasouly! Could you see if syncing to the new run id will work? 
wandb sync [PATH] -p <PROJECT_NAME> -e <ENTITY> --id new_run_id 

Generate the new run id via wandb.util.generate_id(), for example: 
python -c "import wandb; print(wandb.util.generate_id())". 

Let’s see if syncing to a new run_id would resolve the issue.

**Comment by ArtsiomWB** [comment]
We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by happyhappy-jun** [comment]
I get into exact same issue. Revoking my api key during wandb run. 

```
wandb sync [wandb run dir] -p [project] -e [entity] --id=[new run id]
```
this solution works for me
