### ISSUE TITLE
[CLI]: Duplicate docstring in WandbModelCheckpoint callback

### ISSUE THREAD

**Issue by Gladiator07** [wandb/wandb#5241]
### Describe the bug

The argument `save_weights_only` has duplicate docstring in the `WandbModelCheckpoint` callback [here](https://github.com/wandb/wandb/blob/d3a9740846aa204b5de1bb4cd6ea7c1e5174d0e3/wandb/integration/keras/callbacks/model_checkpoint.py#LL59C9-L59C9).

### Environment

None

**Comment by ArtsiomWB** [comment]
Hi @Gladiator07! Thank you for pointing this out! The fix should be merged now! :)
