### ISSUE TITLE
[Q] How to plot differences between runs?

### ISSUE THREAD

**Issue by wobbba** [wandb/wandb#5245]
I'm working with a third party project.

I have 4 runs that together compose one training. They are: Pre-Training, eval1, Fine-Tuning, eval2. I have multiple iterations of this, each identified by a flag `training_ID`. The evals log scalar values for mAP (and others), evaluating the training after which they come. 

I want to plot the increase in mAP that is effected by the Fine-Tuning as a box plot.

I have a Weave query that would do this if it was accepted:
```
runs.filter((row) => row.config["__flags.feat_layer"] == "PreLogits_mean,PreLogits_sig").summary["map"].map((rowM, index) =>
{rowM - runs.filter((row2) => row2.config["__flags.feat_layer"] == "PreLogits").summary["map"][index]})
```
(the feat_layer is used to determine eval1 vs eval2)

Why is this not accepted?
Why is the documentation for Weave so abysmal?

How can I achieve this?

**Comment by wobbba** [comment]
Ok, so I figured out that the tooltip is lying when it says that map can take index as an argument. This explains why it doesn't work. Still why is this so hard? This is such a basic thing to want to do...

**Comment by luisbergua** [comment]
Hi @wobbba, thanks for reporting this, and sorry about the delay here! Weave is still a feature that we're working on so the documentation isn't completed yet but it'll be improved soon as well as the feature itself. Regarding the query you ran, would you mind sharing with me a link to your Workspace so I can have a look at it?

**Comment by wobbba** [comment]
[I hope this is the link you were looking for](https://wandb.ai/ba_ue/TF-DNet/reports/Untitled-Report--Vmlldzo0MDU4MTg3?accessToken=0wese8h6nmnb5rafg5ead292su9x7p9n2bo0itrhmmzchm5mezsaucsczxtymtjh)

Also sorry, I was kinda salty when I made this issue...

**Comment by luisbergua** [comment]
Hi @wobbba, no problem! Thanks for sharing the link. I had a look at the query and the issue is what you mentioned with index. I'll ask internally about this and get back to you.

**Comment by luisbergua** [comment]
Hi @wobbba, apologies for the delay on this. As I mentioned, Weave is still a feature that our team is developing and this was the reason for the lack of docs and some not expected behaviors. In the next months, there'll be an important improvement in this feature and the available documentation. Thank you very much for providing this feedback.
