### ISSUE TITLE
Pyinstaller packaging app throws Module Not Found Error

### ISSUE THREAD

**Issue by OnlinePage** [wandb/wandb#5251]
### Describe the bug

Hi, I trying to pack an app into exe using `Pyinstaller`which is using `wandb `. The app is packaged successfully but on executing it throws below error:

`ModuleNotFoundError: No module named 'wandb_gql'
[3424] Failed to execute script 'DemoProgram' due to unhandled exception!`

The part where `wandb ` is being imported

`
import wandb
from wandb.keras import WandbCallback
import matplotlib.pyplot as plt
`
I believe there should be some kind of `hook` for including `wandb` into the packaged exe while packaging using Pyinstaller.

Kindly refer to above issue..

### Environment

WandB version: 0.12

OS: Winows 11

Python version : 3.9.3

Versions of relevant libraries:

**Comment by thanos-wandb** [comment]
Hi @OnlinePage just wanted to follow up with you on this issue as it seems you've worked out a solution, is that correct? or are there still any issues/questions we could further help with? thanks

**Comment by thanos-wandb** [comment]
Hi @OnlinePage perfect, glad to hear that you've resolved this issue. I will now close the ticket, and please fee free to reach out to us again if you have any other issues or questions.
