### ISSUE TITLE
TypeError: ('train() takes from 0 to 1 positional arguments but 12 were given') [App]: 

### ISSUE THREAD

**Issue by haraldger** [wandb/wandb#5254]
### Current Behavior

I am starting a hyperparameter sweep as per the instructions in the quickstart guides (https://docs.wandb.ai/guides/sweeps/quickstart) but I am encountering the following error message:

"Run 5xep1tqh errored: TypeError('train() takes from 0 to 1 positional arguments but 12 were given')."

It looks like even though I am passing the config object, it is reading 12 different arguments. Possibly, could it be unpacking the config somehow? Strangely enough, my code worked yesterday and I haven't changed anything (as far as I can tell). Any suggestions would be appreciated.

### Screenshots

<img width="468" alt="image" src="https://user-images.githubusercontent.com/55736848/228285840-259c8fe3-abb6-4c33-87ed-8b1b5cd2af8e.png">

<img width="403" alt="image" src="https://user-images.githubusercontent.com/55736848/228285910-a2a97dc2-a847-490e-b440-c05ecf7c6b0e.png">

<img width="897" alt="image" src="https://user-images.githubusercontent.com/55736848/228286018-1b3e86dc-3745-49c5-a3aa-54477e378211.png">

Train function: 

<img width="667" alt="image" src="https://user-images.githubusercontent.com/55736848/228286259-05a0e747-f560-4f41-9721-be9d4eeee4d4.png">

Can provide more screenshots of code if necessary.

### Environment

Running on Google Colab.
Browsers: Google Chrome

**Comment by ubahl** [comment]
I am getting this issue as well.

**Comment by ubahl** [comment]
Turns out the issue occurs if you have another function named `train`. Consider changing the name of the function you pass to the wandb agent.

**Comment by luisbergua** [comment]
Hi @haraldger, thanks for writing in! I just tested on my end with a simple example and it works for me as expected. Is it possible that the issue is having another function named `train` as suggested by @ubahl? For reference, this is the code I'm running:

```
import wandb
import random

metric = {
    "name": "loss",
    "goal": "minimize"
}
parameters_dict = {
    'learning_rate': {"values": [0.001, 0.01, 0.1]},
    'optimizer': {"values": ["adam", "sgd"]}
}
sweep_config = {
    "method": "random",
    "metric": metric,
    "parameters": parameters_dict
}

def train(config=None):
    with wandb.init(config=config):
        config = wandb.config
        for _ in range(10):
            wandb.log({"accuracy": random.random()})

sweep_id = wandb.sweep(sweep_config, project="project", entity="entity")
wandb.agent(sweep_id, function=train, count=5)
```

**Comment by haraldger** [comment]
The issue turned out to be the same as @ubahl above. Thanks all!
