### ISSUE TITLE
[Feature]: Sweep name in the web display

### ISSUE THREAD

**Issue by jlperla** [wandb/wandb#5255]
### Description

I am not sure if this is a bug or a feature request.  Right now if I have a named sweep it does not display in the UI.  See below:
<img width="1716" alt="image" src="https://user-images.githubusercontent.com/13106721/228310773-64993dd9-0aad-4c1e-b269-8d96a9f23be7.png">

Only the sweepid shows, but it would be great if it could show both the id and the name.  

What makes this especially odd is that there is a `rename sweep` option after selecting a sweep, even though you can't actually see the name.  That makes me wonder if I am seeing a bug.

### Suggested Solution

Display both in that UI, or maybe allow it to choose columns.  More generally it would be great to get other sorts of columns there (e.g., the `method`, etc.)

**Comment by luisbergua** [comment]
Hi @jlperla, thanks for reporting this! It's an already known bug so our team is working on a fix for this. Will let you know once this is implemented.

**Comment by luisbergua** [comment]
Hi @jlperla, thanks for your patience here! I just wanted to inform you that our engineers have fixed this issue so now you should see the sweep name in the table. Could you please confirm this?
