### ISSUE TITLE
[Q] Create scatter plot but delete/hide corresponding data table in UI

### ISSUE THREAD

**Issue by svandenhaute** [wandb/wandb#5260]
I use `wandb.plot.scatter` to create scatter plots. The `Table` that needs to be provided for the scatter plot is also shown as an actual table in the UI. Is it possible to delete or hide these Tables by default (or at least move them to a separate panel)?
It makes the interface rather cluttered ...

**Comment by rsanandres-wandb** [comment]
Hello @svandenhaute! 

By default, the `Tables` section should be available and you should be able to hide the Tables section via the `>` as shown in the screenshot I have included. 
![image](https://user-images.githubusercontent.com/122482606/229581423-da382c08-c853-41f6-b641-4e572017c32b.png)
Are you asking if there is a way to only show a certain section (or hide certain sections) automatically?

**Comment by rsanandres-wandb** [comment]
I looked into this issue and I can see the tables being logged with the scatterplot. However, my Tables are being logged to a different section called `Tables` in this [example project.](https://wandb.ai/raph-test/scatterplot+table/runs/qls7v3bn?workspace=user-raphael-sanandres) How are you logging your scatter plots in your code?

**Comment by kptkin** [comment]
closing issue as it is fixed by #6422 . If it still an issue please feel free to open a new ticket.
