### ISSUE TITLE
[App]: Can't override a Docker launch when configure it with the Trigger UI

### ISSUE THREAD

**Issue by juansebashr** [wandb/wandb#5266]
### Current Behavior

Normally when launch a job in the UI, a box appears to put the override configuration like this:
`{
    "args": [],
    "run_config": {},
    "entry_point": []
}`

With a normal launch, it works, but when configuring in the Model Registry trigger doesn't work, has to be put it like this to work:
`{"override": {
    "args": [],
    "run_config": {},
    "entry_point": []
}
}`

### Expected Behavior

The override box in the UI should work the same when launching manually a job or when launching with a trigger

### Steps To Reproduce

1. Go to the Model Registry on the UI
2. Go to create trigger
3. I test it with the alias trigger 
4. Create a trigger with: `{
    "args": [],
    "run_config": {},
    "entry_point": []
}`
5. Launch and see if it overrides the parameters

### Environment

OS: Ubuntu 22.04

Browsers: Chrome

Version: 111.0.5563.110

**Comment by nate-wandb** [comment]
Hi @juansebashr, sorry for the delayed response. Are you still seeing this behavior? There have been several changes to Launch/Model registry recently and I wasn't able to reproduce this.

**Comment by juansebashr** [comment]
No problem!
I will try it and update you of what I find :D

**Comment by nate-wandb** [comment]
Thank you!

**Comment by nate-wandb** [comment]
@juansebashr were you able to confirm if this is fixed for you?
