### ISSUE TITLE
[Feature]: In Tables UI, add option to make column names wrap around

### ISSUE THREAD

**Issue by nikita6187** [wandb/wandb#5269]
### Description

Hello, the column names in the Tables UI are automatically cut off. When manually resizing them (which also takes a lot of time), a lot of whitespace is needed to see the entire column, if the name is a bit longer.

![image](https://user-images.githubusercontent.com/15629332/229049140-118fd6a1-0d60-4b3c-9d4e-8efa2fc40f9a.png)

### Suggested Solution

It would be amazing if we could have the option to wrap around the column names (or alternatively automatically adjust the width to the name).

Thank you!

**Comment by luisbergua** [comment]
Hi @nikita6187, thanks for writing in and suggesting this! I'll create a new feature request and share it with our Product Team!
