### ISSUE TITLE
[Q] Tutorial sweeps and torch.multiprocessing.spawn

### ISSUE THREAD

**Issue by FONSECV** [wandb/wandb#5273]
Hi team,

I would like to know if any of you have a tutorial regarding the use of sweeps with torch.mp.spawn, I've tried to use it for that purpose but got multiple errors and haven't found any examples. thanks in advance.

**Comment by nate-wandb** [comment]
Hi @FONSECV, I don't see any internal examples using `torch.mp.spawn` with sweeps but could you explain a little about how you are looking to use it? 

For example is `wandb.init()` going to be in the processed started by `torch.mp.spawn`?

Thank you,
Nate

**Comment by FONSECV** [comment]
@nate_wandb,

thank you for your reply. I decided to use torchrun instead of mp.spawn, now it is working properly.
