### ISSUE TITLE
[c:api]: wandb.Api().flush() is not working as expected

### ISSUE THREAD

**Issue by meghbhalerao** [wandb/wandb#5285]
### Current Behavior
I am using the wandb api to try to do something like a custom sweep (so that I can do distributed training across machines, this is not related to the Wandb sweep, FYI), by using a run group, but I think this context is not that relevant to the issue. 

So, essentially I have the following loop - 

```
wandb_api = wandb.Api()
for idx, run in enumerate(wandb_api.runs(path = os.path.join(project_name), filters={"group": run_group_name})):
    if run.config["dist_launch_state"] == "started":
         print("some other process has started this run, hence moving to the next run")
   else:
          run.config["dist_launch_state"] == "started"
          run.update()
          do_some_stuff(run.config) here using the run's config
          run.config["dist_launch_state"] = "finished"
          run.update()
    wandb_api.flush()
```
So what I want to do is that I want to run this loop, which essentially executes the `do_some_stuff()` function, and I want to the run this loop in parallel and distributed fashion, potentially across different machines. So what I do is that I run this code snipped in parallel using say python snippet.py where `snippet.py` contains the above for loop snippet. Ideally, what should happen is when I run the jobs in parallel, say the first job has finished running `do_some_stuff()` say 10 times, and hence the `dist_launch_state` of 10 runs has been updated to finished (one of the run, i.e. the last one could be in a started dist_launch_state, i.e the 11th run could be in a started dist_launch_state since there might be some latency in me running the next python snippet.py and since the first job is continuously running it could have started the 11th run, but that is not important to this right now). 

So, now what happens is the second run of the `snippet.py` is that it correctly prints out "some other process has started this run, hence moving to the next run" 10 or 11 times (depending on the exact run states), which is completely expected since the "dist_launch_state" of the run group of those 10 or 11 runs, lets just say 10 for simplicity of notation for now, is either the string started or finished. 

But what happens after this is completely strange and unexpected, now lets say p2 (the second process which is running `snippet.py`) starts the 12th run, it starts the 12th run since the 11th run is started by p1 this runs well and fine. Now, we would expect that p1 (the first process which is running `snippet.py`) will not run the 12th run but will print  "some other process has started this run, hence moving to the next run", since p2 has started this, but this does not happen, rather it runs the 12th run also, and from this point on both the p1 and p2 run all the runs till the end of the run group - say if the run group has 100 runs, p2 will run 100 - 12 runs and p1 will run all 100 runs since it was started first obviously.

I have further tested this issue by running p3 (same notation as above), and it starts at `max(runs(p1), runs(p2))` where runs(p_i) is the number of runs run by the process p_i, and from that point on runs all the runs i.e. p3 will run 100 - max(runs(p1), runs(p2)) runs.

This is not expected at all since it is expected that the runs "see" the centralized wandb server and run only runs for whose `dist_launch_state ` keys are not `started` or  `finished`. 

I think what is happening is that only initially when the processes p1, p2, or p3 start the wandb is getting the run dist_launch_state and there after it is just using that copy of the run dist_launch_state and running the runs, despite me using the `flush()` function, which according to the api docs here - https://docs.wandb.ai/ref/python/public-api/api#flush - must clear the local cache and get the latest state of the runs.

### Environment

OS:
   Static hostname: u124281
         Icon name: computer-server
           Chassis: server
        Machine ID: 1a347b1c907c42bb81d003b8876d5b8b
           Boot ID: 432d800d10b54b43af360314e1145c46
  Operating System: Ubuntu 20.04.4 LTS
            Kernel: Linux 5.4.0-117-generic
      Architecture: x86-64
Browsers:
Safari - this is not relevant imo.
Version:
wandb, version 0.13.10

PS - apologies for the long and verbose issue, but I just want to be clear in what I am saying, thanks!

**Comment by vanpelt** [comment]
You can't change the state of a run directly via the public api, you can only query it.  You can `.stop()` a running run, which should transition it to finished or crashed.  The only way to transition a run from finished to running is by resuming it.

Can you share a brief description of what you're trying to accomplish?

**Comment by meghbhalerao** [comment]
Thanks - sorry I think I was ambiguous in the original post. So, I am not trying to change the state of the run, I am just adding a key called, more specifically, `"dist_launch_state"` to the config dict of the run, via `run.config["dist_launch_state"] = "started"` or `run.config["dist_launch_state"] = "finished"`.
The basic thing that I am trying to accomplish is the following - 
1. I have a run group whichI have already set and it is set in a specific project of wandb, each of the run in this run group has a different config file.
2. What I want to do is, I want to use this run group and using the config files of each of this run in this run group I want to do some model training, so essentially I pass the config dict of each run of this run group by querying the api in a python script a locally run a python script by passing this config dict.
3. But I want to do point number 2 in a distributed fashion across machines, so what I do is I run a python script which loops thru the runs of the run group and gets the config of each of the run using run.config, and since I want to do stuff in a distributed fashion I need some way for the other processes to know if the run has been started or not so I just put a flag in the run.config of this run in the run group which has been started in the loop, this flag is in the form of the string that I have mentioned above "dist_launch_state".
Please do let me know if anything is unclear here.

**Comment by meghbhalerao** [comment]
btw- just to add some further information - I want to access the wandb api multiple times, potentially many 100 of times from the same python script, and each time I access it it must give me the fresh and latest information about the runs, i.e. the latest information stored in a run, say it could be it's config for example. I thought api_object.flush() does this but it is not helping in my case.

**Comment by nate-wandb** [comment]
Hi @meghbhalerao, could you try moving `wandb_api = wandb.Api()` inside of your for loop? I'm not sure why the `flush()` is not working here but reinstantiating the Api should get you the latest data.

**Comment by nate-wandb** [comment]
Hi @meghbhalerao, I wanted to follow up and see if that worked for getting the latest data?

**Comment by meghbhalerao** [comment]
Hi @nate-wandb - thank you for following up. I have put the line `wandb_api = wandb.Api()` inside the loop, but still it is not getting the latest state of the run. However, as I mentioned earlier, if I run the same script another time, it gets the latest state of the runs. Is it something to do with the wandb process which gets started within the python process such that I can get the state of the runs only once in a single wandb process?

**Comment by nate-wandb** [comment]
Hi @meghbhalerao, could you share your updated code. I think I misunderstood your code and didn't realize you are iterating over a value (`wandb_api.runs`) that you get from the `wandb.Api()`. I think you will need to grab the run each time in the loop after reinstantiating the Api() object.

**Comment by nate-wandb** [comment]
Hi @meghbhalerao, do you see the run config getting updated in the app when you run this? I think the issue may be that you need to use `run.config.update()` instead of `run.update()` to update the config on the runs.

**Comment by nate-wandb** [comment]
Hi @meghbhalerao, I just wanted to see if you had a chance to try that out and if you were seeing the config changes reflected in the UI?

Thank you,
Nate
