### ISSUE TITLE
[App]: Not tracking metrics from RCNN from Layout Parser 

### ISSUE THREAD

**Issue by Ammar-Azman** [wandb/wandb#5287]
### Current Behavior

I am running a RCNN model from LayoutParser (https://github.com/Layout-Parser/layout-model-training) and trying to use WandB for model experimentation. But WandB does not showed any metrics or graph after the training end? How can I fix this?

### Expected Behavior

Expected to see graph of metrics like I run Yolov5 before

### Steps To Reproduce

1. Open google colab
2. Git clone https://github.com/Layout-Parser/layout-model-training
3. Setup WandB
4. Run `!bash /content/layout-model-training/scripts/train_prima.sh` 

### Environment

Google Colab

**Comment by ArtsiomWB** [comment]
Hi @Ammar-Azman thank you for writing in. Could you show me how you are setting wandb up?

**Comment by Ammar-Azman** [comment]
Hello @ArtsiomWB . Thank you for your response. I am running the model on Google Colab with the following setup. 
```
!pip install wandb -qU
import wandb

try:
    wandb.login(key='MY_KEY')
    print('Login suceed')
except:
    print("Error happened during login")

```

After the login is succeed, then I run the shell file with `!bash /content/layout-model-training/scripts/train_prima.sh`. As the mode is trained, WandB only collected the system information but no model metrics shown. I tried with ClearML too, but resulted the same.

**Comment by Ammar-Azman** [comment]
Hello @ArtsiomWB . I would like to hear any update on the issue. :)

**Comment by ArtsiomWB** [comment]
Hi, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
