### ISSUE TITLE
[CLI]:  wandb: command not found

### ISSUE THREAD

**Issue by FONSECV** [wandb/wandb#5310]
### Describe the bug

I was using wandb without problems. I had to change my project to another directory and create a new environment. now when trying to use wandb with the following bash file I get wandb command not found, this is the bash file:

#!/bin/bash
#SBATCH -N 1
#SBATCH --partition=batch
##SBATCH --array=1-100%5
#SBATCH -J KNN
#SBATCH -o /ibex/user/fonsecv/Machine_Learning_Course/Notebooks/Notebooks/KNN/output/KNN_Job.%J.out
#SBATCH -e /ibex/user/fonsecv/Machine_Learning_Course/Notebooks/Notebooks/KNN/output/KNN_Job.%J.err
#SBATCH --time=00:10:00
#SBATCH --mem=150G
#SBATCH --reservation=A100
#SBATCH --gpus-per-node=a100:1
#SBATCH --cpus-per-task=8
#SBATCH --constraint=[gpu]

# Set environment variables
source activate MyDefaultA100

# Run the application
wandb --version

I've uninstalled wandb reinstall it again and logged in, but the issue persists. I can call wandb from the command line, but not using the bash file. if I request v100 gpu in my older environment (instead of a100) it works, it also works with v100 in the new environment but not with a100 in none of the environments, which makes me think probably it's not wandb related but not sure.

```python

```

```shell

```I just get this as output in the output.err file:

/var/spool/slurm/job24720616/slurm_script: line 19: wandb: command not found


### Additional Files

_No response_

### Environment

WandB version: wandb, version 0.14.2

OS: Linux

Python version: Python 3.9.15

Versions of relevant libraries:


### Additional Context

_No response_

**Comment by MBakirWB** [comment]
Hi @FONSECV, thank you for writing in. I could think of a few things to consider

- It could be a paths related issue where wandb was not installed correctly or that the path to the package is not included in your system path. Check that the wandb command is in your system path and if it isn't update your shell config file
- Check that the wandb binary is executable by running ls `ls -l $(which wandb)`. The output should show that the file has execute permissions (the x flag should be present in the permissions). If it doesn't, you could make it executable by running `chmod +x $(which wandb)`
- Have you change/updated security/firewall settings recently?

**Comment by MBakirWB** [comment]
Hi @FONSECV, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
