### ISSUE TITLE
[Q] sweep define multiple commands

### ISSUE THREAD

**Issue by Guptajakala** [wandb/wandb#5316]
I'm following this tutorial https://docs.wandb.ai/guides/sweeps/define-sweep-configuration#command-
But in my case, I'm always loading config from a default yaml file. The currently listed options (e.g. argparse, hydra) all do not work for me, if I understand correctly. So I want to execute multiple commands by:

1. Load config from the default yaml file
2. Override the config values by the current sampled sweep's values
3. Write to a new yaml file
4. Run my program and load the newly written yaml file

Is there any easy way to do this?

**Comment by rsanandres-wandb** [comment]
Hello @Guptajakala!

The guide you are looking at in particular is for using [Sweeps](https://docs.wandb.ai/guides/sweeps). If you are attempting to create a sweep, under the CLI tab [here in our docs](https://docs.wandb.ai/guides/sweeps/add-w-and-b-to-your-code#training-script-with-wb-python-sdk) we outline how to create a sweep from a yaml file. Once you define the training script and create an agent for the sweep, the config values will be automatically assigned based on the type [method you define](https://docs.wandb.ai/guides/sweeps/define-sweep-configuration#search-type-methods). Is that what you are asking about or are you using the yaml file in a different way?

**Comment by Guptajakala** [comment]
@rsanandres-wandb 
In the above, I meant I have my own config.yml file, not the sweep yaml file. For a minimal example, I have my own `config.yml` file:
```
name: A
network: resnet
layer_dim: 128
```

Now for sweeping, I want to tune `layer_dim`, so I defined the sweep yaml file following wandb tutorial:
```
program: train.py
method: grid

parameters:
  layer_dim:
    values: [32, 64, 128]
```

The issue is when I launch the agent, it does not override the `layer_dim` in my `config.yml` as expected. I guess it's because I'm not using argparse to fetch the `layer_dim` sampled by the sweep agent?

**Comment by pkuderov** [comment]
Hey @Guptajakala, in our work we do something similar to what you want. You can check out [my example provided in a similar issue](https://github.com/wandb/wandb/issues/2005#issuecomment-1106634054). It is likely a bit too complicated, but I still hope it could be useful to you.

If you need any further help, please let me know :)

**Comment by luisbergua** [comment]
Hi @Guptajakala, wanted to check here if the example provided by @pkuderov worked for you?

**Comment by Guptajakala** [comment]
Hi @luisbergua I haven't tested it out. I ended up with manually adding argparse arguments, since it needs minimal amount of refactorization of my code.
