### ISSUE TITLE
[CLI]: 401 Unauthorized error

### ISSUE THREAD

**Issue by albertfgu** [wandb/wandb#5319]
### Describe the bug

I have set up a GCP VM instance and the wandb login seems fine (the key appears in the `~/.netrc/, etc.).
```
❯ wandb login
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
```
I've also used this setup in other GCP projects with no issues. However on this particular instance, I'm getting errors when I try to call `wandb.init`:

```
>>> wandb.__version__
'0.14.2'
>>> wandb.init(project="hippo")
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
wandb: ERROR Error while calling W&B API: user is not logged in (<Response [401]>)
Problem at: <stdin> 1 <module>
wandb: ERROR The API key is either invalid or missing, or the host is incorrect. To resolve this issue, you may try running the 'wandb login --host [hostname]' command. The host defaults to 'https://api.wandb.ai' if not specified. (Error 401: Unauthorized)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/s4/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    raise e
  File "/opt/conda/envs/s4/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1145, in init
    run = wi.init()
  File "/opt/conda/envs/s4/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 764, in init
    raise error
wandb.errors.AuthenticationError: The API key is either invalid or missing, or the host is incorrect. To resolve this issue, you may try running the 'wandb login --host [hostname]' command. The host defaults to 'https://api.wandb.ai' if not specified. (Error 401: Unauthorized)
```

I did some searching around on the internet and in the wandb issues/discussions and can't see any information about this.

### Environment

WandB version: 0.14.2

OS: Debian GNU/Linux 10 (buster)

Python version: 3.10.10

Versions of relevant libraries:

**Comment by thanos-wandb** [comment]
Hi @albertfgu thanks for reporting this issue. Do you have any `WANDB_` environment variables exported in this VM instance? Are you also logging results to the public cloud `wandb.ai`, or to a local W&B instance?

**Comment by albertfgu** [comment]
You're right, turns out I had a `WANDB_API_KEY` set to a different key, and deleting it fixes the problem. I remember I used to use that workflow; has `WANDB_API_KEY` been deprecated and subsumed by the `wandb login` workflow? Perhaps it could be useful to generate a more informative error message in a case such as mine?

Thanks for the help!

**Comment by kptkin** [comment]
> You're right, turns out I had a `WANDB_API_KEY` set to a different key, and deleting it fixes the problem. I remember I used to use that workflow; has `WANDB_API_KEY` been deprecated and subsumed by the `wandb login` workflow? Perhaps it could be useful to generate a more informative error message in a case such as mine?
> 
> Thanks for the help!

@albertfgu 
`WANDB_API_KEY` wasn't deprecated, but it takes precedence over the key stored in your  `~/.netrc/` file. Can't tell why your setup used to work, but glad it was resolved.
