### ISSUE TITLE
[Q] Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by JieGenius** [wandb/wandb#5322]
When I upgrade wandb-local from 0.28.0 to 0.31.0, I can't open the overview page of past runs. but I can open overview page of newer runs that are created after upgrading to 0.31.0. The error pages as follows:
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/39705429/231342831-7701495f-1cbc-4a1e-ab85-091f7c543502.png">
It is important to note that when I downgraded the image of wandb-local to 0.28.0, the URL of the overview was still accessible.

**Comment by thanos-wandb** [comment]
Hi @JieGenius thanks for reporting this issue. Since you've downgraded to `v0.28.0`, may I please ask what happens with the new runs (created in `0.31.0`), are you able to access these ones too? Also, how did you navigate to this run's url, was it by clicking a link or from home > project > run > overview? Had you tried there to click the ❌ or refresh page icon of this message? 

Could you please provide us with the steps that you followed to upgrade, are you using our Docker image and how did you run the container? I will then try to reproduce the issue following the same steps and see if there was any regression related to `url` creation, and check if you could upgrade to any other intermediate version for now till we fix the issue, such as 0.29.0.

**Comment by JieGenius** [comment]
@thanos-wandb 
I noticed this problem when I upgraded from v0.28.0 to v0.30.0, and then went back to v0.28.0. I updated it after posting v0.31.1 because I thought you might have fixed the bug, but I also found the problem. I navigate this URL as you described. When I click the  ❌ or the button of "Click to refresh the page", nothing changes on the page.

I upgrade docker and run it through the following steps:
`
docker pull wandb/local:0.31.1
docker stop wandb
docker rm wandb
docker run -d --restart=always -v /vol:/vol -p 7065:8080 -e HOST=http://10.x.x.x:7065  --name wandb-local wandb/local:0.31.1
`
I just found that a run generated under v0.31.1 also reports the same error (for older projects, all runs will report this error).
<img width="810" alt="image" src="https://user-images.githubusercontent.com/39705429/231449898-fa62b22b-445e-40e1-a269-fb9c3d168dcc.png">
These three runs were created before 1 hour, and the "different-jazz-45" can't access the overview page, but the other can access the overview page. I don't know why. 

If you need, I can provide some logs in the container that your's system has logged.

**Comment by thanos-wandb** [comment]
Hi @JieGenius thanks so much for the detailed information. The logged data of your runs are still in MySQL db, but for some reason it won't link to the correct URL. 

Would it be possible that you provide us with the Debug Bundle (accessed from top right corner of `/system-admin` page)? You may submit this to support@wandb.com if you'd prefer to not share this publicly (please mention ticket #43835). Also any errors appearing in your Browser Console logs when navigating to these runs would be helpful too.

**Comment by JieGenius** [comment]
I have sent the Debug Bundle through email. If you have any questions, please feel free to ask.

**Comment by thanos-wandb** [comment]
Hi @JieGenius thanks for the `Debug Bundle`, there were several errors in `gorilla.log` file as this one: `"kind":"*errors.errorString","message":"key does not exist"`. I also installed `v0.28.0` and upgraded to `v0.31.1` following same steps as you provided. I wasn't able to reproduce the issue with the Overview page on old logged runs. However, there was an issue with some icons rendering, which was fixed after I logged out and signed in again. Could you please try this and also from an incognito session too?

**Comment by JieGenius** [comment]
When I tried again with the incognito session, I still had the same error. I will share the Network logs through email. Thanks for your time.

**Comment by thanos-wandb** [comment]
Hi @JieGenius could you please try to upgrade to our most recent Local/Server v0.35.0 and see if you're still unable to view the Overview pages of the old runs? Thank you!

**Comment by thanos-wandb** [comment]
Hi @JieGenius since we haven't heard back from you in a while, I will close this ticket for now. Please feel free to reopen it if you're still experiencing any issues and we will be happy to keep investigating!
