### ISSUE TITLE
[Q] Disabling Symlinks in wand.settings.py doesnt work?!

### ISSUE THREAD

**Issue by maba1337** [wandb/wandb#5326]
Hi all,

i tried to use the windows setting in wandb_settings.py 
(https://github.com/wandb/wandb/blob/06117d9651d6e466819b8cac0701ef32364e1586/wandb/sdk/wandb_settings.py#L1503-L1511)

but it doesnt work and using this settings doesnt disable the creation of symlinks? Is this an Issue?

**Comment by nate-wandb** [comment]
Hi @maba1337, are you getting an error when using `wandb` or are you asking if this has the potential to cause problems?

**Comment by kptkin** [comment]
@maba1337 if you are on windows we disable symlink by default you can see in the code you linked, so you don't actually need to do anything to disable it. Do you have by any chance an environment variable  `WANDB_SYMLINK` set to `True`? Also could you check what you get when you run: 
```
import platform
print(platform.system())
```

**Comment by nate-wandb** [comment]
Hi @maba1337, you should be able to `echo %WANDB_SYMLINK%` to see if this has been set

**Comment by nate-wandb** [comment]
Hi @maba1337, did you get a chance to see if this was set?

**Comment by kptkin** [comment]
since we didn't hear from the user closing the issue. re-open if you still facing this issue.

**Comment by jacksonhab** [comment]
HI, I am getting the same problem, and I don't know why. When I run the echo, I get the following

`%WANDB_SYMLINK%`

I am running through a conda environment.
