### ISSUE TITLE
[Feature]: Regex support for files search

### ISSUE THREAD

**Issue by Guptajakala** [wandb/wandb#5331]
### Description

![image](https://user-images.githubusercontent.com/40518028/231648851-6c32060e-0efb-454d-b55e-708f916fa5c2.png)
When searching files, it seems to only search filenames that start with the search keywords. If I search "*pts*", it won't find the file. This is not convenient when I have lots of files. (See above figure)

### Suggested Solution

Enable regex or fuzzy search

**Comment by ArtsiomWB** [comment]
Hi @Guptajakala! Thank you for reporting this. In this case are you saying that if you look up `00100` it will pop up, but if you look up `pts` it wont?

**Comment by Guptajakala** [comment]
@ArtsiomWB Yes, exactly

**Comment by luisbergua** [comment]
Hi @Guptajakala, I just tested on my end and it seems I'm not getting the same behavior as you do. Would you mind sending me a link to your run so I can have a look at this? Thanks!
![image](https://user-images.githubusercontent.com/113048227/233441256-73afd10b-773d-4646-bc00-b67a82c8894f.png)

**Comment by Guptajakala** [comment]
@luisbergua I'm using a local hosted server. Not sure if this [link](https://maglev.wandb.io/research/deform_track_reconstruct/runs/38pahdhn/files?workspace=user-bowenw) works.
On the other hand, I think this issue if not specific to this run. A minimal example to reproduce this maybe
```
wandb.init()
with open('0000000_0000000_depth_cloud.ply','w') as ff:
  ff.write("111\n")
wandb.save('0000000_0000000_depth_cloud.ply')
```
Then you can confirm whether the same issue happens.

**Comment by Guptajakala** [comment]
wandb, version 0.13.3.

@luisbergua 
Thanks for confirming! I think I now know the reason. When I was searching before, I'm not in the first page (see figure where I'm at page 45). After I type the search keywords, it will still assume I'm at page 45 for the searched results too. But in reality, the searched results have less pages (e.g. 5 pages). 
![image](https://user-images.githubusercontent.com/40518028/234072589-59cd4bac-2eb1-45bb-8431-b40065fbc482.png)

This means it's always a good practice to first jump to page1 before searching. I think it'd be better if this UI could be improved such that the searching will always reset the page (Like in google, when you change the kewords and search again, you are back in page1). Or if this is not feasible, remind the user to manually jump back to page1 before searching.

**Comment by luisbergua** [comment]
Thanks for sharing this @Guptajakala! I was able to reproduce the same behavior as you do so I'll share your feedback internally with our team!

**Comment by sydholl** [comment]
WandB Internal User commented: 
Guptajakala commented: 
@ArtsiomWB Yes, exactly
