### ISSUE TITLE
Images not synced anymore

### ISSUE THREAD

**Issue by henrik-schopmans** [wandb/wandb#5332]
### Describe the bug

Since roughly two days ago, images are not syncing from python to the wandb backend properly. I didn't really change anything, at least nothing that I know of.

The image does not appear in "Files" on the webapp and in the "Media" tab, the following message appears:
`Select runs that logged image with the key test to visualize data here.`
In the local run diectory, the image is present ("files/media/images").

```python
import wandb
import matplotlib.pyplot as plt

wandb.init(project="test123", config={"test": 1})

fig = plt.figure()
plt.plot([1, 2, 3])
wandb.log({"test": wandb.Image(fig)})

wandb.finish()
```

```shell

```

### Environment

WandB version: 0.14.2

OS: Pop!_OS 22.04 LTS

Python version: 3.8.0

Versions of relevant libraries:

**Comment by allanchan339** [comment]
Same here, 
Either loading like : 
![image](https://user-images.githubusercontent.com/38370649/231691070-340b5236-dfb4-4eda-a9a1-84856db86dd3.png)
or showing me : 
![image](https://user-images.githubusercontent.com/38370649/231691146-6c46b282-fd2b-4080-9e02-ebf90c35480a.png)

I have no change of any single line of code and the image syncs ( logging) work well last night

**Comment by AndreiCComan** [comment]
Hello,

+1 on this. I am experiencing the same issue when logging Plotly figures.

**Comment by zimmer-m** [comment]
+1 on this, I am experiencing the same issue when saving arbitrary files to the wandb directory, they are not uploaded.

MWE:
```

import wandb
import os

wandb.init(project="test-000", config={"test": 1})

path = os.path.join(wandb.run.dir, "my_file.txt")
with open(path, 'w') as f:
    f.write("This is in the file.")

wandb.finish()
```

Output log of the script (*** censored):
```
python mwe.py 
wandb: Currently logged in as: ***. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.14.2
wandb: Run data is saved locally in /Users/***/Desktop/wandb/run-***
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run rose-totem-3468
wandb: ⭐️ View project at https://wandb.ai/***/test-000
wandb: 🚀 View run at https://wandb.ai/***/test-000/runs/***
wandb: Waiting for W&B process to finish... (success).
wandb: 🚀 View run rose-totem-3468 at: https://wandb.ai/***/test-000/runs/***
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 1 other file(s)
wandb: Find logs at: ./wandb/run-***/logs
```

The file exists in the wandb directory, however it is not available from the webinterface!

**Comment by thanos-wandb** [comment]
Hi @zimmer-m @AndreiCComan @allanchan339 @henrik-schopmans thanks for reporting the issues, we have flagged this issue and looking into it. However, please note that since the files are stored locally in the `wandb/run-<date-time>-<run-id>` directories it would be mostly recommended that you won't delete them till the issue is resolved, in case you may need to `sync` afterwards.

**Comment by Leezp99** [comment]
I also encountered this problem by using wandb.Audio

**Comment by PiotrDabkowski** [comment]
Same here, it has been like this for 12 hours already at least!

**Comment by ClemensSchwarke** [comment]
Applies to all files for me :/

**Comment by thanos-wandb** [comment]
Hi @everyone here, we are working with GCP support to resolve this issue with slow processing of the files, these should eventually show up in UI. 

We have updated our status page with some more information, and I will keep you posted here on any further updates: https://status.wandb.com/

**Comment by CeHao1** [comment]
I encountered this problem as well. Just about 10 hours ago. Looking forward to your fix.

**Comment by thanos-wandb** [comment]
Hi everyone, the engineering team identified and resolved the underlying issue. We have now fully caught up to the backlog of messages, and the files should be visible in the UI.

We really appreciate your patience and understanding during this long-running issue. Please let me know if you're still experiencing any such issue, and we will be happy to keep investigating.

**Comment by TianrongChen** [comment]
@thanos-wandb Hello,I think I am encountering exact same problem just now... it is either loading or shows nothing...
<img width="525" alt="image" src="https://github.com/wandb/wandb/assets/42562954/a910efec-d1f2-4b2c-92d5-4dd3ecff2041">
<img width="525" alt="image" src="https://github.com/wandb/wandb/assets/42562954/a1050bd0-b1dc-43d5-9b95-82a434193a64">

But when I kill the code, the figures will be automatically synced to the wandb...

**Comment by kartikmadhira1** [comment]
Having the same trouble, Images don't seem to be syncing live. However, when I terminate the script, I am able to download the images. 

![images](https://github.com/wandb/wandb/assets/16814100/f58b3ed0-458b-4c86-85c2-815c765d0c2f)


System info:

W&B CLI Version : 0.13.5
Python version : 3.7.6
OS: Linux-5.15.0-97-generic-x86_64-with-debian-bullseye-sid
