### ISSUE TITLE
[CLI]: step not useful for sub-processes

### ISSUE THREAD

**Issue by Ericonaldo** [wandb/wandb#5333]
### Describe the bug

The step is always reset by `_set_run_obj`.

We cannot let the sub-process to store the data in the desired step.

Add a debug print before https://github.com/wandb/wandb/blob/7f5316b6b7c984c4a8a40983dca6e89502c8838f/wandb/sdk/wandb_run.py#L1401

```
if 'debug' in row:
    print('_partial_history_callback', row, step, self._step, self._starting_step, self)
```

Then run the following snippet

```python
import wandb
from multiprocessing import Process

def record(step, run):
    run.log({"debug": True,"global_step": step}, step=step, commit=True)

wandb_run = wandb.init()
for i in range(5):
    p = Process(target=record, args=(i, wandb_run))
    p.start()
```

We will find that in sub process the self._step is always 0 so we cannot sync the step and store related data.

### Environment

WandB version: 0.14

OS: Linux

Python version: 3.10

Versions of relevant libraries:

**Comment by luisbergua** [comment]
Hi @Ericonaldo, thanks for reporting this! I tested the code you provided and I get this warning:
`wandb: WARNING Note that setting step in multiprocessing can result in data loss. Please log your step values as a metric such as 'global_step' `
It seems that removing `step=step` when calling` run.log()` works fine, could you please try this and see if it works for you?

**Comment by Ericonaldo** [comment]
No, the problem still exists and the `self._step` always prints as zero. Actually I am trying to store videos in sub process and I find the saved video always named as 0 step.

**Comment by luisbergua** [comment]
Apologies about the delay here @Ericonaldo. I tested on my end with the code you provided, getting this plot:
![image](https://user-images.githubusercontent.com/113048227/236199670-15717960-e18e-4fd5-9ec0-12a9bd1cc7a4.png)
Where every step `global_step` seems to be logged properly. Could you please explain to me what are you expecting to see in that plot?

**Comment by luisbergua** [comment]
Hi @Ericonaldo, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
