### ISSUE TITLE
[App]: WandB reports UI very finnicky

### ISSUE THREAD

**Issue by kdu4108** [wandb/wandb#5336]
### Current Behavior

Several annoying/finnicky behaviors when trying to create Reports in WandB:
* When I try to use the arrow key to navigate across different textboxes, the cursor follows initially, but when I start to type, the text appears in my cursor's previous position.
* When I try to use ctrl + arrow key or fn + arrow key in order to quickly navigate to the end of a word/line and then type, the cursor follows but when I start to type the text appears in my cursor's previous position.

The Reports feature is really cool to keep things in one place, but the text editing feels buggy to the point where using it is a pain and I'm inclined to write up reports in google docs instead with linking wandb charts :/. Thanks!

### Expected Behavior

When the cursor is directed to a place in the text and I start typing, the new letters should appear where my cursor is now, not where it was a few seconds prior.

### Environment

OS: Ubuntu 22.04

Browsers: Chrome Version 111.0.5563.146 (Official Build) (64-bit)

**Comment by MBakirWB** [comment]
Hi @kdu4108 , we appreciate you writing in with your feedback. Could you please provide me a screen recording of the behavior you are experiencing and the browser/version you are using. Thanks

**Comment by kdu4108** [comment]
Hi, it turns out after restarting my computer today the problems disappeared. I'll write back if it restarts again. Thanks!
