### ISSUE TITLE
[App]: In model registry, the "+" for the alias gets hidden if there are too many aliases

### ISSUE THREAD

**Issue by ChiaraMC** [wandb/wandb#5338]
### Current Behavior

If there are "too many" aliases already associated with an artifact in model registry (in my case, four seems to be too many), the "+" button to add a new one gets pushed out of view, and can't be reached (it does not scroll). In order to be able to click it, we need to zoom out.

Standard view:
<img width="603" alt="Screenshot 2023-04-13 at 17 54 13" src="https://user-images.githubusercontent.com/14994827/231831221-0d640f75-17fc-4ac2-b081-7ddb5817ac55.png">

Zoomed out:
<img width="663" alt="Screenshot 2023-04-13 at 17 54 07" src="https://user-images.githubusercontent.com/14994827/231831256-dff59000-c73b-49f5-ba41-9e15d9d48852.png">

The same thing happens on a standard Artifact page.

### Expected Behavior

We should be able to add another alias without needing to zoom out

### Steps To Reproduce

1. Create an artifact
2. From the artifact page, add several aliases until they don't fit in the available space

### Environment

OS: MacOs 12.5.1 

Browsers: Chrome

Version: 0.14.0

**Comment by rsanandres-wandb** [comment]
@ChiaraMC This has been fixed in the Web App and you should now be able to see all your aliases and the `+` for Models and Artifacts!

**Comment by ChiaraMC** [comment]
Hi @rsanandres-wandb , amazing thank you!
