### ISSUE TITLE
[App]: Scatterplot does not show data with missing-value labels

### ISSUE THREAD

**Issue by avm19** [wandb/wandb#5343]
### Current Behavior

Scatterplot **does not** show run data whose "Labels" values have a missing value.

### Expected Behavior

Scatterplot **shows** run data whose "Labels" values have a missing value. The missing value is denoted with "N/A" or with a dash (like in the Table).

### Steps To Reproduce

1. Have several runs with a config parameter or a summary metric, such that some runs **have** this parameter and some other runs **do not have** this parameter. Such a situation occurs naturally when the model structure is modified, and a new parameter is added to the config to reflect the change. For example, one may add a preprocessing step.
2. Go to Workspace.
3. Create a Scatter plot in such a way that it shows all runs.
4. In the "Labels" Tab of the Scatter plot, add the parameter or metric that has missing values.
5. Observe that some datapoints disappear.

### Screenshots

![image](https://user-images.githubusercontent.com/52547519/231898646-5c954ef3-d878-4786-851b-84bd09706d50.png)
![image](https://user-images.githubusercontent.com/52547519/231898684-53fa2384-0a8d-4426-a6c6-6f746a21f035.png)

### Environment

Browsers:
Firefox

### Additional Context

It is understandable that data points are not drawn when X, Y or Z values are N/A. I don't see any reason for not drawing datapoints with N/A in Labels (Legend Fields, tooltips).

**Comment by luisbergua** [comment]
Hi @avm19, thanks for reporting this! Would it be possible for you to share a link to the affected plot so I can have a look at it?

**Comment by avm19** [comment]
> Hi @avm19, thanks for reporting this! Would it be possible for you to share a link to the affected plot so I can have a look at it?

I have emailed the link!

**Comment by luisbergua** [comment]
Hi @avm19, thank you so much for the link! I have had a look at it and have actually been able to reproduce this issue so I have reported it to our Engineering Team. Will let you know once this is fixed!
