### ISSUE TITLE
[App]: Table data missing in the web app while present on local server

### ISSUE THREAD

**Issue by mpagli** [wandb/wandb#5347]
### Current Behavior

Table in the web app is empty, but the local copy is not.

Local json file:
```
{"columns": ["step", "lineKey", "lineVal"], "data": [[1, "itr 5000", 0.0], [2, "itr 5000", 0.0006885258838383838], [3, "itr 5000", 0.00025684086963383834], [4, "itr 5000", 0.0], [5, "itr 5000", 0.0007850724037247475], [6, "itr 5000", 0.0024203213778409096], [7, "itr 5000", 0.0], [8, "itr 5000", 0.0034935537010732324], [9, "itr 5000", 0.0009293373184974747], [10, "itr 5000", 0.0], [11, "itr 5000", 0.0038487906407828278], [12, "itr 5000", 0.005544458254419192]]}
```

Viewed in the App: `No rows to display`

### Expected Behavior

The data shown in the web app should be the same as the local copy. It used to be working about a week ago, but in the last few days tables shown in the web app are often empty and/or not displaying properly.

### Environment

OS: Ubuntu

Browsers: tested on both mozilla and chrome

Version: 0.14.2

**Comment by rsanandres-wandb** [comment]
Hello @mpagli!

Could you send us a link to your workspace? Also, are you logging the raw `json` file to `wandb` or making a `wandb.Table()` and uploading it?
