### ISSUE TITLE
[Q] Visualize gradients of downloaded run, one plot for each logged epoch

### ISSUE THREAD

**Issue by phrasenmaeher** [wandb/wandb#5348]
Hi, using `w&b` I logged gradients during model training using the following code:

```python
wandb_callback = WandbCallback(save_model=False, monitor="val_loss", log_gradients=True,
                                   training_data=train_ds.take(10), compute_flops=True)
```

After the experiment has finished, I'd like to visualise the gradients on my machine (not in the web application's UI).

Suppose I have the run object already (skipping the code here), I can get the history using `run.history()` and the summary using `run.summary`

Visualising the gradients using the summary-results is easy:

```python
gradient = run.summary['gradients/conv2d_transpose_2/kernel.gradient']

import matplotlib.pyplot as plt

# histogram data
bins = gradient["bins"]  # list of bin edges
values = gradient["values"] # list of bin counts

# plot histogram
fig, ax = plt.subplots()
ax.bar(bins[:-1], values, width=np.diff(bins), align='edge')

# set axis labels and title
ax.set_xlabel('Value')
ax.set_ylabel('Frequency')
ax.set_title('Histogram')

# show plot
plt.show()
```

However, if I understood the documentation correctly, this is a summary of all histograms (_i.e._, all gradients).
What I am looking for is to visualize the per-step diagrams on my machine.
That is, for each epoch where I logged the gradients, I'd like to visualize them.

What I've got so far is:
```python
grad_col = history["gradients/conv2d_transpose/kernel.gradient"]
grad_col.loc[i] #pick gradients for i-th epoch
```

But I do not know how to interpret the output:

```python
{'_type': 'histogram',
 'packedBins': {'count': 64,
  'min': -0.0033248933614231646,
  'size': 6.917011683071905e-05},
 'values': [1,
  0,
  1,
  0,
[omitted]
  1,
  0,
  0,
  2]}
```

How can I interpret and utilise this output to visualise the gradients (in a histogram) for the I-th epoch, using my local machine (_i.e._, having downloaded the run's data)?

**Comment by rsanandres-wandb** [comment]
Hello @phrasenmaeher!

Based on what I understand, I think `run.scan_history()` would work in your situation too. ([Documentation](https://docs.wandb.ai/ref/python/public-api/run#scan_history)). `run.scan_history()` provides an iterable collection of all history records for a run without sampling. 

Here's the code I used to graph each step
```
history = run.scan_history(keys=["gradients/graph_3fc.bias"])
gradients = [row["gradients/graph_3fc.bias"] for row in history]
single_gradient = gradient[0]
```

Then I graphed it the same way as you did.
```
bins = single_gradient["bins"]  # list of bin edges
values = single_gradient["values"] # list of bin counts

# plot histogram
fig, ax = plt.subplots()
ax.bar(bins[:-1], values, width=np.diff(bins), align='edge')

# set axis labels and title
ax.set_xlabel('Value')
ax.set_ylabel('Frequency')
ax.set_title('Histogram')

# show plot
plt.show()
```

**Comment by phrasenmaeher** [comment]
Thanks for your quick answer! Using `scan_history` fully solved my problem.
