### ISSUE TITLE
[App]: WANDB Model Registry not listing the stored models

### ISSUE THREAD

**Issue by NikolaCenic** [wandb/wandb#5353]
### Current Behavior

The model registry feature shows the stored model types but listing the actual models and model versions is loading for a long time without any results.

### Expected Behavior

The expected behavior is listing all the model versions in the correct category.

### Steps To Reproduce

1. Add models to the registry
2. List the models from a specific type.

### Screenshots

![image](https://user-images.githubusercontent.com/51126721/232624208-821b6a42-4a0e-436a-98af-2e3fc713b20c.png)

### Environment

OS:

Browsers: Chrome

Version:

**Comment by luisbergua** [comment]
Hi @NikolaCenic, thanks for reporting this and sorry that you are having issues. Would it be possible for you to share with me a link to this page so I can have a look at it and see why is this taking so much time to load?

**Comment by NikolaCenic** [comment]
Hello, thank you for your assistance, the issue has been resolved.
