### ISSUE TITLE
[CLI]: wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)

### ISSUE THREAD

**Issue by FONSECV** [wandb/wandb#5372]
### Describe the bug

```python

```

```shell

```
wandb: Network error (ReadTimeout), entering retry loop.
wandb: ERROR Error while calling W&B API: context deadline exceeded (<Response [500]>)
wandb: ERROR Error while calling W&B API: context deadline exceeded (<Response [500]>)
wandb: ERROR Error while calling W&B API: context deadline exceeded (<Response [500]>)
wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)
wandb: ERROR Error while calling W&B API: context deadline exceeded (<Response [500]>)
wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)
wandb: Network error (HTTPError), entering retry loop.
wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)
wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)
wandb: Network error (HTTPError), entering retry loop.
wandb: ERROR Error while calling W&B API: driver: bad connection (<Response [500]>)
wandb: Network error (HTTPError), entering retry loop.
wandb: Network error (HTTPError), entering retry loop.
wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)
wandb: Network error (HTTPError), entering retry loop.
wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)
wandb: Network error (HTTPError), entering retry loop.
wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)
wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)
wandb: Network error (HTTPError), entering retry loop.
wandb: ERROR Error while calling W&B API: An internal error occurred. Please contact support. (<Response [500]>)

### Environment

WandB version:

OS: Linux gpu214-10 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Python version: Python 3.9.16

Versions of relevant libraries:

**Comment by rsanandres-wandb** [comment]
Hello @FONSECV !

Are you still running into this issue? We had an [outage](https://status.wandb.com/) some hours ago and this would have affected the UI and SDK during this time period.
