### ISSUE TITLE
[App]:  The link to "On-Prem/Bare Metal" version is directed to a page which is not present

### ISSUE THREAD

**Issue by mhardik003** [wandb/wandb#5373]
### Current Behavior

In the README, on clicking on the   "On-Prem/Bare Metal" version under the W&B Hosting Options, the url redirects to https://docs.wandb.ai/guides/hosting/setup/on-premise-baremetal which is not present on the website

### Expected Behavior

I think it should be directed to https://docs.wandb.ai/guides/hosting/how-to-guides/basic-setup#persistence-and-scalability

### Steps To Reproduce

1. Change the link in the README

### Screenshots

![image](https://user-images.githubusercontent.com/62954265/233022521-7ce46d21-398c-43c1-8ee2-1e5e2eb9b2a7.png)

### Environment

OS: All

Browsers: All 

Version: Latest

**Comment by thanos-wandb** [comment]
Hi @mhardik003 thanks so much for reporting this issue. May I please ask if you were looking for this link? 
https://docs.wandb.ai/guides/hosting/how-to-guides/bare-metal

I also created a PR to fix the links under the W&B Hosting Options, as the other two were also pointing to our previous Docs page links.

**Comment by mhardik003** [comment]
Thank you sir, for looking into this issue and updating it so fast!

**Comment by thanos-wandb** [comment]
Thank you @mhardik003 for reporting it! Have a great day!
