### ISSUE TITLE
[Feature]: Manually override Git-related values for a run

### ISSUE THREAD

**Issue by nicjac** [wandb/wandb#5374]
### Description

When calling `init()`, the client automatically gathers information regarding the Git environment, if one exists. This works well in many cases. However, there is currently no way (as far as I know) to manually override Git-related values saved to the experiment. 

For example, if one is to use SageMaker training jobs, there is no Git environment where `init()` is called, even if the original code was indeed versioned. 

### Suggested Solution

Ideally, one would be able to provide all the information required to log Git-related data to a run as parameters to `init()` or as environment variables. This way, Git information can be passed onto the remote job execution agent and properly logged in wandb.

**Comment by luisbergua** [comment]
Hi @nicjac, thanks for your suggestion! I'll create a feature request for this and share it with our Product Team!
