### ISSUE TITLE
[Q] How to see my used storage or saved files?

### ISSUE THREAD

**Issue by lerouxl** [wandb/wandb#5376]
Hello,

I'm trying to clean up my saved data on Wandb and I'm struggling to find what is taking my storage space. Does there is a way to know/view the storage usage of my projects and runs with a view similar to a folder explorer?

I'm needing to do that as my storage is nearly full (99Gb /100Gb) with 56Gb of Artifact and 43Gb of other stored data. And I don't know where are those 56Gb of artifacts nor what are those 43Gb of other data.

I tried to delete all saved artifacts other than the last and best one with this code but it just saved my 12Gb of data.

My code:
```python
  import wandb
  from tqdm import tqdm
  
  
  api =  wandb.Api(timeout=31)
  runs = api.runs("user/project_name")
  
  al = []
  
  for run in runs:
      name = run.name
      artifacts = run.logged_artifacts()
      
      nb_art = len(artifacts)
      print(f"{name} has {nb_art} artifacts")
      
          
      if nb_art > 5:
          #print(f"{name} has {nb_art} artifacts")
          
          #for artifact in artifacts:
          #    al.extend(artifact.aliases)
          
          for artifact in tqdm(artifacts):
      
              if "best_k" in artifact.aliases or 'latest'  in artifact.aliases:
                  pass
              else:
                  time.sleep(2)
                  artifact.delete()

```

**Comment by nate-wandb** [comment]
Hi @lerouxl, you can access this information at `https://wandb.ai/usage/<insert-your-username>/tracked` if you just put your username into the URL. 

Let me know if this helps or if you have any other questions around this.

Thank you, 
Nate

**Comment by lerouxl** [comment]
Thank you @nate-wandb , that was exactly was I was looking for!
