### ISSUE TITLE
[Q] Logging image - resulting filename too long (OSError: [Errno 36] File name too long)

### ISSUE THREAD

**Issue by Wilann** [wandb/wandb#5406]
I'm logging multiple images using the code format as follows:
```
image = Image.open(image_path)
wandb_image = wandb.Image(image)
wandb.log({<some_text>: wandb_image})
```

For one of the images, I'm getting an error that the filename is too long - granted, this is not the filename that I created, but something it seems `wandb` has renamed it to, based on my directory structure:
```
Traceback (most recent call last):
  File "/home/wilsonchan/anaconda3/envs/ArcRise-AI/lib/python3.8/shutil.py", line 791, in move
    os.rename(src, real_dst)
OSError: [Errno 36] File name too long: '/tmp/tmp5nfwpqrlwandb-media/8rj22c48.png' -> '/tmp/wandb/run-20230422_125134-19csde59/files/media/images/<folder1>, <folder2>, <filename>_262_b1d8a8a444b921bc40a5.png'
```

Where, my directory structure is `/folder1/folder2/filename.png`.

I noticed that the file that was forcefuilly renamed (and therefore "too long") has 251 characters, whereas the longest previous file that was uploaded/logged successfully was 243 characters. 

Is there a fix to this issue? If not, are there any workarounds I can implement? 

Thank you for your time!

**Comment by rsanandres-wandb** [comment]
Hello @Wilann! Happy to help!

Would you be able to reformat your directory/filename in order to fit the filename limit? Also, how long would your `filename` be and would that be able to be shortened?

**Comment by rsanandres-wandb** [comment]
Yes, shortening your folder names would be the recommended way. You could change your system's filename limit, but decreasing your folder name size would be more recommended.

**Comment by rsanandres-wandb** [comment]
The error is being thrown by your OS via a `wandb` operation. It is up to your discretion to increase the filename limit but yes, this error is not coming from `wandb`. We do not enforce an internal `wandb` filename limit, just the one the OS has.
