### ISSUE TITLE
[Q] When I try to use transformer. I get a problem "PermissionError: [Errno 13] Permission denied: '/var/run/secrets/kubernetes.io/serviceaccount/token'",How can I fix it？

### ISSUE THREAD

**Issue by gddange** [wandb/wandb#5412]
settings["docker"] = wandb.env.get_docker(wandb.util.image_id_from_k8s())
  File "/lib/python3.9/site-packages/wandb/util.py", line 1250, in image_id_from_k8s
    headers={"Authorization": f"Bearer {open(token_path).read()}"},
PermissionError: [Errno 13] Permission denied: '/var/run/secrets/kubernetes.io/serviceaccount/token'

**Comment by thanos-wandb** [comment]
Hi @gddange thanks for reporting this issue. 

Would it be possible that you provide some additional context, where are you running the transformer? Could you share with us a minimal code example, so that we could debug further?

From the error that you've mentioned, it appears you get a `PermissionError`. Are you a root user in this container? Are you mounting a k8s secret, and what are the token permissions?

**Comment by gddange** [comment]
> Hi @gddange thanks for reporting this issue.
> 
> Would it be possible that you provide some additional context, where are you running the transformer? Could you share with us a minimal code example, so that we could debug further?
> 
> From the error that you've mentioned, it appears you get a `PermissionError`. Are you a root user in this container? Are you mounting a k8s secret, and what are the token permissions?

**Comment by gddange** [comment]
> Hi @gddange thanks for reporting this issue.
> 
> Would it be possible that you provide some additional context, where are you running the transformer? Could you share with us a minimal code example, so that we could debug further?
> 
> From the error that you've mentioned, it appears you get a `PermissionError`. Are you a root user in this container? Are you mounting a k8s secret, and what are the token permissions?

HI,  I am trying to finetune a llama model using the toolbox mentioned in this Github repository: https://github.com/OptimalScale/LMFlow. As a non-root user, I'm unable to obtain root user permissions. The code is being run on a x86_64 GNU/Linux system.
The trace are:
Traceback (most recent call last):
  File "LMFlow/examples/finetune.py", line 70, in <module>
    main()
  File "LMFlow/examples/finetune.py", line 66, in main
    tuned_model = finetuner.tune(model=model, lm_dataset=lm_dataset)
  File "LMFlow/src/lmflow/pipeline/finetuner.py", line 232, in tune
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/transfomers/src/transformers/trainer.py", line 1639, in train
    return inner_training_loop(
  File "/transfomers/src/transformers/trainer.py", line 1822, in _inner_training_loop
    self.control = self.callback_handler.on_train_begin(args, self.state, self.control)
  File "/transfomers/src/transformers/trainer_callback.py", line 353, in on_train_begin
    return self.call_event("on_train_begin", args, state, control)
  File "/transfomers/src/transformers/trainer_callback.py", line 397, in call_event
    result = getattr(callback, event)(
  File "//transfomers/src/transformers/integrations.py", line 764, in on_train_begin
    self.setup(args, state, model, **kwargs)
  File "/transfomers/src/transformers/integrations.py", line 738, in setup
    self._wandb.init(
  File "/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    raise Exception("problem") from error_seen
Exception: problem

**Comment by thanos-wandb** [comment]
Hi @gddange thanks for the additional information. Could you please first try to login in your CLI with `wand login` and then `wandb init` commands? do these work for you?

**Comment by thanos-wandb** [comment]
Hi @gddange just an update on this, [there's currently a PR](https://github.com/wandb/wandb/pull/5472) under review which should resolve the original issue with permission denied. I will keep you posted once it's merged in our master branch.

**Comment by thanos-wandb** [comment]
Hi @gddange the PR has been merged to our main branch, and will be in our next SDK/client release. If you wanted to test if it works for you, you could install from main branch as follows:
`pip install git+https://github.com/wandb/wandb.git@main`

Please let me know if that worked for you.

**Comment by thanos-wandb** [comment]
Hi @gddange I will close this ticket for now since we haven't heard back from you. If you're still experiencing any issue after installing from our main branch (or if you wanted to wait for our next wandb client/SDK release in June) please let us know and we would be glad to keep investigating.

**Comment by gddange** [comment]
> Hi @gddange I will close this ticket for now since we haven't heard back from you. If you're still experiencing any issue after installing from our main branch (or if you wanted to wait for our next wandb client/SDK release in June) please let us know and we would be glad to keep investigating.

Thank you! The problem have been solved.

**Comment by thanos-wandb** [comment]
Thank you @gddange for confirming, glad to hear it's resolved! I will close the ticket, and please feel free to reach out again if you run into any other issues.
