### ISSUE TITLE
[Q]: How to show the latest logged metrics for runs on the plot.

### ISSUE THREAD

**Issue by samils7** [wandb/wandb#5419]
Hi, I am evaluating a few models and log test accuracies. Figured out I had made a mistake in my eval script and test accuracy comes up as nonsense value for a single run. I have fixed the bug and re-run it. Now the metrics are true.
Results of the 1th run can be seen in the chart below (accuracy - Step);
![resim](https://user-images.githubusercontent.com/25254948/234309031-be965d52-670c-4a19-9de3-0b47e894211b.png)

Problem is, I see only the oldest metrics for runs when I want to compare with other runs and couldn't make it work. Example below;
![resim](https://user-images.githubusercontent.com/25254948/234309229-cc22d4ae-0ee2-4335-bfb2-c8bee720e133.png)

How can I fix the bar of the 1th experiment (or all) to show the latest logged metric?

I hope It is explained clearly. Thanks for your helps.

**Comment by luisbergua** [comment]
Hi @samils7, thanks for writing in! If I'm understanding you properly, you'd like to plot the bar chart showing the value of the accuracy in the last step, is that correct? This should be the default behavior so it'd be great if you could send me a link to that project so I can have a look at it to see what's happening exactly.

**Comment by samils7** [comment]
Hi @luisbergua , thanks for writing too.  Sorry that I can't share this link with you but let me mention my last findings.

I have downloaded this panel as a csv file and I see column names and values of exp 1 is:
- exp_1_step (=126.5)
- exp_1_step__MIN (=110)
- exp_1_step__MAX (=143)
- exp_1_test/acc (=0.68)
- exp_1_test/acc__MIN (=0.00001)
- exp_1_test/acc__MAX (=0.94)

it means there are both min and max accuracy values of experiments stored in this panel and UI only shows MIN values as default and doesn't allow to change.

**Comment by luisbergua** [comment]
Thanks for the context @samils7! I think I see what you mean now. The reason for that is because bar charts are intended for metrics of length 1.
![image](https://user-images.githubusercontent.com/113048227/236496988-7140538d-8a6c-45c7-9686-8e3ced300a3c.png)
If you click on Add Panel -> Bar chart and select a metric logged per step, the bars will show the last step value. Please let me know if that makes sense.

**Comment by samils7** [comment]
Hi @luisbergua Thanks for the suggestion. After manually adding bar chart and selected the metric I want, I see the the latest logged values on newly created bar chart. This is what I wanted to see.
