### ISSUE TITLE
[Q] Api return None's

### ISSUE THREAD

**Issue by de-gozaru** [wandb/wandb#5426]
Hi,

I'm trying to recover the logged data in a jupyter notebook. I'm doing this:
```python
runs = wandb.Api().runs("my/project")

all_runs = defaultdict(dict)

for run in tqdm(list(runs)):
    name = run.name
    new_dict = {}
    
    for k, e in run.history().items():
        new_dict[k] = list(e.to_numpy())  # .to_numpy()
        
    for k, e in run.summary.items():
        if k not in new_dict:
            new_dict[k] = e
    
    all_runs[name] = new_dict
```

however, for some runs, the values for some logged metrics are just a list of None, even though the values are float, and I can see them in the webapp.

It should be noted that this only happens for the test values (which are normally a list with nans and only one float value, But I get a list  with only None).

Is this a known issue, how can I solve it?

Thank you in advance!

**Comment by MBakirWB** [comment]
Hi @de-gozaru , happy to help. I'll run through some tests and report back.Do you have a link to your project workspace I can review data in? Send it to support@wandb.com and add MBakir to subject line, thanks.

**Comment by MBakirWB** [comment]
Hi @de-gozaru since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
