### ISSUE TITLE
[CLI]: `artifact.download()` switches ':' with '-', but returns unmodified path

### ISSUE THREAD

**Issue by tsteffek** [wandb/wandb#5427]
### Describe the bug

I'm trying to download an `wandb.Artifact` into a path such as `artifact:tag`. While downloading, it replaces the `:` with `-`, as noted in a warning (Happening here: [wandb/sdk/lib/filesystem, L102](https://github.com/wandb/wandb/blob/d61815e3210fcc9258b71e002f48d79a9457cf03/wandb/sdk/lib/filesystem.py#L102-L106)). The path that `.download()` returns however, will still contain the `:` and trying to use it will fail, as its looking up the wrong path.

```python
        artifact = wandb.Api().artifact(artifact_name, type=artifact_type)
        artifact_cache = os.path.join(cache_dir, 'artifacts', artifact_name)
        download_path = artifact.download(artifact_cache)
```

```shell
Traceback (most recent call last):
  File "C:\Users\tsteffek\PycharmProjects\train-ner-model\src\main.py", line 63, in <module>
    test(config_args, trainer_args, model_artifact, dataset_artifact, tag)
  File "C:\Users\tsteffek\PycharmProjects\train-ner-model\src\testing.py", line 17, in test
    dataset_test = load_from_disk(os.path.join(dataset_artifact.download_path, config_args.dataset_test_name))
  File "C:\Users\tsteffek\PycharmProjects\ner-torchserve\venv\lib\site-packages\datasets\load.py", line 1880, in load_from_disk
    raise FileNotFoundError(f"Directory {dataset_path} not found")
FileNotFoundError: Directory ./outputs/cache\artifacts\team-name/project-name/artifact-name:tag\file.file not found
```

### Environment

WandB version: 0.15.0

OS: Windows

Python version: 3.10

Versions of relevant libraries: -

**Comment by MBakirWB** [comment]
Hi @tsteffek, thank you for sending this over. We'll review and get back to you with our finding.

**Comment by MBakirWB** [comment]
Hi @tsteffek following up prior to closing out, are you still experiencing this reported behavior?

**Comment by MBakirWB** [comment]
Hi @tsteffek , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
