### ISSUE TITLE
[Q]: Configuring WandB UI to display metrics for best epoch

### ISSUE THREAD

**Issue by kiratben** [wandb/wandb#5439]
By default, the WandB UI (Table) presents metric values for the last epoch of a given run. However, I would like to modify this default behavior to display metrics specifically for the best epoch. Are there any configuration options available within the UI to achieve this desired behavior?

**Comment by thanos-wandb** [comment]
Hi @kiratben thanks for writing in! Could you please provide some more details of the use case, are you referring to a table on the Project or Run level? are you also interested to get this information during training, or after a run has completed? I was wondering if defining the metric with the summary argument as follows:

```
random.seed(1)

# Start a new run
wandb.init(project="define-metric-demo", notes="min of loss, max of acc")

# For loss, capture the min value from history in summary
wandb.define_metric("loss", summary="min")

# For acc, capture the max value from history in summary
wandb.define_metric("acc", summary="max")

# Simulate a training loop where we're logging metrics
for i in range(10):
  log_dict = {
      "loss": random.uniform(0,1/(i+1)),
      "acc": random.uniform(1/(i+1),1),
  }
  wandb.log(log_dict)

# Mark the run as finished, useful in the context of Jupyter notebooks
wandb.finish()
```

You will then have `acc.max` and `loss.min` in your Summary that you could use to display your best epoch. Would this work for you?

**Comment by kiratben** [comment]
Thank you for your response. To provide more context, I am referring to a table in the web user interface that displays the training metrics for multiple versions of a model (the table that you can see in the screenshot). I would like to compare the metrics for the best epoch of each version after completing their respective training. The current table displays only the results for the last epoch, which is insufficient for my purpose. To clarify, I need to see the metrics for the best epoch of each version in order to make a proper comparison. If you require more information, please let me know.
![image](https://user-images.githubusercontent.com/9163492/235223702-7ac3074e-a9be-4851-b69c-218855e69065.png)

**Comment by thanos-wandb** [comment]
Hi @kiratben thanks for the screenshot and sorry for late reply here. This can be achieved by defining a custom metric, and also specifying which aggregate to use for its `Summary`. For instance, for your use case you could do something as follows:

```
import wandb
wandb.init()

# define which metrics will be plotted against it
wandb.define_metric("val_loss", summary="min")
wandb.define_metric("val_loss", summary="last")
wandb.define_metric("val_Precision", summary="max")

for i in range(100):
  log_dict = {
      "val_loss": val_loss,
      "val_Precision": val_Precision,      
  }
  wandb.log(log_dict)
wandb.finish()
```

Would this work for you? you could resume the already logged runs if you wanted to log these additional metrics too.

**Comment by thanos-wandb** [comment]
Hi @kiratben since it seems the above would work for you, I will close this ticket for now. Please feel free to re-open this if you had any more questions/issues, and we would be happy to keep investigating.

**Comment by JeremyCraigMartinez** [comment]
@kiratben did this solve the issue for you? I am seeing a similar issue. I am training an NER model with spaCy. I am using the following logging config

```
config['training.logger'] = {
    '@loggers': 'spacy.WandbLogger.v4',
    'project_name': cert_name,
    'remove_config_values': [],
    'log_dataset_dir': './assets',
    'model_log_interval': '100',
}
```

and it publishes `./training/model-last` instead of `./training/model-best`. Naturally, I would want to compare the best scores rather than just the last scores. In the `sweeps.yml` I have the following

```
method: bayes
metric:
  goal: maximize
  name: score
command:
  - ${env}
  - ${interpreter}
  - sweeps.py
  - ./configs/config.cfg
  - ./training
parameters:
    ...
```

I can see in the stdout the discrepancy between last and best. For example:


```
E    #       LOSS TOK2VEC  LOSS NER  ENTS_F  ENTS_P  ENTS_R  SCORE 
---  ------  ------------  --------  ------  ------  ------  ------

...

wandb: Adding directory to artifact (./training/model-last)... Done. 0.0s

 20    1640       3791.26     97.41   57.14   65.85   50.47    0.57

 20    1650      12032.89    165.31   56.09   60.43   52.34    0.56

 20    1660       3669.51     56.44   54.45   61.90   48.60    0.54

wandb: Waiting for W&B process to finish... (success).

wandb: Run history:
wandb:       ents_f ▁▂▂▃▃▂▄▅▆▆▄▅▆▆▄▇▃▆▆▇▆▆█▆▇▇▇▇▇▇▆█▇█▇▇▇▇██
wandb:       ents_p ▁▂▃▄▃▂▅▆▅▆▄▅▆▆▄▇▄▆▆▆▆▆▇▇▇▇▇▇▇▆▇█▇█▇▇▇▇█▇
wandb:       ents_r ▁▁▂▃▃▂▄▄▆▅▃▅▆▆▄▇▃▆▅▇▅▆█▆▇▇▆▇▇▇▆█▇▇▇▇▇███
wandb:     loss_ner █▂▁▂▁▂▁▁▁▁▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: loss_tok2vec ▁█▁█▁▃▁▁▁▁▁▄▁▂▂▁▂▁▁▁▂▁▁▂▁▁▆▂▁▂▂▁▁▂█▂▂▁▁▃
wandb:        score ▁▂▂▃▃▂▄▅▆▆▄▅▆▆▄▇▃▆▆▇▆▆█▆▇▇▇▇▇▇▆█▇█▇▇▇▇██
wandb:        speed ▅▇▅▁▂▁▂▃▂▂▄▄▅▄▅█▇▄▆▇▅▆▆▆▄▅▅▅▅▂▁▅▆▅▅▆▅▅▅▂
wandb:    token_acc ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:      token_f ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:      token_p ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:      token_r ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: 
wandb: Run summary:
wandb:       ents_f 0.5445
wandb:       ents_p 0.61905
wandb:       ents_r 0.48598
wandb:     loss_ner 56.43864
wandb: loss_tok2vec 3669.51386
wandb:        score 0.5445
wandb:        speed 57350.0027
wandb:    token_acc 1.0
wandb:      token_f 1.0
wandb:      token_p 1.0
wandb:      token_r 1.0
```

In the terminal output, the best score is clearly 57, but wandb captures 54 instead. How can I capture `./training/model-best` rather than `./training/model-last`? @thanos-wandb 

Thanks in advance!

**Comment by JeremyCraigMartinez** [comment]
I'll open a new question since this has been closed

**Comment by thanos-wandb** [comment]
Thank you @JeremyCraigMartinez our team will follow up with you in the new thread.
