### ISSUE TITLE
[App]: Is there a limit for table logging?

### ISSUE THREAD

**Issue by DishantMewada** [wandb/wandb#5443]
### Current Behavior

I have created a custom table as shown in the image. As you can see it is logged 82 times on the left side and it is completely selected. But the table on the right shows only 50 rows. Even exporting it to .csv shows only 50 rows. 

I was wondering if is there a limit for logging for tables and how one can bypass it.

Thanks a million.

### Expected Behavior

The full log should be displayed in the table and exported to CSV. 

### Screenshots

![Screenshot_2023-04-28_00-01-11](https://user-images.githubusercontent.com/26144402/235009082-eca21f61-65d8-4d35-a1cc-08f4c24c4a1b.png)

### Environment

OS: Ubuntu 22.04

Browsers: firefox 112.0.2

Wandb version: 0.13.11

### Additional Context

Please let me know if I am missing something here.

**Comment by thanos-wandb** [comment]
Hi @DishantMewada thanks for reporting this issue. There's a default limit of 200,000 rows, and you could override the limit with: `wandb.Table.MAX_ROWS = X`

In your case, unless you've specified this variable to be 50, it shouldn't happen. Are you using the same table key for all 82 entries? The `wandb.Table` would create an artifact too, could you please click the artifact icon from left panel and check in the artifact's files tab if you can see the whole table in there?

**Comment by DishantMewada** [comment]
@thanos-wandb My table generation code is as follows - 
```

inference_table = wandb.Table(columns=['model_name', 'width', 'height', 'percent_change', 'GFLOPs', 'Params_M',  'bbox_mAP', 'bbox_mAP_50', 'bbox_mAP_75', 'bbox_mAP_s', 'bbox_mAP_m', 'bbox_mAP_l'], 
                            data=[[meta['exp_name'][:-3],IMAGE_WIDTH,IMAGE_HEIGHT,int(imageSize*100),num_flops,params,test_dict.get('bbox_mAP'),test_dict.get('bbox_mAP_50'),test_dict.get('bbox_mAP_75'),test_dict.get('bbox_mAP_s'),test_dict.get('bbox_mAP_m'),test_dict.get('bbox_mAP_l')]])
run.log({"Test Inference": inference_table})
```

where I am populating variables in different runs.

Here is the screenshot of my artifact. I don't know where the table is in here. 
I am fine running the entire experiment again.

Thank you.

![Screenshot_2023-04-28_11-11-51](https://user-images.githubusercontent.com/26144402/235120766-0b3f6de3-791b-474a-b5cf-934cd51f89b4.png)

**Comment by DishantMewada** [comment]
Note: This table is generated through different runs which were in the for loop.

**Comment by thanos-wandb** [comment]
Hi @DishantMewada thanks so much for the additional information, and sorry for late reply here. There's indeed a limit applied when it comes to concatenating tables from different runs and this is set to 50. 

A workaround would be to create a dummy run that gets from all these runs the logged artifacts and adds them to a new table. In that case, since it will be coming from a single run you will be able to visualize up to 200,000 rows. Let me know if that would work for you and if you needed a code snippet to do that.

**Comment by thanos-wandb** [comment]
Hi @DishantMewada I wanted to follow up with you on this issue, there are performance reasons that constrain this limit. Therefore, I was wondering if you were interested in a workaround where you combine the tables in a dummy run, and then log a single table instead. Thank you!
