### ISSUE TITLE
[App]: max metric value cannot be shown in the table view after define_metric

### ISSUE THREAD

**Issue by HiLittleFriend** [wandb/wandb#5450]
### Current Behavior

To get the maximum matric value, i add `wandb.define_metric("metrics/Bleu-1", summary="max")` in the code. After training, the summay file looks like normal, like this `"metrics/Bleu-1": {
    "max": 0.4533
  },
  "metrics/Bleu-2": 0.2884,
  "metrics/Bleu-3": 0.185,`, but when i return to the run page, and add a scalar chat panel of the max bleu-1, nothing is shown unless saying that "Select runs that logged summary:metrics/Bleu-1.max to visualize data in this chart." What's more, on the table view of all runs, the column of metrics/Bleu-1.max show nothing.
  
  I check other metrics which i don't use define_metric too, the scalar chart and table view show nothing.
  
![image](https://user-images.githubusercontent.com/41235297/235281151-45b2c957-e3a3-41ff-960a-52a3e4918ff3.png)

### Expected Behavior

the scalar chat panel or table view should display the number recorded in the summay json file

### Screenshots

![image](https://user-images.githubusercontent.com/41235297/235281200-4c8ff2e5-4073-48de-bfb0-016a27e06f05.png)

### Environment

OS: windows

Browsers: chrome 112.0.5615.138

Version: wandb 0.15

**Comment by ArtsiomWB** [comment]
Hi @HiLittleFriend! Could you sent a link to your workspace where you are running into this issue?

**Comment by ArtsiomWB** [comment]
Hi,
We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by ArtsiomWB** [comment]
Hi @HiLittleFriend , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
