### ISSUE TITLE
[Q] Can team member adds notes to runs by others?

### ISSUE THREAD

**Issue by xibeisiber** [wandb/wandb#5451]
Hi,
In my project, when other team member tries to add notes to my runs, the page says:
_No Access
You do not have permission to view this page_

Can team member adds notes to runs by others?

Thanks!

**Comment by thanos-wandb** [comment]
Hi @xibeisiber thanks for reporting this issue. Is this a project logged in a team or your personal entity? Could you please check in your project's Overview page what are the Privacy settings?

**Comment by xibeisiber** [comment]
> Hi @xibeisiber thanks for reporting this issue. Is this a project logged in a team or your personal entity? Could you please check in your project's Overview page what are the Privacy settings?

The project is logged in a team entity. I can't find the Privacy setting in project's Overview page. Only in team settings.
![image](https://user-images.githubusercontent.com/5679317/235334335-b51516bb-7cbe-42d2-bbad-87db7369e28d.png)

**Comment by thanos-wandb** [comment]
Hi @xibeisiber sorry for late response on this issue, this shouldn't happen based on your team settings. Could you please provide me with your username to investigate this further?

**Comment by xibeisiber** [comment]
> Hi @xibeisiber sorry for late response on this issue, this shouldn't happen based on your team settings. Could you please provide me with your username to investigate this further?

My username is "jiying.jia"

Thanks!

**Comment by thanos-wandb** [comment]
Xi @xibeisiber I have just checked this in your account and it should be possible that all the team members add notes to the runs. Is there any particular member that can't edit the notes, and are you able to add notes to other members runs? Thank you!

**Comment by xibeisiber** [comment]
> Xi @xibeisiber I have just checked this in your account and it should be possible that all the team members add notes to the runs. Is there any particular member that can't edit the notes, and are you able to add notes to other members runs? Thank you!

All other member can't edit the notes of my runs. I can add notes to others..

**Comment by thanos-wandb** [comment]
Hi @xibeisiber apologies for any confusion caused earlier. After investigating this further that's the expected behavior, and only team admins can edit runs notes while members won't have the required permissions. We will be reworking our role-based control access more this year and this can change in the future. Would you like that this is filed as a feature request instead? Thank you!

**Comment by xibeisiber** [comment]
> 

yes, I hope this can be a future feature, as default or can be set by some permission controlling.

Thanks!

**Comment by thanos-wandb** [comment]
Thanks @xibeisiber I have filed this as a feature request so that more permissions controls can be supported in the future. We will reach out to you here once there are any updates. Thank you!

**Comment by xibeisiber** [comment]
> 

Perfect！ Thanks very much for your support!
