### ISSUE TITLE
[Q] Why Optuna's suggest categorical params are not logged and shown in the UI?

### ISSUE THREAD

**Issue by mikolajkania** [wandb/wandb#5465]
Hello guys, I have a burning question. I am running Optuna with wandb and values from _suggest_categorical_ are not logged and shown in the UI.

Let take this as an example. Binary won't be visible, but min_df - will be:
![obraz](https://user-images.githubusercontent.com/14984193/235795364-91a63c02-e0a1-4867-b69d-3430e8b85337.png)

For binary I am getting such mesage:
![obraz](https://user-images.githubusercontent.com/14984193/235795477-c89ad15b-4fcf-4281-ab65-245ab425a6b9.png)

To help Google track it, this is a message:
_Selected runs are not logging media for the key binary, but instead are logging values of type number.
If binary is never supposed to be a media type, please delete this panel and create the proper panel type manually._

It happens with every _suggest_categorical_ parameter I tried (both string and bool) and it is very annoying, as values like binary for sklean vectorizers is a big tuning option. How to fix that?

Example code:

```
def objective(trial):
    params = {
        'vectorizer': {
            'name': 'tfidf',
            'params': {
                'binary': trial.suggest_categorical('binary', [True, False]),
                'min_df': trial.suggest_int('min_df', low=0, high=100, step=5)
            }
        }
    }

    X_train, X_val, _, y_train, y_val, _ = loading(split_train_val=True)
    vectorizer, X_train_vec, X_val_vec, _ = vectorization(params, X_train, X_val=X_val)
    model = training(params, X_train_vec, y_train)
    _, val_f1_score = evaluate(model, X_val_vec, y_val)
    return val_f1_score

def run(config: dict = None, params: dict = None) -> None:
    wandbc = WeightsAndBiasesCallback(metric_name='val_f1')
    print('Starting optuna...')
    study = optuna.create_study(direction='maximize')
    study.optimize(objective, n_trials=3, callbacks=[wandbc])

```

### Additional context (optional)

I can ommit this issue by custom code in the objective method:

```
trial_params = dict(trial.params)
wandb.log(data={"vec_binary": int(trial_params['binary'] == True)}, step=trial.number)
```
I need to manually replace it with ints.

**Comment by mikolajkania** [comment]
After some investigation I moved it to Optuna space: https://github.com/optuna/optuna/issues/4648

**Comment by nzw0301** [comment]
Here is the minimal reproducible code:

```python
import optuna
from optuna.integration import WeightsAndBiasesCallback

def objective(trial):
    params = {
        'vectorizer': {
            'name': 'tfidf',
            'params': {
                'binary': trial.suggest_categorical('boolean_variable', [True, False]),
                'min_df': trial.suggest_int('min_df', low=0, high=100, step=5)
            }
        }
    }

    return 1.

wandbc = WeightsAndBiasesCallback()
study = optuna.create_study()
study.optimize(objective, n_trials=3, callbacks=[wandbc])
```

**Comment by rsanandres-wandb** [comment]
Hello! Just checking in to see if you still need help? It does seem that there has been answers found/provided so thank you to both to you!

**Comment by mikolajkania** [comment]
@rsanandres-wandb The issue seems to be there. I need to create a workaround and translate boolean or string values into ints. I'd rather see original values, as otherwise I need to track them over time somehow.

**Comment by rsanandres-wandb** [comment]
Hello @mikolajkania !

After looking into this, the `binary` value is stored in `wandb`. However, it is stored as a parameter to group by as seen in the screenshot I attached. 
![image](https://github.com/wandb/wandb/assets/122482606/f4b6c49a-3984-4f54-8ae0-30673ff0e89c)

Could I ask what you need the `binary` values for? There may be a way to implement your usecase in a different way.

**Comment by mikolajkania** [comment]
@rsanandres-wandb Thanks for taking a look! Binary is a parameter from Sklearn vectorizer and I during Optuna search I am checking if its value should be True or False. It has a big impact on inference and training.

**Comment by rsanandres-wandb** [comment]
Hello! I looked into it and it looks like we don't have a default chart that can handle booleans in Charts but we are able to handle it in Weave. I have attached a short video taking the above script's runs and making it so that you can visualize the Boolean values. 

https://github.com/wandb/wandb/assets/122482606/091ae99d-640c-4e71-a15a-3091608ae15a

**Comment by mikolajkania** [comment]
Thank you, it might work. Nevertheles, it would be great to have it supported out of the box.
