### ISSUE TITLE
Problems whith fptlib python

### ISSUE THREAD

**Issue by raficulin** [wandb/wandb#5470]
I still don't understand much about networks and I have to fix a problem that came up with transferring files from one computer to another. I'm using the ftplib library and FileZilla to create a server on the computer that needs to receive the transfer. I'm attaching images of the text that shows up in my program. This is a recent issue; everything was working fine until the internet service provider was changed, and apparently there was an issue with the IPs.
It should be noted that the first and second image comes directly from the code, while the third and four is from a separate window that opened. "If you need more information, let me know because I still don't quite understand if it's a code or server issue.
https://ibb.co/C0KrRcs
https://ibb.co/wMhm3hK
https://ibb.co/xhxRmBd
https://ibb.co/cXRNdZr

**Comment by rsanandres-wandb** [comment]
Hello @raficulin!

Just making sure, could you please clarify where you are using`wandb`? I would be happy to assist you in any way I can but I cannot seem to locate where you use `wandb`.

**Comment by raficulin** [comment]
Hello @rsanandres-wandb .
there was a mix up, i'm not using wandb
