### ISSUE TITLE
[Q]wandb local server license expired?

### ISSUE THREAD

**Issue by J-Zhangg** [wandb/wandb#5506]
I deployed a local host for myself, but I was suddenly told today that my license had expired.  And I can not open localhost:8080 . Isn't a license for personal use free forever?

**Comment by ArtsiomWB** [comment]
Hi @J-Zhangg! A local license is free for academics only. Do you have an academic account with us?

**Comment by J-Zhangg** [comment]
> Hi @J-Zhangg! A local license is free for academics only. Do you have an academic account with us?

Thanks for your reply. In fact, I'm pretty sure I checked academics only when I signed up my account. If not, where can I confirm it?

**Comment by ArtsiomWB** [comment]
No problem! what is your wandb username, I could check for you :)

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by J-Zhangg** [comment]
Thank you for your help. I've tried a lot of things and still don't know what the problem is. I've given up. Thank you very much.

**Comment by ArtsiomWB** [comment]
Hi @J-Zhangg! Please let me know your wandb username so I can help you out here. Otherwise, I'll close this ticket for now and you can reopen it anytime you'd like.

**Comment by luo-li-ba-suo** [comment]
Hello @ArtsiomWB ! I met the same problem, and I indeed own an acedemic account. How can I contact with you and offer you my user name?

**Comment by MrRobot2211** [comment]
Hello, I seem to have a free academic account felipe_b online at wandb.ai but, that does not seem to be the case for local use. In fact I am running into a deployment already exists issue and not being able tosee my local runs. Is there any way to fix this?
