### ISSUE TITLE
[Feature]:  Is wandb support comparing among multiple large images?

### ISSUE THREAD

**Issue by jimmysue** [wandb/wandb#5514]
### Description

Our team currently involved in training image retouching algorithms. We strongly in demand for tools for comparing images between generated images and source images during training to tracking the training progress. The comparing interface might be similar as bellow:

<img width="2008" alt="image" src="https://user-images.githubusercontent.com/29350169/236984942-33b24f8e-0f80-477c-aa71-ddf8de10a8f2.png">

The visualizing window can pan and zoom and image simultaneously to spot the detailed difference between images.

Besides that, the images would be large, resolution up to  4096. Is there any sollution in wandb to support this circumstance?

### Suggested Solution

* Easily log images that to be compared
```python
wand.log_image_dict (
  'source':  source,
  'output': output
)
```

**Comment by MBakirWB** [comment]
Hi @jimmysue , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
