### ISSUE TITLE
[CLI]: Disk quota exceed when sending the artifact to remote server

### ISSUE THREAD

**Issue by binyang97** [wandb/wandb#5522]
### Describe the bug

```python

```

```shell

```
[debug-internal.log](https://github.com/wandb/wandb/files/11439233/debug-internal.log)

### Additional Files

The wandb always tried to send the artifact to the remote server but I do not call any function related artifact in my code. I only use wandb.init() and wandb.log() to initialize and create loggings. Though wandb can finish the process, the error message always comes out.

[image](https://github.com/wandb/wandb/assets/91425373/3c0059f1-109d-4dd2-af42-329afbd43bd7)

### Environment

WandB version: 0.15.2

OS: Linux

Python version: 3.8

Versions of relevant libraries:

**Comment by luisbergua** [comment]
Hi @binyang97, thanks for reporting this! So would a code like the following reproduce yours?
```
run = wandb.init()
run.log({"metric": 5})
```
Also, would you mind sharing the details of your environment so we can try to reproduce this on our end?

**Comment by binyang97** [comment]
Thank you for the I play. Yes, I only call wandb.init() and wandb.log() in the code. I tested with higher version of python and the problem is still there. Below are the details. I'm using a remote cluster and I use the slurm commands to submit the job: https://slurm.schedmd.com/sbatch.html

active environment : plr
    active env location : /cluster/home/biyang/miniconda3/envs/plr
            shell level : 2
       user config file : /cluster/home/biyang/.condarc
 populated config files : 
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.17=0
                          __linux=3.10.0=0
                          __unix=0=0
       base environment : /cluster/home/biyang/miniconda3  (writable)
      conda av data dir : /cluster/home/biyang/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /cluster/home/biyang/miniconda3/pkgs
                          /cluster/home/biyang/.conda/pkgs
       envs directories : /cluster/home/biyang/miniconda3/envs
                          /cluster/home/biyang/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.9.7 Linux/3.10.0-1160.88.1.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 550864:455833
             netrc file : /cluster/home/biyang/.netrc
           offline mode : False

**Comment by luisbergua** [comment]
Hi @binyang97, thanks for sharing this! Could you also share your wandb version and what data types are you logging and the estimated size of each file?

**Comment by binyang97** [comment]
Hi @luisbergua wandb version is 0.15.2. I log images and values in the training. Here is the overview. In section "Test" and "Chart" are just figures showing the loss values in each step. In section "Media", it is logged with 20 images at total (2 images and 10 iteration). I put an example of image below. Each image has the resolution of 384 x 2048 and size of file is about 400 KB.

![image](https://github.com/wandb/wandb/assets/91425373/e6206ee8-a262-4a50-96fa-fe4c2db3ea3c)

![image](https://github.com/wandb/wandb/assets/91425373/ff1bc1a8-438d-4d5e-9229-70c16a53f08a)


![intensity_4_0ded1c3f838a464154f7](https://github.com/wandb/wandb/assets/91425373/4af2c73b-e165-456d-bd47-0caa95d0ba5c)

**Comment by luisbergua** [comment]
Hi @binyang97, thanks for sharing your version and data! I have investigated  this, the reason why you're seeing artifacts being sent to the server although you're not explicitly calling them is because for every run an artifact named `run-<id>-history` is created. You can control where those artifacts are stored using the [env variable](https://docs.wandb.ai/guides/track/environment-variables#optional-environment-variables) `WANDB_CACHE_DIR`. Let me know if this is useful!

**Comment by luisbergua** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by binyang97** [comment]
Hi, sorry for late update. I've tested it but there is still the issue. I set th WANDB_CAHCE_DIR in bash file and it indeed created the folder named wandb/artifact under the directory I set. But it still shows the same error message. Is it because the artifact is too large to upload to remote website of wandb?

**Comment by luisbergua** [comment]
Thanks @binyang97! From the screenshot of your project there are only some metrics and 5 steps so the amount of data shouldn't be a problem. Would it be possible, for a run affected by the error, to share `debug.log` and `debug-internal.log`? These files are under your local folder `wandb/run-<date>_<time>-<run-id>/logs` in the same directory where you’re running your code.

**Comment by binyang97** [comment]
I updated the wandb version and the error was gone now. Here is the log of successful one. I have attched the failed one on the top of the issue. I've run the codes with totally the same settings. Anyway, thank you very much for the patient reply. Wish you have a nice weekend.
[debug-internal.log](https://github.com/wandb/wandb/files/11574706/debug-internal.log)

**Comment by luisbergua** [comment]
Great to see this is working properly now @binyang97! Hope you have a nice weekend as well!
