### ISSUE TITLE
[Q] Saving files in /tmp folder at somewhere else

### ISSUE THREAD

**Issue by YandongJi** [wandb/wandb#5525]
My syncing process is producing a ton of files in /tmp folder. Is there a way to save these intermediate files somewhere else and without "sudo" requirement to clear them?

**Comment by nate-wandb** [comment]
Hi @YandongJi, `wandb` defaults to writing to `/tmp` if the `WANDB_DIR` is unreachable or doesn't exist. There are a couple ways to set this directory:

1. Set env variable `WANDB_DIR`
2. Pass the argument to `wandb.init(dir=)`
3. If you are using one of our integrations they usually also have this `dir=` argument. 

Let me know if that helps solve this for you if you have any other questions around this. 

Thank you,
Nate

**Comment by jehontan** [comment]
I am using the WandbLogger in PyTorch Lightning, and setting the `dir` argument seems to have no effect.

I am running on a cluster where the `/tmp` directory is shared, caussing the run to fail if another user had created a `/tmp/wandb` directory and the permissions are not set to allow others to access it.

**Comment by nate-wandb** [comment]
@jehontan does the directory you pass to `dir=` exist prior to starting the run? 

Also, do you get a warning like this in terminal: `wandb: WARNING Path non-existent-dir/wandb/ wasn't writable, using system temp directory.`

**Comment by jehontan** [comment]
@nate-wandb you're right, the dir was missing. The issue is resolved.
