### ISSUE TITLE
[Q] wandb.watch with model inherited from multiple parents

### ISSUE THREAD

**Issue by MartinPerry** [wandb/wandb#5526]
I have model that inherits nn.Module and also AbstractModel class. In the AbstractModel class there are many things to load model, export model, do some logging etc. 

However, problem is, when I use 

`wandb.watch(model, log="all")`

it crashes with:
```
Traceback (most recent call last):
  File "C:\Users\perry\.conda\envs\nnframework\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\perry\.conda\envs\nnframework\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'TorchHistory.add_log_parameters_hook.<locals>.<lambda>'
```

How to solve this?

**Comment by fdsig** [comment]
Hey @MartinPerry , 

Thanks so much for your question -- I wonder if you would be able to share if you are calling wandb.watch after the model has been fully defined or if are you making modifications to the model after you have called wandb.watch? 

would you also be able to share a code snippet of the structure of your model here this would
 be helpful in trying to understand and reproduce the behavior that you are seeing.

**Comment by MartinPerry** [comment]
Yes, the model is fully inited. I call watch just before I run the training loop.
There should be no model structure modifications after the watch call.

```
class SomeModel(AbstractTorchModel, nn.Module):
    def __init__(self,
                 type: AbstractModel.ModelType,
                 inputShape: Optional[list[int]]                 
                 ):
       
        AbstractTorchModel.__init__(self, type, inputShape)
        
        self.conv1 = nn.Sequential(
            nn.Conv2d(inputShape[0], 64, kernel_size=7, stride=2, padding=3, bias=False),
            nn.BatchNorm2d(64),
            nn.ReLU()
        )
       ..... more layers ...
```

and its parent

```
class AbstractTorchModel(AbstractModel, nn.Module):

    def __init__(self, 
                 type: AbstractModel.ModelType,
                 inputShape: Optional[list[int]] = None):

        AbstractModel.__init__(self, type)
        nn.Module.__init__(self)

        self.evaluator = DefaultTorchEvaluator(self)
        self.optimizer = None      
        self.inputShape = inputShape
```

and its parent

```
class AbstractModel:

    class ModelType(Enum):
        SINGLE_LABEL = 1,
        MULTI_LABEL = 2,
        SEGMENTATION = 3,
        CUSTOM = 4

    class RunType(Enum):
        TRAIN = 1,
        VALID = 2,
        TEST = 3,
        INFERENCE = 4

    def __init__(self, type: AbstractModel.ModelType):
        super().__init__()    
        self.start = {}

        #init model classification type
        self.type = type
        self.activeRunType = None
```

I have provided only constructors to see members. However, there ara more methods and code is quite long.

**Comment by MartinPerry** [comment]
I have tracked the problem to DataLoader. If I use num_workers = 0, it is working, if I set num_workers > 0, it crash.

**Comment by MartinPerry** [comment]
I tried to debug it. I have problem only when I use num_workers > 0 (if set to 0, it works). It is curious, since in your example, where is num_workers set to 2 and it works.

However, the crash seems to be related with TorchHistory.add_log_parameters_hook and there is:

```
hook = module.register_forward_hook(
                lambda mod, inp, outp: parameter_log_hook(
                    mod, inp, outp, log_track_params
                )
            )
```

I have problems with lambdas and num_workers on windows. When I replaced lambdas with classes, problem was gone. 
Maybe instead lambda a solution would be to use class with @staticmethod and static parameters? Can I write my own hook, will it work?

**Comment by luisbergua** [comment]
Hey @MartinPerry, thanks for providing this info! I have checked this and looks like the issue is actually related to Windows (Python's multiprocessing module works differently than in Unix systems). It should work if you replace that with your own hook so would it be possible to give this a try and let us know about the results? Thanks!

**Comment by MartinPerry** [comment]
Hi, I have reworked my code so that wandb is not accessed (or referenced) from any code that is inside a thread and it works now.
