### ISSUE TITLE
[Q] How do I download a specific run from a project?

### ISSUE THREAD

**Issue by Akella17** [wandb/wandb#5542]
I am looking at the [Export API](https://docs.wandb.ai/guides/track/public-api-guide) and I tried the following:
```
import wandb
api = wandb.Api()
run = api.run("<entity>/<project>/<run_id>")
```
But I run into `ValueError: Could not find project <project>/<run_id>` error. This error does not appear when I do not provide the run_id, but instead loop over all the runs in the dataset.

**Comment by nate-wandb** [comment]
Hi @Akella17, would you possibly be able to send the literal string that is passed to `api.run()`? Your code should work here so I'm not sure the exact issue but I can test this out from my side. 

Thank you,
Nate

**Comment by nate-wandb** [comment]
Hi @Akella17, I just wanted to follow up and see if this was still an issue?
