### ISSUE TITLE
[Feature]:  Documentation and example of `${envvar}` sweep command configuration usage

### ISSUE THREAD

**Issue by ezhang94** [wandb/wandb#5556]
### Description

The `${envvar}` macro in the [sweep command configuration](https://docs.wandb.ai/guides/sweeps/define-sweep-configuration#command-) has been a very useful feature, but I found the documentation/macro description misleading and wished there was an example of how to use it.

## Update macro description 
Currently, the `${envvar}$ macro description is as follows:
![image](https://github.com/wandb/wandb/assets/2763069/5ee1bc80-45da-46f4-91bb-f7a3ed1efebf)

However, this should be corrected to
> A way to pass environment variables. **${envvar:MYENVVAR}** expands to the value of MYENVVAR environment variable.

The bolded text highlights the change: no space between colon and MYENVVAR. This requirement becomes evident in how the command is parsed (i.e. by the [agent's envvar regex object](https://github.com/wandb/wandb/blob/b2615a0b6d8547cd0a28666947dac9566e923522/wandb/wandb_agent.py#L137)).

## Example usage
The follow example demonstrates how the environmental variable macro can be used on its own and with other macros:
```
command:
  - ${env}
  - ${interpreter}
  - ${envvar:VAR1}
  - ${program}
  - "--param=${envvar:VAR2}"
  - ${args}
 ```
where, for example, `VAR1="-m cProfile"` is a variable to modify which profiler, and `VAR2` is a runtime variable.

**Comment by luisbergua** [comment]
Hi @ezhang94, thanks for reporting this! You're right that this needs to be ${envvar:MYENVVAR} so will ping our team internally to update this. Thanks!

**Comment by luisbergua** [comment]
Hi @ezhang94, this has been updated on our docs. Thanks!
