### ISSUE TITLE
[CLI]: Offline run folders appear without required information and can't be synced

### ISSUE THREAD

**Issue by tristanengst** [wandb/wandb#5561]
### Describe the bug

Offline runs don't always log the information needed for them to be synced, so the information they generate is effectively lost. This happens for around 50% of the offline runs on my cluster, so it's a large issue. So far, I haven't found any factor that correlates with a run working or not. When I run the same code but as an online run, everything works as expected.

More precisely, when the bug occurs, the `offline-run-...` folder created in the `wandb` directory is missing files—see in **additional files** for details. When I try to log it with `wandb sync`, on one such folder, I get
```
(py310IMLESSL) [tme3@narval3 wandb]$ wandb sync offline-run-20230517_061457-bz3nyzr9
Find logs at: /tmp/debug-cli.tme3.log
Skipping directory: /lustre06/project/6061877/tme3/IMLE-SSL/wandb/offline-run-20230517_061457-bz3nyzr9
```
The relevant logs are apparently empty. I also don't find mention of the run in `debug-cli.tme3.log`, while the UIDs of runs that did work correctly do appear there.

I would very much appreciate help solving this! Please let me know if there is other information that would be useful.

### Additional Files

To fully explain what I can see of the issue, here are two runs with identical arguments. I've attached files giving the SLURM submission script, job output file, and zipped run directory respectly, first for a run that did work, and next for one that didn't. Note that the submission scripts and output files are effectively the same—up to compute node, time, and wandb UID details.

--- Job that did work correctly ---
[good_job_results.txt](https://github.com/wandb/wandb/files/11497373/good_job_results.txt)
[good_job_submission_script.txt](https://github.com/wandb/wandb/files/11497393/good_job_submission_script.txt)
[offline-run-20230517_070615-a25xgj3m.zip](https://github.com/wandb/wandb/files/11497410/offline-run-20230517_070615-a25xgj3m.zip)

--- Job that didn't work correctly ---
[bad_job_submission_script.txt](https://github.com/wandb/wandb/files/11497156/bad_job_submission_script.txt)
[bad_job_results.txt](https://github.com/wandb/wandb/files/11497170/bad_job_results.txt)
[offline-run-20230517_061457-bz3nyzr9.zip](https://github.com/wandb/wandb/files/11497211/offline-run-20230517_061457-bz3nyzr9.zip)
The major thing to note about the offline run directory that was created was that it contained _only_ the images I wanted to log, and none of the other files—ie. its top-level should contain the following five entries—`files  logs  run-a25xgj3m.wandb  tmp  wandb`—but instead looks has just one—`files`.

 (Also: due to space constraints from GitHub, I had to unzip and delete some of the images so the zip files would fit.)

### Environment

WandB version: 0.15.1

OS: Linux with Lustre filesystem—probably modified since it's the [Narval cluster of ComputeCanada](https://docs.alliancecan.ca/wiki/Narval/en)

Python version: 3.10.11

Versions of relevant libraries:

**Comment by tristanengst** [comment]
Up till cancelling, you'd see the same outputs in all offline runs, regardless of if they could be synced. In this case, after seeing the job had been running for a while without the folder being created correctly, I cancelled it to avoid wasting compute.

**Comment by thanos-wandb** [comment]
Hi @tristanengst thanks for the additional information, could you please share a minimal example of your Slurm job script file? are these runs part of Sweep and if so are you submitting jobs in a preemptible queue?

**Comment by tristanengst** [comment]
Hi! I've abbreviated and attached one of the SLURM submission scripts from my comment above, and I've replicated it below (or am I misinterpreting and you're asking for a different file?). These aren't part of sweeps and the cluster itself doesn't have preemtion.

The key is in the quotation marks; the first apparent invocation of python is just echoing the script and its arguments to the job result file. Maybe it's somehow being executed?
```
#!/bin/bash

# The SBATCH directives must appear before any executable line in this script.

#SBATCH --time=3:00:00
#SBATCH --account=rrg-keli
#SBATCH --mem=100GB
#SBATCH --nodes=1
#SBATCH --cpus-per-task=12
#SBATCH --gres=gpu:a100:1

#SBATCH --job-name=imle-vit_base_v0-imagenet-bs32-epochs50-ipe20-lr1e-8_ramp_1e-6_ramp_5e-7_1e-7-ns128-nshotall-nway1-seed0-bz3nyzr9-May15-FinetuneLR-GPUS1-TIME3:00:00
#SBATCH --output=job_results/%x_%a.txt

# Below sets the email notification, swap to your email to receive notifications
#SBATCH --mail-user=tristanengst@gmail.com
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=REQUEUE
#SBATCH --mail-type=ALL

export OMP_NUM_THREADS=1
# Print some info for context.
pwd
hostname
date

echo "Starting job number $SLURM_JOB_ID"
source ~/.bashrc
conda activate py310IMLESSL
export PYTHONUNBUFFERED=1

echo "echo 'start: '`date`
mkdir -p $SLURM_TMPDIR/imagenet
echo 'Extracting /home/tme3/scratch/Data/imagenet/train.tar...'
tar -xf /home/tme3/scratch/Data/imagenet/train.tar -C $SLURM_TMPDIR/imagenet
echo 'done: '`date`
mkdir -p $SLURM_TMPDIR/imagenet
echo 'Extracting /home/tme3/projects/rrg-keli/data/imagenet/val.tar...'
tar -xf /home/tme3/projects/rrg-keli/data/imagenet/val.tar -C $SLURM_TMPDIR/imagenet
echo 'done: '`date`


python TrainSSL.py  --wandb offline ... other arguments"

echo 'start: '`date`
mkdir -p $SLURM_TMPDIR/imagenet
echo 'Extracting /home/tme3/scratch/Data/imagenet/train.tar...'
tar -xf /home/tme3/scratch/Data/imagenet/train.tar -C $SLURM_TMPDIR/imagenet
echo 'done: '`date`
mkdir -p $SLURM_TMPDIR/imagenet
echo 'Extracting /home/tme3/projects/rrg-keli/data/imagenet/val.tar...'
tar -xf /home/tme3/projects/rrg-keli/data/imagenet/val.tar -C $SLURM_TMPDIR/imagenet
echo 'done: '`date`


python TrainSSL.py  --wandb offline ... other arguments

# Print completion time.
date
```

**Comment by thanos-wandb** [comment]
Hi @tristanengst thanks so much for sharing the SLURM job script. I was wondering if that issue occurs for you only when you run two consecutive experiments in the way you provided above. Does it happen if you only had a single run? If not, could you please make sure that you add in the end of your `TrainSSL.py` script a `wandb.finish()` call?

**Comment by tristanengst** [comment]
Also, would it be possible in the meantime to spoof a correct run by creating the necessarily files manually? Maybe it'd be too much effort?

**Comment by thanos-wandb** [comment]
Hi @tristanengst thanks for the detailed additional information. Could you please `pip install wandb --upgrade` to our most recent version, and check if the issue still occurs there? 

Do you pass any settings in your `wandb.init` call, could you please share here a code snippet? Also, can you try to disable the symlinks as follows, would this help? `wandb.init(settings=wandb.Settings(symlink=False))`

**Comment by tristanengst** [comment]
Here's my `wandb.init()`, with `symlink=False` as suggested. `args` is an argparse `Namespace`:
```
wandb.init(anonymous="allow", id=args.uid, config=args,
        mode=args.wandb, project="3MRL", entity="apex-lab",
        name=os.path.basename(model_folder(args)),
        resume="allow" if args.continue_run else "never",
        settings=wandb.Settings(code_dir=os.path.dirname(__file__), symlink=False))
```
With conda-installed `wandb=0.15.1`, this appears to fix the issue! I will test the newer WandB version soon, though I suspect I will have to install it via conda, as pip packages are in my experience less likely to work on the cluster in question.

**Comment by thanos-wandb** [comment]
Hi @tristanengst thanks a lot for the confirmation, glad to hear this is now resolved for you! Just for your information, we have released a new version v0.15.4, and you could pip or conda upgrade to it. I will close this ticket for now, as it seems resolved, but please feel free to reopen it if you experience any issue after upgrade and we will be happy to keep investigating.

**Comment by tristanengst** [comment]
Unfortunately it happened again; I'm continuing to investigate with `wandb=0.15.4`.

**Comment by thanos-wandb** [comment]
Sorry to hear this issue occurred again @tristanengst please let me know if that happens with the most recent version too, and I will report/escalate to our SDK team.

**Comment by thanos-wandb** [comment]
Hi @tristanengst just checking in here to see if you have seen the same issue again after upgrading to v0.15.4? Thank you!

**Comment by tristanengst** [comment]
So far I have two successes and zero failures with v0.15.4. I'll follow up if there are subsequent failures as I'll be using the cluster fairly heavily this week.

**Comment by thanos-wandb** [comment]
Perfect, glad to hear that so far seems to work fine. Please let us know later this week if everything went fine.

**Comment by thanos-wandb** [comment]
Hi @tristanengst just checking in here to see if the issue popped up again? thanks!

**Comment by thanos-wandb** [comment]
Hi @tristanengst since we haven't heard back from you and last time the issue seemed resolved, I will go ahead and close this ticket for now. If you're still experiencing any issue please let us know and we will be happy to keep investigating.
