### ISSUE TITLE
LangChain Prompt traces fail even in your example Colab demo

### ISSUE THREAD

**Issue by ryan-popa** [wandb/wandb#5567]
### Describe the bug

Prompts functionality is not working for langchain. It even fails in your demo Colab https://colab.research.google.com/github/wandb/examples/blob/master/colabs/prompts/W%26B_Prompts_Quickstart.ipynb#scrollTo=5vcPcOs8WXsG

There is no documentation on the missing fields

```python
questions = [
    "Find the square root of 5.4.",
    "What is 3 divided by 7.34 raised to the power of pi?",
    "What is the sin of 0.47 radians, divided by the cube root of 27?",
    "what is 1 divided by zero"
]
for question in questions:
  try:
    answer = agent.run(question, callbacks=[WandbTracer(wandb_config)])
    print(answer)
  except Exception as e:
    print(e)
    pass
```
2 validation errors for TracerSession
tenant_id
  field required (type=value_error.missing)
id
  value is not a valid uuid (type=type_error.uuid)
2 validation errors for TracerSession
tenant_id
  field required (type=value_error.missing)
id
  value is not a valid uuid (type=type_error.uuid)
2 validation errors for TracerSession
tenant_id
  field required (type=value_error.missing)
id
  value is not a valid uuid (type=type_error.uuid)
2 validation errors for TracerSession
tenant_id
  field required (type=value_error.missing)
id
  value is not a valid uuid (type=type_error.uuid)

```shell

```

### Environment

WandB version:

OS:

Python version:

Versions of relevant libraries:

**Comment by rsanandres-wandb** [comment]
Hello @ryan-popa !

There is a [fix](https://github.com/wandb/wandb/pull/5558) that has been merged but has not yet pushed to our newest SDK version. We are releasing the fix as part of our next release so we apologize for the inconvenience. Our `WandbTracer `currently has a missing dependency that is needed for `langchain >= 0.0.170`.

**Comment by ayulockin** [comment]
Hey @ryan-popa, W&B Trace is an old product offering which is not maintained anymore. We were focused on shipping a better tooling called W&B Weave. Team is working on the Langchain integration.

[Weave announcement](https://wandb.ai/wandb/weave-announcement/reports/Weave-Simple-tools-for-applying-Generative-AI--Vmlldzo3NDE0Mjcx)
[Weave Documentation](https://wandb.github.io/weave/)

Closing this issue for now. Do let me know if you need anything more.
