### ISSUE TITLE
[Q] Capture model-best, not model-last in sweep for comparison of optimal weights

### ISSUE THREAD

**Issue by JeremyCraigMartinez** [wandb/wandb#5591]
I am seeing a similar issue to https://github.com/wandb/wandb/issues/5439. I want to know how to run a sweep with parameters based off of the performance of the model-best weights, not the model-last weights. I'm sure there are use-cases for everything, but it seems to me like this would be the default since, after training a model, you would probably want the weights from the model that tested the best, not simply from the last epoch. Here is a breakdown of my current setup:

I am training an NER model with spaCy. I am using the following logging config

```
config['training.logger'] = {
    '@loggers': 'spacy.WandbLogger.v4',
    'project_name': project_name,
    'remove_config_values': [],
    'log_dataset_dir': './assets',
    'model_log_interval': '100',
    'log_best_dir': './training/model-best',
}
```

and it publishes `./training/model-last` instead of `./training/model-best`. Naturally, I would want to compare the best scores rather than just the last scores. In the `sweeps.yml` I have the following

```
method: bayes
metric:
  goal: maximize
  name: score
command:
  - ${env}
  - ${interpreter}
  - sweeps.py
  - ./configs/config.cfg
  - ./training
parameters:
    ...
```

I can see in the stdout the discrepancy between last and best. For example:

```
E    #       LOSS TOK2VEC  LOSS NER  ENTS_F  ENTS_P  ENTS_R  SCORE 
---  ------  ------------  --------  ------  ------  ------  ------

...

wandb: Adding directory to artifact (./training/model-last)... Done. 0.0s

 20    1640       3791.26     97.41   57.14   65.85   50.47    0.57

 20    1650      12032.89    165.31   56.09   60.43   52.34    0.56

 20    1660       3669.51     56.44   54.45   61.90   48.60    0.54

wandb: Waiting for W&B process to finish... (success).

wandb: Run history:
wandb:       ents_f ▁▂▂▃▃▂▄▅▆▆▄▅▆▆▄▇▃▆▆▇▆▆█▆▇▇▇▇▇▇▆█▇█▇▇▇▇██
wandb:       ents_p ▁▂▃▄▃▂▅▆▅▆▄▅▆▆▄▇▄▆▆▆▆▆▇▇▇▇▇▇▇▆▇█▇█▇▇▇▇█▇
wandb:       ents_r ▁▁▂▃▃▂▄▄▆▅▃▅▆▆▄▇▃▆▅▇▅▆█▆▇▇▆▇▇▇▆█▇▇▇▇▇███
wandb:     loss_ner █▂▁▂▁▂▁▁▁▁▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: loss_tok2vec ▁█▁█▁▃▁▁▁▁▁▄▁▂▂▁▂▁▁▁▂▁▁▂▁▁▆▂▁▂▂▁▁▂█▂▂▁▁▃
wandb:        score ▁▂▂▃▃▂▄▅▆▆▄▅▆▆▄▇▃▆▆▇▆▆█▆▇▇▇▇▇▇▆█▇█▇▇▇▇██
wandb:        speed ▅▇▅▁▂▁▂▃▂▂▄▄▅▄▅█▇▄▆▇▅▆▆▆▄▅▅▅▅▂▁▅▆▅▅▆▅▅▅▂
wandb:    token_acc ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:      token_f ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:      token_p ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:      token_r ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: 
wandb: Run summary:
wandb:       ents_f 0.5445
wandb:       ents_p 0.61905
wandb:       ents_r 0.48598
wandb:     loss_ner 56.43864
wandb: loss_tok2vec 3669.51386
wandb:        score 0.5445
wandb:        speed 57350.0027
wandb:    token_acc 1.0
wandb:      token_f 1.0
wandb:      token_p 1.0
wandb:      token_r 1.0
```

In the terminal output, the best score is clearly 57, but wandb captures 54 instead. How can I capture `./training/model-best` rather than `./training/model-last`?

cc @thanos-wandb since you helped out with the related issue I tagged above.

Thanks in advance!

**Comment by JeremyCraigMartinez** [comment]
My hope was to capture it in the UI, to make this plot more useful. Right now, this plot depicts the model-last score

![Screenshot 2023-05-22 at 10 39 07 AM](https://github.com/wandb/wandb/assets/6334199/04625bc9-a1b2-4d07-80a1-e8eafd987712)

**Comment by thanos-wandb** [comment]
Hi @JeremyCraigMartinez thanks a lot for the clarification, it seems you will need the `define_metric` here as well as in the following example:

```
# Import the W&B Python Library and log into W&B
import wandb
import random

wandb.login()

# 1: Define objective/training function
def objective(config):
    score = config.x ** 3 + config.y + random.random() * 2.0
    return score

def main():
    wandb.init()
    wandb.define_metric('score', summary='min,max,mean,last')
    for i in range(10):
      score = objective(wandb.config)
      wandb.log({'score': score})
    wandb.finish()

# 2: Define the search space
sweep_configuration = {
    'method': 'random',
    'metric': 
    {
        'goal': 'minimize', 
        'name': 'score'
        },
    'parameters': 
    {
        'x': {'max': 0.1, 'min': 0.01},
        'y': {'values': [1, 3, 7]},
     }
}

# 3: Start the sweep
sweep_id = wandb.sweep(
    sweep=sweep_configuration, 
    project='my-min-max-sweep'
    )

wandb.agent(sweep_id, function=main, count=10)
```

This will create the additional aggregate metrics and you should be able to add the score.max in the parallel coordinates plot. Would this work for you?

**Comment by JeremyCraigMartinez** [comment]
Thanks for the suggestion @thanos-wandb. This led me to a solution.

**Comment by thanos-wandb** [comment]
Thanks a lot @JeremyCraigMartinez for the confirmation, glad to hear this is now resolved for you! We will close this ticket now, and please feel free to reach out to us if you had any other questions.
