### ISSUE TITLE
[CLI]: deleting a variable from run.summary fails if it hasn't already been accessed

### ISSUE THREAD

**Issue by christian-storm** [wandb/wandb#5592]
### Describe the bug

For del run.summary[<var_name>] to work, run.summary[<var_name>] must have been accessed first for reading or writing.  Querying for existence, i.e., <var_name> in run.summary isn't enough.

I've inlined the exceptions in the code.  You'll have to modify <project_name>, <project_run>, and set summary_var to a variable in the run.summary.

```python
import wandb

run_path = "<project_name>/<project_run>"
summary_var = 'train_recall'
api = wandb.Api()
run = api.run(run_path)
if summary_var in run.summary:
    print(f"Variable {summary_var} is in run.summary")
    try:
        del run.summary[summary_var]  # KeyError
    except KeyError as err:
        print(f"Tried to delete {summary_var} from run.summary but received a KeyError exception: {err}")
        """  File "wandb_del_summary_bug.py", line 9, in <module>
                    del run.summary[summary_var]  # KeyError
                  File "<conda environment>/python3.10/site-packages/wandb/old/summary.py", line 141, in __delitem__
                    del self._dict[k]
                KeyError: 'train_recall'"""
    print(f"Is the variable {summary_var} still in run.summary? {summary_var in run.summary}")
    try:
        print(f"Trying to access the value for run.summary[{summary_var}] = {run.summary[{summary_var}]}")
    except TypeError as err:
        print(f"The delete did some damage resulting in a TypeError exception when trying to access run.summary[{summary_var}]: {err}")
        """
        File "wandb_del_summary_bug.py", line 14, in <module>
          print(f"Variable run.summary[{summary_var}] = {run.summary[{summary_var}]}")
        File "<conda environment>/python3.10/site-packages/wandb/old/summary.py", line 108, in __getitem__
          self.get(k)  # load the value into _dict if it should be there
        File "<conda environment>/python3.10/site-packages/wandb/old/summary.py", line 94, in get
          if k not in self._dict:
        TypeError: unhashable type: 'set'"""

print(f"After all that is the variable {summary_var} still in run.summary? {summary_var in run.summary}")
print("If we reset it, the del will work.")
run.summary[summary_var] = 0.5
del run.summary[summary_var]
print("But it isn't the act of setting it that is necessary.  It's the act of accessing it which setting obviously does.")

print("Let's try this again but this time we'll access the variable before trying to delete")
run = api.run(run_path)
if summary_var in run.summary:
    print(f"Variable {summary_var} is in run.summary and has the value {run.summary[summary_var]}")
    del run.summary[summary_var]
print("It worked!! I guess the variable has to be set or accessed before deletion is possible.")
```

The stdout from print statements is provided below.

```shell output when the above is run
Variable train_recall is in run.summary
Tried to delete train_recall from run.summary but received a KeyError exception: 'train_recall'
Is the variable train_recall still in run.summary? True
The delete did some damage resulting in a TypeError exception when trying to access run.summary[train_recall]: unhashable type: 'set'
After all that is the variable train_recall still in run.summary? True
If we reset it, the del will work.
But it isn't the act of setting it that is necessary.  It's the act of accessing it which setting obviously does.
Let's try this again but this time we'll access the variable before trying to delete
It worked!! I guess the variable has to be set or accessed before deletion is possible.
```

### Environment

WandB version: wandb-0.15.3

OS: Mac 13.3.1

Python version: 3.10.4

Versions of relevant libraries: None

**Comment by nate-wandb** [comment]
Hi @christian-storm, thank you for reporting this. I was able to reproduce this as well. Also, just a note that you will have to call `run.summary.update()` at the the end if you would like the deletion to persist. 

I'll submit this to our engineering team and will follow up back up once they get a chance to look into this. 

Thank you,
Nate

**Comment by christian-storm** [comment]
Thanks for the tip Nate...I'm aware of this but left it out so I could reproduce.  However, I must admit I'm a little confused as to the difference between run.update() and run.summary.update().  Does the latter just update the summary bits while the former does the whole enchilada?

**Comment by nate-wandb** [comment]
Hi @christian-storm, sorry for the delay on this. That is correct, `run.update()` will update everything vs `run.summary.update()` and run.config.update()` only affect the summary or config respectively

**Comment by alexaatm** [comment]
Having the same issues, when adding additional metrics to the summary using `run.summary[key]=value` ... See the plot in the custom chart editor but then cannot apply the changes and save it.

**Comment by sydholl** [comment]
WandB Internal User commented: 
christian-storm commented: 
Thanks for the tip Nate...I'm aware of this but left it out so I could reproduce.  However, I must admit I'm a little confused as to the difference between run.update() and run.summary.update().  Does the latter just update the summary bits while the former does the whole enchilada?

**Comment by MBakirWB** [comment]
@christian-storm please note this has been [fixed](https://github.com/wandb/wandb/pull/7720) and will be reflected in the next version of our sdk
