### ISSUE TITLE
[App]: Embedding Projector is not working

### ISSUE THREAD

**Issue by ivivan** [wandb/wandb#5604]
### Wandb embedding projector does not work in the newest version. Plot is empty, for all 3 dimention reduction algorithms.

Check the online demo from the official document (https://docs.wandb.ai/guides/app/features/panels/weave/embedding-projector):

**Demo does not work:**

https://wandb.ai/timssweeney/toy_datasets/reports/Feature-Report-W-B-Embeddings-Projector--VmlldzoxMjg2MjY4?accessToken=bo36zrgl0gref1th5nj59nrft9rc4r71s53zr2qvqlz68jwn8d8yyjdz73cqfyhq&_gl=1*10obh03*_ga*MTE2NzY5MTA4MS4xNjgyNDc4NTY1*_ga_JH1SJHJQXJ*MTY4NDg4MzExOC41MC4xLjE2ODQ4ODU4MDYuMTUuMC4w

### Expected Behavior

should be able to generate 2D plots.

### Steps To Reproduce

Run the official colab and check on the UI:

https://colab.research.google.com/drive/1DaKL4lZVh3ETyYEM1oJ46ffjpGs8glXA#scrollTo=D--9i6-gXBm_

### Environment

OS:

Browsers: Chrome

Version:

**Comment by thanos-wandb** [comment]
Hi @ivivan thanks so much for reporting this issue, and providing all these detailed info. There was a change deployed yesterday that may have caused this regression in the App. I have notified our engineers and we will keep you posted here once it's fixed.

**Comment by thanos-wandb** [comment]
Hi @ivivan thanks a lot once again for reporting this issue, this has been now fixed by our engineers. I will close this ticket now, but please feel free to re-open it if you're still experiencing any issue and we will be happy to keep investigating.
