### ISSUE TITLE
[Feature]: Allow an optional `dir` argument to wandb.sweep(), like you do already for wandb.init()

### ISSUE THREAD

**Issue by fantauzzi** [wandb/wandb#5611]
### Description

`wandb.sweep()` currently doesn't allow setting the directory where metadata will be stored. As a consequence, `wandb.sweep()` always sets it to `./wandb`, which is not always desirable.
Note that we may not want to call `wandb.init(dir=...)` first, because that also starts a new W&B run. 

### Suggested Solution

`wandb.sweep()` should have an optional argument `dir` which behaves the same as the `dir` argument of `wandb.init()`
Also the CLI command `wandb sweep` should have the same.

### Alternatives

The workaround for the missing feature can be to set the environment variable `WANDB_DIR` to the desired directory before calling `wandb.sweep()`

### Additional Context

`wandb.sweep()` creates a `wandb` directory in the current directory (unless the `WANDB_DIR` variable is set otherwise). That may be an undesirable location for such a directory. In my case, that is where the Python source code resides, which also messes up Pycharm code navigation and autocompletion. When Pycharm looks for the `wandb` package to support those functionalities, it finds a `wandb` directory in the same place as the source code, mistakes it for the package directory, doesn't find anything in it, and gives up; therefore code navigation and autocompletion for all the `wandb` package content doesn't work.

**Comment by umakrishnaswamy** [comment]
Hey @fantauzzi,

I submitted a feature request for the scenario you mentioned, and our engineering team is currently looking into it. Will update you with progress!

Best,

Uma

**Comment by igoradamski2** [comment]
Hi - you marked this as completed, but I think that this feature is not implemented?
