### ISSUE TITLE
Downloading files with wilcards 

### ISSUE THREAD

**Issue by rogelioamancisidor** [wandb/wandb#5618]
I download files from python as follows

    api = wandb.Api()
    filepath = os.path.join("media","plotly","weights_plot_399_9729139ec10905caa747.plotly.json")
    entity, project, run_id = "my_entity", "my_project", my_run
    file = api.run(f"{entity}/{project}/{run_id}").file(name=filepath)
    file.download()

However, I am looking for a solution where `filepath` can use wildcars, e.g.
    
    filepath = os.path.join("media","plotly","weights_plot_399*")

so I dont need to look for the last part of the file name.

**Comment by luisbergua** [comment]
Hi @rogelioamancisidor, thanks for writing in! You can use a code like the following to achieve that:
```
import fnmatch
import wandb

api = wandb.Api()
run = api.run("entity/project/run_id")
matching_files = [file for file in run.files() if fnmatch.fnmatch(file.name, "media/plotly/weights_plot_399*")]
for file in matching_files:
    file.download() 
```
Could you please give this a try and see if it works?

**Comment by rogelioamancisidor** [comment]
Thanks @luisbergua, it works as expected!
