### ISSUE TITLE
[App]: Cannot scroll through panels because of overflow

### ISSUE THREAD

**Issue by rjbruin** [wandb/wandb#5628]
### Current Behavior

In Chrome on Linux the dashboard screen overflows to the right, making it impossible to use the arrows that scroll through panels.

This does not happen on Edge.

### Expected Behavior

The screen should not overflow, so that the full interface is visible.

### Screenshots

![Screenshot from 2023-05-27 22-31-52](https://github.com/wandb/wandb/assets/7921619/f8b621cc-ff80-495f-b47b-bd33ca02b277)

### Environment

OS: Ubuntu 22.04

Browsers: Chrome

Version: Chrome 113.0.5672.126 (Official Build) (64-bit)

**Comment by luisbergua** [comment]
Hi @rjbruin, thanks for reporting this! You should be able to modify the size of the panels' section to make it bigger as shown in the video attached, would this help to scroll through the different panels?

https://github.com/wandb/wandb/assets/113048227/71c933b9-a6b9-46cb-932a-4a8d7e37d673
