### ISSUE TITLE
[Q] Runs are using too many CPU threads.

### ISSUE THREAD

**Issue by sinAshish** [wandb/wandb#5629]
Hello,

I am using wandb with pytorch_lightning[1.7.5] for my project, and instead of using logging using wandb, I use PL's wandb_logger.
I notice that my experiments are using too many CPU threads, thereby throttling the number of jobs I can run on a A100 GPU on a slurm cluster.
I can't seem to figure out why it is using so many threads, since I'm only logging losses and metrics after every 500 or 1k iterations, and not using `step=True` or `epoch=True` arguments in self.log(...). This saves me RAM.
Any insight would be helpful.

![image](https://github.com/wandb/wandb/assets/21974209/fd0a8dad-61dd-4f38-8af5-1f9f5cbf5bce)

**Comment by rsanandres-wandb** [comment]
Hello @sinAshish!

In terms of `wandb`, we are only logging the CPU threads that are being used but not necessarily what causes the high amount of CPU threads. I would suggest looking into `pytorch_lightning[1.7.5]` and looking into what issues may arise from that package. For example, this [thread](https://github.com/pytorch/pytorch/issues/80777) regarding high CPU usage when using `torch` may be of your interest.

**Comment by sinAshish** [comment]
> we are only logging the CPU threads that are being used 
@rsanandres-wandb 
that's what I don't understand either. I'm using wandb logger and have self.log, maybe 8-10 times throughout my code, and my num_workers=0 in the dataloader because if I increase num_workers>0, it gives a forking error: "cannot create new thread".

**Comment by rsanandres-wandb** [comment]
Could you provide a code snippet of how you are initializing the training? `wandb` should not be spinning up more threads than needed (much less be spinning up 85 threads in parallel) so maybe there is some behavior within the code that is spinning up multiple threads.

**Comment by sinAshish** [comment]
My PL class looks something like:
```python
class MainModel(pl.LightningModule):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.model = ...
        # init datasets 

    def forward(self, x):
        return self.model(x)

    def training_step(self, batch, batch_idx):
       ...
       # similarly for val and test step

    def training_epoch_end(self, outputs):
       # some visualization code
       # avg metrics
        # similar for val and test at epoch end

    def train_dataloader(self):
        # prepare dataloader with num_workers=0
        # similar for val and test
        
    def calc_error(self, x, y):
        # compute errors 

    @torch.no_grad()
    def plot(self, x, y):
        # plot some results
```
my Logger initialization is:
```python
opt=# config
wandb_logger = WandbLogger(
            project='Name', 
            resume='allow',
            name=opt.name,
            save_code=True,
            allow_val_change=True,
            config = opt._cfg_dict,
            settings = wandb.Settings(code_dir=".."),
            )
```
some callbacks and trainer config:
```python
ckpt_cb = # based on some metric
early_stop = ...
lr_monitor = ..
swa_callback = ...
rich_bar=...
ddp_strat = ddp.DDPStrategy(find_unused_parameters = True , process_group_backend=opt.dist_backend, timeout = datetime.timedelta(seconds=80))

rainer = Trainer(
        sync_batchnorm=True,
        default_root_dir=opt.save_dir,
        logger = [wandb_logger],
        callbacks=[,
            checkpoint_callback1, \
                early_stop, \
                lr_monitor,\
                rich_pbar if os.getenv('SLURM_JOB_ID') is not None else pbar, \
                RichModelSummary(max_depth=2), \
                swa_callback, \
                ],
        accelerator='gpu',
        devices =  "auto",
        auto_select_gpus=True,
        benchmark = True,
        max_epochs = opt.num_epoch,
        detect_anomaly=True,
        accumulate_grad_batches = 1 if opt.batch_size>=4 else 4//opt.batch_size,
        plugins = [SLURMEnvironment()] if 'SLURM_JOB_ID' in os.environ else None,
        strategy=ddp_strategy, 
    )
```

hope this is informative enough!

**Comment by rsanandres-wandb** [comment]
After looking around, I wanted to clarify the meaning of the chart. The `Process CPU Threads in Use` counts all the CPU threads used by the machine logging with `wandb` and not necessarily what `wandb` is using. For context, the number logged comes from `psuutils` and comes from the `cpu.threads()` ([documentation here](https://psutil.readthedocs.io/en/latest/index.html?highlight=cpu%20threads#psutil.Process.threads)). That is to say, after looking at the code and running similar code, the amount of threads are higher than what I was running (roughly 70 threads on my experiment) but not significantly more. However, this does not look to be `wandb` that is running many threads at once.

**Comment by sinAshish** [comment]
oh thank you. that could be it?! 
do you have any tips on how I could reduce the amount of threads in my experiment? @rsanandres-wandb

**Comment by rsanandres-wandb** [comment]
In PyTorch, you can set the number of threads using `torch.set_num_threads()` at the beginning of your script, which gives you some level of control over the threads. You can also check the processes being used by accessing the Activity Monitor's Memory tab or the Task Manager's Services tab, which will give you a better idea of the processes running. It's possible that other programs are also utilizing threads.
