### ISSUE TITLE
protobuf dependency error

### ISSUE THREAD

**Issue by function2-llx** [wandb/wandb#5633]
To reproduce:

```zsh
conda create -n test python=3.10 wandb
conda activate test
python -c 'import wandb'
```
output:
```
ImportError: .../envs/test/lib/python3.10/site-packages/google/protobuf/pyext/_message.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN6google8protobuf2io17SafeDoubleToFloatEd
```

Current workaround: install libprotobuf=3.21.12 manually

**Comment by rsanandres-wandb** [comment]
Hello @function2-llx !

I wasn't able to replicate the exact error you had with your code and the following code worked for me. 

```
conda create -n test python=3.10
conda activate test
python -c 'import wandb'
```

However, after some research it looks like there were several versions of google `protobuf` buffers that are clashing in your system which resulted in your error. ([GitHub Post](https://github.com/facebookresearch/DensePose/issues/119#issuecomment-422692756) I am referencing)

**Comment by function2-llx** [comment]
Hello @rsanandres-wandb , thank you for your reply. 

I'm sorry that I didn't provide all information to reproduce. After some investigation, I find that my highest priority channel is conda-forge. In this case, it will install a higher version of protobuf and cause the issue.

Here are the more detailed steps to reproduce the issue:

## Prioritize Anaconda's official defaults channel 

Create the environment and install `wandb`, where Anaconda's official defaults channel has higher priority than conda-forge.

```zsh
conda create -n test-dft python=3.10 wandb -c defaults -c conda-forge
conda list -n test-dft | grep protobuf
```

### Output
```
libprotobuf               3.20.3               he621ea3_0    defaults
protobuf                  3.20.3          py310h6a678d5_0    defaults
```

In this case, `conda activate test-dft && python -c 'import wandb'` works fine.

## Prioritize conda-forge

Create the environment and install `wandb`, where conda-forge has higher priority.


```zsh
conda create -n test-cf python=3.10 wandb -c conda-forge -c defaults
conda list -n test-cf | grep protobuf
```

### Output

```
libprotobuf               4.23.2               hd1fb520_1    conda-forge
protobuf                  4.23.2          py310hb875b13_0    conda-forge
```
In this case, `conda activate test-cf && python -c 'import wandb'` will cause the following error:

```
ImportError: .../envs/test-cf/lib/python3.10/site-packages/google/protobuf/pyext/_message.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN6google8protobuf2io17SafeDoubleToFloatEd
```

If I manually downgrade the `libprotobuf` package by `conda install libprotobuf=3 --solver classic -c conda-forge`, the command will work well.

So, I believe this is a version compatibility issue.

**Comment by rsanandres-wandb** [comment]
Hello @function2-llx !

```conda create -n test-cf python=3.10 wandb -c conda-forge -c defaults```
```conda list -n test-cf | grep protobuf```

Then I ran

```conda activate test-dft && python -c 'import wandb'```

Which worked for me. The one thing I changed was that I activated the `test-dft` environment (the one we created in the first code block) and there was no error on my end. It looks like something within the `test-cf` environment is throwing this error.



https://github.com/wandb/wandb/assets/122482606/05135551-dc78-49cf-a37d-18a87a946bce

**Comment by function2-llx** [comment]
Hello @rsanandres-wandb , thank you for your reply. 
I tried these commands again today and cannot reproduce the issue. Fortunately, thanks to the package information I posted in the previous message, I noticed that the `libprobuf` package I installed today, though has the same version number (`4.23.2`), has a different build number (`hd1fb520_1` vs `hd1fb520_4`). I then tried to install the `libprotobuf` package with this specific build number, and the issue is reproduced.

Here's a video for how I reproduce the issue in a docker container:


https://github.com/wandb/wandb/assets/38486514/855a3e80-c552-4f1a-960c-9e44a5cc512d

Here are the scripts:

```bash
docker run -it continuumio/miniconda3 bash
# the following commands are executed within the docker container
conda create -n test python=3.10 wandb -c conda-forge -y && conda activate test
conda list | grep protobuf
python -c 'import wandb' # should work fine

# install the package with the previous build that causes error
conda install libprotobuf=4.23.2=hd1fb520_1 -c conda-forge
python -c 'import wandb' # this will raise an error
```

Anyway, this issue will not occur anymore if we install the package normally. I think we can close the issue now. Thank you again for your time!
