### ISSUE TITLE
`wandb.summary.update` does not upload before the end of the run

### ISSUE THREAD

**Issue by vict0rsch** [wandb/wandb#5646]
### Describe the bug

I'm logging metrics with `wandb.Run.log({..})` and summaries with `wandb.Run.summary.update({..})`.

The metrics do show ip on the UI, but not the summary.

To be exact, they do show up, but only _at the end of the run_. This is very unfortunate as those summary metrics are actually baselines (computed only once at the beginning of training) and I need to have access to those values to decide if I'm gonna stop the run...

### Environment

WandB version: version 0.15.0

OS: Linux

Python version: 3.9

**Comment by thanos-wandb** [comment]
Hi @vict0rsch thank you for reporting this issue. 

This is related to our wandb client/SDK and was introduced in `v0.14.1` to address a perf issue ([release notes here](https://github.com/wandb/wandb/releases/tag/v0.14.1)). The [change has been reverted](https://github.com/wandb/wandb/pull/5562) in our most recent release  (v0.15.3) and it should resolve this issue. 

Could you please `pip install --upgrade wandb` and let us know if that worked for you?

**Comment by vict0rsch** [comment]
Indeed thanks!
