### ISSUE TITLE
uploading artifacts to existing runs stopped working

### ISSUE THREAD

**Issue by EvanBrownVTM** [wandb/wandb#5650]
### Describe the bug

when trying to upload an artifact to an existing run wandb hangs forever on:
wandb: Waiting for W&B process to finish... (success).

```python
with wandb.init(project="Subway", entity="viatouch",id=r.id, resume="allow") as run:
                #log model artifact
                artifact = wandb.Artifact(model_name, "model")
                artifact.add_file(weights_fpath)
                artifact.add_file(cfg_fpath)
                run.log_artifact(artifact)
```

```shell
wandb: Currently logged in as: evanbrown (viatouch). Use `wandb login --relogin` to force relogin
wandb: wandb version 0.15.3 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.14.0
wandb: Run data is saved locally in /home/evan/Desktop/wandb_models/wandb/run-20230601_145004-c72vk687
wandb: Run `wandb offline` to turn off syncing.
wandb: Resuming run LD2Trial104-2023-06-01|14:39:39
wandb: ⭐️ View project at https://wandb.ai/viatouch/Subway
wandb: 🚀 View run at https://wandb.ai/viatouch/Subway/runs/c72vk687
wandb: Waiting for W&B process to finish... (success).
```

### Environment

WandB version:
0.14.0
OS:
Linux
Python version:
3.6
Versions of relevant libraries:

**Comment by thanos-wandb** [comment]
Hi @EvanBrownVTM thanks for reporting this issue. I was able to resume to a run and upload an artifact file. Could you please `pip install wandb --upgrade` and try again?

**Comment by EvanBrownVTM** [comment]
After leaving for several hours the upload did complete, seems it is just
very slow.

**Comment by EvanBrownVTM** [comment]
Thanks for looking into this!

**Comment by thanos-wandb** [comment]
Thanks @EvanBrownVTM for the update, glad this is resolved for you. I would recommend to upgrade to our most recent version (`v0.15.4`) as it includes some [artifacts performance upgrade](https://github.com/wandb/wandb/releases/tag/v0.15.4). I will close this ticket now, but please feel free to reopen it if this issue pops up again.
