### ISSUE TITLE
[App]: Summary gets ignored; Runs page shows incorrect summary

### ISSUE THREAD

**Issue by pochtar** [wandb/wandb#5652]
### Current Behavior

If you take a look at the files, the summary is successfully uploaded: https://wandb.ai/xmax/mlp_may23/runs/7u7zj1j1/files/wandb-summary.json

However, if you look at the summary of the run, or at the Runs page, it shows no metrics or summary at all for this particular run:
![image](https://github.com/wandb/wandb/assets/5296703/e90e7b70-d873-49b5-a246-35cc9f2dc110)

This behavior appears inconsistent as other sweep runs with the exact same code do contain summary and the stats.
`wandb sync` says `No runs to be synced.`
Thanks.

### Expected Behavior

Have stats on the Runs page, as well as Summary in Run's info.

### Environment

Version: latest wandb

**Comment by thanos-wandb** [comment]
Hi @pochtar thanks for the update, this appears to happen for you only for a single run (`wild-sweep-2`) while all rest runs have been fully backfilled. Do you still have the local wandb run folders stored in your machine? Could you please share here the `debug.log` and `debug-internal.log` files for this specific run to investigate if that's a different issue? or do you recall having these metrics before for that run too?

**Comment by thanos-wandb** [comment]
Thank you @pochtar that was greatly helpful! I have escalated to our Infra team, and they will backfill using the `wandb-summary.json` file which should fix this issue for you. I will reach out to you here once this process is complete so that you could check.

**Comment by thanos-wandb** [comment]
Hi @pochtar thanks so much for reporting the issue, this should be now resolved for you. Please let us know if you're still seeing any issue.

**Comment by thanos-wandb** [comment]
Hi @pochtar thanks for the update, I see, these runs started before the regression and they weren't filtered for the backfill. I will let the Infra team know and then keep you posted here.

**Comment by thanos-wandb** [comment]
Hi @pochtar could you please check again and see if you still had any metrics that haven't been backfilled yet? Thank you!

**Comment by thanos-wandb** [comment]
Hi @pochtar quick update here, this should be now correctly updated in the Summary table. I will now close this ticket as it has been resolved, but please feel free to reopen it if you're still experiencing any issue and we will be happy to keep investigating. Thanks so much once again for reporting and detailed info provided!

PS: Please check the above suggestion regarding `sync` as well.
