### ISSUE TITLE
[App]: Metrics and tables don't appear in UI but are logged correctly in the run_summary.json 

### ISSUE THREAD

**Issue by Booss3my** [wandb/wandb#5657]
### Current Behavior

Hello,

The issue is the run_summary.json is logged but not viewed in UI.
The logging was working until today, nothing changed in the code, and when I verify the run_summary.json, it contains the metrics it's just not shown in the UI (see images below).

Same thing for tables.

Is it a frontend problem in the app or could it be something on my part?

Thanks in advance for the help!

### Screenshots

Not shown in UI:
![image](https://github.com/wandb/wandb/assets/56868809/9d1e4d37-f806-481e-9231-f73b9d707f00)

Exists in run_summary.json:
![image](https://github.com/wandb/wandb/assets/56868809/481ed616-46a2-47f7-b989-7c9a115bd6bc)

### Environment

OS: Linux-4.9.0-0.bpo.3-amd64-x86_64-with-glibc2.19

Browsers: google chrome

Version: Version 113.0.5672.129

**Comment by thanos-wandb** [comment]
Hi @Booss3my thank you for reporting this issue, we could reproduce on our end too and have escalated to our engineers as a P0 issue. This seems as a recent regression which we're currently investigating it. I will keep you posted here on any updates.

**Comment by thanos-wandb** [comment]
Hi @Booss3my just a quick update here, our Infra team has identified the cause, and rolled back the change. Any new runs should show up the summary table. The summary of the affected runs will be backfilled, this process has started and you should soon see the metrics being populated there.

**Comment by Booss3my** [comment]
Hi @thanos-wandb, thanks a lot for your reactivity ! It works on my end. I'll close the issue

**Comment by thanos-wandb** [comment]
Thank you @Booss3my for confirming that. Apologies for any inconvenience this caused. Have a great weekend!
