### ISSUE TITLE
[CLI]: HTTP Client error 400 when downloading dataset artifacts on WSL2 Windows 11

### ISSUE THREAD

**Issue by ntinou** [wandb/wandb#5678]
### Describe the bug

When trying to download 4 dataset artifacts, containing 5.5k, 2.9k, 5.5k and 2.9k images respectively, on WSL2 in Windows 11, the client downloads a good amount (around 1-2k images) then slows down dramatically and ultimately throws the HTTP client error mentioned below. 
The following code snippet has been tested in Ubuntu 22.04 and Windows 11 and works as expected. The same account is logged in on all 3 operating systems.

```python
import wandb
from pathlib import Path
run = wandb.init(project=project_name)
    dataroot = Path(opt.dataroot)

    flir_ir = run.use_artifact(f"{name}_IR:latest")
    ir_dir = dataroot / "trainB"
    if not ir_dir.is_dir():
        ir_dir.mkdir(parents=True)
    flir_ir.download(root=str(ir_dir))

    if train:
        flir_vis = run.use_artifact(f"{name}_Vis:{vis_alias}")
        vis_dir = dataroot / "trainA"
        if not vis_dir.is_dir():
            vis_dir.mkdir(parents=True)
        flir_vis.download(root=str(vis_dir))

        flir_vis_edges = run.use_artifact(f"{name}_Vis_edges:{vis_alias}")
        vis_edge_dir = Path(opt.Vis_edge_path)
        if not vis_edge_dir.is_dir():
            vis_edge_dir.mkdir(parents=True)
        flir_vis_edges.download(root=str(vis_edge_dir))

        flir_ir_edges = run.use_artifact(f"{name}_IR_edges:latest")
        ir_edge_dir = Path(opt.IR_edge_path)
        if not ir_edge_dir.is_dir():
            ir_edge_dir.mkdir(parents=True)
        flir_ir_edges.download(root=str(ir_edge_dir))
    wandb.finish()
```

```shell
HTTPError: 400 Client Error: Bad Request for url: Bad Request for url: https://storage.googleapis.com/wandb-production.appspot.com/ntinou/thermal2day_PearlGAN_Tensorflow-data/17j4vgms/artifact/367543024/wandb_manifest.json?Expires=16
86097325&GoogleAccessId=wandb-production%40appspot.gserviceaccount.com&Signature=mzkc1QYGkx679W6liBdjGIDseQjUS3VOPW1YuDsZaVZmYZR%2FVphiD98YeKLfTzWk2mw4eJnVswdTHyZH3owH9ipzKRWTkY61Ls%2F14FFtCQp16OQ95CcmMD7zM%2FWwdvR%2Bb5xU0L%2BL2Ojd9YIVh%2FNEsG0Fn1B5d9CUb6y%2FgVZHV9C37ugobtsYyqMmLNLAqXzalycgiilvsuQyCyUZVCNzQIBwICxD1oggiR4%2FZ8REbZ8OfmCRYBaCTpoEM6QAR3kpY131asYShecmSA6xF26quQuv1d%2F2sgm6U90FOf69Jf46pcSPXuRc5T3JJShJups8Drt3kssYRRn9FTTQPIY49w%3D%3D
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: 🚀 View run helpful-frog-31 at: https://wandb.ai/ntinou/thermal2day-data/runs/c2bacf9u
wandb: Synced 6 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20230607_032051-c2bacf9u/logs
```
Log files 
[debug.log](https://github.com/wandb/wandb/files/11671399/debug.log)
[debug-internal.log](https://github.com/wandb/wandb/files/11671400/debug-internal.log)

Please let me know if this is a known problem for WSL2 artifact operations containing several small files or if there is some way to troubleshoot this on my end.
Thanks in advance! 

### Environment

WandB version: 0.13.9

OS: WSL2 on Windows 11

Python version: 3.9.16

Versions of relevant libraries:

**Comment by rsanandres-wandb** [comment]
Hello @ntinou !

After looking at the debug logs, there is nothing inherently wrong with the way that you are grabbing the dataset. What it looks like is happening is that the manifest for the file is timing out before your client is able to retrieve it. We are in the middle of debugging a similar case so thank you for your detailed feedback. I will circle back around to you once we have found something or need some more clarifications.

**Comment by rsanandres-wandb** [comment]
After looking around, what likely happening is that the signed URL is expiring. These URLs expiring in 60 seconds and it is possible that the time between `flir_ir = run.use_artifact(f"{name}_IR:latest")` and `flir_ir.download(root=str(ir_dir)` can be more than 60 seconds sometimes. We can recommend two things:
1. Wrap the download with a retry mechanism so that your script will keep on running
2. Parallelize the scrip so that each script will only have one dataset.
