### ISSUE TITLE
[App]: The webpage keeps refreshing during the renaming of runs in the overview tab

### ISSUE THREAD

**Issue by BruceGeLi** [wandb/wandb#5679]
### Current Behavior

![Screenshot from 2023-06-07 09-58-24](https://github.com/wandb/wandb/assets/37535292/ddfb2ae6-c70c-4521-8cef-f0c657bbfc82)
Hi, 

I found when renaming the runs in the overview tab, the web page will keep refreshing and does not wait until I finish the renaming. The intermediate name will be stored and I always have to do the renaming 3 or 4 times until I type in the new name correctly, which is quite annoying. This behaviour is especially obvious in a project with many runs. 

### Expected Behavior

The webpage should not refresh and the temp name should not be stored until the new name has been fully typed in.

### Steps To Reproduce

1. Find a project with many runs, e.g. 100 + runs. 
2. Rename one of these runs using its own overview tab.
3. Input a new and long name

### Environment

OS: Ubuntu 20.04

Browsers: Chrome 

Version: Version 110.0.5481.177 (Official Build) (64-bit)

**Comment by thanos-wandb** [comment]
Hi @BruceGeLi thanks for reporting this issue, but I wasn't able to reproduce on my end, neither in Chrome nor Firefox. Could you please screen record this so that we can investigate further and flag this with our App team? Thank you!

**Comment by BruceGeLi** [comment]
Hi, here you go.

https://github.com/wandb/wandb/assets/37535292/a93b447a-5c37-4dc8-a0e9-4877f2180afb

**Comment by BruceGeLi** [comment]
The webpage gets some auto refreshment during my typing and won't wait me until finish.

**Comment by thanos-wandb** [comment]
Thanks a lot @BruceGeLi for the screen recording. This is about renaming the grouped runs, but do you also get same experience when clicking on an individual run and trying to rename it from its overview page? There's also an `Auto-refresh` button from top right avatar icon, is this enabled for you?

**Comment by thanos-wandb** [comment]
Hi @BruceGeLi the issue was reproduced on our end when renaming from grouped runs' overview page. This has been reported to our engineers and we will keep you posted here on any updates. Thank you for flagging this!

**Comment by thanos-wandb** [comment]
Hi @BruceGeLi indeed I was able to reproduce the issue as well even without the auto-refresh button so I created an internal ticket for our engineers and linked to that thread. I will temporarily close this thread here, and we will reach out to you once there is a fix or any other updates. Thanks for reporting it!

**Comment by sydholl** [comment]
WandB Internal User commented: 
BruceGeLi commented: 
Hi, here you go.

https://github.com/wandb/wandb/assets/37535292/a93b447a-5c37-4dc8-a0e9-4877f2180afb

**Comment by sydholl** [comment]
WandB Internal User commented: 
thanos-wandb commented: 
Thanks a lot @BruceGeLi for the screen recording. This is about renaming the grouped runs, but do you also get same experience when clicking on an individual run and trying to rename it from its overview page? There's also an `Auto-refresh` button from top right avatar icon, is this enabled for you?

**Comment by haok1402** [comment]
Could we do it a "smart" manner? During re-naming, avoid auto-refresh for that specific tab.
It feels quite annoyed, to turn on and off back and forth for the auto-fresh.

**Comment by thanos-wandb** [comment]
Hi @haok1402 thanks for following up on this and sharing additional feedback, this is in our backlog, and have updated the internal ticket accordingly. We will keep you posted on this here.
