### ISSUE TITLE
[App]: Safari plotting unwanted grey boxes in charts

### ISSUE THREAD

**Issue by lenbrocki** [wandb/wandb#5680]
### Current Behavior

It's a rather minor issue, but Safari is plotting some grey boxes on the charts that shouldn't be there (and are not there in Chrome). 

### Expected Behavior

No grey boxes.

### Screenshots

<img width="1903" alt="Screenshot 2023-06-07 at 12 31 46" src="https://github.com/wandb/wandb/assets/45183581/b83e19ee-2d8e-46a5-8e3f-b4ffb325b1bd">

### Environment

OS: macOS 13.2.1 

Browsers: Safari 16.3

Version: wandb 0.15.3

**Comment by thanos-wandb** [comment]
Hi @lenbrocki thanks so much for reporting this issue. We have already an internal ticket logged on this, so I will temporarily close this thread for now. I have linked the thread here with that ticket, so we will reach out to you as soon as it's fixed.

**Comment by thanos-wandb** [comment]
Hi @lenbrocki I wanted to follow up here, and see if you're still experiencing this issue or if it has resolved since? Thank you!

**Comment by lenbrocki** [comment]
It seems that the problem is solved now. Thanks for the fast response!
