### ISSUE TITLE
[CLI]: Breaking change in public api, Artifact class, v0.15.4

### ISSUE THREAD

**Issue by lendle** [wandb/wandb#5682]
### Describe the bug

`wandb.apis.public.Artifact` was moved in this pr https://github.com/wandb/wandb/pull/5534

Not sure if breaking changes are meant to be disallowed in point releases. Feel free to close this issue if this does not violate the versioning policy. 

### Environment

WandB version: 0.15.4

OS:

Python version:

Versions of relevant libraries:

**Comment by ArtsiomWB** [comment]
Hi @lendle! Thank you for pointing this out, could you elaborate a bit on what you are talking about?

**Comment by ArtsiomWB** [comment]
Gotcha! Thank you for elaborating. It does seem like a pretty big change you are not wrong. I can ask our engineering team about this if you'd like. :)

**Comment by ArtsiomWB** [comment]
Hi @lendle! I have checked with the SDK team, and they said this patch was more of an exception and for the most part we do use point updates for patch releases. Thank you so much for pointing it out!
