### ISSUE TITLE
[App]: small UI issue - the green "running" dot obscures the number of runs in a group

### ISSUE THREAD

**Issue by toizzy** [wandb/wandb#5683]
### Current Behavior

If all of the runs in a group are running, a green dot appears by the group name. This obscures the number of runs in a group, and is not fixed by resizing the bar with the run names

### Expected Behavior

The green dot should probably be to the right of the numbers

### Steps To Reproduce

Group runs such that there is one group where every run is currently running. 

### Screenshots

![image](https://github.com/wandb/wandb/assets/14034611/d9183f56-ff21-4406-bf14-e1cf5be5765a)

### Environment

OS: Ubuntu 22.04

Browsers: firefox 113.0.2

Version:

**Comment by umakrishnaswamy** [comment]
Hey @toizzy, 

Thank you for catching this. This is a known issue and our engineering team is already looking into it. Will update you once progress is made.
