### ISSUE TITLE
[Q]The best way to track the accuracies of models between the models in artifacts

### ISSUE THREAD

**Issue by twmht** [wandb/wandb#5687]
Hi,

I am wondering if there is any way to associate the accuracies between models of the artifacts?

Like we have model v0, v1, v2, each of them have the accuracy about one of the test dataset.

How can I make a table to visualize and compare the accuracy with a specific dataset? Any example about that?

For example, I can only compare the accuracies between the different runs, like 
![image](https://github.com/wandb/wandb/assets/1567200/336962c3-04c7-41e0-90af-27abbe006644)

but how to visualize this between different artifact?

Any idea?

**Comment by umakrishnaswamy** [comment]
Hey @twmht,

There are a few ways you can go about this, but one recommendation is to log the accuracies for your given models into a `wandb` Table. Documentation on logging to a Table can be found [here](https://docs.wandb.ai/guides/data-vis/tables-quickstart). 

From the Table itself, you can create custom charts to visualize the accuracy however you my like. I attached a screenshot with where you can create these chars via the values in the Table you log. 

<img width="633" alt="Screen Shot 2023-06-08 at 3 12 22 PM" src="https://github.com/wandb/wandb/assets/63944839/7e2ee4ff-d5c1-4013-8896-b61343dc1b82">

**Comment by twmht** [comment]
@umakrishnaswamy 

thanks for your reply, but whenever i logged to a table, i can't see which artifact the row is associated, i can only see which run is associated.

So if i want to track the accuracy, do i need to add a new column which describes the model version? this is a recommandation to do this?

**Comment by twmht** [comment]
I have tried to log table

![image](https://github.com/wandb/wandb/assets/1567200/6562ebdb-ecfb-43eb-97d4-10d4024e6ebd)

As i said, I was unable to determine which row is associated with which artifact. Thus it's diffucult to pick up the best model. Is there any better way to visualize, maybe we can put a model artifact link in the columns? how can i do that using wandb API?

**Comment by umakrishnaswamy** [comment]
@twmht There are a few ways you can go about referencing the models you are using (either by referencing the artifact name, artifact alias if you are assigning one, or even getting the artifact version). 

You can access all these things through our `wandb.Api()`. Link to documentation can be found [here](https://docs.wandb.ai/ref/python/public-api/artifact). You can log these values to a wandb.Table for easy viewing.

**Comment by sydholl** [comment]
Uma Krishnaswamy commented: 
Hi @twmht,

We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

Best,

Uma
