### ISSUE TITLE
[App]: ROC curve now doesn't plot (previously did)

### ISSUE THREAD

**Issue by jphdotam** [wandb/wandb#5688]
### Current Behavior

The experiment page lists `Selected runs are not logging media for the key roc_damped, but instead are logging values of type string.` in the charts (not eeven media) page for an ROC curve.

Please see: https://wandb.ai/jameshoward/BeatQualityTmp/runs/vs11qhxn?workspace=user-jameshoward

### Expected Behavior

An ROC curve was plotted when I ran this script 6 months ago. The same code no longer produces an ROC curve successfully.

### Steps To Reproduce

```
roc = wandb.plot.roc_curve(
    y_true=y_true_binary,
    y_probas=y_pred,
    title=f"ROC curve - {title}",
    labels=['Negative', 'Positive']
)
```

Where `y_true_binary.shape=(2218,) y_true_binary.min()=0 y_true_binary.max()=1` and:
`y_true_binary=array([0, 0, 0, ..., 0, 0, 0])`

And `y_pred.shape=(2218, 2) y_pred.min()=0.19230232 y_pred.max()=0.80769765` and:
```
y_pred=array([[0.64023304, 0.359767  ],
       [0.6085884 , 0.3914116 ],
       [0.77655756, 0.22344244],
       ...,
       [0.55647063, 0.4435294 ],
       [0.5798026 , 0.42019743],
       [0.6048473 , 0.39515266]], dtype=float32)
```

### Screenshots

![image](https://github.com/wandb/wandb/assets/1561362/e33b6ff5-5fe3-41c2-abae-9c4fab6ab4df)

### Environment

OS: Windows or OSX using latest wandb (pip install -U wandb today)

Browsers: Chrome and Edge

Version: Current web client

**Comment by umakrishnaswamy** [comment]
Hey @jphdotam,

I tried reproducing on my end, and I was able to plot the ROC curve by running the following line:

`wandb.log({"roc": wandb.plot.roc_curve(y_true_binary, y_pred)})`

Please let me know if this behaves as expected on your end.

**Comment by umakrishnaswamy** [comment]
@jphdotam Instead of the line `self.logger.experiment.log({f"roc_{wandb_name}_wandb": roc})`, could you try the line 

`wandb.log({"roc_{wandb_name}_wandb":roc})` ? Please let me know how that works on your end.

**Comment by sydholl** [comment]
Uma Krishnaswamy commented: 
Hi @jphdotam, We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.
