### ISSUE TITLE
[Q]How can I export the smoothed data？

### ISSUE THREAD

**Issue by Yoega** [wandb/wandb#5699]
Hi, all. I am here to seek for some help.

I have encountered some problems when using the smoothing tool:

1. Can I export the smoothed values from Wandb? I would like to analyze the smoothed data, but I can only view them online in the image. Is there any way to download the CSV file storing the smoothed data?

2. I am wondering if it is possible to provide a more detailed operational process of the smoothing algorithms, especially the EMA algorithm? Mathematical formulas or code are both great. I tried to calculate the smoothed values according to the operational process provided in the Wandb documentation, but I could not match the values computed automatically by Wandb. I have been trying to solve this problem for several hours, but I still can't figure it out.

3. I think I have found a small error in the Wandb documentation, specifically in the "details" section of the EMA smoothing, regarding the calculation formula for S_t. I attached the photo as follows:

<img width="781" alt="Screenshot 2023-06-10 at 18 32 40" src="https://github.com/wandb/wandb/assets/95390839/42f78ce7-c6ac-40c9-8f54-ab1894e4731d">

**I would greatly appreciate it if someone could provide some suggestions!**

**Comment by nate-wandb** [comment]
Hi @Yoega, thank you for raising this.

1. We currently don't have a way to export these smoothed values but if you'd like I can submit a feature request for this?
2. I will talk with our App team to see if I can get an explanation for this. Do your charts have >1500 points? One discrepancy could be caused by the random sampling the application does if the number of points for a given metric is >1500.
3. Could you explain this mistake a bit? I'm a little unfamiliar with the math here but I can get the right eyes on this if I know what the issue is.

Thank you!

**Comment by nate-wandb** [comment]
Hi @Yoega, I just wanted to follow up on this and see if you had an answer on the above questions? 

Thank you,
Nate

**Comment by Yoega** [comment]
Hi @nate-wandb, sorry for my late reply. I was working on my final for the past few days.

Thank you for your answers!!!! 

1. Yes, I will appreciate it if you could submit a feature request for this. Many thanks!
2. Sorry, I did not have points more than 1500. There were only 100 points. But I still can not figure out the principle behind this. Moreover, I even tried the sample provided [(link:),](https://wandb.ai/carey/smoothing-example/reports/W-B-Smoothing-Features--Vmlldzo1MzY3OTc?_gl=1*4m78j9*_ga*MTMyMTkyNzk4Mi4xNjg2MDcwNjQ1*_ga_JH1SJHJQXJ*MTY4NzE0NTU4OS4yOS4wLjE2ODcxNDU1ODkuNjAuMC4w) not matched yet.
3. Yes, here are my thoughts:
![image](https://github.com/wandb/wandb/assets/95390839/8aeb3ede-eaba-410f-9d00-5aa0083a3dd5)

According to Equation 1, maybe the numerator in Equation 2 should be expressed as αYt + (1-α)Yt-1

**Comment by Yoega** [comment]
Hi @nate-wandb,

I am sorry for not replying to your email in a timely manner. I was busy
dealing with my final exams for the past few days.

Thank you so much for your responses. I appreciate your efforts in
addressing our requests. I have already posted my reply on GitHub. Once you
have had a chance to review my answers, we can discuss further.

Thank you again for your kind assistance.

Best regards,
Yoega




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
23/06/19
11:44:25

nate-wandb ***@***.***> 于2023年6月17日周六 03:33写道：

**Comment by Yoega** [comment]
For Q2, I just computed the values based on the following formula. Could you please provide more details about the following formula? e.g. What does numAccum refer to？
![image](https://github.com/wandb/wandb/assets/95390839/ee13591d-ba16-4a18-a62d-78f89347e2fe)

**Comment by drcege** [comment]
+1
For Q1, the smoothing functions may be also exposed in the python API, so we can reproduce the same smoothed series from raw data.

**Comment by nate-wandb** [comment]
@Yoega I just wanted to follow up and see if Justin's response answered your questions or if there was anything else we could help with?

**Comment by Yoega** [comment]
Hi，@jtulk  Thank you so much for your help!!! This solved my problem and the updated sample code is much clearer.👍

**Comment by Yoega** [comment]
Hi, @nate-wandb Thank you for the reminder. Yes, Justin's response answered my questions.😊👍

**Comment by sydholl** [comment]
WandB Internal User commented: 
Yoega commented: 

Hi @nate-wandb, sorry for my late reply. I was working on my final for the past few days.

Thank you for your answers!!!! 

1. Yes, I will appreciate it if you could submit a feature request for this. Many thanks!
2. Sorry, I did not have points more than 1500. There were only 100 points. But I still can not figure out the principle behind this. Moreover, I even tried the sample provided [(link:),](https://wandb.ai/carey/smoothing-example/reports/W-B-Smoothing-Features--Vmlldzo1MzY3OTc?_gl=1*4m78j9*_ga*MTMyMTkyNzk4Mi4xNjg2MDcwNjQ1*_ga_JH1SJHJQXJ*MTY4NzE0NTU4OS4yOS4wLjE2ODcxNDU1ODkuNjAuMC4w) not matched yet.
3. Yes, here are my thoughts:
![image](https://github.com/wandb/wandb/assets/95390839/8aeb3ede-eaba-410f-9d00-5aa0083a3dd5)

According to Equation 1, maybe the numerator in Equation 2 should be expressed as αYt + (1-α)Yt-1

**Comment by sydholl** [comment]
WandB Internal User commented: 
Yoega commented: 
Hi @nate-wandb,

I am sorry for not replying to your email in a timely manner. I was busy
dealing with my final exams for the past few days.

Thank you so much for your responses. I appreciate your efforts in
addressing our requests. I have already posted my reply on GitHub. Once you
have had a chance to review my answers, we can discuss further.

Thank you again for your kind assistance.

Best regards,
Yoega




[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
23/06/19
11:44:25

nate-wandb ***@***.***> 于2023年6月17日周六 03:33写道：

**Comment by sydholl** [comment]
WandB Internal User commented: 
Yoega commented: 
For Q2, I just computed the values based on the following formula. Could you please provide more details about the following formula? e.g. What does numAccum refer to？
![image](https://github.com/wandb/wandb/assets/95390839/ee13591d-ba16-4a18-a62d-78f89347e2fe)

**Comment by sydholl** [comment]
WandB Internal User commented: 
Yoega commented: 
Hi，@jtulk  Thank you so much for your help!!! This solved my problem and the updated sample code is much clearer.👍

**Comment by sydholl** [comment]
WandB Internal User commented: 
Yoega commented: 
Hi, @nate-wandb Thank you for the reminder. Yes, Justin's response answered my questions.😊👍
