### ISSUE TITLE
[CLI]: Key 'prompts': error while logging LLM output & prompt using Langchain<->Wandb 

### ISSUE THREAD

**Issue by rushi-the-neural-arch** [wandb/wandb#5700]
### Describe the bug

I am trying to log the prompt and the corresponding output to wandb while using Langchain and I was following this blog - [Prompt Engineering LLMs with LangChain and W&B](https://wandb.ai/a-sh0ts/langchain_callback_demo/reports/Prompt-Engineering-LLMs-with-LangChain-and-W-B--VmlldzozNjk1NTUw). But somehow I am facing key 'prompts' error while executing `wandb_callback.flush_tracker`. 

```
import wandb, os, random
from datetime import datetime
from langchain.callbacks import WandbCallbackHandler, StdOutCallbackHandler
from langchain.callbacks.manager import CallbackManager # for langchain 0.0.171 for older version, it might be from -> langchain.callbacks.base import CallbackManager
from langchain.llms import OpenAI
wandb.login()

os.environ["OPENAI_API_KEY"] = '...'

project = "langchain-experiment"
exp_name = 'wb-test'
exp_config = {}

wandb.init(
    # set the wandb project where this run will be logged
    project=project,
    name = exp_name,
    config = exp_config,
    reinit=True
    )

session_group = 'Test' 

wandb_callback = WandbCallbackHandler(
    job_type="Testing",
    project=project,
    group=f"minimal_{session_group}",
    name="gpt-3.5",
    tags=["test"],
)

manager = CallbackManager([StdOutCallbackHandler(), wandb_callback])
llm = OpenAI(temperature=0, model_name="gpt-3.5-turbo", callback_manager=manager, verbose=True)

from langchain.schema import (
    AIMessage,
    HumanMessage,
    SystemMessage
)

messages = [
    SystemMessage(content="You are a comedian as well as a writer, help me with some content creation"),
    HumanMessage(content="Tell me a joke")
]

llm_result = llm.generate([messages[0].content])

reset: bool = True,
finish: bool = False,

wandb_callback.flush_tracker(llm_result.generations , name="simple_sequential")

```

```
----> 2 wandb_callback.flush_tracker(llm_result.generations , name="simple_sequential")

File [~/opt/miniconda3/envs/nlp/lib/python3.11/site-packages/langchain/callbacks/wandb_callback.py:543](https://file+.vscode-resource.vscode-cdn.net/Users/rushirajsinhparmar/Downloads/HopinProjects/NLP/scoping_out/Wandb-LangChain/~/opt/miniconda3/envs/nlp/lib/python3.11/site-packages/langchain/callbacks/wandb_callback.py:543), in WandbCallbackHandler.flush_tracker(self, langchain_asset, reset, finish, job_type, project, entity, tags, group, name, notes, visualize, complexity_metrics)
    541 pd = import_pandas()
    542 wandb = import_wandb()
--> 543 action_records_table = wandb.Table(dataframe=pd.DataFrame(self.action_records))
    544 session_analysis_table = wandb.Table(
    545     dataframe=self._create_session_analysis_df()
    546 )
    547 self.run.log(
    548     {
    549         "action_records": action_records_table,
    550         "session_analysis": session_analysis_table,
    551     }
    552 )

File [~/opt/miniconda3/envs/nlp/lib/python3.11/site-packages/wandb/data_types.py:279](https://file+.vscode-resource.vscode-cdn.net/Users/rushirajsinhparmar/Downloads/HopinProjects/NLP/scoping_out/Wandb-LangChain/~/opt/miniconda3/envs/nlp/lib/python3.11/site-packages/wandb/data_types.py:279), in Table.__init__(self, columns, data, rows, dataframe, dtype, optional, allow_mixed_types)
    277 # Explicit dataframe option
    278 if dataframe is not None:
--> 279     self._init_from_dataframe(dataframe, columns, optional, dtype)
    280 else:

Key 'prompts':
	String not assignable to Invalid[] or None
		String not assignable to Invalid[]
	and
		String not assignable to None

```

### Environment

WandB version: `0.15.3`

OS: `Macos`

Python version: `3.11.3`

Versions of relevant libraries: Langchain - `0.0.171`

### Additional Context

The below method to log works perfectly and logs the prompt and output as well!

```
from langchain.llms import OpenAI
from langchain import PromptTemplate, LLMChain

from wandb.integration.langchain import WandbTracer

model = OpenAI(model_name="gpt-3.5-turbo", temperature=0.0)

template = """Answer the following question: {question}"""
prompt = PromptTemplate(
    template=template, 
    input_variables=["question"]
)

QUESTION = "What year did Bruce Springsteen perform at the Superbowl halftime show?"

llm_chain = LLMChain(
    prompt=prompt,
    llm=model, 
    callbacks=[WandbTracer({"project": project})]
)

output = llm_chain.run(QUESTION)

WandbTracer.finish()
```

**Comment by ash0ts** [comment]
Hey @rushi-the-neural-arch! I wrote the Prompt Engineering report. Thank you for bringing to my attention the deprecated logger that was used in the Report. I will be updating the article to show the new logger workflow.
We worked extensively with the folks at Langchain to update how logging looks and is done, and also moved the integration to Langchain itself 🎉. 
Our new Tracer docs can be found at https://python.langchain.com/en/latest/integrations/agent_with_wandb_tracing.html (which we will be reflecting in our docs soon!)

**Comment by rushi-the-neural-arch** [comment]
Thanks @nate-wandb , @ash0ts for looking into this! Wandb docs are super helpful!

**Comment by ns-qasim** [comment]
> Hey @rushi-the-neural-arch! I wrote the Prompt Engineering report. Thank you for bringing to my attention the deprecated logger that was used in the Report. I will be updating the article to show the new logger workflow. We worked extensively with the folks at Langchain to update how logging looks and is done, and also moved the integration to Langchain itself 🎉. Our new Tracer docs can be found at https://python.langchain.com/en/latest/integrations/agent_with_wandb_tracing.html (which we will be reflecting in our docs soon!)

This link isn't working, can you please attach a working one, Thanks!

**Comment by ayulockin** [comment]
Hey @rushi-the-neural-arch , W&B Trace is an old product offering which is not maintained anymore. We were focused on shipping a better tooling called W&B Weave. Team is working on the Langchain integration.

[Weave announcement](https://wandb.ai/wandb/weave-announcement/reports/Weave-Simple-tools-for-applying-Generative-AI--Vmlldzo3NDE0Mjcx)
[Weave Documentation](https://wandb.github.io/weave/)

Closing this issue for now. Do let me know if you need anything more.
