### ISSUE TITLE
[Feature]: Precision-Recall like curves across steps / epochs

### ISSUE THREAD

**Issue by yermandy** [wandb/wandb#5702]
### Description

Hello, using the following code I can log any curve into wandb and have similar preview as PR or ROC curves:
```
def create_custom_wandb_metric(
    xs: list, ys: list, classes: list, title: str = "Precision Recall Curve"
):
    """Creates a custom wandb metric similar to default wandb.plot.pr_curve

    Args:
        xs: list of N values to plot on the x-axis
        ys: list of N values to plot on the y-axis
        classes: class labels for each point (list of N values)
        title: plot title

    Returns:
        wandb object to log
    """
    df = pd.DataFrame(
        {
            "class": classes,
            "y": ys,
            "x": xs,
        }
    ).round(3)

    return wandb.plot_table(
        "wandb/area-under-curve/v0",
        wandb.Table(dataframe=df),
        {"x": "x", "y": "y", "class": "class"},
        {"title": title},
    )
```

### Suggested Solution

It would be very nice to see results (curves) across epochs / steps. Is it possible to achieve this with current wandb version? If not, would it be possible to add such functionality? 

<img width="620" alt="Screenshot 2023-06-12 at 13 54 29" src="https://github.com/wandb/wandb/assets/39454881/914bbae9-72f0-4607-a56f-37b2916c2cbe">

**Comment by nate-wandb** [comment]
Hi @yermandy, this should be possible. Here is [an example](https://wandb.ai/stacey/presets/reports/PR-Curve-Slider-Example--Vmlldzo2NjE5ODk) and here in the [docs ](https://docs.wandb.ai/guides/app/features/custom-charts#how-to-show-a-step-slider-in-a-custom-chart)you can see how to add the slider to custom charts.

Let me know if this helps or if you have any other questions!

**Comment by nate-wandb** [comment]
Hi @yermandy, I wanted to follow up and see if the above examples helped here?

**Comment by yermandy** [comment]
Hello, thank you for your quick reply. No, examples did not help. I tried two things as was :
1. logging epoch using wandb.log together with my curve. 
2. adding epoch to wandb.Table
Neither of those give me expected result. 

Actually, `extraKeys` functionality does not seem to work. Also, when I change `summaryTable` to `historyTable`, I do not get "Show step selector"

**Comment by nate-wandb** [comment]
Hi @yermandy, sorry to hear that. Could you send a link to your workspace where the run is logged so I can take a look?

**Comment by yermandy** [comment]
Hi, @nate-wandb. Here is my [workspace](https://wandb.ai/yermandy/debug-custom-metric?workspace=user-yermandy), the code to reproduce it is logged [here](https://wandb.ai/yermandy/debug-custom-metric/runs/7qeir23o/files/code/metrics.py). You can notice that:
1. wandb removes previous logs of `metrics/custom-metric_table` whenever new table is logged
2. `epoch` selection menu does not appear when I switch table to `historyTable`

**Comment by kclauw** [comment]
Did you find a solution to this problem?

**Comment by yermandy** [comment]
@kclauw not yet

**Comment by nate-wandb** [comment]
Hi @yermandy and @kclauw, sorry for the delay on this. It's a bit hidden but if you edit the Vega spec and select other settings you have the option to turn this on. You can then select the step from the workspace by clicking the gear icon and scrolling to the step you would like to use. Let me know if this helps or if you have any other questions around this.

https://github.com/wandb/wandb/assets/97066933/0932ee3c-79b5-455f-bea2-f75f3f2c3a02


<img width="370" alt="Screen Shot 2023-07-24 at 9 57 42 AM" src="https://github.com/wandb/wandb/assets/97066933/05398913-88fe-40d4-a213-f3a554dfc2b0">

**Comment by nate-wandb** [comment]
@yermandy @kclauw I just wanted to confirm if this worked as a solution for you?

**Comment by yermandy** [comment]
@nate-wandb yes, thank you very much. It took me some time to find how to edit Vega specs but now it works! Appreciate your help
