### ISSUE TITLE
[Feature]: Confusion matrix working with strings/enum preds and y_true

### ISSUE THREAD

**Issue by adangreputationsquad** [wandb/wandb#5711]
### Description

Confusion matrix not robust to strings / enums labels for preds/y_true.

confusion_matrix.py, line 61
```  python
        assert max(preds) <= len(
            class_names
        ), "Higher predicted index than number of classes"
        assert max(y_true) <= len(
            class_names
        ), "Higher label class index than number of classes"
```

here my preds are already my labels, max(preds) and max(y_true) give me an error.

Funnily enough, the confusion matrix works just fine if I don't give them class_name. I feel in that case that the class names should be infered from pred and/or y_true, but if not at least let us give them the names lol

### Suggested Solution

Just replace max(preds) and max(y_true) line 61 and 64 par len(set(preds)).

```python
        assert len(set(preds)) <= len(
            class_names
        ), "Higher predicted index than number of classes"
        assert len(set(y_true)) <= len(
            class_names
        ), "Higher label class index than number of classes"

```

I feel this is also more robust in case the user have class labels that are not integers starting from 0. (I guess the bug I had would also occur if the user's label are integer starting from 1)

**Comment by nate-wandb** [comment]
Hi @adangreputationsquad, thank you for raising this along with a solution. I will pass this to our engineering team and will follow up once they get a chance to look into implementing this. 

Thank you, 
Nate

**Comment by nate-wandb** [comment]
Hi @adangreputationsquad, would it be possible to send a minimal example of data that would cause this error? I was trying to reproduce the error and I wasn't able to with my understanding of the problem. 

Thank you,
Nate

**Comment by adangreputationsquad** [comment]
Sure

```python

import wandb

wandb.init(project="test")

preds = [1, 2, 0, 1, 1, 2, 0]
y_true = [0, 2, 1, 0, 1, 2, 0]
plot = wandb.plot.confusion_matrix(
    preds=preds,
    y_true=y_true,
    class_names=["zero", "one", "two"])
wandb.log({"plot_1": plot})

preds_2 = ["one", "two", "zero", "one", "one", "two", "zero"]
y_true_2 = ["zero", "two", "one", "zero", "one", "two", "zero"]
plot_2 = wandb.plot.confusion_matrix(
    preds=preds_2,
    y_true=y_true_2)
wandb.log({"plot_2": plot_2})
```

Here when I go to wandb, the first plot generate a confusion matrix with its correct labels (zero, one two) but the second does not (the classes are class_1, class_2, class_3).

Now, I don't mind passing the labels again with the class_name argument even if it feels a bit redoundant, but it raises an error...

```python
preds_2 = ["one", "two", "zero", "one", "one", "two", "zero"]
y_true_2 = ["zero", "two", "one", "zero", "one", "two", "zero"]
plot_2 = wandb.plot.confusion_matrix(
    preds=preds_2,
    y_true=y_true_2,
    class_names=["zero", "one", "two"])
wandb.log({"plot_2": plot_2})
```

```
  File "/path/temp.py", line 15, in <module>
    plot_2 = wandb.plot.confusion_matrix(
  File "path/lib/python3.10/site-packages/wandb/plot/confusion_matrix.py", line 78, in confusion_matrix
    counts[class_mapping[y_true[i]], class_mapping[preds[i]]] += 1
KeyError: 'zero'
```

**Comment by nate-wandb** [comment]
Thank you @adangreputationsquad, I see the issue now. I've passed this onto the engineering team and will follow up once we have a fix on this.

**Comment by nate-wandb** [comment]
Hi @tamarl08, thank you for the workaround. I just checked the ticket and we still don't have a fix on this yet but I've added your context to the ticket and can follow up once we have this resolved.

**Comment by thanos-wandb** [comment]
Hi @adangreputationsquad @tamarl08 quick update to let you know that we are now closing this issue as it should been addressed by this PR: https://github.com/wandb/wandb/pull/8678 please let us know if you are still encountering any issues and we will be happy to keep investigating. Thank you for reporting it!
