### ISSUE TITLE
[docs] Incorrect docs in `wandb.plot.confusion_matrix`

### ISSUE THREAD

**Issue by Axel-Jacobsen** [wandb/wandb#5714]
https://github.com/wandb/wandb/blob/302a64bd85584d6188e1a38dec9d849cdab68b85/wandb/plot/confusion_matrix.py#L24-L26

Looking around `wandb.plots` more, it looks like a lot of docs and a lot of function signatures are incorrect or inconsistent. Googling `wandb plot docs`, most of what you get are examples of plotting with wandb. There is a large variance in the api version (got stung by this) and usage (and got stung with this), and I haven't been able to find the api docs for plotting. Eventually, reading the source code was the way to go (the only way to go, actually, since the function doc is incorrect). 

This won't be easy to fix, w/ all the various blog posts that give the user poor instruction. Thoughts on how to start fixing this?

**Comment by umakrishnaswamy** [comment]
Hey @Axel-Jacobsen, Thank you for bringing this up, and sorry to hear about the confusion. Could you link some of the portions of the docs that are inconsistent/incorrect? Would love to take a look.

**Comment by Axel-Jacobsen** [comment]
All good! Thanks for the interest

- The big thing is that the reference (https://docs.wandb.ai/ref/python/) doesn't include `wandb.plot` as far as I can tell, which makes the user rely on blog posts (which, even w/ official blog posts which are correct, aren't necessarily rigorous) or reading the source code
- Soure code: In `wandb.plot`, the functions in `confusion_matrix.py`, `pr_curve.py`, and `roc_curve.py` have incorrect docstrings which state that plots are automatically logged, unlike `scatter.py` and the rest, whose docstrings correctly state you have to `wandb.log` the returned value - though, I am not exactly sure if `wandb.plot_table` automatically plots the table, the inconsistency between the docstrings is confusing. But this is a quick and easy fix!
- Other blogs: there are blogs similar to [this] which have older (?) implementations (specifically `wandb.sklearn.plot_confusion_matrix` instead of `wandb.plot.confusion_matrix`). There are similar things  I understand that this difficult to ameliorate since you don't exactly control other people's blog posts.

**Comment by umakrishnaswamy** [comment]
Hey @Axel-Jacobsen, 

- I recommend taking a look at our docs related to `wandb.plot`, which can be found [here](https://docs.wandb.ai/guides/track/log/plots).  
- Additionally, we have documentation about our wandb - sklearn integration that can be found [here](https://docs.wandb.ai/guides/integrations/scikit)https://docs.wandb.ai/guides/integrations/scikit/. 

Please take a look at these two and if you have any feedback on these, we'd love to hear them.

**Comment by sydholl** [comment]
Uma Krishnaswamy commented: 
Hi Internal, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by umakrishnaswamy** [comment]
Hey @Axel-Jacobsen, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
