### ISSUE TITLE
[CLI]: Cannot log multiple PIL Images

### ISSUE THREAD

**Issue by batschoni** [wandb/wandb#5717]
### Describe the bug

When I am logging PIL images to wandb during training, only the first image appears in the web app. In the below example, it would log `image1` at step 1 and 2 but `image2` is not logged at all.

```python
import wandb
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

# init wandb
wandb.init(
    name="exampleRun",
    project="exampleProject",
    entity="exampleEntity",
    reinit=True,
    #dir=PATH,
)

# example image
image = np.random.rand(256, 256)

# prepare wandb image
fig, ax = plt.subplots()
ax.imshow(image, cmap="gray")
ax.axis('off')
fig.canvas.draw()
image_logging = Image.frombytes('RGB', fig.canvas.get_width_height(),fig.canvas.tostring_rgb())
image_logging = wandb.Image(image_logging, caption=f"Image")
plt.close()

# log the first image at step 1
wandb.log({"image1": image_logging}, step=1, commit=True)

# log the first image at step 2
wandb.log({"image1": image_logging}, step=2, commit=True)

# log the second image at step 1
wandb.log({"image2": image_logging}, step=1, commit=True)

# log the second image at step 2
wandb.log({"image2": image_logging}, step=2, commit=True)

wandb.finish()
```

```shell
wandb: Currently logged in as: *** (***). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.15.4
wandb: Run data is saved locally in ***
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run exampleRun
wandb: ⭐️ View project at https://wandb.ai/***/***
wandb: 🚀 View run at https://wandb.ai/***/***/runs/bp2p7acd

wandb: Waiting for W&B process to finish... (success).
wandb: 🚀 View run exampleRun at: https://wandb.ai/***/***/runs/bp2p7acd
wandb: Synced 7 W&B file(s), 4 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ***
```

### Additional Files

<img width="1041" alt="Bildschirmfoto 2023-06-13 um 18 00 42" src="https://github.com/wandb/wandb/assets/38256934/5fa1f1de-7152-4603-b78a-f34f7e6d5e82">

### Environment

Tested on 2 environments:

WandB version: 15.4 (15.0)

OS:  Linux-4.18.0-372.9.1.el8.x86_64-x86_64-with-glibc2.28 (MacOS 12.6.6)

Python version: 3.10.9 (3.10.9)

Versions of relevant libraries: NA

**Comment by ArtsiomWB** [comment]
Hi, @batschoni thank you for writing in!

This is actually an intended behavior. Our SDK does not let users go back in time (step-wise) and in the example above you first go to steps 1 and 2, and then back in time to 1 and 2. 

If you log images 1 and 2 together in steps 1 and 2 like this:
```py
wandb.log({"image1": image_logging,"image2": image_logging}, step=1, commit=True)

# log the first image at step 2
wandb.log({"image1": image_logging,"image2": image_logging}, step=2, commit=True)
```

This should log the images together with the according steps. 

Something like this, with different steps:
```py
# log the first image at step 1
wandb.log({"image1": image_logging}, step=1, commit=True)

# log the first image at step 2
wandb.log({"image1": image_logging}, step=2, commit=True)

# log the second image at step 1
wandb.log({"image2": image_logging}, step=3, commit=True)

# log the second image at step 2
wandb.log({"image2": image_logging}, step=4, commit=True)
```
would log the images into wandb as well, but on different steps. 

so would something like this:
```py
# log the first image at step 1
wandb.log({"image1": image_logging}, step=1, commit=True)

# log the first image at step 2
wandb.log({"image2": image_logging}, step=1, commit=True)

# log the second image at step 1
wandb.log({"image1": image_logging}, step=2, commit=True)

# log the second image at step 2
wandb.log({"image2": image_logging}, step=2, commit=True)
```

but not when we go from step 1 to step 2 back to step one and back to step 2 unfortunately. 

Cheers!

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by batschoni** [comment]
Hi @ArtsiomWB,

Thanks for your prompt feedback, much appreciated! Logging the images together in one dict (solution 1) indeed works.
