### ISSUE TITLE
[Q] Display single run cloud usage

### ISSUE THREAD

**Issue by santelelle** [wandb/wandb#5721]
Hi,

Is there any way to check the cloud disk usage for each run in the browser. This was possible a while ago when exceeding the 100GB, but now I cannot see it anymore. Has this information been moved somewhere else?

**Comment by ArtsiomWB** [comment]
Hi @santelelle! you can go to https://wandb.ai/usage/<entity_name> to check your space usage per project.

**Comment by santelelle** [comment]
Thank you, this is exactly what I was looking for.
