### ISSUE TITLE
[Q] how to copy runs from on project to another project 

### ISSUE THREAD

**Issue by Kadam-Tushar** [wandb/wandb#5726]
Can I copy runs from one project from a team to another non-team project from? I can see all the runs in my `wandb` folder but I don't know how to sync those runs to another project. 
I need this because I have used all free tracked hours provided by weights and biases for the team entity and now I wish to transfer those runs to my personal project. There is an option for moving those runs as mentioned [here](https://docs.wandb.ai/guides/runs/manage-runs) using GUI, but now I can not access those runs as I am being redirected to billing page because of using all the tracked hours.

**Comment by Kadam-Tushar** [comment]
Hi I asked the same question in wandb discord channel and I got a reply from their bot  `wandbbot` and this piece of code worked like a charm! Thank you! 
Sharing this piece of code in case someone needs it: 
```
import wandb

# Set your API key
wandb.login()

# Set the source and destination projects
src_entity = "src-entity"
src_project = "src-project"
dst_entity = "dst-entity"
dst_project = "dst-project"

# Initialize the wandb API
api = wandb.Api()

# Get the runs from the source project
runs = api.runs(f"{src_entity}/{src_project}")

# Iterate through the runs and copy them to the destination project

for run in runs:
    # Get the run history and files
    history = run.history()
    files = run.files()

    # Create a new run in the destination project
    new_run = wandb.init(project=dst_project, entity=dst_entity, config=run.config, name=run.name,resume="allow")
    
    # Log the history to the new run
    for index, row in history.iterrows():
        new_run.log(row.to_dict())

    # Upload the files to the new run
    for file in files:
        file.download(replace=True)
        new_run.save(file.name,policy = "now")

    # Finish the new run
    new_run.finish()
```

**Comment by ArtsiomWB** [comment]
Thank you for your question and your answer!

**Comment by FoamoftheSea** [comment]
I filled this out a bit for better functionality. In particular, the .history() returns a default sample size of 500, so I set this to always match the number of steps in the copied run. Also you probably want to grab your system history from the run as well. Tbh I think there should be a way to do this in the UI.

`from argparse import ArgumentParser

import numpy as np
import wandb


def main(args):

    if args.names is not None:
        if args.runs is None:
            raise Exception("Renaming copied runs not supported when copying whole project.")
        assert len(args.names) == len(args.runs), "Number of new names must equal number of run IDs"

    args.dst_entity = args.dst_entity if args.dst_entity is not None else args.src_entity
    args.dst_project = args.dst_project if args.dst_project is not None else args.src_project
    same_project = args.src_entity == args.dst_entity and args.src_project == args.dst_project
    if same_project and args.names is None:
        name_append = "-copy"
    else:
        name_append = ""

    # Set your API key
    wandb.login()
    # Initialize the wandb API
    api = wandb.Api()

    # Get the runs from the source project
    runs = api.runs(f"{args.src_entity}/{args.src_project}")

    # Iterate through the runs and copy them to the destination project
    for run in runs:
        if args.runs is not None and run.id not in args.runs:
            continue
        # Get the run history and files
        history = run.history(samples=run.lastHistoryStep + 1)
        system = run.history(samples=run.lastHistoryStep + 1, stream="system")
        history = history.join(system, rsuffix="_system")
        files = run.files()

        name = run.name if args.names is None else args.names[args.runs.index(run.id)]

        # Create a new run in the destination project

        # Log the history to the new run
        new_run = wandb.init(
            project=args.dst_project,
            entity=args.dst_entity,
            config=run.config,
            name=name + name_append,
            resume="allow"
        )
        for index, row in history.iterrows():
            new_run.log({k: v for k, v in row.to_dict().items() if v is None or not (v == "NaN" or np.isnan(v))})

        # Upload the files to the new run
        for file in files:
            file.download(replace=True)
            new_run.save(file.name, policy="now")

        # Finish the new run
        new_run.finish()


if __name__ == "__main__":
    parser = ArgumentParser(description="Copies one or all of the runs in a wandb project to another.")
    parser.add_argument("-se", "--src-entity", type=str, default="indezera", help="Source wandb entity name.")
    parser.add_argument("-sp", "--src-project", type=str, help="Name of the wandb projecet.")
    parser.add_argument("-de", "--dst-entity", type=str, default=None, help="Destination wandb entity name.")
    parser.add_argument("-dp", "--dst-project", type=str, default=None, help="Name of destination wandb project.")
    parser.add_argument("-r", "--runs", nargs="*", type=str, default=None, help="List of run IDs to copy. If None will copy all in project.")
    parser.add_argument("-n", "--names", nargs="*", type=str, default=None, help="List of new names for copied runs (optional).")

    main(parser.parse_args())`
