### ISSUE TITLE
[Q] How to upload old local wandb log files to new local host?

### ISSUE THREAD

**Issue by Dragon-Zhuang** [wandb/wandb#5728]
Hi,
I'm using wandb with the local host through the docker. Due to some personal reasons, the docker which runs the wandb was stopped.
Since all the data is stored in file _wandb/ run-20230615_112117-sty4x9ju/run-sty4x9ju.wandb_, I would like to upload these logs to the new wandb host. 
I find that command **wandb sync** cannot achieve this. What should I do to achieve this?
Thanks a lot.

**Comment by Dragon-Zhuang** [comment]
@nate-wandb Thank you for replay! 
I have tried **wandb sync --synced-all --include-synced**. Some experiment logs are recovered while some are missing. 
Now I decide to give up the local host since the docker that runs the local host was stopped after update.

**Comment by nate-wandb** [comment]
@Dragon-Zhuang I see. Is this no longer something you would like to debug then? 

If you want to keep looking into it, I think the most helpful thing would be to show me the exact commands you are using along with the directory structure and what directory you are in when you run them. 

Thank you,
Nate

**Comment by Dragon-Zhuang** [comment]
Thanks a lot @nate-wandb !
Now I decide to use the offcial wandb rather than the loacl host for stability. And I will close this issue.
