### ISSUE TITLE
[Q] How to change default wandb directory?

### ISSUE THREAD

**Issue by adildahlan** [wandb/wandb#5730]
Hello,
I want to change the default wandb directory.
`os.environ["WANDB_DIR"] = os.path.abspath("your/directory")` only changes the directory of the run.
However, the sweep config is still stored in the default `./wandb` directory.
I hope there is a way to sort this out as I am running out of storage in my home directory and would like to change the path where wandb directory is located. 
Cheers!

**Comment by rsanandres-wandb** [comment]
Hello @adildahlan!

I was able to have the sweep logs changed when I ran `os.environ["WANDB_DIR"] = os.path.abspath("your/directory")` before I ran the `wandb` agent. Most likely what is happening is that when you are starting your sweep agent, the environment variable is not set. You can either set the environment variable with `os.environ["WANDB_DIR"] = os.path.abspath("your/directory")` _before_ you initialize the agent in a script or set the environment variable in the CLI with `export WANDB_DIR="your/directory"`

**Comment by sydholl** [comment]
Raphael San Andres commented: 
Hello

**Comment by adildahlan** [comment]
Many thanks @rsanandres-wandb, just testing this now, It worked!
