### ISSUE TITLE
 Wandb local Docker image doesn't persist user account across restarts

### ISSUE THREAD

**Issue by Hbodor** [wandb/wandb#5735]
I am using the wandb local Docker image for my machine learning experiments. Everything works fine during a single session, but I am encountering an issue when I restart the Docker container.

Every time I restart the container, it seems to forget my user account. I have to create a new account each time, and it comes with a new API key, and empty projects.

I have tried using Docker volumes to persist the data across restarts, but this doesn't seem to work. I have also tried setting the WANDB_API_KEY environment variable when I start the Docker container, but this doesn't solve the problem either.

Here is the command I use to start the Docker container:

`docker run -v wandb:/vol wandb/local`

And here is the command I use to set the WANDB_API_KEY environment variable:

`docker run -e WANDB_API_KEY=my-api-key wandb/local` 

Am I missing something ? 

### Environment

OS:  Debian 10

Browsers: Chrome

**Comment by Hbodor** [comment]
deleting the volume and building it again solved the issue !

**Comment by thanos-wandb** [comment]
Hi @Hbodor thanks for updating the thread, and glad you got this resolved! If you're not applying any other configurations, you may also use our alias commands `wandb server start` and `wandb server stop` if that's easier for you. Closing the ticket on our end too as this seems resolved, but please feel free to reopen it if that issue pops up again.
