### ISSUE TITLE
[App]: Uninstalling wandb in Ultralytics notebooks (resolves Kaggle problem)

### ISSUE THREAD

**Issue by glenn-jocher** [wandb/wandb#5746]
### Current Behavior

I'm uninstalling wandb in Ultralytics notebooks due to unwanted behavior, i.e. indefinite hangs, wandb installation without user awareness or consent and unexpected/unwanted results like user confusion about why they are being prompted for input. See https://www.kaggle.com/code/ultralytics/yolov8/comments#2306977 for details.

Uninstalled from:

- YOLOv3 in https://github.com/ultralytics/yolov3/pull/2079
- YOLOv5 in https://github.com/ultralytics/yolov5/pull/11730
- YOLOv8 in https://github.com/ultralytics/ultralytics/pull/3247

@AyushExel

### Expected Behavior

Loggers should not interfere with YOLO training start.

### Steps To Reproduce

Go to https://www.kaggle.com/code/ultralytics/yolov8 and run setup and train cell. 

May no longer be reproducible at later dates after Ultralytics fixes have been pushed.

### Screenshots

<img width="929" alt="Screenshot 2023-06-18 at 15 29 50" src="https://github.com/wandb/wandb/assets/26833433/7220ede1-eca1-42d8-ae7b-fcbdd1629ca4">

### Environment

Kaggle, any other environment `wandb` is force installed in without the user knowing.

**Comment by rsanandres-wandb** [comment]
Hello @glenn-jocher ! 

Thank you for reporting this! I will pass this onto the team who is working on the `wandb` integration with YOLO.

**Comment by morganmcg1** [comment]
Hi @glenn-jocher, thanks for raising this user issue.

Would a more reasonable approach be to turn off wandb by default and add a flag that the user can use when they want to use wandb?

**Comment by sydholl** [comment]
Raphael San Andres commented: 
Hello, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by rsanandres-wandb** [comment]
Hello @glenn-jocher ! Just wanted to follow up and ask about the above solution from @morganmcg1 . Would that be a sufficient and acceptable approach for you?
