### ISSUE TITLE
[Q] wandb: ERROR Run 5vj3x7js errored: KeyError(1)

### ISSUE THREAD

**Issue by mae338** [wandb/wandb#5763]
Hello Everyone, 
I get this error when running the example in : [Weights & Biases](https://wandb.ai/matt24/vit-snacks-sweeps/reports/Hyperparameter-Search-for-HuggingFace-Transformer-Models--VmlldzoyMTUxNTg0)
Note: - I am using Spyder as IDE, Python : 3.10.11, wandb :0.15.4

wandb: WARNING Config item 'learning_rate' was locked by 'sweep' (ignored update).
wandb: WARNING Config item 'weight_decay' was locked by 'sweep' (ignored update).
wandb: Waiting for W&B process to finish... (failed 1). Press Ctrl-C to abort syncing.
wandb:  View run prime-sweep-1 at: https://wandb.ai/m-elghandur/vit-snacks-sweeps/runs/8n4zd2d6
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: .\wandb\run-20230622_171322-8n4zd2d6\logs
Run 8n4zd2d6 errored: KeyError(1)
wandb: ERROR Run 8n4zd2d6 errored: KeyError(1)

log files: 

[debug-internal.log](https://github.com/wandb/wandb/files/11834907/debug-internal.log)
[debug.log](https://github.com/wandb/wandb/files/11834909/debug.log)

**Comment by umakrishnaswamy** [comment]
@mae338 Currently reproducing this issue on my end and digging further into it, and I will update you with what I find!

**Comment by kptkin** [comment]
@umakrishnaswamy could you please resolve this ticket.

**Comment by mae338** [comment]
It is an incompatibility issue between library versions. Try the following versions: transformers==4.19.4 and wandb==0.12.18

**Comment by umakrishnaswamy** [comment]
@kptkin - apologies for failing to update this thread: this was resolved [here](https://github.com/wandb/wandb/issues/5769)
