### ISSUE TITLE
[Feature]: iOS / Mobile App

### ISSUE THREAD

**Issue by avocardio** [wandb/wandb#5779]
### Description

(I'm aware of #3751 , just wanted to bump to see if this was still on the table?)

Guys, this would be revolutionary. Why would you not want to track long training runs on an app, and get run information via notifications. Also the current mobile site is not super responsive and rather slow. 

### Suggested Solution

A mobile app that has the same (or reduced) features as the desktop web version, i.e. you can track runs and all the metrics. Im not familiar with mobile dev at all, would something like this be feasible to do?

**Comment by umakrishnaswamy** [comment]
Hey @avocardio, I submitted a feature request and will let you know progress as it arises.

**Comment by SonicCodes** [comment]
@umakrishnaswamy  & @avocardio , I've published a polished & efficient WandB mobile client,

For iOS: https://apps.apple.com/us/app/wandview/id6477268896?platform=iphone
For Android: https://play.google.com/store/apps/details?id=com.read21.wandview.wandview&hl=en&gl=US

**Comment by avocardio** [comment]
It looks super good @SonicCodes ! How does it work? And the run contents and API key are stored safely I assume?

Will definitely try it out, and lets also hope that some staff sees this. @lukas

**Comment by SonicCodes** [comment]
@avocardio run contents and API key are only locally stored, you can view the source code at https://github.com/read21-org/wandview to confirm that what I'm saying it true.

**Comment by avocardio** [comment]
@SonicCodes very nice, thank you!

**Comment by morganmcg1** [comment]
@SonicCodes this is awesome, the W&B team here think its really cool! do you have a twitter handle? would love to share it and tag you :)

**Comment by SonicCodes** [comment]
@morganmcg1 it's so awesome you guys liked it, my twitter handle is "@rami_mmo"
