### ISSUE TITLE
[Docs] Labeling of disk utilization is still confusing

### ISSUE THREAD

**Issue by luzuku** [wandb/wandb#5784]
There is a closed issue #1784 which asked the same question of why the website states that [disk i/o util is logged](https://docs.wandb.ai/guides/app/features/system-metrics) when in fact it actually logs `psutil.disk_usage("/")` [here](https://github.com/wandb/wandb/blob/d0b056e17518c08ff71b89d109aa1a2b162f122d/wandb/sdk/internal/system/assets/disk.py#L66-L71) which is not i/o related. This is very confusing, at least to me. I feel like the labeling of system metrics should be precise and unambiguous.

Has this been forgotten or am I overlooking something? I can't find anything disk i/o related in my logs or in this repo.

**Comment by sydholl** [comment]
Internal GitHub User commented: 
There is a closed issue #1784 which asked the same question of why the website states that [disk i/o util is logged](https://docs.wandb.ai/guides/app/features/system-metrics) when in fact it actually logs `psutil.disk_usage("/")` [here](https://github.com/wandb/wandb/blob/d0b056e17518c08ff71b89d109aa1a2b162f122d/wandb/sdk/internal/system/assets/disk.py#L66-L71) which is not i/o related. This is very confusing, at least to me. I feel like the labeling of system metrics should be precise and unambiguous.

Has this been forgotten or am I overlooking something? I can't find anything disk i/o related in my logs or in this repo.

**Comment by umakrishnaswamy** [comment]
Hey @luzuku, I escalated this to our docs team, and will update you with progress/any other information I find.

**Comment by umakrishnaswamy** [comment]
Hey @luzuku, I'm going to go ahead and close out this ticket, but I will update you with progress made on this when it arises.

**Comment by luzuku** [comment]
@umakrishnaswamy This exactly the same thing that happened with #1784 and then nothing happened.

**Comment by umakrishnaswamy** [comment]
@luzuku At the time, the issue was considered a lower priority task for the SDK team, but it is now being picked up for work. This issue is on my personal queue for SDK tasks, and I will have updates for you when progress is made.

**Comment by umakrishnaswamy** [comment]
Hey @luzuku, just wanted to update you and mention that Disk I/O will be displayed in system metrics in addition to Disk Utilization. You'll be able to see this in our next SDK release around the beginning of Sept.

**Comment by umakrishnaswamy** [comment]
Hey @luzuku, you should be able to now see Disk I/O displayed within System Metrics for any new runs you initiate with the new version of our SDK!
