### ISSUE TITLE
wandb.watch does not work with torch/jit/ScriptModules

### ISSUE THREAD

**Issue by truskovskiyk** [wandb/wandb#580]
Hi, first of all, I would like to say huge thank you for a great tool, I really like wandb and it helps me a lot.

Here is a problem, which I get while working with wandb

* Weights and Biases version: wandb, version 0.8.12
* Python version: Python 3.6.1
* Operating System: Darwin

### Description

wandb.watch does not work with any models, which contains layer with ScriptModules

### What I Did

I am working with detection module from torchvision https://github.com/pytorch/vision/tree/master/references/detection
Here is a small example of a problem:
If you run this code
```
import wandb
from torchvision.models.detection import fasterrcnn_resnet50_fpn
wandb.init(project='common')
model = fasterrcnn_resnet50_fpn()
wandb.watch(model)
```
you will get this error
```
wandb: Started W&B process version 0.8.12 with PID 38398
wandb: Local directory: wandb/run-20190928_163622-ngu052su
wandb: Syncing run curious-deluge-85: https://app.wandb.ai/truskovskiyk/common/runs/ngu052su
wandb: Run `wandb off` to turn off syncing.

Traceback (most recent call last):
  File "bug_rep.py", line 8, in <module>
    wandb.watch(model)
  File "/Users/kyryl/Projects/Kyryl/common/client/wandb/__init__.py", line 148, in watch
    model, criterion, graph_idx=idx)
  File "/Users/kyryl/Projects/Kyryl/common/client/wandb/wandb_torch.py", line 227, in hook_torch
    graph.hook_torch_modules(model, criterion, graph_idx=graph_idx)
  File "/Users/kyryl/Projects/Kyryl/common/client/wandb/wandb_torch.py", line 291, in hook_torch_modules
    self.hook_torch_modules(sub_module, prefix=name)
  File "/Users/kyryl/Projects/Kyryl/common/client/wandb/wandb_torch.py", line 291, in hook_torch_modules
    self.hook_torch_modules(sub_module, prefix=name)
  File "/Users/kyryl/Projects/Kyryl/common/client/wandb/wandb_torch.py", line 326, in hook_torch_modules
    sub_module.register_forward_hook(self.create_forward_hook(name, modules)))
  File "/Users/kyryl/vn/common/lib/python3.6/site-packages/torch/jit/__init__.py", line 1834, in fail
    raise RuntimeError(name + " is not supported on ScriptModules")
RuntimeError: register_forward_hook is not supported on ScriptM
wandb: Waiting for W&B process to finish, PID 38398
odules
wandb: Program failed with code 1. Press ctrl-c to abort syncing.
wandb: Process crashed early, not syncing files
```
The problem here is this module https://github.com/pytorch/vision/blob/master/torchvision/ops/misc.py#L135

Here is some toy example of how to reproduce 
```
import wandb
import torch


class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.weight = torch.nn.Parameter(torch.rand(2, 2))
        self.linear = torch.nn.Linear(2, 2)

    def forward(self, x):
        output = self.weight.mv(x)
        output = self.linear(output)
        return output


module = MyModule()
scripted_module = torch.jit.script(MyModule())


wandb.init(project='common')
wandb.watch(scripted_module)
```

ouput 
```
wandb: Started W&B process version 0.8.12 with PID 38764
wandb: Local directory: wandb/run-20190928_164606-sdgo358a
wandb: Syncing run wobbly-crypt-89: https://app.wandb.ai/truskovskiyk/common/runs/sdgo358a
wandb: Run `wandb off` to turn off syncing.

Traceback (most recent call last):
  File "bug_rep.py", line 34, in <module>
    wandb.watch(scripted_module)

wandb: Waiting for W&B process to finish, PID 38764
  File "/Users/kyryl/Projects/Kyryl/common/client/wandb/__init__.py", line 148, in watch
    model, criterion, graph_idx=idx)
  File "/Users/kyryl/Projects/Kyryl/common/client/wandb/wandb_torch.py", line 227, in hook_torch
    graph.hook_torch_modules(model, criterion, graph_idx=graph_idx)
  File "/Users/kyryl/Projects/Kyryl/common/client/wandb/wandb_torch.py", line 326, in hook_torch_modules
    sub_module.register_forward_hook(self.create_forward_hook(name, modules)))
  File "/Users/kyryl/vn/common/lib/python3.6/site-packages/torch/jit/__init__.py", line 1834, in fail
    raise RuntimeError(name + " is not supported on ScriptModules")
RuntimeError: register_forward_hook is not supported on ScriptModules
wandb: Program failed with code 1. Press ctrl-c to abort syncing.
wandb: Process crashed early, not syncing files
```

**Comment by cvphelps** [comment]
Thanks for reporting this! We'll look at it in our weekly meeting.

**Comment by dennisc1** [comment]
@cvphelps do you an update on this? I’m running into the same problem.

**Comment by XefPatterson** [comment]
I aslo have this problem. Wish it was working. Great tool.

**Comment by andrecavalcante** [comment]
I have a similar issue: importing torch breaks wandb. Simple code such as 

import torch
import wandb
if __name__ == '__main__':
   wandb.init(project="project", dir="C:/Users/andre/Documents/wandb/")

generates the error: 
 File "C:\Users\andre\Anaconda3\lib\site-packages\wandb\__init__.py", line 1125, in init
    _init_headless(run)
  File "C:\Users\andre\Anaconda3\lib\site-packages\wandb\__init__.py", line 312, in _init_headless
    "W&B process failed to launch, see: {}".format(path))
wandb.run_manager.LaunchError: W&B process failed to launch, see: wandb\debug.log

**Comment by vanpelt** [comment]
@andrecavalcante this is a Windows related issue.  We have a new version of the client library optimized for Windows here:  https://github.com/wandb/client-ng You can install with `pip install wandb-ng`

**Comment by THSWind** [comment]
> Thanks for reporting this! We'll look at it in our weekly meeting.

Hello, 
     Could you tell me if the problem has been solved?

**Comment by andrecavalcante** [comment]
Hi, I am now using the client wandb-ng on windows. For this client, there is no problem. However I don't know if the original "wandb" client still breaks on windows when using Pytorch.

**Comment by vanpelt** [comment]
@THSWind you can get the latest RC by running `pip install wandb -U --pre`

**Comment by THSWind** [comment]
@vanpelt  okay, I'll try it, thank you very much

**Comment by ariG23498** [comment]
Hey @THSWind 
Is the issue resolved?
We would like to close stale tickets. :smile:

**Comment by andrecavalcante** [comment]
Hi, @ariG23498 the error I reported above does occur for me anymore.

**Comment by tnfru** [comment]
I get this Error too, on POP OS 20.10

**Comment by ariG23498** [comment]
Hey folks,
We do not support `watch` with models with `ScriptModules`.
We are looking forward to add support for this in the later runs.
Will update the thread as soon as this is supported.

**Comment by mehraveh2016** [comment]
hi, I have the same problem, I am working with BART (which is a transformer model ), could you please tell me what is the solution? noting worked for me 
thank you

**Comment by vanpelt** [comment]
@mehraveh2016 you'll need to set the environment variable `WANDB_WATCH=false` to disable gradient logging until we're able to support custom Jit models.

**Comment by anmolmann** [comment]
Hey all, closing the loop here. We [worked](https://github.com/wandb/wandb/pull/3509) on this issue last year. FYI, [this PR ](https://github.com/wandb/wandb/pull/3509)doesn't fix the issue for people who want to track weights, but it helps for users who want to track just gradients.

However, one workaround for this issue is to do the tracing/scripting before `wandb.watch` basically:
```
nn = nn.Linear(10, 2)
gg = torch.jit.script(nn)
wandb.watch(nn, log="all")
```

Or

```
class Net(nn.Module):
        def __init__(self):
            super().__init__()
            self.layer_1 = nn.Linear(10, 2)

        def forward(self, x):
            return self.layer_1(x)

    net = torch.jit.script(Net())
    run.watch(net, log_graph=True)
```

would work because we first script and then add the hooks. `torch.jit`  tracing doesn't support lambda functions this is the source for the original error… when we call these [line](https://github.com/wandb/client/blob/master/wandb/wandb_torch.py#L113-L114). `torch.jit` can’t resolve this hook see this part of the [code](https://github.com/pytorch/pytorch/blob/master/torch/_sources.py#L51-L55). It can’t find def hence it throws the above error.
