### ISSUE TITLE
[App]: Missing data points from custom charts

### ISSUE THREAD

**Issue by ryanliu30** [wandb/wandb#5809]
### Current Behavior

While logging a ROC curve with the following code:
```
def make_wandb_plot(x_data, y_data, xtitle, ytitle, title):
        table = wandb.Table(data=[[x, y] for (x, y) in zip(x_data, y_data)], columns = [xtitle, ytitle])
        return wandb.plot.line(table, xtitle, ytitle, title=title)
wandb.log({"my plot": make_wandb_plot(fpr, tpr, "FPR", "TPR", "ROC curve")}
```
The chart rendered in the app becomes 
<img width="657" alt="Screenshot 2023-06-28 at 5 18 39 PM" src="https://github.com/wandb/wandb/assets/72370449/9bd8b5fd-ad71-4368-8504-25df11cc6271">
However, if I check the tables section and select render as 2D Plot I can see that the numbers have been successfully logged to wandb.
<img width="650" alt="Screenshot 2023-06-28 at 5 20 17 PM" src="https://github.com/wandb/wandb/assets/72370449/ad9a10e3-8595-48ef-9e8c-edb8046a778a">

### Expected Behavior

Custom charts should render all the data logged to the app. Including a run-step selection bar just like media charts will also be nice.

### Environment

OS: macOS 13.4.1 (22F82)

Browsers: Chrome

Version: 114.0.5735.198 (Official Build) (x86_64)

**Comment by thanos-wandb** [comment]
Hi @ryanliu30 thank you for reporting this issue. Would it be please possible to share a link to your Workspace to investigate this further? I was wondering what's the total number of points and if that relates to [sampling (1500 points)](https://docs.wandb.ai/guides/app/features/panels/line-plot/sampling) that's performed in App. Or if the data points haven't yet synced with the App? do you get the same plot after the run has completed?

**Comment by ryanliu30** [comment]
Here's the link to my [workspace](https://wandb.ai/exatrkx/DeepLorentzSet/sweeps/pvgffmac/workspace?workspace=user-liuryan30). Even though I logged a plot each time I validate my model, I didn't see the custom charts being updated.

**Comment by ryanliu30** [comment]
Hi @thanos-wandb, I used pytorch_lightning to train my model. Here's the rough structure of the loop:
```
    def make_wandb_plot(self, x_data, y_data, xtitle, ytitle, title):
        table = wandb.Table(data=[[x, y] for (x, y) in zip(x_data, y_data)], columns = [xtitle, ytitle])
        return wandb.plot.line(table, xtitle, ytitle, title=title)
    
    def shared_on_epoch_end_eval(self, preds):
        # Transpose list of lists
        labels, prob, student_emb, boosted_pred, beta = map(lambda x: np.concatenate(list(x), axis = 0), zip(*preds))
        df = pd.DataFrame({"beta": beta, "acc": (boosted_pred == labels)})
        acc_beta = df.groupby("beta").mean()
        # Evaluate model performance
        auc = roc_auc_score(labels, prob[:, 1])
        acc = np.mean(labels == prob.argmax(-1))
        fpr, tpr, _ = roc_curve(labels, prob[:, 1])
        rej = 1./np.interp([0.3, 0.5], tpr, fpr)
        self.log_dict({
            "auc": auc,
            "acc": acc,
            "rej_30": rej[0], 
            "rej_50": rej[1],           
            "invariance score": (2 * acc_beta.mean().item() - 1)/(2 * acc_beta.max().item() - 1),
        })
        
        wandb.log({
            "Penultimate layer outputs": self.make_pca_plot(labels[:10000], student_emb[:10000]),
            "ROC curve": self.make_wandb_plot(
                fpr,
                tpr,
                "False Positive Rate",
                "True Positive Rate",
                "ROC curve"
            ),
            "Accuracy vs. beta": self.make_wandb_plot(acc_beta.index, acc_beta["acc"], "beta", "Accuracy", "Accuracy vs. beta")
        })

        
    def on_validation_epoch_end(self):
        self.shared_on_epoch_end_eval(self.validation_step_outputs)
        self.validation_step_outputs.clear()
```
Unfortunately, I can't provide you the link to my repo since it is still a work in progress.

**Comment by thanos-wandb** [comment]
Thank you @ryanliu30 for the detailed info and code snippet. It's still not clear why the two plots would be different, unless they refer to different epoch, let me investigate this bit more. 

In the meantime, you may find useful to use our Custom Chart to plot ROC curves. There's an [example here](https://docs.wandb.ai/guides/app/features/custom-charts#builtin-presets) (in ROC curve tab), I hope this helps.

**Comment by thanos-wandb** [comment]
Hi @ryanliu30 checking this further and since your provided code isn't complete to be tested on our end, could you please confirm if `[x_data,y_data]` are same as `[fpr, tpr]` in the following lines:

```
def make_wandb_plot(x_data, y_data, xtitle, ytitle, title):
        table = wandb.Table(data=[[x, y] for (x, y) in zip(x_data, y_data)], columns = [xtitle, ytitle])
        return wandb.plot.line(table, xtitle, ytitle, title=title)
wandb.log({"my plot": make_wandb_plot(fpr, tpr, "FPR", "TPR", "ROC curve")}
```

It seems they refer to different values, and I was wondering if you could try our ROC curve plot as in the example above.

**Comment by ryanliu30** [comment]
Hi @thanos-wandb thanks for your suggestions. I didn't use the built-in ROC curve display. But I found a fix:
```
"ROC curve": self.make_wandb_plot(
    np.interp(np.linspace(0, 1, 1001), tpr, fpr),
    np.linspace(0, 1, 1001),
    "False Positive Rate",
    "True Positive Rate",
    "ROC curve"
),
```
worked just fine for me. So I suppose that the problem is that there were too many points.

**Comment by thanos-wandb** [comment]
Glad to hear this @ryanliu30 thanks for the update! I will close this ticket now since you've worked out a solution, but please feel free to reopen it if you had any further questions or create a new thread for any new issues.
