### ISSUE TITLE
[Q] Log protocol buffers with wandb tracing for LangChain

### ISSUE THREAD

**Issue by jlewi** [wandb/wandb#5820]
I'm using Wandb's tracing feature with LangChain. I would like to log all the values as they pass through the steps in the chain. My chain consists of custom pre/post processing steps before/after standard chains like LLMChain. My custom chains use protocol buffers to represent the data. Wandb logs these protocol buffers as part of the trace but doesn't know how to serialize them so they just get logged as `non-serializable`

Here's a screenshot; Here CodeGenInput is a protocol buffer
<img width="1807" alt="Screen Shot 2023-06-30 at 8 09 27 AM" src="https://github.com/wandb/wandb/assets/777219/11821637-8827-4aa6-8a66-4f246f5edc30">

Is it possible to configure how Wandb serializes different types? Protocol buffers can be serialized to JSON using [json_format](https://googleapis.dev/python/protobuf/latest/google/protobuf/json_format.html).

**Comment by rsanandres-wandb** [comment]
Hello @jlewi !

Could you send a link to your workspace? I will be reproducing this and reporting this to the relevant team and would like to bring the relevant workspace for them to view.

**Comment by jlewi** [comment]
Cool;
https://wandb.ai/jeremylewi/autobuilder?workspace=user-jeremylewi

**Comment by parambharat** [comment]
Hi @jlewi, I'm trying to add serialization support for protocol buffers. Can you provide me with a sample script so that I can build and test the implementation ?

**Comment by jlewi** [comment]
Here are some snippets. I unfortunately haven't had a chance to try these out. This isn't super high priority for me right now so if you need a full repo from me feel free to downgrade or close.

Here's a rudimentary chain that takes as input a protobuf and returns a protobuf.

```
import langchain
from langchain import chains, chat_models, prompts, schema
from langchain.callbacks import manager
from langchain.chains.base import Chain

import codegen_pb2

class LLMTextToCodeGenOutput(Chain):
    """This chain takes the text output of the LLM which should contain markdown and turns it into patches.

    This also requires the orginal codegen_input which should be passed along
    """

    input_key: str = "text"
    output_key: str = "codegen_output"  #: :meta private:

    # The key to look for the input snippets.
    input_snippets_key = "input_snippets"

    @property
    def input_keys(self) -> List[str]:
        """Will be whatever keys the prompt expects.

        :meta private:
        """
        return [self.input_key, "codegen_input"]

    @property
    def output_keys(self) -> List[str]:
        """Will always return text key.

        :meta private:
        """
        return [self.output_key]

    def _call(
        self,
        inputs: Dict[str, Any],
        run_manager: Optional[manager.CallbackManagerForChainRun] = None,
    ) -> Dict[str, Any]:   
        output = codegen_pb2.CodeGenOutput(text="hello")
        return {self.output_key: output}

```

proto buff file might look like

```
syntax = "proto3";

option go_package = "github.com/jlewi/roboweb/go/protos/v1alpha1";

message CodeGenOutput {  
    string text = 1;
}
```

You'd need to install the protobuf toolchain and generate the protocol buffers. I unfortunately won't have time to put together a full repo.

**Comment by sydholl** [comment]
WandB Internal User commented: 
rsanandres-wandb commented: 
Hello @jlewi !

Could you send a link to your workspace? I will be reproducing this and reporting this to the relevant team and would like to bring the relevant workspace for them to view.
