### ISSUE TITLE
[App]: Graphs are empty

### ISSUE THREAD

**Issue by DeepakR-Sastry** [wandb/wandb#5824]
### Current Behavior

Hi, none of the runs are being synced to wandb; all of my graphs are shown as having no data even though they have been running for quite a while. There is no issue with the code as far as I know because we had many runs synced in the past with no issues. In fact, this issue only seemed to come up this morning because we had a few runs yesterday with no problems with the graphing

### Expected Behavior

Graphs are supposed to created for all the runs

### Steps To Reproduce

Try to log anything using wandb and try to visualize the graphs on the webpage. The error we get is: "There's no data for the elected runs.Try a different X axis setting.Current X axis: _step" even though there definitely is data that could be synced.

### Screenshots

![Screenshot from 2023-06-30 12-54-02](https://github.com/wandb/wandb/assets/76264101/9a0f7e6f-c9ec-469b-8126-a31b9d893427)

### Environment

OS: Linux

Browsers: Chrome, Firefox

Version: 0.15.1

**Comment by h4duan** [comment]
I got the same error. Everything was running fine several hours ago and then stopped working.

**Comment by DeepakR-Sastry** [comment]
I think this is acknowledged by their team now: https://status.wandb.com/incidents/q7tfd1d60kqw
