### ISSUE TITLE
[Q] How to use W&B with new `lightning` (not old `pytorch-lightning`) ?

### ISSUE THREAD

**Issue by Hongbo-Miao** [wandb/wandb#5827]
Based on [this](https://github.com/Lightning-AI/lightning/discussions/16688#discussioncomment-4927515), `lightning` replaced `pytorch-lightning`.

However, the [W&B document](https://docs.wandb.ai/guides/integrations/lightning) is still is using old `pytorch-lightning`.

This does not exist

```python
from lightning.loggers import WandbLogger
```

What is the new way using W&B logger? Thanks! 😃

**Comment by sydholl** [comment]
Internal GitHub User commented: 
Based on [this](https://github.com/Lightning-AI/lightning/discussions/16688#discussioncomment-4927515), `lightning` replaced `pytorch-lightning`.

However, the [W&B document](https://docs.wandb.ai/guides/integrations/lightning) is still is using old `pytorch-lightning`.

This does not exist

```python
from lightning.loggers import WandbLogger
```

What is the new way using W&B logger? Thanks! 😃

**Comment by ArtsiomWB** [comment]
Hi @Hongbo-Miao!

Thank you for writing in. I've went over the pytorch-lightning's repo, and it does look like now they use 
`from lightning.pytorch.loggers.wandb import WandbLogger` to import `WandbLogger`. It worked on my side when I tried it out. Could you see if it works for you as well?

**Comment by Hongbo-Miao** [comment]
Thanks @ArtsiomWB , it works well! 😃
Feel free to close this ticket or close after the document fixed, thanks!

**Comment by ArtsiomWB** [comment]
Perfect! Thats great news, I've notified our docs team and they said they'll look into it! Otherwise, I will close this ticket for now. Thank you so much for brining this up!
