### ISSUE TITLE
[Q]RunsStateDeltaQuery responded 504 gateway time out

### ISSUE THREAD

**Issue by yh-xu** [wandb/wandb#5828]
I delolyed wandb server on local host. It took more than 1 min to render page of runs and chart. It seems request of RunsStateDeltaQuery got 504 gateway timeout and thus block the following queries. Sometimes request RunsStateDeltaQuery sometimes got 500 response with error message "context deadline exceeded".  What shall I do to get rid of this problem?

**Comment by thanos-wandb** [comment]
Hi @yh-xu thank you for reporting this issue. Since you've opened a duplicate thread [here](https://github.com/wandb/server/issues/122), and for consistency, I will close this thread and we can continue our discussion there.
