### ISSUE TITLE
[Q] LangChain WandbTracer doesn't log finish_reason for OpenAI calls or token counts 

### ISSUE THREAD

**Issue by jlewi** [wandb/wandb#5829]
Here's a screenshot of the output of the WandbTracer for an LLM call to OpenAI Chat Models

<img width="1893" alt="Screen Shot 2023-07-04 at 9 32 15 AM" src="https://github.com/wandb/wandb/assets/777219/a37c15fe-97dd-4cef-8fe7-370703f36a78">

The only output that gets logged is the generated response.

Here's the relevant code
https://github.com/hwchase17/langchain/blob/5585607654c05d0195850b107936040d3ed47e82/langchain/callbacks/tracers/wandb.py#L47

It does indeed look like the only information that is logged is the actual text generated. 
I think this is missing critical logging information. e.g.

* [finish_reason](https://platform.openai.com/docs/guides/gpt/chat-completions-api)
* usage_tokens

I think this is an issue in WandDBTracer and with the LangChain callback code not passing along enough information for the WandDBTracer to log it.

It looks like LangChain uses a [LLMRun](https://github.com/hwchase17/langchain/blob/5585607654c05d0195850b107936040d3ed47e82/langchain/callbacks/tracers/schemas.py#L60) object which hopefully contains an [LLMResult](https://github.com/hwchase17/langchain/blob/5585607654c05d0195850b107936040d3ed47e82/langchain/schema/output.py#L64)

As far as I can tell LLMOutput gets populated in [_create_chat_result](https://github.com/hwchase17/langchain/blob/5585607654c05d0195850b107936040d3ed47e82/langchain/chat_models/openai.py#L392) it looks like that is passing along usage tokens but not the finish_reason.

**Comment by ArtsiomWB** [comment]
Hi @jlewi! Thank you for writing in!

What version of Wandb SDK are you on, as well as could you send me a link to your workspace?

**Comment by jlewi** [comment]
```
wandb --version
wandb, version 0.15.3
```

https://wandb.ai/autobuilder/experiments?workspace=user-jeremylewi

**Comment by parambharat** [comment]
This is being fixed in this PR:  https://github.com/hwchase17/langchain/pull/6806

**Comment by sydholl** [comment]
Artsiom Skarakhod commented: 
I appreciate you pointing this issue out. I have notified our engineering team and they are currently working on a PR in order to resolve this concern.

Thank you for your time once again.

**Comment by ayulockin** [comment]
Hey @jlewi, closing this as well citing the reasoning in another issue raised by you [here](https://github.com/wandb/wandb/issues/5820#issuecomment-2060360644).
