### ISSUE TITLE
[CLI]: ImportError: cannot import name 'WandbLogger' from 'ray.tune.integration.wandb'

### ISSUE THREAD

**Issue by c4cld** [wandb/wandb#5830]
### Describe the bug

ImportError: cannot import name 'WandbLogger' from 'ray.tune.integration.wandb'

```python

```

```shell

```Traceback (most recent call last):
  File "/root/anaconda3/envs/scenarionet/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/scenarionet/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/aliyun/scenarionet-20230705/scenarionet_training/scripts/train_waymo.py", line 81, in <module>
    train(
  File "/root/aliyun/scenarionet-20230705/scenarionet_training/train_utils/utils.py", line 140, in train
    from scenarionet_training.wandb_utils.our_wandb_callbacks_ray100 import OurWandbLogger
  File "/root/aliyun/scenarionet-20230705/scenarionet_training/wandb_utils/our_wandb_callbacks_ray100.py", line 3, in <module>
    from ray.tune.integration.wandb import WandbLogger, _clean_log, _set_api_key
ImportError: cannot import name 'WandbLogger' from 'ray.tune.integration.wandb' (/root/anaconda3/envs/scenarionet/lib/python3.9/site-packages/ray/tune/integration/wandb.py)


### Additional Files

_No response_

### Environment

WandB version: 0.15.3

OS: ubuntu 18.04

Python version: 3.9

Versions of relevant libraries:
ray == 2.0.0

### Additional Context

_No response_

**Comment by ArtsiomWB** [comment]
Hi @c4cld! Could you send me a line of code where you are importing wandbLogger?

**Comment by c4cld** [comment]
@ArtsiomWB Thank you for your reply ^_^

The line of code where I am importing wandbLogger is as follows:
from ray.tune.integration.wandb import WandbLoggerCallback, _clean_log, \
    Queue, WandbLogger

Are you trying to integrate Wandb with Ray tune here? Has this worked for you before, or is this your first time trying this out?
This is the first time I use wandb and try to integrate wandb with ray.

**Comment by ArtsiomWB** [comment]
Perfect, looking at Ray's documentation [here](https://docs.ray.io/en/latest/tune/examples/tune-wandb.html), it does look like now you have to use `from ray.air.integrations.wandb import WandbLoggerCallback` to import the logger. Could you see if this works for you? If it does I'll ask our team to update our docs.

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by c4cld** [comment]
@ArtsiomWB Thank you for your concern. I have already addressed this issue by downgrading ray to version 1.0.0.

**Comment by ArtsiomWB** [comment]
Perfect! Thank you for the update.
