### ISSUE TITLE
[Q] Resuming Run In W&B Sweep

### ISSUE THREAD

**Issue by mcleod-matthew-gene** [wandb/wandb#5840]
I am using a stack of pytorch lightning, hydra and W&B. I understand how to resume runs when a job is restarted (from either a crash or a spot instance being turned off) when doing specific runs with W&B. 

I am unsure how to continue a specific run within a W&B sweep. The closest to documentation I could find is for [restarting grid search](https://docs.wandb.ai/guides/sweeps/faq#can-i-rerun-a-grid-search), which highlights that if you wish to redo your grid search because of a crashed run, **delete the run and try again**. There are instances I will want to resume run rather than start from scratch. Does W&B support this?

**Comment by ArtsiomWB** [comment]
Hi @mcleod-matthew-gene! Thank you for writing in. You are able to resume a run inside of a sweep as long as that sweep is finished and the run does not have a "crashed/failed" status, and it's finished as well. 

Here is a quick example:

Here I have a run that was finished successfully inside of a sweep, and I can log more data into it, by logging the batch size, epochs, lr, and val_acc into it once each. 

```py
import wandb

batch_size = 10
epochs=30
lr = 40

with wandb.init(entity="wandb", project="my-first-sweep", resume="must", id="kqibvidi"):
    wandb.log({"batch": batch_size})
    wandb.log({"epoch": epochs})
    wandb.log({"lr": lr})
    wandb.log({"val_acc":2})

    wandb.finish()
```

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by mcleod-matthew-gene** [comment]
Thanks for the follow up. There are some runs  that get terminated due to preemption and as a result have an error. Is it possible to resume those that have a "crashed/failed" status within a sweep? Why does the sweep status need to be finished? Can I resume a run with the sweep status as "In Progress"?

**Comment by ArtsiomWB** [comment]
Hey @mcleod-matthew-gene! I looked a bit deeper into this. It does look like any run regardless of the status can be resumed. Doesn't matter if it's finished, crashed, or failed. As long as that run is finished, you should be able to resume it even if its sweep is still running.

**Comment by mcleod-matthew-gene** [comment]
Wonderful, thanks for looking in this! I really appreciate it.
