### ISSUE TITLE
[CLI]: Keras dropped support for internal APIs

### ISSUE THREAD

**Issue by bermeitinger-b** [wandb/wandb#5844]
### Describe the bug

TensorFlow 2.13.0 (https://github.com/tensorflow/tensorflow/releases/tag/v2.13.0) disabled access to "internal API". I guess that the `keras.engine` submodule is regarded as private now.

```python
from wandb.keras import WandbMetricsLogger
```

```shell
wandb: ERROR Unable to patch Tensorflow/Keras
exception while trying to patch_tf_keras
Traceback (most recent call last):
  File ".../lib/python3.11/site-packages/wandb/integration/keras/keras.py", line 86, in patch_tf_keras
    from keras.engine import training
ModuleNotFoundError: No module named 'keras.engine'
```
(the path is shorted by me)

### Environment

WandB version: 0.15.5

Python version: 3.11.3

Versions of relevant libraries: `tensorflow==2.13.0`, `keras==2.13.1`

**Comment by ArtsiomWB** [comment]
Hi @bermeitinger-b! Thank you so much for bringing this up! I have notified our engineering team regarding this issue, and have created an internal ticket for this. We are looking into the issue thanks to you. :)

**Comment by ayulockin** [comment]
Hey @bermeitinger-b, the issue might be resolved if you are trying installing wandb from the repo.

**Comment by bermeitinger-b** [comment]
Yes, I think this worked out.

Now that keras is phased out of tensorflow and into keras-core, what's your plan with this? (You don't need to answer, this is about the issue at hand.)

**Comment by ArtsiomWB** [comment]
Great! I am glad it works for you now. 

Our engineering team is currently working on fixing the integration with Keras.

**Comment by umakrishnaswamy** [comment]
Hey @bermeitinger-b - upgrading to 0.15.10 fixes this issue. Please let me know if you have any other questions/issues in regards to this!
