### ISSUE TITLE
[App]: Account Creation Loop

### ISSUE THREAD

**Issue by nicholscrawford** [wandb/wandb#5846]
### Current Behavior

So I've recently just tried to create an account. After the first signup page, while being redirected, my browser tab crashed. Now upon returning to login, I am prompted to "Create your account" at the page https://wandb.ai/signup.

I already did that step, and selected a personal account. However whenever I go back, it prompts me to do so again and says my account already exists.

Error creating account: entity already exists for the user nichols

### Environment

OS: Tried logging in on both ubuntu, and ios

Browsers: Firefox and Safari

Version: 20.04

**Comment by MBakirWB** [comment]
Hi @nicholscrawford , thank you for writing in and our apologies for the inconvenience. I've asked the app team to investigate and we'll get you unblocked sometime today. I will provide an update by EOD

**Comment by MBakirWB** [comment]
Hey @nicholscrawford , we appreciate you patience while we worked through this. We have identified the issue causing this loop behavior and have fixed it. You are now able to access your account without being prompted to input a new account name.
