### ISSUE TITLE
[Q] WandbTracer with Langchain in Colab

### ISSUE THREAD

**Issue by cjdonahoe** [wandb/wandb#5848]
Hey there,

I'm working with some team members on using the WandbTracer integration with LangChain in Colab.

How do I stop/finish a WandB run that is started from:
```
os.environ["WANDB_PROJECT"] = "langchain-tracing"
os.environ["WANDB_NOTEBOOK_NAME"] = "some_name.ipynb"
os.environ["LANGCHAIN_WANDB_TRACING"] = "true"
```

When I'm running a notebook locally in VS Code, I can run `WandbTracer.finish()` in a notebook cell and it will end the WandB run. This method doesn't work in Colab. Stopping and deleting the Colab runtime doesn't work either.

**Comment by cjdonahoe** [comment]
`langchain`

**Comment by rsanandres-wandb** [comment]
Hello @cjdonahoe !

I tried to replicate the issue and was unable to.  One thing I can recommend is to use the tracer as a context manager in order for it to shut down once it has finished executing.
```
# enable tracing using a context manager
with wandb_tracing_enabled():
    math_agent.run("What is 5 raised to .123243 power?")  # this should be traced
```

If this does not work for you, could you share a short code snippet of how you are running the tracer as well as what `wandb` and `langchain` versions you are using?

**Comment by morganmcg1** [comment]
Closing this issue, for our latest LLM and GenAI products please checkout W&B Weave, our replacement for W&B Prompts
-  [Weave announcement](https://wandb.ai/wandb/weave-announcement/reports/Weave-Simple-tools-for-applying-Generative-AI--Vmlldzo3NDE0Mjcx)
- [Weave Documentation](https://wandb.github.io/weave/)
