### ISSUE TITLE
[Q] Resuming a crashed run

### ISSUE THREAD

**Issue by vb000** [wandb/wandb#5856]
One of my PyTorch lightning experiments using wandb as the logger crashed midway due to a system error. I resumed the experiment with the last checkpoint. When I resumed the experiment, I also tried to resume the wandb run by providing the wandb id of the previous run.

I obtained the wandb id of the previous run from the name of the run directory in the format `run-<timestamp>-<wandb id>`. Wandb however started a new run with the `Run path` on the wandb webpage appearing as `<username>/<project>/internal.log`:

![Screenshot 2023-07-07 at 7 32 03 AM](https://github.com/wandb/wandb/assets/16723254/72bf07f9-b7f6-4481-999b-cfa83a24459d)

Usually, it is something like:

![Screenshot 2023-07-07 at 7 33 35 AM](https://github.com/wandb/wandb/assets/16723254/c4c3ed2a-62a3-4791-b634-5b2bcd2ea31f)

The resumed (intended to be resumed) run then hangs without an error at the point first data is logged to wandb. How might I be able to reliably avoid this stalling when resuming an existing run?

**Comment by ArtsiomWB** [comment]
Hi @vb000! Thank you for writing in! Could you send me some minimal reproduction code of how you are resuming your wandb run?

**Comment by sydholl** [comment]
Artsiom Skarakhod commented: 
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.
