### ISSUE TITLE
[CLI]: wandb sync with --append option fails to sync offline runs with the same id

### ISSUE THREAD

**Issue by mehranagh20** [wandb/wandb#5865]
### Describe the bug

I run my experiments in the offline mode. That results in multiple wandb folders such as:
./wandb/offline-run-20230701_162008-giyrbe5p
./wandb/offline-run-20230705_154815-giyrbe5p
which is expected. However, the second part of the run (newer logs) won't get synced when running:
`wandb sync --sync-all --include-offline --include-synced --append`

Since the second folder is just the continuation of the first one, how can I sync it into the same run?

### Environment

WandB version: 0.15.5

OS: 

Python version: 3.8.12

Versions of relevant libraries:

**Comment by nate-wandb** [comment]
Hi @mehranagh20, you should be able to do this by syncing the first run, then syncing the run that you would like appended with the `--append` flag and  `--id <run-id-from-first-sync>`. 

Let me know if that helps.

**Comment by mehranagh20** [comment]
@nate-wandb I have already tried that. The second run does not get appended. Here is an example of the commands I use:

`wandb sync ./wandb/offline-run-20230701_162008-giyrbe5p --project test-append`
And then for the second run:
`wandb sync ./wandb/offline-run-20230705_154815-giyrbe5p --project test-append --id giyrbe5p --append`

**Comment by amoazeni75** [comment]
@mehranagh20 Have you fixed the issue? I have the same issue

**Comment by nate-wandb** [comment]
Hi @mehranagh20 and @amoazeni75 after reproducing the issue I see the problem as well. I think this is expected not to work since resuming runs is not available for offline runs and appending uses a similar code path. I'll make a feature request to the team to support this and follow up once they have a chance to look into this.

**Comment by nicoboou** [comment]
Hi @nate-wandb @mehranagh20 @amoazeni75, have you found any workaround yet ? Is this going to be fixed ? Such capability is quite crucial when using for ex. SLURM cluster that have nodes disconnected from the Internet...

**Comment by nate-wandb** [comment]
Hi @nicoboou, there should be a fix on this but I don't have an ETA on this yet. The only workaround I could see is spinning up a [wandb server](https://docs.wandb.ai/guides/hosting) locally on the cluster (or any machine it may have network access to) and instead of using offline runs, sync to the local server. I suppose it should be possible to then take the run folders and sync/append them to wandb.ai since they are no longer offline runs but I haven't tested this path yet. If you think this is an option you would want to try I can give this a test?

**Comment by nicolas-dufour** [comment]
Hi @nate-wandb, is there a solution to resume offline runs? Installing a local server is not always possible for publicly managed clusters

**Comment by anmolmann** [comment]
> Hi @nate-wandb, is there a solution to resume offline runs? Installing a local server is not always possible for publicly managed clusters

Hey @nicolas-dufour, it is not possible to use resume with offline mode actually in a straightforward manner. However, there is a workaround which might be useful for your use case: [you should be able to](https://docs.wandb.ai/ref/cli/wandb-sync) `wandb sync` a resumed run. 
Once you are able to sync your offline runs via this cmd: `wandb sync --clean --include-offline --clean-force --clean-old-hours=0` -- you can then [resume your run](https://docs.wandb.ai/guides/runs/resuming#resume-guidance) by passing this arg `resume=True` in the `wandb.init(...)`. Please let us know if this is helpful for your use-case.

**Comment by nicolas-dufour** [comment]
@anmolmann Thanks for the answer!
But then i need to manually intervene between each resuming? My usecase is that i'm resuming when the SLURM cluster is restarting my job automatically so i can't know when to do this

**Comment by cdancette** [comment]
I am also encountering this issue, which makes it hard to use wandb on a cluster with time-limited jobs which need to be resumed. @nate-wandb do you know if this bug will be fixed soon ?

**Comment by nicoboou** [comment]
hi guys, found a temporary workaround in case you are in the situation of @cdancette, i.e. willing to use wandb on a cluster with time-limited jobs (such as SLURM managed clusters) and requeue them:
- create a custom SLURMLogger, that logs everything as a dict in a .txt file (i.e. each line of the .txt is thus a dict)
- when requeing, beware to append the logs in the same file
- at the very end of your entire training, check this file and initiate wandb (offline mode) only here. Log with wandb for each line of the .txt file

works like a charm on my side, but still a workaround :)

**Comment by nicolas-dufour** [comment]
@nicoboou was thinking to do the same but at this point i don't really see the use of wandb if i need to create my own logger to make it work haha. Also becomes quite cumbersome when you start to log images, tables, etc

**Comment by cdancette** [comment]
What I am doing now is resuming the run as a new experiment in wandb, with a new id, and displaying the two on the same curve... Also a workaround, not very satisfying, but at least I can log images and other things. I hope this issue will be resolved soon

**Comment by streethagore** [comment]
Is there any update on this matter ?
My use case is that I am running jobs on a SLURM cluster where compute nodes don't have internet access, and where execution cannot exceed 20 hours.

**Comment by anmolmann** [comment]
Hey, @streethagore , our eng is actively working on this request - resuming a run from a checkpoint via the graphQL API. We'll keep you updated in this thread once this is merged and deployed.

**Comment by anmolmann** [comment]
Hey folks, this [PR](https://github.com/wandb/wandb/pull/7711) implements the SDK changes needed for "run rewinding," a long-requested feature that allows users to truncate the history logged to a run at an intermediate step and resume logging from that step. This will be part of our [next SDK release](https://github.com/wandb/wandb/releases).

**Comment by thethomasboyer** [comment]
Hello @anmolmann , that still doesn't solve the issue for offline runs (or am I missing something?)

Basically in my `wandb` dir I have for example:
```
wandb/offline-run-20250218_134501-f2yl6k90  # (first run)
wandb/offline-run-20250218_184624-f2yl6k90  # (second run)
```
the second most recent run being a **rewind** of the first from the most recent checkpoint (say 20k).

Syncing the first run works fine:
![Image](https://github.com/user-attachments/assets/332b5a98-6ad1-41cf-80b4-be181712ea9e)

then calling `wandb sync wandb/offline-run-20250218_184624-f2yl6m90` simply erases logs of the first one (so typically loss curves start at log step zero, and show an initial value for the training step of 20k (the rewound-from step):
![Image](https://github.com/user-attachments/assets/a8353b52-7fde-42cd-8c68-0bd08af2a7e3)

Calling `wandb sync wandb/offline-run-20250218_184624-f2yl6m90 --append` or `wandb sync --id f2yl6m90 --append wandb/offline-run-20250218_184624-f2yl6m90` does not change anything.

Related/Duplicates?: #3841 #4624 #2423

**Comment by Daraan** [comment]
This is one of the first search result you come around. When you want to resume offline runs I realized it is essential to log a step for `--append` to work, i.e.

```python
resumed_run.log(data, step=...)
```

Without `step=...` my logs did not update. Felt like my uploads ended up in Nirvana 😅 - some kind of server side error would be nice in this situation.

**Comment by alex-bene** [comment]
This issue is still not solved. Resuming an offline run and syncing on the same plot does not work because of collisions with the reset step counter. Any plan to easily expose the internal counter so we can save it in a checkpoint and set/restore it when we resume?
