### ISSUE TITLE
[Feature]: Line plots smart sampling

### ISSUE THREAD

**Issue by ryanliu30** [wandb/wandb#5866]
### Description

In the line plot documentation it says "When over 1500 points are chosen for a line plot metric, W&B returns 1500 randomly sampled points." This is fine in most cases, but it becomes annoying in the case of showing x-axis with log scale. This makes the visualization very distorted for the first few data points and would dominate the whole plot when the datapoints keep increasing. A use case is attached.
![W B Chart 7_9_2023, 12_16_04 AM](https://github.com/wandb/wandb/assets/72370449/439e783a-1920-4998-b527-b35f466cd7f0)

### Suggested Solution

In the case of log scale, sample datapoints according to an exponentially decaying weight such that it won't distort the visualization.

**Comment by nate-wandb** [comment]
Hi @ryanliu30, thank you for the feature request and example. I see how favoring points from the earlier steps would make more sense here. I can submit this to the engineering team and follow up once they have a chance to look into this.

**Comment by wwzeng1** [comment]
@nate-wandb I wrote and reviewed an initial PR using Sweep at https://github.com/wwzeng1/wandb/pull/3/files.
I also opened it against main here, need help testing it though. https://github.com/wandb/wandb/pull/5908

**Comment by nate-wandb** [comment]
Hi @wwzeng1, thank you for submitting this! I've attached this to the feature request and will have our engineering team look into this.

**Comment by wwzeng1** [comment]
Thank you Nate! I suspect it's around 60%+ of the way there, wanted to introduce the tool to you. Please reach out to me if there are issues.
