### ISSUE TITLE
[CLI]: Importing wandb before tensorflow causes error calling nested @tf.function

### ISSUE THREAD

**Issue by alisonpeard** [wandb/wandb#5871]
### Describe the bug

I have reproduced this error with Tensorflow 2.12 and 2.13 and wandb 0.15.4 and 0.15.5. In the case where the following two conditions hold,
1. wandb is imported **before** tensorflow **and**
2. A function decorated with @tf.function calls another function also decorated with @tf.function,<br>
the following error occurs when running code from a Python script:
```
[libprotobuf FATAL google/protobuf/message_lite.cc:353] CHECK failed: target + size == res: 
libc++abi: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: target + size == res: 
zsh: abort      python mfe.py
```
Running from a Jupyter notebook the kernel simply crashes without an error message. 

Removing the inner @tf.function or changing the order of imports resolves this error. 

Here is a MFE:
```
import wandb # switch order of imports to toggle error
import tensorflow as tf

@tf.function # comment this out to toggle error
def custom_score(data):
    pass

data = tf.random.uniform((100, 20, 24, 2), 0, 1)
train = tf.data.Dataset.from_tensor_slices(data).batch(50)

@tf.function
def train_step(data):
    custom_score(data)
        
tf.config.run_functions_eagerly(False)
tf.print("Start training")
train_step(next(iter(train)))
tf.print("Runs finished without error.")

```

This error also occurs when calling an @tf.function function from a keras model's train_step() function, I assume because it is also an Autograph function. It is impractical for me to run custom_score() eagerly as it massively slows down training times.

### Environment

WandB version: 0.15.4 and 0.15.5

OS: macOS Monterey 12.5.1, M2 chip

Python version: 3.9.16

Versions of relevant libraries: 2.12, 2.13

**Comment by nate-wandb** [comment]
Hi @alisonpeard, thank you for the MFE. I tested this in Colab and did not produce the error. I think this is an issue with the protobuf version. Could you let me know what version you have installed and then try upgrading to `protobuf==3.15.0` to see if that resolves this?
