### ISSUE TITLE
[App]: (wandb/local)There's no data for the selected runs. Try a different X axis setting

### ISSUE THREAD

**Issue by luo-li-ba-suo** [wandb/wandb#5886]
### Current Behavior

I deployed the wandb server locally. It prompted me to upgrade, so I pulled the latest version, restarted, and got the following bug.
Here you can see that the current project has the training data curve stored:
![image](https://github.com/wandb/wandb/assets/52479360/a3d09b75-f56b-421b-b0ac-7436c483b93a)
But once we switch to a summary plot:
![image](https://github.com/wandb/wandb/assets/52479360/31170968-61f0-4b39-a3a0-14166d1c5882)
![image](https://github.com/wandb/wandb/assets/52479360/b2b9d60a-4a0a-4429-96db-2dfb90d8148c)
No matter how I change the x axis, it doesn't work.

### Expected Behavior

The expectation is to display the summary curve normally.

### Environment

OS:
Ubuntu
Browsers:
Edge
Version:
[0.38.0](https://hub.docker.com/layers/wandb/local/0.38.0/images/sha256-dc18b800235b1d227e65e4d3dd8135e90bc83f0aa7176951d9e1d70dc5748187?context=explore)

**Comment by thanos-wandb** [comment]
Hi @luo-li-ba-suo thanks so much for reporting this issue, I have escalated it to our Engineering teams and keep you posted here. I have reproduced the issue on my end too, and downgrading to `v0.37.0` would render these plots again in Project's Workspace. Would this work for you for now, till we patch a fix for the latest version?

**Comment by luo-li-ba-suo** [comment]
v0.37.0 does not work either. I tried more early versions and all failed. 
Maybe I did something wrong?
The docker run command I used looks like this:
`docker run --rm -d -e LICENSE={Your License} -p {your_port}:8080 --name wandb-local-{user} -v wandb_data_{user}:/vol  wandb/local`
I have built wandb_data_{user} in advance: `docker volume create wandb_data_{user}`

**Comment by thanos-wandb** [comment]
Hi @luo-li-ba-suo could you please try to explicitly specify the version tag in the last argument of your docker command as such `wandb/local:0.37.0`? what version do you see when you go to User or System Settings page? If this still won't work for you, could you please download the Debug Bundle ([docs](https://docs.wandb.ai/guides/hosting/debug)) and share with us in support@wandb.com?

**Comment by luo-li-ba-suo** [comment]
It worked!
The devil is in the detail! Thank you!

**Comment by thanos-wandb** [comment]
Perfect, glad to hear that @luo-li-ba-suo  - thanks a lot for the confirmation, and for reporting the issue! We will release a new Server W&B version early this week.
