### ISSUE TITLE
[Q]Wrong Entity

### ISSUE THREAD

**Issue by kleinzcy** [wandb/wandb#5909]
My personal entity is A, but I pass a wrong entity parameters B to the project. As a results, I encounter "wandb: ERROR Error while calling W&B API: permission denied (<Response [403]>)". Is there any way to correct the entity when I sync the wandb file?

**Comment by ArtsiomWB** [comment]
Hi @kleinzcy ! Thank you for writing in!

When you are saying:
> but I pass a wrong entity parameters B to the project
Do you mean this happened when you were creating a run?

Is there a bunch of runs now under the wrong entity or just a single file?

>Is there any way to correct the entity when I sync the wandb file?
Do you mean you are interested in getting the data you've logged to the wrong entity back to your original entity?

**Comment by kleinzcy** [comment]
1. Yes, it happens when I creating a run.

2. Yes, I want to getting the data back.

**Comment by ArtsiomWB** [comment]
Gotcha, what was the entity you accidentally wrote your data to? And what entity is it supposed to be?

**Comment by kleinzcy** [comment]
Thank your patience. The entity should be `kleinzcy`, but I wrote it as `klein`.

**Comment by ArtsiomWB** [comment]
Gotcha, so no data needs to be moved now? Great job!

Could you elaborate a bit regarding this part?
> I just wonders if there is a possible to way to fix the wrong entity error.

Also, do you know what is the name of the project you wrote into the wrong entity?

**Comment by kleinzcy** [comment]
The project name is NCDPC，and the detail is as follow:

![image](https://github.com/wandb/wandb/assets/35723500/fd3b5829-7a9e-4c0d-9d04-9357aa9ba219)

**Comment by ArtsiomWB** [comment]
Interesting, could you run wandb
`wandb login --relogin` to relogin and then try running 
`wandb sync --project <PROJECT> --entity <ENTITY> wandb/<run-folder>` in order to sync your project?

**Comment by kleinzcy** [comment]
Under your guidance, I realize that my partner login in his wandb in my env which is reason of the bug.

Thanks very much for your patience.
