### ISSUE TITLE
[App]: Webapps collapses metrics if steps are not overlapping

### ISSUE THREAD

**Issue by mova** [wandb/wandb#5914]
### Current Behavior

See screencast
Note that I start the runs at different steps != 0

The metrics are show as single bars in the webinterface, even though I have recorded multiple values.
Maybe it's because the steps have no overlap between the runs. When I select a single run to show, it works.

### Screenshots

[Screencast.webm](https://github.com/wandb/wandb/assets/779688/58e7e071-0e6a-4122-a272-691d87a1eea2)

### Environment

WandB version: 0.15.5

OS: CentOSLinux7

Python version: 3.10.10

**Comment by rsanandres-wandb** [comment]
Hello @mova!

One thing I noticed is that the x-axis (Step) on the graph do not start at zero when you change between runs. Could you try changing the range of x for the graph and see if that shows both runs?

If not, could you send a link to your workspace so I can look into it?

**Comment by sydholl** [comment]
Raphael San Andres commented: 
Hi, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
