### ISSUE TITLE
[Q] You cannot use personal projects after join a team?

### ISSUE THREAD

**Issue by ntlm1686** [wandb/wandb#5919]
Can I use a token for personal projects and another token for team projects?

**Comment by thanos-wandb** [comment]
Hi @ntlm1686 thanks for writing in! As a user you have an API key (token) but you could select in which entity to log your data. The entity can be either your personal account or the team workspace. You only need to add the entity argument in your code as: `wandb.init(entity="username or team-name"`) accordingly. There is some more information in our [docs page here](https://docs.wandb.ai/guides/technical-faq/admin#what-is-the-difference-between-team-and-entity-as-a-user---what-does-entity-mean-for-me). Would this work for you?

**Comment by thanos-wandb** [comment]
Hi @ntlm1686 just checking in here to see if you've tried the above suggestion and if that would work for you? Thanks!

**Comment by ntlm1686** [comment]
@thanos-wandb  yes, this works, thank you.
