### ISSUE TITLE
Error: You must call wandb.init() before wandb.log()

### ISSUE THREAD

**Issue by h9-tect** [wandb/wandb#5931]
hello I get this error while trying to train a model on colab 
![wb](https://github.com/wandb/wandb/assets/61054665/2c0b8142-6080-44fb-9d3c-1dabcdfc8e73)

**Comment by thanos-wandb** [comment]
Hi @h9-tect thank you for contacting us, and happy to help with this issue. It seems from the error message that you haven't initialized a run before logging your data. Are you using one of our integrations, if so which training framework? Would it be please possible to share a code snippet?

**Comment by h9-tect** [comment]
Thank you so much 
here is what I'm trying to do [Colab](https://colab.research.google.com/drive/1QFqSc13q8MY33OlL1BF0gQgKSfGJ2Le8?usp=sharing)

**Comment by thanos-wandb** [comment]
Thank you @h9-tect for the Colab, that's really helpful. You will need to add the `report_to` argument in your `TrainingArguments` as follows:

```
args = TrainingArguments(
    # other args and kwargs here
    report_to="wandb",  # enable logging to W&B
)
```

Would this work for you? Please also check the documentation for our Hugging Face integration [here](https://docs.wandb.ai/guides/integrations/huggingface).

**Comment by thanos-wandb** [comment]
Hi @h9-tect just checking in here to see if you're still running into this issue after the suggestion above? Thanks!

**Comment by thanos-wandb** [comment]
Hi @h9-tect since we haven't heard back from you, and the above should work for you, I will go ahead and close this ticket for now. If you're still having any issues, please let us know and we will be happy to keep investigating.
