### ISSUE TITLE
Protobuf FatalException with tensorflow-macos and M1 GPU

### ISSUE THREAD

**Issue by NaturalStupldity** [wandb/wandb#5935]
### Bug description

When running latest version (0.15.5) of wandb on macos with Apple M1 chip it cannot work with tensorflow-macos with gpu support. 

I am using python 3.10 with miniconda.
Tensorflow-deps is installed and tensorflow-metal==1.0.0.
When using ```tensorflow-macos==2.10, 2.11, 2.12. 2.13``` (tried all of them) and the protobuf of version that satisfies the [requirements](https://github.com/wandb/wandb/blob/main/requirements.txt) of ```wandb>=3.19.0```  there is an error when using wand library (of ANY version). 

For example, when using ```tensorflow-macos==2.13.0rc1``` (latest) and ```protobuf==4.23.4``` (latest) and ```wandb==0.15.5 (latest)```
there is an error when running tensorflow on gpu:

```shell
2023-07-23 13:34:21.669938: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
[libprotobuf FATAL google/protobuf/message_lite.cc:353] CHECK failed: target + size == res: 
libc++abi: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: target + size == res: 
```

This exception is caused by protobuf, however installing other vesions of it won't help. The same error also goes for ```protobuf==3.20.3``` or later. 

Using older older version of wandb would not help either. The same error is for ```wandb==0.14.0, 0.13.0, 0.12.0``` or older.

### Environment

WandB version:
wandb==0.15.5

OS:
macOS Monterey 12.6.3

Python version:
python 3.10

Versions of relevant libraries:
tensorflow-macos==2.13.0rc1
protobuf==4.23.4

**Comment by sydholl** [comment]
Internal GitHub User commented: 
### Describe the bug

When running latest version (0.15.5) of wandb on macos with Apple M1 chip it cannot work with tensorflow-macos with gpu support. 


I am using python 3.10 with miniconda.
Tensorflow-deps is installed and tensorflow-metal==1.0.0.
When using ```tensorflow-macos==2.10, 2.11, 2.12. 2.13``` (tried all of them) and the protobuf of version that satisfies the [requirements](https://github.com/wandb/wandb/blob/main/requirements.txt) of ```wandb>=3.19.0```  there is an error when using wand library (of ANY version). 

For example, when using ```tensorflow-macos==2.13.0rc1``` (latest) and ```protobuf==4.23.4``` (latest) and ```wandb==0.15.5 (latest)```
there is an error when running tensorflow on gpu:

```shell
2023-07-23 13:34:21.669938: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
[libprotobuf FATAL google/protobuf/message_lite.cc:353] CHECK failed: target + size == res: 
libc++abi: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: target + size == res: 
```

This exception is caused by protobuf, however installing other vesions of it won't help. The same error also goes for ```protobuf==3.20.3``` or later. 

Using older older version of wandb would not help either. The same error is for ```wandb==0.14.0, 0.13.0, 0.12.0``` or older.

### Additional Files

_No response_

### Environment

WandB version:
wandb==0.15.5


OS:
macOS Monterey 12.6.3

Python version:
python 3.10


Versions of relevant libraries:
tensorflow-macos==2.13.0rc1
protobuf==4.23.4

### Additional Context

_No response_

**Comment by rsanandres-wandb** [comment]
Hello! 

Could you share a code snippet of how you are running into this error? I was able to install `tensorflow-macos` and `wandb` as well as was able to import the packages into my script. However, I did not run code so a code snippet of what you are using would be helpful.

**Comment by NaturalStupldity** [comment]
The code actually does not matter. If I do not import ```wandb``` everything works just fine, but adding just  ```import wandb``` (not even using) gives this error. However, if you want to test this here is a code snippet:

```
import tensorflow as tf
import wandb

# Initialize wandb
file_path = "wandb_key.txt"
file = open(file_path, "r")
key = file.read()


wandb.login(key=key)
if not wandb.run:
    wandb.init(project="gpu-test")

# Check if GPU is available
print("Is GPU available:", tf.test.is_gpu_available())

# Generate some dummy data
num_samples = 1000
timesteps = 10
input_dim = 20

x_train = tf.random.normal((num_samples, timesteps, input_dim))
y_train = tf.random.normal((num_samples, 1))

# Build the LSTM model
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(64, input_shape=(timesteps, input_dim)),
    tf.keras.layers.Dense(1)
])

# Compile the model
model.compile(optimizer='adam', loss='mse')

# Log the model architecture
wandb.log({"model_summary": model.summary()})

# Train the model with wandb logging
model.fit(x_train, y_train, epochs=10, batch_size=32, callbacks=[wandb.keras.WandbCallback()])
```

it gives this error:

```
2023-07-25 19:55:15.531987: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2023-07-25 19:55:15.532004: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2023-07-25 19:55:15.532006: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2023-07-25 19:55:15.532063: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:303] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-07-25 19:55:15.532370: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:269] Created TensorFlow device (/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2023-07-25 19:55:15.534171: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:303] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-07-25 19:55:15.534178: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:269] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
Is GPU available: True
Epoch 1/10
2023-07-25 19:55:16.251734: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
[libprotobuf FATAL google/protobuf/message_lite.cc:353] CHECK failed: target + size == res: 
libc++abi: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: target + size == res: 

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by rsanandres-wandb** [comment]
Thanks @NaturalStupldity !

I will make a bug report on this and report this to our SDK team. Thank you brining this to our attention!

**Comment by NaturalStupldity** [comment]
Hello! @dmitryduev, how is it going with this issue? It is kind hard for me to work on projects without even temporary solution. Tell me if there is anything else I can help with

**Comment by NaturalStupldity** [comment]
Hurray! It works now for the latest wandb version!
`wandb==0.15.9` 
`tensorflow-macos==2.13.0`

Thank you very much for fixing this one ;)

**Comment by KonstantinosTsoumas** [comment]
Hello all! I've had the exact same issue. Thanks @NaturalStupidlty for the following reply: 

> Hurray! It works now for the latest wandb version! `wandb==0.15.9` `tensorflow-macos==2.13.0`
> 
> Thank you very much for fixing this one ;)

If anybody is reading this, please check out that you might have installed both 'tensorflow' and 'tensorflow-macos'. Perhaps, both the former and the latter might be of different versions! Be sure to only keep the 'tensorflow-macos'.

Hope this helps :)

**Comment by NaturalStupidlty** [comment]
> Hello all! I've had the exact same issue. Thanks @NaturalStupidlty for the following reply:
> 
> > Hurray! It works now for the latest wandb version! `wandb==0.15.9` `tensorflow-macos==2.13.0`
> > Thank you very much for fixing this one ;)
> 
> If anybody is reading this, please check out that you might have installed both 'tensorflow' and 'tensorflow-macos'. Perhaps, both the former and the latter might be of different versions! Be sure to only keep the 'tensorflow-macos'.
> 
> Hope this helps :)

Actually, the issue was ineed in WandB for me at that time. At least, I have tried a fresh environment and even a fresh conda installation with only tensorflow-macos.

For someone else reading this, note that according to https://www.tensorflow.org/install you can (and should) install tensorflow like this:
```
# NOT tensorflow-macos
pip install tensorflow
```

This works fine for pip > 20.3 and is the way that I do this now even for my conda environmnets

**Comment by vicperotti** [comment]
In my install attempts, the GPU would be recognized:
`[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]`
but Tensorflow could not do calculations.


This installation of Tensorflow worked perfectly on M2 with GPU: (https://developer.apple.com/metal/tensorflow-plugin/)
