### ISSUE TITLE
[Feature]: controllable point thickness in interactive Object3D viewer

### ISSUE THREAD

**Issue by jasonkena** [wandb/wandb#5938]
### Description

Would be great to allow users to dynamically set the point thickness in the visualization to allow object geometries to be visualized better without adding more points.
![image](https://github.com/wandb/wandb/assets/35003073/a61a7791-ff9d-4b60-bf18-9dde4603cae6)

### Suggested Solution

Shift-Scroll or Ctrl-Scroll to change point thickness

**Comment by umakrishnaswamy** [comment]
Hey @jasonkena, thanks for writing in. I made a feature request for this, and if you could include any additional code snippets/context, I would love to include that in the details.

**Comment by jasonkena** [comment]
@umakrishnaswamy sounds good! I'm trying to be able to control the pointSize of the mesh/point cloud interactively. In BabylonJS it would look something like this
[Screencast from 2023-07-25 00-10-59.webm](https://github.com/wandb/wandb/assets/35003073/a4e3e106-01a8-45fb-b63c-aeb528a51b46)

**Comment by umakrishnaswamy** [comment]
@jasonkena Thank you for providing this! I submitted this feature request, and I'll let you know if progress arises.
