### ISSUE TITLE
[Feature]: Choose display of batched video for wandb.Video

### ISSUE THREAD

**Issue by frotaur** [wandb/wandb#5961]
### Description

As of now, wandb.Video can take as a parameter a batch of videos in the for of a numpy array, [B,T,C,H,W].

However, the way the batched video is displayed is unclear. For a batch of 4, it will display in two rows of 2. For a batch of 8, its two rows of 4. For a batch of 10, its two rows of 8, so one row has only 2 videos... 

So my feature request would be for the possibility to specify the number of rows wanted (or columns, equivalently). At the very least, the behavior of how the batch is displayed should be documented, which it isn't right now.

Other than that, no complaints about video logging, works great and easy to use !

### Suggested Solution

For batched inputs in wandb.video, it should be possible to specify the number of rows wanted to display the batch of videos.

### Alternatives

Document in wandb.Video the behavior of how the number of rows is chosen, when the input video is batched of size (B,T,C,H,W).

**Comment by umakrishnaswamy** [comment]
Hey @frotaur, I made this feature request and will update you as any progress arises. I'll close out this issue for now, and will reopen once we make progress on the request.
