### ISSUE TITLE
[App]: `roc_curve` shows "No data available"

### ISSUE THREAD

**Issue by kwsp** [wandb/wandb#5963]
### Current Behavior

Code:

```python3
print(f"{y_true_binary.shape}, {pred.shape}")  # (8046,), (8046, 2)
wandb.log({"roc": wandb.plot.roc_curve(y_true_binary, pred)})
```

"No data available" plot:

![image](https://github.com/wandb/wandb/assets/30088608/73a21d76-e570-4997-843d-1285e25d99f9)

Data instead shows up as a table:

![image](https://github.com/wandb/wandb/assets/30088608/99a8b9b9-7c88-413c-b615-a188da08defd)

### Environment

OS: Ubuntu 22.04

Browsers: Brave

Version: 1.52.129 Chromium: 114.0.5735.198 (Official Build) (64-bit)

**Comment by sydholl** [comment]
Internal GitHub User commented: 
### Current Behavior

Code:

```python3
print(f"{y_true_binary.shape}, {pred.shape}")  # (8046,), (8046, 2)
wandb.log({"roc": wandb.plot.roc_curve(y_true_binary, pred)})
```

"No data available" plot:

![image](https://github.com/wandb/wandb/assets/30088608/73a21d76-e570-4997-843d-1285e25d99f9)

Data instead shows up as a table:

![image](https://github.com/wandb/wandb/assets/30088608/99a8b9b9-7c88-413c-b615-a188da08defd)


### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Screenshots

_No response_

### Environment

OS: Ubuntu 22.04

Browsers: Brave

Version: 1.52.129 Chromium: 114.0.5735.198 (Official Build) (64-bit) 


### Additional Context

_No response_

**Comment by luisbergua** [comment]
Hi @kwsp, thanks for writing in! I just tested on my end with a code like:

```
run = wandb.init(project="test_roc_curve")
y_true_binary = np.random.randint(0, 2, size=8046)
pred = np.random.rand(8046, 2)
run.log({"roc_curve": wandb.plot.roc_curve(y_true_binary, pred)})
run.finish() 
```
Which produces [this](https://wandb.ai/luis_team_test/test_roc_curve/runs/id3d3f0w?workspace=user-luis_bergua) run where the custom charts shows values properly. Would you mind trying this code and also sharing a link to your project so I can take a look at it?

**Comment by kwsp** [comment]
Hi @luisbergua thanks for the response. Your example works fine, and I can reproduce the plot. Seems like your example reproduces the shape of the arrays I passed to `roc_curve` too. Could I share my private project with you without making it public?

**Comment by luisbergua** [comment]
Hi @kwsp, sure! You can share a link and I'll be able to take a look even if the project is private.

**Comment by kwsp** [comment]
@luisbergua Sounds good, here you go: https://wandb.ai/kwsp/OCT_invivo?workspace=user-kwsp

**Comment by luisbergua** [comment]
Hi @kwsp, thanks for sharing this! I took a look, it seems for some reason the Custom Chart isn't recognizing the table and not showing available columns

![image](https://github.com/wandb/wandb/assets/113048227/181615b1-40be-4143-8c86-42d5c2b8edde)

Could you please:
* Test the code I shared and see if it works
* Share a code example to see if you're doing something different when creating the plot

**Comment by luisbergua** [comment]
Hi @kwsp , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
