### ISSUE TITLE
[Q] Ability to create a drop down for field values to filter based off of in HistoryTable with Custom Charts

### ISSUE THREAD

**Issue by snnithya** [wandb/wandb#5965]
Hi, I've been trying to see if it is possible to filter the data displayed in a custom chart based on the value present in a certain column in the historyTable using some kind of dropdown in a query. For example, if I had a historyTable with 'epoch number' as a column and values ranging from 1-10, would it be possible to add a drop down parameter where I could choose the epoch number value to display data from that particular epoch only?

My current solution is to hard code the value (say 'epoch number = 0') in the vega-lite chart definition, something like: `"transform": [
    {
        "filter": {
          "field": "epoch number",
          "equal": 0
      }
]` . However this means I need to create a separate template for each epoch number. I was wondering if this could be interactively controlled as a slider/dropdown in the Query?

### Possible leads (that I don't know how to move forward from):
1. It seems like what I want based on the vega-lite documentation is the ability to define a [parameter](https://vega.github.io/vega-lite/docs/parameter.html). However when I add this to the chart definition on the wandb UI, no data is displayed in the chart. The code snippet goes something like:
`"params": [
    { "name": "epn", "value": 0,
      "bind": {"input": "range", "min": 0, "max": 50, "step": 1} }
  ],
    "transform": [
    {
        "filter": {
          "field": "epoch number",
          "equal":  #"epn"
      }
    },`
2. It seems like this issue #2372  is trying to achieve a similar thing. The issue refers to a 'configurable field' which is what I think I want to achieve. The issue I think is different from this in terms of the fact that the column name remains the same for me. 

Thanks in advance!

**Comment by luisbergua** [comment]
Hi @snnithya, thanks for sharing this! I just tested on my end but it seems that you can only add a slider for the step by going to the "Other Settings" section and enabling the option
<img width="1227" alt="image" src="https://github.com/wandb/wandb/assets/113048227/85c638f1-a103-4f00-bb7f-ae04bd456d8b">
But the bind option doesn't add the slider. Another way to handle this is to add an extra string parameter as a user input such as:
```
{
        "filter": {
          "field": "quantizer",
          "equal": "${string:quantizer_filter}"
      }
    }, 
```
So you can write the desired number without accessing the spec although you need to access the chart settings. Could you please give this a try and see if it would be useful for you?

**Comment by snnithya** [comment]
The string parameter works perfectly! Thanks for your help :)
