### ISSUE TITLE
[CLI]: Not able to log `save_hyperparameters` of type `enum.Enum`

### ISSUE THREAD

**Issue by SarthakJShetty-path** [wandb/wandb#5969]
### Describe the bug

Thank you for developing this tool. It has been super helpful for tracking model training and logging metrics. 

I am running into an issue with `save_hyperparameters()`, when logging hyperparameters of type `enum.Enum`. I am using `WandbLogger()` with PyTorch-Lightning.

Somewhere downstream, I call `self.save_hyperparameters()` to log settings and hyperparameters used during a specific run. When I call this function however, I run into an issue with the JSON serialization. Here is the optimizer class that is being saved:

I have a class of type `enum.Enum` as follows:

```python
class Optimizers(enum.Enum):
    ADAM = torch.optim.Adam
    SGD = torch.optim.SGD
```
Here is the error that I run into:

```shell
    return json.JSONEncoder.default(self, obj)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Optimizers is not JSON serializable
wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.

```
I tried initializing the `Optimizers` class with multiple inheritance, using `str` as the other class. This solves the `JSON` serialization issue, but downstream, the optimizer is called and there the `str` type causes it to fail.

I wanted to know if there was some way to log this `enum` parameter?

Thank you for your time!

### Environment

WandB version: 0.15.7

OS: Ubuntu 20.04

Python version: 3.8.10

Versions of relevant libraries: `torch 1.12.1+cu116`, `pytorch-lightning 1.8.4.post0`

**Comment by ArtsiomWB** [comment]
Hi @SarthakJShetty-path! Thank you for writing in and asking questions!

Unfortunately, there is no way of logging objects that are not JSON serializable. I like your way of turning it into a string, and that should be the workaround, but it does look like it does not work for your workflow.

**Comment by Maxscha** [comment]
I ran into the same issue today, which was surprising cause I only updated a few libraries. Before it was running fine.

I ran some test and figured out that it worked before 0.15.5. The only commit which mentioned changes in JSON-handling was the following: https://github.com/wandb/wandb/commit/c5fe3d56b155655980611d32ef09df35cd336872

**Comment by ArtsiomWB** [comment]
Hi @SarthakJShetty-path! Did Max's work around work for you?

**Comment by SarthakJShetty-path** [comment]
@ArtsiomWB thanks for checking in. I haven't tried this yet, but I will latest by today and update this issue. Thanks!

**Comment by SarthakJShetty-path** [comment]
Quick update: Downgrading to `0.15.4` seemed to solve the problem of saving `enum.Enum` types. Not sure what broke as @Maxscha said. This wasn't a fix per-se, but feel to close the issue. Thanks @ArtsiomWB!

**Comment by ArtsiomWB** [comment]
Thank you so much for the update! This means a lot to us! If you happen to have any more concerns, feel free to write back in or start a new thread.
