### ISSUE TITLE
Parallel sweep

### ISSUE THREAD

**Issue by danmou** [wandb/wandb#597]
* Weights and Biases version: 0.8.12
* Python version: 3.6.9
* Operating System: Debian 10

### Description

I'm running multiple `wandb agent`s in order to parallelize my grid search, and for each of them I have to set `CUDA_VISIBLE_DEVICES` to make them run on different GPUs. It would be really nice if there was a built-in feature to distribute agents over multiple GPUs.

There also seems to be an issue where starting two agents at the same time (e.g. in a script) makes them get the same parameters for the first run. A little delay fixes it though.

**Comment by cvphelps** [comment]
Thanks for reporting these sweeps issues!

**Comment by EdwardBurgin** [comment]
Came with the same question in mind, any update or resolution for us to this?

**Comment by qshzh** [comment]
any update?

**Comment by carloalbertobarbano** [comment]
Same request, this would be very useful

**Comment by RylanSchaeffer** [comment]
Any updates on this feature?

**Comment by vanpelt** [comment]
We isolate experiments at the agent level.  You should be able to achieve this by starting multiple agents on the same machine each with a different CUDA_VISIBLE_DEVICES environment variable.  i.e.

```
CUDA_VISIBLE_DEVICES=0,1 wandb agent XXXX/XXXX/XXX
CUDA_VISIBLE_DEVICES=2,3 wandb agent XXXX/XXXX/XXX
```

Then each agent would only have access to those 2 GPU's.  Another option would be to have your code specify the visible device as a hyper parameter and sweep over it, however this could cause issues where two agents tried to use the same device so may not be worth it.

**Comment by anmolmann** [comment]
Hey everyone, in the past 2 years we've majorly reworked the CLI and UI for Weights & Biases. We're closing issues older than 6 months. Please comment to reopen.

**Comment by Galaxy-Husky** [comment]
> We isolate experiments at the agent level. You should be able to achieve this by starting multiple agents on the same machine each with a different CUDA_VISIBLE_DEVICES environment variable. i.e.
> 
> ```
> CUDA_VISIBLE_DEVICES=0,1 wandb agent XXXX/XXXX/XXX
> CUDA_VISIBLE_DEVICES=2,3 wandb agent XXXX/XXXX/XXX
> ```
> 
> Then each agent would only have access to those 2 GPU's. Another option would be to have your code specify the visible device as a hyper parameter and sweep over it, however this could cause issues where two agents tried to use the same device so may not be worth it.

I created a config yaml including an argument like `device_ids: 0,`, which will be used to set the device.  I use the lightning fabric framework. I want to change the argument to parallelize different runs on diffferent GPUs on the single machine. I have four gpus. When the first four runs are done, the latter agents all try to use the last GPU. Is there any solution? Or is is still recommended to use `CUDA_VISIBLE_DEVICES environment variable`?
