### ISSUE TITLE
[Q] Stable Baselines 3 image logging

### ISSUE THREAD

**Issue by 19kdc3** [wandb/wandb#5971]
Hi,
I'm using stable baselines 3 (SB3) which has an integrated callback function that can be configured to monitor training every step of the agent. I currently have it generating an image array of the environment every step which I want to log in wandb.

I can't find any documentation or examples of logging image arrays to wandb with integration for SB3. I was wondering how this can be achieved. 

Thanks!

**Comment by umakrishnaswamy** [comment]
Hey @19kdc3, we have a wandb <> SB3 integration, and you can find documentation for this [here](https://docs.wandb.ai/guides/integrations/stable-baselines-3#docusaurus_skipToContent_fallback). The workflow is similar to the following:

```
from wandb.integration.sb3 import WandbCallback
model.learn(..., callback=WandbCallback())
```
The W&B SB3 integration uses the logs output from TensorBoard to log your metrics

**Comment by umakrishnaswamy** [comment]
Hi @19kdc3 , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
