### ISSUE TITLE
Website hyperlink doesn't work

### ISSUE THREAD

**Issue by viktor-ktorvi** [wandb/wandb#5976]
In [developer guide](https://docs.wandb.ai/guides) in `Experience W&B in action, [run an example introduction project with Google Colab](http://wandb.me/intro).`. The link loads forever.

**Comment by ArtsiomWB** [comment]
Hi @viktor-ktorvi ! Thank you for writing in once again. What are you seeing on your side when you are trying to load the collab? Any messages in the browser logs? It is loading on my side.

**Comment by viktor-ktorvi** [comment]
<img width="442" alt="image" src="https://github.com/wandb/wandb/assets/69254199/ba382b40-74ac-4efc-9ef4-1fb02b534da0">

Just this forever. Idk about the logs.

**Comment by ArtsiomWB** [comment]
Interesting, could you check if this happens to you in all of your browsers? This does load for us on our side, I have checked internally.

**Comment by viktor-ktorvi** [comment]
Same thing on both Edge and Firefox.

**Comment by nate-wandb** [comment]
Hi @viktor-ktorvi, it is loading for me as well but if you'd like to try downloading the notebook file and run it locally here is the where it is located in our repo: https://github.com/wandb/examples/blob/master/colabs/intro/Intro_to_Weights_%26_Biases.ipynb
