### ISSUE TITLE
[App]: wandb sync does not work

### ISSUE THREAD

**Issue by Guptajakala** [wandb/wandb#5983]
### Current Behavior

When running experiments, wandb will create a folder `wandb/` which stores runs locally. For some reason, some saved files (`wandb.save`) were not synced to the wandb UI. I found they do exist locally under `wandb/{ID}/files/`. When I run the command `wandb sync` in the root folder of my codebase, i.e. `wandb/../`, it outputs:

```
wandb: No runs to be synced.
wandb: NOTE: use wandb sync --clean to delete 3 synced runs from local directory.
```

### Expected Behavior

It should sync all the files

### Environment

OS: Ubuntu 20.04

Browsers: Chrome

Version: 0.15.7

**Comment by Guptajakala** [comment]
to be clear, the run is already in online mode. The charts/plots have been synced without issues. But the model weights were logged via `wandb.save`, and they were not uploaded. So I wanted to manually sync them.

**Comment by nate-wandb** [comment]
Hi @Guptajakala, could you possibly post a link to the run and I will take a look? You should be able to resume the run and run `wandb.save` again on the local path to weights but I'm not entirely sure why the file didn't upload the first time. Could you also check debug-internal.log from the local run folder for any errors?

**Comment by nate-wandb** [comment]
Hi @Guptajakala, I just wanted to follow up and see if you were able to get a solution on this or had a chance to try the above?

**Comment by MBakirWB** [comment]
Hi @Guptajakala , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by sydholl** [comment]
Sydney Hollingsworth commented: 
Reported by user: Guptajakala
 GitHub URL: https://github.com/wandb/wandb/issues/5983

**Comment by sydholl** [comment]
Sydney Hollingsworth commented: 
Auto-assigned

**Comment by sydholl** [comment]
Sydney Hollingsworth commented: 
This ticket has gone stale, please follow up or close.

**Comment by sydholl** [comment]
Sydney Hollingsworth commented: 
This ticket has gone stale, please follow up or close.
