### ISSUE TITLE
[Q]wandb import protobuf failed

### ISSUE THREAD

**Issue by dp-0809** [wandb/wandb#5988]
Hi，
I installed the wandb 0.12.21 and protobuf 3.20.1，but the error reported like:
lib/python3.8/site-packages/wandb/sdk/lib/proto_util.py", line 7, in
from wandb.proto import wandb_internal_pb2 as pb
lib/python3.8/site-packages/wandb/proto/wandb_internal_pb2.py", line 5, in
from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google.protobuf'
So, I'm wandering actually the matched wandb and protobuf version is?
Btw, It's the hugging face "accelerate" dependencies need protobuf>=3.19.x

**Comment by umakrishnaswamy** [comment]
Hey @dp-0809, where in your code is this error occurring? Is this upon importing wandb? 

Additionally, I recommend updating to our latest SDK version to experience the best performance and features.

**Comment by dp-0809** [comment]
After I reinstall wandb to the latest patch, it does work, and the error stopped.

**Comment by umakrishnaswamy** [comment]
Great to hear! I'll close out this request for now but feel free to write back in any time!

**Comment by sydholl** [comment]
Sydney Hollingsworth commented: 
Reported by user: dp-0809
 GitHub URL: https://github.com/wandb/wandb/issues/5988

**Comment by sydholl** [comment]
Sydney Hollingsworth commented: 
Auto-assigned

**Comment by sydholl** [comment]
Sydney Hollingsworth commented: 
This ticket has gone stale, please follow up or close.
