### ISSUE TITLE
[CLI]: Api run history not consistent

### ISSUE THREAD

**Issue by sparisi** [wandb/wandb#5994]
### Describe the bug

```python
import wandb
api = wandb.Api()
run = api.run(f'{entity}/{project}/{id}')
print(run.history()['steps'].max())
```

The print show a different history at every call. Examples

```
0           0
1       20100
2       20600
3       22600
4       22800
        ...
495    498400
496    499400
497    499500
498    500000
499    498400
```

```
0       20000
1       21100
2       24200
3       24300
4       24600
        ...
495    495900
496    496000
497    496800
498    497600
499    497800
```

The run is over, so how is this possible? I need to check `run.history()['steps'].max()` but I keep getting a different value every time. 

### Environment

WandB version: 0.15.8

OS: Windows and Linux

Python version: 3.10

**Comment by rsanandres-wandb** [comment]
Hello @sparisi !

A couple things, what is `run.history()['steps']`? Our default metric for step would be `_step` so is `steps` a defined metric? Also, where are these multiple outputs coming from? Are you looping over `print(run.history()['_step'].max())` ? I ran your code and it would only output one value so I am trying to understand how to replicate your noted behavior.

**Comment by sparisi** [comment]
Yes it is a custom metric (it's training steps). 
Multiple outputs are from multiple runs. I launch runs on a cluster and my code checks for existing completed runs (if `steps` >= 1M), but I noticed some inconsistent behavior: sometimes a run was not being resumed, sometimes it was. And it's all because `run.history()['_step'].max()` is never the same.

**Comment by rsanandres-wandb** [comment]
Hello! Could you send me a link to your project so that I can check out why the steps are different? I tested this with various runs on my end and I was getting expected results.

**Comment by sparisi** [comment]
@rsanandres-wandb 

[Link](https://wandb.ai/parisi/accca/runs/eBipedalWalker-v3_s2_ktb0.5_prt0.1_dc0.5_ec2.0_mgn1.0_smFalse_sTrue_gspu10_bnTrue_dTrue). I made it public, let me know if it works or I need to make it open. 

Thanks!

```python
import wandb
api = wandb.Api()
entity = 'parisi'
project = 'accca'
id = 'eBipedalWalker-v3_s2_ktb0.5_prt0.1_dc0.5_ec2.0_mgn1.0_smFalse_sTrue_gspu10_bnTrue_dTrue'
run = api.run(f'{entity}/{project}/{id}')
print(run.history()['steps'].max())
print(run.history()['steps'].max())
print(run.history()['steps'].max())
```

**Comment by rsanandres-wandb** [comment]
Ah, thank you for the code I can see the inconsistent values now. After digging around in our codebase, this is due to the sampling that `run.history()` does ([here](https://docs.wandb.ai/guides/track/public-api-guide?_gl=1*1ssju9s*_ga*OTkwOTU4MzQxLjE2NzMyODYzMjk.*_ga_JH1SJHJQXJ*MTY5MjMxMTU1NS4zODYuMS4xNjkyMzE0MTkwLjE0LjAuMA..#sampling)). I would recommend looking into [scan_history()](https://docs.wandb.ai/ref/python/public-api/run#scan_history) instead which will give you all the values.

**Comment by sparisi** [comment]
Great, that works! Thanks!

**Comment by sydholl** [comment]
WandB Internal User commented: 
rsanandres-wandb commented: 
Hello @sparisi !

A couple things, what is `run.history()['steps']`? Our default metric for step would be `_step` so is `steps` a defined metric? Also, where are these multiple outputs coming from? Are you looping over `print(run.history()['_step'].max())` ? I ran your code and it would only output one value so I am trying to understand how to replicate your noted behavior.

**Comment by sydholl** [comment]
WandB Internal User commented: 
sparisi commented: 
Yes it is a custom metric (it's training steps). 
Multiple outputs are from multiple runs. I launch runs on a cluster and my code checks for existing completed runs (if `steps` >= 1M), but I noticed some inconsistent behavior: sometimes a run was not being resumed, sometimes it was. And it's all because `run.history()['_step'].max()` is never the same.

**Comment by sydholl** [comment]
WandB Internal User commented: 
sparisi commented: 
@rsanandres-wandb 

[Link](https://wandb.ai/parisi/accca/runs/eBipedalWalker-v3_s2_ktb0.5_prt0.1_dc0.5_ec2.0_mgn1.0_smFalse_sTrue_gspu10_bnTrue_dTrue). I made it public, let me know if it works or I need to make it open. 

Thanks!

```python
import wandb
api = wandb.Api()
entity = 'parisi'
project = 'accca'
id = 'eBipedalWalker-v3_s2_ktb0.5_prt0.1_dc0.5_ec2.0_mgn1.0_smFalse_sTrue_gspu10_bnTrue_dTrue'
run = api.run(f'{entity}/{project}/{id}')
print(run.history()['steps'].max())
print(run.history()['steps'].max())
print(run.history()['steps'].max())
```

**Comment by sydholl** [comment]
WandB Internal User commented: 
sparisi commented: 
Great, that works! Thanks!
