### ISSUE TITLE
[App]: `wandb.Table` column of `wandb.Image`s not appearing (possible 0.15.8 regression)

### ISSUE THREAD

**Issue by schmidt-ai** [wandb/wandb#5995]
### Current Behavior

When logging a `wandb.Table` that has a column of `wandb.Image`s to a run or artifact, the Web UI omits that column from the table view. This appears to be a regression in `0.15.8`, because tables of this kind created using `<=0.15.7` appear to work as expected.

### Expected Behavior

The image column should appear in the Web UI table view.

### Steps To Reproduce

1. Install `0.15.8`
2. Create a `pandas.DataFrame` containing a column of `wandb.Image`s
3. Construct a `wandb.Table` from the dataframe and log it to a run
4. View the table from the web UI

### Environment

OS: macOS-13.5-arm64-arm-64bit

Browsers: Chrome 115.0.5790.114

Version: 0.15.8

**Comment by rsanandres-wandb** [comment]
Hello @schmidt-ai !

I did some testing and ran the following code:
```

run = wandb.init()

img = wandb.Image('image.jpg')
img2 = wandb.Image('image_2.jpg')
img3 = wandb.Image('image_3.jpg')
my_table = wandb.Table(columns=["a", "b"], data=[[img, img3], [img2, img3]])
run.log({"table_key": my_table})

# Pandas
import pandas as pd
df = pd.DataFrame([[img, img3], [img2, img3]])
pd_table = wandb.Table(columns=["a", "b"], data = df) 
run.log({"pd_table": pd_table})
```

The following screenshot was my result. I made sure I am using `wandb==0.15.8` so this seems to be working unless I am misunderstanding the steps that was taken.

<img width="1798" alt="image" src="https://github.com/wandb/wandb/assets/122482606/43c9a654-846b-4332-8309-71c23811661c">

**Comment by rsanandres-wandb** [comment]
This looks the same on my end. I am getting the same result either way. Perhaps its the `columns=["a", "b"]` that is helping with the rendering?

**Comment by rsanandres-wandb** [comment]
Hello! I went ahead and looked around some more and I am not sure which "table columns" you are referring to in the UI. Are you attempting to visualize the table columns in the runs table?
<img width="1510" alt="image" src="https://github.com/wandb/wandb/assets/122482606/cce7e2d6-4f9c-4038-aa3a-63171271ca0c">

**Comment by rsanandres-wandb** [comment]
Thanks for the update! I will make a bug report on this behavior and let the engineers know about it.
