### ISSUE TITLE
[Q]  W&B job associated with a git repository

### ISSUE THREAD

**Issue by celsofranssa** [wandb/wandb#6003]
could someone explain how to create a W&B job associated with a git repository using Python?
I want to use it to launch on AWS.

**Comment by nate-wandb** [comment]
Hi @celsofranssa, is the code that is calling `wandb.init()` inside of a git repo? The job should be created automatically if so.

**Comment by celsofranssa** [comment]
Actually, I am referring to this code snippet on `wandb/wandb/sdk/launch/create_job.py`:

https://github.com/wandb/wandb/blob/fcce87e36c15aed5daf59ea3cee081665b4ffac6/wandb/sdk/launch/create_job.py#L22-L86

**Comment by MBakirWB** [comment]
Hi @celsofranssa , apologies for the delay on this. 

```
from wandb.sdk.launch.create_job import create_job

create_job(
    path="/Users/mbakir/Desktop/FineTuneOPT/", 
    job_type="code",
    entity="mohammadbakir",
    project="Review Autosuggest",
    name="finetuneopt",
    aliases=["my-job"],
    entrypoint="fine_tune_opt.py"
)
```

Please let me know if you have any questions.

**Comment by sydholl** [comment]
WandB Internal User commented: 
celsofranssa commented: 
Actually, I am referring to this code snippet on `wandb/wandb/sdk/launch/create_job.py`:

https://github.com/wandb/wandb/blob/fcce87e36c15aed5daf59ea3cee081665b4ffac6/wandb/sdk/launch/create_job.py#L22-L86
