### ISSUE TITLE
[Q] How to increase the max trial limit

### ISSUE THREAD

**Issue by Guptajakala** [wandb/wandb#6025]
```
wandb: Network error (ConnectionError), entering retry loop.
wandb: ERROR HTTPSConnectionPool(host='maglev.wandb.io', port=443): Max retries exceeded with url: /graphql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f1fff425610>: Failed to re
solve 'XXX.wandb.io' ([Errno -3] Temporary failure in name resolution)"))
```

In the middle of the training there was network disconnection. After a few hours the network recovered, but wandb has run out of trials. Any way to increase the max trial limit to let it keep trying to connect?

**Comment by umakrishnaswamy** [comment]
Hey @Guptajakala, you can change the environment variable for the HTTP timeout with `export WANDB_HTTP_TIMEOUT=30`  or 60 (our default for wandb.Api() is currently 10 [[here](https://github.com/wandb/wandb/blob/6c7524e215b6d597a4cd27ccd35b0ceaed240917/wandb/apis/public.py#L256C5-L256C44)]). Please let me know if this helps.

**Comment by Guptajakala** [comment]
@umakrishnaswamy Great, is the unit in min?

**Comment by umakrishnaswamy** [comment]
@Guptajakala Unit is in seconds
