### ISSUE TITLE
[CLI]: many of directories like "pymp-k1pb1vuf" appearing on my source folders

### ISSUE THREAD

**Issue by yaroslavvb** [wandb/wandb#6035]
### Describe the bug

I'm launching Nvidia's Nemo [framework](https://github.com/NVIDIA/NeMo) and when I use `exp_manager.create_wandb_logger=True` option, I get a ton of files like "pymp-5e9cg0p6" appearing in my version controlled directories.

I see about 400 such folders after a 16 machine Slurm run....is there some environment variable I can set to disable this?

<img width="1175" alt="Screenshot 2023-08-09 at 9 13 30 PM" src="https://github.com/wandb/wandb/assets/23068/6c82da8e-07d2-43ef-9742-b5a8d59c9a71">

### Environment

WandB version: 0.15.5

OS: Debian 

Python version: 3.9.16

Versions of relevant libraries: Nemo head, July 2023

### Additional Context

One theory of what's happening -- the job gets killed before Wandb has a chance to finish the upload and do the clean-up. The upload could perhaps be slow because job is running in Asia. If the job isn't killed within timeframe, Slurm will mark the whole machine as "bad", which requires manual intervention by a human admin to check that it works and bring back online.

I need to figure out how to specify a different directory for this files, "." is a slow shared NFS, so it's a bad location for these files in a first place (as opposed to, say, /scratch)

**Comment by kptkin** [comment]
Hi @yaroslavvb 
Sorry that you are having an issue with this. 
- For directories that end with `wandb-media` and `wandb-artifacts`: like you correctly pointed out in your assessment these are files that we save in a tmp location before we persist it for your run.  
- We use the `tempfile.TemporaryDirectory` to staged these files, which depends on your system configuration. The temp directory location follows the following order: https://docs.python.org/3/library/tempfile.html#tempfile.gettempdir. 
- I'm guessing either your user doesn't have the proper permissions to the higher priority locations or they are not specified and hence it defaults to the your current working directory. 
- In the short term if you are able to configure your temp direction to a location that is preferable for you this should fix this. - In parallel we are also going to open an issue to allow users to specify custom directory for these temporary files.

**Comment by yaroslavvb** [comment]
So I ran `tempfile.TemporaryDirectory` and it gives `/tmp` which appears to be available. Since I'm running these under Slurm, maybe it's some kind bad interaction. Are there wandb logs I should look at to figure out why it won't write to `/tmp`?

**Comment by ArtsiomWB** [comment]
@yaroslavvb `debug.log` and `debug-internal.log` of a run can give us an idea of what directory we are writing into.
Could you please provide those two files associated with a run where you are running into this concern? These files should be located in the wandb folder relative to your working directory. We could take a peek at it.

**Comment by yaroslavvb** [comment]
@ArtsiomWB I did a `find ../../ -name "*.log"` from the directory I launched the run and do not see `debug*.log`. 

I'm wondering if this is wandb-specific bug or a bad interaction with Nemo. We are doing wandb logging from Nemo, it automatically logs ot wandb, this functionality is enabled using this setting
https://github.com/NVIDIA/NeMo/blob/329629d92a85af3ee56e3f547bfe392a47eb27e6/nemo/utils/exp_manager.py#L145

**Comment by kptkin** [comment]
> @ArtsiomWB I did a `find ../../ -name "*.log"` from the directory I launched the run and do not see `debug*.log`.
> 
> I'm wondering if this is wandb-specific bug or a bad interaction with Nemo. We are doing wandb logging from Nemo, it automatically logs ot wandb, this functionality is enabled using this setting https://github.com/NVIDIA/NeMo/blob/329629d92a85af3ee56e3f547bfe392a47eb27e6/nemo/utils/exp_manager.py#L145

@yaroslavvb thanks for the additional information. 
By default it would be the directory from where you launched your run, but it is configurable. So if your Nemo integration configured it to a different location it will be found there.

Do you have access to the `wandb_logger` from your code? If so we could see all the configurations by accessing the run's `Settings` attribute. 

If you were using `wandb` code directly it would be something like this:
```
# run is the relevant run
print(run.settings) # this will give us all the metadata about the construction of the settings object
print(run.settings.to_dict()) # this will serialize it to dict and we could see the final values
```
The values `log_internal` and `log_user` are the location of the logging directories for the debut logs for this run.

I see that Nemo uses Pytorch-Lightning(PTL) under-the-hood, and to access the run in PTL you would do something like this:
```
# trainer is the PTL trainer and `experiment` would be the `wandb` run
trainer.logger.experiment
```

**Comment by yaroslavvb** [comment]
Ah, that explains it -- it writes into the directory where I launched the run.
This doesn't work for us because "." is 1) under source control 2) slow shared NFS

Wondering if there's a quick way to override it, like using environment variables

-------

Otherwise we have to figure out how to do it through Nemo which goes through PyTorch lightning + Hydra. Putting the details down, because this issue would be encountered by anyone else using Nemo with Wandb

We launch a file like [megatron_retro_pretraining.py](https://github.com/NVIDIA/NeMo/blob/3365cdee45679a3692f61414b5ff3e1c71e95044/examples/nlp/language_modeling/megatron_retro_pretraining.py#L23)

which uses Hydra config like [megatron_retro_finetune_config.yaml](https://github.com/NVIDIA/NeMo/blob/3365cdee45679a3692f61414b5ff3e1c71e95044/examples/nlp/language_modeling/conf/megatron_retro_finetune_config.yaml)

by doing a command like 

```

srun python megatron_retro_pretraining \
--config-path conf \
--config-name megatron_retro_finetune_config \
trainer.num_nodes=$SLURM_JOB_NUM_NODES \
exp_manager.exp_dir=$HOME/exp_manager/retro/$EXP_NAME  \
exp_manager.create_wandb_logger=True
```

**Comment by ArtsiomWB** [comment]
Hi @yaroslavvb! I wanted to follow up on this request and see if you happen to have any follow-up questions, or if Katia was able to answer all of them. 
Cheers!
