### ISSUE TITLE
[CLI]: Error when not using the defined layer in call method in Keras model with WandB integration 

### ISSUE THREAD

**Issue by salmanmohebi** [wandb/wandb#6046]
### Describe the bug

When defining a new Keras model and integrating it with WandB (Weights and Biases), I encountered an error related to a specific layer. The error message I received is as follows:

```shell
File "/miniconda3/envs/tf/lib/python3.9/site-packages/wandb/data_types.py", line 1504, in from_keras
    node = Node.from_keras(layers[i])
  File "/miniconda3/envs/tf/lib/python3.9/site-packages/wandb/data_types.py", line 1731, in from_keras
    node.num_parameters = layer.count_params()
ValueError: You tried to call `count_params` on layer conv1d, but the layer isn't built. You can build it manually via: `conv1d.build(batch_input_shape)`.

```

Steps to Reproduce:

- Define a new Keras model.
- Include a specific layer within the `__init__` method of the model.
- Do not use the aforementioned layer in the `call` method of the model.
- Integrate the Keras model with WandB for tracking.

Expected Behavior:
The model should integrate with WandB without any errors, even if there are layers defined in the `__init__` method that is not used in the `call` method.

Actual Behavior:
The error mentioned above is raised when trying to integrate the Keras model with WandB.

Code Snippet:

```python
import tensorflow as tf
import wandb

class MyModel(tf.keras.Model):
    def __init__(self):
        super(MyModel, self).__init__()
        self.conv1d = tf.keras.layers.Conv1D(64, kernel_size=3, activation='relu')
        # Other layers...

    def call(self, inputs):
        # Only using other layers, not `conv1d`
        return inputs

# WandB initialization
wandb.init(project="my-project", mode='disabled')
config = wandb.config

# Create and integrate the model
model = MyModel()

wandb_callback = wandb.keras.WandbCallback(
    monitor="val_loss", 
    verbose=0, 
    mode="min", 
    save_model=False
)

x_train, y_train = tf.random.uniform([100, 10]), tf.random.uniform([100, 10])
wandb.config.update(config)  # Update config with any hyperparameters
model.compile(optimizer='adam', loss='mse')
model.fit(x_train, y_train, epochs=5, callbacks=[wandb_callback])
wandb.log({"example_metric": 0.85})
wandb.finish()
```
Please let me know if you need any further information or clarification.

### Environment

WandB version: 0.15.8

OS: Ubuntu 22.04

Python version: 3.9.16

Versions of relevant libraries:
TensorFlow Version: [2.12.0]

**Comment by rsanandres-wandb** [comment]
Hello! Thank you for the reproducible code snippet! I was able to reproduce the error. I will reporting this bug to our SDK team for them to take a look at.

**Comment by ayulockin** [comment]
Hey @salmanmohebi this is not a W&B issue. I think your question was resolved in my comment to your SO question [here](https://stackoverflow.com/questions/76884027/error-when-not-using-the-defined-layer-in-call-method-in-keras-model-with-wandb?noredirect=1#comment135541070_76884027). Someone also gave a detailed a answer stating the issue with the model definition.

**Comment by salmanmohebi** [comment]
Hi, @ayulockin I guess if we assume that W&B expects to receive properly built Keras models, you are right and this is not a W&B-specific issue.
Thanks for the comment, I will close the issue.

**Comment by sydholl** [comment]
WandB Internal User commented: 
salmanmohebi commented: 
Hi, @ayulockin I guess if we assume that W&B expects to receive properly built Keras models, you are right and this is not a W&B-specific issue.
Thanks for the comment, I will close the issue.
