### ISSUE TITLE
[Q] Writing an expression on a per group basis?

### ISSUE THREAD

**Issue by StoneT2000** [wandb/wandb#6059]
The expressions are really nice, but I was wondering if I could write one on a per group basis?

E.g. in my use case I'm working in Reinforcement Learning, and I plot the episode returns over the course training. I group by the environment being trained on, and some environments report returns at different scales.

Would it be possible to write an expression for each group/environment to scale them all appropriately? They need different scales each.

Alternatively I could just make 3 separate charts and download them and combine myself.

**Comment by sherlcok314159** [comment]
@nate-wandb I think we should have a feature of writing expressions for a session instead of a single plot. **Sometimes we do not know what to analyze in advance** until something happened. Downloading, computing, and re-uploading seems complicated.
