### ISSUE TITLE
[CLI]: Assertion Error with `run.logged_artifacts()` 

### ISSUE THREAD

**Issue by gsaltintas** [wandb/wandb#6075]
### Describe the bug

Hello,
When I try to access the artifacts of a run via `run.logged_artifacts()` I get the following error with `wandb==0.15.8` but it doesn't happen with older versions, namely 0.15.2 and 0.15.7. The more strange thing is that this happens for a subset of runs, where the only difference is an extra pickled file saved, all other things, number of logged artifacts, etc. are the same.

```python
import wandb
api = wandb.Api()
run = api.run(RUN_ID)
list(run.logged_artifacts())
```

results in the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lib/python3.10/site-packages/wandb/apis/public.py", line 1184, in __len__
    self._load_page()
  File "lib/python3.10/site-packages/wandb/apis/public.py", line 1214, in _load_page
    self.objects.extend(self.convert_objects())
  File "lib/python3.10/site-packages/wandb/apis/public.py", line 4238, in convert_objects
    return [
  File "lib/python3.10/site-packages/wandb/apis/public.py", line 4239, in <listcomp>
    wandb.Artifact._from_attrs(
  File "lib/python3.10/site-packages/wandb/sdk/artifacts/artifact.py", line 317, in _from_attrs
    assert len(version_aliases) == 1
AssertionError
```

### Environment

WandB version: 0.15.8

OS: Linux and MacOS

Python version: 3.10.8/3.10.12

**Comment by meghbhalerao** [comment]
I think I am facing a related issue here - https://github.com/wandb/wandb/issues/6111 - I think it looks like `wandb` is just able to look at the first logged artifact.

**Comment by umakrishnaswamy** [comment]
Hey @gsaltintas, I am trying to reproduce the issue on my end to dig further into it - could you link a specific run & project where this is occurring? Would love to try to replicate this and escalate as a potential bug if so.

**Comment by gsaltintas** [comment]
Hey @umakrishnaswamy , thanks for getting back to me. I can no longer reproduce the issue even with wandb 0.15.8. We can close it.

**Comment by sydholl** [comment]
WandB Internal User commented: 
meghbhalerao commented: 
I think I am facing a related issue here - https://github.com/wandb/wandb/issues/6111 - I think it looks like `wandb` is just able to look at the first logged artifact.

**Comment by Serebryanskiy** [comment]
This bug occurs when you upgrade wandb version and try to use the project created with the previous version of wandb. Recreating the project or using another one solves the problem.
