### ISSUE TITLE
[Q] I hit the Filestream rate limit exceeded

### ISSUE THREAD

**Issue by ashutoshrana171** [wandb/wandb#6084]
Hi Team,
I'm trying to fine tune starcoder from hugging face and I'm getting these errors:
"wandb: 429 encountered (Filestream rate limit exceeded, retrying in 4.4 seconds.), retrying request"

Can anyone help solve this?

`!python finetune/finetune.py \
  --model_path="bigcode/starcoderbase"\
  --dataset_name="dataset"\
  --split="train"\
  --size_valid_set 10000\
  --streaming\
  --seq_length 2048\
  --max_steps 1000\
  --batch_size 1\
  --input_column_name="instruction"\
  --output_column_name="output"\
  --gradient_accumulation_steps 16\
  --learning_rate 1e-4\
  --lr_scheduler_type="cosine"\
  --num_warmup_steps 100\
  --weight_decay 0.05\
  --output_dir="./checkpoints"`

**Comment by umakrishnaswamy** [comment]
Hey @ashutoshrana171, we recently rolled back a change made to rate limiting - are you still encountering these issues?

**Comment by ashutoshrana171** [comment]
Hey @umakrishnaswamy 
I settled for a lighter version of LLM model and did not see any issue.
I'll highlight if I have the same issue with heavier models.

Thanks

**Comment by sydholl** [comment]
Uma Krishnaswamy commented: 
Thanks for letting me know, and please let me know if you encounter this in the future!

**Comment by sydholl** [comment]
WandB Internal User commented: 
umakrishnaswamy commented: 
Hey @ashutoshrana171, we recently rolled back a change made to rate limiting - are you still encountering these issues?

**Comment by sydholl** [comment]
WandB Internal User commented: 
ashutoshrana171 commented: 
Hey @umakrishnaswamy 
I settled for a lighter version of LLM model and did not see any issue.
I'll highlight if I have the same issue with heavier models.

Thanks
