### ISSUE TITLE
[Q] How to use entity instead of username?

### ISSUE THREAD

**Issue by viktor-ktorvi** [wandb/wandb#6089]
Hey, I have the following snippet:

```python
    run_path = "viktor-ktorvi/thesis_proposal/j0omkb2y"
    api = wandb.Api()

    run = api.run(path=run_path)
```

The following warning appears `wandb: WARNING Run.username is deprecated. Please use Run.entity instead.
`

I don't think there's an entity above my project so what should I change to do it right?

Thanks!

**Comment by karan842** [comment]
Hey! Can you please explain this little bit more?

**Comment by viktor-ktorvi** [comment]
Well, that's all the code and I don't want it to throw a warning.

**Comment by umakrishnaswamy** [comment]
Hey @viktor-ktorvi, what SDK version are you on? I was able to successfully run the above chunk of code with a run of my own on version 0.15.8.

**Comment by sydholl** [comment]
Uma Krishnaswamy commented: 
Hi @viktor-ktorvi, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please feel free to write back in!

**Comment by sydholl** [comment]
WandB Internal User commented: 
viktor-ktorvi commented: 
Well, that's all the code and I don't want it to throw a warning.

**Comment by sydholl** [comment]
WandB Internal User commented: 
umakrishnaswamy commented: 
Hey @viktor-ktorvi, what SDK version are you on? I was able to successfully run the above chunk of code with a run of my own on version 0.15.8.
