### ISSUE TITLE
[Q] Is the tracked hour policy changed for personal account? Will our personal account be closed?

### ISSUE THREAD

**Issue by hongbo-miao** [wandb/wandb#6090]
Currently, my "Accounts & Billing" page shows that the tracked hours are unlimited. I have used 427 hours so far from approximately three years ago until today because of the experiments I conducted in my personal [open-source repository](https://github.com/Hongbo-Miao/hongbomiao.com). The computation occurred either on my personal laptop, my personal AWS, or Azure instances used in GitHub Actions. Also, to clarify, as of today, none of the companies I have been or am currently associated with are using W&B.
 
![image](https://github.com/wandb/wandb/assets/3375461/b099ff71-5224-4b13-b4a9-918fb36186ed)

The other two associated accounts are from Stanford University. After completing the Stanford courses, I no longer used those two associated accounts.

![image](https://github.com/wandb/wandb/assets/3375461/4e84f36c-7356-4dd5-8993-10655d249ff4)

Today, I received a message on LinkedIn from a member of the W&B team who mentioned that they are considering closing my account:

![image](https://github.com/wandb/wandb/assets/3375461/154bd7bb-9db5-4ef6-8124-420829db87d5)

I would like to confirm whether the "unlimited" tracked hour policy has been changed for personal accounts.

- Could the team clarify if "excessive" usage (427 hours in 3 years) on a personal account could result in the closure of our account?
- If the tracked hour policy has changed, what is the current limit for a personal account?

Thank you! ☺️

(BTW, I have turned on offline mode for my personal repo https://github.com/hongbo-miao/hongbomiao.com/pull/10481
So from now on, there won't be any activities on my personal W&B account any more.)

**Comment by MBakirWB** [comment]
Hi @hongbo-miao , happy to look into this for you. I checked your account and everything seems to be in order and there is no requirement for you to pay for personal usage as we allow unlimited tracking for personal accounts. I am looking into who might have send that message. Could you please share the profile link of the user that sent this message, send it to mohammad.bakir@wandb.com. Thanks!

**Comment by MBakirWB** [comment]
Hi @hongbo-miao since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by hongbo-miao** [comment]
Got it, thanks @MBakirWB for clarification! ☺️

**Comment by KANGRuipeng** [comment]
![image](https://github.com/wandb/wandb/assets/17191047/2ed6069b-05d1-4428-86d2-d495d4d9f2e4)

@MBakirWB same problem， could you unlock the limit of my personal account?

**Comment by KANGRuipeng** [comment]
@MBakirWB rkangaa is my account
