### ISSUE TITLE
[CLI]: Not able to access stored artifact of type Table although it is seen on the web app

### ISSUE THREAD

**Issue by meghbhalerao** [wandb/wandb#6111]
### Describe the bug

Hey folks, 
I am not able to access an artifact of the type Table in this run - https://wandb.ai/megh-bh/smrai-container-documentation-src/runs/x38cxto0?workspace=user-bhaleraomegh - although I can see the table in the UI. I am not able to access it via the API. The minimal standalone code that can reproduce this issue is give below

```python
import wandb
api = wandb.Api()
run = api.run("megh-bh/smrai-container-documentation-src/x38cxto0")
logged_artifacts = run.logged_artifacts()
artifact = logged_artifacts[0] 
table = artifact.get("sum_table")

# debug try 1
print(artifact.files)
print(f"Length of artifact files is {len(artifact.files())}" )
for file in artifact.files():
    print(file)

# debug try 2
print("Table is", table)
print("Check if table is under json is", artifact.get('sum_table.table.json'))

# debug try 3
d = artifact.__dict__
print("Printing key val pair per line in artifact")
for k, v in d.items():
    print(k, v)
```
 The output of the above code is as follows

```shell
<bound method Artifact.files of <Artifact QXJ0aWZhY3Q6NTQyOTMyMjYy>>
Length of artifact files is 0
Table is None
Check if table is under json is None
Printing key val pair per line in artifact
client <wandb.apis.public.RetryingClient object at 0x7f3784240eb0>
_entity megh-bh
_project smrai-container-documentation-src
_artifact_name plot_local_path:v10
_artifact_collection_name plot_local_path
_attrs {'id': 'QXJ0aWZhY3Q6NTQyOTMyMjYy', 'digest': '64e7c61456b10382e2f3b571ac24b659', 'description': '', 'state': 'COMMITTED', 'size': 0, 'createdAt': '2023-08-16T05:36:15', 'updatedAt': '2023-08-18T04:32:54', 'labels': None, 'metadata': '{"local_file_path": "outputs/2023-08-18-04:07:25.483580/br.py"}', 'fileCount': 0, 'versionIndex': 10, 'aliases': [{'artifactCollectionName': 'plot_local_path', 'alias': 'latest'}, {'artifactCollectionName': 'plot_local_path', 'alias': 'v10'}], 'artifactSequence': {'id': 'QXJ0aWZhY3RDb2xsZWN0aW9uOjg4MzEwMTE5', 'name': 'plot_local_path'}, 'artifactType': {'id': 'QXJ0aWZhY3RUeXBlOjEyMDIzNjU=', 'name': 'path on local machine', 'project': {'name': 'smrai-container-documentation-src', 'entity': {'name': 'megh-bh'}}}, 'commitHash': 'c736d248727e52ae6b38'}
_metadata {'local_file_path': 'outputs/2023-08-18-04:07:25.483580/br.py'}
_description 
_sequence_name plot_local_path
_sequence_version_index 10
_aliases ['latest']
_frozen_aliases ['latest']
_manifest <wandb.sdk.wandb_artifacts.ArtifactManifestV1 object at 0x7f3784242380>
_is_downloaded False
_dependent_artifacts []
_download_roots set()
```
It looks like from the output that for some reason wandb is not able to see the table which is logged. This issue wasn't happening before, but it started recently.

### Environment

WandB version:
0.15.8
OS:
 Debian GNU/Linux 11 (bullseye)

Python version:
Python 3.11.4
Versions of relevant libraries:
pytorch                   2.0.1           py3.11_cuda11.8_cudnn8.7.0_0    pytorch
pytorch-cuda              11.8                 h7e8668a_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
torchaudio                2.0.2               py311_cu118    pytorch
torchtriton               2.0.0                     py311    pytorch
torchvision               0.15.2              py311_cu118    pytorch

### Additional Context

I am able to see the table in the UI - just attaching this here for your reference.
<img width="1367" alt="Screenshot 2023-08-18 at 1 59 45 PM" src="https://github.com/wandb/wandb/assets/33202960/4ea0edd3-a81c-42ea-8100-4d390bf6c20e">

Edit - I am able to access the table of this run - https://wandb.ai/megh-bh/smrai-container-documentation-src/runs/p573idp2/overview?workspace=user-bhaleraomegh using the exact same code, which has a table too saved using the same format.
Here is the code needed in case which was used to save the table as an artifact - 

`wandb.log({'sum_table': wandb.Table(dataframe=pd.DataFrame({"summary_elements": pd.Series(summary_elements)}))}, commit=False)`
`summary_elements` is of the type `List`
Thanks for your time and I look forward to hearing from you!
Megh

**Comment by meghbhalerao** [comment]
Edit - actually never mind, I figured out the issue, I made a silly error from my end. I should be accessing the second logged artifact rather than the first by logged artifacts[1] rather than logged artifacts[1] 

It was working initially since I was logging only 1 artifact, and later in my workflow I started logging another one while keeping the old indexing and hence it was causing an error. But still I was not sure why it was showing table was None instead of throwing an error like Table does not exist or something like that, or maybe this is by wandb design.

**Comment by thanos-wandb** [comment]
Thanks a lot for the update and detailed info here @meghbhalerao and glad that you've resolved this issue! Regarding your question, that's indeed the current design. If the table exists, it would print:
`wandb:   1 of 1 files downloaded.  `
while it returns a `NoneType` for non existing table. If an empty table was logged, it would still download it and had a type `wandb.data_types.Table`.  I will go ahead and close this ticket now but please feel free to reopen it if you had any more questions.
