### ISSUE TITLE
[CLI]: error using wand callbacks with ultralytics and DDP

### ISSUE THREAD

**Issue by geoffrey-g-delhomme** [wandb/wandb#6128]
### Describe the bug

Callback cannot access model from YOLO trainer element resulting in an attribute error.

Code from `wandb.integration.ultralytics.py`:241
```python
self.model = copy.deepcopy(trainer.model).eval().to(self.device) # trainer.model fails
```

AttributeError

### Environment

WandB version:
version 0.15.9
OS:
Ubuntu
Python version:
3.10.12
Versions of relevant libraries:
ultralytics 8.0.146

**Comment by sydholl** [comment]
Internal GitHub User commented: 
### Describe the bug



Callback cannot access model from YOLO trainer element resulting in an attribute error.



Code from `wandb.integration.ultralytics.py`:241
```python
self.model = copy.deepcopy(trainer.model).eval().to(self.device) # trainer.model fails
```


AttributeError


### Additional Files

_No response_

### Environment

WandB version:
version 0.15.9
OS:
Ubuntu
Python version:
3.10.12
Versions of relevant libraries:
ultralytics 8.0.146

### Additional Context

_No response_

**Comment by soumik12345** [comment]
Hi @geoffrey-g-delhomme 
Can you please share some sample code to reproduce the issue?

**Comment by geoffrey-g-delhomme** [comment]
Hi, it is not that obvious as DDP is not stable in ultralytics. I made some local changes I did not had the time to push.
However, I proposed a quick fix that explains one way to manage the issue.

**Comment by soumik12345** [comment]
> I proposed a quick fix that explains one way to manage the issue
Hi @geoffrey-g-delhomme 
Did you mention your fix anywhere? Could you please link it on this thread?

**Comment by geoffrey-g-delhomme** [comment]
https://github.com/wandb/wandb/pull/6129

**Comment by ArtsiomWB** [comment]
Hi @geoffrey-g-delhomme! Thank you for submitting your pr, Could you please follow up with @soumik12345, on the PR page?

**Comment by MBakirWB** [comment]
Hi @geoffrey-g-delhomme , we are marking this closed as the conversation is being continued in the comments of your [PR](https://github.com/wandb/wandb/pull/6129#issuecomment-1692038287). Cheers!

**Comment by sydholl** [comment]
WandB Internal User commented: 
geoffrey-g-delhomme commented: 
Hi, it is not that obvious as DDP is not stable in ultralytics. I made some local changes I did not had the time to push.
However, I proposed a quick fix that explains one way to manage the issue.
