### ISSUE TITLE
[CLI]: ultralytics callback selection mechanism does not work

### ISSUE THREAD

**Issue by geoffrey-g-delhomme** [wandb/wandb#6143]
### Describe the bug

When using the `add_wandb_callback` function, arguments `enable_train_validation_logging`, `enable_validation_logging` and `enable_prediction_logging` are without effect.

Code from `wand.integration.ultralytics.callbacks`:
```python
class WandBUltralyticsCallback:

    # ...

    @property
    def callbacks(self) -> Dict[str, Callable]:
        """Property contains all the relevant callbacks to add to the YOLO model for the Weights & Biases logging."""
        return {
            "on_train_start": self.on_train_start,
            "on_fit_epoch_end": self.on_fit_epoch_end,
            "on_train_end": self.on_train_end,
            "on_val_end": self.on_val_end,
            "on_predict_end": self.on_predict_end,
        }

def add_wandb_callback(
    model: YOLO,
    enable_model_checkpointing: bool = False,
    enable_train_validation_logging: bool = True,
    enable_validation_logging: bool = True,
    enable_prediction_logging: bool = True,
    max_validation_batches: Optional[int] = 1,
    visualize_skeleton: Optional[bool] = True,
):
    # ...
        # ...
        if not enable_train_validation_logging:
            _ = wandb_callback.callbacks.pop("on_fit_epoch_end")
            _ = wandb_callback.callbacks.pop("on_train_end")
        if not enable_validation_logging:
            _ = wandb_callback.callbacks.pop("on_val_end")
        if not enable_prediction_logging:
            _ = wandb_callback.callbacks.pop("on_predict_end")
        for event, callback_fn in wandb_callback.callbacks.items():
            model.add_callback(event, callback_fn)
```
In `add_wandb_callback`, `wandb_callback.callbacks` returns a **copy** of the callbacks dictionary. Thus `pop` is not persistent and finally the callback is registered as model callback.

### Environment

WandB version:
version 0.15.9
OS:
Ubuntu
Python version:
3.10.12
Versions of relevant libraries:
ultralytics 8.0.146

**Comment by umakrishnaswamy** [comment]
Hey @geoffrey-g-delhomme, thank you so much for the PR! Was wondering if you had any follow-up questions to this or if there's anything else I could help you with.

**Comment by sydholl** [comment]
WandB Internal User commented: 
umakrishnaswamy commented: 
Hey @geoffrey-g-delhomme, thank you so much for the PR! Was wondering if you had any follow-up questions to this or if there's anything else I could help you with.
