### ISSUE TITLE
[CLI]: WandbModelCheckpoint broken since wandb-0.15.6

### ISSUE THREAD

**Issue by SiLiKhon** [wandb/wandb#6169]
### Describe the bug

`WandbModelCheckpoint` crashes with `FileNotFoundError` since https://github.com/wandb/wandb/commit/a77f38df43deb7908db1d9d4fb9fcd083111d3ca for the following arguments:
```python
callback = WandbModelCheckpoint(
    filepath=(
        Path("wandb_bug_mwe_out_path") / "{epoch:05d}"
    ).as_posix(),
    save_weights_only=True,
)
```

MRE:
```python
import wandb
from wandb.keras import WandbModelCheckpoint
from pathlib import Path

import tensorflow as tf

wandb.init(project="callback_bug")

model = tf.keras.Sequential([tf.keras.layers.Dense(1)])
model.compile(optimizer="adam", loss="mean_squared_error")

callback = WandbModelCheckpoint(
    filepath=(
        Path("wandb_bug_mwe_out_path") / "{epoch:05d}"
    ).as_posix(),
    save_weights_only=True,
)
model.fit(x=tf.random.normal(shape=(10, 5)), y=tf.random.normal(shape=(10,)), callbacks=[callback])
```

Traceback:
```shell
  File "wandb_bug.py", line 18, in <module>
    model.fit(x=tf.random.normal(shape=(10, 5)), y=tf.random.normal(shape=(10,)), callbacks=[callback])
  File "/home/coder/.local/lib/python3.8/site-packages/wandb/integration/keras/keras.py", line 178, in new_v2
    return old_v2(*args, **kwargs)
  File "/home/coder/.local/lib/python3.8/site-packages/wandb/integration/keras/keras.py", line 178, in new_v2
    return old_v2(*args, **kwargs)
  File "/home/coder/.local/lib/python3.8/site-packages/wandb/integration/keras/keras.py", line 178, in new_v2
    return old_v2(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 67, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/coder/.local/lib/python3.8/site-packages/wandb/integration/keras/callbacks/model_checkpoint.py", line 150, in on_epoch_end
    self._log_ckpt_as_artifact(filepath, aliases=aliases)
  File "/home/coder/.local/lib/python3.8/site-packages/wandb/integration/keras/callbacks/model_checkpoint.py", line 166, in _log_ckpt_as_artifact
    raise FileNotFoundError(f"No such file or directory {filepath}")
FileNotFoundError: No such file or directory wandb_bug_mwe_out_path/00001
```

The reason is that the updated code seems to be not compatible with models saved in TF format (which is a set of files
per checkpoint with the common prefix, rather than a single file or directory).

Tested with TF 2.9.2 and 2.13.0.

### Environment

WandB version: >=0.15.6

OS: Linux

Python version: 3.8.10

Versions of relevant libraries:
tensorflow 2.9.2 or 2.13.0 (or probably any other)

**Comment by nate-wandb** [comment]
Hi @SiLiKhon, thank you for reporting this along with the MRE. I confirmed I see the same thing. I've reported this to our engineering team and can follow up here once we a fix on this.

**Comment by sydholl** [comment]
Sydney Hollingsworth commented: 
Auto-assigned

**Comment by sydholl** [comment]
Sydney Hollingsworth commented: 
This ticket has gone stale, please follow up or close.

**Comment by SiLiKhon** [comment]
Hey! Any update? Unfortunately, I'm forced to use version 0.15.5 because of this.

**Comment by MBakirWB** [comment]
Hi @SiLiKhon , revisiting this thread. This should have been resolved per https://github.com/wandb/wandb/pull/5720. Are you still experiencing issues?

**Comment by SiLiKhon** [comment]
Hi @MBakirWB 

From the looks of the code, this PR seems to be the one that created this issue rather than resolving it.
Just checked with 0.16.3 - the problem is still there.

**Comment by ayulockin** [comment]
Hey @soumik12345 can you take a look at this issue. 

Hey @SiLiKhon can you provide the link to the PR?

**Comment by SiLiKhon** [comment]
Hey @ayulockin 
I was referring to the one that @MBakirWB mentioned (https://github.com/wandb/wandb/pull/5720)

**Comment by sydholl** [comment]
This issue should be resolved, please comment if you're still experiencing issues.
