### ISSUE TITLE
[Q] How to plot gradients like histogram per epoch?

### ISSUE THREAD

**Issue by undercutspiky** [wandb/wandb#6174]
Hi,
Is there a way to plot distributions per epoch? I'd like to have a plot that looks like the plot automatically plotted for gradients. I tried logging histograms per epoch but they all appear in the summary section in the overview page and of course there's no separate plot per epoch.

**Comment by ArtsiomWB** [comment]
Hi, @undercutspiky! Thank you for writing in! Could you send me what you expect the distribution graph to look like? (A picture could work). Could you also send me your workspace where you are trying to add this graph?

**Comment by undercutspiky** [comment]
Hi @ArtsiomWB , I would want my histograms to look like the plots that wandb automatically draws for gradients. Something like this:
<img width="450" alt="image" src="https://github.com/wandb/wandb/assets/3168616/ff52224e-e5cf-47aa-ae44-56f87fa48fb9">
My workspace is `user-dhananjt` and I'm trying to add the graph to my latest runs (I've only 1 project on wandb so far) in the dashboard to the `charts` section.

**Comment by ArtsiomWB** [comment]
Thank you for explaining your use case!

In your case, we would recommend using a custom chart. Our [custom charts](https://docs.wandb.ai/guides/app/features/custom-charts?_gl=1*1y6grtj*_ga*OTM0MTg1MDQ2LjE2NjM2MTQ0ODk.*_ga_JH1SJHJQXJ*MTY5MzQxMDYwNC45NzguMS4xNjkzNDExNTY0LjYwLjAuMA..) are based on VegaLite. [Here are Vega's examples on histograms](https://vega.github.io/vega-lite/examples/histogram.html).

<img width="604" alt="Screenshot 2023-08-30 at 10 03 59 AM" src="https://github.com/wandb/wandb/assets/115654725/7d8d0b82-6b26-467c-9c71-9d9656e73f68">

**Comment by undercutspiky** [comment]
Hi, I couldn't find a way to do it via Vega-lite but I noticed that the kind of histograms I was expecting are there but they are just not shown in main workspace where the charts are. I can see them in the charts section for an individual run though. But I guess it's probably because it's not obvious how to show histograms for different runs on the same chart. But thanks for all the help.

**Comment by sydholl** [comment]
WandB Internal User commented: 
undercutspiky commented: 
Hi @ArtsiomWB , I would want my histograms to look like the plots that wandb automatically draws for gradients. Something like this:
<img width="450" alt="image" src="https://github.com/wandb/wandb/assets/3168616/ff52224e-e5cf-47aa-ae44-56f87fa48fb9">
My workspace is `user-dhananjt` and I'm trying to add the graph to my latest runs (I've only 1 project on wandb so far) in the dashboard to the `charts` section.
