### ISSUE TITLE
[Q] How to access remote reference uri of an artifact without starting a new run

### ISSUE THREAD

**Issue by adizhol-gp** [wandb/wandb#6185]
I have an external tracked artifact with the ref stored in s3.
I want to either download it or access it's path value.
All the tutorials show an example of starting a new wandb run to download the artifact, but I don't want this run to be logged at all.

**Comment by adizhol-gp** [comment]
How would you do this from python?

**Comment by sydholl** [comment]
Sydney Hollingsworth commented: 
Reported by user: adizhol-gp
 GitHub URL: https://github.com/wandb/wandb/issues/6185

**Comment by sydholl** [comment]
Sydney Hollingsworth commented: 
This ticket has gone stale, please follow up or close.

**Comment by sydholl** [comment]
Mohammad Bakir commented: 
**Uma Krishnaswamy**

import wandb
api = wandb.Api()
artifact = api.artifact('entity/project/artifact:alias')
artifact.download()
