### ISSUE TITLE
[Q] how to delete media files?

### ISSUE THREAD

**Issue by adizhol-gp** [wandb/wandb#6197]
how to delete media files from a finished run using the UI?

**Comment by thanos-wandb** [comment]
Hi @adizhol-gp thanks for writing in! You could use our Public API to delete files from a finished run, as in the code snippet below:

```
import wandb
api = wandb.Api()

run = api.run("<entity>/<project>/<run_id>")

extension = ".png"
files = run.files()
for file in files:
    if file.name.endswith(extension):
        file.delete()
```

Would this work for you?

**Comment by adizhol-gp** [comment]
Does this have a CLI option?

**Comment by thanos-wandb** [comment]
Hi @adizhol-gp thanks for confirming this worked to delete the media files. There isn't any CLI alternative for this specific operation. Also, unfortunately for the panels you will have to delete these manually from the project's workspace, or edit them and change the media key to any available (if not all removed). Would this work for you?

**Comment by adizhol-gp** [comment]
@thanos-wandb 
Not really.
But I learned my lesson and I'll create table artifacts with images

**Comment by thanos-wandb** [comment]
Got it, thanks for the prompt response and update! I agree this would be more convenient for your use case. Please feel free to reach out to us again if you had any more questions/issues.

**Comment by orybkin** [comment]
Is it possible to delete folders with this approach? Deleting files one by one is slow.
