### ISSUE TITLE
[App]: Cannot View Media in Dashboard

### ISSUE THREAD

**Issue by schopra8** [wandb/wandb#6200]
### Current Behavior

We have followed the ["Log distributed training experiments guide"](https://docs.wandb.ai/guides/track/log/distributed-training). Specifically method 2 -- where we have N different W&B Runs (one per process) with the same group-id.

We log images from each process/run to W&B. The images appear in the files associated with the run but they do not appear on the "charts" page for the run. And you cannot add an "Image" panel to view these images in the W&B Web UI (see screen shots below).

### Expected Behavior

The logged media should be viewable in the "charts" page for each run.

### Screenshots

**Group of W&B Runs**
![CleanShot 2023-08-30 at 15 43 56](https://github.com/wandb/wandb/assets/12915292/0b36d5db-1545-4cf0-8039-658dd29a7185)

**Files associated with individual run**
![image](https://github.com/wandb/wandb/assets/12915292/b8066daa-a0ec-461c-95b5-38cf0cbd19e9)

**The web interface shows that there are 0 files and 1 subfolder, but when you click on the "media" folder in the web interface, we find several images logged (as expected).**
![image](https://github.com/wandb/wandb/assets/12915292/5350b8d0-730c-4c2b-952f-8082a349715d)

**These images are not viewable on the run's overview and you cannot add an image panel to view them**
![CleanShot 2023-08-30 at 16 03 08](https://github.com/wandb/wandb/assets/12915292/dc2f387a-61be-43db-9ddc-ce6fe8b31e24)

### Environment

OS: Ubuntu 20.04

Browsers: Chrome OS

Version: 0.15.9

**Comment by umakrishnaswamy** [comment]
Hey @schopra8, sorry to hear you're running into this issue. Could you send over a code snippet for how you are logging these images? I want to try reproducing this behavior on my end

**Comment by umakrishnaswamy** [comment]
Hi @schopra8 ,

We wanted to follow up with you regarding your issue about not being able to view logged media. Please let us know if we can be of further assistance.

Best,

Uma

**Comment by MBakirWB** [comment]
Hi @schopra8, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by schopra8** [comment]
Hi @MBakirWB and @umakrishnaswamy -- apologies for the delayed response! I didn't notice the Github notification with your responses.

So the problem seems to be rather that it takes a very long time for the other processes to upload their image. If I run evaluation every 50 batches I see the following behavior:

- Eval runs at batch 50 but I can only view images in the dashboard from the main process
- Eval runs at batch 100. Now I can see images in the dashboard for t=50 and 100 for the main process and can see images in the dashboard for t=50 for the other processes. This lag is consistently the size of "1 eval period" and is a bit frustrating -- since that means I have to wait several hours to see an old evaluation dashboard.

To log my images I'm running the following in the latest wandb package:
```
        dist.barrier()
        if dist.get_global_rank() in gpu_to_prompts.keys():
            # Logging Images
            run = self.get_wandb_run()
            img_wandb_log_dict = {
                prompt: [wandb.Image(image) for image in images]
                for prompt, images in prompt_to_images.items()
            }
            run.log(img_wandb_log_dict, step=state.timestamp.batch.value)
```

Any ideas what could be going wrong here?

**Comment by schopra8** [comment]
@MBakirWB @umakrishnaswamy  Seems to be a consistent issue in this other GitHub issue as well. Linking here https://github.com/wandb/wandb/issues/6233 to help with triaging.

**Comment by MBakirWB** [comment]
Hi @schopra8 , appreciate you patience here as we had an issue with github notifications syncing with our tracking system. To debug this furthur, could you provide:
- Link to the workspace(s) or run(s) you are experiencing this behavior with
- Debug.log and Debug-internal.log files in your wandb working directory for the affected runs
- Could you update to our latest sdk version and execute a test run, does this issue persist
- Are you using an integrations in your experiments (e.g PyTorch) and how are you using them in your experiment

**Comment by MBakirWB** [comment]
Hi @schopra8 , following up on my request for info above. Could you please provide the requested information so we can being our investigation. Thanks!

**Comment by schopra8** [comment]
For the link to workspaces/runs/debug logs -- what's the best way to share this securely? Should I shoot you an email? It may contain confidential information ill suited for a Github Issue.

**Comment by schopra8** [comment]
@MBakirWB Hope you're well! Just bumping my last comment about the appropriate way to send over the details

**Comment by MBakirWB** [comment]
Hi @schopra8 , my apologies, will have to keep a closer eye out on replies. Could you please submit the file to support@wandb.com and make "Att: Mohammad, [App]: Cannot View Media in Dashboard Github #6200". Thank you

**Comment by schopra8** [comment]
Will do! Thank you :)
