### ISSUE TITLE
[Q] How to log images without creating a new step

### ISSUE THREAD

**Issue by adizhol-gp** [wandb/wandb#6202]
I'd like to log custom images to use in a report, after the run has finished.
How can I add images and ignore the global step parameter?
OR
How can I overwrite the previously logged images (after I made changes in my code that creates these images)?

Is it possible to log artifacts from a wandb.Image(), and then add it to a report? This will solve all the problems above.

**Comment by luisbergua** [comment]
Hi @adizhol-gp, thanks for writing in! Currently it's not possible to log to an already logged step or to log without increasing the step but. I suggest you to create a [table](https://docs.wandb.ai/guides/tables) and log it as an [artifact](https://docs.wandb.ai/guides/artifacts/construct-an-artifact) using a code like:

```
import wandb
import matplotlib.pyplot as plt
import numpy as np
import tempfile
import os

# Initialize wandb
run = wandb.init(project="log_images_artifact")

# Create a temporary directory to store images
temp_dir = tempfile.mkdtemp()

# Initialize the wandb Table
columns = ["Image"]
wandb_table = wandb.Table(columns=columns)

# Generate 5 random images and save them in a wandb Table
for i in range(1, 6):
    plt.figure()
    x = np.linspace(0, 10, 100)
    y = np.sin(i * x)
    plt.plot(x, y)
    image_path = os.path.join(temp_dir, f"plot_{i}.png")
    plt.savefig(image_path)
    plt.close()
    # Add this image to the wandb Table
    wandb_table.add_data(wandb.Image(image_path))

# Create a wandb Artifact
artifact = wandb.Artifact(
    name="my_plots",
    type="dataset"
)

# Add the table to the artifact
artifact.add(wandb_table, "my_plots_table")

# Log the artifact
run.log_artifact(artifact)

# Close wandb run
run.finish()
```
![image](https://github.com/wandb/wandb/assets/113048227/c899ab91-b9c6-4ee8-8865-11692549fad4)

**Comment by adizhol-gp** [comment]
Ok, thanks.
Do I have to wrap images with a table to log them as artifacts?

**Comment by luisbergua** [comment]
Thanks for your reply @adizhol-gp! Yes that would be the best as logging directly as images will require you to manually access all of them via Weave and concat but if you're okay with this you can also add those like:

```
for i in range(1, 6):
    artifact.add_file(os.path.join(temp_dir, f"plot_{i}.png"), f"plot_{i}.png")
```

![image](https://github.com/wandb/wandb/assets/113048227/4505ad69-48dd-49ea-99fa-dbb6cfd0b945)

**Comment by adizhol-gp** [comment]
How can I add this table to  a report?

**Comment by sydholl** [comment]
Sydney Hollingsworth commented: 
Auto-assigned

**Comment by sydholl** [comment]
Luis Bergua commented: 
Already replied
