### ISSUE TITLE
How to log two different groups of chart seperately?

### ISSUE THREAD

**Issue by ljb121002** [wandb/wandb#6214]
Suppose I have two sets of metrics to track. The first set includes metrics such as accuracy and loss, which need to be logged after every epoch. Additionally, there is a second set of metrics that should be logged after every 100 batches. I want to ensure that each set of metrics is logged independently without affecting the step count of the other. How can I achieve this?

**Comment by nate-wandb** [comment]
Hi @ljb121002, if you track the step yourself and use the step argument in `wandb.log({"my_metric": value}, step=my_step)` you can have control over this. You can log to the same step multiple times but you cannot log to a previous step so as long as the step value is >= to the previous logged step this will work. 

Another option is using the define metric workflow described [here](https://docs.wandb.ai/guides/track/log/log-summary#customize-summary-metrics) to log against a custom x-axis

**Comment by nate-wandb** [comment]
Hi @ljb121002, I just wanted to follow up and see if this answered your question?
