### ISSUE TITLE
[Q] Resume=None isn't overwriting historic data

### ISSUE THREAD

**Issue by bio-mlhui** [wandb/wandb#6216]
Because of some bugs, I re-run a run by passing the same id with resume=None. The logged metrics names are same. But the values does'nt not change.

**Comment by bio-mlhui** [comment]
Thanks for you reply! My use case is: when a run is running, I find some issue in my model design. I stop that run, which is, for example, at step 100. After fixing the issue, I want to re-run that run by calling `wandb.init(id=same id, resume=None, name=name)', i.e. using the same id and wanting to overwrite historic data from step 0. But it turns out that it cannot overwrite historic data from step0 to step100. One way to solve is to use another id and with different name. But what does the "overwrite" mean in the doc of `wandb.init(resume=None)`  **If the new run has the same ID as a previous run, this run overwrites that data**,

**Comment by bio-mlhui** [comment]
Thanks for you reply! My use case is that: when a run is running, i find an issue in my model design. So i stop that run, which is for example at step 100. After fixing the issue, I call `wandb.init(id=same id, resume=None, name=name)` i.e. using the same id and wanting to overwrite data of that run starting from step 0. But it turns out setting `resume=None, id=same id` can not overwrite historic data. So, what is the meaning of **overwrite** in the doc of `wandb.init(resume=None)`: **If the new run has the same ID as a previous run, this run overwrites that data**

**Comment by bio-mlhui** [comment]
Thanks for you reply! My use case is that: when a run is running, i find an issue in my model design. So i stop that run, which is for example at step 100. After fixing the issue, I call `wandb.init(id=same id, resume=None, name=name)` i.e. using the same id and wanting to overwrite data of that run starting from step 0. But it turns out setting `resume=None, id=same id` can not overwrite historic data. One way to solve that is to use the same name but different id. However, I wonder what is the meaning of **overwrite** in the doc of `wandb.init(resume=None)`: **If the new run has the same ID as a previous run, this run overwrites that data**

**Comment by thanos-wandb** [comment]
Hi @bio-mlhui thank you very much for the clarification. Indeed, it is currently not feasible to overwrite historical data that were logged in a previous time step. The reason is that this data is written to immutable Parquet files for efficiency. The 'resume' functionality allows you to return in the same run as previously, but it only enables you to continue from the last step. 

This feature (overwrite previous steps) has been previously requested and logged, and I can +1 that request and add you to the internal ticket if you would like to receive updates on this matter.

**Comment by bio-mlhui** [comment]
Thanks for your reply! I think just appending random identifier to the id and using the same name solves the issue. The doc is a bit confusing though.

**Comment by bio-mlhui** [comment]
Thanks for your reply! I think just appending random identifier to the id and using the same name solves the issue. The doc is a bit confusing though.

**Comment by thanos-wandb** [comment]
Hi @bio-mlhui thank you for your feedback. I will file a Docs update request with the team, as I agree it would help our users to document this. Feel free to reach out if you had any other questions/issues!
