### ISSUE TITLE
[CLI]: ImportError: cannot import name 'YOLO' from 'ultralytics.yolo.engine.model' in wandb==0.15.9

### ISSUE THREAD

**Issue by sung0471** [wandb/wandb#6220]
### Describe the bug

I cannot use wandb because of below issue

"ImportError: cannot import name 'YOLO' from 'ultralytics.yolo.engine.model'"

```python
# "train.py"
from wandb.integration.yolov8 import add_callbacks as add_wandb_callbacks
```

```shell
$ torchrun --nproc_per_node 2 --master_port 9527 train.py ...

Traceback (most recent call last):
  File "C:\<mydirectory>\train.py", line 64, in <module>
    from wandb.integration.yolov8 import add_callbacks as add_wandb_callbacks
  File "C:\<myhome>\.conda\envs\yolov8\lib\site-packages\wandb\integration\yolov8\__init__.py", line 7, in <module>
    from .yolov8 import add_callbacks
  File "C:\<myhome>\.conda\envs\yolov8\lib\site-packages\wandb\integration\yolov8\yolov8.py", line 3, in <module>
    from ultralytics.yolo.engine.model import YOLO
ImportError: cannot import name 'YOLO' from 'ultralytics.yolo.engine.model' (C:\<myhome>\.conda\envs\yolov8\lib\site-packages\ultralytics\engine\model.py)
```

### Environment

WandB version: 0.15.9

OS: Windows 10, Ubuntu 20.04

Python version: 3.9

Versions of relevant libraries:

ultralytics: 8.0.170

### Additional Context

GPU : 4090
cuda : 11.8

**Comment by rsanandres-wandb** [comment]
Hello @sung0471 !

I was able to reproduce this behavior on my own machine and it seems that @soumik12345 is aware of this issue so I will make a bug report for thoroughness. Thanks for reporting this!

**Comment by fdsig** [comment]
Dear @sung0471, Thanks again for reporting this issue and for your patience while we fixed it. Happy to update you here that @soumik12345's pr has been merged [here](https://github.com/wandb/wandb/pull/6796) which will enable  ultralytics==8.0.186 to run with WandB -- please also see [documentation](https://docs.wandb.ai/guides/integrations/ultralytics#getting-started).
