### ISSUE TITLE
[CLI]: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended

### ISSUE THREAD

**Issue by carbocation** [wandb/wandb#6227]
### Describe the bug

Using wandb 0.15.9 on python 3.10.12 with torch 2.1.0.dev20230825+cu118, I get the following notice. (It's not an exception: the program continues running.)

```python
wandb.init(
    project=f'{PROJECT}',
    sync_tensorboard=True,
    notes=MODEL_PREFIX,
    config={
        'lr': LEARNING_RATE, 
        'model_version': net.VERSION,
    }
)
tbwriter = SummaryWriter(f'runs/{MODEL_PREFIX}') # Must come after wand init

#[training loop]
tbwriter.add_scalar('training_loss', training_loss, epoch)
```

```shell
/opt/conda/lib/python3.10/site-packages/wandb/wandb_torch.py:193: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:83.)
  check = torch.cuda.FloatTensor(1).fill_(0)
```

### Environment

WandB version: 
0.15.9 

OS:
Debian 11

Python version: 
3.10.12

Versions of relevant libraries: 
torch 2.1.0.dev20230825+cu118

**Comment by kptkin** [comment]
@carbocation Thanks for opening the issue, will be fixed for the next release!

**Comment by sydholl** [comment]
WandB Internal User commented: 
kptkin commented: 
@carbocation Thanks for opening the issue, will be fixed for the next release!

**Comment by Hambaobao** [comment]
`UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors.`

I still got the warning with `wandb-0.16.1`.

**Comment by kptkin** [comment]
@Hambaobao could you please provide a small repro. based on the reporting the line that was emitting the warning was removed in `0.15.10`
