### ISSUE TITLE
[App]: chart data is always behind what is logged

### ISSUE THREAD

**Issue by rfernand2** [wandb/wandb#6233]
### Current Behavior

I have a training run that logs data every 2000 steps, starting with 0.  At 2000 steps shown on my local machine console log, the metrics for step=0 show up in the wandb charts for my run.  At 4000 steps, the metrics for step=2000 show up.  The chart data seen for the run on the wandb website seems to always be 1 data point behind what has been logged to wandb.

### Expected Behavior

I expect the metrics logged from my machine to show up on the wandb website charts for my run after a short delay (1-30 secs).  Instead they seem to be delayed until the next logging call (about 40 minutes in my case).

### Environment

OS: Windows 11

Browsers: Chrome

Version:

**Comment by rfernand2** [comment]
Note that the system metrics/charts are up-to-date.  This just applies to my explicitly logged metrics.

**Comment by MBakirWB** [comment]
Hi @rfernand2  , appreciate you patience here as we had an issue with github notifications syncing with our tracking system. To debug this furthur, could you provide:

- Link to the workspace(s) or run(s) you are experiencing this behavior with
- Debug.log and Debug-internal.log files in your wandb working directory for the affected runs
- What current wandb version are you using? 
- If you are not using out latest sdk version, could you update to our latest sdk version and execute a test run, does this issue persist? 
- Are you using an integrations in your experiments (e.g PyTorch) and how are you using them in your experiment
- Aside from the metrics being logged, are you also logging and additional files? If yes what is the frequency of logging of these files 
- If possible, could you provide a toy example we can work with to reproduce this behavior. 
Thanks

**Comment by rfernand2** [comment]
Hi @MBakirWB : I am super busy this week.  I suggest we close this for now, and I'll open another ticket if I run into this again, so I can provide you with necessary info at that time.
