### ISSUE TITLE
[CLI]: The directory set with WANDB_DIR or the dir argument to wandb.init is not honored

### ISSUE THREAD

**Issue by alegonz** [wandb/wandb#6235]
### Describe the bug

The documentation states:

[Environment variables](https://docs.wandb.ai/guides/track/environment-variables):
> WANDB_DIR: Set this to an absolute path to store all generated files here instead of the wandb directory relative to your training script. be sure this directory exists and the user your process runs as can write to it.

[`wandb.init`](https://docs.wandb.ai/ref/python/init):
>  `dir`: (str or pathlib.Path, optional) An absolute path to a directory where metadata will be stored. When you call `download()` on an artifact, this is the directory where downloaded files will be saved. By default, this is the `./wandb` directory.

From the documentation I expect that I could have the run metadata stored directly under a custom directory of my choosing (e.g. `.wandb`). However when I set the `dir` argument (or the `WANDB_DIR` env var) I get the run metadata saved directly under `.wandb/wandb` and not `.wandb`.

Example:

```shell
~$ mkdir /tmp/wandb_test/  # Just a temporary directory for testing purposes
~$ cd /tmp/wandb_test/
~$ mkdir .wandb  # Must create custom directory first because otherwise wandb.init fails
$ python3 -c 'import wandb; wandb.init(dir=".wandb")' # or equivalently set the WANDB_DIR env var
(...redacted...)
wandb: Run data is saved locally in .wandb/.wandb/run-20230906_051447-6oy1f4b2
(...redacted...)
wandb: Find logs at: .wandb/.wandb/run-20230906_051447-6oy1f4b2/logs

~$ tree -a
.
└── .wandb
    └── wandb
        ├── debug-internal.log -> run-20230906_052633-bv3oaoga/logs/debug-internal.log
        ├── debug.log -> run-20230906_052633-bv3oaoga/logs/debug.log
        ├── latest-run -> run-20230906_052633-bv3oaoga
        └── run-20230906_052633-bv3oaoga
            ├── files
            │   ├── config.yaml
            │   ├── requirements.txt
            │   ├── wandb-metadata.json
            │   └── wandb-summary.json
            ├── logs
            │   ├── debug-internal.log
            │   └── debug.log
            ├── run-bv3oaoga.wandb
            └── tmp
                └── code

8 directories, 9 files
```

But I expected this directory hierarchy:
```shell
~ $ tree -a
.
└── .wandb
    ├── debug-internal.log -> run-20230906_052633-bv3oaoga/logs/debug-internal.log
    ├── debug.log -> run-20230906_052633-bv3oaoga/logs/debug.log
    ├── latest-run -> run-20230906_052633-bv3oaoga
    └── run-20230906_052633-bv3oaoga
        ├── files
        │   ├── config.yaml
        │   ├── requirements.txt
        │   ├── wandb-metadata.json
        │   └── wandb-summary.json
        ├── logs
        │   ├── debug-internal.log
        │   └── debug.log
        ├── run-bv3oaoga.wandb
        └── tmp
            └── code
```

That is, the run metadata is saved directly under `.wandb` and not `.wandb/wandb`, similarly to the default behavior of`wandb.init` when it is run without specifying the `dir` parameter (or without setting the `WANDB_DIR` env var).

### Environment

WandB version: 0.15.9

OS: Ubuntu 20.04

Python version: 3.8.10

**Comment by umakrishnaswamy** [comment]
Hey @alegonz, this is expected behavior: we create the wandb directory inside of whichever directory you specify in the `dir` argument of `wandb.init `

We create this wandb directory for every run, and this is where all logs and files are saved. Please let me know if you have any questions about this

**Comment by alegonz** [comment]
@umakrishnaswamy I see. I read again the phrasing in the documentation and realized that I had misunderstood the intended behavior. Sorry for the noise. Thanks!
