### ISSUE TITLE
[App]: Model Registry - GraphQL Error

### ISSUE THREAD

**Issue by peterdavidfagan** [wandb/wandb#6236]
### Current Behavior

The Web App for the model registry fails to load due to a GraphQL error. I suspect this was caused by trying to link a model version more than once. As a result of this error I cannot view our model registry anymore.

![image](https://github.com/wandb/wandb/assets/42982057/f7ced198-afd3-4362-9a47-3b2223eca625)

### Expected Behavior

Model registry accounts for user linking model versions more than once without throwing an error.

### Steps To Reproduce

Attempt to link a model artifact to model registry more than once using the same tag (in my case latest).

### Screenshots

![image](https://github.com/wandb/wandb/assets/42982057/ee1b581a-78d0-4eee-8aa8-462dfcb946b7)

### Environment

OS:

Browsers:

Version:

**Comment by umakrishnaswamy** [comment]
Hey @peterdavidfagan, sorry to hear you're running into this. To help me dig into this further, could you answer the following:
- Did you link the model via the API using `wandb.run.link_artifact` ? Or did you link this model through the UI? 
- Could you send over the console logs associated with this page you're seeing? You can access these by right clicking > Inspect > Console 

Thank you for providing these!

**Comment by peterdavidfagan** [comment]
> Hey @peterdavidfagan, sorry to hear you're running into this. To help me dig into this further, could you answer the following:

Hey @umakrishnaswamy, thanks for the assistance with this.

> Did you link the model via the API using wandb.run.link_artifact ? Or did you link this model through the UI?

I was experimenting with both. I believe the error arose after interacting with the UI though.

> Could you send over the console logs associated with this page you're seeing? You can access these by right clicking > Inspect > Console

Sure please find the logs attached.

[wandb.ai-1694071891930.log](https://github.com/wandb/wandb/files/12545980/wandb.ai-1694071891930.log)

**Comment by umakrishnaswamy** [comment]
Hey @peterdavidfagan, thank you for getting back to me with this info. We are currently digging into this further and have a few follow up questions:

- Were these artifacts that you logged accessible in the ui prior to you linking to the registered model? 
-Any more info about how you logged these artifacts & the steps you took to do so would be very helpful as we continue investigating. 

Thanks again!

**Comment by peterdavidfagan** [comment]
Hey @umakrishnaswamy, no worries happy to help. 

> Were these artifacts that you logged accessible in the ui prior to you linking to the registered model?

Yes to the best of my knowledge they were accessible.

> Any more info about how you logged these artifacts & the steps you took to do so would be very helpful as we continue investigating.

Unfortunately this part is less clear in terms of order of execution. From what I recall, I started by playing with the python API in order to try and link the artifact in my training script. After playing with the API I also attempted to link via the UI as well, when doing so via the UI the first time I performed the link of the artifact, I believe I did so twice. The first time it wasn't clear that the artifact had been linked so I refreshed the page containing the artifact and performed the link a second time, this resulted in the error messages in the console. 

I suspect it relates to how the backend stores the link data, in a short period of time I attempted to link the artifact which may have resulted in a conflict or error?

**Comment by umakrishnaswamy** [comment]
Hey @peterdavidfagan, after investigating, our team was able to find the cause of the issue.

Looking at your data, there is no run attached to the latest version of their source artifact collection (which they also linked to the registered model). To unblock you from using the registry while we get a fix out, could you delete your source artifact `ipab-rad/visual-concept-planner/visual-concept-executor` ?

Until we get a fix out, our advice would be to not choose `Keep the artifacts` while deleting runs, as that's what caused these crashes. Please let me know how this goes, and I will continue to update you with progress

**Comment by peterdavidfagan** [comment]
> Hey @peterdavidfagan, after investigating, our team was able to find the cause of the issue.

Awesome, and thank you for the quick response.

> Looking at your data, there is no run attached to the latest version of their source artifact collection (which they also linked to the registered model). To unblock you from using the registry while we get a fix out, could you delete your source artifact ipab-rad/visual-concept-planner/visual-concept-executor ?

Confirming we now have access to the model-registry once again.

> Until we get a fix out, our advice would be to not choose Keep the artifacts while deleting runs, as that's what caused these crashes. Please let me know how this goes, and I will continue to update you with progress

Ok this makes sense, thank you for explaining the cause of this error.

**Comment by umakrishnaswamy** [comment]
@peterdavidfagan Great to hear this unblocked you and that you can access the model registry! I will write back in when progress is made on fixing the root cause of the issue, and please let me know if this happens again.

**Comment by umakrishnaswamy** [comment]
Hey @peterdavidfagan, just wanted to let you know a fix has been merged for this, so it should no longer be a problem in the future. Please let me know if you encounter this behavior again!

**Comment by peterdavidfagan** [comment]
Thanks so much @umakrishnaswamy and have a great start to the day.
