### ISSUE TITLE
[Q]How to delete academic team?

### ISSUE THREAD

**Issue by 39c5bb-miku** [wandb/wandb#6237]
I created three academic teams by mistake.Now I want to delete them.

**Comment by 39c5bb-miku** [comment]
@umakrishnaswamy 
My wandb username is  240986800.
The 3 team names are fault--org、fault_detection-org and zph-org.
They're all empty.

**Comment by umakrishnaswamy** [comment]
Hey @39c5bb-miku all these organizations have been deleted. Please let me know if you have any other questions!

**Comment by 39c5bb-miku** [comment]
@umakrishnaswamy 
Thanks.I've seen all the organizations have been deleted.I have another question about when an artifact can be deleted.Displays when I want to delete it“Something went wrong while trying to delete this artifact.”

**Comment by umakrishnaswamy** [comment]
Hey @39c5bb-miku, what kind of artifact are you trying to delete? We do not allow the deleting of any run-<id>-history artifacts, so that could be a potential cause of this error.

**Comment by 39c5bb-miku** [comment]
@umakrishnaswamy
Why the removal of artifacts is not allowed？Sometimes when programs are running and abort after an error is found, artifacts are generated, but these artifacts are empty, which can be very uncomfortable to look at.I want to be allowed the freedom to delete artifacts.

**Comment by umakrishnaswamy** [comment]
Hey @39c5bb-miku, could you send over a workspace or a run page where you are encountering this? I would love to take a closer look on my end.

**Comment by umakrishnaswamy** [comment]
Hi @39c5bb-miku, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
