### ISSUE TITLE
[App]: Data completely dropped from my dashboard?

### ISSUE THREAD

**Issue by gordicaleksa** [wandb/wandb#6269]
### Current Behavior

I'm locally logging using `wandb.log({prefix + key: stats[key].val}, step=step)` but some of these prefix + key data streams is not showing up in my dashboard it seems like it's dropping whole data streams?

### Expected Behavior

I expected to be able to at least find those data streams in my workspace, ideally I'd have them in a  separate panels because I'm using the "/" syntax as part of the prefix above.

### Steps To Reproduce

Go to: https://wandb.ai/gordicaleksa/open-nllb-test2?workspace=user-gordicaleksa

and see that the following data streams are missing: `valid_main:eng_Latn-tur_Latn` and `valid_main:eng_Latn-hin_Deva`

Then go to: https://wandb.ai/gordicaleksa/open-nllb/runs/ikqq9wer?workspace=user-gordicaleksa
and see that those streams are there.

### Environment

OS: Ubuntu 22.04.3 LTS 64 bit

Browsers: Google Chrome 116.0.5845.96 (Official Build) (64-bit) 

Version: 0.15.9

**Comment by gordicaleksa** [comment]
Ok after a long debugging session (which I've been streaming as well see below :)) ) I figured it out.

You're internally [silently incrementing a step counter by +1](https://github.com/wandb/wandb/blob/main/wandb/sdk/wandb_run.py#L1589) in case I don't specify the step myself in the `wandb.log` function.

That causes you to drop the data on my next calls where I specify the old value of the step (and because it's not monotonic you drop that data assuming it's old).

In your defense you do print out warnings which took me a while to figure out what was happening. A better solution IMHO would be to raise an error immediately and expect us to specify the step, otherwise weird bugs such as this one can happen.

You can find my 1.5 hour suffering [here on YouTube](https://www.youtube.com/watch?v=UxOEGLkIUyA&ab_channel=AleksaGordi%C4%87-TheAIEpiphany) :D recorded, first GitHub issue in the history that has a stream attached to it as an evidence.

This is now more of a suggestion than a bug. Feel free to close if "won't fix".

**Comment by nate-wandb** [comment]
Hi @gordicaleksa, I'll pass your feedback onto the engineering team. It may be a matter of clearing up the documentation or adding a more specific warning about the consequences when the step is < the current step. Thank you for raising this!
