### ISSUE TITLE
[Q] How can I log images for a run that has already finished?

### ISSUE THREAD

**Issue by TahaBinhuraib** [wandb/wandb#6277]

**Comment by ArtsiomWB** [comment]
Hi @TahaBinhuraib, a potential solution would be [resuming your run](https://docs.wandb.ai/guides/runs/resuming#docusaurus_skipToContent_fallback) and then [upload your image artifacts ](https://docs.wandb.ai/guides/artifacts#docusaurus_skipToContent_fallback)once the run has been resumed.

**Comment by MBakirWB** [comment]
Hi @TahaBinhuraib, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
