### ISSUE TITLE
[Q] WB Memory Footprint

### ISSUE THREAD

**Issue by shivanimall** [wandb/wandb#6289]
Hello,

wondering how heavy-weight is WB? What is the memory footprint? Have people successfully used it with long-video data?
My jobs are high in memory consumption (due to input data type), and want to avoid OOM issues.

Thank you!

**Comment by MBakirWB** [comment]
Hi @deevanshimall , happy to help. Users have had success with utilizing wandb for various workflows, including the use of long-video data. You wont run into any OOM issue from our backend, but you may run into slight delay in upload times based on how large your file sizes are. We do offer self hosted services which allow you to configure your own infrastructure for your customized workflows,  https://docs.wandb.ai/guides/hosting/hosting-options.  I'd recommend [creating a cloud account](https://wandb.ai/login?signup=true) and trying out some of your experiments. Please let us know if you have any additional questions.

**Comment by MBakirWB** [comment]
Hi @deevanshimall , I am moving forward with closing this out. If you wish to continue the conversation, please let us know.
