### ISSUE TITLE
[Q] Sync model after training

### ISSUE THREAD

**Issue by hdnh2006** [wandb/wandb#6291]
Hello Wandb team,

I was training a YOLOv8 model and wandb crashed because the internet connection failed. So I tried to run `wandb sync` in order to synchronize all the logs but I realized that the best model wasn't synchronized, is there a way to do it after training using your platform?

I know I can register a model in the platform as you carefully explain in this link: https://docs.wandb.ai/guides/models, but I want to do it for the specific run I made, so is there a way to do it?

I would love to have something like this in my logs (example for other training I made):
![image](https://github.com/wandb/wandb/assets/17271049/7fc420f2-543e-4d58-abd0-ee01aea55fa2)

Thanks in advance

**Comment by MBakirWB** [comment]
Hi @hdnh2006 , adding an artifacts after a run completes can be done through various methods. You can use the sdk add an artifact to an existing run, see [here](https://docs.wandb.ai/guides/artifacts/artifacts-faqs#how-do-i-log-an-artifact-to-an-existing-run)

```
with wandb.init(id=<id of run you want to upload to>, project=<project>, resume="allow") as run:
    art = wandb.Artifact(name="artifact-name", type="model")
    art.add_file("path to checkpoint")
    run.log_artifact(art, aliases=["latest", "best"])
```

you can alternatively log artifacts outside run using command line, see [here](https://docs.wandb.ai/guides/artifacts/track-external-files#log-artifacts-outside-of-runs).  

As for the models registry docs you linked above, if you intend to use the registry to keep track of your models, see the "programatic linking" section of this [section](https://docs.wandb.ai/guides/models/walkthrough#3-link-model-versions-to-the-registered-model).

**Comment by MBakirWB** [comment]
Hi @hdnh2006 , following up here. Do you have any further questions prior to us closing this out. Thanks!
