### ISSUE TITLE
[Q] Sweep agent load program script

### ISSUE THREAD

**Issue by 19kdc3** [wandb/wandb#6293]
Hi,
I have a sweep which I'd like to run multiple agents with, each on a separate PC. Is there a way to automatically have the agent PC load a copy of the agent's program script and all other required files?

I'd like to avoid having to manually load the python scripts onto each agent PC and was wondering if wandb has a method of packaging up all required files used to spin-up an agent on another PC.

**Comment by MBakirWB** [comment]
Hi @19kdc3, what would work best for you here is using our launch job feature for sweeps. Each job contains contextual information about the run it is being created from, including the source code, entrypoint, software dependencies, hyperparameters, dataset version, and so on. Please see our [docs here](https://docs.wandb.ai/guides/launch/walkthrough) for how to get started and let us know if you have any questions.

**Comment by MBakirWB** [comment]
Perfect. Thanks for letting me know. Will marked this resolved.
