### ISSUE TITLE
[Q] wandb.init in Jupyter wouldn't sync Tensorboard media unless I manually sync in [CLI] using `wandb sync` 

### ISSUE THREAD

**Issue by mhrahmani** [wandb/wandb#6304]
I'm running a TTS model training similar to: https://github.com/coqui-ai/TTS/blob/dev/recipes/ljspeech/vits_tts/train_vits.py

I added `wandb.init(project="my-project", sync_tensorboard=True)` and the syncing works well, but it only syncs the system performance logs and the Tensorboard tab is there but it's empty. 

If I manually run `wandb sync -p 'project_name' <log_directory>` in the CLI on the side, it syncs everything and the Tensorboard tab is populated as expected. 

Why is that? 
How can I have it automatically sync everything along with the system logs?
How can I log the Tensorboard media when they're not explicitly available as variable in my code to log with `wandb.log()` ? 

Thanks.

**Comment by thanos-wandb** [comment]
Hi @mhrahmani thank you for reporting this issue. Could you please provide us with the following information:
- `debug.log` and `debug-internal.log` files from the run started as `wandb.init(sync_tensorboard=True)`? These files are under your local folder wandb/run-<date>_<time>-<run-id>/logs in the same directory where you’re running your code.
- wandb SDK version (in CLI: `wandb --version`)
- link to your workspace (or project's name if you don't wish to share in public)

**Comment by thanos-wandb** [comment]
Hi @mhrahmani I wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by mhrahmani** [comment]
> Hi @mhrahmani thank you for reporting this issue. Could you please provide us with the following information:
> 
> * `debug.log` and `debug-internal.log` files from the run started as `wandb.init(sync_tensorboard=True)`? These files are under your local folder `wandb/run-<date>_<time>-<run-id>/logs` in the same directory where you’re running your code.
> * wandb SDK version (in CLI: `wandb --version`)
> * link to your workspace (or project's name if you don't wish to share in public)

Sure, here are the logs for a short run: 
[debug.log](https://github.com/wandb/wandb/files/12705112/debug.log)
[debug-internal.log](https://github.com/wandb/wandb/files/12705113/debug-internal.log)

And my wandb version:
`wandb, version 0.15.10`

My workspace is linked as `workspace=user-mhrahmani` , every project there uses pretty much the same code.

Here's the code I'm running. I have tried it locally and on jupyter notebooks (colab, datalore), doesn't make a difference in how wandb syncs the files (only syncs system stats, other files are only synced if I sync the training folder manually)

```
import os
# os.environ["CUDA_VISIBLE_DEVICES"] = "7"

import wandb
from trainer import Trainer, TrainerArgs

from TTS.tts.configs.shared_configs import BaseDatasetConfig , CharactersConfig
from TTS.config.shared_configs import BaseAudioConfig
from TTS.tts.configs.vits_config import VitsConfig
from TTS.tts.datasets import load_tts_samples
from TTS.tts.models.vits import Vits, VitsAudioConfig
from TTS.tts.utils.text.tokenizer import TTSTokenizer
from TTS.utils.audio import AudioProcessor


# # Start a wandb run with `sync_tensorboard=True`
wandb.init(project="persian-tts-vits-espeak", sync_tensorboard=True)

# output_path = os.path.dirname(os.path.abspath(__file__))
# output_path = output_path + '/notebook_files/runs'
output_path = "/data/notebook_files/runs"
dataset_config = BaseDatasetConfig(
    formatter="mozilla", meta_file_train="metadata_cleaned.csv", path="./datasets/my_dataset" 
)


vits_audio_config = VitsAudioConfig(
    sample_rate=22050,
    win_length=1024,
    hop_length=256,
    num_mels=80,
    mel_fmin=0,
    mel_fmax=None
)
config = VitsConfig(
    audio=vits_audio_config, #from huggingface
    run_name="vits_fa_male_espeak",
    batch_size=32,
    batch_group_size=8,
    eval_batch_size=4,
    num_loader_workers=4,
    num_eval_loader_workers=2,
    run_eval=True,
    test_delay_epochs=-1,
    epochs=1000,
    save_step=1000,
    text_cleaner="phoneme_cleaners", #from MH
    use_phonemes=True,
    phonemizer='espeak', #from TTS github
    phoneme_language="en",
    phoneme_cache_path=os.path.join(output_path, "phoneme_cache_espeak"),
    compute_input_seq_cache=True,
    print_step=25,
    print_eval=True,
    mixed_precision=False, #from TTS - True causes error "Expected reduction dim"
    output_path=output_path,
    datasets=[dataset_config],
)

# INITIALIZE THE AUDIO PROCESSOR
# Audio processor is used for feature extraction and audio I/O.
# It mainly serves to the dataloader and the training loggers.
ap = AudioProcessor.init_from_config(config)

# INITIALIZE THE TOKENIZER
# Tokenizer is used to convert text to sequences of token IDs.
# config is updated with the default characters if not defined in the config.
tokenizer, config = TTSTokenizer.init_from_config(config)

# LOAD DATA SAMPLES
# Each sample is a list of ```[text, audio_file_path, speaker_name]```
# You can define your custom sample loader returning the list of samples.
# Or define your custom formatter and pass it to the `load_tts_samples`.
# Check `TTS.tts.datasets.load_tts_samples` for more details.
train_samples, eval_samples = load_tts_samples(
    dataset_config,
    eval_split=True,
    eval_split_max_size=config.eval_split_max_size,
    eval_split_size=config.eval_split_size,
)

# init model
model = Vits(config, ap, tokenizer, speaker_manager=None)

# init the trainer and 🚀

trainer = Trainer(
    TrainerArgs(),
    config,
    output_path,
    model=model,
    train_samples=train_samples,
    eval_samples=eval_samples,
)
trainer.fit()


```

So my guess is that the actual training is done through the `trainer` module on a separate thread. That might be part of the issue. 

It would be nice if there was a way to pass the training stats and data to wandb in the main code above without having to modify the `trainer` module itself.

hope that clarifies. thanks.

**Comment by thanos-wandb** [comment]
Hi @mhrahmani thanks so much for providing such detailed information. Let us please further investigate this issue using the provided code and will keep you updated here with any additional information or updates we discover.

**Comment by thanos-wandb** [comment]
Hi @mhrahmani I have checked the runs in your project `persian-tts-vits-espeak` as in the code example, and I can see the Tensorboard logged fine. Did you sync those manually? is there any project/run at the moment where only system metrics are displayed? 

I also see this error message in the logs that seems to indicate some issue finding the tensorboard directory:

```
2023-09-22 23:21:55,706 DEBUG   Thread-16 (_thread_except_body):1097919 [tb_watcher.py:_process_events():284] Encountered tensorboard directory watcher error: [Errno 38] Function not implemented: '/data/notebook_files/runs/vits_fa_male_espeak_fa_7_audiobook-September-22-2023_07+48PM-0000000/events.out.tfevents.1695424915.28c3e494f06d.1097845.0' -> '/data/notebook_files/wandb/run-20230922_232152-pr66jwvx/files/events.out.tfevents.1695424915.28c3e494f06d.1097845.0'
```

Are you on a Windows machine?

**Comment by mhrahmani** [comment]
Yes I synced them manually. 

Here are logs from a run that I didn't sync manually:
[debug.log](https://github.com/wandb/wandb/files/12776270/debug.log)
[debug-internal.log](https://github.com/wandb/wandb/files/12776271/debug-internal.1.log)


So I believe the issue is with the CoquiTTS Trainer module. There have been other issues:
https://github.com/coqui-ai/Trainer/issues/19
https://github.com/coqui-ai/Trainer/pull/98

Fortunately the Trainer module can be set to use Accelerate instead:
https://github.com/coqui-ai/Trainer#training-with-accelerate

After using Accelerate, I can now see all my training stats and files being updated beautifully on wandb. 

It also seems much more stable, I'd say it should be the default option for running CoquiTTS.

Thanks. 

-MH

**Comment by thanos-wandb** [comment]
Thank you, @mhrahmani, for sharing how you resolved this issue. Glad to hear that it's now resolved for you! I will go ahead and close this ticket, but please don't hesitate to contact us here if you have any other questions or issues.
