### ISSUE TITLE
ultralytics classification images are R/B flipped

### ISSUE THREAD

**Issue by kyle-dorman** [wandb/wandb#6333]
Hi, 

I am using `wandb, version 0.15.10` and see that my images have the B/R channels flipped. I believe ultralytics models use RGB images before they are fed into the transforms. On disk I am 100% sure the images are correct. 

https://github.com/wandb/wandb/blob/75fa6192726090082c8b2af5014502165ca81b83/wandb/integration/ultralytics/classification_utils.py#L20

<img width="478" alt="Screenshot 2023-09-20 at 3 19 12 PM" src="https://github.com/wandb/wandb/assets/2000807/d81aee8c-72f2-4eb6-b0d5-7f15bf41af42">

**Comment by rsanandres-wandb** [comment]
Hello @kyle-dorman!

Thanks for bringing this up! Would you be able to share a link to your project? I want to investigate if this is an App or SDK related problem.

**Comment by kyle-dorman** [comment]
https://wandb.ai/augmodo/classification

thanks I appreciate the help

**Comment by rsanandres-wandb** [comment]
Thank you for sending a link! I will be making a bug report on this for our engineers.

**Comment by kptkin** [comment]
closing as it is fixed by #6382
