### ISSUE TITLE
[App]: No Run Data as Graphs Displaying / Synchronizing  

### ISSUE THREAD

**Issue by carstenstukenborg** [wandb/wandb#6336]
### Current Behavior

From one moment to the next, nothing synchronizes on Weights and Biases. No more run data is displayed as graphs. 

I have tried different axes of the graphs, unfortunately has not changed anything. 

However, it is strange that config data and and the WandB Summary Report are displayed. 

Maybe similar/related issue: https://github.com/wandb/wandb/issues/4844

I have not made any changes in the code that could cause the behavior. I have also started the project from different servers and also locally to rule out connection problems - the problem still occurred. 

I can't explain the behavior at all right now, so I'm creating this issue. 

### Screenshots

![image](https://github.com/wandb/wandb/assets/103239894/09df40ab-ca38-4911-9756-0c5f991cc25c)
![image](https://github.com/wandb/wandb/assets/103239894/e136ea95-e953-4f80-98a3-a2bf652678db)

### Environment

Project: 
Pytorch Ligthning with Wandb Integration 

OS:
Linux

Browsers:
Chrome

Version:
wandb, version 0.15.10

### Additional Context
When I "click around" a bit, sometimes some graphs show up, then they disappear again. See screenshot.
![image](https://github.com/wandb/wandb/assets/103239894/04251374-54ac-4f8a-ac62-3dfe1252f040)
_No response_

**Comment by MaxGonzalezSaez-Diez** [comment]
I am having the same issue

**Comment by rsanandres-wandb** [comment]
Hello @MaxGonzalezSaez-Diez and @carstenstukenborg !

We experienced [Ingestion delay for run metrics](https://status.wandb.com/incidents/8j4yc85wpkjh) this morning and this issue should be resolved now. We are monitoring the backlog for any further issues and you can check the current status of the site [here](https://status.wandb.com/). Please let me know if you are still experiencing this issue and I can investigate.

**Comment by sydholl** [comment]
Raphael San Andres commented: 
Hello! Since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
