### ISSUE TITLE
[App]: Chart shows 'No data for selected run'

### ISSUE THREAD

**Issue by eriknikulski** [wandb/wandb#6337]
### Current Behavior

No data is shown in any charts in the web view for current runs.
This is in contrast to last week, also the old runs still show data as expected.
There haven't been any changes in my code since the last week.

![Screenshot of today's run](https://github.com/wandb/wandb/assets/32927151/abc89988-ef42-495d-9abf-7fff45dcdfb6)

I tried multiple runs, tried changing x-axis from step to wall time etc. and tried multiple browsers, the results are all as shown in the screenshot above.

Locally it looks like usual, the run is initialized, I can log data and get no errors or warnings.
<img width="903" alt="Screenshot 2023-09-21 at 16 12 25" src="https://github.com/wandb/wandb/assets/32927151/59856b0a-f00a-44fc-a8c2-1fae2382a9e7">

I can access the step of the wandb run and log data just fine.
<img width="430" alt="Screenshot 2023-09-21 at 16 12 02" src="https://github.com/wandb/wandb/assets/32927151/7f0d6e7a-f41a-4616-8ee7-a2aee61b5694">

<img width="638" alt="Screenshot 2023-09-21 at 16 12 40" src="https://github.com/wandb/wandb/assets/32927151/49ea77b0-8ca5-4ace-8695-d4da478f63ea">

### Expected Behavior

Show the charts as shown in the screenshot.

![Current screenshot of a run from last week; this looks as usual](https://github.com/wandb/wandb/assets/32927151/87e6b12d-3554-4756-accd-3b9f3b5d4aea)

### Environment

OS: 
Mac OS 13.5.1

Browsers: 
Firefox, Safari and Chrome

Version: 
0.15.10

**Comment by carstenstukenborg** [comment]
Same here. Just opened issue #6336

**Comment by khdlr** [comment]
Same issue here. Interestingly, the logged values appear correctly in the summary table but not in the plots.

**Comment by sydholl** [comment]
WandB Internal User commented: 
carstenstukenborg commented: 
Same here. Just opened issue #6336

**Comment by eliphatfs** [comment]
Same here. An hour ago and the same code was working.

**Comment by eliphatfs** [comment]
Seems either somehow resolved, or the root cause is that there seems to be a long latency of around 10 mins between table and charts so charts are not displayed at beginning of run.

**Comment by sydholl** [comment]
WandB Internal User commented: 
khdlr commented: 
Same issue here. Interestingly, the logged values appear correctly in the summary table but not in the plots.

**Comment by sydholl** [comment]
WandB Internal User commented: 
eliphatfs commented: 
Same here. An hour ago and the same code was working.

**Comment by sydholl** [comment]
WandB Internal User commented: 
eliphatfs commented: 
Seems either somehow resolved, or the root cause is that there seems to be a long latency of around 10 mins between table and charts so charts are not displayed at beginning of run.

**Comment by sydholl** [comment]
WandB Internal User commented: 
maxw1489 commented: 
Same here :/

**Comment by rsanandres-wandb** [comment]
Hello all! 

This morning we experienced a [Ingestion delay for run metrics](https://status.wandb.com/incidents/8j4yc85wpkjh) which caused many runs to have no data. This has been fixed and we appreciate your patience. Feel free to let me know if there are still some outstanding issues. Latency for data showing up in workspaces should be back to normal times.

**Comment by eriknikulski** [comment]
Seems to be working just fine now, so I will close this
