### ISSUE TITLE
[Q] How do I visualize all the tables that I have logged in a single run?

### ISSUE THREAD

**Issue by ATheCoder** [wandb/wandb#6359]
I know it is possible to use `compare` between tables of a single run and view them together. However, it is only possible to view 2 versions of the table together. What if I want to view all the versions of a table logged to the same key and see how a column improves over time?

The **Weave** table also lets you only see a table in the summary of the run, which means you can only view the last version of a table.

**Comment by umakrishnaswamy** [comment]
Hey @ATheCoder - just to make sure I'm understanding correctly, are you looking to compare tables over times/epochs? And would you be doing this via the Weave SDK, the wandb UI, or a Weave board?

**Comment by ATheCoder** [comment]
Correct, I would be doing this via the wandb UI.

**Comment by umakrishnaswamy** [comment]
Hey @ATheCoder - If you go to your run workspace > Add panel > Weave, you can include the expression below to be able to view multiple versions of a table logged in a single run: `runs.history.concat["my_table_name"]` - please let me know if this helps!

**Comment by umakrishnaswamy** [comment]
Hi @ATheCoder, since we have not heard back from you we are going to close this request. Please let me know if the above helped or if you have other questions!
