### ISSUE TITLE
[Q][Bug] Wandb CLI hangs up my job

### ISSUE THREAD

**Issue by shivanimall** [wandb/wandb#6361]
Hello,

I am using wandb for logging various metrics and after a few hours (~5), my job hangs up due to some error on wandb end.
I have been facing this often now. Below is from my wandb debug log `/work/shivanim/vqvae/wandb/debug-cli.shivanim.log` Thank you for your help in advance!

```
2023-09-25 12:47:02 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10
2023-09-25 12:47:02 WARNING Connection pool is full, discarding connection: storage.googleapis.com. Connection pool size: 10```

**Comment by ArtsiomWB** [comment]
Hi @shivanimall! Thank you for writing in! Could you please provide the debug.log and debug-internal.log files associated with the run where you are running into this issue? These files should be located in the wandb folder relative to your working directory.

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by ArtsiomWB** [comment]
Hi, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
