### ISSUE TITLE
[App]: Identical tags appear in different colours

### ISSUE THREAD

**Issue by freddyheppell** [wandb/wandb#6373]
### Current Behavior

Identical tags are assigned different colours in the run view.

### Expected Behavior

One colour is assigned per tag

### Steps To Reproduce

1. Create a number of runs with identical tags
2. Visit the runs table

### Screenshots

<img width="103" alt="image" src="https://github.com/wandb/wandb/assets/1475568/09ec8fe6-8466-4f56-8ed6-30e607ebfcfd">

Note: There are two tags assigned to each of these runs, the first one is sensitive so I don't want to show it - however this is the same tag in all cases.

### Environment

OS: macOS and Ubuntu

Browsers: Chrome

Version: Any

### Additional Context

Tags were logged as hardcoded strings from a Python script, so it's highly unlikely it's a problem on my end. I believe this issue happened a few weeks ago, then went away, but has now come back.

**Comment by umakrishnaswamy** [comment]
Hey @freddyheppell - just to make sure I'm understanding correctly: were you able to see all tags of the same string in the runs table appear in the same color a few weeks ago, then something changed to where the tags appear in different colors now?

**Comment by freddyheppell** [comment]
I might be misremembering but I think previously identical tags were the same colour, then a few weeks ago they started showing as different colours. I was going to report it but then it reverted to showing them as the same colour before I could get round to it. Then, recently, it started happening again.

**Comment by umakrishnaswamy** [comment]
@freddyheppell - I wasn't able to reproduce the issue when adding tags programmatically. Could you run the following code snippet & let me know how this appears on your end? 

```
import wandb 

for i in range(5):
    wandb.init(project='colorTags', tags=['uma'])

    wandb.log({'point': i})

    wandb.finish()
```
Few questions to dig into this further:
- Are you running wandb locally? 
- Are you running into this issue when adding tags via the UI? Or programmatically?

**Comment by umakrishnaswamy** [comment]
hey @freddyheppell, @frederiknolte  - i was able to reproduce this behavior in the UI and have escalated this to our engineering team. will update you as progress arises on the issue, and thanks again for surfacing!

**Comment by collinmccarthy** [comment]
Same issue here, I'm passing in the tags as a list of strings to `wandb.init()`.

**Comment by umakrishnaswamy** [comment]
@collinmccarthy - which wandb SDK version are you using? if you are logging runs to the same project with the same tags across runs (programmatically), they should appear identical in the UI 

could you provide a code snippet for how you're logging these tags? would love to try to investigate this behavior on my end as well

**Comment by doronser** [comment]
I have the same issue. Using WandbLogger along with pytorch-lightning. The code looks something like this:
`logger = WandbLogger(project='mri_uda', group='G', name='N', job_type='train', save_dir=os.environ['HOME'], log_model=True, tags=['my_tag'])
trainer = pl.Trainer(logger=logger)
trainer.fit(model=model, datamodule=data_module, ckpt_path=ckpt_path)`

**Comment by Karol-G** [comment]
Bump. I also have this issue when adding tags programmatically.

**Comment by constanzafierro** [comment]
+1 I added the tags in the UI and I have this issue

**Comment by MaxSchambach** [comment]
Having the same issue using the Python API. It makes tagging much less useful to visually asses different runs in the web UI.

**Comment by frederiknolte** [comment]
Can we expect any patch soon?

**Comment by fmamberti-wandb** [comment]
We are addressing this with high priority however, we currently do not have an ETA for a fix. We appreciate your patience and we will keep you posted with any updates.

**Comment by fmamberti-wandb** [comment]
Hi @freddyheppell @frederiknolte @MaxSchambach @constanzafierro @Karol-G @doronser @collinmccarthy - we have now rolled out a fix for this, and each unique tag will have its own colour in a project 🎉.

We appreciate your patience while we worked on this.
