### ISSUE TITLE
[CLI]: W&B public API - run.used_artifacts() does not return used artifacts for runs outside the artifact's project

### ISSUE THREAD

**Issue by jamiesonor** [wandb/wandb#6376]
### Describe the bug

When using the W&B public API to retrieve the artifacts used by a run, the used artifacts are not returned when the run exists in a different project from the artifact.

Creating the artifact:
```python
project_creation = "artifact_creation"
project_retrieval = "artifact_retrieval"

run = wandb.init(project=project_creation)
artifact = wandb.Artifact("new_artifact", type="dataset")
run.log_artifact(artifact)
wandb.finish()
```

Initializing two runs in different projects, one in the same project as the original artifact, another in a different project.
```python
run_same_project = wandb.init(project="artifact_creation")
run_same_project.use_artifact(project_creation + "/new_artifact:latest")
run_same_project_path = project_creation + "/" + run_same_project.id
wandb.finish()

run_different_project = wandb.init(project=project_retrieval)
run_different_project.use_artifact(project_creation + "/new_artifact:latest")
run_different_project_path = project_retrieval + "/" + run_different_project.id
wandb.finish()
```

Accessing the two runs from the W&B public API:
```python
api = wandb.Api()
run_same = api.run(run_same_project_path)
run_different = api.run(run_different_project_path)
```

The code below runs as expected - the list of used_artifacts contains `new_artifact:latest`:
```python
used_artifacts_same = run_same.used_artifacts()
for artifact in used_artifacts_same:
    print(artifact)
```

However, when the run is in a different project from the used artifact, the used artifact is not returned. `used_artifacts_different` is empty.
```python
used_artifacts_different = run_different.used_artifacts()
for artifact in used_artifacts_different:
    print(artifact)
```

This results in the exception below:
```shell
Traceback (most recent call last):
  File "/Users/jamiesonor/wandb/wandb_artifact_usage.py", line 30, in <module>
    for artifact in used_artifacts_different:
  File "/Users/jamiesonor/opt/anaconda3/envs/venv/lib/python3.10/site-packages/wandb/apis/public.py", line 1233, in __next__
    if not self._load_page():
  File "/Users/jamiesonor/opt/anaconda3/envs/venv/lib/python3.10/site-packages/wandb/apis/public.py", line 1220, in _load_page
    self.objects.extend(self.convert_objects())
  File "/Users/jamiesonor/opt/anaconda3/envs/venv/lib/python3.10/site-packages/wandb/apis/public.py", line 4294, in convert_objects
    return [
  File "/Users/jamiesonor/opt/anaconda3/envs/venv/lib/python3.10/site-packages/wandb/apis/public.py", line 4295, in <listcomp>
    wandb.Artifact._from_attrs(
  File "/Users/jamiesonor/opt/anaconda3/envs/venv/lib/python3.10/site-packages/wandb/sdk/artifacts/artifact.py", line 287, in _from_attrs
    assert len(version_aliases) == 1
AssertionError
```

### Environment

WandB version:
0.15.11

OS:
macOS Ventura 13.5.2

Python version:
3.10.12

**Comment by luisbergua** [comment]
Hi @jamiesonor, thank you so much for sharing such a detailed example! I just checked on my end and reproduced this issue so I'll be raising this as a bug internally and let you know once it's fixed.

**Comment by jamiesonor** [comment]
@luisbergua Are you aware of any workarounds for this issue in the meantime? I have a large number of dataset versions that I'm tracking as artifacts in my workflow, and this was the only method I found to be able to retrieve the specific version of the data used in each of my model training runs. My model training runs and dataset artifacts are unfortunately stored in separate projects. The inability to retrieve used artifacts is a major hindrance to the analysis I'm trying to perform.

**Comment by luisbergua** [comment]
I see, thanks for sharing this context @jamiesonor! One potential workaround is to use a Weave expression on the UI to retrieve those artifacts as you can see in this screenshot. Do you think this would work for you in the meantime?

![image](https://github.com/wandb/wandb/assets/113048227/64fafab7-28fd-439f-9c40-ba4de606ea26)

**Comment by luisbergua** [comment]
Hi @jamiesonor, I wanted to follow up on here! Please let me know if the proposed workaround would be helpful

**Comment by luisbergua** [comment]
I see, thanks for sharing this @jamiesonor! I'll share this with our Engineering Team so they can prioritize this bug and will keep you posted

**Comment by luisbergua** [comment]
Hi @jamiesonor, thanks for your patience! I just wanted to let you know that this bug has been fixed so if you install the latest version of the SDK with `pip install wandb --upgrade` you won't face this error anymore
