### ISSUE TITLE
[Feature]: wandb.Video perform same automatic processing as wandb.Image

### ISSUE THREAD

**Issue by dome272** [wandb/wandb#6381]
### Description

At the moment it can be quite confusing to get errors caused by wandb.Video(*) about datatypes, device, scale etc. when wandb.Image(*) works with the same kind of data, just in image format.

### Suggested Solution

Probably just copy the code from wandb.Image to wandb.Video and adapt it a bit.

**Comment by luisbergua** [comment]
Hi @dome272, thanks for writing in! Just in case this helps, [here](https://docs.wandb.ai/guides/track/log/media#other-media) you have a link to our docs explaining how to log media and also [here](https://docs.wandb.ai/ref/python/data-types/image) is the explanation of `wandb.Image` and [here](https://docs.wandb.ai/ref/python/data-types/video) for `wandb.Video`. Would you mind sharing if you think something is missing in our docs to make this clearer and also provide an examples of types working for images but not for videos so we can improve those? Thanks!

**Comment by luisbergua** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by luisbergua** [comment]
Hi @dome272 , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by dome272** [comment]
Hey sorry for the late reply. I have an example here. In my training I can do the following for images:
`data_image = [[wandb.Image(recon_images[i])] + [wandb.Image(images[i])] for i in range(len(images))]`
This works fine and the Image class automatically casts the images to the required types.
If I try to do the same with videos this doesn't work and results in a bunch of errors, asking me to bring the video to cpu. After solving a few errors, it seemed to be running, but wandb would display an empty column. After asking @tcapelle he told me to scale the video to 0-255. This seems to automatically happen in wandb.Image.
`data_video = [[wandb.Video((recon_videos[i].cpu().float() * 255).numpy().astype("uint8"))] + [wandb.Video((videos[i].cpu().float() * 255).numpy().astype("uint8"))] for i in range(len(videos))]`

It would be cool if the wandb.Video would do the same things automatically.

**Comment by luisbergua** [comment]
Thanks for sharing this example @dome272! I'll create a feature request for this and raise internally

**Comment by luisbergua** [comment]
Hello @dome272, thanks for your patience! We have been discussing this internally and would like to ask if you could provide some more details on your use-case, and problem statement so we can better understand the scope of this. Thanks!
