### ISSUE TITLE
[CLI]: api.report read from project defaults

### ISSUE THREAD

**Issue by minoring** [wandb/wandb#6393]
### Describe the bug

It appears that the methods `api.load_report` or `Report.from_url` are disregarding the entity specified explicitly in the code and are, instead, using the "Project Defaults" entity set in the wandb user profile. For example from the following code, the entity of Runset differ from specified entity.

Moreover, the output of the runset alters when the "Project Defaults" entity is manually adjusted in the user profile.

```python
    # Initialize the Wandb API
    overrides = {
        "entity": <specified-entity>,
        "project": <specified-project>,
    }
    api = wandb.Api(overrides=overrides)

    # Set your entity and project name
    entity = <specified-entity>
    project = <specified-project>
    report_id = <specified-id>

    # Load the report
    report = api.load_report(f"{entity}/{project}/reports/{report_id}")
    all_runs = []

    for block in report.blocks:
        if hasattr(block, "runsets"):
            for runset in block.runsets:
                  # Bug: Here runset's entity is project default
                  import pdb; pdb.set_trace()
                  # p runset
                  # Runset(entity=<project_default_entity> ...)
```

```shell

```

### Environment

WandB version: 0.15.11

OS: Ubuntu 20.04

Python version: 3.8

Versions of relevant libraries:

**Comment by nate-wandb** [comment]
Hi @minoring, working on a reproduction of this and I am running into a different error: `AttributeError: module 'wandb.apis' has no attribute 'reports'`

Does your code snippet work for you currently other than pointing to the incorrect entity?

**Comment by nate-wandb** [comment]
Hi @minoring, I wanted to follow up and see you had a chance to try this again? I think this might have been a recent change but I want to confirm what you are seeing
