### ISSUE TITLE
[Q] :Programmatically download images/other files from a run

### ISSUE THREAD

**Issue by geomlyd** [wandb/wandb#6406]
Hi,
I'm trying to programmatically download an image logged to a run using the information I can obtain for it from the run's history. This does have a field named `path` (something like "media/images/image_0_052c73a2edf79e3c10e2.jpg"), but I can't really see a "nice" way to use this in the (public) API to download it. From what I can see there does exist a[ file class](https://docs.wandb.ai/ref/python/public-api/file), but it's not mentioned anywhere else in the docs. How can I do this, besides digging into the internal API or relying on the URLs shown for the files in my browser?

**Comment by geomlyd** [comment]
Nevermind; as is often the case after searching for this for some time I found it almost immediately after creating the post...

The solution is to access the `file` method of a Run object, and then one can use all methods listed in the FIle page of the docs.

**Comment by thanos-wandb** [comment]
Thank you, @geomlyd, for letting us know how you resolved the issue. We're glad to hear it's been sorted out. If you have any more questions or run into other issues in the future, feel free to reach out to us here. We're here to assist you.
