### ISSUE TITLE
[Q] in wandb launch command, what does dockerfile should be relative to the job's root mean? 

### ISSUE THREAD

**Issue by zhuoqun-chen** [wandb/wandb#6427]
Hi `wandb` developer team,

I'm wondering what does `--dockerfile` Path to the Dockerfile used to build the job, relative to the job's root mean? If I build a job from a dockerfile, where is this root path, and why do I need it? 

Plus, in the `--resource-args` option, there is no further documents specify what keys we should configure, at least there is no example in the official doc.

Thank you for your time!

**Comment by umakrishnaswamy** [comment]
Hey @zhuoqun-chen 

1. This root path is referring to the path of the [launch job](https://docs.wandb.ai/guides/launch/create-launch-job), which can be created via Python file, docker image, or with a git repo.
2. The --resource-args you mentioned are referring to the target resources outlined [here](https://docs.wandb.ai/guides/launch/launch-terminology#target-resources). Depending on your setup, we have examples of configuration parameters within each link.

**Comment by zhuoqun-chen** [comment]
Hi @umakrishnaswamy, Thank you for the reply. I managed to config `resource-args` after some trials and errors. 

But as for the `launch job`, It seems I can not directly create it via `wandb job create [Options] image <dockerhub_repo_rul>:<tag>`, this kept me waiting forever, here is my complete script tries to create it:

```bash
wandb job create \
    --project <my_project> \
    --entity <my_account> \
    --name job-zqc-<my_project_name> \
    --alias <my_alias> \
    --description <my_description> \
    image zqchen33/<my_project_name>:gh-<hash>
```

In my terminal, running this script stuck at `wandb: Creating launch job of type: image...` forever. 
Is there somthing wrong with this sdk via `CLI`.

What I want is create a job first as an entrance but don't launch and en-queue it, and later in my ci, I will launch it by specifing the `--job` and override some arguments. If it's possible?

**Comment by umakrishnaswamy** [comment]
hey @zhuoqun-chen,

Before you run your experiments, it looks like you need to have a job present in the UI first, which is likely why you are running into these issues. 

The error you're seeing `wandb: Creating launch job of type: image...` stems from something blocking the creation of this job - and this could potentially be due to the aforementioned reason. Please let me know if I could help you further with this or if I'm misunderstanding your setup

**Comment by umakrishnaswamy** [comment]
Hi @zhuoqun-chen , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
