### ISSUE TITLE
[App]: wandb launch job shows crash but actually running & run not showing in Run Workspace

### ISSUE THREAD

**Issue by zhuoqun-chen** [wandb/wandb#6433]
### Current Behavior

This bug happens in `wandb launch` workflow, the problem is very similar to https://github.com/wandb/wandb/issues/1526:
+ the run is running and logging but it's status in docker `queue` shows `crashed`
+ the run never shows up in any group in `Runs Workspace` in Web GUI inside the configured project even though the run is still running

I have no idea whether these two are related.

### Expected Behavior

After I created a new launch job via `wandb create job [Options] image <JOB_PATH>`, I don't run it.

Then later on I run it via `wandb launch --job <JOB_PATH> ...`

I expect the run will shows up inside a group and starts to run by a continuously polling launch-agent.

### Steps To Reproduce

1. create a new job via wandb CLI: `wandb create job [Options] image <JOB_PATH>`, at this time, no groups or runs are inside this job
2. starts a launch agent that is configured to watch for the correct launch queue
3. enqueue a launch job via `wandb launch --job <JOB_PATH>`
4. launch agent detects above job and starts to run it
5. the run starts and log metrics and show curves inside a group in my `Runs Workspace`
6. in `Launch -> View Queue` panel, this run's status should also be `Running` and it's under a group and associated with a job in that row.

### Screenshots

![2023-10-09_20-46](https://github.com/wandb/wandb/assets/73287160/b2e6fdd8-5b30-4041-b5be-7fffa68ce691)
![2023-10-09_20-47](https://github.com/wandb/wandb/assets/73287160/c4881517-a08e-47f9-962f-a9652b262b5b)

Notice the filter is configured to show the runs of status `running` already, it is not the filters or the groups problem.

![2023-10-09_20-50](https://github.com/wandb/wandb/assets/73287160/e230ead9-dc11-486a-aede-82277a0a345f)

### Environment

OS: `ubuntu20.04` & `macOS Sonoma 14.0`

Browsers: `chrome` & `safari`

Version: `0.15.12`

**Comment by nate-wandb** [comment]
Hi @zhuoqun-chen, would you mind sharing the name of the project and I'll take a look? If you're uncomfortable sharing here you can email me at Nathan.kuneman@wandb.com

Also, could you elaborate on this: "the run starts and log metrics and show curves inside a group in my Runs Workspace" 
Are you seeing the run in the group? Or does it not exist in the UI at all?

Thank you,
Nate

**Comment by zhuoqun-chen** [comment]
> Hi @zhuoqun-chen, would you mind sharing the name of the project and I'll take a look? If you're uncomfortable sharing here you can email me at [Nathan.kuneman@wandb.com](mailto:Nathan.kuneman@wandb.com)
> 
> Also, could you elaborate on this: "the run starts and log metrics and show curves inside a group in my Runs Workspace" Are you seeing the run in the group? Or does it not exist in the UI at all?
> 
> Thank you, Nate

Sorry, this sentence really is confusing, and it should be put into `Expected behavior` in my original issue post, which means normally I want to see this, but I don't see any run in the group now.

It indeed doesn't exist in the UI at all.

**Comment by anmolmann** [comment]
Hi @zhuoqun-chen , apologies for the delay here. As a follow-up on the [above](https://github.com/wandb/wandb/issues/6433#issuecomment-1757950838) - could you please share the name of the project and I'll take a look? If you're uncomfortable sharing here you can email me at `anmol@wandb.com`.

**Comment by anmolmann** [comment]
Hi @zhuoqun-chen , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
