### ISSUE TITLE
[App]: Error 1054 (42S22): Unknown column 'duration' in 'where clause'

### ISSUE THREAD

**Issue by PaLeroy** [wandb/wandb#6441]
### Current Behavior

When filtering the runs by runtime, selecting all of them and trying to delete all of them, I got this error preventing the deletion. 

### Expected Behavior

No error when deleting a large amount of runs filtered with duration.

### Steps To Reproduce

On the table on my project.
1. Filter runs by runtime >= 10 minutes (and another filter in my case).
2. Select the 20 runs of the table with the "select all" box.
3. Click on the "Select all runs in this project".
4. Click on the trash to delete them and confirm in the appeared box.
5. Bug page appears: 
"Error 1054 (42S22): Unknown column 'duration' in 'where clause'
An application error occurred."

### Screenshots

![Capture d’écran 2023-10-11 à 11 58 35](https://github.com/wandb/wandb/assets/27734041/1566ac41-6889-4c04-a423-1192a5e07526)

### Environment

OS:
macOS Sonoma Version 14.0
Browsers:
Firefox
Version:
118.0.1 (64 bits)

**Comment by Carlo-Argel** [comment]
Hi @PaLeroy 

I just want to update you that we were able to reproduce the issue that you encountered to this [link](https://wandb.ai/wandb-apac/shadow-removal-import-tool/table?workspace=user-carlo-catimbang). We have created a report on this and will keep you posted on any updates.

Regards,
Carlo Argel

**Comment by clsmath** [comment]
This also happens when filtering on any column, say username. In my case it happens even when it is a single run that is selected.

<img width="867" alt="image" src="https://github.com/wandb/wandb/assets/137041250/d969884e-f416-4606-85c9-d45730c07be9">

**Comment by nblauch** [comment]
Same problem for me. Any progress on this @Carlo-Argel or workarounds @PaLeroy ?

**Comment by universome** [comment]
I'm facing the same problem.

**Comment by Carlo-Argel** [comment]
Hi there,

We are currently working on this concern. Rest assured that we'll update this thread once there is a fixed.
