### ISSUE TITLE
Vendor pathtools

### ISSUE THREAD

**Issue by NeilGirdhar** [wandb/wandb#6446]
### Description

Pathtools is [broken on Python 3.12](https://github.com/gorakhargosh/pathtools/issues/13) and appears to be dead (no commits in 7 years).  This break WandB on Python 3.12.

### Suggested Solution

Please consider vendoring it or using pathlib instead.

**Comment by MBakirWB** [comment]
Hi @NeilGirdhar , thank you for writing in. We've received your request and will review and provide an update.

**Comment by danielkelshaw** [comment]
Also came across this issue -- would be grateful for a fix!

**Comment by MBakirWB** [comment]
Hi @NeilGirdhar @danielkelshaw. We will be turning on support for py3.12 sometime in the next week and will be addressing the pathtools component. You can expect this to be released with next SDK version in 2 weeks.

**Comment by NeilGirdhar** [comment]
Looks like this is fixed by #3443
