### ISSUE TITLE
[Q] Changing Team Type from Work to Academic

### ISSUE THREAD

**Issue by yuhsienchiang** [wandb/wandb#6467]
Hello Wandb team,

Is it possible to change the team type from "Work" to "Academic" since I missed that option when creating the team?

**Comment by Carlo-Argel** [comment]
Hi @yuhsienchiang 

Thank you for reaching out. I'll be glad to assist you with this. I'll be checking this and get back to you for updates.

Regards,
Carlo Argel

**Comment by Carlo-Argel** [comment]
Hi @yuhsienchiang 

 Can you provide the following for me please:

- Link to your account
- Link to your current team

Thank you,
Carlo Argel

**Comment by yuhsienchiang** [comment]
Hello @Carlo-Argel,

Thank you for the quick response and your help.
The information you required are listed below.

Link to my account: https://wandb.ai/yuhsien-chiang
Link to my currentteam: https://wandb.ai/supercat

Thank you

**Comment by sydholl** [comment]
WandB Internal User commented: 
Carlo-Argel commented: 
Hi @yuhsienchiang 

Thank you for reaching out. I'll be glad to assist you with this. I'll be checking this and get back to you for updates.

Regards,
Carlo Argel

**Comment by sydholl** [comment]
WandB Internal User commented: 
yuhsienchiang commented: 
Hello @Carlo-Argel,

Thank you for the quick response and your help.
The information you required are listed below.

Link to my account: https://wandb.ai/yuhsien-chiang
Link to my currentteam: https://wandb.ai/supercat

Thank you

**Comment by Carlo-Argel** [comment]
Hi @yuhsienchiang 

Thank you for providing this informations. We'll get back to you for the updates.

Regards,
Carlo Argel

**Comment by MBakirWB** [comment]
Hi @yuhsienchiang , we've update you to an academic org. Marking resolved but please feel free to reopen if you need to.
