### ISSUE TITLE
[Q] pip3.12 install wandb error

### ISSUE THREAD

**Issue by tianshuo78520a** [wandb/wandb#6468]
When I install Wandb on Python 3.12, it will fail. When can I support it.

![image](https://github.com/wandb/wandb/assets/29832297/1848f0d9-7c32-465e-a6e7-04500236bb28)

**Comment by Carlo-Argel** [comment]
Hi @tianshuo78520a ,

Thanks for reaching out. We will be turning on support for py3.12 sometime in the next week and will be addressing the pathtools component. You can expect this to be released with next SDK version in 2 weeks.

Regards,
Carlo Argel

**Comment by tianshuo78520a** [comment]
Hi @Carlo-Argel 

Thank you very much for your reply and we look forward to using it on Python 3.12

Regards,
tian

**Comment by sydholl** [comment]
WandB Internal User commented: 
Carlo-Argel commented: 
Hi @tianshuo78520a ,

Thanks for reaching out. We will be turning on support for py3.12 sometime in the next week and will be addressing the pathtools component. You can expect this to be released with next SDK version in 2 weeks.

Regards,
Carlo Argel

**Comment by sydholl** [comment]
WandB Internal User commented: 
tianshuo78520a commented: 
Hi @Carlo-Argel 

Thank you very much for your reply and we look forward to using it on Python 3.12

Regards,
tian

**Comment by dmitryduev** [comment]
hey @tianshuo78520a, installing wandb from main should now work with 3.12; the fix will be in the release next week.
thanks for raising this!

**Comment by tianshuo78520a** [comment]
Thank you for your help. I will try installing it later。
