### ISSUE TITLE
[App]: Custom chart shows "no data available"

### ISSUE THREAD

**Issue by lucamarini22** [wandb/wandb#6471]
### Current Behavior

Hi, I really like using wandb and I am very grateful for the services you provide!

However, today I encountered a bug:
Similar to #4368, I get the message "No data available." when trying to plot my key "Val mIoU" on the y axis when creating a custom chart on the Web App, as the screenshot below:

![1](https://github.com/wandb/wandb/assets/47863050/591ff3c9-c687-4545-a907-84794f65262b)

I tried this solution (https://community.wandb.ai/t/no-history-data-in-custom-charts/2087/2) and did not work either.
However, I tried the same solution with another key (val_loss) and it worked (see next screenshot). The same is true for other keys that do not contain the space character in their name.

![2](https://github.com/wandb/wandb/assets/47863050/ecca9810-0d79-4d7e-b344-aa089b92cc3e)

I am therefore suspecting that if a key contains the space character in its name the above does not work, because I tried with two keys without the space character and worked, while with other two without the space character did not.

Could you please help me?

### Screenshots

![1](https://github.com/wandb/wandb/assets/47863050/75ef3905-8104-4214-bf7e-88c723edde09)
![2](https://github.com/wandb/wandb/assets/47863050/cd94bd71-1b0e-43a2-8b92-346f26b030c4)

### Environment

OS:

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

Browsers:

- Firefox 118.0.2

Version:
- wandb, version 0.15.12

**Comment by luisbergua** [comment]
Hi @lucamarini22, thanks for reporting this one! I just tested on my end and was able to get custom charts both using metrics with and without spaces (see [here](https://wandb.ai/luis_team_test/custom_charts_no_data?workspace=user-luis_bergua)). Would you mind sharing a link to your Workspace so I can take a look and also a code snippet of how you're logging your metrics so I can reproduce this on my end?

**Comment by lucamarini22** [comment]
@luisbergua thanks for the reply!

Are the following code snippets enough? Or do you also need to know when the following functions are called?

```
wandb.log(
    {
        "Val mIoU": eval["IoU"],
        "Max Val mIou": max_val_miou_among_epochs,
        "epoch_max_val_miou": epoch_max_val_miou
    }
)
```

and in another function:


```
wandb.log(
    {
        "epoch": epoch,
        "train_loss_mean": train_loss,
        "val_loss": val_loss,
        "min_val_loss_among_epochs": min_val_loss_among_epochs,
        "epoch_min_val_loss": epoch_min_val_loss,
        "sup_component_loss": sup_loss,
        "unsup_component_loss": unsup_loss
    }
)
```

and in another function:


```
wandb.log(
    {
        "train_loss": train_loss,
        "step": (epoch - 1) * len_dataloader + idx_dataloader,
    }
)
```

With normal charts I'm able to plot:
1. "step" on the x-axis and "Val mIoU" on the y-axis 
2. but **not** "epoch" on the x-axis and "Val mIoU" on the y-axis 

With custom charts I'm **not** able to plot any of the 2 above.

Is there a way I can share a link to my workspace without putting it as public?

**Comment by luisbergua** [comment]
Hi @lucamarini22, thank you so much for providing this! For now, those snippets are enough, just a quick question, are those variables `float`? About the link, you can share it without making it public and I'll be able to see it

**Comment by lucamarini22** [comment]
Thanks for the reply @luisbergua

- "Val mIoU" is `float`
- "epoch" is `int`
- "step" is `int`

and her's the link to my workspace: 

https://wandb.ai/elmaren/anomaly-marine-detection/sweeps/9q0ohnkv?workspace=user-lucamarini22

**Comment by luisbergua** [comment]
Thanks for sharing this @lucamarini22! I took a look at your Workspace, reason why you cannot get that chart is because metric `Val mIoU` was logged at a different step than `epoch`. The same happens with `Max Val mIou` and `epoch_max_val_miou` and you can check that if you try to change the x-axis for the created line plots ('epoch' doesn't appear as an option). To fix this, you could log them all at the same step (you can set `commit=False` to wait until that's set to `True` and log everything together, docs [here](https://docs.wandb.ai/ref/python/log)), use `define_metric` (docs [here](https://docs.wandb.ai/guides/track/log/customize-logging-axes)) or create a Weave plot with an expresion like `[{epoch: runs.history.concat["epoch"].dropna, Val_mIoU: runs.history.concat["Val mIoU"].dropna}]`
![image](https://github.com/wandb/wandb/assets/113048227/c8702800-3994-40f5-bbae-1c01c621495b)

**Comment by lucamarini22** [comment]
Thanks @luisbergua ! I'll try your suggestions and let you know if I'll encounter any issue.

In the meanwhile, do you also know why I get the message 

> No data available

 even when I try to create the custom chart by putting:
- `step` on the x-axis
- `Val mIoU` on the y-axis
?

Are also these two logged at different step?

**Comment by lucamarini22** [comment]
Thanks @luisbergua ! I'll mark the issue as solved since both:
- using `_step` in the x-axis
- using Weave worked for me (even though I did not find a way to download the chart once it was created with Weave (maybe it's something that could be of interest)
