### ISSUE TITLE
[Q] Can't create a team

### ISSUE THREAD

**Issue by MarshtompCS** [wandb/wandb#6475]
I have created two teams, one is acdemic and another is corporate.

1. I want to create a team, but when I click create new team button, it redirect to the corporate team. It seems a bug!
2. I want to delete the corporate team, but I can't find how to delete it. However, I can see delete button in my academic team page.

I wonder what should I do to create a new acdemic team?

**Comment by JoanaMarieL** [comment]
Hi @MarshtompCS ,

Let us check your profile first before we can answer your inquiry., could you please share to us your profile link? The issue might be related to roles of your profile or other reason.

**Comment by MarshtompCS** [comment]
> Hi @MarshtompCS ,
> 
> Let us check your profile first before we can answer your inquiry., could you please share to us your profile link? The issue might be related to roles of your profile or other reason.

Thanks for your help! My profile link is: https://wandb.ai/zhaoyuhitsz

**Comment by sydholl** [comment]
WandB Internal User commented: 
JoanaMarieL commented: 
Hi @MarshtompCS ,

Let us check your profile first before we can answer your inquiry., could you please share to us your profile link? The issue might be related to roles of your profile or other reason.

**Comment by sydholl** [comment]
WandB Internal User commented: 
MarshtompCS commented: 
> Hi @MarshtompCS ,
> 
> Let us check your profile first before we can answer your inquiry., could you please share to us your profile link? The issue might be related to roles of your profile or other reason.

Thanks for your help! My profile link is: https://wandb.ai/zhaoyuhitsz

**Comment by MBakirWB** [comment]
Hi @MarshtompCS, assisting my colleague Joana with this request. At this time we allow academic to be part of a single academic team, wether they are admins of the org or not. Could you verify which team(s) you want to delete and I will delete from my end. Thanks

**Comment by MarshtompCS** [comment]
> Hi @MarshtompCS, assisting my colleague Joana with this request. At this time we allow academic to be part of a single academic team, wether they are admins of the org or not. Could you verify which team(s) you want to delete and I will delete from my end. Thanks

I want to delete "great-april". Thank you very much!

**Comment by MBakirWB** [comment]
Hi @MarshtompCS , the team has been deleted. Please feel free to reopen if you wish to continue the conversation

**Comment by sydholl** [comment]
WandB Internal User commented: 
MarshtompCS commented: 
> Hi @MarshtompCS, assisting my colleague Joana with this request. At this time we allow academic to be part of a single academic team, wether they are admins of the org or not. Could you verify which team(s) you want to delete and I will delete from my end. Thanks

I want to delete "great-april". Thank you very much!
