### ISSUE TITLE
[App]: "No selected runs have saved code." when attempting to visualize code

### ISSUE THREAD

**Issue by ethanabrooks** [wandb/wandb#6485]
### Current Behavior

When I add a "Code" panel to my workspace, I see the following:
<img width="465" alt="image" src="https://github.com/wandb/wandb/assets/10344742/07e2c60f-ca6b-449f-965b-4303788201dc">
As you can see at [this link](https://wandb.ai/rldl/icvi/runs/6d3e4_00007/artifacts?workspace=user-ethanbro), there is in fact code saved for this run.
As you can see here, I have enabled code saving for my profile:
<img width="663" alt="image" src="https://github.com/wandb/wandb/assets/10344742/11cf503a-81c6-411c-aded-895321db700f">

### Expected Behavior

I should be able to visualize some code with this panel.

### Steps To Reproduce

1. Click "add panel"
2. Choose "Code"

### Environment

OS: macos

Browsers: Chrome

Version: 118.0.5993.96

**Comment by Carlo-Argel** [comment]
Hi @ethanabrooks ,

Thank you for reaching out for support. I'll be glad to assist you with this. we'll investigate and get back to with updates.

Regards,
Carlo Argel

**Comment by Carlo-Argel** [comment]
Hi @ethanabrooks ,

Upon checking, the "Enable code saving by default" is disabled/untoggled for your teams. You will need to toggle it for you to able to save for your teams.

regards,
Carlo Argel
![image_720](https://github.com/wandb/wandb/assets/147673987/044bff76-0f8d-40c2-ab18-7cdf65901eb5)

**Comment by poltimmer** [comment]
Hi @Carlo-Argel, I've been having the same issue. I have code artifacts saved, and code saving is enabled in my personal account, but the code panel displays "no selected runs have saved code". I don't have any teams, and I'm not part of any teams in wandb.

**Comment by ethanabrooks** [comment]
I switched on "Enable code saving by default" in my teams settings, but I still get the same issue.

**Comment by MBakirWB** [comment]
Hi @ethanabrooks , assisting my colleague Carlo further on this. Are you still having issues with saving your code? I checked the wandb teams you are a member of, https://wandb.ai/l2m/settings, https://wandb.ai/gpt-rl/settings and neither of these teams has code saving enabled. 

@poltimmer, I checked one of your projects and it appears code saving is now working. If you still have issue do let us know.

**Comment by ethanabrooks** [comment]
Hi Mohammad. I am running all of my current projects in https://wandb.ai/rldl where I have code saving enabled. Those other two teams are not in use at the moment. I am able to view my `main.py` file for [this run](https://wandb.ai/rldl/icvi/runs/0zbpkqhv?workspace=user-ethanbro):
![image](https://github.com/wandb/wandb/assets/10344742/27d2f78b-e681-4d3a-a5af-92bb2decc276)
But not for [this run](https://wandb.ai/rldl/icvi/runs/039b6_00000?workspace=user-ethanbro):
![image](https://github.com/wandb/wandb/assets/10344742/56d70dec-811a-44be-94bf-335d1c5fea9d)

Also, I was hoping to actually view my config file (which I am logging using `run.loc_code`, not my `main.py` file, but perhaps this functionality has not been implemented.

**Comment by PgLoLo** [comment]
I confirm. Code is presented in artifacts, but dedicated panel in workspace shows an error "No selected runs have saved code.".

**Comment by MBakirWB** [comment]
@ethanabrooks , to compare run configs between runs, utilize a run comparer panel. Additionally, I was able to see what you do now with the code saving. Do you have the `debug.log` and `debug-internal.log` located in your working directory under the wandb folder available to review? If yes please send them to support@wandb.com and include in subject "Attention Mohammad: Wandb github issue #6485". I suspect the run did not successfully upload the code files prior to crashing. These files will help us confirm.

**Comment by ethanabrooks** [comment]
@MBakirWB unfortunately I deleted my `wandb/` directory since launching that run. Since then, my runs have been displaying my `main.py` file so perhaps the issue is resolved. Thanks for suggesting the "run comparer" -- that is a tool that I will use in the future. That said, my goal in displaying the config file is not to compare configs between runs (the reasons are particular to my setup, so I won't detail them here). If there is any way to display this code in the workspace, let me know. Otherwise, it looks like I can access it by clicking on artifacts.

**Comment by MBakirWB** [comment]
Hi @ethanabrooks , thank you for confirming that you run files are not appearing. If this issue does happen again please let me know and do send over those debug files for review. Additionally, you can utilize a weave panel to display the run configurations of all/specific runs. See example video below. Considering this resolved but do let me know if you have any other questions. 

https://github.com/wandb/wandb/assets/104453360/adbd1625-b021-48de-b76d-f49f72b9550d

**Comment by ethanabrooks** [comment]
@MBakirWB thank you for the suggestion. The goal of displaying the config file is actually not to see what parameters I used but to be able to easily copy/paste the logic used to produce the config. This may lay outside the scope of this issue though.

**Comment by MBakirWB** [comment]
Hi @ethanabrooks , thanks for the additional clarification. This will have to be a feature request. I've recorded one in our system and will keep you updated once there has been movement on it. Do write back in please if there is anything else we could assist you with.

**Comment by ethanabrooks** [comment]
Perfect! Thank you.

**Comment by sydholl** [comment]
WandB Internal User commented: 
ethanabrooks commented: 
Hi Mohammad. I am running all of my current projects in https://wandb.ai/rldl where I have code saving enabled. Those other two teams are not in use at the moment. I am able to view my `main.py` file for [this run](https://wandb.ai/rldl/icvi/runs/0zbpkqhv?workspace=user-ethanbro):
![image](https://github.com/wandb/wandb/assets/10344742/27d2f78b-e681-4d3a-a5af-92bb2decc276)
But not for [this run](https://wandb.ai/rldl/icvi/runs/039b6_00000?workspace=user-ethanbro):
![image](https://github.com/wandb/wandb/assets/10344742/56d70dec-811a-44be-94bf-335d1c5fea9d)

Also, I was hoping to actually view my config file (which I am logging using `run.loc_code`, not my `main.py` file, but perhaps this functionality has not been implemented.

**Comment by sydholl** [comment]
WandB Internal User commented: 
ethanabrooks commented: 
@MBakirWB unfortunately I deleted my `wandb/` directory since launching that run. Since then, my runs have been displaying my `main.py` file so perhaps the issue is resolved. Thanks for suggesting the "run comparer" -- that is a tool that I will use in the future. That said, my goal in displaying the config file is not to compare configs between runs (the reasons are particular to my setup, so I won't detail them here). If there is any way to display this code in the workspace, let me know. Otherwise, it looks like I can access it by clicking on artifacts.
