### ISSUE TITLE
[Q] How to set description and name of run in huggingface trainer?

### ISSUE THREAD

**Issue by JulioZhao97** [wandb/wandb#6487]
I am using huggingface trainer to train model and I want to ask how to set name of run and description of run? 
![image](https://github.com/wandb/wandb/assets/40555727/ce4c4577-7e53-47b0-b0a9-a52320964c8e)
As in the image, my run names are random names and description is empty, but I cannot find where to set these variables.

**Comment by sydholl** [comment]
Internal GitHub User commented: 
I am using huggingface trainer to train model and I want to ask how to set name of run and description of run? 
![image](https://github.com/wandb/wandb/assets/40555727/ce4c4577-7e53-47b0-b0a9-a52320964c8e)
As in the image, my run names are random names and description is empty, but I cannot find where to set these variables.

**Comment by Carlo-Argel** [comment]
Hi @JulioZhao97 ,

Thank you for reaching out. You can check our documentation [here](https://docs.wandb.ai/guides/track/tracking-faq#can-i-just-set-the-run-name-to-the-run-id). This documentation contains information that might help you.

Regards,
Carlo Argel

**Comment by JulioZhao97** [comment]
> Hi @JulioZhao97 ,
> 
> Thank you for reaching out. You can check our documentation [here](https://docs.wandb.ai/guides/track/tracking-faq#can-i-just-set-the-run-name-to-the-run-id). This documentation contains information that might help you.
> 
> Regards, Carlo Argel

Thnaks! I fount it.

**Comment by sydholl** [comment]
WandB Internal User commented: 
Carlo-Argel commented: 
Hi @JulioZhao97 ,

Thank you for reaching out. You can check our documentation [here](https://docs.wandb.ai/guides/track/tracking-faq#can-i-just-set-the-run-name-to-the-run-id). This documentation contains information that might help you.

Regards,
Carlo Argel

**Comment by sydholl** [comment]
WandB Internal User commented: 
JulioZhao97 commented: 
> Hi @JulioZhao97 ,
> 
> Thank you for reaching out. You can check our documentation [here](https://docs.wandb.ai/guides/track/tracking-faq#can-i-just-set-the-run-name-to-the-run-id). This documentation contains information that might help you.
> 
> Regards, Carlo Argel

Thnaks! I fount it.
