### ISSUE TITLE
[Q] How to get full system metrics through API

### ISSUE THREAD

**Issue by N33MO** [wandb/wandb#6501]
I'm trying to retrieve full system metrics for my runs using `run.history(stream="system")`. My run lasts over hours but I only get less than 1000 rows of data, I think the doc mentions it logs every 2 seconds and averages over 30 seconds.
I tried to set `samples` to a very large value, but it still cap at some point, and `run.scan_history()` seems only retrieve customized machine metrics.
Any help would be appreciated.

**Comment by JoanaMarieL** [comment]
Hello @N33MO ,

Good day, I am glad to assist you with this inquiry.

With that, you would like to retrieve the full system metrics for your run but this code run.history(stream="system") is not getting the whole thing. Have you tried this example in Docs 2: 
[https://docs.wandb.ai/guides/track/public-api-guide#download-system-metrics-data] copied below:

```
import wandb
api = wandb.Api()

run = api.run("<entity>/<project>/<run_id>")
system_metrics = run.history(stream="events")
system_metrics.to_csv("sys_metrics.csv")

```
Hope this helps and feel free to write back if you have further questions.

**Comment by JoanaMarieL** [comment]
Hi @N33MO ,
 
 How are you doing?
 May we follow up on our response if that helped you in your case? Let us know how we can further assist.

Thanks,
Joana Marie

**Comment by JoanaMarieL** [comment]
Hello @N33MO ,

Since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by Lavenderjiang** [comment]
This helped a lot. Thanks @JoanaMarieL !

**Comment by N33MO** [comment]
Thank you for your previous response @JoanaMarieL. I also realize that the metric retrieved through wandb API is actually logged every 30 seconds instead of every 2 seconds, so it is working as designed.
