### ISSUE TITLE
DOC - Sweep Tutorial broken links

### ISSUE THREAD

**Issue by OmerShubi** [wandb/wandb#6515]
The link in the [Sweep tutorial](https://docs.wandb.ai/tutorials/sweeps) -> Step 2 and Step 3 -> 

> [Learn more about using Sweeps in the command line](https://docs.wandb.com/sweeps/walkthrough)

 seems broken. 

Fix: replace with https://docs.wandb.ai/guides/sweeps/walkthrough?

Also, in Step 1, the 

> [YAML file](https://docs.wandb.com/sweeps/walkthrough#2-sweep-config) 

link  seems broken.

Finally, in Step 3 - 

> [wandb.config](https://docs.wandb.com/library/config) – Save all your hyperparameters in a configuration object so they can be logged. Read more about how to use wandb.config [here](https://colab.research.google.com/github/wandb/examples/blob/master/colabs/wandb-config/Configs_in_W%26B.ipynb).

The 'here' link seems broken.

**Comment by thanos-wandb** [comment]
Hi @OmerShubi thank you very much for informing us and providing a detailed message. I will create a Docs update request for our team to address this issue and will provide updates in this thread.
