### ISSUE TITLE
Installation Fails on python 3.12 windows 11 - [App]: 

### ISSUE THREAD

**Issue by JJKK1313** [wandb/wandb#6519]
### Current Behavior

I have tried to install the package via pip, as written in the site I wrote in the CLI:
``` pip install wandb```
everything almost goes through, but then crashes with error listed below:
```
Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 25, in <module>
      ModuleNotFoundError: No module named 'imp'
```

### Expected Behavior

I wished it could finish the installation.

### Environment

OS: Windows 11

Browsers:

Version: python 3.12

**Comment by evanatyourservice** [comment]
I'm getting same problem installing through pip in a conda python 3.12 env

```
Collecting pathtools (from wandb->tradezero==0.0.0)
  Downloading pathtools-0.1.2.tar.gz (11 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-51q41hfg/pathtools_9b14847a61414bd0b9f1110c948cb89f/setup.py", line 25, in <module>
          import imp
      ModuleNotFoundError: No module named 'imp'
      [end of output]
```

**Comment by evanatyourservice** [comment]
might just be that wandb supports only up to python 3.11, it looks like everything is going to have to migrate away from imp for 3.12+

**Comment by sydholl** [comment]
WandB Internal User commented: 
evanatyourservice commented: 
might just be that wandb supports only up to python 3.11, it looks like everything is going to have to migrate away from imp for 3.12+

**Comment by umakrishnaswamy** [comment]
hey @JJKK1313 - we just released a new version of our sdk which adds support for 3.12. could you try [upgrading your wandb   sdk to 0.16.0](https://pypi.org/project/wandb/0.16.0/) and let me know if you're reaching the same error?

**Comment by umakrishnaswamy** [comment]
Hi @JJKK1313, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by JJKK1313** [comment]
> hey @JJKK1313 - we just released a new version of our sdk which adds support for 3.12. could you try [upgrading your wandb sdk to 0.16.0](https://pypi.org/project/wandb/0.16.0/) and let me know if you're reaching the same error?
> 
> Note: this version drops support for python 3.6

Yes, the update probably fixed the issue, I managed to install it now easily. Thanks!
