### ISSUE TITLE
[CLI]: Problems running Docker image "wandb/local"

### ISSUE THREAD

**Issue by WilberRojas** [wandb/wandb#6526]
### Describe the bug

Hi, I'm having error when I try to upload data to wandb, I can upload to wandb.ai but I get the following error when I change to wandb local:

```Command
python train.py --data data/dataset_pistol.yaml --weights models/yolov5s.pt --epochs 5 --imgsz 224 --device 0
```

```shell
root@80a37e5c44bd:/usr/src/app# python train.py --data data/dataset_pistol.yaml --weights models/yolov5s.pt --epochs 5 --imgsz 224 --device 0
wandb: W&B API key is configured (use `wandb login --relogin` to force relogin)
train: weights=models/yolov5s.pt, cfg=, data=data/dataset_pistol.yaml, hyp=data/hyps/hyp.scratch-low.yaml, epochs=5, batch_size=16, imgsz=224, rect=False, resume=False, nosave=False, noval=False, noautoanchor=False, evolve=None, bucket=, cache=None, image_weights=False, device=0, multi_scale=False, single_cls=False, optimizer=SGD, sync_bn=False, workers=8, project=runs/train, name=exp, exist_ok=False, quad=False, cos_lr=False, label_smoothing=0.0, patience=100, freeze=[0], save_period=-1, local_rank=-1, entity=None, upload_dataset=False, bbox_interval=-1, artifact_alias=latest
github: skipping check (Docker image), for updates see https://github.com/ultralytics/yolov5
YOLOv5 🚀 v6.1-0-g3752807 torch 1.10.2+cu113 CUDA:0 (NVIDIA GeForce RTX 3060, 12044MiB)

hyperparameters: lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=0.05, cls=0.5, cls_pw=1.0, obj=1.0, obj_pw=1.0, iou_t=0.2, anchor_t=4.0, fl_gamma=0.0, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0
TensorBoard: Start with 'tensorboard --logdir runs/train', view at http://localhost:6006/
wandb: wandb version 0.15.12 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.12.10
wandb: Syncing run devilish-sorcery-2
wandb: ⭐️ View project at http://wandb.cloud.fogsphere.com:8080/redev/YOLOv5
wandb: 🚀 View run at http://wandb.cloud.fogsphere.com:8080/redev/YOLOv5/runs/goecjzh1
wandb: Run data is saved locally in /usr/src/app/wandb/run-20231031_165408-goecjzh1
wandb: Run `wandb offline` to turn off syncing.

Downloading https://github.com/ultralytics/yolov5/releases/download/v7.0/yolov5s.pt to models/yolov5s.pt...
wandb: ERROR Error uploading "wandb-metadata.json": CommError, <Response [403]>
 96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌     | 13.6M/14.1M [00:02<00:00, 6.57MB/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 14.1M/14.1M [00:02<00:00, 6.58MB/s]
Overriding model.yaml nc=80 with nc=1

                 from  n    params  module                                  arguments                     
  0                -1  1      3520  models.common.Conv                      [3, 32, 6, 2, 2]              
  1                -1  1     18560  models.common.Conv                      [32, 64, 3, 2]                
  2                -1  1     18816  models.common.C3                        [64, 64, 1]                   
  3                -1  1     73984  models.common.Conv                      [64, 128, 3, 2]               
  4                -1  2    115712  models.common.C3                        [128, 128, 2]                 
  5                -1  1    295424  models.common.Conv                      [128, 256, 3, 2]              
  6                -1  3    625152  models.common.C3                        [256, 256, 3]                 
  7                -1  1   1180672  models.common.Conv                      [256, 512, 3, 2]              
  8                -1  1   1182720  models.common.C3                        [512, 512, 1]                 
  9                -1  1    656896  models.common.SPPF                      [512, 512, 5]                 
 10                -1  1    131584  models.common.Conv                      [512, 256, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1    361984  models.common.C3                        [512, 256, 1, False]          
 14                -1  1     33024  models.common.Conv                      [256, 128, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1     90880  models.common.C3                        [256, 128, 1, False]          
 18                -1  1    147712  models.common.Conv                      [128, 128, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1    296448  models.common.C3                        [256, 256, 1, False]          
 21                -1  1    590336  models.common.Conv                      [256, 256, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   1182720  models.common.C3                        [512, 512, 1, False]          
 24      [17, 20, 23]  1     16182  models.yolo.Detect                      [1, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [128, 256, 512]]
Model Summary: 270 layers, 7022326 parameters, 7022326 gradients, 15.8 GFLOPs

Transferred 343/349 items from models/yolov5s.pt
Scaled weight_decay = 0.0005
optimizer: SGD with parameter groups 57 weight (no decay), 60 weight, 60 bias
albumentations: Blur(always_apply=False, p=0.01, blur_limit=(3, 7)), MedianBlur(always_apply=False, p=0.01, blur_limit=(3, 7)), ToGray(always_apply=False, p=0.01), CLAHE(always_apply=False, p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
train: Scanning '/usr/src/app/datasets/dataset-singleClass/labels/train' images and labels...2376 found, 0 missing, 0 empty, 0 corrupt: 100%|███████████| 2376/2376 [00:00<00:00, 23929.58it/s]
train: New cache created: /usr/src/app/datasets/dataset-singleClass/labels/train.cache
val: Scanning '/usr/src/app/datasets/dataset-singleClass/labels/val' images and labels...595 found, 0 missing, 0 empty, 0 corrupt: 100%|██████████████████| 595/595 [00:00<00:00, 10077.05it/s]
val: New cache created: /usr/src/app/datasets/dataset-singleClass/labels/val.cache
Plotting labels to runs/train/exp/labels.jpg... 

AutoAnchor: 5.07 anchors/target, 1.000 Best Possible Recall (BPR). Current anchors are a good fit to dataset ✅
Image sizes 224 train, 224 val
Using 8 dataloader workers
Logging results to runs/train/exp
Starting training for 5 epochs...

     Epoch   gpu_mem       box       obj       cls    labels  img_size
       0/4    0.487G    0.0987   0.01729         0        22       224: 100%|██████████| 149/149 [00:09<00:00, 15.37it/s]                                                                      
               Class     Images     Labels          P          R     mAP@.5 mAP@.5:.95: 100%|██████████| 19/19 [00:01<00:00, 10.51it/s]                                                        
                 all        595        639       0.49      0.444      0.385      0.195

     Epoch   gpu_mem       box       obj       cls    labels  img_size
       1/4    0.606G   0.07626   0.01982         0        36       224:   8%|▊         | 12/149 [00:00<00:07, 17.24it/s]                                                                       wandb: ERROR Error uploading "media/metadata/boxes2D/BoundingBoxDebugger_0_60.boxes2D.json": CommError, <Response [403]>
wandb: ERROR Error uploading "media/images/BoundingBoxDebugger_0_2.png": CommError, <Response [403]>
       1/4    0.606G   0.07633   0.02017         0        38       224:   9%|▉         | 14/149 [00:00<00:07, 17.09it/s]                                                                       wandb: ERROR Error uploading "media/images/Mosaics_0_2.jpg": CommError, <Response [403]>
wandb: ERROR Error uploading "media/metadata/boxes2D/BoundingBoxDebugger_0_40.boxes2D.json": CommError, <Response [403]>
wandb: ERROR Error uploading "media/images/BoundingBoxDebugger_0_4.png": CommError, <Response [403]>
wandb: ERROR Error uploading "media/metadata/boxes2D/BoundingBoxDebugger_0_00.boxes2D.json": CommError, <Response [403]>
wandb: ERROR Error uploading "media/metadata/boxes2D/BoundingBoxDebugger_0_10.boxes2D.json": CommError, <Response [403]>
wandb: ERROR Error uploading "media/images/BoundingBoxDebugger_0_7.png": CommError, <Response [403]>
       1/4    0.606G   0.07609   0.02003         0        33       224:   9%|▉         | 14/149 [00:00<00:07, 17.09it/s]                                                                       wandb: ERROR Error uploading "media/images/BoundingBoxDebugger_0_0.png": CommError, <Response [403]>
wandb: ERROR Error uploading "media/images/BoundingBoxDebugger_0_3.png": CommError, <Response [403]>
wandb: ERROR Error uploading "media/metadata/boxes2D/BoundingBoxDebugger_0_20.boxes2D.json": CommError, <Response [403]>
wandb: ERROR Error uploading "media/images/BoundingBoxDebugger_0_5.png": CommError, <Response [403]>
wandb: ERROR Error uploading "media/images/BoundingBoxDebugger_0_6.png": CommError, <Response [403]>
wandb: ERROR Error uploading "media/metadata/boxes2D/BoundingBoxDebugger_0_50.boxes2D.json": CommError, <Response [403]>
wandb: ERROR Error uploading "media/metadata/boxes2D/BoundingBoxDebugger_0_70.boxes2D.json": CommError, <Response [403]>
wandb: ERROR Error uploading "media/images/BoundingBoxDebugger_0_1.png": CommError, <Response [403]>
wandb: ERROR Error uploading "media/metadata/boxes2D/BoundingBoxDebugger_0_30.boxes2D.json": CommError, <Response [403]>
wandb: ERROR Error uploading "media/images/BoundingBoxDebugger_0_12.png": CommError, <Response [403]>
wandb: ERROR Error uploading "media/metadata/boxes2D/BoundingBoxDebugger_0_150.boxes2D.json": CommError, <Response [403]>
       1/4    0.606G   0.07593   0.02005         0        39       224:  11%|█         | 16/149 [00:00<00:08, 16.59it/s]                                                                       wandb: ERROR Error uploading "media/images/BoundingBoxDebugger_0_9.png": CommError, <Response [403]>
wandb: ERROR Error uploading "media/images/BoundingBoxDebugger_0_15.png": CommError, <Response [403]>
wandb: ERROR Error uploading "media/metadata/boxes2D/BoundingBoxDebugger_0_140.boxes2D.json": CommError, <Response [403]>
       1/4    0.606G   0.07575   0.01985         0        36       224:  12%|█▏        | 18/149 [00:01<00:07, 16.52it/s]
```

### Environment

Im using the docker image: ultralytics/yolov5:v6.1
- OS: Ubuntu 20.04.3
- Python version: 3.8.12
- Versions of relevant libraries:
wandb==0.12.10
torch==1.10.2+cu113
torchvision==0.11.3+cu113

### Additional Context

I always use Yolov5's docker image because it has all the environment already configured. I have no problems with uploading the data to https://wandb.ai/. But now I am trying to run local wandb and but I get errors in running the training.
I already run the command:
wandb login --relogin --host=http://{URL}:8080

**Comment by ArtsiomWB** [comment]
Hi @WilberRojas! Thank you for writing in! Could you please provide the debug.log and debug-internal.log files associated with the run where you are running into this issue? These files should be located in the wandb folder relative to your working directory.

**Comment by WilberRojas** [comment]
Here is the files, I change some private information (email, username and url). 
[debug.log](https://github.com/wandb/wandb/files/13239695/debug.log)
[debug-internal.log](https://github.com/wandb/wandb/files/13239696/debug-internal.log)
* I can upload to wandb.ai but not to a local wandb using docker image "wandb/local" (I mention again this point because maybe is important)
* And for run the docker container I use the following command:
docker run --rm -dit -v wandb:/vol -p 8080:8080 --name wandb-local -e HOST=http://IP:8080 wandb/local

**Comment by ArtsiomWB** [comment]
Hi @WilberRojas, took a peek at your debug logs and I do see many:
`requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://{URL}/local-files/redev/YOLOv5/l0vuxdui/wandb-metadata.json..`
Errors which lines up every time you try to upload a file in your console logs. 
It does seem like your URL is either not being read properly, or hasn't been added to the code properly. 

Could you please send your training code in here?

**Comment by WilberRojas** [comment]
Hi @ArtsiomWB, thanks for your reply but that's not the problem. As I mention in the last comment I have replaced all URLs, Emails and usernames for privacy. Because the main url is not important for debugging

**Comment by ArtsiomWB** [comment]
Apologies for the misunderstanding! I see you are currently on wandb 0.12.10. Would it be possible for you to upgrade? The issue could potentially be coming from you using an older version of wandb.

**Comment by WilberRojas** [comment]
I updated to wandb version 0.16.0, which seems to be the latest, and I still get the same error. I think the error is in my local wandb instance, because when I change the host to https://api.wandb.ai I can upload correctly.
I used this command to run wandb, maybe is something wrong:
```
docker run --rm -dit -v wandb:/vol -p 8099:8080 --name wandb-local -e HOST=http://YourIP:8099 wandb/local
```
I also noted that in dockerhub wandb have more images, I don't know if this container depends on another one running, because I'm only running one container with the wandb/local image.

**Comment by ArtsiomWB** [comment]
Gotcha, would it be possible for you to confirm what version of wandb server are you currently on? 
Could you also please provide a toy example of your code so I could try reproducing it on my side if possible?

**Comment by WilberRojas** [comment]
This is the version of docker image:  
* wandb/local:0.45.0 (is the latest)

And the code we are using is from ultralitics Yolov5. Here is the link:
https://github.com/ultralytics/yolov5/blob/master/train.py

PS: The code is already configured by default to use wandb.

**Comment by ArtsiomWB** [comment]
thank you for sending it over! Trying it out on our side!

**Comment by ArtsiomWB** [comment]
Hi @WilberRojas, unfortunately, there is nothing in the errors that indicates where the issue could be coming from. 

Could you please talk a bit about your environment setup and how are you setting up your machines for the experiments? 
Are you writing from your local machine to a wandb local instance deployed somewhere in the cloud?

When the file uploads are erroring out on your side, if you go into the UI, do you see those files under the `files` tab?

**Comment by sydholl** [comment]
WandB Internal User commented: 
ArtsiomWB commented: 
Hi @WilberRojas, took a peek at your debug logs and I do see many:
`requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://{URL}/local-files/redev/YOLOv5/l0vuxdui/wandb-metadata.json..`
Errors which lines up every time you try to upload a file in your console logs. 
It does seem like your URL is either not being read properly, or hasn't been added to the code properly. 

Could you please send your training code in here?

**Comment by sydholl** [comment]
WandB Internal User commented: 
WilberRojas commented: 
Hi @ArtsiomWB, thanks for your reply but that's not the problem. As I mention in the last comment I have replaced all URLs, Emails and usernames for privacy. Because the main url is not important for debugging

**Comment by sydholl** [comment]
WandB Internal User commented: 
WilberRojas commented: 
I updated to wandb version 0.16.0, which seems to be the latest, and I still get the same error. I think the error is in my local wandb instance, because when I change the host to https://api.wandb.ai I can upload correctly.
I used this command to run wandb, maybe is something wrong:
```
docker run --rm -dit -v wandb:/vol -p 8099:8080 --name wandb-local -e HOST=http://YourIP:8099 wandb/local
```
I also noted that in dockerhub wandb have more images, I don't know if this container depends on another one running, because I'm only running one container with the wandb/local image.

**Comment by sydholl** [comment]
WandB Internal User commented: 
WilberRojas commented: 
This is the version of docker image:  
* wandb/local:0.45.0 (is the latest)

And the code we are using is from ultralitics Yolov5. Here is the link:
https://github.com/ultralytics/yolov5/blob/master/train.py

**Comment by sydholl** [comment]
WandB Internal User commented: 
ArtsiomWB commented: 
Hi @WilberRojas, unfortunately, there is nothing in the errors that indicates where the issue could be coming from. 

Could you please talk a bit about your environment setup and how are you setting up your machines for the experiments? 
Are you writing from your local machine to a wandb local instance deployed somewhere in the cloud?

When the file uploads are erroring out on your side, if you go into the UI, do you see those files under the `files` tab?

**Comment by sydholl** [comment]
WandB Internal User commented: 
ArtsiomWB commented: 
Hi @WilberRojas, unfortunately, there is nothing in the errors that indicates where the issue could be coming from. 

Could you please talk a bit about your environment setup and how are you setting up your machines for the experiments? 
Are you writing from your local machine to a wandb local instance deployed somewhere in the cloud?

When the file uploads are erroring out on your side, if you go into the UI, do you see those files under the `files` tab?

**Comment by ArtsiomWB** [comment]
We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance.

**Comment by WilberRojas** [comment]
Thank you @ArtsiomWB, I have a suggestion to solve this easier. Could you provide me the simplest possible code to test wand?
If that works means the error is in the Yolov5 code I use. If that code fails the error is in the Docker instance

**Comment by ArtsiomWB** [comment]
Totally!

Could we see if you can upload an artifact this way?
- Create a folder testimg in the same directory as this script,
- Then the script generate an image in that folder
- use that folders path to upload an artifact 


```py
import wandb
import numpy
from PIL import Image

imarray = numpy.random.rand(100,100,3) * 255
im = Image.fromarray(imarray.astype('uint8')).convert('RGBA')
pathToFile = im.save('testimg/result_image.png')

run = wandb.init()
artifact = wandb.Artifact(name="my_data", type="image")
artifact.add_dir(local_path="testimg")  # Add dataset directory to artifact
wandb.log_artifact(artifact)
wandb.finish()
```

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by ArtsiomWB** [comment]
Hi, since we have not heard back from you we are going to close this request for tracking purposes. If you would like to re-open the conversation, please let us know!

**Comment by WilberRojas** [comment]
I am confused, when I started this issue, in the info said that if no response is received within 2 weeks, the issue will be closed. But you closed it after only 1 week. Maybe you want to update that information.
PS: Leave this issue closed, I will no longer respond.

**Comment by WilberRojas** [comment]
@ArtsiomWB I've been trying to contact you, without success. 
Could you delete this comment, please?
https://github.com/wandb/wandb/issues/6526#issuecomment-1791604001
