### ISSUE TITLE
[Q] How is run_name substituted automatically

### ISSUE THREAD

**Issue by freQuensy23-coder** [wandb/wandb#6552]
If i run wandb.run without run_name parameter it will be substituted automatically with a couple of words, for example, a vibrant sponge

I've looked through source code, but can't find function that generates this names. 

I will be glad if you tell me where to look. Or this functionality is not scope of this repo?

**Comment by ArtsiomWB** [comment]
Hi @freQuensy23-coder! Thank you for writing in and for your curiosity. 

The function that generates names for wandb runs is not available in the public Repo and can only be viewed internally from WandB side. 

Is there a reason why you are interested in it?

**Comment by ArtsiomWB** [comment]
Hi @freQuensy23-coder, wanted to follow up an see if you have any more questions regarding this topic?

**Comment by ArtsiomWB** [comment]
Hi, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
