### ISSUE TITLE
[Q] How to sort gradient panels by maximum absolute value?

### ISSUE THREAD

**Issue by R-N** [wandb/wandb#6553]
Hello, I just started using wandb to observe my gradients. I have a lot of parameters, so a lot of gradient panels. I want to look for exploding and vanishing gradients. How can I sort the panels by its maximum absolute value?

**Comment by luisbergua** [comment]
Hi @R-N, thanks for writing in! Would you mind sharing a link to your Workspace so I can take a look at it and advice you?
