### ISSUE TITLE
[App]: Invited myself to my team and became a member instead of admin

### ISSUE THREAD

**Issue by EdvardsZ** [wandb/wandb#6555]
### Current Behavior

I initially created a new team and invited myself to the team by mistake now I am a member instead of an admin.
I created this team for my university project, however, I can no longer delete a project because it responds with error.
Is there  a way to fix this? ( I guess I must be an admin to do that. However, now no one in our team is the admin now).

I tried just removing my self from the team however, now I stil shows up in the subscription tab

I guess this is same what happened to this issue: https://github.com/wandb/wandb/issues/2285

### Expected Behavior

I would like to delete the team project as it is no longer needed. And also delete the whole team. I see that I no longer have the ability to do that. 

### Steps To Reproduce

https://wandb.ai/cristobal_and_edvards and try to delete a project: DataScienceCompetition2023

### Screenshots

![image](https://github.com/wandb/wandb/assets/52094363/919aee04-8d4a-48d2-91a0-ec9ee2c23ca4)

### Environment

OS: Ubuntu 23.10

Browsers: Chrome

Version:

**Comment by EdvardsZ** [comment]
I would also delete the whole team. I no longer have also that ability

**Comment by MBakirWB** [comment]
Hi @EdvardsZ , 

We have update the single user in the team to an admin. You now have delete privileges on that team. Marking resolved but please let us know if you require further assistance.
