### ISSUE TITLE
wandb.finish() runs forever

### ISSUE THREAD

**Issue by marisabele** [wandb/wandb#6558]
### Current Behavior

I am using wandb inside of conda enviroment. Every time when finishing experiment with wandb.finish() prints success and then keeps running forever, no logs saved.

What is suspicious that conda-environment.yaml has following content:
`If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: `

Setting `conda config --set report_errors true/false` solves problem.

### Expected Behavior

Some error message.

### Environment

OS:

Browsers:

Version:

**Comment by thanos-wandb** [comment]
Hi @marisabele thank you for reporting this issue. Can you please provide us with additional context to help us reproduce the issue. What's your current `wandb` and `conda` version? are you running your code in the base env, or in a virtual conda env?

**Comment by thanos-wandb** [comment]
Hi @marisabele we wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by thanos-wandb** [comment]
Hi @marisabele since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
