### ISSUE TITLE
[Q] Customizing hyperparameter sweeps with dependent parameters

### ISSUE THREAD

**Issue by patricknaughton01** [wandb/wandb#6567]
Hi WandB team,

I've been using the wandb sweep tool from the online website to help me run lots of experiments quickly and it's been super helpful. I want to use the same tool to test my models under different conditions but am running into what seems to be a niche issue. I would like to have a "coupled" sweep, where the potential values for some parameters depend on what other parameters are. For my specific use case, I have a bunch of models that were trained with different inputs, and so when I test them I need the loaded network to be run with the matching input config file.

As a concrete example, say I have two config files, A and B that determine different input settings, and I trained four networks, labeled 1, 2, 3, and 4. Networks 1 and 2 were trained using config A, and 3 and 4 using config B. When I run a sweep, I want only four commands to be run, something like:
```
python test.py A 1
python test.py A 2
python test.py B 3
python test.py B 4
```
but from my understanding, if I sweep over config file and network naively, the agent will also try to execute commands like `python test.py A 3`. These runs should just error out and so won't take up a lot of compute time, but it will make the results logging very messy since I think they will still generate run artifacts, and I would rather not rely on code erroring if I don't have to. The code I want to run (`test.py`) is part of a large library so it's a bit cumbersome to compute in the code, for example, which config to load based on which checkpoint I'm using.

Is there a way to get this behavior? It would be great if I could even just generate the valid list of commands to run on my own (using a separate script) and use wandb to manage the scheduling. It seems like this functionality should be easier in some sense than what the wandb sweep is doing, maybe I just don't know how to set up the sweep config to get this behavior? 

Thanks so much for your help, big fan of wandb!

Patrick

**Comment by umakrishnaswamy** [comment]
hey @patricknaughton01 - you mentioned 'potential values for some parameters depend on what other parameters are' - by this do you mean you'd like certain parameters to be used depending on conditions you set within the config itself? just trying to better understand the question, and thanks for surfacing

**Comment by patricknaughton01** [comment]
Yes, I think this could get pretty complicated in general, but for a specific type of condition where it's easy to write out the tree of allowed combinations it might be doable. The config file might look something like this for the example I gave in the post:
<pre>
params:
  <b>config_type</b>:
    values:
      -
        value: A
        children:
          <b>checkpoint</b>:
            values: [1, 2]
      -
        value: B
        children:
          <b>checkpoint</b>:
            values: [3, 4]
</pre>
where bold indicates a config parameter that would be overriden. So this config would tell wandb to run:
```
python test.py --config_type=A --checkpoint=1
python test.py --config_type=A --checkpoint=2
python test.py --config_type=B --checkpoint=3
python test.py --config_type=B --checkpoint=4
```

This then theoretically could be nested so that the commands wandb runs are composed by traversing the config tree to the leaves.

I was wondering if wandb supports anything like this currently. If not, I'm totally fine with just generating the full list of valid configs to run myself and entering that list into wandb, but I also wasn't sure if the current interface for sweeps supports that. Something akin to just pasting a bunch of commands to run at the command line.

Thanks for your help!

**Comment by umakrishnaswamy** [comment]
hey @patricknaughton01 - currently, we don't support conditional sweeps, but I'd be happy to add your details to the existing feature request & I'll update this thread if any progress on it arises. 

Another alternative could be trying out [Launch](https://docs.wandb.ai/guides/launch#docusaurus_skipToContent_fallback) -  W&B Launch allows you to express more sophisticated hyperparameter search logic, using libraries like [Optuna](https://colab.research.google.com/corgiredirector?site=https%3A%2F%2Foptuna.org%2F%23key_features) along with Python definitions for search logic.

**Comment by patricknaughton01** [comment]
I did look into that a little bit but it seemed like Launch wanted me to set up a docker container to get things running which seemed unnecessary in my case since I have direct access to all the computers I will be using as compute nodes. Sweeps work well in my use case since I can just run the agent in the appropriate directory after I've set up the environment on each node.

Is there any way to achieve the effect of just having the wandb agent run a sequence of command lines I specify manually?

Thanks!

**Comment by umakrishnaswamy** [comment]
@patricknaughton01 - so currently there isn't a way to support this within the wandb config, but a possible workaround could be the following:
1. make two config files A and B
2. Include a conditional statement in a bash script and run that 

the script could look something like:

```
#!/bin/bash

# Read the variable
read -p "Enter the variable value: " var

# Choose the configuration file based on the variable

if [ "$var" == "A" ]
then
  echo "Running sweep with config A"
  wandb sweep config_A.yaml
elif [ "$var" == "B" ]
then
  echo "Running sweep with config B"
  wandb sweep config_B.yaml
else
  echo "Invalid variable value."
fi
```

**Comment by patricknaughton01** [comment]
I see, that should work for me. Thanks so much for your help!
