### ISSUE TITLE
[llamaindex]: Failed to log trace tree to W&B: list index out of range

### ISSUE THREAD

**Issue by salahaz** [wandb/wandb#6571]
### Describe the bug

Hello, 

I just added wandb for observability as part of the llama-index library following the same exact steps as this https://docs.llamaindex.ai/en/stable/examples/callbacks/WandbCallbackHandler.html. Yet it raises the following error 
```shell
Failed to log trace tree to W&B: list index out of range
```

### Environment

WandB version: 0.16.0

OS: Ubuntu 22.04 on WSL2

Python version:  3.10.12

**Comment by luisbergua** [comment]
Thanks for raising this @salahaz! Are you getting this error when executing the colab or are you copying these steps into another file?

**Comment by salahaz** [comment]
@luisbergua I get this error, when using the notebook locally or in any of my local repos.

**Comment by salahaz** [comment]
Thanks for pointing that out @luisbergua. Out of curiosity, what events are those ?? and, are events created by `KnowledgeGraphQueryEngine` in LLamaIndex not handled either?

**Comment by ayulockin** [comment]
> Out of curiosity, what events are those ??
You can find the list of events here: https://github.com/run-llama/llama_index/blob/adbf60f22601866467964152262d07329dc95ee0/llama_index/callbacks/schema.py#L15

> are events created by KnowledgeGraphQueryEngine in LLamaIndex not handled either?

Looking at the event types supported by the logger, the events created by the `KnowledgeGraphQueryEngine` should be supported: https://github.com/run-llama/llama_index/blob/adbf60f22601866467964152262d07329dc95ee0/llama_index/callbacks/wandb_callback.py#L375

I think there's some bug that should be addressed. Will you be able to open an issue in the LlamaIndex GH repo with some details about the use of `KnowledgeGraphQueryEngine`?

**Comment by darinkishore** [comment]
Just wanted to follow up. Have been having the same issue, but with OpenAI agents and autoretrieval. Nothing is logged other than the agent calls, those have no input/output logged. No retrieval steps, llm inputs/outputs/prompts, nothing else is logged.

**Comment by xubujie** [comment]
Get some errors

**Comment by ayulockin** [comment]
I am looking at the integration and fixing the issues.

**Comment by tisu19021997** [comment]
I'm having the same error, nothing logged. I'm using LlamaCPP models in my application. llama-index 0.9.22 and wandb 0.16.2.

**Comment by kdutia** [comment]
i'm getting the same error, nothing is logged in wandb

**Comment by ayulockin** [comment]
Hey folks, we will be deprecating this logger in favour of a new system we were working on internally. Stay tuned for a soft launch of the feature next week - we will soon try to get even better trace logging experience. Thanks for the patience. :)

**Comment by ayulockin** [comment]
Hey @salahaz, as promised to keep you all in loop. Last week we launched W&B Weave which is a better tooling for observability. Team is working on the LlamaIndex integration. W&B Trace is an old product offering which is not maintained anymore. 

[Weave announcement](https://wandb.ai/wandb/weave-announcement/reports/Weave-Simple-tools-for-applying-Generative-AI--Vmlldzo3NDE0Mjcx)
[Weave Documentation](https://wandb.github.io/weave/)

Closing this issue for now. Do let me know if you need anything more.
