### ISSUE TITLE
[Q]FileNotFoundError: [Errno 2] No such file or directory: '/xx/wandb/run-20231109_095148-n40bpgtc/logs/debug-internal.log'

### ISSUE THREAD

**Issue by lullabies777** [wandb/wandb#6576]
- Question
I tried to use wandb sweep, but it shows FileNotFoundError. The log file not found.
- Image:
![image](https://github.com/wandb/wandb/assets/67683748/ff146751-41a1-43db-9a07-d6e637a68e70)

**Comment by Carlo-Argel** [comment]
Hi @lullabies777 

thank you for reaching out for support. I'll inverstigate and get back to you for updates.

Regards,
Carlo Argel
