### ISSUE TITLE
[Q] How do I resolve "WARNING No program path found, not creating job artifact"?

### ISSUE THREAD

**Issue by NeilGirdhar** [wandb/wandb#6583]
This new error reads:
```
wandb: WARNING No program path found, not creating job artifact. See https://docs.wandb.ai/guides/launch/create-job
```
But I wasn't able to make sense from the link what I'm supposed to be doing.

What am I doing is calling `wandb.init` with `dir`, `entity`, `name`, `config`, and `reinit=True`.

**Comment by JoanaMarieL** [comment]
Hi @NeilGirdhar ,

The warning "No program path found, not creating job artifact" usually appears when `wandb` is unable to locate the script currently in execution. This could be due to several reasons:
1. Your code might be running in an interactive environment like a Jupyter notebook or a Python shell. In these cases, there isn't a single script that `wandb `can reference.
2. The `dir `argument in `wandb.init()` might not be set correctly. This argument should be an absolute path to a directory where metadata will be stored. If you're calling `wandb.init()` from a script, ensure the script is in the directory specified by `dir` or a subdirectory of it.
3. The `reinit=True` argument in `wandb.init()` lets you initialize a new `wandb `run in the same process, but it doesn't alter the script that `wandb `references. If you're calling `wandb.init()` multiple times in the same process, ensure the script you want to log is referenced in the first call to `wandb.init()`.
If you're running your code in a script and want to log the script as an artifact, ensure the script is in the correct directory and that you're calling `wandb.init()` correctly. If you're running your code in an interactive environment and want to log a script as an artifact, you'll need to manually log the script using `wandb.save()`.
Here's an example of how to use `wandb.save()`:
```
python
import wandb

# Initialize a new run
run = wandb.init(project="my-project", entity="my-entity", name="my-run", config={"my_param": "my_value"}, reinit=True)

# Save a script or other file as an artifact
run.save("/path/to/my_script.py")
```

You can also share a snippet of the code you are running and your specific use case :)

**Comment by NeilGirdhar** [comment]
> * The `dir `argument in `wandb.init()` might not be set correctly. This argument should be an absolute path to a directory where metadata will be stored. If you're calling `wandb.init()` from a script, ensure the script is in the directory specified by `dir` or a subdirectory of it.

Okay, I will try making this an absolute path, but the default given in [the documentation](https://docs.wandb.ai/ref/python/init) is the relative path `./wandb`.  Also, it's odd that no error is given by WandB when a relative path is provided.

**Comment by JoanaMarieL** [comment]
Hi @NeilGirdhar , 

For 3. it is a mistake, apologies for that. 

Can you try to set up the absolute path and tell us the result please. Also if you still running the issues can you provide us an example of your code that you are using to create the launch job. 
Thanks~

**Comment by NeilGirdhar** [comment]
@JoanaMarieL Still broken, unfortunately.  I'm doing this now:
```python
wandb_cache_path = Path('./.wandb_cache').resolve()
wandb_cache_path.mkdir(parents=True, exist_ok=True)
wandb.init(dir=wandb_cache_path, ...)
```

**Comment by NeilGirdhar** [comment]
Sorry, I've spent about an hour trying to work through WandB's source code, but it's really a tangled web.  It appears that:
* `metadata['codePath']` is not set and `metadata[codePathLocal]` is none,
* `data["codePath"]` comes from `self.settings.program_relpath`, which has type `SettingsData`
* Nothing ever sets the `SettingsData.program_relpath` field.

**Comment by JoanaMarieL** [comment]
> ```python
> wandb_cache_path = Path('./.wandb_cache').resolve()
> wandb_cache_path.mkdir(parents=True, exist_ok=True)
> wandb.init(dir=wandb_cache_path, ...)
> ```

Hi @NeilGirdhar , can you share what is broken specifically? The error you encountered, you can provide us the full stack trace error for this one. Attach the `debug.log` and `debug-internal.log` files for the affected run(s). They are located in the working directory under the `wandb/run-<run-id>/logs` folder

**Comment by NeilGirdhar** [comment]
There's no stack trace since it doesn't raise any exception.  But there is the warning that I listed above.  I'm happy to provide error logs, but will these be generated considering that there's only a warning?

**Comment by JoanaMarieL** [comment]
> Sorry, I've spent about an hour trying to work through WandB's source code, but it's really a tangled web. It appears that:
> 
> * `metadata['codePath']` is not set and `metadata[codePathLocal]` is none,
> * `data["codePath"]` comes from `self.settings.program_relpath`, which has type `SettingsData`
> * Nothing ever sets the `SettingsData.program_relpath` field.
> 
> Regardless, my suggestion is that there should be a way to set (or override) this from `wandb.init`.

Acknowledging this one @NeilGirdhar and will review if this will be possible. We'll circle back to you regarding this matter.

**Comment by JoanaMarieL** [comment]
> Hello. Thank you for your response.
> 
> There's no stack trace since it doesn't raise any exception. But there is the warning that I listed above. I'm happy to provide error logs, but will these be generated considering that there's only a warning?

@NeilGirdhar Yes that will somehow help us understand the reason of the warning. You can send the whole warning as a screenshot or copy paste the whole thing.

**Comment by NeilGirdhar** [comment]
Thank you very much!

I will do that in the next day 😄

**Comment by NeilGirdhar** [comment]
Screenshot:
```
wandb: Tracking run with wandb version 0.16.0
wandb: Run data is saved locally in /home/neil/src/cmm/.wandb_cache/wandb/run-20231120_170642-jhvbzcag
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run geometry
wandb: ⭐️ View project at https://wandb.ai/neilgirdhar/cmm
wandb: 🚀 View run at https://wandb.ai/neilgirdhar/cmm/runs/jhvbzcag
wandb: WARNING No program path found, not creating job artifact. See https://docs.wandb.ai/guides/launch/create-job
wandb:                                                                                
wandb: 🚀 View run geometry at: https://wandb.ai/neilgirdhar/cmm/runs/jhvbzcag
wandb: Synced 4 W&B file(s), 1 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./.wandb_cache/wandb/run-20231120_170642-jhvbzcag/logs
```
[debug.log](https://github.com/wandb/wandb/files/13419906/debug.log)
[debug-internal.log](https://github.com/wandb/wandb/files/13419907/debug-internal.log)

**Comment by JoanaMarieL** [comment]
Hi @NeilGirdhar ,

Appreciate you providing us these things , we would also like to ask for your run link if it is possible. Could you also check if the artifact is really is not being created after that run? Thank you.

**Comment by sydholl** [comment]
WandB Internal User commented: 
NeilGirdhar commented: 
> * The `dir `argument in `wandb.init()` might not be set correctly. This argument should be an absolute path to a directory where metadata will be stored. If you're calling `wandb.init()` from a script, ensure the script is in the directory specified by `dir` or a subdirectory of it.

Okay, I will try making this an absolute path, but the default given in [the documentation](https://docs.wandb.ai/ref/python/init) is the relative path `./wandb`.  Also, it's odd that no error is given by WandB when a relative path is provided.

**Comment by sydholl** [comment]
WandB Internal User commented: 
JoanaMarieL commented: 
Hi @NeilGirdhar , 

For 3. it is a mistake, apologies for that. 

Can you try to set up the absolute path and tell us the result please. Also if you still running the issues can you provide us an example of your code that you are using to create the launch job. 
Thanks~

**Comment by sydholl** [comment]
WandB Internal User commented: 
NeilGirdhar commented: 
@JoanaMarieL Still broken, unfortunately.  I'm doing this now:
```python
wandb_cache_path = Path('./.wandb_cache').resolve()
wandb_cache_path.mkdir(parents=True, exist_ok=True)
wandb.init(dir=wandb_cache_path, ...)
```

**Comment by sydholl** [comment]
WandB Internal User commented: 
NeilGirdhar commented: 
Sorry, I've spent about an hour trying to work through WandB's source code, but it's really a tangled web.  It appears that:
* `metadata['codePath']` is not set and `metadata[codePathLocal]` is none,
* `data["codePath"]` comes from `self.settings.program_relpath`, which has type `SettingsData`
* Nothing ever sets the `SettingsData.program_relpath` field.

**Comment by sydholl** [comment]
WandB Internal User commented: 
NeilGirdhar commented: 
There's no stack trace since it doesn't raise any exception.  But there is the warning that I listed above.  I'm happy to provide error logs, but will these be generated considering that there's only a warning?

**Comment by sydholl** [comment]
WandB Internal User commented: 
JoanaMarieL commented: 
> Sorry, I've spent about an hour trying to work through WandB's source code, but it's really a tangled web. It appears that:
> 
> * `metadata['codePath']` is not set and `metadata[codePathLocal]` is none,
> * `data["codePath"]` comes from `self.settings.program_relpath`, which has type `SettingsData`
> * Nothing ever sets the `SettingsData.program_relpath` field.
> 
> Regardless, my suggestion is that there should be a way to set (or override) this from `wandb.init`.

Acknowledging this one @NeilGirdhar and will review if this will be possible. We'll circle back to you regarding this matter.

**Comment by sydholl** [comment]
WandB Internal User commented: 
JoanaMarieL commented: 
> Hello. Thank you for your response.
> 
> There's no stack trace since it doesn't raise any exception. But there is the warning that I listed above. I'm happy to provide error logs, but will these be generated considering that there's only a warning?

@NeilGirdhar Yes that will somehow help us understand the reason of the warning. You can send the whole warning as a screenshot or copy paste the whole thing.

**Comment by sydholl** [comment]
WandB Internal User commented: 
JoanaMarieL commented: 
Hi @NeilGirdhar ,

Appreciate you providing us these things , we would also like to ask for your run link if it is possible. Could you also check if the artifact is really is not being created after that run? Thank you.

**Comment by sydholl** [comment]
Joana Marie commented: 
Hello

**Comment by NeilGirdhar** [comment]
Hello, it appears that my last comments were deleted?

**Comment by sydholl** [comment]
WandB Internal User commented: 
JoanaMarieL commented: 
Hi @NeilGirdhar ,

Appreciate you providing us these things , we would also like to ask for your run link if it is possible. Could you also check if the artifact is really is not being created after that run? Thank you.

**Comment by sydholl** [comment]
WandB Internal User commented: 
NeilGirdhar commented: 
Hello, it appears that my last comments were deleted?

**Comment by JoanaMarieL** [comment]
Hello @NeilGirdhar ,

Could you try this:
`WANDB_DIR='./.wandb_cache'` instead of setting `dir` when calling `wandb.init` to see if the behavior is the same.
If the warning will still appear.

**Comment by JoanaMarieL** [comment]
Hi @NeilGirdhar , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by NeilGirdhar** [comment]
@JoanaMarieL Thanks Joana.  Sorry that I haven't been able to respond the last couple of days.  I do appreciate your help with this, but my focus is on other urgent problems right now.  I will follow up with this when I have more time.

**Comment by Pseudomanifold** [comment]
Hi @JoanaMarieL,

Taking this up again, since I am running into the same issue. Setting `WANDB_DIR` locally as you suggested does not change the outcome (neither does setting `dir` to an absolute path). I'm on version 0.16.1 of `wandb`.

**Comment by LvanderGoten** [comment]
I seem to be only having these issues with version 0.16.1, I downgraded to version to 0.15.5 now.
