### ISSUE TITLE
[Q] Is there an API for the model registry in the Python SDK?

### ISSUE THREAD

**Issue by alegonz** [wandb/wandb#6587]
I would like to manipulate registered models in the model registry programatically. For example create a new registered model with a certain name, description and tags. Essentially do what one does from the Web UI dialog (see screenshot) but from python.

From the documentation, I understand that one can link an artifact to an already registered model with the `Artifact.link` API, but this assumes the model was registered manually from the Web UI, right? How could I register I model programatically?

Thanks!

![image](https://github.com/wandb/wandb/assets/26665243/3e3174d9-f6f1-4c2e-8a37-6bfe6ebb43e5)

**Comment by MBakirWB** [comment]
Hi @alegonz , we are actively working on implementing this functionality for our next sdk release. There will be a single method call `wandb.log_model()` that will accomplish logging of a model. This will be an addition to the current programmatic approach of creating models. Please see the [examples provided here](https://docs.wandb.ai/guides/model_registry#how-it-works) of how to log artifact models and link them to the registry.

**Comment by alegonz** [comment]
@MBakirWB Got it, thanks!

> There will be a single method call wandb.log_model() that will accomplish logging of a model.

The other day I noticed [this `Run.log_model` API](https://docs.wandb.ai/ref/python/run#log_model) in the docs, but I couldn't find any other documentation about it. Is that related to the `wandb.log_model()` method you mentioned?

**Comment by alegonz** [comment]
> The other day I noticed [this `Run.log_model API`](https://docs.wandb.ai/ref/python/run#log_model) in the docs, but I couldn't find any other documentation about it. Is that related to `the wandb.log_model()` method you mentioned?

It seems unrelated. Looking at [the PR](https://github.com/wandb/wandb/pull/6205) that introduced the `Run.log_model()` method, it seems it just a thin wrapper over `_log_artifact` to log artifacts of `type="model"`.
(I also remembered that the model registry is independent of runs so it wouldn't make sense for `Run.log_model()` to deal with the model registry.)

-----

Regarding the upcoming `wandb.log_model()` method, if that method is supposed to create a new registered model then that name seems misleading as it could be easily confused with `Run.log_model()`. Perhaps a more suitable name would be `wandb.register_model()` or some similar wording that relates to the Model Registry.

**Comment by MBakirWB** [comment]
Hi @alegonz , appreciate your feedback. The APIs mentioned above are meant to abstract artifact APIs from the users. They are just wrappers around the existing artifact APIs. Additionally, there isn't a difference between `wandb.log_model` & `run.log_model`. wandb.init() This initializes W&B without storing the run object in a variable. In this case, you won't have a direct handle to the run, and if you want to use the calls above, you will need to use `wandb.log_mode`l. The later when a user stores the run objects in variable `run`. So you will need to use `run.<run-method>`.

**Comment by alegonz** [comment]
@MBakirWB Sorry, I'm confused now. Is `wandb.log_model` an API for logging model artifacts or for creating models on the registry? My original question in this issue thread concerns the latter, but from your explanation it seems the `wandb.log_model` API is for the former?

**Comment by MBakirWB** [comment]
Hi @alegonz , apologies for confusion. `wandb.log_model` automatically logs an artifact of type `model`. It does not link this to the registry

Example Usage:
```
wandb.init(project="New-Artifact-Api")
wandb.log_model(path="model.pt", model_name="Artifact_Only_MNIST")
wandb.finish()
```

Produces an artifact only of type model, [see here](https://wandb.ai/mohammadbakir/New-Artifact-Api/artifacts/model/Artifact_Only_MNIST/v0)

`wandb.link_model`  logs an artifact of type model and links it to the registry under specified model name if it doesn’t exist already. Note that this reg model will be created in the ‘model-registry’ project, to make it a part of the Model Registry.

Example usage:
```
wandb.init(project="New-Artifact-Api")
wandb.link_model(path="model.pt",linked_model_name="MNIST", model_name="Artifact_Plus_Registry_MNIST")
wandb.finish()
```
Produces both artifact and links to model registry, [see here](https://wandb.ai/mohammadbakir/New-Artifact-Api/artifacts/model/Artifact_Plus_Registry_MNIST/v0)

**Comment by alegonz** [comment]
@MBakirWB Thank you for the clarification and the example! I tried it and confirmed `wandb.link_model` will create a new entry in the model registry if it does not exist. Though it seems it is not possible yet to specify a description or tags for the entry, I guess those can currently be edited on the Web UI?

**Comment by MBakirWB** [comment]
Hi @alegonz , you're welcome and that is correct, currently allows for adding aliases but not tags or descriptions to the created artifact. I've passed this feedback on to our Artifacts team for consideration. Marking this resolved but please do reach out again if you require further assistance.

**Comment by sydholl** [comment]
WandB Internal User commented: 
alegonz commented: 
> The other day I noticed [this `Run.log_model API`](https://docs.wandb.ai/ref/python/run#log_model) in the docs, but I couldn't find any other documentation about it. Is that related to `the wandb.log_model()` method you mentioned?

It seems unrelated. Looking at [the PR](https://github.com/wandb/wandb/pull/6205) that introduced the `Run.log_model()` method, it seems it just a thin wrapper over `_log_artifact` to log artifacts of `type="model"`.
(I also remembered that the model registry is independent of runs so it wouldn't make sense for `Run.log_model()` to deal with the model registry.)

-----

Regarding the upcoming `wandb.log_model()` method, if that method is supposed to create a new registered model then that name seems misleading as it could be easily confused with `Run.log_model()`. Perhaps a more suitable name would be `wandb.register_model()` or some similar wording that relates to the Model Registry.

**Comment by sydholl** [comment]
WandB Internal User commented: 
alegonz commented: 
@MBakirWB Sorry, I'm confused now. Is `wandb.log_model` an API for logging model artifacts or for creating models on the registry? My original question in this issue thread concerns the latter, but from your explanation it seems the `wandb.log_model` API is for the former?
