### ISSUE TITLE
[CLI]: wandb: Network error (ReadTimeout), entering retry loop.

### ISSUE THREAD

**Issue by lhq12** [wandb/wandb#6592]
### Describe the bug

Hello, I got errors when I `wandb sync` the offline runs: `wandb: Network error (ReadTimeout), entering retry loop.`. I also tried to start a new online run and got the same errors. I tried many times yesterday and today, but no one successed. Please help me.

```python

```

```shell
wandb: Network error (ReadTimeout), entering retry loop.
Problem at: main.py 162 init_wandb..
wandb: ERROR Run initialization has timed out after 90.0 sec. 
wandb: ERROR Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "main.py", line 185, in <module>
    main()
  File "main.py", line 173, in main
    cfg.wandb_run = init_wandb(cfg)
  File "main.py", line 162, in init_wandb
    run = wandb.init(name=name,
  File "/root/miniconda3/envs/fl/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1189, in init
    raise e
  File "/root/miniconda3/envs/fl/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/root/miniconda3/envs/fl/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
```

### Environment

WandB version: 0.15.12

OS:  Ubuntu 18.04.5

Python version: 3.8.16

Versions of relevant libraries:

**Comment by JoanaMarieL** [comment]
Hello @lhq12 ,

Happy to help. Could you tell us more about what you are doing please. In my understanding , initially you are using wandb synch for the offline runs then encountered an error. Kindly provide the following:

- Screen recording of the issue, the process and the error
- snippet of the code 
- “full” error stack trace along with **debug.log** and **debug-internal.log files** for us to investigate.
    - To collect the debug.log files:
        - Go to the run directory , example: https://wandb.ai/sydholl/basic-intro/runs/jl1h82y1/files?workspace=user-sydholl "run-xxx" (where xxx is the run name)
        - Under "files" and "logs" repos. For instance: "./files/output.log", "./logs/debug.log", "./logs/debug-internal.log".

**Comment by lhq12** [comment]
Hi,

Thank you for the. I've been monitoring my experiments using wandb in "offline mode," and now I'm attempting to sync the logs to the wandb cloud as usual, but unfortunately, it's not working. Despite my consistent trying in recent days, the process consistently encounters a network error and gets stuck.

<img width="944" alt="image" src="https://github.com/wandb/wandb/assets/45817821/954d87cd-46b1-40cf-bc0b-a056fa428736">

**Comment by lhq12** [comment]
Here is the debug log:

[debug.log](https://github.com/wandb/wandb/files/13336505/debug.log)

**Comment by lhq12** [comment]
Here is the debug.cli.root.log:
[tmpdebug-cli.root.log](https://github.com/wandb/wandb/files/13344729/tmpdebug-cli.root.log)

And I can ping api.wandb.ai successfully.
![d3b02f117cc756433fc1b9ee2d9166f](https://github.com/wandb/wandb/assets/45817821/4bc5b479-833f-4b46-bf9d-59226076205d)

**Comment by JoanaMarieL** [comment]
Hello @lhq12 ,

Thank you for providing these information. Could you also provide the sample code that you are running please.

**Comment by lhq12** [comment]
Here is the code related to wandb:
`def init_wandb(args):
    print(f'-----------------init_wandb:{args.exp_tag}-----------------')
    project = args.pj_name
    name = args.exp_tag # key hyperparams

    # tags
    alg = f'alg={args.algorithm}'
    bs = f'bs={args.batch_size}'
    ds = f'ds={args.dataset}'
    if args.algorithm == 'alone':
        tags = [alg, bs, ds]
    else:
        agg = f'agg={args.agg}'
        st = f'st={args.split_type}'
        nc = f'nc={args.num_clients}'
        nl = f'nl={args.num_labels}'
        net = f'net={args.net}'
        tags = [agg, alg, bs, ds, st, nc, nl, net]

    run = wandb.init(name=name, 
                    tags=tags, 
                    config=args.__dict__, 
                    project=project,
                    mode="offline",
            )
    return run
cfg.run = init_wandb(cfg)
...
cfg.run.log({key, value}, step)
`
And yesterday, I synced the offline run successfully after downloading them from the cloud server to the local environment(with Windows OS). However, attempting to sync them directly on the cloud server still resulted in failure.

**Comment by MBakirWB** [comment]
Hi @lhq12 could you clarify your statement `synced the offline run successfully after downloading them from the cloud server to the local environment(with Windows OS). ` Are you stating that you were running your wandb runs in a containerized environment, downloaded the wandb run files to your local machine and then synced them? When users run into network errors, this typically means that they are behind a firewall/proxy that is prevent communication with wandb or have outdated SSL certs, more on this [here](https://docs.wandb.ai/guides/technical-faq/troubleshooting#how-do-i-deal-with-network-issues)

**Comment by sydholl** [comment]
WandB Internal User commented: 
lhq12 commented: 
Hi,

Thank you for the. I've been monitoring my experiments using wandb in "offline mode," and now I'm attempting to sync the logs to the wandb cloud as usual, but unfortunately, it's not working. Despite my consistent trying in recent days, the process consistently encounters a network error and gets stuck.

<img width="944" alt="image" src="https://github.com/wandb/wandb/assets/45817821/954d87cd-46b1-40cf-bc0b-a056fa428736">

**Comment by sydholl** [comment]
WandB Internal User commented: 
lhq12 commented: 
Here is the debug log:

[debug.log](https://github.com/wandb/wandb/files/13336505/debug.log)

**Comment by sydholl** [comment]
WandB Internal User commented: 
JoanaMarieL commented: 
Hello @lhq12 ,

Thank you for providing these information. Could you also provide the sample code that you are running please.

**Comment by lhq12** [comment]
Thank you @MBakirWB. 

I attempted to sync again just now, and to my surprise, it was successful.

**Comment by JoanaMarieL** [comment]
Hi @lhq12 ,

Great to hear that you have synced it successfully. May we know what did you follow specifically? Thanks :)

**Comment by lhq12** [comment]
Thank you!

I haven't done anything. I simply made a new attempt.

**Comment by JoanaMarieL** [comment]
@lhq12 , alright for now we will mark this as resolved and feel free to reach us out again and will gladly help!
