### ISSUE TITLE
[CLI]: `wandb.setup()` (or `.init()`) cannot load settings stored by cli `wandb login`

### ISSUE THREAD

**Issue by YouJiacheng** [wandb/wandb#6627]
### Describe the bug

I use `docker run --rm -it python:3.11-slim-bullseye bash` to maximize reproducibility.
`wandb==0.16.0` is installed by `pip install wandb`.
First execute
```shell
wandb login --host='http://localhost:8080'
```
and enter a correct key. It gives:
```shell
wandb: You can find your API key in your browser here: http://localhost:8080/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit: 
wandb: Appending key for localhost to your netrc file: /root/.netrc
```
(BTW, if I enter a wrong key, it additionally gives `wandb: Network error (ConnectionError), entering retry loop.`. It seems that error handling code cannot recognize key error?)

After that, `wandb.setup().settings.base_url` is not `http://localhost:8080` as expected.
```python
>>> import wandb
>>> wandb.setup().settings.base_url
'https://api.wandb.ai
>>> wandb.setup().settings.settings_system
'/root/.config/wandb/settings'
```

`cat /root/.config/wandb/settings` gives:
```
cat: /root/.config/wandb/settings: No such file or directory`
```
`cat /tmp/root/.config/wandb/settings` gives:
```
[default]
base_url = http://localhost:8080
```

I have investigated the source code and figure out the root cause:
`wandb login` will try persisting `base_url` twice, unfortunately none of them is useful.
https://github.com/wandb/wandb/blob/0735e217108fa9ebff060a78bb8f2c4e8c471e10/wandb/cli/cli.py#L223-L247

First through `wandb.sdk.wandb_login._handle_host_wandb_setting`
https://github.com/wandb/wandb/blob/0735e217108fa9ebff060a78bb8f2c4e8c471e10/wandb/sdk/wandb_login.py#L28-L43
which will persist `base_url` into
https://github.com/wandb/wandb/blob/0735e217108fa9ebff060a78bb8f2c4e8c471e10/wandb/old/settings.py#L122-L137
i.e., if `/root/.config/wandb` does not exist, it will try `/tmp/.config/wandb` and finally `/tmp/root/.config/wandb`

Second through `wandb.login`, which will call `wandb.sdk.wandb_login._handle_host_wandb_setting` again.

But `wandb.setup()` only load settings from `settings_system`, which is `/root/.config/wandb`(if user doesn't change it).
https://github.com/wandb/wandb/blob/0735e217108fa9ebff060a78bb8f2c4e8c471e10/wandb/sdk/wandb_settings.py#L866-L869

https://github.com/wandb/wandb/blob/0735e217108fa9ebff060a78bb8f2c4e8c471e10/wandb/sdk/wandb_settings.py#L1611-L1626

If I manually create `/root/.config/wandb` with proper access control, the problem can be perfectly solved.

### Environment

WandB version: 0.16.0
Docker Image: python:3.11-slim-bullseye

**Comment by umakrishnaswamy** [comment]
hey @YouJiacheng - I surfaced this to our eng team and will let you know if progress arises on the issue! thanks again

**Comment by umakrishnaswamy** [comment]
hey @YouJiacheng - a fix for this is available in our latest sdk release. please let me know if you have any other questions!
