### ISSUE TITLE
[Q] Delete Organization

### ISSUE THREAD

**Issue by ubless607** [wandb/wandb#6631]
Is it possible to delete organization? I cannot find any button.
- username: zzae607
- https://wandb.ai/account-settings/mmmil-org
- https://wandb.ai/account-settings/2222222222222222222222-org

**Comment by JoanaMarieL** [comment]
Hi @ubless607 .

Yes it is possible and let us help you with that. Thank you for providing all this information. We will circle back once we deleted it.

**Comment by luisbergua** [comment]
Hi @ubless607, I just deleted `mmmil-org` and `2222222222222222222222-org` organizations for you
