### ISSUE TITLE
[App]: Images rendered way too small

### ISSUE THREAD

**Issue by joeryjoery** [wandb/wandb#6632]
### Current Behavior

No matter how I try to shape images (i.e., pngs with wandb.Image), they are rendered horribly in the web-app. Either being far too small or far too large.

### Expected Behavior

It would be nice if the web-app could dynamically adjust the stretch (with fixed aspect-ratio that is) the panel to give a better view of logged images.

### Steps To Reproduce

```python
import matplotlib.pyplot as plt
import wandb

# Initialize wandb etc.

plt.plot ...

wandb.log({'my_plot': plt}  # Doesn't matter how I scale plt with figsize, as the app doesn't nicely render this anyway...
```

### Screenshots

Currently I get this:

![image](https://github.com/wandb/wandb/assets/22054219/7c5e8f9d-80c9-4671-a532-d0ccdf205a3f)

I would like this to stretch so I can actually see the image (which I did right now manually in Paint as an example...):

![image](https://github.com/wandb/wandb/assets/22054219/498a8a33-5f2b-4a72-ac01-9a6aa4069103)

### Environment

OS: Mac/ OSx and Windows 10/ 11

Browsers: Google Chrome

Version:

**Comment by sydholl** [comment]
WandB Internal User commented: 
ArtsiomWB commented: 
Hi @joeryjoery ! Thank you for writing in! Could you please send a link to the workspace where you are seeing this behavior?

**Comment by joeryjoery** [comment]
The workspace I took the image from is private, but this is the link: https://wandb.ai/joery/AXME/runs/qifajder?workspace=user-joery

The plot is under the category: `EvaluationService/sample_plots/gridworld.SquareGrid/0/plots`.

I also edited my issue to include the OS and browser.

**Comment by joeryjoery** [comment]
Apologies for wasting your time, turns out I swapped the matplotlib figure sizes (swapped height and width) accidentally.

Now it works fine.

**Comment by sydholl** [comment]
WandB Internal User commented: 
joeryjoery commented: 
Apologies for wasting your time, turns out I swapped the matplotlib figure sizes (swapped height and width) accidentally.

Now it works fine.
