### ISSUE TITLE
[Q]Delete

### ISSUE THREAD

**Issue by 39c5bb-miku** [wandb/wandb#6633]
How can I delete Artifacts?

**Comment by JoanaMarieL** [comment]
Hello @39c5bb-miku ,

Good day~

To delete an artifacts, you do it interactively with the App UI or programmatically with the wandb SDK. You can check our docs [here ](https://docs.wandb.ai/guides/artifacts/delete-artifacts) for more detailed steps of deleting artifact version, artifact aliases etc. Hope that helps. Have a great day!
