### ISSUE TITLE
[Q] Python API runs, filter by names

### ISSUE THREAD

**Issue by HesunChen** [wandb/wandb#6635]
I was trying to use python api.runs() to retrieve a batch of runs according to their names. I used regex to filter names, and the code is as follows:
```
import wandb

api = wandb.Api()
runs = api.runs(
    path="hesunchen/sf_trans",
    filters={"Name": {"$regex": ".*label_comparison.*"}}  
)
print(runs.length)
```
However, the output is `None`. But when I got nine results using the filter in graphic intereface.
![filter](https://github.com/wandb/wandb/assets/57084181/4a282a80-8d5f-406c-ad98-c3050cd700fe)

**Comment by rsanandres-wandb** [comment]
Hello @pukility!

You can use the regex by changing `Name` to `display_name`:
```
import wandb

api = wandb.Api()
runs = api.runs(
    path="hesunchen/sf_trans",
    filters={"display_name": {"$regex": ".*label_comparison.*"}}  
)
print(runs.length)
```

**Comment by ngrayluna** [comment]
Here is the doc: https://docs.wandb.ai/ref/python/public-api/api/#runs
