### ISSUE TITLE
[Q] Launch sweep with varying source code files

### ISSUE THREAD

**Issue by 19kdc3** [wandb/wandb#6642]
Hi Wandb,

I'm reading through your documentation and I'm confused as to how to run a **launch sweep** that requires **multiple and different types of source code files** (i.e. .py, .txt, .stl, etc.). I've seen recommendations as to using a docker image, log_code, log_artifact, etc. and get the sense that there are a few ways to achieve my goal, but I can't seem to get the pieces in order and would appreciate your suggestions/guidance!

My objective has 2 stages:

1. Run a **lunch sweep from main PC** with **source code + files** and run a **launch agent on remote PC**. Both PC run windows, and remote PC has docker and wandb installed.
2. Run a **lunch sweep from main PC** with **source code + files** and run a **launch agent on a remote linux server** (redhat) utilizing SLURM scheduler.

Ideally I'd like the solution to be applicable to both stages. I.e. the solution for stage 1 only requires additions/modifications to work for stage 2, not an entire overhaul of the solution. 

I appreciate the help/guidance and I'm more than happy to answer any questions you may have. Thanks!

**Comment by rsanandres-wandb** [comment]
Hello @19kdc3 !

As a note, we do not officially support Windows for Launch so there may be issues there. We do support launch with linux. That is to say, launch will in theory work on Windows but we cannot guarantee that it will work.

Since you need multiple different types of files, a docker image probably be your best bet since you will be able to use `buildx` to create the docker image for different architectures. The location of the launch agent will determine which compute it will use. As long as the docker image is compatible with the architecture of the machine that you will be conducting experiments on, the initial location of the sweep should not matter.

**Comment by 19kdc3** [comment]
Hi @rsanandres-wandb , thanks for getting back to me!

With regards to the docker image, I've seen a mixture of ways to use it. I've chosen the path of uploading all the relevant files as "code artifacts" to a job on the wandb server and having the launch agent make the docker image and run the code (I've only succeeded as far as uploading the files as code artifacts). Is this the correct direction or is there a better more efficient process of using a docker image?

**Comment by rsanandres-wandb** [comment]
Yes, that is one of the ways to conduct Launch. Given your setup, that is one of the recommended ways to do conduct launch. Neither of ways is necessarily better in a vacuum, but given your setup I believe the way you stated is a solid path.

**Comment by 19kdc3** [comment]
Great, thank you for confirming! I came across the [production ](https://docs.wandb.ai/guides/integrations/docker#production)section on your Docker integration documentation, and I'm confused on how to specify the `wandb docker-run` command. 

Currently my agent PC downloads the code artifacts from the wandb server and successfully compiles the docker image following your [launch setup for docker documentation](https://docs.wandb.ai/guides/launch/setup-launch-docker#docker-image-builders). However, when docker runs the image on the agent PC it instead uses the command `docker run`. Should it be using the `wandb docker-run` command instead?
