### ISSUE TITLE
[Q] Logging arrays?

### ISSUE THREAD

**Issue by Laknath1996** [wandb/wandb#6646]
I was able to log arrays earlier. But now, the arrays I log actually end up logged as histograms. Is there a way to log arrays as they are?

**Comment by JoanaMarieL** [comment]
Hi @Laknath1996 ,
Happy to help. To further assist, please provide the following information:

- Brief description of your experiment. 
- Are your arrays in numpy or pandas? 
- What type of data does it contain?

An option would be to log them as Tables, [docs here](https://docs.wandb.ai/guides/tables/tables-walkthrough#1-log-a-table), check the `Pandas Dataframe` tab for an example.

**Comment by Laknath1996** [comment]
Thanks for pointing that Tables can be used to log an array. I was trying to log a numpy array that consists of a sequence of predictions made by the model at the end of training. I think logging them as an entry of a dataframe would work. Thank you!

**Comment by JoanaMarieL** [comment]
Glad that it worked on your end @Laknath1996 , will mark this as resolved and feel free to write us again for any questions.
