### ISSUE TITLE
[Q]Can I get a SWEEP_ID by ‘wandb sweep sweep.yaml’ and use it in ‘wandb agent XXX’ directly in command line mode?

### ISSUE THREAD

**Issue by Thunder-Volcano** [wandb/wandb#6652]
Can I get a SWEEP_ID by ‘wandb sweep sweep.yaml’ and use it in ‘wandb agent XXX’ directly in command line mode?
Such as, I can use a .sh script to run my code in multi-GPU machine.

```
wandb init -p project
SWEEP_ID = wandb sweep sweep.yaml
CUDA_VISIBLE_DEVICES=0 wandb agent --count 3 entity/project/SWEEP_ID 
CUDA_VISIBLE_DEVICES=1 wandb agent --count 3 entity/project/SWEEP_ID 
```

**Comment by thanos-wandb** [comment]
Hi @Thunder-Volcano thank you for reaching out. Would it work for you to use `sed` in your bash script in order to parse `SWEEP_ID` as follows:
`wandb sweep sweep.yaml 2> >(sed -n 's/.*ID://p')` and then use this downstream? please let me know if you have further questions about this.

**Comment by Thunder-Volcano** [comment]
> Hi @Thunder-Volcano thank you for reaching out. Would it work for you to use `sed` in your bash script in order to parse `SWEEP_ID` as follows: `wandb sweep sweep.yaml 2> >(sed -n 's/.*ID://p')` and then use this downstream? please let me know if you have further questions about this.

Sorry, I use `sed` in my script, but it get some errors and did not work.
![image](https://github.com/wandb/wandb/assets/59018872/e2c6f932-5aa4-464f-a090-d55a7d3d3b2a)
The result is as follow:
`Syntax error: redirection unexpected`

**Comment by Thunder-Volcano** [comment]
> @Thunder-Volcano could you please use it as follows in your bash script: `SWEEP_ID=$(wandb sweep sweep.yaml 2> >(sed -n 's/.*ID://p'))`
> 
> Would it still not work for you?

Oh, it work in my script!
Actually, it is my bash problem. If I use `sh my_script.sh` in command, it will get the error `Syntax error: redirection unexpected`.
But I use `/bin/bash` instead of `sh`, it run successfully!
