### ISSUE TITLE
[CLI]: Azure OpenAI finetuning sync fails

### ISSUE THREAD

**Issue by bdytx5** [wandb/wandb#6653]
### Describe the bug

I was unable to sync my Azure OpenAI fine tuning run with Wandb. The error I got is shown below (azure openai api key not recognized).
Incorrect API key provided: a94affcd******* com/account/api-keys. (HTTP status code:
401)
Error --> "Incorrect API key provided: a94affcd******* com/account/api-keys. (HTTP status code:
401)"

Also, I have noticed the newest version of the OpenAI package does not contain the 'wandb sync' command, which is in disagreement with the Wandb docs ("Make sure you are using latest version of openai and wandb").

```python
# its CLI
```

```shell
OPENAI_API_KEY=myAPiKeyForAzure openai wandb sync --id ftjob-theID --project OpenAI-Fine-Tune
-> 

```

### Environment

WandB version:

OS:

Python version:

Versions of relevant libraries:

**Comment by Carlo-Argel** [comment]
Hi @bdytx5 ,

Thank you for reaching out. Right now, our team is working on updating to the latest version of OpenAI. You can check the [recent PR here](https://github.com/wandb/wandb/pull/6498). For now, you will need to ping your OpenAI Version to 0.28.0 until changes are fully released.

Regards,
Carlo Argel

**Comment by Carlo-Argel** [comment]
Hi @bdytx5 ,

We currently only support OpenAI Finetuning using SDK Python you can check it [here](https://twitter.com/ayushthakur0/status/1732479125967827193?s=20). The team is currently working for the Azure and we'll let you know of the results.

**Comment by bdytx5** [comment]
Looks like this has been resolved.

**Comment by MBakirWB** [comment]
Hi @bdytx5 , thank you for confirming that the issue has been resolved after the merge. Marking this resolved/closed
