### ISSUE TITLE
[CLI]: wandb server start failed

### ISSUE THREAD

**Issue by jianhai0527** [wandb/wandb#6655]
### Describe the bug

docker server start error

<img width="657" alt="image" src="https://github.com/wandb/wandb/assets/7888850/41b91912-4404-4dc1-9f71-5b9c71ef81cd">

### Environment

WandB version:

OS:

Python version:

Versions of relevant libraries:

**Comment by rsanandres-wandb** [comment]
Hello @jianhai0527 !

This looks to be an issue with your Docker package based on[ this thread.](https://github.com/containers/skopeo/issues/1501) Could you try upgrading docker to see if this fixes your problem? This seems to be particular to your environment and I can't see any `wandb` specific errors in the image that you have uploaded.
