### ISSUE TITLE
[CLI]: wandb.init issue KeyError: 'layout'

### ISSUE THREAD

**Issue by alexandreib** [wandb/wandb#6656]
### Describe the bug

Hello,
When initializing a new project, I got the error below.
I tried to upgrade: ipython and jupyter-lab, but the issue still persist.
it seems imcompatibility issues between diferent libs,
Alexandre

```python
import wandb

wandb.login()

wandb.init(
    project="test"
)
```

```shell
Traceback (most recent call last):
  File "/home/alexandre/.local/lib/python3.10/site-packages/traitlets/traitlets.py", line 645, in get
    # Using a context manager has a large runtime overhead, so we
KeyError: 'layout'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alexandre/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1166, in init
    wi.setup(kwargs)
  File "/home/alexandre/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 158, in setup
    self._setup_printer(settings=singleton._settings)
  File "/home/alexandre/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 144, in _setup_printer
    self.printer = get_printer(settings._jupyter)
  File "/home/alexandre/.local/lib/python3.10/site-packages/wandb/sdk/lib/printer.py", line 311, in get_printer
    return PrinterJupyter()
  File "/home/alexandre/.local/lib/python3.10/site-packages/wandb/sdk/lib/printer.py", line 230, in __init__
    self._progress = ipython.jupyter_progress_bar()
  File "/home/alexandre/.local/lib/python3.10/site-packages/wandb/sdk/lib/ipython.py", line 144, in jupyter_progress_bar
    return ProgressWidget(widgets, min=min, max=max)
  File "/home/alexandre/.local/lib/python3.10/site-packages/wandb/sdk/lib/ipython.py", line 103, in __init__
    self._progress = widgets.FloatProgress(min=min, max=max)
  File "/home/alexandre/.local/lib/python3.10/site-packages/ipywidgets/widgets/widget_float.py", line 26, in __init__
    super().__init__(**kwargs)
  File "/home/alexandre/.local/lib/python3.10/site-packages/ipywidgets/widgets/widget_description.py", line 35, in __init__
    super().__init__(*args, **kwargs)
  File "/home/alexandre/.local/lib/python3.10/site-packages/ipywidgets/widgets/widget.py", line 504, in __init__
  File "/home/alexandre/.local/lib/python3.10/site-packages/ipywidgets/widgets/widget.py", line 517, in open
  File "/home/alexandre/.local/lib/python3.10/site-packages/ipywidgets/widgets/widget.py", line 615, in get_state
    value = to_json(getattr(self, k), self)
  File "/home/alexandre/.local/lib/python3.10/site-packages/traitlets/traitlets.py", line 686, in __get__
    return self
  File "/home/alexandre/.local/lib/python3.10/site-packages/traitlets/traitlets.py", line 648, in get
    try:
  File "/home/alexandre/.local/lib/python3.10/site-packages/traitlets/traitlets.py", line 1752, in trait_defaults
    attrs = {"__module__": cls.__module__}
  File "/home/alexandre/.local/lib/python3.10/site-packages/traitlets/traitlets.py", line 616, in default
    )
  File "/home/alexandre/.local/lib/python3.10/site-packages/ipywidgets/widgets/trait_types.py", line 365, in make_dynamic_default
    js["year"],
  File "/home/alexandre/.local/lib/python3.10/site-packages/ipywidgets/widgets/widget_layout.py", line 86, in __init__
    super().__init__(**kwargs)
  File "/home/alexandre/.local/lib/python3.10/site-packages/ipywidgets/widgets/widget.py", line 504, in __init__
  File "/home/alexandre/.local/lib/python3.10/site-packages/ipywidgets/widgets/widget.py", line 535, in open
    self.comm = comm.create_comm(**args)
  File "/usr/local/lib/python3.10/dist-packages/comm/__init__.py", line 27, in _create_comm
    raise NotImplementedError("Cannot ")
NotImplementedError: Cannot 
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/.local/lib/python3.10/site-packages/traitlets/traitlets.py:645, in TraitType.get(self, obj, cls)
    644 try:
--> 645     value = obj._trait_values[self.name]
    646 except KeyError:
    647     # Check for a dynamic initializer.

KeyError: 'layout'

During handling of the above exception, another exception occurred:

NotImplementedError                       Traceback (most recent call last)
File ~/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py:1166, in init(job_type, dir, config, project, entity, reinit, tags, group, name, notes, magic, config_exclude_keys, config_include_keys, anonymous, mode, allow_val_change, resume, force, tensorboard, sync_tensorboard, monitor_gym, save_code, id, settings)
   1165 wi = _WandbInit()
-> 1166 wi.setup(kwargs)
   1167 assert wi.settings

File ~/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py:158, in _WandbInit.setup(self, kwargs)
    157 if singleton is not None:
--> 158     self._setup_printer(settings=singleton._settings)
    159     assert self.printer

File ~/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py:144, in _WandbInit._setup_printer(self, settings)
    143     return
--> 144 self.printer = get_printer(settings._jupyter)

File ~/.local/lib/python3.10/site-packages/wandb/sdk/lib/printer.py:311, in get_printer(_jupyter)
    310 if _jupyter:
--> 311     return PrinterJupyter()
    312 return PrinterTerm()

File ~/.local/lib/python3.10/site-packages/wandb/sdk/lib/printer.py:230, in PrinterJupyter.__init__(self)
    229 self._html = True
--> 230 self._progress = ipython.jupyter_progress_bar()

File ~/.local/lib/python3.10/site-packages/wandb/sdk/lib/ipython.py:144, in jupyter_progress_bar(min, max)
    143     assert hasattr(widgets, "FloatProgress")
--> 144     return ProgressWidget(widgets, min=min, max=max)
    145 except (ImportError, AssertionError):

File ~/.local/lib/python3.10/site-packages/wandb/sdk/lib/ipython.py:103, in ProgressWidget.__init__(self, widgets, min, max)
    102 self.widgets = widgets
--> 103 self._progress = widgets.FloatProgress(min=min, max=max)
    104 self._label = widgets.Label()

File ~/.local/lib/python3.10/site-packages/ipywidgets/widgets/widget_float.py:26, in _Float.__init__(self, value, **kwargs)
     25     kwargs['value'] = value
---> 26 super().__init__(**kwargs)

File ~/.local/lib/python3.10/site-packages/ipywidgets/widgets/widget_description.py:35, in DescriptionWidget.__init__(self, *args, **kwargs)
     34     del kwargs['description_tooltip']
---> 35 super().__init__(*args, **kwargs)

File ~/.local/lib/python3.10/site-packages/ipywidgets/widgets/widget.py:504, in Widget.__init__(self, **kwargs)
    503 Widget._call_widget_constructed(self)
--> 504 self.open()

File ~/.local/lib/python3.10/site-packages/ipywidgets/widgets/widget.py:517, in Widget.open(self)
    516 if self.comm is None:
--> 517     state, buffer_paths, buffers = _remove_buffers(self.get_state())
    519     args = dict(target_name='jupyter.widget',
    520                 data={'state': state, 'buffer_paths': buffer_paths},
    521                 buffers=buffers,
    522                 metadata={'version': __protocol_version__}
    523                 )

File ~/.local/lib/python3.10/site-packages/ipywidgets/widgets/widget.py:615, in Widget.get_state(self, key, drop_defaults)
    614 to_json = self.trait_metadata(k, 'to_json', self._trait_to_json)
--> 615 value = to_json(getattr(self, k), self)
    616 if not drop_defaults or not self._compare(value, traits[k].default_value):

File ~/.local/lib/python3.10/site-packages/traitlets/traitlets.py:686, in TraitType.__get__(self, obj, cls)
    685 else:
--> 686     return self.get(obj, cls)

File ~/.local/lib/python3.10/site-packages/traitlets/traitlets.py:648, in TraitType.get(self, obj, cls)
    646 except KeyError:
    647     # Check for a dynamic initializer.
--> 648     default = obj.trait_defaults(self.name)
    649     if default is Undefined:

File ~/.local/lib/python3.10/site-packages/traitlets/traitlets.py:1752, in HasTraits.trait_defaults(self, *names, **metadata)
   1751 if len(names) == 1 and len(metadata) == 0:
-> 1752     return self._get_trait_default_generator(names[0])(self)
   1754 trait_names = self.trait_names(**metadata)

File ~/.local/lib/python3.10/site-packages/traitlets/traitlets.py:616, in TraitType.default(self, obj)
    615 elif hasattr(self, "make_dynamic_default"):
--> 616     return self.make_dynamic_default()
    617 else:
    618     # Undefined will raise in TraitType.get

File ~/.local/lib/python3.10/site-packages/ipywidgets/widgets/trait_types.py:365, in InstanceDict.make_dynamic_default(self)
    364 def make_dynamic_default(self):
--> 365     return self.klass(*(self.default_args or ()),
    366                       **(self.default_kwargs or {}))

File ~/.local/lib/python3.10/site-packages/ipywidgets/widgets/widget_layout.py:86, in Layout.__init__(self, **kwargs)
     84         kwargs.setdefault(f'border_{side}', border)
---> 86 super().__init__(**kwargs)

File ~/.local/lib/python3.10/site-packages/ipywidgets/widgets/widget.py:504, in Widget.__init__(self, **kwargs)
    503 Widget._call_widget_constructed(self)
--> 504 self.open()

File ~/.local/lib/python3.10/site-packages/ipywidgets/widgets/widget.py:535, in Widget.open(self)
    533         return Comm(**kwargs)
--> 535 self.comm = create_comm(**args)

File /usr/local/lib/python3.10/dist-packages/comm/__init__.py:27, in _create_comm(*args, **kwargs)
     23 """Create a Comm.
     24 
     25 This method is intended to be replaced, so that it returns your Comm instance.
     26 """
---> 27 raise NotImplementedError("Cannot ")

NotImplementedError: Cannot 

The above exception was the direct cause of the following exception:

Error                                     Traceback (most recent call last)
Cell In[9], line 5
      1 import wandb
      3 wandb.login()
----> 5 wandb.init()

File ~/.local/lib/python3.10/site-packages/wandb/sdk/wandb_init.py:1208, in init(job_type, dir, config, project, entity, reinit, tags, group, name, notes, magic, config_exclude_keys, config_include_keys, anonymous, mode, allow_val_change, resume, force, tensorboard, sync_tensorboard, monitor_gym, save_code, id, settings)
   1206             wandb.termerror("Abnormal program exit")
   1207             os._exit(1)
-> 1208         raise Error("An unexpected error occurred") from error_seen
   1209 return run

Error: An unexpected error occurred
```

### Environment

WandB version: 0.15.12
OS: Ubuntu 22.04.2 LTS
Python version: Python 3.10.12
Versions of relevant libraries:
Package                           Version
--------------------------------- ---------------------
absl-py                           1.3.0
aiofiles                          22.1.0
aiohttp                           3.8.3
aiohttp-retry                     2.8.3
aiosignal                         1.3.1
aiosqlite                         0.18.0
alembic                           1.12.0
amqp                              5.1.1
ansiwrap                          0.8.4
antlr4-python3-runtime            4.9.3
anyio                             4.1.0
appdirs                           1.4.4
apturl                            0.5.2
arch                              6.1.0
argon2-cffi                       23.1.0
argon2-cffi-bindings              21.2.0
arrow                             1.3.0
astroid                           2.15.5
astropy                           5.3.1
asttokens                         2.4.1
astunparse                        1.6.3
async-lru                         2.0.4
async-timeout                     4.0.2
asyncssh                          2.12.0
atpublic                          3.1.1
attrs                             23.1.0
autopep8                          2.0.2
Babel                             2.13.1
backcall                          0.2.0
beautifulsoup4                    4.12.2
billiard                          3.6.4.0
black                             22.12.1.dev8+g7d062ec
bleach                            6.1.0
blinker                           1.4
boto3                             1.26.27
botocore                          1.29.27
bravado                           11.0.3
bravado-core                      5.17.1
Brlapi                            0.8.3
cachetools                        5.2.0
catboost                          1.2.1
category-encoders                 2.6.0
celery                            5.2.7
certifi                           2023.11.17
cffi                              1.16.0
chardet                           4.0.0
charset-normalizer                3.3.2
click                             8.0.3
click-didyoumean                  0.3.0
click-plugins                     1.1.1
click-repl                        0.2.0
cloudpickle                       2.2.1
cmaes                             0.10.0
cmake                             3.26.3
colorama                          0.4.4
colorlog                          6.7.0
colorlover                        0.3.0
comm                              0.2.0
command-not-found                 0.3
commonmark                        0.9.1
configobj                         5.0.6
contourpy                         1.0.6
cryptography                      3.4.8
cufflinks                         0.17.3
cupshelpers                       1.0
cvxopt                            1.3.1
cvxpy                             1.3.2
cycler                            0.11.0
dbus-python                       1.2.18
DBUtils                           3.0.2
dcor                              0.6
debugpy                           1.8.0
decorator                         5.1.1
defer                             1.0.6
defusedxml                        0.7.1
dictdiffer                        0.9.0
dill                              0.3.6
diskcache                         5.4.0
distro                            1.7.0
distro-info                       1.1build1
docker-pycreds                    0.4.0
docstring-to-markdown             0.12
dpath                             2.1.2
dulwich                           0.20.50
dvc                               2.37.0
dvc-data                          0.28.4
dvc-http                          2.27.2
dvc-objects                       0.14.0
dvc-render                        0.0.15
dvc-task                          0.1.6
dvclive                           1.1.2
ecos                              2.0.10
entrypoints                       0.4
exceptiongroup                    1.2.0
exchange-calendars                4.2.8
executing                         2.0.1
fastjsonschema                    2.19.0
filelock                          3.8.2
flake8                            6.0.0
flatbuffers                       23.5.26
flatten-dict                      0.4.2
flufl.lock                        7.1.1
fonttools                         4.38.0
fqdn                              1.5.1
frozenlist                        1.3.3
fsspec                            2022.11.0
funcy                             1.17
future                            0.18.2
gast                              0.4.0
gitdb                             4.0.10
GitPython                         3.1.40
google-auth                       2.15.0
google-auth-oauthlib              1.0.0
google-pasta                      0.2.0
gpg                               1.16.0-unknown
grandalf                          0.6
graphviz                          0.20.1
greenlet                          3.0.0
grpcio                            1.51.1
h11                               0.12.0
h5py                              3.7.0
hmmlearn                          0.3.0
httpcore                          0.15.0
httplib2                          0.20.2
httpx                             0.23.0
hydra-core                        1.3.2
ibapi                             10.19.1
idna                              3.6
importlib-metadata                6.6.0
inflection                        0.5.1
ipykernel                         6.27.1
ipympl                            0.9.3
ipython                           8.18.1
ipython-genutils                  0.2.0
ipywidgets                        8.1.1
isoduration                       20.11.0
isort                             5.12.0
iterative-telemetry               0.0.6
jax                               0.4.8
jedi                              0.19.1
jeepney                           0.7.1
jenkspy                           0.3.3
Jinja2                            3.1.2
jmespath                          1.0.1
joblib                            1.2.0
json5                             0.9.14
jsonpointer                       2.4
jsonref                           1.0.1
jsonschema                        4.20.0
jsonschema-specifications         2023.11.2
jumpdiff                          0.4.2
jupyter                           1.0.0
jupyter_client                    8.6.0
jupyter-console                   6.6.3
jupyter-contrib-core              0.4.2
jupyter-contrib-nbextensions      0.7.0
jupyter_core                      5.5.0
jupyter-events                    0.9.0
jupyter-highlight-selected-word   0.2.0
jupyter-lsp                       2.2.1
jupyter-nbextensions-configurator 0.6.1
jupyter_server                    2.11.1
jupyter_server_fileid             0.8.0
jupyter_server_terminals          0.4.4
jupyter_server_ydoc               0.6.1
jupyter-ydoc                      0.2.2
jupyterlab                        4.0.9
jupyterlab_pygments               0.3.0
jupyterlab_server                 2.25.2
jupyterlab-widgets                3.0.9
kaggle                            1.5.16
keras                             2.12.0
keyring                           23.5.0
kiwisolver                        1.4.4
kombu                             5.2.4
korean-lunar-calendar             0.3.1
language-selector                 0.1
launchpadlib                      1.10.16
lazr.restfulclient                0.14.4
lazr.uri                          1.0.6
lazy-object-proxy                 1.9.0
libclang                          14.0.6
lightgbm                          3.3.2
lit                               16.0.1
llvmlite                          0.39.1
louis                             3.20.0
lxml                              4.9.1
macaroonbakery                    1.3.1
Mako                              1.2.4
MAPIE                             0.6.5
Markdown                          3.4.1
MarkupSafe                        2.1.3
matplotlib                        3.6.2
matplotlib-inline                 0.1.6
mccabe                            0.7.0
mistune                           3.0.2
ml-dtypes                         0.2.0
monotonic                         1.6
more-itertools                    8.10.0
mpmath                            1.3.0
msgpack                           1.0.4
multidict                         6.0.3
multitasking                      0.0.11
mypy-extensions                   0.4.3
nanotime                          0.5.2
Nasdaq-Data-Link                  1.0.4
natsort                           8.0.2
nbclassic                         0.4.8
nbclient                          0.9.0
nbconvert                         7.11.0
nbformat                          5.9.2
neptune-client                    0.16.14
nest-asyncio                      1.5.8
netifaces                         0.11.0
networkx                          2.8.8
nodejs-bin                        18.4.0a4
notebook                          7.0.6
notebook_shim                     0.2.3
numba                             0.56.4
numpy                             1.23.5
nvidia-cublas-cu11                11.10.3.66
nvidia-cuda-cupti-cu11            11.7.101
nvidia-cuda-nvrtc-cu11            11.7.99
nvidia-cuda-runtime-cu11          11.7.99
nvidia-cudnn-cu11                 8.5.0.96
nvidia-cufft-cu11                 10.9.0.58
nvidia-curand-cu11                10.2.10.91
nvidia-cusolver-cu11              11.4.0.1
nvidia-cusparse-cu11              11.7.4.91
nvidia-nccl-cu11                  2.14.3
nvidia-nvtx-cu11                  11.7.91
oauthlib                          3.2.0
olefile                           0.46
omegaconf                         2.3.0
opt-einsum                        3.3.0
optuna                            3.3.0
osqp                              0.6.2.post8
overrides                         7.4.0
packaging                         23.2
panda                             0.3.1
pandas                            2.0.3
pandas-market-calendars           4.2.1
pandocfilters                     1.5.0
papermill                         2.4.0
parso                             0.8.3
pathspec                          0.9.0
pathtools                         0.1.2
patsy                             0.5.3
pexpect                           4.9.0
pickleshare                       0.7.5
Pillow                            9.0.1
pip                               23.3.1
platformdirs                      4.0.0
plotly                            5.13.0
pluggy                            1.0.0
polars                            0.19.3
prometheus-client                 0.19.0
prompt-toolkit                    3.0.41
protobuf                          4.22.3
psutil                            5.9.6
ptyprocess                        0.7.0
pure-eval                         0.2.2
pyarrow                           13.0.0
pyasn1                            0.4.8
pyasn1-modules                    0.2.8
pybind11                          2.11.1
pycairo                           1.20.1
pycodestyle                       2.10.0
pycparser                         2.21
pycups                            2.0.1
pydocstyle                        6.3.0
pydot                             1.4.2
pyee                              9.0.4
pyerfa                            2.0.0.3
pyflakes                          3.0.1
pygit2                            1.11.1
Pygments                          2.17.2
PyGObject                         3.42.1
pygtrie                           2.5.0
pyhumps                           3.0.2
PyJWT                             2.3.0
pykalman                          0.9.5
pylint                            2.17.4
pyluach                           2.2.0
pymacaroons                       0.13.0
pymannkendall                     1.4.3
pymssql                           2.2.7
PyMySQL                           1.0.3
PyNaCl                            1.5.0
pyparsing                         2.4.7
pyportfolioopt                    1.5.4
pyRFC3339                         1.1
pyrsistent                        0.19.2
python-apt                        2.4.0+ubuntu1
python-dateutil                   2.8.2
python-debian                     0.1.43ubuntu1
python-json-logger                2.0.7
python-lsp-jsonrpc                1.0.0
python-lsp-server                 1.7.3
python-slugify                    8.0.1
pytoolconfig                      1.2.5
pytorch-tabnet                    4.1.0
pytrends                          4.8.0
pytz                              2022.1
PyWavelets                        1.4.1
pyxdg                             0.27
PyYAML                            6.0.1
pyzmq                             25.1.1
qdldl                             0.1.5.post2
qtconsole                         5.5.1
QtPy                              2.4.1
referencing                       0.31.1
refinitiv-data                    1.2.0
reportlab                         3.6.8
requests                          2.31.0
requests-oauthlib                 1.3.1
rfc3339-validator                 0.1.4
rfc3986                           1.5.0
rfc3986-validator                 0.1.1
rfc3987                           1.3.8
rich                              12.6.0
Riskfolio-Lib                     4.4.0
rope                              1.8.0
rpds-py                           0.13.2
rsa                               4.9
ruamel.yaml                       0.17.21
ruamel.yaml.clib                  0.2.7
ruptures                          1.1.8
s3transfer                        0.6.0
scapy                             2.5.0
scikit-digital-health             0.11.7
scikit-learn                      1.1.3
scipy                             1.9.3
scmrepo                           0.1.4
scs                               3.2.2
seaborn                           0.13.0
SecretStorage                     3.3.1
Send2Trash                        1.8.2
sentry-sdk                        1.37.1
setproctitle                      1.3.3
setuptools                        68.0.0
shap                              0.42.1
shortuuid                         1.0.11
shtab                             1.5.8
simplejson                        3.18.0
six                               1.16.0
slicer                            0.0.7
smmap                             5.0.0
sniffio                           1.3.0
snowballstemmer                   2.2.0
soupsieve                         2.5
SQLAlchemy                        2.0.21
ssh-import-id                     5.11
stack-data                        0.6.3
statsmodels                       0.13.5
svolfit                           0.0.8
swagger-spec-validator            3.0.3
sympy                             1.11.1
systemd-python                    234
TA-Lib                            0.4.25
tabulate                          0.9.0
tenacity                          8.0.1
tensorboard                       2.12.3
tensorboard-data-server           0.7.0
tensorboard-plugin-wit            1.8.1
tensorflow                        2.12.0
tensorflow-addons                 0.18.0
tensorflow-cpu                    2.12.0
tensorflow-estimator              2.12.0
tensorflow-io-gcs-filesystem      0.28.0
tensorflow-ranking                0.5.3
tensorflow-serving-api            2.13.0
termcolor                         2.1.1
terminado                         0.18.0
text-unidecode                    1.3
textwrap3                         0.9.2
threadpoolctl                     3.1.0
thundersvm                        0.3.12
tinycss2                          1.2.1
tokenize-rt                       5.0.0
tomli                             2.0.1
tomlkit                           0.11.6
toolz                             0.12.0
torch                             2.0.0
torchaudio                        2.0.1
torchvision                       0.15.1
tornado                           6.4
tqdm                              4.64.1
traitlets                         5.14.0
trash-cli                         0.17.1.14
triton                            2.0.0
tslearn                           0.5.3.2
typeguard                         2.13.3
types-python-dateutil             2.8.19.14
typing_extensions                 4.8.0
tzdata                            2023.3
ubuntu-advantage-tools            8001
ubuntu-drivers-common             0.0.0
ufw                               0.36.1
ujson                             5.8.0
unattended-upgrades               0.1
uri-template                      1.3.0
urllib3                           2.1.0
vboxapi                           1.0
vine                              5.0.0
voila                             0.4.0
voluptuous                        0.13.1
wadllib                           1.3.6
wandb                             0.15.12
watchdog                          2.1.9
wcwidth                           0.2.12
webcolors                         1.13
webencodings                      0.5.1
websocket-client                  1.6.4
websockets                        10.4
Werkzeug                          2.2.2
whatthepatch                      1.0.5
wheel                             0.37.1
widgetsnbextension                4.0.9
wrapt                             1.14.1
wxPython                          4.0.7
xdg                               5
xgboost                           1.7.1
xkit                              0.0.0
XlsxWriter                        3.1.2
y-py                              0.5.9
yapf                              0.40.0
yarl                              1.8.2
yfinance                          0.1.87
ypy-websocket                     0.8.2
zc.lockfile                       2.0
zipp                              1.0.0

**Comment by rsanandres-wandb** [comment]
Hello! I am unable to reproduce this issue in a Jupyter Notebook and in a Colab. Could you try upgrading your `wandb` version to see if that helps? If not, could you provide me any more context on your setup? It seems that `traitlets` is also having trouble loading so could you also upgrade that package in case it is corrupted?

**Comment by sienkus** [comment]
I also run into the same error today

`wandb.init(project="SLT of Double Descent",
           config = {'epochs': epochs,
                     'classes': num_classes,
                     'learning_rate': lr,
                     'use_label_noise': use_label_noise,
                     'noise_level': frac_label_noise,
                     'dataset': "CIFAR10",
                     'architecture': "ResNet18",
                     'pytorch_resnet_model': pytorch_default_resnet,
                     'model_width': model_width,
                     'augmented': augmented,
                     'adam optimizer': use_adam_op}
                     )

wandb.watch(model)
config = wandb.config
![Screenshot 2024-01-29 at 1 34 05 PM](https://github.com/wandb/wandb/assets/88231368/ed71c5e0-8ae2-403e-8b87-feaf03bea1f2)
`
