### ISSUE TITLE
[App]: Displaying/Hiding runs impact the displayed metrics for other runs

### ISSUE THREAD

**Issue by AurelienGauffre** [wandb/wandb#6672]
### Current Behavior

Displaying a new group of runs affects the displayed metrics of existing groups (cf. screenshots below). Does Wandb have a limit on the total number of runs it can average in Group ? 

### Screenshots

![image](https://github.com/wandb/wandb/assets/33651103/181b6314-8d9d-4d56-931f-074620f6e115)
![image](https://github.com/wandb/wandb/assets/33651103/f0347efe-71b7-4bee-bcd9-11b5679ecf85)
As observed in the two screenshots, the mean test accuracy for the 10-epoch group increased from 86% to 91% when displaying the 20-epoch group, although it should naturally stay the exact same.

### Environment

OS: Ubuntun 20.04
Browsers: Chrome 
Version: 120.0.6099.62

**Comment by JoanaMarieL** [comment]
Hello @AurelienGauffre ,

I understand, could you please check this option[Sampled Runs] on your end and select the max value:
![Sample run option](https://github.com/wandb/wandb/assets/147673991/d1bcee32-088f-4fc8-bb3d-e7e269a23e97)
And if it is possible to check your workspace by sharing the link for us to investigate further.

Thanks.

**Comment by JoanaMarieL** [comment]
Hi @AurelienGauffre Aurelien, 
We would like to follow up on the suggestion we asked if that works for you?

**Comment by JoanaMarieL** [comment]
Hi @AurelienGauffre , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by AurelienGauffre** [comment]
Thank you for your response and the solution you provided. It's now functioning correctly. I wanted to mention that when I initially tried your solution last week, the button wasn’t appearing at all. Even now, there's a noticeable small delay before the button becomes visible. I've included screenshots illustrating this:
When I am opening the grouping menu :
![image](https://github.com/wandb/wandb/assets/33651103/fa3888f7-f9c3-457d-9017-e9f3cbeb964f)
After waiting 3 seconds :
![image](https://github.com/wandb/wandb/assets/33651103/1d4d2855-8fb6-45af-a30c-761333a8c55b)

Thank you !
