### ISSUE TITLE
[App]: "The operation is insecure. An application error occurred." randomly appears when watching a plot in full screen.

### ISSUE THREAD

**Issue by hkproj** [wandb/wandb#6682]
### Current Behavior

I keep seeing the following screen when watching a full-screen plot of the loss. It happens randomly, sometimes right after opening the plot, sometimes after 10-20s.

<img width="1280" alt="firefox_4y0A1lXnvr" src="https://github.com/wandb/wandb/assets/388315/6870a9dd-eed4-4c2b-8bcd-6b9b047ffb91">

Example of full-screen plot:

<img width="1280" alt="firefox_P0WpqPfSzP" src="https://github.com/wandb/wandb/assets/388315/44ab9b62-3870-4157-af9f-423aa102d6e2">

### Expected Behavior

No error while watching full-screen plots.

### Steps To Reproduce

Open a plot in full-screen mode.

### Environment

OS: Windows 11 Pro

Browsers: Firefox 120.0.1 (64-bit)

Version:

**Comment by thanos-wandb** [comment]
Hi @hkproj I wanted to follow up with you here and see if you're still experiencing this issue.

**Comment by thanos-wandb** [comment]
Hi @hkproj  since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
