### ISSUE TITLE
[App]: Plot points at the mouse position overlapped by a floating legend

### ISSUE THREAD

**Issue by iperminov-mythic** [wandb/wandb#6693]
### Current Behavior
The top plot shows the current behavior - the legend tooltip is right on the top of the current mouse position and plot points at the current position are not visible. 
<img width="328" alt="Screenshot 2023-12-10 114750" src="https://github.com/wandb/wandb/assets/85903057/8eeb6fdc-1015-4256-845c-0e7297252325">

### Expected Behavior

The bottom plot shows the correct behavior - the legend box does not overlap the current mouse position.
My guess is the "Press CMD-C or CTRL-C to copy this data" tip may be the cause of this issue. It make the legend wider, but probably is not accounted for in box size/position computations.

### Environment

OS: Windows

Browsers: Firefox 120

**Comment by fmamberti-wandb** [comment]
Hi @iperminov-mythic, thank you for reporting this.

I will raise this internally and we will keep you updated.

**Comment by fmamberti-wandb** [comment]
Hi @iperminov-mythic I wanted to follow up on this and let you know that we released a fix for this issue you reported a few months back.
