### ISSUE TITLE
Wandb automatically disconnects after startup without any error logs

### ISSUE THREAD

**Issue by AsuraSunshine** [wandb/wandb#6702]
I ran the code using a pre trained model locally and connected to Wandb. After wandb initialization, it automatically disconnects without any error logs.

**Comment by AsuraSunshine** [comment]
Reinitialize using the following code, but not using it

experiment = wandb.init(project='myProjet', resume='allow', anonymous='must',settings=wandb.Settings(start_method="thread"))

**Comment by rsanandres-wandb** [comment]
Hello @AsuraSunshine !

Were you able to fix the issue or are you still running into errors? If you are still running into errors, could you send a code snippet as well as the error stack trace so I can look into it?

**Comment by AsuraSunshine** [comment]
Thank you for your help, I have already resolved it. Previously, the loop body did not work, resulting in Wandb not being able to run continuously.
