### ISSUE TITLE
[App]: launch

### ISSUE THREAD

**Issue by xiaodongmei** [wandb/wandb#6719]
### Current Behavior

![image](https://github.com/wandb/wandb/assets/40419295/d1149288-82c9-4c7c-86e3-1d76adde3d87)

### Expected Behavior

wandb 创建launch报错 Variable "templateVariables" has invalid value null. Expected type "JSONString!", found null.

### Environment

OS:

Browsers:

Version:

**Comment by rsanandres-wandb** [comment]
Hello @xiaodongmei !

I am not completely following what error occurred. Did you get the message `Expected type "JSONString!", found null.` in the UI or within the launch job? Also, in your screenshot, I am unable to see "templateVariables". Where was this input into?
