### ISSUE TITLE
[Q]wandb has been disabled. But still wandb.sdk.service.service.ServiceStartTimeoutError: Timed out waiting for wandb service to start after 30.0 seconds.

### ISSUE THREAD

**Issue by Liu0329** [wandb/wandb#6720]
That drives me crazy. Why ! My server cannot connect internet.

My script:
```
WANDB_DISABLE_SERVICE=True
WANDB_MODE=disabled python test.py
```

**Comment by Carlo-Argel** [comment]
Hi @Liu0329 ,

Thank you for reaching out. Happy to assist you with this one. Can you provide what is the WandB version you are using?

**Comment by Liu0329** [comment]
My wandb is 0.14.  Now the problem is solved by adding `os.environ["WANDB_DISABLED"] = "true"` in the code:

Below does not work:
```
WANDB_DISABLED=true
WANDB_MODE=disabled python test.py
```
And before, `WANDB_MODE=disabled python test.py` worked on another machine, but not on the current machine.

**Comment by Carlo-Argel** [comment]
Hi @Liu0329 ,

I need more time to investigate this for you. We have try to reproduce the issue that you were reporting with the first code snippet provide and it works as expected, no wandb run will be executed.  Could you also explain to us what you meant by "My server cannot connect internet?". Wandb expects a network connection to communicate over with our backend. In the meantime can you try updating your WandB version to the latest version (version 16) and then re-run your test.

**Comment by Liu0329** [comment]
The server cannot connect internet means that I cannot use Wandb and have to disable it.

**Comment by Carlo-Argel** [comment]
Hi @Liu0329 ,Thank you for letting us know that you cannot connect to the internet. We have tested your initial approach against our version of wandb and everything works as expected. I noticed that you mentioned that the problem was solve, I'll mark this as solved, but please don't hesitate to reach back again anytime you need more assistance.
