### ISSUE TITLE
Trouble regarding yolo training integration with add_wandb_callback function

### ISSUE THREAD

**Issue by Tarislada** [wandb/wandb#6726]
### Current Behavior

When running training with yolo with the code 

model = YOLO('YOLO_custom/Models/KH_noseperfect_v3b.pt')
add_wandb_callback(model, enable_model_checkpointing=True)

Error regarding the add_wandb_callback happens. I don't think this happened a few weeks ago, and I did recently reinstalled wandb package via pip on the environment. Also, I had to change some lines regarding https://github.com/wandb/wandb/issues/6566
The following is the error message I see on the terminal.

Starting training for 2000 epochs...

      Epoch    GPU_mem   box_loss  pose_loss  kobj_loss   cls_loss   dfl_loss  Instances       Size
     1/2000      7.42G      4.289      12.92     0.8651      5.529      7.089         36       1088: 100%|██████████| 13/13 [00:05<00:00,  2.51it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95):   0%|          | 0/2 [00:00<?, ?it/s]*****/mambaforge/envs/YOLO/lib/python3.11/site-packages/ultralytics/utils/metrics.py:163: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  sigma = torch.tensor(sigma, device=kpt1.device, dtype=kpt1.dtype)  # (17, )
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Pose(P          R      mAP50  mAP50-95): 100%|██████████| 2/2 [00:00<00:00,  6.18it/s]
                   all         50        100          0          0          0          0          0          0          0          0
Traceback (most recent call last):
  File "*****/YOLOprojects/YOLO_custom/run.py", line 12, in <module>
    model.train(data=data, imgsz=1080, epochs=2000, patience=2000, pose=17) # KH-traincode train model with data. many other arguments are available https://docs.ultralytics.com/cfg/
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "*****/mambaforge/envs/YOLO/lib/python3.11/site-packages/ultralytics/engine/model.py", line 337, in train
    self.trainer.train()
  File "*****/mambaforge/envs/YOLO/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 195, in train
    self._do_train(world_size)
  File "*****/mambaforge/envs/YOLO/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 402, in _do_train
    self.run_callbacks('on_fit_epoch_end')
  File "*****/mambaforge/envs/YOLO/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 160, in run_callbacks
    callback(self)
  File "*****/mambaforge/envs/YOLO/lib/python3.11/site-packages/wandb/integration/ultralytics/callback.py", line 256, in on_fit_epoch_end
    self.train_validation_table = plot_pose_validation_results(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'plot_pose_validation_results' is not defined

### Environment

OS: Linux Ubuntu 22.04

Browsers:

Version: 0.16.1

**Comment by luisbergua** [comment]
Hi @Tarislada, thanks for flagging this! Looks like you're on `wandb==0.16.1`, would you mind sharing which was the last version that was working for you? There were some changes on the integration (see our releases [notes](https://github.com/wandb/wandb/releases)) so those might be affecting here

**Comment by Tarislada** [comment]
My mistake; it was never working with add_wandb_callback in the first place. I went ahead and checked all versions from 0.15.10 to 0.16.1; none of them were working. Also, all versions had two errors. First one is regarding the line 63 and 64 of callback.py on wandb.integration.ultralytics were it states
```
except ImportError as e:
    wandb.error(e)
```
it should be wandb.Error, not error. 
The second was regarding line 45, importing RANK from ultralytics.utils.
it shouldn't be from ultralytics.yolo.utils, but from ultralytics.utils as there were changes to the ultralytics library.

**Comment by luisbergua** [comment]
Hi @Tarislada, thanks for flagging this!
* First one has been fixed, see [here](https://github.com/wandb/wandb/blob/373c1ff3ae2fef79cc32fedbecc6c4ee9c841639/wandb/integration/ultralytics/callback.py#L68)
* For the second one, [there's a try/except block](https://github.com/wandb/wandb/blob/373c1ff3ae2fef79cc32fedbecc6c4ee9c841639/wandb/integration/ultralytics/callback.py#L46) to import from `ultralytics.utils` in case there's a `ModuleNotFoundError`

So this should work as expected now, please let us know if you still see any issues!
