### ISSUE TITLE
Question about resume training automatically creating new items

### ISSUE THREAD

**Issue by op-newman** [wandb/wandb#6727]
I am executing the training of a model, during which I interrupt the training For example, I interrupt the model at epoch=30 The model provides a method to RESUME the training, then I am unmodified, wandb creates a new project to store these parameter plots, and I want to link the training after RESUME in the result of the first training, what can I do to achieve this.

**Comment by Carlo-Argel** [comment]
Hi @op-newman 
Happy to help here. Allow me some time to double-check this and I'll get back to you for updates.

**Comment by MBakirWB** [comment]
Hi @op-newman , 

It is correct that wandb training can be resumed, however, you cannot resume a run and log it's data to a new project as resuming is directly tied to the project and run id. Could you expand on your workflow here and what you intend to do? If you could list out your process in steps, 1,2,3,4 ... that would be very helpful to follow the request. Thanks

**Comment by Carlo-Argel** [comment]
Hi @op-newman ,

I just want to follow up if you still need more assistance regarding this concern.

Regards,
Carlo Argel

**Comment by Carlo-Argel** [comment]
Hi @op-newman , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
