### ISSUE TITLE
[Q] logging all processes in DDP

### ISSUE THREAD

**Issue by thisishale** [wandb/wandb#6733]
I am trying to log all processes in DDP. Reading the documentation, I did it this way:

```
wandb.require("service")
wandb_log = wandb.init(project=args.project_name, 
                                    config={'args': vars(args)},
                                    id=str(datetime.now().strftime(fmt)),
                                    name=args.name, # +'_'+args.job_id,
                                    tags=[args.project_name, args.name, args.dataset, args.cluster],
                                    resume="None",
                                    group="DDP",
                                    mode=mode
                                    )
mp.spawn(train_val, nprocs=args.gpus, args=(args,wandb_log))
```

But only one of the processes(out of 2) gets logged meaning that I only have one log in the DDP group. What am I doing wrong here?

**Comment by umakrishnaswamy** [comment]
@thisishale - thanks for writing in. i noticed you're setting a run id within your init call. sometimes unexpected behavior can occur when the id isn't unique for each process - could you try running the following and let me know if it produces two wandb runs?

`wandb.require("service")
wandb_log = wandb.init(project=args.project_name, 
                                    config={'args': vars(args)},
                                    name=args.name, # +'_'+args.job_id,
                                    tags=[args.project_name, args.name, args.dataset, args.cluster],
                                    resume="None",
                                    group="DDP",
                                    mode=mode
                                    )
mp.spawn(train_val, nprocs=args.gpus, args=(args,wandb_log))`

**Comment by kptkin** [comment]
@thisishale why do you think that you only have one process?
- The way you use it will mean that all the processes will log to the same run. 
- If you want a different run in each process you don't need to pass the run object (`wandb_log`) when you spawn a new process. When you pass the run object wandb will log all to the same run. You would do something like this instead (Assuming that is the behavior you want): 
```
def train_val(args):
    ....
    wandb_log = wandb.init(project=args.project_name, 
                                    config={'args': vars(args)},
                                    name=args.name, # +'_'+args.job_id,
                                    tags=[args.project_name, args.name, args.dataset, args.cluster],
                                    resume="None",
                                    group="DDP",
                                    mode=mode
                                    )
mp.spawn(train_val, nprocs=args.gpus, args=(args))
```
- Also staring from wandb>=0.13.0 we turned service on by default. So if you are using a wandb version >=0.13.0, you can remove `wandb.require("service")` from your code.

**Comment by umakrishnaswamy** [comment]
hey @thisishale - since we have not heard back from you we are going to close this thread, but feel free to write back in if you'd like to open it back up

**Comment by thisishale** [comment]
> @thisishale why do you think that you only have one process?
> 
> * The way you use it will mean that all the processes will log to the same run.
> * If you want a different run in each process you don't need to pass the run object (`wandb_log`) when you spawn a new process. When you pass the run object wandb will log all to the same run. You would do something like this instead (Assuming that is the behavior you want):
> 
> ```
> def train_val(args):
>     ....
>     wandb_log = wandb.init(project=args.project_name, 
>                                     config={'args': vars(args)},
>                                     name=args.name, # +'_'+args.job_id,
>                                     tags=[args.project_name, args.name, args.dataset, args.cluster],
>                                     resume="None",
>                                     group="DDP",
>                                     mode=mode
>                                     )
> mp.spawn(train_val, nprocs=args.gpus, args=(args))
> ```
> 
> * Also staring from wandb>=0.13.0 we turned service on by default. So if you are using a wandb version >=0.13.0, you can remove `wandb.require("service")` from your code.
> * Also you don't need to pass ` resume="None"` if you don't want to resume a run. By default wandb doesn't resume runs.

Thank you so much. I will try this.

**Comment by MBakirWB** [comment]
Hi @thisishale , we wanted to check in to see if after making the recommended modifications you are experiencing other issues or have any questions for us? Thanks

**Comment by MBakirWB** [comment]
Hi @thisishale , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
