### ISSUE TITLE
[App]: Zoom not working

### ISSUE THREAD

**Issue by Natithan** [wandb/wandb#6738]
### Current Behavior

Dragging to select an area within a plot normally zooms to that area, but that doesn't work now. See video. 

https://github.com/wandb/wandb/assets/17345374/e8ded753-8558-4722-9934-808ef4128eb7

### Expected Behavior

It should zoom to the dragged area.

### Steps To Reproduce

1. Go to my wandb worksapce
2. Try to select an area on any plot
3. See it doesn't do anythin

### Environment

OS: Windows 10

Browsers: Edge, Firefox and Chrome all show the behaviour

Version:

**Comment by rsanandres-wandb** [comment]
Hello @Natithan !

Happy to help!

Our App team just released some fixes to this today. Could you let me know if this is still occurring for you and I would be happy to look into it?

**Comment by Natithan** [comment]
Seems to work again! Thanks!

**Comment by dmwit** [comment]
Hm, still doesn't seem to be working for me. I deleted my browser cache to make sure I had the most recent version of the page.

Chromium 115.0.5790.170 (Official Build) Fedora Project (64-bit)

**Comment by henrik-schopmans** [comment]
For me, zoom works for individual runs, but when viewing multiple runs together in the Workspace, it doesn't work as described above.

**Comment by NiccoloCavagnero** [comment]
> For me, zoom works for individual runs, but when viewing multiple runs together in the Workspace, it doesn't work as described above.

Same here.

**Comment by misterguick** [comment]
Zoom on multiple runs doesn't work properly. It zooms only a bit but not on the correct area. Zoom on a single run works perfectly.

**Comment by sydholl** [comment]
This issue has been resolved, please comment to reopen if you are still experiencing issues.
