### ISSUE TITLE
[llamaindex]: Incomplete traces

### ISSUE THREAD

**Issue by sahilshaheen** [wandb/wandb#6739]
### Describe the bug

The traces produced using the `WandbCallbackHandler` is incomplete for simple RAG pipeline. `messages`, `response` are the only relevant information for CBEventType.LLM (there is no `context_str`, `template`, etc. like shown in the following image from the documentation)
![wandb-llamaindex-docs-image](https://docs.wandb.ai/assets/images/llama_index_trace-fe512b920e4a9b05da42ac30f38b2ae1.png)

For retrieval, there is no relevant information in the trace - not even the retrieved snippets are visible.

Tried for various `ServiceContext`s - OpenAI, Anthropic LLMs and OpenAI, HF embeddings

```python
llama_debug = LlamaDebugHandler(print_trace_on_end=True) # for notebook visibility

# wandb.init args
run_args = dict(
    project="explore",
)

wandb_callback = WandbCallbackHandler(run_args=run_args)

callback_manager = CallbackManager([llama_debug, wandb_callback])

service_context = ServiceContext.from_defaults(
    callback_manager=callback_manager,
)

!mkdir -p '../data/paul_graham/'
!wget 'https://raw.githubusercontent.com/run-llama/llama_index/main/docs/examples/data/paul_graham/paul_graham_essay.txt' -O '../data/paul_graham/paul_graham_essay.txt'
docs = SimpleDirectoryReader("../data/paul_graham/").load_data()
index = VectorStoreIndex.from_documents(docs, service_context=service_context)

query_engine = index.as_query_engine()
response = query_engine.query("What did the author do growing up?")
print(response, sep="\n")
```

### Additional Files

[run.zip](https://github.com/wandb/wandb/files/13692435/run.zip)

### Environment

WandB version: 0.16.1

OS: macOS-13.0.1-arm64-arm-64bit

Python version: 3.11.7

Versions of relevant libraries:

llama-index==0.9.15post12

**Comment by rsanandres-wandb** [comment]
Hello @sahilshaheen!

Thank you for this! One last thing, could you send a link to your project so I can investigate on there as well?

**Comment by aaalexlit** [comment]
@sahilshaheen, if I'm not mistaken, you also need to pass the callback_manager when you're creating your query engine like so:
```
query_engine = index.as_query_engine(callback_manager=callback_manager)
```

**Comment by ayulockin** [comment]
Hey @sahilshaheen, W&B Trace is an old product offering which is not maintained anymore. We were focused on shipping a better tooling called W&B Weave. Team is working on the LlamaIndex integration. Note that the new functionality will be available for the latest version of LlamaIndex.

[Weave announcement](https://wandb.ai/wandb/weave-announcement/reports/Weave-Simple-tools-for-applying-Generative-AI--Vmlldzo3NDE0Mjcx)
[Weave Documentation](https://wandb.github.io/weave/)

Closing this issue for now. Do let me know if you need anything more.
