### ISSUE TITLE
[App]: Virtually impossible to set the X axis range when using time

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [wandb/wandb#6742]
### Current Behavior

Entering a min/max value for the X axis when the quantity is a time is impossible. It keeps interpreting it differently. Typing 3600 will sometime be interpreted as seconds sometimes as hours and the worst is that it changes as time passes so a chart that display properly at a given time will suddenly switch units.

### Expected Behavior

Ability to properly control the range of an axis when dealing with time. There are many ways to do so. Maybe add units or something ?

### Steps To Reproduce

1. Set an axis to Realtive Time (Process)
2. Set a value for the range to be 60
3. It gets interpreted to 60 sec
4. Set the value to 3600
5. It gets interpreted to 3600 minutes
6. There is no way to get 1h!!

### Screenshots

![image](https://github.com/wandb/wandb/assets/2017051/94b07b5d-11b7-44a2-9fda-cc5c35ef0c83)
![image](https://github.com/wandb/wandb/assets/2017051/5673205e-d936-49f9-80ac-6d66f18fbce5)

=> It is literally impossible to have the chart scale to an 1h

### Environment

OS: Pop OS

Browsers: Firefox

**Comment by rsanandres-wandb** [comment]
Hello @GuillaumeLeclerc !

Thank you for reporting this! I will be making an internal bug report on this so that our Engineers can look into it.

**Comment by rsanandres-wandb** [comment]
Hello! There was some degradation for charts at the time that you reported this, are you still able to see this behavior? I have attempted to reproduce this again but have been unable to.
