### ISSUE TITLE
[Q] Custom Chart (using vega spec) for table artifact

### ISSUE THREAD

**Issue by ethanabrooks** [wandb/wandb#6743]
There is a table of scalar values that I log periodically throughout training (https://wandb.ai/rldl/icvi/artifacts/run_table/run-6m4vh5xj-tablereturns/v0/files/table/returns.table.json). I see that there are some limited options for plotting this data using some Vega presets:
<img width="424" alt="image" src="https://github.com/wandb/wandb/assets/10344742/d3846ac4-fa0a-49b5-aad7-6df2d53d7184">
However, I was hoping I might access more general vega functionality. In particular, I would like to plot a line chart with error bands. Thank you for your help with this.

**Comment by ArtsiomWB** [comment]
Hi @ethanabrooks!

Thank you for writing in! In order to edit your table as a custom chart, you can go into the workspace and add a new custom chart panel. From there, select summaryTable, select the right table you are interested in, and the right columns. Then you can select the type of chart you are interested in:
https://github.com/wandb/wandb/assets/115654725/083f39d1-55f2-4359-ae80-01fc062d8409

If the fields are not enough you can always edit the Vega spec manually by pressing the Edit button which will take you to the Vega spec editor. 
<img width="515" alt="image" src="https://github.com/wandb/wandb/assets/115654725/d1b5249c-80a3-4d8b-af33-473f7b2c36b7">

Let me know if you have any follow-up questions.

**Comment by ethanabrooks** [comment]
@ArtsiomWB thank you for the response. I have been trying to get custom charts to work for some time, and have issues getting the data to show up. Here is an image:

![image](https://github.com/wandb/wandb/assets/10344742/68fc5e7e-ed21-418c-8f71-6c3831e28c36)


for this run: https://wandb.ai/rldl/icvi/runs/ytgxvd34?workspace=user-ethanbro

Curiously, the fields autopopulate indicating that this is indeed the correct method for accessing the table data. However, as the image indicates, no data shows up in the data field and no graphic renders.

**Comment by ArtsiomWB** [comment]
Interesting, is there a specific chart type you are interested in?

**Comment by ethanabrooks** [comment]
Yes I want to a lineplot with error bands. But wouldn't the data show up regardless of the plot type?

**Comment by ArtsiomWB** [comment]
I was wondering about the plot type in order to repro it on my side, and you are right I am seeing the same behavior! 
The thing here is that I am not being able to find the table/regret inside of the run you have provided above, could you double-check to make sure that run did log that particular table?

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by ethanabrooks** [comment]
Hi Artsiom, here is a link to the artifact for the table that I am trying to plot: https://wandb.ai/rldl/icvi/artifacts/run_table/run-abxfni5d-tablereturns/v1

Let me know if this is the information you needed.

**Comment by ArtsiomWB** [comment]
Hi @ethanabrooks , apologies for the delay in response! Looking at the table provided above, what would you like to have as your x and y axis?

**Comment by ethanabrooks** [comment]
Let's use `episode` for x-axis, `returns` for y-axis, and let's get error-bands across `idx`.

**Comment by ArtsiomWB** [comment]
Hi @ethanabrooks! Apologies for the delay in reply. Has been very hectic right after the holiday season. 

Is this something similar to what you are looking for?
https://wandb.ai/rldl/icvi/reports/undefined-24-01-17-13-28-03---Vmlldzo2NTQ4OTg4
You can edit your vega spec manually by pressing the `Edit` button in the custom charts pannel. 
<img width="1486" alt="image" src="https://github.com/wandb/wandb/assets/115654725/c15fe04f-2560-4b18-94e7-3aeae6c58da0">

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by ethanabrooks** [comment]
Hi Artsiom, this is on the right track but not quite what I would like. The graph should reproduce the format of the error-band graphs that wandb uses in its display of grouped runs, or the format that seaborn uses for lineplot. There should be solid line running through the center of the band-area identifying the mean of the runs. I am not sure how to examine the code for the graph that you posted because the report does not give me access, but if you post on here, I can give you more detailed feedback.

**Comment by ArtsiomWB** [comment]
Apologies for the delay in reply again, tried coming up with something like that but still no luck. 

On Vega's website they do have Vega examples looking like this:
https://vega.github.io/vega-lite/examples/layer_line_errorband_ci.html

You would probably need to build on top of this VegaLite spec. If you encounter any issues, it would be best to run the vega spec by vega-lite forums as it falls outside the scope of our expertise in vega. 

Regarding editing the report, are you not able to access the `edit report` button on your side?
<img width="1406" alt="image" src="https://github.com/wandb/wandb/assets/115654725/f8211048-f5a8-4db1-903e-eeae7952d8ad">

Also, I have made the vega spec availible from your workspace in the custom charts drop-down menu called `scatter plot with error bands`, where you should be able to edit it and its code by pressing the edit button
<img width="1573" alt="image" src="https://github.com/wandb/wandb/assets/115654725/0c4d0917-d01c-44dd-9f35-31758569e5f5">

**Comment by ethanabrooks** [comment]
Hi Artsiom. It's ok I can work out the specifics of the graph myself. My primary concern was the inability to access the data via the graphql interface. I have moved on from this project, but perhaps you can let me know if that issue has been resolved.

**Comment by ArtsiomWB** [comment]
Gotcha! Thank you for elaborating, so in the end, you are interested in being able to access the data logged, using the GQL, to create a custom chart?

**Comment by sydholl** [comment]
WandB Internal User commented: 
ArtsiomWB commented: 
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by sydholl** [comment]
WandB Internal User commented: 
ethanabrooks commented: 
Hi Artsiom. It's ok I can work out the specifics of the graph myself. My primary concern was the inability to access the data via the graphql interface. I have moved on from this project, but perhaps you can let me know if that issue has been resolved.

**Comment by sydholl** [comment]
WandB Internal User commented: 
ArtsiomWB commented: 
Gotcha! Thank you for elaborating, so in the end, you are interested in being able to access the data logged, using the GQL, to create a custom chart?

**Comment by ethanabrooks** [comment]
Hi @sydholl, that is correct. I should add that I am still able to reproduce the problem that I identified earlier (in [this post](https://github.com/wandb/wandb/issues/6743#issuecomment-1862009648)):
<img width="707" alt="image" src="https://github.com/wandb/wandb/assets/10344742/20d14140-7864-461e-84e1-efb2b7a218d5">
Artsiom kindly offered to produce the graph for me, but that is not a long-term solution to my inability to access artifact data in custom charts.

**Comment by ArtsiomWB** [comment]
In the screenshot above, what kind of Custom Chart template are you using?

**Comment by ethanabrooks** [comment]
I modified the lineseries template, removing the transform field:
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "description": "A plot for an arbitrary number of lines",
  "data": {
    "name": "wandb"
  },

  
  "title": "${string:title}",
  "layer": [
    {
      "selection": {
      "grid": {
          "type": "interval",
          "bind": "scales"
        }
      },
      "mark": {"type": "line", "interpolate": "linear"},
      "encoding": {
        "x":{
          "field": "${field:step}",
          "type": "quantitative",
          "title": "${string:xname}"
        },
        "y": {
          "field": "${field:lineVal}",
          "title": "y",
          "type": "quantitative"
        },
        "color": {
          "type": "nominal",
          "field": "name",
          "scale" : {
            "range" : {"field": "color"}
            }
        },
        "strokeDash": {
          "type": "nominal",
          "field": "${field:lineKey}"
        }
      }
    }
  ]
}
```

**Comment by ArtsiomWB** [comment]
Hi! Wanted to follow up regarding this topic!

**Comment by ethanabrooks** [comment]
@ArtsiomWB this is the table I am trying to extract data from: https://wandb.ai/rldl/icvi/artifacts/run_table/run-abxfni5d-tablereturns/v1/files/table/returns.table.json

It is an artifact stored by this run: https://wandb.ai/rldl/icvi/runs/abxfni5d/

**Comment by ArtsiomWB** [comment]
It does look like you can reach this table here because the run above does log the table above. 

I think you are not able to reach the regrets table from the [message above](https://github.com/wandb/wandb/issues/6743#issuecomment-1862009648) is because that run did not log the regrets table, and it did log the returns table. 
https://github.com/wandb/wandb/assets/115654725/b028afdc-1839-48c7-9fa6-24ef2ce157ab

If I go into the output artifacts of your run, I do not see a regret table being created. 

<img width="848" alt="image" src="https://github.com/wandb/wandb/assets/115654725/7bae95ab-aae9-47fe-bcd3-a04175f61f30">

This makes me believe that the table wasn't logged in that particular run and cannot be used in the workspace of that run.

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request.

**Comment by ethanabrooks** [comment]
This appears to work:
<img width="862" alt="image" src="https://github.com/wandb/wandb/assets/10344742/32046220-1553-4957-8086-fb3f132e938e">

I have admittedly lost the thread a bit here, and this is a project that I am finished with. Perhaps this was an issue of user error. I am satisfied with this outcome.
