### ISSUE TITLE
Unable to Delete Panels from Run

### ISSUE THREAD

**Issue by ddav118** [wandb/wandb#6751]
### Current Behavior

When I try to delete a panel from a run, it shows up in the Hidden Panels Section. 

### Expected Behavior

The panel is completely deleted

### Environment

OS: Windows 11

Browsers: Chrome

Version: 120.0.6099.110

**Comment by umakrishnaswamy** [comment]
hey @ddav118, if the panels were generated from your run (example: logging metrics), then it is intended for the panels to go to the hidden section as opposed to being deleted. thank you for flagging this & please let me know if you have other questions

**Comment by umakrishnaswamy** [comment]
hey @ddav118, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
