### ISSUE TITLE
[Q] LOGGING SINGLE CODE FILE RATHER THAN ITERATING A DIRECTORY

### ISSUE THREAD

**Issue by mdivyanshu97** [wandb/wandb#6758]
Hello, 
I was wondering if there was a way, where I could directly give the path of a single file and wandb logs the code? The log_code option is good but as it iterates over all the files in the root directory for matching the condition given in the include_func, it can take a while if your directory contains a large number of files.
Also I noticed when I try to log files from different root folders using separate log_code commands, only one of them is getting logged/ showing on wandb.

Example code:
```
wandb.init()
wandb.run.log_code(root="root1/models",include_fn=lambda path: "model.py" in path)
wandb.run.log_code(root="root2/datasets",include_fn=lambda path: "dataset.py" in path)
wandb.run.log_code(root="root3/utils",include_fn=lambda path: "process.py" in path)

```

**Comment by ArtsiomWB** [comment]
Hi @mdivyanshu97! Thank you for writing in! Unfortunately, there is no direct way outside of using run.log_code to log a code file. If you are interested in seeing it in the future, I could submit a feature request for you.

**Comment by mdivyanshu97** [comment]
Yes that would be great.
Thanks

**Comment by ArtsiomWB** [comment]
What you could also do is log your code file as an artifact
for example like this:
```
import wandb

run = wandb.init(project="artifacts-example", job_type="add-dataset")
artifact = wandb.Artifact(name="codetest", type="code")
artifact.add_file(local_path="course.py")  # Add dataset directory to artifact
run.log_artifact(artifact)  # Logs the artifact version "my_data:v0"
```

It should have a similar behavior to logging a single code file with a command. Could you see if something like this would work for you?

**Comment by ArtsiomWB** [comment]
What you could also do is log your code file as an artifact
for example like this:
```
import wandb

run = wandb.init(project="artifacts-example")
artifact = wandb.Artifact(name="codetest", type="code")
artifact.add_file(local_path="course.py")  # Add code file  to artifact
run.log_artifact(artifact)  # Logs the artifact file
```

It should have a similar behavior to logging a single code file with a command. Could you see if something like this would work for you?

**Comment by ArtsiomWB** [comment]
We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by ArtsiomWB** [comment]
Hi there, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
