### ISSUE TITLE
[Q]KeyError between pytorch lightning and wandb

### ISSUE THREAD

**Issue by hml1996-fight** [wandb/wandb#6768]
I tried using WandbLogger in pytorch lightning.
I use WandbLogger to record metrics and ModelCheckpoint to save models.
There is no problems in training and the wandb project's state is `Finished`.
But it shows an `KeyError` during testing when i use `model.load_from_checkpoint(checkpoint_path)` to load. 
This error is pointing step by step:
self.save_hyperparameters()  -> wandb.sdk.service.server_sock.py
![image](https://github.com/wandb/wandb/assets/72264324/6a597aaa-a5d9-4109-85a8-a3aca1a101c1)
the key is `2oxzo496`,  but I can find it in web pages and local folders.

**Comment by rsanandres-wandb** [comment]
Hello @hml1996-fight !

Could you provide the code snippet that you are using to load the checkpoint? It seems that your multithreading is attempting to create multiple threads but it is running issues at that step. How are you using multithreading in your code?

Also, it looks like the KeyError is referring to the run id `2oxzo496`. Can you verify that this run exists?
