### ISSUE TITLE
[App]: Cannot query field "versionOnThisInstanceString" on type "LocalVersionInfo"

### ISSUE THREAD

**Issue by LinChuangquan** [wandb/wandb#6771]
### Environment

OS: CentOS Linux 7

Browsers: python cli

Version: python wandb version 0.16.1
               wandb server use the latest wandb/local image

### Additional Context

I started a Wandb server on my Linux machine and then logged in the service on my Mac computer through 'Wandb login -- host'. Subsequently, I ran the demo test on the official website and reported the following error. But I saw my run on the project interface and it looked normal. May I ask if you can help me see why this problem occurs

**Comment by LinChuangquan** [comment]
<img width="1308" alt="bc32ce5a7e41b52ed6e777fec" src="https://github.com/wandb/wandb/assets/58781640/e84a58e6-775b-4a87-af18-2992ed991435">
![93d0ea3ab72e63ccb7979378d](https://github.com/wandb/wandb/assets/58781640/b8140d62-d7dc-433a-a4cc-3af10018bc40)

**Comment by LinChuangquan** [comment]
![image](https://github.com/wandb/wandb/assets/58781640/b389638c-af51-4cf2-b75e-602dc162253e)

**Comment by shaosen11** [comment]
I found this bug happened recently month. So the problem is the result of the latest version of wandb. I tried the old version through "pip install wandb==0.16.0" and then this problem was solved.
