### ISSUE TITLE
[App]: Deleting some media files, crashes the panels 

### ISSUE THREAD

**Issue by kkoutini** [wandb/wandb#6775]
### Current Behavior

I log audio files during training. When the training is finished and in case I don't need all the intermediate logs, I delete some audio files from the run using the api (#6197) to save storage space. I keep only the audio files from the last training step. The panels on the web app don't work (see screenshot below).

### Expected Behavior

The panel tolerates missing files and shows the remaining files.

### Steps To Reproduce

1. log audio files in multiple steps
2. delete some audio files as suggested in #6197

### Screenshots

![Screenshot 2023-12-28 105148](https://github.com/wandb/wandb/assets/51880718/8ee83b7d-ab17-44e3-a2fa-3244f7287f6e)

### Environment

OS: Any

Browsers: Chrome

Version: latest

**Comment by ArtsiomWB** [comment]
Hey @kkoutini , Thank you for writing in!

Could you please provide a link to a workspace where you are experiencing this behavior?

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by kkoutini** [comment]
Hi, Thank you, it seems to be working now. I feel like something was cached, which caused the failures. Most of the runs are working now, but [here](https://wandb.ai/augmentation/vocos/runs/mtjtx5gt) is one example I found that is still not working, although the media files from the last steps still exist.

**Comment by ArtsiomWB** [comment]
Thank you for the update! Could you please send me a link to a run where it is working for you now - for me to compare both of the workspaces?

**Comment by kkoutini** [comment]
Hi thank you! 
[Here](https://wandb.ai/augmentation/vocos/runs/ldgg5tkr?workspace=user-kkoutini) is a run that works for me, I can choose the steps 429 and 430, these are the only steps that still have the audio files, and I can play them in the webapp. 
PS: Sometimes, I may need to edit the panels to choose `Columns=Example index` in advanced to get the steps slider, to be able to slide it to the end.

Here is also a minimal code snippet for what I do to delete the intermediate files:
```python
files_gt = defaultdict(list)
for file in  run.files():
   if file.name.endswith(extension) and "gt" in file.name:
      f = file.name.rsplit("/",1)[-1] # get the file name
      k= int(f.rsplit("_",2)[-2])  # this should be  analogous to the step num
      files_gt[k].append(file)
for k in sorted(files_gt)[:-1]: # exclude the last step
   file_to_delete.extend(files_gt[k]) # add all the other indices and steps to the delete list
```

**Comment by ArtsiomWB** [comment]
Thank you for providing the code snippet above. 
When do you delete your files, as well as how often do you log them? Do you log them every wandb step?

Do you delete your files when the training is over and when wandb.finish() has been called, or do you do it in the middle of the experiment?

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by kkoutini** [comment]
Hi, I log the files after each epoch but I don't set a step, during the epoch I log other metrics. Therefore, I think it's not every wandb step.
After the traning is done and wandb.finish is called. I do some anlysis and in some cases, I don't need the files anymore (in most cases). I connect to wandb api and clean the intermediate files and leave only the last logged files. I use the code posted above. 
I don't know which was the last step so sort by the file name and delete all but the last step.
Thanks for the help!

**Comment by kkoutini** [comment]
Hi, I fixed the issue by keeping the last two steps. Apparently,  the problem was that some of the runs crashed before uploading the last step. Thanks again for the help I'll close the issue.
