### ISSUE TITLE
Can not sync the .wandb file[Q]

### ISSUE THREAD

**Issue by kevin568** [wandb/wandb#6776]
Environment : Google Colab python 

Yesterday I'm trainning a model but it crash. assume the id = abc. 
Than today I use the model trained and I want to keep training it, so I use the init option init (id='abc', projectproject=args.project_name, name=args.exp_name, config=args ) 
But I the process due to the instability network, I stop and retrained multiple times. In the end,
It just ran smoothly, but after I finished the train.  I found that it only update the summary part, it doesn't update anything in the charts. It just update summary.

And latter I try to use this https://github.com/wandb/wandb/issues/3888 to sync my record.
But badly it doesn't allow me to sync 
It keep showing "invalid header" 
I try directly point to the file
<img width="991" alt="截圖 2023-12-28 下午6 02 58" src="https://github.com/wandb/wandb/assets/40351912/024c31d5-4fba-42cc-9cf4-65e6c108ed32">
Or use official method point to the directory 
<img width="964" alt="截圖 2023-12-28 下午6 04 18" src="https://github.com/wandb/wandb/assets/40351912/377a7aa6-5524-4ee1-99a2-20fee534e461">
And this prove that the above path I provide is valid path. 
<img width="982" alt="截圖 2023-12-28 下午6 04 36" src="https://github.com/wandb/wandb/assets/40351912/0adb32e4-9ccd-4929-a43d-e02012a3469a">

In the end, I even try to --view --verbose, but it still not working...
<img width="984" alt="截圖 2023-12-28 下午6 06 08" src="https://github.com/wandb/wandb/assets/40351912/cb07e6d9-7348-4736-b948-9dd8784790a1">

I have read docs and search information on the internet in whole days but do not found something helpful.
Can somebody can figure it out ? Or provide me a way to read the .wandb file in vscode, so I can manually collect the information for myself ? 

File structure 
<img width="363" alt="截圖 2023-12-28 下午6 10 02" src="https://github.com/wandb/wandb/assets/40351912/bdbbe4e3-0f61-416e-92dd-db0f13b56ac8">

Thanks for reply ( Sorry for my bad English )

**Comment by ArtsiomWB** [comment]
Hey @kevin568! Thank you for writing in! Could you please send me a code snipet of how you resume your run? Mostly interested in looking at your wandb.init

**Comment by kevin568** [comment]
Below is my init function.
<img width="970" alt="截圖 2023-12-29 下午1 12 45" src="https://github.com/wandb/wandb/assets/40351912/0792a7db-7078-4867-9fe6-5c3777340bdf">
<img width="491" alt="截圖 2023-12-29 下午1 13 03" src="https://github.com/wandb/wandb/assets/40351912/7f000959-c9c6-4f3c-b20a-50c69ce4202e">
<img width="195" alt="截圖 2023-12-29 下午1 14 09" src="https://github.com/wandb/wandb/assets/40351912/f29015c8-8fbe-463c-a3c6-600f63d2212d">

And below is a prove that it actually update and connect to the right project, but not showing in chart.
<img width="1358" alt="截圖 2023-12-29 下午1 15 58" src="https://github.com/wandb/wandb/assets/40351912/d8b100fa-8e00-40a6-ac94-7117ecd7b0d1">
Also it create two artifact  ( 1 days is the first run, 21hr is the second run. ) 
<img width="932" alt="截圖 2023-12-29 下午1 18 56" src="https://github.com/wandb/wandb/assets/40351912/5a94f2b0-ff73-44c4-9de2-dc666b5e55f3">

Also my summary is update too. But only the chart data do not update. 
But due to research purpose I need to collect the graph info, so I want to integrate or just open the wandb file so I can collect data manually . ( get the .wandb into txt file )

**Comment by ArtsiomWB** [comment]
Hi, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
