### ISSUE TITLE
[App]: Parallel Coordinates Plot doubles on Safari

### ISSUE THREAD

**Issue by stelzo** [wandb/wandb#6782]
### Current Behavior

When exporting a Parallel Coordinates Plot in Safari, I get multiple renderings of the legend.
Also, the file size of the image exported with Safari is 2x bigger compared to Chrome.

### Expected Behavior

Export to identical images

### Steps To Reproduce

I did not found a public plot that can be exported from everyone so it probably needs your own data.

1. Open Chrome and Safari
2. Export a Parallel coordinates plot on both

### Screenshots

Safari:
![W B Chart 3 1 2024, 10_17_07](https://github.com/wandb/wandb/assets/40026170/b6344648-75ab-436d-9c63-e4b0be1b7c1e)

Chrome: 
![W B Chart 3 1 2024, 10_18_41](https://github.com/wandb/wandb/assets/40026170/ad16cdd1-47c9-43f1-b7e5-794a5b7e9689)

### Environment

OS: MacOS 14.2.1

Browsers: Safari 17.2.1

Version: WebApp

**Comment by fmamberti-wandb** [comment]
Hi @stelzo - Thank you for reporting this issue. We will reproduce this internally and investigate what is causing it. We will get back to you with any updates or if we need any further information.

**Comment by fmamberti-wandb** [comment]
Hi @stelzo, we have now rolled out a fix and the export from Safari is now fixed. Please don't hesitate to reach out for any further questions.
