### ISSUE TITLE
[Q] Can I recover a wandb project that has been wrongly deleted? (the whole project, not a run in a project)

### ISSUE THREAD

**Issue by kiwi1944** [wandb/wandb#6791]
I have mistakenly deleted one important project just now, and I want to recover this project. Is there any methods?

**Comment by umakrishnaswamy** [comment]
hey @kiwi1944 - please let us know if you are able to provide the project name and username. would be happy to help!

**Comment by umakrishnaswamy** [comment]
Hi @kiwi1944 - since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by Tokenmw** [comment]
> Hi @kiwi1944, can you send me the name of the project and your username and I can see if we are able to recover the project? Feel free to share with [Nathan.Kuneman@wandb.com](mailto:Nathan.Kuneman@wandb.com) if you're not comfortable sharing here.
> 
> Thank you, Nate

I also wanna to recover one important project. Can you help me? I have sent the email for you. Thank you so much.

**Comment by asteve3** [comment]
Hi @nate-wandb, I have also accidentally deleted an important project. Can you or someone help me recover it? Thanks.
