### ISSUE TITLE
[Q] How to resolve this error?

### ISSUE THREAD

**Issue by vishnusharma03** [wandb/wandb#6793]
Issue: It says to call wandb.init() before wandb.save() which is already implemented.
Can you tell me what could be the issue?
I am running in Google Colab?

___CODE___

`def train():
  try:

    model = YOLO('yolov8n.pt')  # Load a pretrained model

    wandb.init(project="Wandb103", entity="username", config={
        "epochs": 1,
        "imgsz": 416
    })

    # Train the model
    results = model.train(data='/content/drive/MyDrive/Tilda/data.yaml', epochs=1, imgsz=416)

    # Log model weights
    wandb.save("runs/detect/train/weights/best.pt")

  except Exception as e:
    logging.error(e)
    raise e

  finally:
    wandb.finish()  # Ensure wandb run is finished even if there's an exception

train()`

__Error Message__ 
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
[<ipython-input-4-defe91cba1d3>](https://localhost:8080/#) in <cell line: 25>()
     23     wandb.finish()  # Ensure wandb run is finished even if there's an exception
     24 
---> 25 train()

2 frames
[/usr/local/lib/python3.10/dist-packages/wandb/sdk/lib/preinit.py](https://localhost:8080/#) in preinit_wrapper(*args, **kwargs)
     34 ) -> Callable:
     35     def preinit_wrapper(*args: Any, **kwargs: Any) -> Any:
---> 36         raise wandb.Error(f"You must call wandb.init() before {name}()")
     37 
     38     preinit_wrapper.__name__ = str(name)

Error: You must call wandb.init() before wandb.save()

**Comment by ArtsiomWB** [comment]
Hi @vishnusharma03, thank you for writing in!

Could you please talk a bit about your environment setup as well as your hardware setup to run the script above?

Warmly,
Artsiom

**Comment by vishnusharma03** [comment]
Hii @ArtisomWB I am using google colab with T4 TPU runtime, can you help me with it?

**Comment by ArtsiomWB** [comment]
Lets take a look at it. Would you mind sending me over your script?

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by vishnusharma03** [comment]
Well I found an alternative way to implement that, so thank you for the help
