### ISSUE TITLE
[Q]  Run specific hyperparameteer combinations in a sweep.

### ISSUE THREAD

**Issue by andrewwarrington** [wandb/wandb#6797]
Hi WandB,

I want to use WandB as an experiment runner on a cluster.  I have a set of hyperparameters and some values, but i only want to run a very specific* and small set of the possible combinations of these hyperparameters (as opposed to all combinations). 

This custom sweep seems to have been discussed before (e.g. [here](https://community.wandb.ai/t/conditional-sweep-config/4017)).  There are a lot of complex ideas about logic etc, but I think a sensible first step would be just allowing the user to supply an explicit "manifest".  What I'm imagining is instead of a standard config, you can specify something like:
```
sweep = {
    "method": "hardcoded",  # "hardcoded" would indicate "parameter_sets" will just be explicitly iterated over
    "name":   "sweep",
    "metric": "reward",
    "parameter_sets": {
         "exp1": {
              "rnn_cell_type": "gru",
              "penalty_term": 0.0,
         },
         "exp2": {
              "rnn_cell_type": "gru",
              "penalty_term": 1.0,
         },
         "exp3": {
              "rnn_cell_type": "vanilla",
              "penalty_term": 1.0,
         },
    },
}
```
e.g. i don't need to run the "vanilla" with a reward penalty of zero.  And then WandB does its magic behind the scenes generating the string to call each config as per usual.  In this, each config could even have a variable number of parameters, eg:

```
sweep = {
    "method": "hardcoded",  # "hardcoded" would indicate "parameter_sets" will just be explicitly iterated over
    "name":   "sweep",
    "metric": "reward",
    "parameter_sets": {
         "exp1": {
              "rnn_cell_type": "gru",
              "penalty_term": 0.0,
         },
         "exp2": {
              "rnn_cell_type": "gru",
         },
         "exp3": {
              "rnn_cell_type": "vanilla",
         },
    },
}
```
e.g. if the `penalty_term ` defaults to 1.0.

Thanks,
A

*A lot of the hyperparameters correspond to physiological conditions, and i only want to test specific combinations out of the many possible combinations.

**Comment by andrewwarrington** [comment]
In reference to the thread references above ([here](https://community.wandb.ai/t/conditional-sweep-config/4017)), that could be solved as:

```
sweep = {
    "method": "hardcoded",  # "hardcoded" would indicate "parameter_sets" will just be explicitly iterated over
    "name":   "sweep",
    "metric": "reward",
    "parameter_sets": {
         "exp1": {
              "approach": a,
              "sub_approach": a1,
         },
         "exp2": {
              "approach": a,
              "sub_approach": a2,
         },
         "exp3": {
              "approach": b,
              "sub_approach": b1,
         },
         "exp4": {
              "approach": b,
              "sub_approach": b2,
         },
    },
}
```

**Comment by rsanandres-wandb** [comment]
Hello @andrewwarrington !

Thanks for the suggestion! I can certainly make a feature request for you and see what our Engineers can do about this.

**Comment by gil2rok** [comment]
Does Hydra allow you to do this?

**Comment by rsanandres-wandb** [comment]
This is possible, although not the cleanest since Hydra does not use subclass the primitive Python dictionaries. 
It can work ([as seen here](https://github.com/wandb/wandb/issues/4686)) and `wandb` does integrate with `hydra` ([example report](https://wandb.ai/adrishd/hydra-example/reports/Configuring-W-B-Projects-with-Hydra--VmlldzoxNTA2MzQw)) but a better workaround would to use `wandb` with [Optuna](https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/002_configurations.html#defining-parameter-spaces) with the [WeightsAndBiasesCallback](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.WeightsAndBiasesCallback.html) since that would integrate better.
