### ISSUE TITLE
[Q] How do I connect minIO instead of S3?

### ISSUE THREAD

**Issue by deg1020** [wandb/wandb#6802]
![gawrgawrgwRghwh](https://github.com/wandb/wandb/assets/31460593/3d555ebf-2530-40b5-9a4e-608be845eb09)

**Comment by ArtsiomWB** [comment]
Hi @deg1020! Thank you for writing in! Are you trying to connect an external bucket to your local wandb deployment or a public cloud team?

**Comment by deg1020** [comment]
Thank you for answer. So, I'm using minio, but what should I do if I don't want to use Notification Subscription?
![image](https://github.com/wandb/wandb/assets/31460593/a912377a-f522-450d-808b-bdf07f47ba89)

**Comment by ArtsiomWB** [comment]
Hi @deg1020, I have checked internally and unfortunately as of right now, we do not support minIO. If you would like to I would love to submit a feature request for you to our engineering team to add this functionality in the future.

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by ArtsiomWB** [comment]
Hi, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
