### ISSUE TITLE
[App]: Sections load very slowly when scrolling

### ISSUE THREAD

**Issue by AlexanderKoch-Koch** [wandb/wandb#6807]
### Current Behavior

When scrolling up and down in the workspace some sections load very slowly.

### Expected Behavior

I expect the sections to load almost instantly.

### Screenshots

https://github.com/wandb/wandb/assets/26693765/f8e0adba-c33e-4d08-9489-2ec8a627a5e8

### Environment

OS: macOS Sonoma 14.2.1

Browsers: Chrome Version 120.0.6099.199 (Official Build) (arm64)

**Comment by MBakirWB** [comment]
Hi @AlexanderKoch-Koch , thank you for reporting this. Could you provide me a link to your private project. Also if you were to clear your cache and reload the page, does the issue persist? Thanks

**Comment by AlexanderKoch-Koch** [comment]
Clearing the cache and reloading does not help. Here is the link to the project:
https://wandb.ai/alex_k/imitation_learning

**Comment by MBakirWB** [comment]
Hi @AlexanderKoch-Koch , thank you for sending this over, it was very helpful. The issue appears to stem from the Media panel when it is expanded, something is causing the workspace to hang. I've asked the app team to review and will update you with their findings.

**Comment by MBakirWB** [comment]
Hi @AlexanderKoch-Koch , I wanted to update you that this is now fixed. Thanks again for flagging. Marking resolved but do let us know if you need help with anything else.
