### ISSUE TITLE
[App]: Unable to display runs for large number of total runs in workspace

### ISSUE THREAD

**Issue by Lily-Le** [wandb/wandb#6809]
### Current Behavior

In Workspace, lists of runs cannot be displayed. It shows 0/ of 0 runs although the total run number is large. 

Can you fix this? Or how can I get it back to normal? With a specific run web link, I still have access to the run. But it's really hard to find out the runs now let alone to sort and filter them. When the total run number is large, it's disappointing. Thanks!  Looking forward to your reply. 

### Screenshots

![image](https://github.com/wandb/wandb/assets/21274476/02a8c3ed-49ae-4687-9d6d-520db839e4bc)

![image](https://github.com/wandb/wandb/assets/21274476/00665228-7c3c-44d4-a96b-5579217924b3)

### Environment

OS: Windows11/Ubuntu20.04

Browsers: Chrome/Firefox

Version: 120.0.6099.199 for chrome

**Comment by MBakirWB** [comment]
Hi @Lily-Le , happy to help. Could you provide me a link to the affected project for us to review (you may keep it private). 

This could be happening due to a visibility selection, could you check if "Visualize None" is not toggled on. To access, select the `eye `next to `Name`.

**Comment by Lily-Le** [comment]
Hi @MBakirWB  Thanks for the quick reply. It gets to normal now. But the problem is not caused by visibility selection as the eye is open. I toggled on 'visialize all'  then.  And even if I toggled on 'visualize none' , at the end it shoud show xx of 3302 but not 0 of 0. 
![image](https://github.com/wandb/wandb/assets/21274476/206d1acb-ac1c-4a8a-b794-89ea4b03d232)

**Comment by JoanaMarieL** [comment]
Hello @Lily-Le , glad that it is normal now. We'll mark this as resolved but feel free to write in again when you have more questions or this weird behavior comes up again.
