### ISSUE TITLE
[App]: Error st is undefined when create a new sweep

### ISSUE THREAD

**Issue by RicardoP0** [wandb/wandb#6832]
### Current Behavior

When creating a sweep through the website I get the error st is undefined and reloading the website does nothing. On firefox is throws the error st is undefined and on chrome the message is Cannot read properties of undefined (reading 'variableName')

### Steps To Reproduce

1. Go to sweeps
2. Create a new sweep
3. Error st is undefined

### Screenshots

![image](https://github.com/wandb/wandb/assets/31822527/ef69c755-0cb3-4a22-a206-3ce40989e4ab)
![image](https://github.com/wandb/wandb/assets/31822527/a355483f-fb0b-4a42-a0fe-17cbb17c4c46)

### Environment

OS: Linux mint

Browsers: Firefox, Chrome

Version:

**Comment by zimmer-m** [comment]
Same for me - I cannot create any further sweeps!

**Comment by zimmer-m** [comment]
@RicardoP0 As a workaround, you could create sweeps from the terminal, i.e., create a sweep.yaml file with your yaml-configuration and then run `wandb sweep sweep.yaml` and add entity/project parameters if needed.

**Comment by patricknaughton01** [comment]
Also experiencing this issue, but I get a slightly different error message:
![image](https://github.com/wandb/wandb/assets/28968518/bc550b84-82f2-46ad-b3ef-db70ee2a67be)

The current workaround of creating sweeps from the CLI is working for me though.

**Comment by Innoversa** [comment]
> @RicardoP0 As a workaround, you could create sweeps from the terminal, i.e., create a sweep.yaml file with your yaml-configuration and then run `wandb sweep sweep.yaml` and add entity/project parameters if needed.

I've encountered the same problem and got the second error message (cannot read properties of undefined). But I was able to `nano sweep.yaml` with desired comment, and then `wandb sweep sweep.yaml` to create and execute desired sweeps. Thank you!

**Comment by patricknaughton01** [comment]
As of today, this seems to have just resolved itself for me, not sure what happened.
