### ISSUE TITLE
[Feature]: Free the 🐡 (Emoji in group/run names)

### ISSUE THREAD

**Issue by jsuarez5341** [wandb/wandb#6835]
### Description

Hello, I would like to bring to your attention a critical missing feature of the utmost importance. It is currently impossible to use emoji in group names (and probably in run names too). This is a mission critical feature for BagsOfMoneyHQ, which is currently an important free tier user.

### Suggested Solution

Free the 🐡 (I would actually like this)

### Alternatives

Let the 🐡 be sad :/

**Comment by xinpw8** [comment]
I 🐡/🐡 second this thank you in advance for making ml fun

**Comment by MBakirWB** [comment]
🐟 
🐟🦈 
🐟😮 🦈 
Yumm 🦈 

Feature documented

**Comment by xinpw8** [comment]
it's pronounced WAND - BEE
