### ISSUE TITLE
[CLI]: `tests/pytest_tests/unit_tests_old/test_logging.py::test_logging` test failure

### ISSUE THREAD

**Issue by samuela** [wandb/wandb#6836]
### Describe the bug

I'm seeing a test failure on tag `v0.16.0` (currently c6b7a82a152e8efee84cb7f0887532c482ccd6c1):
```
E       AssertionError: assert ['info1', 'warn1', 'Failed checking if running in CYGWIN due to: %r', 'info2', 'warn2', 'info5', 'warn5'] == ['info1', 'warn1', 'info2', 'warn2', 'info5', 'warn5']
E         At index 2 diff: 'Failed checking if running in CYGWIN due to: %r' != 'info2'
E         Left contains one more item: 'warn5'
E         Full diff:
E           [
E            'info1',
E            'warn1',
E         +  'Failed checking if running in CYGWIN due to: %r',
E            'info2',
E            'warn2',
E            'info5',
E            'warn5',
E           ]

/private/tmp/nix-build-python3.11-wandb-0.16.0.drv-0/source/tests/pytest_tests/unit_tests_old/test_logging.py:51: AssertionError
```

### Environment

WandB version: v0.16.0

OS: macOS 14.1.1 (23B81)

Python version: 3.11.7

Versions of relevant libraries: n/a

**Comment by luisbergua** [comment]
Hey @samuela, thanks for reporting this! There were some upgrades in our SDK so would you mind confirming if you still see this failing on `0.16.2`?

**Comment by luisbergua** [comment]
Hey @samuela! Given that in our latest release our tests were updated and `tests/pytest_tests/unit_tests_old/test_logging.py` has been actually removed, we're going to close this request but please feel free to re-open it if you see any other tests failing and we'll be more than happy to investigate. Thanks!
