### ISSUE TITLE
[Q] Changing Team Type from Work to Academic

### ISSUE THREAD

**Issue by RolandRiachi** [wandb/wandb#6851]
Hi WandB team!

Would it be possible to change my team's type from "Work" to "Academic" as I missed that option when creating the team?

These are the links to my account & team:
Link to my account: https://wandb.ai/rolandriachi
Link to my team: https://wandb.ai/ts-transfer

**Comment by MBakirWB** [comment]
Hi @RolandRiachi , happy to help. I checked your account and you are currently part of an academic organization. At this time wandb only allows academic to be part of a single academic team org. To continue using the org tied with team ts-transfer:
1. You can upgrade to a paid membership
2. Transfer all runs from ts-transfer to your academic team, [see here on how to transfer runs](https://docs.wandb.ai/guides/app/features/runs-table#move-runs-between-projects). Once you've completed the move, let us know and we can delete the corporate org that is past it's tracked hour trial.

**Comment by MBakirWB** [comment]
Hi @RolandRiachi , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
