### ISSUE TITLE
[App]: TensorBoard not viewable in web UI

### ISSUE THREAD

**Issue by ameya98** [wandb/wandb#6857]
### Current Behavior

I created a Weights and Biases run with `sync_tensorflow = True` but I can't see the TensorBoard in web UI:
<img width="1438" alt="image" src="https://github.com/wandb/wandb/assets/12739380/0aaa6e71-bbf0-4024-af73-5b46ffcbe2d0">
```
Error launching tensorboard: Error creating pod: pods "tensorboard-symphony-generation-symphony-nwwswzdk" is forbidden: error looking up service account default/spiderweb-sa: serviceaccount "spiderweb-sa" not found
```
I can see the W&B native charts for the same experiment, however:
<img width="953" alt="image" src="https://github.com/wandb/wandb/assets/12739380/f7f71a9c-7a81-4f2a-9046-82a179822ee1">
Please let me know what I am doing wrong. 

### Expected Behavior

I should be able to see the TensorBoard logs for my run

### Environment

OS: macOS Monterey

Browsers: Google Chrome

Version: `wandb=0.16.2`

**Comment by zebin-huang** [comment]
I had the same issue before. Can you check if you can run the tensorboard at your local side?

**Comment by thanos-wandb** [comment]
Hi @zebin-huang @ameya98 thank you for reporting this issue. Our Infra team had identified what was causing this issue and had resolved it since reported. Can you please check and let us know if that's now fixed for you?

**Comment by zebin-huang** [comment]
> Hi @zebin-huang @ameya98 thank you for reporting this issue. Our Infra team had identified what was causing this issue and had resolved it since reported. Can you please check and let us know if that's now fixed for you?

It works for me now. Thanks for your support!

**Comment by thanos-wandb** [comment]
Hi @zebin-huang perfect, thank you for confirming! Marking this ticket closed for now, but feel free to reach out if that pops up again for you and we will be happy to keep investigating.
