### ISSUE TITLE
 How to get paginated runs using wandb client?

### ISSUE THREAD

**Issue by MahdiJafari1** [wandb/wandb#6860]
I am using the wandb API to retrieve a large number of runs for a project. Retrieving all runs at once takes a long time, so I want to fetch runs in several batches. Currently, in the wandb API, I notice that there is a per_page parameter for getting runs, but there is no page parameter. Therefore, I don't see a clear way to retrieve the next page of runs.

According to the wandb documentation:
```python
Runs(
    client: "RetryingClient",
    entity: str,
    project: str,
    filters: Optional[Dict[str, Any]] = None,
    order: Optional[str] = None,
    per_page: int = 50,
    include_sweeps: bool = (True)
)
```

How can I retrieve paginated runs?

**Comment by thanos-wandb** [comment]
Hi @MahdiJafari1 thank you for writing in! To retrieve the paginated runs, you could use the `next` method. I have provided a simple code snippet below that returns a single run each time. Would this work for your use case?


```
import wandb
api = wandb.Api()
runs_iterator = api.runs(path, per_page=1)
for _ in range(runs_iterator.length):
  run = runs_iterator.next()
  print(run.name)
```

**Comment by thanos-wandb** [comment]
Hi @MahdiJafari1 just checking in here to see if the above code snippet would work for you, and if you had any additional questions/issues with respect to this request?

**Comment by MahdiJafari1** [comment]
Hi @thanos-wandb Thank you for your response. Yes, The above code iterates through a list of runs. But, there is another issue that the `per_page` parameter is not limiting the runs. Here is the issue for it: https://github.com/wandb/wandb/issues/6884

**Comment by thanos-wandb** [comment]
Hi @MahdiJafari1 thank you for confirming this returns the next page of your paginated runs. We've logged a feature request on the issue you've linked to expose a specific `page` argument. Since those two threads are related, I will close this one and we will keep you posted on #6884 on any updates.
