### ISSUE TITLE
[App]: Different results in Embedding Projector for my own view and public view

### ISSUE THREAD

**Issue by invisprints** [wandb/wandb#6866]
### Current Behavior

I created a report to plot the embeddings of my experiment in 2 dimensions. However, the results I see and the other people that through my share link see are different. Here is the report link and the screenshot:
[Embedding-Visualization](https://wandb.ai/xianruili/wandb-debug/reports/Embedding-Visualization--Vmlldzo2NTc0ODAy)
My view:
![image](https://github.com/wandb/wandb/assets/15833553/94cb54fb-8b95-4fc4-83c0-6a6023e56063)
Others view:
![image](https://github.com/wandb/wandb/assets/15833553/34cdb8f3-dc65-4fa6-8596-2f3492f1fc66)

### Expected Behavior

The result should be the same.

### Steps To Reproduce

The project is public, you can explore it. The data is in Project-Charts-Table

### Environment

OS: Windows 11

Browsers: Google Chrome

Version: 120.0.6099.225 (64 bit)

**Comment by luisbergua** [comment]
Hi @invisprints, thanks for your patience! After checking with our engineers, it seems this is expected behavior since embeddings are non-deterministic, so every time you refresh the page, the plot will change and that's why other users are seeing a different one.

**Comment by invisprints** [comment]
The embedding before t-SNE dimensionality reduction is deterministic. Does wandb not have a fixed t-SNE method? As far as I know, sklearn can achieve this by setting a seed, and the logic of the plot changing every time the page is refreshed is also very strange, isn't it?

**Comment by luisbergua** [comment]
Thanks for your response @invisprints! That's currently not possible but I'll create a feature request for you to have the option to make embeddings deterministic and retain the first one
