### ISSUE TITLE
[Q] Confusion matrix as table 

### ISSUE THREAD

**Issue by MoH-assan** [wandb/wandb#6873]
Hi, 
I am facing the same [issue #3126 (#3126)  but I donot know which custom chart should I use ?
There seem to be different versions here 
![image](https://github.com/wandb/wandb/assets/123608862/a30ebe6b-828c-4b69-8ab0-a99e2c1588fa)

**Comment by fmamberti-wandb** [comment]
Hi @MoH-assan - `Multi-run confusion matrix/v1` is the chart that is automatically created if you log it during your Run using `wandb.plot.confusion_matrix` so should work fine.

Did you log the confusion matrix during your Run or are you trying to add it afterwards?

**Comment by fmamberti-wandb** [comment]
Hi @MoH-assan I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by fmamberti-wandb** [comment]
Hi @MoH-assan, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by MoH-assan** [comment]
> Did you log the confusion matrix during your Run or are you trying to add it afterwards?

Afterwards.
