### ISSUE TITLE
[Q] Using max/min values in weave chart

### ISSUE THREAD

**Issue by MoH-assan** [wandb/wandb#6876]
Is there is way to take advantage of min, max values obtained here https://github.com/wandb/wandb/issues/736#issuecomment-1716142404 to use then in the weave chart.

**Comment by rsanandres-wandb** [comment]
Hello!

You can't directly get the max/min value from the Runs Table, but you are able to get the max/min in Weave with the following:
```runs.history.concat["_step"].max```
<img width="986" alt="image" src="https://github.com/wandb/wandb/assets/122482606/73f6592a-30f4-47ff-bb09-9315da1f4f76">

**Comment by sydholl** [comment]
Raphael San Andres commented: 
Hi, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
