### ISSUE TITLE
[CLI]: `state` does not sem to be Exposed on Sweep

### ISSUE THREAD

**Issue by stellarpower** [wandb/wandb#6879]
### Describe the bug

Sweep states are shown in in the dashboard:
![image](https://github.com/wandb/wandb/assets/5004545/32b52623-4b3c-44db-8993-5472acbaf079)

and [the code for pretty-printing the sweep includes a line to fetch its state]( https://github.com/wandb/wandb/blob/main/wandb/apis/public/sweeps.py#L236   ).

However, in my sweeps, this always defaults to "Unknown State" - this property never appears to be populated in the same way as the dashboard.

```python

```

```shell

```

### Environment

WandB version: wandb, version 0.16.1

Python version: 3.9

**Comment by rsanandres-wandb** [comment]
Hello @stellarpower !

There seems to be some missing from my understanding. Are you seeing that there is an `Unknown State` that is popping up in the UI?

A couple questions if that's the case:
- Are you on a Local instance or the Public instance? If its the Public instance, could I have a link to your project?
- Could you provide a short, reproducible code snippet of your sweep for my own testing?

**Comment by sydholl** [comment]
Raphael San Andres commented: 
Hi Internal, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
