### ISSUE TITLE
[CLI]: CLI is excessively restrictive in check for `--host`; does not support private/internal DNS hostnames

### ISSUE THREAD

**Issue by Jamil** [wandb/wandb#6886]
### Describe the bug

I currently have a wandb server instance deployed internally on a network, inside a VPN service. I have an internal hostname (let's say `myhost`) under which I can access wandb; http://myhost:1234.

Unfortunately, when using the CLI, I can't log in to this instance:

```
$ wandb login --relogin --host=http://myhost:1234
wandb: You can find your API key in your browser here: http://myhost:1234/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:
wandb: ERROR Host must be a url in the form https://some.address.com, received http://myhost:1234
```

If I remove the check for `normalized_host` in `sdk/lib/apikey.py`, everything works as expected without any further changes. The check simply makes sure that either a `.` or `localhost` is in the hostname before allowing login, which is an excessively restrictive check.

### Environment

WandB version:

OS: macOS 14.1

Python version: 3.11

Versions of relevant libraries: 0.16.2

**Comment by Jamil** [comment]
I can make the PR for this since it's such a small change, just want to see if people are open to the change and if there should still be checks on the hostname or whether that line should be removed completely.

**Comment by MBakirWB** [comment]
Hi @Jamil , thank you for reporting this. You are welcome to create a PR for this. I will flag with our SDK team for review and they will make a final decision.

**Comment by Jamil** [comment]
Thank you @MBakirWB! I just opened up the PR at #6999, let me know when you get a chance to review it with the SDK team :)
