### ISSUE TITLE
[CLI]: Cannot call `init` on LambdaLabs VM

### ISSUE THREAD

**Issue by tilman151** [wandb/wandb#6905]
### Describe the bug

I am trying to run a training script on a VM from LambdaLabs and it is failing when `wandb.init` is called. Even though, I properly authenitcated and already logged against the project from another machine, I get a 403 error.

```python
>>> import wandb
>>> wandb.init(entity="<MyUserName>", project="test")
403 response executing GraphQL.

<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/graphql</code> from this server.</h2>
<h2></h2>
</body></html>

wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
Problem at: <stdin> 1 <module>
wandb: ERROR It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/uda-rul-model-selection-mnzczjhJ-py3.10/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1195, in init
    raise e
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/uda-rul-model-selection-mnzczjhJ-py3.10/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/uda-rul-model-selection-mnzczjhJ-py3.10/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
```

Neither using `wandb login` nor setting the environment variable seems to fix the problem. When I try to use offline mode and try to sync later via `wandb sync --sync-all`, it tells me that the runs were synced successfully but they do not appear in the Web UI.

### Environment

WandB version: 0.16.2 installed via Poetry

OS: 

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

Python version: 3.10.12

Versions of relevant libraries:

**Comment by tilman151** [comment]
@vimmoos thank you. I already thought I'm the only one.

**Comment by rsanandres-wandb** [comment]
Hello! It looks like the login is being corrupted somewhere. We save the login credentials in the `~/.netrc` file.

Could we try the following steps:
- Could you delete your ~/.netrc file with rm ~/.netrc then try to run wandb login --cloud ? 
- Alternatively, can you set your environment variable `WANDB_API_KEY` to also try and login?

Once you do this, try running your script again. While you have done the login step before, we want to start on a clean slate to make 100% sure.

**Comment by sydholl** [comment]
WandB Internal User commented: 
rsanandres-wandb commented: 
Hello! It looks like the login is being corrupted somewhere. We save the login credentials in the `~/.netrc` file.

Could we try the following steps:
- Could you delete your ~/.netrc file with rm ~/.netrc then try to run wandb login --cloud ? 
- Alternatively, can you set your environment variable `WANDB_API_KEY` to also try and login?

Once you do this, try running your script again. While you have done the login step before, we want to start on a clean slate to make 100% sure.

**Comment by sydholl** [comment]
Raphael San Andres commented: 
Hi, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by tilman151** [comment]
Retrying with a new VM solved the issues. I probably broke something while setting it up.

**Comment by anmolmann** [comment]
Hey @tilman151, Great to hear that retrying with a new VM resolved the issues! f you have any further questions or encounter more issues in the future, feel free to reach out. Happy computing!
