### ISSUE TITLE
[CLI]: Documentation on Artifact export

### ISSUE THREAD

**Issue by joeryjoery** [wandb/wandb#6928]
### Describe the bug

When I log a table or a plot, I can easily recover the logged entry inside `run.scan_history`. 

When I inspect an individual entry, this gives me a metadata dictionary that looks something like this,

```python
metadata = {
  'ncols': 123,
  'nrows': 321,
  'path': 'path_to_media',
  'artifact_path': 'some_other_path',
  '_latest_artifact_path': 'some_path',
  'sha256': '...',
  'size': 36949,
  '_type': 'table-file'
}
```

How do I now access this artifact? 

I tried following the documentation here https://docs.wandb.ai/guides/artifacts/download-and-use-an-artifact, but this does not work,

```python
import wandb
api = wandb.Api()

api.artifact('entity/project/' + metadata['path'])
```

I've tried multiple things to access the artifact through the metadata but I am simply unable to find out how. 

Yes I know that I can access this through `run.logged_artifacts()` but this is imperfect since it loses the other logged data (like `_step` or other values linked to logged table). In my opinion 

### Environment

WandB version:

OS:

Python version:

Versions of relevant libraries:

**Comment by nate-wandb** [comment]
Hi @joeryjoery, do you receive an error when calling `api.artifact('entity/project/' + metadata['path'])` ? I think the issue is that you don't have the name of the artifact correct. The format should be `artifact = api.artifact("entity/project/artifact:alias")` so you would need fetch the artifact with the alias and then grab the table from the Artifact with `table = artifact.get(path)` to return the `wandb.Table` object. Let me know if that helps

Thank you,
Nate

**Comment by sydholl** [comment]
WandB Internal User commented: 
nate-wandb commented: 
Hi @joeryjoery, do you receive an error when calling `api.artifact('entity/project/' + metadata['path'])` ? I think the issue is that you don't have the name of the artifact correct. The format should be `artifact = api.artifact("entity/project/artifact:alias")` so you would need fetch the artifact with the alias and then grab the table from the Artifact with `table = artifact.get(path)` to return the `wandb.Table` object. Let me know if that helps

Thank you,
Nate

**Comment by joeryjoery** [comment]
Hey thanks for the reply, I still don't quite get it so I'll post the full method,

```python
import wandb
api = wandb.Api()

run = api.run(...)
export = run.scan_history(keys=['my_table_key'])  # This was logged as wandb.log({'my_table_key': wandb.Table(...)})

df = pd.DataFrame(export)
print(df.iloc[0, 0])
>> {'path': 'media/table/EvaluationService/train_functional_metrics/functions.Fourier/0/table_10001_cf0834710bdfb6170f07.table.json',
 'artifact_path': 'wandb-client-artifact://h3qnrqthzsxrgj78eku27jfgoaq4j21ojly56flq9jvf5g2bt55mydynubs5ske6wmiog7u6hr271kalab07xvxeruffqdlr73ssd2j2m2j266aey9xsw2maj0yhm40q/EvaluationService/train_functional_metrics/functions.Fourier/0/table.table.json',
 '_latest_artifact_path': 'wandb-client-artifact://h3bz7a08zwqbbdveg81wrbmzcr0wrxzzb4ywna68xr5lz8ry5en0ezamodqkkaa0ayhqvtcvhdhtysh0dapqwi9ba48wcyku0l3i7duh3enzkzvy7obz329e32jgbgmi:latest/EvaluationService/train_functional_metrics/functions.Fourier/0/table.table.json',
 'sha256': 'cf0834710bdfb6170f07263efeb13569edfe4e6cba0b55bffdd86a89179ac8af',
 'size': 35986,
 '_type': 'table-file',
 'ncols': 123,
 'nrows': 14}


# Compare this with artifacts
print([x.qualified_name for x in run.logged_artifacts()])
>> ['joery/Regression/run-ng2kn18n-EvaluationServicetest_functional_metricsfunctionsFourier0table:v0', 'joery/Regression/run-ng2kn18n-EvaluationServicetrain_functional_metricsfunctionsFourier0table:v0', 'joery/Regression/run-ng2kn18n-EvaluationServicetest_functional_metricsfunctionsFourier0table:v1', 'joery/Regression/run-ng2kn18n-EvaluationServicetrain_functional_metricsfunctionsFourier0table:v1', 'joery/Regression/run-ng2kn18n-EvaluationServicetest_functional_metricsfunctionsFourier0table:v2', 'joery/Regression/run-ng2kn18n-EvaluationServicetrain_functional_metricsfunctionsFourier0table:v2', 'joery/Regression/run-ng2kn18n-EvaluationServicetest_functional_metricsfunctionsFourier0table:v3', 'joery/Regression/run-ng2kn18n-EvaluationServicetrain_functional_metricsfunctionsFourier0table:v3', 'joery/Regression/run-ng2kn18n-EvaluationServicetest_functional_metricsfunctionsFourier0table:v4', 'joery/Regression/run-ng2kn18n-EvaluationServicetrain_functional_metricsfunctionsFourier0table:v4', 'joery/Regression/run-ng2kn18n-history:v0']

# Now try to load something in
dummy_artifact = api.artifact(run.logged_artifacts()[0].qualified_name)  # Success

# How do I do this with the data inside `df`?
other_artifact = api.artifact( ??? + df.iloc[0, 0][ ??? ])
```

The reason why I want to read the artifacts like this is so that I can validate the V0 V1 ... V4 versioning of different artifacts to their respective `wandb.log` entry (as I want to make plots to their correct labels).

**Comment by joeryjoery** [comment]
To clarify/ simplify,

I would like to know how I can get the artifact qualified name (or just the artifact):
```python
'joery/Regression/run-ng2kn18n-EvaluationServicetest_functional_metricsfunctionsFourier0table:v0'
```

from the logged table entry inside the history,
```python
{'path': 'media/table/EvaluationService/train_functional_metrics/functions.Fourier/0/table_10001_cf0834710bdfb6170f07.table.json',
 'artifact_path': 'wandb-client-artifact://h3qnrqthzsxrgj78eku27jfgoaq4j21ojly56flq9jvf5g2bt55mydynubs5ske6wmiog7u6hr271kalab07xvxeruffqdlr73ssd2j2m2j266aey9xsw2maj0yhm40q/EvaluationService/train_functional_metrics/functions.Fourier/0/table.table.json',
 '_latest_artifact_path': 'wandb-client-artifact://h3bz7a08zwqbbdveg81wrbmzcr0wrxzzb4ywna68xr5lz8ry5en0ezamodqkkaa0ayhqvtcvhdhtysh0dapqwi9ba48wcyku0l3i7duh3enzkzvy7obz329e32jgbgmi:latest/EvaluationService/train_functional_metrics/functions.Fourier/0/table.table.json',
 'sha256': 'cf0834710bdfb6170f07263efeb13569edfe4e6cba0b55bffdd86a89179ac8af',
 'size': 35986,
 '_type': 'table-file',
 'ncols': 123,
 'nrows': 14}
```

Highly appreciate any help

**Comment by joeryjoery** [comment]
I solved the problem by coincidence, I'll post the way that I achieved it so someone else can find this (preferably you guys can add this to the documentation).

The path that is printed out in my previous reply, refers to the path that W&B downloads the artifact files to, *if* you use `[f.download() for f in run.files]`. If you access the artifact through `run.logged_artifacts()`, then the downloaded file will be cached **somewhere else**, and not to the path stored in `history`. This is super confusing.

```python
...
api = wandb.Api()

my_run = api('entity/project/run')

history = my_run.scan_history()
history = pd.DataFrame(history)

for file in my_run.files():
    file.download()  # Will save the file to the paths defined in the History Entry

# Heuristic to get table-entries from logged history
table_entries = history.loc[:, history.columns.str.contains('table')].dropna()

# Convert string-values to dictionary and extract the `path` field (see reply above).
table_paths = table_entries.map(lambda x: ast.literal_eval(x)['path'])

# Now you can access the artifacts *from* the history object
with open(table_paths.iloc[0, 0], 'r') as f:
    my_table_artifact = json.loads(f)

# Do something with artifact
...

```

**Comment by MBakirWB** [comment]
Hi @joeryjoery thank you for providing solution for your issue. Will be marking this closed.

**Comment by adrianloy** [comment]
> To clarify/ simplify,
> 
> I would like to know how I can get the artifact qualified name (or just the artifact):
> 
> 'joery/Regression/run-ng2kn18n-EvaluationServicetest_functional_metricsfunctionsFourier0table:v0'
> 
> from the logged table entry inside the history,
> 
> {'path': 'media/table/EvaluationService/train_functional_metrics/functions.Fourier/0/table_10001_cf0834710bdfb6170f07.table.json',
>  'artifact_path': 'wandb-client-artifact://h3qnrqthzsxrgj78eku27jfgoaq4j21ojly56flq9jvf5g2bt55mydynubs5ske6wmiog7u6hr271kalab07xvxeruffqdlr73ssd2j2m2j266aey9xsw2maj0yhm40q/EvaluationService/train_functional_metrics/functions.Fourier/0/table.table.json',
>  '_latest_artifact_path': 'wandb-client-artifact://h3bz7a08zwqbbdveg81wrbmzcr0wrxzzb4ywna68xr5lz8ry5en0ezamodqkkaa0ayhqvtcvhdhtysh0dapqwi9ba48wcyku0l3i7duh3enzkzvy7obz329e32jgbgmi:latest/EvaluationService/train_functional_metrics/functions.Fourier/0/table.table.json',
>  'sha256': 'cf0834710bdfb6170f07263efeb13569edfe4e6cba0b55bffdd86a89179ac8af',
>  'size': 35986,
>  '_type': 'table-file',
>  'ncols': 123,
>  'nrows': 14}
> 
> Highly appreciate any help

I have exactly the same problem. How do I create an object of type `Artifact` or of type `Entry` based on these dict keys? How can I make use of the `artifact_path` value? The documentation is really poor on this.
