### ISSUE TITLE
[Feature]: Create Anonymous Link for Current Project

### ISSUE THREAD

**Issue by chang-github-00** [wandb/wandb#6929]
### Description

Is there a way to provide an anonymous version link for a current project? Also we hope the link could stay up for a few months rather than 7 days.

### Suggested Solution

We tried to register a fully anonymous account, though the user name always show a user name/ mail address depending on the resigister venue.

**Comment by JoanaMarieL** [comment]
Hello @chang-github-00 , happy to help. Hoping you have read our docs [here ](https://docs.wandb.ai/guides/app/features/anon) about this feature of Anonymous Mode. For requesting this as a Feature Request, may we request more context about it for a longer duration, greater than 7 days up to few months. How impactful this could be to your experiments/use case?

**Comment by JoanaMarieL** [comment]
Hi @chang-github-00 , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
