### ISSUE TITLE
[Q] Support for local deployment in k3d cluster

### ISSUE THREAD

**Issue by FeU-aKlos** [wandb/wandb#6934]
I deployed wandb as well as minio in a k3d cluster. Unfortunately, if I try to use the Ingress-address, the ingress address cannot be resolved by dns server.

Would be nice, If one could also use the internal k8s name of the service (my case minio.minio.svc.cluster.local) for referencing the bucket, or is there a way, to get it work in k3d?

**Comment by MBakirWB** [comment]
Hi @FeU-aKlos , we don't currently support k3d for deployment, but here is some potential feedback that might help.

Your suggestion about using the internal Kubernetes service name (e.g., minio.minio.svc.cluster.local for MinIO) fmight work for bypassing the need for DNS resolution of the Ingress address by external DNS servers. For issues with k3d specifically (please note this is general info per my research online so it may not work)
1. Direct Service Access: As mentioned, using the internal service name for intra-cluster communication
2. DNS Resolution for Ingress: If you need to access your services from outside the cluster using the Ingress address, you must ensure that the DNS name used in the Ingress configuration is resolvable:
3. k3d-specific Configuration: Ensure that your k3d cluster is configured to expose the ingress controller's service externally. k3d has options to map ports from the host to the cluster, which can be used to expose your Ingress controller.
4. Investigate Ingress Controller Logs: If any issues persist, check the logs of your Ingress controller within the k3d cluster. It might provide clues on why the DNS resolution is not working.

**Comment by MBakirWB** [comment]
Hi @FeU-aKlos , given we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
