### ISSUE TITLE
[Q] After running run.log,  if we update the table and use run.log again it doesn't work.

### ISSUE THREAD

**Issue by DANISHFAYAZNAJAR** [wandb/wandb#6935]
<img width="785" alt="Screenshot 2024-02-02 at 12 17 17 PM" src="https://github.com/wandb/wandb/assets/70327223/133ff4e4-ccc1-433c-9bd4-8e220e987a76">

After running run.log() first time it logs to run successfully . But I try to add more data and log that too, but it's not logging that as well.

**Comment by DANISHFAYAZNAJAR** [comment]
<img width="474" alt="Screenshot 2024-02-02 at 12 47 04 PM" src="https://github.com/wandb/wandb/assets/70327223/14fd2c4a-9e69-4e53-983d-d9d93ccc38bc">

On local if I am add more data to table its getting added but when I log the table only that data is logged which has been initially logged.


<img width="1440" alt="Screenshot 2024-02-02 at 12 50 42 PM" src="https://github.com/wandb/wandb/assets/70327223/78a8a81f-c63b-4e9c-abb5-e90407f639e6">
<img width="1425" alt="Screenshot 2024-02-02 at 12 50 51 PM" src="https://github.com/wandb/wandb/assets/70327223/a9d552a8-8c6f-4684-b0e3-173b451305b0">

**Comment by MBakirWB** [comment]
Hi @DANISHFAYAZNAJAR , `add_data` does not allow you to continuously update wandb tables that were previously logged. It is intended for incrementally adding data to your table before you log it to wandb. Example:

```
my_table = wandb.Table(columns=["a","b"], data = [["a1", "b1"], ["a2", "b2"]])
my_table.add_data("a3", "b3")
....Keep adding data via add_data
run.log() on finalized table
```

If you are interested in streaming data to a wandb table you will need to use our weave StreamTable feature, see here
https://docs.wandb.ai/guides/weave/streamtable

**Comment by MBakirWB** [comment]
Hi @DANISHFAYAZNAJAR , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
