### ISSUE TITLE
[App]: Night Mode Enabled by the Wrong Key Combo

### ISSUE THREAD

**Issue by tristanengst** [wandb/wandb#6943]
### Current Behavior

Night mode is enabled on Mac by pressing cmd+m. This is a problem because it's also the normal keyboard shortcut to minimize a window, and is thus incredibly annoying.

### Expected Behavior

Night mode is toggled by a user setting via some GUI, or by some other keyboard shortcut. At the very least, the current shortcut-based toggle should be disabled.

### Environment

OS: macOS 14.3

Browsers: Brave 1.62.156

Version:

**Comment by umakrishnaswamy** [comment]
hey @tristanengst - thank you for flagging. I surfaced this to our app team and update you on any discussion surrounding this behavior

**Comment by umakrishnaswamy** [comment]
hey @tristanengst - a fix has been merged for this. thank you again for surfacing this - you should be able to toggle between light and dark mode using option + m rather than cmd + m

**Comment by tristanengst** [comment]
Awesome, thank you! Confirmed option+m amd cmd+m work as intended.
