### ISSUE TITLE
[Q] Is there a way to create Launch queues using python 

### ISSUE THREAD

**Issue by abindg** [wandb/wandb#6976]
Hi , 

I am asking this question more from MLOPS persepctive . When I am setting up a pipeline to deploy WandB server and launch agents on my kubernetes cluster , I also want to create the launch queues programitically . I have not seen any cli options to achieve that . From the public API documentation , I can see there is a class called Runqueue (https://docs.wandb.ai/ref/python/public-api/runqueue) .

I am though unable to find how to call this class or the method ? There are no examples around . I know this may be a very trivial question , but can someone please point me in the right direction . How to invoke this class or method .

**Comment by umakrishnaswamy** [comment]
hey @abindg - we have this example [Colab notebook](https://colab.research.google.com/drive/1wX0OSVxZJDHRsZaOaOEDx-lLUrO1hHgP#scrollTo=fEE8r1M4cpry) for how to create launch queues programmatically

**Comment by sydholl** [comment]
WandB Internal User commented: 
umakrishnaswamy commented: 
hey @abindg - we have this example [Colab notebook](https://colab.research.google.com/drive/1wX0OSVxZJDHRsZaOaOEDx-lLUrO1hHgP#scrollTo=fEE8r1M4cpry) for how to create launch queues programmatically

**Comment by abindg** [comment]
Hi Thanks . This can be closed . I used 

 api.create_run_queue(name=queue_name, entity=entity, type="kubernetes", config=config)
