### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by lorsonblair** [wandb/wandb#6986]
Trying to run a trace session but I keep getting this error:

Traceback (most recent call last):
  File "/home/lorson/Projects/PruningLowPrecision/PatchTST-senqnn-supv/run_longExp.py", line 325, in <module>
    wandb.agent(sweep_id, function=exp.train_quant(sqcfg, setting_fp, setting_int, prc, wandb), count=5)
  File "/home/lorson/Projects/PruningLowPrecision/PatchTST-senqnn-supv/exp/exp_main.py", line 469, in train_quant
    optimizer = self._select_optimizer(config.learning_rate)
  File "/home/lorson/miniconda3/envs/pchtstquant/lib/python3.10/site-packages/wandb/sdk/wandb_config.py", line 164, in __getattr__
    raise AttributeError(
AttributeError: <class 'wandb.sdk.wandb_config.Config'> object has no attribute 'learning_rate'

I suspect that it is because of this warning, so my wandb environment is not being correctly initialized. How can I get rid of the warning and error? I'm not sure how to get rid of the previous instance of wandb.  

wandb: WARNING Changes to your `wandb` environment variables will be ignored because your `wandb` session has already started. For more information on how to modify your settings with `wandb.init()` arguments, please refer to https://wandb.me/wandb-init

**Comment by lorsonblair** [comment]
Hi @fmamberti-wandb, thanks for your response. I fixed the issue. The problem was that my train function had arguments so I had to use the functools.partial(..) to pass it to wandb.agent(). I found the solution on a previous reported issue (https://github.com/wandb/wandb/issues/2724).

**Comment by fmamberti-wandb** [comment]
@lorsonblair, I am glad to know you managed to fix this - and thank you for providing the context on how you did it.

Feel free to reach out in the future with any further queries.
