### ISSUE TITLE
[Q] Python library compatibility guarantees

### ISSUE THREAD

**Issue by timsueberkrueb** [wandb/wandb#6989]
Hey, what are the compatibility guarantees (if any) between different `wandb` Python client versions and the wandb SaaS offering? I could not find documentation regarding this. Thanks in advance!

**Comment by umakrishnaswamy** [comment]
hey @timsueberkrueb - We officially support sdk versions that are within the last 6 months of the most recent server release. in general, you can utilize older sdk versions with our SaaS offering, but you may experience decreased performance, so I advise remaining up to date with our latest SDK

**Comment by sydholl** [comment]
WandB Internal User commented: 
umakrishnaswamy commented: 
hey @timsueberkrueb - We officially support sdk versions that are within the last 6 months of the most recent server release. in general, you can utilize older sdk versions with our SaaS offering, but you may experience decreased performance, so I advise remaining up to date with our latest SDK

**Comment by timsueberkrueb** [comment]
Thank you for clarifying!
