### ISSUE TITLE
Can I change my Team Type from Work to Academic

### ISSUE THREAD

**Issue by melaniezhang** [wandb/wandb#6995]
I accidentally created my team as work type but it's an academic project and I've run out of tracking hours.

**Comment by JoanaMarieL** [comment]
Hello @melaniezhang , thank you for writing in and happy to help. Could you please provide the following details:

User name and Team name. Make sure that your academic email is linked to your profile.

**Comment by JoanaMarieL** [comment]
Hi @melaniezhang , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
