### ISSUE TITLE
[Q] Jobs/Launch/Queue

### ISSUE THREAD

**Issue by omaruus99** [wandb/wandb#7007]
I’ve created 4 jobs for the same project, I’ve configured a queue and an agent, but when I run my jobs, only the 1st job is launched, where’s the problem? Is there any documentation for this? Here is my configuration : 

Create job : (for each job created)
wandb job create --project "<project-name>" --entity "<your-entity>" \
--name "<name-for-job>" image image-name:tag

Queue : (1 queue for 4 jobs)
e: /mnt/c/nnUNet_raw:/nnUNet_raw
gpus: all

Agent : 
wandb launch-agent -e ip_team -q mlops_pipeline

**Comment by ArtsiomWB** [comment]
Hi @omaruus99 ! Thank you for writing in, taking a look

**Comment by ArtsiomWB** [comment]
Hi @omaruus99! Apologies for the delay in reply. Could you please provide a link to your workspace where you re experiencing this behavior?

**Comment by sydholl** [comment]
WandB Internal User commented: 
ArtsiomWB commented: 
Hi @omaruus99! Apologies for the delay in reply. Could you please provide a link to your workspace where you re experiencing this behavior?

**Comment by nate-wandb** [comment]
Hi @omaruus99, I wanted to follow up and see if you could provide the link to the workspace for this issue and we can take a look?
