### ISSUE TITLE
[Q] OOM error with sweep (with videos input)

### ISSUE THREAD

**Issue by shivanimall** [wandb/wandb#7019]
I am running a sweep in my code (which uses video input data), and running into out-of-memory (OOM) error.

Is there intensive memory allocation when for just running sweeps? Plus, what is the garbage collection before a next sweep starts? Is there anything I can add to my code to avoid this or should this already be handled by wandb? 

I recognise that my code has heavy-weight architectures / input data / computational graph and in case memory for those are not cleared between successive runs it will cause OOM error.

**Comment by JoanaMarieL** [comment]
Hello @shivanimall thank you for writing in and happy to help. could you please share the following:

- code snippet of your code or a toy example for reproducing this on our end
- how are you configuring your sweep

**Comment by JoanaMarieL** [comment]
Hi @shivanimall , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
