### ISSUE TITLE
[Q] I want to delete the team

### ISSUE THREAD

**Issue by EomYunJung** [wandb/wandb#7025]
Hello, I want to delete team in wandb.
How can I do?

Your wandb username -> EomYunJung
The team name you have created -> asr_
Would you like any of the associated projects to be moved to your personal entity? Yes

**Comment by JoanaMarieL** [comment]
Hi @EomYunJung , if you have an Admin Role, you will be able to delete the team by going to Team Settings and the bottom part, there is a Delete Team. Kindly try if you can go to it please. We'll be able to also help you move your projects, would like to know if there is specific ones or all projects?

**Comment by JoanaMarieL** [comment]
Hi @EomYunJung , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
