### ISSUE TITLE
[Q] Can I change my Team Type from Work to Academic?

### ISSUE THREAD

**Issue by Josh00-Lu** [wandb/wandb#7032]
I made an error by creating an "Corporate Team" previously. As a result, my account has exceeded the track limit, hindering access to crucial experimental data stored within it.

My user name is: josh00
My account is: luhf23@mails.tsinghua.edu.cn
My team is: https://wandb.ai/evolving

Your assistance in resolving this matter is highly appreciated. Thank you very much for your attention to this issue.

**Comment by JoanaMarieL** [comment]
Hello @Josh00-Lu , happy to help. Thank you for all the details provided, we will review your account first and will get back to you on what to do next.

**Comment by luisbergua** [comment]
Hey @Josh00-Lu, I just updated your subscription to academic
