### ISSUE TITLE
[Feature]: Option to delete an organization

### ISSUE THREAD

**Issue by SebastianBitsch** [wandb/wandb#7046]
### Description

I have searched the web the repo and the wandb client, but can't find any way to delete an organization. (except one closed issue on GitHub where an admin deleted the project for him)

### Suggested Solution

A button in the settings or Accounts & Billing tab where the owner can delete the organization

**Comment by JoanaMarieL** [comment]
Hi @SebastianBitsch , appreciate the request that you made. As of now we currently don't have a way for users to self delete their Org, but we can assist in deletion of it if you'd like. And we'll file your suggestion as a Feature Request.

**Comment by SebastianBitsch** [comment]
Hi @JoanaMarieL, thanks that sound good. Could you please delete the organization "mlops-mnist-org", my profile name is "@sebastianbitsch". The project was for a course I (/we) were following and it is no longer needed  - thanks in advance

**Comment by fmamberti-wandb** [comment]
Hi @SebastianBitsch we have not deleted the `mlops-mnist-org` organisation. Thank you again for your feedback and please don't hesitate to reach out in the future with any further questions.
