### ISSUE TITLE
[CLI]: Gymnasium v1.0.0 incompatible with `monitor_gym`

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [wandb/wandb#7047]
### Describe the bug

Gymnasium has just released [v1.0.0a1](https://github.com/Farama-Foundation/Gymnasium/releases/tag/v1.0.0a1) which removes `gymnasium.wrappers.monitoring.video_recorder` in favour of `gymnasium.wrappers.RecordVideo`. 
Therefore, `wandb.init(monitor_gym=True)` fails
 

```shell
> pip install gymnasium==1.0.0a1
```

```python
import wandb

wandb.init(
    project="project_name",
    entity="entity",
    monitor_gym=True,
)
```

```shell
Error importing optional module gymnasium.wrappers.monitoring.video_recorder
Traceback (most recent call last):
  File ".../.venv/lib/python3.11/site-packages/wandb/util.py", line 233, in import_module_lazy
    return sys.modules[name]
           ~~~~~~~~~~~^^^^^^
KeyError: 'gymnasium.wrappers.monitoring.video_recorder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../.venv/lib/python3.11/site-packages/wandb/util.py", line 262, in get_module
    return import_module_lazy(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.11/site-packages/wandb/util.py", line 235, in import_module_lazy
    spec = importlib.util.find_spec(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib.util>", line 94, in find_spec
ModuleNotFoundError: No module named 'gymnasium.wrappers.monitoring'
wandb: ERROR Couldn't import the gymnasium python package, install with `pip install gymnasium`
Traceback (most recent call last):
  File ".../scratch_wandb_monitor_gym.py", line 3, in <module>
    wandb.init(
  File ".../.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1195, in init
    raise e
  File ".../.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1172, in init
    wi.setup(kwargs)
  File ".../.venv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 279, in setup
    wandb.gym.monitor()
  File ".../.venv/lib/python3.11/site-packages/wandb/integration/gym/__init__.py", line 38, in monitor
    vcr = wandb.util.get_module(
          ^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.11/site-packages/wandb/util.py", line 269, in get_module
    raise wandb.Error(required)
wandb.errors.Error: Couldn't import the gymnasium python package, install with `pip install gymnasium`
```

### Environment

WandB version: 0.16.3

OS: MacOS

Python version: 3.11

Versions of relevant libraries: Gymnasium 1.0.0a1

**Comment by kptkin** [comment]
@pseudo-rnd-thoughts thanks for reporting this issue, we usually don't test with pre-releases of our integrations.
However this looks like something we could patch quite easily,  so we will try to include it in the upcoming march release.

**Comment by pseudo-rnd-thoughts** [comment]
Thanks @kptkin, let me know if there are any issues that I can help fix

**Comment by kptkin** [comment]
> Thanks @kptkin, let me know if there are any issues that I can help fix

@pseudo-rnd-thoughts we accept contributions so if you are in the mood, we are happy to accept a patch here 😄 
otherwise we will try to squeeze it to the march release

**Comment by drewmee** [comment]
Hi @kptkin and @pseudo-rnd-thoughts,

I went ahead had a crack at adding Gymnasium v1.0.0 support to `monitor_gym`.

Please have a look at the PR for a full description of changes.

Also please note that full functionality for post-v1.0.0 versions of Gymnasium will depend on updates from other projects that use Gymnasium. These updates are being tracked in the related Gymnasium issue: Farama-Foundation/Gymnasium#944. So perhaps the PR should remain in draft form until that support is added to the other projects.

I look forward to hearing your thoughts and feedback.

I am currently interviewing for the Senior Data Platform Engineer on the Data Science team at Weights & Biases. If you find my PR to be helpful, please do let the Taylor Holland the hiring manager know. I want to show that I can come in, take initiative, and immediately contribute :)

Best regards,
Drew Meyers
