### ISSUE TITLE
[CLI]: Too many files created in ~./local/share/wandb/artifacts/staging, causes DiskQuotaError

### ISSUE THREAD

**Issue by tristanengst** [wandb/wandb#7066]
### Describe the bug

A few dozen online WandB runs generate hundreds of thousands of files in `~./local/share/wandb/artifacts/staging`. This triggers a DiskQuotaError, and training fails. Taken together, the actual number of individual media items being logged by all the runs would be at most a few hundred.

Running in offline mode appears to resolve the issue, though I haven't tried syncing yet.

```python

```

```shell

```

### Environment

WandB version: 0.16.0+computecanada

OS: CentOS Linux v7

Python version: 3.11

Versions of relevant libraries:

### Additional Context

This is significant because a few dozen runs can generate hundreds of thousands of files. On my cluster environment, this is enough to trigger a DiskQuotaError and make WandB effectively unusable. It's possible that using the compute node itself as the staging directory could work, but this isn't a good solution to the problem as if the job times out before finishing, then (I assume) any unsynced results would be lost.

I believe there are a number of possibly related issues:
- https://github.com/wandb/wandb/issues/4535
- https://github.com/wandb/wandb/issues/5055
- https://community.wandb.ai/t/wandb-artifact-cache-directory-fills-up-the-home-directory/5224/3

Updating from WandB 16.0 to the latest version is currently impossible due to the packages offered on the cluster.

**Comment by fdsig** [comment]
Hey @tristanengst,

Thanks so much for sharing this and sorry to hear you are running into issues here.

Happy to hear that running online worked initially. 

In terms of getting you back on track -- if this is related to disk/ storage and artifacts as your cache file path suggests you should be able to clear this between runs with:

```bash
wandb artifact cache cleanup 0GB
```

Referenced in our docs [here](https://docs.wandb.ai/ref/cli/wandb-artifact/wandb-artifact-cache/wandb-artifact-cache-cleanup)

Look forward to hearing back from you.

**Comment by fdsig** [comment]
Hey @tristanengst,

I am checking in to see if the above has given you the functionality needed for your use case. Please let us know if you require further assistance and if not would you object to me closing this out for you?

**Comment by fmamberti-wandb** [comment]
Hi @tristanengst , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by tristanengst** [comment]
The above works.
