### ISSUE TITLE
[App]: Images metadata are visualized instead of the image itself

### ISSUE THREAD

**Issue by pietrobolcato** [wandb/wandb#7070]
### Current Behavior

When logging an image in a table, i'm seeing it's metadata instead of the image itself

![image](https://github.com/wandb/wandb/assets/3061306/8a99d455-e814-4a93-b095-a74117495e69)

### Expected Behavior

I should be seeing the image 

### Steps To Reproduce

Log a PIL image in a table

### Environment

Chromium

```
Arc:	122.0.6261.57 (Official Build) (arm64) 
Revision	87957e464700ccf3468df47ce741e0dc089e0544-refs/branch-heads/6261@{#853}
OS	macOS Version 14.1.2 (Build 23B92)
JavaScript	V8 12.2.281.16
User agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Command Line	/Applications/Arc.app/Contents/MacOS/Arc --flag-switches-begin --flag-switches-end
Executable Path	/Applications/Arc.app/Contents/MacOS/Arc
Profile Path	/Users/pb/Library/Application Support/Arc/User Data/Default
Linker	lld
Variations Seed Type	Null
Active variations	f38ef081-ca7d8d80

```

**Comment by pietrobolcato** [comment]
Actually same exact issue as: https://github.com/wandb/wandb/issues/7024

also the images for old run disappeared :/ running on wandb~=0.16.2

**Comment by pietrobolcato** [comment]
Edit: if i remove the line `allow_mixed_types=True` from the wandb table initialization, then works - this is a recent behavior, and it's breaking all the images i had logged in the past; def needs a fix please 🙏

**Comment by MBakirWB** [comment]
Hi @pietrobolcato thank you for reporting this and we appreciate your patience.  It's been escalated to our team and being treated as high priority. Will try to get you updates this week and report back on my teams timeline for this.

**Comment by pietrobolcato** [comment]
> Hi @pietrobolcato thank you for reporting this and we appreciate your patience.  It's been escalated to our team and being treated as high priority. Will try to get you updates this week and report back on my teams timeline for this.

Sounds good appreciate it, thanks a lot! Looking forward to know more about timeline for the fix 🙏

**Comment by pietrobolcato** [comment]
hey there, this is still an issue, quite disrupting tbh - any update?

**Comment by anmolmann** [comment]
Hey everyone, this issue should be resolved now, [PR](https://github.com/wandb/weave/pull/1393) for reference. Please let us know if you still encounter this on your end.
