### ISSUE TITLE
[Q] Wandb API endpoint URL/IP address and port?

### ISSUE THREAD

**Issue by rahit** [wandb/wandb#7073]
I am trying to use wandb on a institution managed HPC system. Unfortunately internet is not available by default (probably blocked by firewall).

When I have requested a way for me to use wandb, they have asked me to provide the IP and port and they might be able to help.

I was wondering what is the IP/port that wandb uses when sending the data and authentication request? Or can you suggest any workaround?

**Comment by thanos-wandb** [comment]
Hi @rahit We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by thanos-wandb** [comment]
Hi @rahit since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know and we will be happy to keep investigating!

**Comment by rahit** [comment]
Apologies for the delayed response. After multiple emails with the admin they have confirmed that - 

> wandb requires access to Google Cloud Storage, which is not accessible from the compute nodes.
> the solution is to run wandb in offline mode and run a wandb sync from the login nodes later.
> 
> It has been decided already that http proxy to Google storage will not be setup.

Looks like using the offline version for now is the only way. :(

**Comment by thanos-wandb** [comment]
Thanks for the update, @rahit. Indeed this sounds the best option for your current setup. Another option you may want to consider to self-host W&B Server (https://docs.wandb.ai/guides/hosting/hosting-options).
