### ISSUE TITLE
[Q] Getting launch agent error while deploying experiment to kubernetes . Previously it was running fine . Noticed that the helm chart image got changed

### ISSUE THREAD

**Issue by abindg** [wandb/wandb#7076]
Hi ,

I had a working WandB launch queue and agent configured . Today I updated the kubernetes config to include a Pod Disruption budget for the WandB jobs . During this process the agent helm chart was also ran , and I saw that the image is updated from [0.16.0-state-fix] to [0.16.3] . After this I ran a pipeline to enque a demo experiment to check everything is fine , but it is crashing due to agent issues . From the agent logs I can see:

**wandb: ERROR launch: Error running job: Exception when ensuring Kubernetes API key secret: Server disconnected**

I have a valid API key . The same key was used to enque the jobs , create queues and also in the agent config .

What has changed ?

**Comment by abindg** [comment]
This is the stack trace :

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/launch/runner/kubernetes_runner.py", line 678, in ensure_api_key_secret
    return await core_api.create_namespaced_secret(namespace, secret)
  File "/usr/local/lib/python3.9/site-packages/kubernetes_asyncio/client/api_client.py", line 185, in __call_api
    response_data = await self.request(
  File "/usr/local/lib/python3.9/site-packages/kubernetes_asyncio/client/rest.py", line 238, in POST
    return (await self.request("POST", url,
  File "/usr/local/lib/python3.9/site-packages/kubernetes_asyncio/client/rest.py", line 185, in request
    r = await self.pool_manager.request(**args)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 605, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 966, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 622, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/launch/agent/agent.py", line 604, in task_run_job
    await self._task_run_job(
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/launch/agent/agent.py", line 673, in _task_run_job
    run = await backend.run(project, image_uri)
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/launch/runner/kubernetes_runner.py", line 587, in run
    job, secret = await self._inject_defaults(
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/launch/runner/kubernetes_runner.py", line 424, in _inject_defaults
    api_key_secret = await ensure_api_key_secret(
  File "/usr/local/lib/python3.9/site-packages/wandb/sdk/launch/runner/kubernetes_runner.py", line 704, in ensure_api_key_secret
    raise LaunchError(
wandb.sdk.launch.errors.LaunchError: Exception when ensuring Kubernetes API key secret: Server disconnected

**Comment by KyleGoyette** [comment]
Hi @abindg there were 2 recent changes that could impact you here. First, we updated the helm chart to include the release name in the service account, secrets and many other objects: https://github.com/wandb/helm-charts/pull/47/files. If you have specific perms associated with the old service account name this could be the source of the issue.

This PR: https://github.com/wandb/wandb/pull/6722  also aims to create the W&B api key secret for each pod.  This is the source of your exact error. It is unclear why your api server is disconnecting, if you have access to the api server logs that would be quite helpful for debugging.

**Comment by abindg** [comment]
> Hi @abindg there were 2 recent changes that could impact you here. First, we updated the helm chart to include the release name in the service account, secrets and many other objects: https://github.com/wandb/helm-charts/pull/47/files. If you have specific perms associated with the old service account name this could be the source of the issue.
> 
> This PR: #6722 also aims to create the W&B api key secret for each pod. This is the source of your exact error. It is unclear why your api server is disconnecting, if you have access to the api server logs that would be quite helpful for debugging.

1. I have removed the cluster Role binding and only using Role binding for my setup . The role binding binds the role to the service account
2. With the exact same configs using the older image everything works 
3. I have checked the secret , checked the API key from the secret , it is the same as that supplied . The agent logs only show this details that I have pasted

**Comment by abindg** [comment]
hi @KyleGoyette 

I had substituted the rbac.yaml of helm template with my own rbac.yaml . It looks like below and removes cluster role and custer role binding . 

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wandb-launch-serviceaccount-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Values.namespace }}
  name: wandb-launch-agent-{{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps", "secrets", "pods/log"]
    verbs: ["create", "get", "watch", "list", "update", "delete", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "jobs/status"]
    verbs: ["create", "get", "watch", "list", "update", "delete", "patch"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wandb-launch-role-binding-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: wandb-launch-serviceaccount-{{ .Release.Name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: wandb-launch-agent-{{ .Release.Name }}
  apiGroup: rbac.authorization.k8s.io

**Comment by KyleGoyette** [comment]
Okay, I'd like to try to isolate the issue to either the new helm chart or the new agent code. Can you try installing the newest version of the helm chart, but update the image to:
wandb/launch-agent:0.16.0-state-fix?

**Comment by sydholl** [comment]
WandB Internal User commented: 
KyleGoyette commented: 
Hi @abindg there were 2 recent changes that could impact you here. First, we updated the helm chart to include the release name in the service account, secrets and many other objects: https://github.com/wandb/helm-charts/pull/47/files. If you have specific perms associated with the old service account name this could be the source of the issue.

This PR: https://github.com/wandb/wandb/pull/6722  also aims to create the W&B api key secret for each pod.  This is the source of your exact error. It is unclear why your api server is disconnecting, if you have access to the api server logs that would be quite helpful for debugging.

**Comment by fmamberti-wandb** [comment]
Hi @abindg, I wanted to check if you had the chance to test what Kyle suggested:

> Can you try installing the newest version of the helm chart, but update the image to:
wandb/launch-agent:0.16.0-state-fix?
