### ISSUE TITLE
[CLI]: Wandb logging does not work in Pytorch Lightning DDP

### ISSUE THREAD

**Issue by smandava98** [wandb/wandb#7084]
### Describe the bug

Hi! I'm having issues with wandb not logging any of my metrics.

Train init code:
```
logger = WandbLogger(name="b", project="p", log_model=True)

loggers = [logger]
```
I add this as a callback in Pytorch lightning.

Logging code:
```
@pl.utilities.rank_zero.rank_zero_only
    def wandb_logging(self, batch: Dict, output: Dict, step_count: int, train: bool = True, write_to_summary_writer: bool = True) -> None:

        mode = 'train' if train else 'val'
        losses = output['losses']
        for loss_name, val in losses.items():
            wandb.log({f"{mode}/{loss_name}": val.detach().item()})
        wandb.log({f"{mode}/step": step_count})
        return None
```

I also tried with self.log but it only works if I train on 1 GPU. for some reason in pytorch ddp, I cannot see any logs at all. It never logs when it is supposed to. I verified that the cod runs, its just the wandb.log does absolutely nothing.

Let me know if there is a fix for this please.

### Environment

WandB version: 0.16.1

OS: Mac

Python version: 3.10

**Comment by sydholl** [comment]
WandB Internal User commented: 
smandava98 commented: 
<img width="1223" alt="Screen Shot 2024-03-02 at 3 58 23 AM" src="https://github.com/wandb/wandb/assets/22734015/0c906359-a6e9-4af8-99bb-9e495125e78a">

Nothing seems to get logged. But I do see stuff popping up in my local wandb folder. Please let me know if there is a resolution for this

**Comment by fmamberti-wandb** [comment]
Hi @smandava98, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by 0xnakul** [comment]
Hi! @smandava98 I am facing a similar issue. I would be grateful if you could let me know how you tackled the issue.
Thanks!
