### ISSUE TITLE
[Q] wandb: Network error (TransientError), entering retry loop.

### ISSUE THREAD

**Issue by zearo-github** [wandb/wandb#7085]
when I use: ` wandb sync /data2_12t/user/zjj/wandb/offline-run-20240304_171154-hr4mlisq ` to upload the log file, it shows：`wandb: Network error (TransientError), entering retry loop.`
But I can ping the wandb.ai
![image](https://github.com/wandb/wandb/assets/90169120/2ac47720-bcbf-4a43-9764-93bf950323eb)

I run the code in the Ubuntu 20.04.4 LTS's command line.
Could you help me?

**Comment by fmamberti-wandb** [comment]
Hi @zearo-github sorry to hear you are experiencing this.

Would you mind sharing some additional information to help troubleshoot this:

- What version of `wandb` SDK are you currently running? (`wandb --version`)
- Would you be able to share the `wandb.log` and `wandb-internal.log` files for the run? These should be in `./wandb/run-date_time-runid/logs
- If you try logging a new Run, do you get the same error?

**Comment by fmamberti-wandb** [comment]
Hi @zearo-github, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by zearo-github** [comment]
oh, fine! Thank you for your help!!!
1.  version of wandb SDK: wandb, version 0.16.2
2. the logs are as follow:
[debug.log](https://github.com/wandb/wandb/files/14636126/debug.log)
[debug-internal.log](https://github.com/wandb/wandb/files/14636127/debug-internal.log)
3. Yes, it always shows me :wandb: Network error (TransientError),entering retry loop.
But when I try the tutorials in the colab like https://colab.research.google.com/github/wandb/examples/blob/master/colabs/intro/Intro_to_Weights_%26_Biases.ipynb
it works.

**Comment by zearo-github** [comment]
The log files of another run are as following:
[debug.log](https://github.com/wandb/wandb/files/14680643/debug.log)
[debug-internal.log](https://github.com/wandb/wandb/files/14680644/debug-internal.log)

**Comment by fmamberti-wandb** [comment]
Hi @zearo-github, thank you fore sending these. I see a few exceptions raising when trying to upload data to `https://storage.googleapis.com/`.

From the device you are running into this error:

- Where you ever able to successfully log Runs to W&B ? 
- Are there any Firewall rules or Proxy settings that may prevent access to `wandb.ai` or `storage.googleapis.com`?

**Comment by zearo-github** [comment]
1. Yes, I can not ping wandb.aistorage.googleapis.com, it return nothing, like this
![image](https://github.com/wandb/wandb/assets/90169120/c5cfca95-f522-4b41-8222-4717af342e1d)
Maybe this problem is probably caused by my remote server. I feel sad about this.

2. Today, I run my code online, it can upload some data, and produce the loss curve, like this:
![image](https://github.com/wandb/wandb/assets/90169120/38478641-aefa-4886-975b-4a46dce7d6aa)
Can I say this run is successfully?

Anyway, thank you for your reply! My friend. :kissing_heart:

**Comment by fmamberti-wandb** [comment]
It seems that is working - you may want to check that all the metrics are logged till the last step and that the Run is showing the `Finished` state in the Run table. Let us know if you have any further questions.

**Comment by zearo-github** [comment]
Thank you for your help！
