### ISSUE TITLE
[Q]Redirect to the sign up interface when logging in

### ISSUE THREAD

**Issue by LiYufengzz** [wandb/wandb#7095]
I have registered wandb through google account，Every time I try to log in, I am redirected to sign up and prompted that my username has already been used, making it impossible to log in.
![image](https://github.com/wandb/wandb/assets/26202915/72fe0a94-0313-466b-a04b-2f7c7d943c7a)
When I click on my email account on the above interface, it will jump to the registration interface below. 
![image](https://github.com/wandb/wandb/assets/26202915/88665d8d-e3f6-437a-b9f2-a3f7cc2cf0cd)

**Comment by MBakirWB** [comment]
Hi @LiYufengzz , our apologies you are facing this. What we can do is delete this account and have you sign up again as it appears you someone fell into a loop which we are investigating. Would you be okay with this?

**Comment by MBakirWB** [comment]
Hi @LiYufengzz , checking in once more if you are okay with use deleting your account so you can go through a fresh signup?
