### ISSUE TITLE
[App]: Changing the line thickness in the Edit Panel has failed.

### ISSUE THREAD

**Issue by ZhenZhuHuang** [wandb/wandb#7131]
### Current Behavior

When I want to change the thickness of the lines, the lines don't change at all.

### Steps To Reproduce

Enter Project -> Select a Run within the project -> Click Edit Panel -> Click Legend -> Change the thickness of the lines

### Screenshots

![屏幕截图 2024-03-09 170638](https://github.com/wandb/wandb/assets/97666369/b714c0d7-8db2-448d-9a81-214534576502)
![屏幕截图 2024-03-09 170616](https://github.com/wandb/wandb/assets/97666369/59aaad4e-8721-4444-98a0-ba2390dc11c7)

### Environment

OS:Windows

Browsers:Edge

Version:

**Comment by thanos-wandb** [comment]
Hi @ZhenZhuHuang thank you very much for reporting this issue. Our engineers have deployed a fix for it, and it should now be working for you. I will close this support request on our side, but please let us know if you encounter any further issues. We will be happy to continue investigating.
