### ISSUE TITLE
[CLI]:  'WandbMetricsLogger' object has no attribute '_implements_train_batch_hooks'

### ISSUE THREAD

**Issue by TheCrazyT** [wandb/wandb#7135]
### Describe the bug

Was getting this error recently.
Although my same code was working before.
I guess it happened either because of a wandb update or an update in keras itself.

```python
from wandb.keras import WandbMetricsLogger
callbacks = [WandbMetricsLogger()]
model.fit(x, y = BATCH_SIZE, epochs = epochs, steps_per_epoch = COUNT, callbacks = callbacks, verbose = 2)
```

```shell
File /opt/conda/lib/python3.10/site-packages/tf_keras/src/utils/traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File /opt/conda/lib/python3.10/site-packages/tf_keras/src/callbacks.py:245, in <genexpr>(.0)
    237 # Performance optimization: determines if batch hooks need to be called.
    239 self._supports_tf_logs = all(
    240     getattr(cb, "_supports_tf_logs", False) for cb in self.callbacks
    241 )
    242 self._batch_hooks_support_tf_logs = all(
    243     getattr(cb, "_supports_tf_logs", False)
    244     for cb in self.callbacks
--> 245     if cb._implements_train_batch_hooks()
    246     or cb._implements_test_batch_hooks()
    247     or cb._implements_predict_batch_hooks()
    248 )
    250 self._should_call_train_batch_hooks = any(
    251     cb._implements_train_batch_hooks() for cb in self.callbacks
    252 )
    253 self._should_call_test_batch_hooks = any(
    254     cb._implements_test_batch_hooks() for cb in self.callbacks
    255 )

AttributeError: 'WandbMetricsLogger' object has no attribute '_implements_train_batch_hooks'
```

### Environment

WandB version: 0.16.4

OS: Linux-5.15.133+-x86_64-with-glibc2.31

Python version: 3.10.13

Versions of relevant libraries:
tf_keras 2.16.0
tensorflow 2.16.1

**Comment by TheCrazyT** [comment]
Oh well.
In the end WandbMetricsLogger seem to use this subtype:
https://github.com/keras-team/keras/blob/v3.0.5/keras/callbacks/callback.py
And of course _implements_train_batch_hooks does not exist there.

Now I'm not shure who is to blame ...
That dependency madness with the same class in many projects(tf_keras/src/callbacks.py vs keras/src/callbacks/callback.py vs tensorflow/python/keras/callbacks.py) makes it even more difficult.
Maybe its really a bug within wandb, but currently it is hard to figure it out ...

**Comment by TheCrazyT** [comment]
Solved the problem by forcing an install of keras==2.15.0 over pip. (beside tf_keras install)
So wandb is not to blame ... it is just the normal dependency madness :(

**Comment by tjpeter** [comment]
Unfortunately, I need keras==2.16.0 or higher for some quantization optimisation. Any way to still use the WandbMetricsLogger or a workaround? Because I still get 

`AttributeError: 'WandbMetricsLogger' object has no attribute '_implements_train_batch_hooks'
`

**Comment by TheCrazyT** [comment]
Might be possible with a wrapper class.
But not shure how complicated it will be.
I doubt that there exist an out of the box solution.

**Comment by TheCrazyT** [comment]
Maybe keras.callbacks.LambdaCallback can be helpful for that approach.
