### ISSUE TITLE
I accidently deleted one team, can I still recover that, this team is very important to me[Q]

### ISSUE THREAD

**Issue by uwanny** [wandb/wandb#7136]
I accidently deleted one team, can I still recover that, this team is very important to me.

**Comment by JoanaMarieL** [comment]
Hi @uwanny 

We would like to inform you that Team Recovery is not an option at this time. 

We understand this is not great news, but given the fact that we ask for confirmation for the Team Name during deletion, so we need you guys to be careful and double check your entries.

**Comment by JoanaMarieL** [comment]
Hi @uwanny , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
