### ISSUE TITLE
[CLI]: WandbCallback overwrite all log at summary step (Huggingface Trainer)

### ISSUE THREAD

**Issue by nmd2k** [wandb/wandb#7147]
### Describe the bug

When running fine-tuning (on multiple-gpus) using HF Trainer, I notice Wandb logger eventually overwrite all experiment's log at the final summary step, but it work normally while running.

=> While running:
![image](https://github.com/wandb/wandb/assets/48562727/5ed05aa2-0209-4822-8bdc-1cf98876564b)

=> At the end:
![image](https://github.com/wandb/wandb/assets/48562727/5e086207-5b97-4874-a583-46cd7ed8430e)

### Environment

WandB version: wandb==0.16.4
OS: Linux
Python version: 3.9.18

Versions of relevant libraries:
transformer==4.37.1

**Comment by fmamberti-wandb** [comment]
Hi @nmd2k, thank you for reporting this. To help us reproduce and troubleshoot this issue, would you mind sharing some additional information:

- You mentioned you have seen this happening when running on multiple gpus. Did you run the same code on a single GPU and was the summary not overwritten in that case?  
- Can you share the URL to a Run where the summary was overwritten
- Can you share a snippet of code you used for the fine-tuning, in particular those sections where you are logging data to W&B?

These info will help us reproduce this issue on our side

**Comment by fmamberti-wandb** [comment]
Hi @nmd2k, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by fmamberti-wandb** [comment]
Hi @nmd2k, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by OE-Heart** [comment]
I have a similar problem when I use wandb with transformer. 
The wandb logger overwrite all train logs at the final summary step, but all eval logs are saved.

### Workspace URL
https://wandb.ai/ouyixin/knowledge_lens/runs/11bin6ih/workspace?nw=nwuserouyixin

###Script I uses
model=gpt2-medium
train_file=data/ablation/test_text.jsonl
CUDA_VISIBLE_DEVICES=0,1 python pretrain.py \
    --config_name $model \
    --tokenizer_name $model \
    --train_file $train_file \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --do_train \
    --do_eval \
    --evaluation_strategy steps \
    --output_dir outputs/$model/$(date +"%Y-%m-%d-%H-%M-%S")/output \
    --logging_dir outputs/$model/$(date +"%Y-%m-%d-%H-%M-%S") \
    --report_to wandb \
    --logging_steps 10 \
    --save_steps 50 \

### Environment
wandb==0.17.4
transformers==4.24.0

**Comment by OE-Heart** [comment]
Hi @fmamberti-wandb, can you give me some advice on how to fix this problem? I would appreciate it:)

> I have a similar problem when I use wandb with transformer. The wandb logger overwrite all train logs at the final summary step, but all eval logs are saved.
> ### Workspace URL
> 
> https://wandb.ai/ouyixin/knowledge_lens/runs/11bin6ih/workspace?nw=nwuserouyixin
> ### Script I uses
> 
> ```shell
> model=gpt2-medium
> train_file=data/ablation/test_text.jsonl
> CUDA_VISIBLE_DEVICES=0,1 python pretrain.py \
>     --config_name $model \
>     --tokenizer_name $model \
>     --train_file $train_file \
>     --per_device_train_batch_size 8 \
>     --per_device_eval_batch_size 8 \
>     --do_train \
>     --do_eval \
>     --evaluation_strategy steps \
>     --output_dir outputs/$model/$(date +"%Y-%m-%d-%H-%M-%S")/output \
>     --logging_dir outputs/$model/$(date +"%Y-%m-%d-%H-%M-%S") \
>     --report_to wandb \
>     --logging_steps 10 \
>     --save_steps 50 \
> ```
> 
> ### Environment
> 
> wandb==0.17.4 transformers==4.24.0
