### ISSUE TITLE
[App]: Filters do not work well

### ISSUE THREAD

**Issue by WanchengWildMan** [wandb/wandb#7162]
### Current Behavior

On Mar. 14th, The filters cannot search for a string, e.g., when I search in the ID filter as follows, it doesn't appear any results. 
![image](https://github.com/wandb/wandb/assets/33253257/ba39aee4-104a-4572-a8b3-1847b6d81a78)

### Expected Behavior

The filters work well as yesterday.

### Steps To Reproduce

1. Add a filter
2. select 'ID' or Name in the key
3. click the  'Select a value'
4. Nothing can be searched

### Environment

OS: Windows, Android

Browsers: Chrome, Edge

Version:

### Additional Context

I have hundreds of runs, maybe it takes too much time to fetch all the values? But it works well before today.

**Comment by ssisk** [comment]
Sorry that you encountered this! We are pushing out a fix, should be out shortly (in the next half hour or so)

**Comment by MBakirWB** [comment]
@WanchengWildMan this is now fixed by the team. If you encounter any problems, please feel free to reopen the conversation.
