### ISSUE TITLE
[App]: Data not available for various plots

### ISSUE THREAD

**Issue by Aveturi13** [wandb/wandb#7169]
### Current Behavior

Hi,
I am running a classifier model training script which generates a couple of custom plots: a barplot depicting class frequencies of the train/val set, the ROC and PRC curves of the val-set performance and a confusion matrix. For generating all these plots, I've used the basic functionality provided in the wandb documentation (Code snippets shared below). 

I use both cloud and private versions of wandb. In the cloud version, when I run the attached code (shared below), the plots are successfully generated but when running in the local version, I get a "No data available" for all these plots. I'm not sure why exactly this is happening. I would greatly appreciate some help on this!

### Expected Behavior

I'm supposed to get the following output (seen in cloud version):

<img width="1455" alt="Screenshot 2024-03-17 at 7 07 44 PM" src="https://github.com/wandb/wandb/assets/44966149/01e148cb-b13f-468c-93c3-769a86f9a1c3">

But I get this (local wandb server):

<img width="1174" alt="Screenshot 2024-03-17 at 7 17 18 PM" src="https://github.com/wandb/wandb/assets/44966149/57764ee0-a6a5-4225-95f2-cb98f11a50db">

### Steps To Reproduce

Following is the code I wrote for generating these charts/plots:

### Code for bar plot
```
# log the class frequencies in each fold
train_classes, train_outputs = np.unique(train.outputs, return_counts=True)
val_classes, val_outputs = np.unique(val.outputs, return_counts=True)
train_outputs = train_outputs / np.sum(train_outputs)
val_outputs = val_outputs / np.sum(val_outputs)

# create wandb tables
train_data = [[label, val] for (label, val) in zip(train_classes, train_outputs)]
train_table = wandb.Table(data=train_data, columns=["class", "frequency"])
val_data = [[label, val] for (label, val) in zip(val_classes, val_outputs)]
val_table = wandb.Table(data=val_data, columns=["class", "frequency"])

# log tables as barplot
wandb.log(
    {
        f"train_distribution_fold": wandb.plot.bar(
    train_table, "class", "frequency", title=f'Class Distribution for Train set'
    ),
    f"val_distribution_fold": wandb.plot.bar(
    val_table, "class", "frequency", title=f'Class Distribution for Val set'
        ),
    }
)
```

### Code for model evaluation charts
```
# log model evaluation charts
wandb.log(
    {
        "pr": wandb.plot.pr_curve(ground_truths.numpy(), predictions.numpy(), labels=val_ds.class_mapping),
        "roc": wandb.plot.roc_curve(ground_truths.numpy(), predictions.numpy(), labels=val_ds.class_mapping),
        "conf_mat": wandb.plot.confusion_matrix(y_true=ground_truths.numpy(), probs=predictions.numpy(),
class_names=val_ds.class_mapping)
    }
)
```

### Environment

I'm running my code on a remote linux machine and visualizing the results on my desktop browser.

OS: Linux

Browsers: Chrome 

Version: Chrome Version 122.0.6261.112 (Official Build) (arm64), W&B Local 0.50.3, W&B package version 0.16.3.

### Additional Context

Similar to the suggestions in issue #4368, I ran a `wandb verify` and got the following:

```
Default host selected: http://localhost:8081
Find detailed logs for this test at: /tmp/tmpmj4fcxqt/wandb
Checking if logged in...................................................✅
Checking signed URL upload..............................................✅
Checking ability to send large payloads through proxy...................✅
Checking requests to base url...........................................❌
Connections are not made over https. SSL required for secure communications.
Checking requests made over signed URLs.................................❌
Signed URL requests not made over https. SSL is required for secure communications.
Checking CORs configuration of the bucket...............................❌
Your object store does not have a valid CORs configuration, you must allow GET and PUT to Origin: http://localhost:8081
Checking wandb package version is up to date............................✅
Checking logged metrics, saving and downloading a file..................✅
Checking artifact save and download workflows...........................✅
```

Not sure if the CORs configuration is the issue, but I didn't find any resolution for this issue in #4368 

Additionally, here is the commands used to start up the local server on the remote machine:

```
wandb server start --port 8081
wandb login --host=http://localhost:8081
```

**Comment by umakrishnaswamy** [comment]
hey @Aveturi13 - this seems like a CORS issue, but to confirm, would it be possible to send over the console/network logs associated with the workspace where you're not seeing the charts populate? if you're on chrome, you can obtain this by right clicking > Inspect > console/network

**Comment by umakrishnaswamy** [comment]
hey @Aveturi13 - I wanted to follow up on this. please let me know if you're able to provide the above info
