### ISSUE TITLE
[CLI]: After wandb sync, There no summary value. Then I checked wandb-summary.json, the content is empty.

### ISSUE THREAD

**Issue by John1911603424** [wandb/wandb#7175]
### Describe the bug

After wandb sync, There no summary value. Then I checked wandb-summary.json, the content is empty.

```python
experiment.log({
                                'train loss': loss.item() if accum_steps <= 1 else loss.item()*divided_accum_steps,
                                'learning rate': optimizer.param_groups[0]['lr'],
                                'validation loss': val_loss,
                                # 'images': wandb.Image(images[0].cpu()),
                                # 'masks': {
                                #     'true': wandb.Image(true_masks[0].float().cpu()),
                                #     'pred': wandb.Image(masks_pred.argmax(dim=1)[0].float().cpu()),
                                # },
                                'step': global_step,
                                'epoch': epoch,
                                # **histograms
                            })

                            new_train_scores = {**train_scores[0], **train_scores[1], **train_scores[2], **train_scores[3], **train_scores[4],
                                'step': global_step,
                                'epoch': epoch,}
                            new_val_scores = {**val_scores[0], **val_scores[1], **val_scores[2], **val_scores[3], **val_scores[4],
                                'step': global_step,
                                'epoch': epoch,}
                            experiment.log(new_train_scores)
                            experiment.log(new_val_scores)

```

```shell

```

### Additional Files

[offline-run-20240315_130221-p5jara3x.zip](https://github.com/wandb/wandb/files/14644677/offline-run-20240315_130221-p5jara3x.zip)

### Environment

WandB version:
0.15.11

OS:
Ubuntu

Python version:
3.8
Versions of relevant libraries:

**Comment by luisbergua** [comment]
Hey @John1911603424, thanks for flagging this! Do you see the same issue if you upgrade your SDK to `0.16.4` with `pip install wandb -U`?

**Comment by John1911603424** [comment]
> Hey @John1911603424, thanks for flagging this! Do you see the same issue if you upgrade your SDK to `0.16.4` with `pip install wandb -U`?

I trained many models on WandB version 0.15.11 and only three records result in this problem, I haven't tried the new version of the SDK yet, do I need to retrain and upload or can I upload this problematic record file.

**Comment by John1911603424** [comment]
Is there any way for me to upload the metric data from the Wandb file

**Comment by luisbergua** [comment]
Hey @John1911603424, you can use our Public API to populate the summary like:
```
import wandb

api = wandb.Api()
run = api.run(<run-path>)
run.summary[<key>] = value
run.update()  
```
