### ISSUE TITLE
[Q] How to see recent runs in the updated wandb UI?

### ISSUE THREAD

**Issue by DachunKai** [wandb/wandb#7204]
In the UI updated on March 13, 2024, we can no longer directly see recent runs, which I find inconvenient.

**Comment by fmamberti-wandb** [comment]
Hi @DachunKai, thank you for reaching out with your feedback.

In your home page you should be able to see a list of recent Runs for the organisation you currently have selected, as follow:

<img width="1045" alt="Screenshot 2024-03-25 at 09 34 37" src="https://github.com/wandb/wandb/assets/152398141/dec04e2f-9e65-4828-b59a-ec846386d23a">

If you are part of multiple organisations, you may have to select a different one from your User profile: clicking on your user image on the top-right of the page, from the dropdown menu you will have a `Other accounts` section with all the organisations you are part of and can see recent Runs from each one selecting it there. Please let me know if you have any further questions on this.

**Comment by fmamberti-wandb** [comment]
Hi @DachunKai , I wanted to follow up on this request. Please let us know if we can be of further assistance

**Comment by fmamberti-wandb** [comment]
Hi @DachunKai , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
