### ISSUE TITLE
[Q]how to launch job in self-built k8s environment, is there has guides about this?

### ISSUE THREAD

**Issue by ICDI0906** [wandb/wandb#7212]

**Comment by fmamberti-wandb** [comment]
Hi @ICDI0906, thank you for reaching out with your question.

You can follow the documentation on how to set up Launch on K8s [here](https://docs.wandb.ai/guides/launch/setup-launch-kubernetes). The documentation will include steps to:

- [Configure](https://docs.wandb.ai/guides/launch/setup-launch-kubernetes#configure-a-queue-for-kubernetes) and [Create](https://docs.wandb.ai/guides/launch/setup-launch-kubernetes#configure-a-queue-for-kubernetes) a Queue
- [Configure](https://docs.wandb.ai/guides/launch/setup-launch-kubernetes#configure-a-queue-for-kubernetes) a Launch agent using Helm chart
- [Configure](https://docs.wandb.ai/guides/launch/create-launch-job) a Launch Job, with a linked [Colab Notebook](https://colab.research.google.com/drive/1wX0OSVxZJDHRsZaOaOEDx-lLUrO1hHgP)

Please let me know if you have any further questions.

**Comment by wandb-kc** [comment]
Francesco Mamberti commented: 
Hi, thank you for reaching out with your question.

You can follow the documentation on how to set up Launch on K8s here. The documentation will include steps to:


- Configure and Create a Queue
- Configure a Launch agent using Helm chart
- Configure a Launch Job, with a linked Colab Notebook

Please let me know if you have any further questions.

**Comment by fmamberti-wandb** [comment]
Hi @ICDI0906, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
