### ISSUE TITLE
[App]: The list of options for X-axis is non-deterministic

### ISSUE THREAD

**Issue by ValerianRey** [wandb/wandb#7214]
### Current Behavior

In my workspace, when I click "edit panel" on a plot and I try to select the x-axis, the list of options is incomplete and non-deterministic. I want to use "epoch" for x-axis, but this option does not always appear. If I reload the page, the list of options may be different, and sometimes "epoch" appears.

On the first screenshot, we can see that the list of options is much longer than in the second screenshot. All I did between those 2 screenshots was to reload the page.

![Screenshot from 2024-03-24 14-09-27](https://github.com/wandb/wandb/assets/31951177/d0823545-bf56-4e46-a702-948f506e7e4c)
![Screenshot from 2024-03-24 14-09-45](https://github.com/wandb/wandb/assets/31951177/0e48584d-8be9-4b2a-a2b3-5d3894d2985b)

Sometimes I have to reload the page dozens of times before "epoch" actually appears in the list. And I have to do this for all of my ~50 plots...

### Environment

OS: Ubuntu 20.04.6 LTS

Browsers: Brave [Version 1.63.174 Chromium: 122.0.6261.128 (Official Build) (64-bit)](https://brave.com/latest/)

Version:

**Comment by nate-wandb** [comment]
Hi @ValerianRey, could you possibly share a link to the project where you are seeing this and I will take a look?

Thank you,
Nate

**Comment by anmolmann** [comment]
Hi @ValerianRey , I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by anmolmann** [comment]
Hi @ValerianRey , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
