### ISSUE TITLE
[Q] What process is being tracked on a launch job?

### ISSUE THREAD

**Issue by mfung37** [wandb/wandb#7252]
I was wondering what is being tracked when is a launch job is being used.

I have a launch-agent running locally using docker containers and using the free online wandb.ai website. 
I launched a job, [autogluon_job.txt](https://github.com/wandb/wandb/files/14796384/autogluon_job.txt), that I let run to test out the systems tab.

The output when running htop shows constant high cpu usage, this should be predominantly from running the job
![Htop output](https://github.com/wandb/wandb/assets/157086188/2ad1a927-dc9f-473e-a857-391b2d7d9262)

However, in wandb, it shows fairly consistently low almost 0% cpu usage
![System Tab CPU Percent](https://github.com/wandb/wandb/assets/157086188/c023d2c9-e55d-4640-b33e-83b6413395c7)

What is being tracked, which in this case cpu usage?
If possible, can I track all processes in the container as aggregate?

**Comment by ArtsiomWB** [comment]
Hi @mfung37! Apologies you are running into this behavior, could you please provide a link to your workspace where you are experiencing it?

Could you please also talk a bit about your experiment setup? Do you use any external libraries?

**Comment by mfung37** [comment]
Here is the [workspace](https://wandb.ai/marfung37/launch_demo?nw=nwusermarfung37). The latest run "breezy-elevator-8" was the run where I ran the sample-launch-job. You can see the cpu usage chart in the systems tab, which I let run for around 40 minutes.

I was running with the external library [autogluon](https://auto.gluon.ai), an AutoML solution, that I was interested in running on weights and biases. For my run, I had ran sample code that autogluon had that was modified to work with weights and biases to be a launch job.

However, the tracking of the cpu usage didn't seem to match what I saw on my system of close to 100% cpu consistently. Therefore, I was wondering what/how things are being tracked, so I can see if maybe I modify the code to fit my needs or choose not to run autogluon.

**Comment by ArtsiomWB** [comment]
@mfung37 hey wanted to follow up with you regarding this thread!

Would you be able to send me a toy code example of you running your launch, so I could see if I am experiencing the same behavior?

**Comment by ArtsiomWB** [comment]
Hi, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
