### ISSUE TITLE
[Q] argument `fps` to `wandb.Video` does not change speed of created video

### ISSUE THREAD

**Issue by liubaoryol** [wandb/wandb#7269]
I am creating a video from a numpy array, but the speed is too fast and I am not able to properly see it and understand it.

Let's take the example code from the official documentation to reproduce the error:

```
import numpy as np
import wandb

wandb.init()
# axes are (time, channel, height, width)
frames = np.random.randint(low=0, high=256, size=(10, 3, 100, 100), dtype=np.uint8)
wandb.log({"video": wandb.Video(frames, fps=4)})
```
I want the change between frames to be slower, so I changed `fps=4` to `fps=1` and it is still fast. I also changed `fps=10000` and see no difference at all.
NOTE: the resulting video of wandb that I am referencing to is a gif on my local. I am judging not by the wandb dashboard, as it seems to have internal errors itself so I'm not able to visualize it there yet (hopefully this will be solved soon)

**Comment by thanos-wandb** [comment]
Hi @liubaoryol thank you for reporting this issue. Just a quick update this should be resolved with this PR: https://github.com/wandb/wandb/pull/8585 therefore marking this ticket as resolved for now. Please let us know if you are still encountering any issue and we will be more than happy to keep investigating.
