### ISSUE TITLE
[Q] Create matplotlib and save as wandb.Image

### ISSUE THREAD

**Issue by liubaoryol** [wandb/wandb#7270]
In my imitation learning experiments, I am logging a video of the gym environment's rollout, obtained at each iteration of my model's training. Together with the video, I want to log a plot (which also should be updated at each training iteration) representing some latent variables added by myself to this gym environment. However, to create this plot I need to use matplotlib or seaborn, but the core get dumped as soon as I use these.
```  
latents = np.zeros(10)
fig, ax = plt.subplots() # FAILS HERE
ax.plot(latents)
fig.canvas.draw()
# Convert the canvas to a raw RGB buffer
buf = fig.canvas.tostring_rgb()
ncols, nrows = fig.canvas.get_width_height()
image = np.frombuffer(buf, dtype=np.uint8).reshape(nrows, ncols, 3)
self.wandb_run.log({"rollout/latent": wandb.Image(image)})
```

How could I add a plot relating to the particular rollout?

**Comment by nate-wandb** [comment]
Hi @liubaoryol, this might be better to raise in Matplotlib repo if it is failing before running any `wandb` code unless you suspect it might be caused by the `wandb` library?

Thank you,
Nate

**Comment by wandb-kc** [comment]
WandB Internal User commented: 
nate-wandb commented: 
Hi @liubaoryol, this might be better to raise in Matplotlib repo if it is failing before running any `wandb` code unless you suspect it might be caused by the `wandb` library?

Thank you,
Nate

**Comment by liubaoryol** [comment]
Hi! Thank you for your response. I found some workarounds to this, so I will not be needing this anymore
