### ISSUE TITLE
[App]: Sweep run the same parameters multiply times. 

### ISSUE THREAD

**Issue by bigbenbird** [wandb/wandb#7271]
### Current Behavior

I start a Sweep task, and it runs for more than `1000` runs, but it only search for about `304`  parameters. In average, the sweep platform runs 3 times for the same parameters. 

### Expected Behavior

1 run for 1 parameter

### Environment

OS: Linux

Browsers: Chrome

Version:

**Comment by nate-wandb** [comment]
Hi @bigbenbird could you share a link to the workspace where this is happening and I can take a look?

**Comment by nate-wandb** [comment]
Hi @bigbenbird, I just wanted to follow up on this and see if you still wanted us to look into this?
