### ISSUE TITLE
[Q] Can I delete all of my created teams in wandb?

### ISSUE THREAD

**Issue by LzyFischer** [wandb/wandb#7273]
I create two teams in wandb just for test, while I couldn't delete them fully and can't create new academic teams since I have one active.
Is there anyway to delete all of them?

**Comment by wandb-kc** [comment]
Internal GitHub User commented: 
I create two teams in wandb just for test, while I couldn't delete them fully and can't create new academic teams since I have one active.
Is there anyway to delete all of them?

**Comment by paulosabile-wb** [comment]
Hi Kevin!

Happy to help you on this one! You can follow these steps to delete your team:
 

1. Login to wandb
2. Access your account where the team is located
3. From the left side pane, under Teams section, click the Team you need to delete
4. Click Team Settings
5. Scroll on the bottom part of the page and you can find the Delete button

 
Please note that team deletion cannot be reversed. Once you deleted a team, there is no way to revert or undo it.
 
I hope this helps. If you have questions or encountered any issues let us know!
 
 
Thank you!

**Comment by paulosabile-wb** [comment]
Hi @wandb-kc,

We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

Best Regards,
Paulo

**Comment by paulosabile-wb** [comment]
Hi @wandb-kc, since we have not heard back from you we are going to mark this request as Solved. If you would like to re-open the conversation, please let us know!
