### ISSUE TITLE
[Q] Can I restore the project I deleted?

### ISSUE THREAD

**Issue by kdwonn** [wandb/wandb#7278]
I have mistakenly deleted one important project just now, and I want to restore it. My username is kdwon and project name is ocl-pool. Is there any methods?

**Comment by JoanaMarieL** [comment]
Hello @kdwonn , sorry to hear that but unfortunately complete project restoration is not supported at this time as after the user confirms they want to delete the project by typing "DELETE ALL" in the pop-up, the project is immediately moved through our garbage collectors. We also have a warning before proceeding that deletion cannot be undone.

Let us know if you have further questions.

**Comment by JoanaMarieL** [comment]
Hi @kdwonn , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by wandb-kc** [comment]
Joana Marie commented: 
Hi kdwonn, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
