### ISSUE TITLE
[Q] How can i delete the organization in wandb?

### ISSUE THREAD

**Issue by TheDarkKnight-21th** [wandb/wandb#7302]
<img width="1148" alt="image" src="https://github.com/wandb/wandb/assets/85755635/496304c6-8619-4227-a3fb-3cfe71faac6d">

how can i delete the organization?? 

i visited the account-setting in the organization but, there is nothing. (white boar)

how can i do?

**Comment by JoanaMarieL** [comment]
Hi @TheDarkKnight-21th , happy to help and we can assist you in deleting the requested org. Make sure that the org does not have any teams belong to it and let us know if we will now proceed in deleting it. To confirm the org name: `20240101-org`?

**Comment by TheDarkKnight-21th** [comment]
> Hi @TheDarkKnight-21th , happy to help and we can assist you in deleting the requested org. Make sure that the org does not have any teams belong to it and let us know if we will now proceed in deleting it. To confirm the org name: `20240101-org`?

yes ! i don't have any teams! and i wanna delete the organization '20240101-org' ! :)

i have a question more. Can't USER directly delete the organization? i think it is quite uncomfortable :(

**Comment by wandb-kc** [comment]
Joana Marie commented: 
Request #64161 "[User Management] How can i dele..." was closed and merged into this request. Last comment in request #64161:

hi. i am personal user. (my id is not academic id but is personal id )

i wanna delete the organization(corporate). In the organization, there is not any team already.

In setting, there is the delete button for team , not organization.

when i visited the account-setting, also there is nothing (just white)

how can i do?

adding issue : )

 ![image](https://global.discourse-cdn.com/business7/uploads/wandb/optimized/2X/3/3efad0a9fa06024294a2c1a6ecc06f91d6cf064f_2_656x500.png)
image1198×913 67 KB

I posted this issue already also this on the wandb github.
( [Q] How can i delete the organization in wandb? · Issue #7302 · wandb/wandb · GitHub )

After asking the delete decision to me , the developer have not repliy more.

What should i do?

 [Discourse post]

**Comment by JoanaMarieL** [comment]
Hello @TheDarkKnight-21th | @wandb-kc , apologies for the late response, we will proceed on deletion of the requested org. We'll advise once completed. As for the request of having the button for org deletion, we may file it as a Feature Request if you'd like :)

**Comment by TheDarkKnight-21th** [comment]
> Hello @TheDarkKnight-21th | @wandb-kc , apologies for the late response, we will proceed on deletion of the requested org. We'll advise once completed. As for the request of having the button for org deletion, we may file it as a Feature Request if you'd like :)

plz delete the organization quickly :( .

**Comment by wandb-kc** [comment]
WandB Internal User commented: 
TheDarkKnight-21th commented: 
> Hello @TheDarkKnight-21th | @wandb-kc , apologies for the late response, we will proceed on deletion of the requested org. We'll advise once completed. As for the request of having the button for org deletion, we may file it as a Feature Request if you'd like :)

plz delete the organization quickly :( .

**Comment by wandb-kc** [comment]
Joana Marie commented: 
Request #64313 "[Non Support] [Q] How can i dele..." was closed and merged into this request. Last comment in request #64313: 

![image](https://github.com/wandb/wandb/assets/85755635/49ca7389-18c9-4cfa-a27b-745f44bb2062)


how can i delete the organization??

i visited the account-setting in the organization but, there is nothing. (white boar)

how can i do?

also, ! i don't have any teams! and i wanna delete the organization '20240101-org' absolutely ( corporate account, not personal account )! :)

Finally, i have a question more. Can't USER directly delete the organization? i think it is quite uncomfortable :(

**Comment by wandb-kc** [comment]
Joana Marie commented: 
Request #64318 "[User Management] [Feature]: Pl..." was closed and merged into this request. Last comment in request #64318:

### Description

Now, we have to request on github issue or wandb help to delete or rename the organization.

it is so uncomfortable for developer to use the wandb :(

plz make a button for deleting the organization.

https://github.com/wandb/wandb/issues/7302

### Suggested Solution

plz make a button for deleting the organization.

### Alternatives

_No response_

### Additional Context

_No response_

**Comment by thanos-wandb** [comment]
Hi @TheDarkKnight-21th just a quick update to let you know that we have now deleted the Org per your request. I will now close this ticket but please feel free to reopen it if you had any additional questions related to this.

**Comment by geriskenderi** [comment]
Hello. Very similarly to this issue, I have an organization I wish to delete without any teams inside named "https://wandb.ai/bidsa-omics-org/"

My personal username is "gskenderi". Could you please proceed with the deletion of the organization?
