### ISSUE TITLE
[App]: Can't add logs to report in older project

### ISSUE THREAD

**Issue by bdytx5** [wandb/wandb#7305]
### Current Behavior

I have 20+ projects. When trying to add some charts to an existing report within one of my older projects, it does not show the projects in the dropdown after clicking "add to report." I just noticed this and I assume its a bug. 

### Expected Behavior

All of my projects should show up in dropdown after clicking "add to report" 

### Steps To Reproduce

Create 21+ projects, and try to add a report to the first project. 

### Environment

OS:

Browsers: Chrome

Version: 123.0.6312.105

**Comment by ArtsiomWB** [comment]
Hi @bdytx5! Thank you for writing in!

Could you please go ahead and send me the project you are trying to create a Report in, and the other project you are trying to add to the report?

**Comment by bdytx5** [comment]
https://wandb.ai/byyoung3/ml-news?nw=nwuserbyyoung3

**Comment by ArtsiomWB** [comment]
When you are trying to add the charts to the report from a certain project. Do you press on a chart and then press `add to report`?

Or is there a different way of you adding them to the report?
<img width="396" alt="image" src="https://github.com/wandb/wandb/assets/115654725/7f6b6eab-ffe4-4dc7-952d-f730e2333c5a">

**Comment by ArtsiomWB** [comment]
Hi! Wanted to follow up with you regarding this thread

**Comment by bdytx5** [comment]
yeah sorry about the delay, I lost track of this. You are correct, I simply click the add to report button.

**Comment by ArtsiomWB** [comment]
Thank you for confirming! @bdytx5, could you send me a screenshot of this behavior happening to you? I am not having much luck reproducing this on my side. :(

It would be great to see you pressing the add to report button and then the project you are expecting to see there, not, being there.

**Comment by ArtsiomWB** [comment]
Hi! Wanted to follow up with you regarding this thread.

**Comment by bdytx5** [comment]
<img width="460" alt="Screenshot 2024-04-24 at 8 57 17 PM" src="https://github.com/wandb/wandb/assets/32812705/0248c5c6-3e83-4460-ae68-b6f15edc9be9">

**Comment by ArtsiomWB** [comment]
No worries at all! What project are you expecting to see in the screenshot and not seeing on your side in the UI? @bdytx5

**Comment by ArtsiomWB** [comment]
Hey! Wanted to follow up with you regarding this thread.

**Comment by bdytx5** [comment]
ml-news project doesn't seem to show. I created a ml-news2 as a workaround for now.

**Comment by ArtsiomWB** [comment]
I do see `ml-news` on my side when looking at your UI. Thank you for letting me know you do have a workaround at the moment. I will go ahead and let our engineering team know about this behavior so they will keep their eyes on it in case it pops up again. If you do see this again, please let us know as well. Thank you so much for your time @bdytx5


<img width="566" alt="image" src="https://github.com/wandb/wandb/assets/115654725/80cb9ab0-8d4f-4345-a4d0-55a1dffa59af">
