### ISSUE TITLE
[Q] Questions about freeing up storage.

### ISSUE THREAD

**Issue by nzl-thu** [wandb/wandb#7311]
Hello,

I am seeking to optimize the storage usage in my wandb account by removing media files and have two questions regarding the storage management UI:

1. When I choose a run and hit the delete button like this:
<img width="1859" alt="image" src="https://github.com/wandb/wandb/assets/36226201/31df311d-3adb-4381-9520-1ac252f046ba">
which of the following is the expected outcome?

a) the entire run is removed, including the logged data (e.g., training loss).
b) only the media/artifacts associated with the run are deleted, while the logged data remains intact.
I am inclined to believe it is the latter (b), as the run directory appears to contain only a "media" folder. However, as the exact storage location of the logged data is not unclear to me, I am seeking confirmation here.

2. After I deleted all files in a run (`dm6frnej` for example):
<img width="1862" alt="image" src="https://github.com/wandb/wandb/assets/36226201/f0df81e6-1573-4598-ab4b-09b9656c92f7">
why the storage utilization of this run remains changed?
<img width="1868" alt="image" src="https://github.com/wandb/wandb/assets/36226201/230d4e73-8556-49b4-9d76-20c68689b40d">
I have read that wandb has some "time-to-live (TTL)" mechanism for artifacts management. However, I have not set the TTL policy for my project so I suppose this may not be the reason.

Thank you!

**Comment by Adamits** [comment]
I am seeing exactly the same behavior. I would have thought that some caching mechanism could be causing this, but several days have passed and the app still says I have no more storage space.

This is a pretty large problem as it makes my account unusable.

**Comment by nzl-thu** [comment]
> I am seeing exactly the same behavior. I would have thought that some caching mechanism could be causing this, but several days have passed and the app still says I have no more storage space.
> 
> This is a pretty large problem as it makes my account unusable.

Yes! This is frustrating...

**Comment by Riccorl** [comment]
I've been deleting files through the Python API for a week but still see no changes in the web UI. I want to access my runs at some point...

**Comment by ArtsiomWB** [comment]
Hey guys apologies you are seeing this behavior. To confirm, both @nzl-thu and @Adamits are deleting their data using the UI and @Riccorl is deleting it using the API?

@Riccorl, could you send me the toy script of you trying to delete your data?

Could you guys also all send me your username so I can look into your accounts as well, as potentially escalate this to our engineering team.

**Comment by Adamits** [comment]
Hi @ArtsiomWB 

Mine seems to have started working somewhere in the last few hours. I still might have a script inadvertently synching model data, so I suspect I could need to mass delete artifacts again. In case it is still useful, my username is also adamits on W&B. My profile is at https://wandb.ai/adamits

Thanks!

**Comment by nzl-thu** [comment]
> Hey guys apologies you are seeing this behavior. To confirm, both @nzl-thu and @Adamits are deleting their data using the UI and @Riccorl is deleting it using the API?
> 
> @Riccorl, could you send me the toy script of you trying to delete your data?
> 
> Could you guys also all send me your username so I can look into your accounts as well, as potentially escalate this to our engineering team.

Sure, my profile is at https://wandb.ai/thu-n.
Meanwhile, could you please answer my first question as well?

Thank you!

**Comment by nzl-thu** [comment]
Hi @ArtsiomWB 

My profile is at https://wandb.ai/thu-n.
Meanwhile, could you please answer my first question as well?

Thank you!

**Comment by Riccorl** [comment]
> Hey guys apologies you are seeing this behavior. To confirm, both @nzl-thu and @Adamits are deleting their data using the UI and @Riccorl is deleting it using the API?
> 
> @Riccorl, could you send me the toy script of you trying to delete your data?
> 
> Could you guys also all send me your username so I can look into your accounts as well, as potentially escalate this to our engineering team.

Here is the script I used:

```python
import argparse
import wandb

if __name__ == "__main__":
    arg_parser = argparse.ArgumentParser()
    arg_parser.add_argument("project_name", type=str, help="Name of the project")
    arg_parser.add_argument(
        "--dry_run", action="store_true", help="If true, don't delete anything"
    )
    args = arg_parser.parse_args()

    dry_run = args.dry_run

    project_name = args.project_name

    api = wandb.Api(overrides={"project": project_name, "entity": "riccorl"})
    runs = api.runs(project_name)

    print("Deleting checkpoints and models in runs")
    for run in runs:
        if run.state != "finished":
            continue
        for f in run.files():
            if "ckpt" in f.name or "pt" in f.name or "hf_model" in f.name or "retriever" in f.name or "document_index" in f.name or "model" in f.name:
                print(f"DELETING {run.id}/{f.name}")
                if not dry_run:
                    f.delete()
                else:
                    print("DRY RUN: NOT DELETING")

    print("Deleting models in artifacts")
    project = api.project(project_name)
    for artifact_type in project.artifacts_types():
        for artifact_collection in artifact_type.collections():
            for version in api.artifacts(artifact_type.type, artifact_collection.name):
                if artifact_type.type == "model":
                    print(f"DELETING {version.name}")
                    if not dry_run:
                        version.delete(delete_aliases=True)
                    else:
                        print("DRY RUN: NOT DELETING")
```

Just FYI, I can see the prints ("DELETING ...") the first time I run the script on a project, but it doesn't print that line anymore after that.

**Comment by ArtsiomWB** [comment]
Apologies for taking a long time to get back to you guys. Currently we are experiencing some unexpected behaviors regarding freeing up space, and we are sincerely sorry for the inconvenience. What happens right now is that after you free up your space the job gets added to the queue, and because of a very high number of people currently cleaning up their accounts, it takes longer than usual to update the storage that is displayed in the account. 

Regarding @nzl-thu's question I just tried it out on my side and once you delete your run from that page, option a is the one that is happening:
> a) the entire run is removed, including the logged data (e.g., training loss).
So no metrics or artifacts + media files are saved. 

Since it has been sometime since I've gotten back to you guys, is everyone still seeing this behavior?

**Comment by Riccorl** [comment]
Thanks for the update!

> Since it has been sometime since I've gotten back to you guys, is everyone still seeing this behavior?

Yes I still can't access my runs due to storage limits

**Comment by ArtsiomWB** [comment]
@Riccorl, looking at your code, to confirm you are trying to delete checkpoints in models in runs per a single project right?

**Comment by ArtsiomWB** [comment]
@nzl-thu , you could use a scrip like this:
```
import wandb

# Initialize the W&B API
api = wandb.Api()

# Replace <entity> with your actual entity name
entity = "<entity>"

# Define the file extensions you want to delete
image_extensions = [".png", ".jpg", ".jpeg", ".bmp", ".gif"]
media_extensions = [".mp4", ".mp3", ".wav", ".avi", ".mov"]
extensions_to_delete = image_extensions + media_extensions

# Iterate over all projects
for project in api.projects(entity):
    print(f"Processing project: {project.name}")
    
    # Iterate over all runs in the project
    for run in api.runs(f"{entity}/{project.name}"):
        print(f" - Processing run: {run.id}")
        
        # Get all files in the run
        files = run.files()
        
        # Delete files with the specified extensions
        for file in files:
            if any(file.name.endswith(ext) for ext in extensions_to_delete):
                print(f"   - Deleting file: {file.name}")
                file.delete()
```

Just be careful because it does go over every single project in your entity and delete all of the media files from it.

**Comment by Riccorl** [comment]
> @Riccorl, looking at your code, to confirm you are trying to delete checkpoints in models in runs per a single project right?

Yep, I confirm

**Comment by Riccorl** [comment]
Given the current issues, isn't it possible to give run access in the meantime? I can't access my account for a month now.

**Comment by Riccorl** [comment]
> @Riccorl, apologies it's taking so long to resolve this, could you please write into [supprt@wandb.com](mailto:supprt@wandb.com), and I can potentially help you with that there? For us to talk privately about your account status?

Sure, thanks for the help!

**Comment by czyuyue** [comment]
> Apologies for taking a long time to get back to you guys. Currently we are experiencing some unexpected behaviors regarding freeing up space, and we are sincerely sorry for the inconvenience. What happens right now is that after you free up your space the job gets added to the queue, and because of a very high number of people currently cleaning up their accounts, it takes longer than usual to update the storage that is displayed in the account.
> 
> Regarding [@nzl-thu](https://github.com/nzl-thu)'s question I just tried it out on my side and once you delete your run from that page, option a is the one that is happening:
> 
> > a) the entire run is removed, including the logged data (e.g., training loss).
> > So no metrics or artifacts + media files are saved.
> 
> Since it has been sometime since I've gotten back to you guys, is everyone still seeing this behavior?

Thanks. You said the request will be added to the queue. How long I can release my memory space? Since I need some memory urgently.

**Comment by limesqueezy** [comment]
The issue persists. It might even take a whole day to get media files deleted through the UI.

**Comment by vsakovskaya** [comment]
The issue still persists. I've deleted media files through the UI but the storage utilization still remains unchanged.

**Comment by wullli** [comment]
I still have this exact issue in 2025.

**Comment by simpleParadox** [comment]
How long does it usually take for the backend to update the correct storage amount? My username is `simpleparadox` on wandb.

**Comment by JgusbcAIST** [comment]
It is almost 2026 and the issue is still present, I already deleted (manually in my case)  some data that was consuming a lot of space but my storage is still showing up as "Full". It is annoying because I cannot use my wandb workspace until this bug is fixed or until I pay to buy more storage :(

**Comment by mattia-scardecchia** [comment]
I'm in the same boat right now. Did people ever re-obtain access to their workspace? after how long?

**Comment by AleksanderWojsz** [comment]
@mattia-scardecchia, for me it took ~15 minutes.
