### ISSUE TITLE
[Q] Contributing guide out of date

### ISSUE THREAD

**Issue by eddiebergman** [wandb/wandb#7316]
Hi there,

I wanted to take a look at contributing and hit a roadblock with the Contributing guide, specifically this section:

https://github.com/wandb/wandb/blob/2829aafc12541eff629b813ed7be896a916b0a64/CONTRIBUTING.md?plain=1#L236-L247

This file no longer exists and removed as part of #7002 which removed the deprecated `pkg_resources` package, specifically commit c3f39af.

Viewing the [last version of the file](https://github.com/wandb/wandb/blob/44c499418e56b2eb14f7ab04cff7317ae159a4c7/tools/setup_dev_environment.py), it seems that all it does is would be to install `pyenv` and the listed versions, which I can replicate easily.

---

Is there a new recommended way to setup environments or (i.e. not sure if tox can do it itself?) or is it just a matter of removing the lines from the CONTRIBUTING.md?

**Comment by kptkin** [comment]
hi @eddiebergman you are right and we are planning to release an update version in the coming week. 
yes, most of the contribution should be quite similar the main purpose of that file was to install pyenv to manage your python versions. We still use tox to run our tests, but you could run a specific test directly using `pytest`. 

I will update this issue next week when we update our contribution document.
