### ISSUE TITLE
[CLI]: wandb doesn't report logs from all nodes for distributed training using HuggingFace trainer

### ISSUE THREAD

**Issue by tnnandi** [wandb/wandb#7324]
### Describe the bug

By default, simply adding "report_to": "wandb" as an argument for training_args (for HF Trainer) only creates plots (say, for GPU usage) for only the master node on the wandb GUI. By overriding the default wandb.init() as shown below, I can create one eantry for each GPU on the wandb GUI, but only that from rank 0 are plotted. FYI: I'm using DeepSpeed for distributed training. 

For a training instance with 2 nodes (each with 4 GPUs), wandb shows only 4 plots for GPU system metrics. Weights and Biases GUI should show system metrics from all GPUs involved in the training, and not from only those on the master node. FYI: individually logging into the different nodes, I've confirmed that those are indeed being used. 

```
training_args = {
    "learning_rate": max_lr,
    "do_train": True,
    "do_eval": False,
    "group_by_length": True,
    "length_column_name": "length",
    "disable_tqdm": False,
    # "lr_scheduler_type": lr_schedule_fn,
    # "warmup_steps": warmup_steps,
    "weight_decay": weight_decay,
    "per_device_train_batch_size": geneformer_batch_size,
    "num_train_epochs": epochs,
    "save_strategy": "steps",
    "save_steps": np.floor(num_examples / geneformer_batch_size / 8),  # 8 saves per epoch
    "logging_steps": 1000,
    "output_dir": training_output_dir,
    "logging_dir": logging_dir,
    "log_on_each_node": True,
    "report_to": "wandb",
}

training_args = TrainingArguments(**training_args)

print("Starting training.")

wandb.init(
    project="geneformer_multinode_project",
    name="geneformer_multinode",
    tags=["2_node"],
    group="geneformer_group",
)


# define the trainer
trainer = GeneformerPretrainer(
    model=model, .....


```

```shell

```

### Environment

WandB version: 0.16.6

OS: SUSE linux

Python version: 3.9.0

Versions of relevant libraries: torch 2.1.2+cu118, transformers  4.39.3, accelerate 0.29.1, deepspeed 0.14.0

**Comment by noaleetz** [comment]
Hi @tnnandi - I have shared an update in [this](https://github.com/wandb/wandb/issues/7470#issuecomment-2814205540) github issue which I think will be helpful for 2 things you mentioned above:
- show system metrics from all process involved in experiment
- show console logs from all processes
