### ISSUE TITLE
[App]: Can't access to the overview page 

### ISSUE THREAD

**Issue by realjoenguyen** [wandb/wandb#7356]
### Current Behavior

I can't get access to the overview page of my experiments 
Got this error 

> Cannot read properties of undefined (reading 'map')
> An application error occurred.
>  Click to refresh the page.

### Screenshots

![image](https://github.com/wandb/wandb/assets/26454297/ba0c618b-11a8-445b-902d-0ea97548b1e0)

### Environment

OS: MacOs

Browsers: Chrome 

Version: Version 123.0.6312.107 (Official Build) (arm64)

**Comment by JoanaMarieL** [comment]
Hello @realjoenguyen , sorry for running into this. Could we ask for the following to better understand the behavior:

- Share a screenshot of any console logs you are seeing. In Chrome → Right Click → Inspect
- Reproduce the error and  capture network traffic via a HAR file. Here's how: https://support.google.com/admanager/answer/10358597?hl=en
- share-able workspace/run link that we can access so we could check it further

**Comment by realjoenguyen** [comment]
@JoanaMarieL Thank you for your reply, 

> Share a screenshot of any console logs you are seeing. In Chrome → Right Click → Inspect
![image](https://github.com/wandb/wandb/assets/26454297/688ce50d-031c-4b3d-9ece-f6dac43e2251)

> Reproduce the error and capture network traffic via a HAR file. Here's how: https://support.google.com/admanager/answer/10358597?hl=en
[wandb.ai.har.zip](https://github.com/wandb/wandb/files/14949319/wandb.ai.har.zip)

Please unzip the file as github doesn't support to upload file `.har` 

> share-able workspace/run link that we can access so we could check it further

[The link](https://wandb.ai/osu-rl/messenger_s1/runs/trm2qy2l/overview?nw=nwuserrealjoenguyen) is here.

**Comment by JoanaMarieL** [comment]
Hi @realjoenguyen , apologies for the delay here and thank you for your patience. The fix has been deployed and wanted to check if it is also working on your end?

**Comment by realjoenguyen** [comment]
@JoanaMarieL thank you, it works now

**Comment by JoanaMarieL** [comment]
Thanks @realjoenguyen , we'll mark this as resolved and feel free to reach us out again for any concern.
