### ISSUE TITLE
[Q] How can I delete organization

### ISSUE THREAD

**Issue by min99830** [wandb/wandb#7379]
I created organization name 'team0601p-org' for academic.

But, now I need another academic organization. Can I remove this organization and create another?

**Comment by umakrishnaswamy** [comment]
hey @min99830 - I'd be happy to remove this organization for you. Could I go ahead and proceed?

**Comment by min99830** [comment]
Yes! Thank you!

**Comment by umakrishnaswamy** [comment]
@min99830 - organization has been deleted!
