### ISSUE TITLE
[Q] someone please suggest me why i am facing this warning

### ISSUE THREAD

**Issue by deveshcse** [wandb/wandb#7382]
wandb: WARNING Skipping trace saving - unable to safely convert LangChain Run into W&B Trace due to: Object of type 'float32' is not JSON serializable
wandb: WARNING WARNING: Failed to serialize model: Object of type 'float32' is not JSON serializable

**Comment by luisbergua** [comment]
Hey @deveshcse, thanks for raising this! Would you mind sharing a code example and the full terminal output so I can take a look and reproduce on my end?

**Comment by ayulockin** [comment]
Hey @deveshcse, W&B Trace is an old product offering which is not maintained anymore. We were focused on shipping a better tooling called W&B Weave. Team is working on the Langchain integration.

-  [Weave announcement](https://wandb.ai/wandb/weave-announcement/reports/Weave-Simple-tools-for-applying-Generative-AI--Vmlldzo3NDE0Mjcx)
- [Weave Documentation](https://wandb.github.io/weave/)

Closing this issue for now. Do let me know if you need anything more.
