### ISSUE TITLE
[Q] Is it possible to get the datapoints used to create the GPU power usage graph

### ISSUE THREAD

**Issue by jonastgu** [wandb/wandb#7383]
Hi,
Is there any way to log the datapoints used to create the GPU power usage graph?

**Comment by luisbergua** [comment]
Hey @jonastgu, thanks for your question! You can retrieve system metrics using our [public API](https://docs.wandb.ai/ref/python/public-api/):
```
import wandb

api = wandb.Api()
run = api.run(<run-path>)
run.systemMetrics 
```
Would this be helpful for you?
