### ISSUE TITLE
[Q] I can't create academic organization

### ISSUE THREAD

**Issue by min99830** [wandb/wandb#7389]
I requested delete my academic organization for creating new academic organization.

But, I can't create academic organization although previous organization is deleted. 

Is there any reason for this or just error?

**Comment by JoanaMarieL** [comment]
hello @min99830 , apologies for the inconvenience and happy to help. May we request for a screenshot of error you are encountering? Thanks!

**Comment by min99830** [comment]
![image](https://github.com/wandb/wandb/assets/72486552/023c25ed-39a6-47d1-a3ac-4d5f7912ef8f)
@JoanaMarieL Error says `user already has an active trial`. But, the trial organization is deleted.

**Comment by thanos-wandb** [comment]
Hi @min99830 thank you for reporting this issue. Would it be possible to try once again and see if you're now able to create an academic team? what was the name of the Org that you had previously deleted?

**Comment by thanos-wandb** [comment]
Hi @min99830 I have been checking this but it looks like you've now deleted your account? please let us know if you need any further assistance.

**Comment by min99830** [comment]
My account is alive. I login wandb by github account. @thanos-wandb

I can't make academic organization. :(

Thank you for helping me.

**Comment by thanos-wandb** [comment]
Hi @min99830 thank you for the confirmation. It seems you have another active free trial (org: `swinvq-org`) and that's the reason it won't let you create an academic team. Please let us know how would you like us to proceed.

**Comment by thanos-wandb** [comment]
Hi @min99830 just a quick update, the Org `swinvq-org ` has been now updated to academic subscription as you're currently entitled to 1 academic team. Please let us know if that worked for you, or if you had any additional questions?

**Comment by min99830** [comment]
@thanos-wandb Thank you. It's allright now.
