### ISSUE TITLE
[CLI]: Replace deprecated appdirs with platformdirs

### ISSUE THREAD

**Issue by SiHaoShen** [wandb/wandb#7409]
### Describe the bug

from https://github.com/ActiveState/appdirs
`Note: This project has been officially deprecated. You may want to check out https://pypi.org/project/platformdirs/ which is a more active fork of appdirs. Thanks to everyone who has used appdirs. Shout out to ActiveState for the time they gave their employees to work on this over the years.`

relevant discussion: https://github.com/ActiveState/appdirs/issues/79

Platformdirs is a maintained fork from appdirs package:
https://github.com/platformdirs/platformdirs

### Environment

WandB version: v0.16.6

OS: Windows11

Python version: 3.9.18

Versions of relevant libraries: appdirs v1.4.3

**Comment by kptkin** [comment]
@SiHaoShen Thanks a lot for updating us!

**Comment by ArtsiomWB** [comment]
Thank you for the update, @SiHaoShen!
