### ISSUE TITLE
[CLI]: Wandb agent fails with no log

### ISSUE THREAD

**Issue by arkadiusz-czerwinski** [wandb/wandb#7444]
### Describe the bug

After setting up wandb launch environment, successfully adding job to queue with ```wandb job create```, the run fails, with no feedback other than.: "The submitted job exited successfully but failed to call wandb.init". There is no feedback in the agent terminal.

```shell
wandb launch-agent -e ENTITY -q QUEUE -v
```

The repo is available [here](https://github.com/dkphd/ecg_benchmarking_lit), with the code and Dockerfile.

### Environment

WandB version: 0.16.6

OS:

Python version:

Versions of relevant libraries:

**Comment by anmolmann** [comment]
Hey @arkadiusz-czerwinski , thanks for writing to W&B support. We'll investigate this on our end and get back to you soon.

**Comment by anmolmann** [comment]
Hey @arkadiusz-czerwinski , 

1. Job run will be reported as a failure if they don’t include a `wandb.init` to create a run, which I think might have happened in your case.  This was another gap in our documentation--apologies.
2. If you look to the far right of the job run’s view under the queue, do you see an error icon (example in the video below, bottom right)?  This should immediately pop an error modal.  (We’ve heard from other customers who missed this, so we’re working on making it more prominent and discoverable). 

https://github.com/wandb/wandb/assets/20401632/bf0366c2-491e-4bb6-8be8-e7681af502b5

Please let me know if this video helps locating the stack trace on your end.

**Comment by anmolmann** [comment]
Hi @arkadiusz-czerwinski , I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by arkadiusz-czerwinski** [comment]
Hi. Thank you for giving me a reminder. In case of our setup, the script starts with wandb init. The error, however, states that the script failed before reaching the wandb init, although highest verbose settings were selected.

**Comment by anmolmann** [comment]
Hi @arkadiusz-czerwinski , could you share your queue config and the script as well? This will help us in reproducing this issue on our end for further investigation.

**Comment by arkadiusz-czerwinski** [comment]
Fair point. The code is visible in the initial message as well as here: https://github.com/dkphd/ecg_benchmarking_lit. 
The config look as follows: 
```yaml
gpus: all
label: [tutorial]
volume: [/mnt/space:/mnt/space]
```

**Comment by arkadiusz-czerwinski** [comment]
Update: the issue seems to be that during creation of a job from git, entry point is required, but is then not passed forward to the wandb, which caused the error, as it had to be defined in Dockerfile.wandb.

**Comment by arkadiusz-czerwinski** [comment]
Thank you for being so `cooperative.`
