### ISSUE TITLE
[Feature]: Selection slider for parallel coordinates

### ISSUE THREAD

**Issue by yermandy** [wandb/wandb#7445]
### Description

Hello, I stumbled across a feature that is present in the Optuna's parallel coordinate plot. Namely, you can specify (select) which parallel coordinates you want to highlight. I found the feature super useful as it signifies which coordinates (and runs) led to the expected results. 

### Unselected:

<img width="774" alt="Screenshot 2024-04-22 at 15 03 26" src="https://github.com/wandb/wandb/assets/39454881/43c2b94e-78e3-4566-a97a-3ffc2abc3ffa">

### Selected objective

<img width="779" alt="Screenshot 2024-04-22 at 15 04 33" src="https://github.com/wandb/wandb/assets/39454881/3c69a121-1c0d-497b-bf50-01229edae43a">

### Selected objective + some parameter

<img width="772" alt="Screenshot 2024-04-22 at 15 04 55" src="https://github.com/wandb/wandb/assets/39454881/9621e5e7-3360-428a-a440-6faf7c748e85">

## In W&B:

I am sweeping over some hyperparameters and I would like to see which parallel coordinates led to the best results. When there are more runs, I can barely see what is going on there and what I should select.

<img width="485" alt="Screenshot 2024-04-22 at 15 06 29" src="https://github.com/wandb/wandb/assets/39454881/dcb6e3f8-1128-459c-aae1-3cad7db78d1d">

For now, I am filtering runs by selecting fitness to be more than some constant but this solution is not ideal as I miss some information (cases where the model performs worse).

### Suggested Solution

You can see the functionality [here](https://optuna.readthedocs.io/en/stable/reference/visualization/generated/optuna.visualization.plot_parallel_coordinate.html)

**Comment by umakrishnaswamy** [comment]
hey @yermandy - I attached a short video for how you can accomplish this by selecting the parallel coordinates you want to highlight, which automatically performs a filter. Would this satisfy the feature request? or is there additional functionality you'd like to include? thank you so much!  

video: https://github.com/wandb/wandb/assets/63944839/668b3ded-43af-43ac-a215-31c10d1a7c32

**Comment by yermandy** [comment]
@umakrishnaswamy wow, this is incredible, exactly what I am looking for! Besides the fact, that it has some small bug somewhere. 

Here, for instance, it does not remove runs with alpha out of selected range, it is a perfect feature.

<img width="994" alt="Screenshot 2024-04-23 at 7 29 24" src="https://github.com/wandb/wandb/assets/39454881/ddb9c8bd-2380-489d-8ee1-bca6b9ed4ea0">

A very good feature is that I can also select a region in a scatter plot and it will automatically filter parallel coordinates. But again, there is a bug somewhere with proper filtering

https://github.com/wandb/wandb/assets/39454881/1d9529d4-a7d6-4f43-a258-eea6675f3d5f

Thank you!

**Comment by yermandy** [comment]
I am very sorry, it is not a bug precisely. I realized that I had some manually selected runs (👁️) in the left pane. If I hide everything (visualize none), it works as expected. Thank you very much, it is very helpful!

https://github.com/wandb/wandb/assets/39454881/680e06c2-755c-4e88-824a-627ebceda209

**Comment by yermandy** [comment]
Here is my workflow (for future generations):

https://github.com/wandb/wandb/assets/39454881/1efb37bb-280d-4e78-b28b-09f0a444b7de

**Comment by yermandy** [comment]
A small question @umakrishnaswamy, has it already been implemented and I missed it or you have just added that?
