### ISSUE TITLE
[Q] Why does Wandb revert to a single dot at the end of training?

### ISSUE THREAD

**Issue by cinjon** [wandb/wandb#7482]
When my axolotl model finishes finetuning, it becomes a single dot on wandb. I'm not doing anything special. My config looks like this, where the nulls are detritus from auto-saving configs:

```
wandb_entity: <entityname>
wandb_log_model: null
wandb_name: <unique_wandbname>
wandb_project: <projectname>
wandb_run_id: null
wandb_watch: null
```

In the wandb log file, it shows all the step-logs as expected.

But at the end it looks like this:

![Screenshot 2024-04-25 at 12 09 00 PM](https://github.com/wandb/wandb/assets/615351/40b4c94d-705d-442c-8a6e-8015735eb2de)

**Comment by ArtsiomWB** [comment]
Hi @cinjon , what version of wandb are you currently using?

Are you at any point trying to write to your graph at a previous step, that already has data written to it?

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by cinjon** [comment]
It hasn't been resolved; I've just been busy elsewhere. I'm not sure what's happening right now as it only happens with one type of training and not another. I apologize, but I'll come back to this soon.

**Comment by ArtsiomWB** [comment]
Sounds good, waiting for an update.

**Comment by ArtsiomWB** [comment]
Hi! Wanted to follow up with you regarding this thread

**Comment by ArtsiomWB** [comment]
Hi, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
