### ISSUE TITLE
[Q] Changing Team Type from Work to Academic 

### ISSUE THREAD

**Issue by SvetlanaDanilova** [wandb/wandb#7501]
Hello Wandb team,
Is it possible to change the team type from "Work" to "Academic" because I missed that option while creating the team?

Link to my account: https://wandb.ai/danilovasvetlana7658 
Link to my current team: https://wandb.ai/lana_dan

**Comment by anmolmann** [comment]
Hi @SvetlanaDanilova , thanks for writing in. I've notified our Product team regarding this as we recently made some updates to our onboarding flow and this might be a result of those updates. I'll follow up with you as soon as I've an update regarding the next steps.

**Comment by anmolmann** [comment]
Hey @SvetlanaDanilova , as a follow-up question how did you determine that you were on a `work` plan and not on an academic plan? Did you try to upgrade because your tracked hour usage was up?

**Comment by SvetlanaDanilova** [comment]
Yes

**Comment by anmolmann** [comment]
I see, so because you are not a new user who's affected by the new onboarding signup flow and instead are an existing user. I will recommend you add your academic email as a second email to your user settings under the `Email` panel as the first step.
<img width="697" alt="image" src="https://github.com/wandb/wandb/assets/20401632/8197ee27-9aed-41c5-80dc-3143db640137">

Once you do this, please let me know and I will turn your team academic from my side.

**Comment by SvetlanaDanilova** [comment]
I already have an account registered to my academic email danilova.ss@phystech.edu, so I cannot add it.

**Comment by anmolmann** [comment]
Hi @SvetlanaDanilova , if you already have an academic account, unfortunately, we cannot create another academic account. What you can do in this case is move your runs/projects to your academic email if that's a suitable option. You can either let us know and we can move the projects for you. Or, you can use our [API](https://docs.wandb.ai/guides/track/public-api-guide#import-data-from-another-wb-instance) to move the projects yourself.
```from wandb.apis.importers.wandb import WandbImporter
from wandb.apis.importers import Namespace

importer = WandbImporter(
    src_base_url="https://api.wandb.ai",
    src_api_key="your-api-key-here",
    dst_base_url="https://api.wandb.ai",
    dst_api_key="target-environment-api-key-here",
)

# Imports all runs, artifacts, reports
# from "entity/project" in src to "entity/project" in dst
importer.import_all(namespaces=[
    Namespace(entity, project),
    # ... add more namespaces here
])
```

**Comment by SvetlanaDanilova** [comment]
Can you please move all my projects for me to my personal academic account https://wandb.ai/danilova-ss?

**Comment by anmolmann** [comment]
Hi @SvetlanaDanilova , all your projects from `danilovasvetlana7658` and `lana_dan` have been moved to your academic account `danilova-ss` as requested above. Please let us know in case of any further queries.

**Comment by SvetlanaDanilova** [comment]
Thank you!
