### ISSUE TITLE
[App]: Unable to see any graph 

### ISSUE THREAD

**Issue by realjoenguyen** [wandb/wandb#7503]
### Current Behavior

Unable to see any plot when clicking to the "show/hidden" button 

### Screenshots

<img width="879" alt="image" src="https://github.com/wandb/wandb/assets/26454297/53bd9165-dfe9-406a-8a2d-efaa85e9c9f6">

### Environment

OS: MacOS 14.4.1 (23E224)

Browsers:  Chrome Version 124.0.6367.93 (Official Build) (arm64)

### Additional Context

my workspace link is [here](https://wandb.ai/osu-rl/messenger_s1/groups/s1_sent_xlarge/workspace?nw=nwuserrealjoenguyen)

**Comment by anmolmann** [comment]
Hey @realjoenguyen , are you still encountering this issue. I just tried accessing your workspace from the link above and was able to view the chart panels on my end.

![image](https://github.com/wandb/wandb/assets/20401632/d9506eed-a411-4e59-bca2-e691f8faa222)

**Comment by anmolmann** [comment]
Hi @realjoenguyen , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by realjoenguyen** [comment]
@anmolmann I did reset my workspace and then it worked fine
