### ISSUE TITLE
 Issue: Unable to Write wandb Choice

### ISSUE THREAD

**Issue by OualidBougzime** [wandb/wandb#7524]
I encountered an issue where I can't write my choice wandb:

```
wandb: WARNING Path /home/oualid/FineTuneVLLM/FineTune/LLaVA/wandb/ wasn't writable, using system temp directory.
wandb: WARNING Path /home/oualid/FineTuneVLLM/FineTune/LLaVA/wandb/ wasn't writable, using system temp directory
wandb: WARNING Path /home/oualid/FineTuneVLLM/FineTune/LLaVA/wandb/ wasn't writable, using system temp directory
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results
wandb: Enter your choice: 
```

OS: Ubuntu

**Request for Assistance:**
I'm seeking guidance on resolving this issue to enable proper wandb functionality. Any advice or suggestions would be greatly appreciated.

**Comment by thanos-wandb** [comment]
Hi @OualidBougzime thank you for reporting this issue. Could you please provide some additional information on your current environment, is this on a notebook or in your terminal? and what's your rwx permissions in that printed path? what happens when you enter one of those choices?

**Comment by OualidBougzime** [comment]
> Hi @OualidBougzime thank you for reporting this issue. Could you please provide some additional information on your current environment, is this on a notebook or in your terminal? and what's your rwx permissions in that printed path? what happens when you enter one of those choices?

Thank you for your assistance. I add the cell: `wandb login` and It's working right now.

**Comment by thanos-wandb** [comment]
Great! Thank you for letting us know how you've got this fixed. Closing the ticket now and please feel free to reach out if you had any more questions or issues.
