### ISSUE TITLE
[Q] Changing team type from corporate/work to academic

### ISSUE THREAD

**Issue by zy-f** [wandb/wandb#7542]
Hi W&B team,
Is it possible to change the following team's type from "Corporate" to "Academic"?
Team account: https://wandb.ai/sustainlab1
My personal account: https://wandb.ai/cpolzak

We didn't realize we'd run into an issue and my labmate and I hit the corporate hour tracking limit. We both just deleted other old academic teams we were on to make space for this one.

Thank you for your time and help!

**Comment by ArtsiomWB** [comment]
Hi! I see that you already have a subscription under your account named waggle, without a team. It is marked as academic and therefore it does not let you make a second academic team. I can go ahead and delete it since it doesn't have a team anyway, and then mark sustainlab1 as academic for you.

**Comment by zy-f** [comment]
Please do! I couldn't figure out how to fully delete waggle

**Comment by zy-f** [comment]
Bumping thread in case my reply got lost -- I'm fine with waggle being deleted and having sustainlab1 marked -- if there's still an issue because of my teammate's account, he's also fine with that team being deleted (please also let me know if I need to provide evidence of that)

**Comment by ArtsiomWB** [comment]
Thank you for the bump, this got completely buried 😓 

Waggle is not deleted and sustainlab1 is marked as your academic team. 

Cheers!
Artsiom

**Comment by ArtsiomWB** [comment]
Thank you for the bump, this got completely buried 😓

`Waggle` is now deleted and `sustainlab1` is marked as your academic team.

Let me know if you have any more questions regarding this!
