### ISSUE TITLE
[Q] How to insert 'plotly' to 'table'?

### ISSUE THREAD

**Issue by wangzyon** [wandb/wandb#7572]

**Comment by umakrishnaswamy** [comment]
hey @wangzyon - we have documentation for how to accomplish this [here](https://docs.wandb.ai/guides/track/log/logging-faqs#how-do-i-add-plotlybokeh-charts-into-tables). please let me know if you have any questions

**Comment by umakrishnaswamy** [comment]
Hi, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
