### ISSUE TITLE
[CLI]: `Run.log_artifact` fails for GCS objects uploaded with `transfer_manager.upload_chunks_concurrently`

### ISSUE THREAD

**Issue by alexdmiller** [wandb/wandb#7575]
### Describe the bug

We are using [`transfer_manager.upload_chunks_concurrently`](https://cloud.google.com/python/docs/reference/storage/latest/google.cloud.storage.transfer_manager#google_cloud_storage_transfer_manager_upload_chunks_concurrently) to speed up checkpoint uploads to GCS. Under the hood, this function uses [multipart uploads](https://cloud.google.com/storage/docs/multipart-uploads), which do not set md5 hashes on files  ([source](https://cloud.google.com/storage/docs/hashes-etags)). The lack of md5 hash causes the wandb SDK to crash on [this line](https://github.com/wandb/wandb/blob/2876e011e99797947491519e745fba17255beca0/wandb/sdk/interface/interface.py#L311). As an alternative, the wandb SDK could use the [`CRC32C` hash](https://cloud.google.com/storage/docs/hashes-etags#crc32c), which is available for all objects.

https://github.com/wandb/wandb/pull/7337 seems somewhat related, although the ETag header is not present for multipart uploads either.

Example code:

```python
artifact = WandbArtifact(...)
artifact.add_reference("gs://bucket/path/to/multipart/upload")
run.log_artifact(checkpoint_artifact)
```

### Environment

WandB version: `0.16.6`

Python version: `3.10.12`

**Comment by moredatarequired** [comment]
@alexdmiller , can you confirm that the fix in #7337 doesn't fix your use case? It should specifically address GS reference artifacts, which I believe should have etags even for multipart uploads, it's just that the etags in the multipart case differ from the MD5 hash, and may not match the result from the XML api.

**Comment by alexdmiller** [comment]
I see, I mistakenly thought that 0.16.6 had the fix. I will check and get back to you, thank you!

**Comment by alexdmiller** [comment]
I confirmed that https://github.com/wandb/wandb/pull/7337 does indeed fix our issue, thanks for looking into this!
