### ISSUE TITLE
[Feature]: Add a "preempted" state

### ISSUE THREAD

**Issue by collinmccarthy** [wandb/wandb#7588]
### Description

Many clusters only support training jobs for a relatively short period of time, e.g. 4 hours, before they are interrupted/preempted and requeued, e.g. with `scontrol requeue` for a Slurm cluster. AWS/GCP preemption does something similar. When we call `wandb.finish()` with exit_code=0, we get success. If we exit with exit_code=<nonzero> we get failed. If we timeout, we get crashed. But none of these really apply to a preempted job, making the status misleading whichever exit code you choose.

### Suggested Solution

I would love to distinguish between a run that has failed or crashed, and one that has just been preempted. That way I could get notifications only for jobs that actually failed or crashed, and not get notifications for preempted jobs. Ideally the UI would show the status "Preempted" in a color like orange too, rather than green (for finished) or red (for failed or crashed).

**Comment by luisbergua** [comment]
Hey @collinmccarthy, thanks for writing in! You can use:
```
wandb.mark_preempting()
```
 Which will mark your run as preempted (docs [here](https://docs.wandb.ai/guides/runs/resuming#preemptible-sweeps)) . Let me know if this is helpful!

<img width="370" alt="image" src="https://github.com/wandb/wandb/assets/113048227/2aee836c-3d2b-443f-b8d7-ba9472d97ac6">

**Comment by collinmccarthy** [comment]
Ah thank you, I forgot this existed. I'm not using a sweep, but I was able to get the behavior I wanted by calling this and then `wandb.finish(exit_code=1)`.
