### ISSUE TITLE
integration imports in 0.17

### ISSUE THREAD

**Issue by tcapelle** [wandb/wandb#7610]
Regarding [this issue](https://github.com/wandb/examples/issues/524) do we need to import integration explicitely now? I am curious if @soumik12345 know this.

**Comment by tcapelle** [comment]
Ignore this, just found out in the changelogs.

**Comment by dmitryduev** [comment]
yes. high-level aliases have been deprecated for a couple years now, we finally dropped that in 0.17.0, see https://github.com/wandb/wandb/releases/tag/v0.17.0
