### ISSUE TITLE
[Q]How to delete a team

### ISSUE THREAD

**Issue by wyhsleep** [wandb/wandb#7643]
May I ask how can I delete a team since I create one by mistake.

**Comment by paulosabile-wb** [comment]
Hi @wyhsleep 

Happy to help you on this one! You can follow these steps to delete your team:
 

1. Login to wandb
2. Go to your teams settings by accessing https://wandb.ai/<your-team-name>
3. Go to Settings tab
4. Scroll on the bottom part of the page and you can find the Delete button

![image](https://github.com/wandb/wandb/assets/161790454/f583a58b-9b27-468f-a1e8-061b612cb35e)

Please note that team deletion cannot be reversed. Once you deleted a team, there is no way to revert or undo it.
 
I hope this helps. If you have questions or encountered any issues let us know!
 
 
Thank you!

**Comment by paulosabile-wb** [comment]
Hi @wyhsleep ,

We wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

Best,
Weights & Biases

**Comment by wyhsleep** [comment]
Thank you for your help. Problem solved！！！

**Comment by paulosabile-wb** [comment]
You're welcome @wyhsleep I will now mark this as Solved! Please contact us again if you need assistance.
