### ISSUE TITLE
[CLI]: Local files named `config.yaml` and saved by wandb are overwritten

### ISSUE THREAD

**Issue by collinmccarthy** [wandb/wandb#7654]
### Describe the bug

I'm adding Wandb to some detectron2 models for some baselines, and detectron2 names their config file `config.yaml`. I save this file with `wandb.save(config_yaml_path)` and it uploads successfully. But then the local version gets overwritten by the config file that gets generated by wandb, also named `config.yaml` but in the run directory.  I'm not passing in a config, so it's just a yaml file with `wandb_version: 1` and the `_wandb` dictionary. 

Of course, this happens because when I save the file it creates a symlink, and then wandb creates it's own `config.yaml` file which overwrites the version pointed to by the symlink. I'm guessing this description is enough for you all to track down the issue. 

### Environment

WandB version: 0.17.0

OS: Ubuntu 20.04 LTS

Python version: 3.8 (max supported by detectron2)

Versions of relevant libraries: 
detectron2: 0.6 (latest)

### Additional Context

My workaround is to rename the file to `config.yml` instead of `config.yaml` prior to saving with wandb, and then everything works fine.

**Comment by luisbergua** [comment]
Hey @collinmccarthy! Would you mind sharing if setting the env variable `WANDB_CONFIG_DIR` (docs [here](https://docs.wandb.ai/guides/track/environment-variables#optional-environment-variables)) to a different directory solves the problem?

**Comment by luisbergua** [comment]
Hey @collinmccarthy, just checking if you had the time to test setting the env variable as I suggested and if it worked

**Comment by collinmccarthy** [comment]
Hey @luisbergua, sorry for the delay. Setting `WANDB_CONFIG_DIR` to a different directory did not work. However if I noticed that when my init args use `resume=False` instead of `resume='auto'` the `config.yaml` file is no longer a symlink and everything works fine. So this issue only happens when resuming and saving a file named `config.yaml`.
