### ISSUE TITLE
[App]: "This is ... personal exploration space. Changes you make will be discarded at the end of the session. On own project.

### ISSUE THREAD

**Issue by samuele-bortolato** [wandb/wandb#7658]
### Current Behavior

The account shows as mine, shows my works, gives me the usual options, but when I go inside a project the workspace seems to often get stuck thinking I'm working on someone else's workspace, while it's actually my own. 

The annoying part is that it doesn't allow me to delete wrong runs, nor modify the panels, saying:

> "Changes are not auto-saved: Changes you make to a teammate's workspace are only visible to you and will be discarded at the end of the session. You can copy to your workspace or create a new view if you wish to keep your work."

I haven't created a team nor shared the workspace. 

I don't know if it's related, but the url automatically adds ?nw=nwuser<_my username_>
![image](https://github.com/wandb/wandb/assets/81489249/c7e342b1-6688-47a1-805e-ff4f37cb90b0)

### Expected Behavior

It should not mistake my work for someone else's.

### Steps To Reproduce

Not sure, it just started doing it. I haven't used it in a couple months, I signed in with the google account as usual.

### Screenshots

![photo1715903034](https://github.com/wandb/wandb/assets/81489249/94e60aff-7f48-4631-ba76-2d1866d628c9)

### Environment

OS: Windows 10

Browsers: Chrome

Version: 124.0.6367.91 (Official Build) (64-bit)

**Comment by paulosabile-wb** [comment]
Hi Samuele,

Is it possible that you have 2 different user accounts in wandb and you are currently logged in as "Your-Account-B" while the workspace you are viewing was created by "Your-Account-A"?


Thanks,
Paulo

**Comment by paulosabile-wb** [comment]
Thank you @samuele-bortolato  for sharing this details. This behavior appears to be odd as I haven't seen the app doing this before.

Could you please try clearing your browser cache and see if this is still provide the same results? I'd like to request if you can create a video recording while viewing your workspace so I can investigate the issue further. Appreciate your help on this!

**Comment by paulosabile-wb** [comment]
Hi @samuele-bortolato. Good day! Since we have not heard back from you, we will assume that the issue has been resolved on your end and we are going to close this request. If you would like to re-open the conversation, please let us know and we will keep investigating.

**Comment by samuele-bortolato** [comment]
I was testing it a bit, clearing the cache seems to have solved the issue. I think we can close the request.
Thank you for the support.
