### ISSUE TITLE
[App]: Cannot see the curve that collides with x-axis when downloading and cannot see the complete number on x-axis

### ISSUE THREAD

**Issue by LiqunZhao** [wandb/wandb#7672]
### Current Behavior

When I download the graph from the web, I usually find there are two problem:
1. On the Web, even if one curve collides with the x-axis, I can still see it. But the number at the end is not complete.
2. However, when downloaded from the Web, the curve colliding with the x-axis is not visible anymore, and the number at the end is still not visible.

When on web:
![on web](https://github.com/wandb/wandb/assets/69634744/e8389d7b-5708-41ba-8ed3-e8c650bef71b)
When downloading:
![when download](https://github.com/wandb/wandb/assets/69634744/2a1784a9-6731-4420-8f26-92df3f7e2111)
It can be seen that the line colliding with the x-axis and visible on the web is not visible when downloading (it seems that when downloading, the x-axis becomes bold and covers any other curves). Also, in both pictures, the number "200" cannot be shown completely.problems

### Expected Behavior

1. Show the curves colliding with the x-axis when downloading, just like how it is shown on the web.
2. Any instructions on how to show the number in the end completely (for example, show the number "200" clearly).

### Environment

OS: Ubuntu 18.04

Browsers: Google chrome

Version:

**Comment by umakrishnaswamy** [comment]
hey @LiqunZhao - would it be possible to send over a link to the workspace where you're seeing this, as well as the chart you're trying to do this with? I'm trying to reproduce the behavior on my end. thanks a ton! if you would like to send over the link more privately, you can also send it over to support@wandb.com

**Comment by umakrishnaswamy** [comment]
Hi @LiqunZhao, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know
