### ISSUE TITLE
[CLI]: nested logging of tables seems to be broken

### ISSUE THREAD

**Issue by sammlapp** [wandb/wandb#7691]
### Describe the bug

Logging tables nested within sections is buggy. 

```python
import wandb
import pandas as pd

table1 = wandb.Table(dataframe=pd.DataFrame({'a':[1,2,3],'b':[4,5,6]}))

wandb_session=wandb.init(entity='kitzeslab',project="opensoundscape",name='test wandb table')
wandb_session.log({"test_non_nested": table1})
wandb_session.log({"test0/nested0": table1})
wandb_session.log({"test1 / nested1": table1})
wandb_session.log({"test2": {"nested2":table1}})
```

Results: 
No errors are given. 

test_non_nested logs a table in Table section, as expected
test0 logs a table in Section test0 as expected 
test1 works on mac but results in an error on windows (according to other users, I have not confirmed because I don't have a windows machine)
test2 does not work as expected. I expect it to log a table in a section named test2. Instead, it creates a table with no data, and no rows, in the Tables section. The name of the table is runs.summary["test2\.nested2"].

### Environment

WandB version:
0.13.11

OS:
Mac OS 12.6

Python version:
3.9.13

Versions of relevant libraries:

**Comment by paulosabile-wb** [comment]
Hi @sammlapp

Good day and thank you for reaching out to us. Happy to help you on this!

The test1 table works on Windows when I tried it on my machine.

While it seems I was able to reproduce the behavior for test2, I am also getting no rows logged on the table. Let me investigate this behavior and I will get back to you for an update.


Best Regards,
Paulo

**Comment by sammlapp** [comment]
Interesting, thanks for looking into it. Perhaps @paulpeyret-biophonia has a minimal working example of the issue with logging using " / " on Windows?

**Comment by paulpeyret-biophonia** [comment]
Hello,

Note: wandb seems to create temp files and folders that it sends to the wandb server, then it deletes (flush) the temp folder.

I have the same behavior as @paulosabile-wb with your code snippet on my windows machine.

**### Test1:**
I was able to reproduce the error in CNN.train() with this following snippet.

This sneaky bug is only raised when you run log function with " /" in the name (it must be the first log of all logs otherwise it works fine)
```
import wandb
import pandas as pd

table1 = wandb.Table(dataframe=pd.DataFrame({'a':[1,2,3],'b':[4,5,6]}))
wandb_session=wandb.init(entity='kitzeslab',project="opensoundscape",name='test wandb table')
wandb_session.log({"test1 / nested1": table1})
```

This is caused by the call of os.makedirs() function that remove any space at the end of the folder name before creating it.
You can test it here:
```
import os
my_filename='./test1 / nested1.table.json'
print(os.path.dirname(my_filename))
os.makedirs(os.path.dirname(my_filename), exist_ok=True)
```
So no space before "/" in wandb_session.log() input dictionary key shall solve this bug.

**Comment by paulosabile-wb** [comment]
Hi @sammlapp Good day! Just checking if you were able to make your test1 table work by following @paulpeyret-biophonia suggestion above?

**Comment by sammlapp** [comment]
Sorry for the delay - I'm largely off grid for fieldwork. I would consider @paulpeyret-biophonia's suggestion a workaround rather than a solution - it is buggy that " /" causes an exception.

**Comment by paulosabile-wb** [comment]
Hi @paulpeyret-biophonia Good day! It seems that I am unable to reproduce errors when following your snippet. Could you please clarify what errors are being thrown when you were testing the bug when logging the nested table in Windows?

Could you also share me your sdk version by running `wandb --version`?

**Comment by paulpeyret** [comment]
Hi @paulosabile-wb , 

The error is : 
```
File "C:\Users\Username\myproject\.venv\lib\site-packages\wandb\util.py", line 1617, in fsync_open
    with open(path, mode, encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Username\\AppData\\Local\\Temp\\tmpcatlpygf\\test1 / nested1.table.json'
```

My config is: 
wandb, version 0.13.11
Windows 11

**Comment by paulosabile-wb** [comment]
Thank you @paulpeyret . I am not able to reproduce this when using version 0.17.1. Any chance you could try this on the latest version of wandb?
