### ISSUE TITLE
[Q] Fetch all projects and reports of a user

### ISSUE THREAD

**Issue by SauravMaheshkar** [wandb/wandb#7703]
Is there any way in which I can fetch all the projects and all the reports of a particular user ?

**Comment by gsaltintas** [comment]
As per the [documentation](https://docs.wandb.ai/ref/python/public-api/api), you can use something like below:

```python
entity = "ENTITY_NAME"
reports = [] 
for project in  api.projects(entity=entity):
    reports.extend(api.reports(path="/".join(project.path)))
```

**Comment by JoanaMarieL** [comment]
Thank you for sharing @gsaltintas , does this work for you @SauravMaheshkar ?

**Comment by SauravMaheshkar** [comment]
Thank you @gsaltintas for the help. @JoanaMarieL I'm able to get all of my written reports using the above snippet. However it seems like each report is a instance of `BetaReport`. Is there any way I can access the blocks of each of these reports ? I remember there used to be a `blocks` attribute perhaps in a previous API version ?

**Comment by JoanaMarieL** [comment]
Hi @SauravMaheshkar , could you please try this block of code, to pull the list of reports:

```
api = wandb.Api()
reports = api.reports(path="<entity>/<project>")
for report in reports:
    print(report, report.displayName)
```

**Comment by JoanaMarieL** [comment]
Hi @SauravMaheshkar , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by SauravMaheshkar** [comment]
> Hi @SauravMaheshkar , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

Yup, I've opened another issue in [wandb/wandb-workspaces](https://github.com/wandb/wandb-workspaces), that seems like a better place for this query.
