### ISSUE TITLE
[Q] How to directly obtain a figure with grey grid background and manually set label name

### ISSUE THREAD

**Issue by StaminaTang** [wandb/wandb#7706]
Hello!
Thank you very much for your excellent work! Have a nice day! 
I am writing to ask for help obtaining the figure with formats like a grey grid background and manually setting label names. Could you please give me some suggestions?
Currently, I get the plot like this:
<img width="1359" alt="image" src="https://github.com/wandb/wandb/assets/17592448/879ea1ee-a4d4-4c97-b459-51d071bb4c30">
All the settings (smoothing, color, grouping...) in this plot are well-designed, perfect, and right fit. However, I need to obtain figures like this:
<img width="349" alt="image" src="https://github.com/wandb/wandb/assets/17592448/3447bb5f-dfc8-4d75-886a-66c1b022b14d">
<img width="590" alt="image" src="https://github.com/wandb/wandb/assets/17592448/82a28568-5c73-46c1-bda3-2f5542d01b9e">
I have tried the download button, but the figure goes like this:
<img width="636" alt="image" src="https://github.com/wandb/wandb/assets/17592448/344f6bc1-72e9-440b-ba3f-3b5f248a8c8a">
 I need to fit it in the above format, and I do not know how to do smoothing and grouping using the .csv. Do you have any idea how to handle this problem directly by using wandb? I heard there is a function called a custom chart. Do you think it could achieve this kind of format adaptation without re-running the runs?

Thank you very much!

**Comment by umakrishnaswamy** [comment]
hey @StaminaTang - My recommendation would be the following:
- you can pull the values for a specific metric using run.scan_history() ([docs](https://docs.wandb.ai/ref/python/public-api/run#scan_history))
- once you do that, you can resume the wandb run (documentation [here](https://docs.wandb.ai/guides/runs/resuming#docusaurus_skipToContent_fallback) on how to do that), and you can log these points in a wandb Table or as a custom chart directly ([documentation](https://docs.wandb.ai/guides/app/features/custom-charts/walkthrough#docusaurus_skipToContent_fallback))

**Comment by umakrishnaswamy** [comment]
hey @StaminaTang - due to inactivity, I'll close out this thread, but feel free to write back in whenever
