### ISSUE TITLE
[App]: Duplicate Runs in the Sweep with Parallel Agents

### ISSUE THREAD

**Issue by marsh312** [wandb/wandb#7749]
### Current Behavior

When I use `wandb.agent` to sweep different hyperparameters, I notice that there are a significant number of runs with identical hyperparameters. This results in a considerable waste of computing resources.

The main part of my running script is as follows:
```python
import argparse
import os
from pprint import pprint
import wandb

parser = argparse.ArgumentParser()

parser.add_argument('--wd', type=float, default=1e-2)
parser.add_argument('--batch_gap_to_rebuild_tree', type=int, default=80000)
parser.add_argument('--sample_num', type=int, default=70)
parser.add_argument('--emb_dim', type=int, default=24)
parser.add_argument('--scheduler_mode', type=str, default='exponential', choices=['polynomial', 'exponential', 'cosine'])
parser.add_argument('--lr', type=float, default=1e-3)
parser.add_argument('--min_lr', type=float, default=1e-6)
parser.add_argument('--dropout_p', type=float, default=0.0)
parser.add_argument('--gpu_id', type=int, default=0)
parser.add_argument('--sweep_id', type=str, required=True)
parser.add_argument('--project_name', type=str, required=True)
parser.add_argument('--sweep_count', type=int, default=5, required=True)
parser.add_argument('--dataset', type=str, choices=['mind', 'movie', 'tmall', 'amazon'], required=True, help='dataset')

args = parser.parse_args()

dir_path = './sweep_log_{}'.format(args.dataset)
os.makedirs(dir_path, exist_ok=True)

def train(config=None):
    with wandb.init(config=config, dir=dir_path, group=args.dataset, settings=wandb.Settings(init_timeout=300)):
        # Replace the attributes in args with the attributes in config
        print('Arguments passed:')
        pprint(vars(args))
        for key, val in wandb.config.items():
            if key in vars(args):
                setattr(args, key, val)
            else:
                print('Warning: {} is not in the arguments'.format(key))
        print('After replaced with config:')
        pprint(vars(args))

wandb.agent(args.sweep_id, train, count=args.sweep_count, project=args.project_name)
```

The shell script is as follows:
```sh
(
    python sweep_one_epoch.py --dataset mind --sweep_id gi5t62yt --project_name mind_deforec_sweep --sweep_count 5 --gpu_id 1
)&
(
    python sweep_one_epoch.py --dataset mind --sweep_id gi5t62yt --project_name mind_deforec_sweep --sweep_count 5 --gpu_id 2
)&
(
    python sweep_one_epoch.py --dataset mind --sweep_id gi5t62yt --project_name mind_deforec_sweep --sweep_count 20 --gpu_id 5
)&
wait
```

### Screenshots

![739e63a1c32fb043fafa0c1e5a485724](https://github.com/wandb/wandb/assets/64718620/ad9e89e6-d0ff-4eb6-9fdf-b2a6e549c6d7)

I have observed that these two runs have the same hyperparameters. Additionally, they both share the same `gpu_id`, indicating that they are executed by the same agent. Therefore, it appears that the issue is not related to the use of multiple agents.

### Environment

OS: Linux ubuntu 5.4.0-126-generic

Browsers: Edge 125.0.2535.79 

Version: wandb 0.16.0

### Additional Context

I would like to understand the cause of this problem as soon as possible. Thanks!

**Comment by luisbergua** [comment]
Thanks @marsh312! I did some tests on my end but was unable to reproduce the issue. Would you mind sharing if you're using Hydra? We have seen this issue happening when using it so wanted to double-check

**Comment by marsh312** [comment]
> Thanks @marsh312! I did some tests on my end but was unable to reproduce the issue. Would you mind sharing if you're using Hydra? We have seen this issue happening when using it so wanted to double-check

Of course, @luisbergua! I am using a shell script to run the sweep, not Hydra. The script is listed above.

**Comment by luisbergua** [comment]
Thanks @marsh312! I haven't been able to repro this issue yet so wanted to ask if you could try to avoid passing `--gpu_id` and only execute the command once. I know you mentioned that repeating runs have the same `--gpu_id` and agree that this doesn't seem to be associated with the use of multiple GPUs but would like to double-check. Also sharing our [docs](https://docs.wandb.ai/guides/launch/sweeps-on-launch) about sweeps on launch since those could be helpful for running sweeps in distributed environments

**Comment by marsh312** [comment]
Sorry, @luisbergua! Due to resource limitations, I was only able to conduct some experiments based on your instructions and haven't witnessed the same issue again. Here is my hypothesis regarding the issue: because the sweep space I set is small and discrete, using the Bayesian sweep method might lead to duplicate runs. Do you think this hypothesis is reasonable?

**Comment by ericchen321** [comment]
I'm experiencing the same issue with grid-based search. In my case I set up a hyperparameter search that's supposed to execute 24 runs, and I launched 4 agents to execute in parallel. But the search never stops and in the end I got over 1k runs... and still not stopping. Eventually had to kill the process in order to stop the sweep.
