### ISSUE TITLE
[Q] Transfer wandb-local data between servers

### ISSUE THREAD

**Issue by jafarinia** [wandb/wandb#7760]
Hi. I want to transfer wandb-local data between servers and I have deleted the wandb directories created in the project directories. So my only way is doing it wand the wand docker volume. Manually copy/pasting it does not work and I cant login in the new instance. Is there any proper way to do it?

**Comment by paulosabile-wb** [comment]
Hi @hussein-jafarinia 

Good day and thank you for reaching out to us. Happy to help you on this!

Would it help you if you export your runs into a csv file and then log them to your new server/instance as a new run?

You can do something like a script (below) to "export" a run into a csv and then check this [guide ](https://docs.wandb.ai/guides/track/log/working-with-csv#import-and-log-your-dataset-csv-file) on how you can log a run from a csv file.

```
import wandb
import pandas as pd

# Retrieve the run
run = wandb.Api().run("mohammadbakir/test_slow_wandb/q5x7ip2i")

# Scan the run history
history = run.scan_history()

# Convert the history to a list of dictionaries
history_list = [row for row in run.scan_history()]

# Convert the list of dictionaries to a DataFrame
history_df = pd.DataFrame(history_list)

# Save the DataFrame to a CSV file
history_df.to_csv('run_history.csv', index=False)

print("Run history saved to run_history.csv")
```

**Comment by hussein-jafarinia** [comment]
@paulosabile-wb 
Thanks for the help. It not an option because my runs are actually a lot (in order of thousands) and some of them are in sweeps and some capabilities that wandb provides like watching aggregation of sweeps in forms of mean, std of metrics, ... are important and it would be a very very laborious thing to do all of these manually.

**Comment by hussein-jafarinia** [comment]
I'm sure there is another way. Because the docker volume is actually there. I just don't know how to make it work on a new machine (probably some problems with the mysql database)

**Comment by paulosabile-wb** [comment]
Hi @hussein-jafarinia Good day and thank you for patiently waiting for my update. I checked this with our team and at this time, there isn't any supported migration offerings from one instance to another instance. We apologize for this.

**Comment by paulosabile-wb** [comment]
Hi @hussein-jafarinia , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
