### ISSUE TITLE
[Q] Cant login, not authorized despite using the correct API key

### ISSUE THREAD

**Issue by asusdisciple** [wandb/wandb#7783]
Sooo I have filed this under Question because I probably do something wrong. I wanted to test wandb on my remote server to track experiments. So far so good, installation went flawlessly, server can be started and is running. However when I try to use the logger in pytorch lightning I get the error message:

```
wandb.errors.AuthenticationError:
The API key you provided is either invalid or missing.  If the `WANDB_API_KEY` environment variable is set, make sure it is correct. Otherwise, to resolve this issue, you may try running the 'wandb login --relogin' command. If you are using a local server, make sure that you're using the correct hostname. If you're not sure, you can try logging in again using the 'wandb login --relogin --host [hostname]' command.(Error 401: Unauthorized)
```

Needless to say I just copied the the API key from the "danger zone" in my account. I use the wandb_local docker container, so I do not have any subscription if that is necessary. I set the WANDB_API_KEY environment variable manually, but that did not help. I tried using the host argument with either the IP of my server `(http://192.168.1.12:6666`) or `localhost:6666` but neither worked. I then tried to connect my local notebook with the remote server which runs wandb with `ssh -R 6666:localhost:6666 -N -f xxx@192.168.1.12` but was not able to access the GUI with port forwarding.

If I try to relogin I get the message:

`Could not get viewer with default API key. Please relogin using `WANDB_BASE_URL=http://192.168.1.12:6666 wandb login --relogin` and try again`

Do I maybe need a different API key?

Also I am able to connect locally to the server over the web ui. I then see the sign-up page (even though I already have an account). If I log out via the button on the top right, and click on login again, I see the login mask for a split seocnd before I am redirected to sign-up page again. 

Any help would be appreciated.

**Comment by luisbergua** [comment]
Hey @asusdisciple! Mind sharing where are you getting your API key from? It sounds like you haven't generated a local license which is necessary to sign up and then retrieve the api key associated with the account in the local instance. See our docs [here](https://docs.wandb.ai/guides/hosting/self-managed/basic-setup#3-generate-a-license)

**Comment by asusdisciple** [comment]
Ah you might be right. I was under the impression that wandb was free for personal use even if used locally no? I get my key from https://wandb.ai/home:

![image](https://github.com/wandb/wandb/assets/138434950/06154924-6348-492f-9d82-8b10855cf640)

**Comment by asusdisciple** [comment]
I solved this issue by using this command:

`docker run --rm -dit -v wandb:/vol -p 8099:8080 --name wandb-local -e HOST=http://yourip:8099/ wandb/local`

**Comment by diaolanya** [comment]
> I solved this issue by using this command:我使用这条命令解决了这个问题：
> 
> `docker run --rm -dit -v wandb:/vol -p 8099:8080 --name wandb-local -e HOST=http://yourip:8099/ wandb/local`

great command, wandb is running normally.
好指令，wandb已经可以正常的跑起来了。
