### ISSUE TITLE
[Q] Wandb does not log when using tmux or screen

### ISSUE THREAD

**Issue by andrewsong90** [wandb/wandb#7805]
Hello!

Connecting and logging with Wandb works well when running experiments on main terminal CLI (when working in-person).

However, whenever I initiate the experiments within tmux or screen (for remote working), it seems the wandb server does not get connected and no results are logged. I am using Huggingface accelerator for Wandb logging.

Does anyone know the solution to this?
Thanks

**Comment by fmamberti-wandb** [comment]
Hi @andrewsong90 , would you be able to share some additional information on your experimental setup when trying to initiate experiments via tmux or screen:

- Are you logging data to W&B cloud platform or to a self-hosted instance?
- How are you initiating the experiments via remote tools? Are you initiating a script stored locally on the remote resource?
- Are you remoting to the same resource that successfully logs experiments? Do you get any terminal output when initiate the run remotely ? Would you be able to provide the `debug.log` and `debug-internal.log` files that should be created on the remote resources at the location `./wandb/run-<date_time>-<runid>/logs` ? 

This information will help us troubleshooting your issue

**Comment by fmamberti-wandb** [comment]
Hi @andrewsong90, I wanted to follow up here and check if you still require our assistance or your issue is now resolved.

**Comment by fmamberti-wandb** [comment]
Hi @andrewsong90, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
