### ISSUE TITLE
[CLI]: no good exit when terminated script by CTRL+C

### ISSUE THREAD

**Issue by christopher5106** [wandb/wandb#7806]
### Describe the bug

It's been now more than 5 years that I use your platform and still the same bug... everytime I exit my programs with CTRL+C, the wandb client remains as a daemon and pollutes the shell with messages 

` wandb: \ 0.003 MB of 0.003 MB uploaded`

that makes the shell unusable anymore. I don't undertand this termination of the logger has not been better managed since, and it's terrible to use.

### Environment

WandB version:

OS:

Python version:

Versions of relevant libraries:

**Comment by fmamberti-wandb** [comment]
Hi @christopher5106 - I am sorry to hear you are experiencing this issue. Would you mind sharing some additional information to help us troubleshoot this:

- What platform are you running your W&B experiments on?
- What version of the SDK do you currently have installed?
- Does this happen with all your W&B experiments? It would be useful to know what objects are you logging (metrics, Images, Artifacts, Tables)
- Do you have the URL for one of the interrupted Runs as well as the `debug.log` and `debug-internal.log` files you can find  in the `./wandb/run-<date_time>-<runid>/logs` folder?

Finally, with version 0.17.0+ we have been releasing a new backend for the SDK `[wandb-core](https://github.com/wandb/wandb/tree/main/core#readme)` as part of the `wandb` package. Among other features, this should improve the robustness of the client so it would be worth testing if you are still experiencing the same issue after enabling it.

The new backend can be enabled setting `wandb.require("core")` at the beginning of your script.

**Comment by christopher5106** [comment]
Yes, it seems the new backend has solved that issue (under Ubuntu). We don't have annoying messages from the zombie process in the shell. I didn't checked how it was programmed, but I believe subprocess is now better managed.
