### ISSUE TITLE
[App]: t.userInfo is null trying to access https://wandb.ai/settings

### ISSUE THREAD

**Issue by oliver-batchelor** [wandb/wandb#7807]
### Current Behavior

I cannot access the settings page, I get a box like this on all the browsers I have tried (Firefox and Chrome)

![image](https://github.com/wandb/wandb/assets/1128677/3f7df7cf-816e-492e-aaa6-abbc8b92fa1e)

### Environment

OS: Linux

Browsers: Firefox, Chrome

Version:

**Comment by fmamberti-wandb** [comment]
Hi @oliver-batchelor - sorry to hear you are experiencing this issue. Would you mind confirming your W&B username so we can investigate what's causing this?

**Comment by fmamberti-wandb** [comment]
You should now be able to access the User Settings page. Please double-check your current settings as some may have been reset to default to fix the issue.

**Comment by oliver-batchelor** [comment]
Username is 'saulzar' - however I note that today, I can access the
settings page fine.
