### ISSUE TITLE
[Q] Upgrade to gqlparser 2.5.14 in next release? 

### ISSUE THREAD

**Issue by Veronicacz** [wandb/wandb#7818]
Hi there, 

Recently there's a security issue in the `vektah/gqlparser` open-source library, which you are currently using in your [core code](https://github.com/wandb/wandb/blob/main/core/go.mod) "`github.com/vektah/gqlparser/v2 v2.5.11 // indirect`". According to GitHub security advisory [GHSA-2hmf-46v7-v6fx](https://github.com/advisories/GHSA-2hmf-46v7-v6fx), this issue allows a remote attacker to cause a denial of service.

We're using Wandb in our project and due to security requirements we have to resolve any security issue which is filed as GitHub security advisory. And, to resolve this issue and enhance the security of wandb, I wondered if it's possible for you to upgrade `gqlparser `to version 2.5.14, where this vulnerability has been addressed, in your next release version.

Thank you!

**Comment by JoanaMarieL** [comment]
Hello @Veronicacz , thank you for writing in, we'll look into this and will get back into you for any update.
