### ISSUE TITLE
Issue showing runs in the groups from mobile browsers

### ISSUE THREAD

**Issue by bolak92** [wandb/wandb#7830]
### Current Behavior

Hello,

I am having an issue to view the grouped runs in the web browsers accessed through the phone browsers. I tried several, including safari, edge, and chrome with reproducible result. The runs are from a team org.
I attached a photo with the bug shown
![IMG_4326](https://github.com/wandb/wandb/assets/49613273/a6c82189-5a51-4f8d-86eb-f9cf0560d438)

### Expected Behavior

To normally show the groups runs in the run tab. When the ungrouping arrow is pressed upon.

### Steps To Reproduce

1. From your phone browser, Go to a team workspace.
2. Press on the runs button to access the runs table.
3. If you have some grouping, try to press on the arrow beside the group name to expand it.

### Environment

OS: iOS

Browsers: safari edge

Version: iOS17.5.1 latest safari and latest edge available

**Comment by luisbergua** [comment]
Hey @bolak92, thanks for flagging this! I tested but was unable to reproduce using Safari/Chrome. May I please ask if this happens only when grouping by a specific param and could you please share your workspace?

**Comment by luisbergua** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by bolak92** [comment]
Hello,
I just tried it again and the problem persists unfortunately.

**Comment by luisbergua** [comment]
Hi @bolak92, thanks for confirming this. Would you mind sharing a link to your project so I can test on my end? Also, does this happen with every parameter?

**Comment by luisbergua** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by luisbergua** [comment]
Hi @bolak92 , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
