### ISSUE TITLE
[Q] "None" was logged when wandb.sweep using pytorch_lightning

### ISSUE THREAD

**Issue by yykmeng** [wandb/wandb#7832]
Hi, I'm training my model using pytorch_lightning frame. Everything is fine when training but when I use wandb.sweep I found that "None"s were logged for all my "train/*" metrics.

So would we only log the metric in the sweep config?
![image](https://github.com/wandb/wandb/assets/167537388/4a32a77d-5082-40ad-b4a9-2ad65584eefd)
![image](https://github.com/wandb/wandb/assets/167537388/5569f8c1-6544-46aa-8b4c-b87374518b64)

**Comment by yykmeng** [comment]
> Hi, I'm training my model using pytorch_lightning frame. Everything is fine when training but when I use wandb.sweep I found that "None"s were logged for all my "train/*" metrics.
> 
> So would we only log the metric in the sweep config? ![image](https://private-user-images.githubusercontent.com/167537388/340992545-4a32a77d-5082-40ad-b4a9-2ad65584eefd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODcyMDEsIm5iZiI6MTcxODc4NjkwMSwicGF0aCI6Ii8xNjc1MzczODgvMzQwOTkyNTQ1LTRhMzJhNzdkLTUwODItNDBhZC1iNGE5LTJhZDY1NTg0ZWVmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwODQ4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZWVkNWEyMjRiYzJkNWJjMDcwMjg1Njc4ZmY4N2YzNWExM2ZlNzdmNGQxZWNiM2IxN2U2M2U5NDI3ZTI1ZjZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XvgS4fDL3xLkjz211dXi2xWq-DrOZ9b4evEnaQyOhXc) ![image](https://private-user-images.githubusercontent.com/167537388/340992646-5569f8c1-6544-46aa-8b4c-b87374518b64.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODcyMDEsIm5iZiI6MTcxODc4NjkwMSwicGF0aCI6Ii8xNjc1MzczODgvMzQwOTkyNjQ2LTU1NjlmOGMxLTY1NDQtNDZhYS04YjRjLWI4NzM3NDUxOGI2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwODQ4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjI1ODI1MzUzYTRlMDhkNGQ2YjEyYmU1NzY0MTg2OTllNzRhZmQwNWNkMjBiODFjMjdmYTBkODRhNzc2YTYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8We2wvHk-6mfLM-AfQExEunsH1tdGHaYVC3nvkj8U2c)

Sadly I found that my goal metric was logged as "None" either...
![image](https://github.com/wandb/wandb/assets/167537388/b697c0e4-7176-48db-be0e-cb33fb36a686)

I have no idea what is going on, anybody can help me?

**Comment by JasonArkens17** [comment]
Hi there! May I start by asking what version of wandb you are using?

**Comment by yykmeng** [comment]
> Hi there! May I start by asking what version of wandb you are using?

Hi, thank you for reply.

Version of wandb is 0.17.2. I finally found that I made a mistake, that it's "NaN" rather than "None".

"NaN" was produced because bugs in my metrics calculate functions. So this issus was closed as bugs have been fixed.
