### ISSUE TITLE
[CLI]: Offline wandb sync failed

### ISSUE THREAD

**Issue by yykmeng** [wandb/wandb#7846]
### Describe the bug

我用pytorch_lightning训练我的模型，每次一但开启offline模式，或者在online实时同步过程中断网以后，等脚本运行结束再进行wandb sync，就会出现下面的错误

```python
def main(args):
    f = open(f"{args.config}")
    opts = EasyDict(yaml.safe_load(f))

    now = datetime.datetime.now().strftime("_%Y-%m-%d_%H:%M:%S")
    run_name = opts.model_name + now
    tags = [opts.model_name, "training"]
    log_path = os.path.join(os.getcwd(), "logs", run_name)
    
    if trainer.local_rank == 0:
        maybe_mkdir_p(log_path)

    wandb.require("core")
    wandb.login()

    trainer = pl.Trainer(
        accelerator=opts.accelerator,
        strategy=opts.strategy,
        devices=opts.devices,
        max_epochs=opts.train_epochs,
        check_val_every_n_epoch=opts.val_gap,
        callbacks=callbacks,
        precision=opts.precision,
        accumulate_grad_batches=opts.accumulate_grad_batches,
        fast_dev_run=opts.fast_dev_run,
        logger=WandbLogger(
            project=opts.project_name,
            name=run_name,
            save_dir=log_path,
            tags=tags,
            offline=opts.offline,
            config=opts,
            group='DDP' if len(opts.devices) > 1 else None
        ),
        log_every_n_steps=opts.log_gap,
    )

    trainer.fit(
        model, train_dataloader, val_dataloader, ckpt_path=opts.ckpt_resume_path
    )
    
    if trainer.local_rank == 0:
        wandb.finish()
```

```shell
Find logs at: /tmp/debug-cli.myuser.log
Syncing: https://wandb.ai/mygroup/myproject/runs/it2aw0fk ... Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home2/myuser/applications/miniconda3/envs/dl/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/home2/myuser/applications/miniconda3/envs/dl/lib/python3.12/site-packages/wandb/sync/sync.py", line 289, in run
    data = self._robust_scan(ds)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home2/myuser/applications/miniconda3/envs/dl/lib/python3.12/site-packages/wandb/sync/sync.py", line 237, in _robust_scan
    return ds.scan_data()
           ^^^^^^^^^^^^^^
  File "/home2/myuser/applications/miniconda3/envs/dl/lib/python3.12/site-packages/wandb/sdk/internal/datastore.py", line 156, in scan_data
    record = self.scan_record()
             ^^^^^^^^^^^^^^^^^^
  File "/home2/myuser/applications/miniconda3/envs/dl/lib/python3.12/site-packages/wandb/sdk/internal/datastore.py", line 137, in scan_record
    checksum_computed = zlib.crc32(data, self._crc[dtype]) & 0xFFFFFFFF
                                         ~~~~~~~~~^^^^^^^
IndexError: list index out of range
```
另一个类似的错误也经常出现，也是offline模式结束脚本以后wandb sync，或者online下断网以后wandb sync
```shell
Find logs at: /home2/myuser/projects/brain_anomaly_detection/wandb/debug-cli.ykm2023.log
Syncing: https://wandb.ai/mygroup/myproject/runs/ttngp283 ... Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home2/myuser/applications/miniconda3/envs/dl/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/home2/myuser/applications/miniconda3/envs/dl/lib/python3.12/site-packages/wandb/sync/sync.py", line 289, in run
    data = self._robust_scan(ds)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home2/myuser/applications/miniconda3/envs/dl/lib/python3.12/site-packages/wandb/sync/sync.py", line 245, in _robust_scan
    raise e
  File "/home2/myuser/applications/miniconda3/envs/dl/lib/python3.12/site-packages/wandb/sync/sync.py", line 237, in _robust_scan
    return ds.scan_data()
           ^^^^^^^^^^^^^^
  File "/home2/myuser/applications/miniconda3/envs/dl/lib/python3.12/site-packages/wandb/sdk/internal/datastore.py", line 153, in scan_data
    assert pad == pad_check, "invalid padding"
           ^^^^^^^^^^^^^^^^
AssertionError: invalid padding
```

### Environment

WandB version: 0.17.2

OS: Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-105-generic x86_64)

Python version: 3.12.3

Versions of relevant libraries: pytorch_lightning 2.3.0

**Comment by yykmeng** [comment]
> Jason Davenport commented: Hi there! To clarify the issue you are having is with syncing your wandb runs? If this is the case may I please ask a bit more about how you are running things? Are you running in offline mode and then waiting to sync until later or are you running into syncing issues during normal runs?
> 
> The stack traces you provided had several errors; however, none of them were related to syncing data so I just want to make sure I have things straight.
> 
> Thanks!
> 
> Best, Jason

Hi! These errors occured when I called "wandb sync <somepath>" by shell, after my script finished.

At first I run thing in online mode and at that moment everything is fine. Because I develop in a remote enviroment and the network is not stable, I want to run in offline mode then errors occured if I "wandb sync <somepath>" after the script is over.

I also tried sync during the script running (I mean calling "wandb sync" while script is running in offline mode), it works, nothing is wrong. But once script finished, I have a high probability of encountering this problem. This is strange because sometimes it is fine, but there is a high probability of errors.

By the way, I use ddp strategy (pytorch_lighting implemented) for training, may this be the reason??

**Comment by kptkin** [comment]
@yykmeng thanks for reporting the issue, we are actively taking a look into it, will report here with our findings.

if you feel comfortable sharing your run folder with support it will be very helpful to further debug it.

**Comment by WarmongeringBeaver** [comment]
I have the same error when calling `wandb sync wandb/latest-run` on some offline run with `0.17.3`.
Did not happen with `0.16.5`.

**Comment by WarmongeringBeaver** [comment]
Hello,

I have sent an email to support@wandb.com with a log folder causing that error and referencing that issue.

**Comment by yykmeng** [comment]
> @yykmeng thanks for reporting the issue, we are actively taking a look into it, will report here with our findings.
> 
> if you feel comfortable sharing your run folder with support it will be very helpful to further debug it. To contact support you could use the following email: [support@wandb.com](mailto:support@wandb.com)



> Jason Davenport commented: Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

Hi! I had to move forward with my project instead of waiting for the bug to be fixed, so now I'm using wandb online mode and the bug hasn't continued to appear. But others seem to be experiencing this same problem @WarmongeringBeaver

**Comment by yykmeng** [comment]
> @yykmeng thanks for reporting the issue, we are actively taking a look into it, will report here with our findings.
> 
> if you feel comfortable sharing your run folder with support it will be very helpful to further debug it. To contact support you could use the following email: [support@wandb.com](mailto:support@wandb.com)



> @yykmeng thanks for reporting the issue, we are actively taking a look into it, will report here with our findings.
> 
> if you feel comfortable sharing your run folder with support it will be very helpful to further debug it. To contact support you could use the following email: [support@wandb.com](mailto:support@wandb.com)
Hi,

I'm moving forward with my project and I can't wait for the bugs to be fixed, sorry for the log files being deleted at the time.

I'm now using wandb online mode and the bug hasn't reappeared yet, if the next time the bug occurs I'll upload the log file.

**Comment by raubitsj** [comment]
This has been fixed in [0.17.6](https://pypi.org/project/wandb/0.17.6/) which was released today.

There was an issue in the internal format of the transaction log which was not fully compatible with the existing "wandb sync" command.

Please reach out if you have critical files that need to be recovered as this should be possible.

**Comment by noaleetz** [comment]
Hi @yykmeng and @WarmongeringBeaver - wanted to follow up here and see if the latest release resolved the issues you were running into?

**Comment by WarmongeringBeaver** [comment]
Hello,

I don't have access to the logs that were causing trouble anymore, but I will come back here if I encounter a similar error.

Thank you for the quick fix btw ☺

**Comment by HRezaei** [comment]
> Hi @yykmeng and @WarmongeringBeaver - wanted to follow up here and see if the latest release resolved the issues you were running into?

Hi Noa, 
I encounter this error when trying to sync, using version 0.17.8:
```shell
$ wandb sync --include-synced --include-offline --sync-all wandb/offline-run-20240905_174550-euufawam/
Find logs at: /jmain02/home/J2AD016/jjw03/myuser/scratch/wandb/debug-cli.myuser.log
Syncing: https://wandb.ai/myuser/myproject/runs/7a3x3zdi ... Exception in thread Thread-1:
Traceback (most recent call last):
  File "/jmain02/home/J2AD016/jjw03/myuser/.conda/envs/dlp/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/jmain02/home/J2AD016/jjw03/myuser/.conda/envs/dlp/lib/python3.10/site-packages/wandb/sync/sync.py", line 289, in run
    data = self._robust_scan(ds)
  File "/jmain02/home/J2AD016/jjw03/myuser/.conda/envs/dlp/lib/python3.10/site-packages/wandb/sync/sync.py", line 245, in _robust_scan
    raise e
  File "/jmain02/home/J2AD016/jjw03/myuser/.conda/envs/dlp/lib/python3.10/site-packages/wandb/sync/sync.py", line 237, in _robust_scan
    return ds.scan_data()
  File "/jmain02/home/J2AD016/jjw03/myuser/.conda/envs/dlp/lib/python3.10/site-packages/wandb/sdk/internal/datastore.py", line 153, in scan_data
    assert pad == pad_check, "invalid padding"
AssertionError: invalid padding
```

**Comment by JasonArkens17** [comment]
Hi @HRezaei I just wanted to let you know I am actively working to repro this on my end. I will update you here as we make progress. Out of curiosity, does this happen every time you use sync or only with this specific run?

**Comment by yykmeng** [comment]
Hi, @JasonArkens17 @noaleetz. I'm using wandb 0.17.8 now and everytime I try `wandb sync my_path` it just be like
```
Find logs at: somewhere/wandb/debug-cli.my_user.log
Skipping directory: my_path
```
No errors occur but always skip the run I want to sync...
