### ISSUE TITLE
[CLI]:  init wandb sdk but  the /tmp/code directory was not created

### ISSUE THREAD

**Issue by uniqueni** [wandb/wandb#7847]
### Describe the bug

When running a multi-machine task using the Megatron-LM framework, wandb init will show that the /tmp/code directory is not created

https://github.com/NVIDIA/Megatron-LM/blob/e33c8f78a35765d5aa37475a144da60e8a2349d1/megatron/training/global_vars.py#L180

### Environment

WandB version:  W&B Local 0.55.0

OS:

Python version: 3.10

Versions of relevant libraries:

**Comment by JoanaMarieL** [comment]
Hi @uniqueni , thank you for writing in. Could you also please send the following:

- full stack trace error
- the debug.log and debug-internal.log. These files are under your local folder wandb/run-<date>_<time>-<run-id>/logs in the same directory where you’re running your code.

**Comment by uniqueni** [comment]
> Hi @uniqueni , thank you for writing in. Could you also please send the following:
> 
> * full stack trace error
> * the debug.log and debug-internal.log. These files are under your local folder wandb/run-_-/logs in the same directory where you’re running your code.

@JoanaMarieL 
My job err 
<img width="954" alt="image" src="https://github.com/wandb/wandb/assets/44921652/688dfb88-0b5f-4835-94eb-b36f56b361a4">

but logs directory is empty

<img width="1291" alt="image" src="https://github.com/wandb/wandb/assets/44921652/a0f37da4-e0d2-4b7f-b811-593976b3ff1d">

**Comment by JoanaMarieL** [comment]
Hello @uniqueni , thank you for providing all the requested information. We suggest to add this on your code: `WANDB_DISABLE_CODE=True` and let us know if that will proceed without issue.

**Comment by JoanaMarieL** [comment]
Hi @uniqueni , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
