### ISSUE TITLE
[Q] why some steps didn't be logged during training?

### ISSUE THREAD

**Issue by shliu0** [wandb/wandb#7853]
![截屏2024-06-25 11 09 55](https://github.com/wandb/wandb/assets/126319446/f59cc85c-1ea6-42ab-9c97-91484a9a687c)
I am training a vqvae and using 1*8 gpus, the code to log as belows, where variable `logs` is a dict:
```
if accelerator.sync_gradients and not generator_step and accelerator.is_main_process:
    # Log metrics
    if global_step % args.log_loss_steps == 0:
        ...
        accelerator.log(logs, step=global_step)
```

**Comment by JoanaMarieL** [comment]
Hi @shliu0 . thank you for writing in. To further investigate, could you please provide the following:

- Workspace/Run Link (you may also send it to our support email for privacy: support@wandb.com, and link this github)
- the `debug.log` and `debug-internal.log`. These files are under your local folder `wandb/run-<date>_<time>-<run-id>/logs` in the same directory where you’re running your code.

Thanks!

**Comment by shliu0** [comment]
> Hi @shliu0 . thank you for writing in. To further investigate, could you please provide the following:
> 
> * Workspace/Run Link (you may also send it to our support email for privacy: [support@wandb.com](mailto:support@wandb.com), and link this github)
> * the `debug.log` and `debug-internal.log`. These files are under your local folder `wandb/run-<date>_<time>-<run-id>/logs` in the same directory where you’re running your code.
> 
> Thanks!



> Hi @shliu0 . thank you for writing in. To further investigate, could you please provide the following:
> 
> * Workspace/Run Link (you may also send it to our support email for privacy: [support@wandb.com](mailto:support@wandb.com), and link this github)
> * the `debug.log` and `debug-internal.log`. These files are under your local folder `wandb/run-<date>_<time>-<run-id>/logs` in the same directory where you’re running your code.
> 
> Thanks!

Thanks for your reply! I have sent an email to [support@wandb.com](mailto:support@wandb.com), please check it. :)
