### ISSUE TITLE
[CLI]: Logging an external artifact folder in Azure Storage Account (HNS) results in a directory stub being logged

### ISSUE THREAD

**Issue by marijncv** [wandb/wandb#7867]
### Describe the bug

Logging an external artifact (folder) that resides in an Azure Storage Account with [hierarchical namespace](https://learn.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-namespace) enabled results in the logging of a directory stub instead of all the files in the directory

```python
import wandb
from wandb import Artifact
wandb.require("core")

artifact = Artifact(name="patch_camelyon", type="dataset")
response = artifact.add_reference("https://account.blob.core.windows.net/data/patch_camelyon") # this is a folder containing subfolders and files
print(response)
```
results in:
```shell
[ArtifactManifestEntry(path='patch_camelyon', digest='0x8DC968AC18C07B1', ref='https://account.blob.core.windows.net/data/patch_camelyon', size=0, extra={"etag": "0x8DC968AC18C07B1"}, skip_cache=False)]
```

The culprit is [here](https://github.com/wandb/wandb/blob/0ab9f80d8c08cf736dfe3e9d8cedf967bd125017/wandb/sdk/artifacts/storage_handlers/azure_handler.py#L114). In a storage account with hierarchical namespace enabled, the call to `blob_client.exists(version_id=query.get("versionId"))` returns `True` because the HNS storage account creates directory stubs as described [here](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blobs-list-python#use-a-flat-listing) (scroll a bit down to the note).

The solution to this could be to check for the existence of the `hdi_isfolder` metadata that the HNS storage account attaches to directory stubs.
```


### Additional Files

_No response_

### Environment

WandB version:
0.17.3

OS:
Macos

Python version:
3.10.14

Versions of relevant libraries:


### Additional Context

_No response_

**Comment by ArtsiomWB** [comment]
Hi @marijncv! Thank you so much for writing in and reporting this. 

Is there a way for you to try out our new wandb GO backend and see if you are still running into this concern?
You can do it by updating to the latest version of wandb and calling `wandb.require("core")` at the top of your script.

**Comment by marijncv** [comment]
@ArtsiomWB thanks for the quick reply! Unfortunately the same issue occurs after updating to `0.17.3` and using `wandb.require("core")`.

I created a [PR](https://github.com/wandb/wandb/pull/7876) that addresses the issue for me. Although I'm struggling with getting the system tests to run. Curious what you think!

**Comment by ArtsiomWB** [comment]
Could you try to run a couple of liters such as, `black`, `mypy` and `ruff`? I do see mypy erroring out in one of the tests.

**Comment by marijncv** [comment]
@ArtsiomWB the mypy error should be fixed now! Also merged latest main into the branch

**Comment by ArtsiomWB** [comment]
Thank you for the follow up! I have gone ahead and asked out Artifact team to take a look at this PR. @marijncv

**Comment by ArtsiomWB** [comment]
Hey @marijncv. Our Engineering team will take a look into it and will working on approving it. Thank you so much for submitting this PR!
