### ISSUE TITLE
[Q] Any docs on the settings argument to `wandb.init`?

### ISSUE THREAD

**Issue by Ilykuleshov** [wandb/wandb#7878]
I have been searching for some time now, and have not yet found any docs on customizing the saving behaviour. According to #3733, this is possible using the `settings` argument. Are there actually no docs on this, or have I just not found them?

**Comment by fmamberti-wandb** [comment]
Hi @Ilykuleshov, thank you for reaching out. Currently, there isn't a documentation page listing all the options available for the `settings` argument, however these can be seen [here](https://github.com/wandb/wandb/blob/23be35a68aeb326b4710d450f09a231dd5310b04/wandb/sdk/wandb_settings.py#L296).

Would you mind sharing some additional information on what you need to customise on the saving behaviour? This would help us provide further guidance.

**Comment by Ilykuleshov** [comment]
Thank you very much for your answer, I am particularly interested in the option to save the logs in a specified folder without creating any subdirectories.

**Comment by fmamberti-wandb** [comment]
Hi @Ilykuleshov, currently you can change the location `wandb` uses to save the logs setting the environment variable with `WANDB_DIR` (see [here](https://docs.wandb.ai/guides/track/environment-variables#optional-environment-variables)). This will include where the `debug.log` and `debug-internal/log` are saved (`WANDB_DIR/wandb/run-<date_time>-<id>/logs/) as well as the output.log file (`WANDB_DIR/wandb/run-<date_time>-<id>/files`)

However, it is not currently possible to have all the files saved in a specific folder without creating subdirectories. Would you mind sharing your use case for this?

**Comment by fmamberti-wandb** [comment]
Hi @Ilykuleshov , I wanted to follow up on this request. Please let us know if we can be of further assistance

**Comment by Ilykuleshov** [comment]
Thank you very much for your assistance, I figured out a way to do what I want without this feature.
Specifically, I wanted to save the wandb logs to the hydra working directory, to escape having two folders created for each run. Since that is impossible, I chose to simply turn off hydra file logging, the config is being logged to wandb anyway. Still, in this context, such a feature may be very useful, please consider adding this.

**Comment by fmamberti-wandb** [comment]
Thanks for sharing the additiona context for your use case - I have now passed this on to our product team as a feature request.
