### ISSUE TITLE
[App]: api.wandb.ai returns 403 forbidden in some regions

### ISSUE THREAD

**Issue by RuRo** [wandb/wandb#7881]
### Current Behavior

1) Open `https://wandb.ai/my_user_name/my_project_name` in the browser, observe the following error message:

> **No cloud providers available for BYOB. This is an invalid state;
> please contact support.**
>
> An application error occurred.

2) Run the following python script (with the correct API key in the `WANDB_API_KEY` env var)
```sh
python -c 'import wandb; wandb.init(project="my_project_name")'
```
observe the following error

<details>

```python
403 response executing GraphQL.
<!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>403</title>403 Forbidden
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
wandb: ERROR It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/reproduction/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1185, in init
    wandb._sentry.reraise(e)
  File "/tmp/reproduction/.venv/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/tmp/reproduction/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1171, in init
    return wi.init()
  File "/tmp/reproduction/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
```

</details>

3) Run the following `curl` command
```sh
curl 'https://api.wandb.ai/' -vvv
```
observe that it responds with a 403

<details>

```
* Host api.wandb.ai:443 was resolved.
* IPv6: (none)
* IPv4: 35.186.228.49
*   Trying 35.186.228.49:443...
* Connected to api.wandb.ai (35.186.228.49) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / RSASSA-PSS
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=api.wandb.ai
*  start date: May  1 09:38:04 2024 GMT
*  expire date: Jul 30 10:31:38 2024 GMT
*  subjectAltName: host "api.wandb.ai" matched cert's "api.wandb.ai"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1D4
*  SSL certificate verify ok.
*   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (4096/152 Bits/secBits), signed using sha384WithRSAEncryption
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://api.wandb.ai/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: api.wandb.ai]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [user-agent: curl/8.8.0]
* [HTTP/2] [1] [accept: */*]
> GET / HTTP/2
> Host: api.wandb.ai
> User-Agent: curl/8.8.0
> Accept: */*
> 
* Request completely sent off
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 403 
< content-length: 134
< content-type: text/html; charset=UTF-8
< date: Sat, 29 Jun 2024 02:31:20 GMT
< alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
< 
* Connection #0 to host api.wandb.ai left intact
<!doctype html><meta charset="utf-8"><meta name=viewport content="width=device-width, initial-scale=1"><title>403</title>403 Forbidden
```

</details>

### Expected Behavior

1) website working as usual

2) script working as usual

3) `curl 'https://api.wandb.ai/'` should return a 404, not a 403

I suspect, that there is some erroneous region blocking going on, because the same curl request from my server in a different region gives the correct results:

<details>

```
* Host api.wandb.ai:443 was resolved.
* IPv6: (none)
* IPv4: 35.186.228.49
*   Trying 35.186.228.49:443...
* Connected to api.wandb.ai (35.186.228.49) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / RSASSA-PSS
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=api.wandb.ai
*  start date: May  1 09:38:04 2024 GMT
*  expire date: Jul 30 10:31:38 2024 GMT
*  subjectAltName: host "api.wandb.ai" matched cert's "api.wandb.ai"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1D4
*  SSL certificate verify ok.
*   Certificate level 0: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 1: Public key type RSA (2048/112 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (4096/152 Bits/secBits), signed using sha384WithRSAEncryption
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://api.wandb.ai/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: api.wandb.ai]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [user-agent: curl/8.8.0]
* [HTTP/2] [1] [accept: */*]
> GET / HTTP/2
> Host: api.wandb.ai
> User-Agent: curl/8.8.0
> Accept: */*
> 
* Request completely sent off
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 404 
< content-type: text/plain; charset=utf-8
< vary: Origin
< x-content-type-options: nosniff
< date: Sat, 29 Jun 2024 02:32:39 GMT
< content-length: 19
< via: 1.1 google
< alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
< 
404 page not found
* Connection #0 to host api.wandb.ai left intact
```

</details>

### Steps To Reproduce

See above

### Screenshots

![image](https://github.com/wandb/wandb/assets/3747318/98f46cee-663e-4ded-ab77-8782e2170892)

### Environment

OS: Linux

Browsers: Chrome

Version: 126.0.6478.114

**Comment by ixtora** [comment]
I have the same problem.

Python 3.8
wandb 0.17.3
transformers 4.41.2

`[rank0]:   File "/home/ixtora/.virtualenvs/main_env/lib/python3.8/site-packages/transformers/integrations/integration_utils.py", line 746, in setup
[rank0]:     self._wandb.init(
[rank0]:   File "/home/ixtora/.virtualenvs/main_env/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1195, in init
[rank0]:     raise e
[rank0]:   File "/home/ixtora/.virtualenvs/main_env/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
[rank0]:     run = wi.init()
[rank0]:   File "/home/ixtora/.virtualenvs/main_env/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 785, in init
[rank0]:     raise error
[rank0]: wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)`

**Comment by EmpyEmpt** [comment]
same error - wandb.ai as a whole does not work, seems like some region blocking is going on similar to recent docker outage

will there be any comments by WANDB team? it would be nice to at least have an official statement on termination of work in said regions

**Comment by ramit-wandb** [comment]
Hi there, apologies for the inconvenience caused here. We are currently looking into this issue. Could you guys share the page where you are encountering this error? It will really help speed up the resolution of this error.

 If you wish not to share your project publicly, you can also email me the link at ramit@wandb.com.

**Comment by RuRo** [comment]
@ramit-wandb it appears that the whole `api.wandb.ai` subdomain is getting region blocked in Russia, so any specific URLs/pages/projects are irrelevant. As you can see in the issue, even the root URL of `https://api.wandb.ai/` returns a 403, unless I access it from an overseas server or use a VPN.

This is a very recent change and there wasn't any official announcements by wandb. As such, I am assuming that this was a misconfiguration of some kind.

**Comment by ielenik** [comment]
> Could you guys share the page where you are encountering this error? It will really help speed up the resolution of this error.
As an example, the login page does not work (403).  
See: https://api.wandb.ai/oidc/login?

**Comment by ielenik** [comment]
Looks like fixed for now

**Comment by fmamberti-wandb** [comment]
Hi, as the issue is now fixed I will close this. Thank you for your patience while we investiagated.

**Comment by philurame** [comment]
The issue has occurred again; please reopen the issue.

**Comment by Natyren** [comment]
@ramit-wandb @fmamberti-wandb Hello! Please check this issue; it’s urgent for many users.

**Comment by kroggen** [comment]
Check https://github.com/mlflow/mlflow

**Comment by estebarb** [comment]
No update on this? It is not possible to use w&b from Digital Ocean TOR-1 DC.

**Comment by Davidos533** [comment]
still a pressing problem
