### ISSUE TITLE
[Feature]: Add sum aggregation to panel grouping ui

### ISSUE THREAD

**Issue by josiahls** [wandb/wandb#7882]
### Description

Logging individual timing. Was hoping to get an aggregated sum of the total timing of a training iteration, however I don't see sum as an option in the grouping.

![image](https://github.com/wandb/wandb/assets/19930483/22c2d108-95a5-4a85-b3f4-db09a4c9ee42)

### Suggested Solution

Add sum as an aggregation method.

### Alternatives

Manually make my own panel either via graphql or python, but just adding a sum aggregation method would be easier than learning / adding either of these.

**Comment by vitoria-wandb** [comment]
Hey @josiahls ! Thank you so much for your feature request!

Could you please share a bit more of information about this, such as:

- which version of Wandb are you using
- are you using the public api? Or a local instance?
- if you are using the public api, could you share with us the link to the workspace? 
- In which panel/chart are you trying to do this for? 


Thank you!

**Comment by josiahls** [comment]
@vitoria-wandb 
- This is the wandb website, not sure what the version is since this is on the website.
- I'm using the wandb website hosted by wandb.
- Not sure if I should share any links to my workspace since this is work related.
- I have timing panels that have timing metrics. I want to create a new panel and sum them together. UI has max/min/mean grouping capabilities but no sum capabilities.

**Comment by vitoria-wandb** [comment]
Hey @josiahls - definitely, I think though that now I see what you mean - thank you for your continued patience with this!

Let me ask you some questions:

- would you like at each step `s` sum $metric-a_s$ at step s and them $metric-b_s$ at step s, i.e. $metric-a_s + metric-b_s$, then at step $s+1$ $metric-a_{s+1} + metric-b_{s+1}$ etc
- or are you referring to the cumulative sum of metric-a from step 1 to step N, and separately the cumulative sum of metric-b from step 1 to step N?


Please let us know, thank you!

**Comment by josiahls** [comment]
@vitoria-wandb I think the first one. That would give me a line graph of the total time per step.

**Comment by vitoria-wandb** [comment]
Hey @josiahls - thank you for your patience with this, I raised the feature request for you! Thanks for flagging this to us, any other questions let us know in the future!
