### ISSUE TITLE
[App]: Cannot access the user setting page

### ISSUE THREAD

**Issue by 594zyc** [wandb/wandb#7891]
### Current Behavior

Got the following error while trying to open the user settings page:

Cannot read properties of null (reading 'oidcName') An application error occurred.

### Environment

OS:

Browsers:

Version:

**Comment by JoanaMarieL** [comment]
Hello @594zyc , thank you for writing in. May we request for the following information:

- WandB Username
- Retry to access the User's Setting page then save and send the browser console logs. Here's how: Right Click on the page>Inspect>Console Tab> Save As.
- Upon retrying to access the page, capture network traffic via a HAR file. Here's how: https://support.google.com/admanager/answer/10358597?hl=en

**Comment by 594zyc** [comment]
Hi,

Thanks for your prompt reply! The console log and the HAR file are attached below 

[wandb.ai-1719900374462.log](https://github.com/user-attachments/files/16062494/wandb.ai-1719900374462.log)

https://drive.google.com/file/d/1nLGeuYh96-w4-OeyAcgTblNgyoWGTewV/view?usp=sharing

Thanks

**Comment by JoanaMarieL** [comment]
Hi @594zyc , thank you for  sharing the logs. Could you also provide your WandB Username? or the email associated with it.

**Comment by JoanaMarieL** [comment]
Hi @594zyc , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
