### ISSUE TITLE
[CLI]: 

### ISSUE THREAD

**Issue by j-cyoung** [wandb/wandb#7894]
### Describe the bug

**It seems the wandb crash when I run another program using DDP.**
I have two separate Python programs, A and B. Program A uses `torch.nn.DataParallel` to run a neural network and wandb to log results. Program B uses `torch.nn.parallel.DistributedDataParallel` to run a neural network but does not use wandb. Initially, I ran four instances of program A on GPUs 0, 1, 2, and 3, each occupying one GPU, and they ran without issues. Then I ran two instances of program B, each occupying two GPUs (0,1 and 2,3). After a while, all instances of program A crashed, showing the errors below. It appears that some process or thread crashed, but I am unsure of the exact cause.

```python
# program A
        wandb.log({"Progress": it}, step=it)
        ''' Evaluate synthetic data '''
        if it in eval_it_pool:
            for model_eval in model_eval_pool:
                print('-------------------------\nEvaluation\nmodel_train = %s, model_eval = %s, iteration = %d'%(args.model, model_eval, it))
                if args.dsa:
                    print('DSA augmentation strategy: \n', args.dsa_strategy)
                    print('DSA augmentation parameters: \n', args.dsa_param.__dict__)
                else:
                    print('DC augmentation parameters: \n', args.dc_aug_param)

                accs_test = []
                accs_train = []
                for it_eval in range(args.num_eval):
                    net_eval = get_network(model_eval, channel, num_classes, im_size).to(args.device) # get a random model

                    eval_labs = label_syn
                    with torch.no_grad():
                        image_save = image_syn
                    image_syn_eval, label_syn_eval = copy.deepcopy(image_save.detach()), copy.deepcopy(eval_labs.detach()) # avoid any unaware modification

                    args.lr_net = syn_lr.item()
                    _, acc_train, acc_test = evaluate_synset(it_eval, net_eval, image_syn_eval, label_syn_eval, testloader, args, texture=args.texture)
                    accs_test.append(acc_test)
                    accs_train.append(acc_train)
                accs_test = np.array(accs_test)
                accs_train = np.array(accs_train)
                acc_test_mean = np.mean(accs_test)
                acc_test_std = np.std(accs_test)
                if acc_test_mean > best_acc[model_eval]:
                    best_acc[model_eval] = acc_test_mean
                    best_std[model_eval] = acc_test_std
                    save_this_it = True
                print('Evaluate %d random %s, mean = %.4f std = %.4f\n-------------------------'%(len(accs_test), model_eval, acc_test_mean, acc_test_std))
                wandb.log({'Accuracy/{}'.format(model_eval): acc_test_mean}, step=it)
                wandb.log({'Max_Accuracy/{}'.format(model_eval): best_acc[model_eval]}, step=it)
                wandb.log({'Std/{}'.format(model_eval): acc_test_std}, step=it)
                wandb.log({'Max_Std/{}'.format(model_eval): best_std[model_eval]}, step=it)

# program B
def main(rank: int, world_size: int, save_every: int, args: argparse.Namespace):
    ddp_setup(rank, world_size, args.port)
    model, trainset, testset, optimizer, criterion = load_train_objs(args.lr)
    trainloader, testloader = prepare_dataloader(trainset, testset, args.batch_size)
    trainer = Trainer(
        model=model,
        trainloader=trainloader,
        testloader=testloader,
        optimizer=optimizer,
        criterion=criterion,
        save_every=save_every,
        save_dir=args.output_dir,
        gpu_id=rank
    )
    if args.resume:
        trainer.resume(os.path.join(args.output_dir, "ckpt.pth"))
    trainer.train(args.epochs)
    destroy_process_group()


if __name__ == "__main__":
    args = read_cmd()

    if args.check_ckpt:
        checkpoint = torch.load(args.check_ckpt)
        best_acc = checkpoint["acc"]
        start_epoch = checkpoint["epoch"]
        print(f"==> test ckp: {args.check_ckpt}, acc: {best_acc}, epoch: {start_epoch}")
        exit()

    if not os.path.exists(args.output_dir):
        os.makedirs(args.output_dir)

    start_time = time.time()
    world_size = torch.cuda.device_count()
    print(f"world size: {world_size}")
    mp.spawn(main, args=(world_size, 10, args), nprocs=world_size)
    end_time = time.time()
    print(f"total time: {end_time - start_time} s")

```

```shell
Exception in thread NetStatThr:
Traceback (most recent call last):
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 149, in check_network_status
    status_response = self._interface.communicate_network_status()
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 125, in communicate_network_status
    resp = self._communicate_network_status(status)
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 397, in _communicate_network_status
    resp = self._communicate(req, local=True)
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 222, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 227, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Exception in thread ChkStopThr:
Traceback (most recent call last):
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 167, in check_status
    status_response = self._interface.communicate_stop_status()
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 114, in communicate_stop_status
    resp = self._communicate_stop_status(status)
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 387, in _communicate_stop_status
    resp = self._communicate(req, local=True)
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 222, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 227, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
[2024-07-01 23:27:54] Evaluate_02: epoch = 1000 train time = 347 s train loss = 0.091399 train acc = 0.9914, test acc = 0.2799
[2024-07-01 23:33:34] Evaluate_03: epoch = 1000 train time = 339 s train loss = 0.108471 train acc = 0.9828, test acc = 0.2804
[2024-07-01 23:40:07] Evaluate_04: epoch = 1000 train time = 393 s train loss = 0.075205 train acc = 0.9912, test acc = 0.2811
Evaluate 5 random ConvNet, mean = 0.2799 std = 0.0024
-------------------------
Traceback (most recent call last):
  File "/home/jiangchenyang/work/dd/longtail/mtt-distillation/distill.py", line 500, in <module>
    main(args)
  File "/home/jiangchenyang/work/dd/longtail/mtt-distillation/distill.py", line 244, in main
    wandb.log({'Accuracy/{}'.format(model_eval): acc_test_mean}, step=it)
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1422, in log
    self._log(data=data, step=step, commit=commit)
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1235, in _log
    self._partial_history_callback(data, self.history_step)
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1083, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 517, in publish_partial_history
    self._publish_partial_history(partial_history)
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 61, in _publish_partial_history
    self._publish(rec)
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/site-packages/wandb/sdk/interface/interface_queue.py", line 49, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
Traceback (most recent call last):
  File "/home/jiangchenyang/work/dd/longtail/mtt-distillation/distill.py", line 500, in <module>
    main(args)
  File "/home/jiangchenyang/work/dd/longtail/mtt-distillation/distill.py", line 244, in main
    wandb.log({'Accuracy/{}'.format(model_eval): acc_test_mean}, step=it)
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1422, in log
    self._log(data=data, step=step, commit=commit)
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1235, in _log
    self._partial_history_callback(data, self.history_step)
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 1083, in _partial_history_callback
    self._backend.interface.publish_partial_history(
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 517, in publish_partial_history
    self._publish_partial_history(partial_history)
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 61, in _publish_partial_history
    self._publish(rec)
  File "/home/jiangchenyang/env/miniconda3/envs/distillation/lib/python3.9/site-packages/wandb/sdk/interface/interface_queue.py", line 49, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

```

### Environment

WandB version:  wandb                     0.12.11            pyhd8ed1ab_0    conda-forge

OS: Ubuntu 22.04

Python version: 3.9.7

Versions of relevant libraries:

_libgcc_mutex             0.1                        main    conda-forge
_openmp_mutex             4.5                       1_gnu  
anyio                     3.5.0            py39h06a4308_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py39h7f8727e_0  
asttokens                 2.0.5              pyhd3eb1b0_0  
attrs                     23.1.0           py39h06a4308_0  
babel                     2.11.0           py39h06a4308_0  
backcall                  0.2.0              pyhd3eb1b0_0  
beautifulsoup4            4.12.2           py39h06a4308_0  
blas                      1.0                         mkl    conda-forge
bleach                    4.1.0              pyhd3eb1b0_0  
bottleneck                1.3.4            py39hce1f21e_0  
brotli                    1.0.9                he6710b0_2  
brotlipy                  0.7.0           py39h27cfd23_1003  
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2024.3.11            h06a4308_0  
certifi                   2024.2.2         py39h06a4308_0  
cffi                      1.15.0           py39hd667e15_1  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     7.1.2              pyh9f0ad1d_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
comm                      0.2.1            py39h06a4308_0  
configparser              5.2.0              pyhd8ed1ab_0    conda-forge
cryptography              36.0.0           py39h9ce1e76_0  
cudatoolkit               11.3.1               h2bc3f7f_2  
cycler                    0.11.0             pyhd3eb1b0_0  
dataclasses               0.8                pyhc8e2a94_3    conda-forge
dbus                      1.13.18              hb2f20db_0  
debugpy                   1.5.1            py39h295c915_0  
decorator                 5.1.1              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
docker-pycreds            0.4.0                      py_0    conda-forge
entrypoints               0.4              py39h06a4308_0  
exceptiongroup            1.2.0            py39h06a4308_0  
executing                 0.8.3              pyhd3eb1b0_0  
expat                     2.4.4                h295c915_0  
ffmpeg                    4.3                  hf484d3e_0    pytorch
fontconfig                2.13.1               h6c09931_0  
fonttools                 4.25.0             pyhd3eb1b0_0  
freetype                  2.11.0               h70c0345_0  
giflib                    5.2.1                h7b6447c_0  
gitdb                     4.0.9              pyhd8ed1ab_0    conda-forge
gitpython                 3.1.27             pyhd8ed1ab_0    conda-forge
glib                      2.69.1               h4ff587b_1  
gmp                       6.2.1                h2531618_2  
gnutls                    3.6.15               he1e5248_0  
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
icu                       58.2                 he6710b0_3  
idna                      3.3                pyhd3eb1b0_0  
importlib-metadata        7.0.1            py39h06a4308_0  
intel-openmp              2021.4.0          h06a4308_3561  
ipykernel                 6.19.2           py39hb070fc8_0  
ipython                   8.15.0           py39h06a4308_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                8.1.2            py39h06a4308_0  
jedi                      0.18.1           py39h06a4308_1  
jinja2                    3.1.3            py39h06a4308_0  
jpeg                      9d                   h7f8727e_0  
json5                     0.9.6              pyhd3eb1b0_0  
jsonschema                4.17.3           py39h06a4308_0  
jupyter                   1.0.0            py39h06a4308_9  
jupyter_client            7.2.2            py39h06a4308_0  
jupyter_console           6.6.3            py39h06a4308_0  
jupyter_core              5.5.0            py39h06a4308_0  
jupyter_server            1.23.4           py39h06a4308_0  
jupyterlab                3.5.3            py39h06a4308_0  
jupyterlab_pygments       0.2.2            py39h06a4308_0  
jupyterlab_server         2.16.3           py39h06a4308_0  
jupyterlab_widgets        3.0.10           py39h06a4308_0  
kiwisolver                1.4.2            py39h295c915_0  
kornia                    0.6.3              pyhd8ed1ab_0    conda-forge
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   9.3.0               h5101ec6_17  
libiconv                  1.15                 h63c8f33_5  
libidn2                   2.3.2                h7f8727e_0  
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.15.8               h780b84a_0    conda-forge
libsodium                 1.0.18               h7b6447c_0  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.2.0                h85742a9_0  
libunistring              0.9.10               h27cfd23_0  
libuuid                   1.0.3                h7f8727e_2  
libuv                     1.40.0               h7b6447c_0  
libwebp                   1.2.2                h55f646e_0  
libwebp-base              1.2.2                h7f8727e_0  
libxcb                    1.15                 h7f8727e_0  
libxml2                   2.9.12               h03d6c58_0  
lz4-c                     1.9.3                h295c915_1  
markupsafe                2.1.1            py39h7f8727e_0  
matplotlib                3.5.1            py39h06a4308_1  
matplotlib-base           3.5.1            py39ha18d171_1  
matplotlib-inline         0.1.6            py39h06a4308_0  
mistune                   2.0.4            py39h06a4308_0  
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py39h7f8727e_0  
mkl_fft                   1.3.1            py39hd3c417c_0  
mkl_random                1.2.2            py39h51133e4_0  
munkres                   1.1.4                      py_0  
nbclassic                 1.0.0            py39h06a4308_0  
nbclient                  0.8.0            py39h06a4308_0  
nbconvert                 7.10.0           py39h06a4308_0  
nbformat                  5.9.2            py39h06a4308_0  
ncurses                   6.3                  h7f8727e_2  
nest-asyncio              1.6.0            py39h06a4308_0  
nettle                    3.7.3                hbbd107a_1  
notebook                  6.5.4            py39h06a4308_1  
notebook-shim             0.2.3            py39h06a4308_0  
numexpr                   2.8.1            py39h6abb31d_0  
numpy                     1.21.2           py39h20f2e39_0  
numpy-base                1.21.2           py39h79a1101_0  
openh264                  2.1.1                h4ff587b_0  
openssl                   1.1.1w               h7f8727e_0  
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.2            py39h295c915_0  
pandocfilters             1.5.0              pyhd3eb1b0_0  
parso                     0.8.3              pyhd3eb1b0_0  
pathtools                 0.1.2                      py_1    conda-forge
pcre                      8.45                 h295c915_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    9.0.1            py39h22f2fdc_0  
pip                       21.2.4           py39h06a4308_0  
platformdirs              3.10.0           py39h06a4308_0  
prometheus_client         0.14.1           py39h06a4308_0  
promise                   2.3              py39hf3d152e_5    conda-forge
prompt-toolkit            3.0.43           py39h06a4308_0  
prompt_toolkit            3.0.43               hd3eb1b0_0  
protobuf                  3.15.8           py39he80948d_0    conda-forge
psutil                    5.8.0            py39h27cfd23_1  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pure_eval                 0.2.2              pyhd3eb1b0_0  
pycparser                 2.21               pyhd3eb1b0_0  
pygments                  2.15.1           py39h06a4308_1  
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pyqt                      5.9.2            py39h2531618_6  
pyrsistent                0.18.0           py39heee7806_0  
pysocks                   1.7.1            py39h06a4308_0  
python                    3.9.7                h12debd9_1  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.2           py39h06a4308_0  
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.11.0          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2024.1           py39h06a4308_0  
pyyaml                    5.4.1            py39h3811e60_0    conda-forge
pyzmq                     22.3.0           py39h295c915_2  
qt                        5.9.7                h5867ecd_1  
qtconsole                 5.5.1            py39h06a4308_0  
qtpy                      2.4.1            py39h06a4308_0  
readline                  8.1.2                h7f8727e_1  
requests                  2.27.1             pyhd3eb1b0_0  
scipy                     1.7.3            py39hc147768_0  
send2trash                1.8.2            py39h06a4308_0  
sentry-sdk                1.5.7              pyhd8ed1ab_0    conda-forge
setproctitle              1.2.2            py39h3811e60_0    conda-forge
setuptools                58.0.4           py39h06a4308_0  
shortuuid                 1.0.8            py39hf3d152e_0    conda-forge
sip                       4.19.13          py39h295c915_0  
six                       1.16.0             pyhd3eb1b0_1  
smmap                     3.0.5              pyh44b312d_0    conda-forge
sniffio                   1.3.0            py39h06a4308_0  
soupsieve                 2.5              py39h06a4308_0  
sqlite                    3.38.0               hc218d9a_0  
stack_data                0.2.0              pyhd3eb1b0_0  
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.17.1           py39h06a4308_0  
tinycss2                  1.2.1            py39h06a4308_0  
tk                        8.6.11               h1ccaba5_0  
tomli                     2.0.1            py39h06a4308_0  
torchaudio                0.11.0               py39_cu113    pytorch
torchvision               0.12.0               py39_cu113    pytorch
tornado                   6.1              py39h27cfd23_0  
tqdm                      4.63.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.7.1            py39h06a4308_0  
typing-extensions         3.10.0.2             hd3eb1b0_0  
typing_extensions         3.10.0.2           pyh06a4308_0  
tzdata                    2021e                hda174b7_0  
urllib3                   1.26.8             pyhd3eb1b0_0  
wandb                     0.12.11            pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyhd3eb1b0_0  
webencodings              0.5.1            py39h06a4308_1  
websocket-client          0.58.0           py39h06a4308_4  
wheel                     0.37.1             pyhd3eb1b0_0  
widgetsnbextension        4.0.10           py39h06a4308_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h516909a_0    conda-forge
yaspin                    2.1.0              pyhd8ed1ab_0    conda-forge
zeromq                    4.3.4                h2531618_0  
zipp                      3.17.0           py39h06a4308_0  
zlib                      1.2.11               h7f8727e_4  
zstd                      1.4.9                haebb681_0

**Comment by JoanaMarieL** [comment]
Thank you for providing all these information @j-cyoung . Could you also attached the `debug.log` and `debug-internal.log`. These files are under your local folder `wandb/run-<date>_<time>-<run-id>/logs` in the same directory where you’re running your code?

**Comment by j-cyoung** [comment]
[debug.log](https://github.com/user-attachments/files/16061322/debug.log)
[debug-internal.log](https://github.com/user-attachments/files/16061323/debug-internal.log)

**Comment by JoanaMarieL** [comment]
Hello @j-cyoung , we suggest to upgrade to the latest version of WandB and try again.

**Comment by j-cyoung** [comment]
I have attached the files above.

**Comment by JoanaMarieL** [comment]
> Hello @j-cyoung , we suggest to upgrade to the latest version of WandB and try again.

hi @j-cyoung , apologies for the confusion of the exalate, we suggest the above^ and let us know what would be the outcome.

**Comment by JoanaMarieL** [comment]
Hi @j-cyoung , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
