### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by ChandanaRaj-art** [wandb/wandb#7896]
### Describe the bug

ImportError: cannot import name '_psutil_linux' from partially initialized module 'psutil' (most likely due to a circular import) (/usr/lib/python3/dist-packages/psutil/__init__.py)  [0702/113556.988260:ERROR:daemon_controller_delegate_linux.cc(210)] Failed to start host. 

### Environment

WandB version:

OS: 22.04.4 LTS (Jammy Jellyfish)

Python version: 3.12.3

Versions of relevant libraries:

### Additional Context

Was trying to install chrome remote desktop- but getting this atribute error.
tried following command as well
sudo apt install python3.12-dev
python -m ensurepip --upgrade
python -m pip install --upgrade setuptools
python -m pip install psutil

**Comment by JoanaMarieL** [comment]
hello @ChandanaRaj-art , are you also using W&B when the error was encountered? Can you share your specific use case too. Thanks!

**Comment by JoanaMarieL** [comment]
Hi @ChandanaRaj-art , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
