### ISSUE TITLE
[Q]W&B table function

### ISSUE THREAD

**Issue by aqizhoua** [wandb/wandb#7901]
Why can't I use the table function of wandb? Is it related to the version of wandb? My version is 0.15.3.I wrote the following simple code to test the table function, but the results cannot be displayed.
The test code is:
```
columns = ["Name", "Age", "Score"]
data = [["ZhuZhu", 1, 0], ["MaoMao",2,1]]
table = wandb.Table(data=data, columns=columns)
wandb.log({"table": table})
wandb.finish()
```
The screenshot of the wandb table is:
![image](https://github.com/wandb/wandb/assets/89376576/fb06499c-cda0-43bd-9178-45b29f5d2d2c)

**Comment by paulosabile-wb** [comment]
Hi @aqizhoua Good day and thank you for contacting us! Happy to help.

I tried the same script that you are using and I was able to run and create a table. The table appears correctly as well in the UI. I am on version `0.17.4`. Would you mind testing your code on the latest SDK version?


Thanks,
Paulo

**Comment by aqizhoua** [comment]
> Hi @aqizhoua Good day and thank you for contacting us! Happy to help.
> 
> I tried the same script that you are using and I was able to run and create a table. The table appears correctly as well in the UI. I am on version `0.17.4`. Would you mind testing your code on the latest SDK version?
> 
> Thanks, Paulo

Hi,Paulo!Thank you for your quick and patient reply. I created a new virtual environment and installed wandb version `0.17.4`, but the table still cannot be displayed. The json file can be seen, but the table cannot be displayed.
The json file is as follows:
![image](https://github.com/wandb/wandb/assets/89376576/bd60a980-c4dd-414c-9251-34bb2c5f7aac)
The table still does not display：
![image](https://github.com/wandb/wandb/assets/89376576/118d106e-b490-4803-aab9-406332422a6f)

**Comment by paulosabile-wb** [comment]
Hi @aqizhoua Thanks for your update. This is quite a strange behavior. May I know what happens if you click on the Reset Panel button as per your screenshot?

**Comment by aqizhoua** [comment]
hi,[@paulosabile-wb](https://github.com/paulosabile-wb)Thanks for your quick response. I clicked on the Reset Panel button and it still crashed and asked me to submit a crash report.

**Comment by paulosabile-wb** [comment]
Hi @aqizhoua Thanks for your update. We'd like to further investigate this issue, could you please share us the project URL where we can access these "crashing" tables? Thank you!

**Comment by aqizhoua** [comment]
Hi @paulosabile-wb How do I make a project public? I've been searching for a while but can't find a way to make a project public. Can you give me some help?

**Comment by paulosabile-wb** [comment]
Hi @aqizhoua You can do this by changing the project visibility. You can go to the project Overview and click on Edit project details button. Then change the project visibility. You can still share the URL without changing this as we should be able to have a view access from our end. Let me know if you have questions!

**Comment by aqizhoua** [comment]
Hi @paulosabile-wb The test url is https://wandb.ai/aqizhou-Shanghai%20University/test/runs/btc5l8r9 .Thanks.

**Comment by paulosabile-wb** [comment]
Hi @aqizhoua Thank you for sharing the URL. We have reproduced the issue from our end. We will now further investigate this and we'll get back to you for an update.

**Comment by aqizhoua** [comment]
OK, I will actively cooperate with your investigation and hope to fix this problem as soon as possible.

**Comment by paulosabile-wb** [comment]
Hi @aqizhoua Good day! Our team have reviewed the issue on the tables and we applied a fix for this. Can you check from your end please if the tables are now working as expected for you? Thank you!

**Comment by aqizhoua** [comment]
Hi @paulosabile-wb  It can be displayed normally here, thank you for your work!Could you please tell me what the problem was that caused it to not display normally before?

**Comment by paulosabile-wb** [comment]
Hi @aqizhoua Apologies for my delayed response. Our team have identified a small bug that affects the tables created by some users in the UI. We have fixed this so this should not happen again on any tables that you will create. If in case you experience issues, please do not hesitate to let us know so we can review. Thank you!
