### ISSUE TITLE
tox -e mypy fail

### ISSUE THREAD

**Issue by dabao1990** [wandb/wandb#7910]
centos 8

cd py-wandb@0.16.6

pip install tox==4.5.1

tox -e mypy 

[root@localhost spack-src]#tox -e mypy
mypy: commands[0]> mypy --install-types --non-interactive --show-error-codes --config-file /home/stage/root/spack-stage-py-wandb-0.16.6-n3qkvddaqdv6gebms72liaofahsncvb5/spack-src/pyproject.toml -p wandb --html-report mypy-results/ --cobertura-xml-report mypy-results/ --lineprecision-report mypy-results/
Generated Cobertura report: /home/stage/root/spack-stage-py-wandb-0.16.6-n3qkvddaqdv6gebms72liaofahsncvb5/spack-src/mypy-results/cobertura.xml
Generated HTML report (via XSLT): /home/stage/root/spack-stage-py-wandb-0.16.6-n3qkvddaqdv6gebms72liaofahsncvb5/spack-src/mypy-results/index.html
wandb/sdk/internal/internal_api.py:2705: error: If x = b'abc' then f"{x}" or "{}".format(x) produces "b'abc'", not "abc". If this is desired behavior, use f"{x!r}" or "{!r}".format(x). Otherwise, decode the bytes  [str-bytes-safe]
Found 5 errors in 3 files (checked 456 source files)
wandb/sdk/internal/internal_api.py:2771: error: If x = b'abc' then f"{x}" or "{}".format(x) produces "b'abc'", not "abc". If this is desired behavior, use f"{x!r}" or "{!r}".format(x). Otherwise, decode the bytes  [str-bytes-safe]
wandb/sdk/data_types/object_3d.py:39: error: Name "np.float_" is not defined  [name-defined]
wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py:303: error: Missing positional argument "file_spec" in call to "__call__" of "_Wrapped"  [call-arg]
wandb/sdk/artifacts/storage_policies/wandb_storage_policy.py:304: error: Argument 1 to "__call__" of "_Wrapped" has incompatible type "dict[str, Sequence[Collection[str]]]"; expected "StepPrepare"  [arg-type]
mypy: exit 1 (129.65 seconds) /home/stage/root/spack-stage-py-wandb-0.16.6-n3qkvddaqdv6gebms72liaofahsncvb5/spack-src> mypy --install-types --non-interactive --show-error-codes --config-file /home/stage/root/spack-stage-py-wandb-0.16.6-n3qkvddaqdv6gebms72liaofahsncvb5/spack-src/pyproject.toml -p wandb --html-report mypy-results/ --cobertura-xml-report mypy-results/ --lineprecision-report mypy-results/ pid=333353
  mypy: FAIL code 1 (129.76=setup[0.11]+cmd[129.65] seconds)
  evaluation failed :( (130.16 seconds)

**Comment by fmamberti-wandb** [comment]
Hi @dabao1990, thank you for reaching out with your report. We have now released a newer version of wandb SDK (0.17.4) - do you get the same error with this version?

**Comment by dabao1990** [comment]
> 嗨，我想跟进这个请求。如果可以提供进一步的帮助，请告诉我们

Due to the relocation of machines in the lab, there are no machine tests these days.

**Comment by dabao1990** [comment]
> Hi @dabao1990 , I wanted to follow up on this request. Please let us know if we can be of further assistance



> Hi @dabao1990 , I wanted to follow up on this request. Please let us know if we can be of further assistance

Due to the relocation of machines in the lab, there are no machine tests these days.

**Comment by fmamberti-wandb** [comment]
Hi @dabao1990, I wanted to follow up here. I was able to run tox on centos 8 and latest version of wandb. I will mark this as complete, please feel free to re-open if you are still experiencing the same issue once you have access to the device again.
