### ISSUE TITLE
[Feature]: Conda package for 0.17.2 or later

### ISSUE THREAD

**Issue by damien2012eng** [wandb/wandb#7912]
### Description

Dear all, 

I saw the numpy was upgraded to 2.0 in the release 0.17.2 as mentioned [here](https://github.com/wandb/wandb/issues/7812). However, it can only be installed via pip. There is no conda packages for 0.17.2 or later. Any plans of releasing these packages? 

### Suggested Solution

Release conda packages for 0.17.2 and later.

**Comment by garywei944** [comment]
Also, the current version v0.16.6 has issue #7770 with the latest Nvidia driver.

**Comment by fmamberti-wandb** [comment]
Hi @damien2012eng and @garywei944 an updated package for wandb has been released for conda. Thank you for your patience and feel free to reach out in the future for any further issue.
