### ISSUE TITLE
[Q] How can i delete the organization in wandb?

### ISSUE THREAD

**Issue by keeplearning-again** [wandb/wandb#7914]
how can i delete the organization??
i visited the account-setting in the organization but, there is nothing. (white boar)
how can i do?
![image](https://github.com/wandb/wandb/assets/54490665/7b18c23d-053a-4d00-b8f6-31c23e92038f)

**Comment by JoanaMarieL** [comment]
Hi @keeplearning-again ,we can help in deleting you Org. Could you please confirm the following details:
ORG name: clynet-org
user: johnxiao

**Comment by keeplearning-again** [comment]
Yes. this is my org name and user account name. Thanks a lot!



---Original---
From: "Joana Marie ***@***.***&gt;
Date: Tue, Jul 9, 2024 10:15 AM
To: ***@***.***&gt;;
Cc: "Ruiqiang ***@***.******@***.***&gt;;
Subject: Re: [wandb/wandb] [Q] How can i delete the organization in wandb?(Issue #7914)




 
Hi @keeplearning-again ,we can help in deleting you Org. Could you please confirm the following details:
 ORG name: clynet-org
 user: johnxiao
