### ISSUE TITLE
[App]: Edit report draft does not work

### ISSUE THREAD

**Issue by angus27rzz** [wandb/wandb#7922]
### Current Behavior

When I go to the project reports and I move on the project that I want to edit I see the message:

Draft edit in progress
[Continue](https://wandb.ai/valer/normalizing_flows/reports/Normalizing-Flows--Vmlldzo4NjA1Mjc0/edit)
Discard

However, when I click continue I get this:

<img width="683" alt="Screenshot 2024-07-09 at 16 43 55" src="https://github.com/wandb/wandb/assets/120127773/f2fc6d4b-a8d0-465b-bd35-1d9d43c68285">

As I edited the report considerably I would really like to recover my draft.

Can you help?

Thanks

### Environment

OS: macOS

Browsers: Chrome and Safari

Version:

**Comment by luisbergua** [comment]
Hi @angus27rzz, thanks for flagging this! I was able to reproduce the issue so will escalate to our engineers and keep you posted

**Comment by angus27rzz** [comment]
Ok, thank you!

**Comment by luisbergua** [comment]
Hey @angus27rzz, this issue has been fixed and you should be able to edit your report now!

**Comment by angus27rzz** [comment]
Thank you very much!
