### ISSUE TITLE
[App]: `Ignore outliers in chart scaling` not functioning

### ISSUE THREAD

**Issue by wuyushuwys** [wandb/wandb#7927]
### Current Behavior

Hello teams,
I met an issue when I using the web APP. The `Ignore outliers in chart scaling` button does not working, neither disable or enable. This happening across difference device and and different browsers. I've tried to clean the cache or re-open the browser but none of these working. Nothing happened when i click the buttom.

Thanks!

### Expected Behavior

The `Ignore outliers in chart scaling` button should work as expected.

### Steps To Reproduce

1. Go to any of my project.
2. Click the `Ignore outliers in chart scaling` button.
3. All charts are not changing the same.

### Screenshots

1. Before click the button
<img width="1079" alt="image" src="https://github.com/wandb/wandb/assets/16226176/86a70068-2d1a-47e4-bbcc-9ca86da37bef">
2. After click the button
<img width="1103" alt="image" src="https://github.com/wandb/wandb/assets/16226176/7cc659b3-5a0c-4f88-8e00-856d6eb8fae9">

### Environment

OS: macOS Sonoma 14.5

Browsers: Chrome / Safari / Edge

Version:

**Comment by luisbergua** [comment]
Hey @wuyushuwys, thanks for flagging this! There's an issue on our end affecting here but our engineers are already investigating so will let you know as soon as it's fixed

**Comment by wuyushuwys** [comment]
Thanks for letting me know!

**Comment by luisbergua** [comment]
@wuyushuwys this has been fixed so you shouldn't see the issue anymore

**Comment by karimknaebel** [comment]
this seems to be a problem again for me. could you look into this?

**Comment by luisbergua** [comment]
Hey @kabouzeid! We made several updates to workspace settings in the last few months, would you mind confirming if you are referring to this option?

<img width="380" height="61" alt="Image" src="https://github.com/user-attachments/assets/699c2ea0-62ef-42b3-b204-5ff803ca19cb" />

If so, would it be possible to share a project link so we can see the issue? I just tried in a project and that seems to work fine

**Comment by karimknaebel** [comment]
yes, this setting :) can i somehow privately share a project link with you?

**Comment by luisbergua** [comment]
sure! would you mind emailing support@wandb.com and referencing this thread? we can take it from there
