### ISSUE TITLE
[App]: W&B Run Overview does not show Table properly

### ISSUE THREAD

**Issue by cemde** [wandb/wandb#7930]
### Current Behavior

Logged `wandb.Table`s appear in local logs but not online in the UI. Sometimes the do appear 6 times, sometimes they dont appear at all.

[Here is my forum entry about this issue](https://community.wandb.ai/t/wandb-table-does-not-update-properly/7126). This explains everything in detail with screenshots.

### Expected Behavior

If I update a table using the `wandb` python package, it should appear online. That means the number of tables locally should equal the number of tables online and their content should be equal too.

### Steps To Reproduce

See the issue in the forum.

### Environment

OS: MacOS and Linux

Browsers: Safari & Firefox

Version: 0.17.4

**Comment by paulosabile-wb** [comment]
Hi @cemde 

I have tried a simple incremental table where I used `add_data` to increment the contents of my table. Everytime I need to add rows in my table, I just need to update the add_data line with the new values and log it. Please check this sample code snippet and see if you can apply the same approach on what you are trying to setup. Let me know if this helps! 

```
import wandb

# Step 1: Initialize a W&B Run
run = wandb.init(project="incremenTable")

# Step 2: Create a W&B Table (if not already created)
my_table = wandb.Table(columns=["column1", "column2"])

# Step 3: Add Data Incrementally
# Assuming new data is [["3a", "3b"], ["4a", "4b"]]
for new_row in [["3a", "3b"], ["4a", "4b"]]:
    my_table.add_data(*new_row)

# Step 4: Log the Updated Table
run.log({"my_table_key": my_table})
run.finish()
```


Thanks,
Paulo

**Comment by paulosabile-wb** [comment]
Hi @cemde , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
