### ISSUE TITLE
[CLI]: Network error (TransientError), entering retry loop.

### ISSUE THREAD

**Issue by whycantfindaname** [wandb/wandb#7948]
### Describe the bug

I use the proxy to log in and watch my own projects:jason-liao-nankai-university/24.7.11%20final_example. 
I can run the example code(pytorch-intro) with wandb successfully syncing run to app both in my laptop and my colab. But it didnt work in my host with a gpu RTX3090. After training one epoch it just froze and started returing Network error (TransientError), entering retry loop.
![Snipaste_2024-07-12_09-32-31](https://github.com/user-attachments/assets/74919aec-1f7e-4097-9429-631a28496b38)
![Snipaste_2024-07-12_09-33-52](https://github.com/user-attachments/assets/4fc50e06-919b-4f15-ac27-d2cf42dfee43)
In my app, i can only see the log of that one epoch.
![Snipaste_2024-07-12_09-35-44](https://github.com/user-attachments/assets/fa7ddf5a-c8f8-4486-b291-c3b38ac0de5c)

### Environment

WandB version:0.17.4

OS: Ubuntu 24.04

Python version: 3.11.9

Versions of relevant libraries:
Requirement already satisfied: click!=8.0.0,>=7.1 in /home/liaowenjie/anaconda3/envs/dl/lib/python3.11/site-packages (from wandb) (8.1.7)
Requirement already satisfied: docker-pycreds>=0.4.0 in /home/liaowenjie/anaconda3/envs/dl/lib/python3.11/site-packages (from wandb) (0.4.0)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /home/liaowenjie/anaconda3/envs/dl/lib/python3.11/site-packages (from wandb) (3.1.43)
Requirement already satisfied: platformdirs in /home/liaowenjie/anaconda3/envs/dl/lib/python3.11/site-packages (from wandb) (4.2.2)
Requirement already satisfied: protobuf!=4.21.0,<6,>=3.19.0 in /home/liaowenjie/anaconda3/envs/dl/lib/python3.11/site-packages (from wandb) (5.27.2)
Requirement already satisfied: psutil>=5.0.0 in /home/liaowenjie/anaconda3/envs/dl/lib/python3.11/site-packages (from wandb) (6.0.0)
Requirement already satisfied: pyyaml in /home/liaowenjie/anaconda3/envs/dl/lib/python3.11/site-packages (from wandb) (6.0.1)
Requirement already satisfied: requests<3,>=2.0.0 in /home/liaowenjie/anaconda3/envs/dl/lib/python3.11/site-packages (from wandb) (2.32.3)
Requirement already satisfied: sentry-sdk>=1.0.0 in /home/liaowenjie/anaconda3/envs/dl/lib/python3.11/site-packages (from wandb) (2.9.0)
Requirement already satisfied: setproctitle in /home/liaowenjie/anaconda3/envs/dl/lib/python3.11/site-packages (from wandb) (1.3.3)
Requirement already satisfied: setuptools in /home/liaowenjie/anaconda3/envs/dl/lib/python3.11/site-packages (from wandb) (69.5.1)
Requirement already satisfied: six>=1.4.0 in /home/liaowenjie/anaconda3/envs/dl/lib/python3.11/site-packages (from docker-pycreds>=0.4.0->wandb) (1.16.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /home/liaowenjie/anaconda3/envs/dl/lib/python3.11/site-packages (from gitpython!=3.1.29,>=1.0.0->wandb) (4.0.11)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/liaowenjie/anaconda3/envs/dl/lib/python3.11/site-packages (from requests<3,>=2.0.0->wandb) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /home/liaowenjie/anaconda3/envs/dl/lib/python3.11/site-packages (from requests<3,>=2.0.0->wandb) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/liaowenjie/anaconda3/envs/dl/lib/python3.11/site-packages (from requests<3,>=2.0.0->wandb) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/liaowenjie/anaconda3/envs/dl/lib/python3.11/site-packages (from requests<3,>=2.0.0->wandb) (2024.7.4)
Requirement already satisfied: smmap<6,>=3.0.1 in /home/liaowenjie/anaconda3/envs/dl/lib/python3.11/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb) (5.0.1)

**Comment by 15910807576** [comment]
I encountered the same problem

**Comment by ArtsiomWB** [comment]
Hi @whycantfindaname, thank you for writing in. Could you please provide the debug.log and debug-internal.log files associated with the run where you are running into this issue? These files should be located in the wandb folder relative to your working directory.

**Comment by lmllmllm** [comment]
I also encountered a network error. Here are my debug.log and debug-internal.log files.
Yesterday, the error was: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url:……
Then I set offline: True, but the network connection error still appeared during training, and it was stuck in the synchronization phase after training was completed.
wandb.ai: The evaluation parameters of the training can be seen normally in the Workspace in Runs, Files is empty, and the status is always Running.
The above situation suddenly appeared yesterday. It was used normally for several months before.
[debug.log](https://github.com/user-attachments/files/16200459/debug.log)
[debug-internal.log](https://github.com/user-attachments/files/16200460/debug-internal.log)

**Comment by lmllmllm** [comment]
[debug.log](https://github.com/user-attachments/files/16200484/debug.log)

**Comment by whycantfindaname** [comment]
> Hi @whycantfindaname, thank you for writing in. Could you please provide the debug.log and debug-internal.log files associated with the run where you are running into this issue? These files should be located in the wandb folder relative to your working directory.

I encountered the same problem as @lmllmllm.Here is my debug.log and debug-internal.log files:
[debug.log](https://github.com/user-attachments/files/16229420/debug.log)
[debug-internal.log](https://github.com/user-attachments/files/16229421/debug-internal.log)
[debug.log](https://github.com/user-attachments/files/16229426/debug.log)
[debug-internal.log](https://github.com/user-attachments/files/16229427/debug-internal.log)

**Comment by ArtsiomWB** [comment]
Thank you for sending over the log files. I do see that inside of @lmllmllm's  logs there are multiple file upload errors. 

Looking at your logs provided above, @whycantfindaname, I am not seeing any errors at all. 

> But it didnt work in my host with a gpu RTX3090. After training one epoch it just froze and started returing Network error

Could both of you please talk a bit about your setup? For @whycantfindaname, are both of the machines connected to the same network? (your laptop and the machine with 3090?

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by whycantfindaname** [comment]
> Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

Thanks a lot. The problem has been solved but i dont know why

**Comment by ArtsiomWB** [comment]
There potentially were changes on our side. Let is know if there were any follow up questions.

**Comment by ArtsiomWB** [comment]
Hi guys! Since we haven't heard from you, I will go ahead and close this thread out. Let me know if you are running into this again!
