### ISSUE TITLE
[App]: Select runs that logged image with the key test to visualize data here 

### ISSUE THREAD

**Issue by CuddleSabe** [wandb/wandb#7950]
### Current Behavior

<img width="1058" alt="截屏2024-07-12 13 48 36" src="https://github.com/user-attachments/assets/48158350-98de-4782-b1e3-cc8f11e0a3d3">

### Environment

OS:

Browsers:

Version:

**Comment by CuddleSabe** [comment]
> Hi @CuddleSabe, thank you for writing in. Could you please point me to the workspace where you are experiencing this? Also talk a bit about this behavior and what your current workflow is?

Hi, my workspace is "https://wandb.ai/1565912498/all_in_one?nw=nwuser1565912498".
I use huggingface's train script to train a model, the loss is successfully upload, but the val image was not uploaded.

**Comment by CuddleSabe** [comment]
> Hi @CuddleSabe, thank you for writing in. Could you please point me to the workspace where you are experiencing this? Also talk a bit about this behavior and what your current workflow is?

I can see the val img in my local disk, but can't see on Wanda

**Comment by ArtsiomWB** [comment]
Thank you so much for providing the workspace, @CuddleSabe. What version of wandb are you currently on? Could you also please send me a toy script of this behavior happening in your side?

Could you please point me to a specific run where the val images are not showing up?

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by ArtsiomWB** [comment]
Hi, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know or create a new follow up thread!
