### ISSUE TITLE
[CLI]: resume from step can only resume once

### ISSUE THREAD

**Issue by JosselinSomervilleRoberts** [wandb/wandb#7951]
### Describe the bug

Hi, I wanted to play around with the `resume_from` introduced in #7711.
For info, I am experimenting with this feature for cases of pre-emption. I checkpoint once per epoch but since I might get pre-empted in the middle of an epoch, I need to resume from the step of the checkpoint.

I tried to play around with a toy example. Let's say I have a batch size of 16 and 2 batches per epoch.
Here is my manual experiment.

```python
import wandb

_id = "dummy_id_bananas"
batch_size=16
wandb.init(resume_from=f"{_id}?_step=0")

# First epoch
wandb.log({'bananas': 1}, step=batch_size)
wandb.log({'bananas': 2}, step=2*batch_size)

# Start of second epoch - we checkpoint
wandb.log({'bananas': 3}, step=3*batch_size)

# Pre-emption occurs.
wandb.finish()

# Job is relaunched, we resume from the start of the second epoch
wandb.init(resume_from=f"{_id}?_step={2*batch_size}")
wandb.log({'bananas': 6}, step=3*batch_size)
wandb.log({'bananas': 7}, step=4*batch_size)

# So far so good.
# First run was [1,2,3]
# Second run was: [1,2] (from save) + [6,7]
# We observe [1,2,6] in UI -> PROBLEM: Missing entry at step=64 for banana=7

# We start the third epoch
wandb.log({'bananas': 8}, step=5*batch_size)

# But we get pre-empted
wandb.finish()

# Third time relaunching. we relaunch at the start of the third epoch
wandb.init(resume_from=f"{_id}?_step={4*batch_size}")
wandb.log({'bananas': 10}, step=5*batch_size)
wandb.log({'bananas': 11}, step=6*batch_size)

# End of third epoch, let's say the job is done.
wandb.finish()
# We expect to see in the UI: [1,2,6,7,10,11]
# But PROBLEM: We still only see [1,2,6]
```

I ran this experiment several times with different ID to make sure it was consistent and I get this issue every time.

### Additional Files

<img width="701" alt="image" src="https://github.com/user-attachments/assets/40907983-71c7-440b-b4c5-f58a4aba4455">

### Environment

WandB version: 0.17.3

OS: Ubuntu 22.04.2 LTS

Python version: 3.10.13

Versions of relevant libraries:

**Comment by JosselinSomervilleRoberts** [comment]
Some additional testing led me to find that the summary metrics are not synced with the plots. Here is what I get for the above run.
![image](https://github.com/user-attachments/assets/4ce7759e-9955-474a-a3bd-65168f3d940a)

It seems like all the logs from the second run were uploaded which is better (but it is still missing the third run). 

I guess this is both an UI and a CLI bug then.

**Comment by dannygoldstein** [comment]
Hi @JosselinSomervilleRoberts, thanks for writing in.

I ran the script that you provided with wandb version 0.17.4 and I got the expected output: 

https://wandb.ai/dannygoldstein/core/runs/xh3zocgv/overview

This run has [1,2,6,7,10,11] in the UI. In the overview page, you can navigate to the run's other versions and they have the correct metric values. 

Did you write in to us to have rewind enabled for you? Are you using wandb-core (our new go backend) in your client? 

Also, could you provide me with a link to your project/runs that you used for this experiment?

**Comment by thanos-wandb** [comment]
Hi @JosselinSomervilleRoberts thank you for reaching out. Could you please provide us with your wandb username so we can check if rewind has been enabled for you? If it hasn't, we will proceed with enabling it accordingly. You may email us at support@wandb.com if you don't wish to publicly disclose this info.

**Comment by thanos-wandb** [comment]
Hi @JosselinSomervilleRoberts I wanted to follow up on this, do you still see any issues and have you reached out to us to get the rewind feature activated? thank you!

**Comment by thanos-wandb** [comment]
Hi @JosselinSomervilleRoberts, since we haven't heard back from you, we will be closing this request for now. However, please feel free to reach out once you've had time to look into it, and we will be more than happy to assist you further.
