### ISSUE TITLE
[Q] How can I upload file to old finished runs?

### ISSUE THREAD

**Issue by quocanhnguyenBF** [wandb/wandb#7980]
I use Run.upload_file(), as per https://github.com/wandb/wandb/issues/4285, I'm using the newest wandb, so it may have depreciated?

Traceback (most recent call last):
  File "/mnt/c/Users/ai2/Documents/maritime_mcgriddles_v1/eval.py", line 32, in <module>
    run.upload_file(file_path, './media')
AttributeError: 'Run' object has no attribute 'upload_file'

**Comment by quocanhnguyenBF** [comment]
[A] I basically just use 
wandb.init(old_run_id)
and 
wandb.log(image_dict)
https://docs.wandb.ai/guides/track/log/media

**Comment by paulosabile-wb** [comment]
Hi @quocanhnguyenBF Good day and thank you for reaching out to us! That is correct you can use `wandb.log()` to log data into wandb and you can log it to your existing projects. If you need further assistance please let us know!
