### ISSUE TITLE
[CLI]: Wandb log crashes with page errors on logging wandb.Image

### ISSUE THREAD

**Issue by Galivan** [wandb/wandb#7984]
### Describe the bug

When logging a wandb.Image, the process fails with exit code -1073741818 (0xC0000006), and page faults are seen with fault handler.
The full error is in a added file.

```python
import wandb
import numpy as np

wandb.init(
    project="my-awesome-project",
)

wandb.log({"test":wandb.Image(np.array([[1,2,3],[1,2,3]]))})
wandb.finish()
```

```shell
*****
wandb: Currently logged in as: ***** (*****). Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.17.5
wandb: Run data is saved locally in *****
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run comfy-eon-9
wandb:  View project at https://wandb.ai/*****/my-awesome-project
wandb:  View run at https://wandb.ai/*****/my-awesome-project/runs/8wvgao4t

Process finished with exit code -1073741818 (0xC0000006)
```

### Additional Files

[err_log.txt](https://github.com/user-attachments/files/16321125/err_log.txt)

### Environment

WandB version: 0.17.5

OS: Windows 11

Python version: 3.9.13

Versions of relevant libraries:
numpy version: 1.26.4

### Additional Context
Same thing happens for the following line:
```python
wandb.log({"test":[1,2,3]})
```
_No response_

**Comment by vitoria-wandb** [comment]
Hey @Galivan - I do not see the error you are seeing, and I have tried to repro with all the info you provided. Could you share your debug logs? They are saved locally where you tried to run that code, thanks!

**Comment by Galivan** [comment]
[debug.log](https://github.com/user-attachments/files/16401172/debug.log)
[debug-internal.log](https://github.com/user-attachments/files/16401173/debug-internal.log)
Hey @vitoria-wandb , I attached both the debug and debug-internal files, hope it is what you asked for.
From a quick scan, it seems that `system_monitor.py` thinks the os in windows 10, could it cause the problem somehow?
Thanks!

**Comment by Galivan** [comment]
Hey, 
I think I fixed the problem.
Had a problem with my drive - some bad blocks. One of them seemed to contain Pandas python package, which caused some of those issues.
A long CHKDSK run fixed the issue.
Thanks!

**Comment by vitoria-wandb** [comment]
Hey @Galivan - thank you for this update! Happy to hear this worked, let us know in the future if you have any other questions!
