### ISSUE TITLE
[Q] why are there no source distributions on pypi for 0.17.x?

### ISSUE THREAD

**Issue by dhellmann** [wandb/wandb#7988]
I'm working on building a distribution that includes wandb, and I need to build from source. I see there are no sdists on pypi.org for versions after 0.16.4. Is that intentional, or an oversight?

**Comment by JoanaMarieL** [comment]
Hi @dhellmann , let us check this internally and will get back to you for an update.

**Comment by dhellmann** [comment]
Thanks, @JoanaMarieL!

**Comment by JoanaMarieL** [comment]
Our pleasure to help @dhellmann , our Eng Team is aware of this and will keep you posted for any progress.

**Comment by kptkin** [comment]
@dhellmann sorry for the issue here, we change our release process and we are working on resolving this. In the short term, we do upload all the source code to github releases, wonder if that could be a temporary workaround, until fix this issue?

I will be updating this thread, but we are optimistic to get a fix for this issue before the next release.

**Comment by dhellmann** [comment]
Hi, @kptkin , the [tool we're using for this build](https://github.com/python-wheel-build/fromager) works mostly automatically with sdists. We do have the ability to configure builds from GitHub release archives.

What's your release schedule like? If it's going to be sort of soon, I might just wait, instead of doing the extra coding that would be needed to consume a release archive.

**Comment by kptkin** [comment]
> Hi, @kptkin , the [tool we're using for this build](https://github.com/python-wheel-build/fromager) works mostly automatically with sdists. We do have the ability to configure builds from GitHub release archives.
> 
> What's your release schedule like? If it's going to be sort of soon, I might just wait, instead of doing the extra coding that would be needed to consume a release archive.

We are planning to have it fixed in a week or so.

**Comment by dhellmann** [comment]
> > Hi, @kptkin , the [tool we're using for this build](https://github.com/python-wheel-build/fromager) works mostly automatically with sdists. We do have the ability to configure builds from GitHub release archives.
> > What's your release schedule like? If it's going to be sort of soon, I might just wait, instead of doing the extra coding that would be needed to consume a release archive.
> 
> We are planning to have it fixed in a week or so, basically want to fix it before the next release in any case as we don't want to break more workflows

OK, that sounds good. I'll see what our schedules look like, and then my team can decide what we need to do internally.

Thank you for keeping me informed!

**Comment by dhellmann** [comment]
Thank you!

**Comment by timoffex** [comment]
The next release will include a source distribution! It requires Go to build from source, but you can temporarily skip the Go step by setting the WANDB_BUILD_UNIVERSAL environment variable to "true".

**Comment by dhellmann** [comment]
I spotted the go dependency, that's a fun one. :-)

For our project, we're trying to build everything fully from source for secure builds, but also fully optimized so we can give the best performance. Having the sdists should make that easier, so thank you, again!

**Comment by JoanaMarieL** [comment]
Hello @dhellmann , you are most welcome. ~

**Comment by raubitsj** [comment]
Source packages were published for 0.17.6
https://pypi.org/project/wandb/0.17.6/
--
[wandb-0.17.6-py3-none-any.whl](https://files.pythonhosted.org/packages/84/ff/67a3b4bdd24d0885894446cccd92ab8f7930ee866978c15440699e42471e/wandb-0.17.6-py3-none-any.whl#sha256=30c4f110d406368a4653fa137ad04e8ba0a68dee25836de55c3ca384b23e30c2)
[wandb-0.17.6-py3-none-macosx_10_14_x86_64.whl](https://files.pythonhosted.org/packages/6d/11/52eb8ec54f77a511e3ecb8523d577a21fb53bf2610884bf5626349a7e04c/wandb-0.17.6-py3-none-macosx_10_14_x86_64.whl#sha256=c554897b9b9a38490fa86d972975528b424daf5bcf35a5249ef2d25bf99986c2)
[wandb-0.17.6-py3-none-macosx_11_0_arm64.whl](https://files.pythonhosted.org/packages/06/62/7ef0315321d04194d652cc91015a9eb411d77003783426947f4b23b395e0/wandb-0.17.6-py3-none-macosx_11_0_arm64.whl#sha256=4015215335b4cff6268342339022382a38a7e086a8388c8b52df53bc6f18f39a)
[wandb-0.17.6-py3-none-manylinux_2_17_aarch64.manylinux2014_aarch64.whl](https://files.pythonhosted.org/packages/12/85/cd8126eb64bcad7b6175496fe5e2ac84d05689ae748cd458cf2a0e322af4/wandb-0.17.6-py3-none-manylinux_2_17_aarch64.manylinux2014_aarch64.whl#sha256=d38c52fdd0add655e0c3d408d7d0a84a19ec559512b157b8d42e9f67d98b3004)
[wandb-0.17.6-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl](https://files.pythonhosted.org/packages/b4/ca/7dfa74d65e76f3608834781f163bedefe3ead636d79f782c7668a0d89a7d/wandb-0.17.6-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=86743223a5f0c76a5c5ebc5a077aaa87221545ff8f12ba754c51a0bc1fe1e67e)
[wandb-0.17.6-py3-none-win32.whl](https://files.pythonhosted.org/packages/df/b9/1d26752a7c9ff5b255c921e13a9c5176e21a0b77e53d3febf892d90c86a5/wandb-0.17.6-py3-none-win32.whl#sha256=247b1c9677fd633a460201f421d4fd4f370e7243d06257fab0ad1bb728ddcc1c)
[wandb-0.17.6-py3-none-win_amd64.whl](https://files.pythonhosted.org/packages/fc/2c/280b8891362967e54de2267454ac6033568b8412ec31225f00ecc11db7a6/wandb-0.17.6-py3-none-win_amd64.whl#sha256=51954f993b372c20812616838302183f0e3abf137614f05d80c7c17c307bfff9)
[wandb-0.17.6.tar.gz](https://files.pythonhosted.org/packages/6e/23/cd49f71a56865b798914442954da000e23cd9d6dbbc2d641ddc7cc6187d4/wandb-0.17.6.tar.gz#sha256=416739f293d59b95bcb189ecbaeb19b3a74ff2b80d501a90b93e6b6f9435c017)
