### ISSUE TITLE
[Q] New run with different name will overwrite and replace previous run under same project.

### ISSUE THREAD

**Issue by HenryLau7** [wandb/wandb#7995]
I write a test code as follows,

```python
import wandb

project_name = "test"
wandb_log = {"parameter1": 1, "parameter2": 2}

def create_run(round):
    unique_name = f'Round_{round}'
    
    run = wandb.init(project=project_name, name=unique_name, reinit=True, config=wandb_log)
    wandb.log({
        "round": round,
        "log": round+1,
    })
    run.finish()

for round in range(5):
    create_run(round)
```

But in the project page, there is only the last run left.

<img width="722" alt="image" src="https://github.com/user-attachments/assets/c45456f5-f690-4977-b4af-8330cc69a49e">

<img width="722" alt="image" src="https://github.com/user-attachments/assets/4fd93483-dc0a-4556-86c0-5998e6edbe3c">

Anybody knows how to fix it?

**Comment by luisbergua** [comment]
Hey @HenryLau7! I just tested but was unable to reproduce since all the runs are created and data isn't overwritten (see [here](https://wandb.ai/luis_team_test/test_run_overwritten?nw=nwuserluis_bergua)). This is actually the expected behavior and we never delete data so I wonder if you could check in your terminal output that all the runs are being executed. Could you also provide a project link so I can take a look?

**Comment by HenryLau7** [comment]
Yes, all runs executed successfully, and the log was consistently updated on the project page throughout the runs. It seems that only I met this scenario, it's so weird. I don't know whether I accidentally changed a default setting.

**Comment by luisbergua** [comment]
Could you share a link to the project? I'll take a look at it

**Comment by HenryLau7** [comment]
> Could you share a link to the project? I'll take a look at it

https://microsoft-research.wandb.io/v-yuanyeliu/test?nw=nwuservyuanyeliu

**Comment by luisbergua** [comment]
Hey @HenryLau7! Just wanted to follow up here to see if this is still an issue?

**Comment by HenryLau7** [comment]
Hi @luisbergua  Thanks a lot. I have solved. There should be an argument `id={Unique name}`.

`run = wandb.init(project=f"",name=f'Round_{round}-Rank{rank}', reinit=True, config=wandb_log, id=f'Round_{round}-Rank{rank}')`

It works.
