### ISSUE TITLE
[CLI]: wandb sync won't upload offline runs

### ISSUE THREAD

**Issue by xiongyi-cui-TRI** [wandb/wandb#8002]
### Describe the bug

wandb cli won't sync offline runs 
when I use `wandb sync path` to upload a offline run, it will only sync online runs. It won't create a run for offline runs.
 

```shell
```

```shell
wandb sync /path/to/wandb/offline-run-aabb/
Find logs at: /path/to/wandb/debug-cli.xiongyi.cui.log
wandb: ERROR Error while calling W&B API: run "aabb" not found while updating run (<Response [404]>)
Syncing: https://wandb.ai/tri/ma_pred/runs/aabb ... done.
```

### Environment

WandB version: 0.17.4

OS: Ubuntu 20.04.6 LTS

Python version: 3.10

Versions of relevant libraries:

**Comment by paulosabile-wb** [comment]
Hi @vkrishnamurthy11 Good day and thank you for reaching out to us. Could you please try to use an alternative method to sync offline runs like this?

` wandb sync [PATH] -p <PROJECT_NAME> -e <ENTITY> --id new_run_id`

Let me know if this works for you.

Regards,
Paulo

**Comment by paulosabile-wb** [comment]
Hi @xiongyi-cui-TRI , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!

**Comment by xiongyi-cui-TRI** [comment]
I haven't got a chance to test it. But on another server with wandb=0.16, `wandb sync` is working fine.
In the worst case, I can downgrade it to 0.16
