### ISSUE TITLE
[Q] WandB log captures from the terminal  stdout are out of order when using python's logging module?

### ISSUE THREAD

**Issue by JanmajaySingh** [wandb/wandb#8008]
Display orders of model training progression are fine when using print statements (for example when printing batch progression per epoch).

However things are out of order when using python's logging interspersed with print().
For example: in the terminal screenshot below the batch progression is displayed correctly:
<img width="531" alt="Screenshot 2024-07-25 at 9 32 37 AM" src="https://github.com/user-attachments/assets/20b045fd-a481-443b-869d-a29ff2652bea">

However in wandb, Epoch 4's Batch 0 is displayed above Epoch 3's losses which is not the order these lines are executed in code.
<img width="1153" alt="Screenshot 2024-07-25 at 9 35 24 AM" src="https://github.com/user-attachments/assets/78e79908-0e05-4bf9-aaa4-bef2c4977018">

Is this a bug?

**Comment by kptkin** [comment]
@JanmajaySingh i was able to reproduce it locally and i see that the behavior is more consistent with what you would expect in our new client service (see [here](https://github.com/wandb/wandb/blob/0a11fcbc8271465832ddcab50dba671c1cece48a/core/README.md) for more details). Please give it a try and let us know if that solved your issues or/and if you have other questions.

**Comment by JanmajaySingh** [comment]
Thanks for looking into this @kptkin!
