### ISSUE TITLE
[Q] Need help changing an email

### ISSUE THREAD

**Issue by eliphatfs** [wandb/wandb#8010]
I changed my github email as the previous one is recycled by the institution.
However, the wandb email is still the old one.
When I click 'add email' and 'login from github', the new email is not added.
When I click 'login from google' and pick the new email, the new email is not added and it says 'the email has already been added'. I think this is due to it querying the github email, but the record is wrong in wandb.

**Comment by paulosabile-wb** [comment]
Hi @eliphatfs Good day and thank you for reaching out to us! Happy to help you on this.

We can review this for you, could you please share us your username and previous email address in wandb so we can check? And please also share your new email address. Thank you!

**Comment by eliphatfs** [comment]
Hi Jason,

Thank you for your response.
I cannot register a new account because I directly logs into my old account when i log in via either github or google.
