### ISSUE TITLE
[CLI]: `wandb agent` runs into service wait timeout and ignores `WANBD__SERVICE_WAIT` env var

### ISSUE THREAD

**Issue by FFroehlich** [wandb/wandb#8023]
### Describe the bug

I am trying to run a sweep consisting of ~360 runs with parallelisation on a cluster via slurm jobarrays. A majority of runs does not start due to timeouts waiting for the wandb service to start:
```shell
Error: Timed out waiting for wandb service to start after 30.0 seconds. Try increasing the timeout with the `_service_wait` setting.
```

I have tried extending the timeout via `export WANBD__SERVICE_WAIT=300`, but this appears to be ignored by `wandb agent`.

I have tried staggering start times via `sleep $((SLURM_ARRAY_TASK_ID*5))`, but this does not appear to help.

## MWE
**run.sh**
```
#!/bin/bash
#SBATCH -c 1
#SBATCH -N 1

export WANBD__SERVICE_WAIT=300
sleep $((SLURM_ARRAY_TASK_ID*5))
srun wandb agent "$SWEEP_ID" --count 1
```

**sweep.sh**
```
export SWEEP_ID=...
sbatch --wait --array=0-359 ./run.sh
```

## Traceback

The traceback in `debug-cli.**.log` isn't really helpful:
```
2024-07-26 17:45:28 ERROR Traceback (most recent call last):
  File ".../wandb/cli/cli.py", line 108, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File ".../wandb/cli/cli.py", line 1820, in agent
    api = _get_cling_api()
          ^^^^^^^^^^^^^^^^
  File ".../wandb/cli/cli.py", line 133, in _get_cling_api
    wandb.setup(settings=dict(_cli_only_mode=True))
  File ".../wandb/sdk/wandb_setup.py", line 325, in setup
    ret = _setup(settings=settings)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../wandb/sdk/wandb_setup.py", line 318, in _setup
    wl = _WandbSetup(settings=settings)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../wandb/sdk/wandb_setup.py", line 303, in __init__
    _WandbSetup._instance = _WandbSetup__WandbSetup(settings=settings, pid=pid)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../wandb/sdk/wandb_setup.py", line 114, in __init__
    self._setup()
  File ".../wandb/sdk/wandb_setup.py", line 250, in _setup
    self._setup_manager()
  File "...wandb/sdk/wandb_setup.py", line 283, in _setup_manager
    self._manager = wandb_manager._Manager(settings=self._settings)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../wandb/sdk/wandb_manager.py", line 145, in __init__
    self._service.start()
  File ".../wandb/sdk/service/service.py", line 253, in start
    self._launch_server()
  File ".../wandb/sdk/service/service.py", line 247, in _launch_server
    _sentry.reraise(e)
  File ".../wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File ".../wandb/sdk/service/service.py", line 245, in _launch_server
    self._wait_for_ports(fname, proc=internal_proc)
  File ".../wandb/sdk/service/service.py", line 134, in _wait_for_ports
    raise ServiceStartTimeoutError(
wandb.sdk.service.service.ServiceStartTimeoutError: Timed out waiting for wandb service to start after 30.0 seconds. Try increasing the timeout with the `_service_wait` setting.
```

### Environment

WandB version: 0.17.5

OS: Rocky Linux 8.7 (Green Obsidian)

Python version: 3.11.5

Versions of relevant libraries:

**Comment by fmamberti-wandb** [comment]
Hi @FFroehlich thank you for reaching out and sorry to hear you are experiencing this issue.

> I am trying to run a sweep consisting of ~360 runs with parallelisation on a cluster via slurm jobarrays

How many of these runs would you be looking to run in parallel? There is a good chance that could hit the rate limits if running too many agents in parallels. See more on Rate limits on our [docs](https://docs.wandb.ai/guides/track/limits#rate-limits)

> I have tried extending the timeout via export WANBD__SERVICE_WAIT=300

Would you mind trying to update the code on your training script to set the service wait in the init call as an override rather than as env variable:

```wandb.init(...,settings=wandb.Settings(_service_wait=300)```

Would you also be able to share the `debug.log` and `debug-internal.log` files you should be able to find in the `./wandb/run-<date_time>-<runid>/logs` folder on the device logging the run, for any of the runs that fails to start?

**Comment by FFroehlich** [comment]
> Hi @FFroehlich thank you for reaching out and sorry to hear you are experiencing this issue.
> 
> > I am trying to run a sweep consisting of ~360 runs with parallelisation on a cluster via slurm jobarrays
> 
> How many of these runs would you be looking to run in parallel? There is a good chance that could hit the rate limits if running too many agents in parallels. See more on Rate limits on our [docs](https://docs.wandb.ai/guides/track/limits#rate-limits)

See above, the number is 360. I have experienced issues with as little as 20 parallel runs. Passing run information shouldn't be more than a couple hundred bytes, so I don't really see how this would hit rate limits.

> 
> > I have tried extending the timeout via export WANBD__SERVICE_WAIT=300
> 
> Would you mind trying to update the code on your training script to set the service wait in the init call as an override rather than as env variable:
> 
> `wandb.init(...,settings=wandb.Settings(_service_wait=300)`

This will not help, the timeout issue happens before any python script is ever run. The timeout happens in the call to `wandb agent` before any run information is ever fetched.

> Would you also be able to share the `debug.log` and `debug-internal.log` files you should be able to find in the `./wandb/run-<date_time>-<runid>/logs` folder on the device logging the run, for any of the runs that fails to start?

I can't, the timeout happens before a run id or any other run associated metadata is created.

**Comment by FFroehlich** [comment]
Just to clarify, this is what a working run looks like:
```
wandb: Starting wandb agent 🕵️
wandb: Starting wandb agent 🕵️
2024-07-29 16:23:51,954 - wandb.wandb_agent - INFO - Running runs: []
2024-07-29 16:23:53,006 - wandb.wandb_agent - INFO - Agent received command: run
2024-07-29 16:23:53,010 - wandb.wandb_agent - INFO - Agent starting run with config:
	...
2024-07-29 16:23:53,015 - wandb.wandb_agent - INFO - About to run command: /usr/bin/env python ...
```

This is what a run with a timeout looks like:
```
wandb: ERROR Find detailed error logs at: ...
Error: Timed out waiting for wandb service to start after 30.0 seconds. Try increasing the timeout with the `_service_wait` setting.
```

**Comment by FFroehlich** [comment]
The entity is "lab_frohlich" and the project is, for example, "erk_pulse_ude.egfr_feedback". 

Sweep configuration uses "grid" as search method (this sweep includes ~5k runs)

```
method: grid
metric:
  goal: minimize
  name: loss.min
name: erk_pulse_ude
parameters:
  activation_fn_name:
    values:
      - relu
      - swish
  colloquium_fraction:
    values:
      - 0
      - 0.2
      - 0.4
  final_activation_fn_name:
    values:
      - exp
      - softplus
      - sigmoid
  mlp_depth:
    values:
      - 1
      - 2
      - 4
  mlp_layer_width:
    values:
      - 4
      - 8
      - 16
  n_epochs:
    values:
      - 4000
  reg_strength:
    values:
      - 0.1
      - 0.01
      - 0.001
  seed:
    values:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
  variant:
    values:
      - egfr_feedback
program: src/train.py
project: erk_pulse_ude.egfr_feedback
```

I initially tried multiple runs in each agent, but this didn't seem to help much and massively increased wall-time.

**Comment by thanos-wandb** [comment]
Thank you for the additional details, @FFroehlich. The increased wall time is due to multiple runs being executed consecutively for each agent. To ensure site reliability in our public cloud/SaaS offering, we enforce [rate limits](https://docs.wandb.ai/guides/track/limits#rate-limits), which might be causing the timeouts you’re experiencing since the number of parallel agents you’re starting exceeds the limits of your subscription plan.

Regarding the service wait environment variable issue, could you try adding it directly in your `train.py` script? You can do this in the `wandb.init` call as follows:
`wandb.init(settings=wandb.Settings(_service_wait=300))`

Please let us know if that helps resolving the issue, or if you're still seeing any timeouts.

**Comment by thanos-wandb** [comment]
Hi @FFroehlich I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by leesh-1** [comment]
Hi @thanos-wandb, I'm having the exact same issue since yesterday. Maybe it has to do with the newest update? The most confusing thing is that when I log to wandb from another project, with an old repo, I don't have this timeout issue (even now). But when I try to run from my new code, which was working fine until ~24 hours ago, and try to run even a single wandb initialization, it times out. Basically, I'm completely unable to log any experiments at the moment due to having my entire setup use wandb, and would greatly appreciate any help.

**Comment by leesh-1** [comment]
> Hi @FFroehlich I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

Also, I wanted to note that a similar issue has appeared a year ago (https://github.com/wandb/wandb/issues/5214), and none of the workarounds mentioned there appear to work for me.

**Comment by thanos-wandb** [comment]
Hi @leesh-1 apologies for any inconvenience this is currently causing you. Just to understand how the issue relates here and to gather some additional debugging information:

- what's the exact error message you're seeing, could you provide us with a stack trace?
- are the old and new project logged under the same W&B entity? 
- what's your current `wandb --version`
- have you enabled `wandb-core`, our [new SDK backend](https://github.com/wandb/wandb/tree/main/core) written in Go? you only have to add `wandb.require("core")`
- would it be possible to run a simple init/log/finish script where you enable the debug flag that has more verbose logging on network tracing and share with us the [SDK debug logs](https://docs.wandb.ai/guides/technical-faq/admin#which-files-should-i-check-when-my-code-crashes)? you can do that as follows:

`WANDB_DEBUG=True python test.py`

where `test.py`:
```
import wandb
wandb.init()
wandb.log({'metric': 1})
wandb.finish()
```

**Comment by thanos-wandb** [comment]
Hi @leesh-1 we wanted to follow up with you regarding your support request as we have not heard back from you. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by thanos-wandb** [comment]
Hi @leesh-1 @FFroehlich since we have not heard back from you in a while we are going to close this request. If you would like to re-open the conversation, please let us know and we will be more than happy to assist you any further.
