### ISSUE TITLE
cannot log image

### ISSUE THREAD

**Issue by haowang020110** [wandb/wandb#8041]
### Current Behavior

The wandb image cannot be logged with wandb.log since 2days ago.Before that it can be logged used the same code.

### Screenshots

<img width="2560" alt="截屏2024-07-27 11 57 59" src="https://github.com/user-attachments/assets/b1717494-525a-460e-b06e-0e87a1b460f8">

### Environment

OS:

Browsers:

Version:

**Comment by haowang020110** [comment]
Hi I found the problem is that my run name include string "[0,1000]" , can this bug be solved?
thanks a lot

**Comment by vitoria-wandb** [comment]
Hey @haowang020110 - thanks for reaching out! 

- Could you please share with us a code snippet of how you are logging your images? 
- did you manually name your run or you are saying that one of the generated names added that string? If you manually generated that, could you show us a code snippet of how you did so we can investigate further?

Thanks - let us know!
