### ISSUE TITLE
[Q]How to modify run history

### ISSUE THREAD

**Issue by MaKaNu** [wandb/wandb#8056]
We have the following issue:

We have Plotly Plot, which is getting an update every X Episode. If we now look on wandb we will see for every X Episode the updated version of the Plotly Plot and a slider to select the previous plots.

Via `run.history()` we are also able to see the data in the dataframe.

Actually, we only want the latest updated version of the Plotly Plot and don't need the redundant previous ones.

How can we delete the previous Plots from the run?

**Comment by luisbergua** [comment]
Hey @MaKaNu, thanks for writing in! Deleting already logged data is not possible at this moment so that won't be possible. Please let me know if this is helpful!

**Comment by MaKaNu** [comment]
Hello, that is very sad to hear. Going forward, I will only recommend using wandb for distributed hyperparameter learning and not for visualization that extends beyond line graphs.

**Comment by luisbergua** [comment]
I'm sorry to hear that @MaKaNu. I was wondering if you could find our new features [rewind](https://docs.wandb.ai/guides/runs/rewind) and [fork](https://docs.wandb.ai/guides/runs/forking) runs helpful for your use case? If so, we can enable those for your account so you can give them a try, just let me know

**Comment by sydholl** [comment]
Due to inactivity we are closing this request, please comment to reopen.
