### ISSUE TITLE
[Q] I got this bug at epoch 26, what could the problem be?

### ISSUE THREAD

**Issue by BatmanofZuhandArrgh** [wandb/wandb#8068]
Bug:

`
Generating Visualizations for batch-1/1:   0%|                                                    | 0/8 [00:00<?, ?it/s]Traceback (most recent call last):                                                                                        File "/mnt/c/Users/ai2/Documents/maritime_mcgriddles_v1/train.py", line 34, in <module>                                   model.train(cfg=yolov8_model_config, data=yolov8_data_config)  # start training                                       File "/home/anh/miniconda3/envs/yolov8/lib/python3.9/site-packages/ultralytics/engine/model.py", line 341, in train       self.trainer.train()                                                                                                  File "/home/anh/miniconda3/envs/yolov8/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 195, in train     self._do_train(world_size)                                                                                            File "/home/anh/miniconda3/envs/yolov8/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 402, in _do_train                                                                                                                         self.run_callbacks('on_fit_epoch_end')                                                                                File "/home/anh/miniconda3/envs/yolov8/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 160, in run_callbacks                                                                                                                     callback(self)                                                                                                        File "/home/anh/miniconda3/envs/yolov8/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context                                                                                                                     return func(*args, **kwargs)                                                                                          File "/home/anh/miniconda3/envs/yolov8/lib/python3.9/site-packages/wandb/integration/ultralytics/callback.py", line 302, in on_fit_epoch_end                                                                                                      self.train_validation_table = plot_detection_validation_results(                                                      File "/home/anh/miniconda3/envs/yolov8/lib/python3.9/site-packages/wandb/integration/ultralytics/bbox_utils.py", line 177, in plot_detection_validation_results                                                                                   ground_truth_data = get_ground_truth_bbox_annotations(                                                                File "/home/anh/miniconda3/envs/yolov8/lib/python3.9/site-packages/wandb/integration/ultralytics/bbox_utils.py", line 41, in get_ground_truth_bbox_annotations                                                                                    cls_labels = batch["cls"][indices].squeeze(1).tolist()                                                              IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)                                      wandb: / 844.974 MB of 844.974 MB uploaded    
`

Code: 
```

# ultralytics/yolov8 preprocessor
from typing import Final
import wandb
from wandb.integration.ultralytics import add_wandb_callback
from tracking.wandb_utils import log_artifact
import yaml
from ultralytics import YOLO

# Initialize experiment
exp_name = "exp_name"
proj_name = "proj_name"

# Attach training configurations to experiment

yolov8_model_config: Final[str] = "configs/config.yaml"
yolov8_data_config: Final[str] = "configs/data.yaml"

with open(yolov8_model_config) as f:
    model_configs: dict = yaml.safe_load(f)
with open(yolov8_data_config) as f:
    data_configs: dict = yaml.safe_load(f)

wandb.init(project=proj_name, name=exp_name, job_type="training",  config=model_configs, tags=["model_name", "num_class"])
config = wandb.config

model = YOLO(model_configs.get("model", "yolov8n.pt"))
add_wandb_callback(model, enable_model_checkpointing=True)

# # Log the config and data files as artifactss
log_artifact(yolov8_data_config, 'dataset')
log_artifact(yolov8_model_config, 'config')
log_artifact('./train.py', 'train.py')

model.train(cfg=yolov8_model_config, data=yolov8_data_config)  # start training
metrics = model.val()

# Export the model to ONNX format
path = model.export(format="onnx")


# print('-------METRICS--------')
# print(metrics)
# print(path)

# Finish the W&B run
wandb.finish()

```

**Comment by ArtsiomWB** [comment]
Hi @BatmanofZuhandArrgh! Thank you for writing in. Could you please provide the debug.log and debug-internal.log files associated with the run where you are running into this issue? These files should be located in the wandb folder relative to your working directory. 

As well as the link to the failed run?

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.
