### ISSUE TITLE
[CLI]: Running Sweep stops running new runs every 5 runs and each sweep creates 5 agents 

### ISSUE THREAD

**Issue by ecada** [wandb/wandb#8076]
### Describe the bug

I was using WandB without any issues until yesterday. After upgrading my account to exceed 100 GB, my sweeps containing 30-100 runs have started stopping unexpectedly. Despite no crashes or failed runs, each agent now only completes 5 runs, whereas previously, each agent would complete 93-99 runs. (the sweep just stops running new runs until I run the sweep again with nohup wandb agent xxxxx &) Running “nohup wandb agent xxxxx &” every 5 runs is not a viable option, as I need to run my experiments in parallel. 
The is no max count limit in the sweep it is a grid method
The premature stopping of experiments is significantly impacting my research. Thank you in advance for your assistance.

```python

```

```shell

```

### Additional Files

<img width="1657" alt="Screenshot 2024-08-03 at 14 54 52" src="https://github.com/user-attachments/assets/99318b60-4753-43ae-bb33-5b0193324e19">

### Environment

WandB version: 0.17.5

OS: Ubuntu 22.04

Python version:3.19.16

Versions of relevant libraries:

**Comment by vitoria-wandb** [comment]
Hey @ecada , 

Thanks for reaching out!

Could you please share a couple of things:
- Could you please send debug.log and debug-internal.log? These files are under your local folder wandb/run-<date-time>-<run-id>/logs in the same directory where you’re running your code. 
- Could you share the code you are using to run your sweep? 


Thank you!
W&B

**Comment by vitoria-wandb** [comment]
Hi @ecada , since we have not heard back from you we are going to close this request. 

If you would like to re-open the conversation, please let us know!
