### ISSUE TITLE
Failed to query for notebook name

### ISSUE THREAD

**Issue by DbCrWk** [wandb/wandb#8104]
I'm writing Jupyter notebooks in VS Code and I get this error when running wandb.

_Originally posted by @DbCrWk in https://github.com/wandb/wandb/issues/1153#issuecomment-2277075603_

Hi y'all, I'm opening a new issue based on this earlier issues because I'm having the same problem.

**Comment by ArtsiomWB** [comment]
Hi @DbCrWk, thank you for writing in!

Could you please send us the full error stack of the issue you are currently seeing? What version of wandb are you currently running?

**Comment by DbCrWk** [comment]
<img width="1294" alt="image" src="https://github.com/user-attachments/assets/06fb2641-7c95-4517-bd96-b031ea9ec614">

| Failed to detect the name of this notebook, you can set it manually with the WANDB_NOTEBOOK_NAME environment variable to enable code saving.

`wandb, version 0.16.6`

**Comment by DbCrWk** [comment]
@ArtsiomWB thanks for getting back to me!

**Comment by ArtsiomWB** [comment]
Totally! 
Could you please go ahead and update to the latest version to wandb and see if this warning will go away. We have made some changes to our client's back-end that could have potentially resolved this warning.

**Comment by DbCrWk** [comment]
Same error with `wandb, version 0.17.6`

**Comment by vitoria-wandb** [comment]
Hey @DbCrWk - I would have some questions so to find an appropriate resolution for this:

- are you having also some GraphQL errors with this like the one below?

`500 response executing GraphQL.` or like `wandb: ERROR 400 Client Error: Bad Request for url:` ?

- Also, could you please try out new wandb version [0.17.7](https://github.com/wandb/wandb)?  It's a new release that was released between yesterday and today, hopefully that could help. 

- Is this error showing up right after `wandb.init()`? In case, could you please try to use our [backend core](https://github.com/wandb/wandb/tree/main/core) with `wandb.require("core")` as in [this documentation ](https://github.com/wandb/wandb/tree/main/core) ?

Thank you, let us know!

**Comment by DbCrWk** [comment]
I am not seeing GraphQL errors. Everything is working as expected, except for detecting the notebook name. Updating to latest and setting to `core` did not fix this issue. My guess is that this is not a backend issue, as it seems to be unable to detect the name of the notebook in the notebook itself.

**Comment by vitoria-wandb** [comment]
I see, have you already tried doing `os.environ["WANDB_NOTEBOOK_NAME"] = "some_name.ipynb"` or restarting the kernel on the jupyter notebook? Let's see if this could do the trick, thanks!

**Comment by DbCrWk** [comment]
> I see, have you already tried doing `os.environ["WANDB_NOTEBOOK_NAME"] = "some_name.ipynb"` or restarting the kernel on the jupyter notebook? Let's see if this could do the trick, thanks!

Restarting the kernel does not solve the problem. I create a lot of notebooks and even on a fresh notebook, it does not fix the issue. I understand that I could set `WANDB_NOTEBOOK_NAME` manually, but in my view, this defeats the point of `wandb` automatically detecting the notebook name. Worse, if someone copies over a notebook and forgets to change the exported environment variable, `wandb` would report an inconsistent name for the notebook.

My suspicion is that there is a bug or edge case in the detection process.

**Comment by DbCrWk** [comment]
Interestingly, I see that there is some documentation on test fixtures that suggests that this might be expected?

Here's a few relevant links I see:
- https://github.com/wandb/wandb/blame/48d19dfb80f7aa3b2fe73bccb379567b8901e192/tests/pytest_tests/assets/wandb/offline-run-20210216_154407-g9dvvkua/files/upstream_diff_78c43d0cc7146adb88cef2fcca4ec244a2d6a162.patch#L392
- https://github.com/wandb/wandb/blob/48d19dfb80f7aa3b2fe73bccb379567b8901e192/tests/pytest_tests/assets/notebooks/code_saving.ipynb
- https://github.com/wandb/wandb/pull/4982

@dmitryduev I was wondering if you had any insight into that particular assertion? Do you by chance know what would cause wandb to not detect the notebook and hence why there is a test fixture that contains it?

**Comment by ArtsiomWB** [comment]
Thank you for looking into this. 

Let me try to reproduce this behavior on my side. To confirm and summarize the thread, you are running this via Jupyter Notebook in VS Code using the latest version of wandb. 

Is there anything else you have that could be specific to your environment that will help me reproduce this?

**Comment by DbCrWk** [comment]
@ArtsiomWB this is an entire minimum working example from my end :)

I'm running python 3.10.12.

<img width="1190" alt="image" src="https://github.com/user-attachments/assets/fd53cd50-d8f7-49eb-8c1e-4fff2fe7acac">

**Comment by ArtsiomWB** [comment]
Hey @DbCrWk! I think I have been able to reproduce a similar behavior on my end on the latest version of wandb. Looking into this.

**Comment by DbCrWk** [comment]
@ArtsiomWB thanks!

**Comment by ArtsiomWB** [comment]
Hey, @DbCrWk! Thank you for reporting this. It does look like a bug. I have gone ahead and sent this behavior over to our engineering team.

**Comment by DbCrWk** [comment]
> Hey, @DbCrWk! Thank you for reporting this. It does look like a bug. I have gone ahead and sent this behavior over to our engineering team.

Cool, thanks!

**Comment by DbCrWk** [comment]
@dmitryduev thanks a ton! @ArtsiomWB thanks for shepherding!
