### ISSUE TITLE
[Q] How to Plot loss and accuracy 

### ISSUE THREAD

**Issue by MaKaNu** [wandb/wandb#8110]
Whenever we try to Plot our usual loss/accuracy plot we have the issue, that the data is plotted separate.

What we don't want: 
1. We don't want single plots with one line each and we don't want to combine them afterwards on the webplattform. We only want one plot with both lines.
2. We cannot use plot line series, because the table is huge and we don't need the table at all. 
3. We cannot use matplotlib because we want to Plot for thousands of steps and we don't want to create thousands of plots which will all be logged without possibility to delete them.

There are a few "solutions" that doesn't work and this is a feature that every other render engine I know and use supports.

**Comment by vitoria-wandb** [comment]
Hey! Thanks for reaching out! I totally see what you mean. You could go about it in a couple of ways:

- wait for your training loop is done, and then change in the UI (which I know you said it is not your ideal workflow)
- or, wait for the training loop to be done and change how your workspace looks like **programmatically** - which I think is more what you are looking for. The documentation for this can be found [here](https://docs.wandb.ai/tutorials/workspaces#docusaurus_skipToContent_fallback).


Let me know if this was of help, thanks!

**Comment by ArtsiomWB** [comment]
Hi Internal, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
