### ISSUE TITLE
[Q] Is there is a way to upload the summary of offline crashed runs?

### ISSUE THREAD

**Issue by MoH-assan** [wandb/wandb#8114]
Hi 

If an offline run crashes before `wand.finish()` the summary is not uploaded even after triggering sync. 

 Is there a way to upload the summary of such a crashed run? 
 I tried resuming and finishing the crash run, but this didn't fix it. 
 
 Theis https://github.com/wandb/wandb/issues/7227 might be related

**Comment by sydholl** [comment]
Due to inactivity we are closing this request, please comment to reopen.
