### ISSUE TITLE
[App]: `export WANDB_SILENT="true"` isn't being honored 

### ISSUE THREAD

**Issue by vgoklani** [wandb/wandb#8120]
### Current Behavior

"Changes to your `wandb` environment variables will be ignored because your `wandb` session has already started. For more information on how to modify your settings with `wandb.init()` arguments, please refer to [the W&B docs](https://wandb.me/wandb-init)."

### Expected Behavior

pure silence; that means no logging whatsoever

### Environment

OS:

Browsers:

Version:
latest

### Additional Context

I want absolute silence

**Comment by luisbergua** [comment]
Hi @vgoklani, thanks for writing in! Mind sharing your `wandb --version` and a screenshot of the output of the following code?
```
import wandb
import os

os.environ["WANDB_SILENT"] = 'True'

run = wandb.init(project="test_silent")
for step in range(10):
    run.log({"metric": step})
run.finish() 
```
I tried using the latest version and it works as expected

**Comment by luisbergua** [comment]
Hi @vgoklani, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
