### ISSUE TITLE
[App]: Hover over graphs in Workspace cuts off making it difficult to read

### ISSUE THREAD

**Issue by logan-dunbar** [wandb/wandb#8139]
### Current Behavior

When hovering over graphs in the Workspace window the hover popup is cut off making it difficult to read the values of the graphs

### Expected Behavior

I expect that when hovering over the graphs the popup box to be fully displayed so I can see all the values.

### Screenshots

![wandb_error_ui](https://github.com/user-attachments/assets/6b86970d-5289-4e6c-b222-68672b6f0fcf)

### Environment

OS: Ubuntu 22.04

Browsers: Firefox v129.0.1, Chrome v127.0.6533.99

**Comment by logan-dunbar** [comment]
It would also be nice if the hover popup did not block the graph below it, as often I cannot see where I have selected on the graph, as in the below example, where I am hovering in the top right box but cannot see the graphs below the popup:
![Screenshot from 2024-08-15 12-26-35](https://github.com/user-attachments/assets/c97400f0-e3d6-4645-ab8c-435f75b854ac)

**Comment by ArtsiomWB** [comment]
Hi Logan!

Thank you for writing in! I have gone ahead and sent your feedback to our engineering team. Will let you know if I get any updates regarding this

**Comment by logan-dunbar** [comment]
Hi Artsiom,

Not sure if you can access it on the back end, but you can take a look at my thesis workspace?

https://wandb.ai/logan_dunbar/thesis/workspace

I don't have anything public at the moment, but it has happened with all the workspaces I have created so far, so should be easy to replicate.

**Comment by ArtsiomWB** [comment]
Hi @logan-dunbar! Thank you for sending over the link. What browser are you using to replicate this behavior? I do not see the tool tip box being covered up on my side.

**Comment by logan-dunbar** [comment]
Hi @ArtsiomWB I'm using both Firefox and Chrome, and it's happening on both. I've resized the window to be 1388×1486, I've just taken another screenshot and it's still there. It depends where you hover on the graph, if you hover over the eval/mean_ep_length box (top left below) it is fine when the popup box faces to the right, but if you hover over about 8M+ the box shifts to the left and gets cut off:

![Screenshot from 2024-08-27 20-17-16](https://github.com/user-attachments/assets/41a90243-ebbe-4b46-ab82-1ad1e62ff47f)

But you can see in the below screenshot, even when it goes to the right, the other boxes also get cut off (which maybe in this case is desirable, not sure, but at least the primary box should always be visible I think):

![Screenshot from 2024-08-27 20-21-27](https://github.com/user-attachments/assets/b76c1aa3-8363-4851-9cce-13976ed4a482)

**Comment by ArtsiomWB** [comment]
Thank you for the screenshots! I have been able to repro this on my side as well and have reported it as a bug to our engineering team.

**Comment by ArtsiomWB** [comment]
Quick update from our side. The concern regarding tooltips being covered up by the edge of the graph should now be fixed. Thank you for bringing it up!
