### ISSUE TITLE
[CLI]: Filestream rate limit exceeded

### ISSUE THREAD

**Issue by norikazu99** [wandb/wandb#8150]
### Describe the bug

I usually run offline runs and then use wandb sync --sync-all to sync multiple runs. I got this error regarding rate limits.

### Environment

WandB version: 0.17.7

OS: Ubuntu 

Python version: 3.12.4

**Comment by boshwandb** [comment]
Hi @norikazu99. This is a known issue but should be fixed by now. Could you confirm if you are still experiencing this issue?

**Comment by norikazu99** [comment]
Hello, excuse me for the late reply. The issue was resolved.
