### ISSUE TITLE
[Q] Filestream rate limit exceeded and wandb sync is slow

### ISSUE THREAD

**Issue by AndyCao1125** [wandb/wandb#8152]
Hi, I often use wandb online mode without error, but today, I meet the question:"wandb: 429 encountered (Filestream rate limit exceeded, retrying in XX seconds.)" 

I have tried many schemes, but none of them is satisfactory: 
1. First, I tried to change an account, but this problem still exists. 
2. I tried to run the code that could work before (the number of parameters is smaller), but it is still exceeded the limitation. 
3. I tried the method of this issue (https://github.com/wandb/wandb/issues/5445#issuecomment-1540793408) by performing offline first and then syncing the local log, but I found that the sync speed was very slow after a simple test. 

Is there any other solution? Or what are the underlying reasons for this? For example, too many wandb records locally? Too much logged media? 

Since I really like wandb, I don't want to replace it with other tools for the time being. 

I hope you can answer my confusion. Thank you so much!

**Comment by effortprogrammer** [comment]
I am also encountering the same issue, and it seems like wandb community has several posts related with this issue..

**Comment by norikazu99** [comment]
Had the same issue. This seems to be fixed on my side.

**Comment by effortprogrammer** [comment]
> Had the same issue. This seems to be fixed on my side.

How did you fix?

**Comment by paulosabile-wb** [comment]
Hi @norikazu99 @effortprogrammer @AndyCao1125 ,

Good day and thank you for reaching out to us. Happy to help you on this!

We have experienced some issues during the weekend that affected some of our users and this caused the rate limit issues. We have fixed this now and you should be able to continue logging experiments in wandb.

Please do let us know if you are still experiencing issues.


Thanks,
Paulo

**Comment by AndyCao1125** [comment]
Thanks for your help! It's fixed now.
