### ISSUE TITLE
[App]: Wrongly Displayed Group Maximum Values in Wandb Web APP

### ISSUE THREAD

**Issue by Josh00-Lu** [wandb/wandb#8154]
### Current Behavior

Dear Wandb Support Team,

I hope this message finds you well.

I am currently encountering an issue with the grouping and data display functionality on Wandb. I have grouped my runs under the group and attempted to view the maximum ‘Mean Reward’ value using the ‘Show max’ setting. However, the displayed value does not reflect the highest ‘Mean Reward’ within the group, as evident from the screenshots.

For instance, while the highest ‘Mean Reward’ in my group is 94.51, the value shown (93.984) as the maximum is different and does not match any of the actual maximum values from the individual runs. I have attached screenshots for your reference.

Could you please assist me in resolving this discrepancy? I rely on accurate metrics display for my experiments, and this issue is impacting my workflow.

Thank you for your assistance.

Best regards,
Josh

### Expected Behavior

Should display with the max value of each group

### Steps To Reproduce

1. Go to runs
2. Select one column -> show max -> max 

### Screenshots

<img width="822" alt="截屏2024-08-20 07 38 01" src="https://github.com/user-attachments/assets/b08ee81d-b16d-4dfe-a7fd-fab03eb2abe1">

<img width="524" alt="截屏2024-08-20 07 37 42" src="https://github.com/user-attachments/assets/35e0b6d1-d96a-44b2-917c-624e6e564d1d">

### Environment

OS: MacOS 14.6.1

Browsers: Edge

Version: Latest (127.0.2651.105)

**Comment by JoanaMarieL** [comment]
Hello @Josh00-Lu ,

Thank you for writing in and happy to help. Could you please provide the following to further investigate:

-Code Snippet, config for your Mean Reward column
-Workspace link if share-able you may also send it to our wandb Support Email (support@wandb.com) and mention this Github issue link

**Comment by JoanaMarieL** [comment]
Hi @Josh00-Lu , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
