### ISSUE TITLE
[Q] Using the early_terminate option, how to early terminate if the ELBO plateaus for more than 5 epochs ?

### ISSUE THREAD

**Issue by aymeric75** [wandb/wandb#8158]
Hello,

I have hard time understanding how to use the _early_terminate_ option

Doc [here](https://docs.wandb.ai/guides/sweeps/sweep-config-keys)

I tried the following in order to tell "stop the run after the 200th epoch if the Elbo plateaus
```
            "method": "bayes",
            "metric": {
                "goal": "minimize",
                "name": "elbo"
            },
            "early_terminate": {
                "type": "hyperband",
                "min_iter": 200,
            },
```

But it does not work (it continues running)

Any help 

Thanks

**Comment by paulosabile-wb** [comment]
Hi @aymeric75 Good day. Happy to help here.

The bayes method is designed to work with at least some parameters having a range (and distribution) so the search space shouldn't have a finite number of combination of parameters, making the repetition highly unlikely and it is expected that it would run forever unless stopped.

The `min_iter/max_iter` are [based in terms of iterations](https://docs.wandb.ai/guides/sweeps/define-sweep-configuration#hyperband). Let me review this for a while and I will get back to you for a workaround here.

**Comment by paulosabile-wb** [comment]
Hi @aymeric75 , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
