### ISSUE TITLE
Numpy 2.1 deprecation warnings with `.reshape`

### ISSUE THREAD

**Issue by phinate** [wandb/wandb#8166]
The `newshape` parameter, used in `wandb.Video` here

https://github.com/wandb/wandb/blob/ad115b8d2d17d9f738c1a9e7e069e81e1aac0eab/wandb/sdk/data_types/video.py#L217-L219

is deprecated as of NumPy 2.1.

**Comment by ArtsiomWB** [comment]
Hi! Thank you for writing in!

What version of SDK are you running into this? Looks like it's the latest, right? What does the warning look like on your side?
