### ISSUE TITLE
[Q]wandb: Network error (ConnectTimeout), entering retry loop.

### ISSUE THREAD

**Issue by kekekeke8** [wandb/wandb#8228]
wandb: W&B API key is configured (use `wandb login --relogin` to force relogin)
wandb: Network error (ConnectTimeout), entering retry loop.
wandb: Network error (ConnectTimeout), entering retry loop.
wandb: Network error (ConnectTimeout), entering retry loop.
wandb: Network error (ConnectTimeout), entering retry loop.

several days before, it works well, but recently it always fail even if try possible solution from network. Can anyone help?

**Comment by kptkin** [comment]
This is a transient error, due to network issues on your system, it should be resolved once you connection is improved.

**Comment by hislordshipprof** [comment]
facing similar issues 
i'm using wandb==0.16.5 but it keeps giving this error
wandb: Network error (JSONDecodeError), entering retry loop.

i did check my network to confirm if theres any proxy blocking it but theres no proxy setup

**Comment by fmamberti-wandb** [comment]
Hi @hislordshipprof, thanks for reaching out with your issue - to help us troubleshoot would you mind sharing

- the `debug.log` and `debug-internal.log` from the `./wandb/run-<date_time>-<run_id>/logs folder
- the full stack error 
- a code snippet of the code you are running

Thanks!

**Comment by fmamberti-wandb** [comment]
Hi @hislordshipprof , I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by hislordshipprof** [comment]
Thank you. I resolved it my network url saved in the.netrc file wasn't
pointing to the correct path

**Comment by fmamberti-wandb** [comment]
That's great to hear. Thank you for letting us know - I will close this now, please don't hesitate to reach out for any further questions in the future
