### ISSUE TITLE
[Bug]: "finish" is not a known attribute of module "wandb" in 0.17.8

### ISSUE THREAD

**Issue by chanind** [wandb/wandb#8248]
### Describe the bug

On wandb 0.17.8, Pyright reports that `"finish" is not a known attribute of module "wandb"`. It also reports a similar error for `"log_artifact" is not a known attribute of module "wandb"`. This does not happen on 0.17.7 and earlier. This also affects vscode, as it reports that `wandb.finish()` and `wandb.log_artifact()` don't exist as well.

After some investigation, it seems that this is due to the new `__init__.pyi` file from #8103. Deleting this file causes these typing errors to disappear. The `__init__.pyi` file makes no mention of `wand.finish()` or `wandb.log_artifact()`, so it's natural that Pyright will think these methods don't exist.

It also looks like `finish()` and `log_artifact()` are not included in `__all__` in `__init__.py`, likely as an accident, so I'm actually surprised that Python was allowing these functions to be imported from the main `wandb` module to begin with.

**Comment by kptkin** [comment]
@chanind Thanks a lot for reporting this issue, it is an accidental mistake on our part, we will be fixing it for the upcoming release! appreciate your useful and detailed report!
