### ISSUE TITLE
How to use Tables to log generated text?

### ISSUE THREAD

**Issue by vgoklani** [wandb/wandb#8249]
During the validation portion of our training loop, we would like to store generated-text in a wandb table, but are confused about how this is supposed to work.

```python
run = wandb.init(...)

table = wandb.Table(columns=["step", "generated_eval_text"])

def log(metrics: dict, step: int, generated_eval_text: Optional[str] = None):
    data = {k: v for k, v in metrics.items() if isinstance(v, (int, float))}

    if generated_eval_text is not None:
        table.add_data(str(step), generated_eval_text)
        data["generated_eval_text"] = table

    run.log(data=data, step=step)
```

Here is a cross-section of our approach, but unfortunately this is not working. We see multiple tables showing up labeled "generated_eval_text" each with one row on the dashboard. 

1. Are we supposed to log the full table on every table update? Can we just send the new row?
2. Is our approach correct, or are we doing something fundamentally wrong?

Thanks!

**Comment by vgoklani** [comment]
Thanks for the response!

We would prefer to have one single table and then just add rows every so often. This way we can periodically check the dashboard to see the quality of the generated text.

It sounds like you're saying that we can't do that. Each time we do a `run.log({"generated_eval_text": table})` we are pushing a new table object to the dashboard.

Is my interpretation correct? Is there for us to monitor the evolution of the generated text on single table as the model is training? 

Thanks!

**Comment by vgoklani** [comment]
<bump>

**Comment by C-J-Cundy** [comment]
You can use the solutions here: 
https://github.com/wandb/wandb/issues/2981
