### ISSUE TITLE
[Bug]: discrepancy in NaN values from API histories vs web

### ISSUE THREAD

**Issue by modanesh** [wandb/wandb#8252]
### Describe the bug

I logged a lot of experiments on WandB, and unfortunately I don't have access to the local files in the `wandb` folder. So I have to download them using the API for further processing. I wrote this code to do it for me:

```python
import wandb
import time
import pandas as pd
from wandb.apis.public import Api
from requests.exceptions import HTTPError

api = Api()

def fetch_run_history(run, max_retries=5, backoff_factor=1):
    for attempt in range(max_retries):
        try:
            return run.history()
        except HTTPError as e:
            if e.response.status_code == 429:
                # Too many requests, wait before retrying
                wait = backoff_factor * (2 ** attempt)
                print(f"Rate limit exceeded. Retrying in {wait} seconds…")
                time.sleep(wait)
            else:
                raise e
    raise Exception("Max retries exceeded")

def fetch_all_histories(project_name, max_retries=5, backoff_factor=1, batch_size=100):
    runs = api.runs(project_name)
    histories = []
    for i in range(0, len(runs), batch_size):
        batch = runs[i:i + batch_size]
        for run in batch:
            try:
                history = fetch_run_history(run, max_retries, backoff_factor)
                histories.append((run.name, history))
            except Exception as e:
                print(f"Failed to fetch history for run {run.name}: {e}")
    return histories

# Fetch all histories for the project
project_name = "UARL"
histories = fetch_all_histories(project_name)

# Combine histories into a single DataFrame
combined_histories = []
for run_name, history in histories:
    history['run_name'] = run_name
    combined_histories.append(history)

df_combined = pd.concat(combined_histories, ignore_index=True)

# Save to CSV or handle as needed
df_combined.to_csv("combined_histories.csv", index=False)
```

In these downloaded runs, all of them has an attribute of "eval/mean_reward" which I recorded as `NaN`. However, the plot corresponding to this value shows meaningful numbers. Below is a screenshot of a plot from an experiment:

![image](https://github.com/user-attachments/assets/df87b6a4-8966-48e6-8361-5cd4e5692cc6)

And these are values from the downloaded histories:

```
[NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
NaN
128.736565
NaN
NaN
NaN
...
]
```

I'm wondering what's the reason for this discrepancy?

Thanks.

**Comment by modanesh** [comment]
Was able to resolve it with `scan_history()` method instead of the `history()`. Thus closing the issue.

**Comment by fdsig** [comment]
Hey @modanesh Thanks so much for sharing your learning and confirming that you found a solution as this does help future readers/ members of wandb ML community. 

For completeness [here ](https://docs.wandb.ai/guides/track/public-api-guide#sampling) is a relevant section in our docs .

As you've marked close will consider this resolved but please do reach out for anything you need assistance with wandb related now or in the future.
