### ISSUE TITLE
[Q]: wandb: WARNING Disabling the wandb service is deprecated as of version 0.18.0 and will be removed in version 0.19.0.

### ISSUE THREAD

**Issue by 39c5bb-miku** [wandb/wandb#8278]
### Ask your question

When I use the 0.17.8 version, "wandb: WARNING Disabling the wandb service is deprecated as of version 0.18.0 and will be removed in version 0.19.0.", should I use "os.environ.setdefault (" WANDB_MODE "," disabled "if not config.wandb" else offline ") ", what code should I use to implement this feature after this feature is discarded

**Comment by ArtsiomWB** [comment]
Hi @39c5bb-miku! thank you for writing in. 

could you please talk a but about your workflow and why you are interested in disabling wandb service?

**Comment by wcarvalho** [comment]
I also have this. When debugging, I want to disable WANDB.

**Comment by zzccppp** [comment]
Also have this warning, actually I have a if statement when debugging, it will disable the wandb service:

`if "debugpy" in sys.modules:
    print("Debugger detected, disable wandb")
    wandb.init(project=config["wandb_project"], config=config, mode="disabled")
else:
    wandb.init(
        project=config["wandb_project"],
        config=config,
    )`

**Comment by kptkin** [comment]
@zzccppp @wcarvalho  sorry it is a small bug we introduced, should be fixed in the next release.

**Comment by kptkin** [comment]
@zzccppp @wcarvalho @39c5bb-miku just to let you know, wandb is indeed disabled, the fact that you see the warning message is just a bug in our condition to print it but wandb won't be doing anything, we will fix it so the message won't show up.

**Comment by 39c5bb-miku** [comment]
@kptkin Thank you for your response.

**Comment by datalee** [comment]
`Using the `WANDB_DISABLED` environment variable is deprecated and will be removed in v5.`？with 0.18.1，how to use environment variable？

**Comment by RemyLau** [comment]
Any solution for this yet?

**Comment by ArtsiomWB** [comment]
Hey @datalee, Thank you for the follow-up. You can still use the environment variable as needed. The warning is false. Our sdk team is still working on a fix. We'll let you know when it gets resolved.
