### ISSUE TITLE
[Bug-App]: Cannot read properties of undefined (reading 'type')

### ISSUE THREAD

**Issue by ZL0308** [wandb/wandb#8281]
### Describe the bug

It happened after creating a new project. 
![screenshot](https://github.com/user-attachments/assets/295c6aaa-5223-4692-a613-f40d4965b40d)

**Comment by ArtsiomWB** [comment]
Hi @ZL0308  thank you for bringing this up. It looks like this behavior is affecting multiple wandb users. We have notified our engineering team about this and they are currently looking into this concern. Thank you for bringing it up.

**Comment by ArtsiomWB** [comment]
Hi!

This behavior should be resolved now.

Thank you for bringing it up!
Let us know if you are seeing this behavior again.
