### ISSUE TITLE
[Bug-App]: Cannot read properties of undefined (reading 'type') when creating project

### ISSUE THREAD

**Issue by Zafirmk** [wandb/wandb#8282]
### Describe the bug

# Current Behaviour
Error pops up after creating a new project. Can not access new project but is still visible in the projects tab.

# Screenshot
<img width="652" alt="Screenshot 2024-09-05 at 12 40 21 PM" src="https://github.com/user-attachments/assets/7292d3bd-04ac-4c6c-bb82-06b8590cd1b3">

# Environment
OS: MacOs

Browsers: Chrome

**Comment by ArtsiomWB** [comment]
Hi @Zafirmk thank you for brining this up. This behavior is affecting multiple wandb users. We have notified our engineering team about this and they are currently looking into this concern. Thank you for bringing it up.

**Comment by ArtsiomWB** [comment]
Hi!

This behavior should be resolved

Thank you for bringing it up!
Let us know if you are seeing this behavior again.
