### ISSUE TITLE
[Bug]: Internal server error when loading run history with api

### ISSUE THREAD

**Issue by smspillaz** [wandb/wandb#8291]
### Describe the bug

WandB client version 0.17.9

I get an internal server error when trying to load a run's history, for example:

```
import wandb
import pprint

api = wandb.Api()
projects = [
    p.name for p in api.projects(entity='entity')
]
project_runs = {
    p: [
        r for r in api.runs(path=f"entity/{p}", per_page=500)
    ]
    for p in projects
}
for p, runs in project_runs.items():
    print(p)
    for run in runs:
        print(f"Loading run {run.entity}/{run.project}/{run.id}")
        history = run.history(samples=run.lastHistoryStep + 1)
        system = run.history(samples=run.lastHistoryStep + 1, stream="system")
        history = history.join(system, rsuffix="_system")
        files = run.files()

        import sys
        sys.exit()

```

This throws an internal server error

```
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql
```

**Comment by smspillaz** [comment]
The error happens on `run.history(samples=run.lastHistoryStep + 1)`

I'm trying to export all my runs from all my projects and move them into a single project (not shown here).

**Comment by fmamberti-wandb** [comment]
Hi @smspillaz , thanks for sharing your use case.

If you are trying to move all the Runs from one project to another, the quickest way would be to select them from the Runs Table and use the Move option to move them across
<img width="498" alt="Screenshot 2024-09-16 at 17 45 23" src="https://github.com/user-attachments/assets/c6762569-9d97-4e24-89dd-4af1389bbbc4">

Would that work for you or do you need to do this programmatically?

**Comment by fmamberti-wandb** [comment]
Hi @smspillaz , I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by fmamberti-wandb** [comment]
Hi @smspillaz , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
