### ISSUE TITLE
[Q]: Why I cannot connect the wandb? with CommError: It appears that you do not have permission to access the requested resource. 

### ISSUE THREAD

**Issue by falconlee236** [wandb/wandb#8342]
### Ask your question

I connect wandb in colab env.
but When I call wandb.init(), then that error occured
<img width="1301" alt="image" src="https://github.com/user-attachments/assets/dc239f52-14f1-4198-a6a5-b61ad9ab0648">

how can i fixed it?
'ps'
I installed `wandb==0.17.9` version
* my account email is `falconlee236@gmail.com`

**Comment by paulosabile-wb** [comment]
Hi @falconlee236 Good day and thank you for reaching out to us. Happy to help you on this!

Can you try to specify the `entity `on your `wandb.init` call? Let me know if this allows you to log your experiment.

**Comment by falconlee236** [comment]
> Hi @falconlee236 Good day and thank you for reaching out to us. Happy to help you on this!
> 
> Can you try to specify the `entity `on your `wandb.init` call? Let me know if this allows you to log your experiment.

![image](https://github.com/user-attachments/assets/2931ce88-fe87-4e00-8a5b-438a661b358e)

the wandb.init() method in colab is always specifiy `entity`, `mode`, `project`, `name` parameters

```python
#Comment following two lines if you don't want logging
from lightning.pytorch.loggers import WandbLogger

run = wandb.init(
    entity="OptiMap",
    mode="online",
    project="test",
    name="advrp-cv"
)

logger = WandbLogger()
```

but almost tutorial of wandb with colab env is only use `init` function without other parameters.

I was so confused of that parameters was optional parameters anyway.

Do you change that parameters not optional parameter?   
Or I gonna change that parameters necessary
@paulosabile-wb

**Comment by falconlee236** [comment]
Hi! @paulosabile-wb , @kptkin 

Can I change     `project`, `enttiy`, `mode` parameters in python api?
and also [this api docs](https://docs.wandb.ai/ref/python/init) change too.


If you approved. i gonna change my modification.

```python
def init(
    job_type: Optional[str] = None,
    dir: Optional[StrPath] = None,
    config: Union[Dict, str, None] = None,
    project: str = None, # changed
    entity: str = None, # changed
    reinit: Optional[bool] = None,
    tags: Optional[Sequence] = None,
    group: Optional[str] = None,
    name: Optional[str] = None,
    notes: Optional[str] = None,
    magic: Optional[Union[dict, str, bool]] = None,
    config_exclude_keys: Optional[List[str]] = None,
    config_include_keys: Optional[List[str]] = None,
    anonymous: Optional[str] = None,
    mode: str = "online", # changed -> default is online in api docs.
    allow_val_change: Optional[bool] = None,
    resume: Optional[Union[bool, str]] = None,
    force: Optional[bool] = None,
    tensorboard: Optional[bool] = None,  # alias for sync_tensorboard
    sync_tensorboard: Optional[bool] = None,
    monitor_gym: Optional[bool] = None,
    save_code: Optional[bool] = None,
    id: Optional[str] = None,
    fork_from: Optional[str] = None,
    resume_from: Optional[str] = None,
    settings: Union[Settings, Dict[str, Any], None] = None,
) -> Run:
```

https://github.com/wandb/wandb/blob/v0.18.0/wandb/sdk/wandb_init.py#L979-L1249

**Comment by paulosabile-wb** [comment]
Hi @falconlee236 Good day and thanks for your follow up suggestions here.

Upon checking in Collab, if you try to run `wandb.init` without the `entity `parameter, it should trigger `wandb.login` and you will be asked to enter your API key so you can proceed. The API key should allow the wandb service to identify which entity is this run for and this should prevent you from getting any permission errors.

When you tried to run your experiment using Collab, did you try to run `wandb.login` before executing `wandb.init`? I'd like to confirm as well which collab tutorial are you using so I can also review, if you can share a URL that can help me review the setup.

Thank you!

**Comment by falconlee236** [comment]
Hi @paulosabile-wb .
After your commented, The problem was absolutely resolved. How to fix the bug? What kind of the PR you uploaded concerning this Issue? 

If you don't change about this code. You should close this issue. 

__This situation was so wired..__
