### ISSUE TITLE
[Q]: Details on run forking

### ISSUE THREAD

**Issue by collinmccarthy** [wandb/wandb#8353]
### Ask your question

Hi, I have a use case for run forking but I want to make sure I understand a few details that I don't see (or missed) from the documentation.

I trained a model for 30 epochs and stopped it. Now I want to duplicate that run (fork it) for a new run, and then go on continuing the original run. 

Before forking the run, I manually duplicated the local directory that contains all the run files and the wandb folder after 30 epochs. So locally the run is "duplicated". Now I initialize the new run as shown in the docs, but adding `name`, `dir` and `resume` as follows. 

```python
wandb.init(
    project="your_project_name",
    entity="your_entity_name",
    fork_from=f"{original_run.id}?_step=200",
    name="new_run_name",
    dir="new_run_dir_I_duplicated_manually",
    resume="auto",  # Use `wandb-resume.json`
)
```

Now for a few important questions.

1. After both runs are finished training, are they both _completely_ independent, full runs, in terms of the UI and python API? e.g. I can delete the first run without messing up the second, I can use the API to get the history or delete files or delete artifacts, etc., so I really can't tell that the run was forked without digging into the internals? I don't want to find out a month from now that when I used this feature the forked run doesn't support X or Y, or I couldn't delete the first run or something.

2. How is this going to work with `resume="auto"`? Do I need to delete `wandb-resume.json` in the new directory so the old run ID isn't used? And if an hour later the run gets preempted, and initializes in the exact same way, is the run forked again (bad) or is `wandb-resume.json` used to resume from the already-forked run (good)?

3. Is there a better way to do what I'm trying to do, if this is more complicated than the feature supports right now?

Thank you,
-Collin

**Comment by ArtsiomWB** [comment]
Hi Collin,

Thank you for reaching out. To ensure we're on the same page, I want to clarify your request.

It sounds like you're interested in starting a run for 10 steps. After completing those 10 steps, you want to split the experiment into two separate runs:

The first would continue the original algorithm by resuming the experiment from step 11.
The second would start at step 11, but use a different algorithm and behavior, with steps 0-10 as the baseline from the original run.
Is that correct? Please let me know if I’ve understood your request correctly.

**Comment by collinmccarthy** [comment]
Yes that is correct. The goal at the end is to have two independent runs (files, logs, etc.). The way I achieve this is (following your example).

- Train the first run (`run-1`) for 10 steps, and stop it
- Duplicate the folder, and re-name it to `run-2`
- Fork the first run, specifying the `run-2` dir as the new forked output dir
- Resume training `run-1` and `run-2`, while changing the config / launch args for run-2
  - To do this, I use `resume="auto"` for both runs

My attempt at forking using both `resume` and `fork_from` didn't work (the API doesn't support it, which makes sense because it's not clear which has priority in what circumstances). So I wrote a script to fork the run, then setup the forked run so it can be resumed with "auto". The script is [here](https://github.com/collinmccarthy/wandb-scripts/blob/main/wandb_fork.py) but I haven't finished testing it because I don't have forking enabled on my account. I emailed support yesterday but haven't heard back yet. 

Do I have to manually create the `wandb-resume.json` file if to resume training from step 11 in our example, for the forked `run-2`?

**Comment by collinmccarthy** [comment]
I just ran into an unrelated issue where one of my runs failed to upload some data, so I had to use `wandb sync`. How would using `wandb sync` work with a forked run?

**Comment by ArtsiomWB** [comment]
What I would recommend doing here is first to run your run in offline mode for example like this:
```py
import wandb

run = wandb.init(project="free-gh-splitting", mode="offline")
for i in range(10):
    run.log({"test":i})
run.finish()
```

then to fork it sync this run once with one id, and the second time with another id as such:
`wandb sync /Users/artsiomskarakhod/Documents/tests2/free_gh/wandb/offline-run-20240917_122158-qfpk752f --id run1`
`wandb sync /Users/artsiomskarakhod/Documents/tests2/free_gh/wandb/offline-run-20240917_122158-qfpk752f --id run2`
Now you have 2 different runs with the same data log to wandb:
<img width="761" alt="image" src="https://github.com/user-attachments/assets/eac635ae-23b7-4a06-b83b-716ba5c020ff">


From there, resume the first run and do the necessary training on it with wandb.initing your run as such:
`run = wandb.init(project="free-gh-splitting", id="run1", resume="must")`

and then do the same for the second run to add the necesarry data:
`run = wandb.init(project="free-gh-splitting", id="run2", resume="must")`

After resuming them, you will have two runs with the same beginnings but different ends:
<img width="763" alt="image" src="https://github.com/user-attachments/assets/dfcc9fc4-5b45-41dc-b062-abaf5f10dac6">

**Comment by collinmccarthy** [comment]
@ArtsiomWB Awesome thank you! I'm still waiting on support to enable run forking for my account then I'll try it out and update / close the issue.

**Comment by ArtsiomWB** [comment]
Totally, Always happy to help, @collinmccarthy! The workflow above is possible without enabling any kind of setting from our side. You just need to create an offline run, sync it twice with different run ids and then resume those runs with the changes you wanted to apply to the run

**Comment by collinmccarthy** [comment]
Ohhh @ArtsiomWB that's a great solution then, would eliminate any potential issues related to the forking mechanism. Thanks again!

(Closing the issue because I don't plan on coming back to this for a while)

**Comment by collinmccarthy** [comment]
@ArtsiomWB I'm back exactly one year later (weird) needing a solution to the same problem. My colleague has trained a model, and I want to continue training it on a different cluster, with the full run history intact. If I copy everything over and restart the same run, I get a permission error. If I try to sync with a new wandb id, it doesn't work, I assume because it wasn't logged in offline mode. I can write a script to generate a new wandb id, pull the full history, and re-log everything but I'm not even sure that can be done to produce the exact same history state (I haven't stepped through this in enough detail to be sure).

I know I could just continue logging to a new wandb id without the old run history but I'd really like a way to sync the run even if it was logged normally, just with a new wandb id. Is that possible or no?
