### ISSUE TITLE
[Bug]: Warning when import wandb

### ISSUE THREAD

**Issue by thinh-dao** [wandb/wandb#8358]
### Describe the bug

Hello wandb team, I'm reporting a warning when I import the latest version of wandb: `SentryHubDeprecationWarning: 'sentry_sdk.Hub' is deprecated and will be removed in a future major release. Please consult our 1.x to 2.x migration guide for details on how to migrate `Hub` usage to the new API: https://docs.sentry.io/platforms/python/migration/1.x-to-2.x
  self.hub = sentry_sdk.Hub(client)`

**Comment by ArtsiomWB** [comment]
Hey @Ducthinh19102003! Thank you for writing in!

Looking at the warning above, it does not seem to be [coming from wandb](https://getsentry.github.io/sentry-python/_modules/sentry_sdk/hub.html). 

Are you seeing this warning on `0.18.0` every time you import wandb?

Do you use [sentry-python](https://getsentry.github.io/sentry-python/index.html), in your current code?

**Comment by ArtsiomWB** [comment]
Hi @Ducthinh19102003! I have reported this behavior to our engineering team. Thank you for bringing it up!

**Comment by anmolmann** [comment]
HI @thinh-dao , quick update on this - a fix for this issue has been merged by our team and this fix will be included in our [next SDK release](https://github.com/wandb/wandb/releases).
