### ISSUE TITLE
[Bug]: nvidia_gpu_stats binary causes high CPU cycle usage.                   

### ISSUE THREAD

**Issue by mgharbi** [wandb/wandb#8359]
### Describe the bug

Using the new backend with:

```
import wandb
wandb.require("core")
```

WandB spawns a `nvidia_gpu_stats` process that has a very high CPU usage. This should not happen!

Launching an 8GPU  job and running `top` shows the following:

```
Tasks:  58 total,   1 running,  57 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.6 us,  3.6 sy,  0.0 ni, 95.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem : 1886814.+total, 1015482.+free,  17659.7 used, 853672.1 buff/cache
top - 10:38:28 up 43 days, 22:19,  2 users,  load average: 24.18, 26.19, 21.18
Tasks: 281 total,   1 running, 280 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.3 us, 29.1 sy,  0.9 ni, 69.5 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 st
MiB Mem : 1886814.+total, 931970.9 free,  39175.9 used, 915667.9 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used. 1775770.+avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                               
 711417 root      35  15 6721488 377724   6784 S  5907   0.0  11:15.03 nvidia_gpu_stat                                                                                       
 709541 root      35  15  295.4g   8.8g   8.0g S  42.4   0.5   0:12.62 ray::_RayTrainW                                                                                       
 709539 root      35  15  295.4g   8.8g   8.0g S  37.7   0.5   0:12.60 ray::_RayTrainW                                                                                       
 709532 root      35  15  295.5g   8.8g   8.0g S  34.8   0.5   0:12.41 ray::_RayTrainW                                                                                       
 709529 root      35  15  296.0g   8.8g   8.0g S  34.1   0.5   0:13.55 ray::_RayTrainW                                                                                       
 709538 root      35  15  295.4g   8.8g   8.0g S  32.8   0.5   0:12.44 ray::_RayTrainW                                                                                       
 709534 root      35  15  295.5g   8.8g   8.0g S  32.1   0.5   0:12.43 ray::_RayTrainW                                                                                       
 709535 root      35  15  295.5g   8.8g   8.0g S  31.1   0.5   0:11.86 ray::_RayTrainW                                                                                       
 709533 root      35  15  295.5g   8.8g   8.0g S  30.1   0.5   0:12.34 ray::_RayTrainW  
 ```
 
 
I can reproduce that without even import wandb, e.g.:

```
watch /opt/conda/lib/python3.10/site-packages/wandb/bin/nvidia_gpu_stats 
```

**Comment by ArtsiomWB** [comment]
Hi @mgharbi! Thank you for writing in. What version of wandb are you currently running on your machine? 

What OS are you running on your machine as well?

**Comment by vgoklani** [comment]
same issue here, i am on 0.18.0

How do I disable all GPU stats, i don't want this thing pinging my GPU. Just track the model metrics that are explicitly specified, nothing more.

**Comment by ArtsiomWB** [comment]
Hey @vgoklani! Thank you for the follow-up. I escalated the issue to our SDK team yesterday. This is a bug and they are currently taking a look into any potential resolutions to this concern.

**Comment by vgoklani** [comment]
Thanks @ArtsiomWB more generally, how do I stop logging gpu stats? We log what we need manually, so we don't want additional overhead. thanks

**Comment by ArtsiomWB** [comment]
Totally!
Could you try setting your wandb setting `_disable_stats=True` inside of `wandb.init()` as such:
`wandb.init(settings=wandb.Settings(_disable_stats=True))`

This will turn off system metrics logging.

**Comment by jeromerony** [comment]
Hi,
I am observing the same issue with version 0.18.0 on a 8xH100 with CPU usage in the 12000%.
This should be a priority.
Thanks!

**Comment by WiserZhou** [comment]
I am observing the same issue with the RTX 3090 and wandb version 0.18.1. Just like @ArtsiomWB said, this method would be useful!
`wandb.init(project=project_name, name=wandb_name, config=args, settings=wandb.Settings(_disable_stats=True)) `

**Comment by ashleys0** [comment]
Hi, it seems like I'm seeing a similar issue. ```wandb, version 0.18.1```
with A6000s, each experiment creates a nvidia_gpu_stat that takes up 500-1500% CPU. 


Does ``` wandb.init(settings=wandb.Settings(_disable_stats=True)) ``` only affect logging of GPU/hardware stats? I only care about logging things like loss and validation metrics, so I could always use 'disable stats,' regardless of the bug fix. Well, I guess unless it uses like 5% CPU after a fix.

**Comment by dongzhuoyao** [comment]
Can you fix this asap? it's a serious bug

**Comment by dmitryduev** [comment]
@ashleys0 @dongzhuoyao could you please update to 0.18.5 and see if that fixes it for you?
