### ISSUE TITLE
[Bug]: Deprecation warning for sentry_sdk.Hub

### ISSUE THREAD

**Issue by olly-writes-code** [wandb/wandb#8361]
### Describe the bug

Hi! 

Deprecation warning detailed below.

```
/venv/lib/python3.11/site-packages/wandb/analytics/sentry.py:90: SentryHubDeprecationWarning: `sentry_sdk.Hub` is deprecated and will be removed in a future major release. Please consult our 1.x to 2.x migration guide for details on how to migrate `Hub` usage to the new API: https://docs.sentry.io/platforms/python/migration/1.x-to-2.x
    self.hub = sentry_sdk.Hub(client)
```

Thank you!! 🙏

**Comment by kptkin** [comment]
@olly-writes-code thanks for reporting this issue, we will fix it!

**Comment by olly-writes-code** [comment]
Thanks!! :)

**Comment by ArtsiomWB** [comment]
Hi @olly-writes-code! To repro the warning above, could you please give us a toy code example? For some reason I am not seeing the warning on my end.

**Comment by olly-writes-code** [comment]
Hi @ArtsiomWB. Thanks for helping out!

I can confirm that the sentry dependency is out of date. In the wandb pyproject.toml it's at v1 https://github.com/wandb/wandb/blob/main/pyproject.toml#L18 

but the latest version is 2.14.0 (see [pypi](https://pypi.org/project/sentry-sdk/))

Sentry has details on migrating [here](https://docs.sentry.io/platforms/python/migration/1.x-to-2.x)

I get the error whenever I run my test suite. I can investigate to repro, but IMO the warning is correct and the resolution is clear if upgrading is possible.

**Comment by ArtsiomWB** [comment]
This is super helpful, thank you for sending it over!

I have sent the feedback to our eng team. 

I will let you know if we have any follow-up questions for you regarding this concern!
