### ISSUE TITLE
[Q]: What happened to std/min/max shaded areas in run workspace figures and line plots?

### ISSUE THREAD

**Issue by bebark** [wandb/wandb#8370]
What happened to the configurable option in a metric's panel (under the grouping tab I believe) for setting min/max or std as the shaded region of a figure? As far as I can tell it is now only available in the workspace setting and you can only set the shaded area to be min/max values.

**Comment by fmamberti-wandb** [comment]
Hi @bebark , thank you for reaching out with your question. 

Currently, setting other aggregate metrics in a line plot is only available in 'Random Sampling' for Point aggregation method.

For your charts, if you select it in the data tab:
<img width="1790" alt="Screenshot 2024-09-13 at 16 11 47" src="https://github.com/user-attachments/assets/f8002015-08c0-4424-abbd-0848aa5dff5d">

You can also change the default setting for this in the Workspace settings, in the Runs panel.

You should then be able to select the aggregate metrics for shadowing when grouping runs:

<img width="1805" alt="Screenshot 2024-09-13 at 16 16 31" src="https://github.com/user-attachments/assets/35659a22-d0e7-4b3f-85ca-7acfe3608e30">

We also have some documentation for Point Aggregation [here](https://docs.wandb.ai/guides/app/features/panels/line-plot/sampling). Please keep in mind that Full Fidelity in an actively developing feature so both docs and functionality are often updated.

Let me know if you have any further questions on this.
