### ISSUE TITLE
[Q]: Editing Tags when uploading tensorboard data with `wandb sync`

### ISSUE THREAD

**Issue by gokul-uf** [wandb/wandb#8372]
### Ask your question

Hi folks,
I have a tensorboard summaries folder containing several `tfevent` files that I want to upload to my wandb instance. 

The tags look like `<eval_set>/<eval_metric>`.  For example, `imagenet/accuracy@1`. 

I want to somehow edit these tags to look like `eval/<eval_set>/<eval_metric>`. I don't see this option in the `wandb sync` command nor on the website.

Is it possible to do what I'm trying?

Thanks!

**Comment by fmamberti-wandb** [comment]
Hi @gokul-uf , thank you for reaching out with your question. Do you have these files synced already on a project that you can share with us so we can have a look and provide further guidance?

**Comment by fmamberti-wandb** [comment]
Hi @gokul-uf , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
