### ISSUE TITLE
[Q]: Encountered permission denied (<Response [403]>) when calling wandb sync.

### ISSUE THREAD

**Issue by kevincheng7** [wandb/wandb#8382]
### Ask your question

Hi,
After I finished training using wandb's offline mode on a slurm cluster, I tried uploading the training results to the wandb cloud.

First I login using
`wandb login --relogin`
Then I ran
`wandb sync ./results/wandb/offline-run-20240905_202516-98664 --id 98664`

But this gave me the following error
`Find logs at: /tmp/debug-cli.2201111701.log`
`wandb: ERROR Error while calling W&B API: permission denied (<Response [403]>)`
`Syncing: https://wandb.ai/1971225082/<name_of_my_project>/runs/98664 ... done.`

I checked the `/tmp/debug-cli.2201111701.log` and it shows

`2024-09-14 11:33:39 INFO open for scan: /gpfs/share/home/2201111701/Kaiwencheng/MDdyffusion/results/wandb/offline-run-20240905_202516-98664/run-98664.wandb`
`2024-09-14 11:33:40 ERROR 403 response executing GraphQL.`
`2024-09-14 11:33:40 ERROR {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}`
`2024-09-14 11:33:40 ERROR It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)`

How to solve this question?

**Comment by Rashfu** [comment]
same problem here

**Comment by fmamberti-wandb** [comment]
Hi @kevincheng7, thank you for reaching out and sorry to hear you are experiencing this issue. Looking at the logs you shared, it seems that is trying to log to `1971225082` Entity, which doesn't exist. 

Do you have the `WANDB_ENTITY` environment variable set to it by any chance? 

Would you mind either setting WANDB_ENTITY = 'your_team_name' (You can find this under your user settings under default team) or when syncing add `-e <your_team_name>` to your sync command?

This should ensure you are logging against an entity you have access to.

**Comment by yannlabbe** [comment]
Had the same problem, changing the default team in the user profile worked. Thanks!

**Comment by fmamberti-wandb** [comment]
Hi @kevincheng7 , I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.
