### ISSUE TITLE
[Q]: When using deepspeed for multi-machine distributed training and setting reported_to = "wandb" in the trainer arguments, wandb will initialize multiple identical wandb runs. For example, four machines will have four identical wandb runs. How can I set it to create only one run? Should I add the wandb initialization code in the train code?

### ISSUE THREAD

**Issue by 1787648106** [wandb/wandb#8428]

**Comment by luisbergua** [comment]
Hi @1787648106, thanks for writing in! Would you mind sharing a minimal code example of your workflow so we can take a look and see what's possible? Thanks in advance!

**Comment by 1787648106** [comment]
> Hi @1787648106, thanks for writing in! Would you mind sharing a minimal code example of your workflow so we can take a look and see what's possible? Thanks in advance!

hello, the launch shell:
`deepspeed --hostfile /etc/mpi/hostfile --master_port=62234 train.py \
         --deepspeed deepspeed.json \
         ...
         --report_to wandb \
         --run_name xxxxxxxxx \
`
the train.py:
`
import wandb
os.environment["WANDB_DISABLED"] = "false"
os.environment["WANDB_API_KEY"] = "xxxxxxx"
os.environment["WANDB_PROJECT"] = "xxxx"
....
trainer = Seq2SeqTrainer(
    model=model,
    args=training_args,
    .....
)
`
The above is the part of my code about wandb, thank you for your reply.

**Comment by luisbergua** [comment]
Hi @1787648106, thanks for your patience and apologies for the delay! I have been exploring this, but it seems the integration is managed by Deepspeed. In any case, I would recommend setting the env variable `WANDB_RUN_GROUP` to group your runs (see some more details in [this](https://wandb.ai/wandb-japan/basic-project-for-report-creating/reports/How-to-use-wandb-for-pre-training-of-LLMs-for-partners--Vmlldzo3Njk2ODYx#log-multi-nodes-trainings-with-group-runs) report and [this](https://docs.wandb.ai/guides/runs/grouping) page from our docs). Please let me know if this is helpful!

**Comment by luisbergua** [comment]
Hi @1787648106 , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
