### ISSUE TITLE
[Bug]: wandb-core is not compiled for my system 

### ISSUE THREAD

**Issue by sukwonchung** [wandb/wandb#8437]
### Describe the bug

Hello, 
During model training, I kept getting an error like this. 
"WandbCoreNotAvailableError:Looks like wandb-core is not compiled for your system (Linux-5.19.0-0_fbk12_11583_g0bef9520ca2b-x86_64-with-glibc2.34): Please contact support at support@wandb.com to request `wandb-core` support for your system." 

Could you compile this?
Thank you in advance.

**Comment by kptkin** [comment]
@sukwonchung thanks for reporting. could you please share which version of `wandb` you are getting this issue?

**Comment by sukwonchung** [comment]
Hi @kptkin, 

using 

import wandb 
wandb.__version__

I got '0.17.8.dev1'. Any clue or suggestions? Thank you in advance!

**Comment by kptkin** [comment]
@sukwonchung this is interesting, these are development versions, how did you end up using this version? are you building our library from source?

**Comment by sukwonchung** [comment]
Interesting. What about this version? 

I was using a kernel that someone built, and I was searching the version information from the code. From the code, it specifies that the version is using the default setting, which is this.  

VERSION = {
    "default": "0.17.7._git_a52c693",
}

Somehow, when I try to import version like that, it showed that version. 

Btw, I was using an infrastructure from work. Not using the open source library. That could be why, but I am not expert here at all. 

Are there any version you recommend me to try? seems I can replace the version information and try to compile. so probably something that's compatible with (Linux-5.19.0-0_fbk12_11583_g0bef9520ca2b-x86_64-with-glibc2.34)?

**Comment by kptkin** [comment]
@sukwonchung thanks for the update... feel free to re-open the ticket again if you have further issues
