### ISSUE TITLE
[Q]: Multiple wandb logs on one Slurm node

### ISSUE THREAD

**Issue by writingindy** [wandb/wandb#8452]
### Ask your question

Hi, I'm trying to run torchtune for finetuning and I'm experimenting with wandb as a way to log my fine-tuning runs. I have access to a HPC cluster that has its resources managed by Slurm, when I try to run two jobs on the same node, I'm encountering a RunTimeError on the second job that runs:

```
RuntimeError: The server socket has failed to listen on any local network address. useIpv6: 0, code: -98, name: EADDRINUSE, message: address already in use
``` 

The first job runs fine and wandb logs it perfectly, but the second job to run on the same node fails with this error. Other (single) jobs on different nodes run fine as well.

My torchtune configuration is essentially the same as the recipes they have, since I'm just trying wandb out for now (just swapping out the logging for wandb suggested in the torchtune docs) https://pytorch.org/torchtune/stable/deep_dives/wandb_logging.html?highlight=wandb

**Comment by fmamberti-wandb** [comment]
Hi @writingindy, thank you for reaching out and sorry to hear you are experiencing this issue. Would you mind sharing some additional information to help us investigate this:

- The full stack error trace when a second job is started on the same node?
- Is the second job started while the first one is still running?
- would you be able to get from the node running the jobs the `debug.log` and `debug-internal.log` files from the `./wandb/run-<date_time>-<run_id>` folder for the failed ones?
- Can you share the command you are using to start the job and a snippet of the code showing how the wandb logger is setup?

**Comment by fmamberti-wandb** [comment]
Hi @writingindy , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
