### ISSUE TITLE
[Bug]: WandbCoreNotAvailableError: Looks like wandb-core is not compiled for your system (Darwin-23.5.0-x86_64-i386-64bit)

### ISSUE THREAD

**Issue by dmottice20** [wandb/wandb#8455]
### Describe the bug

Trying to connect to a Wandb project and store results from various hyperparameter configurations (_Note: first time user here so this is likely an issue on my end_). 

I am able to install `wandb` python package successfully and login via my terminal. I am able to connect successfully in a Google colab notebook and log experiemnts. When I try to do this in a notebook locally, I receive a `WandbCoreNotAvailable Error` error. I am using a virtualenv as well. Am I missing something or does Wandb not run in a virtualenv?

```
---------------------------------------------------------------------------
WandbCoreNotAvailableError                Traceback (most recent call last)
/var/folders/k3/8c3mqv1s6lx59_xfcsfxgwhw0000gn/T/ipykernel_84111/2812843664.py in <module>
     17 for i, (train, test) in enumerate(rolling_window):
     18     # Initialize the wandb run.
---> 19     wandb.init(project="principal-capstone-v0", config=config)
     20     # Add params to WANDB
     21     wandb.config.TRAIN_SIZE = TRAIN_SIZE

~/workspace/principalCapstone/principal-env/lib/python3.7/site-packages/wandb/sdk/wandb_init.py in init(job_type, dir, config, project, entity, reinit, tags, group, name, notes, magic, config_exclude_keys, config_include_keys, anonymous, mode, allow_val_change, resume, force, tensorboard, sync_tensorboard, monitor_gym, save_code, id, fork_from, resume_from, settings)
   1253         # Need to build delay into this sentry capture because our exit hooks
   1254         # mess with sentry's ability to send out errors before the program ends.
-> 1255         wandb._sentry.reraise(e)
   1256         raise AssertionError()  # unreachable

~/workspace/principalCapstone/principal-env/lib/python3.7/site-packages/wandb/analytics/sentry.py in reraise(self, exc)
    153         # this will messily add this "reraise" function to the stack trace,
    154         # but hopefully it's not too bad
--> 155         raise exc.with_traceback(sys.exc_info()[2])
    156 
    157     @_safe_noop

~/workspace/principalCapstone/principal-env/lib/python3.7/site-packages/wandb/sdk/wandb_init.py in init(job_type, dir, config, project, entity, reinit, tags, group, name, notes, magic, config_exclude_keys, config_include_keys, anonymous, mode, allow_val_change, resume, force, tensorboard, sync_tensorboard, monitor_gym, save_code, id, fork_from, resume_from, settings)
   1238     try:
   1239         wi = _WandbInit()
...
-> 1935             f"Looks like wandb-core is not compiled for your system ({platform.platform()}):"
   1936             " Please contact support at support@wandb.com to request `wandb-core`"
   1937             " support for your system."

WandbCoreNotAvailableError: Looks like wandb-core is not compiled for your system (Darwin-23.5.0-x86_64-i386-64bit): Please contact support at support@wandb.com to request `wandb-core` support for your system.
```

Here is some additional information:
- Python 3.11.4
- wandb v0.18.1
- OS: MacOS Sonoma v14.5
- Github repo: https://github.com/dmottice20/principalCapstone 
- Specific .ipynb: https://github.com/dmottice20/principalCapstone/blob/master/xgb.ipynb

**Comment by kptkin** [comment]
@dmottice20 thanks for reporting this issue, we are looking into it and it should be fixed for the next release 0.18.2

**Comment by dmitryduev** [comment]
hey @dmottice20, could you please provide some more info re your setup?
could you run:

```shell
python -c "import pathlib, wandb; print(pathlib.Path(wandb.__file__).parent / 'bin')"
# then ls -lhtr the contents of that folder
```

Also, would appreciate the output for this:
```shell
# want to see which wheel pip picks up:
pip uninstall wandb -y && pip install wandb --verbose
```

**Comment by dmitryduev** [comment]
Actually, @dmottice20, I think something got botched in your environment. In the example nb I see
```
~/workspace/principalCapstone/principal-env/lib/python3.7/site-packages/wandb
```
yet
```
# Check python version
!python --version
Python 3.11.4
```

could you please check you python environments?

**Comment by dmottice20** [comment]
@dmitryduev thanks for the catch! That was it! I had to dig into why the kernel as not matching the venv created and found the error. For future reference in case any one else has this issue, here were my steps to fix the issue:

1. Ensure needed packages are saved to `requirements.txt`
2. Delete the old venv - `rm -rf venv`
3. Rebuild the old venv - `pip install -r requirements.txt`
4. Good to go - after that, notebook ran smoothly.

Yes, I was able to pull a python interpreter and connect - tried it with Google colab and simply on my terminal. The issue was poor management of the environments on my end so I apologize for the thrash!

**Comment by chenwei-zhang** [comment]
I got the same issue. 
My wandb version is the latest one: v0.18.7.

Here's the error message:
wandb.errors.errors.WandbCoreNotAvailableError: File not found: /home/cwzhang/atomic/lib/python3.11/site-packages/wandb/bin/wandb-core.Please contact support at support@wandb.com.Your platform is: Linux-5.14.0-362.24.2.el9_3.x86_64-x86_64-Intel-R-_Xeon-R-_Silver_4216_CPU_@_2.10GHz-with-glibc2.37.
