### ISSUE TITLE
[Feature]: Report similar to W&B Sweeps when using Ray Callback

### ISSUE THREAD

**Issue by dennymarcels** [wandb/wandb#8479]
### Description

Hi y'all,
I depend on Ray for hyperparameter tuning. I've been using the W&B callback to report all metrics to W&B, which is quite helpful, but I would LOVE to get those beautiful sweep plots as well, which doesn't happen now.

### Suggested Solution

Use metrics reported by Ray to generate the same plots that are displayed when using W&B Sweeps.

**Comment by luisbergua** [comment]
Hi @dennymarcels, thanks for sharing this feedback! Just to make sure, you'd like to see those plots automatically? You can manually edit the workspace and add the ones that you want so just trying to make sure that I fully understand your feedback

**Comment by dennymarcels** [comment]
Hi @luisbergua, I was thinking about those automatic plots shown in the [Sweeps page](https://docs.wandb.ai/guides/sweeps/). The one on the bottom would be especially useful to me.

**Comment by luisbergua** [comment]
Thanks for sharing this @dennymarcels! That's the Parallel coordinates plot and can be added manually to the workspace and customized as needed. Would this work for you?
![image](https://github.com/user-attachments/assets/62566c94-33cc-4e68-9542-5fb0823b31ee)

**Comment by dennymarcels** [comment]
Hi @luisbergua, it did exactly what I wanted, many thanks!
The one issue though is that, if I group the logs, the chart is also grouped (and the hyperparameters are shown as averages of the groups, which doesn't even make sense). I tried turning off "Use grouping from the run tables in charts" to no effect.

**Comment by luisbergua** [comment]
Thanks for sharing this @dennymarcels! Could you please share a link to your project so I can take a look?

**Comment by luisbergua** [comment]
Hey @dennymarcels, would you have any problems with sharing a link to your project?

**Comment by dennymarcels** [comment]
@luisbergua I appreciate your concern, but our info is to be deemed confidential. I am exploring the dashboards to find a way to extract more information.
