### ISSUE TITLE
[Feature]: Is there any method to use `wandb.log()` in different step in the same project?

### ISSUE THREAD

**Issue by guanjinquan** [wandb/wandb#8486]
### Description

 Is there any method to use `wandb.log()` in different step in the same project? 

In my project, I want to draw two figure, the first one based on `x = epoch_id`, the second one based on `x = iteration_id`. 

I found it is impossible to use `wandb.log(step=epoch_id)` or `wandb.log(step=iteration_id)`. Which will cause an error: 

```
User provided step: 8 is less than current step: 513360. Dropping entry .....
```

That made me awkward. So is there any easy way to solve my problem? Please!

### Suggested Solution

If `wandb` can support  `wandb.log(step=epoch_id)` or `wandb.log(step=iteration_id)` to log different information, or there are solutions for my question, I will be very grateful!

**Comment by paulosabile-wb** [comment]
Hi @guanjinquan Good day and thank you for reaching out to us. IF you need to log data using an existing step on the same run, have you check our forking feature and see if this can help on your use-case? Please check this docs page for your reference. https://docs.wandb.ai/guides/runs/forking

**Comment by paulosabile-wb** [comment]
Hi @guanjinquan , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
