### ISSUE TITLE
[Bug]: Only the first step of some runs are being logged

### ISSUE THREAD

**Issue by keyonvafa** [wandb/wandb#8491]
### Describe the bug

I've been encountering a strange bug that only started today. Sometimes when I log code with wandb, it works as expected. Other times, the dashboard on the web only shows the first iteration, and although the run finishes as normal on my machine, the dashboard never updates. I've replicated this on two machines (a Linux machine and my Macbook). 

Here's a minimal code block that replicates the bug:

```{python}
import wandb
import random
import time

wandb.init(project="debug-example", name="minimal-run14")

for epoch in range(10):
    loss = random.random()
    accuracy = random.random()
    wandb.log({
        "epoch": epoch,
        "loss": loss,
        "accuracy": accuracy
    }, step=epoch)
    time.sleep(1)
wandb.finish()
```

Here's a screenshot of the runs. Note that runs 14 and 15 show but only the first step of 16.
![Screenshot 2024-09-25 at 4 01 06 PM](https://github.com/user-attachments/assets/2b4c4bd9-949d-4bbc-9fc4-dc0fbcfa5259)

WandB version: 0.18.1
Python version: 3.11.6
Operating system: MacOS Ventura 13.2.1 

Thank you

**Comment by petergchang** [comment]
I've been having a similar issue as well -

**Comment by keyonvafa** [comment]
What do you mean by random sampling?

**Comment by keyonvafa** [comment]
Fantastic, that fixes the issue for me. Thanks!
