### ISSUE TITLE
Broken link on the docs webpage

### ISSUE THREAD

**Issue by giusmatera** [wandb/wandb#8509]
Hi,

It seems like the link at the bottom of [this webpage](https://docs.wandb.ai/tutorials/huggingface) (pointing to https://docs.wandb.ai/huggingface) is broken. I tried searching for the documentation elsewhere, but couldn't find it.

Thanks for your help!

Best,
Giuseppe

**Comment by paulosabile-wb** [comment]
Hi @giusmatera Good day and thank you for reporting this issue. We've encountered some issues on the Docs page but this has been fixed and you should be able to search again. Please give it another try and let me know if you are still experiencing issues. Thank you!

**Comment by giusmatera** [comment]
Hi,

thanks for your reply! No, unfortunately, the problem is still there

**Comment by paulosabile-wb** [comment]
Hi @giusmatera I am sorry to hear that you are still experiencing issues when accessing our docs. Could you please clarify if you are referring to this link?

![image](https://github.com/user-attachments/assets/c0093f8c-fdbb-4106-87a6-bddbf40e892a)

**Comment by giusmatera** [comment]
Hi, here is what I see. 

<img width="934" alt="image" src="https://github.com/user-attachments/assets/c37da321-882d-4bb8-9f81-b0a23b44c3bf">

and then, clicking on that link,

<img width="860" alt="image" src="https://github.com/user-attachments/assets/1d822483-7404-4b31-b3cc-f9bb57b3f6bb">

**Comment by paulosabile-wb** [comment]
Thank you @giusmatera for flagging this. Our team has been notified about this and we are already working to fix this links on our docs page. The link should work once we deploy the fix. Again, thank you for reporting this to us! Should you have questions, please let us know!
