### ISSUE TITLE
[Q]: Unable to use WandbCallback() to log experiments

### ISSUE THREAD

**Issue by prakyaths** [wandb/wandb#8525]
### Ask your question

I encounter below error when I try to use WandbCallback()
![image](https://github.com/user-attachments/assets/f499fd5f-cc4a-4e30-92fb-e7dc3a50cde0)
Below are the version details
TensorFlow version: 2.17.0
tf.keras version: 3.4.1
wandb version: 0.18.2
I wanted to use WandbCallback() since it handles logging tasks automatically. Is it recommended to use WandbMetricsLogger() for keras version 3.x or later? Does it provide all the features of WandbCallback()?

**Comment by luisbergua** [comment]
Hi @prakyaths, thanks for writing in! The `WandbCallback()` is a legacy version (see [here](https://docs.wandb.ai/guides/integrations/keras#wandbcallback-legacy)), so indeed we recommend using `WandbMetricsLogger`, `WandbModelCheckpoint` and `WandbEvalCallback`. See our [docs](https://docs.wandb.ai/guides/integrations/keras) for details on how to use and integrate those. Please let me know if this helps!

**Comment by luisbergua** [comment]
Hi @prakyaths , I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by prakyaths** [comment]
Hello @luisbergua, Thanks for the clarification and the links to the documentation!!

**Comment by luisbergua** [comment]
No problem @prakyaths! Closing this for now, feel free to re-open if needed
