### ISSUE TITLE
[Bug]: `plot_table` missing from wandb typing stubs

### ISSUE THREAD

**Issue by lgeiger** [wandb/wandb#8547]
### Describe the bug

When linting the [custom charts example](https://docs.wandb.ai/guides/app/features/custom-charts/#custom-presets) fails since the `plot_table` function is missing in the [typing stubs file](https://github.com/wandb/wandb/blob/main/wandb/__init__.pyi).

Example code:
```python
import wandb

table = wandb.Table(data=[], columns=["step", "height"])
fields = {"x": "step", "value": "height"}

my_custom_chart = wandb.plot_table(
    vega_spec_name="carey/new_chart", data_table=table, fields=fields
)
```
mypy output:
```
test.py:6: error: Module has no attribute "plot_table"  [attr-defined]
```

- wandb version: 0.18.3
- mypy version: 1.11.2

**Comment by fmamberti-wandb** [comment]
Hi @lgeiger , thank you for raising this. Our engineering team is already working on this and we will let you know of any further updates.
