### ISSUE TITLE
[Q]: Find python command that started a run

### ISSUE THREAD

**Issue by phrasenmaeher** [wandb/wandb#8576]
### Ask your question

I am using a python script (attached below) to get the best runs for a couple of sweeps I am doing.
For each best run, I would like to get the command that started that run.
I can directly see it in the web interface (see attached screenshot), but would like to know if there's a programatic way via the API.

```
import wandb
project_name = "ABC"
entity_name = "NAME"
sweeps = wandb.Api().project(project_name).sweeps()
for sweep in sweeps:
    print(sweep)
    best_run = sweep.best_run()
    if best_run:
        summary = best_run.summary
        print(f"Best Run: {best_run.name}")
        print(f"Accuracy: {summary['metric_name']}")
        print(f"Sweep ID: {best_run.sweep.id}")
        print(f"Sweep name: {best_run.sweep.name}")
        print(f"Run URL: {best_run.url}")
```
![Image](https://github.com/user-attachments/assets/94bdf2a5-9db0-4f12-9a3e-993265fe427f)

**Comment by luisbergua** [comment]
Hey @phrasenmaeher! We store the command in a file named `wandb-metadata.json` under the key `program` (you can see it under the `Files` tab of the run) so you would need to download it and retrieve it like:
```
import wandb
import json

api = wandb.Api()
run_api = api.run(<run-path>)
meta = json.load(run_api.file("wandb-metadata.json").download())
meta["program"]
```
Please let me know if this is helpful!

**Comment by phrasenmaeher** [comment]
Hi @luisbergua , thanks for the reply. Your answer solved my question. For others, here's the code to get the run command:

```python
if best_run:
            summary = best_run.summary
            run_api = wandb.Api().run(f"{entity_name}/{project_name}/{best_run.id}")
            meta = json.load(run_api.file("wandb-metadata.json").download(replace=True))
            program = meta["program"]
            args = meta["args"]
            cmd_string = f"{program} "+" ".join(args)
```
