### ISSUE TITLE
[Bug]: wandb.watch causes AttributeError when WANDB_MODE=disabled

### ISSUE THREAD

**Issue by macio232** [wandb/wandb#8618]
### Describe the bug

As suggested in https://github.com/wandb/wandb/issues/8571#issuecomment-2412092073

mwe.py:
```python
import torch
import wandb

# Initialize a new W&B run
wandb.init(
    project="minimal-example",
)
wandb.watch(torch.nn.Module())

# Log a single value (e.g., accuracy)
wandb.log({"accuracy": 0.95})

# Finish the run
wandb.finish()
```
Result:
```bash
❯ WANDB_MODE=disabled python ./mwe.py
Traceback (most recent call last):
  File "[...]/./mwe.py", line 11, in <module>
    wandb.watch(torch.nn.Module())
  File "[...]/lib/python3.12/site-packages/wandb/sdk/wandb_watch.py", line 112, in watch
    wandb.run._torch.add_log_gradients_hook(
    ^^^^^^^^^^^^^^^^
  File "[...]/lib/python3.12/site-packages/wandb/sdk/wandb_run.py", line 931, in _torch
    if self._torch_history is None:
       ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Run' object has no attribute '_torch_history'
```

- The version of the wandb package you are using. -- 0.18.3 but the same behaviour with anything later than 0.16.6
- The version of Python you are using. -- 3.12.7
- The version of the operating system you are using. -- Linux 6.6.56-1-lts

**Comment by luisbergua** [comment]
Hey @macio232! Thanks for creating a separate thread and sharing these clear details, I could reproduce the issue, so will raise it with our engineers and let you know as soon as they provide any updates

**Comment by kptkin** [comment]
@macio232 thanks a lot for your reproduction. 
Few points:
1. A general suggestion for better practices, if you have access to the run object call the methods directly on it, so your script would look like this:
```
import torch
import wandb

# Initialize a new W&B run
run = wandb.init(
    project="minimal-example",
)
run.watch(torch.nn.Module())

# Log a single value (e.g., accuracy)
run.log({"accuracy": 0.95})

# Finish the run
run.finish()
```
In the above case disabled mode worked.
2. I will be fixing it for your example as it is indeed doesn't work.
