### ISSUE TITLE
[Q]: Error Failed in Two Process

### ISSUE THREAD

**Issue by jujimeizuo** [wandb/wandb#8619]
### Ask your question

- Linux 22.04
- python 3.10.15

----

- I have two process, `frontend_process` and `backend_process`
- then I init wandb by `run = wandb.init` in `frontend_process`, and transfer this `run` to `backend_process`, such as

  ```py
  backend_process = mp.Process(target=self.backend.run, args=(wandb_run,))
  ```

- then run the program (Both the front-end and the back-end will log)

  ```python
  backend_process.start()
  frontend.run()
  ```
  
- finally, I got below error:

  ```bash
  Traceback (most recent call last):
    File "/root/miniconda3/envs/tmp/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
      obj = _ForkingPickler.dumps(obj)
    File "/root/miniconda3/envs/tmp/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
      cls(buf, protocol).dump(obj)
    File "/root/miniconda3/envs/tmp/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 902, in __getstate__
      if not self._settings or self._settings._disable_service:
  AttributeError: 'Run' object has no attribute '_settings'. Did you mean: 'settings'?
  ```

- But when I did't run `frontend.run()`, it's ok!

  ```python
  backend_process.start()
  frontend.run()
  ```

I did't know this condition...

Have a good day!

**Comment by luisbergua** [comment]
Hey @jujimeizuo, thanks for contacting us! It seem you're trying to run `wandb.init` in both processes, which might be the source of the issue. As you can see [here](https://docs.wandb.ai/guides/track/tracking-faq/#how-can-i-use-wandb-with-multiprocessing-eg-distributed-training), we recommend to either only start the run in one process or use the `group` argument. Would you mind letting me know if any of those would work for you?

**Comment by kptkin** [comment]
@jujimeizuo which version of the wandb package are you using? could try updating to the latest version and see if the issue resolved

**Comment by jujimeizuo** [comment]
> [@jujimeizuo](https://github.com/jujimeizuo) which version of the wandb package are you using? could try updating to the latest version and see if the issue resolved

- wandb==0.18.3, it's latest

**Comment by kptkin** [comment]
> > [@jujimeizuo](https://github.com/jujimeizuo) which version of the wandb package are you using? could try updating to the latest version and see if the issue resolved
> 
> * wandb==0.18.3, it's latest

I see, could you please provide a small repro of how your script looks, i know you shared all the details in your first message, but a full code snippet, would make it easier for me to debug further. Thanks!

**Comment by jujimeizuo** [comment]
> Hey [@jujimeizuo](https://github.com/jujimeizuo), thanks for contacting us! It seem you're trying to run `wandb.init` in both processes, which might be the source of the issue. As you can see [here](https://docs.wandb.ai/guides/track/tracking-faq/#how-can-i-use-wandb-with-multiprocessing-eg-distributed-training), we recommend to either only start the run in one process or use the `group` argument. Would you mind letting me know if any of those would work for you?

Yeah, I only start the run in one process, but it's not work and share same wandb_run.(I don't know why) The way of using `group` I try, it's work for multiprocess.

Thanks for your reply!
