### ISSUE TITLE
[Bug]: expose `create_and_run_agent` as a public API

### ISSUE THREAD

**Issue by marijncv** [wandb/wandb#8620]
### Describe the bug

Currently the `create_and_run_agent` function can be imported from `wandb.sdk.launch._launch`. However, this makes it seem as if this is a private api and should therefore not be imported. To reduce this ambiguity, we should add the function to `__all__` in `wandb/sdk/launch/__init__.py`

**Comment by luisbergua** [comment]
Hey @marijncv, thanks for pointing this out! I'll ensure to raise your feedback with our Launch team, and we'll keep you posted with any relevant updates

**Comment by luisbergua** [comment]
Thanks for flagging this @marijncv, let me please check with our team!

**Comment by luisbergua** [comment]
Hey @marijncv, our eng team just reviewed and approved your [PR](https://github.com/wandb/wandb/pull/8621) so feel free to merge once all the tests have passed!
