### ISSUE TITLE
[Bug]: wandb fails to log power on MI300x GPUs

### ISSUE THREAD

**Issue by ntenenz** [wandb/wandb#8623]
### Describe the bug

When extracting power consumption from `rocm-smi -a --json`, wandb tries to match the field [`Average Graphics Package Power (W)`](https://github.com/wandb/wandb/blob/3f841abaa6d9f4ca814f61901b3f344938a59c3c/core/pkg/monitor/gpu_amd.go#L279).  However, some newer AMD GPUs (e.g, MI300x) instead report `Current Socket Graphics Package Power (W)`. This results in power being unreported for jobs on MI300x GPUs.

Ideally, wandb would parse both fields -- the current string for older GPUs and the newer one for MI300x (and onwards).

cc @charis-poag-amd who can provide more insight from the AMD side on current and future power reporting across AMD SKUs.

**Comment by luisbergua** [comment]
Thanks for flagging this @ntenenz! As you can see there's already a PR with a fix, so once this is merged the issue will be fixed in our next release

**Comment by ntenenz** [comment]
Thanks for the prompt fix @dmitryduev!

**Comment by dmitryduev** [comment]
The fix is in the latest release, please give it a try @ntenenz
