### ISSUE TITLE
[Q]: How do I deal with: "ValueError: Tensorboard already patched"

### ISSUE THREAD

**Issue by ashleys0** [wandb/wandb#8672]
### Ask your question

related previous issue: https://github.com/wandb/wandb/issues/463

In the previous issue linked above, a comment says ```... I just fixed this in master. You can install with pip install --upgrade git+git://github.com/wandb/client.git@master#egg=wandb We'll be pushing 0.8.8 today or tomorrow.```

they said this issue was fixed but seems like it hasn't been. Is the solution just to delete one of the lines?

```
val - test: 100%|█████████▉| 698/699 [05:42<00:00,  2.05it/s]
Eval - test: 100%|██████████| 699/699 [05:42<00:00,  2.15it/s]
Eval - test: 100%|██████████| 699/699 [05:42<00:00,  2.04it/s]

Traceback (most recent call last):
/miniconda3/envs/ml/lib/python3.12/site-packages/wandb/integration/tensorboard/monkeypatch.py", line 32, in patch
    raise ValueError(
ValueError: Tensorboard already patched, remove `sync_tensorboard=True` from `wandb.init` or only call `wandb.tensorboard.patch` once.
```

```
        tensorboard_log_dir = "~/path"

        wandb.init(
            project=self.config['proj_name'],  
            config=self.config, 
            name=self.name,
            settings=wandb.Settings(_disable_stats=True),  
            sync_tensorboard=True       #  <--------
        )


        self.trainer.fit(train_dataloader, val_dataloader)

...
        test_results = self.trainer.evaluate(test_dataloader)

        if self.accelerator.is_main_process:
            for key in test_results:
                self.accelerator.log({f'Test_Metric/{key}': test_results[key]})
        self.log(f'Test Results: {test_results}')

        # Specify the TensorBoard log directory
        wandb.tensorboard.patch(tensorboard_log_dir)      #  <--------

        # Sync existing TensorBoard logs
        os.system(f"tensorboard --logdir={tensorboard_log_dir} --bind_all")
        wandb.finish()

        self.trainer.end()
```

**Comment by fmamberti-wandb** [comment]
Hi @ashleys0 , thank you for reaching out. 

This is correct, the two shouldn't be used together. You can find more information on how to use each in [our docs](https://docs.wandb.ai/guides/integrations/tensorboard/#how-do-i-configure-tensorboard-when-im-using-it-with-wandb).

Please let us know if you have any further questions.

**Comment by fmamberti-wandb** [comment]
Hi @ashleys0 , I wanted to follow up on this request. Please let us know if we can be of further assistance

**Comment by fmamberti-wandb** [comment]
Hi @ashleys0 , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
