### ISSUE TITLE
[Bug-App]: Error while calling W&B API: joined SQL must have at least one part (<Response [500]>)

### ISSUE THREAD

**Issue by frederiknolte** [wandb/wandb#8714]
### Describe the bug

I created a sweep and started it via `wandb agent xxxxxxx/xxxxxxx/xxxxxxxx` but am getting the following error:

`wandb: ERROR Error while calling W&B API: joined SQL must have at least one part (<Response [500]>)`

Notably, I am running the sweep with multiple agents and while the first agent in the sweep runs without issue, any additional agent gives me this error.

**Comment by fmamberti-wandb** [comment]
Hi @frederiknolte, thank you for reaching out. This was a temporary issue which should have been solved soon after you raised it - could you please confirm if this is the case and if you can now start agents as expected?

**Comment by fmamberti-wandb** [comment]
Hi @frederiknolte , I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.
