### ISSUE TITLE
[Bug]: Resuming runs returns empty dict for wandb.config

### ISSUE THREAD

**Issue by dHonerkamp** [wandb/wandb#8771]
### Describe the bug

Hi, 
Updating to the newest version, 0.18.5 I'm getting an empty config back when trying to resume a run via
```
    common_args = dict(project=cli_args.wandb_project,
                       group=cli_args.wandb_group,
                       entity=cli_args.wandb_entity,
                       sync_tensorboard=True,
                       monitor_gym=False,
                       mode="online",)
    
      wandb.init(id=cli_args.resume_id,
                   resume="must",
                   **common_args)
print(wandb.config)
```
This just returns an empty dict. I've checked that the run exists, wandb.run.url returns the right id, and other information of the run object, such as wandb.run.step are correct. Online I can also see the config values. 

Digging a bit deeper, this seems to be happening from v18 onwards. It seems the backend delivers the data in a different format, such that the function `dict_no_value_from_proto_list` then does not convert the config values to a dict anymore. Frustratingly, this seems to also happen with new runs that I log with wandb==0.18.5. I correctly get the config if I resume the runs with version 0.17.9

Any help would be appreciated.

Using Python 3.10.14 and ubuntu20.04

**Comment by kptkin** [comment]
@dHonerkamp Thanks a lot for reporting this issue. It is indeed a bug in >=0.18 and it is indeed happens exactly due to the reason you identified.  It should be a relatively easy fix so we probably be able to get it in the next release.
