### ISSUE TITLE
[Bug]:  `wandb sync` Stuck in Infinite While Loop - Unable to Complete Synchronization

### ISSUE THREAD

**Issue by luo-li-ba-suo** [wandb/wandb#8780]
### Describe the bug

**Description:**
When attempting to synchronize logs using the `wandb sync` command, the process enters an infinite while loop and fails to exit normally. This issue appears to be related to the `self._robust_scan(ds)` method not returning `None` in the file "sync/sync.py" of the wandb package, preventing the loop from terminating.

**Expected Behavior:**
The `wandb sync` command should process all data and exit gracefully upon completion of the synchronization without getting stuck in an infinite loop.

**Actual Behavior:**
The `wandb sync` command gets stuck in a `while` loop during execution:
```
while True:
    data = self._robust_scan(ds)
    if data is None:
        break
    # Process data
```
The loop does not exit because `self._robust_scan(ds)` never returns `None`, leading to an infinite loop.

**Steps to Reproduce:**
1. Ensure you have the latest version of `wandb` installed.(Version: 0.17.5)
2. Attempt to synchronize a run using the `wandb sync <path_to_run_directory>` command.
3. Observe that the process enters an infinite loop and does not complete.

**Additional Information:**
1.Not all runs will encounter this matter. I didn't find the law of this bug.
2.The directory I want to sync with uses 14M storage that is not large
3.The training process producing the run is totally no problem
4.I click the link where the run is syncing to, I find there is part of log synced, but no training curves are synced

**Comment by luisbergua** [comment]
Hi @luo-li-ba-suo, thank you so much for flagging this and sharing these details! Would it be possible to share a code to reproduce the affected run? I tested on my end but was unable to reproduce

**Comment by luo-li-ba-suo** [comment]
I have an offline run directory that can reproduce this problem, but there are sth in this directory that are not for sharing due to the company rule. I will try again next time.

**Comment by luisbergua** [comment]
Hey @luo-li-ba-suo, thanks for sharing this! Sounds good, please feel free to share either the code or the folder if you face this again

**Comment by luo-li-ba-suo** [comment]
Hi @luisbergua , I guess I found the method to reproduce the problem, here is the step:

2. Change the permission of offline folder to be not allowed, and `wandb sync`, then you'll see:
`Find logs at: /tmp/debug-cli.mlp.log
wandb: WARNING Path /mnt/project/****/wandb/offline-run-20241108_031158-lucy70ll/wandb/ wasn't writable, using system temp directory.
wandb: WARNING Path /mnt/project/****/wandb/offline-run-20241108_031158-lucy70ll/wandb/ wasn't writable, using system temp directory
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/dist-packages/wandb/sync/sync.py", line 279, in run
    ds.open_for_scan(sync_item)
  File "/usr/local/lib/python3.10/dist-packages/wandb/sdk/internal/datastore.py", line 102, in open_for_scan
    self._fp = open(fname, "r+b")
PermissionError: [Errno 13] Permission denied: '/mnt/project/****/wandb/offline-run-20241108_031158-lucy70ll/run-lucy70ll.wandb'`

2.Fix the permission problem, and `wandb sync` again, you'll find the process is stuck

**Comment by luisbergua** [comment]
Hey @luo-li-ba-suo, thanks for sharing this! Mind letting me know how you're removing the permissions? I used a code like this:
```
import wandb
import os
import numpy as np


dir_name = "./new_logs"
if not os.path.exists(dir_name):
    os.makedirs(dir_name)

os.environ["WANDB_DIR"] = dir_name
os.environ["WANDB_CORE_DEBUG"] = "True"

run = wandb.init(project="test_log_images", mode="offline")
for i in range(10):
    run.log({"image": wandb.Image(np.random.rand(100, 100, 3))})
run.finish() 
```
Then removed the permissions:
```
chmod u-rwx new_logs/wandb/offline-run-20241113_133404-6x4eupx8
wandb sync new_logs/wandb/offline-run-20241113_133404-6x4eupx8
Usage: wandb sync [OPTIONS] [PATH]...
Try 'wandb sync --help' for help.

Error: Invalid value for '[PATH]...': Path 'new_logs/wandb/offline-run-20241113_133404-6x4eupx8' is not readable.
chmod u+rwx new_logs/wandb/offline-run-20241113_133404-6x4eupx8
wandb sync new_logs/wandb/offline-run-20241113_133404-6x4eupx8 
Find logs at: /var/folders/pm/2xvdwrw556g2y26njmzdpk4c0000gn/T/debug-cli.luisberguasanchez.log
Syncing: https://wandb.ai/luis_team_test/test_log_images/runs/6x4eupx8 ... done.
```
Buy as you can see, after giving the permissions back the run is synced without any issues, so maybe I'm doing something different?

**Comment by luisbergua** [comment]
Hey @luo-li-ba-suo, just wanted to check if you had the chance to take a look at my message above, and if you could share how you removed the permissions, since I couldn't reproduce this behavior? Thanks!

**Comment by luisbergua** [comment]
Hi @luo-li-ba-suo, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
