### ISSUE TITLE
[Feature]: Allow cache to be bypassed for artifact uploads

### ISSUE THREAD

**Issue by collinmccarthy** [wandb/wandb#8781]
### Description

Hi, I was recently guilty of filling up the disk space on our cluster because my wandb artifact cache had grown to 1.6TB over the last month alone while I was experimenting with my LLM training pipeline, which uploads checkpoints to wandb. 

I see a few other issues related to this:
- #1193
- #4099
- #4478

### Suggested Solution

This might be what #4478 was trying to do, but can we just add an optional boolean kwarg to `log_artifact` to allow calling it like `wandb.log_artifact(artifact, cache=False)`? 

I understand there's a desire to do something better with cache management here, but a lot of folks like me have no intention of re-using certain artifacts that are being uploaded (like checkpoints) because we're only uploading them for safe storage or to share with external collaborators. 

Thanks

**Comment by paulosabile-wb** [comment]
Hi @collinmccarthy Good day and thank you for reaching out to us! Happy to help you here. Let me reach out to the team if we have an available option to disabled caching when calling `log_artifact`. For the meantime, could you please take a look if [this method](https://docs.wandb.ai/ref/cli/wandb-artifact/wandb-artifact-cache/wandb-artifact-cache-cleanup/) can help you for now? Thanks!

**Comment by collinmccarthy** [comment]
Thanks, and yes I'm using that for now.

**Comment by luisbergua** [comment]
Hi @collinmccarthy, apologies for the delay here! Our recommendation would be to either use the command Paulo provided above `wandb cache cleanup`, or:
```
from wandb.sdk.artifacts.artifact_file_cache import get_artifact_file_cache

get_artifact_file_cache().cleanup(target_size=X, remove_temp=True) 
```
Or set the environment variable `WANDB_CACHE_DIR` to a different location. Please let us know if any of those would work for you!

**Comment by collinmccarthy** [comment]
Hi @luisbergua,

Thanks for the snippet. I think `wandb cache cleanup` would work when I don't have any runs going on a given node. 

I'm currently using this, I forget if this is from a previous discussion or just from the API. Does this do what I want it to do (effectively bypass the cache for this artifact), or no? This artifact is just meant to contain the checkpoint directory created by HuggingFace. 

```python
artifact = wandb.Artifact(name=artifact_name, type="model", metadata=metadata)
artifact.add_dir(ckpt_dir, name=ckpt_name, skip_cache=True)
```

**Comment by luisbergua** [comment]
Hi @collinmccarthy! Yes, `skip_cache` would also work for your purpose. Closing this for now, please feel free to re-open if needed!
