### ISSUE TITLE
[Bug-App]: Storage can't release

### ISSUE THREAD

**Issue by sanbuphy** [wandb/wandb#8782]
### Describe the bug

![Image](https://github.com/user-attachments/assets/b5642c96-e4da-42ce-a62a-14fe32cbd1b9)
![Image](https://github.com/user-attachments/assets/a68c9eeb-1910-41f8-aa41-d76ba1461da9)

I want to ask why these folders  are empty ( i delete it) , but I can still see the space occupation? How can I make wandb not automatically store weights? Thanks!

**Comment by paulosabile-wb** [comment]
Hi @sanbuphy Good day and thank you for reaching out to us! Happy to help you on this.

Sometimes, the system takes time to reflect the actual storage details in the UI. Could you please check again and see if it is now reflecting correctly?


Thanks,
Paulo

**Comment by paulosabile-wb** [comment]
Hi @sanbuphy , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
