### ISSUE TITLE
[Bug]: Cannot change the run name through UI

### ISSUE THREAD

**Issue by Boltzmachine** [wandb/wandb#8807]
### Describe the bug

I tried changing the name of my run through the UI. 

![Image](https://github.com/user-attachments/assets/00e8eb7e-2ea9-498d-b707-bb75effecfb5)

But the figure does not change accordingly, still showing the original name
![Image](https://github.com/user-attachments/assets/a4c17ed5-df16-4efd-b11f-6c64a8834766)

And the name on the left panel is back
![Image](https://github.com/user-attachments/assets/ecff8276-ef90-411b-9ec8-ee28fe8c0360)
 when I reload the webpage

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by Boltzmachine** [comment]
Hi Thanks for the timely follow-up. However, I cannot reproduce it the next day.

**Comment by ArtsiomWB** [comment]
Thank you for sending over the project. I am not seeing this behavior on my end either. Looks like it was a hiccup on our end.  

Since you are not seeing this behavior either, I will go ahead and close this thread out. Please let us know if you see this behavior again!
