### ISSUE TITLE
[Bug]: WandB Stuck When Fetching Artifacts

### ISSUE THREAD

**Issue by lumoe** [wandb/wandb#8930]
#### Description
The process becomes unresponsive while fetching artifacts using the WandB API. The issue occurs specifically during the `api.artifact` call. 

- Authentication has been successfully set up using the API token.
- No error messages or timeouts are encountered.
- The last observed output is:
  ```
  - Retrieving metadata for me/project/test-results:v{i}
  ```
  indicating that it gets stuck during the `api.artifact` function. I let it run for 30+ minutes without any progress and no indication that it is downloading big files. The expected artifact is ~0.5MB

#### Code to Reproduce

```python
from wandb import Api

api = Api()

for i in range(1, 5):
    print(f"- Retrieving metadata for me/project/test-results:v{i}")
    artifact = api.artifact(f'me/project/test-results:v{i}', type='test-results')
    print("- Metadata successfully retrieved")
    artifact_dir = artifact.download()
    print(f"- Artifact downloaded successfully to directory: {artifact_dir}")
```

#### Environment
- WandB SDK version: 0.18.7
- Python version: Python 3.8.20
- Operating system: MB Pro M3, 15.1.1 

#### Additional Notes
Any advice on what might be causing this issue or further debugging steps would be appreciated.

**Comment by ArtsiomWB** [comment]
Hi @lumoe! Thank you for writing in!

Could you please send me a link to an artifact you are currently trying to retrieve?

Are you able to call `use_artifact()` on that artifact, and try downloading it in the middle of the run instead of the API? (docs)

**Comment by ArtsiomWB** [comment]
Hi there, I wanted to follow up on this request. Please let us know if we can be of further assistance or if your issue has been resolved.

**Comment by ArtsiomWB** [comment]
Hi, since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
