### ISSUE TITLE
[Bug]: Files deleted through API are not really deleted

### ISSUE THREAD

**Issue by radekd91** [wandb/wandb#8944]
### Describe the bug

Recently there was a bug in the wandb API that was crashing `file.delete()` call (Issue #8753 ) in a simple deletion script such as:

```python
import wandb

entity = wandb.setup()._get_username()
api = wandb.Api()

project = ...  # some project name
run_id = ...  # some run ID
run = api.run(f"{entity}/{project}/{run_id}")
files = run.files()
files[0].delete()  # Runs fine now but the files don't seem to get deleted
```

The bug has been been seemingly fixed. It no longer crashes, however, I believe the files are either not getting deleted or at least the deletion is not registered on the wandb web interface. 

I have been running deletion scripts to selectively delete data that is no longer needed. However, nothing changed in the space reported on the web interface. I understand the interface might take a few hours to update. However, in my case it's several days now. 

I am overquota and basically blocked right now, with no good way to delete the files I no longer need.

**Comment by JoanaMarieL** [comment]
Hello @radekd91 , thank you for flagging this one. Our engineers were actively working on the storage issue and will keep you updated. For the meantime could you please share your WandB Account so we could check your actual storage on our end after you have deleted some data?

**Comment by radekd91** [comment]
Thanks for the quick response.

My wandb username is: `rdanecek`

**Comment by JulienGaubil** [comment]
I am facing the exact same issue as well

**Comment by Dibz15** [comment]
As of yesterday, I'm able to delete files using the API, and after a few hours the changes were visible to me in the web UI.

**Comment by JoanaMarieL** [comment]
Thank you for sharing @Dibz15 we appreciate it.

@radekd91 @JulienGaubil , you may also try again--our engineers were continuously fixing things for all the users gradually.

**Comment by JoanaMarieL** [comment]
Hello @radekd91 , @JulienGaubil , may we follow up on your case if it is all clear now? If the files you've deleted reflected already? Thanks!

**Comment by JoanaMarieL** [comment]
Hi @radekd91 , since we have not heard back from you we are going to close this request. If you would like to re-open the conversation, please let us know!
