### ISSUE TITLE
[Bug-App]: Failed to disconnect the slack integration through web app setting.

### ISSUE THREAD

**Issue by pipixiaqishi1** [wandb/wandb#8950]
### Describe the bug

Hi, I am using the web app for alerts to slack. I connected to the wrong channel when setting it up the first time. Then I want to disconnect it at the setting page of the web app. It fails and returns the following page.

![Image](https://github.com/user-attachments/assets/eb2e9507-48dd-405e-bfc8-7e4dbfdbb020)

![Image](https://github.com/user-attachments/assets/206b5351-ab3b-449b-8c2b-d1a4d85dce85)

**Comment by luisbergua** [comment]
Hey @pipixiaqishi1, thanks for flagging this! I just tested but couldn't reproduce this issue, so would it be possible to share the name of your entity to I can take a look?

**Comment by pipixiaqishi1** [comment]
Thanks for your reply. My username of wandb is jerrykzhang and my account is connected with my current GitHub account.

**Comment by luisbergua** [comment]
Thanks for sharing this @pipixiaqishi1! That seems to be your personal account, so may I please ask how you're trying to remove this? Just by going to the `/settings` page? I would recommend that you create a team and then set the integration there

**Comment by pipixiaqishi1** [comment]
Oh yes, I see, thanks for your assistance.
