### ISSUE TITLE
[Bug]: "wandb.Video requires moviepy when passing raw data" Error due to new moviepy version

### ISSUE THREAD

**Issue by raffiii** [wandb/wandb#8972]
### Describe the bug

The moviepy package was updated to 2.x and removed the `moviepy.editor` namespace (see [here](https://zulko.github.io/moviepy/getting_started/updating_to_v2.html)), breaking the `Video.encode` method. 
Fixing by either migrating to moviepy 2.x or pinning the earlier version.

Version info:
NixOS 24.05
Python 3.11.10
wandb 0.18.7
moviepy 2.1.1

**Comment by kptkin** [comment]
closing as it duplicates #8971
