### ISSUE TITLE
[Q]: How can I move a project between accounts?

### ISSUE THREAD

**Issue by rudolfwilliam** [wandb/wandb#8979]
### Ask your question

I accidentally created a project in a team account, where I do not want the project to be. I want that this project to be in my personal account. How can I move all runs (i.e., the entire project) to my personal account? Thanks for the support.

**Comment by JoanaMarieL** [comment]
Hi @rudolfwilliam , thank you for writing in and happy to help. Here's a guide on our [doc](https://docs.wandb.ai/guides/runs/manage-runs/#move-runs-to-a-team), please give it a try and let us know if you'll encounter any issues.

**Comment by rudolfwilliam** [comment]
Thanks. I did not find this explanation.

**Comment by JoanaMarieL** [comment]
Thank you for the update @rudolfwilliam , let us know if you have more question, for now will mark this as complete. Feel free to reopen if you need further assistance.
