### ISSUE TITLE
[Bug]: JSONDecodeError on syncing offline run

### ISSUE THREAD

**Issue by ju-kreber** [wandb/wandb#9047]
### Describe the bug

Hi, I've encountered a strange bug when syncing an offline run with `wandb sync ...`.
The environment is a miniforge environment with Python 3.12 and wandb 0.19.0 from pip.
Fresh `pip install -U --force-reinstall wandb` did not change the issue.
The `debug-cli` log was uninformative. Here's the error:

```
Syncing: https://wandb.ai/<masked> ... Exception in thread Thread-1:
Traceback (most recent call last):
  File "<masked>/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "<masked>/lib/python3.12/site-packages/wandb/sync/sync.py", line 296, in run
    sm.send(pb)
  File "<masked>/lib/python3.12/site-packages/wandb/sdk/internal/sender.py", line 391, in send
    send_handler(record)
  File "<masked>/lib/python3.12/site-packages/wandb/sdk/internal/sender.py", line 1205, in send_stats
    d[item.key] = json.loads(item.value_json)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<masked>/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<masked>/lib/python3.12/json/decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<masked>/lib/python3.12/json/decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
I did a bit of debugging and found that in `wandb/sdk/internal/sender.py:1205`, the GPU name "NVIDIA A100 80GB PCIe" is passed to `json.loads()` as a string without quotation marks, resulting in the described error.
I worked around it with the dirty hack of changing 1205 to
```python
try:
    d[item.key] = json.loads(item.value_json)
except json.JSONDecodeError:
    d[item.key] = json.loads('"' + item.value_json + '"')
```
which seems to sync without issues for me.

I synced offline runs before without issues, including GPU names, so I am not sure what brought up this issue.
I will provide further information to debug this on request.

Best regards,
Jens

**Comment by kimmchii** [comment]
I got the same issue when trying to sync an offline run. 
I fixed it by downgrading the wandb version from `0.19.0` to `0.18.0`.

```python
pip install wandb==0.18.0
```

**Comment by ju-kreber** [comment]
> I got the same issue when trying to sync an offline run. I fixed it by downgrading the wandb version from `0.19.0` to `0.18.0`.

That's good to know! Also given that 0.19.0 came out quite recently (Dec 5), this matches the fact that it still worked recently for me on slightly older environments.

I also tried using the conda-forge version instead of the pip version, but same result. So it looks very much like a regression in 0.19.0.

**Comment by kptkin** [comment]
@ju-kreber yes, the issue was introduced in whatever version you used to generate the wandb file, it seems that the GPU name wasn't properly serialized to a json string and hence is not correctly deserialized. Could you please share which version of the sdk you used when you generate the offline run, that would help understand if the issue is still present or have been resolved.

Thanks a lot for your help! And sorry for the issue

**Comment by kptkin** [comment]
@ju-kreber thanks a lot for all the information it is very helpful, we are going to take a look and get back to you as soon as we figure out what went wrong.

**Comment by ZeguanXiao** [comment]
Can these broken offline runs be uploaded once the new version fixes them?

**Comment by dmitryduev** [comment]
@ZeguanXiao yes! We'll do a release today or tomorrow, but for now you can use the rc release we shipped yesterday: https://pypi.org/project/wandb/0.19.1rc1/
