### ISSUE TITLE
Status of W&B tracing integration in langchain?

### ISSUE THREAD

**Issue by eyurtsev** [wandb/wandb#9085]
Unclear what the status of wandb tracing in langchain is. I know that @parambharat was working on a w&b tracer. Should the ones in langchain be marked as deprecated?

https://github.com/langchain-ai/langchain/pull/28059

**Comment by scottire** [comment]
hi @eyurtsev, thanks for the nudge and for consolidating our docs on that integrations page. Weave is the more complete of the two options, so we can push users to that instead of the `wandb_tracing_enabled` option. We can follow up with a new PR but the change made works for now. Thanks a lot
