### ISSUE TITLE
[Bug]: wandb.init crashes when using reinit=True

### ISSUE THREAD

**Issue by MathisTLD** [wandb/wandb#9120]
### Describe the bug

Below code doesn't work as expected (run1 should be finished automatically but instead the whole app crashes)

```python
run1 = wandb.init(
                    id="id1"
                    name="name1",
                    reinit=True,
)
# log stuff ...
# next call to wandb.init will crash because logging message at
# https://github.com/wandb/wandb/blob/e4b76e8c2126e1847d2049d3bff4553b271d98ad/wandb/sdk/wandb_init.py#L669
run2 = wandb.init(
                    id="id2"
                    name="name2",
                    reinit=True,
)
```

A workaround would be to manually finish my previous run but this would make my code way mode complex. That's why I prefer relying on the `reinit` flag that is not working as expected.
I already patched this in [this commit](https://github.com/MathisTLD/wandb/commit/243db8a2c2a71855bf061fa9e6c02b8f736a4d76#diff-63f38ce7b0a29a84c0252e3ff04f02b546e4f199c0006956408db2c1fc567085L669), pull request incoming

**Comment by ArtsiomWB** [comment]
Hi @MathisTLD! 

Thank you for writing in! I see our engineering team has responded to your pr. Tracking this thread from the support's side as well.
