### ISSUE TITLE
[Enhancement] CatBoost support in W&B

### ISSUE THREAD

**Issue by neomatrix369** [wandb/wandb#965]
`wandb --version && python --version && uname`

* Weights and Biases version: wandb, version 0.8.31
* Python version: Python 3.7.2
* Operating System: MacOS Sierra

### Description

I have successfully implemented W&B to capture parameters and save and upload my models to the cloud.

Although there is no callbacks support (via a named param) in [Catboost](https://catboost.ai/docs/).

If it's trivial i'm happy to implement it for you if you can show me an example or point me to how you would this when no callbacks support is available. 

Is there a custom `WandBCallback` implementation that can be adapted to work with Catboost?

### What I Did

I looked on their GitHub repo and found this [one conversation](https://github.com/catboost/catboost/issues/147). And other [such conversations](https://github.com/catboost/catboost/issues?q=is%3Aissue+callback+is%3Aclosed) as well. They talk about reading their debug logs or other log files written out during the training process.

**Comment by neomatrix369** [comment]
Actually looking closer into the code it seems there is `callback` support, see https://github.com/catboost/catboost/search?q=fit+callback&unscoped_q=fit+callback, although their docs don't mention it at all.

**Comment by neomatrix369** [comment]
PS: apart from this I'm really really enjoying the current GUI on my dashboard, of course there are many more goodies to play with and would love to know how to enable them. (Working my way thru the docs).

**Comment by neomatrix369** [comment]
While I was at it, I wrote a small snippet of code to read the _CatBoost_ logs and send the relevant metrics to W&B and got these:
![Screen Shot 2020-04-15 at 19 01 04](https://user-images.githubusercontent.com/1570917/79371007-8e9ab600-7f4b-11ea-91fd-b8e8e0e68a6d.png)
![Screen Shot 2020-04-15 at 19 01 14](https://user-images.githubusercontent.com/1570917/79371011-8fcbe300-7f4b-11ea-910c-cf5a1f25ce6e.png)

The `catboost_info` folder looks like this: 
```
catboost_info
├── catboost_training.json
├── learn
│   └── events.out.tfevents
├── learn_error.tsv
├── test
│   └── events.out.tfevents
├── test_error.tsv
└── time_left.tsv
```
I only enabled one flag (`allow_writing_files=True`) to record training logs, other metrics generation options open to be explored.

My code snippet looks like the below, which may not be W&B `callbacks` idiomatic but it does the job in a native fashion - if you have suggestions on top of this please let me know:

```python
def log_catboost_metrics(self):
    if 'allow_writing_files' in self.param_dict.keys():
        if self.param_dict['allow_writing_files']:
            with open('catboost_info/catboost_training.json', 'r') as json_file:
                catboost_training_json = json.load(json_file)
            iterations = catboost_training_json['iterations']
            [
                self.log_metrics({'train_rmse': each_iteration['learn'][0],
                                  'test_rmse': each_iteration['test'][0]})
                for each_iteration in iterations
            ]
```

**Comment by neomatrix369** [comment]
The `catboost_info` folder looks like this: 
```
catboost_info
├── catboost_training.json
├── learn
│   └── events.out.tfevents
├── learn_error.tsv
├── test
│   └── events.out.tfevents
├── test_error.tsv
└── time_left.tsv
```
I only enabled one flag (`allow_writing_files=True`) to record training logs, other metrics generation options open to be explored.

My code snippet looks like the below, which may not be W&B `callbacks` idiomatic but it does the job in a native fashion - if you have suggestions on top of this please let me know:

```python
def log_catboost_metrics(self):
    if 'allow_writing_files' in self.param_dict.keys():
        if self.param_dict['allow_writing_files']:
            with open('catboost_info/catboost_training.json', 'r') as json_file:
                catboost_training_json = json.load(json_file)
            iterations = catboost_training_json['iterations']
            [
                self.log_metrics({'train_rmse': each_iteration['learn'][0],
                                  'test_rmse': each_iteration['test'][0]})
                for each_iteration in iterations
            ]
```
The file with all metrics the details is `catboost_training.json` and looks like this:
```
{
"meta":{"test_sets":["test"],"test_metrics":[{"best_value":"Min","name":"RMSE"}],"learn_metrics":[{"best_value":"Min","name":"RMSE"}],"launch_mode":"Train","parameters":"","iteration_count":1000,"learn_sets":["learn"],"name":"experiment"},
"iterations":[
{"learn":[2.196726314],"iteration":0,"passed_time":0.1498032305,"remaining_time":149.6534272,"test":[3.899913204]},
{"learn":[2.044413975],"iteration":1,"passed_time":0.289971577,"remaining_time":144.6958169,"test":[3.879890591]},
{"learn":[1.903037375],"iteration":2,"passed_time":0.4285649268,"remaining_time":142.4264107,"test":[3.864610588]},
{"learn":[1.771561035],"iteration":3,"passed_time":0.5685178003,"remaining_time":141.5609323,"test":[3.847450844]},
{"learn":[1.6492136],"iteration":4,"passed_time":0.7080523576,"remaining_time":140.9024192,"test":[3.828261616]},
....
```

The maintainers encourage everyone to read the training logs to gather metrics.

Any thoughts?

**Comment by cvphelps** [comment]
Hi @neomatrix369, this is awesome! Thanks for taking a look at how to integrate W&B with Catboost. @borisdayma could you chat with Mani about this?

**Comment by borisdayma** [comment]
I see there are tfevents files. If they sync metrics through Tensorboard you can easily log everything by using `wandb.init(sync_tensorboard=True)`.
Let me know if that works!

**Comment by neomatrix369** [comment]
> Hi @neomatrix369, this is awesome! Thanks for taking a look at how to integrate W&B with Catboost. @borisdayma could you chat with Mani about this?

It's a pleasure, I'll give @borisdayma's suggestion a try and loop back.

**Comment by neomatrix369** [comment]
> I see there are tfevents files. If they sync metrics through Tensorboard you can easily log everything by using `wandb.init(sync_tensorboard=True)`.
> Let me know if that works!

Would `wandb` to look into the `catboost_info` folder or will it trap the `tf events` as they occur via the TensorFlow (while experiments are in play)?

**Comment by neomatrix369** [comment]
> I see there are tfevents files. If they sync metrics through Tensorboard you can easily log everything by using `wandb.init(sync_tensorboard=True)`.
> Let me know if that works!

Just tried this and didn't see anything appear in the W&B Dashboard, hence my previous question.

**Comment by neomatrix369** [comment]
@borisdayma any feedback for me from the above, I didn't get any progress trying out the above you suggested.

**Comment by borisdayma** [comment]
@cvphelps How does wandb find tensorboard checkpoints when we use `sync_tensorboard`?
I'm thinking that they may not be found as they are in a different folder.

**Comment by sekeratib** [comment]
Hi, is there any activity on this issue?

It would be great indeed, to have something like this working!

`from wandb.catbooost import WandbCallback`

**Comment by thunderock** [comment]
I use both Catboost and wandb pretty heavilly in my daily life, would've liked to have wandb support this !

**Comment by vanpelt** [comment]
@thunderock we used to have this in the mainline, but it got dropped as we were upgrading the library.  We'll try to get it back in, but you take the old code and add it to your own library until it makes it back in:

https://github.com/wandb/client/blob/v0.9.5/wandb/catboost

**Comment by thunderock** [comment]
@vanpelt  sure makes sense :+1:   Do let me know in case you want me to ramp up and pick this up.

**Comment by sekeratib** [comment]
@Neronjust2017 this solves my problem, thanks!

**Comment by dmitryduev** [comment]
We added a simple `WandbCallback` for [CatBoost](https://catboost.ai/) in #2975 back in `wandb==0.12.11`.

**Comment by chanansh** [comment]
how to use? @dmitryduev
